// topics/trastornos-del-movimiento/study.js: Autoevaluación de Trastornos del Movimiento.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Nota de método (ver memoria del proyecto): todas las preguntas se escribieron primero con la
// respuesta correcta en options[0]/correct:0 (trivialmente verificable), y luego se redistribuyó
// la posición de `correct` mecánicamente con un script, sin volver a adivinar cuál texto es el
// correcto. Cada pregunta se releyó completa (options+correct+explanation) tras la
// redistribución para confirmar que options[correct] es realmente la respuesta correcta.

export const quiz = [
  { q: '¿Cómo se clasifican los trastornos del movimiento según el circuito de los ganglios basales?', options: ['Hipocinéticos (menos movimiento del esperado) e hipercinéticos (movimiento involuntario excesivo)', 'Exclusivamente por la edad de inicio de los síntomas', 'Exclusivamente por el sexo del paciente afectado', 'No existe ninguna clasificación fisiopatológica reconocida para estos trastornos'], correct: 0, explanation: 'Los trastornos del movimiento se clasifican en hipocinéticos (dominados por la enfermedad de Parkinson) e hipercinéticos (temblor esencial, distonía, corea).', dificultad: 'facil' },
  { q: '¿Qué efecto tiene la dopamina sobre la vía directa e indirecta de los ganglios basales?', options: ['Inhibe ambas vías por igual sin ninguna diferencia', 'Facilita la vía directa (facilita el movimiento) e inhibe la vía indirecta (que frena el movimiento)', 'Facilita ambas vías por igual sin ninguna diferencia', 'No tiene ningún efecto sobre ninguna de las 2 vías'], correct: 1, explanation: 'La dopamina facilita la vía directa (que facilita el movimiento) e inhibe la vía indirecta (que lo frena), explicando el equilibrio entre hipocinesia e hipercinesia.', dificultad: 'intermedio' },
  { q: '¿Por qué la pérdida dopaminérgica en la enfermedad de Parkinson produce hipocinesia?', options: ['Aumenta la actividad de la vía directa de forma desproporcionada', 'No tiene ninguna relación con el equilibrio entre las 2 vías de los ganglios basales', 'Desplaza el equilibrio hacia una inhibición neta del movimiento por predominio de la vía indirecta sin freno dopaminérgico', 'Produce exclusivamente síntomas sensitivos, nunca motores'], correct: 2, explanation: 'La pérdida dopaminérgica desplaza el equilibrio hacia la vía indirecta (que frena el movimiento), produciendo hipocinesia neta.', dificultad: 'dificil' },
  { q: '¿Cuál es el criterio motor cardinal, obligatorio, para el diagnóstico clínico de enfermedad de Parkinson según los criterios MDS?', options: ['Temblor de reposo exclusivamente, sin ningún otro criterio', 'Inestabilidad postural exclusivamente', 'Rigidez exclusivamente, sin bradicinesia', 'Bradicinesia'], correct: 3, explanation: 'La bradicinesia es el criterio motor cardinal y obligatorio para el diagnóstico clínico de enfermedad de Parkinson según los criterios MDS, más al menos rigidez o temblor de reposo.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo apoya retrospectivamente el diagnóstico de enfermedad de Parkinson idiopática frente a un parkinsonismo atípico?', options: ['La ausencia completa de cualquier respuesta a levodopa', 'Una respuesta clara y sostenida a levodopa', 'La progresión extremadamente rápida en semanas', 'La presencia de signos cerebelosos prominentes desde el inicio'], correct: 1, explanation: 'Una respuesta clara y sostenida a levodopa apoya fuertemente el diagnóstico de enfermedad de Parkinson idiopática; los parkinsonismos atípicos responden poco o transitoriamente.', dificultad: 'intermedio' },
  { q: '¿Cuál es el hallazgo patológico característico de la enfermedad de Parkinson?', options: ['Cuerpos de Lewy (agregados de alfa-sinucleína mal plegada)', 'Placas de amiloide beta exclusivamente', 'Ovillos neurofibrilares de proteína tau exclusivamente', 'Desmielinización difusa de la sustancia blanca'], correct: 0, explanation: 'Los cuerpos de Lewy, agregados de alfa-sinucleína mal plegada, son el sustrato patológico característico de la enfermedad de Parkinson.', dificultad: 'intermedio' },
  { q: '¿Cuál es el trastorno de temblor más frecuente en la población general?', options: ['Temblor de reposo de la enfermedad de Parkinson', 'Temblor intencional cerebeloso', 'Temblor psicógeno funcional', 'Temblor esencial'], correct: 3, explanation: 'El temblor esencial es el trastorno de temblor más frecuente en la población general, más frecuente que el temblor de la enfermedad de Parkinson.', dificultad: 'facil' },
  { q: '¿Cómo se distingue el temblor esencial del temblor de reposo de la enfermedad de Parkinson?', options: ['Ambos tipos de temblor son clínicamente indistinguibles en cualquier circunstancia', 'El temblor esencial siempre es unilateral, nunca bilateral', 'El temblor esencial es postural/de acción; el de Parkinson es de reposo y mejora con el movimiento voluntario', 'El temblor de Parkinson siempre mejora con el alcohol, el esencial nunca'], correct: 2, explanation: 'El temblor esencial es postural/de acción (aparece al mantener una postura), mientras que el de Parkinson es de reposo y mejora con el movimiento voluntario.', dificultad: 'intermedio' },
  { q: '¿Cuál es el tratamiento farmacológico de primera línea para el temblor esencial sintomático?', options: ['Propranolol o primidona', 'Levodopa/carbidopa', 'Toxina botulínica sistémica', 'Tetrabenazina'], correct: 0, explanation: 'Propranolol o primidona son el tratamiento de primera línea para el temblor esencial sintomático, con eficacia comparable.', dificultad: 'facil' },
  { q: '¿Qué mecanismo fisiopatológico produce la co-contracción muscular característica de la distonía?', options: ['Destrucción completa de la unión neuromuscular', 'Un mecanismo idéntico al de la miastenia gravis', 'Alteración de la inhibición recíproca normal entre músculos agonistas y antagonistas', 'Ausencia total de cualquier señal nerviosa hacia el músculo afectado'], correct: 2, explanation: 'La distonía refleja una alteración de la inhibición recíproca normal entre músculos agonistas y antagonistas, produciendo co-contracción simultánea.', dificultad: 'dificil' },
  { q: '¿Cuál es el tratamiento de primera línea para la distonía focal (cervical, blefaroespasmo, calambre del escritor)?', options: ['Levodopa/carbidopa', 'Cirugía de resección muscular', 'Anticoagulación terapéutica', 'Toxina botulínica intramuscular'], correct: 3, explanation: 'La toxina botulínica intramuscular es el tratamiento de primera línea para la distonía focal, inyectada en los músculos hiperactivos.', dificultad: 'facil' },
  { q: '¿Qué gen se asocia clásicamente con formas generalizadas de distonía de inicio temprano?', options: ['El gen HTT (huntingtina)', 'DYT1/TOR1A', 'El gen LRRK2', 'El gen APOE'], correct: 1, explanation: 'El gen DYT1/TOR1A se asocia clásicamente con formas generalizadas de distonía de inicio temprano.', dificultad: 'dificil' },
  { q: '¿Qué mutación genética produce la enfermedad de Huntington?', options: ['Deleción completa del cromosoma 21', 'Mutación puntual en el gen APOE', 'Translocación entre los cromosomas 9 y 22', 'Expansión de repeticiones CAG en el gen HTT'], correct: 3, explanation: 'La enfermedad de Huntington es producida por una expansión de repeticiones CAG en el gen HTT, que codifica la huntingtina.', dificultad: 'facil' },
  { q: '¿Cuál es la tríada clásica de la enfermedad de Huntington?', options: ['Bradicinesia, rigidez, y temblor de reposo', 'Ataxia, disartria, y nistagmo', 'Corea progresiva, deterioro cognitivo, y síntomas psiquiátricos', 'Debilidad, arreflexia, y fasciculaciones'], correct: 2, explanation: 'La tríada clásica de la enfermedad de Huntington es corea progresiva, deterioro cognitivo, y síntomas psiquiátricos.', dificultad: 'facil' },
  { q: '¿Cuál es el tratamiento farmacológico específico de la corea en la enfermedad de Huntington?', options: ['Levodopa/carbidopa', 'Tetrabenazina o deutetrabenazina', 'Toxina botulínica sistémica', 'Propranolol'], correct: 1, explanation: 'Tetrabenazina o deutetrabenazina, inhibidores del transportador vesicular de monoaminas tipo 2, son el tratamiento específico de la corea en Huntington.', dificultad: 'intermedio' },
  { q: '¿Qué fenómeno genético explica el inicio más temprano y mayor gravedad en generaciones sucesivas de la enfermedad de Huntington?', options: ['Anticipación genética (mayor número de repeticiones CAG), particularmente por transmisión paterna', 'Un mecanismo de herencia recesiva ligada al X', 'La enfermedad nunca se transmite de una generación a la siguiente', 'Un fenómeno idéntico al de la impronta genómica materna exclusiva'], correct: 0, explanation: 'La anticipación genética (mayor número de repeticiones CAG e inicio más temprano en generaciones sucesivas, particularmente por transmisión paterna) es característica de la enfermedad de Huntington.', dificultad: 'dificil' },
  { q: '¿Qué es el fenómeno de "wearing-off" en el tratamiento con levodopa?', options: ['Un movimiento coreiforme que ocurre en el pico de concentración plasmática', 'Reaparición predecible de los síntomas parkinsonianos antes de la siguiente dosis programada', 'Una mejoría sostenida indefinida sin ninguna fluctuación', 'Una reacción alérgica aguda a la primera dosis de levodopa'], correct: 1, explanation: 'El wearing-off es la reaparición predecible de los síntomas parkinsonianos antes de la siguiente dosis programada de levodopa.', dificultad: 'intermedio' },
  { q: '¿Cuándo ocurre característicamente la discinesia "peak-dose"?', options: ['Coincide con el pico de concentración plasmática del fármaco, 30-90 minutos después de la toma', 'Exclusivamente varias horas después de suspender por completo el tratamiento', 'Exclusivamente durante el sueño nocturno, nunca durante el día', 'De forma aleatoria sin ninguna relación con el horario de dosificación'], correct: 0, explanation: 'La discinesia peak-dose coincide con el pico de concentración plasmática del fármaco, típicamente 30-90 minutos después de la toma.', dificultad: 'intermedio' },
  { q: '¿Qué fármaco se agrega específicamente para reducir las discinesias peak-dose?', options: ['Levodopa en dosis más altas', 'Toxina botulínica sistémica', 'Amantadina', 'Prednisona'], correct: 2, explanation: 'La amantadina tiene evidencia específica para reducir las discinesias peak-dose en la enfermedad de Parkinson.', dificultad: 'intermedio' },
  { q: '¿Qué se debe hacer con la levodopa durante la hospitalización de un paciente con enfermedad de Parkinson?', options: ['Suspenderla inmediatamente al ingreso hospitalario en todos los casos', 'Duplicar la dosis habitual sin ninguna justificación clínica', 'Reemplazarla sistemáticamente por un antipsicótico típico', 'Mantener estrictamente el horario habitual de dosificación, nunca suspenderla abruptamente'], correct: 3, explanation: 'Nunca se debe suspender abruptamente la levodopa durante una hospitalización, dado el riesgo de un síndrome neuroléptico maligno-símil; debe mantenerse el horario habitual.', dificultad: 'facil' },
  { q: '¿Qué es la "regla del año" para distinguir demencia asociada a Parkinson de demencia por cuerpos de Lewy?', options: ['El deterioro cognitivo que aparece más de 1 año después del inicio motor se clasifica como demencia asociada a Parkinson', 'Ambas entidades son exactamente lo mismo sin ninguna distinción posible', 'Solo se puede diagnosticar mediante biopsia cerebral en cualquier caso', 'La regla del año no tiene ninguna aplicación clínica real'], correct: 0, explanation: 'Según la regla del año, el deterioro cognitivo que aparece más de 1 año después del inicio motor se clasifica como demencia asociada a Parkinson; si aparece antes o simultáneamente, es demencia por cuerpos de Lewy.', dificultad: 'dificil' },
  { q: '¿Cuál es el inhibidor de colinesterasa con mejor evidencia específica en la demencia asociada a Parkinson?', options: ['Donepezilo exclusivamente, sin ninguna evidencia para otros agentes', 'Rivastigmina', 'Memantina exclusivamente', 'Ningún inhibidor de colinesterasa tiene evidencia en este contexto'], correct: 1, explanation: 'La rivastigmina tiene la evidencia más sólida específicamente en la demencia asociada a Parkinson.', dificultad: 'intermedio' },
  { q: '¿Por qué se deben evitar los fármacos anticolinérgicos en el paciente con Parkinson y deterioro cognitivo?', options: ['Siempre mejoran la función cognitiva en este contexto', 'No tienen ningún efecto sobre el sistema nervioso central', 'Pueden empeorar significativamente la cognición', 'Son el tratamiento de elección específico para la demencia asociada a Parkinson'], correct: 2, explanation: 'Los anticolinérgicos pueden empeorar significativamente la cognición, por lo que se evitan activamente en el paciente con deterioro cognitivo concomitante.', dificultad: 'intermedio' },
  { q: '¿Cómo se documenta la hipotensión ortostática en el paciente con enfermedad de Parkinson?', options: ['Exclusivamente mediante electrocardiograma en reposo', 'Exclusivamente mediante resonancia magnética cerebral', 'No es posible documentar objetivamente este hallazgo', 'Midiendo la presión arterial en decúbito y de pie (a 1 y 3 minutos), buscando una caída ≥20 mmHg sistólica o ≥10 mmHg diastólica'], correct: 3, explanation: 'La hipotensión ortostática se documenta midiendo la presión arterial en decúbito y de pie, buscando una caída ≥20 mmHg sistólica o ≥10 mmHg diastólica.', dificultad: 'intermedio' },
  { q: '¿Qué síntoma autonómico puede preceder el diagnóstico motor de Parkinson por años, siendo un posible marcador prodrómico?', options: ['Estreñimiento', 'Hipertensión arterial de nueva aparición', 'Poliuria marcada', 'Hipertermia sostenida'], correct: 0, explanation: 'El estreñimiento, por afectación temprana del plexo mientérico, puede preceder el diagnóstico motor de Parkinson por años, siendo reconocido como posible marcador prodrómico.', dificultad: 'intermedio' },
  { q: '¿Qué antipsicótico se prefiere para la psicosis inducida por fármacos dopaminérgicos en Parkinson, dado que no empeora el parkinsonismo motor?', options: ['Haloperidol', 'Risperidona en dosis altas', 'Pimavanserina', 'Olanzapina en dosis altas'], correct: 2, explanation: 'La pimavanserina, sin actividad antagonista dopaminérgica significativa, se prefiere porque no empeora el parkinsonismo motor.', dificultad: 'intermedio' },
  { q: '¿Por qué se deben evitar los antipsicóticos típicos y los atípicos de alta potencia dopaminérgica en el paciente con Parkinson?', options: ['No tienen ningún efecto sobre el sistema motor en ningún paciente', 'Son el tratamiento de elección específico para la psicosis en este contexto', 'Mejoran simultáneamente tanto la psicosis como el control motor', 'Empeoran marcadamente el parkinsonismo motor por su acción antagonista dopaminérgica'], correct: 3, explanation: 'Los antipsicóticos típicos y los atípicos de alta potencia dopaminérgica empeoran marcadamente el parkinsonismo motor por su acción antagonista dopaminérgica.', dificultad: 'intermedio' },
  { q: '¿Cuál es el orden recomendado para simplificar el esquema dopaminérgico ante psicosis, antes de recurrir a un antipsicótico?', options: ['Suspender siempre la levodopa primero, en cualquier circunstancia', 'Suspender primero anticolinérgicos, luego amantadina, luego agonistas dopaminérgicos, dejando la levodopa para el final', 'No existe ningún orden recomendado, se suspende todo simultáneamente', 'Aumentar la dosis de todos los agentes simultáneamente'], correct: 1, explanation: 'Se recomienda suspender primero los agentes con mayor propensión psicotogénica y menor beneficio motor relativo (anticolinérgicos, luego amantadina, luego agonistas dopaminérgicos), dejando la levodopa para el final.', dificultad: 'dificil' },
  { q: '¿Qué rango de estadios comprende la escala de Hoehn y Yahr?', options: ['1 a 10 exclusivamente', 'Únicamente 2 categorías: leve y grave', '0 a 100 como porcentaje de discapacidad', '0 a 5 (incluyendo estadios intermedios 1.5 y 2.5)'], correct: 3, explanation: 'La escala de Hoehn y Yahr comprende un rango de 0 a 5, incluyendo los estadios intermedios 1.5 y 2.5 en la versión modificada.', dificultad: 'facil' },
  { q: '¿Qué caracteriza al estadio 5 de la escala de Hoehn y Yahr?', options: ['Dependencia de silla de ruedas o encamado, salvo con ayuda', 'Enfermedad unilateral sin ningún impacto funcional', 'Ausencia completa de cualquier signo de enfermedad', 'Bilateral leve con recuperación en la prueba de tracción'], correct: 0, explanation: 'El estadio 5 de Hoehn y Yahr corresponde a la dependencia de silla de ruedas o encamado, salvo con asistencia.', dificultad: 'facil' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 68 años presenta bradicinesia progresiva, rigidez en rueda dentada, y temblor de reposo asimétrico en la mano derecha de 8 meses de evolución. Marcha con reducción del braceo derecho.',
    steps: [
      { q: '¿Qué diagnóstico es más probable dado este cuadro?', options: ['Temblor esencial', 'Corea de Huntington', 'Enfermedad de Parkinson', 'Distonía generalizada'], correct: 2, explanation: 'La combinación de bradicinesia, rigidez en rueda dentada, y temblor de reposo asimétrico es característica de la enfermedad de Parkinson.' },
      { q: '¿Qué hallazgo apoyaría retrospectivamente este diagnóstico si se inicia tratamiento?', options: ['La ausencia total de cualquier respuesta a levodopa', 'Una respuesta clara y sostenida a levodopa', 'La aparición de signos cerebelosos marcados', 'Una progresión extremadamente rápida en días'], correct: 1, explanation: 'Una respuesta clara y sostenida a levodopa apoya el diagnóstico de enfermedad de Parkinson idiopática frente a un parkinsonismo atípico.' },
      { q: 'Tras 6 años de tratamiento con levodopa, el paciente refiere que los síntomas reaparecen consistentemente 30 minutos antes de cada dosis programada. ¿Qué fenómeno es este?', options: ['Discinesia peak-dose', 'Psicosis dopaminérgica', 'Wearing-off', 'Demencia asociada a Parkinson'], correct: 2, explanation: 'La reaparición predecible de los síntomas antes de la siguiente dosis programada es el fenómeno de wearing-off.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 45 años presenta temblor bilateral de las manos al sostener una taza o escribir, presente desde hace 15 años, con antecedente de que su padre y su abuela tuvieron un temblor similar. No hay bradicinesia ni rigidez.',
    steps: [
      { q: '¿Qué diagnóstico es más probable dado este cuadro y el antecedente familiar?', options: ['Enfermedad de Parkinson', 'Enfermedad de Huntington', 'Distonía cervical', 'Temblor esencial'], correct: 3, explanation: 'El temblor de acción bilateral, familiar, y de larga evolución, sin bradicinesia ni rigidez, es característico del temblor esencial.' },
      { q: 'La paciente refiere que el temblor mejora notablemente tras una copa de vino en eventos sociales. ¿Qué implica este dato?', options: ['Es un dato característico de la historia del temblor esencial, no una recomendación terapéutica', 'Confirma que se trata de enfermedad de Parkinson en lugar de temblor esencial', 'Indica que el temblor es de origen psicógeno funcional', 'Es indicación de manejo con toxina botulínica sistémica'], correct: 0, explanation: 'La mejoría transitoria con alcohol es un dato característico de la historia clínica del temblor esencial, aunque no constituye una recomendación terapéutica.' },
      { q: 'El temblor comienza a interferir con su trabajo como técnica de laboratorio. ¿Cuál es el tratamiento de primera línea?', options: ['Levodopa/carbidopa', 'Propranolol o primidona', 'Tetrabenazina', 'Toxina botulínica sistémica'], correct: 1, explanation: 'Propranolol o primidona son el tratamiento de primera línea para el temblor esencial sintomático que interfiere con la función.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 38 años presenta corea progresiva de manos y tronco, cambios de personalidad recientes, e irritabilidad. Su padre fue diagnosticado con un trastorno del movimiento similar a los 55 años y murió con demencia avanzada.',
    steps: [
      { q: '¿Qué diagnóstico se debe sospechar fuertemente dado este cuadro y el antecedente familiar?', options: ['Temblor esencial', 'Enfermedad de Parkinson', 'Distonía focal', 'Enfermedad de Huntington'], correct: 3, explanation: 'La corea progresiva con cambios de personalidad y antecedente familiar autosómico dominante compatible sugiere fuertemente enfermedad de Huntington.' },
      { q: '¿Qué estudio confirma el diagnóstico?', options: ['Resonancia magnética exclusivamente, sin ningún estudio genético', 'Electromiografía de rutina', 'Estudio genético del número de repeticiones CAG en el gen HTT', 'Punción lumbar con cultivo de LCR'], correct: 2, explanation: 'El estudio genético del número de repeticiones CAG en el gen HTT confirma el diagnóstico de enfermedad de Huntington.' },
      { q: '¿Cuál es el tratamiento farmacológico específico para controlar la corea?', options: ['Tetrabenazina o deutetrabenazina', 'Levodopa/carbidopa', 'Toxina botulínica sistémica', 'Propranolol'], correct: 0, explanation: 'Tetrabenazina o deutetrabenazina, inhibidores del transportador vesicular de monoaminas tipo 2, son el tratamiento específico de la corea en esta enfermedad.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 74 años con enfermedad de Parkinson de 10 años de evolución desarrolla alucinaciones visuales de personas en su habitación, con conciencia parcial de que no son reales. No hay fiebre ni alteración aguda del estado de alerta.',
    steps: [
      { q: '¿Cuál es el primer paso antes de atribuir estas alucinaciones exclusivamente al tratamiento dopaminérgico?', options: ['Iniciar de inmediato haloperidol en dosis altas', 'Descartar activamente una causa metabólica o infecciosa aguda precipitante (delirium)', 'Duplicar la dosis de levodopa sin ninguna evaluación adicional', 'Suspender por completo todo tratamiento dopaminérgico de forma abrupta'], correct: 1, explanation: 'El primer paso es descartar activamente una causa metabólica o infecciosa precipitante antes de atribuir la psicosis exclusivamente al tratamiento dopaminérgico.' },
      { q: 'Descartada una causa aguda precipitante, ¿cuál es el siguiente paso en el manejo?', options: ['Aumentar la dosis de agonista dopaminérgico de inmediato', 'Iniciar risperidona en dosis altas como primera línea', 'Simplificar el esquema dopaminérgico, suspendiendo primero los agentes de mayor propensión psicotogénica y menor beneficio motor', 'No es necesario ningún ajuste del tratamiento'], correct: 2, explanation: 'El siguiente paso es simplificar el esquema dopaminérgico, suspendiendo primero los agentes de mayor propensión psicotogénica y menor beneficio motor relativo.' },
      { q: 'Las alucinaciones persisten pese a la simplificación del esquema. ¿Qué antipsicótico es apropiado, dado que no empeora el parkinsonismo motor?', options: ['Haloperidol', 'Pimavanserina', 'Risperidona en dosis altas', 'Olanzapina en dosis altas'], correct: 1, explanation: 'La pimavanserina, sin actividad antagonista dopaminérgica significativa, es apropiada porque no empeora el control motor, a diferencia de los antipsicóticos típicos y atípicos de alta potencia.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 71 años con enfermedad de Parkinson de 12 años de evolución refiere mareo intenso al levantarse de la cama, especialmente después del desayuno, con 2 caídas en el último mes.',
    steps: [
      { q: '¿Qué complicación se debe sospechar dado este cuadro?', options: ['Discinesia peak-dose', 'Psicosis dopaminérgica', 'Distonía cervical', 'Hipotensión ortostática (disfunción autonómica)'], correct: 3, explanation: 'El mareo al incorporarse, agravado tras las comidas, con caídas asociadas, sugiere hipotensión ortostática como manifestación de disfunción autonómica.' },
      { q: '¿Cómo se confirma este diagnóstico a la cabecera del paciente?', options: ['Midiendo la presión arterial en decúbito y de pie (1 y 3 minutos), buscando una caída ≥20 mmHg sistólica o ≥10 mmHg diastólica', 'Únicamente mediante un electrocardiograma en reposo', 'Únicamente mediante resonancia magnética cerebral', 'No es posible confirmar este diagnóstico de forma objetiva'], correct: 0, explanation: 'Se confirma midiendo la presión arterial en decúbito y de pie, buscando la caída característica que define la hipotensión ortostática.' },
      { q: '¿Cuál es la primera línea de manejo antes de considerar tratamiento farmacológico específico?', options: ['Iniciar fludrocortisona de inmediato sin ninguna medida previa', 'Medidas no farmacológicas: hidratación adecuada, elevación de la cabecera, medias de compresión, revisión de antihipertensivos concomitantes', 'Suspender por completo el tratamiento dopaminérgico de la enfermedad de Parkinson', 'Indicar reposo absoluto en cama de forma permanente'], correct: 1, explanation: 'Las medidas no farmacológicas (hidratación, elevación de cabecera, medias de compresión, revisión de antihipertensivos) son la primera línea antes de escalar a tratamiento farmacológico específico.' }
    ]
  }
];

export const flashcards = [
  { front: 'Clasificación de trastornos del movimiento', back: 'Hipocinéticos (Parkinson) e hipercinéticos (temblor, distonía, corea).' },
  { front: 'Efecto de la dopamina sobre vía directa/indirecta', back: 'Facilita la directa (facilita movimiento), inhibe la indirecta (frena movimiento).' },
  { front: 'Criterio motor cardinal de Parkinson (MDS)', back: 'Bradicinesia (obligatoria) + rigidez o temblor de reposo.' },
  { front: 'Sustrato patológico de Parkinson', back: 'Cuerpos de Lewy (alfa-sinucleína mal plegada).' },
  { front: 'Apoyo diagnóstico retrospectivo de Parkinson', back: 'Respuesta clara y sostenida a levodopa.' },
  { front: 'Trastorno de temblor más frecuente', back: 'Temblor esencial.' },
  { front: 'Temblor esencial vs. Parkinson', back: 'Esencial: postural/acción. Parkinson: reposo, mejora con movimiento.' },
  { front: '1ª línea del temblor esencial sintomático', back: 'Propranolol o primidona.' },
  { front: 'Mecanismo de la distonía', back: 'Alteración de la inhibición recíproca agonista-antagonista.' },
  { front: '1ª línea de la distonía focal', back: 'Toxina botulínica intramuscular.' },
  { front: 'Gen de distonía generalizada de inicio temprano', back: 'DYT1/TOR1A.' },
  { front: 'Mutación de la enfermedad de Huntington', back: 'Expansión de repeticiones CAG en el gen HTT.' },
  { front: 'Tríada de Huntington', back: 'Corea + deterioro cognitivo + síntomas psiquiátricos.' },
  { front: 'Tratamiento específico de la corea en Huntington', back: 'Tetrabenazina o deutetrabenazina.' },
  { front: 'Anticipación genética en Huntington', back: 'Más repeticiones CAG e inicio más temprano en generaciones sucesivas (transmisión paterna).' },
  { front: 'Wearing-off', back: 'Reaparición predecible de síntomas antes de la siguiente dosis de levodopa.' },
  { front: 'Discinesia peak-dose: cuándo ocurre', back: '30-90 min después de la toma (pico plasmático).' },
  { front: 'Fármaco para discinesias peak-dose', back: 'Amantadina.' },
  { front: 'Levodopa durante hospitalización', back: 'Nunca suspender abruptamente; mantener horario habitual.' },
  { front: 'Regla del año (demencia Parkinson vs. cuerpos de Lewy)', back: '&gt;1 año tras inicio motor = demencia de Parkinson; antes/simultáneo = cuerpos de Lewy.' },
  { front: 'Inhibidor de colinesterasa en demencia de Parkinson', back: 'Rivastigmina (mejor evidencia específica).' },
  { front: 'Por qué evitar anticolinérgicos con deterioro cognitivo', back: 'Empeoran significativamente la cognición.' },
  { front: 'Cómo documentar hipotensión ortostática', back: 'PA en decúbito y de pie (1 y 3 min): caída ≥20 sistólica / ≥10 diastólica.' },
  { front: 'Síntoma autonómico prodrómico de Parkinson', back: 'Estreñimiento (puede preceder por años).' },
  { front: 'Antipsicótico preferido en psicosis dopaminérgica', back: 'Pimavanserina (sin acción antagonista dopaminérgica significativa).' },
  { front: 'Por qué evitar antipsicóticos típicos en Parkinson', back: 'Empeoran marcadamente el parkinsonismo motor.' },
  { front: 'Orden de simplificación ante psicosis', back: 'Anticolinérgicos → amantadina → agonistas dopaminérgicos → levodopa (último).' },
  { front: 'Rango de la escala de Hoehn y Yahr', back: '0 a 5 (incluye 1.5 y 2.5).' },
  { front: 'Hoehn y Yahr estadio 5', back: 'Dependiente de silla de ruedas o encamado.' },
  { front: 'Fenómenos on-off', back: 'Transiciones impredecibles entre buen control motor y estado parkinsoniano.' }
];
