// topics/coagulacion-intravascular-diseminada/study.js: Autoevaluación de Coagulación
// Intravascular Diseminada.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Nota de método (ver memoria del proyecto): todas las preguntas se escribieron primero con la
// respuesta correcta en options[0]/correct:0 (trivialmente verificable), y luego se redistribuyó
// la posición de `correct` mecánicamente con un script, sin volver a adivinar cuál texto es el
// correcto. Cada pregunta se releyó completa (options+correct+explanation) tras la
// redistribución para confirmar que options[correct] es realmente la respuesta correcta.

export const quiz = [
  { q: '¿Por qué la CID se describe como un síndrome y nunca como una enfermedad primaria?', options: ['Porque es una mutación genética hereditaria presente desde el nacimiento', 'Porque nunca se asocia a ninguna otra condición médica identificable', 'Porque siempre se desencadena por una enfermedad subyacente que activa la coagulación de forma sistémica y descontrolada', 'Porque afecta exclusivamente a la piel, sin repercusión sistémica'], correct: 2, explanation: 'La CID es un síndrome adquirido que siempre se desencadena por una enfermedad subyacente (sepsis, obstétrica, neoplasia, trauma), nunca una enfermedad primaria en sí misma.', dificultad: 'facil' },
  { q: '¿Cuál es la paradoja central de la CID?', options: ['Solo ocurre trombosis, nunca hemorragia, en cualquier forma del síndrome', 'Trombosis microvascular generalizada y hemorragia ocurren simultáneamente', 'Solo ocurre hemorragia, nunca trombosis, en cualquier forma del síndrome', 'No existe ninguna paradoja; el cuadro es siempre puramente hemorrágico'], correct: 1, explanation: 'La paradoja central de la CID es que la trombosis microvascular generalizada (con isquemia de órganos) y la hemorragia (por consumo de plaquetas/factores e hiperfibrinólisis secundaria) ocurren simultáneamente.', dificultad: 'facil' },
  { q: '¿Qué distingue a la CID crónica/compensada de la CID aguda/descompensada?', options: ['La crónica siempre es más grave y de peor pronóstico que la aguda', 'Ambas formas son clínicamente idénticas, sin ninguna diferencia relevante', 'La crónica ocurre solo en niños y la aguda solo en adultos', 'La crónica tiene instauración lenta con predominio trombótico y sangrado mínimo; la aguda tiene instauración rápida con predominio hemorrágico'], correct: 3, explanation: 'La CID crónica/compensada tiene instauración lenta (semanas a meses) con predominio trombótico y sangrado mínimo; la aguda/descompensada tiene instauración rápida (horas a días) con predominio hemorrágico.', dificultad: 'intermedio' },
  { q: '¿Cuál es la causa más frecuente de CID en la práctica clínica?', options: ['Sepsis', 'Embolia de líquido amniótico', 'Leucemia promielocítica aguda', 'Trauma mayor'], correct: 0, explanation: 'La sepsis, particularmente por gramnegativos, es la causa más frecuente de CID en la práctica clínica.', dificultad: 'facil' },
  { q: '¿Qué mecanismo explica la activación de la coagulación en la CID asociada a sepsis?', options: ['Un déficit hereditario aislado del factor VIII presente desde el nacimiento', 'La exposición directa a líquido amniótico en la circulación materna', 'Las citocinas proinflamatorias inducen expresión de factor tisular en monocitos y endotelio, mientras se suprimen los anticoagulantes fisiológicos', 'Una mutación adquirida exclusiva de las células tumorales'], correct: 2, explanation: 'En la sepsis, las citocinas proinflamatorias inducen la expresión de factor tisular en monocitos y endotelio activado, mientras se suprimen simultáneamente los mecanismos anticoagulantes fisiológicos.', dificultad: 'intermedio' },
  { q: '¿Cuál es la piedra angular del manejo de la CID asociada a sepsis?', options: ['La transfusión sistemática de plasma fresco congelado independientemente del sangrado clínico', 'El tratamiento agresivo y temprano de la sepsis de base (control de la fuente, antibióticos, reanimación)', 'La anticoagulación terapéutica inmediata con heparina en todos los casos', 'La esplenectomía de urgencia'], correct: 1, explanation: 'El tratamiento agresivo y temprano de la sepsis de base es la piedra angular del manejo de la CID de cualquier etiología, dado que no existe un tratamiento específico que revierta la CID sin resolver la causa.', dificultad: 'intermedio' },
  { q: '¿Por qué la placenta y el líquido amniótico son capaces de desencadenar una CID particularmente explosiva?', options: ['Contienen grandes cantidades de heparina endógena', 'Carecen por completo de cualquier proteína procoagulante', 'Solo activan la vía extrínseca de forma muy lenta y gradual', 'Son extraordinariamente ricos en factor tisular'], correct: 3, explanation: 'La placenta y el líquido amniótico son extraordinariamente ricos en factor tisular, capaz de desencadenar una activación masiva y súbita de la coagulación al exponerse a la circulación materna.', dificultad: 'intermedio' },
  { q: '¿Cuál es la causa obstétrica de CID con una de las mortalidades más altas entre todas las etiologías de CID?', options: ['Embolia de líquido amniótico', 'Óbito fetal retenido evacuado oportunamente', 'Preeclampsia leve sin complicaciones', 'Parto vaginal sin complicaciones'], correct: 0, explanation: 'La embolia de líquido amniótico es infrecuente pero se asocia a una de las mortalidades más altas entre las causas de CID.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo de laboratorio es particularmente temprano y sensible en la CID obstétrica aguda?', options: ['La elevación aislada de la creatina-cinasa', 'El aumento del colesterol total', 'La caída rápida del fibrinógeno sérico', 'La disminución de la velocidad de sedimentación globular'], correct: 2, explanation: 'El fibrinógeno puede caer con extrema rapidez en la CID obstétrica aguda, siendo con frecuencia el hallazgo de laboratorio más temprano y sensible en este contexto.', dificultad: 'intermedio' },
  { q: '¿Qué mecanismo explica la coagulopatía particularmente grave e hiperfibrinolítica de la leucemia promielocítica aguda (LPA)?', options: ['Los promielocitos carecen por completo de cualquier contenido procoagulante', 'Solo se activa la vía extrínseca, sin ningún componente de fibrinólisis', 'El mecanismo es idéntico al de la CID por sepsis, sin ninguna particularidad', 'Los promielocitos leucémicos expresan simultáneamente factor tisular y activador tisular del plasminógeno en niveles anormalmente altos'], correct: 3, explanation: 'Los promielocitos leucémicos de la LPA expresan de forma característica tanto factor tisular como activador tisular del plasminógeno en niveles anormalmente altos, produciendo activación simultánea de coagulación y fibrinólisis.', dificultad: 'dificil' },
  { q: '¿Qué debe hacerse ante la sospecha clínica y morfológica de LPA con coagulopatía asociada?', options: ['Esperar la confirmación citogenética completa antes de iniciar cualquier tratamiento', 'Iniciar ácido all-trans retinoico de inmediato, sin esperar la confirmación citogenética completa', 'Iniciar quimioterapia citotóxica estándar sin ácido all-trans retinoico', 'Observar sin tratamiento hasta que la coagulopatía se resuelva espontáneamente'], correct: 1, explanation: 'Ante sospecha clínica/morfológica de LPA, el ácido all-trans retinoico debe iniciarse de inmediato sin esperar la confirmación citogenética completa, dado que revierte rápidamente la coagulopatía asociada.', dificultad: 'intermedio' },
  { q: '¿Qué patrón clínico caracteriza a la CID asociada a adenocarcinomas mucosecretores?', options: ['Trombosis venosa migratoria y recurrente (síndrome de Trousseau) con sangrado mínimo', 'Hemorragia intracraneal masiva como manifestación inicial más frecuente', 'Un score ISTH siempre por encima de 7', 'Instauración siempre más rápida que la CID por sepsis'], correct: 0, explanation: 'Los adenocarcinomas mucosecretores producen característicamente una CID crónica de bajo grado con trombosis venosa migratoria y recurrente (síndrome de Trousseau) y sangrado mínimo o ausente.', dificultad: 'intermedio' },
  { q: '¿Qué caracteriza a la fase hiperfibrinolítica temprana de la coagulopatía inducida por trauma?', options: ['Ocurre exclusivamente varios días después del trauma inicial', 'Aparece incluso antes de que la reanimación con líquidos contribuya a la dilución de factores', 'Nunca se asocia a la activación de la vía de la proteína C', 'Es indistinguible en mecanismo de la CID asociada a sepsis'], correct: 1, explanation: 'La coagulopatía inducida por trauma tiene una fase hiperfibrinolítica temprana que aparece incluso antes de que la reanimación con líquidos contribuya a la dilución de factores, mediada por la activación excesiva de la proteína C.', dificultad: 'dificil' },
  { q: '¿Cuáles son los 3 componentes de la tríada letal que agrava la coagulopatía inducida por trauma?', options: ['Hipotermia, acidosis, y coagulopatía dilucional', 'Hipertermia, alcalosis, y policitemia', 'Hiperglucemia, hipernatremia, y leucocitosis', 'Bradicardia, hipertensión, y bradipnea'], correct: 0, explanation: 'La tríada letal que agrava la coagulopatía inducida por trauma consiste en hipotermia, acidosis, y coagulopatía dilucional por reanimación con grandes volúmenes de cristaloide.', dificultad: 'facil' },
  { q: '¿Cuál es la ventana de tiempo ideal para administrar ácido tranexámico en el trauma mayor con hemorragia significativa?', options: ['Dentro de las primeras 24 horas, sin ninguna diferencia según el momento exacto', 'Únicamente después de 6 horas del trauma, nunca antes', 'Dentro de las primeras 3 horas del trauma', 'No existe ninguna ventana de tiempo relevante para su administración'], correct: 2, explanation: 'El ácido tranexámico debe administrarse idealmente dentro de las primeras 3 horas del trauma, dado el beneficio demostrado en mortalidad con la administración temprana.', dificultad: 'intermedio' },
  { q: '¿Por qué el paciente con CID grave sangra pese a estar en un estado inicialmente protrombótico?', options: ['La CID nunca produce sangrado real, solo trombosis', 'El sangrado se debe exclusivamente a un trauma no relacionado con la CID', 'El hígado deja de sintetizar cualquier proteína durante la CID', 'El consumo sostenido de plaquetas y factores por el depósito continuo de fibrina supera la capacidad de síntesis hepática y medular de reponerlos'], correct: 3, explanation: 'El paciente sangra porque el consumo sostenido de plaquetas y factores por el depósito continuo de fibrina en la microvasculatura supera la capacidad de síntesis de reponerlos, produciendo hipocoagulabilidad sobrepuesta al estado protrombótico inicial.', dificultad: 'dificil' },
  { q: '¿Qué hemoderivado es preferido para mantener el fibrinógeno por encima de 100-150 mg/dL en la CID con sangrado activo?', options: ['Concentrado eritrocitario exclusivamente', 'Albúmina humana', 'Crioprecipitado', 'Inmunoglobulina intravenosa'], correct: 2, explanation: 'El crioprecipitado es el hemoderivado preferido para mantener el fibrinógeno por encima de 100-150 mg/dL, dado que lo concentra en un volumen mucho menor que el plasma fresco congelado.', dificultad: 'intermedio' },
  { q: '¿Por qué los antifibrinolíticos (ácido tranexámico) se usan con precaución individualizada en la CID, a diferencia de su uso rutinario en otros contextos hemorrágicos?', options: ['Nunca tienen ningún efecto sobre la fibrinólisis en ningún contexto clínico', 'Están completamente contraindicados en absolutamente todos los pacientes con CID', 'Son el tratamiento de primera línea recomendado de rutina en toda CID sin excepción', 'Pueden agravar la trombosis microvascular en un síndrome que ya cursa con depósito extenso de fibrina'], correct: 3, explanation: 'Los antifibrinolíticos se usan con precaución individualizada en la CID porque pueden agravar la trombosis microvascular en un síndrome que ya cursa con depósito extenso de fibrina, salvo en contextos específicos con beneficio demostrado (trauma temprano, hemorragia obstétrica).', dificultad: 'dificil' },
  { q: '¿Qué produce la oclusión de la microvasculatura dérmica en la púrpura fulminans?', options: ['El depósito extenso de fibrina en la microvasculatura, produciendo lesiones purpúricas que progresan a necrosis', 'Una reacción alérgica aislada sin ninguna coagulopatía subyacente', 'Una infección fúngica superficial de la piel', 'Una deficiencia nutricional de vitamina C'], correct: 0, explanation: 'La oclusión de la microvasculatura dérmica por el depósito extenso de fibrina produce las lesiones purpúricas estrelladas características que progresan rápidamente a necrosis si no se revierte el proceso subyacente.', dificultad: 'intermedio' },
  { q: '¿Con qué infección se asocia clásicamente la púrpura fulminans?', options: ['Infección urinaria no complicada', 'Meningococcemia fulminante', 'Faringitis estreptocócica', 'Otitis media aguda'], correct: 1, explanation: 'La púrpura fulminans clásica se asocia con mayor frecuencia a la meningococcemia fulminante.', dificultad: 'facil' },
  { q: '¿Cómo se describen característicamente los bordes de las lesiones cutáneas de la púrpura fulminans?', options: ['Perfectamente circulares y de bordes lisos', 'Lineales, siguiendo estrictamente un trayecto vascular único', 'Estrellados, con bordes geográficos irregulares y centro necrótico grisáceo-negro', 'Indistinguibles de una simple equimosis leve sin ninguna progresión'], correct: 2, explanation: 'Las lesiones de la púrpura fulminans son estrelladas, con bordes geográficos irregulares, que progresan rápidamente a un centro necrótico grisáceo-negro.', dificultad: 'intermedio' },
  { q: '¿Qué mecanismo produce el síndrome de Waterhouse-Friderichsen en la meningococcemia fulminante?', options: ['Una infección directa y aislada del tejido suprarrenal por hongos', 'Microtrombosis y hemorragia consecuente en la vasculatura suprarrenal, destruyendo funcionalmente ambas glándulas', 'Un tumor suprarrenal primario de crecimiento rápido', 'Una reacción autoinmune contra la corteza suprarrenal de inicio crónico'], correct: 1, explanation: 'El síndrome de Waterhouse-Friderichsen resulta de la combinación de microtrombosis extensa de la vasculatura suprarrenal y la hemorragia consecuente dentro de la glándula, destruyendo funcionalmente ambas suprarrenales.', dificultad: 'dificil' },
  { q: '¿Qué hallazgo clínico debe hacer sospechar Waterhouse-Friderichsen en un paciente con meningococcemia fulminante?', options: ['Choque refractario a líquidos y vasopresores desproporcionado a la gravedad aparente de la sepsis', 'Una presión arterial completamente normal en todo momento', 'Ausencia total de cualquier alteración electrolítica', 'Mejoría espontánea y completa sin ningún tratamiento adicional'], correct: 0, explanation: 'El choque refractario a líquidos y vasopresores, desproporcionado a la gravedad aparente de la sepsis, debe hacer sospechar insuficiencia suprarrenal aguda por Waterhouse-Friderichsen.', dificultad: 'intermedio' },
  { q: '¿Cuál es el manejo apropiado ante sospecha fuerte de Waterhouse-Friderichsen?', options: ['Esperar la confirmación completa por tomografía suprarrenal antes de cualquier tratamiento', 'Administrar únicamente antipiréticos sin ningún soporte hormonal', 'Suspender los antibióticos hasta confirmar el diagnóstico endocrino', 'Iniciar hidrocortisona de estrés empíricamente, sin esperar la confirmación completa por imagen'], correct: 3, explanation: 'Ante sospecha clínica fuerte de Waterhouse-Friderichsen, la hidrocortisona de estrés debe iniciarse empíricamente sin esperar la confirmación completa por imagen, dado el riesgo relativamente bajo de una dosis de estrés a corto plazo.', dificultad: 'intermedio' },
  { q: '¿Qué factor contribuye a la isquemia digital y de extremidades en la CID grave asociada a choque séptico?', options: ['La vasodilatación periférica excesiva sin ningún componente de microtrombosis', 'Una infección fúngica sistémica no relacionada con la CID', 'La vasoconstricción periférica intensa por el uso de vasopresores en dosis altas, combinada con la microtrombosis', 'La hipoglucemia grave y sostenida'], correct: 2, explanation: 'La isquemia digital resulta de la oclusión microvascular por fibrina combinada con la vasoconstricción periférica intensa que acompaña al uso de vasopresores en dosis altas.', dificultad: 'intermedio' },
  { q: '¿Cuál es el manejo apropiado ante isquemia digital progresiva que evoluciona hacia gangrena en el contexto de CID grave?', options: ['Amputar de inmediato en cuanto aparece cualquier signo de cianosis digital', 'Diferir la amputación hasta la demarcación completa de la línea de gangrena establecida', 'No hay ningún manejo posible una vez que aparece isquemia digital', 'Iniciar anticoagulación terapéutica en dosis altas como único tratamiento'], correct: 1, explanation: 'La amputación debe diferirse hasta la demarcación completa de la línea de gangrena establecida, evitando la intervención precipitada antes de que la extensión real del daño esté claramente delimitada.', dificultad: 'intermedio' },
  { q: '¿Qué componentes conforman el score ISTH de CID manifiesta?', options: ['Únicamente el recuento plaquetario y la hemoglobina', 'Únicamente la creatinina sérica y la bilirrubina', 'Presión arterial, frecuencia cardiaca, y temperatura corporal', 'Recuento plaquetario, marcador relacionado con fibrina, prolongación del TP, y fibrinógeno'], correct: 3, explanation: 'El score ISTH de CID manifiesta combina el recuento plaquetario, un marcador relacionado con fibrina (dímero D/PDF), la prolongación del TP, y el nivel de fibrinógeno.', dificultad: 'facil' },
  { q: '¿Qué puntaje del score ISTH es compatible con CID manifiesta?', options: ['≥5', '≥2', '≥10', 'Cualquier puntaje mayor de 0 ya es diagnóstico'], correct: 0, explanation: 'Un puntaje ISTH ≥5 es compatible con CID manifiesta; un puntaje &lt;5 es sugestivo de CID no manifiesta.', dificultad: 'facil' },
  { q: '¿Qué se recomienda si el score ISTH es menor de 5 pero la sospecha clínica de CID persiste?', options: ['Descartar definitivamente el diagnóstico de forma permanente', 'Repetir el score en 1-2 días', 'Iniciar anticoagulación terapéutica de inmediato sin más estudio', 'No es necesario ningún seguimiento adicional en ningún caso'], correct: 1, explanation: 'Si el score ISTH es &lt;5 pero la sospecha clínica persiste, se recomienda repetir el score en 1-2 días, dado que la CID no manifiesta puede progresar.', dificultad: 'intermedio' },
  { q: 'En el score ISTH, ¿cuántos puntos se asignan a un recuento plaquetario por debajo de 50,000/µL?', options: ['2 puntos', '0 puntos', '5 puntos', '1 punto, el mismo valor que un recuento entre 50,000 y 100,000/µL'], correct: 0, explanation: 'Un recuento plaquetario por debajo de 50,000/µL se puntúa con 2 puntos en el score ISTH (1 punto si está entre 50,000-100,000/µL, 0 puntos si es mayor de 100,000/µL).', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente en choque séptico por neumonía grave. Laboratorio: plaquetas 45,000/µL, fibrinógeno 90 mg/dL, TP prolongado 7 segundos sobre el control, dímero D marcadamente elevado (incremento fuerte).',
    steps: [
      { q: 'Calculando el score ISTH con estos valores (plaquetas 2 pts, fibrinógeno 1 pt, TP 2 pts, dímero D 3 pts), ¿cuál es el resultado y su interpretación?', options: ['3 puntos, sugestivo de CID no manifiesta', '8 puntos, pero no tiene ninguna relevancia clínica', '0 puntos, descarta cualquier coagulopatía', '8 puntos, compatible con CID manifiesta'], correct: 3, explanation: 'La suma de 2+1+2+3 = 8 puntos, muy por encima del punto de corte de 5, compatible con CID manifiesta.' },
      { q: '¿Cuál es la prioridad terapéutica inmediata en este paciente?', options: ['Anticoagulación terapéutica inmediata con heparina en dosis altas', 'Esplenectomía de urgencia', 'Tratamiento agresivo de la sepsis de base (control de la fuente, antibióticos, reanimación)', 'Observación sin ninguna intervención hasta que el score ISTH normalice espontáneamente'], correct: 2, explanation: 'El tratamiento agresivo de la sepsis de base es la piedra angular del manejo, dado que no existe un tratamiento específico que revierta la CID sin resolver la causa.' },
      { q: 'El paciente presenta sangrado activo de sitios de venopunción. ¿Qué hemoderivado es más apropiado para el fibrinógeno de 90 mg/dL?', options: ['Crioprecipitado', 'Concentrado eritrocitario exclusivamente', 'Albúmina humana', 'Inmunoglobulina intravenosa'], correct: 0, explanation: 'El crioprecipitado es el hemoderivado más eficiente para corregir la hipofibrinogenemia (fibrinógeno &lt;100-150 mg/dL) con sangrado activo.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer embarazada de 34 semanas presenta dolor abdominal súbito, sangrado vaginal, y útero hipertónico. Se sospecha abruptio placentae. El fibrinógeno cae rápidamente en las siguientes horas.',
    steps: [
      { q: '¿Por qué el abruptio placentae puede desencadenar una CID de instauración muy rápida?', options: ['La placenta carece por completo de cualquier proteína procoagulante', 'El mecanismo es idéntico y tan lento como el de un adenocarcinoma mucosecretor', 'La placenta es extraordinariamente rica en factor tisular, que se expone súbitamente a la circulación materna', 'Solo puede desencadenar CID si el embarazo es múltiple'], correct: 2, explanation: 'La exposición súbita y masiva de factor tisular placentario a la circulación materna desencadena una generación explosiva de trombina en el abruptio placentae.' },
      { q: '¿Qué hallazgo de laboratorio debe vigilarse con particular atención en este contexto, dado que puede caer con rapidez extrema?', options: ['El colesterol total', 'El fibrinógeno sérico', 'La velocidad de sedimentación globular', 'La fosfatasa alcalina'], correct: 1, explanation: 'El fibrinógeno puede caer con extrema rapidez en la CID obstétrica aguda, siendo con frecuencia el hallazgo más temprano y sensible.' },
      { q: '¿Cuál es el manejo definitivo de esta paciente, coordinado con reanimación agresiva?', options: ['Manejo expectante ambulatorio sin ninguna intervención', 'Anticoagulación terapéutica como único tratamiento', 'Observación hasta que el trabajo de parto inicie espontáneamente', 'Resolución obstétrica urgente del embarazo, coordinada con protocolo de transfusión masiva'], correct: 3, explanation: 'El manejo obstétrico definitivo urgente (resolución del embarazo) coordinado con reanimación hemodinámica y soporte transfusional agresivo es el tratamiento apropiado del abruptio placentae con CID asociada.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 45 años con equimosis extensas de aparición súbita y epistaxis. Frotis de sangre periférica muestra promielocitos anormales. Fibrinógeno 80 mg/dL, dímero D muy elevado.',
    steps: [
      { q: '¿Qué diagnóstico se debe sospechar dado el hallazgo de promielocitos anormales con esta coagulopatía?', options: ['Leucemia promielocítica aguda (LPA)', 'Anemia ferropénica simple', 'Trombocitopenia inducida por fármacos aislada', 'Enfermedad de von Willebrand tipo 1'], correct: 0, explanation: 'La combinación de promielocitos anormales en el frotis con una coagulopatía hiperfibrinolítica grave (fibrinógeno muy bajo, dímero D muy elevado) es característica de la leucemia promielocítica aguda.' },
      { q: '¿Qué tratamiento debe iniciarse de inmediato, sin esperar la confirmación citogenética completa?', options: ['Quimioterapia citotóxica estándar sin ácido all-trans retinoico', 'Radioterapia craneal profiláctica', 'Trasplante de médula ósea urgente', 'Ácido all-trans retinoico'], correct: 3, explanation: 'Ante sospecha clínica/morfológica de LPA, el ácido all-trans retinoico debe iniciarse de inmediato, dado que revierte rápidamente la coagulopatía asociada y el retraso aumenta el riesgo de hemorragia fatal.' },
      { q: '¿Qué objetivo de fibrinógeno debe mantenerse con crioprecipitado durante toda la inducción de este paciente?', options: ['Por encima de 500 mg/dL, un nivel considerablemente más alto de lo necesario', 'Por encima de 100-150 mg/dL', 'No es necesario mantener ningún nivel específico de fibrinógeno', 'Por debajo de 50 mg/dL'], correct: 1, explanation: 'Durante la inducción de la LPA se debe mantener el fibrinógeno por encima de 100-150 mg/dL con crioprecipitado, dado el riesgo hemorrágico extremo en ese periodo.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente politraumatizado ingresa con sangrado microvascular difuso de sitios de venopunción y heridas, pese a control quirúrgico adecuado del sitio de lesión anatómica. Temperatura 34.5°C, pH 7.20.',
    steps: [
      { q: '¿Qué patrón de sangrado sugiere una coagulopatía sistémica más que una fuente anatómica única?', options: ['Sangrado exclusivamente del sitio quirúrgico ya controlado, sin ningún otro sitio afectado', 'Ausencia completa de cualquier sangrado clínico', 'Sangrado microvascular difuso, no atribuible a un vaso identificable, en múltiples sitios simultáneos', 'Sangrado limitado a un solo catéter venoso'], correct: 2, explanation: 'El sangrado microvascular difuso, no atribuible a un vaso identificable y en múltiples sitios simultáneos, sugiere una coagulopatía sistémica más que una fuente anatómica localizada.' },
      { q: 'Con temperatura 34.5°C y pH 7.20, ¿qué componentes de la tríada letal están presentes y deben corregirse activamente?', options: ['Hipotermia y acidosis', 'Hipertermia y alcalosis', 'Solo hiperglucemia, sin ningún otro componente', 'Ninguno; estos valores son irrelevantes para la coagulopatía'], correct: 0, explanation: 'La temperatura de 34.5°C indica hipotermia y el pH de 7.20 indica acidosis, 2 de los 3 componentes de la tríada letal que agravan la coagulopatía inducida por trauma.' },
      { q: '¿Qué fármaco debe haberse administrado idealmente dentro de las primeras 3 horas del trauma para reducir la mortalidad?', options: ['Warfarina', 'Ácido tranexámico', 'Heparina no fraccionada en dosis terapéutica', 'Aspirina en dosis altas'], correct: 1, explanation: 'El ácido tranexámico administrado idealmente dentro de las primeras 3 horas del trauma mayor con hemorragia significativa reduce la mortalidad.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Niño de 6 años con fiebre alta desarrolla lesiones cutáneas purpúricas estrelladas de aparición súbita en extremidades, que progresan rápidamente a necrosis central. Hemocultivo pendiente. Choque persiste pese a líquidos y dosis crecientes de norepinefrina.',
    steps: [
      { q: '¿Qué infección se debe sospechar fuertemente dado este cuadro de púrpura fulminans?', options: ['Infección urinaria no complicada', 'Faringitis viral simple', 'Meningococcemia fulminante', 'Otitis media aguda no complicada'], correct: 2, explanation: 'La combinación de fiebre alta y púrpura fulminans de aparición súbita es característica de la meningococcemia fulminante.' },
      { q: 'El choque persiste pese a líquidos y dosis crecientes de norepinefrina, desproporcionado a la sepsis de base. ¿Qué complicación endocrina se debe sospechar?', options: ['Hipertiroidismo primario', 'Diabetes insípida central aislada', 'Hiperparatiroidismo primario', 'Síndrome de Waterhouse-Friderichsen (hemorragia suprarrenal bilateral)'], correct: 3, explanation: 'El choque refractario a líquidos y vasopresores, desproporcionado a la sepsis de base, en un paciente con púrpura fulminans, debe hacer sospechar Waterhouse-Friderichsen.' },
      { q: '¿Cuál es el manejo apropiado ante esta sospecha, sin esperar la confirmación completa por imagen?', options: ['Iniciar hidrocortisona de estrés empíricamente, junto con antibióticos inmediatos', 'Esperar la confirmación completa por tomografía suprarrenal antes de cualquier tratamiento adicional', 'Suspender los antibióticos empíricos hasta confirmar el diagnóstico endocrino', 'No hay ningún tratamiento adicional posible más allá de los líquidos y vasopresores ya iniciados'], correct: 0, explanation: 'Ante sospecha fuerte de Waterhouse-Friderichsen, la hidrocortisona de estrés debe iniciarse empíricamente sin esperar la confirmación completa por imagen, junto con antibióticos empíricos inmediatos para la meningococcemia.' }
    ]
  }
];

export const flashcards = [
  { front: 'CID: ¿enfermedad primaria o síndrome?', back: 'Síndrome adquirido, siempre secundario a una enfermedad desencadenante.' },
  { front: 'La paradoja central de la CID', back: 'Trombosis microvascular y hemorragia ocurren simultáneamente.' },
  { front: 'CID crónica/compensada vs. aguda/descompensada', back: 'Crónica: lenta, predominio trombótico. Aguda: rápida, predominio hemorrágico.' },
  { front: 'Causa más frecuente de CID', back: 'Sepsis, particularmente por gramnegativos.' },
  { front: 'Mecanismo de la CID por sepsis', back: 'Citocinas inducen factor tisular en monocitos/endotelio + supresión de anticoagulantes fisiológicos.' },
  { front: 'Piedra angular del manejo de cualquier CID', back: 'Tratar la enfermedad desencadenante; no hay tratamiento específico que revierta la CID por sí sola.' },
  { front: 'Por qué la placenta/líquido amniótico desencadenan CID explosiva', back: 'Extraordinariamente ricos en factor tisular.' },
  { front: 'Causa obstétrica de CID con mayor mortalidad', back: 'Embolia de líquido amniótico.' },
  { front: 'Hallazgo más temprano/sensible en CID obstétrica aguda', back: 'Caída rápida del fibrinógeno.' },
  { front: 'Mecanismo de la CID en LPA', back: 'Promielocitos expresan factor tisular Y activador tisular del plasminógeno: hiperfibrinólisis grave.' },
  { front: 'Manejo urgente ante sospecha de LPA con coagulopatía', back: 'Ácido all-trans retinoico de inmediato, sin esperar citogenética.' },
  { front: 'CID crónica de adenocarcinoma mucosecretor', back: 'Síndrome de Trousseau: trombosis venosa migratoria, sangrado mínimo.' },
  { front: 'Fase hiperfibrinolítica temprana en trauma', back: 'Aparece antes de la dilución por líquidos; vía de la proteína C activada en exceso.' },
  { front: 'Tríada letal en trauma', back: 'Hipotermia + acidosis + coagulopatía dilucional.' },
  { front: 'Ventana de ácido tranexámico en trauma', back: 'Idealmente dentro de las primeras 3 horas.' },
  { front: 'Por qué el paciente con CID sangra pese al estado protrombótico', back: 'El consumo de plaquetas/factores supera la capacidad de síntesis de reponerlos.' },
  { front: 'Hemoderivado de elección para fibrinógeno bajo en CID', back: 'Crioprecipitado (objetivo &gt;100-150 mg/dL).' },
  { front: 'Por qué los antifibrinolíticos se usan con precaución en CID', back: 'Pueden agravar la trombosis microvascular ya presente.' },
  { front: 'Mecanismo de la púrpura fulminans', back: 'Depósito de fibrina en microvasculatura dérmica → necrosis.' },
  { front: 'Infección clásicamente asociada a púrpura fulminans', back: 'Meningococcemia fulminante.' },
  { front: 'Apariencia de las lesiones de púrpura fulminans', back: 'Estrelladas, bordes geográficos, centro necrótico grisáceo-negro.' },
  { front: 'Mecanismo del síndrome de Waterhouse-Friderichsen', back: 'Microtrombosis + hemorragia suprarrenal bilateral por CID grave.' },
  { front: 'Pista clínica de Waterhouse-Friderichsen', back: 'Choque refractario desproporcionado a la sepsis de base.' },
  { front: 'Manejo ante sospecha de Waterhouse-Friderichsen', back: 'Hidrocortisona de estrés empírica, sin esperar confirmación por imagen.' },
  { front: 'Mecanismo de la isquemia digital en CID grave', back: 'Microtrombosis + vasoconstricción por vasopresores en dosis altas.' },
  { front: 'Manejo de la gangrena digital establecida', back: 'Diferir amputación hasta demarcación completa de la línea de gangrena.' },
  { front: 'Componentes del score ISTH de CID', back: 'Plaquetas, marcador de fibrina (dímero D/PDF), TP prolongado, fibrinógeno.' },
  { front: 'Punto de corte del score ISTH', back: '≥5: CID manifiesta. &lt;5: repetir en 1-2 días si persiste la sospecha.' },
  { front: 'ISTH: puntos por plaquetas &lt;50,000/µL', back: '2 puntos (1 punto si 50,000-100,000/µL, 0 si &gt;100,000/µL).' },
  { front: 'ISTH: puntos por fibrinógeno', back: '≤100 mg/dL = 1 punto; &gt;100 mg/dL = 0 puntos.' }
];
