// topics/coagulacion-intravascular-diseminada/study.js: Autoevaluación de Coagulación
// Intravascular Diseminada.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Nota de método (ver memoria del proyecto): todas las preguntas se escribieron primero con la
// respuesta correcta en options[0]/correct:0 (trivialmente verificable), y luego se redistribuyó
// la posición de `correct` mecánicamente con un script, sin volver a adivinar cuál texto es el
// correcto. Cada pregunta se releyó completa (options+correct+explanation) tras la
// redistribución para confirmar que options[correct] es realmente la respuesta correcta.

export const quiz = [
  { q: '¿Por qué la CID se describe como un síndrome y nunca como una enfermedad primaria?', options: ['Es una mutación hereditaria del nacimiento', 'Aparece de forma aislada y primaria', 'Lo desencadena una enfermedad de base', 'Afecta solo a la piel, sin repercusión'], correct: 2, explanation: 'La CID es un síndrome adquirido que siempre se desencadena por una enfermedad subyacente (sepsis, obstétrica, neoplasia, trauma), nunca una enfermedad primaria en sí misma.', dificultad: 'facil' },
  { q: '¿Cuál es la paradoja central de la CID?', options: ['Solo hay trombosis, sin hemorragia', 'Trombosis y hemorragia simultáneas', 'Solo hay hemorragia, sin trombosis', 'No hay paradoja: es puramente hemorrágico'], correct: 1, explanation: 'La paradoja central de la CID es que la trombosis microvascular generalizada (con isquemia de órganos) y la hemorragia (por consumo de plaquetas/factores e hiperfibrinólisis secundaria) ocurren simultáneamente.', dificultad: 'facil' },
  { q: '¿Qué distingue a la CID crónica/compensada de la CID aguda/descompensada?', options: ['La crónica es la de peor pronóstico', 'Ambas formas son clínicamente idénticas', 'La crónica en niños, la aguda en adultos', 'Crónica trombótica, aguda hemorrágica'], correct: 3, explanation: 'La CID crónica/compensada tiene instauración lenta (semanas a meses) con predominio trombótico y sangrado mínimo; la aguda/descompensada tiene instauración rápida (horas a días) con predominio hemorrágico.', dificultad: 'intermedio' },
  { q: '¿Cuál es la causa más frecuente de CID en la práctica clínica?', options: ['Sepsis', 'Embolia de líquido amniótico', 'Leucemia promielocítica aguda', 'Trauma mayor'], correct: 0, explanation: 'La sepsis, particularmente por gramnegativos, es la causa más frecuente de CID en la práctica clínica.', dificultad: 'facil' },
  { q: '¿Qué mecanismo explica la activación de la coagulación en la CID asociada a sepsis?', options: ['Déficit hereditario aislado de factor VIII', 'Paso de líquido amniótico a la circulación', 'Citocinas que inducen factor tisular', 'Mutación adquirida de células tumorales'], correct: 2, explanation: 'En la sepsis, las citocinas proinflamatorias inducen la expresión de factor tisular en monocitos y endotelio activado, mientras se suprimen simultáneamente los mecanismos anticoagulantes fisiológicos.', dificultad: 'intermedio' },
  { q: '¿Cuál es la piedra angular del manejo de la CID asociada a sepsis?', options: ['Plasma fresco congelado sistemático', 'Tratar la sepsis de base de inmediato', 'Anticoagulación con heparina en todos', 'Esplenectomía de urgencia abierta'], correct: 1, explanation: 'El tratamiento agresivo y temprano de la sepsis de base es la piedra angular del manejo de la CID de cualquier etiología, dado que no existe un tratamiento específico que revierta la CID sin resolver la causa.', dificultad: 'intermedio' },
  { q: '¿Por qué la placenta y el líquido amniótico son capaces de desencadenar una CID particularmente explosiva?', options: ['Contienen grandes cantidades de heparina endógena', 'Carecen por completo de cualquier proteína procoagulante', 'Solo activan la vía extrínseca de forma muy lenta y gradual', 'Son extraordinariamente ricos en factor tisular'], correct: 3, explanation: 'La placenta y el líquido amniótico son extraordinariamente ricos en factor tisular, capaz de desencadenar una activación masiva y súbita de la coagulación al exponerse a la circulación materna.', dificultad: 'intermedio' },
  { q: '¿Cuál es la causa obstétrica de CID con una de las mortalidades más altas entre todas las etiologías de CID?', options: ['Embolia de líquido amniótico', 'Óbito fetal retenido evacuado oportunamente', 'Preeclampsia leve sin complicaciones', 'Parto vaginal sin complicaciones'], correct: 0, explanation: 'La embolia de líquido amniótico es infrecuente pero se asocia a una de las mortalidades más altas entre las causas de CID.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo de laboratorio es particularmente temprano y sensible en la CID obstétrica aguda?', options: ['La elevación aislada de la creatina-cinasa', 'El aumento del colesterol total', 'La caída rápida del fibrinógeno sérico', 'La disminución de la velocidad de sedimentación globular'], correct: 2, explanation: 'El fibrinógeno puede caer con extrema rapidez en la CID obstétrica aguda, siendo con frecuencia el hallazgo de laboratorio más temprano y sensible en este contexto.', dificultad: 'intermedio' },
  { q: '¿Qué mecanismo explica la coagulopatía particularmente grave e hiperfibrinolítica de la leucemia promielocítica aguda (LPA)?', options: ['Los promielocitos carecen de procoagulantes', 'Solo se activa la vía extrínseca clásica', 'El mecanismo es igual al de la sepsis', 'Expresan factor tisular y tPA a la vez'], correct: 3, explanation: 'Los promielocitos leucémicos de la LPA expresan de forma característica tanto factor tisular como activador tisular del plasminógeno en niveles anormalmente altos, produciendo activación simultánea de coagulación y fibrinólisis.', dificultad: 'dificil' },
  { q: '¿Qué debe hacerse ante la sospecha clínica y morfológica de LPA con coagulopatía asociada?', options: ['Esperar la confirmación citogenética', 'Iniciar ATRA sin esperar confirmación', 'Quimioterapia citotóxica estándar sin ATRA', 'Observar hasta que se resuelva sola'], correct: 1, explanation: 'Ante sospecha clínica/morfológica de LPA, el ácido all-trans retinoico debe iniciarse de inmediato sin esperar la confirmación citogenética completa, dado que revierte rápidamente la coagulopatía asociada.', dificultad: 'intermedio' },
  { q: '¿Qué patrón clínico caracteriza a la CID asociada a adenocarcinomas mucosecretores?', options: ['Trombosis venosa migratoria, poco sangrado', 'Hemorragia intracraneal masiva inicial', 'Un score ISTH sistemáticamente alto', 'Instauración más rápida que en la sepsis'], correct: 0, explanation: 'Los adenocarcinomas mucosecretores producen característicamente una CID crónica de bajo grado con trombosis venosa migratoria y recurrente (síndrome de Trousseau) y sangrado mínimo o ausente.', dificultad: 'intermedio' },
  { q: '¿Qué caracteriza a la fase hiperfibrinolítica temprana de la coagulopatía inducida por trauma?', options: ['Ocurre varios días después del trauma', 'Aparece antes de la dilución por líquidos', 'No se asocia a la vía de la proteína C', 'Su mecanismo es igual al de la sepsis'], correct: 1, explanation: 'La coagulopatía inducida por trauma tiene una fase hiperfibrinolítica temprana que aparece incluso antes de que la reanimación con líquidos contribuya a la dilución de factores, mediada por la activación excesiva de la proteína C.', dificultad: 'dificil' },
  { q: '¿Cuáles son los 3 componentes de la tríada letal que agrava la coagulopatía inducida por trauma?', options: ['Hipotermia, acidosis, y coagulopatía dilucional', 'Hipertermia, alcalosis, y policitemia', 'Hiperglucemia, hipernatremia, y leucocitosis', 'Bradicardia, hipertensión, y bradipnea'], correct: 0, explanation: 'La tríada letal que agrava la coagulopatía inducida por trauma consiste en hipotermia, acidosis, y coagulopatía dilucional por reanimación con grandes volúmenes de cristaloide.', dificultad: 'facil' },
  { q: '¿Cuál es la ventana de tiempo ideal para administrar ácido tranexámico en el trauma mayor con hemorragia significativa?', options: ['Dentro de las primeras 24 horas', 'Después de 6 horas del trauma', 'Dentro de las primeras 3 horas', 'El momento no modifica el efecto'], correct: 2, explanation: 'El ácido tranexámico debe administrarse idealmente dentro de las primeras 3 horas del trauma, dado el beneficio demostrado en mortalidad con la administración temprana.', dificultad: 'intermedio' },
  { q: '¿Por qué el paciente con CID grave sangra pese a estar en un estado inicialmente protrombótico?', options: ['La CID no produce sangrado verdadero', 'El sangrado se debe a un trauma aparte', 'El hígado deja de sintetizar proteínas', 'El consumo supera la capacidad de reponer'], correct: 3, explanation: 'El paciente sangra porque el consumo sostenido de plaquetas y factores por el depósito continuo de fibrina en la microvasculatura supera la capacidad de síntesis de reponerlos, produciendo hipocoagulabilidad sobrepuesta al estado protrombótico inicial.', dificultad: 'dificil' },
  { q: '¿Qué hemoderivado es preferido para mantener el fibrinógeno por encima de 100-150 mg/dL en la CID con sangrado activo?', options: ['Concentrado eritrocitario', 'Albúmina humana al 20%', 'Crioprecipitado', 'Inmunoglobulina intravenosa'], correct: 2, explanation: 'El crioprecipitado es el hemoderivado preferido para mantener el fibrinógeno por encima de 100-150 mg/dL, dado que lo concentra en un volumen mucho menor que el plasma fresco congelado.', dificultad: 'intermedio' },
  { q: '¿Por qué los antifibrinolíticos (ácido tranexámico) se usan con precaución individualizada en la CID, a diferencia de su uso rutinario en otros contextos hemorrágicos?', options: ['No tienen efecto sobre la fibrinólisis', 'Están formalmente contraindicados en la CID', 'Son el tratamiento de primera línea en la CID', 'Pueden agravar la trombosis microvascular'], correct: 3, explanation: 'Los antifibrinolíticos se usan con precaución individualizada en la CID porque pueden agravar la trombosis microvascular en un síndrome que ya cursa con depósito extenso de fibrina, salvo en contextos específicos con beneficio demostrado (trauma temprano, hemorragia obstétrica).', dificultad: 'dificil' },
  { q: '¿Qué produce la oclusión de la microvasculatura dérmica en la púrpura fulminans?', options: ['Depósito extenso de fibrina en la dermis', 'Una reacción alérgica sin coagulopatía', 'Infección fúngica superficial de la piel', 'Deficiencia nutricional de vitamina C'], correct: 0, explanation: 'La oclusión de la microvasculatura dérmica por el depósito extenso de fibrina produce las lesiones purpúricas estrelladas características que progresan rápidamente a necrosis si no se revierte el proceso subyacente.', dificultad: 'intermedio' },
  { q: '¿Con qué infección se asocia clásicamente la púrpura fulminans?', options: ['Infección urinaria no complicada', 'Meningococcemia fulminante', 'Faringitis estreptocócica', 'Otitis media aguda'], correct: 1, explanation: 'La púrpura fulminans clásica se asocia con mayor frecuencia a la meningococcemia fulminante.', dificultad: 'facil' },
  { q: '¿Cómo se describen característicamente los bordes de las lesiones cutáneas de la púrpura fulminans?', options: ['Redondeados y de bordes lisos regulares', 'Lineales, siguiendo un trayecto vascular', 'Estrellados, con centro necrótico', 'Iguales a los de una equimosis simple'], correct: 2, explanation: 'Las lesiones de la púrpura fulminans son estrelladas, con bordes geográficos irregulares, que progresan rápidamente a un centro necrótico grisáceo-negro.', dificultad: 'intermedio' },
  { q: '¿Qué mecanismo produce el síndrome de Waterhouse-Friderichsen en la meningococcemia fulminante?', options: ['Infección fúngica directa de la glándula', 'Microtrombosis y hemorragia suprarrenal', 'Un tumor suprarrenal de crecimiento rápido', 'Reacción autoinmune contra la corteza'], correct: 1, explanation: 'El síndrome de Waterhouse-Friderichsen resulta de la combinación de microtrombosis extensa de la vasculatura suprarrenal y la hemorragia consecuente dentro de la glándula, destruyendo funcionalmente ambas suprarrenales.', dificultad: 'dificil' },
  { q: '¿Qué hallazgo clínico debe hacer sospechar Waterhouse-Friderichsen en un paciente con meningococcemia fulminante?', options: ['Choque refractario a líquidos y vasopresores', 'Presión arterial normal en todo momento', 'Ausencia de alteraciones electrolíticas', 'Mejoría espontánea sin soporte adicional'], correct: 0, explanation: 'El choque refractario a líquidos y vasopresores, desproporcionado a la gravedad aparente de la sepsis, debe hacer sospechar insuficiencia suprarrenal aguda por Waterhouse-Friderichsen.', dificultad: 'intermedio' },
  { q: '¿Cuál es el manejo apropiado ante sospecha fuerte de Waterhouse-Friderichsen?', options: ['Esperar la tomografía suprarrenal previa', 'Solo antipiréticos, sin soporte hormonal', 'Suspender los antibióticos hasta confirmar', 'Hidrocortisona de estrés empírica'], correct: 3, explanation: 'Ante sospecha clínica fuerte de Waterhouse-Friderichsen, la hidrocortisona de estrés debe iniciarse empíricamente sin esperar la confirmación completa por imagen, dado el riesgo relativamente bajo de una dosis de estrés a corto plazo.', dificultad: 'intermedio' },
  { q: '¿Qué factor contribuye a la isquemia digital y de extremidades en la CID grave asociada a choque séptico?', options: ['Vasodilatación periférica sin microtrombos', 'Una infección fúngica sistémica añadida', 'Vasopresores en dosis altas y microtrombosis', 'Hipoglucemia grave y sostenida en el tiempo'], correct: 2, explanation: 'La isquemia digital resulta de la oclusión microvascular por fibrina combinada con la vasoconstricción periférica intensa que acompaña al uso de vasopresores en dosis altas.', dificultad: 'intermedio' },
  { q: '¿Cuál es el manejo apropiado ante isquemia digital progresiva que evoluciona hacia gangrena en el contexto de CID grave?', options: ['Amputar en cuanto aparece la cianosis', 'Diferir la amputación hasta la demarcación', 'No hay manejo posible una vez isquémico', 'Anticoagulación en dosis altas aislada'], correct: 1, explanation: 'La amputación debe diferirse hasta la demarcación completa de la línea de gangrena establecida, evitando la intervención precipitada antes de que la extensión real del daño esté claramente delimitada.', dificultad: 'intermedio' },
  { q: '¿Qué componentes conforman el score ISTH de CID manifiesta?', options: ['Solo recuento plaquetario y hemoglobina', 'Creatinina sérica y bilirrubina total', 'Presión, frecuencia cardiaca y temperatura', 'Plaquetas, dímero D, TP y fibrinógeno'], correct: 3, explanation: 'El score ISTH de CID manifiesta combina el recuento plaquetario, un marcador relacionado con fibrina (dímero D/PDF), la prolongación del TP, y el nivel de fibrinógeno.', dificultad: 'facil' },
  { q: '¿Qué puntaje del score ISTH es compatible con CID manifiesta?', options: ['≥5 puntos', '≥2 puntos', '≥10 puntos', '≥8 puntos'], correct: 0, explanation: 'Un puntaje ISTH ≥5 es compatible con CID manifiesta; un puntaje &lt;5 es sugestivo de CID no manifiesta.', dificultad: 'facil' },
  { q: '¿Qué se recomienda si el score ISTH es menor de 5 pero la sospecha clínica de CID persiste?', options: ['Descartar el diagnóstico y cerrar el caso', 'Repetir el score en 1-2 días', 'Anticoagular de inmediato sin más estudio', 'Suspender el seguimiento del paciente'], correct: 1, explanation: 'Si el score ISTH es &lt;5 pero la sospecha clínica persiste, se recomienda repetir el score en 1-2 días, dado que la CID no manifiesta puede progresar.', dificultad: 'intermedio' },
  { q: 'En el score ISTH, ¿cuántos puntos se asignan a un recuento plaquetario por debajo de 50,000/µL?', options: ['2 puntos', '0 puntos', '5 puntos', '1 punto'], correct: 0, explanation: 'Un recuento plaquetario por debajo de 50,000/µL se puntúa con 2 puntos en el score ISTH (1 punto si está entre 50,000-100,000/µL, 0 puntos si es mayor de 100,000/µL).', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente en choque séptico por neumonía grave. Laboratorio: plaquetas 45,000/µL, fibrinógeno 90 mg/dL, TP prolongado 7 segundos sobre el control, dímero D marcadamente elevado (incremento fuerte).',
    steps: [
      { q: 'Calculando el score ISTH con estos valores (plaquetas 2 pts, fibrinógeno 1 pt, TP 2 pts, dímero D 3 pts), ¿cuál es el resultado y su interpretación?', options: ['3 puntos, sugestivo de no manifiesta', '8 puntos, sin relevancia clínica alguna', '0 puntos, descarta toda coagulopatía', '8 puntos, compatible con CID manifiesta'], correct: 3, explanation: 'La suma de 2+1+2+3 = 8 puntos, muy por encima del punto de corte de 5, compatible con CID manifiesta.' },
      { q: '¿Cuál es la prioridad terapéutica inmediata en este paciente?', options: ['Heparina en dosis altas de inmediato', 'Esplenectomía de urgencia abierta', 'Tratar la sepsis de base de inmediato', 'Observar hasta que el ISTH normalice'], correct: 2, explanation: 'El tratamiento agresivo de la sepsis de base es la piedra angular del manejo, dado que no existe un tratamiento específico que revierta la CID sin resolver la causa.' },
      { q: 'El paciente presenta sangrado activo de sitios de venopunción. ¿Qué hemoderivado es más apropiado para el fibrinógeno de 90 mg/dL?', options: ['Crioprecipitado', 'Concentrado eritrocitario', 'Albúmina humana al 20%', 'Inmunoglobulina intravenosa'], correct: 0, explanation: 'El crioprecipitado es el hemoderivado más eficiente para corregir la hipofibrinogenemia (fibrinógeno &lt;100-150 mg/dL) con sangrado activo.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer embarazada de 34 semanas presenta dolor abdominal súbito, sangrado vaginal, y útero hipertónico. Se sospecha abruptio placentae. El fibrinógeno cae rápidamente en las siguientes horas.',
    steps: [
      { q: '¿Por qué el abruptio placentae puede desencadenar una CID de instauración muy rápida?', options: ['La placenta carece de procoagulantes', 'Su mecanismo es lento, como el tumoral', 'La placenta es muy rica en factor tisular', 'Solo ocurre si el embarazo es múltiple'], correct: 2, explanation: 'La exposición súbita y masiva de factor tisular placentario a la circulación materna desencadena una generación explosiva de trombina en el abruptio placentae.' },
      { q: '¿Qué hallazgo de laboratorio debe vigilarse con particular atención en este contexto, dado que puede caer con rapidez extrema?', options: ['El colesterol total', 'El fibrinógeno sérico', 'La velocidad de sedimentación globular', 'La fosfatasa alcalina'], correct: 1, explanation: 'El fibrinógeno puede caer con extrema rapidez en la CID obstétrica aguda, siendo con frecuencia el hallazgo más temprano y sensible.' },
      { q: '¿Cuál es el manejo definitivo de esta paciente, coordinado con reanimación agresiva?', options: ['Manejo expectante de forma ambulatoria', 'Anticoagulación como único tratamiento', 'Esperar el inicio espontáneo del parto', 'Resolución obstétrica urgente'], correct: 3, explanation: 'El manejo obstétrico definitivo urgente (resolución del embarazo) coordinado con reanimación hemodinámica y soporte transfusional agresivo es el tratamiento apropiado del abruptio placentae con CID asociada.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 45 años con equimosis extensas de aparición súbita y epistaxis. Frotis de sangre periférica muestra promielocitos anormales. Fibrinógeno 80 mg/dL, dímero D muy elevado.',
    steps: [
      { q: '¿Qué diagnóstico se debe sospechar dado el hallazgo de promielocitos anormales con esta coagulopatía?', options: ['Leucemia promielocítica aguda (LPA)', 'Anemia ferropénica simple', 'Trombocitopenia inducida por fármacos aislada', 'Enfermedad de von Willebrand tipo 1'], correct: 0, explanation: 'La combinación de promielocitos anormales en el frotis con una coagulopatía hiperfibrinolítica grave (fibrinógeno muy bajo, dímero D muy elevado) es característica de la leucemia promielocítica aguda.' },
      { q: '¿Qué tratamiento debe iniciarse de inmediato, sin esperar la confirmación citogenética completa?', options: ['Quimioterapia citotóxica sin ATRA', 'Radioterapia craneal profiláctica', 'Trasplante de médula ósea urgente', 'Ácido all-trans retinoico'], correct: 3, explanation: 'Ante sospecha clínica/morfológica de LPA, el ácido all-trans retinoico debe iniciarse de inmediato, dado que revierte rápidamente la coagulopatía asociada y el retraso aumenta el riesgo de hemorragia fatal.' },
      { q: '¿Qué objetivo de fibrinógeno debe mantenerse con crioprecipitado durante toda la inducción de este paciente?', options: ['Por encima de 500-600 mg/dL', 'Por encima de 100-150 mg/dL', 'Por encima de 300-400 mg/dL', 'Por debajo de 50-80 mg/dL'], correct: 1, explanation: 'Durante la inducción de la LPA se debe mantener el fibrinógeno por encima de 100-150 mg/dL con crioprecipitado, dado el riesgo hemorrágico extremo en ese periodo.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente politraumatizado ingresa con sangrado microvascular difuso de sitios de venopunción y heridas, pese a control quirúrgico adecuado del sitio de lesión anatómica. Temperatura 34.5°C, pH 7.20.',
    steps: [
      { q: '¿Qué patrón de sangrado sugiere una coagulopatía sistémica más que una fuente anatómica única?', options: ['Sangrado solo del sitio quirúrgico ya controlado', 'Ausencia de sangrado clínicamente visible', 'Sangrado microvascular difuso en varios sitios', 'Sangrado limitado a un único catéter venoso'], correct: 2, explanation: 'El sangrado microvascular difuso, no atribuible a un vaso identificable y en múltiples sitios simultáneos, sugiere una coagulopatía sistémica más que una fuente anatómica localizada.' },
      { q: 'Con temperatura 34.5°C y pH 7.20, ¿qué componentes de la tríada letal están presentes y deben corregirse activamente?', options: ['Hipotermia y acidosis', 'Hipertermia y alcalosis', 'Hiperglucemia y alcalosis', 'Hipertermia y acidosis'], correct: 0, explanation: 'La temperatura de 34.5°C indica hipotermia y el pH de 7.20 indica acidosis, 2 de los 3 componentes de la tríada letal que agravan la coagulopatía inducida por trauma.' },
      { q: '¿Qué fármaco debe haberse administrado idealmente dentro de las primeras 3 horas del trauma para reducir la mortalidad?', options: ['Warfarina oral', 'Ácido tranexámico', 'Heparina no fraccionada', 'Aspirina en dosis altas'], correct: 1, explanation: 'El ácido tranexámico administrado idealmente dentro de las primeras 3 horas del trauma mayor con hemorragia significativa reduce la mortalidad.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Niño de 6 años con fiebre alta desarrolla lesiones cutáneas purpúricas estrelladas de aparición súbita en extremidades, que progresan rápidamente a necrosis central. Hemocultivo pendiente. Choque persiste pese a líquidos y dosis crecientes de norepinefrina.',
    steps: [
      { q: '¿Qué infección se debe sospechar fuertemente dado este cuadro de púrpura fulminans?', options: ['Infección urinaria no complicada', 'Faringitis viral simple', 'Meningococcemia fulminante', 'Otitis media aguda no complicada'], correct: 2, explanation: 'La combinación de fiebre alta y púrpura fulminans de aparición súbita es característica de la meningococcemia fulminante.' },
      { q: 'El choque persiste pese a líquidos y dosis crecientes de norepinefrina, desproporcionado a la sepsis de base. ¿Qué complicación endocrina se debe sospechar?', options: ['Crisis tirotóxica aguda', 'Diabetes insípida central', 'Hiperparatiroidismo primario', 'Waterhouse-Friderichsen'], correct: 3, explanation: 'El choque refractario a líquidos y vasopresores, desproporcionado a la sepsis de base, en un paciente con púrpura fulminans, debe hacer sospechar Waterhouse-Friderichsen.' },
      { q: '¿Cuál es el manejo apropiado ante esta sospecha, sin esperar la confirmación completa por imagen?', options: ['Hidrocortisona de estrés empírica', 'Esperar la tomografía suprarrenal', 'Suspender los antibióticos empíricos', 'Continuar solo líquidos y vasopresores'], correct: 0, explanation: 'Ante sospecha fuerte de Waterhouse-Friderichsen, la hidrocortisona de estrés debe iniciarse empíricamente sin esperar la confirmación completa por imagen, junto con antibióticos empíricos inmediatos para la meningococcemia.' }
    ]
  }
];

export const flashcards = [
  { front: 'CID: ¿enfermedad primaria o síndrome?', back: 'Síndrome adquirido, siempre secundario a una enfermedad desencadenante.' },
  { front: 'La paradoja central de la CID', back: 'Trombosis microvascular y hemorragia ocurren simultáneamente.' },
  { front: 'CID crónica/compensada vs. aguda/descompensada', back: 'Crónica: lenta, predominio trombótico. Aguda: rápida, predominio hemorrágico.' },
  { front: 'Causa más frecuente de CID', back: 'Sepsis, particularmente por gramnegativos.' },
  { front: 'Mecanismo de la CID por sepsis', back: 'Citocinas inducen factor tisular en monocitos/endotelio + supresión de anticoagulantes fisiológicos.' },
  { front: 'Piedra angular del manejo de cualquier CID', back: 'Tratar la enfermedad desencadenante; no hay tratamiento específico que revierta la CID por sí sola.' },
  { front: 'Por qué la placenta/líquido amniótico desencadenan CID explosiva', back: 'Extraordinariamente ricos en factor tisular.' },
  { front: 'Causa obstétrica de CID con mayor mortalidad', back: 'Embolia de líquido amniótico.' },
  { front: 'Hallazgo más temprano/sensible en CID obstétrica aguda', back: 'Caída rápida del fibrinógeno.' },
  { front: 'Mecanismo de la CID en LPA', back: 'Promielocitos expresan factor tisular Y activador tisular del plasminógeno: hiperfibrinólisis grave.' },
  { front: 'Manejo urgente ante sospecha de LPA con coagulopatía', back: 'Ácido all-trans retinoico de inmediato, sin esperar citogenética.' },
  { front: 'CID crónica de adenocarcinoma mucosecretor', back: 'Síndrome de Trousseau: trombosis venosa migratoria, sangrado mínimo.' },
  { front: 'Fase hiperfibrinolítica temprana en trauma', back: 'Aparece antes de la dilución por líquidos; vía de la proteína C activada en exceso.' },
  { front: 'Tríada letal en trauma', back: 'Hipotermia + acidosis + coagulopatía dilucional.' },
  { front: 'Ventana de ácido tranexámico en trauma', back: 'Idealmente dentro de las primeras 3 horas.' },
  { front: 'Por qué el paciente con CID sangra pese al estado protrombótico', back: 'El consumo de plaquetas/factores supera la capacidad de síntesis de reponerlos.' },
  { front: 'Hemoderivado de elección para fibrinógeno bajo en CID', back: 'Crioprecipitado (objetivo &gt;100-150 mg/dL).' },
  { front: 'Por qué los antifibrinolíticos se usan con precaución en CID', back: 'Pueden agravar la trombosis microvascular ya presente.' },
  { front: 'Mecanismo de la púrpura fulminans', back: 'Depósito de fibrina en microvasculatura dérmica → necrosis.' },
  { front: 'Infección clásicamente asociada a púrpura fulminans', back: 'Meningococcemia fulminante.' },
  { front: 'Apariencia de las lesiones de púrpura fulminans', back: 'Estrelladas, bordes geográficos, centro necrótico grisáceo-negro.' },
  { front: 'Mecanismo del síndrome de Waterhouse-Friderichsen', back: 'Microtrombosis + hemorragia suprarrenal bilateral por CID grave.' },
  { front: 'Pista clínica de Waterhouse-Friderichsen', back: 'Choque refractario desproporcionado a la sepsis de base.' },
  { front: 'Manejo ante sospecha de Waterhouse-Friderichsen', back: 'Hidrocortisona de estrés empírica, sin esperar confirmación por imagen.' },
  { front: 'Mecanismo de la isquemia digital en CID grave', back: 'Microtrombosis + vasoconstricción por vasopresores en dosis altas.' },
  { front: 'Manejo de la gangrena digital establecida', back: 'Diferir amputación hasta demarcación completa de la línea de gangrena.' },
  { front: 'Componentes del score ISTH de CID', back: 'Plaquetas, marcador de fibrina (dímero D/PDF), TP prolongado, fibrinógeno.' },
  { front: 'Punto de corte del score ISTH', back: '≥5: CID manifiesta. &lt;5: repetir en 1-2 días si persiste la sospecha.' },
  { front: 'ISTH: puntos por plaquetas &lt;50,000/µL', back: '2 puntos (1 punto si 50,000-100,000/µL, 0 si &gt;100,000/µL).' },
  { front: 'ISTH: puntos por fibrinógeno', back: '≤100 mg/dL = 1 punto; &gt;100 mg/dL = 0 puntos.' }
];
