// topics/linfadenopatias/study.js: Autoevaluación de Linfadenopatías.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Nota de método (ver memoria del proyecto): todas las preguntas se escribieron primero con la
// respuesta correcta en options[0]/correct:0 (trivialmente verificable), y luego se redistribuyó
// la posición de `correct` mecánicamente con un script, sin volver a adivinar cuál texto es el
// correcto.

export const quiz = [
  { q: '¿Qué distingue a la linfadenopatía "generalizada" de la "localizada"?', options: ['La generalizada siempre es de causa maligna y la localizada nunca lo es', 'La afectación de 2 o más regiones ganglionares no contiguas, frente a una sola región', 'La generalizada solo ocurre en niños', 'No existe ninguna distinción clínicamente relevante entre ambas'], correct: 1, explanation: 'La linfadenopatía generalizada se define por la afectación de 2 o más regiones ganglionares no contiguas, a diferencia de la localizada que afecta una sola región.', dificultad: 'facil' },
  { q: '¿Cuál es el reto clínico central en la evaluación de la linfadenopatía?', options: ['Determinar el color exacto de la piel suprayacente', 'Medir la temperatura corporal exacta del paciente', 'Ninguno, todos los casos requieren biopsia inmediata', 'Distinguir de forma eficiente qué casos requieren observación expectante y cuáles requieren biopsia urgente'], correct: 3, explanation: 'El reto central es distinguir eficientemente entre observación expectante (la mayoría de los casos, benignos) y biopsia urgente (la minoría con enfermedad grave), sin someter a la mayoría a procedimientos innecesarios ni retrasar el diagnóstico en la minoría grave.', dificultad: 'facil' },
  { q: '¿Qué localización ganglionar amerita biopsia por sí sola, independientemente de los demás criterios de alarma?', options: ['Supraclavicular', 'Cervical anterior', 'Inguinal', 'Axilar'], correct: 0, explanation: 'La localización supraclavicular (ganglio de Virchow/signo de Troisier) tiene un alto valor predictivo de malignidad y amerita biopsia por sí sola, independientemente de los demás criterios.', dificultad: 'facil' },
  { q: '¿Por qué la localización supraclavicular izquierda es especialmente relevante en la evaluación de una linfadenopatía?', options: ['Porque siempre indica una infección viral banal', 'Porque nunca requiere ningún estudio adicional', 'Porque esa cadena ganglionar drena estructuras torácicas y abdominales profundas, señalando con frecuencia malignidad visceral oculta', 'Porque es la localización más frecuente de linfadenopatía reactiva benigna'], correct: 2, explanation: 'El ganglio supraclavicular izquierdo (de Virchow) drena estructuras torácicas y abdominales profundas, por lo que su afectación con frecuencia señala malignidad visceral oculta más que un proceso local benigno.', dificultad: 'intermedio' },
  { q: '¿Cuáles son los criterios de alarma reconocidos para orientar biopsia sobre observación en linfadenopatía?', options: ['Únicamente el color de la piel suprayacente', 'Únicamente la temperatura corporal del paciente', 'Únicamente la presencia de dolor a la palpación', 'Tamaño &gt;2 cm, localización supraclavicular, duración &gt;4-6 semanas, consistencia dura/fija, síntomas B, edad &gt;40 años'], correct: 3, explanation: 'Los criterios de alarma reconocidos son: tamaño &gt;2 cm, localización supraclavicular, duración &gt;4-6 semanas, consistencia dura/fija, síntomas B, y edad &gt;40 años.', dificultad: 'facil' },
  { q: '¿Cuál es el tiempo de observación expectante razonable ante una linfadenopatía sin criterios de alarma?', options: ['24 horas', '4-6 semanas', '2 años', 'No se debe observar nunca, siempre biopsiar de inmediato'], correct: 1, explanation: 'Ante una linfadenopatía sin criterios de alarma, un periodo de observación expectante de 4-6 semanas es razonable antes de considerar biopsia.', dificultad: 'facil' },
  { q: '¿Qué mecanismo explica el agrandamiento ganglionar en la linfadenopatía reactiva/benigna?', options: ['Hiperplasia folicular reactiva: expansión policlonal normal de linfocitos en respuesta a un estímulo antigénico', 'Infiltración por una población celular clonal neoplásica', 'Depósito de amiloide en el parénquima ganglionar', 'Necrosis licuefactiva por isquemia'], correct: 0, explanation: 'La linfadenopatía reactiva se produce por hiperplasia folicular reactiva: una expansión policlonal normal (no clonal ni neoplásica) en respuesta a un estímulo antigénico local.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo clínico es más sugestivo de infiltración neoplásica que de hiperplasia reactiva simple?', options: ['Consistencia blanda, móvil, y dolorosa', 'Aparición reciente asociada a un foco infeccioso local claro', 'Consistencia dura, fija a planos profundos, e indolora', 'Regresión completa en 2 semanas'], correct: 2, explanation: 'Un ganglio duro, fijo a planos profundos e indoloro sugiere infiltración por células neoplásicas que alteran la arquitectura normal y lo adhieren a tejidos circundantes, a diferencia del patrón reactivo típico.', dificultad: 'intermedio' },
  { q: '¿Qué técnica de biopsia se prefiere ante sospecha de linfoma, y por qué?', options: ['Biopsia por aguja fina, porque es menos invasiva y siempre suficiente', 'Ninguna biopsia es necesaria si el paciente tiene síntomas B', 'Solo estudios de imagen, sin ningún tejido', 'Biopsia excisional, porque aporta la arquitectura tisular completa necesaria para la clasificación histológica precisa'], correct: 3, explanation: 'La biopsia excisional se prefiere sobre la aguja fina ante sospecha de linfoma porque aporta la arquitectura tisular completa necesaria para la clasificación histológica precisa, mientras que la aguja fina con frecuencia solo aporta células aisladas insuficientes.', dificultad: 'intermedio' },
  { q: '¿Qué antibiótico se debe evitar empíricamente ante sospecha de mononucleosis infecciosa, y por qué?', options: ['Ampicilina/amoxicilina, por el riesgo de un exantema característico asociado', 'Ácido acetilsalicílico, por riesgo de síndrome de Reye', 'Paracetamol, por hepatotoxicidad', 'Ibuprofeno, por riesgo gastrointestinal'], correct: 0, explanation: 'Ampicilina/amoxicilina deben evitarse empíricamente ante sospecha de mononucleosis infecciosa por el riesgo de un exantema característico asociado a su administración en este contexto.', dificultad: 'intermedio' },
  { q: '¿Qué caracteriza a la linfadenopatía generalizada infecciosa/autoinmune, en contraste con la causada por neoplasia diseminada?', options: ['Consistencia siempre pétrea e indolora en todos los casos', 'Con frecuencia consistencia elástica y manifestaciones sistémicas específicas de una causa identificable (fiebre, faringitis, artralgias)', 'Ausencia total de cualquier manifestación sistémica', 'Afectación exclusiva de una sola región ganglionar'], correct: 1, explanation: 'La linfadenopatía generalizada infecciosa/autoinmune con frecuencia tiene consistencia elástica y se acompaña de manifestaciones sistémicas específicas de la causa identificable, a diferencia del patrón más duro/fijo de la neoplasia diseminada.', dificultad: 'intermedio' },
  { q: '¿Qué marcadores de laboratorio, aunque inespecíficos, apoyan la sospecha de una neoplasia hematológica de alta proliferación como causa de linfadenopatía?', options: ['Colesterol y triglicéridos elevados', 'Creatinina y urea normales', 'LDH y ácido úrico elevados', 'Bilirrubina directa normal'], correct: 2, explanation: 'LDH y ácido úrico elevados son marcadores indirectos de alto recambio celular, frecuentes en neoplasias hematológicas de alta proliferación, aunque no son diagnósticos por sí solos.', dificultad: 'intermedio' },
  { q: '¿Por qué el retraso diagnóstico de malignidad se considera una complicación del proceso diagnóstico y no una entidad biológica?', options: ['Porque refleja una falla en la decisión clínica (observación/antibióticos prolongados) más que un mecanismo de enfermedad propio', 'Porque siempre ocurre por un error de laboratorio', 'Porque es exclusivo de la linfadenopatía reactiva benigna', 'Porque no tiene ninguna consecuencia clínica real'], correct: 0, explanation: 'El retraso diagnóstico refleja una falla del proceso de decisión clínica (favorecer manejo conservador más allá de lo apropiado) más que un mecanismo biológico de enfermedad, por eso se aborda como complicación del proceso.', dificultad: 'dificil' },
  { q: '¿Cuál es la medida más eficaz para prevenir el retraso diagnóstico de malignidad en la evaluación de linfadenopatía?', options: ['Confiar únicamente en la impresión clínica subjetiva sin ningún checklist', 'Indicar antibióticos empíricos repetidos indefinidamente sin reevaluación', 'Evitar cualquier biopsia siempre que sea posible', 'Aplicación sistemática de los criterios de alarma en cada evaluación, con una fecha explícita de reevaluación'], correct: 3, explanation: 'La aplicación sistemática y documentada de los criterios de alarma, con una fecha explícita de reevaluación, es la medida más eficaz para prevenir el retraso diagnóstico de malignidad.', dificultad: 'intermedio' },
  { q: '¿Qué complicación se produce por compresión, invasión, o trombosis de la vena cava superior secundaria a una adenopatía mediastínica voluminosa?', options: ['Síndrome de lisis tumoral', 'Síndrome de vena cava superior', 'Síndrome de secreción inadecuada de hormona antidiurética', 'Síndrome nefrótico'], correct: 1, explanation: 'El síndrome de vena cava superior se produce por compresión, invasión, o trombosis de la vena cava superior secundaria a una masa ganglionar mediastínica voluminosa.', dificultad: 'facil' },
  { q: '¿Por qué la vena cava superior es particularmente vulnerable a la compresión por una masa mediastínica?', options: ['Tiene la pared más gruesa de todo el sistema venoso', 'Está completamente fuera del mediastino', 'Es una estructura de pared delgada y baja presión rodeada de estructuras rígidas dentro del mediastino', 'Nunca está en contacto con estructuras ganglionares'], correct: 2, explanation: 'La vena cava superior es una estructura de pared delgada y baja presión rodeada de estructuras rígidas (esternón, tráquea, bronquio principal derecho, arteria pulmonar), lo que la hace particularmente vulnerable a la compresión externa.', dificultad: 'intermedio' },
  { q: '¿Por qué se recomienda obtener el diagnóstico tisular antes de administrar corticoides ante sospecha de linfoma con síndrome de vena cava superior, cuando es clínicamente seguro hacerlo?', options: ['Los corticoides pueden alterar la histología del linfoma si se administran antes de la biopsia', 'Los corticoides son tóxicos para el equipo de biopsia', 'No hay ninguna razón real para este orden', 'Los corticoides siempre curan el linfoma sin necesidad de biopsia'], correct: 0, explanation: 'Los corticoides pueden alterar la histología de un linfoma, por lo que debe obtenerse el diagnóstico tisular antes de administrarlos cuando sea clínicamente seguro hacerlo.', dificultad: 'dificil' },
  { q: '¿Qué procedimiento intervencionista alivia rápidamente los síntomas del síndrome de vena cava superior en casos graves?', options: ['Trasplante de médula ósea urgente', 'Esplenectomía', 'Diálisis peritoneal', 'Colocación de una endoprótesis (stent) intravascular en la vena cava superior'], correct: 3, explanation: 'La colocación de una endoprótesis (stent) intravascular en la vena cava superior alivia rápidamente los síntomas en casos graves de síndrome de vena cava superior.', dificultad: 'intermedio' },
  { q: '¿Qué distingue a la linfadenitis supurativa de la linfadenopatía reactiva simple?', options: ['La linfadenitis supurativa nunca produce dolor', 'La presencia de signos inflamatorios agudos marcados (eritema, calor, fluctuación) por infección bacteriana con formación de absceso', 'La linfadenopatía reactiva siempre requiere drenaje quirúrgico', 'No existe ninguna diferencia clínica entre ambas'], correct: 1, explanation: 'La linfadenitis supurativa se distingue por signos inflamatorios agudos marcados (eritema, calor, fluctuación) por infección bacteriana con formación de absceso, a diferencia de la hiperplasia reactiva simple.', dificultad: 'facil' },
  { q: '¿Cuáles son los patógenos más frecuentemente implicados en la linfadenitis supurativa?', options: ['Staphylococcus aureus y Streptococcus del grupo A', 'Mycobacterium tuberculosis exclusivamente', 'Virus de Epstein-Barr exclusivamente', 'Candida albicans exclusivamente'], correct: 0, explanation: 'Staphylococcus aureus y Streptococcus del grupo A son los patógenos más frecuentemente implicados en la linfadenitis supurativa bacteriana aguda.', dificultad: 'intermedio' },
  { q: '¿Cuándo está indicado el drenaje quirúrgico o guiado por imagen en la linfadenitis supurativa?', options: ['Nunca, los antibióticos solos siempre son suficientes', 'Inmediatamente en todos los casos, incluso sin fluctuación', 'Ante fluctuación clínica clara o colección confirmada que no responde a antibióticos solos en 48-72 horas', 'Solo si el paciente lo solicita explícitamente'], correct: 2, explanation: 'El drenaje está indicado ante fluctuación clínica clara o colección confirmada por imagen que no responde adecuadamente a los antibióticos solos en 48-72 horas.', dificultad: 'intermedio' },
  { q: '¿Qué estudio de imagen es de primera línea para caracterizar una adenopatía superficial?', options: ['Resonancia magnética cerebral', 'Radiografía simple de tórax exclusivamente', 'Densitometría ósea', 'Ecografía de la región ganglionar afectada'], correct: 3, explanation: 'La ecografía de la región ganglionar afectada es el estudio de primera línea para caracterizar adenopatías superficiales, distinguiendo rasgos benignos de sospechosos.', dificultad: 'facil' },
  { q: '¿Qué hallazgo ecográfico se asocia a características sospechosas de malignidad en un ganglio linfático?', options: ['Forma ovalada con hilio graso conservado', 'Forma redondeada con pérdida del hilio graso e hipervascularización periférica', 'Tamaño menor de 1 cm en cualquier localización', 'Ausencia completa de flujo vascular detectable'], correct: 1, explanation: 'La forma redondeada, la pérdida del hilio graso conservado, y la hipervascularización periférica son hallazgos ecográficos asociados a características sospechosas de malignidad.', dificultad: 'dificil' },
  { q: '¿Qué hallazgo obliga a descartar patología mamaria en una mujer con linfadenopatía?', options: ['Adenopatía cervical bilateral', 'Adenopatía inguinal bilateral', 'Adenopatía axilar unilateral', 'Adenopatía epitroclear bilateral'], correct: 2, explanation: 'La adenopatía axilar unilateral obliga a descartar patología mamaria como causa, dado el territorio de drenaje linfático de la mama.', dificultad: 'intermedio' },
  { q: '¿Qué estudio de estadiaje se recomienda una vez confirmado histológicamente el diagnóstico de una neoplasia con linfadenopatía diseminada?', options: ['PET-TC de cuerpo completo', 'Radiografía simple de tórax aislada', 'Electrocardiograma', 'Ecografía abdominal exclusivamente'], correct: 0, explanation: 'El PET-TC de cuerpo completo se recomienda para mapear la extensión de la enfermedad y orientar el estadiaje una vez confirmado el diagnóstico histológico.', dificultad: 'facil' },
  { q: '¿Qué estudio se considera si hay sospecha de infiltración medular concomitante en un paciente con linfadenopatía por neoplasia diseminada?', options: ['Biopsia hepática', 'Biopsia renal', 'Biopsia de piel', 'Aspirado/biopsia de médula ósea'], correct: 3, explanation: 'El aspirado/biopsia de médula ósea se considera si hay sospecha de infiltración medular concomitante (leucemia, linfoma con afectación medular).', dificultad: 'intermedio' },
  { q: '¿Cuál es una complicación reconocida de la biopsia ganglionar cervical posterior o axilar?', options: ['Perforación intestinal', 'Lesión de estructuras nerviosas relevantes (nervio espinal accesorio, plexo braquial)', 'Neumotórax bilateral obligatorio', 'Insuficiencia renal aguda directa'], correct: 1, explanation: 'La biopsia de ganglios cervicales posteriores o axilares tiene riesgo de lesión de estructuras nerviosas relevantes cercanas, como el nervio espinal accesorio o el plexo braquial.', dificultad: 'intermedio' },
  { q: '¿Qué significa un resultado de biopsia "no concluyente" y qué se debe hacer?', options: ['Que el material obtenido no permite establecer un diagnóstico definitivo, y con frecuencia se debe repetir con técnica excisional', 'Que el diagnóstico es definitivamente benigno y no requiere más estudio', 'Que el paciente debe someterse a quimioterapia empírica de inmediato', 'Que el ganglio debe extirparse por completo sin ningún estudio adicional'], correct: 0, explanation: 'Un resultado no concluyente significa que el material obtenido no permite establecer diagnóstico definitivo, y con frecuencia se debe repetir la biopsia, preferentemente con técnica excisional si la primera fue por aguja fina.', dificultad: 'intermedio' },
  { q: '¿Cuál es el umbral de tamaño ganglionar generalmente considerado como criterio de alarma en la mayoría de las cadenas?', options: ['Mayor de 0.2 cm', 'Mayor de 10 cm exclusivamente', 'Mayor de 2 cm', 'No existe ningún umbral de tamaño relevante'], correct: 2, explanation: 'Un tamaño mayor de 2 cm es uno de los criterios de alarma reconocidos para orientar la biopsia sobre la observación expectante.', dificultad: 'facil' },
  { q: '¿Por qué aplicar un único punto de corte de tamaño a todas las cadenas ganglionares puede ser engañoso?', options: ['Porque todas las cadenas ganglionares tienen exactamente el mismo tamaño normal', 'Porque el umbral de "normalidad" varía por región anatómica (por ejemplo, la cadena inguinal tolera fisiológicamente un tamaño mayor)', 'Porque el tamaño ganglionar nunca es relevante clínicamente', 'Porque solo la cadena cervical tiene ganglios palpables'], correct: 1, explanation: 'El umbral de tamaño normal varía por región anatómica; por ejemplo, la cadena inguinal tolera fisiológicamente un tamaño algo mayor que la cervical o axilar, por lo que aplicar un único punto de corte a todas las cadenas puede sobreestimar o subestimar el riesgo.', dificultad: 'dificil' },
  {
    type: 'cascade', dificultad: 'facil',
    vignette: 'Varón de 22 años presenta un ganglio cervical anterior de 1.5 cm, blando, móvil, doloroso a la palpación, aparecido hace 4 días junto con odinofagia y fiebre.',
    steps: [
      { q: '¿Cuál es la sospecha diagnóstica inicial más probable?', options: ['Linfoma de Hodgkin', 'Metástasis de un primario oculto', 'Linfadenopatía reactiva/benigna secundaria a faringitis', 'Amiloidosis sistémica'], correct: 2, explanation: 'Un ganglio pequeño, blando, doloroso, de aparición reciente, asociado a un foco infeccioso local (faringitis) es característico de linfadenopatía reactiva/benigna.' },
      { q: 'Al calcular los criterios de alarma, ¿cuántos están presentes en este caso?', options: ['Ninguno: no cumple ninguno de los 6 criterios de alarma', 'Los 6 criterios están presentes', 'Solo el criterio de edad', 'Solo el criterio de localización supraclavicular'], correct: 0, explanation: 'El tamaño es &lt;2 cm, la localización no es supraclavicular, la duración es de días (no &gt;4-6 semanas), la consistencia es blanda y dolorosa (no dura/fija), no hay síntomas B descritos, y la edad es &lt;40 años: ningún criterio de alarma está presente.' },
      { q: '¿Cuál es el manejo apropiado en este momento?', options: ['Biopsia excisional urgente inmediata', 'Quimioterapia empírica', 'PET-TC de cuerpo completo inmediato', 'Tratar el foco infeccioso y observar; se espera regresión en 2-4 semanas'], correct: 3, explanation: 'Sin criterios de alarma presentes, el manejo apropiado es tratar el foco infeccioso identificado y observar, esperando regresión en 2-4 semanas.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 55 años presenta un ganglio supraclavicular izquierdo de 1.2 cm, duro, indoloro, descubierto incidentalmente hace 2 semanas. No refiere síntomas B ni foco infeccioso identificable.',
    steps: [
      { q: '¿Qué implica la localización de este ganglio, independientemente de su tamaño relativamente pequeño?', options: ['Ninguna implicación especial, dado que mide menos de 2 cm', 'La localización supraclavicular por sí sola ya justifica biopsia, dado su alto valor predictivo de malignidad', 'Descarta automáticamente cualquier neoplasia', 'Solo es relevante si el ganglio fuera del lado derecho'], correct: 1, explanation: 'La localización supraclavicular por sí sola justifica biopsia, independientemente del tamaño, dado su alto valor predictivo de malignidad visceral oculta (particularmente el lado izquierdo, ganglio de Virchow).' },
      { q: '¿Qué técnica de biopsia es preferible en este caso?', options: ['Biopsia por aguja fina exclusivamente', 'Ninguna biopsia, solo observación', 'Biopsia excisional, para obtener arquitectura tisular completa', 'Biopsia de médula ósea en lugar del ganglio'], correct: 2, explanation: 'La biopsia excisional es preferible para obtener la arquitectura tisular completa necesaria para un diagnóstico histológico preciso, particularmente ante sospecha de malignidad.' },
      { q: 'Si la biopsia confirma metástasis ganglionar de adenocarcinoma, ¿cuál es el siguiente paso apropiado?', options: ['Estudio de imagen dirigido (TC/PET-TC) para localizar el primario torácico o abdominal probable', 'No se requiere ningún estudio adicional', 'Repetir la misma biopsia sin cambios', 'Iniciar tratamiento sin ninguna caracterización adicional'], correct: 0, explanation: 'Ante metástasis ganglionar confirmada en un ganglio supraclavicular, el siguiente paso es un estudio de imagen dirigido para localizar el primario torácico o abdominal probable, dado el territorio de drenaje de esa cadena.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 45 años con linfoma conocido presenta edema facial y de cuello progresivo de 5 días, más notorio al despertar, con distensión de las venas del cuello y la pared torácica anterior. Refiere disnea leve.',
    steps: [
      { q: '¿Qué complicación se debe sospechar de inmediato?', options: ['Síndrome de lisis tumoral', 'Neumonía adquirida en la comunidad', 'Trombosis venosa profunda aislada de miembro inferior', 'Síndrome de vena cava superior'], correct: 3, explanation: 'El edema facial/cervical progresivo con distensión venosa cervical y torácica en un paciente con linfoma conocido es característico del síndrome de vena cava superior.' },
      { q: '¿Cuál es el estudio de elección urgente para confirmar y caracterizar la causa?', options: ['Radiografía simple de tórax aislada', 'TC de tórax con contraste', 'Ecografía Doppler de miembros inferiores', 'Electrocardiograma'], correct: 1, explanation: 'La TC de tórax con contraste es el estudio de elección urgente, que confirma la obstrucción de la vena cava superior y caracteriza la masa causal.' },
      { q: 'El paciente no tiene compromiso respiratorio ni neurológico grave. ¿Cuál es la conducta apropiada respecto a los corticoides?', options: ['Obtener el diagnóstico tisular (o confirmar el ya conocido) antes de administrar corticoides, dado que es clínicamente seguro esperar', 'Administrar corticoides en dosis altas de inmediato sin ninguna otra consideración', 'Nunca administrar corticoides en este contexto bajo ninguna circunstancia', 'Administrar quimioterapia empírica sin biopsia'], correct: 0, explanation: 'Cuando es clínicamente seguro esperar (sin compromiso respiratorio/neurológico grave), se prefiere confirmar el diagnóstico tisular antes de administrar corticoides, que pueden alterar la histología si se dan antes de la biopsia.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Niño de 6 años presenta un ganglio cervical derecho de crecimiento rápido en 3 días, marcadamente doloroso, con eritema y calor de la piel suprayacente, fluctuante a la palpación, y fiebre de 38.5°C.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable?', options: ['Linfadenopatía reactiva simple', 'Linfoma de Hodgkin', 'Linfadenitis supurativa', 'MGUS'], correct: 2, explanation: 'El crecimiento rápido, el dolor marcado, los signos inflamatorios agudos (eritema, calor), la fluctuación, y la fiebre son característicos de linfadenitis supurativa con formación de absceso.' },
      { q: '¿Cuál es el manejo inicial apropiado?', options: ['Biopsia excisional inmediata sin antibióticos', 'Observación sin ningún tratamiento', 'Quimioterapia empírica', 'Antibióticos empíricos con cobertura antiestafilocócica/antiestreptocócica'], correct: 3, explanation: 'El manejo inicial de la linfadenitis supurativa es antibióticos empíricos con cobertura para Staphylococcus aureus y Streptococcus del grupo A, los patógenos más frecuentemente implicados.' },
      { q: 'A las 72 horas, el ganglio persiste fluctuante sin mejoría clínica. ¿Cuál es el siguiente paso?', options: ['Continuar el mismo esquema antibiótico indefinidamente sin cambios', 'Drenaje quirúrgico o guiado por imagen, con cultivo del material obtenido', 'Suspender todo tratamiento y solo observar', 'Iniciar quimioterapia sistémica'], correct: 1, explanation: 'Ante fluctuación persistente sin respuesta adecuada a los antibióticos solos en 48-72 horas, está indicado el drenaje quirúrgico o guiado por imagen, con cultivo dirigido del material obtenido.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 48 años presenta un ganglio axilar de 2.5 cm, duro, de crecimiento progresivo documentado durante 8 semanas, sin dolor. En una primera consulta hace 6 semanas se indicó un ciclo de antibióticos sin foco infeccioso identificado, sin mejoría.',
    steps: [
      { q: 'Al revisar el caso, ¿qué se identifica como el problema principal en el manejo hasta este punto?', options: ['Retraso diagnóstico: se indicaron antibióticos empíricos sin foco infeccioso claro pese a criterios de alarma ya presentes (tamaño, duración, consistencia)', 'Ningún problema, el manejo fue completamente apropiado', 'El paciente debió haber recibido quimioterapia desde la primera consulta', 'El ganglio debió haberse ignorado por completo'], correct: 0, explanation: 'El caso ilustra un retraso diagnóstico: ya en la primera consulta había criterios de alarma presentes (tamaño &gt;2cm, consistencia dura, crecimiento progresivo), y se optó por antibióticos empíricos sin foco infeccioso identificado en lugar de proceder a biopsia.' },
      { q: '¿Cuál es la conducta apropiada en este momento, dado que ya han pasado 8 semanas con progresión?', options: ['Indicar un segundo ciclo de antibióticos empíricos', 'Continuar observando otras 6 semanas más', 'Solicitar únicamente una radiografía simple de tórax', 'Biopsia excisional sin demora adicional'], correct: 3, explanation: 'Dado el crecimiento progresivo documentado durante 8 semanas y los criterios de alarma ya presentes desde el inicio, la conducta apropiada es proceder a biopsia excisional sin demora adicional.' },
      { q: '¿Qué medida sistemática habría prevenido este retraso desde la primera consulta?', options: ['Confiar únicamente en la impresión clínica subjetiva sin ningún checklist', 'Evitar cualquier biopsia de forma sistemática', 'Aplicación explícita y documentada de los criterios de alarma con una fecha programada de reevaluación', 'No es posible prevenir este tipo de retraso'], correct: 2, explanation: 'La aplicación explícita y documentada de los criterios de alarma, junto con una fecha programada de reevaluación (en lugar de dejarlo a la iniciativa del paciente), es la medida sistemática que habría prevenido este retraso diagnóstico.' }
    ]
  }
];

export const flashcards = [
  { front: 'Linfadenopatía localizada vs. generalizada', back: 'Localizada: 1 sola región. Generalizada: ≥2 regiones ganglionares no contiguas.' },
  { front: 'Criterios de alarma para biopsia (6)', back: 'Tamaño &gt;2 cm, localización supraclavicular, duración &gt;4-6 semanas, consistencia dura/fija, síntomas B, edad &gt;40 años.' },
  { front: 'Ganglio de Virchow / signo de Troisier', back: 'Ganglio supraclavicular izquierdo; drena estructuras torácicas/abdominales profundas, con frecuencia señala malignidad visceral oculta. Justifica biopsia por sí solo.' },
  { front: 'Tiempo de observación expectante razonable', back: '4-6 semanas ante linfadenopatía sin criterios de alarma.' },
  { front: 'Mecanismo de la linfadenopatía reactiva', back: 'Hiperplasia folicular reactiva: expansión policlonal normal en respuesta a un estímulo antigénico local.' },
  { front: 'Hallazgo clínico sugestivo de infiltración neoplásica', back: 'Ganglio duro, fijo a planos profundos, indoloro (a diferencia del patrón reactivo blando/móvil/doloroso).' },
  { front: 'Biopsia excisional vs. aguja fina ante sospecha de linfoma', back: 'Excisional preferida: aporta arquitectura tisular completa necesaria para clasificación histológica precisa.' },
  { front: 'Antibiótico a evitar ante sospecha de mononucleosis', back: 'Ampicilina/amoxicilina, por riesgo de exantema característico asociado.' },
  { front: 'Marcadores de alto recambio celular en linfadenopatía', back: 'LDH y ácido úrico elevados, sugieren neoplasia hematológica de alta proliferación (inespecíficos).' },
  { front: 'Adenopatía axilar unilateral en mujer', back: 'Obliga a descartar patología mamaria.' },
  { front: 'Hallazgo ecográfico sospechoso de malignidad ganglionar', back: 'Forma redondeada, pérdida del hilio graso, hipervascularización periférica.' },
  { front: 'Síndrome de vena cava superior: mecanismo', back: 'Compresión/invasión/trombosis de la VCS por masa ganglionar mediastínica voluminosa; pared delgada rodeada de estructuras rígidas del mediastino.' },
  { front: 'Síndrome de vena cava superior: por qué esperar biopsia antes de corticoides', back: 'Los corticoides pueden alterar la histología del linfoma si se dan antes de la biopsia (cuando es clínicamente seguro esperar).' },
  { front: 'Síndrome de vena cava superior: alivio rápido en casos graves', back: 'Endoprótesis (stent) intravascular en la vena cava superior.' },
  { front: 'Linfadenitis supurativa: patógenos frecuentes', back: 'Staphylococcus aureus y Streptococcus del grupo A.' },
  { front: 'Linfadenitis supurativa: indicación de drenaje', back: 'Fluctuación clínica clara o colección confirmada sin respuesta a antibióticos solos en 48-72 horas.' },
  { front: 'Complicación nerviosa de biopsia ganglionar cervical/axilar', back: 'Lesión del nervio espinal accesorio (cervical posterior) o del plexo braquial (axilar).' },
  { front: 'Resultado de biopsia no concluyente: siguiente paso', back: 'Repetir, preferentemente con técnica excisional si la primera fue por aguja fina.' },
  { front: 'Retraso diagnóstico de malignidad: causa principal', back: 'Antibióticos empíricos repetidos u observación prolongada sin foco infeccioso claro, pese a criterios de alarma ya presentes.' },
  { front: 'Retraso diagnóstico: medida de prevención', back: 'Aplicación sistemática de criterios de alarma con fecha explícita de reevaluación programada.' },
  { front: 'Estudio de imagen de primera línea para adenopatía superficial', back: 'Ecografía de la región ganglionar afectada.' },
  { front: 'Estudio de estadiaje tras confirmación histológica de neoplasia diseminada', back: 'PET-TC de cuerpo completo.' },
  { front: 'Umbral de tamaño ganglionar normal: variabilidad por región', back: 'Varía por región (inguinal tolera fisiológicamente más tamaño que cervical/axilar); cualquier ganglio supraclavicular palpable es anómalo.' },
  { front: 'Adenopatía inguinal aislada: interpretación', back: 'Con frecuencia reactiva a procesos de miembros inferiores o infecciones de transmisión sexual locales.' },
  { front: 'Estudio ante sospecha de infiltración medular concomitante', back: 'Aspirado/biopsia de médula ósea.' },
  { front: 'Linfadenopatía generalizada infecciosa/autoinmune: causas frecuentes', back: 'VIH, mononucleosis infecciosa (VEB), citomegalovirus, tuberculosis, lupus eritematoso sistémico.' },
  { front: 'Linfadenopatía generalizada por neoplasia diseminada: causas', back: 'Leucemia, linfoma en estadio avanzado, metástasis ganglionares diseminadas de un primario sólido.' },
  { front: 'Definición de linfadenopatía "de alto riesgo"', back: '1 región con 1 o más criterios de alarma presentes: orienta biopsia sobre observación.' },
  { front: 'Fisiopatología de la linfadenitis supurativa', back: 'Infección bacteriana con necrosis licuefactiva y formación de colección purulenta franca dentro del ganglio.' },
  { front: 'Consideración perioperatoria antes de biopsia ganglionar', back: 'Evaluar coagulación previa en el paciente con factores de riesgo hemorrágico conocidos.' }
];
