// topics/soporte-vital-avanzado/study.js: Autoevaluacion de soporte vital avanzado y RCP.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
// Fuente: Parte 9 de las guias de la American Heart Association de 2025 (Wigginton JG, et al.
// Circulation 2025;152(suppl 2):S538-S577). 30 sueltas + 6 cascadas de 3 = 48 subpreguntas,
// 32 tarjetas.

export const quiz = [
  { q:'&#191;Cual es la supervivencia al alta tras una parada cardiaca EXTRAhospitalaria atendida?', options:['En torno al 30% de los casos', 'Cerca de la mitad de los casos', 'Alrededor del 10% de los casos', 'Menos de uno de cada cien'], correct:2, explanation:'La incidencia atendida por los servicios de emergencia es de 83.4 casos por cada 100.000 habitantes y a&#241;o, y la supervivencia al alta ronda el 10%. Es una cifra baja que conviene tener presente al hablar con las familias.', dificultad:'facil' },
  { q:'&#191;Y cual es la supervivencia al alta tras una parada INTRAhospitalaria?', options:['Alrededor del 24% de los casos', 'En torno al 60% de los casos', 'Alrededor del 5% de los casos', 'Cerca del 40% de los casos'], correct:0, explanation:'Ocurre en aproximadamente 1 de cada 100 ingresados. Se recupera circulacion en el 72.2% y sobrevive al alta el 24.2%. El pronostico es bastante mejor que fuera del hospital.', dificultad:'facil' },
  { q:'De los que sobreviven a una parada intrahospitalaria, &#191;que proporcion lo hace con buen resultado neurologico?', options:['En torno al 30% de ellos', 'Alrededor del 55% de ellos', 'Menos del 10% de ellos', 'Cerca del 85% de ellos'], correct:3, explanation:'Alrededor del 85% de los supervivientes tiene un resultado neurologico favorable. Es un dato que contrapesa la idea extendida de que sobrevivir a una parada suele significar quedar con da&#241;o grave.', dificultad:'intermedio' },
  { q:'&#191;Que coloca la edicion de 2025 por delante del algoritmo?', options:['La eleccion del antiarritmico de segunda linea', 'La valoracion de la estabilidad clinica', 'El acceso intraoseo lo antes posible', 'La via aerea avanzada desde el inicio'], correct:1, explanation:'El primero de los mensajes principales de la guia es que la valoracion rapida de la estabilidad clinica es esencial, y esta edicion desarrolla mucho mas como se manifiesta la mala perfusion de organo.', dificultad:'facil' },
  { q:'Segun la guia de 2025, &#191;como se reconoce mejor la inestabilidad?', options:['Por las manifestaciones de mala perfusion de organo', 'Por una tension sistolica por debajo de 90 mmHg', 'Por una frecuencia cardiaca mayor de 150 lpm', 'Por el valor del lactato arterial inicial'], correct:0, explanation:'Lo que define la inestabilidad no es un numero sino como se manifiesta la mala perfusion: alteracion del estado mental, piel fria y moteada, oliguria, dolor toracico isquemico, disnea con congestion e hipotension.', dificultad:'intermedio' },
  { q:'Una arritmia en un paciente inestable, &#191;que puede ser?', options:['Solo la causa del cuadro clinico', 'Causa o manifestacion de la inestabilidad', 'Un hallazgo casual sin relacion', 'Un dato sin ningun valor pronostico'], correct:1, explanation:'La guia lo se&#241;ala de forma expresa. Distinguirlo cambia la conducta: si la arritmia es la causa, se trata la arritmia; si es consecuencia de una sepsis o una hemorragia, tratar solo la arritmia no resuelve nada.', dificultad:'intermedio' },
  { q:'&#191;Cual es el tratamiento de una taquicardia ventricular POLIMORFA?', options:['Cardioversion sincronizada a 100 J', 'Amiodarona en bolo lento', 'Desfibrilacion inmediata', 'Adenosina en bolo rapido'], correct:2, explanation:'La guia de 2025 la considera siempre inestable y pide tratarla de inmediato con desfibrilacion. El retraso en administrar la descarga empeora el resultado.', dificultad:'facil' },
  { q:'&#191;Por que la polimorfa se desfibrila en lugar de cardiovertirse?', options:['Porque responde peor a la energia baja', 'Porque el paciente suele estar estable', 'Porque de ese modo se evita la sedacion', 'Porque se considera siempre inestable'], correct:3, explanation:'Es una de las excepciones que conviene tener grabadas: la polimorfa se trata como inestable en todos los casos. Ademas, el sincronizador puede no capturar un QRS tan irregular.', dificultad:'intermedio' },
  { q:'En la cardioversion de una fibrilacion auricular, &#191;que energia recomienda la edicion de 2025 para la primera descarga?', options:['Una primera descarga de 200 J o mas', 'Una primera descarga en torno a 50 J', 'Una primera descarga de 70 a 100 J', 'La energia minima que logre capturar'], correct:0, explanation:'Es uno de los cambios de 2025: una primera descarga de mayor energia, de 200 J o mas, es preferible a empezar con energias menores en la cardioversion de la fibrilacion auricular.', dificultad:'intermedio' },
  { q:'&#191;Que dice la edicion de 2025 sobre el flutter auricular?', options:['Se cardiovierte con la energia minima eficaz', 'La primera descarga tambien de 200 J o mas', 'Ya no se cardiovierte, se frena la respuesta', 'Se prefiere la descarga no sincronizada'], correct:1, explanation:'La recomendacion de energia mas alta en la primera descarga se aplica tanto a la fibrilacion auricular como al flutter. Sigue siendo una cardioversion sincronizada.', dificultad:'dificil' },
  { q:'&#191;Cuando se administra la adrenalina en un ritmo NO desfibrilable?', options:['Tras el segundo ciclo de compresiones', 'Despues de la primera descarga', 'Al fracasar el antiarritmico', 'Cuanto antes sea posible'], correct:3, explanation:'En el ritmo no desfibrilable es razonable administrarla tan pronto como sea factible. No hay descarga que dar, de modo que nada justifica esperar.', dificultad:'facil' },
  { q:'&#191;Y cuando se administra en un ritmo desfibrilable?', options:['Tras los intentos iniciales de desfibrilacion', 'Antes de administrar la primera descarga del episodio', 'A los diez minutos de reanimacion avanzada', 'Junto con el primer bolo de antiarritmico'], correct:0, explanation:'En el ritmo desfibrilable es razonable administrarla despues de los intentos iniciales de desfibrilacion. La diferencia con el otro ritmo se olvida a menudo.', dificultad:'intermedio' },
  { q:'&#191;Por que se retrasa la adrenalina en el ritmo desfibrilable?', options:['Porque es menos eficaz cuando hay fibrilacion', 'Porque en ese ritmo hay menos acidosis tisular', 'Porque ahi lo decisivo es la descarga, no el farmaco', 'Porque interfiere con el sensor del desfibrilador'], correct:2, explanation:'Lo que reinicia el corazon en la fibrilacion ventricular es la desfibrilacion, y la adrenalina no debe retrasarla. En el ritmo no desfibrilable no existe esa alternativa, y por eso se da cuanto antes.', dificultad:'dificil' },
  { q:'&#191;Cual es la dosis y el intervalo de la adrenalina en la parada?', options:['0.5 mg cada diez minutos', '1 mg cada 3 a 5 minutos', '3 mg en dosis unica inicial', '1 mg cada minuto sin techo'], correct:1, explanation:'Un miligramo cada 3 a 5 minutos. Conviene asignar a alguien el control del tiempo, porque el retraso entre dosis es uno de los fallos mas frecuentes en la reanimacion real.', dificultad:'facil' },
  { q:'Segun la edicion de 2025, &#191;cual es la via de PRIMERA eleccion para los farmacos?', options:['La intraosea, por su rapidez de colocacion', 'La endotraqueal cuando ya hay tubo puesto', 'La intravenosa, como en ediciones previas', 'La intracardiaca en la asistolia refractaria'], correct:2, explanation:'La guia mantiene el acceso intravenoso como primera eleccion. Es el orden inverso al que mucha gente ha interiorizado en los ultimos a&#241;os.', dificultad:'intermedio' },
  { q:'&#191;Que lugar ocupa entonces el acceso intraoseo?', options:['Es la via preferida desde la edicion de 2025', 'Esta desaconsejado en el paciente adulto', 'Se reserva para el paciente pediatrico', 'Es la alternativa si el intravenoso no es viable'], correct:3, explanation:'Es una alternativa razonable cuando el acceso intravenoso no es viable o se retrasa. Alternativa razonable, no primera opcion.', dificultad:'intermedio' },
  { q:'&#191;Que ha hecho la guia de 2025 con la administracion de farmacos por el tubo endotraqueal?', options:['Ha retirado la recomendacion por obsoleta', 'La ha elevado a primera alternativa de rescate', 'La mantiene vigente para la adrenalina', 'La reserva a la lidocaina en bolo'], correct:0, explanation:'Es uno de los procedimientos obsoletos cuyas recomendaciones se han eliminado por disponer de equivalentes modernos mas eficaces. No es una via de rescate.', dificultad:'dificil' },
  { q:'&#191;Que dice la guia sobre la reanimacion con la cabeza elevada?', options:['Se recomienda si se dispone del dispositivo', 'Es de eleccion en el paciente con obesidad', 'Se desaconseja fuera de ensayos clinicos', 'Mejora de forma clara la perfusion cerebral'], correct:2, explanation:'La guia la desaconseja fuera de ensayos clinicos rigurosos con las protecciones adecuadas. Es una tecnica que se ha difundido mas deprisa que su evidencia.', dificultad:'intermedio' },
  { q:'&#191;Y sobre el cambio de vector y la desfibrilacion secuencial doble?', options:['Se recomiendan a partir de la tercera descarga', 'Su utilidad no esta establecida', 'Estan formalmente contraindicadas', 'Sustituyen a la amiodarona en la refractaria'], correct:1, explanation:'La guia concluye que su utilidad no esta establecida en la fibrilacion ventricular refractaria, y que merecen mas investigacion. Ni recomendadas ni prohibidas.', dificultad:'dificil' },
  { q:'&#191;Que antiarritmicos pueden considerarse si la fibrilacion ventricular no responde a la descarga?', options:['Procainamida o sotalol', 'Sotalol o bretilio', 'Un betabloqueante intravenoso', 'Amiodarona o lidocaina'], correct:3, explanation:'Pueden considerarse amiodarona o lidocaina en la fibrilacion ventricular o la taquicardia ventricular sin pulso que no responde a la desfibrilacion. Es una recomendacion debil.', dificultad:'intermedio' },
  { q:'&#191;Como valora la guia los betabloqueantes, el bretilio, la procainamida y el sotalol en ese contexto?', options:['Que su beneficio es incierto', 'Que son la alternativa recomendada', 'Que estan contraindicados', 'Que se prefieren a la amiodarona'], correct:0, explanation:'La guia los agrupa como de beneficio incierto en la parada por fibrilacion ventricular o taquicardia sin pulso refractaria a la desfibrilacion.', dificultad:'dificil' },
  { q:'&#191;Que dice la guia sobre el calcio de rutina en la parada?', options:['Se recomienda en la actividad electrica sin pulso', 'No se recomienda su administracion sistematica', 'Se administra tras la tercera dosis de adrenalina', 'Sustituye al bicarbonato cuando hay acidosis'], correct:1, explanation:'No se recomienda la administracion sistematica de calcio durante la parada. Eso no impide usarlo ante una indicacion concreta, como una hiperpotasemia conocida.', dificultad:'facil' },
  { q:'&#191;Y que dice sobre el bicarbonato sodico?', options:['Se recomienda si la parada supera los 20 minutos', 'Se administra en toda acidosis documentada', 'Tampoco se recomienda de rutina', 'Es el farmaco de eleccion en la asistolia'], correct:2, explanation:'Tampoco se recomienda su administracion sistematica durante la parada. El mismo criterio se aplica al magnesio.', dificultad:'intermedio' },
  { q:'Que el magnesio no se recomiende de rutina, &#191;que significa?', options:['Que esta contraindicado durante la parada', 'Que se administra ya en la unidad de criticos', 'Que se sustituye por calcio intravenoso', 'Que sigue indicado ante una causa concreta'], correct:3, explanation:'No recomendado de rutina no equivale a prohibido. El magnesio conserva su sitio en la taquicardia ventricular polimorfa con QT largo; lo que se descarta es darlo a ciegas en toda parada.', dificultad:'intermedio' },
  { q:'&#191;Que dice la guia sobre la ecografia a pie de cama durante la parada?', options:['Puede considerarse si no interrumpe la reanimacion', 'Debe hacerla cualquiera de los reanimadores', 'Esta indicada en toda parada cardiaca', 'Se realiza antes de iniciar las compresiones'], correct:0, explanation:'Puede considerarse, realizada por profesionales con experiencia, para diagnosticar causas reversibles, siempre que no interrumpa la reanimacion. Esa condicion es la que mas se incumple.', dificultad:'facil' },
  { q:'&#191;Cuando debe diferirse la colocacion de una via aerea avanzada?', options:['Cuando la intubacion se prevea facil', 'Cuando hay mas de tres reanimadores', 'Cuando el carbonico espirado es alto', 'Cuando vaya a interrumpir las compresiones'], correct:3, explanation:'Si su colocacion va a interrumpir las compresiones, se difiere hasta que el paciente no responda a la reanimacion inicial y a los intentos de desfibrilacion.', dificultad:'intermedio' },
  { q:'&#191;Que recomienda la guia sobre quien intuba durante la parada?', options:['Que la realice el anestesista de guardia del hospital', 'Que tenga experiencia o entrenamiento frecuentes', 'Que se use un dispositivo supraglotico', 'Que se intube antes de la primera descarga'], correct:1, explanation:'La guia recomienda que los profesionales que realizan la intubacion tengan experiencia frecuente o entrenamiento frecuente. La tasa de exito depende mucho de eso.', dificultad:'dificil' },
  { q:'&#191;Que fiabilidad tiene el carbonico espirado medido durante la ventilacion con bolsa y mascarilla?', options:['Es inservible mientras no haya tubo', 'Sobrestima el valor de forma constante', 'Es comparable a la de otros dispositivos', 'Requiere capnografia de onda para valer'], correct:2, explanation:'La guia se&#241;ala que sus valores durante la ventilacion con bolsa y mascarilla son tan fiables como con otros dispositivos, lo que amplia su utilidad a situaciones sin via aerea avanzada.', dificultad:'intermedio' },
  { q:'&#191;Que advierte de forma expresa la guia de 2025 sobre el carbonico espirado?', options:['Que no se use aislado para terminar la reanimacion', 'Que no sirve para confirmar la posicion del tubo', 'Que no se puede medir durante las compresiones', 'Que no guarda relacion con el gasto cardiaco'], correct:0, explanation:'Informa de la calidad de las compresiones, avisa de la recuperacion de la circulacion con una subida brusca y orienta el pronostico, pero no debe usarse de forma aislada para terminar los esfuerzos.', dificultad:'intermedio' },
  { q:'&#191;Que distingue la recuperacion de la circulacion de la recuperacion de la circulacion ESPONTANEA?', options:['El tiempo durante el cual se mantiene el pulso obtenido', 'Que la espontanea se debe a la funcion cardiaca propia', 'El sitio donde se palpa el pulso central del paciente', 'La recuperacion o no del nivel de conciencia'], correct:1, explanation:'La guia de 2025 precisa la terminologia: se habla de recuperacion de la circulacion cuando esta se consigue por medios mecanicos, como una oxigenacion por membrana extracorporea, y de espontanea cuando se debe a la propia funcion cardiaca.', dificultad:'dificil' },

  { type:'cascade', vignette:'Varon de 68 a&#241;os ingresado en planta por un sindrome coronario agudo. Al ir a tomarle las constantes, la enfermera lo encuentra sin respuesta y sin respiracion eficaz. El monitor muestra un trazado caotico, de amplitud gruesa, sin complejos identificables. No se palpa pulso carotideo.', steps:[
    { q:'&#191;Cual es la primera medida?', options:['Colocar un acceso intraoseo', 'Intubar al paciente', 'Desfibrilar de inmediato', 'Administrar adrenalina'], correct:2 },
    { q:'&#191;Cuando corresponde la adrenalina en este caso?', options:['Despues de los intentos iniciales de desfibrilacion', 'Antes incluso de la primera descarga de este episodio', 'Al aparecer una asistolia en el monitor', 'Al colocar la via aerea avanzada definitiva'], correct:0 },
    { q:'Tras tres descargas sin respuesta, &#191;que puede considerarse?', options:['Procainamida intravenosa', 'Bicarbonato sodico en bolo', 'Un betabloqueante intravenoso', 'Amiodarona o lidocaina'], correct:3 }
  ], explanation:'Fibrilacion ventricular en un paciente monitorizado: rama desfibrilable y la descarga es la prioridad absoluta, sin esperar a nada. La adrenalina llega despues de los intentos iniciales de desfibrilacion, 1 mg cada 3 a 5 minutos. Si la fibrilacion persiste, pueden considerarse amiodarona o lidocaina; los demas antiarritmicos son de beneficio incierto en este contexto.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Mujer de 74 a&#241;os ingresada por neumonia. La avisan por parada. Al llegar el equipo, el monitor muestra una linea practicamente plana en la derivacion que esta seleccionada. La paciente no responde y no se palpa pulso.', steps:[
    { q:'&#191;Que conviene comprobar antes de asumir que es una asistolia?', options:['La temperatura central con un termometro timpanico', 'Las derivaciones, la ganancia y otra derivacion', 'La glucemia capilar en el pulpejo del dedo', 'La posicion del tubo con el capnografo'], correct:1 },
    { q:'Confirmada la asistolia, &#191;cuando se administra la adrenalina?', options:['Tras dos ciclos de compresiones', 'Despues de una descarga de prueba', 'Cuanto antes sea posible', 'Al conseguir una via central'], correct:2 },
    { q:'&#191;Que NO se administra de rutina en esta situacion?', options:['La adrenalina intravenosa', 'El oxigeno suplementario', 'El suero salino en carga', 'Calcio, bicarbonato y magnesio'], correct:3 }
  ], explanation:'Una fibrilacion ventricular fina puede aparentar una linea plana, y el tratamiento es el contrario, de modo que antes de asumir asistolia se comprueban derivaciones y ganancia. Confirmada, es rama no desfibrilable: compresiones de calidad, adrenalina cuanto antes y busqueda sistematica de la causa. La guia de 2025 no recomienda la administracion sistematica de calcio, bicarbonato ni magnesio.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 52 a&#241;os traido por un accidente de trafico. Durante la valoracion pierde el pulso. El monitor muestra un ritmo organizado a 40 por minuto. Tiene las yugulares ingurgitadas, hipofonesis en el hemitorax derecho y la traquea desviada a la izquierda.', steps:[
    { q:'&#191;Cual es la causa mas probable de la parada?', options:['Un neumotorax a tension', 'Un taponamiento cardiaco', 'Una hemorragia masiva', 'Una tromboembolia pulmonar'], correct:0 },
    { q:'&#191;Cual es la medida prioritaria?', options:['Administrar adrenalina en bolo', 'Iniciar una transfusion urgente', 'Descomprimir el torax de inmediato', 'Solicitar una tomografia toracica'], correct:2 },
    { q:'&#191;Que papel tiene la ecografia a pie de cama aqui?', options:['Sustituye a la exploracion fisica del paciente', 'Puede ayudar si no interrumpe las compresiones', 'Debe hacerse antes de empezar con las compresiones', 'Carece de utilidad durante la parada'], correct:1 }
  ], explanation:'Actividad electrica sin pulso con ingurgitacion yugular, hipofonesis unilateral y desviacion traqueal: neumotorax a tension, que es una causa reversible y el tratamiento es la descompresion inmediata, no otra dosis de adrenalina. La ecografia puede ayudar a confirmarlo en manos expertas, siempre que no interrumpa la reanimacion.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Mujer de 63 a&#241;os que acude por palpitaciones. Esta consciente pero con mala perfusion periferica, tension de 78/45, sudorosa y con dolor toracico. El electrocardiograma muestra una fibrilacion auricular con respuesta ventricular a 165 por minuto.', steps:[
    { q:'&#191;Cual es la conducta correcta?', options:['Digoxina intravenosa lenta', 'Amiodarona en perfusion', 'Control de frecuencia con betabloqueante', 'Cardioversion sincronizada'], correct:3 },
    { q:'&#191;Que energia se elige para la primera descarga?', options:['En torno a 50 J', '200 J o mas', 'De 70 a 100 J', 'La minima que capture'], correct:1 },
    { q:'Si la arritmia no revierte con esa descarga, &#191;que procede?', options:['Pasar a una descarga no sincronizada', 'Renunciar a la cardioversion y frenar la frecuencia', 'Escalar energia y revisar parches y sedacion', 'Repetir la descarga con la mitad de energia'], correct:2 }
  ], explanation:'Hipotension, mala perfusion y dolor toracico con una fibrilacion auricular rapida: es una arritmia que esta causando la inestabilidad, y la conducta es la cardioversion sincronizada. La edicion de 2025 prefiere una primera descarga de 200 J o mas. Si no revierte, se escala energia y se revisa lo demas: posicion de los parches, contacto, sedacion y si hay una causa de fondo que mantenga la arritmia.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Aviso a un domicilio por una parada cardiaca. Nadie presencio el momento del colapso y no se habia iniciado ninguna maniobra antes de la llegada del equipo. El ritmo es una asistolia desde el primer registro. Tras el tratamiento avanzado completo en el lugar, no se ha administrado ninguna descarga y no se ha recuperado la circulacion en ningun momento.', steps:[
    { q:'&#191;Que regla de terminacion corresponde a este escenario?', options:['La de soporte vital avanzado', 'La de soporte vital basico', 'La regla intrahospitalaria', 'Ninguna, hay que trasladar'], correct:0 },
    { q:'&#191;Se cumplen sus criterios en este caso?', options:['No, falta el criterio del ritmo', 'No, falta el criterio de la edad', 'No, falta el criterio del tiempo', 'Si, se cumplen todos'], correct:3 },
    { q:'&#191;Bastaria un carbonico espirado bajo para decidir parar?', options:['Si, es el criterio definitivo', 'Si, cuando esta por debajo de 10', 'No, no debe usarse de forma aislada', 'No, porque no se mide en el domicilio'], correct:2 }
  ], explanation:'Parada no presenciada por nadie, sin reanimacion por testigos, sin descargas y sin recuperacion de circulacion tras el tratamiento avanzado: se cumplen los criterios de la regla de soporte vital avanzado. La edicion de 2025 insiste en aplicar la regla que corresponde al ambito y al nivel de los intervinientes, y advierte de forma expresa de que el carbonico espirado no debe usarse de forma aislada para terminar los esfuerzos.', dificultad:'dificil' },

  { type:'cascade', vignette:'Varon de 45 a&#241;os monitorizado en urgencias por sincope, con un QT largo conocido. Presenta una taquicardia ventricular polimorfa que degenera y pierde el pulso. Mientras el equipo se organiza, un companero propone intubarlo antes de hacer nada mas. Todavia no hay ningun acceso vascular.', steps:[
    { q:'&#191;Cual es el tratamiento de esa arritmia?', options:['Cardioversion sincronizada', 'Desfibrilacion inmediata', 'Amiodarona en bolo lento', 'Sobreestimulacion con marcapasos'], correct:1 },
    { q:'&#191;Que hacer con la propuesta de intubar primero?', options:['Diferirla si va a interrumpir las compresiones', 'Aceptarla, porque es la prioridad inicial del caso', 'Sustituirla por una via aerea quirurgica', 'Intubar despues de cinco ciclos de compresiones'], correct:0 },
    { q:'&#191;Que acceso vascular se busca primero?', options:['Una via central femoral', 'Un acceso intraoseo humeral', 'Una via central yugular', 'Un acceso intravenoso periferico'], correct:3 }
  ], explanation:'La taquicardia ventricular polimorfa se considera siempre inestable y se desfibrila de inmediato. La via aerea avanzada no es prioritaria: si su colocacion va a interrumpir las compresiones, se difiere hasta que el paciente no responda a la reanimacion inicial y a la desfibrilacion. Y la guia de 2025 mantiene el acceso intravenoso como primera eleccion, con el intraoseo como alternativa razonable si el intravenoso no es viable o se retrasa.', dificultad:'dificil' }
];

export const flashcards = [
  { front:'Mensaje que la guia de 2025 pone en primer lugar', back:'La valoracion rapida de la ESTABILIDAD clinica es esencial. Esta edicion desarrolla mucho mas como se manifiesta la mala perfusion de organo.' },
  { front:'Como se reconoce la inestabilidad', back:'Por la PERFUSION de organo, no por un numero: estado mental, piel fria y moteada, oliguria, dolor toracico isquemico, disnea con congestion e hipotension.' },
  { front:'Arritmia e inestabilidad', back:'Puede ser la CAUSA de la inestabilidad o su MANIFESTACION. Tratar la arritmia de quien esta inestable por sepsis o hemorragia no resuelve nada.' },
  { front:'Los dos ritmos desfibrilables', back:'Fibrilacion ventricular y taquicardia ventricular sin pulso. La prioridad absoluta es la DESCARGA.' },
  { front:'Los dos ritmos no desfibrilables', back:'Asistolia y actividad electrica sin pulso. Aqui el resultado depende de encontrar la CAUSA, no del farmaco.' },
  { front:'Taquicardia ventricular polimorfa', back:'Se considera SIEMPRE inestable: desfibrilacion inmediata. El retraso en la descarga empeora el resultado.' },
  { front:'Adrenalina en ritmo NO desfibrilable', back:'Cuanto antes sea posible. No hay descarga que dar, de modo que nada justifica esperar.' },
  { front:'Adrenalina en ritmo desfibrilable', back:'DESPUES de los intentos iniciales de desfibrilacion. Lo que reinicia el corazon ahi es la descarga, y la adrenalina no debe retrasarla.' },
  { front:'Dosis de adrenalina', back:'1 mg cada 3 a 5 minutos. Asignar a alguien el control del tiempo: el retraso entre dosis es un fallo frecuente.' },
  { front:'Via de eleccion en 2025', back:'INTRAVENOSA. El intraoseo es la alternativa razonable si la intravenosa no es viable o se retrasa. Es el orden inverso al que muchos han interiorizado.' },
  { front:'Farmacos por el tubo endotraqueal', back:'RETIRADO en 2025 como procedimiento obsoleto con equivalentes modernos mas eficaces. No es una via de rescate.' },
  { front:'RCP con la cabeza elevada', back:'Se DESACONSEJA fuera de ensayos clinicos rigurosos con las protecciones adecuadas.' },
  { front:'Cambio de vector y desfibrilacion secuencial doble', back:'Utilidad NO establecida en la fibrilacion refractaria. Ni recomendadas ni prohibidas: hace falta mas investigacion.' },
  { front:'Antiarritmicos que pueden considerarse', back:'Amiodarona o lidocaina, en fibrilacion ventricular o taquicardia sin pulso que no responde a la desfibrilacion. Recomendacion debil.' },
  { front:'Antiarritmicos de beneficio incierto', back:'Betabloqueantes, bretilio, procainamida y sotalol en la parada refractaria a la desfibrilacion.' },
  { front:'Calcio, bicarbonato y magnesio', back:'NO se recomienda su administracion de rutina. Conservan su sitio ante una indicacion concreta: calcio en hiperpotasemia, magnesio en polimorfa con QT largo.' },
  { front:'Corticoides en la parada', back:'Beneficio INCIERTO segun la guia de 2025.' },
  { front:'Via aerea avanzada: cuando diferirla', back:'Si su colocacion va a interrumpir las compresiones, se difiere hasta que el paciente no responda a la reanimacion inicial y a la desfibrilacion.' },
  { front:'Quien debe intubar en la parada', back:'Quien tenga EXPERIENCIA o entrenamiento FRECUENTES. La guia lo recomienda de forma expresa porque la tasa de exito depende mucho de eso.' },
  { front:'Carbonico espirado con bolsa y mascarilla', back:'Sus valores son tan fiables como con otros dispositivos, lo que amplia su utilidad a situaciones sin via aerea avanzada.' },
  { front:'Carbonico espirado y fin de la reanimacion', back:'NO debe usarse de forma AISLADA para terminar los esfuerzos. Aviso expreso de la edicion de 2025.' },
  { front:'Ecografia a pie de cama', back:'Puede considerarse, en manos expertas, para diagnosticar causas reversibles SI NO INTERRUMPE la reanimacion. Esa condicion es la que mas se incumple.' },
  { front:'Cardioversion de fibrilacion auricular y flutter', back:'Primera descarga de 200 J o mas, preferible a energias menores. Cambio de 2025.' },
  { front:'Desfibrilacion en la parada', back:'La energia que recomiende el fabricante; si no se conoce, la MAXIMA disponible. Reanudar compresiones sin comprobar el pulso.' },
  { front:'Las causas reversibles', back:'Hipoxia, hipovolemia, acidosis, hipo e hiperpotasemia, hipotermia, neumotorax a tension, taponamiento, toxicos, trombosis coronaria y trombosis pulmonar.' },
  { front:'Trampa de la asistolia', back:'Una fibrilacion ventricular FINA puede parecer una linea plana. Comprobar derivaciones, ganancia y mas de una derivacion antes de asumirlo.' },
  { front:'Seudoactividad electrica sin pulso', back:'Hay contraccion en la ecografia aunque no se palpe pulso. Su pronostico es mejor que el de la ausencia real de actividad.' },
  { front:'Reglas de terminacion', back:'Se aplica la que corresponde al AMBITO y al nivel de los intervinientes: soporte vital basico, soporte vital avanzado o regla universal.' },
  { front:'Supervivencia extrahospitalaria', back:'Incidencia atendida de 83.4 por cada 100.000 habitantes y a&#241;o. Supervivencia al alta en torno al 10%.' },
  { front:'Supervivencia intrahospitalaria', back:'Ocurre en 1 de cada 100 ingresados. Recuperacion de circulacion en el 72.2%, supervivencia al alta del 24.2%, y buen resultado neurologico en cerca del 85% de los supervivientes.' },
  { front:'Recuperacion de la circulacion: los dos terminos', back:'Recuperacion de la CIRCULACION cuando se consigue por medios mecanicos, como una oxigenacion extracorporea. ESPONTANEA cuando se debe a la propia funcion cardiaca.' },
  { front:'Lo que de verdad cambia el resultado', back:'Compresiones de calidad sin interrupciones, desfibrilacion precoz y encontrar la causa. Ningun farmaco de la parada ha demostrado con claridad mejorar el resultado neurologico a largo plazo.' }
];

export default { quiz, flashcards };
