// topics/anemias-hemoliticas-hereditarias/study.js: Autoevaluación de Anemias Hemolíticas
// Hereditarias. Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud
// comparable entre opciones, distractores plausibles, sin pistas gramaticales/semánticas,
// posición de `correct` distribuida sin patrón (verificar el listado de índices antes de dar el
// archivo por terminado).
//
// Índices `correct` de las 30 preguntas sueltas, en orden: 1,3,0,2,1,3,2,0,1,3,0,2,3,1,0,2,3,1,2,
// 0,3,2,0,1,3,0,2,1,3,2. Recuento: 0×7, 1×7, 2×8, 3×8. Sin racha >2 ni ciclo fijo.
// Índices `correct` de los pasos de las 5 preguntas en cascada (3 pasos c/u), en orden: 1,3,0 /
// 2,0,3 / 1,2,0 / 3,1,2 / 0,3,1. Recuento: 0×4, 1×4, 2×3, 3×4.

export const quiz = [
  { q: '¿Qué distingue a las anemias hemolíticas hereditarias de las adquiridas?', options: ['Las hereditarias cursan con Coombs positiva', 'Defecto intrínseco frente a mecanismo extrínseco', 'Las adquiridas carecen de reticulocitosis', 'Las hereditarias no elevan la bilirrubina'], correct: 1, explanation: 'Las anemias hemolíticas hereditarias tienen un defecto intrínseco del eritrocito (membrana o enzimas), a diferencia de las adquiridas, de mecanismo extrínseco (autoinmune, microangiopático).', dificultad: 'facil' },
  { q: '¿Cuál es la membranopatía eritrocitaria más frecuente en población de ascendencia norteuropea?', options: ['Deficiencia de piruvato cinasa', 'Eliptocitosis hereditaria', 'Deficiencia de G6PD', 'Esferocitosis hereditaria'], correct: 3, explanation: 'La esferocitosis hereditaria es la membranopatía más frecuente y la anemia hemolítica hereditaria más común en población de ascendencia norteuropea.', dificultad: 'facil' },
  { q: '¿Por qué la deficiencia de G6PD tiene mayor prevalencia en regiones históricamente endémicas de malaria?', options: ['Ventaja selectiva frente al paludismo', 'Consanguinidad extendida en esas zonas', 'Exposición ambiental a insecticidas', 'Deficiencia nutricional de folato'], correct: 0, explanation: 'La deficiencia de G6PD confiere una ventaja selectiva heterocigota frente al paludismo por Plasmodium falciparum, lo que explica su mayor prevalencia en regiones históricamente endémicas de malaria.', dificultad: 'intermedio' },
  { q: '¿Cuáles son las proteínas del citoesqueleto de membrana más frecuentemente afectadas en la esferocitosis hereditaria?', options: ['Colágeno tipo IV y laminina', 'Actina y miosina musculares', 'Ankirina, banda 3 y espectrina', 'Queratina y desmoplaquina'], correct: 2, explanation: 'Las mutaciones más frecuentes en la esferocitosis hereditaria afectan a ankirina, banda 3, espectrina (alfa/beta) y proteína 4.2.', dificultad: 'intermedio' },
  { q: '¿Cuál es el patrón de herencia predominante en la esferocitosis hereditaria?', options: ['Recesiva ligada al cromosoma X', 'Autosómica dominante en ~75%', 'Herencia mitocondrial materna', 'Autosómica recesiva en su mayoría'], correct: 1, explanation: 'La esferocitosis hereditaria tiene herencia autosómica dominante en ~75% de los casos, autosómica recesiva o de novo en el resto.', dificultad: 'facil' },
  { q: '¿Cuál es la prueba diagnóstica de elección actual para la esferocitosis hereditaria?', options: ['Prueba de fragilidad osmótica', 'Biopsia de médula ósea diagnóstica', 'Panel de anticuerpos antinucleares', 'Citometría con eosina-5-maleimida'], correct: 3, explanation: 'El EMA binding test es la prueba de elección actual, con mayor sensibilidad y especificidad que la fragilidad osmótica.', dificultad: 'facil' },
  { q: '¿Por qué es obligatorio realizar una prueba de antiglobulina directa (Coombs directa) antes de atribuir un cuadro con esferocitos a una causa hereditaria?', options: ['La Coombs confirma la forma hereditaria', 'La Coombs mide la actividad de G6PD', 'La hemólisis autoinmune da esferocitos', 'La Coombs sustituye a la biopsia medular'], correct: 2, explanation: 'La anemia hemolítica autoinmune puede producir esferocitos indistinguibles morfológicamente de la esferocitosis hereditaria; la Coombs directa negativa es esencial para excluir la causa adquirida.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo del hemograma es un dato de apoyo característico (aunque no exclusivo) de la esferocitosis hereditaria?', options: ['CHCM elevada en el hemograma', 'VCM marcadamente elevado y persistente', 'Trombocitopenia intensa mantenida', 'Leucocitosis neutrofílica constante'], correct: 0, explanation: 'La CHCM/MCHC con frecuencia está elevada (&gt;35 g/dL) en la esferocitosis hereditaria, un dato de apoyo característico aunque no exclusivo.', dificultad: 'intermedio' },
  { q: '¿Cuál es el tratamiento definitivo de la esferocitosis hereditaria moderada-grave sintomática?', options: ['Trasplante alogénico de progenitores', 'Esplenectomía programada', 'Quimioterapia de inducción', 'Plasmaféresis seriada'], correct: 1, explanation: 'La esplenectomía es el tratamiento definitivo de la esferocitosis hereditaria moderada-grave sintomática, con resolución sustancial de la anemia y la ictericia en la mayoría de los casos.', dificultad: 'facil' },
  { q: '¿Por qué se recomienda diferir la esplenectomía electiva en la esferocitosis hereditaria hasta después de los 5-6 años cuando sea posible?', options: ['El bazo no es extirpable a esa edad', 'La anemia mejora sola antes de esa edad', 'La vacunación no es eficaz antes', 'Mayor riesgo de sepsis por encapsulados'], correct: 3, explanation: 'El riesgo de sepsis fulminante por gérmenes encapsulados es mayor a menor edad, por lo que se prefiere diferir la esplenectomía electiva cuando es clínicamente posible.', dificultad: 'intermedio' },
  { q: '¿Qué proteínas están mutadas con mayor frecuencia en la eliptocitosis hereditaria?', options: ['Espectrina o proteína 4.1', 'Ankirina y banda 3', 'Glucosa-6-fosfato deshidrogenasa', 'Piruvato cinasa eritrocitaria'], correct: 0, explanation: 'La eliptocitosis hereditaria se debe a mutaciones en espectrina o proteína 4.1, que debilitan las interacciones horizontales del citoesqueleto de membrana.', dificultad: 'intermedio' },
  { q: '¿Qué caracteriza a la piropoiquilocitosis hereditaria?', options: ['Forma heterocigota leve y asintomática', 'Forma de inicio en la edad adulta', 'Forma homocigota grave del neonato', 'Forma que no requiere transfusión'], correct: 2, explanation: 'La piropoiquilocitosis hereditaria es la forma homocigota o doble heterocigota de la eliptocitosis, con fenotipo neonatal grave y fragilidad térmica característica.', dificultad: 'dificil' },
  { q: '¿Cuál es el patrón de herencia de la deficiencia de G6PD?', options: ['Autosómica dominante', 'Autosómica recesiva', 'Herencia mitocondrial', 'Recesiva ligada al X'], correct: 3, explanation: 'La deficiencia de G6PD tiene herencia recesiva ligada al cromosoma X.', dificultad: 'facil' },
  { q: '¿Por qué la deficiencia de G6PD predomina clínicamente en varones?', options: ['Mayor exposición ocupacional a tóxicos', 'Herencia ligada al X, son hemicigotos', 'Diferencias hormonales en la enzima', 'Las mujeres no portan la mutación'], correct: 1, explanation: 'Al ser una herencia recesiva ligada al X, los varones (hemicigotos, con un solo alelo) expresan la deficiencia clínicamente con mayor frecuencia que las mujeres heterocigotas.', dificultad: 'intermedio' },
  { q: '¿Cuál es el mecanismo fisiopatológico central de la deficiencia de G6PD?', options: ['NADPH insuficiente frente al estrés oxidativo', 'Bloqueo de la glucólisis con déficit de ATP', 'Defecto estructural del citoesqueleto', 'Producción excesiva de 2,3-difosfoglicerato'], correct: 0, explanation: 'La deficiencia de G6PD reduce la generación de NADPH en la vía de las pentosas fosfato, comprometiendo la capacidad antioxidante del eritrocito frente al estrés oxidativo.', dificultad: 'facil' },
  { q: '¿Qué hallazgo del frotis es característico de la crisis hemolítica aguda por deficiencia de G6PD?', options: ['Esferocitos abundantes en el frotis', 'Eliptocitos predominantes', 'Cuerpos de Heinz y bite cells', 'Dacriocitos en forma de lágrima'], correct: 2, explanation: 'Los cuerpos de Heinz (hemoglobina oxidada precipitada) y las "bite cells" son característicos de la crisis hemolítica aguda por deficiencia de G6PD.', dificultad: 'intermedio' },
  { q: '¿Por qué la actividad enzimática de G6PD puede resultar falsamente normal si se mide inmediatamente después de una crisis hemolítica aguda?', options: ['La enzima se regenera en minutos', 'El ensayo pierde sensibilidad al calor', 'Los reticulocitos carecen de actividad', 'Quedan reticulocitos jóvenes activos'], correct: 3, explanation: 'Tras la crisis, los eritrocitos más viejos y deficientes ya fueron destruidos, y la población predominante de reticulocitos jóvenes tiene actividad enzimática relativamente preservada, dando un resultado falsamente normal.', dificultad: 'dificil' },
  { q: '¿Cuál es el desencadenante clásico de hemólisis aguda grave por deficiencia de G6PD en las variantes mediterráneas, conocido como favismo?', options: ['Exposición solar prolongada', 'Consumo de habas', 'Ejercicio físico intenso', 'Consumo de lácteos'], correct: 1, explanation: 'El favismo es la hemólisis aguda grave desencadenada por el consumo de habas en pacientes con ciertas variantes mediterráneas de deficiencia de G6PD.', dificultad: 'facil' },
  { q: '¿Cuál es el patrón de herencia de la deficiencia de piruvato cinasa?', options: ['Recesiva ligada al X', 'Autosómica dominante', 'Autosómica recesiva', 'Mitocondrial'], correct: 2, explanation: 'La deficiencia de piruvato cinasa tiene herencia autosómica recesiva.', dificultad: 'facil' },
  { q: '¿Por qué los pacientes con deficiencia de piruvato cinasa toleran grados de anemia más profundos con relativamente menos síntomas?', options: ['Aumento del 2,3-difosfoglicerato compensador', 'Mayor afinidad de la hemoglobina por el O2', 'Ausencia de reticulocitosis compensadora', 'Gasto cardiaco reducido de forma protectora'], correct: 0, explanation: 'El aumento compensador de 2,3-difosfoglicerato desplaza la curva de disociación de la hemoglobina hacia la derecha, mejorando la liberación tisular de oxígeno pese a la anemia.', dificultad: 'dificil' },
  { q: '¿Cuál es el tratamiento farmacológico dirigido específico aprobado para la deficiencia de piruvato cinasa?', options: ['Ácido fólico en monoterapia diaria', 'Deferasirox quelante oral', 'Rituximab en dosis semanales', 'Mitapivat, activador de la enzima'], correct: 3, explanation: 'El mitapivat, un activador alostérico de la piruvato cinasa, es el primer tratamiento dirigido al defecto molecular específico de esta enzimopatía.', dificultad: 'intermedio' },
  { q: '¿Qué variables se necesitan para calcular el índice de producción reticulocitaria (IPR)?', options: ['Hemoglobina y VCM del paciente', 'Bilirrubina indirecta y LDH', 'Reticulocitos y hematocrito', 'Plaquetas y leucocitos totales'], correct: 2, explanation: 'El IPR se calcula a partir del porcentaje de reticulocitos, el hematocrito del paciente, el hematocrito normal de referencia, y un factor de maduración.', dificultad: 'intermedio' },
  { q: 'Un paciente anémico tiene un IPR de 0.8. ¿Cómo se interpreta este resultado?', options: ['Respuesta medular inadecuada', 'Respuesta medular adecuada', 'Hemólisis intravascular masiva', 'Valor normal sin significado'], correct: 0, explanation: 'Un IPR &lt;2 sugiere una respuesta medular inadecuada, obligando a reconsiderar el diagnóstico o a sospechar una crisis aplásica sobreañadida en un paciente con hemólisis crónica conocida.', dificultad: 'intermedio' },
  { q: 'Según la clasificación de gravedad de la esferocitosis hereditaria, ¿qué categoría corresponde a hemoglobina 9 g/dL, reticulocitos 8% y bilirrubina 2.5 mg/dL?', options: ['Esferocitosis leve', 'Esferocitosis moderada', 'Esferocitosis grave', 'No clasificable con estos datos'], correct: 1, explanation: 'Hb 8-11 g/dL, reticulocitos 6-10% y bilirrubina 2-3 mg/dL corresponden a la categoría moderada.', dificultad: 'intermedio' },
  { q: '¿Cuál es el virus clásicamente asociado a la crisis aplásica en pacientes con hemólisis crónica?', options: ['Citomegalovirus', 'Virus de Epstein-Barr', 'Virus de la hepatitis B', 'Parvovirus B19'], correct: 3, explanation: 'El parvovirus B19 es el virus clásicamente asociado a la crisis aplásica en pacientes con hemólisis crónica, por su tropismo directo por los precursores eritroides.', dificultad: 'facil' },
  { q: '¿Cuál es el mecanismo por el que el parvovirus B19 produce una crisis aplásica clínicamente grave en el paciente con hemólisis crónica, pero pasa inadvertido en una persona sana?', options: ['Depende de la reticulocitosis continua', 'Solo infecta eritrocitos displásicos', 'Produce hemólisis directa masiva', 'Solo afecta a esplenectomizados'], correct: 0, explanation: 'La vida media eritrocitaria acortada en la hemólisis crónica hace que el cese transitorio de la producción reticulocitaria por el parvovirus B19 produzca una caída brusca de hemoglobina, sin el amortiguamiento de la vida media normal de ~120 días de una persona sana.', dificultad: 'dificil' },
  { q: '¿Qué hallazgo de laboratorio distingue a la crisis aplásica de una exacerbación hemolítica simple?', options: ['Bilirrubina elevada en ambas', 'LDH elevada solo en la hemólisis', 'Reticulocitopenia marcada', 'Esferocitos solo en la crisis'], correct: 2, explanation: 'La reticulocitopenia marcada distingue a la crisis aplásica de una exacerbación hemolítica simple, que cursa con reticulocitosis conservada o aumentada.', dificultad: 'intermedio' },
  { q: '¿Cuál es la medida más eficaz para prevenir la crisis megaloblástica en un paciente con hemólisis crónica?', options: ['Restricción proteica en la dieta', 'Ácido fólico profiláctico', 'Transfusión mensual programada', 'Evitar la exposición solar'], correct: 1, explanation: 'La suplementación profiláctica indefinida con ácido fólico previene casi por completo la crisis megaloblástica en la hemólisis crónica.', dificultad: 'facil' },
  { q: '¿Qué tipo de cálculo biliar es característico de la colelitiasis asociada a hemólisis crónica?', options: ['Cálculos de colesterol puro', 'Cálculos de oxalato de calcio', 'Cálculos de estruvita', 'Cálculos pigmentarios'], correct: 3, explanation: 'Los cálculos de bilirrubinato de calcio ("pigmentarios", típicamente negros y friables) son característicos de la colelitiasis asociada a hemólisis crónica.', dificultad: 'facil' },
  { q: '¿Cuál es la conducta más apropiada ante colelitiasis asintomática hallada de forma incidental en un paciente que además tiene indicación de esplenectomía por su enfermedad hemolítica de base?', options: ['Dejar la vesícula sin intervenir', 'Colecistectomía aislada, sin el bazo', 'Colecistectomía en el mismo tiempo', 'Esperar a que se vuelva sintomática'], correct: 2, explanation: 'Cuando ya hay indicación de esplenectomía, es razonable combinar la colecistectomía en el mismo tiempo quirúrgico para evitar un segundo procedimiento separado.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Niña de 7 años con ictericia intermitente desde lactante y antecedente de madre con esplenectomía en la infancia por "anemia hereditaria". La biometría hemática muestra Hb 9.5 g/dL, reticulocitos 9%, CHCM elevada. El frotis muestra microesferocitos.',
    steps: [
      { q: '¿Cuál es el primer estudio que debe solicitarse para descartar la principal causa adquirida que puede simular este cuadro?', options: ['Ecografía abdominal completa', 'Prueba de Coombs directa', 'Biopsia de médula ósea', 'Panel viral ampliado'], correct: 1 },
      { q: 'La Coombs directa es negativa. ¿Cuál es la prueba confirmatoria de elección actual?', options: ['Fragilidad osmótica clásica', 'Electroforesis de hemoglobina', 'Prueba de Ham ácida', 'Citometría con EMA binding'], correct: 3 },
      { q: 'Se confirma esferocitosis hereditaria, clasificada como moderada. ¿Cuál es la conducta más apropiada respecto a la esplenectomía?', options: ['Diferir a los 5-6 años, vacunando antes', 'Esplenectomía inmediata sin vacunar', 'La esplenectomía está contraindicada', 'Trasplante alogénico de médula ósea'], correct: 0 }
    ],
    explanation: 'El antecedente familiar con esferocitos y Coombs negativa orienta a esferocitosis hereditaria, confirmada por el EMA binding test. En la forma moderada sintomática, la esplenectomía es el tratamiento definitivo, pero se difiere hasta después de los 5-6 años cuando es posible, con vacunación completa contra gérmenes encapsulados al menos 2 semanas antes, por el mayor riesgo de sepsis fulminante a menor edad.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 24 años, de ascendencia mediterránea, inicia primaquina para profilaxis antipalúdica. Al tercer día presenta ictericia, orina oscura y fatiga aguda. La biometría hemática muestra Hb 7.8 g/dL (basal 15 g/dL). El frotis muestra cuerpos de Heinz y células mordidas.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable?', options: ['Hemólisis autoinmune por fármacos', 'Esferocitosis hereditaria no conocida', 'Crisis por G6PD tras primaquina', 'Talasemia mayor no diagnosticada'], correct: 2 },
      { q: '¿Cuál es la conducta inmediata más apropiada?', options: ['Suspender primaquina e hidratar', 'Continuar primaquina a dosis menor', 'Iniciar corticoide inmunosupresor', 'Esplenectomía de urgencia'], correct: 0 },
      { q: 'Se solicita actividad enzimática de G6PD 2 días después del inicio del cuadro y resulta normal. ¿Cómo se interpreta este resultado?', options: ['Descarta la deficiencia de G6PD', 'Confirma esferocitosis hereditaria', 'Indica iniciar tratamiento con hierro', 'Falso normal, repetir en 2-3 meses'], correct: 3 }
    ],
    explanation: 'La hemólisis aguda con cuerpos de Heinz y bite cells tras un fármaco oxidante conocido (primaquina) en un paciente de ascendencia con alta prevalencia de deficiencia de G6PD es característica de una crisis hemolítica por esa deficiencia. La conducta inmediata es suspender el desencadenante e hidratar. La actividad enzimática medida muy cerca del episodio agudo puede ser falsamente normal, por lo que debe repetirse 2-3 meses después si la sospecha clínica persiste.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Niño de 6 años con esferocitosis hereditaria conocida presenta palidez marcada y fatiga extrema de 3 días de evolución, con fiebre leve la semana previa. No hay ictericia acentuada respecto a su basal. La biometría hemática muestra Hb 4.5 g/dL (basal 10 g/dL) con reticulocitos absolutos muy bajos.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable?', options: ['Exacerbación hemolítica simple', 'Crisis aplásica por parvovirus B19', 'Crisis megaloblástica por folato', 'Colecistitis aguda litiásica'], correct: 1 },
      { q: '¿Qué hallazgo de laboratorio es más consistente con este diagnóstico, a diferencia de una simple exacerbación hemolítica?', options: ['Bilirrubina marcadamente elevada', 'LDH marcadamente elevada', 'Reticulocitos muy bajos o ausentes', 'Esferocitos abundantes en el frotis'], correct: 2 },
      { q: '¿Cuál es la conducta más apropiada?', options: ['Transfusión de soporte y aislamiento', 'Esplenectomía de urgencia programada', 'Inmunoglobulina intravenosa en dosis altas', 'Hierro parenteral de inmediato'], correct: 0 }
    ],
    explanation: 'El descenso brusco de hemoglobina sin ictericia acentuada ni reticulocitosis en un paciente con hemólisis crónica conocida, tras un pródromo viral, es característico de una crisis aplásica, típicamente por parvovirus B19; la reticulocitopenia marcada la distingue de una exacerbación hemolítica simple. El manejo es de soporte transfusional según gravedad, aislamiento de gotitas, y vigilancia hasta la recuperación espontánea de la eritropoyesis en 1-2 semanas; la inmunoglobulina IV se reserva para el paciente inmunocomprometido con infección persistente.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Recién nacido presenta ictericia prolongada y anemia hemolítica no esferocítica. La Coombs directa es negativa. El frotis muestra equinocitos sin esferocitos prominentes. Los padres son primos hermanos.',
    steps: [
      { q: 'Dado el patrón (Coombs negativa, sin esferocitos prominentes, consanguinidad parental), ¿cuál es la sospecha diagnóstica más probable?', options: ['Esferocitosis hereditaria', 'Deficiencia de G6PD', 'Anemia hemolítica autoinmune neonatal', 'Deficiencia de piruvato cinasa'], correct: 3 },
      { q: '¿Qué estudio confirma el diagnóstico?', options: ['Prueba de fragilidad osmótica clásica', 'Actividad enzimática de piruvato cinasa', 'Electroforesis de hemoglobina completa', 'Citometría de flujo con EMA binding'], correct: 1 },
      { q: 'Conforme crece, el niño tolera cifras de hemoglobina relativamente bajas con síntomas menores a los esperados. ¿Cuál es la explicación fisiológica de este hallazgo característico de esta enzimopatía?', options: ['Mayor afinidad de su hemoglobina por el O2', 'Ausencia de reticulocitosis compensadora', 'El 2,3-DPG desplaza la curva a la derecha', 'Gasto cardiaco permanentemente reducido'], correct: 2 }
    ],
    explanation: 'La anemia hemolítica no esferocítica con Coombs negativa, equinocitos y consanguinidad parental (herencia autosómica recesiva) sugiere deficiencia de piruvato cinasa, confirmada por el ensayo de actividad enzimática. Estos pacientes toleran grados de anemia más profundos con relativamente menos síntomas por el aumento compensador de 2,3-difosfoglicerato, que desplaza la curva de disociación de la hemoglobina hacia la derecha y mejora la liberación tisular de oxígeno.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Adolescente de 15 años con esferocitosis hereditaria grave, dependiente de transfusiones, tiene programada una esplenectomía. La ecografía abdominal preoperatoria de rutina muestra múltiples cálculos vesiculares asintomáticos.',
    steps: [
      { q: '¿Cuál es el tipo de cálculo biliar esperado en este contexto?', options: ['Cálculos de bilirrubinato de calcio', 'Cálculos de colesterol puro biliares', 'Cálculos de oxalato de calcio', 'Cálculos de estruvita infecciosos'], correct: 0 },
      { q: '¿Cuál es la conducta más apropiada respecto a la vesícula, dado que los cálculos son asintomáticos pero ya está programada la esplenectomía?', options: ['Dejar los cálculos sin intervenir', 'Posponer la esplenectomía hasta operar', 'Colecistectomía en un segundo tiempo', 'Colecistectomía en el mismo tiempo'], correct: 3 },
      { q: 'Antes del procedimiento quirúrgico combinado, ¿qué medida preventiva es indispensable dado que se realizará esplenectomía?', options: ['Quelación de hierro profiláctica', 'Vacunar contra gérmenes encapsulados', 'Suspender el ácido fólico previo', 'Iniciar mitapivat preoperatorio'], correct: 1 }
    ],
    explanation: 'La colelitiasis en la hemólisis crónica es característicamente pigmentaria (bilirrubinato de calcio). Cuando ya hay indicación de esplenectomía, es razonable combinar la colecistectomía en el mismo tiempo quirúrgico para evitar un segundo procedimiento. Antes de cualquier esplenectomía, la vacunación contra gérmenes encapsulados debe completarse con al menos 2 semanas de anticipación, para reducir el riesgo de sepsis fulminante posesplenectomía.'
  }
];

export const flashcards = [
  { front: 'Membranopatía más frecuente en ascendencia norteuropea', back: 'Esferocitosis hereditaria.' },
  { front: 'Enzimopatía eritrocitaria más frecuente en el mundo', back: 'Deficiencia de G6PD (~400 millones de personas), por ventaja selectiva frente a la malaria.' },
  { front: 'Proteínas mutadas en esferocitosis hereditaria', back: 'Ankirina, banda 3, espectrina, proteína 4.2. Herencia AD ~75%.' },
  { front: 'Prueba diagnóstica de elección para esferocitosis hereditaria', back: 'EMA binding test (citometría de flujo), superior a la fragilidad osmótica.' },
  { front: 'Antes de diagnosticar esferocitosis hereditaria, siempre', back: 'Coombs directa NEGATIVA (excluye anemia hemolítica autoinmune, que puede tener esferocitos idénticos).' },
  { front: 'Dato de apoyo en el hemograma de esferocitosis hereditaria', back: 'CHCM/MCHC elevada (&gt;35 g/dL).' },
  { front: 'Tratamiento definitivo de esferocitosis hereditaria moderada-grave', back: 'Esplenectomía; diferir a &gt;5-6 años si es posible, con vacunación previa.' },
  { front: 'Proteínas mutadas en eliptocitosis hereditaria', back: 'Espectrina o proteína 4.1. Herencia AD.' },
  { front: 'Piropoiquilocitosis hereditaria', back: 'Forma homocigota/doble heterocigota de eliptocitosis; fenotipo neonatal grave, fragilidad térmica.' },
  { front: 'Herencia de la deficiencia de G6PD', back: 'Recesiva ligada al X; predomina clínicamente en varones (hemicigotos).' },
  { front: 'Mecanismo de la deficiencia de G6PD', back: 'Falta de NADPH en la vía de pentosas fosfato → vulnerabilidad al estrés oxidativo.' },
  { front: 'Frotis en crisis por G6PD', back: 'Cuerpos de Heinz + "bite cells" (células mordidas).' },
  { front: 'Por qué la actividad de G6PD puede salir falsamente normal post-crisis', back: 'Los eritrocitos viejos/deficientes ya se destruyeron; quedan reticulocitos jóvenes con actividad preservada. Repetir en 2-3 meses.' },
  { front: 'Favismo', back: 'Hemólisis aguda grave por consumo de habas en variantes mediterráneas de deficiencia de G6PD.' },
  { front: 'Herencia de la deficiencia de piruvato cinasa', back: 'Autosómica recesiva.' },
  { front: 'Por qué la deficiencia de PK tolera anemia profunda mejor', back: '↑2,3-DPG desplaza la curva de disociación de Hb a la derecha → mejor liberación de O2 tisular.' },
  { front: 'Tratamiento dirigido de deficiencia de piruvato cinasa', back: 'Mitapivat (activador alostérico de la piruvato cinasa).' },
  { front: 'Fórmula del IPR', back: 'Retic corregido = retic% × (Hto paciente/Hto normal). IPR = retic corregido / factor de maduración.' },
  { front: 'Interpretación del IPR', back: '≥3 respuesta medular adecuada (hemólisis/sangrado); &lt;2 hipoproliferativa.' },
  { front: 'Clasificación de gravedad de esferocitosis hereditaria', back: 'Leve/moderada/grave según Hb, reticulocitos y bilirrubina.' },
  { front: 'Virus de la crisis aplásica', back: 'Parvovirus B19: infecta precursores eritroides, cesa la eritropoyesis 7-10 días.' },
  { front: 'Crisis aplásica: hallazgo clave que la distingue', back: 'Reticulocitopenia marcada (NO reticulocitosis) + sin ictericia acentuada.' },
  { front: 'Prevención de la crisis megaloblástica', back: 'Ácido fólico profiláctico indefinido en toda hemólisis crónica.' },
  { front: 'Tipo de cálculo biliar en hemólisis crónica', back: 'Bilirrubinato de calcio ("pigmentario"), no de colesterol.' },
  { front: 'Colelitiasis + indicación de esplenectomía', back: 'Combinar colecistectomía + esplenectomía en el mismo tiempo quirúrgico.' },
  { front: 'Vacunación pre-esplenectomía', back: 'Neumococo, meningococo, H. influenzae b, al menos 2 semanas antes.' }
];

export const caseSteps = [];
export const caseSummary = undefined;

export default { quiz, flashcards, caseSteps, caseSummary };
