// topics/policitemia-secundaria/study.js: Autoevaluación de Policitemia Secundaria.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Índices `correct` de las 30 preguntas sueltas, en orden: 2,0,3,1,2,1,0,3,2,0,1,3,0,2,3,1,0,2,3,
// 1,2,0,3,1,0,2,3,0,2,1. Recuento: 0×8, 1×7, 2×8, 3×7. Sin racha >2 ni ciclo fijo.
// Índices `correct` de los pasos de las 5 preguntas en cascada (3 pasos c/u), en orden: 0,1,2 /
// 2,0,3 / 1,3,0 / 0,2,1 / 3,1,2. Recuento: 0×4, 1×4, 2×4, 3×3.

export const quiz = [
  { q: '¿Cuál es la diferencia fundamental entre la eritrocitosis secundaria y la policitemia vera?', options: ['No hay diferencia real entre ambas', 'La secundaria tiene peor pronóstico', 'La secundaria es reactiva, no clonal', 'La secundaria solo ocurre en niños'], correct: 2, explanation: 'La eritrocitosis secundaria es reactiva, mediada por EPO, sin mutación clonal; la policitemia vera es una neoplasia mieloproliferativa clonal, casi siempre JAK2 positiva.', dificultad: 'facil' },
  { q: '¿Cuál es la causa más frecuente de eritrocitosis secundaria en la práctica clínica?', options: ['Hipoxemia crónica y apnea del sueño', 'Tumores productores de eritropoyetina', 'Mutación del receptor de eritropoyetina', 'Policitemia de Chuvash congénita'], correct: 0, explanation: 'La enfermedad pulmonar crónica hipoxemiante y la apnea obstructiva del sueño son las causas más frecuentes de eritrocitosis secundaria.', dificultad: 'facil' },
  { q: '¿Qué hace el factor inducible por hipoxia (HIF) al ser estabilizado por la hipoxia tisular renal?', options: ['Inhibe la producción de eritropoyetina', 'Degrada la ferroportina celular', 'Bloquea la vía JAK-STAT', 'Activa el gen de la eritropoyetina'], correct: 3, explanation: 'El HIF estabilizado activa la transcripción del gen de la eritropoyetina en las células peritubulares renales.', dificultad: 'intermedio' },
  { q: '¿Por qué el tabaquismo produce eritrocitosis pese a una saturación de oxígeno arterial medida que puede parecer normal?', options: ['El tabaco induce la mutación JAK2', 'La carboxihemoglobina engaña al oxímetro', 'El tabaco produce policitemia vera', 'El tabaco reduce el volumen plasmático'], correct: 1, explanation: 'El monóxido de carbono forma carboxihemoglobina, que reduce la liberación tisular de oxígeno pese a una saturación medida engañosamente normal.', dificultad: 'intermedio' },
  { q: '¿Cuál es el nivel esperado de eritropoyetina sérica en la policitemia vera?', options: ['Muy elevado de forma constante', 'Igual que en la forma secundaria', 'Bajo o indetectable', 'Sin relación con el diagnóstico'], correct: 2, explanation: 'La EPO está característicamente baja/indetectable en la policitemia vera, por la retroalimentación negativa de la eritrocitosis clonal autónoma.', dificultad: 'facil' },
  { q: '¿Qué combinación de JAK2 y EPO es más sugestiva de eritrocitosis secundaria?', options: ['JAK2 positiva con EPO sérica baja', 'JAK2 negativa, EPO normal o alta', 'JAK2 positiva con EPO sérica alta', 'JAK2 negativa con EPO sérica baja'], correct: 1, explanation: 'JAK2 negativa con EPO normal o alta apoya fuertemente el diagnóstico de eritrocitosis secundaria.', dificultad: 'intermedio' },
  { q: '¿Cuáles son los criterios OMS 2016 de eritrocitosis en el varón?', options: ['Hemoglobina &gt;16.5 g/dL o hematocrito &gt;49%', 'Hemoglobina &gt;12 g/dL', 'Hematocrito &gt;35%', 'Cualquier hemoglobina por encima del límite inferior normal'], correct: 0, explanation: 'Los criterios OMS 2016 de eritrocitosis en el varón son hemoglobina &gt;16.5 g/dL o hematocrito &gt;49%.', dificultad: 'facil' },
  { q: '¿Qué mecanismo produce la eritrocitosis en la cardiopatía congénita cianótica?', options: ['Producción de EPO por el corazón', 'Mutación clonal de la célula madre', 'Reducción del volumen plasmático', 'Cortocircuito derecha-izquierda'], correct: 3, explanation: 'El cortocircuito derecha-izquierda produce hipoxia tisular real, estimulando la producción apropiada de EPO.', dificultad: 'intermedio' },
  { q: '¿Cuál es el tumor más frecuentemente asociado a producción inapropiada de eritropoyetina?', options: ['Adenoma hipofisario secretor', 'Carcinoma ductal de mama', 'Carcinoma de células renales', 'Adenocarcinoma de próstata'], correct: 2, explanation: 'El carcinoma de células renales es el tumor más frecuentemente asociado a producción inapropiada de EPO.', dificultad: 'facil' },
  { q: '¿Qué caracteriza a la eritrocitosis postrasplante renal?', options: ['El injerto produce EPO sin regulación', 'Ocurre solo en el rechazo agudo', 'Es indistinguible de la policitemia vera', 'No responde al tratamiento farmacológico'], correct: 0, explanation: 'El riñón trasplantado produce EPO sin estar sujeto a la regulación fisiológica normal que existía en el riñón nativo enfermo.', dificultad: 'intermedio' },
  { q: '¿Qué fármaco de uso reconocido puede producir eritrocitosis como efecto adverso?', options: ['Paracetamol en dosis altas', 'Testosterona de reemplazo', 'Levotiroxina sustitutiva', 'Omeprazol de uso crónico'], correct: 1, explanation: 'La terapia de reemplazo de testosterona es una causa farmacológica reconocida y frecuente de eritrocitosis.', dificultad: 'facil' },
  { q: '¿Qué tratamiento farmacológico ha demostrado reducir eficazmente el hematocrito en la eritrocitosis postrasplante renal?', options: ['Betabloqueadores cardioselectivos', 'Diuréticos de asa en dosis altas', 'Corticoides sistémicos crónicos', 'Un IECA o un ARA II'], correct: 3, explanation: 'Los inhibidores de la ECA o los ARA-II han demostrado reducir eficazmente el hematocrito en la eritrocitosis postrasplante renal.', dificultad: 'intermedio' },
  { q: '¿Cuál es el nivel de eritropoyetina sérica característico de la mutación de ganancia de función del receptor de EPO (EPOR)?', options: ['Bajo-normal pese a la eritrocitosis', 'Muy elevado de forma constante', 'Indetectable de forma sistemática', 'Sin un patrón característico claro'], correct: 0, explanation: 'La mutación de EPOR produce señalización constitutiva del receptor, con EPO sérica característicamente baja-normal pese a la eritrocitosis.', dificultad: 'facil' },
  { q: '¿Qué caracteriza a la policitemia de Chuvash?', options: ['Mutación somática del gen PIGA', 'Deficiencia adquirida de hierro', 'Mutación de VHL que estabiliza HIF', 'Deficiencia hereditaria de G6PD'], correct: 2, explanation: 'La policitemia de Chuvash es producida por una mutación del gen VHL que impide la degradación normal del HIF, activando la producción de EPO de forma inapropiada.', dificultad: 'intermedio' },
  { q: '¿Cómo afecta una hemoglobina de alta afinidad por el oxígeno a la liberación tisular de oxígeno?', options: ['La aumenta de forma marcada', 'No modifica la liberación tisular', 'Solo altera la absorción de hierro', 'La reduce, con hipoxia funcional'], correct: 3, explanation: 'Una hemoglobina de alta afinidad reduce la liberación tisular de oxígeno pese a saturación arterial normal-alta, generando hipoxia tisular funcional.', dificultad: 'dificil' },
  { q: '¿Qué es la eritrocitosis relativa/espuria (síndrome de Gaisböck)?', options: ['Aumento real de la masa eritrocitaria', 'Hematocrito alto por menos plasma', 'Una forma leve de policitemia vera', 'Mutación congénita del receptor de EPO'], correct: 1, explanation: 'La eritrocitosis relativa/espuria es una elevación aparente del hematocrito por hemoconcentración, sin un verdadero aumento de la masa eritrocitaria.', dificultad: 'facil' },
  { q: '¿Cuál es el perfil de paciente clásicamente descrito en el síndrome de Gaisböck?', options: ['Varón de edad media, obeso y fumador', 'Mujer joven sin comorbilidades', 'Niño con cardiopatía congénita', 'Adulto mayor en diálisis crónica'], correct: 0, explanation: 'El perfil clásico del síndrome de Gaisböck es el varón de edad media con obesidad, hipertensión arterial y tabaquismo activo.', dificultad: 'intermedio' },
  { q: '¿Está indicada la flebotomía terapéutica en la eritrocitosis relativa/espuria pura?', options: ['Sí, igual que en la policitemia vera', 'Sí, pero en volúmenes mínimos', 'No, no hay exceso real que reducir', 'Solo si el paciente lo solicita'], correct: 2, explanation: 'La flebotomía no está indicada en la eritrocitosis relativa/espuria pura, dado que no hay verdadera masa eritrocitaria excesiva.', dificultad: 'facil' },
  { q: '¿Qué causa frecuentemente coexiste sin ser reconocida en el paciente con perfil de eritrocitosis relativa/espuria?', options: ['Deficiencia de vitamina B12', 'Enfermedad celíaca no tratada', 'Deficiencia crónica de folato', 'Apnea obstructiva del sueño'], correct: 3, explanation: 'La apnea obstructiva del sueño comparte el mismo perfil de paciente (obesidad) y debe buscarse activamente antes de asumir que la eritrocitosis es puramente relativa.', dificultad: 'intermedio' },
  { q: '¿Qué mutación confirma policitemia vera, independientemente del nivel de EPO?', options: ['Mutación del gen VHL', 'JAK2 (V617F o exón 12)', 'Mutación del gen EPOR', 'Mutación del gen TMPRSS6'], correct: 1, explanation: 'La mutación JAK2 (V617F o del exón 12) confirma policitemia vera, independientemente del nivel de EPO.', dificultad: 'facil' },
  { q: '¿Qué hallazgo clínico orienta fuertemente hacia policitemia vera y no hacia eritrocitosis secundaria?', options: ['Disnea de esfuerzo progresiva', 'Cefalea leve y ocasional', 'Prurito acuagénico', 'Fatiga inespecífica crónica'], correct: 2, explanation: 'El prurito acuagénico, la esplenomegalia y la eritromelalgia son hallazgos que orientan fuertemente hacia policitemia vera.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo de laboratorio adicional, si está presente, orienta más hacia policitemia vera que hacia eritrocitosis secundaria pura?', options: ['Leucocitosis y trombocitosis', 'Hierro sérico bajo aislado', 'Bilirrubina indirecta normal', 'Creatinina sérica normal'], correct: 0, explanation: 'La leucocitosis y trombocitosis asociadas son mucho más sugestivas de policitemia vera que de eritrocitosis secundaria pura.', dificultad: 'facil' },
  { q: '¿Cuál es el mecanismo del mayor riesgo trombótico en la eritrocitosis con hematocrito muy elevado?', options: ['La EPO activa la coagulación', 'Deficiencia de factores de coagulación', 'Anticuerpos antifosfolípido', 'Aumento de la viscosidad sanguínea'], correct: 3, explanation: 'El hematocrito muy elevado aumenta la viscosidad sanguínea de forma no lineal, reduciendo el flujo microvascular y favoreciendo la estasis y la trombosis.', dificultad: 'intermedio' },
  { q: '¿Por qué el riesgo trombótico absoluto es generalmente menor en la eritrocitosis secundaria que en la policitemia vera a un hematocrito equivalente?', options: ['La secundaria no eleva el hematocrito', 'Falta la activación plaquetaria clonal', 'La secundaria recibe anticoagulación', 'El hematocrito no supera el 45%'], correct: 1, explanation: 'En la eritrocitosis secundaria no hay el componente adicional de activación plaquetaria y leucocitaria clonal presente en la policitemia vera.', dificultad: 'facil' },
  { q: '¿Por qué reducir el hematocrito mediante flebotomía sin corregir primero la hipoxia de base puede ser problemático en la eritrocitosis hipóxica?', options: ['Reduce el transporte de oxígeno útil', 'La flebotomía produce anafilaxia grave', 'Está formalmente prohibida aquí', 'Aumenta la producción renal de EPO'], correct: 0, explanation: 'La flebotomía sin corregir la hipoxia puede reducir la capacidad de transporte de oxígeno sin mejorar la oxigenación tisular real, empeorando el equilibrio adaptativo.', dificultad: 'intermedio' },
  { q: '¿Qué complicación de laboratorio puede producir la flebotomía terapéutica repetida, independientemente de la causa de la eritrocitosis?', options: ['Hipercalcemia sintomática', 'Hiperpotasemia progresiva', 'Ferropenia por depleción', 'Hipernatremia mantenida'], correct: 2, explanation: 'La flebotomía repetida extrae hierro junto con los eritrocitos removidos, pudiendo inducir ferropenia iatrogénica.', dificultad: 'facil' },
  { q: '¿Cuál es la medida diagnóstica central para evitar un manejo erróneo (flebotomía indiscriminada, entre otros) en la eritrocitosis?', options: ['Iniciar tratamiento empírico sin estudio', 'Repetir la biometría en 6 meses', 'Referir directamente a psiquiatría', 'Determinar JAK2 y EPO sérica'], correct: 3, explanation: 'Determinar JAK2 y EPO sérica en todo paciente con eritrocitosis, antes de cualquier tratamiento, es la medida diagnóstica central.', dificultad: 'intermedio' },
  { q: '¿Qué riesgo existe al atribuir automáticamente la eritrocitosis al tabaquismo en un paciente fumador sin más estudio?', options: ['Pasar por alto una causa tratable', 'No hay riesgo, la atribución es correcta', 'Reducir el hematocrito medido', 'Aumentar la producción de EPO'], correct: 0, explanation: 'La atribución automática al tabaquismo puede pasar por alto una causa concomitante tratable, retrasando su diagnóstico.', dificultad: 'facil' },
  { q: '¿Qué estudio debe solicitarse de rutina en toda eritrocitosis nueva, incluso con una causa aparente evidente?', options: ['Radiografía de tórax simple', 'Colonoscopia de tamizaje', 'JAK2 y EPO sérica', 'Electroforesis de proteínas'], correct: 2, explanation: 'JAK2 y EPO sérica deben solicitarse de rutina en toda eritrocitosis nueva, incluso con una causa aparente evidente.', dificultad: 'intermedio' },
  { q: '¿Cuál es el método estándar de referencia histórico para confirmar una eritrocitosis verdadera y distinguirla de la relativa/espuria?', options: ['Biopsia de médula ósea diagnóstica', 'Masa eritrocitaria por isótopos', 'Tomografía computarizada simple', 'Electrocardiograma de reposo'], correct: 1, explanation: 'La medición de la masa eritrocitaria y el volumen plasmático por dilución isotópica es el método de referencia histórico para esta distinción.', dificultad: 'facil' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 68 años, fumador activo con EPOC grave, presenta cefalea y plétora facial. Hb 19.5 g/dL, Hct 58%. SaO2 88% en aire ambiente.',
    steps: [
      { q: '¿Cuál es el paso diagnóstico inicial más apropiado?', options: ['Determinar JAK2 y EPO sérica', 'Iniciar flebotomía de inmediato', 'Atribuirla solo al tabaquismo', 'Iniciar citorreducción empírica'], correct: 0 },
      { q: 'JAK2 resulta negativa y la EPO sérica está elevada. ¿Qué apoya este resultado?', options: ['Policitemia vera con EPO elevada', 'Eritrocitosis secundaria por hipoxia', 'Un tumor productor de EPO renal', 'Eritrocitosis relativa o espuria'], correct: 1 },
      { q: '¿Cuál es el tratamiento más eficaz para esta eritrocitosis?', options: ['Flebotomía terapéutica agresiva con objetivo de hematocrito &lt;45% sin más consideración', 'Agentes estimulantes de la eritropoyesis', 'Oxigenoterapia suplementaria y cese tabáquico, dirigidos a corregir la hipoxia de base', 'Trasplante alogénico de células madre hematopoyéticas'], correct: 2 }
    ],
    explanation: 'Antes de asumir que la EPOC explica toda la eritrocitosis, debe determinarse JAK2 y EPO. JAK2 negativa con EPO elevada apoya eritrocitosis secundaria por hipoxia, consistente con la EPOC y el tabaquismo. El tratamiento más eficaz es corregir la hipoxia de base (oxigenoterapia, cese tabáquico), no la flebotomía agresiva extrapolada de la policitemia vera.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 55 años sin antecedentes relevantes presenta hallazgo incidental de Hb 18.8 g/dL. Gasometría arterial normal, sin hipoxemia. EPO sérica marcadamente elevada. JAK2 negativa. Sin uso de andrógenos ni antecedente de trasplante renal.',
    steps: [
      { q: '¿Cuál es la sospecha diagnóstica más probable dado este patrón?', options: ['Eritrocitosis por hipoxia oculta', 'Policitemia vera JAK2 negativa', 'Producción inapropiada de EPO', 'Eritrocitosis relativa o espuria'], correct: 2 },
      { q: '¿Qué estudio de imagen es más apropiado para investigar esta sospecha?', options: ['Ecografía o TC abdominal y renal', 'Radiografía de tórax en 2 proyecciones', 'Ecocardiograma transtorácico', 'No hace falta ninguna imagen'], correct: 0 },
      { q: 'Se identifica una masa renal sospechosa. ¿Cuál es el tratamiento definitivo de la eritrocitosis asociada?', options: ['Flebotomía terapéutica de por vida sin tratar el tumor', 'Quimioterapia citorreductora tipo policitemia vera', 'Inhibidor de la enzima convertidora de angiotensina', 'Resección quirúrgica del tumor identificado'], correct: 3 }
    ],
    explanation: 'EPO elevada sin hipoxemia y sin otra causa identificable sugiere producción inapropiada de EPO, posiblemente por un tumor. La ecografía/TC abdominal-renal es el estudio dirigido apropiado (carcinoma de células renales es la causa más frecuente). Identificada la masa, la resección quirúrgica es el tratamiento definitivo y curativo de la eritrocitosis asociada.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 22 años presenta eritrocitosis detectada desde la adolescencia. Su padre y un tío paterno tuvieron un cuadro similar sin diagnóstico claro. EPO sérica baja-normal. JAK2 negativa. Sin hipoxemia, sin uso de fármacos, sin masa tumoral en el estudio de imagen.',
    steps: [
      { q: '¿Qué categoría de causa se sospecha dado el inicio temprano y el antecedente familiar?', options: ['Eritrocitosis relativa/espuria', 'Eritrocitosis congénita/hereditaria', 'Producción inapropiada de EPO por un tumor no detectado', 'Policitemia vera de inicio pediátrico'], correct: 1 },
      { q: 'Dado que la EPO sérica es baja-normal pese a la eritrocitosis, ¿qué mutación específica se debe considerar?', options: ['Mutación de VHL (policitemia de Chuvash), que típicamente eleva la EPO', 'Mutación JAK2 V617F, ya descartada', 'Mutación de TMPRSS6', 'Mutación de ganancia de función del receptor de eritropoyetina (EPOR)'], correct: 3 },
      { q: '¿Cuál es el manejo más apropiado de este paciente?', options: ['Soporte según síntomas', 'Trasplante alogénico inmediato', 'Citorreducción tipo policitemia vera', 'No requiere seguimiento alguno'], correct: 0 }
    ],
    explanation: 'El inicio temprano con antecedente familiar sugiere una causa congénita/hereditaria. La EPO baja-normal (a diferencia de la elevada en VHL) orienta hacia una mutación de ganancia de función de EPOR. El manejo es de soporte según síntomas, sin tratamiento dirigido al defecto genético, con flebotomía solo si es sintomático y con cautela.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 50 años con obesidad, hipertensión arterial y tabaquismo activo presenta Hct 54%. Refiere somnolencia diurna marcada y su pareja reporta ronquido intenso con pausas respiratorias observadas durante el sueño.',
    steps: [
      { q: '¿Cuál es la sospecha inicial más razonable dado el perfil clínico (obesidad, hipertensión, tabaquismo)?', options: ['Gaisböck, pero investigar otra causa', 'Policitemia vera ya confirmada', 'Eritrocitosis congénita del adulto', 'Hallazgo sin relevancia clínica'], correct: 0 },
      { q: 'Dados los síntomas de somnolencia diurna y las pausas respiratorias observadas, ¿qué estudio es prioritario?', options: ['Repetir la biometría en 6 meses', 'Biopsia de médula ósea de entrada', 'Polisomnografía nocturna', 'Angio-TC de tórax urgente'], correct: 2 },
      { q: 'La polisomnografía confirma apnea obstructiva del sueño grave. ¿Cómo cambia esto el diagnóstico y manejo?', options: ['No cambia el diagnóstico ya establecido', 'Parte puede ser verdadera; indicar CPAP', 'Indica iniciar citorreducción de inmediato', 'Confirma que es policitemia vera'], correct: 1 }
    ],
    explanation: 'El perfil clínico sugiere eritrocitosis relativa/espuria, pero debe investigarse activamente apnea obstructiva del sueño, frecuente en este mismo perfil de paciente. Los síntomas descritos justifican polisomnografía prioritaria. Confirmada la apnea grave, la eritrocitosis puede ser en parte verdadera (por hipoxia intermitente), y el CPAP es el tratamiento dirigido apropiado.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 60 años sin antecedentes relevantes presenta trombosis venosa profunda de miembro inferior. Se documenta incidentalmente Hb 17.8 g/dL. No se había estudiado previamente el origen de una eritrocitosis, dado que nunca se había medido antes.',
    steps: [
      { q: '¿Cuál es el paso más apropiado tras confirmar la trombosis venosa profunda y el hallazgo incidental de eritrocitosis?', options: ['Ignorar la eritrocitosis por ahora', 'Iniciar citorreducción sin confirmar', 'Indicar flebotomía de inmediato', 'Completar el diferencial diagnóstico'], correct: 3 },
      { q: 'JAK2 resulta positiva. ¿Cuál es el diagnóstico más probable?', options: ['Eritrocitosis por hipoxia crónica', 'Policitemia vera con trombosis', 'Eritrocitosis relativa o espuria', 'Tumor productor de eritropoyetina'], correct: 1 },
      { q: '¿Cuál es la implicación de este hallazgo para el manejo a largo plazo?', options: ['Solo la anticoagulación estándar', 'Vigilancia sin tratamiento adicional', 'Manejo específico de policitemia vera', 'Confirma que es relativa o espuria'], correct: 2 }
    ],
    explanation: 'Ante una eritrocitosis nunca antes estudiada que se presenta con trombosis, debe completarse el diferencial (JAK2/EPO) antes de atribuir el evento solo a un episodio aislado. JAK2 positiva confirma policitemia vera, con la trombosis como posible manifestación inicial. Esto implica manejo específico de policitemia vera, no solo el manejo estándar de la trombosis.'
  }
];

export const flashcards = [
  { front: 'Diferencia fundamental: eritrocitosis secundaria vs. policitemia vera', back: 'Secundaria: reactiva, JAK2 negativa, EPO-dependiente. PV: neoplasia clonal, JAK2 positiva, EPO baja.' },
  { front: 'Causa más frecuente de eritrocitosis secundaria', back: 'Enfermedad pulmonar crónica hipoxemiante y apnea obstructiva del sueño.' },
  { front: 'Vía HIF-EPO', back: 'Hipoxia tisular → estabiliza HIF → transcripción del gen de EPO → proliferación eritroide.' },
  { front: 'Por qué el tabaquismo produce eritrocitosis pese a SaO2 normal', back: 'Carboxihemoglobina reduce liberación tisular de O2; el oxímetro de pulso no la detecta.' },
  { front: 'EPO sérica en policitemia vera', back: 'Baja/indetectable (retroalimentación negativa por eritrocitosis clonal autónoma).' },
  { front: 'Combinación JAK2/EPO más sugestiva de eritrocitosis secundaria', back: 'JAK2 negativa + EPO normal/alta.' },
  { front: 'Criterios OMS 2016 de eritrocitosis', back: 'Hb &gt;16.5 g/dL (varón) / &gt;16 g/dL (mujer), o Hct &gt;49%/48%.' },
  { front: 'Tumor más frecuente productor de EPO', back: 'Carcinoma de células renales.' },
  { front: 'Mecanismo de la eritrocitosis postrasplante renal', back: 'EPO producida por el injerto sin la regulación fisiológica del riñón nativo previo.' },
  { front: 'Tratamiento de la eritrocitosis postrasplante renal', back: 'IECA o ARA-II, eficaces para reducir el hematocrito.' },
  { front: 'Fármaco causa reconocida de eritrocitosis', back: 'Terapia de reemplazo de testosterona (andrógenos).' },
  { front: 'EPO en la mutación de EPOR (ganancia de función)', back: 'Baja-normal, pese a la eritrocitosis (señalización constitutiva del receptor).' },
  { front: 'Policitemia de Chuvash: mecanismo', back: 'Mutación VHL, impide degradación de HIF pese a oxigenación adecuada → EPO elevada.' },
  { front: 'Hemoglobina de alta afinidad: efecto', back: 'Reduce liberación tisular de O2 pese a saturación normal-alta → hipoxia funcional.' },
  { front: 'Eritrocitosis relativa/espuria (Gaisböck)', back: 'Hematocrito elevado por volumen plasmático reducido; NO hay verdadero aumento de masa eritrocitaria.' },
  { front: 'Perfil clásico del síndrome de Gaisböck', back: 'Varón de edad media, obesidad, hipertensión, tabaquismo.' },
  { front: 'Flebotomía en eritrocitosis relativa/espuria', back: 'NO indicada; no hay verdadera masa eritrocitaria excesiva.' },
  { front: 'Causa a buscar activamente en perfil de Gaisböck', back: 'Apnea obstructiva del sueño (mismo perfil de paciente).' },
  { front: 'Hallazgos que orientan a policitemia vera sobre eritrocitosis secundaria', back: 'Prurito acuagénico, esplenomegalia, eritromelalgia, leucocitosis/trombocitosis.' },
  { front: 'Mecanismo del riesgo trombótico por hematocrito elevado', back: 'Aumento no lineal de la viscosidad sanguínea, reduce flujo microvascular.' },
  { front: 'Por qué el riesgo trombótico es menor en eritrocitosis secundaria vs. PV', back: 'Sin activación plaquetaria/leucocitaria clonal adicional.' },
  { front: 'Riesgo de flebotomía sin corregir hipoxia de base', back: 'Reduce transporte de O2 sin mejorar oxigenación tisular real.' },
  { front: 'Complicación de flebotomía repetida', back: 'Ferropenia inducida por depleción de depósitos de hierro.' },
  { front: 'Medida diagnóstica central antes de cualquier tratamiento', back: 'Determinar JAK2 y EPO sérica en toda eritrocitosis.' },
  { front: 'Riesgo de atribuir eritrocitosis solo al tabaquismo', back: 'Pasar por alto una causa concomitante tratable (tumor productor de EPO, apnea del sueño).' },
  { front: 'Estudio de rutina en toda eritrocitosis nueva', back: 'JAK2 y EPO sérica, incluso con causa aparente evidente.' },
  { front: 'Estándar de referencia histórico: eritrocitosis verdadera vs. relativa', back: 'Masa eritrocitaria y volumen plasmático por dilución isotópica.' }
];
