// topics/neumonia/study.js: Autoevaluacion de Neumonia.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// 48 subpreguntas (30 sueltas + 6 cascadas de 3 pasos) y 32 tarjetas.
// Distribucion de `correct` en el banco completo: 12, 11, 12 y 13 por posicion.
// Sin em dash (ver [[feedback-no-em-dash]]). Texto sin acentos.

export const quiz = [
  { q: 'Que se necesita para poder hablar de neumonia y no de infeccion respiratoria baja?', options: ['Un cultivo de esputo con germen identificado', 'Una proteina C reactiva por encima de 100', 'Un infiltrado en la imagen de torax', 'Una saturacion por debajo del 92%'], correct: 2, explanation: 'El diagnostico exige clinica compatible mas infiltrado en la radiografia o, en centros con experiencia, en la ecografia pulmonar. El cultivo es positivo en una minoria de los casos y los reactantes no distinguen bien entre bronquitis y neumonia.', dificultad: 'facil' },
  { q: 'Que componentes integran el CURB-65?', options: ['Confusion, urea, respiraciones, presion arterial y edad', 'Confusion, urea, radiografia, presion arterial y edad', 'Comorbilidad, urea, respiraciones, presion arterial y edad', 'Confusion, urea, respiraciones, procalcitonina y edad'], correct: 0, explanation: 'Cada criterio suma un punto: confusion nueva, nitrogeno ureico mayor de 19 mg/dL, frecuencia respiratoria de 30 o mas, sistolica menor de 90 o diastolica de 60 o menos, y edad de 65 a&#241;os o mas. No incluye la saturacion, que es su principal carencia.', dificultad: 'facil' },
  { q: 'Por que prefieren las guias el PSI frente al CURB-65?', options: ['Porque incluye la saturacion de oxigeno', 'Porque se calcula sin datos de laboratorio', 'Porque predice mejor la etiologia bacteriana', 'Porque identifica mejor al paciente de bajo riesgo'], correct: 3, explanation: 'Su fuerza esta en las clases I y II, que permiten dar el alta con seguridad. Su punto debil es el contrario: al puntuar sobre todo edad y comorbilidad, puede infravalorar a un adulto joven sin antecedentes que llega realmente grave.', dificultad: 'intermedio' },
  { q: 'Cuantos criterios se necesitan para definir una neumonia grave segun ATS/IDSA?', options: ['Dos criterios mayores o cuatro menores', 'Un criterio mayor o tres menores', 'Un criterio mayor o dos menores', 'Dos criterios mayores o dos menores'], correct: 1, explanation: 'Los mayores son la ventilacion mecanica y el choque septico con vasopresores, y cualquiera de los dos basta. Los menores son nueve, entre ellos la frecuencia respiratoria de 30 o mas, la PaO2/FiO2 de 250 o menos y los infiltrados multilobares.', dificultad: 'intermedio' },
  { q: 'Cual de estos hallazgos es un criterio menor de neumonia grave?', options: ['La leucocitosis por encima de 20000', 'La fiebre por encima de 39 grados', 'La leucopenia por debajo de 4000', 'La taquicardia por encima de 120'], correct: 2, explanation: 'La leucopenia y la hipotermia enga&#241;an porque parecen menos alarmantes que la leucocitosis y la fiebre alta, y sin embargo traducen una respuesta inflamatoria desregulada. Ninguna de las otras tres figura entre los nueve criterios menores.', dificultad: 'dificil' },
  { q: 'Por que se abandono la categoria de neumonia asociada a cuidados sanitarios?', options: ['Porque no existia consenso sobre su definicion temporal', 'Porque se solapaba con la neumonia nosocomial', 'Porque las tasas de mortalidad no diferian del resto', 'Porque no predecia bien la presencia de resistencias'], correct: 3, explanation: 'Agrupaba a pacientes de residencias, en dialisis o con ingresos recientes y llevaba a tratarlos con carbapenemico y vancomicina. Hoy la cobertura ampliada se decide por factores de riesgo individuales y por la epidemiologia local, no por la procedencia del paciente.', dificultad: 'intermedio' },
  { q: 'Que dato justifica cubrir SARM o Pseudomonas en una neumonia comunitaria?', options: ['El aislamiento previo del germen en via respiratoria', 'La procedencia de una residencia de mayores', 'El tratamiento con dialisis cronica ambulatoria', 'La edad superior a los 80 a&#241;os con comorbilidad'], correct: 0, explanation: 'Junto con el ingreso reciente con antibiotico intravenoso ponderado segun la epidemiologia local. Las otras tres son precisamente las situaciones que definian la desaparecida categoria de neumonia asociada a cuidados sanitarios y que ya no bastan por si solas.', dificultad: 'intermedio' },
  { q: 'Que hay que hacer si se amplia la cobertura empirica a SARM o a Pseudomonas?', options: ['Mantenerla los 7 dias completos de tratamiento', 'Cultivar y desescalar a las 48 a 72 horas', 'A&#241;adir un aminoglucosido durante las primeras 72 horas', 'Repetir la radiografia antes de retirar el antibiotico'], correct: 1, explanation: 'Ampliar sin desescalar es la peor de las combinaciones posibles y la mas frecuente en la practica. Los cultivos se toman antes de la primera dosis, sin retrasarla, y si el germen no aparece se estrecha el espectro.', dificultad: 'intermedio' },
  { q: 'Cual es el tratamiento empirico de una neumonia que ingresa en planta sin criterios de gravedad?', options: ['Amoxicilina oral a dosis altas en monoterapia', 'Carbapenemico mas vancomicina intravenosos', 'Cotrimoxazol mas corticoide sistemico', 'Betalactamico mas macrolido, o fluoroquinolona sola'], correct: 3, explanation: 'La combinacion con macrolido es la preferida por su cobertura de los germenes atipicos y por su posible efecto inmunomodulador. La amoxicilina sola se reserva al ambulatorio sano, y la cobertura de amplio espectro exige factores de riesgo concretos.', dificultad: 'facil' },
  { q: 'Que aporta la ecografia pulmonar segun la guia de 2026?', options: ['Sustituye a la tomografia en la neumonia complicada o grave', 'Permite identificar el germen responsable en el esputo', 'Es alternativa a la radiografia donde hay experiencia', 'Descarta la neumonia si el estudio resulta normal'], correct: 2, explanation: 'Es mas sensible que la radiografia simple para la consolidacion periferica, no irradia y se hace a pie de cama. Depende por completo del explorador y no valora bien lo que no llega a la pleura, de modo que un estudio normal no descarta nada.', dificultad: 'intermedio' },
  { q: 'En que paciente con neumonia y prueba de virus positiva se puede prescindir del antibiotico?', options: ['En el ambulatorio sin comorbilidad', 'En el ingresado sin criterios de gravedad', 'En el ambulatorio con comorbilidad controlada', 'En cualquiera con radiografia poco extensa'], correct: 0, explanation: 'Es el unico escenario en el que la guia de 2026 lo sugiere. En el ambulatorio con comorbilidad y en todo paciente ingresado, grave o no, se mantiene por el riesgo de coinfeccion bacteriana, que es la que explica buena parte de la mortalidad de la gripe.', dificultad: 'intermedio' },
  { q: 'Cual es la duracion sugerida del antibiotico en la neumonia no grave que alcanza estabilidad?', options: ['Diez dias en todos los casos', 'Menos de 5 dias, con un minimo de 3', 'Siete dias contados desde el ingreso', 'Hasta la normalizacion de la radiografia'], correct: 1, explanation: 'Es una de las novedades de la guia de 2026, que se aparta del clasico minimo de 5 dias. En la neumonia grave, en cambio, la recomendacion es fuerte a favor de 5 dias o mas, porque un tratamiento insuficiente en ese grupo puede costar la vida.', dificultad: 'intermedio' },
  { q: 'Cual es la recomendacion actual sobre el corticoide sistemico en la neumonia?', options: ['Se administra en toda neumonia que requiere ingreso', 'Se administra solo en la neumonia de origen gripal', 'Se administra en la grave, no en la no grave', 'Se administra solo si hay derrame paraneumonico asociado'], correct: 2, explanation: 'La recomendacion en contra en la neumonia no grave es fuerte, y su motivo es evitar la hiperglucemia y el resto de efectos adversos. En la grave se sugiere a favor, apoyada en el ensayo CAPE COD, con la excepcion explicita de la neumonia gripal.', dificultad: 'intermedio' },
  { q: 'Que neumonia grave queda EXCLUIDA de la recomendacion de corticoide?', options: ['La causada por Legionella pneumophila', 'La causada por Streptococcus pneumoniae', 'La causada por Pseudomonas aeruginosa', 'La causada por el virus de la gripe'], correct: 3, explanation: 'La guia lo dice de forma explicita en la propia recomendacion. En la neumonia gripal el corticoide se ha asociado a mayor replicacion viral, infecciones secundarias y peor evolucion, a diferencia de lo observado en la COVID-19 con necesidad de oxigeno.', dificultad: 'dificil' },
  { q: 'Cuando se administra oseltamivir a un paciente ingresado con gripe?', options: ['Solo si lleva menos de 48 horas de sintomas', 'Con independencia del tiempo de evolucion', 'Solo si tiene factores de riesgo de complicacion', 'Solo si la radiografia muestra infiltrados bilaterales'], correct: 1, explanation: 'El beneficio es mayor cuanto mas precoz sea el inicio, pero en el paciente hospitalizado se pauta igualmente aunque hayan pasado mas de dos dias. El retraso del antiviral se asocia de forma consistente a peor evolucion.', dificultad: 'intermedio' },
  { q: 'Que papel tiene la procalcitonina al inicio de una neumonia?', options: ['No debe usarse para decidir si se inicia el antibiotico', 'Sustituye al hemocultivo en el paciente ingresado', 'Distingue la neumonia viral de la bacteriana', 'Determina la duracion exacta del tratamiento'], correct: 0, explanation: 'Un valor bajo no descarta una neumonia bacteriana, y usarla para no tratar ha producido retrasos peligrosos. Su lugar esta en el seguimiento, ayudando a acortar la duracion junto con la evolucion clinica, nunca en la decision inicial.', dificultad: 'intermedio' },
  { q: 'En que paciente con neumonia comunitaria estan indicados los hemocultivos?', options: ['En todo paciente que consulta con fiebre alta', 'En todo paciente que requiere ingreso hospitalario', 'En todo paciente mayor de 65 a&#241;os con comorbilidad', 'En la neumonia grave y si se amplia la cobertura'], correct: 3, explanation: 'En el resto la rentabilidad es baja y los falsos positivos generan tratamiento innecesario y estancias mas largas. Se extraen antes de la primera dosis, pero sin retrasarla en el paciente septico, donde cada hora cuenta.', dificultad: 'intermedio' },
  { q: 'Cuando se considera nosocomial una neumonia?', options: ['Cuando aparece en las primeras 24 horas del ingreso', 'Cuando el paciente procede de una residencia', 'Cuando aparece 48 horas o mas despues del ingreso', 'Cuando se aisla un germen multirresistente'], correct: 2, explanation: 'Y siempre que no estuviera incubandose al llegar. Antes de ese plazo la neumonia es comunitaria por mucho que el paciente este hospitalizado, y se trata como tal: es una de las distinciones que mas se falla y la que decide todo el esquema antibiotico.', dificultad: 'facil' },
  { q: 'Cuando se considera que una neumonia esta asociada a la ventilacion mecanica?', options: ['Cuando aparece durante la primera hora de intubacion', 'Cuando aparece mas de 48 horas despues de la intubacion', 'Cuando aparece en cualquier momento del ingreso en la unidad', 'Cuando aparece tras la retirada del tubo endotraqueal'], correct: 1, explanation: 'El mecanismo es la microaspiracion alrededor del neumotaponamiento, que no sella la via aerea, sobre un pulmon con el aclaramiento mucociliar abolido. La biopelicula de la superficie interna del tubo actua como reservorio permanente.', dificultad: 'intermedio' },
  { q: 'Cual es la duracion habitual del antibiotico en la neumonia nosocomial?', options: ['7 dias', '3 dias', '14 dias', '21 dias'], correct: 0, explanation: 'Los estudios comparativos no encontraron ventaja en prolongarla, y si mas resistencias y mas efectos adversos. Se acompa&#241;a de desescalada guiada por los cultivos y por la evolucion clinica a las 48 a 72 horas.', dificultad: 'intermedio' },
  { q: 'Que separa a la neumonitis quimica de la neumonia por aspiracion?', options: ['La presencia de fiebre en el momento inicial', 'El germen aislado en el cultivo de esputo', 'La localizacion del infiltrado en la radiografia', 'El tiempo transcurrido desde el episodio'], correct: 3, explanation: 'La neumonitis empieza en minutos u horas y mejora en 24 a 48; la neumonia tarda dias en aparecer y empeora. Esa diferencia temporal es lo que decide si hay que dar antibiotico, porque la neumonitis es una quemadura acida y no una infeccion.', dificultad: 'intermedio' },
  { q: 'Cual es el tratamiento inicial de una neumonitis por aspiracion de contenido gastrico?', options: ['Amoxicilina-clavulanico durante siete dias', 'Corticoide sistemico a dosis altas', 'Soporte y observacion, sin antibiotico', 'Clindamicina por la cobertura anaerobia'], correct: 2, explanation: 'Es una quemadura quimica esteril y el antibiotico no aporta nada al principio, ademas de seleccionar resistencias. Se aspira la via aerea si hay material visible, se da oxigeno y se observa 48 horas: si entonces aparecen fiebre y leucocitosis, se trata como neumonia.', dificultad: 'intermedio' },
  { q: 'Que conducta corresponde a la cobertura anaerobia en la neumonia por aspiracion?', options: ['A&#241;adirla siempre que la aspiracion sea presenciada', 'Reservarla para el absceso pulmonar y el empiema', 'A&#241;adirla en todo paciente con disfagia conocida', 'Reservarla para los pacientes institucionalizados'], correct: 1, explanation: 'La microbiologia ha cambiado y hoy predominan los germenes que ya causan la neumonia comunitaria, con menos peso de los anaerobios estrictos del que se les atribuia. Se trata como una neumonia comunitaria o nosocomial segun donde se adquirio.', dificultad: 'dificil' },
  { q: 'Que hallazgo define el absceso pulmonar en la imagen?', options: ['La cavitacion con nivel hidroaereo', 'El infiltrado alveolar multilobar', 'El derrame pleural loculado', 'El patron en vidrio deslustrado difuso'], correct: 0, explanation: 'Se acompa&#241;a de expectoracion abundante y de mal olor, y en la evolucion prolongada de dedos en palillo de tambor. Obliga a descartar una obstruccion bronquial o un cuerpo extra&#241;o subyacente con tomografia o broncoscopia.', dificultad: 'facil' },
  { q: 'Que exploracion hay que hacer en toda neumonia del anciano con sospecha de aspiracion?', options: ['Una gammagrafia de ventilacion y perfusion', 'Una manometria esofagica de alta resolucion', 'Un cribado de disfagia a pie de cama', 'Una tomografia de senos paranasales'], correct: 2, explanation: 'La prueba de deglucion de agua es el cribado inicial, y si es positiva se modifican texturas y se valora por logopedia antes del alta. Sin corregir el mecanismo, el cuadro se repite, y esa es la causa mas frecuente de reingreso en este grupo.', dificultad: 'intermedio' },
  { q: 'Que complicacion se pasa por alto con mas frecuencia tras un ingreso por neumonia?', options: ['La fibrosis pulmonar residual', 'La insuficiencia suprarrenal por el corticoide', 'La colitis por Clostridioides difficile', 'El evento cardiovascular en los 30 dias siguientes'], correct: 3, explanation: 'Uno de cada cuatro a cinco pacientes sufre un infarto, una arritmia o una insuficiencia cardiaca durante el ingreso o poco despues, y el exceso de riesgo persiste durante a&#241;os. Explica buena parte de la mortalidad al a&#241;o, muy superior a la hospitalaria.', dificultad: 'dificil' },
  { q: 'A quien hay que hacer radiografia de control tras una neumonia resuelta?', options: ['Al fumador y al mayor de 50 a&#241;os', 'A todo paciente que ha requerido ingreso', 'A todo paciente tratado con antibiotico intravenoso', 'A quien ha tenido derrame paraneumonico'], correct: 0, explanation: 'Y a quien persiste sintomatico, para descartar una neoplasia subyacente que se manifesto como neumonia obstructiva. En el resto de los pacientes con resolucion clinica completa, el control radiologico sistematico no aporta nada.', dificultad: 'intermedio' },
  { q: 'Que limitacion tiene el antigeno urinario de Legionella?', options: ['Se negativiza en las primeras 24 horas', 'Detecta solo el serogrupo 1', 'Requiere muestra de orina de 24 horas', 'Da falsos positivos con el neumococo'], correct: 1, explanation: 'Un resultado negativo no descarta la legionelosis. Ademas permanece positivo durante semanas, de modo que un resultado positivo no siempre corresponde al episodio actual. Sigue siendo util porque permite desescalar a tratamiento dirigido.', dificultad: 'dificil' },
  { q: 'Que prueba tiene prioridad ante una neumonia en un paciente inmunodeprimido?', options: ['La serologia frente a germenes atipicos', 'El cultivo seriado de esputo espontaneo', 'La tomografia de torax con broncoscopia precoz', 'La prueba de la tuberculina y su repeticion'], correct: 2, explanation: 'La radiografia es insuficiente y el abanico etiologico se amplia a Pneumocystis, hongos, micobacterias y virus. El diagnostico microbiologico dirigido mediante lavado broncoalveolar cambia el tratamiento mucho mas a menudo que en el inmunocompetente.', dificultad: 'intermedio' },
  { q: 'Cuando se a&#241;ade corticoide al cotrimoxazol en la neumonia por Pneumocystis?', options: ['Si hay infiltrados bilaterales en la radiografia', 'Si el paciente tiene menos de 200 linfocitos CD4', 'Si hay fiebre mantenida mas de 72 horas', 'Si la PaO2 es menor de 70 mmHg'], correct: 3, explanation: 'La lisis del microorganismo por el tratamiento produce un empeoramiento inflamatorio en los primeros dias, que el corticoide previene. La indicacion es gasometrica, y tambien vale un gradiente alveolo-arterial de oxigeno de 35 mmHg o mayor.', dificultad: 'dificil' },

  { type: 'cascade', vignette: 'Varon de 74 a&#241;os con EPOC acude por fiebre, tos productiva y disnea de 3 dias. Confuso segun su familia. Frecuencia respiratoria de 32, presion arterial de 96/58, frecuencia cardiaca de 108, saturacion del 89% en aire ambiente. Nitrogeno ureico de 28 mg/dL. La radiografia muestra consolidacion en dos lobulos.', steps: [
    { q: 'Cual es su puntuacion CURB-65?', options: ['5 puntos', '2 puntos', '3 puntos', '4 puntos'], correct: 0 },
    { q: 'Que hay que valorar de inmediato con esos datos?', options: ['El alta con antibiotico oral y control en 48 horas', 'La toracocentesis diagnostica del derrame', 'El traslado a una unidad de hospitalizacion a domicilio', 'El ingreso en cuidados intensivos'], correct: 3 },
    { q: 'Que estudio microbiologico corresponde antes de la primera dosis?', options: ['Ninguno: la rentabilidad es baja en este perfil', 'Hemocultivos, esputo y antigenos urinarios', 'Solo cultivo de esputo si expectora bien', 'Serologias de germenes atipicos pareadas'], correct: 1 }
  ], explanation: 'Suma un punto por cada criterio: confusion, nitrogeno ureico mayor de 19, frecuencia respiratoria de 30 o mas, presion diastolica de 60 o menos y edad de 65 o mas. Con 5 puntos y varios criterios menores de gravedad (frecuencia respiratoria, confusion, uremia, infiltrados multilobares), corresponde valorar cuidados intensivos de forma precoz, no tras el deterioro, y extraer cultivos completos antes de la primera dosis sin retrasarla.', dificultad: 'facil' },

  { type: 'cascade', vignette: 'Mujer de 45 a&#241;os sin antecedentes, con fiebre, tos y dolor pleuritico de 2 dias. Frecuencia respiratoria de 20, presion arterial de 124/76, saturacion del 96%. La radiografia muestra consolidacion en el lobulo inferior derecho. La prueba molecular respiratoria detecta virus de la gripe A. Se encuentra bien y tolera la via oral.', steps: [
    { q: 'Cual es la conducta mas apropiada respecto al antibiotico?', options: ['A&#241;adir cobertura de SARM por la gripe', 'Ingresar para antibiotico intravenoso', 'No prescribir antibiotico y tratar el virus', 'Pautar amoxicilina-clavulanico siete dias'], correct: 2 },
    { q: 'Que conducta corresponde si tuviera una diabetes mal controlada?', options: ['Repetir la radiografia en 24 horas antes de decidir', 'Prescribir antibiotico por el riesgo de coinfeccion', 'Prescindir igualmente del antibiotico', 'Solicitar hemocultivos antes de decidir'], correct: 1 },
    { q: 'Cuanto tiempo de antibiotico corresponderia si finalmente se prescribe y mejora?', options: ['Menos de 5 dias, con un minimo de 3', 'Diez dias completos desde el inicio', 'Siete dias contados desde la desaparicion de la fiebre', 'Hasta la resolucion radiologica del infiltrado'], correct: 0 }
  ], explanation: 'La guia de 2026 sugiere no prescribir antibiotico solo en el paciente ambulatorio SIN comorbilidad con prueba viral positiva, que es exactamente este caso. La presencia de comorbilidad invierte la recomendacion por el riesgo de coinfeccion bacteriana. Y en el ambulatorio que alcanza estabilidad clinica, la duracion sugerida es menor de 5 dias con un minimo de 3, frente al clasico minimo de 5.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Varon de 62 a&#241;os ingresado en cuidados intensivos, intubado desde hace 6 dias por un politraumatismo. Aparece fiebre de 38.6 grados, secreciones purulentas abundantes, leucocitos de 17000 y un nuevo infiltrado en el lobulo inferior izquierdo. Ha necesitado subir la fraccion inspirada de oxigeno. Recibio ceftriaxona intravenosa hace 2 meses por una infeccion urinaria.', steps: [
    { q: 'Como se clasifica esta neumonia?', options: ['Comunitaria de presentacion tardia', 'Por aspiracion no presenciada', 'Nosocomial de planta convencional', 'Asociada a la ventilacion mecanica'], correct: 3 },
    { q: 'Que hay que hacer antes de cambiar el antibiotico?', options: ['Tomar muestra respiratoria para cultivo cuantitativo', 'Repetir la radiografia a las 24 horas', 'Solicitar antigenos urinarios de neumococo y Legionella', 'Retirar el tubo endotraqueal y reintubar'], correct: 0 },
    { q: 'Que justifica a&#241;adir cobertura de SARM en su caso?', options: ['La duracion de la ventilacion mecanica', 'El aislamiento del germen en un companero de unidad', 'El antibiotico intravenoso en los ultimos 90 dias', 'La presencia de secreciones purulentas abundantes'], correct: 2 }
  ], explanation: 'Aparece mas de 48 horas despues de la intubacion, de modo que es una neumonia asociada a la ventilacion. La muestra respiratoria para cultivo cuantitativo debe obtenerse ANTES de modificar el antibiotico, porque despues pierde valor. El antibiotico intravenoso en los 90 dias previos es uno de los criterios que justifican la cobertura empirica de SARM, junto con la prevalencia local alta o desconocida y el alto riesgo de muerte.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Mujer de 81 a&#241;os con demencia avanzada, encamada, con antecedente de ictus y disfagia conocida. La familia refiere que se atraganto durante la comida hace 3 dias. Ahora presenta fiebre de 38.2 grados, tos y consolidacion en el segmento posterior del lobulo superior derecho. No hay cavitacion.', steps: [
    { q: 'Cual es el diagnostico mas probable?', options: ['Neumonitis quimica por aspiracion acida', 'Neumonia por aspiracion', 'Absceso pulmonar en fase inicial', 'Neumonia nosocomial de la residencia'], correct: 1 },
    { q: 'Que conducta corresponde con el antibiotico?', options: ['No pautar antibiotico y observar 48 horas', 'A&#241;adir clindamicina por la cobertura anaerobia', 'Tratar como una neumonia comunitaria', 'Iniciar meropenem por el riesgo de resistencia'], correct: 2 },
    { q: 'Que medida evita mejor la recidiva?', options: ['La profilaxis antibiotica de mantenimiento', 'La colocacion de una gastrostomia percutanea', 'El tratamiento del reflujo con inhibidores de bomba', 'La valoracion de la disfagia y el ajuste de texturas'], correct: 3 }
  ], explanation: 'Han pasado 3 dias desde la aspiracion y hay fiebre con consolidacion en zona declive: eso es neumonia por aspiracion y no neumonitis quimica, que habria empezado en minutos y ya estaria mejorando. La cobertura anaerobia de rutina ya no se recomienda y se reserva al absceso y al empiema. La gastrostomia no elimina el riesgo de aspiracion, mientras que el ajuste de texturas y la valoracion logopedica si reducen la recidiva.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Varon de 58 a&#241;os con trasplante renal hace 5 meses, en tratamiento con tacrolimus, micofenolato y prednisona. Consulta por disnea de esfuerzo progresiva de 2 semanas y febricula. Saturacion del 88% al caminar y del 94% en reposo. La radiografia de torax es practicamente normal. No recibe profilaxis desde hace 2 meses.', steps: [
    { q: 'Que prueba de imagen corresponde solicitar?', options: ['Tomografia de torax de alta resolucion', 'Repetir la radiografia en 48 horas', 'Gammagrafia de ventilacion y perfusion', 'Ecografia pulmonar a pie de cama'], correct: 0 },
    { q: 'Cual es el germen mas probable en este contexto?', options: ['Streptococcus pneumoniae', 'Pneumocystis jirovecii', 'Pseudomonas aeruginosa', 'Legionella pneumophila'], correct: 1 },
    { q: 'Que a&#241;ade al cotrimoxazol si su PaO2 fuera de 62 mmHg?', options: ['Caspofungina intravenosa', 'Pentamidina inhalada', 'Azitromicina oral', 'Corticoide sistemico'], correct: 3 }
  ], explanation: 'La hipoxemia de esfuerzo desproporcionada con radiografia poco llamativa, en un trasplantado dentro de la ventana de infecciones oportunistas y sin profilaxis, es la presentacion clasica de Pneumocystis. La tomografia muestra el vidrio deslustrado difuso que la radiografia no ve, y el diagnostico se confirma con lavado broncoalveolar. Con PaO2 menor de 70 mmHg se a&#241;ade corticoide, porque la lisis del microorganismo empeora la inflamacion en los primeros dias.', dificultad: 'dificil' },

  { type: 'cascade', vignette: 'Varon de 55 a&#241;os ingresado hace 4 dias por neumonia comunitaria del lobulo inferior izquierdo, tratado con ceftriaxona y azitromicina. Persiste febril, con dolor pleuritico y empeoramiento del intercambio gaseoso. La radiografia de control muestra un derrame pleural nuevo de unos 3 cm en decubito lateral.', steps: [
    { q: 'Cual es el siguiente paso mas apropiado?', options: ['Ampliar el antibiotico a piperacilina-tazobactam', 'A&#241;adir corticoide sistemico durante 5 dias', 'Realizar toracocentesis diagnostica', 'Repetir la radiografia en 48 horas'], correct: 2 },
    { q: 'Que otras causas de mala evolucion hay que revisar a la vez?', options: ['La adherencia del paciente al tratamiento oral', 'La dosis de azitromicina y su via de administracion', 'La necesidad de fisioterapia respiratoria intensiva', 'Germen no cubierto, absceso o diagnostico alternativo'], correct: 3 },
    { q: 'Que hallazgo en el liquido obligaria a colocar un drenaje?', options: ['Un pH del liquido pleural menor de 7.20', 'Una proteina total mayor de 3 g/dL', 'Un recuento de linfocitos predominante', 'Una glucosa igual a la del plasma'], correct: 0 }
  ], explanation: 'Todo derrame de mas de 1 cm en decubito lateral en una neumonia que no mejora debe puncionarse, porque el empiema cambia por completo el manejo y no se resuelve con antibiotico solo. La mala evolucion a las 72 horas obliga ademas a replantear el germen, buscar complicaciones locales y reconsiderar el diagnostico. Un pH menor de 7.20, junto con la glucosa baja, la lactato deshidrogenasa alta o el pus franco, define el derrame complicado que requiere drenaje.', dificultad: 'intermedio' }
];

export const flashcards = [
  { front: 'Que hace falta para diagnosticar neumonia', back: 'Clinica compatible MAS infiltrado en la imagen. Sin imagen no es neumonia.' },
  { front: 'Componentes del CURB-65', back: 'Confusion, Urea (nitrogeno ureico mayor de 19), Respiraciones 30 o mas, presion Baja y 65 a&#241;os o mas.' },
  { front: 'Interpretacion del CURB-65', back: '0 a 1 ambulatorio, 2 valorar ingreso, 3 o mas neumonia grave.' },
  { front: 'Por que se prefiere el PSI', back: 'Identifica mejor al paciente de BAJO riesgo que puede irse a casa.' },
  { front: 'Punto debil del PSI', back: 'Infravalora al joven sin comorbilidad, porque puntua sobre todo edad y comorbilidad.' },
  { front: 'Criterios de neumonia grave', back: '1 criterio MAYOR (ventilacion mecanica o choque con vasopresores) o 3 MENORES.' },
  { front: 'Dos criterios menores que enga&#241;an', back: 'Leucopenia menor de 4000 e hipotermia menor de 36 grados: parecen leves y son gravedad.' },
  { front: 'Por que se abandono la categoria de cuidados sanitarios', back: 'No predecia la resistencia y generaba mucho tratamiento de amplio espectro innecesario.' },
  { front: 'Cuando cubrir SARM o Pseudomonas', back: 'Aislamiento previo en via respiratoria o ingreso con antibiotico intravenoso en 90 dias.' },
  { front: 'Regla obligatoria al ampliar la cobertura', back: 'Cultivar antes de la primera dosis y DESESCALAR a las 48 a 72 horas.' },
  { front: 'Empirico del ingresado no grave', back: 'Betalactamico mas macrolido, o fluoroquinolona respiratoria en monoterapia.' },
  { front: 'Empirico del ambulatorio sano', back: 'Amoxicilina a dosis altas o doxiciclina.' },
  { front: 'Novedad de 2026 sobre la imagen', back: 'La ecografia pulmonar es alternativa aceptable a la radiografia donde hay experiencia.' },
  { front: 'Virus positivo: cuando NO dar antibiotico', back: 'Solo en el paciente ambulatorio SIN comorbilidad.' },
  { front: 'Duracion en la neumonia no grave estable', back: 'Menos de 5 dias, con un minimo de 3 (guia de 2026).' },
  { front: 'Duracion en la neumonia grave', back: '5 dias o mas, con recomendacion FUERTE.' },
  { front: 'Corticoide sistemico en la neumonia', back: 'A favor en la GRAVE, en contra en la no grave. Excluida la neumonia gripal.' },
  { front: 'Oseltamivir en el ingresado con gripe', back: 'Siempre, con independencia del tiempo de evolucion.' },
  { front: 'Procalcitonina al inicio', back: 'NO sirve para decidir si se inicia el antibiotico: un valor bajo no descarta nada.' },
  { front: 'Cuando pedir hemocultivos', back: 'En la neumonia grave y cuando se va a cubrir SARM o Pseudomonas.' },
  { front: 'Definicion de neumonia nosocomial', back: '48 horas o mas tras el ingreso, sin estar incubandose al llegar.' },
  { front: 'Definicion de neumonia asociada a la ventilacion', back: 'Mas de 48 horas despues de la intubacion.' },
  { front: 'Duracion en la neumonia nosocomial', back: '7 dias, con desescalada guiada por cultivos.' },
  { front: 'Lo que guia el empirico de la nosocomial', back: 'El ANTIBIOGRAMA de la propia unidad, no una tabla de un libro.' },
  { front: 'Neumonitis quimica frente a neumonia por aspiracion', back: 'Minutos u horas y mejora, frente a dias y empeora. Solo la segunda lleva antibiotico.' },
  { front: 'Cobertura anaerobia en la aspiracion', back: 'Ya NO de rutina: se reserva al absceso pulmonar y al empiema.' },
  { front: 'Imagen del absceso pulmonar', back: 'Cavitacion con nivel hidroaereo, con expectoracion abundante y de mal olor.' },
  { front: 'Lo que evita la recidiva de la aspiracion', back: 'Cribado de disfagia, ajuste de texturas e higiene bucal. La gastrostomia NO la elimina.' },
  { front: 'Complicacion que mas se pasa por alto', back: 'El evento cardiovascular en los 30 dias siguientes: infarto, arritmia e insuficiencia cardiaca.' },
  { front: 'A quien hacer radiografia de control', back: 'Al fumador, al mayor de 50 a&#241;os y al que sigue sintomatico. No de rutina.' },
  { front: 'Limitacion del antigeno urinario de Legionella', back: 'Detecta solo el serogrupo 1 y permanece positivo semanas.' },
  { front: 'Corticoide en la neumonia por Pneumocystis', back: 'Se a&#241;ade al cotrimoxazol si la PaO2 es menor de 70 mmHg.' }
];

export default { quiz, flashcards };
