// topics/exploracion-respiratoria/study.js — Autoevaluación de Exploración Respiratoria.
// Mismo patrón que exploracion-cardiovascular/study.js: banco único, preguntas sueltas +
// preguntas en cascada sobre una viñeta (retroalimentación consolidada al final).

export const quiz = [
  { q: '¿Cuál es el orden correcto de la exploración respiratoria?', options: ['Auscultación, percusión, palpación, inspección', 'Inspección, palpación, percusión, auscultación (IPPA)', 'Percusión, inspección, auscultación, palpación', 'Palpación, auscultación, inspección, percusión'], correct: 1, explanation: 'El orden clásico IPPA (Inspección, Palpación, Percusión, Auscultación) se mantiene vigente en la exploración respiratoria, a diferencia de la cardiovascular donde la percusión cayó en desuso.', dificultad: 'facil' },
  { q: 'A diferencia de la exploración cardiovascular, ¿por qué la percusión mantiene rendimiento diagnóstico pleno en la exploración respiratoria?', options: ['Porque el corazón no se puede percutir', 'Porque distingue con precisión aire, consolidación y líquido dentro del tórax', 'Porque es más rápida que la auscultación', 'No hay ninguna diferencia real'], correct: 1, explanation: 'La percusión torácica sigue teniendo alto rendimiento porque diferencia con precisión los 3 grandes sustratos posibles bajo la pared torácica: aire (hiperresonancia), consolidación (matidez elástica) y líquido (matidez pétrea).', dificultad: 'intermedio' },
  { q: '¿Por qué se explora primero la cara posterior del tórax?', options: ['Es más cómodo para el explorador', 'Concentra la mayor superficie pulmonar, incluidas ambas bases', 'Porque ahí no hay ruidos cardiacos que interfieran', 'No hay una razón particular'], correct: 1, explanation: 'La cara posterior del tórax tiene la mayor cantidad de parénquima pulmonar accesible, incluidas las bases, por lo que suele explorarse primero y de forma más extensa.', dificultad: 'facil' },
  { q: 'La respiración de Cheyne-Stokes (ciclos crescendo-decrescendo separados por apnea) se explica por:', options: ['Acidosis metabólica compensada', 'Un retraso en la retroalimentación de los quimiorreceptores centrales al CO2, típico de insuficiencia cardiaca o daño cerebral bilateral', 'Lesión pontina aislada', 'Obstrucción mecánica de la vía aérea superior'], correct: 1, explanation: 'El tiempo de circulación prolongado (insuficiencia cardiaca) o el daño cerebral bilateral retrasan la respuesta del centro respiratorio al CO2, generando el patrón oscilante característico.', dificultad: 'dificil' },
  { q: '¿Qué mecanismo explica la respiración de Kussmaul?', options: ['Compensación respiratoria de una acidosis metabólica severa, para eliminar CO2 y elevar el pH', 'Lesión bulbar', 'Insuficiencia cardiaca descompensada', 'Obstrucción de la vía aérea superior'], correct: 0, explanation: 'La respiración de Kussmaul (profunda, rápida, sostenida) es la respuesta compensadora del organismo ante una acidosis metabólica severa (cetoacidosis diabética, acidosis láctica), buscando eliminar CO2.', dificultad: 'intermedio' },
  { q: '¿Qué indica la disociación toracoabdominal (movimiento paradójico del abdomen hacia adentro en inspiración)?', options: ['Un hallazgo normal en decúbito supino', 'Fatiga o claudicación diafragmática inminente, signo de falla respiratoria inminente', 'Acidosis metabólica compensada', 'Derrame pleural leve'], correct: 1, explanation: 'Es uno de los signos físicos de mayor valor para anticipar la necesidad de ventilación mecánica, incluso antes de que se alteren los gases arteriales.', dificultad: 'dificil' },
  { q: 'El tórax en tonel (aumento del diámetro anteroposterior, horizontalización costal) es característico de:', options: ['Cifoescoliosis', 'Atrapamiento aéreo crónico (EPOC/enfisema)', 'Derrame pleural crónico', 'Tuberculosis apical antigua'], correct: 1, explanation: 'El atrapamiento aéreo crónico hiperinsufla el tórax de forma sostenida, aumentando el diámetro anteroposterior y horizontalizando las costillas.', dificultad: 'facil' },
  { q: 'En el tórax inestable (flail chest), ¿por qué el segmento afectado se mueve de forma paradójica?', options: ['Porque el paciente contiene la respiración voluntariamente', 'Porque las fracturas costales múltiples en 2 o más puntos aíslan ese segmento del resto de la caja torácica, desacoplándolo de los cambios de presión intrapleural', 'Porque hay un neumotórax asociado siempre', 'Es un artefacto de la exploración, no un hallazgo real'], correct: 1, explanation: 'El segmento fracturado en múltiples puntos deja de estar mecánicamente acoplado al resto del tórax, así que sigue la presión intrapleural en vez de moverse con la caja torácica: se hunde en inspiración y protruye en espiración.', dificultad: 'dificil' },
  { q: '¿Cómo se explora la expansión torácica y qué magnitud es normal?', options: ['Con el estetoscopio, comparando ambos lados; normal 1 cm', 'Con ambas manos y los pulgares aproximados en la línea media, pidiendo inspiración profunda; normal ~3-5 cm de separación', 'Percutiendo la espalda; normal 8 cm', 'No tiene una técnica estandarizada'], correct: 1, explanation: 'La palpación bimanual con los pulgares aproximados en la línea media es la técnica estándar; la separación simétrica esperada con una inspiración profunda es de aproximadamente 3-5 cm.', dificultad: 'facil' },
  { q: '¿Por qué el frémito táctil AUMENTA sobre una zona de consolidación pulmonar?', options: ['Porque el tejido consolidado, denso y sin aire, transmite mejor las vibraciones que el parénquima aireado normal', 'Porque la consolidación produce más sonido al fonar', 'Porque la consolidación acerca la pared torácica a la vía aérea', 'El frémito nunca aumenta, solo disminuye'], correct: 0, explanation: 'Un sólido (tejido consolidado) transmite el sonido/vibración mejor que un gas (parénquima aireado normal), el mismo principio físico detrás del soplo tubárico y de la broncofonía.', dificultad: 'intermedio' },
  { q: '¿En cuáles 3 condiciones está disminuido o abolido el frémito táctil?', options: ['Neumonía, tuberculosis, asma', 'Derrame pleural, neumotórax, atelectasia obstructiva completa', 'Bronquitis, faringitis, laringitis', 'Fiebre, taquicardia, taquipnea'], correct: 1, explanation: 'En las tres, algo interrumpe la transmisión de la vibración hasta la pared torácica: el líquido (derrame) la amortigua, el aire pleural (neumotórax) no la transmite, y la vía aérea ocluida (atelectasia obstructiva) impide que la vibración generada en la laringe siquiera llegue.', dificultad: 'intermedio' },
  { q: '¿Qué diferencia hay entre la matidez de una consolidación y la de un derrame pleural?', options: ['No hay ninguna diferencia perceptible', 'La consolidación da una matidez elástica; el derrame, una matidez "pétrea", más marcada y sin ningún componente resonante', 'La consolidación siempre es hiperresonante', 'El derrame da hiperresonancia'], correct: 1, explanation: 'La matidez "pétrea" del derrame pleural (por el líquido, que no tiene ningún componente aéreo) es más marcada y característica que la matidez "elástica" de la consolidación (tejido sólido pero aún con cierta estructura alveolar).', dificultad: 'dificil' },
  { q: '¿Qué representa el signo de Skoda?', options: ['Matidez pétrea sobre un derrame', 'Una franja de timpanismo por encima del nivel superior de un derrame pleural, por compresión pasiva del parénquima adyacente', 'Hiperresonancia generalizada en el enfisema', 'Ausencia de frémito en el neumotórax'], correct: 1, explanation: 'El pulmón comprimido pero no colapsado justo por encima del nivel del derrame genera una franja de timpanismo relativo, sin llenarse de líquido — el signo de Skoda.', dificultad: 'dificil' },
  { q: '¿Qué describe la línea de Damoiseau-Ellis?', options: ['El límite horizontal de matidez en una consolidación', 'La curva cóncava hacia arriba y medial del límite superior de matidez en un derrame pleural libre, más alta en la línea axilar', 'El límite de excursión diafragmática normal', 'La distribución del murmullo vesicular normal'], correct: 1, explanation: 'A diferencia del límite horizontal de una consolidación, el derrame pleural libre se distribuye por gravedad con un límite superior curvo, más alto lateralmente (línea axilar) que en la columna o el esternón.', dificultad: 'dificil' },
  { q: '¿Qué caracteriza al murmullo vesicular normal, y por qué tiene ese timbre suave?', options: ['Espiración más larga que inspiración, tono agudo, generado en la tráquea', 'Inspiración más larga e intensa que la espiración, tono grave, porque el parénquima alveolar filtra las frecuencias altas generadas en los bronquios medianos', 'Se ausculta solo sobre la tráquea', 'No tiene relación con el ciclo respiratorio'], correct: 1, explanation: 'El murmullo vesicular se genera en bronquios de mediano calibre, pero el parénquima alveolar circundante actúa como filtro de frecuencias altas, dándole su timbre suave y su predominio inspiratorio.', dificultad: 'intermedio' },
  { q: '¿Dónde es normal auscultar respiración bronquial (tubárica)?', options: ['En ambas bases pulmonares', 'Sobre la tráquea y el manubrio esternal', 'En toda la superficie pulmonar por igual', 'Solo en el ápex izquierdo'], correct: 1, explanation: 'La respiración bronquial, generada por turbulencia directa en la vía aérea grande sin el filtro alveolar, es normal únicamente sobre la tráquea y el manubrio esternal.', dificultad: 'facil' },
  { q: '¿Qué significa auscultar un "soplo tubárico" (ruido bronquial) fuera de la tráquea?', options: ['Un hallazgo normal en personas delgadas', 'Un signo mayor de consolidación: el tejido sin aire alveolar transmite el sonido bronquial directamente hasta la pared torácica', 'Neumotórax', 'Derrame pleural'], correct: 1, explanation: 'Al perderse el filtro alveolar normal (porque el alvéolo está lleno de exudado, no de aire), el sonido bronquial generado en la vía aérea grande se transmite sin atenuar hasta zonas donde normalmente se oiría vesicular.', dificultad: 'intermedio' },
  { q: '¿Qué diferencia principal hay entre sibilancias y roncus?', options: ['Las sibilancias son graves y los roncus agudos', 'Las sibilancias son agudas/musicales por vía aérea pequeña estrechada; los roncus son graves, por secreciones en vía aérea grande, y suelen cambiar con la tos', 'No hay ninguna diferencia real', 'Los roncus solo ocurren en niños'], correct: 1, explanation: 'Las sibilancias reflejan estrechamiento difuso de la vía aérea pequeña (broncoespasmo/edema/moco) y no cambian con la tos; los roncus reflejan secreciones en vía aérea de mayor calibre y sí suelen modificarse al toser.', dificultad: 'intermedio' },
  { q: 'Una sibilancia localizada y fija que no cambia con la tos, en un paciente sin antecedente de asma, debe hacer sospechar:', options: ['Asma leve', 'Obstrucción endobronquial focal (cuerpo extraño, tumor) hasta demostrar lo contrario', 'Bronquitis viral común', 'Un hallazgo normal'], correct: 1, explanation: 'A diferencia de las sibilancias difusas del asma/EPOC, una sibilancia fija y localizada sugiere una obstrucción mecánica puntual de la vía aérea que debe investigarse.', dificultad: 'dificil' },
  { q: '¿Qué distingue a los estertores finos ("velcro") de los gruesos?', options: ['Los finos ocurren al final de la inspiración y no cambian con la tos; los gruesos ocurren en ambas fases y sí se modifican con la tos', 'Los finos son musicales y los gruesos no', 'Los gruesos son exclusivos de la fibrosis pulmonar', 'No hay diferencia clínica entre ambos'], correct: 0, explanation: 'Los estertores finos se generan por apertura súbita de vía aérea/alvéolos colapsados (no cambian con la tos); los gruesos, por aire pasando a través de secreciones en vía aérea grande (sí cambian con la tos).', dificultad: 'intermedio' },
  { q: 'Estertores finos bibasales, persistentes, que NO cambian con la tos, orientan principalmente a:', options: ['Bronquiectasias', 'Fibrosis pulmonar', 'Neumotórax', 'Asma'], correct: 1, explanation: 'El patrón de estertores finos tipo velcro, bibasales y persistentes en el tiempo (sin modificarse con la tos) es característico de la fibrosis pulmonar intersticial.', dificultad: 'intermedio' },
  { q: '¿Cómo se describe clásicamente el roce pleural y qué lo hace desaparecer?', options: ['Musical y agudo; desaparece con broncodilatador', 'Áspero, como "cuero nuevo" o "pisar nieve"; desaparece si se acumula suficiente derrame pleural entre las hojas', 'Grave y rítmico; desaparece con la tos', 'No desaparece bajo ninguna circunstancia'], correct: 1, explanation: 'El roce pleural refleja la fricción directa de las hojas pleurales inflamadas; si se acumula líquido entre ellas, deja de haber fricción directa y el roce desaparece.', dificultad: 'intermedio' },
  { q: '¿Qué es la pectoriloquia áfona?', options: ['La ausencia total de ruidos respiratorios', 'Que la voz susurrada se transmita con una claridad excepcional, distinguiéndose las sílabas, sobre una zona de consolidación', 'Un sinónimo de egofonía', 'Un hallazgo normal en la base pulmonar izquierda'], correct: 1, explanation: 'Normalmente la voz susurrada se filtra y no se distingue con claridad; sobre una consolidación, el tejido sólido transmite incluso el susurro con una nitidez anormal.', dificultad: 'intermedio' },
  { q: '¿Dónde se ausculta característicamente la egofonía positiva?', options: ['En el ápex pulmonar sano', 'En el límite superior de un derrame pleural, donde el pulmón está comprimido pero no completamente consolidado', 'Sobre la tráquea únicamente', 'En cualquier punto de un neumotórax'], correct: 1, explanation: 'La combinación de compresión pulmonar (sin consolidación completa) en el borde superior de un derrame filtra selectivamente ciertas frecuencias de la voz, cambiando el timbre de la "e" a una "a" nasal.', dificultad: 'dificil' },
  { q: 'En el síndrome de derrame pleural masivo, ¿hacia dónde se desvía la tráquea?', options: ['Hacia el lado del derrame', 'Hacia el lado sano (contralateral)', 'No se desvía nunca', 'Depende de la edad del paciente'], correct: 1, explanation: 'Un derrame masivo ocupa espacio y empuja las estructuras mediastínicas, incluida la tráquea, hacia el lado sano — igual que el neumotórax a tensión.', dificultad: 'intermedio' },
  { q: 'A diferencia del derrame pleural y el neumotórax, en la atelectasia obstructiva la tráquea se desvía:', options: ['Hacia el lado sano, igual que en los otros dos síndromes', 'Hacia el lado enfermo, por la pérdida de volumen pulmonar que "atrae" las estructuras mediastínicas', 'Nunca se desvía en la atelectasia', 'Solo se desvía si hay fiebre asociada'], correct: 1, explanation: 'La atelectasia colapsa y reduce el volumen de ese pulmón, por lo que el mediastino y la tráquea son atraídos hacia el lado afectado — el patrón opuesto al del derrame o el neumotórax a tensión, que ocupan espacio y empujan hacia el lado sano.', dificultad: 'dificil' },
  { q: '¿Qué hallazgo diferencia mejor, a la cabecera, un neumotórax de una consolidación, ya que ambos pueden tener frémito y expansión alterados?', options: ['La frecuencia cardiaca', 'La percusión: hiperresonancia/timpanismo en el neumotórax vs. matidez elástica en la consolidación', 'El color de piel', 'Ninguno, son indistinguibles sin radiografía'], correct: 1, explanation: 'El neumotórax tiene exceso de aire (hiperresonante), mientras que la consolidación tiene ausencia de aire por ocupación tisular (mate) — la percusión los distingue con claridad.', dificultad: 'intermedio' },
  { q: 'Un paciente con neumonía lobar presenta frémito aumentado, matidez a la percusión y soplo tubárico. ¿Qué esperarías al pedirle que diga "33" en voz normal?', options: ['Broncofonía negativa', 'Broncofonía positiva (voz anormalmente clara e intensa)', 'Egofonía únicamente, sin broncofonía', 'Abolición completa de la transmisión de la voz'], correct: 1, explanation: 'La broncofonía comparte el mismo mecanismo que el frémito aumentado y el soplo tubárico: el tejido consolidado transmite mejor el sonido, por lo que la voz se ausculta anormalmente clara.', dificultad: 'intermedio' },
  { q: '¿Qué representa el aleteo nasal y el tiraje (intercostal, supraclavicular, subcostal) como signos de dificultad respiratoria?', options: ['Un hallazgo normal en reposo', 'Una presión pleural negativa exagerada, necesaria para vencer una resistencia de la vía aérea aumentada o una distensibilidad pulmonar disminuida', 'Bradicardia asociada', 'Un signo exclusivo de patología cardiaca'], correct: 1, explanation: 'El tiraje y el uso de músculos accesorios reflejan el trabajo respiratorio aumentado necesario para generar suficiente presión negativa ante una vía aérea obstruida o un pulmón poco distensible.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente de 45 años con fiebre y tos productiva de 3 días. A la exploración del hemitórax derecho: frémito táctil aumentado, matidez a la percusión y un ruido de tipo bronquial (tubárico) en la base derecha.',
    steps: [
      { q: '¿Qué síndrome pleuropulmonar es más probable?', options: ['Derrame pleural', 'Consolidación (neumonía lobar)', 'Neumotórax', 'Atelectasia obstructiva'], correct: 1 },
      { q: '¿Qué esperarías encontrar al pedirle al paciente que susurre "33" (pectoriloquia áfona) sobre esa zona?', options: ['Positiva — se distinguen las sílabas con claridad anormal', 'Negativa — sonido apagado, como en cualquier otra zona sana', 'No aplica a la consolidación', 'Solo es válida para el frémito, no para pruebas de voz'], correct: 0 },
      { q: '¿Hacia dónde esperarías la posición de la tráquea?', options: ['Desviada hacia el lado sano', 'Desviada hacia el lado enfermo', 'Centrada, sin desviación significativa', 'No es valorable en la consolidación'], correct: 2 }
    ],
    explanation: 'La tríada de frémito aumentado + matidez elástica + soplo tubárico es clásica de consolidación (neumonía lobar): el tejido lleno de exudado, sin aire alveolar que lo filtre, transmite mejor tanto las vibraciones táctiles como el sonido bronquial y la voz (pectoriloquia áfona positiva). A diferencia del derrame o el neumotórax, la consolidación no ocupa espacio adicional ni colapsa volumen, por lo que la tráquea permanece centrada.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente de 68 años con disnea progresiva y dolor pleurítico derecho de una semana. Expansión torácica abolida a la derecha, frémito abolido, matidez "pétrea" con un límite superior curvo más alto en la axila que en la espalda, murmullo vesicular abolido.',
    steps: [
      { q: '¿Qué síndrome es este, y cómo se llama el límite superior de matidez descrito?', options: ['Consolidación; límite de Skoda', 'Derrame pleural; línea de Damoiseau-Ellis', 'Neumotórax; signo de Kussmaul', 'Atelectasia; línea de Damoiseau-Ellis'], correct: 1 },
      { q: '¿Hacia dónde esperarías que estuviera desviada la tráquea si el derrame es masivo?', options: ['Hacia el lado del derrame (derecho)', 'Hacia el lado sano (izquierdo)', 'No se desvía en el derrame pleural', 'Depende de la frecuencia cardiaca'], correct: 1 },
      { q: 'Si auscultas justo en el límite superior de la matidez y pides al paciente decir una "e" sostenida, ¿qué hallazgo confirmaría la localización de ese borde?', options: ['Egofonía positiva (se ausculta como una "a" nasal)', 'Pectoriloquia áfona negativa', 'Roce pleural intenso', 'Sibilancias difusas'], correct: 0 }
    ],
    explanation: 'El derrame pleural masivo combina expansión y frémito abolidos, matidez pétrea con la característica curva de Damoiseau-Ellis, murmullo abolido, y desviación traqueal hacia el lado SANO (por ocupación de espacio, igual que el neumotórax a tensión). La egofonía positiva en el borde superior del derrame es un hallazgo clásico que confirma esa localización exacta.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente de 30 años, previamente sano, con dolor torácico súbito y disnea tras un esfuerzo. Hipotensión, ingurgitación yugular, hemitórax izquierdo hiperresonante a la percusión, murmullo vesicular abolido, frémito abolido.',
    steps: [
      { q: '¿Qué síndrome es más probable dado el contexto (inicio súbito, hipotensión, ingurgitación yugular)?', options: ['Consolidación extensa', 'Neumotórax a tensión', 'Derrame pleural crónico', 'Fibrosis pulmonar'], correct: 1 },
      { q: '¿Qué diferencia a este cuadro de un derrame pleural masivo en la percusión, aunque ambos tengan frémito y murmullo abolidos?', options: ['El neumotórax es hiperresonante/timpánico; el derrame es mate ("pétreo")', 'No hay ninguna diferencia en la percusión', 'El derrame siempre es hiperresonante', 'El neumotórax siempre es mate'], correct: 0 },
      { q: '¿Hacia dónde esperarías la desviación traqueal en este neumotórax a tensión?', options: ['Hacia el lado sano (derecho), igual que en el derrame masivo', 'Hacia el lado afectado (izquierdo)', 'No se desvía en el neumotórax', 'Solo se desvía en la atelectasia'], correct: 0 }
    ],
    explanation: 'El neumotórax a tensión comparte con el derrame masivo la abolición de expansión, frémito y murmullo, y la desviación traqueal hacia el lado sano (ambos "ocupan espacio" dentro del hemitórax) — pero se distinguen con claridad en la percusión: hiperresonante/timpánico en el neumotórax (exceso de aire) vs. mate/pétreo en el derrame (líquido). La hipotensión y la ingurgitación yugular en este caso son datos de alarma de un neumotórax A TENSIÓN, una urgencia que compromete el retorno venoso.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente con cáncer pulmonar conocido presenta disnea progresiva. Expansión torácica disminuida a la izquierda, frémito abolido, matidez a la percusión, murmullo vesicular abolido. La tráquea, sin embargo, está desviada HACIA la izquierda.',
    steps: [
      { q: '¿Qué síndrome explica mejor esta combinación de matidez con desviación traqueal hacia el lado enfermo?', options: ['Derrame pleural masivo', 'Neumotórax a tensión', 'Atelectasia obstructiva (por el tumor ocluyendo la vía aérea)', 'Consolidación simple'], correct: 2 },
      { q: '¿Por qué la tráquea se desvía HACIA el lado enfermo en este caso, a diferencia del derrame o el neumotórax?', options: ['Porque hay más aire de ese lado', 'Porque el pulmón colapsado pierde volumen y "atrae" las estructuras mediastínicas hacia sí', 'Es un error de exploración, no ocurre realmente', 'Porque el tumor empuja la tráquea directamente'], correct: 1 },
      { q: '¿Qué esperarías encontrar en la auscultación de la voz (broncofonía) sobre la zona colapsada?', options: ['Positiva, igual que en la consolidación', 'Negativa/abolida, porque la vía aérea ocluida ni siquiera deja llegar el sonido generado en la laringe', 'Egofonía intensa', 'Roce pleural característico'], correct: 1 },
    ],
    explanation: 'La atelectasia obstructiva combina matidez (sin aire) con desviación traqueal HACIA el lado enfermo — el opuesto exacto del derrame o el neumotórax — porque el pulmón colapsado pierde volumen y atrae el mediastino, en vez de ocupar espacio y empujarlo. A diferencia de la consolidación (donde la vía aérea sigue permeable y transmite bien el sonido), en la atelectasia obstructiva la oclusión de la vía aérea abole también la transmisión de la voz.'
  }
];

export const flashcards = [
  { front: 'Orden de la exploración respiratoria', back: 'Inspección → Palpación (expansión y frémito) → Percusión → Auscultación (IPPA) — a diferencia de la cardiovascular, la percusión aquí sigue teniendo pleno valor diagnóstico.' },
  { front: 'Respiración de Cheyne-Stokes', back: 'Ciclos crescendo-decrescendo separados por apnea — retraso de los quimiorreceptores centrales al CO2 (insuficiencia cardiaca, daño cerebral bilateral).' },
  { front: 'Respiración de Kussmaul', back: 'Profunda, rápida, sostenida — compensación de acidosis metabólica severa.' },
  { front: 'Disociación toracoabdominal', back: 'Movimiento paradójico del abdomen hacia adentro en inspiración — fatiga/claudicación diafragmática, falla respiratoria inminente.' },
  { front: 'Tórax en tonel', back: 'Aumento del diámetro anteroposterior, horizontalización costal — atrapamiento aéreo crónico (EPOC/enfisema).' },
  { front: 'Tórax inestable (flail chest)', back: 'Fracturas costales múltiples en ≥2 puntos por costilla — el segmento se mueve paradójico (adentro en inspiración, afuera en espiración) por desacople mecánico del resto de la caja.' },
  { front: 'Expansión torácica normal', back: '~3-5 cm de separación simétrica de los pulgares con inspiración profunda, técnica bimanual.' },
  { front: 'Por qué aumenta el frémito en la consolidación', back: 'El tejido consolidado (sólido, sin aire) transmite mejor las vibraciones que el parénquima aireado normal.' },
  { front: '3 causas de frémito abolido', back: 'Derrame pleural (amortigua), neumotórax (el aire pleural no transmite), atelectasia obstructiva completa (la vía aérea ocluida no deja llegar la vibración).' },
  { front: 'Matidez elástica vs. pétrea', back: 'Elástica: consolidación (tejido sólido con cierta estructura). Pétrea: derrame pleural (líquido, sin ningún componente resonante).' },
  { front: 'Signo de Skoda', back: 'Franja de timpanismo por ENCIMA del límite superior de un derrame pleural, por compresión pasiva del parénquima adyacente.' },
  { front: 'Línea de Damoiseau-Ellis', back: 'Límite superior de matidez del derrame pleural: curva cóncava hacia arriba y medial, más alta en la línea axilar (no horizontal como en la consolidación).' },
  { front: 'Murmullo vesicular vs. respiración bronquial', back: 'Vesicular: suave, inspiración>espiración, filtrado por el alvéolo, en toda la superficie pulmonar. Bronquial: ruda, espiración≥inspiración con pausa, sin filtro, solo normal sobre la tráquea.' },
  { front: 'Soplo tubárico', back: 'Ruido bronquial auscultado fuera de la tráquea → signo mayor de consolidación (pierde el filtro alveolar normal).' },
  { front: 'Sibilancias vs. roncus', back: 'Sibilancias: agudas, musicales, vía aérea pequeña estrechada, no cambian con la tos. Roncus: graves, secreciones en vía aérea grande, sí cambian con la tos.' },
  { front: 'Estertores finos vs. gruesos', back: 'Finos ("velcro"): fin de inspiración, apertura de alvéolos colapsados, NO cambian con la tos (fibrosis, edema temprano). Gruesos: ambas fases, secreciones en vía grande, SÍ cambian con la tos.' },
  { front: 'Roce pleural', back: '"Cuero nuevo"/"pisar nieve", ambas fases, no cambia con la tos, desaparece si se acumula derrame entre las hojas pleurales.' },
  { front: 'Broncofonía / pectoriloquia áfona / egofonía', back: 'Las tres son positivas sobre consolidación (mismo mecanismo que el frémito). La egofonía marca específicamente el borde superior de un derrame pleural.' },
  { front: 'Desviación traqueal: derrame/neumotórax vs. atelectasia', back: 'Derrame y neumotórax (ocupan espacio) → desvían la tráquea hacia el lado SANO. Atelectasia (pierde volumen) → atrae la tráquea hacia el lado ENFERMO.' },
  { front: 'Percusión: cómo distinguir neumotórax de consolidación', back: 'Ambos pueden tener frémito/murmullo abolidos, pero el neumotórax es hiperresonante (exceso de aire) y la consolidación es mate (ausencia de aire).' },
  { front: 'Excursión diafragmática normal', back: '3-5 cm de diferencia entre el límite de matidez en espiración e inspiración máximas, en línea escapular.' },
  { front: 'Los 4 síndromes pleuropulmonares (resumen)', back: 'Consolidación: frémito↑, matidez elástica, soplo tubárico. Derrame: frémito abolido, matidez pétrea, tráquea al lado sano. Neumotórax: frémito abolido, hiperresonante, tráquea al lado sano. Atelectasia: frémito abolido, matidez, tráquea al lado enfermo.' }
];

export default { quiz, flashcards };
