// topics/exploracion-respiratoria/study.js — Autoevaluación de Exploración Respiratoria.
// Mismo patrón que exploracion-cardiovascular/study.js: banco único, preguntas sueltas +
// preguntas en cascada sobre una viñeta (retroalimentación consolidada al final). Redacción de
// opciones sujeta a .claude/skills/reglas-preguntas/SKILL.md (misma categoría lógica, longitud/
// detalle comparables, sin pistas gramaticales/semánticas, posición de `correct` distribuida sin
// patrón a lo largo de todo el array).

export const quiz = [
  { q: '¿Cuál es el orden correcto de la exploración respiratoria?', options: ['Auscultación, percusión, palpación, inspección', 'Inspección, palpación, percusión, auscultación (IPPA)', 'Percusión, inspección, auscultación, palpación', 'Palpación, auscultación, inspección, percusión'], correct: 1, explanation: 'El orden clásico IPPA (Inspección, Palpación, Percusión, Auscultación) se mantiene vigente en la exploración respiratoria, a diferencia de la cardiovascular donde la percusión cayó en desuso.', dificultad: 'facil' },
  { q: 'A diferencia de la exploración cardiovascular, ¿por qué la percusión mantiene rendimiento diagnóstico pleno en la exploración respiratoria?', options: ['El corazón no se puede percutir bien', 'Es más rápida que la auscultación completa', 'No hay diferencia real entre las dos', 'Distingue aire, consolidación y líquido'], correct: 3, explanation: 'La percusión torácica sigue teniendo alto rendimiento porque diferencia con precisión los 3 grandes sustratos posibles bajo la pared torácica: aire (hiperresonancia), consolidación (matidez elástica) y líquido (matidez pétrea).', dificultad: 'intermedio' },
  { q: '¿Por qué se explora primero la cara posterior del tórax?', options: ['Concentra más superficie pulmonar', 'Resulta más cómodo para el explorador', 'Ahí no interfieren los ruidos cardiacos', 'No existe una razón particular para ello'], correct: 0, explanation: 'La cara posterior del tórax tiene la mayor cantidad de parénquima pulmonar accesible, incluidas las bases, por lo que suele explorarse primero y de forma más extensa.', dificultad: 'facil' },
  { q: 'La respiración de Cheyne-Stokes (ciclos crescendo-decrescendo separados por apnea) se explica por:', options: ['Acidosis metabólica compensada, sin repercusión en el patrón respiratorio', 'Lesión pontina aislada, sin compromiso de otros centros', 'Un retraso en la retroalimentación de los quimiorreceptores centrales al CO2', 'Obstrucción mecánica de la vía aérea superior, de inicio súbito'], correct: 2, explanation: 'El tiempo de circulación prolongado (insuficiencia cardiaca) o el daño cerebral bilateral retrasan la respuesta del centro respiratorio al CO2, generando el patrón oscilante característico.', dificultad: 'dificil' },
  { q: '¿Qué mecanismo explica la respiración de Kussmaul?', options: ['Lesión bulbar con pérdida completa del ritmo respiratorio', 'Insuficiencia cardiaca descompensada con congestión pulmonar', 'Obstrucción de la vía aérea superior, de inicio agudo', 'Compensación respiratoria de una acidosis metabólica severa'], correct: 3, explanation: 'La respiración de Kussmaul (profunda, rápida, sostenida) es la respuesta compensadora del organismo ante una acidosis metabólica severa (cetoacidosis diabética, acidosis láctica), buscando eliminar CO2 y elevar el pH.', dificultad: 'intermedio' },
  { q: '¿Qué indica la disociación toracoabdominal (movimiento paradójico del abdomen hacia adentro en inspiración)?', options: ['Un hallazgo normal en decúbito supino, sin significado patológico', 'Fatiga o claudicación diafragmática inminente, signo de falla respiratoria', 'Acidosis metabólica compensada, sin relación con el trabajo respiratorio', 'Derrame pleural leve, sin repercusión en la mecánica ventilatoria'], correct: 1, explanation: 'Es uno de los signos físicos de mayor valor para anticipar la necesidad de ventilación mecánica, incluso antes de que se alteren los gases arteriales.', dificultad: 'dificil' },
  { q: 'El tórax en tonel (aumento del diámetro anteroposterior, horizontalización costal) es característico de:', options: ['La cifoescoliosis torácica', 'El derrame pleural crónico', 'El atrapamiento aéreo (EPOC)', 'La tuberculosis apical antigua'], correct: 2, explanation: 'El atrapamiento aéreo crónico hiperinsufla el tórax de forma sostenida, aumentando el diámetro anteroposterior y horizontalizando las costillas.', dificultad: 'facil' },
  { q: 'En el tórax inestable (flail chest), ¿por qué el segmento afectado se mueve de forma paradójica?', options: ['Las fracturas aíslan ese segmento', 'El paciente contiene la respiración', 'Se acompaña de un neumotórax asociado', 'Es un artefacto de la exploración'], correct: 0, explanation: 'El segmento fracturado en múltiples puntos deja de estar mecánicamente acoplado al resto del tórax, así que sigue la presión intrapleural en vez de moverse con la caja torácica: se hunde en inspiración y protruye en espiración.', dificultad: 'dificil' },
  { q: '¿Cómo se explora la expansión torácica y qué magnitud es normal?', options: ['Con el estetoscopio, comparando ambos lados; normal alrededor de 1 cm', 'Percutiendo la espalda de arriba hacia abajo; normal unos 8 cm', 'Con ambas manos y los pulgares aproximados en la línea media; normal ~3-5 cm', 'No tiene una técnica estandarizada, varía según el explorador'], correct: 2, explanation: 'La palpación bimanual con los pulgares aproximados en la línea media es la técnica estándar; la separación simétrica esperada con una inspiración profunda es de aproximadamente 3-5 cm.', dificultad: 'facil' },
  { q: '¿Por qué el frémito táctil AUMENTA sobre una zona de consolidación pulmonar?', options: ['La consolidación produce más sonido', 'Acerca la pared torácica a la vía aérea', 'El frémito solo llega a disminuir', 'El tejido denso transmite mejor'], correct: 3, explanation: 'Un sólido (tejido consolidado) transmite el sonido/vibración mejor que un gas (parénquima aireado normal), el mismo principio físico detrás del soplo tubárico y de la broncofonía.', dificultad: 'intermedio' },
  { q: '¿En cuáles 3 condiciones está disminuido o abolido el frémito táctil?', options: ['Neumonía, tuberculosis y asma bronquial', 'Derrame, neumotórax y atelectasia', 'Bronquitis, faringitis y laringitis aguda', 'Fiebre, taquicardia y taquipnea marcada'], correct: 1, explanation: 'En las tres, algo interrumpe la transmisión de la vibración hasta la pared torácica: el líquido (derrame) la amortigua, el aire pleural (neumotórax) no la transmite, y la vía aérea ocluida (atelectasia obstructiva) impide que la vibración generada en la laringe siquiera llegue.', dificultad: 'intermedio' },
  { q: '¿Qué diferencia hay entre la matidez de una consolidación y la de un derrame pleural?', options: ['Consolidación: elástica; derrame: pétrea', 'No hay diferencia perceptible entre ambos', 'La consolidación resulta hiperresonante', 'El derrame pleural da hiperresonancia'], correct: 0, explanation: 'La matidez "pétrea" del derrame pleural (por el líquido, que no tiene ningún componente aéreo) es más marcada y característica que la matidez "elástica" de la consolidación (tejido sólido pero aún con cierta estructura alveolar).', dificultad: 'dificil' },
  { q: '¿Qué representa el signo de Skoda?', options: ['Matidez pétrea sobre la zona del derrame', 'Franja de timpanismo sobre el derrame', 'Hiperresonancia difusa en el enfisema', 'Falta de frémito táctil en el neumotórax'], correct: 1, explanation: 'El pulmón comprimido pero no colapsado justo por encima del nivel del derrame genera una franja de timpanismo relativo, sin llenarse de líquido — el signo de Skoda.', dificultad: 'dificil' },
  { q: '¿Qué describe la línea de Damoiseau-Ellis?', options: ['El límite horizontal de la consolidación', 'El límite normal de la excursión diafragmática', 'La curva cóncava del límite del derrame', 'La distribución normal del murmullo'], correct: 2, explanation: 'A diferencia del límite horizontal de una consolidación, el derrame pleural libre se distribuye por gravedad con un límite superior curvo, más alto lateralmente (línea axilar) que en la columna o el esternón.', dificultad: 'dificil' },
  { q: '¿Qué caracteriza al murmullo vesicular normal, y por qué tiene ese timbre suave?', options: ['Inspiración más larga; filtro alveolar', 'Espiración más larga y de tono agudo', 'Solo se ausculta sobre la tráquea', 'No se relaciona con el ciclo respiratorio'], correct: 0, explanation: 'El murmullo vesicular se genera en bronquios de mediano calibre, pero el parénquima alveolar circundante actúa como filtro de frecuencias altas, dándole su timbre suave y su predominio inspiratorio.', dificultad: 'intermedio' },
  { q: '¿Dónde es normal auscultar respiración bronquial (tubárica)?', options: ['En ambas bases, de forma simétrica', 'En toda la superficie pulmonar por igual', 'Únicamente en el ápex izquierdo', 'Sobre la tráquea y el manubrio'], correct: 3, explanation: 'La respiración bronquial, generada por turbulencia directa en la vía aérea grande sin el filtro alveolar, es normal únicamente sobre la tráquea y el manubrio esternal.', dificultad: 'facil' },
  { q: '¿Qué significa auscultar un "soplo tubárico" (ruido bronquial) fuera de la tráquea?', options: ['Un signo mayor de consolidación', 'Un hallazgo normal en personas delgadas', 'Neumotórax, por falta de tejido aireado', 'Derrame, por líquido en el espacio pleural'], correct: 0, explanation: 'Al perderse el filtro alveolar normal (porque el alvéolo está lleno de exudado, no de aire), el sonido bronquial generado en la vía aérea grande se transmite sin atenuar hasta zonas donde normalmente se oiría vesicular.', dificultad: 'intermedio' },
  { q: '¿Qué diferencia principal hay entre sibilancias y roncus?', options: ['Sibilancias graves y roncus agudos, musicales', 'Sibilancias agudas; roncus por secreción', 'No hay diferencia perceptible entre ambos', 'Los roncus solo se dan en pediatría'], correct: 1, explanation: 'Las sibilancias reflejan estrechamiento difuso de la vía aérea pequeña (broncoespasmo/edema/moco) y no cambian con la tos; los roncus reflejan secreciones en vía aérea de mayor calibre y sí suelen modificarse al toser.', dificultad: 'intermedio' },
  { q: 'Una sibilancia localizada y fija que no cambia con la tos, en un paciente sin antecedente de asma, debe hacer sospechar:', options: ['Un asma leve de reciente diagnóstico', 'Una bronquitis viral en resolución', 'Un hallazgo normal, sin más relevancia', 'Obstrucción endobronquial focal'], correct: 3, explanation: 'A diferencia de las sibilancias difusas del asma/EPOC, una sibilancia fija y localizada sugiere una obstrucción mecánica puntual de la vía aérea que debe investigarse.', dificultad: 'dificil' },
  { q: '¿Qué distingue a los estertores finos ("velcro") de los gruesos?', options: ['Los finos son musicales; los gruesos, no', 'Los gruesos son propios de la fibrosis', 'Los finos no cambian con la tos', 'No hay diferencia clínica relevante entre ambos'], correct: 2, explanation: 'Los estertores finos se generan por apertura súbita de vía aérea/alvéolos colapsados (no cambian con la tos); los gruesos, por aire pasando a través de secreciones en vía aérea grande (sí cambian con la tos).', dificultad: 'intermedio' },
  { q: 'Estertores finos bibasales, persistentes, que NO cambian con la tos, orientan principalmente a:', options: ['Las bronquiectasias', 'La fibrosis pulmonar', 'El neumotórax simple', 'El asma bronquial'], correct: 1, explanation: 'El patrón de estertores finos tipo velcro, bibasales y persistentes en el tiempo (sin modificarse con la tos) es característico de la fibrosis pulmonar intersticial.', dificultad: 'intermedio' },
  { q: '¿Cómo se describe clásicamente el roce pleural y qué lo hace desaparecer?', options: ['Áspero, como cuero nuevo; cede con derrame', 'Musical y agudo; cede con broncodilatador', 'Grave y rítmico, como ronquido; cede al toser', 'No llega a desaparecer; es un hallazgo fijo'], correct: 0, explanation: 'El roce pleural refleja la fricción directa de las hojas pleurales inflamadas; si se acumula líquido entre ellas, deja de haber fricción directa y el roce desaparece.', dificultad: 'intermedio' },
  { q: '¿Qué es la pectoriloquia áfona?', options: ['Ausencia total de ruidos respiratorios', 'Un sinónimo exacto del hallazgo de egofonía', 'La voz susurrada se transmite clara', 'Un hallazgo normal de la base izquierda'], correct: 2, explanation: 'Normalmente la voz susurrada se filtra y no se distingue con claridad; sobre una consolidación, el tejido sólido transmite incluso el susurro con una nitidez anormal.', dificultad: 'intermedio' },
  { q: '¿Dónde se ausculta característicamente la egofonía positiva?', options: ['En el ápex pulmonar sano, sin alteración', 'Sobre la tráquea, no en el parénquima', 'En cualquier punto de un neumotórax establecido', 'En el límite superior de un derrame'], correct: 3, explanation: 'La combinación de compresión pulmonar (sin consolidación completa) en el borde superior de un derrame filtra selectivamente ciertas frecuencias de la voz, cambiando el timbre de la "e" a una "a" nasal.', dificultad: 'dificil' },
  { q: 'En el síndrome de derrame pleural masivo, ¿hacia dónde se desvía la tráquea?', options: ['Hacia el lado del derrame, por atracción', 'La tráquea no llega a desviarse', 'Hacia el lado sano (contralateral)', 'Depende solo de la edad del paciente'], correct: 2, explanation: 'Un derrame masivo ocupa espacio y empuja las estructuras mediastínicas, incluida la tráquea, hacia el lado sano — igual que el neumotórax a tensión.', dificultad: 'intermedio' },
  { q: 'A diferencia del derrame pleural y el neumotórax, en la atelectasia obstructiva la tráquea se desvía:', options: ['Hacia el lado sano, como en el derrame', 'Hacia el lado enfermo, por el colapso', 'La tráquea no se desvía en la atelectasia', 'Solo se desvía si hay fiebre asociada'], correct: 1, explanation: 'La atelectasia colapsa y reduce el volumen de ese pulmón, por lo que el mediastino y la tráquea son atraídos hacia el lado afectado — el patrón opuesto al del derrame o el neumotórax a tensión, que ocupan espacio y empujan hacia el lado sano.', dificultad: 'dificil' },
  { q: '¿Qué hallazgo diferencia mejor, a la cabecera, un neumotórax de una consolidación, ya que ambos pueden tener frémito y expansión alterados?', options: ['La percusión: hiperresonante o mate', 'La frecuencia cardiaca en cada hemitórax', 'El color de la piel del lado afectado', 'Nada: son indistinguibles sin radiografía'], correct: 0, explanation: 'El neumotórax tiene exceso de aire (hiperresonante), mientras que la consolidación tiene ausencia de aire por ocupación tisular (mate) — la percusión los distingue con claridad.', dificultad: 'intermedio' },
  { q: 'Un paciente con neumonía lobar presenta frémito aumentado, matidez a la percusión y soplo tubárico. ¿Qué esperarías al pedirle que diga "33" en voz normal?', options: ['Broncofonía negativa, con voz apagada y poco clara', 'Egofonía únicamente, sin broncofonía asociada', 'Abolición completa de la transmisión de la voz', 'Broncofonía positiva (voz anormalmente clara e intensa)'], correct: 3, explanation: 'La broncofonía comparte el mismo mecanismo que el frémito aumentado y el soplo tubárico: el tejido consolidado transmite mejor el sonido, por lo que la voz se ausculta anormalmente clara.', dificultad: 'intermedio' },
  { q: '¿Qué representa el aleteo nasal y el tiraje (intercostal, supraclavicular, subcostal) como signos de dificultad respiratoria?', options: ['Un hallazgo normal en reposo, sin más', 'Presión pleural negativa exagerada', 'Bradicardia por el esfuerzo respiratorio', 'Un signo propio de la patología cardiaca'], correct: 1, explanation: 'El tiraje y el uso de músculos accesorios reflejan el trabajo respiratorio aumentado necesario para generar suficiente presión negativa ante una vía aérea obstruida o un pulmón poco distensible.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente de 45 años con fiebre y tos productiva de 3 días. A la exploración del hemitórax derecho: frémito táctil aumentado, matidez a la percusión y un ruido de tipo bronquial (tubárico) en la base derecha.',
    steps: [
      { q: '¿Qué síndrome pleuropulmonar es más probable?', options: ['Un derrame pleural', 'Un neumotórax simple', 'Una consolidación lobar', 'Una atelectasia obstructiva'], correct: 2 },
      { q: '¿Qué esperarías encontrar al pedirle al paciente que susurre "33" (pectoriloquia áfona) sobre esa zona?', options: ['Positiva — se distinguen las sílabas con claridad anormal', 'Negativa — sonido apagado, como en cualquier otra zona sana', 'No aplica a la consolidación', 'Solo es válida para el frémito, no para pruebas de voz'], correct: 0 },
      { q: '¿Hacia dónde esperarías la posición de la tráquea?', options: ['Desviada hacia el lado sano', 'Desviada hacia el lado enfermo', 'No valorable en la consolidación', 'Centrada, sin desviación'], correct: 3 }
    ],
    explanation: 'La tríada de frémito aumentado + matidez elástica + soplo tubárico es clásica de consolidación (neumonía lobar): el tejido lleno de exudado, sin aire alveolar que lo filtre, transmite mejor tanto las vibraciones táctiles como el sonido bronquial y la voz (pectoriloquia áfona positiva). A diferencia del derrame o el neumotórax, la consolidación no ocupa espacio adicional ni colapsa volumen, por lo que la tráquea permanece centrada.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente de 68 años con disnea progresiva y dolor pleurítico derecho de una semana. Expansión torácica abolida a la derecha, frémito abolido, matidez "pétrea" con un límite superior curvo más alto en la axila que en la espalda, murmullo vesicular abolido.',
    steps: [
      { q: '¿Qué síndrome es este, y cómo se llama el límite superior de matidez descrito?', options: ['Consolidación; el límite de Skoda', 'Derrame; línea de Damoiseau-Ellis', 'Neumotórax; el signo de Kussmaul', 'Atelectasia; línea de Damoiseau-Ellis'], correct: 1 },
      { q: '¿Hacia dónde esperarías que estuviera desviada la tráquea si el derrame es masivo?', options: ['Hacia el lado sano (izquierdo)', 'Hacia el lado del derrame (derecho)', 'No se desvía en el derrame pleural', 'Depende de la frecuencia cardiaca'], correct: 0 },
      { q: 'Si auscultas justo en el límite superior de la matidez y pides al paciente decir una "e" sostenida, ¿qué hallazgo confirmaría la localización de ese borde?', options: ['Pectoriloquia áfona negativa, sin transmisión clara de la voz', 'Roce pleural intenso, audible en ambas fases respiratorias', 'Egofonía positiva (se ausculta como una "a" nasal)', 'Sibilancias difusas, audibles en ambos campos pulmonares'], correct: 2 }
    ],
    explanation: 'El derrame pleural masivo combina expansión y frémito abolidos, matidez pétrea con la característica curva de Damoiseau-Ellis, murmullo abolido, y desviación traqueal hacia el lado SANO (por ocupación de espacio, igual que el neumotórax a tensión). La egofonía positiva en el borde superior del derrame es un hallazgo clásico que confirma esa localización exacta.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente de 30 años, previamente sano, con dolor torácico súbito y disnea tras un esfuerzo. Hipotensión, ingurgitación yugular, hemitórax izquierdo hiperresonante a la percusión, murmullo vesicular abolido, frémito abolido.',
    steps: [
      { q: '¿Qué síndrome es más probable dado el contexto (inicio súbito, hipotensión, ingurgitación yugular)?', options: ['Consolidación extensa', 'Neumotórax a tensión', 'Derrame pleural crónico', 'Fibrosis pulmonar'], correct: 1 },
      { q: '¿Qué diferencia a este cuadro de un derrame pleural masivo en la percusión, aunque ambos tengan frémito y murmullo abolidos?', options: ['No hay diferencia alguna en la percusión', 'El derrame pleural resulta hiperresonante', 'El neumotórax resulta mate a la percusión', 'Neumotórax timpánico; derrame mate'], correct: 3 },
      { q: '¿Hacia dónde esperarías la desviación traqueal en este neumotórax a tensión?', options: ['Hacia el lado afectado (izquierdo)', 'Hacia el lado sano, como en el derrame', 'No se desvía en el neumotórax a tensión', 'Solo se desvía en la atelectasia obstructiva'], correct: 1 }
    ],
    explanation: 'El neumotórax a tensión comparte con el derrame masivo la abolición de expansión, frémito y murmullo, y la desviación traqueal hacia el lado sano (ambos "ocupan espacio" dentro del hemitórax) — pero se distinguen con claridad en la percusión: hiperresonante/timpánico en el neumotórax (exceso de aire) vs. mate/pétreo en el derrame (líquido). La hipotensión y la ingurgitación yugular en este caso son datos de alarma de un neumotórax A TENSIÓN, una urgencia que compromete el retorno venoso.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente con cáncer pulmonar conocido presenta disnea progresiva. Expansión torácica disminuida a la izquierda, frémito abolido, matidez a la percusión, murmullo vesicular abolido. La tráquea, sin embargo, está desviada HACIA la izquierda.',
    steps: [
      { q: '¿Qué síndrome explica mejor esta combinación de matidez con desviación traqueal hacia el lado enfermo?', options: ['Un derrame pleural masivo', 'Un neumotórax a tensión', 'Una consolidación simple', 'Atelectasia obstructiva'], correct: 3 },
      { q: '¿Por qué la tráquea se desvía HACIA el lado enfermo en este caso, a diferencia del derrame o el neumotórax?', options: ['El pulmón colapsado atrae el mediastino', 'Hay más aire acumulado de ese lado', 'Es un error de técnica; no ocurre así', 'El tumor empuja la tráquea de forma directa'], correct: 0 },
      { q: '¿Qué esperarías encontrar en la auscultación de la voz (broncofonía) sobre la zona colapsada?', options: ['Positiva, como en la consolidación', 'Egofonía intensa, como en el derrame', 'Abolida: la vía ocluida no transmite', 'Roce pleural audible en ambas fases'], correct: 2 }
    ],
    explanation: 'La atelectasia obstructiva combina matidez (sin aire) con desviación traqueal HACIA el lado enfermo — el opuesto exacto del derrame o el neumotórax — porque el pulmón colapsado pierde volumen y atrae el mediastino, en vez de ocupar espacio y empujarlo. A diferencia de la consolidación (donde la vía aérea sigue permeable y transmite bien el sonido), en la atelectasia obstructiva la oclusión de la vía aérea abole también la transmisión de la voz.'
  }
];

export const flashcards = [
  { front: 'Orden de la exploración respiratoria', back: 'Inspección → Palpación (expansión y frémito) → Percusión → Auscultación (IPPA) — a diferencia de la cardiovascular, la percusión aquí sigue teniendo pleno valor diagnóstico.' },
  { front: 'Respiración de Cheyne-Stokes', back: 'Ciclos crescendo-decrescendo separados por apnea — retraso de los quimiorreceptores centrales al CO2 (insuficiencia cardiaca, daño cerebral bilateral).' },
  { front: 'Respiración de Kussmaul', back: 'Profunda, rápida, sostenida — compensación de acidosis metabólica severa.' },
  { front: 'Disociación toracoabdominal', back: 'Movimiento paradójico del abdomen hacia adentro en inspiración — fatiga/claudicación diafragmática, falla respiratoria inminente.' },
  { front: 'Tórax en tonel', back: 'Aumento del diámetro anteroposterior, horizontalización costal — atrapamiento aéreo crónico (EPOC/enfisema).' },
  { front: 'Tórax inestable (flail chest)', back: 'Fracturas costales múltiples en ≥2 puntos por costilla — el segmento se mueve paradójico (adentro en inspiración, afuera en espiración) por desacople mecánico del resto de la caja.' },
  { front: 'Expansión torácica normal', back: '~3-5 cm de separación simétrica de los pulgares con inspiración profunda, técnica bimanual.' },
  { front: 'Por qué aumenta el frémito en la consolidación', back: 'El tejido consolidado (sólido, sin aire) transmite mejor las vibraciones que el parénquima aireado normal.' },
  { front: '3 causas de frémito abolido', back: 'Derrame pleural (amortigua), neumotórax (el aire pleural no transmite), atelectasia obstructiva completa (la vía aérea ocluida no deja llegar la vibración).' },
  { front: 'Matidez elástica vs. pétrea', back: 'Elástica: consolidación (tejido sólido con cierta estructura). Pétrea: derrame pleural (líquido, sin ningún componente resonante).' },
  { front: 'Signo de Skoda', back: 'Franja de timpanismo por ENCIMA del límite superior de un derrame pleural, por compresión pasiva del parénquima adyacente.' },
  { front: 'Línea de Damoiseau-Ellis', back: 'Límite superior de matidez del derrame pleural: curva cóncava hacia arriba y medial, más alta en la línea axilar (no horizontal como en la consolidación).' },
  { front: 'Murmullo vesicular vs. respiración bronquial', back: 'Vesicular: suave, inspiración>espiración, filtrado por el alvéolo, en toda la superficie pulmonar. Bronquial: ruda, espiración≥inspiración con pausa, sin filtro, solo normal sobre la tráquea.' },
  { front: 'Soplo tubárico', back: 'Ruido bronquial auscultado fuera de la tráquea → signo mayor de consolidación (pierde el filtro alveolar normal).' },
  { front: 'Sibilancias vs. roncus', back: 'Sibilancias: agudas, musicales, vía aérea pequeña estrechada, no cambian con la tos. Roncus: graves, secreciones en vía aérea grande, sí cambian con la tos.' },
  { front: 'Estertores finos vs. gruesos', back: 'Finos ("velcro"): fin de inspiración, apertura de alvéolos colapsados, NO cambian con la tos (fibrosis, edema temprano). Gruesos: ambas fases, secreciones en vía grande, SÍ cambian con la tos.' },
  { front: 'Roce pleural', back: '"Cuero nuevo"/"pisar nieve", ambas fases, no cambia con la tos, desaparece si se acumula derrame entre las hojas pleurales.' },
  { front: 'Broncofonía / pectoriloquia áfona / egofonía', back: 'Las tres son positivas sobre consolidación (mismo mecanismo que el frémito). La egofonía marca específicamente el borde superior de un derrame pleural.' },
  { front: 'Desviación traqueal: derrame/neumotórax vs. atelectasia', back: 'Derrame y neumotórax (ocupan espacio) → desvían la tráquea hacia el lado SANO. Atelectasia (pierde volumen) → atrae la tráquea hacia el lado ENFERMO.' },
  { front: 'Percusión: cómo distinguir neumotórax de consolidación', back: 'Ambos pueden tener frémito/murmullo abolidos, pero el neumotórax es hiperresonante (exceso de aire) y la consolidación es mate (ausencia de aire).' },
  { front: 'Excursión diafragmática normal', back: '3-5 cm de diferencia entre el límite de matidez en espiración e inspiración máximas, en línea escapular.' },
  { front: 'Los 4 síndromes pleuropulmonares (resumen)', back: 'Consolidación: frémito↑, matidez elástica, soplo tubárico. Derrame: frémito abolido, matidez pétrea, tráquea al lado sano. Neumotórax: frémito abolido, hiperresonante, tráquea al lado sano. Atelectasia: frémito abolido, matidez, tráquea al lado enfermo.' }
];

export default { quiz, flashcards };
