// topics/asma/study.js: Autoevaluacion de Asma.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// 48 subpreguntas (30 sueltas + 6 cascadas de 3 pasos) y 32 tarjetas.
// Distribucion de `correct` en el banco completo: 12 en cada posicion.
// Sin em dash (ver [[feedback-no-em-dash]]). Texto sin acentos.

export const quiz = [
  { q: 'Que caracteristica define al asma frente a otras obstrucciones cronicas?', options: ['La presencia de eosinofilia en sangre periferica', 'La variabilidad de la limitacion al flujo aereo', 'El inicio de los sintomas en la infancia', 'La respuesta al corticoide inhalado'], correct: 1, explanation: 'La definicion tiene dos mitades y la misma palabra clave en ambas: sintomas que varian y limitacion VARIABLE al flujo aereo. La eosinofilia, el inicio precoz y la respuesta al corticoide apoyan el diagnostico pero no lo definen, y ninguno de los tres es constante.', dificultad: 'facil' },
  { q: 'Que resultado de la prueba broncodilatadora se considera positivo en el adulto?', options: ['Ascenso del FEV1 mayor del 8% sobre el basal', 'Ascenso del FEV1 de mas de 150 mL en valor absoluto', 'Ascenso del flujo pico mayor del 15%', 'Ascenso del FEV1 mayor del 12% y de mas de 200 mL'], correct: 3, explanation: 'Los dos criterios se exigen a la vez, porque un porcentaje alto sobre un FEV1 muy bajo puede corresponder a un cambio absoluto irrelevante. Se mide 10 a 15 minutos despues de 200 a 400 microgramos de salbutamol, y una prueba negativa no descarta el asma.', dificultad: 'facil' },
  { q: 'Que variabilidad diaria del flujo pico documenta el diagnostico en el adulto?', options: ['Mayor del 10%', 'Mayor del 5%', 'Mayor del 25%', 'Mayor del 40%'], correct: 0, explanation: 'Se calcula como media de la amplitud diurna a lo largo de al menos 2 semanas con dos medidas diarias. Un solo dia por encima del umbral no diagnostica nada, y el registro tiene el valor a&#241;adido de ense&#241;ar al paciente a reconocer su propio deterioro.', dificultad: 'intermedio' },
  { q: 'Que papel tiene el oxido nitrico exhalado en el asma?', options: ['Confirma el diagnostico si supera el umbral', 'Sustituye a la espirometria en el seguimiento', 'Marca inflamacion tipo 2 y adherencia al corticoide', 'Cuantifica la gravedad de la crisis en urgencias'], correct: 2, explanation: 'Un valor alto predice respuesta al corticoide inhalado, y un descenso brusco suele indicar que el paciente ha empezado a tomarlo. Pero sube en la rinitis alergica y en la bronquitis eosinofilica, y baja con el tabaco y con la broncoconstriccion, de modo que no sirve como criterio diagnostico.', dificultad: 'intermedio' },
  { q: 'Que significa una prueba de provocacion con metacolina negativa?', options: ['Que el paciente tiene asma de tipo neutrofilico', 'Que el asma esta bien controlada con el tratamiento', 'Que hace falta repetirla con manitol para decidir', 'Que el asma activa queda practicamente descartada'], correct: 3, explanation: 'La prueba es muy sensible y poco especifica, de modo que su valor esta en el resultado negativo. Un resultado positivo aparece tambien en rinitis, EPOC, fibrosis quistica e insuficiencia cardiaca, y por eso no confirma el asma por si solo.', dificultad: 'dificil' },
  { q: 'Cual es la recomendacion actual sobre el broncodilatador de accion corta en monoterapia?', options: ['Se mantiene como opcion en el asma leve', 'No se recomienda en ningun paciente con asma', 'Se reserva a la broncoconstriccion por ejercicio', 'Se usa hasta que aparezcan sintomas nocturnos'], correct: 1, explanation: 'Alivia el sintoma sin tocar la inflamacion, permite tolerar un asma cada vez peor sin consultar, y su uso frecuente se asocia a exacerbaciones graves y a muerte por asma. Todo paciente debe recibir corticoide inhalado, aunque sea solo cuando tiene sintomas.', dificultad: 'facil' },
  { q: 'Cual es el tratamiento preferido en los escalones 1 y 2 de GINA?', options: ['Corticoide inhalado diario a dosis baja', 'Antileucotrieno oral diario', 'Corticoide inhalado con formoterol a demanda', 'Corticoide inhalado con LABA de mantenimiento'], correct: 2, explanation: 'Los ensayos SYGMA y Novel START mostraron que esta pauta reduce las exacerbaciones graves frente al rescate con broncodilatador solo, y con mucha menos exposicion acumulada a corticoide que el mantenimiento diario. La clave es que el paciente recibe antiinflamatorio cada vez que se alivia.', dificultad: 'intermedio' },
  { q: 'Que caracteriza al esquema de mantenimiento y rescate con un unico inhalador?', options: ['El mismo inhalador se usa a diario y a demanda', 'El rescate se hace con un broncodilatador aparte', 'El corticoide se toma solo cuando hay sintomas', 'La dosis diaria se ajusta segun el flujo pico'], correct: 0, explanation: 'Se emplea la combinacion de corticoide inhalado con formoterol tanto en las dosis fijas diarias como en las de alivio, de modo que cada rescate a&#241;ade antiinflamatorio justo cuando el paciente esta peor. Corresponde a los escalones 3 y 4 de la via preferida.', dificultad: 'intermedio' },
  { q: 'Cuantas preguntas componen el control sintomatico de GINA?', options: ['Tres preguntas', 'Cuatro preguntas', 'Cinco preguntas', 'Siete preguntas'], correct: 1, explanation: 'Sintomas diurnos mas de dos veces por semana, despertar nocturno por asma, uso del rescate mas de dos veces por semana y limitacion de la actividad, referidas a las ultimas 4 semanas. Ninguna afirmativa es control bueno, una o dos parcial, y tres o cuatro asma no controlada.', dificultad: 'facil' },
  { q: 'Que puntuacion del test ACT indica asma bien controlada?', options: ['12 o mas', '15 o mas', '18 o mas', '20 o mas'], correct: 3, explanation: 'La escala va de 5 a 25 puntos. De 16 a 19 es asma no bien controlada y 15 o menos es control muy pobre. Un cambio de 3 puntos es clinicamente relevante, lo que hace al test util para seguimiento a distancia.', dificultad: 'intermedio' },
  { q: 'Que relacion hay entre el control sintomatico y el riesgo futuro de exacerbacion?', options: ['El control predice bien el riesgo futuro', 'El riesgo se calcula a partir del ACT', 'Son dimensiones independientes', 'El riesgo solo importa si hay mal control'], correct: 2, explanation: 'Un paciente con pocos sintomas puede estar en altisimo riesgo por haber sido intubado alguna vez, no usar corticoide inhalado, gastar mas de un envase de rescate al mes o tener un FEV1 bajo. Por eso las dos dimensiones se valoran por separado en cada consulta.', dificultad: 'intermedio' },
  { q: 'Como se establece la gravedad del asma?', options: ['Por el escalon de tratamiento que necesita', 'Por el valor del FEV1 en la primera espirometria', 'Por el numero de sintomas nocturnos semanales', 'Por la cifra de eosinofilos en sangre periferica'], correct: 0, explanation: 'Es una definicion retrospectiva: no se puede etiquetar a un paciente de asma grave hasta haberlo tratado bien durante meses. Leve si se controla en los escalones 1 y 2, moderada en el 3, y grave si necesita el 4 o el 5 o sigue sin control en ellos.', dificultad: 'dificil' },
  { q: 'Cuando debe administrarse el corticoide sistemico en la crisis asmatica?', options: ['Solo si no responde a tres tandas de salbutamol', 'Al alta, para prevenir la recaida', 'Cuando el flujo pico baja del 50%', 'En la primera hora, en casi todas las crisis'], correct: 3, explanation: 'Su efecto tarda horas en aparecer, de modo que retrasarlo desplaza toda la curva de mejoria. Reduce ingresos y recaidas y se pauta en practicamente toda crisis que llega al hospital, con independencia de la respuesta inicial al broncodilatador.', dificultad: 'facil' },
  { q: 'Que pauta de corticoide oral corresponde a la crisis asmatica del adulto?', options: ['Prednisona 20 mg al dia durante 10 dias', 'Prednisona 40 a 50 mg, 5 a 7 dias', 'Prednisona 60 mg al dia durante 14 dias', 'Prednisona 30 mg al dia durante 3 dias'], correct: 1, explanation: 'No hace falta pauta descendente en un ciclo tan corto, y la via oral es tan eficaz como la intravenosa si el paciente tolera. Prolongarlo mas alla de una semana a&#241;ade efectos adversos sin mejorar el resultado.', dificultad: 'facil' },
  { q: 'Cual es el objetivo de saturacion en la crisis asmatica del adulto no gestante?', options: ['Del 93 al 95%', 'Del 88 al 92%', 'Por encima del 97%', 'Del 85 al 90%'], correct: 0, explanation: 'A diferencia de la EPOC, aqui no se busca la ventana baja del 88 al 92%, pero tampoco se persigue la saturacion maxima: el oxigeno excesivo tambien empeora el intercambio en el asma. En la gestante el objetivo sube al 94 al 98% porque el feto tolera mal la hipoxemia.', dificultad: 'intermedio' },
  { q: 'Que significa una PaCO2 normal en un paciente en plena crisis asmatica?', options: ['Que la crisis esta respondiendo al tratamiento', 'Que la gasometria se ha extraido con retraso', 'Que el paciente esta agotandose', 'Que coexiste una alcalosis metabolica'], correct: 2, explanation: 'Lo esperable en una crisis es que el paciente hiperventile y la PaCO2 este baja. Que se haya normalizado significa que el musculo respiratorio ya no puede mantener esa hiperventilacion, y anuncia el fracaso ventilatorio: es un signo de alarma, no de mejoria.', dificultad: 'intermedio' },
  { q: 'Que indica un torax silente en un paciente con crisis asmatica?', options: ['Que el broncoespasmo ha cedido', 'Que no se mueve aire suficiente', 'Que hay un derrame pleural asociado', 'Que el diagnostico probablemente sea otro'], correct: 1, explanation: 'Las sibilancias necesitan flujo aereo para producirse, de modo que su desaparicion en un paciente que empeora indica obstruccion extrema. Es uno de los signos de riesgo vital, junto con la somnolencia, la confusion y la PaCO2 normal o en ascenso.', dificultad: 'facil' },
  { q: 'Cuando esta indicado el sulfato de magnesio intravenoso en la crisis asmatica?', options: ['En toda crisis que acude al hospital', 'Como sustituto del corticoide sistemico', 'Antes del primer broncodilatador', 'En la crisis grave que no responde al inicio'], correct: 3, explanation: 'Se administran 2 g intravenosos en 20 minutos. Reduce ingresos en el subgrupo de crisis graves refractarias al tratamiento inicial, pero no aporta nada en la crisis leve o moderada y no sustituye a ninguno de los pilares del tratamiento.', dificultad: 'intermedio' },
  { q: 'Que conducta corresponde al antibiotico en la crisis asmatica?', options: ['No pautarlo salvo evidencia de infeccion bacteriana', 'Pautarlo si el esputo cambia de color', 'Pautarlo en toda crisis que requiere ingreso', 'Pautarlo si la proteina C reactiva esta elevada'], correct: 0, explanation: 'La mayoria de las crisis son de origen viral o alergico. El cambio de color del esputo se debe a los propios eosinofilos y no indica infeccion bacteriana, a diferencia de lo que ocurre en la exacerbacion de la EPOC.', dificultad: 'intermedio' },
  { q: 'Que debe llevar el paciente al alta tras una crisis asmatica?', options: ['Un broncodilatador de rescate y cita en un mes', 'Antibiotico de amplio espectro durante una semana', 'Corticoide inhalado, plan escrito y cita en 2 a 7 dias', 'Corticoide oral en pauta descendente de tres semanas'], correct: 2, explanation: 'Dar el alta solo con un broncodilatador es el error que mas muertes evitables ha producido en este tema. Una crisis siempre significa que el tratamiento de fondo era insuficiente o no se estaba tomando, de modo que hay que iniciarlo o subirlo antes de que el paciente se vaya.', dificultad: 'facil' },
  { q: 'Cual es el primer paso ante un paciente que no se controla con dosis altas de corticoide inhalado y LABA?', options: ['Iniciar un biologico dirigido al fenotipo', 'A&#241;adir corticoide oral de mantenimiento', 'Solicitar tomografia de torax de alta resolucion', 'Comprobar el diagnostico, la tecnica y la adherencia'], correct: 3, explanation: 'Solo entre el 3 y el 10% de los asmaticos tienen asma grave de verdad. La mayoria de los remitidos como graves tienen mala tecnica, mala adherencia, una comorbilidad no tratada o un diagnostico equivocado, y saltarse ese orden convierte un asma mal tratada en candidata a biologico.', dificultad: 'intermedio' },
  { q: 'Que cifra de eosinofilos en sangre apoya el fenotipo tipo 2?', options: ['50 por microlitro o mas', '150 por microlitro o mas', '500 por microlitro o mas', '1500 por microlitro o mas'], correct: 1, explanation: 'Junto con un oxido nitrico exhalado de 20 partes por mil millones o mas, eosinofilos en esputo del 2% o mas, el desencadenante alergico claro y la dependencia de corticoide oral. Todos se miden sin corticoide sistemico, que los suprime y da falsos negativos.', dificultad: 'intermedio' },
  { q: 'Que biologico se prefiere en el asma grave con poliposis nasosinusal y dermatitis atopica?', options: ['Dupilumab', 'Omalizumab', 'Benralizumab', 'Tezepelumab'], correct: 0, explanation: 'Bloquea el receptor de la interleucina 4 y actua sobre las tres enfermedades a la vez, ademas de tener indicacion en el paciente dependiente de corticoide oral. Puede producir una eosinofilia transitoria que en la mayoria de los casos es asintomatica.', dificultad: 'intermedio' },
  { q: 'Que biologico es eficaz en el asma grave con eosinofilos bajos?', options: ['Mepolizumab', 'Reslizumab', 'Tezepelumab', 'Omalizumab'], correct: 2, explanation: 'Bloquea la linfopoyetina estromal timica, que actua por encima de la cascada inflamatoria, y es el unico que ha demostrado reducir exacerbaciones tambien cuando los biomarcadores tipo 2 son bajos. Los dirigidos a la interleucina 5 dependen de la cifra de eosinofilos.', dificultad: 'dificil' },
  { q: 'Que requisito se necesita para indicar omalizumab?', options: ['Eosinofilos por encima de 300 por microlitro', 'Sensibilizacion a un aeroalergeno perenne', 'Dependencia de corticoide oral de mantenimiento', 'Oxido nitrico exhalado por encima de 50 partes'], correct: 1, explanation: 'Es un anticuerpo anti-IgE y exige alergia demostrada mas una IgE total dentro del rango de dosificacion segun el peso. Mejora ademas la urticaria cronica y la poliposis cuando coexisten con el asma.', dificultad: 'intermedio' },
  { q: 'Que pregunta orienta hacia un asma de origen ocupacional?', options: ['Ha tenido usted alguna vez alergia alimentaria?', 'Fuma usted o ha fumado alguna vez?', 'Tiene antecedentes familiares de asma?', 'Mejora usted en vacaciones y fines de semana?'], correct: 3, explanation: 'Es la pregunta que hay que hacer a todo asmatico de inicio en la edad adulta, porque del 10 al 25% de esos casos son ocupacionales. El patron se pierde cuando la enfermedad avanza, ya que la inflamacion tarda cada vez mas en revertir tras el periodo de descanso.', dificultad: 'intermedio' },
  { q: 'Cual es el tratamiento del asma ocupacional por un agente sensibilizante?', options: ['Subir el corticoide inhalado a dosis altas', 'A&#241;adir un antileucotrieno de forma indefinida', 'Retirar la exposicion cuanto antes', 'Usar mascarilla de proteccion en la jornada'], correct: 2, explanation: 'Es lo unico asociado a remision, y la probabilidad de conseguirla cae con cada a&#241;o de exposicion continuada tras el inicio de los sintomas. El tratamiento farmacologico habitual se mantiene, pero no sustituye a la retirada, y la proteccion respiratoria es una solucion peor cuando esta no es posible.', dificultad: 'intermedio' },
  { q: 'Cual es el mecanismo de la enfermedad respiratoria exacerbada por antiinflamatorios?', options: ['Desvio del acido araquidonico hacia los leucotrienos', 'Reaccion de hipersensibilidad mediada por IgE', 'Activacion directa de los mastocitos por el farmaco', 'Deposito de inmunocomplejos en la mucosa bronquial'], correct: 0, explanation: 'No es una alergia. Estos pacientes sobreproducen cisteinil-leucotrienos y producen poca prostaglandina E2, que normalmente frena esa via; al inhibir la ciclooxigenasa 1 se retira el freno. Por eso reaccionan a cualquier inhibidor de esa enzima y toleran los selectivos de la ciclooxigenasa 2.', dificultad: 'dificil' },
  { q: 'Que prueba confirma la enfermedad respiratoria exacerbada por antiinflamatorios?', options: ['La determinacion de IgE especifica frente al farmaco', 'La prueba cutanea con acido acetilsalicilico', 'El recuento de eosinofilos en sangre periferica', 'La provocacion controlada en centro experto'], correct: 3, explanation: 'No existe ninguna prueba in vitro ni cutanea que la diagnostique, precisamente porque no es una reaccion mediada por IgE. El diagnostico es clinico ante la triada de asma, poliposis y reaccion a los antiinflamatorios, y solo se confirma con provocacion cuando es imprescindible.', dificultad: 'intermedio' },
  { q: 'Que conducta corresponde al corticoide inhalado en una gestante con asma?', options: ['Sustituirlo por un antileucotrieno oral', 'Mantenerlo sin cambios durante el embarazo', 'Suspenderlo durante el primer trimestre', 'Reducirlo a la mitad hasta el parto'], correct: 1, explanation: 'El riesgo de una crisis para el feto supera con mucho al de los farmacos: la hipoxemia materna compromete directamente la oxigenacion fetal, y el asma mal controlada se asocia a prematuridad, bajo peso y preeclampsia. El abandono por miedo infundado al farmaco es una causa clasica de deterioro en el embarazo.', dificultad: 'facil' },

  { type: 'cascade', vignette: 'Mujer de 28 a&#241;os con tos seca nocturna y opresion toracica desde hace 6 meses, peores en primavera y al correr. Antecedente de rinitis alergica. Exploracion normal. Espirometria: FEV1/FVC de 0.68, FEV1 de 2100 mL (72% del predicho). Tras 400 microgramos de salbutamol el FEV1 sube a 2480 mL.', steps: [
    { q: 'Como se interpreta la prueba broncodilatadora?', options: ['Negativa: el ascenso no llega a 400 mL', 'Negativa: el ascenso porcentual es menor del 15%', 'No valorable sin conocer el flujo pico', 'Positiva: sube mas del 12% y mas de 200 mL'], correct: 3 },
    { q: 'Cual es el tratamiento inicial mas apropiado?', options: ['Salbutamol a demanda como unico tratamiento', 'Corticoide inhalado con formoterol a demanda', 'Antileucotrieno oral diario en monoterapia', 'Corticoide oral en pauta corta y revision'], correct: 1 },
    { q: 'Que hay que a&#241;adir siempre a la prescripcion?', options: ['Antibiotico profilactico en primavera', 'Registro diario del oxido nitrico exhalado', 'Plan de accion escrito y tecnica del inhalador', 'Provocacion con metacolina de confirmacion'], correct: 2 }
  ], explanation: 'Un ascenso de 380 mL y del 18% cumple los dos criterios a la vez, de modo que documenta la limitacion variable y confirma el asma en una historia compatible. El escalon inicial de la via preferida es corticoide inhalado con formoterol a demanda, nunca un broncodilatador solo. La provocacion no aporta nada cuando la variabilidad ya esta documentada, y el plan de accion escrito con la tecnica del inhalador comprobada es una de las pocas intervenciones con impacto demostrado en ingresos.', dificultad: 'facil' },

  { type: 'cascade', vignette: 'Varon de 34 a&#241;os traido a urgencias por crisis asmatica. Habla con palabras sueltas, sentado e inclinado hacia delante, con tiraje. Frecuencia respiratoria de 34, frecuencia cardiaca de 128, saturacion del 88% en aire ambiente. Flujo pico del 40% de su mejor valor. Refiere que gasta un envase de salbutamol cada tres semanas.', steps: [
    { q: 'Como se clasifica la crisis?', options: ['Crisis grave', 'Crisis leve o moderada', 'Crisis de riesgo vital', 'Crisis no valorable sin gasometria'], correct: 0 },
    { q: 'Que tratamiento corresponde en la primera hora?', options: ['Salbutamol y antibiotico de amplio espectro', 'Salbutamol, ipratropio y corticoide sistemico', 'Salbutamol y aminofilina en perfusion continua', 'Salbutamol y ventilacion no invasiva inmediata'], correct: 1 },
    { q: 'Que dato de su historia predice mejor una crisis futura grave?', options: ['La edad y el sexo del paciente', 'La ausencia de fiebre y de expectoracion purulenta', 'El flujo pico del 40% al llegar', 'El consumo elevado de broncodilatador de rescate'], correct: 3 }
  ], explanation: 'Hablar con palabras sueltas, taquipnea mayor de 30, taquicardia mayor de 120, saturacion menor del 90% y flujo pico del 50% o menos definen la crisis grave, sin que haya todavia signos de riesgo vital. El tratamiento a&#241;ade ipratropio al salbutamol y exige corticoide sistemico en la primera hora, sin antibiotico ni aminofilina. Gastar mas de un envase de rescate al mes es un factor de riesgo consistente de exacerbacion grave y de muerte por asma.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Mujer de 46 a&#241;os con asma desde los 40, sin atopia, con poliposis nasal y anosmia. Sigue con sintomas diarios y dos ciclos de corticoide oral en el ultimo a&#241;o pese a dosis altas de corticoide inhalado con LABA. Refiere que se ahoga al tomar ibuprofeno. Eosinofilos de 620 por microlitro. La enfermera comprueba que la tecnica del inhalador es correcta y las dispensaciones son regulares.', steps: [
    { q: 'Que diagnostico integra todo el cuadro?', options: ['Aspergilosis broncopulmonar alergica', 'Enfermedad exacerbada por antiinflamatorios', 'Granulomatosis eosinofilica con poliangeitis', 'Disfuncion de cuerdas vocales asociada al asma'], correct: 1 },
    { q: 'Que analgesico se le puede ofrecer?', options: ['Naproxeno a dosis analgesica', 'Acido acetilsalicilico a dosis baja', 'Diclofenaco por via topica', 'Paracetamol a dosis baja'], correct: 3 },
    { q: 'Que biologico es el mas indicado en su caso?', options: ['Dupilumab', 'Omalizumab', 'Tezepelumab', 'Reslizumab'], correct: 0 }
  ], explanation: 'Asma del adulto sin atopia, poliposis con anosmia y reaccion a un antiinflamatorio componen la triada, cuyo mecanismo es el desvio del acido araquidonico hacia los leucotrienos al inhibirse la ciclooxigenasa 1. Se toleran el paracetamol a dosis bajas y los inhibidores selectivos de la ciclooxigenasa 2, pero no los demas antiinflamatorios, incluida la via topica en algunos pacientes. Con adherencia y tecnica ya comprobadas y poliposis asociada, dupilumab actua a la vez sobre el asma y sobre los polipos.', dificultad: 'dificil' },

  { type: 'cascade', vignette: 'Varon de 31 a&#241;os, panadero desde hace 4 a&#241;os, con tos, sibilancias y rinitis de un a&#241;o de evolucion. No fuma. Dice encontrarse bien durante las vacaciones y volver a estar mal a los dos dias de reincorporarse. Espirometria basal normal en la consulta del lunes por la ma&#241;ana.', steps: [
    { q: 'Que prueba resulta mas util para confirmar la sospecha?', options: ['Tomografia de torax de alta resolucion', 'Registro seriado del flujo pico dentro y fuera del trabajo', 'Espirometria repetida en la consulta cada mes', 'Determinacion de precipitinas frente a Aspergillus fumigatus'], correct: 1 },
    { q: 'Cual es la medida terapeutica decisiva?', options: ['Retirar la exposicion al agente causal', 'Iniciar corticoide inhalado a dosis altas', 'Prescribir un antileucotrieno de mantenimiento', 'Indicar mascarilla de proteccion en la jornada'], correct: 0 },
    { q: 'Que actuacion adicional corresponde en este caso?', options: ['Solicitar provocacion con metacolina de control', 'Repetir la espirometria basal a los 6 meses', 'Notificar como enfermedad profesional', 'Iniciar inmunoterapia con extracto de harina'], correct: 2 }
  ], explanation: 'La mejoria en vacaciones con recaida al reincorporarse es el patron clasico, y el registro seriado de flujo pico en periodo laboral y de descanso es la prueba mas accesible para documentarlo. Una espirometria normal el lunes por la ma&#241;ana no descarta nada. La retirada precoz de la exposicion es lo unico asociado a remision, y el caso debe notificarse como enfermedad profesional, lo que ademas obliga a vigilar a los compa&#241;eros del mismo puesto.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Mujer de 30 a&#241;os embarazada de 26 semanas, con asma conocida. Acude por disnea y sibilancias de 2 dias. Suspendio el corticoide inhalado al saber que estaba embarazada. Habla con frases, frecuencia respiratoria de 26, frecuencia cardiaca de 108, saturacion del 92%.', steps: [
    { q: 'Cual es la causa mas probable del deterioro?', options: ['El aumento fisiologico de la ventilacion del embarazo', 'La compresion diafragmatica por el utero grande', 'El reflujo gastroesofagico propio de la gestacion', 'La retirada del corticoide inhalado'], correct: 3 },
    { q: 'Que objetivo de saturacion corresponde en esta paciente?', options: ['Del 88 al 92%', 'Del 90 al 93%', 'Del 94 al 98%', 'Por encima del 99%'], correct: 2 },
    { q: 'Que conducta es correcta respecto al tratamiento de fondo?', options: ['Reanudar el corticoide inhalado sin demora', 'Esperar al posparto para reintroducirlo', 'Sustituirlo por un antileucotrieno oral', 'Usar solo broncodilatador hasta el tercer trimestre'], correct: 0 }
  ], explanation: 'El abandono del corticoide inhalado por miedo infundado al farmaco es una causa clasica de deterioro en el embarazo, y ocurre justo en el periodo de mayor riesgo, que es el segundo y el tercer trimestre. El objetivo de saturacion en la gestante es mas alto que en la mujer no embarazada porque el feto tolera mal la hipoxemia. El riesgo de una crisis supera con mucho al de cualquiera de los farmacos habituales del asma.', dificultad: 'facil' },

  { type: 'cascade', vignette: 'Varon de 52 a&#241;os con asma desde la infancia y 30 paquetes-a&#241;o de tabaco. Disnea de esfuerzo progresiva y dos exacerbaciones el ultimo a&#241;o. Espirometria posbroncodilatador: FEV1/FVC de 0.62 con FEV1 del 55%, con ascenso del 9% tras salbutamol. Eosinofilos de 340 por microlitro. La tomografia muestra enfisema centrolobulillar leve.', steps: [
    { q: 'Como se describe mejor la situacion del paciente?', options: ['Asma grave con obstruccion fija', 'Coexistencia de asma y EPOC', 'EPOC pura de origen tabaquico', 'Bronquiectasias con obstruccion asociada'], correct: 1 },
    { q: 'Que decision es la mas importante en su tratamiento?', options: ['Mantener el corticoide inhalado', 'Iniciar roflumilast por las exacerbaciones', 'A&#241;adir azitromicina de mantenimiento', 'Solicitar valoracion para biologico'], correct: 0 },
    { q: 'Que se a&#241;ade sobre esa base?', options: ['Corticoide oral a dias alternos', 'Antileucotrieno oral diario', 'Doble broncodilatacion con LABA y LAMA', 'Teofilina de liberacion prolongada'], correct: 2 }
  ], explanation: 'Un asma de la infancia con carga tabaquica importante, obstruccion no del todo reversible y enfisema corresponde a la coexistencia de las dos enfermedades, que GINA prefiere describir asi en lugar de como un sindrome propio. El error clasico es etiquetarlo solo de EPOC y retirarle el corticoide inhalado: en presencia del componente asmatico eso expone al paciente a crisis graves. Sobre el corticoide inhalado se a&#241;ade la doble broncodilatacion.', dificultad: 'dificil' }
];

export const flashcards = [
  { front: 'Definicion de asma en una palabra', back: 'VARIABLE: sintomas que varian y limitacion variable al flujo aereo espiratorio.' },
  { front: 'Prueba broncodilatadora positiva en el adulto', back: 'Ascenso del FEV1 mayor del 12% Y de mas de 200 mL.' },
  { front: 'Variabilidad del flujo pico diagnostica', back: 'Amplitud diurna media mayor del 10% en el adulto, en 2 semanas con dos medidas diarias.' },
  { front: 'Cuando hay que documentar la variabilidad', back: 'ANTES de iniciar el corticoide inhalado: despues la variabilidad se aplana.' },
  { front: 'Papel del oxido nitrico exhalado', back: 'Marcador de inflamacion tipo 2 y de adherencia. NO es criterio diagnostico.' },
  { front: 'Valor de la provocacion con metacolina', back: 'Muy sensible y poco especifica: su valor esta en el resultado NEGATIVO, que descarta.' },
  { front: 'Regla que ha cambiado el tratamiento del asma', back: 'El broncodilatador de accion corta en monoterapia no es tratamiento para NADIE.' },
  { front: 'Escalones 1 y 2 de la via preferida', back: 'Corticoide inhalado con formoterol a dosis baja, solo a demanda.' },
  { front: 'Escalones 3 y 4 de la via preferida', back: 'Mismo inhalador de mantenimiento y rescate, a dosis baja y despues media.' },
  { front: 'Las cuatro preguntas del control de GINA', back: 'Sintomas diurnos, despertar nocturno, uso del rescate y limitacion de la actividad.' },
  { front: 'Umbrales del control de GINA', back: '0 afirmativas bien controlada, 1 o 2 parcialmente, 3 o 4 no controlada.' },
  { front: 'Umbrales del test ACT', back: '20 o mas bien controlada, 16 a 19 no bien controlada, 15 o menos muy mal controlada.' },
  { front: 'Control y riesgo futuro', back: 'Son dimensiones INDEPENDIENTES: se puede estar poco sintomatico y en alto riesgo.' },
  { front: 'Factor de riesgo mas potente de muerte por asma', back: 'La intubacion o el ingreso en cuidados intensivos por asma en cualquier momento.' },
  { front: 'Consumo de rescate que marca riesgo', back: 'Mas de un envase al mes se asocia a crisis graves y a mortalidad.' },
  { front: 'Como se define la gravedad del asma', back: 'De forma retrospectiva, por el escalon de tratamiento necesario para el control.' },
  { front: 'Corticoide sistemico en la crisis', back: 'En la PRIMERA HORA: prednisona 40 a 50 mg, 5 a 7 dias, sin pauta descendente.' },
  { front: 'Objetivo de saturacion en la crisis', back: 'Del 93 al 95% en el adulto y del 94 al 98% en la gestante.' },
  { front: 'PaCO2 normal en plena crisis', back: 'Signo de ALARMA: el paciente ya no puede mantener la hiperventilacion.' },
  { front: 'Torax silente', back: 'No es mejoria: no hay flujo aereo suficiente para generar sibilancias.' },
  { front: 'Signos de riesgo vital en la crisis', back: 'Somnolencia o confusion, torax silente y PaCO2 normal o en ascenso.' },
  { front: 'Sulfato de magnesio en la crisis', back: '2 g intravenosos en 20 minutos, solo en la crisis grave que no responde al inicio.' },
  { front: 'Antibiotico en la crisis asmatica', back: 'No de rutina: la mayoria son virales o alergicas, y el esputo se ti&#241;e por eosinofilos.' },
  { front: 'Lo que nunca falta al alta tras una crisis', back: 'Corticoide inhalado, plan de accion escrito, tecnica revisada y cita en 2 a 7 dias.' },
  { front: 'Primer paso ante un asma que no se controla', back: 'Confirmar diagnostico, tecnica, adherencia y comorbilidades, ANTES de subir de escalon.' },
  { front: 'Biomarcadores de inflamacion tipo 2', back: 'Eosinofilos 150/microlitro o mas, oxido nitrico 20 ppb o mas, eosinofilos en esputo 2% o mas.' },
  { front: 'Biologico si hay poliposis o dermatitis atopica', back: 'Dupilumab, que actua sobre las tres enfermedades a la vez.' },
  { front: 'Biologico si los eosinofilos son bajos', back: 'Tezepelumab, el unico eficaz sin fenotipo tipo 2 claro.' },
  { front: 'Pregunta clave del asma ocupacional', back: 'Mejora en vacaciones y fines de semana? El tratamiento es retirar la exposicion.' },
  { front: 'Mecanismo de la enfermedad exacerbada por antiinflamatorios', back: 'Desvio del acido araquidonico hacia los leucotrienos al inhibirse la ciclooxigenasa 1.' },
  { front: 'Como NO se diagnostica esa enfermedad', back: 'Con pruebas de alergia: no es IgE mediada. Se confirma con provocacion controlada.' },
  { front: 'Corticoide inhalado en el embarazo', back: 'No se suspende: el riesgo de la crisis para el feto supera al del farmaco.' }
];

export default { quiz, flashcards };
