// topics/exploracion-piel-faneras/study.js — Autoevaluación de Exploración de Piel y Faneras.
// Mismo patrón que historia-clinica/study.js y los demás temas de Semiología: banco único,
// preguntas sueltas + preguntas en cascada sobre una viñeta (retroalimentación consolidada al
// final, sin revelar correcto/incorrecto paso a paso). Redacción de opciones sujeta a
// .claude/skills/reglas-preguntas/SKILL.md (misma categoría lógica, longitud/detalle comparables,
// sin pistas gramaticales/semánticas, posición de `correct` distribuida sin patrón a lo largo de
// todo el array).

export const quiz = [
  { q: '¿Para qué sirve la maniobra de vitropresión (diascopia)?', options: ['Para medir con precisión el tamaño exacto de una lesión', 'Para evaluar la temperatura local de la piel afectada', 'Para distinguir si una lesión roja es vascular o purpúrica', 'Para diagnosticar un melanoma de forma directa e inmediata'], correct: 2, explanation: 'Al presionar un vidrio transparente sobre la lesión, el eritema (vascular) blanquea porque la sangre está dentro de los vasos y se desplaza; la púrpura no blanquea porque la sangre ya está extravasada en el tejido.', dificultad: 'facil' },
  { q: 'Una lesión roja que NO blanquea con la vitropresión debe interpretarse como:', options: ['Púrpura, hasta demostrar lo contrario; obliga a descartar coagulopatía o vasculitis', 'Un eritema normal, sin ninguna implicación patológica', 'Siempre un hallazgo benigno, sin necesidad de más estudio', 'Un signo aislado de deshidratación leve'], correct: 0, explanation: 'La ausencia de blanqueamiento indica que la sangre ya salió de los vasos hacia el tejido (extravasación), lo que obliga a descartar trastornos de la coagulación o vasculitis.', dificultad: 'intermedio' },
  { q: '¿Qué diferencia a una mácula de una mancha?', options: ['La mácula es palpable y la mancha no', 'La mancha siempre es de origen purpúrico', 'La mácula solo puede ser de color rojo', 'Únicamente el tamaño: mácula &lt;1 cm, mancha &gt;1 cm; ninguna es palpable'], correct: 3, explanation: 'Mácula y mancha son cambios de color planos, no palpables; se diferencian solo por el tamaño (corte en 1 cm).', dificultad: 'facil' },
  { q: '¿Cuáles son los 3 orígenes posibles de una mácula o mancha?', options: ['Solo vascular', 'Vascular, pigmentario o purpúrico', 'Solo infeccioso', 'Solo traumático'], correct: 1, explanation: 'Una mácula/mancha puede deberse a un cambio vascular (eritema), pigmentario (hiper/hipopigmentación) o a extravasación de sangre (púrpura).', dificultad: 'intermedio' },
  { q: '¿Qué diferencia principal hay entre una pápula y un nódulo, más allá del tamaño?', options: ['El nódulo compromete dermis profunda/hipodermis, "se palpa más profundo de lo que se ve"', 'No hay ninguna diferencia real entre ambas lesiones', 'La pápula siempre contiene líquido en su interior', 'El nódulo nunca llega a ser una lesión palpable'], correct: 0, explanation: 'El nódulo se extiende a planos más profundos (dermis profunda/hipodermis), por lo que al palparlo se percibe más profundo de lo que sugiere su apariencia visual, a diferencia de la pápula, más superficial.', dificultad: 'facil' },
  { q: '¿Qué mecanismo genera la roncha (habón)?', options: ['Acumulación de queratina en el estrato córneo superficial', 'Depósito de melanina en la capa basal epidérmica', 'Proliferación excesiva de queratinocitos en la epidermis', 'Edema transitorio de la dermis por degranulación de mastocitos e histamina'], correct: 3, explanation: 'La histamina liberada por la degranulación de mastocitos aumenta la permeabilidad vascular, generando el edema dérmico transitorio característico de la roncha.', dificultad: 'intermedio' },
  { q: 'Si una lesión "en roncha" persiste MÁS de 24 horas en el mismo sitio, ¿qué se debe sospechar?', options: ['Una urticaria simple, solo más intensa de lo habitual', 'Vasculitis urticarial, que amerita biopsia', 'Es normal, las ronchas pueden durar varios días sin problema', 'Una reacción alérgica leve, sin ninguna importancia clínica'], correct: 1, explanation: 'Cada roncha de la urticaria simple dura típicamente &lt;24 horas; una lesión fija que persiste más tiempo (documentable marcando su contorno) sugiere vasculitis urticarial, una entidad distinta que requiere biopsia.', dificultad: 'dificil' },
  { q: '¿Qué diferencia a una vesícula de una ampolla (bulla)?', options: ['El tipo de contenido líquido de cada una', 'La vesícula siempre tiene contenido purulento', 'Únicamente el tamaño: vesícula &lt;1 cm, ampolla &gt;1 cm; ambas con líquido claro', 'La ampolla nunca llega a ser una lesión palpable'], correct: 2, explanation: 'Vesícula y ampolla comparten el mismo tipo de contenido (líquido claro) y se diferencian solo por el tamaño.', dificultad: 'facil' },
  { q: '¿Qué determina que el signo de Nikolsky sea positivo en una enfermedad ampollosa?', options: ['La edad del paciente al momento del diagnóstico', 'Que la ampolla contenga pus en su interior', 'El tamaño de la ampolla, sin relación con el plano anatómico', 'Que el plano de la ampolla sea intraepidérmico (acantólisis), haciéndola flácida y frágil'], correct: 3, explanation: 'Las ampollas intraepidérmicas, por pérdida de adhesión entre queratinocitos (acantólisis), son frágiles y la fricción sobre piel perilesional de aspecto sano puede generar una ampolla nueva: Nikolsky positivo.', dificultad: 'dificil' },
  { q: '¿Cómo se diferencian el pénfigo vulgar y el penfigoide ampolloso por el plano de la ampolla?', options: ['Son completamente indistinguibles entre sí desde el punto de vista clínico', 'Pénfigo: ampollas flácidas, intraepidérmicas, Nikolsky positivo. Penfigoide: ampollas tensas, subepidérmicas, Nikolsky negativo', 'Penfigoide siempre presenta un signo de Nikolsky claramente positivo', 'Pénfigo siempre produce ampollas de consistencia tensa y resistente'], correct: 1, explanation: 'El plano de clivaje anatómico (intraepidérmico por acantólisis en el pénfigo vs. subepidérmico por autoanticuerpos contra hemidesmosomas en el penfigoide) determina directamente la fragilidad de la ampolla y el resultado del Nikolsky.', dificultad: 'dificil' },
  { q: '¿Qué diferencia a la erosión de la úlcera?', options: ['El color superficial que presenta la lesión', 'La erosión siempre es de mayor tamaño que la úlcera', 'La profundidad: la erosión llega a la epidermis; la úlcera alcanza la dermis', 'No hay ninguna diferencia real entre ambas lesiones'], correct: 2, explanation: 'La erosión respeta la membrana basal (solo epidermis); la úlcera compromete la dermis, con bordes y fondo definibles.', dificultad: 'facil' },
  { q: '¿Por qué la erosión cura sin dejar cicatriz, a diferencia de la úlcera?', options: ['Porque respeta la membrana basal y los anexos dérmicos, permitiendo reepitelización completa', 'Porque la erosión nunca llega a infectarse secundariamente', 'Porque la erosión es siempre de menor tamaño', 'Ambas lesiones curan siempre sin dejar cicatriz'], correct: 0, explanation: 'Al no destruir la dermis ni sus anexos, la erosión se reepiteliza por completo; la úlcera, al destruir la dermis, cicatriza con tejido de granulación y colágeno desorganizado.', dificultad: 'intermedio' },
  { q: 'Un patrón de distribución "en dermatoma" (banda que sigue una raíz nerviosa) es característico de:', options: ['Psoriasis', 'Herpes zóster', 'Urticaria', 'Vitíligo'], correct: 1, explanation: 'El herpes zóster ocurre por reactivación del virus varicela-zóster latente en un ganglio de la raíz dorsal, que viaja por el nervio sensitivo hasta la piel que inerva, generando el patrón en banda dermatomal.', dificultad: 'facil' },
  { q: 'Un patrón de distribución "anular" con aclaramiento central es característico de:', options: ['Melanoma', 'Pénfigo vulgar', 'Tiña (o granuloma anular, eritema migrans)', 'Alopecia areata'], correct: 2, explanation: 'El borde activo descamativo con aclaramiento central por resolución centrífuga es típico de la tiña, aunque el patrón anular también se ve en granuloma anular y eritema migrans.', dificultad: 'facil' },
  { q: '¿Qué es el fenómeno de Koebner y en qué enfermedades es característico?', options: ['Aparición de lesiones nuevas en sitios de trauma cutáneo previo', 'Un tipo específico de ampolla de plano subepidérmico', 'Un patrón específico de alopecia de tipo cicatricial', 'Un signo clínico exclusivo y característico del melanoma'], correct: 0, explanation: 'El fenómeno de Koebner (lesiones nuevas en sitios de trauma cutáneo, como un rasguño o una cicatriz quirúrgica) apoya activamente el diagnóstico de psoriasis, liquen plano o vitíligo.', dificultad: 'dificil' },
  { q: 'En la regla ABCDE del melanoma, ¿qué evalúa el criterio "D"?', options: ['Densidad de la lesión', 'Duración de la lesión en semanas', 'Distribución de la lesión en el cuerpo', 'Diámetro mayor a 6 mm'], correct: 3, explanation: 'El criterio D corresponde al diámetro, con un punto de corte aproximado de 6 mm (el tamaño de un borrador de lápiz).', dificultad: 'facil' },
  { q: '¿Qué es el "signo del patito feo" (ugly duckling sign)?', options: ['Un signo exclusivo y característico de las neoplasias benignas', 'Un patrón de distribución cutánea en forma de anillo', 'Una lesión distinta de los demás nevos del paciente, sospechosa aunque cumpla pocos criterios', 'Un hallazgo ungueal característico de hipoalbuminemia'], correct: 2, explanation: 'Los nevos de una persona suelen parecerse entre sí ("firma nevomelanocítica"); una lesión que se ve distinta a las demás es sospechosa aunque individualmente no cumpla con claridad varios criterios ABCDE.', dificultad: 'intermedio' },
  { q: '¿Por qué el criterio "E" (evolución) es el de mayor sensibilidad individual en el ABCDE?', options: ['Porque un melanoma temprano puede no cumplir A, B, C o D aún, pero siempre está cambiando', 'Porque es el único de los 5 criterios medible con una regla', 'Porque la evolución solo llega a aplicarse en lesiones benignas', 'No es en realidad más sensible que los demás criterios'], correct: 0, explanation: 'Un melanoma en etapa temprana puede parecer casi simétrico, de borde regular y pequeño diámetro, pero el cambio en el tiempo (evolución) suele estar presente incluso entonces.', dificultad: 'dificil' },
  { q: '¿Cuál es la presentación clínica típica del carcinoma basocelular?', options: ['Placa hiperqueratósica ulcerada de base indurada', 'Pápula o placa perlada/translúcida con telangiectasias y borde enrollado', 'Lesión pigmentada asimétrica de bordes irregulares', 'Roncha pruriginosa transitoria'], correct: 1, explanation: 'El carcinoma basocelular se presenta clásicamente como una lesión perlada/translúcida, con telangiectasias superficiales y un borde "enrollado", con frecuencia ulcerada en el centro.', dificultad: 'facil' },
  { q: 'De las 3 neoplasias cutáneas malignas más frecuentes, ¿cuál tiene el mayor potencial de diseminación temprana?', options: ['Carcinoma basocelular', 'Carcinoma espinocelular', 'Las 3 tienen exactamente el mismo potencial metastásico', 'Melanoma'], correct: 3, explanation: 'El melanoma tiene el mayor potencial de diseminación linfática y hematógena temprana de las 3, seguido del carcinoma espinocelular; el basocelular rara vez metastatiza.', dificultad: 'facil' },
  { q: '¿Por qué el subtipo NODULAR de melanoma es considerado el más agresivo?', options: ['Porque carece de fase de crecimiento radial previa, invadiendo vertical desde el inicio', 'Porque siempre corresponde a la lesión de mayor diámetro', 'Porque nunca llega a cumplir los criterios ABCDE', 'Porque solo llega a aparecer en personas jóvenes'], correct: 0, explanation: 'A diferencia de otros subtipos que tienen una fase de crecimiento superficial/radial detectable antes de invadir en profundidad, el melanoma nodular invade verticalmente casi desde su inicio, reduciendo la ventana para un diagnóstico temprano.', dificultad: 'dificil' },
  { q: '¿Por qué el melanoma acral lentiginoso se diagnostica con frecuencia de forma tardía?', options: ['Porque no llega a producir ningún síntoma reconocible', 'Porque nunca llega a cumplir los criterios ABCDE clásicos', 'Porque aparece en localizaciones poco examinadas (palmas, plantas, subungueal), sobre todo en piel oscura', 'Porque solo llega a afectar a pacientes pediátricos'], correct: 2, explanation: 'Al ubicarse en zonas poco examinadas de rutina (palmas, plantas, lecho ungueal) y ser el subtipo predominante en piel oscura, el melanoma acral lentiginoso suele diagnosticarse tarde si no se buscan activamente esas localizaciones.', dificultad: 'intermedio' },
  { q: '¿Qué es el signo de Schamroth y qué detecta?', options: ['Un patrón de distribución cutánea en forma de anillo', 'Una prueba específica para diagnosticar la psoriasis ungueal', 'Un hallazgo exclusivo y característico de la endocarditis', 'La desaparición del rombo entre uñas al juntarlas dorso con dorso; detecta acropaquia'], correct: 3, explanation: 'Normalmente, al juntar dorso con dorso las falanges distales de dos dedos opuestos, se forma un rombo entre las uñas; en la acropaquia ese espacio desaparece.', dificultad: 'facil' },
  { q: '¿Cuál es el mecanismo propuesto de la acropaquia (dedos en palillo de tambor)?', options: ['Depósito directo de colágeno inducido por la exposición solar', 'Megacariocitos que escapan el filtro pulmonar se depositan en el lecho ungueal', 'Una reacción alérgica a ciertos medicamentos específicos', 'Vasculitis exclusivamente de pequeño vaso, sin otro mecanismo'], correct: 1, explanation: 'En condiciones que permiten que megacariocitos/plaquetas eviten su fragmentación normal en el filtro pulmonar, estos se depositan distalmente y liberan factores de crecimiento que inducen la hiperplasia subungueal característica.', dificultad: 'dificil' },
  { q: '¿Qué representa una línea de Beau y cómo se puede estimar cuándo ocurrió el evento causante?', options: ['Un cambio de color permanente, sin forma de estimar el momento', 'Una hemorragia subungueal, siempre debida a trauma reciente', 'Un signo exclusivo y característico de la psoriasis', 'Un surco transversal por interrupción del crecimiento; la distancia desde la cutícula estima el momento'], correct: 3, explanation: 'La línea de Beau marca el punto donde el crecimiento ungueal se interrumpió por una enfermedad sistémica grave; conociendo la velocidad aproximada de crecimiento (≈0.1 mm/día) y la distancia desde la cutícula, se puede estimar cuándo ocurrió el evento.', dificultad: 'intermedio' },
  { q: '¿Qué distingue a las líneas de Muehrcke de la leuconiquia verdadera?', options: ['Muehrcke no se mueve con el crecimiento; la leuconiquia verdadera sí se mueve', 'No hay ninguna diferencia real entre ambos hallazgos', 'La leuconiquia verdadera nunca guarda relación con la hipoalbuminemia', 'Las líneas de Muehrcke solo llegan a aparecer en niños'], correct: 0, explanation: 'Solo las líneas de Muehrcke, al ser fijas y no desplazarse con el crecimiento de la placa, son un marcador confiable de hipoalbuminemia; la leuconiquia verdadera se mueve porque afecta la placa ungueal misma.', dificultad: 'dificil' },
  { q: '¿Qué sugieren las "uñas de Terry" (2/3 proximales blancos con banda distal rosada/marrón)?', options: ['Anemia ferropénica, de forma exclusiva y aislada', 'Cirrosis, insuficiencia cardiaca o renal (también en el envejecimiento normal)', 'Endocarditis infecciosa, de forma exclusiva y aislada', 'Psoriasis ungueal, sin ninguna relación sistémica asociada'], correct: 1, explanation: 'Las uñas de Terry se asocian a hepatopatía crónica, insuficiencia cardiaca e insuficiencia renal, aunque también pueden verse como parte del envejecimiento normal.', dificultad: 'intermedio' },
  { q: '¿Qué representan las hemorragias en astilla subungueales y qué causa clásica (aunque inespecífica) se debe considerar?', options: ['Depósitos de melanina, sin ningún significado patológico real', 'Un signo exclusivo y característico de la psoriasis', 'Pequeñas líneas hemorrágicas longitudinales; microembolismos sépticos en endocarditis (también trauma)', 'Un hallazgo completamente normal en todas las personas'], correct: 2, explanation: 'Aunque inespecíficas (el trauma local es una causa frecuente y benigna), las hemorragias en astilla son un hallazgo clásico —aunque no sensible ni específico por sí solo— de microembolismos sépticos en la endocarditis infecciosa.', dificultad: 'facil' },
  { q: '¿Cuál es la pregunta clínica más importante ante cualquier alopecia?', options: ['Si el paciente usa algún producto capilar específico', 'Si el cuero cabelludo conserva orificios foliculares visibles o no', 'La edad exacta y precisa del paciente, exclusivamente', 'El color original exacto del cabello perdido'], correct: 1, explanation: 'La presencia o ausencia de orificios foliculares determina si el proceso es potencialmente reversible o permanente, y por tanto la urgencia de biopsiar.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo en el borde activo es característico de la alopecia areata?', options: ['Pelos rotos a ras del cuero cabelludo, con descamación asociada', 'Pústulas foliculares, con inflamación evidente', 'Ausencia total de orificios foliculares visibles', 'Pelos "en signo de exclamación" (más delgados hacia la raíz que hacia la punta)'], correct: 3, explanation: 'Los pelos en signo de exclamación, en el borde de un parche de alopecia areata, reflejan el ataque autoinmune activo sobre el folículo en fase anágena.', dificultad: 'facil' },
  { q: '¿Por qué el efluvio telógeno se manifiesta típicamente 2-3 MESES después del evento estresante que lo desencadena?', options: ['Es una reacción alérgica de aparición completamente inmediata', 'No existe ninguna relación temporal real entre evento y caída', 'Porque el paso sincrónico de folículos de anágeno a telógeno tarda ese tiempo en volverse visible', 'Porque el pelo tarda 2-3 meses en volver a crecer desde cero'], correct: 2, explanation: 'El estrés fisiológico empuja folículos a la fase telógena de forma sincrónica; el pelo en telógeno tarda semanas a meses en desprenderse, explicando el retraso característico entre el evento y la caída visible.', dificultad: 'dificil' },
  { q: '¿Cómo se distingue la tricotilomanía de la alopecia areata?', options: ['Tricotilomanía: parches irregulares sin inflamación; areata: signo de exclamación', 'Son completamente indistinguibles desde el punto de vista clínico', 'La tricotilomanía siempre corresponde a una alopecia cicatricial', 'La alopecia areata siempre presenta pelos de longitud variable'], correct: 0, explanation: 'La tricotilomanía produce parches de forma irregular con pelos rotos de distinta longitud por arrancamiento compulsivo, sin inflamación del cuero cabelludo; la alopecia areata produce parches redondos y bien delimitados con el signo de exclamación característico en el borde activo.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente femenina de 45 años con erosiones dolorosas en la mucosa oral de 3 semanas de evolución, seguidas de la aparición de ampollas flácidas en el tronco que se rompen con facilidad.',
    steps: [
      { q: 'Al friccionar suavemente la piel perilesional de aspecto sano, se genera una ampolla nueva. ¿Cómo se llama este hallazgo?', options: ['Signo de Nikolsky positivo', 'Signo de Koebner', 'Signo de Schamroth', 'Signo del patito feo'], correct: 0 },
      { q: '¿En qué plano anatómico se forma la ampolla, dado que es flácida y el Nikolsky es positivo?', options: ['Subepidérmico, por autoanticuerpos contra hemidesmosomas', 'En la hipodermis, sin relación con la epidermis', 'Intraepidérmico, por acantólisis mediada por autoanticuerpos anti-desmogleína', 'No tiene relación con el plano anatómico'], correct: 2 },
      { q: '¿Qué diagnóstico es más probable, dado el compromiso mucoso temprano y las características de las ampollas?', options: ['Penfigoide ampolloso', 'Urticaria, de origen alérgico', 'Tiña corporal, de origen fúngico', 'Pénfigo vulgar'], correct: 3 }
    ],
    explanation: 'El compromiso mucoso temprano, las ampollas flácidas y frágiles, y el Nikolsky positivo son compatibles con pénfigo vulgar, una enfermedad ampollosa autoinmune con acantólisis intraepidérmica (pérdida de adhesión entre queratinocitos por autoanticuerpos anti-desmogleína) — a diferencia del penfigoide ampolloso, de plano subepidérmico, ampollas tensas y Nikolsky negativo, que rara vez compromete la mucosa oral de forma temprana.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente masculino de 60 años acude porque un lunar en la espalda "se ve distinto a los demás" desde hace 2 meses: ha crecido, cambió de color y ahora tiene un borde irregular.',
    steps: [
      { q: '¿Cómo se llama el hallazgo de que esta lesión "se vea distinta" a los demás nevos del paciente?', options: ['Signo de Nikolsky', 'Signo del patito feo (ugly duckling sign)', 'Fenómeno de Koebner', 'Signo de Schamroth'], correct: 1 },
      { q: 'De los criterios ABCDE, ¿cuál está más claramente presente en la descripción del paciente (cambio en 2 meses)?', options: ['Asimetría', 'Bordes', 'Color', 'Evolución'], correct: 3 },
      { q: '¿Cuál es la conducta más apropiada ante esta descripción?', options: ['Tranquilizar al paciente, es normal que los lunares cambien', 'Evaluación dermatológica dirigida con dermatoscopia y considerar biopsia', 'Indicar un corticoide tópico', 'Esperar 6 meses y reevaluar'], correct: 1 }
    ],
    explanation: 'Una lesión pigmentada que "se ve distinta" a los demás nevos del paciente (signo del patito feo) y que muestra evolución documentada (crecimiento, cambio de color, borde) —el criterio individual de mayor sensibilidad— amerita evaluación dermatológica dirigida con dermatoscopia y biopsia si persiste la sospecha, sin esperar a que se cumplan más criterios ABCDE.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente femenina de 35 años con dolor urente en el hemitórax derecho de 2 días, seguido de la aparición de un racimo de vesículas sobre base eritematosa, dispuestas en una banda que sigue el trayecto de un espacio intercostal, sin cruzar la línea media.',
    steps: [
      { q: '¿Cómo se llama este patrón de distribución en banda?', options: ['En dermatoma', 'Anular', 'En diana', 'Lineal por contacto'], correct: 0 },
      { q: '¿Qué mecanismo explica que las lesiones no crucen la línea media?', options: ['Es una coincidencia, sin ninguna explicación anatómica real', 'Se debe a una reacción alérgica de contacto localizada', 'La reactivación ocurre en un ganglio dorsal específico, cuyo nervio no cruza al lado contrario', 'El virus solo es capaz de infectar un lado del cuerpo'], correct: 2 },
      { q: '¿Cómo se describe la agrupación de las vesículas dentro de la banda?', options: ['Difusas y aisladas entre sí', 'Agrupadas/herpetiforme', 'En diana, con 3 zonas concéntricas', 'Anulares, con aclaramiento central'], correct: 1 }
    ],
    explanation: 'El dolor urente seguido de vesículas agrupadas ("herpetiforme") sobre base eritematosa, en una banda dermatomal que respeta la línea media, es el cuadro clásico de herpes zóster: la reactivación del virus varicela-zóster ocurre en un ganglio de la raíz dorsal específico y viaja por el nervio sensitivo correspondiente, que inerva un territorio cutáneo unilateral y bien delimitado.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente masculino de 68 años con fiebre de 10 días de evolución, soplo cardiaco de reciente aparición, y pequeñas líneas hemorrágicas longitudinales bajo varias uñas. Al juntar dorso con dorso los dedos índices, el rombo esperado entre las uñas está ausente.',
    steps: [
      { q: '¿Cómo se llama el hallazgo de las líneas hemorrágicas subungueales y qué sugiere en este contexto?', options: ['Líneas de Muehrcke; hipoalbuminemia', 'Línea de Beau; interrupción del crecimiento ungueal', 'Coiloniquia; anemia ferropénica', 'Hemorragias en astilla; microembolismos sépticos, compatibles con endocarditis'], correct: 3 },
      { q: '¿Cómo se llama el hallazgo de que el rombo entre las uñas haya desaparecido, y qué representa?', options: ['Signo de Nikolsky, que indica fragilidad epidérmica', 'Signo de Koebner, que indica psoriasis', 'Signo de Schamroth negativo, que indica acropaquia (dedos en palillo)', 'Un hallazgo normal, sin ningún significado patológico'], correct: 2 },
      { q: 'Dado el cuadro (fiebre prolongada, soplo nuevo, hemorragias en astilla, posible acropaquia de evolución subaguda), ¿qué diagnóstico es más probable?', options: ['Endocarditis infecciosa subaguda', 'Psoriasis ungueal', 'Alopecia areata', 'Tiña ungueal'], correct: 0 }
    ],
    explanation: 'La combinación de fiebre prolongada, un soplo cardiaco nuevo y hallazgos ungueales sugestivos de microembolismos (hemorragias en astilla) junto con posible acropaquia de curso subagudo es compatible con endocarditis infecciosa, donde émbolos sépticos repetidos y la respuesta inflamatoria crónica explican estos signos periféricos clásicos.'
  }
];

export const flashcards = [
  { front: 'Vitropresión (diascopia)', back: 'Blanquea → vascular (eritema). No blanquea → púrpura (sangre extravasada).' },
  { front: 'Mácula vs. mancha', back: 'Solo tamaño: mácula &lt;1 cm, mancha &gt;1 cm. Ambas planas, no palpables.' },
  { front: 'Pápula vs. nódulo', back: 'Pápula: superficial, &lt;1 cm. Nódulo: &gt;1 cm, dermis profunda/hipodermis — "se palpa más profundo de lo que se ve".' },
  { front: 'Roncha/habón: mecanismo y duración', back: 'Edema dérmico por histamina (mastocitos). Cada roncha dura &lt;24 h → si persiste más, sospechar vasculitis urticarial.' },
  { front: 'Vesícula vs. ampolla', back: 'Solo tamaño: vesícula &lt;1 cm, ampolla &gt;1 cm. Ambas con líquido claro.' },
  { front: 'Nikolsky positivo', back: 'Ampolla intraepidérmica (acantólisis) → flácida, frágil. Pénfigo, SJS/TEN, piel escaldada estafilocócica.' },
  { front: 'Nikolsky negativo', back: 'Ampolla subepidérmica (hemidesmosomas) → tensa, resistente. Penfigoide ampolloso.' },
  { front: 'Erosión vs. úlcera', back: 'Erosión: solo epidermis, cura sin cicatriz. Úlcera: alcanza la dermis, cura con cicatriz.' },
  { front: 'Patrón en dermatoma', back: 'Herpes zóster — reactivación del VZV en un ganglio de la raíz dorsal.' },
  { front: 'Patrón anular', back: 'Tiña (aclaramiento central), granuloma anular, eritema migrans (Lyme).' },
  { front: 'Fenómeno de Koebner', back: 'Lesiones nuevas en sitios de trauma previo → psoriasis, liquen plano, vitíligo.' },
  { front: 'ABCDE del melanoma', back: 'Asimetría, Bordes irregulares, Color heterogéneo, Diámetro &gt;6 mm, Evolución (el criterio más sensible individualmente).' },
  { front: 'Signo del patito feo', back: 'Lesión que se ve distinta a los demás nevos del paciente — sospechosa aunque cumpla pocos criterios ABCDE.' },
  { front: 'Carcinoma basocelular', back: 'Perla translúcida, telangiectasias, borde enrollado. Bajo potencial metastásico (daño local).' },
  { front: 'Carcinoma espinocelular', back: 'Placa/nódulo hiperqueratósico ulcerado, base indurada. Mayor riesgo en labio/oreja/inmunosuprimidos.' },
  { front: 'Melanoma nodular', back: 'El subtipo más agresivo — sin fase de crecimiento radial previa, invade en vertical desde el inicio.' },
  { front: 'Melanoma acral lentiginoso', back: 'Palmas/plantas/subungueal — más frecuente en piel oscura, con frecuencia diagnóstico tardío.' },
  { front: 'Signo de Schamroth', back: 'Ausencia del rombo entre uñas al juntarlas dorso con dorso → acropaquia.' },
  { front: 'Mecanismo de la acropaquia', back: 'Megacariocitos/plaquetas que escapan el filtro pulmonar se depositan en el lecho ungueal y liberan PDGF/VEGF.' },
  { front: 'Línea de Beau', back: 'Surco transversal por interrupción del crecimiento ungueal en enfermedad grave. Distancia desde la cutícula estima el momento (~0.1 mm/día).' },
  { front: 'Líneas de Muehrcke vs. leuconiquia verdadera', back: 'Muehrcke: fijas, no se mueven con el crecimiento (lecho vascular) → hipoalbuminemia. Leuconiquia verdadera: se mueve (placa ungueal).' },
  { front: 'Uñas de Terry', back: '2/3 proximales blancos, banda distal rosada/marrón → cirrosis, IC, IRC (o envejecimiento normal).' },
  { front: 'Hemorragias en astilla', back: 'Microembolismos sépticos (endocarditis) o trauma local — inespecíficas.' },
  { front: 'Alopecia cicatricial vs. no cicatricial', back: 'Pregunta clave: ¿hay orificios foliculares visibles? Sí = no cicatricial (reversible). No = cicatricial (permanente).' },
  { front: 'Alopecia areata: pelos en signo de exclamación', back: 'Más delgados hacia la raíz que hacia la punta, en el borde activo del parche — ataque autoinmune en fase anágena.' },
  { front: 'Efluvio telógeno: timing', back: 'Caída difusa 2-3 meses DESPUÉS de un estrés fisiológico (parto, cirugía, fiebre alta) — paso sincrónico anágeno→telógeno.' },
  { front: 'Tricotilomanía vs. alopecia areata', back: 'Tricotilomanía: parches irregulares, pelos de longitud variable (arrancados), sin inflamación. Areata: parches redondos, signo de exclamación.' }
];

export default { quiz, flashcards };
