// topics/exploracion-abdominal/study.js — Autoevaluación de Exploración Abdominal.
// Mismo patrón que historia-clinica/study.js y exploracion-cardiovascular/study.js: banco único,
// preguntas sueltas + preguntas en cascada sobre una viñeta (retroalimentación consolidada al
// final, sin revelar correcto/incorrecto paso a paso). Redacción de opciones sujeta a
// .claude/skills/reglas-preguntas/SKILL.md (misma categoría lógica, longitud/detalle comparables,
// sin pistas gramaticales/semánticas, posición de `correct` distribuida sin patrón a lo largo de
// todo el array).

export const quiz = [
  { q: '¿Cuál es el orden correcto de la exploración abdominal?', options: ['Palpación, percusión, auscultación, inspección, en ese orden', 'Auscultación, palpación, inspección, percusión, en ese orden', 'Inspección, palpación, percusión, auscultación (IPPA), igual que el tórax', 'Inspección, auscultación, percusión, palpación (IAPP)'], correct: 3, explanation: 'El abdomen invierte el orden clásico del tórax: Inspección, Auscultación, Percusión y Palpación (IAPP), porque percutir o palpar antes de auscultar puede alterar artificialmente los ruidos hidroaéreos.', dificultad: 'facil' },
  { q: '¿Por qué en el abdomen se ausculta ANTES de palpar o percutir, a diferencia del tórax?', options: ['Por comodidad y preferencia del examinador', 'La palpación altera los ruidos', 'Para que el estetoscopio se caliente antes', 'No hay razón fisiológica: es convención'], correct: 1, explanation: 'A diferencia del pulmón, el intestino responde mecánicamente al tacto: percutir o palpar antes de auscultar puede simular hiperperistaltismo donde no lo hay, o alterar el hallazgo real.', dificultad: 'intermedio' },
  { q: '¿Qué víscera se proyecta típicamente en el hipocondrio izquierdo?', options: ['Bazo', 'Hígado', 'Vejiga', 'Apéndice'], correct: 0, explanation: 'El hipocondrio izquierdo corresponde a la proyección anatómica del bazo, análogo especular del hipocondrio derecho (hígado y vesícula).', dificultad: 'facil' },
  { q: '¿Qué líneas delimitan las 9 regiones topográficas del abdomen?', options: ['Dos axilares y una umbilical transversal', 'Las líneas mamilares y la línea alba', 'Dos medioclaviculares y dos horizontales', 'Una sola línea media vertical, sin más'], correct: 2, explanation: 'Dos líneas verticales medioclaviculares y dos horizontales (subcostal arriba, transtubercular/bispinosa abajo) dividen el abdomen en 9 regiones estándar.', dificultad: 'intermedio' },
  { q: '¿Qué sugiere la "cabeza de medusa" (red venosa colateral centrífuga desde el ombligo)?', options: ['Deshidratación severa, con signos de hipoperfusión asociados', 'Obstrucción intestinal mecánica, con distensión generalizada', 'Insuficiencia renal aguda, de origen prerrenal', 'Hipertensión portal con recanalización de la vena umbilical'], correct: 3, explanation: 'La recanalización de la vena umbilical (obliterada normalmente tras el nacimiento) por hipertensión portal crea un flujo colateral que se irradia desde el ombligo hacia la periferia.', dificultad: 'facil' },
  { q: '¿Dónde aparecen respectivamente el signo de Cullen y el signo de Grey Turner?', options: ['Cullen: periumbilical; Turner: flancos', 'Los dos aparecen en el ombligo', 'Cullen: flancos; Turner: periumbilical', 'Los dos en la fosa iliaca derecha'], correct: 0, explanation: 'Cullen es la equimosis periumbilical y Grey Turner la de los flancos; ambas reflejan hemorragia retroperitoneal/intraperitoneal disecando el tejido subcutáneo, clásicamente en pancreatitis necrohemorrágica.', dificultad: 'intermedio' },
  { q: '¿Por qué la ausencia de los signos de Cullen y Grey Turner NO descarta una pancreatitis grave con hemorragia retroperitoneal?', options: ['No llegan a aparecer en la pancreatitis', 'Son tardíos y poco sensibles', 'Solo aparecen en el paciente obeso', 'Requieren una TC previa para confirmarse'], correct: 1, explanation: 'Ambos signos tardan 24-72 horas en aparecer desde el inicio del sangrado y tienen baja sensibilidad, por lo que su ausencia temprana no descarta la gravedad del cuadro.', dificultad: 'dificil' },
  { q: '¿Cuántos ruidos hidroaéreos por minuto se consideran normales?', options: ['De 0 a 4 por minuto', 'De 35 a 60 por minuto', 'De 5 a 34 por minuto', 'Más de 60 por minuto'], correct: 2, explanation: 'El rango normal de ruidos hidroaéreos es de 5 a 34 por minuto, con borborigmos ocasionales.', dificultad: 'facil' },
  { q: '¿Cuánto tiempo mínimo de auscultación continua se requiere antes de declarar "silencio abdominal"?', options: ['Hasta 2 minutos', 'Unos 5 segundos', 'Unos 30 segundos', 'Hasta 10 minutos'], correct: 0, explanation: 'Se necesitan hasta 2 minutos continuos de auscultación antes de confirmar la ausencia de ruidos; un tiempo insuficiente es la causa más frecuente de sobrediagnosticar íleo.', dificultad: 'intermedio' },
  { q: '¿Qué mecanismo explica los "ruidos de lucha" (aumentados, agudos, en ráfagas) en la obstrucción intestinal mecánica temprana?', options: ['El intestino distal se paraliza del todo', 'Los produce el gas atrapado en el estómago', 'Reflejan una perforación intestinal asociada', 'El proximal lucha contra la obstrucción'], correct: 3, explanation: 'En la obstrucción mecánica temprana, el segmento proximal a la obstrucción intenta vencer la resistencia con contracciones vigorosas y frecuentes, generando ruidos agudos en ráfagas coincidiendo con el cólico.', dificultad: 'dificil' },
  { q: 'Un soplo venoso continuo, "en zumbido", periumbilical, junto con red venosa colateral, corresponde a:', options: ['Estenosis de la arteria renal', 'Aneurisma de la aorta abdominal', 'Síndrome de Cruveilhier-Baumgarten', 'Fístula arteriovenosa hepática'], correct: 2, explanation: 'El soplo venoso continuo periumbilical, junto con la cabeza de medusa, forma parte del síndrome de Cruveilhier-Baumgarten por hipertensión portal.', dificultad: 'dificil' },
  { q: 'Un soplo abdominal sistodiastólico (no solo sistólico) en epigastrio o flancos sugiere:', options: ['Estenosis renal en su forma más leve', 'Estenosis renal más severa', 'Un hallazgo normal en personas delgadas', 'Un aneurisma de aorta ya roto'], correct: 1, explanation: 'El componente diastólico del soplo renal se asocia a mayor severidad de la estenosis, a diferencia de un soplo puramente sistólico.', dificultad: 'intermedio' },
  { q: '¿Cuál es el rango normal del área de matidez hepática en línea medioclavicular derecha?', options: ['De 1 a 3 cm', 'De 15 a 20 cm', 'De 20 a 25 cm', 'De 6 a 12 cm'], correct: 3, explanation: 'La distancia entre el borde superior (percutido de arriba abajo desde resonancia pulmonar) y el inferior (de abajo arriba desde timpanismo intestinal) es normal entre 6 y 12 cm.', dificultad: 'facil' },
  { q: '¿Qué es el signo de Jobert y qué indica?', options: ['Matidez hepática aumentada: hepatomegalia', 'Timpanismo hepático: neumoperitoneo', 'Matidez en el espacio de Traube: bazo', 'Matidez que cambia de posición: ascitis'], correct: 1, explanation: 'El signo de Jobert es la pérdida de la matidez hepática normal por la presencia de aire libre interpuesto entre el hígado y la pared (neumoperitoneo), típico de la perforación de una víscera hueca.', dificultad: 'dificil' },
  { q: '¿Por qué el signo de Castell (percusión dinámica del último espacio intercostal en la línea axilar anterior izquierda) es más útil que la matidez estática del espacio de Traube para detectar esplenomegalia?', options: ['Traube no es timpánico si todo es normal', 'Castell no exige que el paciente respire', 'Traube pierde especificidad por derrame', 'Traube solo se percute en decúbito lateral'], correct: 2, explanation: 'La matidez del espacio de Traube puede deberse a varias causas no esplénicas, mientras que el cambio dinámico de timpánico (espiración) a mate (inspiración profunda) en el signo de Castell es más específico de esplenomegalia.', dificultad: 'dificil' },
  { q: '¿Qué volumen aproximado de líquido libre se necesita para detectar matidez cambiante (shifting dullness)?', options: ['Cerca de 1500 mL', 'Cerca de 100 mL', 'Cerca de 10 litros', 'Cerca de 50 mL'], correct: 0, explanation: 'La matidez cambiante requiere un volumen relativamente moderado de líquido libre, aproximadamente 1500 mL, para ser detectable por percusión.', dificultad: 'intermedio' },
  { q: 'En la maniobra de la oleada ascítica (fluid wave), ¿para qué sirve que un asistente aplique el borde de su mano sobre la línea media del abdomen?', options: ['Para que el paciente permanezca inmóvil', 'Bloquea la onda por la grasa de la pared', 'Para medir a la vez la frecuencia cardiaca', 'No tiene función real, es una tradición'], correct: 1, explanation: 'Sin la mano bloqueadora, la onda puede transmitirse directamente por la grasa de la pared abdominal (sobre todo en obesidad), simulando una oleada ascítica positiva sin líquido libre real.', dificultad: 'intermedio' },
  { q: '¿Qué explica que el punto marcado como mate en decúbito supino se vuelva timpánico al girar al paciente hacia decúbito lateral?', options: ['El gas intestinal se destruye al moverse', 'La pared cambia de grosor con la postura', 'Es un artefacto, sin base fisiológica', 'El líquido migra y el gas flota'], correct: 3, explanation: 'El líquido libre se redistribuye por gravedad al girar al paciente; el gas intestinal, más ligero, flota hacia la parte más alta, dejando timpánico el punto que antes estaba cubierto por líquido.', dificultad: 'dificil' },
  { q: '¿Cómo se distingue la defensa muscular voluntaria de la involuntaria en la palpación abdominal?', options: ['La voluntaria cede con distracción', 'No hay forma clínica de distinguirlas', 'La involuntaria solo se da en pediatría', 'La voluntaria cursa con fiebre alta'], correct: 0, explanation: 'La defensa voluntaria es un acto consciente por ansiedad y cede al distraer al paciente; la involuntaria es un reflejo visceroparietal por irritación peritoneal real y persiste pese a cualquier intento de relajación.', dificultad: 'intermedio' },
  { q: 'Un borde hepático blando, liso y doloroso a la palpación es más típico de:', options: ['Cirrosis avanzada, con nódulos difusos', 'Carcinoma hepatocelular con invasión', 'Congestión pasiva o hepatitis aguda', 'Un hallazgo normal en la persona sana'], correct: 2, explanation: 'La congestión venosa aguda (insuficiencia cardiaca derecha) o la inflamación aguda (hepatitis) distienden la cápsula de Glisson de forma difusa, dando un borde blando, liso y doloroso.', dificultad: 'dificil' },
  { q: '¿Qué sugiere un hígado pulsátil, sincrónico con el pulso arterial (no con la respiración), en un paciente con ingurgitación yugular?', options: ['Hepatitis viral aguda con transaminasas', 'Cirrosis compensada, sin descompensar', 'Un hallazgo normal en jóvenes delgados', 'Insuficiencia tricuspídea severa'], correct: 3, explanation: 'En la insuficiencia tricuspídea severa, el flujo regurgitante sistólico se transmite hacia atrás por las venas suprahepáticas hasta el hígado, generando una pulsatilidad sincrónica con el pulso arterial.', dificultad: 'intermedio' },
  { q: '¿Cómo se distingue una hepatomegalia real de un simple desplazamiento del hígado hacia abajo por hiperinsuflación pulmonar (EPOC)?', options: ['No es posible distinguirlas clínicamente', 'El desplazamiento duele y la real no', 'En la real, la matidez también aumenta', 'El desplazamiento solo pasa en niños'], correct: 2, explanation: 'Medir el área de matidez (no solo la posición del borde palpable) permite distinguir un hígado realmente crecido de uno simplemente empujado hacia abajo por un diafragma aplanado.', dificultad: 'dificil' },
  { q: '¿Cuál es la posición correcta del paciente para la palpación esplénica (técnica de Middleton/Schuster)?', options: ['Decúbito lateral derecho', 'Decúbito supino extendido', 'Decúbito lateral izquierdo', 'Sedestación inclinado adelante'], correct: 0, explanation: 'En decúbito lateral derecho, con las rodillas flexionadas, la gravedad y la elevación de la parrilla costal izquierda por detrás facilitan que un bazo crecido descienda hacia el reborde costal palpable.', dificultad: 'facil' },
  { q: '¿Qué características distinguen a una masa esplénica palpable de un riñón izquierdo palpable?', options: ['Son idénticas e indistinguibles al tacto', 'El bazo tiene muesca y se mueve', 'El riñón izquierdo resulta más grande', 'El bazo no se desplaza al respirar'], correct: 1, explanation: 'La muesca esplénica y el movimiento respiratorio (por su relación con el diafragma) distinguen al bazo de una masa renal, que es lisa, sin muesca, y tiene el colon interpuesto por delante (timpanismo).', dificultad: 'intermedio' },
  { q: '¿Por qué el bazo normalmente NO es palpable, y qué grado de crecimiento se necesita para que se vuelva palpable?', options: ['Lo cubre la parrilla; debe doblar su tamaño', 'No llega a ser palpable aunque crezca', 'Se palpa en toda persona delgada', 'Basta un aumento del 10% de su tamaño'], correct: 0, explanation: 'La parrilla costal cubre al bazo normal; solo cuando su tamaño se aproximadamente duplica, desciende lo suficiente por debajo del reborde costal para ser palpable en inspiración profunda.', dificultad: 'dificil' },
  { q: '¿Cómo se define un signo de Murphy positivo?', options: ['Dolor difuso en todo el abdomen al palpar', 'Fiebre con dolor en hipocondrio derecho', 'Corte brusco de la inspiración al palpar', 'Ictericia con dolor abdominal generalizado'], correct: 2, explanation: 'El signo de Murphy positivo es la detención súbita de la inspiración por dolor cuando la vesícula inflamada, al descender con el diafragma, choca contra los dedos del examinador colocados en el punto cístico.', dificultad: 'facil' },
  { q: '¿Por qué el signo de Murphy puede ser falsamente negativo en obesidad severa o en el paciente anciano/diabético?', options: ['La vesícula no se inflama en estos casos', 'Estos pacientes no tienen vesícula funcional', 'El signo no es negativo si hay colecistitis', 'La vesícula no desciende; el dolor se atenúa'], correct: 3, explanation: 'La obesidad limita mecánicamente el descenso de la vesícula hasta los dedos del examinador, y la neuropatía o la respuesta atenuada del anciano/diabético reduce la percepción del dolor, generando falsos negativos.', dificultad: 'intermedio' },
  { q: 'Un "falso Murphy" (dolor al palpar el hipocondrio derecho sin verdadera interrupción inspiratoria) puede verse en:', options: ['Apendicitis retrocecal, con irritación del músculo psoas', 'Neumonía del lóbulo inferior derecho o pleuritis basal derecha', 'Estenosis mitral, con soplo diastólico retumbante asociado', 'Insuficiencia renal crónica, en fase terminal avanzada'], correct: 1, explanation: 'La irritación pleural basal derecha puede producir dolor referido al hipocondrio derecho con la palpación, simulando un Murphy positivo sin que exista patología vesicular.', dificultad: 'dificil' },
  { q: '¿Dónde se localiza el punto de McBurney?', options: ['A medio camino entre el ombligo y el pubis', 'Justo sobre la espina iliaca anterosuperior', 'Tercio externo entre espina iliaca y ombligo', 'En hipocondrio derecho, junto al reborde'], correct: 2, explanation: 'El punto de McBurney corresponde a la base fija del apéndice, ubicada en el tercio externo de la línea que une la espina iliaca anterosuperior derecha con el ombligo.', dificultad: 'facil' },
  { q: '¿Qué mecanismo explica el signo de Rovsing (dolor en fosa iliaca derecha al palpar la fosa iliaca izquierda)?', options: ['Es un reflejo neurológico cruzado, sin más', 'La palpación izquierda comprime el apéndice', 'Solo ocurre si ya hay perforación franca', 'El gas desplazado tracciona el peritoneo'], correct: 3, explanation: 'Al comprimir la fosa iliaca izquierda, el gas y el contenido intestinal se desplazan y traccionan indirectamente el peritoneo inflamado del lado derecho, generando dolor a distancia.', dificultad: 'intermedio' },
  { q: '¿Qué diferencia anatómica explica que el signo del psoas y el del obturador sean positivos en distintos casos de apendicitis?', options: ['Los dos dependen de la misma posición', 'Psoas: retrocecal; obturador: pélvico', 'El del obturador solo aplica en mujeres', 'El del psoas solo vale en pediatría'], correct: 1, explanation: 'La posición variable del apéndice determina qué estructura muscular vecina se irrita: un apéndice retrocecal irrita el psoas, uno pélvico irrita el obturador interno.', dificultad: 'dificil' },
  { q: '¿Qué mecanismo real genera el dolor del signo de Blumberg (rebote), más allá de la idea intuitiva de "estirar el peritoneo"?', options: ['La sacudida de la pared y las vísceras', 'El estiramiento pasivo al retirar la mano', 'Una isquemia transitoria de la pared', 'La liberación súbita de gas intestinal'], correct: 0, explanation: 'El dolor de rebote se debe al movimiento brusco que sacude el peritoneo inflamado al soltar la presión, no a un simple estiramiento pasivo — por eso maniobras que generan ese mismo movimiento sin tocar el punto doloroso (percusión suave, toser) reproducen el dolor.', dificultad: 'dificil' },
  { q: '¿Qué ventaja tiene el "signo de la tos" (dolor abdominal al toser) frente al signo de Blumberg clásico?', options: ['Duele más y por eso es más confiable', 'Solo sirve para descartar apendicitis', 'Requiere anestesia local previa al hacerlo', 'Rinde igual, con menos molestia'], correct: 3, explanation: 'El signo de la tos reproduce el mismo mecanismo de sacudida del peritoneo inflamado que el rebote clásico, con un rendimiento diagnóstico similar y menos dolor provocado.', dificultad: 'intermedio' },
  { q: 'Un "vientre en tabla" (defensa involuntaria generalizada) sugiere principalmente:', options: ['Ansiedad importante durante la exploración', 'Peritonitis difusa por perforación', 'Estreñimiento crónico, sin irritación peritoneal', 'Normal en quien tiene musculatura potente'], correct: 1, explanation: 'La contractura refleja y generalizada de toda la pared abdominal, que no cede con ninguna maniobra de relajación, es característica de peritonitis difusa y constituye una urgencia quirúrgica.', dificultad: 'facil' },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente femenina de 52 años, obesa, con dolor en hipocondrio derecho posprandial, fiebre y náusea. A la palpación del punto cístico, el dolor es difuso pero NO logra provocarse una interrupción clara de la inspiración.',
    steps: [
      { q: '¿Por qué el signo de Murphy clásico podría ser falsamente negativo en esta paciente?', options: ['La obesidad impide el contacto vesicular', 'La colecistitis no cursa con Murphy positivo', 'El signo de Murphy solo aplica en hombres', 'La fiebre asociada invalida la maniobra'], correct: 0 },
      { q: '¿Qué alternativa tiene mejor rendimiento en este escenario?', options: ['Repetir la palpación manual varias veces', 'Descartarla si el Murphy es negativo', 'El signo de Murphy ecográfico', 'Palpar el punto de McBurney en su lugar'], correct: 2 },
      { q: 'Si además se ausculta un abdomen con ruidos hidroaéreos normales y sin soplos, ¿qué sugiere esto sobre el diagnóstico?', options: ['Descarta por completo la colecistitis aguda', 'Confirma una obstrucción intestinal asociada', 'Indica un cuadro de origen puramente funcional', 'No la descarta: los ruidos no cambian'], correct: 3 }
    ],
    explanation: 'La obesidad limita el descenso mecánico de la vesícula hasta los dedos del examinador, generando falsos negativos del Murphy manual; el equivalente ecográfico, con compresión directa sobre la vesícula visualizada, es más sensible en ese escenario. La auscultación normal es un hallazgo esperado y no descarta colecistitis: solo se altera si hay una complicación asociada (íleo biliar, perforación con peritonitis).'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente masculino de 24 años con dolor periumbilical que migró en 12 horas a la fosa iliaca derecha, con febrícula y anorexia.',
    steps: [
      { q: '¿Qué punto de palpación es más específico para localizar el origen del dolor?', options: ['Punto epigástrico', 'Punto de McBurney', 'Punto cístico', 'Punto renoureteral'], correct: 1 },
      { q: 'Al palpar la fosa iliaca izquierda, el paciente refiere dolor en la fosa iliaca derecha. ¿Cómo se llama este signo y qué lo explica?', options: ['Signo de Murphy, por contacto vesicular directo con los dedos', 'Signo de Cullen, por hemorragia retroperitoneal disecando tejido', 'Signo de Kussmaul, por rigidez del pericardio inflamado', 'Signo de Rovsing, por desplazamiento de gas a distancia'], correct: 3 },
      { q: 'Si el dolor se reproduce al toser (signo de la tos) sin necesidad de palpar profundamente, ¿qué indica esto sobre el estado del peritoneo?', options: ['Hay irritación peritoneal, con menos dolor', 'El peritoneo está sano; el dolor es funcional', 'Aun así hay que repetir el Blumberg clásico', 'El diagnóstico más probable es pancreatitis'], correct: 0 }
    ],
    explanation: 'La secuencia de dolor periumbilical migrando a fosa iliaca derecha, junto con el punto de McBurney positivo, el signo de Rovsing (tracción peritoneal a distancia por desplazamiento de gas) y un signo de la tos positivo (irritación peritoneal, mecanismo equivalente al rebote pero menos doloroso), es el cuadro clásico de apendicitis aguda.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente femenina de 60 años con cirrosis conocida, presenta distensión abdominal progresiva. A la inspección se observa red venosa colateral centrífuga desde el ombligo.',
    steps: [
      { q: '¿Cómo se llama el hallazgo de la inspección y qué mecanismo lo explica?', options: ['Signo de Cullen, por hemorragia retroperitoneal disecante', 'Signo de Grey Turner, por pancreatitis necrohemorrágica grave', '"Cabeza de medusa", por hipertensión portal con recanalización venosa', 'Estrías cutáneas, por hipercortisolismo de larga evolución'], correct: 2 },
      { q: '¿Qué maniobra de percusión confirmaría la sospecha de líquido libre asociado?', options: ['El signo de Jobert', 'La matidez cambiante', 'El signo de Castell', 'La percusión cardiaca'], correct: 1 },
      { q: 'A la palpación hepática, el borde es firme, romo, nodular e indoloro. ¿Qué sugiere esta consistencia frente a un borde blando y doloroso?', options: ['Congestión aguda por insuficiencia derecha', 'Una hepatitis viral aguda de inicio reciente', 'Cirrosis o infiltración neoplásica', 'Es un hallazgo normal en cualquiera'], correct: 2 }
    ],
    explanation: 'El cuadro integra tres hallazgos concordantes con hepatopatía crónica avanzada e hipertensión portal: la cabeza de medusa (recanalización de la vena umbilical), la matidez cambiante (ascitis por hipertensión portal e hipoalbuminemia), y un borde hepático firme, nodular e indoloro (fibrosis/cirrosis, a diferencia del borde blando y doloroso de la congestión aguda).'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente masculino de 45 años con dolor abdominal tipo cólico, distensión y vómito. A la auscultación se escuchan ruidos aumentados, de tono agudo, en ráfagas coincidiendo con el dolor.',
    steps: [
      { q: '¿Cómo se llama este patrón de ruidos hidroaéreos y qué sugiere?', options: ['Silencio abdominal: íleo paralítico', 'Ruidos de lucha: obstrucción mecánica', 'Soplo venoso continuo: hipertensión portal', 'Roce peritoneal: una perihepatitis'], correct: 1 },
      { q: 'Si el cuadro progresa sin tratamiento durante varios días y los ruidos finalmente desaparecen, ¿qué fase representa esto?', options: ['Obstrucción tardía o complicación', 'Resolución espontánea de la obstrucción', 'Un hallazgo esperado en la evolución', 'Mejoría definitiva, sin más estudios'], correct: 0 },
      { q: '¿Qué hallazgo a la percusión sería esperado en este cuadro de obstrucción con distensión?', options: ['Matidez generalizada en todo el abdomen', 'Matidez cambiante, típica de la ascitis', 'Ausencia de matidez hepática (Jobert)', 'Timpanismo aumentado por el gas'], correct: 3 },
    ],
    explanation: 'La obstrucción intestinal mecánica temprana genera hiperperistaltismo con ruidos de lucha (agudos, en ráfagas, coincidiendo con el cólico) y timpanismo aumentado por acumulación de gas proximal; si progresa sin resolverse, el intestino se agota y los ruidos pueden desaparecer, marcando una fase tardía o una complicación (isquemia, perforación) que requiere reevaluación urgente.'
  }
];

export const flashcards = [
  { front: 'Orden de la exploración abdominal', back: 'IAPP: Inspección, Auscultación, Percusión, Palpación — se ausculta ANTES de tocar la pared (invierte el orden IPPA del tórax).' },
  { front: 'Por qué se ausculta antes de palpar en el abdomen', back: 'La percusión y la palpación estimulan mecánicamente el intestino y pueden alterar artificialmente los ruidos hidroaéreos.' },
  { front: 'Las 9 regiones abdominales', back: '2 líneas medioclaviculares verticales + línea subcostal y transtubercular horizontales → hipocondrios, epigastrio, flancos, región umbilical, fosas iliacas, hipogastrio.' },
  { front: '"Cabeza de medusa"', back: 'Red venosa colateral centrífuga desde el ombligo → hipertensión portal con recanalización de la vena umbilical.' },
  { front: 'Signo de Cullen vs. Grey Turner', back: 'Cullen: equimosis periumbilical. Grey Turner: equimosis en los flancos. Ambos por hemorragia retroperitoneal (pancreatitis necrohemorrágica); tardíos (24-72 h) y poco sensibles.' },
  { front: 'Ruidos hidroaéreos normales', back: '5-34/min. Se requieren hasta 2 minutos de auscultación antes de declarar silencio abdominal.' },
  { front: '"Ruidos de lucha"', back: 'Aumentados, agudos, en ráfagas con el cólico → obstrucción intestinal mecánica temprana (intestino proximal hiperperistaltando contra la resistencia).' },
  { front: 'Síndrome de Cruveilhier-Baumgarten', back: 'Soplo venoso continuo "en zumbido" periumbilical + cabeza de medusa → hipertensión portal con recanalización de la vena umbilical.' },
  { front: 'Soplo renal sistodiastólico', back: 'Estenosis de arteria renal más severa que si fuera solo sistólico.' },
  { front: 'Área de matidez hepática normal', back: '6-12 cm en línea medioclavicular derecha (borde superior por percusión descendente, inferior por percusión ascendente).' },
  { front: 'Signo de Jobert', back: 'Desaparición de la matidez hepática (timpanismo) → neumoperitoneo por víscera hueca perforada.' },
  { front: 'Espacio de Traube vs. signo de Castell', back: 'Traube (matidez estática): baja especificidad. Castell (matidez dinámica en inspiración, último EIC línea axilar anterior izq.): mejor rendimiento para esplenomegalia.' },
  { front: 'Matidez cambiante (shifting dullness)', back: 'Detecta ~1500 mL de líquido libre: el punto mate en supino se vuelve timpánico al girar al paciente (el líquido migra por gravedad).' },
  { front: 'Oleada ascítica: mano bloqueadora', back: 'Bloquea la transmisión de la onda por la grasa de la pared, evitando falsos positivos (sobre todo en obesidad).' },
  { front: 'Defensa voluntaria vs. involuntaria', back: 'Voluntaria: cede con distracción/relajación. Involuntaria ("vientre en tabla"): reflejo por irritación peritoneal real, no cede con nada.' },
  { front: 'Hepatomegalia: borde blando y doloroso vs. duro y nodular', back: 'Blando/doloroso: congestión aguda (IC derecha) o hepatitis. Duro/nodular/indoloro: cirrosis o infiltración neoplásica.' },
  { front: 'Hígado pulsátil sincrónico con el pulso', back: 'Insuficiencia tricuspídea severa — reflujo sistólico transmitido retrógrado por las venas suprahepáticas.' },
  { front: 'Hepatomegalia real vs. desplazamiento (EPOC)', back: 'Real: área de matidez percutida AUMENTADA. Desplazamiento: área normal, solo más baja.' },
  { front: 'Técnica de palpación esplénica (Middleton)', back: 'Decúbito lateral derecho, rodillas flexionadas; mano izquierda del examinador eleva la parrilla costal izquierda por detrás.' },
  { front: 'Bazo vs. riñón izquierdo palpable', back: 'Bazo: muesca medial, se mueve con la respiración. Riñón: liso, sin muesca, timpanismo de colon interpuesto por delante.' },
  { front: 'Signo de Murphy', back: 'Interrupción brusca de la inspiración por dolor al palpar el punto cístico (vesícula inflamada descendiendo). Falso negativo en obesidad/anciano-diabético.' },
  { front: 'Punto de McBurney', back: 'Tercio externo de la línea EIAS derecha-ombligo — coincide con la base fija del apéndice.' },
  { front: 'Signo de Rovsing', back: 'Dolor en fosa iliaca derecha al palpar la fosa iliaca izquierda — desplazamiento de gas y tracción peritoneal a distancia.' },
  { front: 'Signo del psoas vs. del obturador', back: 'Psoas: apéndice retrocecal. Obturador: apéndice pélvico. Cada uno irrita el músculo vecino correspondiente.' },
  { front: 'Mecanismo real del signo de Blumberg', back: 'No es "estiramiento" del peritoneo al soltar, sino el movimiento súbito que sacude el peritoneo parietal inflamado — por eso el signo de la tos reproduce el mismo dolor.' },
  { front: 'Vientre en tabla generalizado', back: 'Defensa involuntaria difusa → peritonitis generalizada, típicamente por perforación de víscera hueca. Urgencia quirúrgica.' }
];

export default { quiz, flashcards };
