// topics/exploracion-abdominal/study.js — Autoevaluación de Exploración Abdominal.
// Mismo patrón que historia-clinica/study.js y exploracion-cardiovascular/study.js: banco único,
// preguntas sueltas + preguntas en cascada sobre una viñeta (retroalimentación consolidada al
// final, sin revelar correcto/incorrecto paso a paso). Redacción de opciones sujeta a
// .claude/skills/reglas-preguntas/SKILL.md (misma categoría lógica, longitud/detalle comparables,
// sin pistas gramaticales/semánticas, posición de `correct` distribuida sin patrón a lo largo de
// todo el array).

export const quiz = [
  { q: '¿Cuál es el orden correcto de la exploración abdominal?', options: ['Palpación, percusión, auscultación, inspección, en ese orden', 'Auscultación, palpación, inspección, percusión, en ese orden', 'Inspección, palpación, percusión, auscultación (IPPA), igual que el tórax', 'Inspección, auscultación, percusión, palpación (IAPP)'], correct: 3, explanation: 'El abdomen invierte el orden clásico del tórax: Inspección, Auscultación, Percusión y Palpación (IAPP), porque percutir o palpar antes de auscultar puede alterar artificialmente los ruidos hidroaéreos.', dificultad: 'facil' },
  { q: '¿Por qué en el abdomen se ausculta ANTES de palpar o percutir, a diferencia del tórax?', options: ['Por comodidad y preferencia personal del examinador durante el examen', 'Porque la percusión y la palpación estimulan mecánicamente el intestino y alteran los ruidos', 'Porque el estetoscopio se calienta con el contacto prolongado con la piel', 'No hay ninguna razón fisiológica real, es solo una convención'], correct: 1, explanation: 'A diferencia del pulmón, el intestino responde mecánicamente al tacto: percutir o palpar antes de auscultar puede simular hiperperistaltismo donde no lo hay, o alterar el hallazgo real.', dificultad: 'intermedio' },
  { q: '¿Qué víscera se proyecta típicamente en el hipocondrio izquierdo?', options: ['Bazo', 'Hígado', 'Vejiga', 'Apéndice'], correct: 0, explanation: 'El hipocondrio izquierdo corresponde a la proyección anatómica del bazo, análogo especular del hipocondrio derecho (hígado y vesícula).', dificultad: 'facil' },
  { q: '¿Qué líneas delimitan las 9 regiones topográficas del abdomen?', options: ['Dos líneas axilares y una transversal umbilical', 'Las líneas mamilares y la línea alba únicamente', 'Dos líneas medioclaviculares verticales y dos horizontales (subcostal y transtubercular)', 'Una sola línea media vertical, sin ninguna otra línea'], correct: 2, explanation: 'Dos líneas verticales medioclaviculares y dos horizontales (subcostal arriba, transtubercular/bispinosa abajo) dividen el abdomen en 9 regiones estándar.', dificultad: 'intermedio' },
  { q: '¿Qué sugiere la "cabeza de medusa" (red venosa colateral centrífuga desde el ombligo)?', options: ['Deshidratación severa, con signos de hipoperfusión asociados', 'Obstrucción intestinal mecánica, con distensión generalizada', 'Insuficiencia renal aguda, de origen prerrenal', 'Hipertensión portal con recanalización de la vena umbilical'], correct: 3, explanation: 'La recanalización de la vena umbilical (obliterada normalmente tras el nacimiento) por hipertensión portal crea un flujo colateral que se irradia desde el ombligo hacia la periferia.', dificultad: 'facil' },
  { q: '¿Dónde aparecen respectivamente el signo de Cullen y el signo de Grey Turner?', options: ['Cullen: periumbilical. Grey Turner: en los flancos', 'Ambos en el ombligo', 'Cullen: en los flancos. Grey Turner: periumbilical', 'Ambos en la fosa iliaca derecha'], correct: 0, explanation: 'Cullen es la equimosis periumbilical y Grey Turner la de los flancos; ambas reflejan hemorragia retroperitoneal/intraperitoneal disecando el tejido subcutáneo, clásicamente en pancreatitis necrohemorrágica.', dificultad: 'intermedio' },
  { q: '¿Por qué la ausencia de los signos de Cullen y Grey Turner NO descarta una pancreatitis grave con hemorragia retroperitoneal?', options: ['Porque nunca aparecen en la pancreatitis', 'Porque son signos tardíos (24-72 h) y de baja sensibilidad', 'Porque solo aparecen en pacientes obesos', 'Porque requieren siempre una TC para confirmarse primero'], correct: 1, explanation: 'Ambos signos tardan 24-72 horas en aparecer desde el inicio del sangrado y tienen baja sensibilidad, por lo que su ausencia temprana no descarta la gravedad del cuadro.', dificultad: 'dificil' },
  { q: '¿Cuántos ruidos hidroaéreos por minuto se consideran normales?', options: ['0-4', '35-60', '5-34', 'Más de 60'], correct: 2, explanation: 'El rango normal de ruidos hidroaéreos es de 5 a 34 por minuto, con borborigmos ocasionales.', dificultad: 'facil' },
  { q: '¿Cuánto tiempo mínimo de auscultación continua se requiere antes de declarar "silencio abdominal"?', options: ['Hasta 2 minutos', '5 segundos', '30 segundos', '10 minutos'], correct: 0, explanation: 'Se necesitan hasta 2 minutos continuos de auscultación antes de confirmar la ausencia de ruidos; un tiempo insuficiente es la causa más frecuente de sobrediagnosticar íleo.', dificultad: 'intermedio' },
  { q: '¿Qué mecanismo explica los "ruidos de lucha" (aumentados, agudos, en ráfagas) en la obstrucción intestinal mecánica temprana?', options: ['El intestino distal a la obstrucción se paraliza por completo', 'Son producidos por gas atrapado en el estómago únicamente', 'Reflejan siempre una perforación intestinal asociada', 'El intestino proximal a la obstrucción hiperperistalta contra la resistencia'], correct: 3, explanation: 'En la obstrucción mecánica temprana, el segmento proximal a la obstrucción intenta vencer la resistencia con contracciones vigorosas y frecuentes, generando ruidos agudos en ráfagas coincidiendo con el cólico.', dificultad: 'dificil' },
  { q: 'Un soplo venoso continuo, "en zumbido", periumbilical, junto con red venosa colateral, corresponde a:', options: ['Estenosis de arteria renal, con soplo sistodiastólico asociado', 'Aneurisma de aorta abdominal, con soplo sistólico pulsátil', 'Síndrome de Cruveilhier-Baumgarten (hipertensión portal con recanalización umbilical)', 'Fístula arteriovenosa hepática de origen postraumático'], correct: 2, explanation: 'El soplo venoso continuo periumbilical, junto con la cabeza de medusa, forma parte del síndrome de Cruveilhier-Baumgarten por hipertensión portal.', dificultad: 'dificil' },
  { q: 'Un soplo abdominal sistodiastólico (no solo sistólico) en epigastrio o flancos sugiere:', options: ['Estenosis de arteria renal, en su forma más leve', 'Estenosis de arteria renal más severa que si fuera solo sistólico', 'Un hallazgo normal esperado en personas delgadas', 'Aneurisma de aorta abdominal, ya roto y complicado'], correct: 1, explanation: 'El componente diastólico del soplo renal se asocia a mayor severidad de la estenosis, a diferencia de un soplo puramente sistólico.', dificultad: 'intermedio' },
  { q: '¿Cuál es el rango normal del área de matidez hepática en línea medioclavicular derecha?', options: ['1-3 cm', '15-20 cm', 'No tiene un rango normal establecido', '6-12 cm'], correct: 3, explanation: 'La distancia entre el borde superior (percutido de arriba abajo desde resonancia pulmonar) y el inferior (de abajo arriba desde timpanismo intestinal) es normal entre 6 y 12 cm.', dificultad: 'facil' },
  { q: '¿Qué es el signo de Jobert y qué indica?', options: ['Matidez hepática notablemente aumentada; indica hepatomegalia franca', 'Desaparición de la matidez hepática (timpanismo); indica neumoperitoneo por perforación', 'Matidez presente en el espacio de Traube; indica esplenomegalia', 'Matidez que cambia con la posición del paciente; indica ascitis'], correct: 1, explanation: 'El signo de Jobert es la pérdida de la matidez hepática normal por la presencia de aire libre interpuesto entre el hígado y la pared (neumoperitoneo), típico de la perforación de una víscera hueca.', dificultad: 'dificil' },
  { q: '¿Por qué el signo de Castell (percusión dinámica del último espacio intercostal en la línea axilar anterior izquierda) es más útil que la matidez estática del espacio de Traube para detectar esplenomegalia?', options: ['Porque el espacio de Traube nunca es timpánico en condiciones normales', 'Porque Castell no requiere que el paciente respire durante la maniobra', 'Porque la matidez de Traube tiene baja especificidad, alterada también por derrame pleural o alimento', 'Porque Traube solo puede percutirse con el paciente en decúbito lateral'], correct: 2, explanation: 'La matidez del espacio de Traube puede deberse a varias causas no esplénicas, mientras que el cambio dinámico de timpánico (espiración) a mate (inspiración profunda) en el signo de Castell es más específico de esplenomegalia.', dificultad: 'dificil' },
  { q: '¿Qué volumen aproximado de líquido libre se necesita para detectar matidez cambiante (shifting dullness)?', options: ['~1500 mL', '~100 mL', '~10 L', 'No depende del volumen, solo de la técnica'], correct: 0, explanation: 'La matidez cambiante requiere un volumen relativamente moderado de líquido libre, aproximadamente 1500 mL, para ser detectable por percusión.', dificultad: 'intermedio' },
  { q: 'En la maniobra de la oleada ascítica (fluid wave), ¿para qué sirve que un asistente aplique el borde de su mano sobre la línea media del abdomen?', options: ['Para que el paciente permanezca inmóvil durante toda la maniobra', 'Para bloquear la transmisión de la onda por la grasa de la pared, evitando un falso positivo', 'Para medir la frecuencia cardiaca del paciente de forma simultánea', 'No tiene ninguna función real, es solo una tradición sin base'], correct: 1, explanation: 'Sin la mano bloqueadora, la onda puede transmitirse directamente por la grasa de la pared abdominal (sobre todo en obesidad), simulando una oleada ascítica positiva sin líquido libre real.', dificultad: 'intermedio' },
  { q: '¿Qué explica que el punto marcado como mate en decúbito supino se vuelva timpánico al girar al paciente hacia decúbito lateral?', options: ['El gas intestinal se destruye por completo con el movimiento del paciente', 'La pared abdominal cambia de grosor según la posición adoptada', 'Es un artefacto de la técnica, sin ninguna base fisiológica real', 'El líquido migra por gravedad al nuevo flanco declive, y el gas flota hacia la zona antes mate'], correct: 3, explanation: 'El líquido libre se redistribuye por gravedad al girar al paciente; el gas intestinal, más ligero, flota hacia la parte más alta, dejando timpánico el punto que antes estaba cubierto por líquido.', dificultad: 'dificil' },
  { q: '¿Cómo se distingue la defensa muscular voluntaria de la involuntaria en la palpación abdominal?', options: ['La voluntaria cede con distracción; la involuntaria no cede con nada', 'No hay ninguna forma clínica de distinguirlas entre sí', 'La involuntaria ocurre exclusivamente en la población pediátrica', 'La voluntaria siempre se acompaña de fiebre elevada asociada'], correct: 0, explanation: 'La defensa voluntaria es un acto consciente por ansiedad y cede al distraer al paciente; la involuntaria es un reflejo visceroparietal por irritación peritoneal real y persiste pese a cualquier intento de relajación.', dificultad: 'intermedio' },
  { q: 'Un borde hepático blando, liso y doloroso a la palpación es más típico de:', options: ['Cirrosis avanzada, con nódulos regenerativos difusos', 'Carcinoma hepatocelular, con invasión vascular asociada', 'Congestión pasiva por insuficiencia cardiaca derecha o hepatitis aguda', 'Un hallazgo normal en cualquier persona sana'], correct: 2, explanation: 'La congestión venosa aguda (insuficiencia cardiaca derecha) o la inflamación aguda (hepatitis) distienden la cápsula de Glisson de forma difusa, dando un borde blando, liso y doloroso.', dificultad: 'dificil' },
  { q: '¿Qué sugiere un hígado pulsátil, sincrónico con el pulso arterial (no con la respiración), en un paciente con ingurgitación yugular?', options: ['Hepatitis viral aguda, con elevación importante de transaminasas', 'Cirrosis compensada, sin datos de descompensación actual', 'Un hallazgo normal en personas delgadas y jóvenes', 'Insuficiencia tricuspídea severa, por reflujo sistólico transmitido por las venas suprahepáticas'], correct: 3, explanation: 'En la insuficiencia tricuspídea severa, el flujo regurgitante sistólico se transmite hacia atrás por las venas suprahepáticas hasta el hígado, generando una pulsatilidad sincrónica con el pulso arterial.', dificultad: 'intermedio' },
  { q: '¿Cómo se distingue una hepatomegalia real de un simple desplazamiento del hígado hacia abajo por hiperinsuflación pulmonar (EPOC)?', options: ['No es posible distinguirlas clínicamente bajo ninguna circunstancia', 'El desplazamiento siempre duele, y la hepatomegalia real nunca', 'En la hepatomegalia real, el área de matidez también aumenta', 'El desplazamiento del hígado solo ocurre en la población pediátrica'], correct: 2, explanation: 'Medir el área de matidez (no solo la posición del borde palpable) permite distinguir un hígado realmente crecido de uno simplemente empujado hacia abajo por un diafragma aplanado.', dificultad: 'dificil' },
  { q: '¿Cuál es la posición correcta del paciente para la palpación esplénica (técnica de Middleton/Schuster)?', options: ['Decúbito lateral derecho, rodillas flexionadas', 'Decúbito supino con piernas extendidas', 'Decúbito lateral izquierdo', 'Sedestación inclinado hacia adelante'], correct: 0, explanation: 'En decúbito lateral derecho, con las rodillas flexionadas, la gravedad y la elevación de la parrilla costal izquierda por detrás facilitan que un bazo crecido descienda hacia el reborde costal palpable.', dificultad: 'facil' },
  { q: '¿Qué características distinguen a una masa esplénica palpable de un riñón izquierdo palpable?', options: ['Ambas son completamente idénticas e indistinguibles a la palpación', 'El bazo tiene muesca medial y se mueve con la respiración; el riñón es liso, sin muesca', 'El riñón izquierdo siempre es de mayor tamaño que el bazo', 'El bazo nunca se mueve con los movimientos de la respiración'], correct: 1, explanation: 'La muesca esplénica y el movimiento respiratorio (por su relación con el diafragma) distinguen al bazo de una masa renal, que es lisa, sin muesca, y tiene el colon interpuesto por delante (timpanismo).', dificultad: 'intermedio' },
  { q: '¿Por qué el bazo normalmente NO es palpable, y qué grado de crecimiento se necesita para que se vuelva palpable?', options: ['Está protegido por la parrilla costal; debe crecer al doble de su tamaño normal', 'Nunca llega a ser palpable, ni siquiera si crece mucho', 'Es palpable siempre, incluso sin crecer, en personas delgadas', 'Basta un aumento leve, de apenas el 10% de su tamaño'], correct: 0, explanation: 'La parrilla costal cubre al bazo normal; solo cuando su tamaño se aproximadamente duplica, desciende lo suficiente por debajo del reborde costal para ser palpable en inspiración profunda.', dificultad: 'dificil' },
  { q: '¿Cómo se define un signo de Murphy positivo?', options: ['Dolor difuso en todo el abdomen al realizar la palpación', 'Fiebre asociada de forma constante a dolor en hipocondrio derecho', 'Interrupción brusca e involuntaria de la inspiración al palpar el punto cístico, por contacto vesicular', 'Ictericia acompañada de dolor abdominal generalizado'], correct: 2, explanation: 'El signo de Murphy positivo es la detención súbita de la inspiración por dolor cuando la vesícula inflamada, al descender con el diafragma, choca contra los dedos del examinador colocados en el punto cístico.', dificultad: 'facil' },
  { q: '¿Por qué el signo de Murphy puede ser falsamente negativo en obesidad severa o en el paciente anciano/diabético?', options: ['Porque la vesícula nunca llega a inflamarse en este tipo de pacientes', 'Porque estos pacientes carecen por completo de vesícula funcional', 'El signo de Murphy nunca es negativo si existe colecistitis real', 'Porque en la obesidad la vesícula no desciende lo suficiente, y en el anciano/diabético el dolor está atenuado'], correct: 3, explanation: 'La obesidad limita mecánicamente el descenso de la vesícula hasta los dedos del examinador, y la neuropatía o la respuesta atenuada del anciano/diabético reduce la percepción del dolor, generando falsos negativos.', dificultad: 'intermedio' },
  { q: 'Un "falso Murphy" (dolor al palpar el hipocondrio derecho sin verdadera interrupción inspiratoria) puede verse en:', options: ['Apendicitis retrocecal, con irritación del músculo psoas', 'Neumonía del lóbulo inferior derecho o pleuritis basal derecha', 'Estenosis mitral, con soplo diastólico retumbante asociado', 'Insuficiencia renal crónica, en fase terminal avanzada'], correct: 1, explanation: 'La irritación pleural basal derecha puede producir dolor referido al hipocondrio derecho con la palpación, simulando un Murphy positivo sin que exista patología vesicular.', dificultad: 'dificil' },
  { q: '¿Dónde se localiza el punto de McBurney?', options: ['En el punto medio exacto entre el ombligo y la sínfisis del pubis', 'Directamente sobre la espina iliaca anterosuperior derecha', 'En el tercio externo de la línea entre la espina iliaca anterosuperior derecha y el ombligo', 'En el hipocondrio derecho, cerca del reborde costal'], correct: 2, explanation: 'El punto de McBurney corresponde a la base fija del apéndice, ubicada en el tercio externo de la línea que une la espina iliaca anterosuperior derecha con el ombligo.', dificultad: 'facil' },
  { q: '¿Qué mecanismo explica el signo de Rovsing (dolor en fosa iliaca derecha al palpar la fosa iliaca izquierda)?', options: ['Es un reflejo neurológico cruzado, sin ninguna relación mecánica', 'La palpación izquierda comprime de forma directa el apéndice', 'Solo se produce si ya existe perforación apendicular franca', 'El desplazamiento de gas a distancia tracciona el peritoneo parietal inflamado del lado derecho'], correct: 3, explanation: 'Al comprimir la fosa iliaca izquierda, el gas y el contenido intestinal se desplazan y traccionan indirectamente el peritoneo inflamado del lado derecho, generando dolor a distancia.', dificultad: 'intermedio' },
  { q: '¿Qué diferencia anatómica explica que el signo del psoas y el del obturador sean positivos en distintos casos de apendicitis?', options: ['Ambos dependen exactamente de la misma posición anatómica del apéndice', 'El psoas se relaciona con un apéndice retrocecal; el obturador, con un apéndice pélvico', 'El signo del obturador solo es aplicable en pacientes mujeres', 'El signo del psoas solo tiene validez en pacientes pediátricos'], correct: 1, explanation: 'La posición variable del apéndice determina qué estructura muscular vecina se irrita: un apéndice retrocecal irrita el psoas, uno pélvico irrita el obturador interno.', dificultad: 'dificil' },
  { q: '¿Qué mecanismo real genera el dolor del signo de Blumberg (rebote), más allá de la idea intuitiva de "estirar el peritoneo"?', options: ['El movimiento súbito de la pared y las vísceras, que sacude el peritoneo inflamado', 'El estiramiento pasivo del peritoneo al retirar la mano, exclusivamente', 'La isquemia transitoria y breve de la pared abdominal', 'La liberación súbita de gas intestinal previamente comprimido'], correct: 0, explanation: 'El dolor de rebote se debe al movimiento brusco que sacude el peritoneo inflamado al soltar la presión, no a un simple estiramiento pasivo — por eso maniobras que generan ese mismo movimiento sin tocar el punto doloroso (percusión suave, toser) reproducen el dolor.', dificultad: 'dificil' },
  { q: '¿Qué ventaja tiene el "signo de la tos" (dolor abdominal al toser) frente al signo de Blumberg clásico?', options: ['Es más doloroso y, por eso mismo, más confiable', 'Solo sirve para descartar apendicitis, nunca para confirmarla', 'Requiere anestesia local previa a su realización', 'Tiene sensibilidad similar para irritación peritoneal, con menos molestia'], correct: 3, explanation: 'El signo de la tos reproduce el mismo mecanismo de sacudida del peritoneo inflamado que el rebote clásico, con un rendimiento diagnóstico similar y menos dolor provocado.', dificultad: 'intermedio' },
  { q: 'Un "vientre en tabla" (defensa involuntaria generalizada) sugiere principalmente:', options: ['Ansiedad importante del paciente durante la exploración física', 'Peritonitis difusa, típicamente por perforación de una víscera hueca', 'Estreñimiento crónico, sin ninguna relación con irritación peritoneal', 'Un hallazgo normal en pacientes con musculatura muy desarrollada'], correct: 1, explanation: 'La contractura refleja y generalizada de toda la pared abdominal, que no cede con ninguna maniobra de relajación, es característica de peritonitis difusa y constituye una urgencia quirúrgica.', dificultad: 'facil' },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente femenina de 52 años, obesa, con dolor en hipocondrio derecho posprandial, fiebre y náusea. A la palpación del punto cístico, el dolor es difuso pero NO logra provocarse una interrupción clara de la inspiración.',
    steps: [
      { q: '¿Por qué el signo de Murphy clásico podría ser falsamente negativo en esta paciente?', options: ['Porque la obesidad puede impedir que la vesícula descienda lo suficiente para el contacto', 'Porque la colecistitis nunca da Murphy positivo, bajo ninguna circunstancia', 'Porque el signo de Murphy solo es aplicable en hombres', 'Porque la fiebre asociada invalida por completo la maniobra'], correct: 0 },
      { q: '¿Qué alternativa tiene mejor rendimiento en este escenario?', options: ['Repetir la palpación manual varias veces seguidas', 'Descartar la colecistitis si el Murphy manual resulta negativo', 'El signo de Murphy ecográfico: dolor máximo al comprimir el transductor sobre la vesícula', 'Palpar el punto de McBurney en su lugar, en su reemplazo'], correct: 2 },
      { q: 'Si además se ausculta un abdomen con ruidos hidroaéreos normales y sin soplos, ¿qué sugiere esto sobre el diagnóstico?', options: ['Descarta por completo la posibilidad de colecistitis aguda', 'Confirma la presencia de una obstrucción intestinal concomitante', 'Indica que el cuadro es de origen puramente funcional', 'No descarta colecistitis: los ruidos intestinales no suelen alterarse salvo que haya complicación'], correct: 3 }
    ],
    explanation: 'La obesidad limita el descenso mecánico de la vesícula hasta los dedos del examinador, generando falsos negativos del Murphy manual; el equivalente ecográfico, con compresión directa sobre la vesícula visualizada, es más sensible en ese escenario. La auscultación normal es un hallazgo esperado y no descarta colecistitis: solo se altera si hay una complicación asociada (íleo biliar, perforación con peritonitis).'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente masculino de 24 años con dolor periumbilical que migró en 12 horas a la fosa iliaca derecha, con febrícula y anorexia.',
    steps: [
      { q: '¿Qué punto de palpación es más específico para localizar el origen del dolor?', options: ['Punto epigástrico', 'Punto de McBurney', 'Punto cístico', 'Punto renoureteral'], correct: 1 },
      { q: 'Al palpar la fosa iliaca izquierda, el paciente refiere dolor en la fosa iliaca derecha. ¿Cómo se llama este signo y qué lo explica?', options: ['Signo de Murphy, por contacto vesicular directo con los dedos', 'Signo de Cullen, por hemorragia retroperitoneal disecando tejido', 'Signo de Kussmaul, por rigidez del pericardio inflamado', 'Signo de Rovsing, por desplazamiento de gas a distancia'], correct: 3 },
      { q: 'Si el dolor se reproduce al toser (signo de la tos) sin necesidad de palpar profundamente, ¿qué indica esto sobre el estado del peritoneo?', options: ['Que hay irritación peritoneal, con rendimiento similar al rebote pero menos dolor', 'Que el peritoneo está completamente sano y el dolor es funcional', 'Que aun así se requiere repetir obligatoriamente el Blumberg clásico', 'Que el diagnóstico más probable en este caso es una pancreatitis'], correct: 0 }
    ],
    explanation: 'La secuencia de dolor periumbilical migrando a fosa iliaca derecha, junto con el punto de McBurney positivo, el signo de Rovsing (tracción peritoneal a distancia por desplazamiento de gas) y un signo de la tos positivo (irritación peritoneal, mecanismo equivalente al rebote pero menos doloroso), es el cuadro clásico de apendicitis aguda.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente femenina de 60 años con cirrosis conocida, presenta distensión abdominal progresiva. A la inspección se observa red venosa colateral centrífuga desde el ombligo.',
    steps: [
      { q: '¿Cómo se llama el hallazgo de la inspección y qué mecanismo lo explica?', options: ['Signo de Cullen, por hemorragia retroperitoneal disecante', 'Signo de Grey Turner, por pancreatitis necrohemorrágica grave', '"Cabeza de medusa", por hipertensión portal con recanalización venosa', 'Estrías cutáneas, por hipercortisolismo de larga evolución'], correct: 2 },
      { q: '¿Qué maniobra de percusión confirmaría la sospecha de líquido libre asociado?', options: ['Signo de Jobert', 'Matidez cambiante (shifting dullness)', 'Signo de Castell', 'Percusión del área cardiaca'], correct: 1 },
      { q: 'A la palpación hepática, el borde es firme, romo, nodular e indoloro. ¿Qué sugiere esta consistencia frente a un borde blando y doloroso?', options: ['Congestión aguda por insuficiencia cardiaca derecha', 'Hepatitis viral aguda, de inicio reciente', 'Cirrosis o infiltración neoplásica, en vez de congestión aguda o hepatitis', 'Es un hallazgo normal en cualquier paciente'], correct: 2 }
    ],
    explanation: 'El cuadro integra tres hallazgos concordantes con hepatopatía crónica avanzada e hipertensión portal: la cabeza de medusa (recanalización de la vena umbilical), la matidez cambiante (ascitis por hipertensión portal e hipoalbuminemia), y un borde hepático firme, nodular e indoloro (fibrosis/cirrosis, a diferencia del borde blando y doloroso de la congestión aguda).'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente masculino de 45 años con dolor abdominal tipo cólico, distensión y vómito. A la auscultación se escuchan ruidos aumentados, de tono agudo, en ráfagas coincidiendo con el dolor.',
    steps: [
      { q: '¿Cómo se llama este patrón de ruidos hidroaéreos y qué sugiere?', options: ['Silencio abdominal; íleo paralítico', '"Ruidos de lucha"; obstrucción intestinal mecánica temprana', 'Soplo venoso continuo; hipertensión portal', 'Roce peritoneal; perihepatitis'], correct: 1 },
      { q: 'Si el cuadro progresa sin tratamiento durante varios días y los ruidos finalmente desaparecen, ¿qué fase representa esto?', options: ['Obstrucción tardía, con el intestino agotado, o complicación peritoneal', 'Resolución espontánea y completa de la obstrucción intestinal', 'Un hallazgo normal y esperado en la evolución habitual', 'Mejoría clínica definitiva, sin necesidad de más estudios'], correct: 0 },
      { q: '¿Qué hallazgo a la percusión sería esperado en este cuadro de obstrucción con distensión?', options: ['Matidez generalizada en todo el abdomen', 'Matidez cambiante típica de un cuadro de ascitis', 'Ausencia de matidez hepática (signo de Jobert)', 'Timpanismo aumentado, por acumulación de gas proximal a la obstrucción'], correct: 3 },
    ],
    explanation: 'La obstrucción intestinal mecánica temprana genera hiperperistaltismo con ruidos de lucha (agudos, en ráfagas, coincidiendo con el cólico) y timpanismo aumentado por acumulación de gas proximal; si progresa sin resolverse, el intestino se agota y los ruidos pueden desaparecer, marcando una fase tardía o una complicación (isquemia, perforación) que requiere reevaluación urgente.'
  }
];

export const flashcards = [
  { front: 'Orden de la exploración abdominal', back: 'IAPP: Inspección, Auscultación, Percusión, Palpación — se ausculta ANTES de tocar la pared (invierte el orden IPPA del tórax).' },
  { front: 'Por qué se ausculta antes de palpar en el abdomen', back: 'La percusión y la palpación estimulan mecánicamente el intestino y pueden alterar artificialmente los ruidos hidroaéreos.' },
  { front: 'Las 9 regiones abdominales', back: '2 líneas medioclaviculares verticales + línea subcostal y transtubercular horizontales → hipocondrios, epigastrio, flancos, región umbilical, fosas iliacas, hipogastrio.' },
  { front: '"Cabeza de medusa"', back: 'Red venosa colateral centrífuga desde el ombligo → hipertensión portal con recanalización de la vena umbilical.' },
  { front: 'Signo de Cullen vs. Grey Turner', back: 'Cullen: equimosis periumbilical. Grey Turner: equimosis en los flancos. Ambos por hemorragia retroperitoneal (pancreatitis necrohemorrágica); tardíos (24-72 h) y poco sensibles.' },
  { front: 'Ruidos hidroaéreos normales', back: '5-34/min. Se requieren hasta 2 minutos de auscultación antes de declarar silencio abdominal.' },
  { front: '"Ruidos de lucha"', back: 'Aumentados, agudos, en ráfagas con el cólico → obstrucción intestinal mecánica temprana (intestino proximal hiperperistaltando contra la resistencia).' },
  { front: 'Síndrome de Cruveilhier-Baumgarten', back: 'Soplo venoso continuo "en zumbido" periumbilical + cabeza de medusa → hipertensión portal con recanalización de la vena umbilical.' },
  { front: 'Soplo renal sistodiastólico', back: 'Estenosis de arteria renal más severa que si fuera solo sistólico.' },
  { front: 'Área de matidez hepática normal', back: '6-12 cm en línea medioclavicular derecha (borde superior por percusión descendente, inferior por percusión ascendente).' },
  { front: 'Signo de Jobert', back: 'Desaparición de la matidez hepática (timpanismo) → neumoperitoneo por víscera hueca perforada.' },
  { front: 'Espacio de Traube vs. signo de Castell', back: 'Traube (matidez estática): baja especificidad. Castell (matidez dinámica en inspiración, último EIC línea axilar anterior izq.): mejor rendimiento para esplenomegalia.' },
  { front: 'Matidez cambiante (shifting dullness)', back: 'Detecta ~1500 mL de líquido libre: el punto mate en supino se vuelve timpánico al girar al paciente (el líquido migra por gravedad).' },
  { front: 'Oleada ascítica: mano bloqueadora', back: 'Bloquea la transmisión de la onda por la grasa de la pared, evitando falsos positivos (sobre todo en obesidad).' },
  { front: 'Defensa voluntaria vs. involuntaria', back: 'Voluntaria: cede con distracción/relajación. Involuntaria ("vientre en tabla"): reflejo por irritación peritoneal real, no cede con nada.' },
  { front: 'Hepatomegalia: borde blando y doloroso vs. duro y nodular', back: 'Blando/doloroso: congestión aguda (IC derecha) o hepatitis. Duro/nodular/indoloro: cirrosis o infiltración neoplásica.' },
  { front: 'Hígado pulsátil sincrónico con el pulso', back: 'Insuficiencia tricuspídea severa — reflujo sistólico transmitido retrógrado por las venas suprahepáticas.' },
  { front: 'Hepatomegalia real vs. desplazamiento (EPOC)', back: 'Real: área de matidez percutida AUMENTADA. Desplazamiento: área normal, solo más baja.' },
  { front: 'Técnica de palpación esplénica (Middleton)', back: 'Decúbito lateral derecho, rodillas flexionadas; mano izquierda del examinador eleva la parrilla costal izquierda por detrás.' },
  { front: 'Bazo vs. riñón izquierdo palpable', back: 'Bazo: muesca medial, se mueve con la respiración. Riñón: liso, sin muesca, timpanismo de colon interpuesto por delante.' },
  { front: 'Signo de Murphy', back: 'Interrupción brusca de la inspiración por dolor al palpar el punto cístico (vesícula inflamada descendiendo). Falso negativo en obesidad/anciano-diabético.' },
  { front: 'Punto de McBurney', back: 'Tercio externo de la línea EIAS derecha-ombligo — coincide con la base fija del apéndice.' },
  { front: 'Signo de Rovsing', back: 'Dolor en fosa iliaca derecha al palpar la fosa iliaca izquierda — desplazamiento de gas y tracción peritoneal a distancia.' },
  { front: 'Signo del psoas vs. del obturador', back: 'Psoas: apéndice retrocecal. Obturador: apéndice pélvico. Cada uno irrita el músculo vecino correspondiente.' },
  { front: 'Mecanismo real del signo de Blumberg', back: 'No es "estiramiento" del peritoneo al soltar, sino el movimiento súbito que sacude el peritoneo parietal inflamado — por eso el signo de la tos reproduce el mismo dolor.' },
  { front: 'Vientre en tabla generalizado', back: 'Defensa involuntaria difusa → peritonitis generalizada, típicamente por perforación de víscera hueca. Urgencia quirúrgica.' }
];

export default { quiz, flashcards };
