// topics/hipertension-pulmonar/study.js: Autoevaluacion de Hipertension Pulmonar.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// 48 subpreguntas (30 sueltas + 6 cascadas de 3 pasos) y 32 tarjetas.
// Sin em dash (ver [[feedback-no-em-dash]]). Texto sin acentos.

export const quiz = [
  { q: 'Que presion arterial pulmonar media define hoy la hipertension pulmonar?', options: ['25 mmHg o mas', 'Mayor de 30 mmHg', 'Mayor de 20 mmHg', '35 mmHg o mas'], correct: 2, explanation: 'La guia ESC/ERS de 2022 bajo el umbral desde los 25 mmHg clasicos. El motivo es que los pacientes que quedaban en esa franja intermedia ya tenian peor pronostico que los normales, y con la definicion antigua se les decia que estaban bien.', dificultad: 'facil' },
  { q: 'Que resistencia vascular pulmonar define hoy la forma precapilar?', options: ['Mayor de 2 unidades Wood', 'Mayor de 3 unidades Wood', 'Mayor de 5 unidades Wood', 'Mayor de 1 unidad Wood'], correct: 0, explanation: 'Tambien bajo en 2022, desde el umbral clasico de 3. Se calcula restando el enclavamiento a la presion media y dividiendo por el gasto cardiaco, y es la cifra que indica si hay enfermedad del propio vaso pulmonar.', dificultad: 'intermedio' },
  { q: 'Que define el perfil poscapilar de la hipertension pulmonar?', options: ['Una resistencia vascular mayor de 3 unidades Wood', 'Un gasto cardiaco por debajo de 2.5 L/min', 'Una saturacion venosa mixta menor del 60%', 'Una presion de enclavamiento mayor de 15 mmHg'], correct: 3, explanation: 'El enclavamiento refleja la presion de la auricula izquierda, de modo que si esta elevado el problema viene de aguas arriba: es el grupo 2, el mas frecuente de todos. La resistencia separa despues la forma aislada de la combinada.', dificultad: 'intermedio' },
  { q: 'Que aporta el ecocardiograma en el diagnostico de la hipertension pulmonar?', options: ['Mide la presion pulmonar con exactitud', 'Asigna una probabilidad diagnostica', 'Sustituye al cateterismo si es concluyente', 'Determina el grupo clinico al que pertenece'], correct: 1, explanation: 'Combina la velocidad de regurgitacion tricuspidea con otros signos para clasificar la probabilidad en baja, intermedia o alta. Con esa probabilidad se decide a quien se estudia mas y a quien se cateteriza, pero la presion la mide el cateterismo.', dificultad: 'facil' },
  { q: 'Que hay que descartar PRIMERO ante una probabilidad ecocardiografica intermedia o alta?', options: ['La hipertension pulmonar tromboembolica cronica', 'Las causas del grupo 5, de mecanismo multifactorial', 'La cardiopatia izquierda y la enfermedad pulmonar', 'La hipertension arterial pulmonar idiopatica'], correct: 2, explanation: 'Los grupos 2 y 3 explican la gran mayoria de los casos. Buscar una hipertension arterial pulmonar antes de haber descartado una insuficiencia cardiaca o una EPOC es invertir el algoritmo y lleva a tratamientos equivocados.', dificultad: 'intermedio' },
  { q: 'Que prueba es obligatoria en toda hipertension pulmonar sin causa clara?', options: ['La gammagrafia de ventilacion y perfusion', 'La resonancia cardiaca con realce tardio de gadolinio', 'La angiografia pulmonar convencional', 'La tomografia por emision de positrones'], correct: 0, explanation: 'Descarta el grupo 4, que es el unico potencialmente curable con cirugia. Omitirla condena al paciente a un tratamiento paliativo cuando podia haberse operado, y por eso no admite excepciones.', dificultad: 'facil' },
  { q: 'Que significa una angiotomografia pulmonar normal en el estudio de una hipertension pulmonar?', options: ['Que se puede iniciar tratamiento vasodilatador especifico', 'Que descarta el origen tromboembolico cronico', 'Que la causa es con seguridad del grupo 1', 'Que NO descarta la enfermedad tromboembolica cronica'], correct: 3, explanation: 'La gammagrafia de ventilacion y perfusion es mas sensible para la enfermedad tromboembolica cronica, cuyas lesiones son organizadas y adheridas a la pared y pueden pasar desapercibidas en la angiotomografia. Un estudio de perfusion normal si la descarta.', dificultad: 'dificil' },
  { q: 'Cual es el unico grupo con tratamiento vasodilatador especifico establecido?', options: ['El grupo 2, por cardiopatia izquierda', 'El grupo 1, arterial pulmonar', 'El grupo 3, por enfermedad pulmonar', 'El grupo 5, multifactorial'], correct: 1, explanation: 'En el grupo 2 el vasodilatador produce edema pulmonar y en el grupo 3 empeora el intercambio gaseoso. En el grupo 4 el tratamiento es la cirugia, con riociguat solo si es inoperable o si persiste tras ella.', dificultad: 'facil' },
  { q: 'Por que es perjudicial el vasodilatador pulmonar en la hipertension del grupo 2?', options: ['Aumenta el flujo hacia un ventriculo izquierdo sobrecargado', 'Produce vasoconstriccion refleja de la circulacion bronquial', 'Reduce de forma directa la contractilidad del ventriculo derecho', 'Interfiere con la absorcion de los diureticos de asa'], correct: 0, explanation: 'El resultado es edema pulmonar. Los ensayos que han probado estos farmacos en la hipertension pulmonar por cardiopatia izquierda han sido negativos o han mostrado da&#241;o, y por eso la conducta es tratar la cardiopatia.', dificultad: 'intermedio' },
  { q: 'Cual es la unica excepcion reconocida al uso de vasodilatadores en el grupo 3?', options: ['El sildenafilo oral en la EPOC grave', 'El bosentan en el sindrome de fibrosis y enfisema', 'El treprostinil inhalado en la EPID', 'El riociguat en la hipoventilacion por obesidad'], correct: 2, explanation: 'Mejoro la capacidad de ejercicio en un ensayo controlado en pacientes con hipertension pulmonar asociada a enfermedad intersticial. El resto de los vasodilatadores empeoran el intercambio al dilatar zonas mal ventiladas y agravan la hipoxemia.', dificultad: 'dificil' },
  { q: 'Que caracteriza al grupo 4 frente a los demas?', options: ['Que responde bien al antagonista del calcio', 'Que no requiere anticoagulacion de mantenimiento', 'Que se diagnostica sin cateterismo derecho', 'Que es potencialmente curable con cirugia'], correct: 3, explanation: 'La endarterectomia pulmonar puede normalizar la hemodinamica y devolver al paciente a una vida normal. Ese potencial curativo es lo que justifica que la gammagrafia sea obligatoria en toda hipertension pulmonar sin explicar.', dificultad: 'facil' },
  { q: 'Cual es el tratamiento de eleccion de la hipertension pulmonar tromboembolica cronica operable?', options: ['El riociguat a dosis maxima tolerada', 'La endarterectomia pulmonar', 'La angioplastia pulmonar con balon', 'El trasplante pulmonar bilateral'], correct: 1, explanation: 'La angioplastia con balon se reserva a la enfermedad distal no accesible a la cirugia o a la hipertension residual, y el riociguat a los casos inoperables o persistentes. Ninguno de los dos debe retrasar la valoracion quirurgica en un centro experto.', dificultad: 'intermedio' },
  { q: 'Que anticoagulacion corresponde en la hipertension pulmonar tromboembolica cronica?', options: ['Solo durante los 6 meses posteriores a la cirugia', 'Ninguna si la endarterectomia normaliza la presion', 'Indefinida en todos los pacientes', 'Solo si se demuestra una trombofilia asociada'], correct: 2, explanation: 'Se mantiene de por vida, incluso tras una endarterectomia con buen resultado. En el sindrome antifosfolipido debe hacerse obligatoriamente con antagonista de la vitamina K y no con anticoagulantes de accion directa.', dificultad: 'intermedio' },
  { q: 'Que tres variables se usan para estratificar el riesgo en la hipertension arterial pulmonar?', options: ['Clase funcional, marcha de 6 minutos y peptido natriuretico', 'Presion media, resistencia vascular pulmonar y gasto cardiaco', 'Edad, sexo y presion arterial pulmonar sistolica', 'Saturacion, DLCO y distancia recorrida en la marcha'], correct: 0, explanation: 'Son las tres que se repiten en cada revision. En el diagnostico se a&#241;aden datos de imagen y de hemodinamica, y en el seguimiento el estrato intermedio se divide en dos porque el pronostico dentro de esa franja es muy distinto.', dificultad: 'intermedio' },
  { q: 'Cual es el objetivo terapeutico en la hipertension arterial pulmonar?', options: ['Normalizar la presion arterial pulmonar media', 'Mantener la resistencia por debajo de 3 unidades Wood', 'Conseguir una marcha superior a 500 metros', 'Alcanzar y mantener el riesgo bajo'], correct: 3, explanation: 'No se persigue una cifra de presion sino un estado de riesgo, valorado con la clase funcional, la marcha y el peptido natriuretico. Si a los 3 a 6 meses el paciente no esta en riesgo bajo, se escala el tratamiento en lugar de esperar.', dificultad: 'intermedio' },
  { q: 'Cual es el tratamiento inicial de un paciente del grupo 1 con riesgo bajo o intermedio?', options: ['Monoterapia con inhibidor de fosfodiesterasa 5', 'Doble terapia oral de inicio', 'Triple terapia con prostaciclina parenteral', 'Antagonista del calcio a dosis altas'], correct: 1, explanation: 'Antagonista del receptor de la endotelina mas inhibidor de la fosfodiesterasa 5 desde el principio. La monoterapia ha quedado reservada a casos muy concretos, como el paciente mayor con comorbilidad cardiopulmonar o el vasorreactivo demostrado.', dificultad: 'intermedio' },
  { q: 'Que corresponde a un paciente del grupo 1 con riesgo ALTO al diagnostico?', options: ['Triple terapia con prostaciclina parenteral', 'Doble terapia oral y revision a los 6 meses', 'Monoterapia y escalada segun la respuesta', 'Antagonista del calcio y control ambulatorio'], correct: 0, explanation: 'Y remision inmediata a trasplante pulmonar. La mortalidad al a&#241;o en este estrato supera el 20%, de modo que escalar poco a poco pierde un tiempo que no se recupera.', dificultad: 'intermedio' },
  { q: 'En que pacientes se realiza la prueba de vasorreactividad aguda?', options: ['En toda hipertension pulmonar de perfil precapilar', 'En la asociada a esclerosis sistemica', 'En la idiopatica, hereditaria o por farmacos', 'En la tromboembolica cronica inoperable'], correct: 2, explanation: 'En las formas asociadas y en los demas grupos no se hace, porque un resultado aparentemente positivo no predice la respuesta a los antagonistas del calcio y puede llevar a un tratamiento peligroso.', dificultad: 'intermedio' },
  { q: 'Que define una prueba de vasorreactividad positiva?', options: ['Un descenso de la resistencia mayor del 20%', 'Una caida de la presion sistolica pulmonar de 15 mmHg', 'Un aumento del gasto cardiaco superior al 30%', 'Un descenso de 10 mmHg o mas hasta 40 mmHg o menos'], correct: 3, explanation: 'Los tres elementos son necesarios: la magnitud del descenso, el valor absoluto alcanzado y que el gasto cardiaco no caiga. Solo alrededor del 10% de las formas idiopaticas cumplen los criterios, y de ellos la mitad deja de responder al a&#241;o.', dificultad: 'dificil' },
  { q: 'Que riesgo tiene dar antagonistas del calcio sin prueba de vasorreactividad?', options: ['Producir taquicardia refleja mantenida', 'Provocar hipotension y colapso hemodinamico', 'Inducir tolerancia farmacologica precoz', 'Enmascarar la progresion natural de la enfermedad'], correct: 1, explanation: 'En el paciente no vasorreactivo, que es la gran mayoria, el efecto inotropo negativo y la vasodilatacion sistemica sobre un ventriculo derecho al limite pueden precipitar un fallo agudo. Por eso nunca se prueban de forma empirica.', dificultad: 'intermedio' },
  { q: 'Que sintoma indica que el gasto cardiaco no puede aumentar con el ejercicio?', options: ['La tos seca de esfuerzo', 'La ortopnea de aparicion reciente y progresiva', 'El sincope o presincope de esfuerzo', 'La disnea paroxistica nocturna'], correct: 2, explanation: 'Es un marcador de riesgo alto y motivo de remision urgente a un centro experto. Se confunde con facilidad con un sincope vasovagal, y esa confusion retrasa el diagnostico de una enfermedad que ya esta avanzada.', dificultad: 'intermedio' },
  { q: 'Cual es la causa de muerte mas frecuente en la hipertension arterial pulmonar?', options: ['El fallo agudo del ventriculo derecho', 'La hemoptisis masiva por circulacion bronquial', 'La muerte subita por arritmia ventricular', 'La embolia pulmonar sobrea&#241;adida'], correct: 0, explanation: 'La enfermedad no mata por la presion sino por el fallo del ventriculo que tiene que vencerla. Por eso el pronostico depende de la funcion del ventriculo derecho mucho mas que de la cifra de presion pulmonar.', dificultad: 'intermedio' },
  { q: 'Cual es el vasopresor de eleccion en el fallo agudo del ventriculo derecho?', options: ['La dopamina en dosis intermedia', 'La adrenalina en perfusion continua', 'La fenilefrina en bolos repetidos', 'La noradrenalina'], correct: 3, explanation: 'Mantiene la presion aortica y con ella la perfusion coronaria del ventriculo derecho, que es la clave para romper la espiral de isquemia y disfuncion. La hipotension en este contexto no se trata con volumen sino sosteniendo la presion.', dificultad: 'dificil' },
  { q: 'Por que es peligrosa la ventilacion mecanica en el fallo derecho por hipertension pulmonar?', options: ['Porque impide medir la presion de enclavamiento', 'Porque reduce la precarga y aumenta la poscarga pulmonar', 'Porque obliga a suspender el tratamiento especifico', 'Porque produce hipercapnia con vasodilatacion sistemica'], correct: 1, explanation: 'La presion positiva disminuye el retorno venoso a un ventriculo que ya no eyecta bien y aumenta la resistencia pulmonar. La induccion anestesica puede precipitar una parada, de modo que la decision de intubar la toma alguien con experiencia.', dificultad: 'dificil' },
  { q: 'Que enfermedad autoinmunitaria obliga a cribado anual de hipertension pulmonar?', options: ['La esclerosis sistemica', 'La artritis reumatoide seropositiva', 'El sindrome de Sjogren primario', 'La polimialgia reumatica'], correct: 0, explanation: 'Es la conectivopatia que mas se asocia a hipertension arterial pulmonar, y el diagnostico precoz mejora el pronostico. El cribado combina ecocardiograma, DLCO y peptido natriuretico aunque el paciente este asintomatico.', dificultad: 'intermedio' },
  { q: 'Que conducta corresponde ante una mujer en edad fertil con hipertension arterial pulmonar?', options: ['Permitir el embarazo con seguimiento estrecho', 'Recomendar el embarazo antes de los 30 a&#241;os', 'Asegurar una anticoncepcion eficaz', 'Suspender el tratamiento si desea gestar'], correct: 2, explanation: 'La mortalidad materna sigue siendo muy alta pese a la mejora en centros expertos, porque el embarazo aumenta el gasto cardiaco en torno al 50% sobre un ventriculo derecho sin reserva. Es parte del tratamiento y se revisa en cada consulta.', dificultad: 'intermedio' },
  { q: 'Que farmacos estan contraindicados si una paciente con hipertension arterial pulmonar queda embarazada?', options: ['Los inhibidores de la fosfodiesterasa 5 por via oral', 'Los analogos de la prostaciclina', 'Los diureticos de asa a dosis bajas', 'Los antagonistas del receptor de la endotelina'], correct: 3, explanation: 'Son teratogenos, igual que el riociguat, y deben retirarse. El tratamiento se reorganiza con inhibidores de la fosfodiesterasa 5 y prostaciclinas, en un centro experto y con un equipo multidisciplinar.', dificultad: 'dificil' },
  { q: 'Que hallazgo ecocardiografico se asocia de forma consistente a peor pronostico?', options: ['La insuficiencia tricuspidea moderada', 'El derrame pericardico', 'La dilatacion de la arteria pulmonar', 'El aplanamiento del tabique en sistole'], correct: 1, explanation: 'Traduce una presion auricular derecha elevada y aparece en la enfermedad avanzada. Rara vez produce taponamiento, y drenarlo no mejora nada y puede desestabilizar al paciente, de modo que su valor es pronostico y no terapeutico.', dificultad: 'intermedio' },
  { q: 'Que procedimiento esta contraindicado en la hipertension portopulmonar moderada o grave?', options: ['La ligadura endoscopica de varices', 'La paracentesis evacuadora de gran volumen', 'La derivacion portosistemica intrahepatica transyugular', 'La profilaxis con betabloqueante no cardioselectivo'], correct: 2, explanation: 'Aumenta el flujo pulmonar sobre un lecho vascular ya enfermo y puede precipitar un fallo del ventriculo derecho. Es una de las pocas contraindicaciones absolutas del procedimiento y hay que buscarla antes de indicarlo.', dificultad: 'dificil' },
  { q: 'Que efecto tiene la interrupcion brusca del tratamiento especifico en la hipertension arterial pulmonar?', options: ['Puede producir un deterioro grave e incluso mortal', 'Se tolera bien si se reintroduce en una semana', 'Solo afecta a los pacientes en clase funcional IV', 'Produce un efecto rebote limitado a la tos'], correct: 0, explanation: 'La retirada brusca, sobre todo de las prostaciclinas parenterales, puede desencadenar un fallo derecho agudo. Por eso durante un ingreso por cualquier motivo hay que asegurar la continuidad del tratamiento y proteger el acceso venoso.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Mujer de 46 a&#241;os con disnea de esfuerzo progresiva de 18 meses y dos episodios de mareo intenso al subir escaleras. Auscultacion con segundo tono pulmonar reforzado. Radiografia de torax y espirometria normales. El ecocardiograma muestra velocidad de regurgitacion tricuspidea de 3.8 m/s, ventriculo derecho dilatado y vena cava inferior de 24 mm sin colapso.', steps: [
    { q: 'Que probabilidad ecocardiografica tiene?', options: ['Probabilidad baja', 'Probabilidad alta', 'Probabilidad intermedia', 'Probabilidad no valorable'], correct: 1 },
    { q: 'Que prueba no puede faltar en el estudio?', options: ['La resonancia cardiaca con realce tardio', 'La prueba de esfuerzo cardiopulmonar', 'La tomografia por emision de positrones', 'La gammagrafia de ventilacion y perfusion'], correct: 3 },
    { q: 'Que dato de su historia es un marcador de riesgo alto?', options: ['El presincope de esfuerzo', 'La duracion de 18 meses de los sintomas', 'La espirometria normal', 'El sexo y la edad de la paciente'], correct: 0 }
  ], explanation: 'Una velocidad de regurgitacion tricuspidea mayor de 3.4 m/s asigna probabilidad alta por si sola, sin necesidad de otros signos. La gammagrafia es obligatoria en toda hipertension pulmonar sin explicar porque descarta el grupo 4, el unico potencialmente curable con cirugia, y es mas sensible que la angiotomografia. El presincope de esfuerzo significa que el gasto cardiaco no puede aumentar y define por si solo un riesgo alto.', dificultad: 'facil' },

  { type: 'cascade', vignette: 'Varon de 74 a&#241;os con obesidad, hipertension arterial, diabetes y fibrilacion auricular permanente. Disnea de esfuerzo y edemas. El ecocardiograma muestra fraccion de eyeccion del 58%, auricula izquierda muy dilatada y velocidad de regurgitacion tricuspidea de 3.2 m/s. El cateterismo derecho da presion media de 34 mmHg, enclavamiento de 22 mmHg y gasto cardiaco de 4.5 L/min.', steps: [
    { q: 'Cual es su resistencia vascular pulmonar aproximada?', options: ['Alrededor de 7.5 unidades Wood', 'Alrededor de 1.3 unidades Wood', 'Alrededor de 2.7 unidades Wood', 'Alrededor de 4.9 unidades Wood'], correct: 2 },
    { q: 'Como se clasifica el perfil hemodinamico?', options: ['Combinada pre y poscapilar', 'Precapilar pura', 'Poscapilar aislada', 'Sin hipertension pulmonar'], correct: 0 },
    { q: 'Que tratamiento NO corresponde en este paciente?', options: ['El control de la volemia con diureticos', 'El tratamiento de la fibrilacion auricular', 'La perdida de peso y el ejercicio', 'El sildenafilo por la hipertension pulmonar'], correct: 3 }
  ], explanation: 'La resistencia es la presion media menos el enclavamiento dividido por el gasto: 34 menos 22, entre 4.5, es decir unas 2.7 unidades Wood. Con enclavamiento mayor de 15 y resistencia mayor de 2 se trata de una forma combinada, que es el grupo 2 con componente vascular a&#241;adido y peor pronostico que la aislada. El fenotipo cardiometabolico con auricula izquierda dilatada lo confirma. Los vasodilatadores pulmonares no estan indicados y pueden producir edema pulmonar.', dificultad: 'dificil' },

  { type: 'cascade', vignette: 'Varon de 52 a&#241;os que tuvo una embolia pulmonar bilateral hace 3 a&#241;os, anticoagulado 6 meses y despues suspendido. Consulta por disnea de esfuerzo de un a&#241;o. Ecocardiograma con probabilidad alta. La angiotomografia pulmonar se informa como sin defectos de repleccion agudos. La gammagrafia muestra multiples defectos de perfusion segmentarios en cu&#241;a con ventilacion conservada.', steps: [
    { q: 'Como se interpreta la angiotomografia informada como normal?', options: ['Descarta el origen tromboembolico cronico', 'Obliga a repetirla con mejor tecnica', 'Indica que la causa es del grupo 1', 'No descarta la enfermedad tromboembolica cronica'], correct: 3 },
    { q: 'Que hay que hacer antes de confirmar el diagnostico?', options: ['Iniciar riociguat y reevaluar en 3 meses', 'Anticoagular de forma eficaz al menos 3 meses', 'Realizar una prueba de vasorreactividad', 'Completar un estudio de sue&#241;o'], correct: 1 },
    { q: 'Cual es el tratamiento de eleccion si la enfermedad es proximal y operable?', options: ['El trasplante pulmonar bilateral', 'La angioplastia pulmonar con balon', 'La endarterectomia pulmonar', 'El treprostinil subcutaneo'], correct: 2 }
  ], explanation: 'Las lesiones cronicas estan organizadas y adheridas a la pared, y la angiotomografia puede informarse como normal si no se buscan de forma especifica; la gammagrafia es mas sensible y aqui es diagnostica. La definicion exige al menos 3 meses de anticoagulacion eficaz antes de confirmar el diagnostico, algo que este paciente no cumplia porque se le suspendio a los 6 meses. La endarterectomia es el tratamiento de eleccion y puede ser curativa.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Mujer de 38 a&#241;os con hipertension arterial pulmonar idiopatica diagnosticada hace 6 meses, en tratamiento con ambrisentan y tadalafilo. En la revision esta en clase funcional III, camina 290 metros en 6 minutos y tiene un NT-proBNP de 940 ng/L. El ecocardiograma muestra un derrame pericardico ligero de nueva aparicion.', steps: [
    { q: 'En que estrato de riesgo se encuentra en el seguimiento?', options: ['Alto-intermedio', 'Bajo', 'Bajo-intermedio', 'Alto'], correct: 0 },
    { q: 'Cual es la conducta mas apropiada?', options: ['Mantener el tratamiento y revisar en 6 meses', 'Sustituir el ambrisentan por bosentan', 'Escalar el tratamiento a&#241;adiendo un tercer farmaco', 'Reducir la dosis por probable intolerancia'], correct: 2 },
    { q: 'Que significa el derrame pericardico en este contexto?', options: ['Que hay que drenarlo para aliviar la disnea', 'Que sugiere una pericarditis concomitante', 'Que obliga a suspender los vasodilatadores', 'Que es un marcador de mal pronostico'], correct: 3 }
  ], explanation: 'Clase funcional III, marcha de 290 metros y NT-proBNP de 940 corresponden a estratos 3, 3 y 3, con una media que situa a la paciente en riesgo alto-intermedio. No haber alcanzado el riesgo bajo a los 6 meses obliga a escalar, no a observar: se a&#241;ade selexipag o un analogo de prostaciclina, o se cambia el tadalafilo por riociguat, y se valora sotatercept y la remision a trasplante. El derrame pericardico traduce presion auricular derecha elevada, empeora el pronostico y no debe drenarse.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Varon de 61 a&#241;os con hipertension arterial pulmonar en tratamiento con epoprostenol intravenoso. Ingresa por fiebre y tos, y en 24 horas presenta hipotension de 82/50 mmHg, oliguria, ingurgitacion yugular marcada y hepatomegalia pulsatil. El ecocardiograma muestra ventriculo derecho muy dilatado con tabique desplazado.', steps: [
    { q: 'Que hay que buscar y tratar en primer lugar?', options: ['Una progresion natural de la enfermedad', 'El desencadenante, en este caso la infeccion', 'Una embolia pulmonar sobrea&#241;adida', 'Un taponamiento cardiaco por derrame'], correct: 1 },
    { q: 'Que farmaco corresponde para sostener la presion arterial?', options: ['Dopamina a dosis diureticas', 'Fenilefrina en bolos', 'Adrenalina en perfusion', 'Noradrenalina'], correct: 3 },
    { q: 'Que conducta seria un error grave en este paciente?', options: ['Suspender el epoprostenol intravenoso', 'Administrar diuretico intravenoso', 'Corregir la hipoxemia y la acidosis', 'Avisar al centro experto de referencia'], correct: 0 }
  ], explanation: 'La infeccion es el desencadenante mas frecuente del fallo derecho agudo y tratarla es prioritario. La noradrenalina mantiene la presion aortica y con ella la perfusion coronaria del ventriculo derecho, que es la clave para romper la espiral de isquemia y disfuncion. La interrupcion brusca de una prostaciclina parenteral puede producir un deterioro grave e incluso mortal: durante el ingreso hay que asegurar su continuidad y proteger el acceso venoso.', dificultad: 'dificil' },

  { type: 'cascade', vignette: 'Mujer de 29 a&#241;os con hipertension arterial pulmonar hereditaria, en clase funcional II con bosentan y sildenafilo, estable desde hace dos a&#241;os. Acude a consulta refiriendo que esta embarazada de 9 semanas y que desea continuar la gestacion.', steps: [
    { q: 'Que farmaco de su tratamiento hay que retirar de inmediato?', options: ['El sildenafilo', 'El bosentan', 'Ninguno de los dos', 'Los dos a la vez'], correct: 1 },
    { q: 'Que informacion hay que darle sobre el riesgo?', options: ['Que el riesgo es similar al de la poblacion general', 'Que el riesgo se concentra en el primer trimestre', 'Que la mortalidad materna sigue siendo muy alta', 'Que el riesgo desaparece si se mantiene en clase II'], correct: 2 },
    { q: 'Cual es el momento de mayor riesgo si decide continuar?', options: ['La semana 20 de gestacion', 'El primer trimestre', 'La induccion del parto', 'El periparto y el posparto inmediato'], correct: 3 }
  ], explanation: 'Los antagonistas del receptor de la endotelina y el riociguat son teratogenos y se retiran; los inhibidores de la fosfodiesterasa 5 y las prostaciclinas se mantienen. La mortalidad materna en la hipertension arterial pulmonar sigue siendo muy elevada pese a la mejora en centros expertos, y por eso se recomienda evitar el embarazo y ofrecer la interrupcion. Si la paciente decide continuar, el riesgo maximo esta en el periparto y en el posparto inmediato, cuando la autotransfusion uterina y los cambios de volumen sobrecargan un ventriculo derecho sin reserva.', dificultad: 'intermedio' }
];

export const flashcards = [
  { front: 'Definicion hemodinamica de hipertension pulmonar', back: 'Presion arterial pulmonar media MAYOR DE 20 mmHg (bajo desde 25 en 2022).' },
  { front: 'Definicion de la forma precapilar', back: 'Media mayor de 20, enclavamiento 15 o menos y resistencia MAYOR DE 2 unidades Wood.' },
  { front: 'Formula de la resistencia vascular pulmonar', back: '(Presion media menos enclavamiento) dividido por el gasto cardiaco, en unidades Wood.' },
  { front: 'Que define el perfil poscapilar', back: 'Presion de enclavamiento mayor de 15 mmHg: el problema viene del corazon izquierdo.' },
  { front: 'Que aporta el ecocardiograma', back: 'Una PROBABILIDAD (baja, intermedia o alta). Estima, no mide ni diagnostica.' },
  { front: 'Que hay que descartar primero', back: 'Los grupos 2 y 3, que explican la gran mayoria de los casos.' },
  { front: 'Prueba obligatoria en toda HP sin explicar', back: 'La gammagrafia de ventilacion y perfusion: descarta el grupo 4, el unico curable.' },
  { front: 'Angiotomografia normal en el estudio de HP', back: 'NO descarta la enfermedad tromboembolica cronica. La gammagrafia es mas sensible.' },
  { front: 'Los cinco grupos clinicos', back: '1 arterial, 2 cardiopatia izquierda, 3 enfermedad pulmonar, 4 tromboembolica, 5 multifactorial.' },
  { front: 'Unico grupo con vasodilatador especifico', back: 'El grupo 1. En el 2 produce edema pulmonar y en el 3 empeora el intercambio.' },
  { front: 'Excepcion al vasodilatador en el grupo 3', back: 'Treprostinil inhalado en la hipertension pulmonar asociada a EPID.' },
  { front: 'Que caracteriza al grupo 4', back: 'Es POTENCIALMENTE CURABLE con endarterectomia pulmonar.' },
  { front: 'Anticoagulacion en el grupo 4', back: 'INDEFINIDA en todos, incluso tras una endarterectomia con buen resultado.' },
  { front: 'Riociguat en el grupo 4', back: 'Solo si es inoperable o si la hipertension persiste tras la cirugia.' },
  { front: 'Las tres variables de la estratificacion de riesgo', back: 'Clase funcional, marcha de 6 minutos y peptido natriuretico.' },
  { front: 'Objetivo terapeutico en la HAP', back: 'Alcanzar y MANTENER el riesgo bajo, no una cifra de presion.' },
  { front: 'Tratamiento inicial en riesgo bajo o intermedio', back: 'Doble terapia oral: antagonista de la endotelina mas inhibidor de fosfodiesterasa 5.' },
  { front: 'Tratamiento inicial en riesgo alto', back: 'Triple terapia con PROSTACICLINA PARENTERAL y remision a trasplante.' },
  { front: 'Cada cuanto se reestratifica el riesgo', back: 'Cada 3 a 6 meses; si no esta en riesgo bajo, se ESCALA el tratamiento.' },
  { front: 'En quien se hace la prueba de vasorreactividad', back: 'Solo en la HAP idiopatica, hereditaria o inducida por farmacos.' },
  { front: 'Criterios de vasorreactividad positiva', back: 'Descenso de 10 mmHg o mas hasta 40 o menos, con gasto cardiaco conservado.' },
  { front: 'Antagonistas del calcio sin prueba previa', back: 'Pueden producir hipotension y colapso hemodinamico: nunca de forma empirica.' },
  { front: 'Cuantos vasorreactivos mantienen la respuesta', back: 'Solo la mitad al a&#241;o: hay que reevaluarlos a los 3 a 6 meses.' },
  { front: 'Sincope de esfuerzo en la HP', back: 'Significa que el gasto cardiaco NO puede aumentar. Marcador de riesgo alto.' },
  { front: 'Causa de muerte mas frecuente en la HAP', back: 'El fallo agudo del ventriculo derecho.' },
  { front: 'Vasopresor de eleccion en el fallo derecho', back: 'Noradrenalina: mantiene la perfusion coronaria del ventriculo derecho.' },
  { front: 'Por que evitar la ventilacion mecanica', back: 'Reduce la precarga y aumenta la poscarga pulmonar; la induccion puede parar al paciente.' },
  { front: 'Conectivopatia con cribado anual obligado', back: 'La esclerosis sistemica: eco, DLCO y peptido natriuretico aunque este asintomatica.' },
  { front: 'Embarazo en la HAP', back: 'Mortalidad materna muy alta: anticoncepcion eficaz como parte del tratamiento.' },
  { front: 'Farmacos contraindicados en el embarazo', back: 'Antagonistas del receptor de la endotelina y riociguat, por teratogenia.' },
  { front: 'Procedimiento contraindicado en la portopulmonar', back: 'La derivacion portosistemica si la HP es moderada o grave.' },
  { front: 'Interrupcion brusca del tratamiento especifico', back: 'Puede producir fallo derecho agudo y muerte, sobre todo con prostaciclina parenteral.' }
];

export default { quiz, flashcards };
