// topics/nodulo-cancer-tiroides/study.js: Autoevaluacion de Nodulo y Cancer de Tiroides.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// Metodo (ver memoria del proyecto): las 48 preguntas (30 sueltas + 6 cascadas de 3 pasos) se
// escribieron con la respuesta correcta en options[0]/correct:0 y luego se redistribuyo la
// posicion de `correct` con un script. Sin em dash (ver [[feedback-no-em-dash]]).

export const quiz = [
  { q: 'Que proporcion de los nodulos tiroideos detectados por ecografia es maligna?', options: ['Del 30 al 40%', 'Menos del 1%', 'Alrededor del 20%', 'Del 5 al 10%'], correct: 3, explanation: 'Los nodulos se ven por ecografia en mas del 50% de los mayores de 60 anos, de modo que la tarea es encontrar el cancer que importa sin puncionar ni operar a la enorme mayoria que no lo tiene.', dificultad: 'facil' },
  { q: 'Cual es la primera prueba ante el hallazgo de un nodulo tiroideo?', options: ['La TSH', 'La ecografia cervical', 'La puncion con aguja fina', 'La gammagrafia tiroidea'], correct: 0, explanation: 'Es la que decide el camino: si la TSH esta suprimida se hace gammagrafia, y si es normal o alta se sigue por ecografia con TI-RADS. Pedir la ecografia sin TSH lleva a puncionar nodulos calientes.', dificultad: 'facil' },
  { q: 'Que conducta corresponde a un nodulo caliente en la gammagrafia?', options: ['Puncionarlo por su mayor riesgo de malignidad', 'No puncionarlo y tratarlo como hipertiroidismo', 'Operarlo de entrada por su comportamiento autonomo', 'Seguirlo con tiroglobulina cada seis meses'], correct: 1, explanation: 'Un nodulo hiperfuncionante practicamente nunca es maligno. Se maneja como adenoma toxico o bocio multinodular toxico, con yodo radiactivo o cirugia segun el caso.', dificultad: 'intermedio' },
  { q: 'Cual de estos rasgos ecograficos es mas sospechoso de malignidad?', options: ['El patron espongiforme homogeneo', 'El halo hipoecoico completo y fino', 'El nodulo mas alto que ancho', 'Los artefactos en cola de cometa grandes'], correct: 2, explanation: 'Junto con el margen irregular o con extension extratiroidea y los focos ecogenicos puntiformes, es de los rasgos que mas puntuan en el TI-RADS. El patron espongiforme y las colas de cometa grandes son practicamente sinonimo de benignidad.', dificultad: 'intermedio' },
  { q: 'A partir de que tamano se punciona un nodulo TR5 del sistema TI-RADS?', options: ['A partir de 0.5 cm', 'A partir de 1 cm', 'A partir de 1.5 cm', 'A partir de 2.5 cm'], correct: 1, explanation: 'La conducta depende de la categoria Y del tamano a la vez: TR5 desde 1 cm, TR4 desde 1.5 cm y TR3 desde 2.5 cm. Por debajo de esos umbrales se hace seguimiento ecografico.', dificultad: 'intermedio' },
  { q: 'Que categorias del TI-RADS no requieren puncion con independencia del tamano?', options: ['Las categorias TR1, TR2 y TR3', 'Unicamente la categoria TR1', 'Las categorias TR1 y TR2', 'TR1, TR2 y los TR4 pequenos'], correct: 2, explanation: 'TR1 corresponde a 0 puntos y TR2 a 1 o 2 puntos. TR3 si se punciona a partir de 2.5 cm, y por debajo de ese tamano se sigue por ecografia.', dificultad: 'intermedio' },
  { q: 'Por que la citologia no puede diagnosticar un carcinoma folicular?', options: ['Porque las celulas foliculares no se aspiran de forma adecuada', 'Porque el tumor carece de rasgos citologicos propios definidos', 'Porque la muestra suele contaminarse con abundante coloide', 'Porque hace falta demostrar invasion capsular o vascular'], correct: 3, explanation: 'La puncion aspira celulas, no arquitectura. Por eso la categoria Bethesda IV solo puede informar de neoplasia folicular, sin distinguir el adenoma benigno del carcinoma, y hace falta la pieza quirurgica o un panel molecular.', dificultad: 'intermedio' },
  { q: 'Cual es el riesgo de malignidad de una citologia Bethesda II (benigna)?', options: ['Del 1 al 4%', 'Del 15 al 20%', 'Menos del 0.1%', 'Alrededor del 10%'], correct: 0, explanation: 'Es un riesgo bajo pero no nulo, y por eso el nodulo benigno se sigue con ecografia en lugar de darse de alta. Se repuncionaria si crece de forma significativa o cambian sus caracteristicas.', dificultad: 'intermedio' },
  { q: 'Cual es la principal utilidad de los paneles moleculares en la citologia indeterminada?', options: ['Su valor predictivo negativo, que evita cirugias innecesarias', 'Su capacidad de sustituir a la puncion con aguja fina', 'Su valor pronostico en la enfermedad ya metastasica', 'Su utilidad para elegir la extension de la diseccion ganglionar'], correct: 0, explanation: 'Se aplican a las categorias Bethesda III y IV. Un resultado negativo permite evitar la lobectomia diagnostica en muchos pacientes, que es donde mas dano hace la incertidumbre.', dificultad: 'dificil' },
  { q: 'Que ocurrio con la variante folicular encapsulada no invasora del carcinoma papilar?', options: ['Se reclasifico dentro de los carcinomas poco diferenciados', 'Se reclasifico como NIFTP y dejo de considerarse carcinoma', 'Paso a considerarse una variante agresiva del papilar', 'Se integro dentro del grupo de los carcinomas foliculares'], correct: 1, explanation: 'Fue parte del giro hacia la desescalada: reconocer que un tumor de comportamiento indolente no debia llamarse carcinoma redujo el sobretratamiento sin empeorar los resultados.', dificultad: 'dificil' },
  { q: 'Cual es la via de diseminacion caracteristica del carcinoma papilar?', options: ['La hematogena', 'La perineural', 'La linfatica', 'La transcelomica'], correct: 2, explanation: 'Los ganglios cervicales estan afectados al diagnostico en el 30 al 50% de los casos y eso apenas modifica la supervivencia. El folicular y el oncocitico, en cambio, se diseminan por via hematogena a hueso y pulmon.', dificultad: 'facil' },
  { q: 'Cual es la alteracion molecular mas frecuente del carcinoma papilar?', options: ['La fusion PAX8-PPARG', 'La mutacion del gen RET germinal', 'La mutacion de TP53', 'La mutacion BRAF V600E'], correct: 3, explanation: 'Aparece en cerca del 60% de los casos y activa la via MAPK. La fusion PAX8-PPARG es propia del folicular, RET germinal del medular hereditario y TP53 se acumula en la desdiferenciacion hacia anaplasico.', dificultad: 'intermedio' },
  { q: 'Que criterio define el carcinoma folicular frente al adenoma?', options: ['El tamano mayor de 4 centimetros', 'La presencia de rasgos nucleares en vidrio esmerilado', 'La invasion de la capsula o de los vasos', 'La captacion aumentada en la gammagrafia'], correct: 2, explanation: 'Es un diagnostico arquitectural, no citologico, y por eso requiere la pieza quirurgica. Los rasgos nucleares en vidrio esmerilado definen al papilar, no al folicular.', dificultad: 'intermedio' },
  { q: 'Que particularidad tiene el carcinoma oncocitico (de celulas de Hurthle)?', options: ['Se disemina de forma preferente por via linfatica', 'Responde mejor que el papilar a la supresion de TSH', 'Tiene un pronostico mejor que el carcinoma papilar', 'Capta mal el yodo radiactivo'], correct: 3, explanation: 'Esa mala captacion limita el yodo radiactivo como tratamiento y como rescate, lo que hace mas importante la cirugia completa y explica que se tienda mas a la tiroidectomia total.', dificultad: 'dificil' },
  { q: 'De que celulas deriva el carcinoma medular de tiroides?', options: ['De las celulas C parafoliculares', 'Del epitelio folicular tiroideo', 'De los linfocitos B intratiroideos', 'De las celulas oncociticas de Hurthle'], correct: 0, explanation: 'Producen calcitonina, no tiroglobulina. De ahi que no capten yodo, no respondan a la supresion de TSH y se sigan con calcitonina y antigeno carcinoembrionario en lugar de con tiroglobulina.', dificultad: 'facil' },
  { q: 'En que pacientes con carcinoma medular hay que estudiar el gen RET?', options: ['Solo en los que tienen antecedente familiar conocido', 'En todos, haya o no antecedente familiar', 'Solo en los menores de 40 anos al diagnostico', 'Solo si la calcitonina supera los 1000 pg/mL'], correct: 1, explanation: 'Hasta una cuarta parte de los casos aparentemente esporadicos tiene una mutacion germinal. Un resultado positivo obliga a cribar a los familiares y a descartar feocromocitoma e hiperparatiroidismo.', dificultad: 'intermedio' },
  { q: 'Que hay que descartar antes de operar un carcinoma medular de tiroides?', options: ['Una insuficiencia suprarrenal', 'Una hipertension pulmonar', 'Una miocardiopatia hipertrofica', 'Un feocromocitoma'], correct: 3, explanation: 'Forma parte del MEN2 y una crisis hipertensiva intraoperatoria por un feocromocitoma no diagnosticado puede ser mortal. Si existe, se opera primero el feocromocitoma. Tambien se descarta hiperparatiroidismo.', dificultad: 'intermedio' },
  { q: 'Que papel tiene el yodo radiactivo en el carcinoma medular?', options: ['Es el tratamiento de eleccion tras la cirugia', 'Ninguno, porque el tumor no capta yodo', 'Se reserva a la enfermedad metastasica progresiva', 'Se usa solo para el rastreo, no como tratamiento'], correct: 1, explanation: 'La celula C no expresa el cotransportador sodio-yoduro. Por la misma razon, la levotiroxina se da como sustitucion y no como supresion: el tumor no tiene receptor de TSH.', dificultad: 'intermedio' },
  { q: 'Cual es la supervivencia mediana del carcinoma anaplasico de tiroides?', options: ['De 3 a 5 anos', 'De 12 a 18 meses', 'De 4 a 6 meses', 'Superior a 10 anos'], correct: 2, explanation: 'Es una de las neoplasias mas agresivas de la medicina y se considera estadio IV por definicion en cualquier extension. Supone del 1 al 2% de los canceres de tiroides pero una proporcion desproporcionada de sus muertes.', dificultad: 'facil' },
  { q: 'Sobre que enfermedad de base asienta casi siempre el linfoma tiroideo?', options: ['La tiroiditis de Hashimoto', 'El bocio multinodular no toxico', 'La enfermedad de Graves tratada con yodo', 'La tiroiditis subaguda de De Quervain'], correct: 0, explanation: 'La Hashimoto aporta el sustrato linfoide y multiplica el riesgo por 60 a 80. Distinguirlo del anaplasico es urgente, porque el linfoma es potencialmente curable con quimioterapia y no requiere cirugia.', dificultad: 'intermedio' },
  { q: 'Que tratamiento ha cambiado el pronostico del carcinoma anaplasico con BRAF V600E?', options: ['La combinacion de dabrafenib con trametinib', 'La quimioterapia con doxorrubicina y cisplatino', 'El yodo radiactivo en dosis ablativa alta', 'La supresion intensa de la TSH con levotiroxina'], correct: 0, explanation: 'Por eso la determinacion de BRAF V600E se hace de inmediato al diagnostico: cambia el tratamiento en dias y puede permitir una cirugia posterior en tumores inicialmente irresecables.', dificultad: 'dificil' },
  { q: 'Que explora el signo de Pemberton?', options: ['La movilidad de la glandula con la deglucion', 'La presencia de un soplo sobre el tiroides', 'La obstruccion del operculo toracico por un bocio', 'La irritabilidad neuromuscular por hipocalcemia'], correct: 2, explanation: 'Se eleva ambos brazos sobre la cabeza durante un minuto y aparecen congestion facial, cianosis e ingurgitacion yugular. Es caracteristico del bocio con extension retroesternal.', dificultad: 'intermedio' },
  { q: 'Que papel tiene la levotiroxina supresora en el bocio multinodular no toxico?', options: ['Es el tratamiento de eleccion antes de plantear cirugia', 'Se usa solo en bocios menores de 40 mililitros', 'Se combina con yodo radiactivo para reducir el volumen', 'Se ha abandonado por ineficaz y por su coste cardiaco y oseo'], correct: 3, explanation: 'Reduce el volumen de forma minima y transitoria, y la supresion mantenida de TSH aumenta el riesgo de fibrilacion auricular y de perdida osea. El tratamiento es la cirugia o el yodo radiactivo si hay compresion.', dificultad: 'intermedio' },
  { q: 'Cual es la frecuencia del hipoparatiroidismo PERMANENTE tras una tiroidectomia total?', options: ['Del 20 al 30%', 'Del 1 al 3%', 'Menos del 0.1%', 'Alrededor del 10%'], correct: 1, explanation: 'El transitorio si aparece en el 20 al 30%. Ambas cifras empeoran de forma marcada con cirujanos de bajo volumen, que es el factor de riesgo mas importante de las complicaciones de esta cirugia.', dificultad: 'intermedio' },
  { q: 'Cual es la conducta ante un hematoma cervical compresivo tras una tiroidectomia?', options: ['Trasladar a quirofano para revision urgente', 'Abrir la herida de inmediato a pie de cama', 'Solicitar una tomografia cervical urgente', 'Intubar y observar la evolucion durante horas'], correct: 1, explanation: 'Es una urgencia de minutos: la compresion venosa produce edema laringeo que puede hacer imposible la intubacion. No se espera a quirofano ni a pruebas de imagen; despues se completa la revision en el quirofano.', dificultad: 'dificil' },
  { q: 'Que ion hay que corregir siempre en una hipocalcemia posquirurgica refractaria?', options: ['El potasio', 'El fosforo', 'El sodio', 'El magnesio'], correct: 3, explanation: 'La hipomagnesemia altera la secrecion y la accion de la hormona paratiroidea, y mientras no se corrige el calcio no responde por mucho calcio y calcitriol que se administren.', dificultad: 'intermedio' },
  { q: 'Que consecuencia tiene la lesion BILATERAL del nervio laringeo recurrente?', options: ['Obstruccion de la via aerea con estridor', 'Disfonia con voz debil y aspiracion con liquidos', 'Perdida de los tonos agudos con fatiga vocal', 'Anestesia de la mucosa laringea supraglotica'], correct: 0, explanation: 'Las cuerdas quedan en posicion paramediana y cierran la glotis. La lesion unilateral produce disfonia y aspiracion; la perdida de tonos agudos corresponde a la rama externa del laringeo superior.', dificultad: 'intermedio' },
  { q: 'Que condicion invalida la interpretacion de la tiroglobulina en el seguimiento?', options: ['La supresion de la TSH por debajo de 0.1 mUI/L', 'La existencia de restos tiroideos tras la lobectomia', 'La presencia de anticuerpos antitiroglobulina positivos', 'La administracion previa de contraste yodado'], correct: 2, explanation: 'Los anticuerpos falsean la tiroglobulina a la baja y la hacen no interpretable, por lo que se piden siempre en la misma muestra. En ese caso se usa la tendencia del propio titulo de anticuerpos como marcador indirecto.', dificultad: 'intermedio' },
  { q: 'Que diferencia hay entre la estadificacion TNM y el riesgo de recurrencia de la ATA?', options: ['El TNM predice la recurrencia y la ATA la mortalidad', 'Ambos predicen lo mismo con distintos puntos de corte', 'El TNM predice mortalidad y la ATA recurrencia', 'El TNM se aplica al medular y la ATA al diferenciado'], correct: 2, explanation: 'El carcinoma diferenciado es la unica neoplasia solida en la que la edad forma parte de la estadificacion, con punto de corte en 55 anos. En la practica diaria manda la clasificacion de riesgo de la ATA.', dificultad: 'dificil' },
  { q: 'Que explica el aumento por tres de la incidencia del cancer de tiroides en tres decadas?', options: ['El sobrediagnostico de microcarcinomas papilares', 'El aumento real de la exposicion a radiacion', 'La mejora de los tratamientos, que alarga la supervivencia', 'El envejecimiento progresivo de la poblacion'], correct: 0, explanation: 'La mortalidad no aumento en paralelo, lo que delata sobrediagnostico. La respuesta ha sido desescalar: umbrales de puncion mas altos, mas lobectomia, yodo radiactivo selectivo y vigilancia activa en casos seleccionados.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Mujer de 45 anos con un nodulo tiroideo palpado en una revision. TSH de 1.8 mUI/L. La ecografia describe un nodulo solido, hipoecoico, mas ancho que alto, de margen lobulado, con focos ecogenicos puntiformes, de 1.8 cm de diametro maximo.', steps: [
    { q: 'Que categoria TI-RADS corresponde?', options: ['TR3, por sumar 3 puntos', 'TR5, por sumar 9 puntos', 'TR4, por sumar 5 puntos', 'TR2, por sumar 2 puntos'], correct: 1 },
    { q: 'Cual es la conducta con ese tamano?', options: ['Seguimiento ecografico en 12 meses', 'Cirugia directa sin puncion previa del nodulo', 'Gammagrafia tiroidea antes de decidir nada', 'Puncion con aguja fina'], correct: 3 },
    { q: 'La citologia informa Bethesda VI. Que cirugia se plantea?', options: ['Tiroidectomia total con diseccion central profilactica', 'Tiroidectomia total con vaciamiento lateral bilateral', 'Vigilancia activa por tratarse de un tumor pequeno', 'Lobectomia, por ser de 1 a 4 cm sin extension ni ganglios'], correct: 3 }
  ], explanation: 'Solido 2, hipoecoico 2, mas ancho que alto 0, margen lobulado 2 y focos puntiformes 3 suman 9 puntos, que es TR5 y se punciona desde 1 cm. Con un carcinoma papilar de 1.8 cm sin extension extratiroidea ni ganglios, la lobectomia es una opcion valida y evita el hipotiroidismo definitivo y parte de las complicaciones.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Mujer de 52 anos con un nodulo tiroideo de 3 cm. Refiere palpitaciones y perdida de peso leve. La TSH es de 0.05 mUI/L con T4 libre en el limite alto y T3 elevada.', steps: [
    { q: 'Cual es la siguiente prueba?', options: ['Puncion con aguja fina del nodulo', 'Tomografia cervical con contraste', 'Gammagrafia tiroidea', 'Determinacion de calcitonina serica'], correct: 2 },
    { q: 'El nodulo resulta caliente con el resto suprimido. Que se hace?', options: ['No puncionarlo: un nodulo caliente casi nunca es maligno', 'Puncionarlo igualmente por su tamano mayor de 2.5 cm', 'Seguirlo con ecografia semestral sin mas estudios', 'Iniciar levotiroxina supresora para reducirlo'], correct: 0 },
    { q: 'Cual es el tratamiento de eleccion?', options: ['Metimazol de forma indefinida', 'Yodo radiactivo o hemitiroidectomia', 'Tiroidectomia total con vaciamiento central', 'Ablacion percutanea con etanol'], correct: 1 }
  ], explanation: 'Con TSH suprimida el camino se desvia a la gammagrafia antes de aplicar el TI-RADS. Un adenoma toxico se maneja como hipertiroidismo: la autonomia no remite, de modo que el antitiroideo solo sirve de puente y el tratamiento definitivo es el yodo radiactivo o la hemitiroidectomia.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Varon de 38 anos con un nodulo tiroideo de 2.8 cm, TSH normal. La puncion se informa como Bethesda IV, neoplasia folicular.', steps: [
    { q: 'Que significa esa categoria citologica?', options: ['Que el nodulo es maligno con una probabilidad superior al 90%', 'Que no se puede distinguir adenoma de carcinoma folicular', 'Que la muestra fue insuficiente y hay que repetirla', 'Que se trata de un carcinoma papilar variante folicular'], correct: 1 },
    { q: 'Cual es la conducta razonable?', options: ['Panel molecular o lobectomia diagnostica', 'Tiroidectomia total con yodo radiactivo posterior', 'Seguimiento ecografico a los 12 meses', 'Repetir la puncion con aguja gruesa'], correct: 0 },
    { q: 'La histologia muestra invasion capsular con dos focos de invasion vascular. Que implica?', options: ['Adenoma folicular sin criterios de malignidad', 'Carcinoma papilar variante folicular encapsulada', 'Carcinoma folicular minimamente invasor', 'Carcinoma poco diferenciado de alto grado'], correct: 2 }
  ], explanation: 'La puncion aspira celulas y no arquitectura, y el diagnostico de carcinoma folicular exige demostrar invasion capsular o vascular. Los paneles moleculares aportan sobre todo un valor predictivo negativo alto que evita lobectomias innecesarias. Con invasion minima y sin otros factores, la lobectomia puede ser suficiente.', dificultad: 'dificil' },

  { type: 'cascade', vignette: 'Mujer de 40 anos con un nodulo tiroideo de 2 cm y adenopatias cervicales. La calcitonina es de 850 pg/mL y el antigeno carcinoembrionario esta elevado. No refiere antecedentes familiares.', steps: [
    { q: 'Cual es el diagnostico mas probable?', options: ['Carcinoma papilar con metastasis ganglionares', 'Linfoma tiroideo sobre tiroiditis', 'Carcinoma folicular con invasion vascular', 'Carcinoma medular de tiroides'], correct: 3 },
    { q: 'Que hay que hacer antes de la cirugia?', options: ['Descartar feocromocitoma con metanefrinas y estudiar RET', 'Administrar yodo radiactivo para reducir la masa tumoral', 'Iniciar levotiroxina supresora durante seis semanas', 'Solicitar tiroglobulina basal como marcador de seguimiento'], correct: 0 },
    { q: 'Cual es la cirugia indicada?', options: ['Lobectomia con vigilancia posterior de la calcitonina', 'Biopsia quirurgica seguida de quimioterapia', 'Diseccion ganglionar aislada sin tocar la glandula', 'Tiroidectomia total con diseccion central'], correct: 3 }
  ], explanation: 'La calcitonina muy elevada con antigeno carcinoembrionario alto es practicamente diagnostica. El gen RET se estudia en todos los casos porque hasta una cuarta parte de los aparentemente esporadicos es hereditario, y el feocromocitoma se descarta antes de operar porque una crisis intraoperatoria puede ser mortal. En el medular no cabe la lobectomia.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Varon de 72 anos que consulta por una masa cervical que ha crecido de forma visible en tres semanas, con disfonia y estridor con el esfuerzo. La masa es dura y fija. Tiene antecedente de tiroiditis de Hashimoto de larga evolucion.', steps: [
    { q: 'Cual es la conducta diagnostica?', options: ['Puncion con aguja fina y control en dos semanas', 'Biopsia con aguja gruesa urgente', 'Ecografia con TI-RADS y seguimiento segun categoria', 'Gammagrafia tiroidea con captacion a las 24 horas'], correct: 1 },
    { q: 'Que dos entidades hay que distinguir con urgencia?', options: ['Carcinoma papilar y carcinoma folicular', 'Tiroiditis subaguda y tiroiditis de Riedel', 'Carcinoma anaplasico y linfoma tiroideo', 'Bocio subesternal y timoma mediastinico'], correct: 2 },
    { q: 'La inmunohistoquimica confirma carcinoma anaplasico. Que se determina de inmediato?', options: ['El titulo de anticuerpos antitiroperoxidasa', 'La captacion de yodo radiactivo', 'La mutacion BRAF V600E', 'La tiroglobulina serica basal'], correct: 2 }
  ], explanation: 'Una masa de crecimiento rapido con disfonia es una urgencia diagnostica, y la puncion con aguja fina suele ser insuficiente para ambas entidades. Distinguirlas es decisivo: el linfoma es potencialmente curable con quimioterapia y no requiere cirugia, mientras que el anaplasico con BRAF V600E puede responder a dabrafenib con trametinib.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Mujer de 58 anos a las 18 horas de una tiroidectomia total por carcinoma papilar con diseccion central. Refiere parestesias peribucales y en las manos. El signo de Chvostek es positivo. Calcio corregido de 7.1 mg/dL.', steps: [
    { q: 'Cual es el diagnostico?', options: ['Sindrome de hueso hambriento', 'Hipoparatiroidismo posquirurgico', 'Alcalosis respiratoria por hiperventilacion', 'Hipocalcemia por deficit de vitamina D previo'], correct: 1 },
    { q: 'Cual es el tratamiento inicial?', options: ['Hormona paratiroidea recombinante', 'Bisfosfonato intravenoso', 'Restriccion de fosforo en la dieta', 'Calcio oral con calcitriol'], correct: 3 },
    { q: 'La hipocalcemia no responde pese al calcio y el calcitriol. Que hay que comprobar?', options: ['El magnesio serico', 'El potasio serico', 'La funcion hepatica', 'El equilibrio acido-base'], correct: 0 }
  ], explanation: 'Las paratiroides dependen casi por completo de la arteria tiroidea inferior y la diseccion central aumenta el riesgo de desvascularizarlas. Una hormona paratiroidea medida en las primeras horas predice la hipocalcemia sintomatica. La hipomagnesemia altera la secrecion y la accion de la hormona paratiroidea y hace la hipocalcemia refractaria mientras no se corrige.', dificultad: 'facil' }
];

export const flashcards = [
  { front: 'Proporcion de nodulos tiroideos que son malignos', back: 'Del 5 al 10%, pese a que se ven por ecografia en mas de la mitad de los mayores de 60 anos.' },
  { front: 'Primera prueba ante un nodulo tiroideo', back: 'La TSH, porque decide el camino diagnostico.' },
  { front: 'Conducta ante un nodulo caliente', back: 'No se punciona: practicamente nunca es maligno y se trata como hipertiroidismo.' },
  { front: 'Rasgos ecograficos de mayor sospecha', back: 'Mas alto que ancho, margen irregular o con extension extratiroidea, y focos ecogenicos puntiformes.' },
  { front: 'Umbrales de puncion del TI-RADS', back: 'TR5 desde 1 cm, TR4 desde 1.5 cm y TR3 desde 2.5 cm.' },
  { front: 'Categorias TI-RADS que no se puncionan', back: 'TR1 y TR2.' },
  { front: 'Que significa Bethesda IV', back: 'Neoplasia folicular: la citologia NO puede distinguir adenoma de carcinoma folicular.' },
  { front: 'Riesgo de malignidad de una citologia Bethesda II', back: 'Del 1 al 4%: bajo pero no nulo, por eso se sigue con ecografia.' },
  { front: 'Utilidad principal de los paneles moleculares', back: 'Su valor predictivo negativo alto, que evita lobectomias diagnosticas en Bethesda III y IV.' },
  { front: 'Que es el NIFTP', back: 'La variante folicular encapsulada no invasora, que dejo de considerarse carcinoma.' },
  { front: 'Carcinoma papilar: frecuencia y diseminacion', back: '85% de los casos, diseminacion linfatica y supervivencia a 10 anos superior al 95%.' },
  { front: 'Alteracion molecular mas frecuente del papilar', back: 'La mutacion BRAF V600E, en cerca del 60% de los casos.' },
  { front: 'Criterio diagnostico del carcinoma folicular', back: 'La invasion capsular o vascular: es un diagnostico arquitectural, no citologico.' },
  { front: 'Diseminacion del carcinoma folicular', back: 'Hematogena, a hueso y pulmon.' },
  { front: 'Particularidad del carcinoma oncocitico', back: 'Capta mal el yodo radiactivo, lo que limita su uso como tratamiento y como rescate.' },
  { front: 'Origen del carcinoma medular', back: 'Las celulas C parafoliculares, que producen calcitonina y no tiroglobulina.' },
  { front: 'Cuando estudiar el gen RET', back: 'En TODO carcinoma medular: hasta una cuarta parte de los esporadicos tiene mutacion germinal.' },
  { front: 'Que descartar antes de operar un carcinoma medular', back: 'Feocromocitoma con metanefrinas, y tambien hiperparatiroidismo con calcio y PTH.' },
  { front: 'Yodo radiactivo en el carcinoma medular', back: 'Ninguno: el tumor no capta yodo. La levotiroxina se da como sustitucion, no como supresion.' },
  { front: 'Pronostico del carcinoma anaplasico', back: 'Supervivencia mediana de 4 a 6 meses; es estadio IV por definicion en cualquier extension.' },
  { front: 'Tratamiento del anaplasico con BRAF V600E', back: 'Dabrafenib con trametinib. La mutacion se determina de inmediato al diagnostico.' },
  { front: 'Linfoma tiroideo', back: 'Asienta sobre una tiroiditis de Hashimoto; es potencialmente curable y NO requiere cirugia.' },
  { front: 'Signo de Pemberton', back: 'Congestion facial, cianosis e ingurgitacion yugular al elevar los brazos: obstruccion del operculo toracico.' },
  { front: 'Levotiroxina supresora en el bocio no toxico', back: 'Abandonada: ineficaz y con coste cardiaco y oseo.' },
  { front: 'Hipoparatiroidismo tras tiroidectomia total', back: 'Transitorio en el 20 al 30% y permanente en el 1 al 3%.' },
  { front: 'Conducta ante un hematoma cervical compresivo', back: 'Abrir la herida de inmediato a pie de cama, sin esperar a quirofano ni a pruebas de imagen.' },
  { front: 'Hipocalcemia posquirurgica que no responde', back: 'Corregir el MAGNESIO: su deficit altera la secrecion y la accion de la PTH.' },
  { front: 'Lesion bilateral del nervio laringeo recurrente', back: 'Obstruccion de la via aerea por cierre glotico, que puede exigir traqueostomia.' },
  { front: 'Lesion de la rama externa del laringeo superior', back: 'Perdida de los tonos agudos y fatiga vocal, sin disfonia franca.' },
  { front: 'Por que se piden anticuerpos con la tiroglobulina', back: 'Los antitiroglobulina la falsean a la baja y la hacen no interpretable.' },
  { front: 'TNM frente a riesgo de recurrencia de la ATA', back: 'El TNM predice MORTALIDAD y usa la edad (55 anos); la ATA predice RECURRENCIA y gobierna la practica.' },
  { front: 'La desescalada de la ultima decada', back: 'Umbrales de puncion mas altos, mas lobectomia, yodo radiactivo selectivo y vigilancia activa en microcarcinomas.' }
];
