// topics/meningoencefalitis-infecciosa/study.js: Autoevaluacion de meningoencefalitis infecciosa.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// 48 subpreguntas (30 sueltas + 6 cascadas de 3 pasos) y 32 tarjetas.
// Sin em dash (ver [[feedback-no-em-dash]]). Texto sin acentos.

export const quiz = [
  { q: 'Con que frecuencia esta completa la triada clasica de la meningitis en el adulto?', options: ['En menos de la mitad', 'En casi todos los casos', 'En tres de cada cuatro', 'Solo si hay neumococo'], correct: 0, explanation: 'Fiebre, rigidez de nuca y alteracion de la conciencia coinciden en una minoria. Lo que si es casi constante es tener DOS de estos cuatro: cefalea, fiebre, rigidez de nuca y alteracion del nivel de conciencia.', dificultad: 'facil' },
  { q: 'Cual es el factor pronostico modificable mas importante de la meningitis bacteriana?', options: ['La eleccion de la cefalosporina', 'El uso de una dosis de carga', 'El tiempo hasta la primera dosis', 'La duracion total del tratamiento'], correct: 2, explanation: 'El retraso del antibiotico se asocia de forma consistente a mayor mortalidad. La eleccion del farmaco importa, pero llegar pronto importa mas, y es lo unico que depende por completo del equipo que atiende.', dificultad: 'intermedio' },
  { q: 'Cuando se administra la dexametasona en la meningitis bacteriana?', options: ['Al confirmar el neumococo', 'Antes o con el antibiotico', 'A las 24 horas de tratamiento', 'Solo si hay mala evolucion'], correct: 1, explanation: 'Su efecto consiste en modular la respuesta inflamatoria desencadenada por la lisis bacteriana. Administrada despues de la primera dosis de antibiotico ya no llega a tiempo y no aporta beneficio.', dificultad: 'intermedio' },
  { q: 'Cuando se suspende la dexametasona iniciada de forma empirica?', options: ['Si el paciente mejora pronto', 'Al completar los 10 dias', 'Si aparece hiperglucemia', 'Si el germen no es neumococo'], correct: 3, explanation: 'El beneficio demostrado se concentra en la meningitis neumococica. Con otro germen se retira, y mantenerla sin indicacion solo suma efectos adversos sin ninguna ganancia.', dificultad: 'intermedio' },
  { q: 'Por que se a&#241;ade ampicilina en el paciente mayor de 50 a&#241;os?', options: ['Por el neumococo resistente', 'Porque cubre Listeria', 'Por sinergia con vancomicina', 'Por los bacilos gramnegativos'], correct: 1, explanation: 'Las cefalosporinas NO cubren Listeria monocytogenes, que aparece por encima de los 50 a&#241;os, en el embarazo y en la inmunodepresion. Olvidar la ampicilina es el error mas repetido de este apartado.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 68 a&#241;os llevado a urgencias por fiebre de 39 grados, cefalea intensa desde hace 10 horas y confusion progresiva. Esta desorientado y somnoliento, con rigidez de nuca marcada. No hay papiledema, ni focalidad, ni antecedente de crisis, ni inmunodepresion conocida.',
    steps: [
      { q: 'Que corresponde hacer en los primeros minutos?', options: ['Tomografia craneal urgente sin contraste', 'Puncion lumbar inmediata en urgencias', 'Hemocultivos y tratamiento sin demora', 'Resonancia craneal con contraste'], correct: 2 },
      { q: 'Hay criterio para hacer tomografia antes de la puncion?', options: ['No, porque no hay focalidad ni papiledema', 'No, porque hay rigidez de nuca marcada', 'Solo si el Gram resulta negativo', 'Si, por la alteracion de la conciencia'], correct: 3 },
      { q: 'Que cobertura empirica corresponde?', options: ['Vancomicina, cefalosporina y ampicilina', 'Vancomicina con cefalosporina sola', 'Cefalosporina con aciclovir', 'Meropenem con vancomicina'], correct: 0 }
    ],
    explanation: 'La secuencia es lo que decide el pronostico: hemocultivos, dexametasona y antibiotico ANTES de cualquier prueba de imagen. La alteracion del nivel de conciencia es uno de los criterios que indican tomografia antes de la puncion, junto con la inmunodepresion, la enfermedad previa del sistema nervioso central, la crisis reciente, el papiledema y la focalidad. Pero pedir esa tomografia no autoriza a esperar: el tratamiento se administra antes de bajar al aparato. Y con 68 a&#241;os hay que a&#241;adir AMPICILINA a la vancomicina y a la cefalosporina de tercera generacion, porque estas ultimas no cubren Listeria.'
  },
  { q: 'Cual de estos hallazgos indica tomografia antes de la puncion lumbar?', options: ['La rigidez de nuca intensa', 'El exantema petequial', 'El papiledema', 'La fiebre alta mantenida'], correct: 2, explanation: 'Junto con la inmunodepresion, la enfermedad previa del sistema nervioso, la crisis en la semana previa, la alteracion de la conciencia y la focalidad. La rigidez, el exantema y la fiebre no predicen efecto de masa.', dificultad: 'intermedio' },
  { q: 'Por que el cociente de glucosa vale mas que la glucosa aislada del liquido?', options: ['Porque no depende de la glucemia', 'Porque se mide con mas precision', 'Porque detecta antes los virus', 'Porque se altera mas tarde'], correct: 0, explanation: 'Una glucosa de 45 mg/dL en el liquido significa cosas distintas si la glucemia es 90 o si es 300. Por eso hay que extraer una glucemia SIMULTANEA a la puncion para poder calcularlo.', dificultad: 'intermedio' },
  { q: 'Que significa un liquido linfocitario con glucosa baja?', options: ['Una meningitis virica tipica', 'Una puncion traumatica', 'Una meningitis quimica', 'Que NO es una meningitis virica'], correct: 3, explanation: 'Obliga a pensar en tuberculosis, criptococo, Listeria, Brucella, sifilis y carcinomatosis meningea. Interpretarlo como virico por el predominio linfocitario es uno de los errores mas caros del tema.', dificultad: 'intermedio' },
  { q: 'Que limitacion tiene corregir la celularidad por una puncion traumatica?', options: ['Solo sirve por debajo de 5000 hematies', 'Es una aproximacion, no una regla exacta', 'Exige conocer el hematocrito del paciente', 'No se aplica si ya hubo antibiotico'], correct: 1, explanation: 'La correccion resta un leucocito por cada 500 a 1000 hematies, pero si el resultado queda en el limite manda la clinica y no la aritmetica. Que el liquido aclare entre tubos apoya la puncion traumatica y tampoco la prueba.', dificultad: 'dificil' },
  { q: 'Que hay que hacer ante una presion de apertura muy elevada en la meningitis criptococica?', options: ['Administrar manitol en bolo', 'Restringir liquidos de forma estricta', 'Punciones evacuadoras repetidas', 'Elevar la dosis de fluconazol'], correct: 2, explanation: 'La hipertension intracraneal es la principal causa de muerte precoz en esta meningitis, y su tratamiento son las punciones repetidas. Forman parte del tratamiento y no son un gesto diagnostico.', dificultad: 'dificil' },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 41 a&#241;os con infeccion por VIH mal controlada, que consulta por cefalea de tres semanas y febricula. El liquido cefalorraquideo muestra 180 celulas por mm3 con un 15% de polimorfonucleares, glucosa de 24 mg/dL con una glucemia simultanea de 96 mg/dL, proteinas de 220 mg/dL y una presion de apertura de 34 cmH2O.',
    steps: [
      { q: 'Cuanto vale el cociente de glucosa?', options: ['0.15', '0.25', '0.40', '0.55'], correct: 1 },
      { q: 'Que perfil tiene este liquido?', options: ['Linfocitario con glucosa baja', 'Linfocitario con glucosa normal', 'Purulento tipico', 'Practicamente normal'], correct: 0 },
      { q: 'Que corresponde hacer con la presion de apertura?', options: ['Repetirla en una semana', 'Tratarla con corticoides', 'Anotarla y no intervenir', 'Puncionar de forma repetida'], correct: 3 }
    ],
    explanation: 'El cociente de glucosa se calcula dividiendo la del liquido entre la glucemia simultanea: 24 entre 96 son 0.25, muy por debajo de 0.4. Con predominio linfocitario y proteinas muy elevadas, el perfil es LINFOCITARIO CON GLUCOSA BAJA, que no es una meningitis virica y obliga a buscar tuberculosis y criptococo, sobre todo en este contexto. Y una presion de apertura de 34 cmH2O es el hallazgo que mas condiciona la supervivencia inmediata: en la meningitis criptococica la hipertension intracraneal es la principal causa de muerte precoz y se trata con punciones evacuadoras repetidas, no con corticoides ni con manitol.'
  },
  { q: 'Cual es la prueba de eleccion para el diagnostico de meningitis criptococica?', options: ['El antigeno criptococico', 'La tincion con tinta china', 'El cultivo en medio de Sabouraud', 'La citologia del liquido'], correct: 0, explanation: 'Tiene sensibilidad muy alta en suero y en liquido, muy superior a la tinta china. Se pide ante toda meningitis subaguda o linfocitaria y en cualquier paciente con inmunodepresion celular.', dificultad: 'intermedio' },
  { q: 'Que significa una prueba molecular para herpes negativa en las primeras 72 horas?', options: ['Que descarta el diagnostico', 'Que hay que buscar otro virus', 'Que el cuadro es bacteriano', 'Que NO descarta el diagnostico'], correct: 3, explanation: 'Puede ser negativa al principio. Si la sospecha sigue alta se mantiene el aciclovir y se repite la puncion a los pocos dias, porque la enfermedad no tratada deja secuelas graves o mata.', dificultad: 'dificil' },
  { q: 'Que separa clinicamente una meningitis de una encefalitis?', options: ['La intensidad de la cefalea referida', 'El fallo de la funcion cerebral', 'La presencia de fiebre elevada mantenida', 'El grado de rigidez de nuca observado'], correct: 1, explanation: 'En la meningitis el paciente esta molesto pero contesta y se orienta. En la encefalitis fallan la conducta, el lenguaje, la memoria o aparecen crisis, y eso cambia el plan: aciclovir, resonancia y electroencefalograma.', dificultad: 'facil' },
  { q: 'Que territorio afecta de forma caracteristica la encefalitis herpetica?', options: ['El tronco del encefalo', 'La sustancia blanca periventricular', 'Los lobulos temporales mediales', 'Los ganglios de la base'], correct: 2, explanation: 'Se afectan tambien la insula y el sistema limbico, con frecuencia de forma asimetrica. La resonancia es mucho mas sensible que la tomografia, que puede ser normal en las primeras horas.', dificultad: 'intermedio' },
  { q: 'Por que hay que hidratar bien durante el tratamiento con aciclovir?', options: ['Por el riesgo de da&#241;o renal', 'Por la hipotension que produce', 'Por la hemolisis asociada', 'Por la diarrea que provoca'], correct: 0, explanation: 'El farmaco puede cristalizar en el ri&#241;on si el paciente esta deshidratado. Una hidratacion adecuada previene esa toxicidad y permite completar el tratamiento sin interrupciones.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 55 a&#241;os con fiebre desde hace tres dias. Desde ayer la familia refiere que habla de forma extra&#241;a, no recuerda lo que ha hecho por la ma&#241;ana y ha presentado un episodio de desviacion de la mirada con movimientos del brazo derecho. Esta desorientado. La tomografia craneal es normal.',
    steps: [
      { q: 'Que hay que a&#241;adir de inmediato al tratamiento?', options: ['Corticoides a dosis alta', 'Ganciclovir intravenoso', 'Inmunoglobulinas intravenosas', 'Aciclovir intravenoso'], correct: 3 },
      { q: 'La prueba molecular para herpes es negativa a las 24 horas. Que se hace?', options: ['Suspender el tratamiento antiviral', 'Mantenerlo y repetir la puncion', 'Cambiar a un antiviral distinto', 'Dar el alta con control ambulatorio'], correct: 1 },
      { q: 'Que prueba de imagen aporta mas en este momento?', options: ['Repetir la tomografia con contraste', 'Angiografia cerebral', 'Resonancia craneal', 'Tomografia por emision de positrones'], correct: 2 }
    ],
    explanation: 'Fiebre con alteracion del lenguaje, fallo de la memoria reciente y una crisis focal definen un perfil ENCEFALITICO, y ante esa sospecha el aciclovir se inicia sin esperar a ninguna confirmacion, porque el pronostico depende del tiempo hasta la primera dosis. Una prueba molecular negativa en las primeras 72 horas NO descarta el diagnostico: se mantiene el tratamiento y se repite la puncion a los pocos dias. Y una tomografia normal no significa nada en este contexto: la resonancia es mucho mas sensible y muestra la afectacion temporal medial, insular y limbica que caracteriza al cuadro.'
  },
  { q: 'Que aporta el electroencefalograma en un paciente con encefalitis que no despierta?', options: ['Confirma el virus responsable', 'Mide la presion intracraneal', 'Descarta el edema cerebral', 'Detecta crisis no convulsivas'], correct: 3, explanation: 'Son una causa tratable de bajo nivel de conciencia que se pasa por alto si no se busca. Ademas suele mostrar enlentecimiento focal temporal y a veces descargas periodicas lateralizadas.', dificultad: 'dificil' },
  { q: 'Que obliga a hacer el hallazgo de un exantema petequial?', options: ['Iniciar corticoides a dosis alta', 'Aislar por gotas y dar profilaxis', 'Suspender la cefalosporina', 'Repetir la puncion a las 12 horas'], correct: 1, explanation: 'Sugiere meningococo, lo que obliga a aislamiento por gotas durante las primeras 24 horas de tratamiento y a quimioprofilaxis de los contactos estrechos. Ambas medidas se olvidan con el paciente grave delante.', dificultad: 'intermedio' },
  { q: 'Que hay que buscar ante una meningitis bacteriana recurrente?', options: ['Una fistula de liquido cefalorraquideo', 'Una resistencia antibiotica adquirida', 'Una duracion de tratamiento insuficiente', 'Una reinfeccion por contacto estrecho'], correct: 0, explanation: 'Junto con el deficit del complemento y un foco parameningeo cronico. Tratar el episodio sin buscar la puerta de entrada garantiza el siguiente, y muchas de esas causas son corregibles.', dificultad: 'dificil' },
  { q: 'Que hallazgo de resonancia separa un absceso cerebral de un tumor necrotico?', options: ['El realce en anillo', 'El edema perilesional', 'La restriccion de la difusion', 'El efecto de masa asociado'], correct: 2, explanation: 'El pus tiene alta celularidad y viscosidad, de modo que restringe la difusion; la necrosis tumoral no lo hace. El realce en anillo, el edema y el efecto de masa aparecen en ambos.', dificultad: 'intermedio' },
  { q: 'Que papel tiene la puncion lumbar ante un absceso cerebral con efecto de masa?', options: ['Es la prueba diagnostica clave', 'Sirve para medir la presion', 'Permite ajustar el antibiotico', 'Esta contraindicada'], correct: 3, explanation: 'Aporta poco y a&#241;ade riesgo de herniacion. El diagnostico microbiologico se obtiene por aspiracion del absceso, que ademas descomprime, y por los hemocultivos extraidos antes del antibiotico.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Se recibe el resultado de una puncion lumbar que costo tres intentos. El liquido tiene 1200 leucocitos por mm3 con un 60% de polimorfonucleares, 12000 hematies por mm3, glucosa de 58 mg/dL con una glucemia simultanea de 100 mg/dL y proteinas de 95 mg/dL. El paciente habia recibido una dosis de ceftriaxona en otro centro.',
    steps: [
      { q: 'Como queda la celularidad tras corregir por los hematies?', options: ['Alrededor de 1180, sigue muy elevada', 'Alrededor de 600, la mitad', 'Alrededor de 200, casi normal', 'No se puede estimar de ningun modo'], correct: 0 },
      { q: 'Que perfil tiene el liquido?', options: ['Linfocitario con glucosa baja', 'Purulento con glucosa conservada', 'Linfocitario con glucosa normal', 'Compatible con la normalidad'], correct: 1 },
      { q: 'Que conducta corresponde con ese perfil?', options: ['Dar el alta con analgesia', 'Cambiar a tratamiento antiviral', 'Mantener el antibiotico empirico', 'Iniciar tratamiento antituberculoso'], correct: 2 }
    ],
    explanation: 'La correccion por puncion traumatica resta un leucocito por cada 500 a 1000 hematies: con 12000 hematies se restan entre 12 y 24 leucocitos, de modo que la celularidad corregida ronda los 1180 y sigue siendo una pleocitosis marcada. El cociente de glucosa es 58 entre 100, es decir 0.58, conservado, pero con predominio de polimorfonucleares. Ese perfil no tranquiliza: puede ser una meningitis virica muy precoz, una bacteriana incipiente o, como aqui sugiere el antecedente, una bacteriana PARCIALMENTE TRATADA por la dosis previa de ceftriaxona. Corresponde mantener el tratamiento empirico y repetir la puncion si la evolucion no aclara el cuadro.'
  },
  { q: 'Que explica las complicaciones caracteristicas de la meningitis tuberculosa?', options: ['El exudado espeso de la base', 'La toxina bacteriana circulante', 'La respuesta neutrofilica intensa', 'La diseminacion hematogena masiva'], correct: 0, explanation: 'Ese exudado atrapa los pares craneales, obstruye la circulacion del liquido produciendo hidrocefalia y envuelve las arterias de la base causando vasculitis e infartos. Explica la triada completa.', dificultad: 'dificil' },
  { q: 'Que efecto tiene la dexametasona adyuvante en la meningitis tuberculosa?', options: ['Acelera la esterilizacion del liquido', 'Evita la aparicion de hidrocefalia', 'Reduce la mortalidad', 'Previene los infartos cerebrales'], correct: 2, explanation: 'Es una de las pocas indicaciones firmes de corticoide en infeccion del sistema nervioso central. El tratamiento antituberculoso se inicia ante la sospecha, sin esperar a la confirmacion microbiologica.', dificultad: 'intermedio' },
  { q: 'Que predice mejor la mortalidad y las secuelas en la meningitis tuberculosa?', options: ['El recuento de celulas del liquido inicial', 'El estadio clinico al empezar a tratar', 'El valor de la adenosina desaminasa', 'La extension del realce meningeo basal'], correct: 1, explanation: 'Los estadios del British Medical Research Council se basan en el nivel de conciencia y en la focalidad. Por eso el diagnostico precoz importa tanto: cada dia de retraso empeora el estadio de partida.', dificultad: 'dificil' },
  { q: 'Cual es la causa mas frecuente de meningitis virica en el adulto?', options: ['El virus varicela zoster', 'El virus herpes simple tipo 1', 'El virus de la parotiditis', 'Los enterovirus'], correct: 3, explanation: 'Tienen un pico estacional en los meses calidos y suelen resolverse solos en una o dos semanas. Le siguen el virus herpes simple tipo 2, que puede dar meningitis recurrente, y la primoinfeccion por VIH.', dificultad: 'facil' },
  { q: 'Que serologia se olvida con frecuencia ante una meningitis linfocitaria?', options: ['La del VIH', 'La de la sifilis', 'La de la brucelosis', 'La de la enfermedad de Lyme'], correct: 0, explanation: 'La primoinfeccion se presenta como una meningitis aseptica y su deteccion cambia por completo el manejo del paciente. Hay que pedir serologia y carga viral, porque la serologia puede ser aun negativa.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 46 a&#241;os con otitis media cronica de a&#241;os de evolucion. Consulta por cefalea progresiva de dos semanas, sobre todo del lado izquierdo, y desde hace dos dias debilidad del brazo derecho. Esta afebril. La tomografia muestra una lesion temporal izquierda con realce en anillo y edema alrededor.',
    steps: [
      { q: 'Que prueba resuelve el diagnostico diferencial con un tumor?', options: ['Tomografia con doble contraste', 'Espectroscopia por resonancia', 'Angiografia de troncos cerebrales', 'Difusion en la resonancia'], correct: 3 },
      { q: 'Corresponde hacer una puncion lumbar?', options: ['Si, para obtener el germen', 'No, por el efecto de masa', 'Si, midiendo la presion', 'Solo tras dar manitol'], correct: 1 },
      { q: 'Que procedimiento es de eleccion en la mayoria de estos casos?', options: ['Radioterapia estereotactica', 'Biopsia abierta diferida', 'Observacion con antibiotico solo', 'Aspiracion estereotactica'], correct: 3 }
    ],
    explanation: 'Una lesion en anillo en un paciente con otitis media cronica y sin fiebre es un absceso cerebral hasta que se demuestre lo contrario, aunque la ausencia de fiebre lleve a estudiarlo primero como un tumor. La DIFUSION resuelve el diferencial: el pus restringe y la necrosis tumoral no. La puncion lumbar esta contraindicada por el efecto de masa y ademas aporta poco. Y la aspiracion estereotactica es de eleccion porque hace dos cosas a la vez: descomprime y proporciona el diagnostico microbiologico que permite dirigir un tratamiento que durara semanas. Sin tratar el foco otico, la recurrencia es probable.'
  },
  { q: 'Por que conviene repetir la puncion a las 48 horas ante un neumococo resistente tratado con dexametasona?', options: ['Porque el corticoide enmascara la fiebre y el dolor', 'Porque el cultivo tarda ese tiempo', 'Porque el corticoide reduce su penetracion', 'Porque cambia el recuento celular'], correct: 2, explanation: 'Al reducir la inflamacion, la dexametasona disminuye la permeabilidad de la barrera y con ella la penetracion del antibiotico. Comprobar la esterilizacion del liquido evita descubrir tarde un fracaso terapeutico.', dificultad: 'dificil' },
  { q: 'Que ventaja tienen los hemocultivos extraidos antes del antibiotico?', options: ['Detectan tambien los virus habituales', 'Siguen informando si la puncion se difiere', 'Permiten evitar la puncion lumbar', 'Dan el resultado en menos de una hora'], correct: 1, explanation: 'Identifican el germen en una proporcion importante de las meningitis bacterianas. Se extraen en un minuto, no retrasan nada y rescatan el diagnostico cuando el liquido ya esta esterilizado.', dificultad: 'intermedio' },
  { q: 'Que significa una tomografia craneal normal antes de la puncion lumbar?', options: ['Que el cuadro no es de origen bacteriano', 'Que se puede retrasar el antibiotico sin riesgo', 'Que la presion intracraneal es normal', 'Que NO descarta hipertension intracraneal'], correct: 3, explanation: 'La imagen busca lesiones con efecto de masa, no mide la presion. Si la clinica sugiere herniacion inminente, una tomografia normal no autoriza a puncionar, y en ningun caso justifica esperar para tratar.', dificultad: 'dificil' },
  { q: 'Que germenes hay que cubrir en la meningitis tras neurocirugia o con derivacion ventricular?', options: ['Estafilococos y gramnegativos', 'Listeria y neumococo', 'Meningococo y Haemophilus', 'Anaerobios y estreptococos orales'], correct: 0, explanation: 'La flora cambia por completo y obliga a cobertura antipseudomonica. Y hay una parte no farmacologica sin la cual el tratamiento suele fracasar: retirar el dispositivo infectado.', dificultad: 'intermedio' },
  { q: 'Que hay que sospechar si una encefalitis herpetica empeora tras haber mejorado?', options: ['Una recaida por dosis insuficiente', 'Una resistencia al aciclovir', 'Una encefalitis autoinmune', 'Una sobreinfeccion bacteriana'], correct: 2, explanation: 'La encefalitis por anticuerpos frente al receptor de NMDA puede aparecer despues de una herpetica y tiene tratamiento propio. Es un fenomeno bien descrito que se pasa por alto si no se piensa en el.', dificultad: 'dificil' },
  {
    type: 'cascade', dificultad: 'facil',
    vignette: 'Mujer de 19 a&#241;os que vive en una residencia de estudiantes. Acude por fiebre de 39 grados, cefalea intensa y vomitos de 6 horas de evolucion. Esta somnolienta, con rigidez de nuca, y presenta lesiones petequiales en tronco y extremidades. La tension arterial es de 85 sobre 50 mmHg.',
    steps: [
      { q: 'Que medida de control hay que a&#241;adir al tratamiento?', options: ['Aislamiento de contacto estricto', 'Aislamiento protector inverso', 'Aislamiento por gotas', 'Aislamiento aereo con presion negativa'], correct: 2 },
      { q: 'Que corresponde con los companeros de residencia?', options: ['Vigilancia clinica sin tratamiento', 'Quimioprofilaxis a los contactos estrechos', 'Vacunacion inmediata de todos', 'Cultivo faringeo a toda la residencia'], correct: 1 },
      { q: 'Que complicacion hay que temer con este cuadro?', options: ['Purpura fulminante', 'Absceso cerebral', 'Hidrocefalia cronica', 'Empiema subdural'], correct: 0 }
    ],
    explanation: 'El exantema petequial con fiebre, rigidez de nuca e hipotension en una persona joven que vive en un espacio cerrado orienta a enfermedad meningococica. Ademas del tratamiento, obliga a dos medidas de salud publica que se olvidan con el paciente grave delante: aislamiento POR GOTAS durante las primeras 24 horas de tratamiento y QUIMIOPROFILAXIS de los contactos estrechos. La complicacion que hay que temer es la PURPURA FULMINANTE con coagulacion intravascular diseminada y shock, que puede progresar en horas y que explica por que este cuadro se maneja desde el principio como una urgencia hemodinamica y no solo infecciosa.'
  }
];

export const flashcards = [
  { front: 'La triada clasica de la meningitis', back: 'Completa en menos de la mitad. Casi todos tienen DOS de cuatro.' },
  { front: 'Los cuatro datos de los que hay que tener dos', back: 'Cefalea, fiebre, rigidez de nuca y alteracion del nivel de conciencia.' },
  { front: 'El orden de las primeras horas', back: 'Hemocultivos, dexametasona y antibiotico. Despues tomografia y puncion.' },
  { front: 'El factor pronostico modificable clave', back: 'El tiempo hasta la primera dosis de antibiotico.' },
  { front: 'Momento de la dexametasona', back: 'ANTES o CON la primera dosis. Despues ya no aporta.' },
  { front: 'Cuando se suspende la dexametasona', back: 'Si el germen no resulta ser neumococo.' },
  { front: 'Por que ampicilina si hay mas de 50 a&#241;os', back: 'Las cefalosporinas NO cubren Listeria. Tambien en embarazo e inmunodepresion.' },
  { front: 'Criterios de tomografia antes de la puncion', back: 'Inmunodepresion, enfermedad del SNC, crisis reciente, papiledema, conciencia o focalidad.' },
  { front: 'Si se pide la tomografia', back: 'Tratar ANTES de bajar al aparato. La imagen nunca justifica el retraso.' },
  { front: 'Tomografia normal antes de puncionar', back: 'NO descarta hipertension intracraneal.' },
  { front: 'El cociente de glucosa', back: 'Glucosa del liquido entre glucemia SIMULTANEA. Por debajo de 0.4 es patologico.' },
  { front: 'Perfil bacteriano del liquido', back: 'Polimorfonucleares, cociente bajo y proteinas elevadas.' },
  { front: 'Perfil virico del liquido', back: 'Linfocitos, glucosa NORMAL y proteinas poco elevadas.' },
  { front: 'Linfocitos con glucosa BAJA', back: 'NO es virica: tuberculosis, criptococo, Listeria, Brucella o carcinomatosis.' },
  { front: 'Correccion de la puncion traumatica', back: 'Restar un leucocito por cada 500 a 1000 hematies. Es una aproximacion.' },
  { front: 'La presion de apertura', back: 'Gratis y se olvida siempre. En la criptococica dicta el tratamiento.' },
  { front: 'Hipertension intracraneal en la criptococica', back: 'Principal causa de muerte precoz. Se trata con punciones evacuadoras repetidas.' },
  { front: 'Prueba de eleccion para criptococo', back: 'Antigeno criptococico en suero y liquido, muy superior a la tinta china.' },
  { front: 'Meningitis frente a encefalitis', back: 'En la encefalitis falla la FUNCION cerebral: conducta, lenguaje, memoria o crisis.' },
  { front: 'Encefalitis herpetica: cuando tratar', back: 'Aciclovir ante la sospecha, sin esperar a la prueba molecular.' },
  { front: 'Prueba molecular de herpes negativa el primer dia', back: 'NO descarta. Mantener el aciclovir y repetir la puncion.' },
  { front: 'Imagen de la encefalitis herpetica', back: 'Resonancia: temporal medial, insula y sistema limbico, a menudo asimetrica.' },
  { front: 'Electroencefalograma en la encefalitis', back: 'Enlentecimiento temporal y deteccion de CRISIS NO CONVULSIVAS.' },
  { front: 'Empeora tras mejorar en una herpetica', back: 'Pensar en encefalitis autoinmune posherpetica, por anticuerpos anti-NMDA.' },
  { front: 'Exantema petequial', back: 'Aislamiento por gotas 24 horas y quimioprofilaxis de contactos estrechos.' },
  { front: 'Meningitis recurrente', back: 'Buscar fistula de liquido, deficit de complemento o foco parameningeo cronico.' },
  { front: 'Triada de complicaciones de la TB meningea', back: 'Pares craneales, hidrocefalia e infartos, por el exudado de la BASE.' },
  { front: 'Dexametasona en meningitis tuberculosa', back: 'Reduce la mortalidad. Se trata ante la sospecha, sin esperar confirmacion.' },
  { front: 'Estadios del British Medical Research Council', back: 'Segun conciencia y focalidad. El estadio inicial predice muerte y secuelas.' },
  { front: 'Absceso frente a tumor en la resonancia', back: 'El absceso RESTRINGE la difusion; la necrosis tumoral no.' },
  { front: 'Puncion lumbar en el absceso con masa', back: 'Contraindicada. El diagnostico se obtiene por aspiracion estereotactica.' },
  { front: 'Meningitis tras neurocirugia o derivacion', back: 'Estafilococos y gramnegativos: cubrir Pseudomonas y RETIRAR el dispositivo.' }
];

export default { quiz, flashcards };
