// topics/apnea-sueno/study.js: Autoevaluacion de Apnea del Sue&#241;o.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// 48 subpreguntas (30 sueltas + 6 cascadas de 3 pasos) y 32 tarjetas.
// Sin em dash (ver [[feedback-no-em-dash]]). Texto sin acentos.

export const quiz = [
  { q: 'Que separa un evento respiratorio obstructivo de uno central?', options: ['La duracion del evento', 'La presencia de esfuerzo respiratorio', 'La magnitud de la desaturacion', 'La posicion en que se produce'], correct: 1, explanation: 'En el obstructivo el paciente sigue luchando contra una via aerea cerrada y las bandas toracoabdominales se mueven, incluso en oposicion de fase. En el central el esfuerzo desaparece porque no llega la orden del centro respiratorio. De esa diferencia dependen la causa que hay que buscar y el tratamiento.', dificultad: 'facil' },
  { q: 'Que define una APNEA en un estudio de sue&#241;o?', options: ['Caida del flujo del 30% durante 10 segundos', 'Caida del flujo del 50% durante 20 segundos', 'Cualquier pausa que se acompa&#241;e de desaturacion', 'Caida del flujo del 90% durante 10 segundos'], correct: 3, explanation: 'La apnea exige una caida del flujo del 90% o mas durante al menos 10 segundos. La caida del 30% durante 10 segundos o mas, acompa&#241;ada de desaturacion o de microdespertar, define la hipopnea.', dificultad: 'intermedio' },
  { q: 'Por que un mismo registro puede dar indices distintos segun la regla que se aplique?', options: ['Porque hay dos definiciones de hipopnea', 'Porque el flujo se mide de dos maneras', 'Porque las fases del sue&#241;o se puntuan distinto', 'Porque el esfuerzo se registra de dos formas'], correct: 0, explanation: 'La regla recomendada exige una desaturacion del 3% o un microdespertar; la alternativa exige una del 4%. Con la segunda salen indices mas bajos y algunos pacientes sintomaticos quedan por debajo del umbral. Ante un informe que no cuadra con la clinica, hay que mirar que regla se uso.', dificultad: 'dificil' },
  { q: 'Que indice de apnea-hipopnea define la apnea obstructiva GRAVE?', options: ['Mayor de 15 por hora', 'Mayor de 20 por hora', 'Mayor de 30 por hora', 'Mayor de 45 por hora'], correct: 2, explanation: 'Las tres franjas son 5 a 15 leve, 15 a 30 moderada y por encima de 30 grave. En la forma grave la CPAP esta indicada con independencia de los sintomas.', dificultad: 'facil' },
  { q: 'Que indice basta para diagnosticar apnea obstructiva en un paciente sin sintomas ni comorbilidad?', options: ['5 o mas por hora', '15 o mas por hora', '10 o mas por hora', '30 o mas por hora'], correct: 1, explanation: 'Con 15 o mas eventos por hora el diagnostico se establece con independencia de los sintomas. Por debajo de esa cifra hace falta un indice de 5 o mas ACOMPA&#209;ADO de sintomas o de comorbilidad relevante.', dificultad: 'intermedio' },
  { q: 'Por que la poligrafia domiciliaria infraestima el indice de apnea-hipopnea?', options: ['Porque no detecta las hipopneas leves', 'Porque el sensor de flujo es menos sensible', 'Porque no registra la posicion corporal', 'Porque divide por el tiempo de registro'], correct: 3, explanation: 'No mide sue&#241;o porque no lleva electroencefalograma, de modo que el denominador incluye el tiempo que el paciente estuvo despierto en la cama. El indice resultante es menor que el que daria una polisomnografia sobre el mismo paciente.', dificultad: 'intermedio' },
  { q: 'En cual de estos pacientes NO debe usarse la poligrafia domiciliaria?', options: ['Un varon obeso con ronquido y apneas presenciadas', 'Una mujer con somnolencia y perimetro cervical alto', 'Un paciente con insuficiencia cardiaca avanzada', 'Un conductor profesional con somnolencia marcada'], correct: 2, explanation: 'La enfermedad cardiorrespiratoria significativa, la sospecha de hipoventilacion, la debilidad neuromuscular, los opioides cronicos, el ictus previo y la sospecha de otro trastorno del sue&#241;o obligan a polisomnografia. En todos ellos el estudio simplificado puede dar un resultado falsamente tranquilizador.', dificultad: 'intermedio' },
  { q: 'Que corresponde ante una poligrafia negativa en un paciente que sigue siendo sospechoso?', options: ['Hacer polisomnografia', 'Dar el alta con consejo higienico', 'Repetir la poligrafia en 6 meses', 'Iniciar CPAP de forma empirica'], correct: 0, explanation: 'Un resultado negativo o no concluyente en un paciente con clinica sugestiva obliga a subir de escalon diagnostico, no a cerrar el caso. Es uno de los errores mas repetidos del tema y deja sin tratar a pacientes sintomaticos.', dificultad: 'intermedio' },
  { q: 'Para que sirve el cuestionario STOP-BANG?', options: ['Para confirmar el diagnostico de apnea', 'Para medir la gravedad de la enfermedad', 'Para descartar la apnea si sale bajo', 'Para priorizar quien se estudia antes'], correct: 3, explanation: 'Es una herramienta de cribado: muy sensible y poco especifica. Sirve para ordenar la lista de espera y para el cribado preoperatorio, pero una puntuacion baja no autoriza a dejar de estudiar a un paciente con clinica sugestiva.', dificultad: 'facil' },
  { q: 'Que significa una escala de Epworth normal en un paciente con ronquido y apneas presenciadas?', options: ['Que la apnea, si existe, sera leve', 'Que NO descarta una apnea grave', 'Que no procede estudiar el sue&#241;o', 'Que la causa es probablemente nasal'], correct: 1, explanation: 'La escala mide el sintoma y se correlaciona mal con el indice de apnea-hipopnea. Muchos pacientes con apnea grave puntuan bajo, sobre todo las mujeres y quienes consultan por fatiga, insomnio o cefalea matutina.', dificultad: 'intermedio' },
  { q: 'Como se presenta con mas frecuencia la apnea obstructiva en la mujer?', options: ['Con fatiga, insomnio y animo bajo', 'Con ronquido muy intenso y apneas', 'Con somnolencia diurna marcada', 'Con nicturia y sudoracion nocturna'], correct: 0, explanation: 'La presentacion atipica, junto con el hecho de que el ronquido se refiere menos, explica que la enfermedad se diagnostique menos y mas tarde en la mujer. Conviene mantener un umbral de sospecha bajo aunque el cuadro no sea el clasico.', dificultad: 'intermedio' },
  { q: 'Cual es el tratamiento de eleccion de la apnea obstructiva grave?', options: ['El dispositivo de avance mandibular', 'La cirugia de la via aerea superior', 'La presion positiva continua', 'La estimulacion del nervio hipogloso'], correct: 2, explanation: 'La CPAP actua como una ferula neumatica que impide el colapso de la faringe. En la forma grave esta indicada con independencia de los sintomas, y las demas opciones se reservan a la intolerancia o a casos seleccionados.', dificultad: 'facil' },
  { q: 'Que se considera habitualmente adherencia adecuada a la CPAP?', options: ['2 horas por noche todas las noches', '6 horas por noche el 50% de las noches', '4 horas por noche el 30% de las noches', '4 horas por noche el 70% de las noches'], correct: 3, explanation: 'Es el umbral que se usa de forma convencional, pero conviene verlo como un minimo administrativo y no como un objetivo: el beneficio aumenta con mas horas de uso, y la adherencia es lo que separa un tratamiento eficaz de un aparato guardado en un armario.', dificultad: 'intermedio' },
  { q: 'Que alternativa tiene mejor evidencia en el paciente que no tolera la CPAP?', options: ['La uvulopalatofaringoplastia', 'El dispositivo de avance mandibular', 'El oxigeno nocturno a bajo flujo', 'El modafinilo en dosis matutina'], correct: 1, explanation: 'Desplaza la mandibula y la lengua hacia delante y amplia el espacio retrogloso. Es la alternativa con mejor respaldo en la apnea leve y moderada y en la intolerancia a la presion positiva. Nunca se abandona el tratamiento sin ofrecer una alternativa.', dificultad: 'intermedio' },
  { q: 'Que NO han demostrado los ensayos aleatorizados sobre la CPAP?', options: ['Que mejore la somnolencia diurna', 'Que mejore la calidad de vida', 'Que reduzca los eventos cardiovasculares', 'Que baje algo la presion arterial'], correct: 2, explanation: 'Los ensayos no encontraron reduccion de eventos cardiovasculares, con dos advertencias importantes: la adherencia media fue baja y se excluyo a los pacientes muy somnolientos, que son probablemente los que mas se benefician. La conclusion practica no es dejar de tratar sino perseguir la adherencia.', dificultad: 'dificil' },
  { q: 'Que obliga a hacer el hallazgo de apneas centrales predominantes?', options: ['Buscar la causa que las produce', 'Iniciar servoventilacion adaptativa', 'Aumentar la presion de la CPAP', 'Repetir el estudio a los 3 meses'], correct: 0, explanation: 'La apnea central no es un diagnostico final sino un signo. Hay que buscar insuficiencia cardiaca, opioides cronicos, lesion del tronco, altitud o el propio tratamiento con presion positiva como responsables.', dificultad: 'intermedio' },
  { q: 'En que situacion esta contraindicada la servoventilacion adaptativa?', options: ['En la apnea central por opioides cronicos', 'En la apnea central de la altitud', 'En la apnea central emergente con CPAP', 'En la fraccion de eyeccion del 45% o menos'], correct: 3, explanation: 'Cuando hay insuficiencia cardiaca con fraccion de eyeccion del 45% o menos y apnea central predominante, un ensayo aleatorizado encontro un aumento de la mortalidad cardiovascular. En ese escenario se optimiza el tratamiento cardiologico en lugar de ventilar con ese modo.', dificultad: 'dificil' },
  { q: 'Cual es la causa mas frecuente de apnea central en la practica clinica?', options: ['El uso cronico de opioides', 'La insuficiencia cardiaca', 'La lesion del tronco encefalico', 'La insuficiencia renal avanzada'], correct: 1, explanation: 'La insuficiencia cardiaca con fraccion de eyeccion reducida es la causa mas comun, seguida de los opioides. El tiempo de circulacion alargado retrasa la informacion que llega a los quimiorreceptores y hace oscilar el sistema, lo que produce el patron creciente-decreciente.', dificultad: 'intermedio' },
  { q: 'Que corresponde ante una apnea central que aparece al iniciar la CPAP?', options: ['Retirar la CPAP de forma inmediata', 'Cambiar a servoventilacion adaptativa', 'Mantener el tratamiento y reevaluar', 'A&#241;adir oxigeno nocturno al circuito'], correct: 2, explanation: 'La forma emergente con el tratamiento se resuelve sola en semanas o meses en la mayoria de los casos. Retirar la CPAP de forma precipitada priva al paciente de un tratamiento que necesita por un fenomeno que suele ser transitorio.', dificultad: 'dificil' },
  { q: 'Que define el sindrome de hipoventilacion-obesidad?', options: ['Obesidad con PaCO2 diurna mayor de 45 mmHg', 'Obesidad con desaturaciones nocturnas repetidas', 'Obesidad con indice de apnea-hipopnea mayor de 30', 'Obesidad con bicarbonato serico mayor de 27 mEq/L'], correct: 0, explanation: 'Hacen falta tres cosas: indice de masa corporal de 30 o mas, PaCO2 en VIGILIA mayor de 45 mmHg y exclusion de otras causas de hipoventilacion. El bicarbonato elevado es una pista de cribado, no un criterio diagnostico.', dificultad: 'intermedio' },
  { q: 'Que aporta un bicarbonato serico por debajo de 27 mEq/L en un paciente obeso?', options: ['Confirma que la apnea es obstructiva pura', 'Hace muy improbable la hipoventilacion', 'Descarta la apnea obstructiva del sue&#241;o', 'Indica que hay compensacion renal activa'], correct: 1, explanation: 'La retencion renal de bicarbonato es la huella de una hipercapnia cronica; si no esta, el sindrome de hipoventilacion-obesidad es muy poco probable y puede evitarse la gasometria. No dice nada, en cambio, sobre la apnea obstructiva, que hay que estudiar aparte.', dificultad: 'intermedio' },
  { q: 'Por que es peligroso poner solo oxigeno a un paciente que hipoventila?', options: ['Porque produce atelectasias por reabsorcion', 'Porque reseca la mucosa y empeora el ronquido', 'Porque impide medir bien la saturacion', 'Porque mejora la saturacion sin ventilar'], correct: 3, explanation: 'El pulsioximetro se normaliza y el equipo se queda tranquilo mientras el CO2 sigue subiendo. Lo que hace falta es presion positiva, no mas oxigeno, y el oxigeno solo se a&#241;ade cuando la ventilacion ya esta asegurada.', dificultad: 'intermedio' },
  { q: 'Que proporcion de pacientes con hipoventilacion-obesidad tiene ademas apnea obstructiva?', options: ['Alrededor del 90%', 'Alrededor del 30%', 'Alrededor del 50%', 'Alrededor del 70%'], correct: 0, explanation: 'La coexistencia es la norma y explica que en la mayoria de estos pacientes la CPAP baste como soporte inicial. Se reserva la ventilacion con dos niveles de presion para los casos en que predomina la hipoventilacion o la CPAP no corrige la hipercapnia.', dificultad: 'dificil' },
  { q: 'De que es la apnea obstructiva la causa identificable mas frecuente?', options: ['De la fibrilacion auricular de novo', 'Del ictus criptogenico del adulto joven', 'De la hipertension arterial resistente', 'De la miocardiopatia dilatada idiopatica'], correct: 2, explanation: 'Por eso hay que buscarla de forma activa ante una hipertension que no se controla con tres farmacos, uno de ellos diuretico, antes de seguir a&#241;adiendo tratamiento. La monitorizacion ambulatoria suele mostrar ausencia del descenso nocturno de la presion.', dificultad: 'intermedio' },
  { q: 'Que medida reduce el riesgo respiratorio posoperatorio en el paciente con apnea?', options: ['Sedar de forma profunda para evitar la agitacion', 'Extubar en decubito supino estricto', 'Retirar la CPAP durante todo el ingreso', 'Minimizar opioides con analgesia multimodal'], correct: 3, explanation: 'Los opioides deprimen el impulso ventilatorio y el tono de los musculos dilatadores de la faringe justo cuando el rebote de sue&#241;o REM concentra los eventos. A ello se suman extubar despierto y en semiincorporado, mantener la CPAP del paciente y prolongar la monitorizacion de la saturacion.', dificultad: 'intermedio' },
  { q: 'Que hay que preguntar de forma sistematica a todo paciente con sospecha de apnea?', options: ['Cuantas almohadas usa para dormir', 'Si se ha dormido conduciendo', 'Si ronca en decubito lateral', 'Cuanto cafe toma por la tarde'], correct: 1, explanation: 'Es la consecuencia con mayor riesgo inmediato, para el paciente y para terceros. Hay que preguntarlo de forma explicita, dar el consejo de no conducir mientras la somnolencia no este controlada y dejarlo documentado en la historia.', dificultad: 'facil' },
  { q: 'Que sintoma nocturno se atribuye casi siempre a la prostata y mejora al tratar la apnea?', options: ['La sudoracion nocturna profusa', 'El reflujo gastroesofagico', 'La nicturia repetida', 'Los calambres en las piernas'], correct: 2, explanation: 'Las oscilaciones de la presion intratoracica aumentan la liberacion de peptido natriuretico auricular y con ella la diuresis nocturna. Es un sintoma muy infravalorado que mejora de forma llamativa con el tratamiento.', dificultad: 'dificil' },
  { q: 'Que grupo de farmacos agrava los eventos obstructivos por relajacion faringea?', options: ['Las benzodiacepinas', 'Los inhibidores de la bomba de protones', 'Los antagonistas del calcio', 'Los inhibidores de la enzima convertidora'], correct: 0, explanation: 'Junto con el alcohol y los relajantes musculares, reducen el tono de los musculos dilatadores de la faringe y prolongan los eventos. Revisar la medicacion es una de las intervenciones mas rentables y mas olvidadas de este tema.', dificultad: 'facil' },
  { q: 'Que papel tienen los farmacos para la obesidad en la apnea obstructiva?', options: ['Sustituyen a la CPAP en la apnea grave', 'Actuan dilatando la via aerea superior', 'Estan indicados solo tras la cirugia', 'Reducen el indice como coadyuvantes'], correct: 3, explanation: 'La tirzepatida demostro en un ensayo aleatorizado una reduccion del indice de apnea-hipopnea en pacientes con obesidad. Actuan a traves de la perdida de peso, y por eso son un coadyuvante que se suma al tratamiento con presion positiva y no lo reemplaza.', dificultad: 'intermedio' },
  { q: 'Que causa endocrina reversible puede producir o agravar la apnea obstructiva?', options: ['El hiperparatiroidismo primario', 'El hipotiroidismo', 'La insuficiencia suprarrenal', 'El sindrome de Cushing'], correct: 1, explanation: 'Produce macroglosia, edema de las partes blandas faringeas y reduccion del impulso ventilatorio. Es una de las pocas causas corregibles y merece descartarse ante un cuadro que no encaja del todo con la anatomia del paciente.', dificultad: 'intermedio' },

  { type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 54 a&#241;os que consulta traido por su pareja. Ronca fuerte, se le oye desde otra habitacion, y ella ha observado pausas respiratorias. Refiere cansancio durante el dia. Esta en tratamiento por hipertension arterial. Indice de masa corporal de 33 y perimetro cervical de 44 cm. No tiene otras enfermedades.',
    steps: [
      { q: 'Cuantos puntos suma en el cuestionario STOP-BANG?', options: ['5 de 8 puntos', '6 de 8 puntos', '7 de 8 puntos', '8 de 8 puntos'], correct: 2 },
      { q: 'Que estudio corresponde pedir en primer lugar?', options: ['Poligrafia respiratoria domiciliaria', 'Polisomnografia en laboratorio', 'Oximetria nocturna aislada', 'Prueba de latencias multiples de sue&#241;o'], correct: 0 },
      { q: 'La poligrafia registra 240 eventos en 6.4 horas. Que resultado es?', options: ['Alrededor de 25 por hora, moderada', 'Alrededor de 30 por hora, moderada', 'Alrededor de 45 por hora, grave', 'Alrededor de 37 por hora, grave'], correct: 3 }
    ],
    explanation: 'Suma 7 de 8: ronquido, cansancio, apneas observadas, hipertension, edad mayor de 50, perimetro cervical mayor de 40 y sexo masculino; no suma el indice de masa corporal, que no llega a 35. Es riesgo alto. Al no tener comorbilidad cardiorrespiratoria ni sospecha de hipoventilacion, la poligrafia domiciliaria es apropiada. Con 240 eventos en 6.4 horas el indice es de 37.5 por hora, es decir apnea GRAVE, y corresponde CPAP con independencia de los sintomas. Y como es una poligrafia, el indice real es probablemente aun mayor.' },

  { type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 58 a&#241;os con indice de masa corporal de 46. Consulta por somnolencia diurna intensa, cefalea al despertar que le cede en una hora y edemas en las piernas. Toma zolpidem para dormir desde hace a&#241;os. Saturacion basal del 91% respirando aire ambiente.',
    steps: [
      { q: 'Que prueba de laboratorio simple orienta primero el diagnostico?', options: ['La hormona tiroestimulante', 'El bicarbonato serico', 'El peptido natriuretico', 'El hemograma completo'], correct: 1 },
      { q: 'El bicarbonato resulta de 32 mEq/L. Que corresponde ahora?', options: ['Iniciar CPAP domiciliaria de inmediato', 'Repetir el bicarbonato en un mes', 'Pedir poligrafia respiratoria domiciliaria', 'Hacer gasometria arterial despierta'], correct: 3 },
      { q: 'La PaCO2 es de 54 mmHg con pH de 7.36. Que NO debe hacerse?', options: ['Dejarla solo con oxigeno domiciliario', 'Iniciar presion positiva nocturna', 'Retirar el hipnotico que estaba tomando', 'Iniciar un programa de perdida de peso'], correct: 0 }
    ],
    explanation: 'La cefalea matutina y la somnolencia en una paciente con obesidad extrema obligan a pensar en hipoventilacion. El bicarbonato es el cribado barato: por debajo de 27 mEq/L la hace muy improbable, y de 27 o mas obliga a confirmar con gasometria arterial DESPIERTA y respirando aire ambiente. Con indice de masa corporal de 46 y PaCO2 de 54 mmHg sin otra causa, se cumplen los criterios del sindrome de hipoventilacion-obesidad. El error clasico es dejarla solo con oxigeno: corrige el numero del pulsioximetro sin corregir la ventilacion y puede agravar la hipercapnia. Lo que hace falta es presion positiva, retirar el hipnotico y perder peso.' },

  { type: 'cascade', dificultad: 'dificil',
    vignette: 'Varon de 67 a&#241;os con miocardiopatia dilatada y fraccion de eyeccion del 30%. Refiere despertares frecuentes y sue&#241;o poco reparador. En la polisomnografia predominan eventos sin esfuerzo toracoabdominal, con un patron respiratorio creciente y decreciente separado por pausas.',
    steps: [
      { q: 'Que patron respiratorio describe el estudio?', options: ['Respiracion de Cheyne-Stokes', 'Respiracion de Kussmaul', 'Respiracion de Biot', 'Respiracion paradojica'], correct: 0 },
      { q: 'Que prueba hay que tener antes de decidir el tratamiento?', options: ['Una gasometria arterial diurna', 'Una espirometria con broncodilatador', 'Un ecocardiograma', 'Una resonancia del tronco encefalico'], correct: 2 },
      { q: 'Con esa fraccion de eyeccion, que modo esta CONTRAINDICADO?', options: ['La CPAP a presion fija', 'La servoventilacion adaptativa', 'La oxigenoterapia nocturna', 'La ventilacion con dos niveles'], correct: 1 }
    ],
    explanation: 'La ausencia de esfuerzo con patron creciente-decreciente es la respiracion de Cheyne-Stokes, tipica de la insuficiencia cardiaca con fraccion de eyeccion reducida, donde el tiempo de circulacion alargado hace oscilar el control de la ventilacion. El ecocardiograma no es un complemento sino el dato que decide: con fraccion de eyeccion del 45% o menos y apnea central predominante, la servoventilacion adaptativa esta CONTRAINDICADA porque un ensayo aleatorizado encontro aumento de la mortalidad cardiovascular. El tratamiento es optimizar la insuficiencia cardiaca, con CPAP como primer escalon si se decide dar soporte.' },

  { type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 49 a&#241;os con apnea obstructiva grave, en tratamiento con CPAP desde hace 3 meses. Acude a revision y sigue igual de somnoliento que antes de empezar.',
    steps: [
      { q: 'Que es lo primero que hay que mirar?', options: ['La presion prescrita en el equipo', 'La necesidad de cambiar a dos niveles', 'La posibilidad de narcolepsia asociada', 'La descarga de datos de uso y fugas'], correct: 3 },
      { q: 'Usa el equipo 2.5 horas por noche. Ante que problema estamos?', options: ['Un fracaso terapeutico del dispositivo', 'Un problema de adherencia', 'Una presion insuficiente para su indice', 'Una apnea central emergente'], correct: 1 },
      { q: 'Que intervencion tiene mas probabilidad de mejorarlo?', options: ['Subir la presion de forma empirica', 'A&#241;adir un farmaco para la somnolencia', 'Revisar mascarilla, fugas y nariz', 'Cambiar a dispositivo de avance mandibular'], correct: 2 }
    ],
    explanation: 'Ante una CPAP que no funciona, lo primero es la descarga de datos: horas de uso, fugas e indice residual de eventos. Distingue dos problemas que se parecen y se resuelven de forma distinta: el fracaso terapeutico real (usa el equipo y sigue teniendo eventos) y el no uso. Con 2.5 horas por noche estamos en el segundo. Subir la presion o a&#241;adir un farmaco no arregla un equipo que no se usa: lo que mas rinde es trabajar la interfaz (mascarilla, humidificacion, fugas) y tratar la obstruccion nasal, y hacerlo pronto, porque la mayoria de los abandonos ocurren en las primeras semanas.' },

  { type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 62 a&#241;os programado para protesis total de rodilla. Indice de masa corporal de 36 y perimetro cervical de 43 cm. Ronca fuerte y se siente cansado durante el dia. Esta en tratamiento por hipertension arterial. Duerme solo, de modo que nadie ha podido observar si hace pausas.',
    steps: [
      { q: 'Cuantos puntos suma en el cuestionario STOP-BANG?', options: ['5 de 8 puntos', '6 de 8 puntos', '7 de 8 puntos', '4 de 8 puntos'], correct: 2 },
      { q: 'Que significa esa puntuacion en este contexto?', options: ['Riesgo alto de apnea moderada o grave', 'Diagnostico de apnea obstructiva grave', 'Riesgo bajo por no haber apneas observadas', 'Indicacion directa de CPAP preoperatoria'], correct: 0 },
      { q: 'Que medida perioperatoria corresponde?', options: ['Sedacion profunda para evitar la agitacion posoperatoria', 'Extubacion en decubito supino estricto', 'Analgesia con opioides a dosis plenas', 'Analgesia multimodal y vigilancia prolongada'], correct: 3 }
    ],
    explanation: 'Suma 7 de 8: no puntua el item de apneas observadas porque duerme solo, pero si el resto. Es riesgo alto de apnea moderada o grave, no un diagnostico: eso lo dara el estudio de sue&#241;o. En el perioperatorio, esa puntuacion cambia la conducta: analgesia multimodal para reducir opioides, extubacion despierto y en semiincorporado, monitorizacion prolongada de la saturacion y, si el paciente ya usa CPAP, que la lleve al hospital. En cirugia programada no urgente puede valorarse retrasarla para completar el estudio.' },

  { type: 'cascade', dificultad: 'facil',
    vignette: 'Conductor profesional de 45 a&#241;os, indice de masa corporal de 31, que ronca. En la escala de Epworth puntua: 2 leyendo, 2 viendo la television, 1 sentado inactivo en un lugar publico, 3 como pasajero en un coche durante una hora, 3 tumbado por la tarde, 1 charlando, 2 despues de comer y 2 detenido en el trafico.',
    steps: [
      { q: 'Que puntuacion total resulta y que significa?', options: ['12 puntos: somnolencia leve', '16 puntos: somnolencia moderada', '16 puntos: dentro de lo normal', '20 puntos: somnolencia grave'], correct: 1 },
      { q: 'Que dato de esa escala preocupa mas de forma inmediata?', options: ['Que puntue alto tumbado por la tarde', 'Que puntue alto viendo la television', 'Que la suma supere el umbral de 10', 'Que puntue alto dentro de un coche'], correct: 3 },
      { q: 'Que corresponde hacer, ademas de completar el estudio?', options: ['Aconsejar no conducir y DOCUMENTARLO', 'Iniciar un estimulante de la vigilia', 'Recomendar siestas antes de conducir', 'Repetir la escala dentro de 6 meses'], correct: 0 }
    ],
    explanation: 'La suma es 16 sobre 24, que corresponde a somnolencia moderada: el umbral de somnolencia diurna excesiva esta por encima de 10. Lo que mas preocupa no es la cifra global sino que puntue alto en las dos situaciones dentro de un coche, en un conductor profesional. Ademas de completar el estudio del sue&#241;o, corresponde dar consejo explicito de no conducir mientras la somnolencia no este controlada y dejarlo documentado en la historia. Antes de atribuirlo todo a la apnea hay que descartar la causa mas frecuente de somnolencia, que es el sue&#241;o insuficiente por habitos o por turnos.' }
];

export const flashcards = [
  { front: 'La pregunta que separa obstructivo de central', back: 'Si HAY esfuerzo respiratorio: obstructivo. Si no lo hay: central.' },
  { front: 'Definicion de apnea', back: 'Caida del flujo del 90% o mas durante 10 segundos o mas.' },
  { front: 'Definicion de hipopnea', back: 'Caida del 30% o mas durante 10 s o mas, con desaturacion o microdespertar.' },
  { front: 'Las dos reglas de hipopnea', back: 'Desaturacion del 3% o microdespertar (recomendada) frente a desaturacion del 4%.' },
  { front: 'Gravedad por indice de apnea-hipopnea', back: 'Leve 5 a 15; moderada 15 a 30; GRAVE por encima de 30.' },
  { front: 'Criterio diagnostico de apnea obstructiva', back: 'Indice de 5 o mas CON sintomas o comorbilidad, o de 15 o mas sin ellos.' },
  { front: 'Por que la poligrafia infraestima el indice', back: 'Divide por el tiempo de REGISTRO y no por el tiempo dormido: no mide sue&#241;o.' },
  { front: 'Cuando NO vale la poligrafia domiciliaria', back: 'Cardiorrespiratoria significativa, hipoventilacion, neuromuscular, opioides, ictus, otro trastorno del sue&#241;o.' },
  { front: 'Poligrafia negativa en paciente sospechoso', back: 'POLISOMNOGRAFIA, no el alta. Es uno de los errores mas repetidos.' },
  { front: 'Para que sirve el STOP-BANG', back: 'Para CRIBAR y priorizar. No confirma ni descarta la enfermedad.' },
  { front: 'Items del STOP-BANG', back: 'Ronquido, cansancio, apneas observadas, presion arterial; IMC, edad, cuello, sexo.' },
  { front: 'Umbrales del STOP-BANG', back: '0 a 2 riesgo bajo; 3 a 4 intermedio; 5 a 8 riesgo alto.' },
  { front: 'Escala de Epworth', back: '8 situaciones de 0 a 3; por encima de 10, somnolencia diurna excesiva.' },
  { front: 'Epworth normal en un paciente sospechoso', back: 'NO descarta una apnea grave: mide el sintoma, no la enfermedad.' },
  { front: 'Presentacion de la apnea en la mujer', back: 'Fatiga, insomnio, animo bajo y cefalea, mas que somnolencia clasica.' },
  { front: 'Tratamiento de eleccion en apnea moderada y grave', back: 'CPAP, que actua como ferula neumatica de la faringe.' },
  { front: 'Adherencia adecuada a la CPAP', back: '4 horas o mas por noche el 70% de las noches, como MINIMO.' },
  { front: 'Alternativa si no tolera la CPAP', back: 'Dispositivo de avance mandibular, que es la de mejor evidencia.' },
  { front: 'Lo que la CPAP SI ha demostrado', back: 'Mejora somnolencia, calidad de vida y cognicion; baja algo la presion arterial.' },
  { front: 'Lo que la CPAP NO ha demostrado', back: 'Reducir eventos cardiovasculares en ensayos aleatorizados (adherencia baja).' },
  { front: 'Contraindicacion de la estimulacion del hipogloso', back: 'El colapso concentrico completo del velo del paladar.' },
  { front: 'Apnea central: que significa', back: 'Es un SIGNO, no un diagnostico: obliga a buscar la causa.' },
  { front: 'Causas de apnea central', back: 'Insuficiencia cardiaca, opioides, ictus, altitud y la emergente con el tratamiento.' },
  { front: 'Contraindicacion de la servoventilacion adaptativa', back: 'Fraccion de eyeccion del 45% o menos con apnea central predominante.' },
  { front: 'Apnea central emergente con la CPAP', back: 'Suele resolverse sola en semanas o meses: no retirar la CPAP.' },
  { front: 'Criterios de hipoventilacion-obesidad', back: 'IMC de 30 o mas, PaCO2 DESPIERTO mayor de 45 mmHg y exclusion de otras causas.' },
  { front: 'El cribado barato de la hipoventilacion', back: 'Bicarbonato serico: por debajo de 27 mEq/L la hace muy improbable.' },
  { front: 'El error que mata en la hipoventilacion', back: 'Poner OXIGENO SOLO: sube la saturacion sin corregir la ventilacion.' },
  { front: 'Apnea obstructiva asociada al sindrome de hipoventilacion', back: 'La tiene alrededor del 90%, casi siempre grave.' },
  { front: 'Causa identificable mas frecuente de hipertension resistente', back: 'La apnea obstructiva del sue&#241;o.' },
  { front: 'Perioperatorio del paciente con apnea', back: 'Cribar, minimizar opioides, extubar despierto y semiincorporado, monitorizar mas.' },
  { front: 'La pregunta que no se puede olvidar', back: 'Si se ha dormido conduciendo. Aconsejar y DOCUMENTARLO.' }
];

export default { quiz, flashcards };
