// topics/neoplasias-snc-hipertension-intracraneal/study.js: Autoevaluación de Neoplasias del SNC
// e Hipertensión Intracraneal.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Nota de método (ver memoria del proyecto): todas las preguntas se escribieron primero con la
// respuesta correcta en options[0]/correct:0 (trivialmente verificable), y luego se redistribuyó
// la posición de `correct` mecánicamente con un script, sin volver a adivinar cuál texto es el
// correcto. Cada pregunta se releyó completa (options+correct+explanation) tras la
// redistribución para confirmar que options[correct] es realmente la respuesta correcta.

export const quiz = [
  { q: '¿Qué comparten las neoplasias del SNC y la hipertensión intracraneal como desenlace común?', options: ['Ambas son siempre benignas y de curso indolente', 'Ninguna de las dos afecta jamás el estado de alerta del paciente', 'El aumento de la presión dentro de un compartimento craneal rígido de volumen fijo (Monro-Kellie)', 'Ambas ocurren exclusivamente en la población pediátrica'], correct: 2, explanation: 'Ambas comparten el desenlace común del aumento de presión dentro de un compartimento craneal rígido de volumen fijo, según la doctrina de Monro-Kellie.', dificultad: 'facil' },
  { q: '¿Qué distingue fundamentalmente a la hipertensión intracraneal idiopática de las 3 entidades tumorales de este tema?', options: ['Es la única de las 4 entidades que produce papiledema', 'La presión se eleva SIN ninguna lesión estructural identificable', 'Es la única que ocurre en mujeres', 'Es la única que puede causar cefalea'], correct: 1, explanation: 'A diferencia de las 3 entidades tumorales, en la hipertensión intracraneal idiopática la presión se eleva sin ninguna lesión estructural identificable.', dificultad: 'facil' },
  { q: '¿Cuál es más frecuente en conjunto: las metástasis cerebrales o todos los tumores primarios del SNC combinados?', options: ['Las metástasis cerebrales son más frecuentes que todos los tumores primarios combinados', 'Los tumores primarios son siempre más frecuentes que las metástasis', 'Ambos grupos tienen exactamente la misma frecuencia', 'Las metástasis cerebrales son extremadamente infrecuentes en la práctica clínica'], correct: 0, explanation: 'Las metástasis cerebrales son, en conjunto, más frecuentes que todos los tumores primarios del SNC combinados.', dificultad: 'intermedio' },
  { q: '¿Cuál es el tumor primario del sistema nervioso central más frecuente en general?', options: ['Glioblastoma', 'Metástasis cerebral', 'Astrocitoma difuso de bajo grado', 'Meningioma'], correct: 3, explanation: 'El meningioma es el tumor primario del SNC más frecuente en general, habitualmente benigno.', dificultad: 'facil' },
  { q: '¿Por qué el meningioma con frecuencia permanece asintomático durante años?', options: ['Nunca produce ningún efecto de masa en ninguna circunstancia', 'Siempre se localiza fuera del cráneo', 'Es extraaxial y comprime el parénquima adyacente por efecto de masa progresivo en lugar de infiltrarlo', 'Es indistinguible de tejido cerebral normal en cualquier estudio'], correct: 2, explanation: 'Al ser extraaxial, el meningioma comprime el parénquima adyacente progresivamente en lugar de infiltrarlo, lo que explica por qué muchos permanecen asintomáticos por años.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo radiológico característico apoya el diagnóstico de meningioma en la resonancia magnética?', options: ['Signo de la cola dural (realce lineal de la duramadre adyacente)', 'Necrosis central con realce en anillo irregular', 'Localización exclusiva en la unión sustancia gris-blanca', 'Ausencia completa de cualquier realce con contraste'], correct: 0, explanation: 'El signo de la cola dural (realce lineal de la duramadre adyacente al tumor) es un hallazgo característico que apoya el diagnóstico de meningioma.', dificultad: 'intermedio' },
  { q: '¿Cuál es el tumor maligno primario del sistema nervioso central más frecuente en adultos?', options: ['Meningioma', 'Glioblastoma', 'Metástasis cerebral', 'Craneofaringioma'], correct: 1, explanation: 'El glioblastoma es el tumor maligno primario del SNC más frecuente en adultos y uno de los tumores sólidos de peor pronóstico en oncología.', dificultad: 'facil' },
  { q: '¿Por qué es particularmente difícil lograr una resección completa de un glioma?', options: ['Siempre se localiza en una zona inaccesible quirúrgicamente', 'Está completamente encapsulado y no puede tocarse quirúrgicamente', 'No existe ninguna técnica quirúrgica aplicable a este tumor', 'Es intraaxial e infiltra el propio tejido cerebral, careciendo de un margen bien definido'], correct: 3, explanation: 'El glioma es intraaxial e infiltra el propio tejido cerebral sin un margen bien definido, lo que explica la dificultad de la resección completa y la inevitabilidad de la recurrencia local.', dificultad: 'intermedio' },
  { q: '¿Qué marcador molecular predice una mayor respuesta a temozolomida en el glioblastoma?', options: ['Codeleción 1p/19q exclusivamente', 'Ausencia total de cualquier mutación', 'Metilación del promotor de MGMT', 'Sobreexpresión de receptores de progesterona'], correct: 2, explanation: 'La metilación del promotor de MGMT silencia la reparación del daño inducido por temozolomida, prediciendo una mayor respuesta al fármaco.', dificultad: 'dificil' },
  { q: '¿Cuál es el esquema estándar de tratamiento del glioblastoma tras la resección quirúrgica máxima segura?', options: ['Observación exclusiva sin ningún tratamiento adicional', 'Quimioterapia sistémica sin ningún componente de radioterapia', 'Trasplante de médula ósea', 'Radioterapia con temozolomida concurrente, seguida de temozolomida de mantenimiento (esquema de Stupp)'], correct: 3, explanation: 'El esquema de Stupp (radioterapia con temozolomida concurrente, seguida de temozolomida de mantenimiento) es el estándar tras la resección máxima segura del glioblastoma.', dificultad: 'intermedio' },
  { q: '¿Cuáles son las 3 fuentes primarias más frecuentes de metástasis cerebrales?', options: ['Próstata, colon, y riñón exclusivamente', 'Pulmón, mama, y melanoma', 'Únicamente tumores hematológicos', 'Páncreas, estómago, y esófago exclusivamente'], correct: 1, explanation: 'El pulmón, la mama, y el melanoma son las fuentes primarias más frecuentes de metástasis cerebrales.', dificultad: 'facil' },
  { q: '¿Por qué las metástasis cerebrales tienen predilección por la unión de la sustancia gris-blanca?', options: ['El calibre vascular se reduce abruptamente en esa zona, favoreciendo el atrapamiento de émbolos tumorales', 'Esa zona carece por completo de irrigación sanguínea', 'Las células tumorales evitan activamente esa localización', 'No existe ninguna predilección real por esa localización'], correct: 0, explanation: 'El calibre vascular se reduce abruptamente en la unión sustancia gris-blanca, favoreciendo el atrapamiento de émbolos tumorales circulantes en esa localización.', dificultad: 'dificil' },
  { q: '¿Cuáles son los criterios diagnósticos centrales de la hipertensión intracraneal idiopática (pseudotumor cerebri)?', options: ['Una masa cerebral claramente visible en la resonancia magnética', 'Ausencia completa de cefalea o cualquier síntoma neurológico', 'Papiledema, examen neurológico normal salvo paresia del VI par, presión de apertura elevada con LCR normal, y neuroimagen sin lesión estructural', 'Un nivel de glucosa en LCR marcadamente elevado'], correct: 2, explanation: 'Los criterios centrales son papiledema, examen neurológico normal salvo paresia del VI par, presión de apertura elevada con LCR citoquímico normal, y neuroimagen sin lesión estructural, hidrocefalia, ni trombosis venosa.', dificultad: 'intermedio' },
  { q: '¿En qué población ocurre característicamente la hipertensión intracraneal idiopática?', options: ['Mujeres en edad reproductiva con obesidad', 'Hombres de edad avanzada con bajo peso', 'Exclusivamente lactantes menores de 1 año', 'Exclusivamente pacientes con cáncer sistémico conocido'], correct: 0, explanation: 'La hipertensión intracraneal idiopática ocurre predominantemente en mujeres en edad reproductiva con obesidad.', dificultad: 'facil' },
  { q: '¿Cuál es el tratamiento farmacológico de primera línea para la hipertensión intracraneal idiopática?', options: ['Dexametasona en dosis altas', 'Fenitoína', 'Warfarina', 'Acetazolamida'], correct: 3, explanation: 'La acetazolamida, un inhibidor de la anhidrasa carbónica que reduce la producción de LCR, es el tratamiento farmacológico de primera línea.', dificultad: 'facil' },
  { q: '¿Qué estudio debe realizarse ANTES de una punción lumbar en la sospecha de hipertensión intracraneal idiopática, y por qué?', options: ['Electroencefalograma, para descartar epilepsia concomitante', 'Resonancia magnética con venografía, para descartar lesión estructural y trombosis de senos venosos', 'Radiografía simple de cráneo, que es suficiente para descartar cualquier causa secundaria', 'Ningún estudio previo es necesario en ningún caso'], correct: 1, explanation: 'La resonancia magnética con venografía debe realizarse antes de la punción lumbar para descartar lesión estructural y trombosis de senos venosos, ambas causas secundarias que deben excluirse primero.', dificultad: 'intermedio' },
  { q: '¿Cuál es la diferencia fundamental entre el edema vasogénico peritumoral y el edema citotóxico isquémico?', options: ['Ambos tienen exactamente el mismo mecanismo fisiopatológico', 'El citotóxico siempre responde mejor a corticoides que el vasogénico', 'El vasogénico se produce por disrupción de la barrera hematoencefálica; el citotóxico por falla de la bomba Na+/K+ con la barrera intacta', 'El vasogénico solo ocurre en la sustancia gris, nunca en la blanca'], correct: 2, explanation: 'El edema vasogénico se produce por disrupción de la barrera hematoencefálica (permitiendo la extravasación de líquido), mientras que el citotóxico isquémico ocurre con la barrera intacta pero con falla de la bomba de sodio-potasio neuronal.', dificultad: 'dificil' },
  { q: '¿Por qué el edema peritumoral responde bien a los corticoides mientras que el edema citotóxico isquémico no?', options: ['Los corticoides restauran parcialmente la integridad de la barrera hematoencefálica rota, mecanismo ausente en el edema citotóxico', 'Los corticoides no tienen ningún efecto real sobre ningún tipo de edema cerebral', 'El edema citotóxico siempre es más pequeño y por eso no requiere tratamiento', 'Ambos tipos de edema responden exactamente igual a los corticoides'], correct: 0, explanation: 'Los corticoides restauran parcialmente la integridad de la barrera hematoencefálica rota en el edema vasogénico, un mecanismo que no aplica al edema citotóxico isquémico (barrera intacta).', dificultad: 'dificil' },
  { q: '¿Cuál es el fármaco de elección para el edema peritumoral sintomático?', options: ['Insulina en infusión continua', 'Heparina de bajo peso molecular', 'Furosemida en dosis altas', 'Dexametasona'], correct: 3, explanation: 'La dexametasona es el corticoide de elección para el tratamiento del edema vasogénico peritumoral sintomático.', dificultad: 'facil' },
  { q: '¿Se recomienda la profilaxis anticonvulsivante primaria de rutina en el paciente con tumor cerebral recién diagnosticado sin crisis previa?', options: ['Sí, está indicada en absolutamente todos los pacientes con tumor cerebral', 'No, no está recomendada de rutina sin historia de crisis previa', 'Solo se recomienda en pacientes pediátricos con tumor cerebral', 'Solo se recomienda si el tumor es un meningioma'], correct: 1, explanation: 'La profilaxis anticonvulsivante primaria NO está recomendada de rutina en el paciente sin historia de crisis previa; el tratamiento se inicia tras la primera crisis ya ocurrida.', dificultad: 'intermedio' },
  { q: '¿Por qué se prefiere levetiracetam sobre los anticonvulsivantes inductores enzimáticos más antiguos en el paciente con tumor cerebral?', options: ['Tiene un perfil favorable de interacciones farmacológicas, relevante dado el uso concomitante frecuente de quimioterapia', 'Es el único anticonvulsivante capaz de controlar cualquier tipo de crisis', 'No tiene ningún efecto adverso conocido', 'Es el único aprobado para uso en el sistema nervioso central'], correct: 0, explanation: 'Levetiracetam se prefiere por su perfil favorable de interacciones farmacológicas, dado que los inductores enzimáticos más antiguos pueden alterar el metabolismo de agentes quimioterapéuticos.', dificultad: 'intermedio' },
  { q: '¿Qué localizaciones tumorales predisponen particularmente a hidrocefalia obstructiva?', options: ['Exclusivamente la corteza cerebral frontal', 'Exclusivamente el lóbulo temporal', 'Fosa posterior, tercer ventrículo, y acueducto de Silvio', 'Cualquier localización tiene el mismo riesgo de hidrocefalia obstructiva'], correct: 2, explanation: 'Los tumores de la fosa posterior, el tercer ventrículo, y el acueducto de Silvio predisponen particularmente a hidrocefalia obstructiva por su ubicación en puntos estratégicos de la circulación del LCR.', dificultad: 'intermedio' },
  { q: '¿Cuál es la medida temporal urgente ante hidrocefalia aguda con deterioro del estado de alerta?', options: ['Observación sin ninguna intervención', 'Anticoagulación terapéutica', 'Punción lumbar diagnóstica de rutina', 'Derivación ventricular externa'], correct: 3, explanation: 'La derivación ventricular externa es la medida temporal urgente ante hidrocefalia aguda con deterioro del estado de alerta.', dificultad: 'facil' },
  { q: '¿El papiledema por hipertensión intracraneal crónica es característicamente unilateral o bilateral?', options: ['Unilateral, siempre del lado del tumor', 'Bilateral', 'Unilateral, siempre contralateral al tumor', 'No tiene ningún patrón de lateralidad reconocible'], correct: 1, explanation: 'El papiledema por hipertensión intracraneal crónica es característicamente bilateral, a diferencia de otras causas de edema del disco óptico unilateral.', dificultad: 'facil' },
  { q: '¿Por qué la presión intracraneal elevada se transmite al nervio óptico produciendo papiledema?', options: ['El nervio óptico no tiene ninguna relación anatómica con el espacio subaracnoideo', 'El papiledema se produce por un mecanismo infeccioso directo del nervio óptico', 'La presión intracraneal nunca afecta estructuras oculares de ningún tipo', 'El espacio subaracnoideo intracraneal es continuo con el espacio que rodea al nervio óptico dentro de su vaina'], correct: 3, explanation: 'El espacio subaracnoideo intracraneal es continuo con el espacio que rodea al nervio óptico dentro de su vaina, permitiendo la transmisión directa de la presión elevada.', dificultad: 'dificil' },
  { q: '¿Cuál es el estudio de seguimiento más importante para detectar el daño funcional temprano por papiledema y guiar el tratamiento?', options: ['Electrocardiograma seriado', 'Radiografía de tórax seriada', 'Campimetría (campos visuales) seriada', 'Perfil lipídico seriado'], correct: 2, explanation: 'La campimetría seriada es el estudio más importante para detectar el daño funcional temprano y guiar la necesidad de escalar el tratamiento.', dificultad: 'intermedio' },
  { q: '¿Cuál es la regla de seguridad crítica antes de realizar una punción lumbar cuando hay sospecha de tumor de fosa posterior?', options: ['La punción lumbar puede realizarse de forma segura sin ningún estudio previo en cualquier caso', 'Obtener neuroimagen previa siempre, dado el riesgo de herniación amigdalina precipitada por el procedimiento', 'Solo se requiere neuroimagen previa en pacientes pediátricos', 'La neuroimagen previa solo es necesaria si el paciente ya tiene síntomas de herniación establecida'], correct: 1, explanation: 'Siempre debe obtenerse neuroimagen previa a la punción lumbar si hay sospecha de tumor de fosa posterior, dado el riesgo de herniación amigdalina precipitada por el procedimiento.', dificultad: 'intermedio' },
  { q: '¿Qué mecanismo explica la herniación amigdalina precipitada por una punción lumbar en un paciente con tumor de fosa posterior no reconocido?', options: ['El gradiente de presión al retirar LCR lumbar puede empujar súbitamente las amígdalas cerebelosas ya comprimidas hacia el foramen magno', 'La punción lumbar nunca puede precipitar ningún tipo de herniación', 'El LCR retirado se reemplaza instantáneamente sin ningún cambio de presión', 'El mecanismo es idéntico al de la herniación uncal por hematoma epidural'], correct: 0, explanation: 'El gradiente de presión creado al retirar LCR desde el espacio lumbar puede empujar súbitamente las amígdalas cerebelosas ya comprimidas hacia el foramen magno, con compresión bulbar y paro respiratorio.', dificultad: 'dificil' },
  { q: '¿Qué escalas cuantifican el estado funcional del paciente oncológico y guían la intensidad del tratamiento que puede tolerar?', options: ['Escala de Coma de Glasgow', 'Score ISTH de CID', 'Karnofsky Performance Status y ECOG', 'Canadian CT Head Rule'], correct: 2, explanation: 'El Karnofsky Performance Status y la escala ECOG cuantifican el estado funcional del paciente oncológico, guiando la intensidad del tratamiento que puede tolerar.', dificultad: 'facil' },
  { q: '¿A partir de qué puntaje de Karnofsky se considera que el paciente generalmente tolera tratamiento oncológico activo?', options: ['≥20', '≥100 exclusivamente', 'El puntaje de Karnofsky no tiene ninguna relación con la tolerancia al tratamiento', '≥70'], correct: 3, explanation: 'Un puntaje de Karnofsky ≥70 (equivalente aproximado a ECOG 0-2) generalmente indica que el paciente tolera tratamiento oncológico activo.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 55 años, hallazgo incidental en RM (solicitada por otra razón) de una masa extraaxial de base dural amplia, con realce homogéneo intenso y signo de la cola dural, de 1.5 cm, asintomática.',
    steps: [
      { q: '¿Qué diagnóstico es más probable dado este hallazgo?', options: ['Glioblastoma', 'Meningioma', 'Metástasis cerebral', 'Absceso cerebral'], correct: 1, explanation: 'La masa extraaxial de base dural amplia con realce homogéneo y signo de la cola dural es característica del meningioma.' },
      { q: '¿Por qué es plausible que este tumor haya sido completamente asintomático hasta ahora?', options: ['Es extraaxial y de crecimiento lento, comprimiendo el parénquima progresivamente sin infiltrarlo', 'Es imposible que un meningioma sea asintomático', 'Todos los meningiomas producen síntomas graves desde su inicio', 'Solo los meningiomas malignos pueden ser asintomáticos'], correct: 0, explanation: 'El meningioma es extraaxial y de crecimiento lento, por lo que con frecuencia permanece asintomático durante años antes de producir síntomas por compresión.' },
      { q: 'Dado el tamaño pequeño, la ausencia de síntomas, y la edad de la paciente, ¿cuál es el manejo inicial más apropiado?', options: ['Resección quirúrgica de urgencia inmediata', 'Observación con resonancia magnética seriada', 'Quimioterapia sistémica', 'Radioterapia holocraneal inmediata'], correct: 1, explanation: 'En el meningioma pequeño y asintomático, la observación con imagen seriada es el manejo inicial apropiado, reservando la cirugía para cuando se vuelva sintomático o muestre crecimiento significativo.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 62 años presenta cefalea progresiva de 3 semanas de evolución y una crisis convulsiva de novo. RM muestra una masa intraaxial infiltrante con realce en anillo irregular y necrosis central.',
    steps: [
      { q: '¿Qué diagnóstico es más probable dado este patrón radiológico?', options: ['Meningioma', 'Hipertensión intracraneal idiopática', 'Glioblastoma', 'Absceso cerebral sin ningún otro dato clínico compatible'], correct: 2, explanation: 'El realce en anillo irregular con necrosis central en una masa intraaxial infiltrante es característico del glioblastoma.' },
      { q: '¿Qué estudio adicional del tejido resecado orienta el pronóstico y guía el tratamiento con temozolomida?', options: ['Estado de metilación del promotor de MGMT', 'Cultivo bacteriano de rutina', 'Tinción de Gram', 'Prueba de embarazo'], correct: 0, explanation: 'El estado de metilación del promotor de MGMT predice la respuesta a temozolomida y orienta el pronóstico, siendo parte esencial de la clasificación OMS 2021.' },
      { q: '¿Cuál es el esquema de tratamiento estándar tras la resección quirúrgica máxima segura?', options: ['Observación exclusiva sin tratamiento adicional', 'Quimioterapia oral sin ningún componente de radioterapia', 'Inmunoterapia sistémica como único tratamiento', 'Radioterapia con temozolomida concurrente, seguida de temozolomida de mantenimiento'], correct: 3, explanation: 'El esquema de Stupp (radioterapia con temozolomida concurrente, seguida de temozolomida de mantenimiento) es el estándar tras la resección máxima segura del glioblastoma.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 26 años con IMC 34, presenta cefalea progresiva de 2 meses, oscurecimientos visuales transitorios con los cambios de posición, y papiledema bilateral en el examen de fondo de ojo. Examen neurológico normal salvo leve paresia del VI par derecho.',
    steps: [
      { q: '¿Qué estudios deben realizarse ANTES de considerar una punción lumbar en esta paciente?', options: ['Electroencefalograma exclusivamente', 'Resonancia magnética cerebral con venografía', 'Radiografía simple de cráneo exclusivamente', 'Ningún estudio previo es necesario'], correct: 1, explanation: 'Debe realizarse resonancia magnética con venografía antes de la punción lumbar, para descartar lesión estructural y trombosis de senos venosos como causas secundarias.' },
      { q: 'La RM y venografía son normales, sin lesión estructural, hidrocefalia, ni trombosis. La punción lumbar muestra presión de apertura elevada con LCR citoquímico normal. ¿Qué diagnóstico se establece?', options: ['Meningitis bacteriana aguda', 'Glioma de bajo grado', 'Hipertensión intracraneal idiopática (pseudotumor cerebri)', 'Hidrocefalia obstructiva por tumor de fosa posterior'], correct: 2, explanation: 'Con lesión estructural, hidrocefalia, y trombosis venosa descartadas, y presión de apertura elevada con LCR normal, se cumplen los criterios de hipertensión intracraneal idiopática.' },
      { q: '¿Cuál es el manejo inicial más apropiado en esta paciente?', options: ['Radioterapia holocraneal', 'Resección quirúrgica exploratoria', 'Quimioterapia sistémica', 'Pérdida de peso y acetazolamida'], correct: 3, explanation: 'La pérdida de peso (incluso moderada) y la acetazolamida como tratamiento farmacológico de primera línea son el manejo inicial apropiado.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 68 años con antecedente de cáncer pulmonar conocido presenta cefalea y hemiparesia izquierda progresiva de 1 semana. RM muestra una lesión de 2 cm en la unión sustancia gris-blanca frontal derecha con realce en anillo, rodeada de edema extenso que se extiende considerablemente más allá del tamaño de la lesión.',
    steps: [
      { q: '¿Qué diagnóstico es más probable dado el antecedente oncológico y la localización de la lesión?', options: ['Metástasis cerebral', 'Meningioma', 'Hipertensión intracraneal idiopática', 'Enfermedad de Alzheimer'], correct: 0, explanation: 'La localización en la unión sustancia gris-blanca con realce en anillo, en un paciente con cáncer pulmonar conocido, es característica de una metástasis cerebral.' },
      { q: '¿Qué tipo de edema es este, y por qué es desproporcionadamente extenso respecto al tamaño de la lesión?', options: ['Edema citotóxico isquémico, por falla de la bomba Na+/K+ neuronal', 'Edema vasogénico, por disrupción de la barrera hematoencefálica de la vasculatura tumoral anómala', 'No hay ningún edema real, solo artefacto de imagen', 'Edema por sobrecarga de volumen sistémica'], correct: 1, explanation: 'Es edema vasogénico, producido por la disrupción de la barrera hematoencefálica en la vasculatura tumoral anómala, con frecuencia desproporcionadamente extenso en las metástasis.' },
      { q: 'El paciente presenta somnolencia progresiva por el efecto de masa combinado. ¿Cuál es el tratamiento de elección para el edema mientras se define el manejo oncológico definitivo?', options: ['Heparina de bajo peso molecular', 'Furosemida en dosis altas', 'Antibióticos de amplio espectro', 'Dexametasona'], correct: 3, explanation: 'La dexametasona es el tratamiento de elección para el edema vasogénico peritumoral sintomático, con mejoría clínica frecuentemente notable dentro de horas a 1-2 días.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Niño de 8 años presenta cefalea progresiva peor en las mañanas, vómito matutino recurrente, y ataxia de la marcha de 3 semanas de evolución. Se sospecha tumor de fosa posterior.',
    steps: [
      { q: '¿Qué complicación se debe sospechar dado este cuadro clínico, y qué localización tumoral la explica mejor?', options: ['Meningitis bacteriana aguda no relacionada con ningún tumor', 'Hipertensión intracraneal idiopática, dado que es la causa más frecuente en niños', 'Hidrocefalia obstructiva, por compresión del cuarto ventrículo o el acueducto de Silvio', 'Migraña primaria sin ninguna relación con hallazgos estructurales'], correct: 2, explanation: 'El cuadro de cefalea peor en decúbito/mañanas, vómito matutino, y ataxia sugiere hidrocefalia obstructiva, particularmente por un tumor de fosa posterior que comprime el cuarto ventrículo o el acueducto.' },
      { q: '¿Por qué NO se debe realizar una punción lumbar en este paciente antes de la neuroimagen?', options: ['Riesgo de herniación amigdalina precipitada por el gradiente de presión al retirar LCR lumbar', 'La punción lumbar es completamente segura en cualquier sospecha de tumor de fosa posterior', 'La punción lumbar es el único estudio diagnóstico válido en este contexto', 'No existe ninguna razón real para evitar la punción lumbar en este caso'], correct: 0, explanation: 'La punción lumbar sin neuroimagen previa en sospecha de tumor de fosa posterior conlleva riesgo de herniación amigdalina precipitada por el gradiente de presión al retirar LCR lumbar.' },
      { q: 'Confirmada la hidrocefalia obstructiva con deterioro progresivo, ¿cuál es la medida temporal urgente apropiada?', options: ['Observación domiciliaria sin ninguna intervención', 'Derivación ventricular externa', 'Antibióticos empíricos de amplio espectro', 'Anticoagulación terapéutica'], correct: 1, explanation: 'La derivación ventricular externa es la medida temporal urgente ante hidrocefalia obstructiva con deterioro progresivo, mientras se organiza el tratamiento definitivo del tumor causal.' }
    ]
  }
];

export const flashcards = [
  { front: 'Desenlace común de neoplasia del SNC e hipertensión intracraneal', back: 'Aumento de presión en compartimento craneal rígido (Monro-Kellie).' },
  { front: 'Qué distingue a la hipertensión intracraneal idiopática', back: 'Presión elevada SIN lesión estructural identificable.' },
  { front: '¿Más frecuente: metástasis o tumores primarios del SNC?', back: 'Metástasis, más frecuentes que todos los primarios combinados.' },
  { front: 'Tumor primario del SNC más frecuente en general', back: 'Meningioma.' },
  { front: 'Meningioma: por qué es con frecuencia asintomático', back: 'Extraaxial, comprime progresivamente sin infiltrar.' },
  { front: 'Signo radiológico característico del meningioma', back: 'Signo de la cola dural.' },
  { front: 'Tumor maligno primario del SNC más frecuente en adultos', back: 'Glioblastoma.' },
  { front: 'Por qué el glioma es difícil de resecar completamente', back: 'Es intraaxial, infiltra sin margen definido.' },
  { front: 'Marcador que predice respuesta a temozolomida', back: 'Metilación del promotor de MGMT.' },
  { front: 'Esquema estándar del glioblastoma', back: 'Esquema de Stupp: RT + temozolomida concurrente, luego mantenimiento.' },
  { front: '3 fuentes primarias más frecuentes de metástasis cerebrales', back: 'Pulmón, mama, melanoma.' },
  { front: 'Por qué las metástasis prefieren la unión gris-blanca', back: 'Calibre vascular se reduce abruptamente, atrapa émbolos tumorales.' },
  { front: 'Criterios de hipertensión intracraneal idiopática', back: 'Papiledema + examen normal (salvo VI par) + presión de apertura elevada + LCR normal + RM sin lesión.' },
  { front: 'Población típica de hipertensión intracraneal idiopática', back: 'Mujeres en edad reproductiva con obesidad.' },
  { front: 'Tratamiento farmacológico de 1ª línea en hipertensión intracraneal idiopática', back: 'Acetazolamida.' },
  { front: 'Estudio obligatorio antes de PL en sospecha de HII', back: 'RM + venografía (descartar lesión y trombosis venosa).' },
  { front: 'Edema vasogénico vs. citotóxico: mecanismo', back: 'Vasogénico: barrera rota. Citotóxico: barrera intacta, falla bomba Na+/K+.' },
  { front: 'Por qué el edema vasogénico responde a corticoides', back: 'Restauran parcialmente la barrera hematoencefálica rota.' },
  { front: 'Fármaco de elección para edema peritumoral', back: 'Dexametasona.' },
  { front: 'Profilaxis anticonvulsivante primaria en tumor cerebral', back: 'NO recomendada de rutina sin crisis previa.' },
  { front: 'Anticonvulsivante preferido en paciente oncológico', back: 'Levetiracetam (sin interacción con quimioterapia).' },
  { front: 'Localizaciones que predisponen a hidrocefalia obstructiva', back: 'Fosa posterior, 3er ventrículo, acueducto de Silvio.' },
  { front: 'Medida urgente en hidrocefalia aguda', back: 'Derivación ventricular externa.' },
  { front: 'Papiledema: ¿unilateral o bilateral?', back: 'Bilateral.' },
  { front: 'Por qué la PIC elevada produce papiledema', back: 'Espacio subaracnoideo continuo con la vaina del nervio óptico.' },
  { front: 'Seguimiento clave del papiledema', back: 'Campimetría (campos visuales) seriada.' },
  { front: 'Regla de seguridad antes de PL en sospecha de fosa posterior', back: 'Neuroimagen SIEMPRE previa (riesgo de herniación amigdalina).' },
  { front: 'Mecanismo de herniación amigdalina por PL', back: 'Gradiente de presión al retirar LCR lumbar empuja amígdalas al foramen magno.' },
  { front: 'Escalas de estado funcional oncológico', back: 'Karnofsky Performance Status y ECOG.' },
  { front: 'Karnofsky: umbral para tolerar tratamiento activo', back: '≥70 (aprox. ECOG 0-2).' }
];
