// topics/sindrome-cardiovascular-renal-metabolico/study.js
// Autoevaluacion del sindrome cardiovascular-renal-metabolico.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// Las preguntas son sobre el MARCO (estadios, criterios de paso, farmacos transversales,
// regresion, PREVENT, determinantes sociales), no sobre el detalle de cada enfermedad, que se
// evalua en los temas de Obesidad, Diabetes Mellitus, Hipertension Arterial y Dislipidemias.
//
// Metodo (ver memoria del proyecto): las 48 preguntas (30 sueltas + 6 cascadas de 3 pasos) se
// escribieron con la respuesta correcta en options[0]/correct:0 y luego se redistribuyo la
// posicion de `correct` con un script. Sin em dash (ver [[feedback-no-em-dash]]).

export const quiz = [
  { q: 'Que integra el sindrome cardiovascular-renal-metabolico?', options: ['Solo la diabetes tipo 2 y la enfermedad coronaria establecida', 'La hipertension arterial y la insuficiencia cardiaca de forma aislada', 'Las enfermedades autoinmunes con afectacion renal y cardiaca', 'Adiposidad disfuncional, alteraciones metabolicas, rinon y corazon'], correct: 3, explanation: 'El marco de la AHA reconoce que la adiposidad disfuncional, los factores metabolicos, la enfermedad renal cronica y la enfermedad cardiovascular no son problemas independientes que coinciden, sino un continuo con mecanismos compartidos.', dificultad: 'facil' },
  { q: 'Que organizacion propuso el marco del sindrome cardiovascular-renal-metabolico y en que ano?', options: ['La Organizacion Mundial de la Salud, en 2019', 'La American Heart Association, en 2023', 'La American Diabetes Association, en 2015', 'La Sociedad Europea de Cardiologia, en 2021'], correct: 1, explanation: 'La AHA lo formalizo en un aviso presidencial en 2023 (Ndumele CE, et al. Circulation), acompanado de una declaracion cientifica con la evidencia y el manejo clinico.', dificultad: 'facil' },
  { q: 'Que define el estadio 0 del continuo CKM?', options: ['Presencia de sobrepeso sin otras alteraciones asociadas', 'Prediabetes aislada con peso y cintura normales', 'Ausencia de todos los factores de riesgo CKM', 'Enfermedad renal cronica en estadio inicial sin sintomas'], correct: 2, explanation: 'El estadio 0 exige peso y cintura normales, glucemia, presion y lipidos normales, y ausencia de enfermedad renal y cardiovascular. El objetivo aqui es la prevencion primordial: no entrar en el estadio siguiente.', dificultad: 'facil' },
  { q: 'Que define el estadio 1 del continuo CKM?', options: ['Exceso o disfuncion de la adiposidad, sin nada mas', 'Diabetes tipo 2 de diagnostico reciente sin complicaciones', 'Hipertension arterial en tratamiento con un solo farmaco', 'Calcio coronario positivo en un paciente sin sintomas'], correct: 0, explanation: 'El estadio 1 lo define el sobrepeso u obesidad, la adiposidad abdominal o la adiposidad disfuncional (prediabetes o intolerancia a la glucosa), sin otros factores metabolicos ni enfermedad renal cronica.', dificultad: 'intermedio' },
  { q: 'En que estadio CKM se situa la prediabetes aislada?', options: ['En el estadio 0, porque no es una enfermedad establecida', 'En el estadio 1, como marcador de adiposidad disfuncional', 'En el estadio 2, junto con la diabetes ya establecida', 'En el estadio 3, por el riesgo cardiovascular que conlleva'], correct: 1, explanation: 'En este marco la prediabetes no es un hallazgo menor sino la manifestacion de una adiposidad disfuncional, y por tanto define el estadio 1. La diabetes ya establecida corresponde al estadio 2.', dificultad: 'dificil' },
  { q: 'Que criterios definen el estadio 2 del continuo CKM?', options: ['Solo la diabetes tipo 2 con mal control glucemico mantenido', 'Enfermedad cardiovascular subclinica detectada por imagen', 'Obesidad grado II o superior sin otras alteraciones metabolicas', 'Factores metabolicos establecidos o enfermedad renal cronica'], correct: 3, explanation: 'El estadio 2 lo define la presencia de diabetes, hipertension, trigliceridos de 135 mg/dL o mas, sindrome metabolico, o enfermedad renal cronica de cualquier grado, sin enfermedad cardiovascular subclinica ni clinica.', dificultad: 'intermedio' },
  { q: 'Que define el estadio 3 del continuo CKM?', options: ['Enfermedad cardiovascular subclinica o riesgo equivalente', 'La aparicion del primer evento cardiovascular clinico', 'La coexistencia de diabetes y de hipertension arterial', 'El inicio del tratamiento renal sustitutivo cronico'], correct: 0, explanation: 'El estadio 3 lo define la aterosclerosis subclinica (calcio coronario o placa), el dano miocardico subclinico (peptidos natriureticos o troponina elevados, alteraciones ecocardiograficas), o los equivalentes de riesgo alto: enfermedad renal de muy alto riesgo o riesgo predicho alto.', dificultad: 'intermedio' },
  { q: 'Como se subdivide el estadio 4 del continuo CKM?', options: ['En 4a, con un solo territorio afectado, y 4b, con varios', 'En 4a, sin sintomas, y 4b, con sintomas', 'En 4a, sin fallo renal, y 4b, con fallo renal', 'En 4a, en menores de 65 anos, y 4b, en mayores'], correct: 2, explanation: 'El estadio 4 se subdivide segun la funcion renal porque el fallo renal condiciona la eleccion y la dosis de casi todos los farmacos y ensombrece de forma sustancial el pronostico.', dificultad: 'intermedio' },
  { q: 'Cual es una de las ideas centrales del marco CKM sobre la progresion entre estadios?', options: ['La progresion es unidireccional e irreversible una vez iniciada', 'Los estadios avanzan a un ritmo constante y previsible', 'Los estadios pueden retroceder si se revierte lo que los definia', 'El estadio se fija en la edad adulta y ya no cambia'], correct: 2, explanation: 'La regresion es explicita en el marco: perder peso, lograr la remision de la diabetes o revertir la albuminuria devuelven al paciente a un estadio anterior con mejor pronostico. No es una escalera de un solo sentido.', dificultad: 'intermedio' },
  { q: 'Que lugar ocupan los determinantes sociales de la salud en el marco CKM?', options: ['Son parte del marco y atraviesan todos los estadios', 'Se consideran contexto social ajeno al modelo clinico habitual', 'Solo se tienen en cuenta a partir del estadio 4', 'Se mencionan pero no modifican la conducta terapeutica'], correct: 0, explanation: 'El aviso de la AHA los incorpora de forma explicita porque condicionan tanto la progresion como la viabilidad del tratamiento: el acceso a alimentos, a atencion y a medicamentos determina si el plan terapeutico se cumple.', dificultad: 'intermedio' },
  { q: 'Que ecuaciones propone la AHA para estimar el riesgo en el marco CKM?', options: ['Las Pooled Cohort Equations', 'El SCORE2 europeo', 'La escala de Framingham clasica', 'Las ecuaciones PREVENT'], correct: 3, explanation: 'Las ecuaciones PREVENT (2024) sustituyen a las Pooled Cohort Equations: estiman el riesgo de enfermedad cardiovascular total, ateroesclerotica e insuficiencia cardiaca e incorporan el filtrado glomerular y, de forma opcional, la albuminuria, la HbA1c y un indice de privacion social.', dificultad: 'intermedio' },
  { q: 'Que ventaja aporta la estimacion de riesgo a 30 anos de las ecuaciones PREVENT?', options: ['Sustituye la necesidad de medir el perfil lipidico completo', 'Evita infratratar al joven, cuyo riesgo a 10 anos parece bajo', 'Permite prescindir del calculo del filtrado glomerular', 'Predice con exactitud la fecha del primer evento cardiovascular'], correct: 1, explanation: 'En el adulto joven el riesgo a 10 anos es casi siempre bajo por la edad, lo que hace perder decadas de prevencion. La estimacion a 30 anos revela el riesgo acumulado a lo largo de la vida y orienta mejor la decision.', dificultad: 'dificil' },
  { q: 'Cual es la prueba mas infrautilizada para estadificar correctamente el continuo CKM?', options: ['El cociente albumina/creatinina en orina', 'El perfil lipidico completo en ayuno', 'La glucemia capilar posprandial', 'El electrocardiograma de reposo de doce derivaciones'], correct: 0, explanation: 'El cociente albumina/creatinina detecta dano renal con filtrado glomerular todavia normal y sube al paciente al estadio 2. Si solo se mira la creatinina, esa enfermedad renal pasa desapercibida y el paciente queda infraestadificado.', dificultad: 'intermedio' },
  { q: 'Que grupos de farmacos actuan sobre los tres ejes del continuo CKM?', options: ['Diureticos tiazidicos, betabloqueadores y digoxina oral', 'Sulfonilureas, inhibidores de DPP-4 y acarbosa', 'Inhibidores de SGLT2, agonistas de GLP-1 y finerenona', 'Antiagregantes, anticoagulantes orales y nitratos'], correct: 2, explanation: 'Son los que reducen eventos en mas de un eje a la vez y la razon practica por la que el marco CKM cambia decisiones: su beneficio cardiorrenal es independiente del control glucemico.', dificultad: 'intermedio' },
  { q: 'Que criterio guia la eleccion entre los farmacos transversales del marco CKM?', options: ['El precio del farmaco por encima de cualquier otra consideracion', 'El eje dominante en ese paciente, no la cifra de HbA1c', 'La preferencia del paciente entre via oral e inyectable', 'El valor absoluto del indice de masa corporal'], correct: 1, explanation: 'Si domina la insuficiencia cardiaca o la enfermedad renal se elige un inhibidor de SGLT2; si domina la obesidad o el riesgo ateroesclerotico, un agonista del receptor de GLP-1; y si persiste la albuminuria pese a IECA o ARA e inhibidor de SGLT2, se anade finerenona.', dificultad: 'intermedio' },
  { q: 'Con que filtrado glomerular se pueden iniciar los inhibidores de SGLT2 por indicacion renal?', options: ['Solo con un filtrado por encima de 60 mL/min/1.73 m2', 'Con cualquier filtrado, incluso en dialisis', 'Solo con un filtrado por encima de 45 mL/min/1.73 m2', 'Con un filtrado de 20 mL/min/1.73 m2 o mayor'], correct: 3, explanation: 'Se inician con un filtrado de 20 o mas y, una vez iniciados, se mantienen aunque el filtrado descienda despues. Su beneficio renal y cardiovascular persiste en los grados avanzados de enfermedad renal cronica.', dificultad: 'dificil' },
  { q: 'Como se interpreta el descenso del filtrado glomerular al iniciar un inhibidor de SGLT2?', options: ['Indica toxicidad renal y obliga a suspender de inmediato', 'Refleja una deshidratacion que exige suspender el diuretico', 'Es un error de laboratorio que hay que repetir sin demora', 'Es hemodinamico y esperable; no obliga a suspender'], correct: 3, explanation: 'El descenso inicial se debe a la restauracion de la retroalimentacion tubuloglomerular, que reduce la hiperfiltracion: es precisamente el mecanismo del que deriva el beneficio a largo plazo. Suspender el farmaco por ese descenso es un error frecuente.', dificultad: 'dificil' },
  { q: 'Que condicion hay que comprobar antes de iniciar finerenona?', options: ['Que el potasio serico sea menor de 5 mmol/L', 'Que el filtrado glomerular supere 60 mL/min/1.73 m2', 'Que la HbA1c este por debajo del 7%', 'Que el paciente no tome un inhibidor de SGLT2'], correct: 0, explanation: 'La finerenona puede producir hiperpotasemia, asi que se inicia solo con potasio menor de 5 mmol/L y se controla el potasio y la funcion renal a las 4 semanas. Se usa precisamente anadida al IECA o ARA y al inhibidor de SGLT2.', dificultad: 'intermedio' },
  { q: 'En que situacion se anade finerenona en el continuo CKM?', options: ['Como primer farmaco antes que el bloqueo del sistema renina-angiotensina', 'Cuando persiste la albuminuria pese a IECA o ARA y a inhibidor de SGLT2', 'Solo cuando el filtrado glomerular es normal y no hay albuminuria', 'Unicamente en pacientes sin diabetes tipo 2'], correct: 1, explanation: 'La finerenona se anade al bloqueo del sistema renina-angiotensina y al inhibidor de SGLT2 cuando persiste la albuminuria, con potasio menor de 5 mmol/L. Ha demostrado beneficio renal y cardiovascular (FIDELIO, FIGARO) y tambien en insuficiencia cardiaca con fraccion de eyeccion preservada (FINEARTS-HF).', dificultad: 'intermedio' },
  { q: 'Por que el marco CKM insiste en buscar enfermedad cardiovascular subclinica en el estadio 2?', options: ['Porque permite retirar los farmacos que ya esta tomando', 'Porque sustituye la necesidad de controlar la presion arterial', 'Porque reclasifica a estadio 3 y cambia el tratamiento', 'Porque confirma que el paciente no necesita mas seguimiento'], correct: 2, explanation: 'Sin peptidos natriureticos, calcio coronario ni ecocardiograma, estos pacientes se manejan como estadio 2 y se infratratan. Reconocer el estadio 3 es la diferencia entre prevenir el primer evento y tratarlo.', dificultad: 'intermedio' },
  { q: 'Cual es el objetivo terapeutico principal en el estadio 1 del continuo CKM?', options: ['Iniciar estatina de alta intensidad en todos los pacientes', 'Anadir un inhibidor de SGLT2 con independencia del resto', 'Actuar sobre la adiposidad: perder al menos un 5% del peso', 'Comenzar bloqueo del sistema renina-angiotensina de forma preventiva'], correct: 2, explanation: 'En el estadio 1 el objetivo es la adiposidad: estilo de vida estructurado con meta de perder al menos un 5%, y farmaco para el peso segun los umbrales de la obesidad. No hay indicacion de estatina, IECA ni inhibidor de SGLT2 solo por estar en este estadio.', dificultad: 'intermedio' },
  { q: 'Que objetivo de presion arterial se persigue a partir del estadio 2 del continuo CKM?', options: ['Menor de 150/90 mmHg', 'Menor de 130/80 mmHg', 'Menor de 120/70 mmHg de forma estricta', 'Menor de 140/90 mmHg con independencia del perfil'], correct: 1, explanation: 'A partir del estadio 2, y sobre todo si hay albuminuria, el objetivo es una presion arterial menor de 130/80 mmHg, preferentemente con un IECA o un ARA como parte del esquema.', dificultad: 'facil' },
  { q: 'Que estudio demostro el beneficio del abordaje multifactorial intensivo en el paciente con diabetes y albuminuria?', options: ['El estudio ACCORD', 'El estudio UKPDS 33', 'El estudio EMPA-REG OUTCOME', 'El estudio Steno-2'], correct: 3, explanation: 'Steno-2 mostro que tratar de forma intensiva y simultanea la glucemia, la presion arterial, los lipidos y la antiagregacion reduce de forma marcada los eventos y la mortalidad, que es exactamente la logica del marco CKM.', dificultad: 'dificil' },
  { q: 'En que situacion esta indicado un inhibidor de SGLT2 con independencia de que haya diabetes?', options: ['En la insuficiencia cardiaca y en la enfermedad renal cronica', 'Solo en la diabetes tipo 2 con HbA1c por encima del 8%', 'Unicamente en la diabetes tipo 1 con mal control metabolico', 'Solo en la hipertension arterial resistente al tratamiento'], correct: 0, explanation: 'Los inhibidores de SGLT2 tienen indicacion propia en la insuficiencia cardiaca con cualquier fraccion de eyeccion y en la enfermedad renal cronica, con y sin diabetes: su beneficio es independiente del control glucemico.', dificultad: 'intermedio' },
  { q: 'Que efecto adverso obliga a suspender el inhibidor de SGLT2 antes de una cirugia mayor?', options: ['La hiperpotasemia grave', 'La cetoacidosis euglucemica', 'La hipoglucemia prolongada', 'La retencion hidrosalina'], correct: 1, explanation: 'El ayuno y el estres quirurgico sobre el tratamiento con inhibidor de SGLT2 precipitan cetoacidosis con glucemia poco elevada. Se suspende 3 a 4 dias antes de una cirugia mayor y ante cualquier enfermedad aguda con ayuno (ver el tema de Cetoacidosis Diabetica y Estado Hiperosmolar).', dificultad: 'intermedio' },
  { q: 'Que caracteriza a la insuficiencia cardiaca del paciente con perfil CKM?', options: ['Se presenta de forma caracteristica con fraccion de eyeccion reducida', 'Rara vez se asocia a enfermedad renal cronica', 'Con frecuencia cursa con fraccion de eyeccion preservada', 'Responde mal a los inhibidores de SGLT2'], correct: 2, explanation: 'La obesidad, la diabetes y la hipertension producen remodelado con hipertrofia y fibrosis y disfuncion diastolica, de modo que la insuficiencia cardiaca con fraccion de eyeccion preservada es especialmente frecuente en este perfil de paciente.', dificultad: 'intermedio' },
  { q: 'Que valor de trigliceridos es uno de los criterios de estadio 2 del continuo CKM?', options: ['135 mg/dL o mas', '500 mg/dL o mas', '200 mg/dL o mas', '100 mg/dL o mas'], correct: 0, explanation: 'El marco de la AHA usa un umbral de trigliceridos de 135 mg/dL, mas bajo que el clasico de 150, como marcador de disfuncion metabolica que ya coloca al paciente en el estadio 2.', dificultad: 'dificil' },
  { q: 'Por que el marco CKM se considera util y no solo un cambio de vocabulario?', options: ['Porque sustituye las guias de cada enfermedad por un protocolo unico', 'Porque elimina la necesidad de derivar a cardiologia o nefrologia', 'Porque permite prescindir de la estimacion cuantitativa del riesgo', 'Porque adelanta la deteccion y ordena los farmacos multiorgano'], correct: 3, explanation: 'El marco cambia dos cosas practicas: convierte la adiposidad disfuncional en un estadio (lo que adelanta la intervencion) y ordena el uso de los farmacos que reducen eventos en mas de un eje, con independencia del control glucemico.', dificultad: 'intermedio' },
  { q: 'Que significa la existencia de un equivalente de riesgo alto en el marco CKM?', options: ['Permite clasificar en estadio 3 sin imagen positiva', 'Obliga a reclasificar al paciente directamente en el estadio 4', 'Indica que el paciente ya no necesita cribado periodico', 'Sustituye el calculo del riesgo con las ecuaciones PREVENT'], correct: 0, explanation: 'La enfermedad renal cronica de muy alto riesgo por la matriz de KDIGO y un riesgo predicho alto funcionan como equivalentes de enfermedad subclinica y colocan al paciente en el estadio 3 sin necesidad de una prueba de imagen positiva.', dificultad: 'dificil' },
  { q: 'Que se debe hacer al alta hospitalaria de un paciente con perfil CKM?', options: ['Limitar el informe al motivo de ingreso para no sobrecargarlo', 'Suspender los farmacos cardiorrenales hasta la revision ambulatoria', 'Delegar toda la estadificacion en la consulta de atencion primaria', 'Registrar el estadio y dejar un plan explicito por ejes'], correct: 3, explanation: 'El ingreso es donde con mas frecuencia se descubre que un paciente llevaba anos en estadio 2 o 3 sin nombrarlo. Dejar el estadio y el plan por escrito, con los farmacos cardiorrenales ya iniciados, es lo que hace que el marco sirva de algo.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 44 anos sin antecedentes. Peso 78 kg, talla 162 cm, cintura 91 cm. Presion arterial 122/78 mmHg. Glucemia en ayuno 108 mg/dL, HbA1c 5.9%, perfil lipidico normal, creatinina normal con filtrado glomerular de 96 mL/min/1.73 m2 y cociente albumina/creatinina de 12 mg/g.',
    steps: [
      { q: 'En que estadio CKM la situa este perfil?', options: ['Estadio 0', 'Estadio 2', 'Estadio 1', 'Estadio 3'], correct: 2, explanation: 'Tiene exceso de adiposidad (indice de masa corporal de 29.7 y cintura de 91 cm) y adiposidad disfuncional en forma de prediabetes (glucemia 108 y HbA1c 5.9%), pero sin diabetes, hipertension, dislipidemia ni enfermedad renal: es un estadio 1.' },
      { q: 'Que dato descarta el estadio 2 en esta paciente?', options: ['La presion arterial de 122/78 mmHg sin ningun tratamiento', 'El cociente albumina/creatinina normal con filtrado normal', 'El indice de masa corporal por debajo de 30 kg/m2 medido', 'La ausencia de sintomas cardiovasculares o renales referidos'], correct: 1, explanation: 'La enfermedad renal cronica es uno de los criterios de estadio 2 y se pierde si solo se mira la creatinina. Un cociente albumina/creatinina menor de 30 mg/g con filtrado normal permite descartarla y dejar a la paciente en estadio 1.' },
      { q: 'Cual es la conducta apropiada en el estadio 1?', options: ['Iniciar un inhibidor de SGLT2 por la prediabetes detectada', 'Comenzar estatina de intensidad moderada de forma preventiva', 'Repetir la analitica en cinco anos sin intervenir ahora', 'Estilo de vida estructurado con meta de perder un 5% del peso'], correct: 3, explanation: 'En el estadio 1 la intervencion es sobre la adiposidad: alimentacion, actividad fisica con trabajo de fuerza y apoyo conductual, con meta de perder al menos un 5%. Es el estadio donde la regresion a estadio 0 es mas realista.' }
    ],
    explanation: 'Una mujer con adiposidad central y prediabetes, sin otros factores ni enfermedad renal, esta en estadio 1: el cociente albumina/creatinina normal es lo que permite descartar el estadio 2, y la conducta es actuar sobre la adiposidad.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 61 anos con diabetes tipo 2 de 9 anos e hipertension. Toma metformina, un IECA a dosis maxima y una estatina. Filtrado glomerular 52 mL/min/1.73 m2, cociente albumina/creatinina 380 mg/g, potasio 4.4 mmol/L, presion arterial 136/82 mmHg. No tiene enfermedad cardiovascular conocida ni sintomas.',
    steps: [
      { q: 'En que estadio CKM esta este paciente con albuminuria?', options: ['Estadio 1', 'Estadio 3', 'Estadio 2', 'Estadio 4a'], correct: 2, explanation: 'Tiene factores metabolicos establecidos (diabetes e hipertension) y enfermedad renal cronica (filtrado menor de 60 y albuminuria), pero no hay enfermedad cardiovascular subclinica demostrada ni clinica: es un estadio 2.' },
      { q: 'Que farmaco corresponde anadir en primer lugar?', options: ['Un inhibidor de SGLT2', 'Un segundo bloqueante del sistema renina-angiotensina', 'Un inhibidor de DPP-4 por su neutralidad', 'Un diuretico tiazidico para la presion arterial'], correct: 0, explanation: 'Con filtrado de 20 o mas y albuminuria, el inhibidor de SGLT2 reduce la progresion renal y los eventos cardiovasculares y se mantiene aunque el filtrado baje despues. Nunca se anade un ARA al IECA.' },
      { q: 'Si tras anadirlo persiste una albuminuria de 300 mg/g con potasio de 4.6 mmol/L, que se hace?', options: ['Duplicar la dosis del IECA por encima de la maxima', 'Anadir finerenona', 'Suspender el inhibidor de SGLT2 por falta de respuesta', 'Anadir espironolactona sin control posterior del potasio'], correct: 1, explanation: 'La finerenona esta indicada cuando persiste la albuminuria pese a IECA o ARA y a inhibidor de SGLT2, siempre que el potasio sea menor de 5 mmol/L, y se controla el potasio y la funcion renal a las 4 semanas.' }
    ],
    explanation: 'Un paciente con diabetes, hipertension y enfermedad renal cronica con albuminuria, sin enfermedad cardiovascular, esta en estadio 2: se anade un inhibidor de SGLT2 al IECA y, si persiste la albuminuria con potasio menor de 5, se anade finerenona.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 58 anos con obesidad, hipertension y dislipidemia en tratamiento. Filtrado glomerular 71 mL/min/1.73 m2 y cociente albumina/creatinina 18 mg/g. Se solicita una analitica ampliada: NT-proBNP de 480 pg/mL sin sintomas de insuficiencia cardiaca, y un ecocardiograma muestra hipertrofia ventricular izquierda con disfuncion diastolica.',
    steps: [
      { q: 'En que estadio CKM la coloca el hallazgo ecocardiografico?', options: ['Estadio 2', 'Estadio 3', 'Estadio 1', 'Estadio 4a'], correct: 1, explanation: 'Los peptidos natriureticos elevados sin clinica y las alteraciones ecocardiograficas constituyen enfermedad cardiaca subclinica, lo que la coloca en estadio 3 aunque no tenga sintomas ni enfermedad renal significativa.' },
      { q: 'Que cambia en su tratamiento respecto del estadio anterior?', options: ['Se intensifican objetivos y se anaden farmacos cardiorrenales', 'Se puede relajar el control lipidico por la ausencia de sintomas', 'Se sustituyen todos los farmacos por medidas de estilo de vida', 'No cambia nada hasta que aparezcan sintomas de enfermedad'], correct: 0, explanation: 'En el estadio 3 el objetivo pasa de controlar factores a prevenir el primer evento: objetivos mas estrictos de colesterol LDL y de presion arterial, y anadir inhibidor de SGLT2 y agonista del receptor de GLP-1 con beneficio probado aunque el control metabolico ya sea bueno.' },
      { q: 'Por que es importante haber reconocido este estadio?', options: ['Porque permite suspender el seguimiento cardiologico', 'Porque descarta la necesidad de controlar la albuminuria', 'Porque implica que ya no se puede modificar el pronostico', 'Porque es el ultimo estadio de prevencion primaria'], correct: 3, explanation: 'Sin buscar la enfermedad subclinica, esta paciente se habria manejado como estadio 2 y se habria infratratado. Reconocer el estadio 3 es la diferencia entre prevenir el evento y tratarlo cuando ya ha ocurrido.' }
    ],
    explanation: 'Peptidos natriureticos elevados sin sintomas y alteraciones ecocardiograficas definen enfermedad cardiaca subclinica y colocan a la paciente en estadio 3: se intensifican los objetivos y se anaden farmacos cardiorrenales, porque es el ultimo estadio de prevencion primaria.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 69 anos con diabetes tipo 2, insuficiencia cardiaca con fraccion de eyeccion del 38% y enfermedad renal cronica con filtrado glomerular de 26 mL/min/1.73 m2, en seguimiento por nefrologia. Ingresa por descompensacion de la insuficiencia cardiaca. Al revisar el tratamiento no toma ningun inhibidor de SGLT2.',
    steps: [
      { q: 'En que estadio CKM esta este paciente ingresado?', options: ['Estadio 4a', 'Estadio 3', 'Estadio 4b', 'Estadio 2'], correct: 2, explanation: 'Tiene enfermedad cardiovascular clinica (insuficiencia cardiaca) junto con enfermedad renal avanzada: corresponde al estadio 4b, la subdivision con fallo renal, que condiciona la eleccion de farmacos y ensombrece el pronostico.' },
      { q: 'Se puede iniciar un inhibidor de SGLT2 con ese filtrado glomerular?', options: ['No: hace falta un filtrado por encima de 45 mL/min/1.73 m2', 'No: la insuficiencia cardiaca lo contraindica en este caso', 'Si: se inician con filtrado de 20 o mas', 'Solo si la HbA1c esta por encima del 8% de forma mantenida'], correct: 2, explanation: 'Se inician con filtrado de 20 o mas y este paciente tiene doble indicacion, renal y cardiaca. Ademas, su beneficio en la insuficiencia cardiaca existe con cualquier fraccion de eyeccion y es independiente del control glucemico.' },
      { q: 'Tras iniciarlo, el filtrado glomerular baja de 26 a 22 mL/min/1.73 m2. Que se hace?', options: ['Suspenderlo de inmediato por nefrotoxicidad establecida', 'Reducir la dosis a la mitad de forma indefinida', 'Sustituirlo por un inhibidor de DPP-4 mas seguro', 'Mantenerlo: el descenso inicial es esperable'], correct: 3, explanation: 'El descenso inicial se debe a la restauracion de la retroalimentacion tubuloglomerular, que reduce la hiperfiltracion: es el mecanismo del que deriva el beneficio a largo plazo. Un descenso menor del 30% que se estabiliza no obliga a suspender.' }
    ],
    explanation: 'Un paciente con insuficiencia cardiaca y enfermedad renal avanzada esta en estadio 4b; el inhibidor de SGLT2 se inicia con filtrado de 20 o mas por doble indicacion, y el descenso inicial esperable del filtrado no obliga a suspenderlo.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varon de 34 anos con obesidad (indice de masa corporal 33) y prediabetes. Presion arterial 128/80 mmHg, lipidos limitrofes, funcion renal normal. Se calcula su riesgo cardiovascular a 10 anos con una herramienta convencional y resulta del 2.1%, por lo que se le dice que no necesita hacer nada.',
    steps: [
      { q: 'Cual es el problema de esa conclusion?', options: ['La herramienta no es aplicable en presencia de obesidad', 'El riesgo a 10 anos parece bajo en el joven por la edad', 'El riesgo calculado esta mal porque falta el filtrado glomerular', 'La prediabetes invalida cualquier calculo de riesgo previo'], correct: 1, explanation: 'En el adulto joven la edad domina el calculo y el riesgo a 10 anos resulta bajo casi siempre, aunque el perfil metabolico sea claramente adverso. Actuar solo sobre esa cifra retrasa la prevencion decadas.' },
      { q: 'Que aporta el marco CKM en este paciente?', options: ['Lo situa en estadio 1 y estima ademas el riesgo a 30 anos con PREVENT', 'Lo clasifica directamente en estadio 3 por la obesidad', 'Sustituye el calculo de riesgo por la medida del indice de masa corporal', 'Indica iniciar de inmediato un inhibidor de SGLT2 y una estatina'], correct: 0, explanation: 'El marco lo situa en estadio 1 (exceso de adiposidad mas prediabetes), y las ecuaciones PREVENT permiten estimar el riesgo a 30 anos, que es el que revela el problema real en el paciente joven.' },
      { q: 'Cual es la conducta apropiada en este joven?', options: ['Intervencion estructurada sobre la adiposidad y vigilancia periodica', 'No intervenir hasta que el riesgo a 10 anos supere el 10%', 'Iniciar estatina de alta intensidad por el riesgo a 30 anos', 'Derivar a cirugia metabolica por el indice de masa corporal'], correct: 0, explanation: 'En estadio 1 la intervencion es sobre la adiposidad, con meta de perder al menos un 5% del peso, y vigilancia de la aparicion de criterios de estadio 2. No hay indicacion de estatina ni de cirugia solo por este perfil.' }
    ],
    explanation: 'Un joven con obesidad y prediabetes tiene un riesgo a 10 anos enganosamente bajo: el marco CKM lo situa en estadio 1 y la estimacion a 30 anos de PREVENT revela el riesgo real, lo que justifica intervenir sobre la adiposidad ahora.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 52 anos con diabetes tipo 2 y obesidad, en estadio 2. Con dieta, metformina y un agonista del receptor de GLP-1 pierde 19 kg en 18 meses. La HbA1c pasa del 7.8% al 5.8% sin farmacos hipoglucemiantes distintos de la metformina, y el cociente albumina/creatinina baja de 62 a 19 mg/g. La presion arterial se normaliza y suspende el antihipertensivo.',
    steps: [
      { q: 'Que ha ocurrido en terminos del marco CKM?', options: ['El estadio se mantiene porque ya no puede retroceder', 'Ha habido regresion de estadio, que el marco reconoce', 'Ha pasado directamente al estadio 0 al normalizar la analitica', 'El concepto de estadio no se aplica tras la perdida de peso'], correct: 1, explanation: 'El marco CKM contempla de forma explicita la regresion: perder peso, lograr la remision de la diabetes o revertir la albuminuria devuelven al paciente a un estadio anterior con mejor pronostico. No es una escalera de un solo sentido.' },
      { q: 'A que estadio ha pasado?', options: ['Al estadio 0, porque todos los parametros se han normalizado', 'Sigue en estadio 2 de forma permanente', 'Al estadio 1, porque persiste el exceso de adiposidad', 'Al estadio 3, por el antecedente de albuminuria'], correct: 2, explanation: 'Han desaparecido los criterios de estadio 2 (la albuminuria ha vuelto por debajo de 30 mg/g y la diabetes esta en remision sin antidiabeticos distintos de la metformina), pero persiste el exceso de adiposidad, que define el estadio 1.' },
      { q: 'Que implica esto para el seguimiento?', options: ['Suspender todo tratamiento porque la enfermedad esta curada', 'Espaciar el seguimiento a una sola revision cada cinco anos', 'Retirar el agonista de GLP-1 por objetivo ya alcanzado', 'Mantener el tratamiento y vigilar la reaparicion de criterios'], correct: 3, explanation: 'La regresion se mantiene solo mientras se mantiene lo que la produjo: retirar el tratamiento devuelve el peso y con el los criterios del estadio previo. Se sigue vigilando peso, presion, glucemia y albuminuria.' }
    ],
    explanation: 'La perdida de peso con remision de la diabetes y reversion de la albuminuria produce regresion de estadio 2 a estadio 1, que el marco CKM reconoce de forma explicita; el estadio 0 no se alcanza porque persiste el exceso de adiposidad, y hay que mantener el tratamiento que lo logro.'
  }
];

export const flashcards = [
  { front: 'Que integra el sindrome CKM', back: 'Adiposidad disfuncional, alteraciones metabolicas, enfermedad renal cronica y enfermedad cardiovascular, como un continuo.' },
  { front: 'Quien propuso el marco CKM', back: 'La American Heart Association, en un aviso presidencial de 2023.' },
  { front: 'Estadio 0', back: 'Sin ningun factor de riesgo CKM. Prevencion primordial; cribado cada 3 a 5 anos.' },
  { front: 'Estadio 1', back: 'Exceso o disfuncion de la adiposidad (sobrepeso, obesidad abdominal o prediabetes) sin otros factores ni enfermedad renal.' },
  { front: 'Estadio 2', back: 'Factores metabolicos (diabetes, hipertension, trigliceridos 135 o mas, sindrome metabolico) o enfermedad renal cronica de cualquier grado.' },
  { front: 'Estadio 3', back: 'Enfermedad cardiovascular subclinica (calcio coronario, peptidos natriureticos, eco) o equivalente de riesgo alto.' },
  { front: 'Estadio 4', back: 'Enfermedad cardiovascular clinica. 4a sin fallo renal, 4b con fallo renal.' },
  { front: 'Donde se situa la prediabetes en el marco CKM', back: 'En el estadio 1, como marcador de adiposidad disfuncional (la diabetes ya establecida es estadio 2).' },
  { front: 'Idea central sobre la progresion', back: 'Los estadios PUEDEN RETROCEDER: perder peso, remitir la diabetes o revertir la albuminuria devuelven a un estadio anterior.' },
  { front: 'Determinantes sociales en el marco CKM', back: 'Son parte explicita del marco y atraviesan todos los estadios; condicionan la progresion y la viabilidad del tratamiento.' },
  { front: 'Ecuaciones de riesgo del marco CKM', back: 'PREVENT (AHA 2024): riesgo de ECV total, ateroesclerotica e insuficiencia cardiaca a 10 y 30 anos; incluyen el filtrado glomerular.' },
  { front: 'Ventaja del riesgo a 30 anos', back: 'Evita infratratar al joven, cuyo riesgo a 10 anos siempre parece bajo por la edad.' },
  { front: 'Prueba mas infrautilizada para estadificar', back: 'El cociente albumina/creatinina: detecta enfermedad renal con filtrado normal y sube al estadio 2.' },
  { front: 'Los tres farmacos transversales', back: 'Inhibidores de SGLT2, agonistas del receptor de GLP-1 y finerenona.' },
  { front: 'Como se elige entre ellos', back: 'Por el eje dominante, no por la HbA1c: SGLT2 si domina corazon o rinon; GLP-1 si domina obesidad o riesgo ateroesclerotico.' },
  { front: 'Filtrado minimo para iniciar un inhibidor de SGLT2', back: '20 mL/min/1.73 m2; una vez iniciado se mantiene aunque el filtrado baje.' },
  { front: 'Descenso inicial del filtrado con iSGLT2 o IECA', back: 'Hemodinamico y esperable; si es menor del 30% y se estabiliza, NO se suspende.' },
  { front: 'Condicion para iniciar finerenona', back: 'Potasio serico menor de 5 mmol/L; control de potasio y funcion renal a las 4 semanas.' },
  { front: 'Cuando se anade finerenona', back: 'Si persiste la albuminuria pese a IECA o ARA y a inhibidor de SGLT2.' },
  { front: 'Objetivo de presion arterial desde el estadio 2', back: 'Menor de 130/80 mmHg, preferentemente con IECA o ARA si hay albuminuria.' },
  { front: 'Objetivo terapeutico del estadio 1', back: 'Actuar sobre la adiposidad: perder al menos un 5% del peso. No hay indicacion de estatina ni iSGLT2 solo por el estadio.' },
  { front: 'Por que buscar enfermedad subclinica en el estadio 2', back: 'Porque reclasifica a estadio 3 y cambia la intensidad del tratamiento; sin buscarla, el paciente se infratrata.' },
  { front: 'Estudio del abordaje multifactorial intensivo', back: 'Steno-2: tratar a la vez glucemia, presion, lipidos y antiagregacion reduce eventos y mortalidad.' },
  { front: 'iSGLT2 sin diabetes', back: 'Indicados en insuficiencia cardiaca con cualquier fraccion de eyeccion y en enfermedad renal cronica.' },
  { front: 'Efecto adverso que obliga a suspender el iSGLT2 antes de cirugia', back: 'Cetoacidosis euglucemica: suspender 3 a 4 dias antes de cirugia mayor o ante enfermedad aguda con ayuno.' },
  { front: 'Insuficiencia cardiaca del perfil CKM', back: 'Con frecuencia con fraccion de eyeccion preservada, por remodelado con hipertrofia y disfuncion diastolica.' },
  { front: 'Umbral de trigliceridos del estadio 2', back: '135 mg/dL o mas (mas bajo que el clasico de 150).' },
  { front: 'Por que el marco CKM es util y no solo vocabulario', back: 'Identifica el riesgo antes (la adiposidad ya es un estadio) y ordena los farmacos que protegen varios ejes a la vez.' },
  { front: 'Equivalentes de riesgo alto', back: 'Enfermedad renal cronica de muy alto riesgo o riesgo predicho alto: permiten clasificar en estadio 3 sin imagen positiva.' },
  { front: 'Que dejar por escrito al alta', back: 'El estadio CKM y un plan explicito por ejes, con los farmacos cardiorrenales ya iniciados y las citas correspondientes.' },
  { front: 'Estadio 3: por que importa reconocerlo', back: 'Es el ultimo estadio de prevencion primaria: la diferencia entre prevenir el primer evento y tratarlo.' },
  { front: 'Que NO cambia el marco CKM', back: 'No sustituye las guias de cada enfermedad ni el tratamiento clasico (estatina, IECA o ARA, control de la presion): los ordena y les anade los farmacos transversales.' }
];
