// topics/farmacodermias/study.js: Autoevaluacion de farmacodermias y eritrodermia.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
// Fuentes: guias latinoamericanas de SJS y NET 2025 (doi:10.1016/j.waojou.2025.101046),
// Hoetzenecker 2016 y Tso 2021. 30 sueltas + 6 cascadas de 3 = 48 subpreguntas, 32 tarjetas.

export const quiz = [
  { q:'&#191;Que proporcion de las erupciones cutaneas por farmacos es grave?', options:['Alrededor de la mitad', 'En torno al 2%', 'Practicamente todas', 'Cerca del 25%'], correct:1, explanation:'La gran mayoria sigue un curso benigno. Alrededor del 2% son graves y pueden ser mortales, y el trabajo del internista es separar esas dos categorias a pie de cama.', dificultad:'facil' },
  { q:'&#191;Que separa el Stevens-Johnson de la necrolisis epidermica toxica?', options:['El farmaco responsable del cuadro', 'La afectacion o no de las mucosas', 'La presencia de fiebre elevada', 'El porcentaje de superficie despegada'], correct:3, explanation:'Son un espectro de la misma enfermedad. Stevens-Johnson por debajo del 10% de superficie despegada, solapamiento del 10 a menos del 30%, y necrolisis epidermica toxica en el 30% o mas.', dificultad:'facil' },
  { q:'&#191;Cual es la latencia tipica del DRESS?', options:['De 2 a 8 semanas', 'De 1 a 2 dias', 'De minutos a horas', 'De 4 a 14 dias'], correct:0, explanation:'Es la latencia mas larga de todas las farmacodermias. Eso explica el error clasico: descartar el farmaco precisamente por llevar semanas tomandolo, cuando esa latencia es justo lo esperable.', dificultad:'intermedio' },
  { q:'&#191;Que signo clinico es muy caracteristico del DRESS?', options:['El signo de Nikolsky positivo', 'La descamacion en collarete', 'El edema facial', 'Las lesiones en diana tipicas'], correct:2, explanation:'El edema facial tiene gran valor diagnostico. Un exantema con la cara hinchada obliga a pedir hemograma con formula y funcion hepatica ese mismo dia.', dificultad:'intermedio' },
  { q:'&#191;Que es el signo de Nikolsky?', options:['La epidermis se despega al frotar', 'Una lesion con tres anillos concentricos', 'La descamacion en forma de collarete', 'La palidez al presionar una lesion'], correct:0, explanation:'Al frotar suavemente piel aparentemente sana, la epidermis se despega. Indica despegamiento activo y es propio de la necrolisis epidermica toxica y del sindrome de la piel escaldada estafilococica.', dificultad:'facil' },

  { type:'cascade', vignette:'Mujer de 58 a&#241;os ingresada por crisis gotosa, en tratamiento con alopurinol iniciado hace 24 dias. Consulta por exantema generalizado, fiebre de 38.6 grados y la cara visiblemente hinchada. En la analitica destacan 1.800 eosinofilos y unas transaminasas cinco veces por encima del limite alto.', steps:[
    { q:'&#191;Cual es el diagnostico mas probable?', options:['Un exantema maculopapular banal', 'Una necrolisis epidermica inicial', 'Un DRESS', 'Una pustulosis exantematica aguda'], correct:2 },
    { q:'&#191;Que conducta es la correcta con el alopurinol?', options:['Mantenerlo y vigilar la analitica', 'Retirarlo y no reintroducirlo', 'Bajar la dosis a la mitad', 'Cambiarlo por otro del mismo grupo'], correct:1 },
    { q:'&#191;Que hay que vigilar a MESES vista?', options:['Una recurrencia de la gota', 'Una fibrosis pulmonar tardia', 'Un deterioro cognitivo', 'La funcion tiroidea'], correct:3 }
  ], explanation:'Exantema con fiebre, EDEMA FACIAL, eosinofilia y afectacion hepatica, con una latencia de tres semanas desde el alopurinol: es un DRESS de libro. El farmaco se retira y no se reintroduce nunca. Y hay una particularidad de esta entidad que se olvida: las secuelas AUTOINMUNES TARDIAS, sobre todo la tiroiditis, que aparecen meses despues, cuando ya nadie relaciona los sintomas con aquel episodio.', dificultad:'intermedio' },

  { q:'&#191;Cual es la causa principal de muerte en la necrolisis epidermica toxica?', options:['La insuficiencia renal aguda', 'La hemorragia digestiva', 'El fallo hepatico fulminante', 'La sepsis'], correct:3, explanation:'La mortalidad en fase aguda va del 10 al 40% segun la extension, y la causa principal de muerte es la sepsis con fallo multiorganico posinfeccioso, seguida de la afectacion pulmonar.', dificultad:'intermedio' },
  { q:'&#191;Que sintoma precede al despegamiento en la necrolisis epidermica?', options:['El prurito intenso generalizado', 'La sensacion de tirantez', 'El hormigueo en las extremidades', 'El dolor de la piel'], correct:3, explanation:'Que la piel DUELA antes de que aparezcan las ampollas es uno de los avisos mas precoces, y se pregunta muy poco. No hay que esperar a las ampollas para actuar.', dificultad:'intermedio' },
  { q:'&#191;Que caracteriza al exantema fijo medicamentoso?', options:['Recurre en la misma localizacion', 'Afecta de forma simetrica el tronco', 'Cursa con fiebre alta y adenopatias', 'Deja ampollas en todas las mucosas'], correct:0, explanation:'Reaparece exactamente en la MISMA localizacion cada vez que se toma el farmaco, como placas redondeadas eritematoviolaceas que dejan hiperpigmentacion residual. Esa recurrencia en el mismo sitio es su rasgo definitorio y permite reconocerlo con la historia.', dificultad:'intermedio' },
  { q:'&#191;Que separa el sindrome de la piel escaldada estafilococica de la necrolisis epidermica?', options:['La presencia de fiebre en el cuadro', 'El signo de Nikolsky positivo', 'Que respeta las mucosas', 'La extension de la superficie afectada'], correct:2, explanation:'El sindrome de la piel escaldada respeta las mucosas y el despegamiento es alto, en la capa granulosa, mientras que en la necrolisis epidermica hay necrosis de todo el espesor y en el 80% de los casos hay dos o mas mucosas afectadas.', dificultad:'dificil' },
  { q:'&#191;Cual es la latencia tipica de la pustulosis exantematica generalizada aguda?', options:['De 1 a 2 dias', 'De 2 a 3 semanas', 'De 6 a 8 semanas', 'De 3 a 6 meses'], correct:0, explanation:'Es la latencia mas corta de las farmacodermias graves, y por eso el sospechoso principal es un farmaco iniciado ayer o anteayer, al contrario que en el DRESS.', dificultad:'intermedio' },
  { q:'En la pustulosis exantematica generalizada aguda, el cultivo del pus:', options:['Muestra estreptococo del grupo A', 'Es esteril', 'Crece estafilococo aureus', 'No debe realizarse nunca'], correct:1, explanation:'Las pustulas son esteriles, y el cultivo negativo apoya el diagnostico y lo separa de una infeccion cutanea. Por eso tampoco hacen falta antibioticos.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 34 a&#241;os que lleva 12 dias con lamotrigina. Acude por fiebre, dolor en la boca que le impide comer, y unas lesiones en tronco de centro oscuro. Refiere que la piel del pecho le duele al rozarse con la camiseta. Al explorarlo, la piel se despega con la friccion suave en una zona del abdomen.', steps:[
    { q:'&#191;Que dato es el mas alarmante?', options:['El despegamiento con la friccion', 'La fiebre de los ultimos dias', 'El tiempo con el farmaco', 'La edad del paciente'], correct:0 },
    { q:'&#191;Que hay que calcular para clasificar el cuadro?', options:['El porcentaje de eritema total', 'El numero de mucosas afectadas', 'El indice de masa corporal', 'La superficie DESPEGADA'], correct:3 },
    { q:'Ademas del soporte, &#191;que valoracion no puede faltar?', options:['Neurologica por la lamotrigina', 'La valoracion oftalmologica', 'Psiquiatrica por el dolor', 'Nutricional en dos semanas'], correct:1 }
  ], explanation:'Dolor cutaneo, lesiones en diana atipicas, afectacion de mucosas y signo de Nikolsky positivo tras 12 dias de lamotrigina: es una necrolisis epidermica en curso. Se clasifica por la superficie DESPEGADA, no por el eritema, que es el error mas comun y sobrestima la gravedad. Y la valoracion oftalmologica precoz es imprescindible: las secuelas oculares son la complicacion cronica mas incapacitante y en buena parte se pueden evitar.', dificultad:'dificil' },

  { q:'Al calcular la superficie en una necrolisis epidermica, &#191;que se cuenta?', options:['Todo el eritema que se vea', 'La superficie con prurito', 'La piel despegada o despegable', 'Solo las ampollas ya rotas'], correct:2, explanation:'Solo cuenta la piel despegada o que se despega al rozarla. Contar el eritema sobrestima la gravedad y es el error mas comun. Se calcula con la regla de los nueves o, mejor, con el metodo de Lund-Browder.', dificultad:'intermedio' },
  { q:'&#191;Cuantas variables tiene el SCORTEN?', options:['Siete', 'Cuatro', 'Diez', 'Doce'], correct:0, explanation:'Edad de 40 o mas, neoplasia, frecuencia cardiaca de 120 o mas, superficie despegada mayor del 10%, urea elevada, bicarbonato bajo y glucemia elevada. Un punto cada una, de 0 a 7.', dificultad:'intermedio' },
  { q:'&#191;Cuando conviene repetir el SCORTEN?', options:['Cada seis horas el primer dia', 'Solo si el paciente empeora', 'Al alta de la unidad', 'Al tercer dia de ingreso'], correct:3, explanation:'Se calcula en las primeras 24 horas y conviene repetirlo al tercer dia, porque asi mejora su capacidad predictiva. La escala orienta el nivel de cuidados, no decide el tratamiento.', dificultad:'dificil' },
  { q:'&#191;Que ensayo revisa la guia latinoamericana sobre el tratamiento de la necrolisis?', options:['Inmunoglobulina frente a plasmaferesis', 'Etanercept frente a prednisolona', 'Ciclosporina frente a placebo', 'Talidomida frente a corticoide'], correct:1, explanation:'Un ensayo aleatorizado no ciego de 2018 con 91 pacientes comparo etanercept con prednisolona intravenosa. La mortalidad fue menor con etanercept (8.3% frente a 16.3%) sin significacion estadistica, y la reepitelizacion fue mas rapida: 14 frente a 19 dias.', dificultad:'dificil' },
  { q:'&#191;Que es lo que mas cambia la supervivencia en la necrolisis epidermica?', options:['La inmunoglobulina intravenosa precoz', 'El corticoide sistemico a dosis altas', 'La profilaxis antibiotica sistemica', 'El soporte y la retirada del farmaco'], correct:3, explanation:'Lo que salva vidas es la retirada inmediata del farmaco y el soporte: temperatura, volumen, nutricion precoz, analgesia, curas y busqueda activa de infeccion. El tratamiento inmunomodulador es el area de mayor incertidumbre.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 71 a&#241;os con psoriasis en placas de larga evolucion. Ingresa por un cuadro de eritema y descamacion que afecta a practicamente toda la superficie corporal. Tiene escalofrios, la temperatura es de 35.2 grados, la albumina de 2.4 g/dL y esta taquicardico. Hace dos semanas termino una pauta descendente rapida de prednisona que le pauto otro medico.', steps:[
    { q:'&#191;Que esta ocurriendo con la piel?', options:['Una infeccion cutanea extensa', 'Ha dejado de funcionar como barrera', 'Una reaccion alergica de contacto', 'Un proceso puramente cosmetico'], correct:1 },
    { q:'&#191;Que hay que corregir de forma prioritaria?', options:['La albumina y la temperatura', 'El prurito con antihistaminicos', 'La descamacion con queratoliticos', 'El aspecto estetico de las placas'], correct:0 },
    { q:'&#191;Que farmaco hay que usar con especial cautela aqui?', options:['El emoliente en abundancia', 'El antibiotico si hay infeccion', 'El corticoide sistemico', 'El analgesico para el dolor'], correct:2 }
  ], explanation:'Es una eritrodermia, que no es una enfermedad sino un estado en el que la piel deja de funcionar como organo: hipotermia, deshidratacion, hipoalbuminemia por perdida cutanea de proteinas e insuficiencia cardiaca de alto gasto. El soporte es lo prioritario. Y aqui hay una trampa: con psoriasis de base, el corticoide sistemico es peligroso porque su retirada precipita un brote pustuloso, que es justo lo que ha desencadenado este episodio.', dificultad:'dificil' },

  { q:'&#191;Que farmacos se asocian con mas frecuencia a la necrolisis epidermica toxica?', options:['Paracetamol e ibuprofeno', 'Alopurinol y antiepilepticos aromaticos', 'Estatinas y antagonistas del calcio', 'Inhibidores de la bomba de protones'], correct:1, explanation:'Alopurinol, carbamazepina, fenitoina, lamotrigina, sulfamidas, oxicam y nevirapina encabezan la lista. Determinados alelos HLA aumentan el riesgo segun el farmaco y la etnia.', dificultad:'intermedio' },
  { q:'&#191;Cual es el diferencial mas dificil de la pustulosis exantematica generalizada aguda?', options:['La foliculitis estafilococica extensa', 'La necrolisis epidermica inicial', 'La psoriasis pustulosa generalizada', 'El eccema herpetico diseminado'], correct:2, explanation:'Comparten parte de la via y el resultado morfologico. A favor de la pustulosis por farmacos juegan la latencia corta y clara, la fiebre simultanea y la resolucion rapida al retirarlo; a favor de la psoriasis, el antecedente personal y la recurrencia sin farmaco.', dificultad:'dificil' },
  { q:'&#191;Que virus se reactiva de forma caracteristica en el DRESS?', options:['El citomegalovirus de forma exclusiva', 'El herpesvirus humano 6', 'El virus de Epstein-Barr siempre', 'El parvovirus B19'], correct:1, explanation:'La reactivacion de virus del grupo herpes, sobre todo el herpesvirus humano 6, se asocia a los brotes tardios y a las recaidas al bajar el corticoide, y explica el curso prolongado y ondulante tan propio de esta entidad.', dificultad:'dificil' },
  { q:'&#191;Por que el DRESS no se diagnostica solo mirando la piel?', options:['Porque el exantema es poco llamativo', 'Porque el edema facial falta a menudo', 'Porque exige afectacion de organos', 'Porque la biopsia es la que decide'], correct:2, explanation:'Es un diagnostico SISTEMICO: hacen falta la eosinofilia o los linfocitos atipicos y la afectacion de al menos un organo interno. Sin analitica no se puede diagnosticar ni excluir, y hay que repetirla porque la afectacion visceral puede aparecer despues de retirar el farmaco.', dificultad:'intermedio' },
  { q:'&#191;Como debe bajarse el corticoide en un DRESS con afectacion visceral?', options:['Suspendiendolo de golpe al mejorar', 'En una pauta de cinco dias', 'Alternando dias con y sin dosis', 'De forma lenta, en semanas o meses'], correct:3, explanation:'Un descenso rapido produce recaida, que es una particularidad de esta entidad relacionada con la reactivacion viral. Hay que avisar al paciente y al equipo de que el curso es prolongado y ondulante.', dificultad:'dificil' },
  { q:'&#191;Cuales son las causas mas frecuentes de eritrodermia?', options:['Solo los linfomas cutaneos', 'Unicamente las reacciones a farmacos', 'Dermatosis previa, farmacos y linfoma', 'Las infecciones bacterianas extensas'], correct:2, explanation:'Por orden: una dermatosis inflamatoria previa que se generaliza (psoriasis, dermatitis atopica, seborreica), reacciones a farmacos, linfoma cutaneo de celulas T y, en una minoria, causa desconocida.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Mujer de 47 a&#241;os que a las 36 horas de empezar amoxicilina presenta fiebre de 38.8 grados y una erupcion de decenas de pustulas de 2 milimetros, no foliculares, sobre piel eritematosa y edematosa, que empezo en los pliegues y se ha generalizado. Los leucocitos son de 18.000 con neutrofilia.', steps:[
    { q:'&#191;Que apoya mas el diagnostico de farmacodermia aqui?', options:['La cifra de leucocitos', 'La latencia de 36 horas', 'La localizacion inicial', 'La edad de la paciente'], correct:1 },
    { q:'&#191;Que prueba conviene hacer?', options:['Hemocultivos seriados', 'Serologia de herpesvirus', 'Cultivo del contenido pustuloso', 'Biopsia de medula osea'], correct:2 },
    { q:'&#191;Que NO esta indicado?', options:['Retirar la amoxicilina', 'A&#241;adir un antibiotico nuevo', 'Corticoide topico potente', 'Vigilar la temperatura'], correct:1 }
  ], explanation:'Pustulas peque&#241;as no foliculares con fiebre y neutrofilia a las 36 horas de un antibiotico es una pustulosis exantematica generalizada aguda. La latencia muy corta es lo que mas apoya el origen farmacologico. El cultivo del pus confirma que las pustulas son ESTERILES. Y no hay que a&#241;adir un antibiotico: es inutil, porque no hay infeccion, y arriesgado, porque se introduce otro farmaco en plena farmacodermia.', dificultad:'intermedio' },

  { q:'&#191;Que herramienta sugiere la guia latinoamericana ante duda sobre el farmaco culpable?', options:['El algoritmo ALDEN', 'La prueba de provocacion oral', 'La determinacion de IgE especifica', 'El test de liberacion de histamina'], correct:0, explanation:'ALDEN valora la latencia, si el farmaco estaba presente el dia del inicio, la exposicion previa, la notoriedad del farmaco como causa conocida y las causas alternativas. Es util en el paciente polimedicado, que es la situacion habitual.', dificultad:'dificil' },
  { q:'&#191;Que esta contraindicado de forma absoluta tras una necrolisis epidermica?', options:['La reexposicion al farmaco', 'La vacunacion antigripal anual', 'El uso de cualquier antibiotico', 'La anestesia general futura'], correct:0, explanation:'La reexposicion puede ser mortal, y lo mismo vale tras un DRESS o una pustulosis generalizada. Ese riesgo es todo el motivo del trabajo de identificar al culpable y dejarlo por escrito.', dificultad:'intermedio' },
  { q:'&#191;Cuando se hacen pruebas cutaneas para identificar el farmaco?', options:['Durante la fase aguda del cuadro', 'Antes de retirar el farmaco', 'Solo en el ambito de investigacion', 'En fase de resolucion'], correct:3, explanation:'Las pruebas epicutaneas o intradermicas de lectura retardada y las de transformacion linfocitaria se hacen SIEMPRE en fase de resolucion y en centros con experiencia. La reexposicion controlada esta contraindicada de forma absoluta tras una necrolisis, un DRESS o una pustulosis generalizada.', dificultad:'dificil' },
  { q:'&#191;Que debe incluir el informe de alta tras una farmacodermia?', options:['Solo el nombre del farmaco prohibido', 'La lista completa de la medicacion', 'Una recomendacion de dieta', 'El farmaco y alternativas seguras'], correct:3, explanation:'Un informe que solo dice lo que el paciente no puede tomar deja al siguiente medico sin salida. Hay que anotar el farmaco, la reaccion concreta, la fecha, los congeneres con reactividad cruzada y alternativas seguras para lo que necesite.', dificultad:'intermedio' },
  { q:'En la eritrodermia, &#191;que aporta la biopsia inicial?', options:['Identifica el farmaco responsable', 'Mide la gravedad del cuadro', 'A menudo es inespecifica', 'Confirma siempre la causa'], correct:2, explanation:'En la eritrodermia la histologia suele ser inespecifica al principio y solo despues muestra el patron de la enfermedad de base, de modo que hay que repetirla en varias localizaciones y en el tiempo.', dificultad:'dificil' },
  { q:'&#191;Que hay que hacer antes de retirar farmacos en un paciente polimedicado con exantema?', options:['Escribir la cronologia con fechas', 'Retirar todos a la vez sin mas', 'Pedir niveles plasmaticos de todos', 'Esperar 48 horas de observacion'], correct:0, explanation:'La cronologia escrita de todos los farmacos con sus fechas de inicio suele bastar para descartar la mitad de los sospechosos. Si no se escribe antes, esa informacion se pierde y ya no se puede se&#241;alar al culpable.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 66 a&#241;os ingresado en planta por neumonia, con ceftriaxona desde hace 8 dias. Aparece un exantema maculopapular en tronco que se extiende a los miembros y le pica. No tiene fiebre por encima de 37.2 grados, la boca y los ojos estan normales, la piel no le duele y el hemograma y la bioquimica son normales.', steps:[
    { q:'&#191;Cuantas banderas de gravedad tiene?', options:['Tres o mas', 'Dos', 'Ninguna', 'Las seis'], correct:2 },
    { q:'&#191;Cual es la conducta razonable?', options:['Traslado urgente a quemados', 'Biopsia cutanea inmediata', 'Corticoide sistemico a dosis altas', 'Retirar el farmaco y vigilar'], correct:3 },
    { q:'&#191;Que hay que hacer los dias siguientes?', options:['Repetir la comprobacion de banderas', 'Reintroducir el farmaco para confirmar', 'Suspender toda la medicacion del ingreso', 'Dar el alta de inmediato'], correct:0 }
  ], explanation:'Exantema maculopapular pruriginoso a los 8 dias de un betalactamico, sin ninguna de las seis banderas y con analitica normal: la probabilidad de que sea benigno es alta. Se retira el farmaco, se trata el picor y se vigila. Lo que no hay que dejar de hacer es repetir la comprobacion a diario mientras siga ingresado, porque un exantema aparentemente banal puede ser el primer dia de un DRESS o de una necrolisis.', dificultad:'intermedio' },

  { q:'&#191;Que porcentaje de superficie define la eritrodermia?', options:['Mas del 50%', 'Mas del 70%', 'Mas del 90%', 'El 100% exacto'], correct:2, explanation:'Eritema y descamacion que afectan a mas del 90% de la superficie corporal. Es un patron de reaccion y no una enfermedad: siempre hay una causa detras que hay que buscar.', dificultad:'facil' },
  { q:'&#191;Por que aparece hipoalbuminemia en la eritrodermia?', options:['Por insuficiencia hepatica aguda', 'Por perdida de proteinas por la piel', 'Por hemodilucion masiva', 'Por malabsorcion intestinal'], correct:1, explanation:'La descamacion continua produce una perdida cutanea de proteinas importante. Junto con la perdida de calor y de agua y la insuficiencia cardiaca de alto gasto, es lo que convierte a la piel en un organo en fallo.', dificultad:'intermedio' },
  { q:'&#191;Que tipo de hipersensibilidad es la necrolisis epidermica toxica?', options:['De tipo IVc', 'De tipo I mediada por IgE', 'De tipo II citotoxica por anticuerpos', 'De tipo III por inmunocomplejos'], correct:0, explanation:'Los estudios de inmunofenotipado de los linfocitos presentes en las lesiones han sugerido una hipersensibilidad de tipo IVc, con linfocitos T citotoxicos y celulas asesinas naturales y granulisina como mediador principal.', dificultad:'dificil' },
  { q:'&#191;Que se debe evitar de rutina en la necrolisis epidermica toxica?', options:['La analgesia adecuada del paciente', 'La profilaxis antibiotica sistemica', 'El soporte nutricional precoz', 'El control de la temperatura'], correct:1, explanation:'La profilaxis antibiotica sistemica de rutina no esta indicada. Lo que hay que hacer es buscar la infeccion de forma activa y repetida, porque los signos habituales son poco fiables en una piel denudada.', dificultad:'dificil' },
  { q:'&#191;Que hallazgo histologico define la necrolisis epidermica toxica?', options:['Pustulas subcorneas con neutrofilos', 'Despegamiento en la capa granulosa', 'Infiltrado linfocitario en banda', 'Necrosis de todo el espesor epidermico'], correct:3, explanation:'La necrosis de todo el espesor de la epidermis con despegamiento subepidermico es lo que la define y lo que la separa del sindrome de la piel escaldada estafilococica, cuyo despegamiento es alto, en la capa granulosa.', dificultad:'dificil' }
];

export const flashcards = [
  { front:'&#191;Cuantas farmacodermias son graves?', back:'En torno al 2% de las erupciones cutaneas por farmacos. La gran mayoria son exantemas maculopapulares benignos.' },
  { front:'Las SEIS banderas de gravedad', back:'Fiebre, MUCOSAS, DOLOR cutaneo, EDEMA FACIAL, ampollas o Nikolsky, y alteracion ANALITICA. Una sola cambia el nivel de cuidados.' },
  { front:'Dos datos de alarma que no son banderas', back:'Progresion rapida pese a retirar el farmaco, y lesiones en DIANA ATIPICAS de centro oscuro, que anuncian el despegamiento.' },
  { front:'Exantema maculopapular', back:'Lo mas frecuente. Latencia 4-14 dias, pica, sin mucosas ni analitica alterada. Se resuelve en 1-2 semanas al retirar el farmaco, con descamacion.' },
  { front:'Ventanas de latencia', back:'Urticaria: minutos-horas. Pustulosis aguda: 1-2 dias. Exantema maculopapular: 4-14 dias. Stevens-Johnson y necrolisis: 1-3 semanas. DRESS: 2-8 semanas.' },
  { front:'El error clasico del DRESS', back:'Descartar el farmaco por llevar SEMANAS tomandolo. Esa latencia larga es justo lo esperable en el DRESS.' },
  { front:'Espectro Stevens-Johnson y necrolisis', back:'Se separan por la superficie DESPEGADA: <10% Stevens-Johnson, 10 a <30% solapamiento, 30% o mas necrolisis epidermica toxica.' },
  { front:'&#191;Que superficie se cuenta?', back:'Solo la piel DESPEGADA o despegable, no el eritema. Contar el eritema sobrestima la gravedad. Lund-Browder es mas preciso que la regla de los nueves.' },
  { front:'Mecanismo de la necrolisis epidermica', back:'Hipersensibilidad de tipo IVc: linfocitos T citotoxicos y celulas asesinas naturales, con GRANULISINA como mediador principal.' },
  { front:'Histologia de la necrolisis', back:'Necrosis de TODO el espesor epidermico con despegamiento subepidermico. En el sindrome de la piel escaldada el despegamiento es alto, en la capa granulosa.' },
  { front:'Necrolisis frente a piel escaldada estafilococica', back:'La piel escaldada RESPETA las mucosas y despega en la capa granulosa. En la necrolisis hay dos o mas mucosas afectadas en el 80% de los casos.' },
  { front:'Dolor cutaneo', back:'Que la piel DUELA antes de que aparezcan ampollas es el aviso mas precoz de necrolisis epidermica. Se pregunta muy poco.' },
  { front:'SCORTEN: las 7 variables', back:'Edad 40 o mas, neoplasia, FC 120 o mas, superficie despegada >10%, urea alta, bicarbonato bajo y glucemia alta. Un punto cada una.' },
  { front:'SCORTEN: cuando se calcula', back:'En las primeras 24 horas, y conviene REPETIRLO al tercer dia, porque asi predice mejor. Orienta el nivel de cuidados, no decide el tratamiento.' },
  { front:'Mortalidad de la necrolisis', back:'Del 10 al 40% en fase aguda segun la extension. La causa principal de muerte es la SEPSIS con fallo multiorganico, seguida de la afectacion pulmonar.' },
  { front:'&#191;Que salva vidas en la necrolisis?', back:'El SOPORTE: retirada del farmaco, unidad de quemados precoz, temperatura, volumen, nutricion, analgesia, curas y busqueda activa de infeccion.' },
  { front:'Etanercept frente a prednisolona', back:'Ensayo de 2018 con 91 pacientes: mortalidad 8.3% frente a 16.3% (sin significacion) y reepitelizacion en 14 frente a 19 dias. Certeza baja.' },
  { front:'Lo que NO se hace en la necrolisis', back:'Profilaxis antibiotica sistemica de rutina. Hay que buscar la infeccion de forma activa: los signos habituales fallan en piel denudada.' },
  { front:'Secuelas de la necrolisis', back:'Oculares (ojo seco, simblefaron, ceguera), cutaneas, ungueales, genitales y psicologicas. La valoracion oftalmologica PRECOZ evita buena parte de ellas.' },
  { front:'DRESS: el cuadro', back:'Exantema + fiebre + adenopatias + EOSINOFILIA o linfocitos atipicos + al menos un organo interno. Latencia 2-8 semanas.' },
  { front:'DRESS: el signo mas util', back:'El EDEMA FACIAL. Un exantema con la cara hinchada obliga a pedir hemograma y funcion hepatica ese mismo dia.' },
  { front:'DRESS: organos afectados', back:'Higado (el mas frecuente y el que marca el pronostico), ri&#241;on (nefritis intersticial), pulmon, corazon (miocarditis, a veces tardia) y tiroides.' },
  { front:'DRESS: reactivacion viral', back:'Herpesvirus humano 6 sobre todo. Explica los brotes tardios, el curso ondulante y la recaida al bajar el corticoide.' },
  { front:'DRESS: como se baja el corticoide', back:'LENTAMENTE, en semanas o meses. Un descenso rapido produce recaida.' },
  { front:'DRESS: secuela tardia que se olvida', back:'La TIROIDITIS autoinmune, meses despues, cuando ya nadie relaciona los sintomas con aquel episodio. Vigilar la funcion tiroidea.' },
  { front:'Pustulosis exantematica generalizada aguda', back:'Latencia de 1-2 dias. Decenas de pustulas no foliculares de 2-3 mm sobre eritema, con fiebre y neutrofilia. Cultivo del pus ESTERIL.' },
  { front:'Pustulosis: el diferencial dificil', back:'La psoriasis pustulosa generalizada. A favor del farmaco: latencia corta y clara, fiebre simultanea y resolucion rapida al retirarlo.' },
  { front:'Pustulosis: lo que NO hay que hacer', back:'A&#241;adir un antibiotico. Es inutil (las pustulas son esteriles) y arriesgado (otro farmaco en plena farmacodermia).' },
  { front:'Eritrodermia', back:'Eritema y descamacion en mas del 90% de la superficie. Es un PATRON, no una enfermedad: hipotermia, deshidratacion, hipoalbuminemia e insuficiencia cardiaca de alto gasto.' },
  { front:'Eritrodermia: causas', back:'Por orden: dermatosis previa que se generaliza (psoriasis, atopica, seborreica), FARMACOS, linfoma cutaneo de celulas T, y una minoria idiopatica.' },
  { front:'Eritrodermia: la trampa del corticoide', back:'Si la causa es una psoriasis, el corticoide sistemico es peligroso: su retirada precipita un brote pustuloso. Identificar la causa antes de instaurarlo.' },
  { front:'Lo que cierra el caso', back:'El REGISTRO: farmaco, reaccion concreta y fecha en la historia, informe y tarjeta para el paciente, congeneres con reactividad cruzada, y ALTERNATIVAS SEGURAS.' }
];

export default { quiz, flashcards };
