// topics/miocardiopatias/study.js: Autoevaluación de Miocardiopatías.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Índices `correct` de las 32 preguntas sueltas, en orden: 1,2,0,3,1,2,0,3,2,1,3,0,1,2,3,0,2,1,0,
// 3,1,0,2,3,0,1,3,2,0,1,2,3. Recuento: 0×8, 1×8, 2×8, 3×8. Sin racha >2 ni ciclo fijo.
// Índices `correct` de los pasos de las 5 preguntas en cascada (3 pasos c/u), en orden: 1,3,0 /
// 2,0,3 / 1,2,0 / 3,1,2 / 0,3,1. Recuento: 0×4, 1×4, 2×3, 3×4.

export const quiz = [
  { q: '¿Cuál de las siguientes es la enfermedad cardiaca genética más frecuente en la población general?', options: ['Miocardiopatía dilatada', 'Miocardiopatía hipertrófica', 'Miocardiopatía restrictiva', 'Miocardiopatía arritmogénica del ventrículo derecho'], correct: 1, explanation: 'La miocardiopatía hipertrófica tiene una prevalencia de expresión fenotípica de ~1:500 adultos, lo que la convierte en la enfermedad cardiaca genética más frecuente; también es la causa aislada más común de muerte súbita cardiaca en atletas jóvenes.', dificultad: 'facil' },
  { q: '¿Cuál miocardiopatía es la causa más frecuente de insuficiencia cardiaca no isquémica y la primera indicación de trasplante cardiaco en el adulto?', options: ['Miocardiopatía restrictiva', 'Miocardiopatía arritmogénica del ventrículo derecho', 'Miocardiopatía dilatada', 'Miocardiopatía hipertrófica'], correct: 2, explanation: 'La miocardiopatía dilatada, con una prevalencia estimada de 1:250-1:2500, es la causa más frecuente de insuficiencia cardiaca no isquémica y la principal indicación de trasplante cardiaco en el adulto.', dificultad: 'facil' },
  { q: 'De las tres formas clásicas de miocardiopatía (hipertrófica, dilatada, restrictiva), ¿cuál es la menos frecuente?', options: ['Miocardiopatía restrictiva', 'Miocardiopatía dilatada', 'Miocardiopatía hipertrófica', 'Ninguna: las tres tienen una prevalencia similar'], correct: 0, explanation: 'La miocardiopatía restrictiva representa menos del 5% de las miocardiopatías, la menos frecuente de las tres formas clásicas, aunque la amiloidosis cardiaca (su causa más relevante) está subdiagnosticada.', dificultad: 'facil' },
  { q: '¿En qué población es más subdiagnosticada la amiloidosis cardiaca por transtiretina de tipo wild-type (no hereditaria) como causa de miocardiopatía restrictiva?', options: ['Mujeres jóvenes sin comorbilidades', 'Niños con cardiopatía congénita', 'Adultos jóvenes con miocardiopatía hipertrófica obstructiva', 'Varones mayores de 65-70 años con insuficiencia cardiaca de fracción de eyección preservada'], correct: 3, explanation: 'La amiloidosis por transtiretina wild-type es una causa reconocida pero subdiagnosticada de insuficiencia cardiaca con FEVI preservada en el varón mayor de 65-70 años; su prevalencia real se revisó al alza con la disponibilidad de la gammagrafía con pirofosfato.', dificultad: 'intermedio' },
  { q: '¿En cuál de las siguientes miocardiopatías las mutaciones de proteínas del sarcómero cardiaco (como MYH7 y MYBPC3) son la causa genética más frecuente?', options: ['Miocardiopatía restrictiva', 'Miocardiopatía hipertrófica', 'Miocardiopatía arritmogénica del ventrículo derecho', 'Miocardiopatía periparto'], correct: 1, explanation: 'Las mutaciones de proteínas sarcoméricas, con mayor frecuencia en MYH7 o MYBPC3, son la causa genética más común de la miocardiopatía hipertrófica, con herencia autosómica dominante y penetrancia incompleta.', dificultad: 'facil' },
  { q: 'En la miocardiopatía dilatada "idiopática", ¿qué gen se identifica con mayor frecuencia al realizar un panel genético dirigido?', options: ['PKP2', 'MYBPC3', 'TTN', 'GLA'], correct: 2, explanation: 'El gen TTN (titina) es el que se identifica con mayor frecuencia en la miocardiopatía dilatada de causa no aclarada inicialmente, presente en hasta un tercio de los casos con mutación identificable.', dificultad: 'intermedio' },
  { q: '¿Cuál es el gen mutado con mayor frecuencia en la miocardiopatía arritmogénica del ventrículo derecho?', options: ['PKP2', 'TTN', 'MYH7', 'HFE'], correct: 0, explanation: 'PKP2, que codifica una proteína del desmosoma (placofilina-2), es el gen mutado con mayor frecuencia en la miocardiopatía arritmogénica del ventrículo derecho.', dificultad: 'facil' },
  { q: 'En la miocardiopatía dilatada, la mutación de un gen específico se asocia a un riesgo arrítmico particularmente alto (bloqueo auriculoventricular progresivo y arritmia ventricular), independiente del grado de disfunción sistólica. ¿Cuál es ese gen?', options: ['MYBPC3', 'PKP2', 'TTN', 'LMNA'], correct: 3, explanation: 'Las mutaciones del gen LMNA (lámina A/C) se asocian a un riesgo arrítmico desproporcionadamente alto en la miocardiopatía dilatada, con bloqueo auriculoventricular progresivo característico en el electrocardiograma, independiente de la FEVI.', dificultad: 'dificil' },
  { q: 'En la miocardiopatía hipertrófica obstructiva, ¿qué maniobra clínica AUMENTA la intensidad del soplo sistólico?', options: ['Squatting (posición en cuclillas)', 'Handgrip sostenido', 'Maniobra de Valsalva', 'Elevación pasiva de las piernas'], correct: 2, explanation: 'La maniobra de Valsalva reduce la precarga y el volumen ventricular, lo que acerca la valva mitral anterior al septo hipertrofiado y aumenta el gradiente de obstrucción; por eso el soplo se intensifica, un patrón opuesto al de la estenosis aórtica.', dificultad: 'intermedio' },
  { q: '¿Qué maniobra clínica DISMINUYE la intensidad del soplo sistólico en la miocardiopatía hipertrófica obstructiva?', options: ['Bipedestación súbita', 'Squatting (posición en cuclillas)', 'Maniobra de Valsalva', 'Deshidratación'], correct: 1, explanation: 'El squatting aumenta la precarga y la poscarga, lo que aumenta el volumen ventricular y aleja la valva mitral anterior del septo, reduciendo el gradiente de obstrucción y la intensidad del soplo.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo del pulso arterial es característico de la miocardiopatía hipertrófica obstructiva?', options: ['Pulso paradójico', 'Pulso alternante', 'Pulso parvus et tardus', 'Pulso bisferiens'], correct: 3, explanation: 'El pulso bisferiens (dos picos sistólicos palpables) es característico de la miocardiopatía hipertrófica obstructiva, por la eyección inicial rápida seguida de la caída abrupta del flujo cuando se instala la obstrucción dinámica a mitad de la sístole.', dificultad: 'intermedio' },
  { q: '¿En cuál de las siguientes miocardiopatías es más característico encontrar el signo de Kussmaul (aumento paradójico de la presión venosa yugular con la inspiración)?', options: ['Miocardiopatía restrictiva', 'Miocardiopatía dilatada', 'Miocardiopatía periparto', 'Miocardiopatía hipertrófica no obstructiva'], correct: 0, explanation: 'El signo de Kussmaul refleja la incapacidad del ventrículo derecho rígido para acomodar el aumento del retorno venoso durante la inspiración, un hallazgo característico de la miocardiopatía restrictiva (y de la pericarditis constrictiva, su principal diagnóstico diferencial).', dificultad: 'facil' },
  { q: 'Ante la sospecha de amiloidosis cardiaca, ¿cuál es el estudio que debe solicitarse ANTES de la gammagrafía con pirofosfato?', options: ['Resonancia magnética cardiaca con gadolinio', 'Electroforesis de proteínas séricas/urinarias con cadenas ligeras libres', 'Biopsia endomiocárdica', 'Prueba de esfuerzo con respuesta tensional'], correct: 1, explanation: 'Debe descartarse primero una gammapatía monoclonal (amiloidosis de cadenas ligeras) mediante electroforesis y cadenas ligeras libres, porque la gammagrafía con pirofosfato puede ser falsamente positiva en esa forma si no se interpreta en el contexto correcto.', dificultad: 'intermedio' },
  { q: '¿Cuál es el tratamiento farmacológico dirigido específico de la amiloidosis cardiaca por transtiretina sintomática?', options: ['Espironolactona', 'Sacubitrilo/valsartán', 'Tafamidis', 'Mavacamten'], correct: 2, explanation: 'El tafamidis, un estabilizador de la transtiretina, es el tratamiento dirigido específico de la amiloidosis cardiaca por transtiretina sintomática, y ha demostrado reducir la mortalidad y las hospitalizaciones.', dificultad: 'facil' },
  { q: '¿Cuál es el tratamiento farmacológico dirigido específico de la miocardiopatía periparto, sin equivalente en las demás miocardiopatías de esta sección?', options: ['Tafamidis', 'Mavacamten', 'Flebotomía terapéutica', 'Bromocriptina'], correct: 3, explanation: 'La bromocriptina, un inhibidor de la secreción de prolactina, es la terapia dirigida específica de la miocardiopatía periparto, basada en el mecanismo fisiopatológico propuesto de un fragmento de prolactina antiangiogénico.', dificultad: 'intermedio' },
  { q: '¿Cuál es el mecanismo de acción del mavacamten, un fármaco de segunda línea en la miocardiopatía hipertrófica obstructiva sintomática?', options: ['Inhibidor de la miosina cardiaca, con efecto inótropo negativo directo', 'Bloqueador de los canales de calcio tipo L', 'Antagonista del receptor de mineralocorticoides', 'Estabilizador de la transtiretina'], correct: 0, explanation: 'El mavacamten es un inhibidor de la miosina cardiaca que reduce la formación de puentes cruzados actina-miosina, con un efecto inótropo negativo directo; requiere vigilancia ecocardiográfica seriada de la FEVI durante su uso.', dificultad: 'intermedio' },
  { q: '¿Cuál de los siguientes fármacos es uno de los 4 pilares farmacológicos estándar de la insuficiencia cardiaca con fracción de eyección reducida en la miocardiopatía dilatada?', options: ['Verapamilo', 'Tafamidis', 'Inhibidor de SGLT2', 'Bromocriptina'], correct: 2, explanation: 'El inhibidor de SGLT2 (dapagliflozina o empagliflozina) es uno de los 4 pilares farmacológicos de la insuficiencia cardiaca con FEVI reducida, junto con el inhibidor del receptor de angiotensina-neprilisina (o IECA/ARA-II), el betabloqueador y el antagonista del receptor de mineralocorticoides; los otros fármacos listados son tratamientos dirigidos de otras miocardiopatías.', dificultad: 'facil' },
  { q: '¿Cuál es el criterio estándar de FEVI para indicar un cardiodesfibrilador implantable en prevención primaria en la miocardiopatía dilatada, tras al menos 3 meses de tratamiento médico óptimo?', options: ['FEVI ≤50%', 'FEVI ≤35%', 'FEVI ≤45%', 'FEVI ≤25%'], correct: 1, explanation: 'El CDI en prevención primaria se indica con FEVI ≤35% pese a al menos 3 meses de tratamiento médico óptimo, salvo consideraciones especiales por etiología (como la mutación de LMNA, donde el umbral de indicación puede ser más bajo).', dificultad: 'intermedio' },
  { q: 'Un paciente con miocardiopatía hipertrófica tiene un HCM Risk-SCD de 7% a 5 años. ¿Cómo se clasifica este riesgo y qué implica?', options: ['Riesgo alto; se considera la indicación de un cardiodesfibrilador implantable', 'Riesgo bajo; no se requiere ninguna acción adicional', 'Riesgo intermedio; se individualiza sin considerar el CDI', 'El HCM Risk-SCD no aplica a partir del 5%, requiere otro modelo'], correct: 0, explanation: 'Un HCM Risk-SCD ≥6% se clasifica como riesgo alto, y apoya considerar la indicación de un cardiodesfibrilador implantable, siempre integrado con el juicio clínico.', dificultad: 'facil' },
  { q: '¿En cuál de las siguientes situaciones el modelo HCM Risk-SCD NO ha sido validado y no debe aplicarse?', options: ['En pacientes con antecedente familiar de muerte súbita', 'En pacientes con taquicardia ventricular no sostenida documentada', 'En pacientes con síncope inexplicado', 'En atletas de alto rendimiento con hipertrofia fisiológica del corazón de atleta'], correct: 3, explanation: 'El HCM Risk-SCD no debe aplicarse en menores de 16 años, en atletas de alto rendimiento con hipertrofia fisiológica ("corazón de atleta", que no es miocardiopatía hipertrófica verdadera), ni tras miectomía/ablación septal previas; las otras tres opciones son justamente las variables que el modelo sí incorpora.', dificultad: 'dificil' },
  { q: '¿Cuál es la intervención con mayor evidencia para enlentecer la progresión estructural y reducir el riesgo arrítmico en la miocardiopatía arritmogénica del ventrículo derecho?', options: ['El tratamiento con un antiarrítmico de clase III desde el diagnóstico', 'La restricción estricta del ejercicio físico de competición y de resistencia de alta intensidad', 'La colocación temprana de un marcapasos definitivo', 'La anticoagulación oral profiláctica'], correct: 1, explanation: 'La restricción del ejercicio físico de alta intensidad, incluso en portadores asintomáticos de una mutación patogénica, es la intervención con mayor evidencia para enlentecer la progresión estructural y reducir el riesgo arrítmico en la miocardiopatía arritmogénica.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo electrocardiográfico es característico (aunque no diagnóstico de forma aislada) de la miocardiopatía arritmogénica del ventrículo derecho?', options: ['Onda épsilon', 'Onda Q patológica en derivaciones inferiores', 'Intervalo QT corto', 'Elevación difusa del segmento ST con concavidad superior'], correct: 0, explanation: 'La onda épsilon, una pequeña deflexión al final del complejo QRS en las derivaciones precordiales derechas, es un hallazgo característico (criterio mayor de despolarización) de la miocardiopatía arritmogénica del ventrículo derecho, aunque no es diagnóstica de forma aislada.', dificultad: 'intermedio' },
  { q: '¿Qué aportan los criterios de Padua (2020) frente al Task Force Criteria original (2010) para el diagnóstico de la miocardiopatía arritmogénica?', options: ['Eliminan la necesidad de estudio genético', 'Sustituyen por completo a la ecocardiografía por la resonancia magnética', 'Incorporan criterios específicos del ventrículo izquierdo, identificando formas biventriculares y de dominancia izquierda', 'Reducen el número de categorías diagnósticas de seis a tres'], correct: 2, explanation: 'Los criterios de Padua 2020 añaden categorías específicas para el ventrículo izquierdo (realce tardío de gadolinio de la pared libre, disfunción/dilatación del VI), identificando formas biventriculares y de dominancia izquierda que el Task Force original de 2010 no capturaba.', dificultad: 'intermedio' },
  { q: '¿En cuáles de las siguientes miocardiopatías la sola presencia de fibrilación auricular documentada ya indica anticoagulación oral, sin necesidad de calcular el CHA₂DS₂-VASc?', options: ['Miocardiopatía dilatada y periparto', 'Miocardiopatía arritmogénica del ventrículo derecho únicamente', 'Ninguna: el CHA₂DS₂-VASc siempre debe calcularse antes de anticoagular', 'Miocardiopatía hipertrófica y amiloidosis cardiaca (restrictiva)'], correct: 3, explanation: 'En la miocardiopatía hipertrófica y en la amiloidosis cardiaca, cualquier episodio de fibrilación auricular documentado ya indica anticoagulación oral, independientemente del puntaje CHA₂DS₂-VASc, por el riesgo trombótico intrínsecamente elevado de estas dos entidades.', dificultad: 'dificil' },
  { q: '¿Qué distingue el chorro de insuficiencia mitral funcional de la miocardiopatía hipertrófica obstructiva (relacionada al SAM) del de la miocardiopatía dilatada (por tethering)?', options: ['En la hipertrófica el chorro es característicamente póstero-lateral; en la dilatada es central', 'En la hipertrófica el chorro es central; en la dilatada es póstero-lateral', 'Ambos tienen siempre un chorro central indistinguible entre sí', 'El mecanismo es idéntico en ambas, solo cambia la gravedad'], correct: 0, explanation: 'En la miocardiopatía hipertrófica obstructiva, la insuficiencia mitral relacionada con el movimiento sistólico anterior (SAM) produce un chorro característicamente póstero-lateral; en la dilatada, el tethering de los músculos papilares produce típicamente un chorro central.', dificultad: 'dificil' },
  { q: 'En la miocardiopatía hipertrófica obstructiva con insuficiencia mitral relacionada al SAM, ¿cuál es la conducta terapéutica más apropiada?', options: ['Reparación mitral transcatéter borde a borde como primera línea', 'Tratar la obstrucción del tracto de salida (miectomía septal o ablación con alcohol), lo que resuelve la insuficiencia mitral en la mayoría de los casos', 'Reemplazo valvular mitral quirúrgico de entrada, sin tratar la obstrucción', 'Terapia de resincronización cardiaca'], correct: 1, explanation: 'A diferencia de la insuficiencia mitral funcional de la miocardiopatía dilatada, la relacionada al SAM en la hipertrófica es consecuencia directa de la obstrucción: tratar la obstrucción (miectomía septal o ablación con alcohol) resuelve la insuficiencia mitral en la mayoría de los casos, sin necesidad de cirugía valvular directa.', dificultad: 'intermedio' },
  { q: '¿Cuál de los siguientes grupos farmacológicos está CONTRAINDICADO en el tratamiento de la miocardiopatía periparto ANTES del parto, por su teratogenicidad?', options: ['Betabloqueadores cardioselectivos', 'Diuréticos de asa', 'Antagonistas de los receptores de mineralocorticoides, solo por falta de datos de seguridad', 'IECA/ARA-II y sacubitrilo/valsartán'], correct: 3, explanation: 'Los IECA/ARA-II y el sacubitrilo/valsartán están contraindicados durante el embarazo por su teratogenicidad, y se sustituyen por hidralazina más nitrato hasta después del parto; el betabloqueador cardioselectivo (metoprolol) es seguro en ambas etapas.', dificultad: 'intermedio' },
  { q: '¿Qué proporción aproximada de las pacientes con miocardiopatía periparto recupera la función sistólica normal o casi normal dentro de los primeros 6-12 meses?', options: ['Menos del 10%', 'Prácticamente el 100%', 'Hasta la mitad (~50%)', 'Ninguna: la disfunción siempre es permanente'], correct: 2, explanation: 'Hasta la mitad de las pacientes con miocardiopatía periparto recupera la función sistólica normal o casi normal dentro de los primeros 6-12 meses, lo que la distingue del resto de las miocardiopatías de esta sección por su mejor potencial de recuperación.', dificultad: 'facil' },
  { q: '¿Qué hallazgo combinado en el electrocardiograma y el ecocardiograma es característico ("discordancia electro-ecocardiográfica") de la amiloidosis cardiaca?', options: ['Bajo voltaje periférico en el ECG pese a hipertrofia parietal marcada en el ecocardiograma', 'Voltaje elevado en el ECG con grosor parietal normal en el ecocardiograma', 'Bajo voltaje en el ECG con grosor parietal normal en el ecocardiograma', 'Voltaje elevado en el ECG proporcional al grosor parietal en el ecocardiograma'], correct: 0, explanation: 'La discordancia entre el bajo voltaje periférico del electrocardiograma y el grosor parietal marcadamente aumentado en el ecocardiograma es una pista clásica de amiloidosis cardiaca, porque el tejido amiloide infiltrado no genera el voltaje eléctrico que correspondería a esa masa miocárdica.', dificultad: 'intermedio' },
  { q: 'De las siguientes dos entidades, ¿cuál es potencialmente curable mediante pericardiectomía quirúrgica?', options: ['Miocardiopatía restrictiva por amiloidosis', 'Pericarditis constrictiva', 'Miocardiopatía restrictiva por hemocromatosis no tratada', 'Ninguna de las dos tiene tratamiento quirúrgico curativo'], correct: 1, explanation: 'La pericarditis constrictiva, a diferencia de la mayoría de las causas de miocardiopatía restrictiva, es potencialmente curable mediante pericardiectomía quirúrgica: distinguirla de la restrictiva mediante hemodinamia invasiva tiene un impacto terapéutico directo.', dificultad: 'facil' },
  { q: '¿Qué patrón de realce tardío de gadolinio en la resonancia magnética cardiaca es característico de la miocardiopatía dilatada no isquémica, a diferencia del patrón de la cardiopatía isquémica?', options: ['Subendocárdico, siguiendo un territorio coronario', 'Transmural, siguiendo un territorio coronario', 'Medioparietal, sin distribución coronaria', 'Ausencia total de realce en cualquier caso'], correct: 2, explanation: 'El realce tardío de gadolinio de patrón medioparietal, sin distribución de un territorio coronario específico, es característico de la miocardiopatía dilatada no isquémica; el patrón subendocárdico/transmural siguiendo un territorio coronario es propio de la cardiopatía isquémica.', dificultad: 'intermedio' },
  { q: 'Para el diagnóstico de cualquier miocardiopatía según la clasificación morfofuncional, ¿qué debe excluirse primero como causa suficiente de la anormalidad observada?', options: ['Únicamente la cardiopatía congénita', 'Únicamente la valvulopatía', 'Únicamente la hipertensión arterial', 'Enfermedad coronaria, hipertensión arterial, valvulopatía y cardiopatía congénita suficientes para explicar la anormalidad'], correct: 3, explanation: 'La definición morfofuncional de miocardiopatía exige que la anormalidad estructural/funcional del miocardio NO se explique por enfermedad coronaria, hipertensión arterial, valvulopatía ni cardiopatía congénita suficientes para justificarla; de lo contrario, se trata de cardiopatía secundaria a esas causas, no de una miocardiopatía primaria.', dificultad: 'facil' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 17 años, jugador de fútbol americano, presenta un episodio de síncope durante un entrenamiento de alta intensidad. Su padre falleció súbitamente a los 40 años sin causa aclarada. El ecocardiograma muestra un grosor parietal septal de 22 mm, sin dilatación de cavidades, y un gradiente en el tracto de salida del ventrículo izquierdo de 15 mmHg en reposo que aumenta a 60 mmHg con la maniobra de Valsalva.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable?', options: ['Corazón de atleta (hipertrofia fisiológica de entrenamiento)', 'Miocardiopatía hipertrófica obstructiva', 'Miocardiopatía dilatada en fase temprana', 'Hipertensión arterial no diagnosticada con hipertrofia secundaria'], correct: 1 },
      { q: '¿Qué hallazgo adicional del caso constituye por sí solo un factor mayor de riesgo de muerte súbita?', options: ['La edad del paciente (17 años)', 'El grosor parietal de 22 mm, sin ningún otro contexto', 'La práctica de fútbol americano', 'El síncope inexplicado de esfuerzo, junto con el antecedente familiar de muerte súbita'], correct: 3 },
      { q: '¿Cuál es la conducta más apropiada respecto al riesgo arrítmico de este paciente?', options: ['Calcular el HCM Risk-SCD y discutir la indicación de un cardiodesfibrilador implantable', 'Tranquilizar a la familia: el síncope de esfuerzo en un adolescente deportista es benigno por definición', 'Indicar amiodarona de forma indefinida sin más estudio', 'Autorizar el regreso inmediato a la competición de alto rendimiento sin restricciones'], correct: 0 }
    ],
    explanation: 'El síncope de esfuerzo y el antecedente familiar de muerte súbita en un paciente con hipertrofia septal asimétrica y obstrucción dinámica del tracto de salida configuran el cuadro clásico de miocardiopatía hipertrófica obstructiva de alto riesgo arrítmico. Ambos son factores mayores de riesgo de muerte súbita; la conducta apropiada es estratificar formalmente el riesgo (HCM Risk-SCD y factores mayores adicionales) y discutir la indicación de un cardiodesfibrilador implantable, además de restringir el ejercicio de alta intensidad hasta completar la evaluación.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 50 años, con consumo diario de alcohol durante 15 años, acude por disnea progresiva de 3 meses de evolución, ahora con ortopnea y edema de miembros inferiores. El ecocardiograma muestra dilatación del ventrículo izquierdo con FEVI de 25%, sin valvulopatía significativa. La coronariografía es normal.',
    steps: [
      { q: '¿Cuál es la conducta inicial más importante, además de iniciar tratamiento médico de insuficiencia cardiaca?', options: ['Indicar cardiodesfibrilador implantable de inmediato, sin esperar reevaluación', 'Suspender toda actividad física de forma permanente e indefinida', 'Recomendar la suspensión completa del consumo de alcohol, dado su potencial de recuperación parcial o total de la FEVI', 'Referir directamente a trasplante cardiaco sin ensayar tratamiento médico'], correct: 2 },
      { q: 'Se inicia tratamiento médico. ¿Cuáles son los 4 pilares farmacológicos que deben iniciarse y titularse en paralelo?', options: ['Inhibidor del receptor de angiotensina-neprilisina (o IECA/ARA-II), betabloqueador, antagonista de mineralocorticoides e inhibidor de SGLT2', 'Solo diurético de asa y digoxina', 'Verapamilo, mavacamten y tafamidis', 'Bromocriptina y anticoagulación profiláctica'], correct: 0 },
      { q: 'Tres meses después, con tratamiento médico óptimo y suspensión del alcohol, la FEVI persiste en 30%. ¿Cuál es la conducta más apropiada?', options: ['Continuar solo con vigilancia clínica, sin reevaluar dispositivos', 'Trasplante cardiaco inmediato, sin más estudio', 'Suspender el tratamiento médico por falta de respuesta', 'Evaluar candidatura a cardiodesfibrilador implantable en prevención primaria, dado que la FEVI persiste ≤35%'], correct: 3 }
    ],
    explanation: 'El primer paso ante una miocardiopatía dilatada con causa tóxica identificable es eliminarla (el alcohol tiene potencial real de recuperación parcial o total de la FEVI), en paralelo con el inicio de los 4 pilares farmacológicos de la insuficiencia cardiaca con FEVI reducida. Si tras al menos 3 meses de tratamiento médico óptimo la FEVI persiste ≤35%, se evalúa la candidatura a un cardiodesfibrilador implantable en prevención primaria.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 72 años presenta disnea de esfuerzo progresiva, edema de miembros inferiores y ascitis, con ingurgitación yugular marcada que aumenta paradójicamente con la inspiración. El ecocardiograma muestra grosor parietal aumentado con biauriculomegalia y patrón de llenado restrictivo, con FEVI preservada. El electrocardiograma muestra bajo voltaje periférico.',
    steps: [
      { q: '¿Qué signo clínico descrito en el caso es característico de la fisiología restrictiva?', options: ['Pulso bisferiens', 'Signo de Kussmaul (aumento paradójico de la presión venosa yugular con la inspiración)', 'Pulso paradójico mayor a 10 mmHg', 'Soplo que aumenta con Valsalva'], correct: 1 },
      { q: 'La combinación de grosor parietal aumentado en el ecocardiograma con bajo voltaje en el electrocardiograma orienta principalmente hacia:', options: ['Miocardiopatía hipertrófica sarcomérica típica', 'Corazón de atleta', 'Amiloidosis cardiaca', 'Hipertensión arterial de larga evolución'], correct: 2 },
      { q: '¿Cuál es el primer estudio que debe solicitarse para orientar la etiología de la amiloidosis, antes de la gammagrafía con pirofosfato?', options: ['Electroforesis de proteínas séricas/urinarias y cadenas ligeras libres', 'Biopsia endomiocárdica de entrada', 'Cateterismo cardiaco derecho e izquierdo', 'Resonancia magnética cardiaca sin estudio sérico previo'], correct: 0 }
    ],
    explanation: 'El signo de Kussmaul, la biauriculomegalia con patrón de llenado restrictivo y la discordancia entre el grosor parietal aumentado y el bajo voltaje electrocardiográfico configuran el cuadro clásico de amiloidosis cardiaca. Antes de la gammagrafía con pirofosfato, debe descartarse una gammapatía monoclonal (amiloidosis de cadenas ligeras) mediante electroforesis y cadenas ligeras libres, porque el pirofosfato puede ser falsamente positivo en esa forma si no se interpreta en el contexto correcto.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 22 años, jugador de fútbol amateur, presenta palpitaciones sostenidas durante un partido, seguidas de presíncope. El electrocardiograma en reposo muestra inversión de la onda T en V1-V3 y una onda épsilon. El ecocardiograma muestra dilatación segmentaria del ventrículo derecho con un aneurisma en el tracto de entrada.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable?', options: ['Taquicardia ventricular idiopática del tracto de salida del VD, con corazón estructuralmente normal', 'Corazón de atleta con adaptación fisiológica del ventrículo derecho', 'Miocarditis viral aguda', 'Miocardiopatía arritmogénica del ventrículo derecho'], correct: 3 },
      { q: '¿Cuál es la intervención inicial con mayor evidencia para enlentecer la progresión de esta enfermedad?', options: ['Ablación por catéter inmediata, antes de cualquier otra medida', 'Restricción estricta del ejercicio físico de competición y de resistencia de alta intensidad', 'Anticoagulación oral profiláctica', 'Reposo relativo, sin restricción específica del deporte de competición'], correct: 1 },
      { q: 'Se confirma el diagnóstico y se documenta taquicardia ventricular sostenida con inestabilidad hemodinámica durante el seguimiento. ¿Cuál es la conducta más apropiada?', options: ['Betabloqueador en monoterapia, sin otra medida', 'Vigilancia ambulatoria, sin intervención adicional', 'Cardiodesfibrilador implantable en prevención secundaria', 'Trasplante cardiaco inmediato'], correct: 2 }
    ],
    explanation: 'La combinación de palpitaciones/presíncope de esfuerzo, la onda épsilon, la inversión de T en precordiales derechas y el aneurisma segmentario del ventrículo derecho configuran el diagnóstico de miocardiopatía arritmogénica del ventrículo derecho. La restricción del ejercicio de alta intensidad es la intervención inicial con mayor evidencia; ante taquicardia ventricular sostenida con inestabilidad hemodinámica ya documentada, el cardiodesfibrilador implantable en prevención secundaria es la indicación firme.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 32 años, 3 semanas posparto, primer embarazo sin complicaciones prenatales documentadas, presenta disnea progresiva, ortopnea y edema de miembros inferiores. El ecocardiograma muestra FEVI de 30%, sin dilatación marcada, y no hay antecedente de cardiopatía previa.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable?', options: ['Miocardiopatía periparto', 'Disnea fisiológica normal del puerperio', 'Embolia pulmonar aislada, sin compromiso miocárdico', 'Miocardiopatía hipertrófica no diagnosticada previamente'], correct: 0 },
      { q: '¿Cuál es el tratamiento farmacológico dirigido específico que debe añadirse al tratamiento estándar de insuficiencia cardiaca?', options: ['Tafamidis', 'Mavacamten', 'Verapamilo', 'Bromocriptina, junto con anticoagulación profiláctica concomitante'], correct: 3 },
      { q: 'La paciente pregunta sobre un embarazo futuro. ¿Qué debe orientar la asesoría reproductiva?', options: ['No hay ningún riesgo de recurrencia si el embarazo se planea después de 1 año', 'El riesgo de recurrencia es significativo, mayor cuanto menor sea la FEVI de recuperación alcanzada; debe reevaluarse antes de decidir', 'Un nuevo embarazo está formalmente contraindicado de por vida en cualquier caso', 'El riesgo de recurrencia es idéntico independientemente del grado de recuperación de la FEVI'], correct: 1 }
    ],
    explanation: 'La insuficiencia cardiaca de novo hacia el final del embarazo o en el puerperio, sin cardiopatía previa ni otra causa identificable, define la miocardiopatía periparto. La bromocriptina, sumada a la anticoagulación profiláctica por su propio riesgo protrombótico, es la terapia dirigida específica de este subtipo. Antes de un embarazo posterior, la asesoría reproductiva debe considerar que el riesgo de recurrencia es significativo y mayor cuanto menor sea la FEVI de recuperación alcanzada.'
  }
];

export const flashcards = [
  { front: 'Miocardiopatía genética más frecuente', back: 'Hipertrófica (~1:500 adultos); también la causa más común de muerte súbita en atletas jóvenes.' },
  { front: 'Miocardiopatía más frecuente como causa de trasplante cardiaco', back: 'Dilatada: primera causa de insuficiencia cardiaca no isquémica y de trasplante en el adulto.' },
  { front: 'Genes más frecuentes por subtipo', back: 'Hipertrófica: MYH7/MYBPC3 (sarcómero). Dilatada: TTN. Arritmogénica: PKP2 (desmosoma). LMNA (dilatada): alto riesgo arrítmico.' },
  { front: 'Soplo de la hipertrófica obstructiva: qué lo aumenta y qué lo disminuye', back: 'Aumenta con Valsalva/bipedestación (↓precarga). Disminuye con squatting/handgrip (↑precarga/poscarga): patrón opuesto a la estenosis aórtica.' },
  { front: 'Pulso característico de la hipertrófica obstructiva', back: 'Pulso bisferiens (dos picos sistólicos).' },
  { front: 'Signo de Kussmaul: en qué miocardiopatía', back: 'Restrictiva: aumento paradójico de la presión venosa yugular con la inspiración.' },
  { front: 'Orden de estudio ante sospecha de amiloidosis cardiaca', back: 'Cadenas ligeras libres/electroforesis PRIMERO → si negativo, gammagrafía con pirofosfato (capta en ATTR, no en AL).' },
  { front: 'Discordancia electro-ecocardiográfica', back: 'Bajo voltaje en el ECG pese a grosor parietal aumentado en el eco: pista clásica de amiloidosis cardiaca.' },
  { front: 'Tratamiento dirigido de la amiloidosis por transtiretina', back: 'Tafamidis (estabilizador de transtiretina).' },
  { front: 'Restrictiva vs. constrictiva: cuál es quirúrgicamente curable', back: 'La pericarditis constrictiva, mediante pericardiectomía; la restrictiva rara vez lo es.' },
  { front: 'HCM Risk-SCD: bandas de riesgo a 5 años', back: '<4% bajo; 4-<6% intermedio; ≥6% alto (considerar CDI).' },
  { front: 'HCM Risk-SCD: en quién NO debe aplicarse', back: 'Menores de 16 años, atletas de alto rendimiento con hipertrofia fisiológica, o tras miectomía/ablación septal previas.' },
  { front: 'Mavacamten: mecanismo', back: 'Inhibidor de la miosina cardiaca, efecto inótropo negativo directo; vigilar FEVI seriada.' },
  { front: 'Indicación quirúrgica en la hipertrófica obstructiva refractaria', back: 'Miectomía septal (de elección) o ablación septal con alcohol si gradiente ≥50 mmHg con síntomas pese a tratamiento médico.' },
  { front: '4 pilares farmacológicos de la IC-FEr (miocardiopatía dilatada)', back: 'ARNI (o IECA/ARA-II) + betabloqueador + antagonista de mineralocorticoides + inhibidor de SGLT2.' },
  { front: 'CDI en prevención primaria en la dilatada: umbral de FEVI', back: 'FEVI ≤35% pese a ≥3 meses de tratamiento médico óptimo.' },
  { front: 'Onda épsilon: en qué miocardiopatía', back: 'Arritmogénica del ventrículo derecho (criterio mayor de despolarización, Task Force Criteria).' },
  { front: 'Intervención con mayor evidencia en la arritmogénica del VD', back: 'Restricción estricta del ejercicio de alta intensidad, incluso en portadores asintomáticos.' },
  { front: 'Criterios de Padua 2020: qué añaden', back: 'Categorías específicas del ventrículo izquierdo, identificando formas biventriculares/de dominancia izquierda no capturadas por el Task Force 2010.' },
  { front: 'Fibrilación auricular: en qué 2 miocardiopatías se anticoagula sin calcular CHA₂DS₂-VASc', back: 'Hipertrófica y amiloidosis cardiaca (restrictiva): cualquier episodio documentado ya indica anticoagulación.' },
  { front: 'Insuficiencia mitral funcional: mecanismo y chorro por subtipo', back: 'Dilatada: tethering, chorro central. Hipertrófica (SAM): chorro póstero-lateral, se resuelve tratando la obstrucción.' },
  { front: 'Tratamiento dirigido específico de la miocardiopatía periparto', back: 'Bromocriptina + anticoagulación profiláctica concomitante.' },
  { front: 'Fármacos contraindicados en la periparto ANTES del parto', back: 'IECA/ARA-II y sacubitrilo/valsartán (teratogénicos): sustituir por hidralazina + nitrato.' },
  { front: 'Pronóstico de recuperación de la miocardiopatía periparto', back: 'Hasta ~50% recupera FEVI normal o casi normal en 6-12 meses; el subtipo con mejor potencial de recuperación.' },
  { front: 'Patrón de realce tardío de gadolinio: dilatada no isquémica vs. isquémica', back: 'Dilatada no isquémica: medioparietal, sin territorio coronario. Isquémica: subendocárdico/transmural, sí territorio coronario.' },
  { front: 'Definición morfofuncional de miocardiopatía: qué debe excluirse primero', back: 'Enfermedad coronaria, hipertensión arterial, valvulopatía y cardiopatía congénita suficientes para explicar la anormalidad.' }
];

export const caseSteps = [];
export const caseSummary = undefined;

export default { quiz, flashcards, caseSteps, caseSummary };
