// topics/epoc/study.js: Autoevaluacion de EPOC.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// 48 subpreguntas (30 sueltas + 6 cascadas de 3 pasos) y 32 tarjetas.
// Distribucion de `correct` en el banco completo: 12 en la posicion 0, 12 en la 1, 11 en la 2
// y 13 en la 3. Sin em dash (ver [[feedback-no-em-dash]]). Texto sin acentos.

export const quiz = [
  { q: 'Que prueba es imprescindible para diagnosticar una EPOC?', options: ['La radiografia de torax con hiperinsuflacion', 'La tomografia que cuantifica el enfisema', 'La espirometria posbroncodilatador', 'La gasometria arterial en aire ambiente'], correct: 2, explanation: 'Sin espirometria no hay EPOC: el cociente FEV1/FVC posbroncodilatador por debajo de 0.70 es condicion necesaria del diagnostico. La radiografia sirve para excluir otras causas, la tomografia para valorar el enfisema y la cirugia, y la gasometria para detectar insuficiencia respiratoria, pero ninguna diagnostica la enfermedad.', dificultad: 'facil' },
  { q: 'Que valor del cociente FEV1/FVC posbroncodilatador define la obstruccion?', options: ['Por debajo de 0.70', 'Por debajo de 0.80', 'Por debajo de 0.60', 'Por debajo de 0.50'], correct: 0, explanation: 'El umbral fijo de 0.70 es el criterio de GOLD por su simplicidad. Tiene el precio conocido de sobrediagnosticar al anciano e infradiagnosticar al joven, por lo que en casos limite se contrasta con el limite inferior de la normalidad para la edad y con la clinica.', dificultad: 'facil' },
  { q: 'Que informacion aporta el grado espirometrico GOLD 1 a 4?', options: ['La carga de sintomas del paciente', 'El riesgo de exacerbar en el proximo a&#241;o', 'La indicacion de corticoide inhalado', 'La magnitud de la obstruccion y el pronostico'], correct: 3, explanation: 'El grado se calcula con el FEV1 en porcentaje del predicho y aporta informacion pronostica, pero se correlaciona mal con los sintomas. El tratamiento inicial lo decide el grupo A, B o E, no el grado: un GOLD 4 poco sintomatico y sin exacerbaciones es grupo A.', dificultad: 'intermedio' },
  { q: 'Que define al paciente como grupo E de GOLD?', options: ['Una disnea mMRC de 2 o superior', 'Dos exacerbaciones moderadas o un ingreso', 'Un FEV1 por debajo del 30% del valor predicho', 'Un recuento de eosinofilos de 300 o mas'], correct: 1, explanation: 'El grupo E se define solo por la historia de exacerbaciones del ultimo a&#241;o y prescinde a proposito de los sintomas: quien exacerba tiene un problema distinto del que solo se ahoga. Los eosinofilos no definen el grupo, deciden si se a&#241;ade corticoide inhalado dentro de el.', dificultad: 'intermedio' },
  { q: 'Cual es el tratamiento inicial del paciente en grupo B de GOLD?', options: ['LABA mas LAMA', 'LABA mas corticoide inhalado', 'LAMA mas corticoide inhalado', 'LABA en monoterapia'], correct: 0, explanation: 'La doble broncodilatacion con LABA mas LAMA supera a cualquier monoterapia en sintomas y funcion pulmonar, y por eso GOLD abandono la monoterapia en el paciente sintomatico. El corticoide inhalado no entra de inicio en el grupo B, que por definicion no es exacerbador.', dificultad: 'intermedio' },
  { q: 'Que recuento de eosinofilos apoya la triple terapia de inicio en el grupo E?', options: ['50 celulas por microlitro o mas', '100 celulas por microlitro o mas', '300 celulas por microlitro o mas', '1000 celulas por microlitro o mas'], correct: 2, explanation: 'A partir de 300 por microlitro el beneficio del corticoide inhalado en prevencion de exacerbaciones es claro. Por debajo de 100 el beneficio es minimo y persiste el riesgo de neumonia; entre 100 y 300 la decision se individualiza segun el historial de ingresos y el antecedente de asma.', dificultad: 'intermedio' },
  { q: 'Que dato desaconseja a&#241;adir un corticoide inhalado en la EPOC?', options: ['El antecedente personal de asma', 'Las neumonias de repeticion', 'El ingreso previo por exacerbacion', 'Las dos exacerbaciones moderadas al a&#241;o'], correct: 1, explanation: 'El corticoide inhalado deprime la inmunidad local de la via aerea y aumenta el riesgo de neumonia, por lo que las neumonias repetidas y la infeccion micobacteriana previa lo desaconsejan. Las otras tres situaciones son argumentos a favor de a&#241;adirlo, no en contra.', dificultad: 'intermedio' },
  { q: 'Cual es el mecanismo principal de la disnea en la EPOC?', options: ['La reduccion de la superficie de intercambio gaseoso', 'La debilidad primaria del musculo diafragmatico', 'El aumento de la resistencia inspiratoria de la via aerea', 'El atrapamiento aereo con hiperinsuflacion dinamica'], correct: 3, explanation: 'En la EPOC el aire entra, lo que no puede es salir. La espiracion lenta deja aire atrapado, sube el volumen teleespiratorio y aparece PEEP intrinseca, que el paciente debe vencer antes de inspirar. Con el esfuerzo el tiempo espiratorio se acorta y el fenomeno se agrava.', dificultad: 'intermedio' },
  { q: 'Que variable predice la disnea de esfuerzo mejor que el FEV1?', options: ['La capacidad de difusion pulmonar de monoxido de carbono', 'La presion arterial de oxigeno medida en reposo', 'El recuento de eosinofilos en sangre periferica', 'La caida de la capacidad inspiratoria en el ejercicio'], correct: 3, explanation: 'La hiperinsuflacion dinamica reduce la capacidad inspiratoria justo cuando la demanda ventilatoria es maxima, y esa caida se correlaciona con la disnea y con la tolerancia al ejercicio mucho mejor que el FEV1. Explica que un broncodilatador mejore mucho al paciente moviendo apenas 100 mL de FEV1.', dificultad: 'dificil' },
  { q: 'Un paciente obstructivo intubado sufre hipotension brusca. Cual es la primera maniobra?', options: ['Administrar un bolo rapido de cristaloides', 'Desconectar del respirador y dejar espirar', 'Iniciar noradrenalina en perfusion continua', 'Aumentar la PEEP externa aplicada'], correct: 1, explanation: 'La auto-PEEP por atrapamiento reduce el retorno venoso y puede llegar a la actividad electrica sin pulso. Desconectar permite vaciar el pulmon y confirma el mecanismo en segundos. Despues se alarga el tiempo espiratorio bajando la frecuencia y se ajusta la PEEP externa a unas cuatro quintas partes de la intrinseca.', dificultad: 'dificil' },
  { q: 'En cuanto tiempo debe instaurarse el empeoramiento para hablar de exacerbacion?', options: ['En menos de 14 dias', 'En menos de 48 horas', 'En menos de 30 dias', 'En menos de 3 meses'], correct: 0, explanation: 'La definicion de Roma exige un empeoramiento agudo de disnea, tos o expectoracion instaurado en menos de 14 dias, con inflamacion local y sistemica. El limite temporal separa la exacerbacion de la progresion natural de la enfermedad y del deterioro por una comorbilidad.', dificultad: 'intermedio' },
  { q: 'Cuantos dias debe durar el corticoide sistemico en la exacerbacion?', options: ['3 dias', '10 dias', '5 dias', '14 dias'], correct: 2, explanation: 'El ensayo REDUCE demostro que 5 dias no son inferiores a 14 en tiempo hasta la siguiente exacerbacion, con mucha menos exposicion acumulada a corticoide. Tampoco hace falta pauta descendente en un ciclo tan corto.', dificultad: 'facil' },
  { q: 'Que dosis de prednisona se pauta en la exacerbacion de la EPOC?', options: ['20 mg al dia', '40 mg al dia', '60 mg al dia', '80 mg al dia'], correct: 1, explanation: 'La dosis estandar es de 40 mg diarios por via oral durante 5 dias. La via oral es tan eficaz como la intravenosa si el paciente tolera, y dosis mayores no aportan beneficio y si mas hiperglucemia, insomnio y delirium en el anciano.', dificultad: 'facil' },
  { q: 'Que hallazgo indica antibiotico en la exacerbacion de la EPOC?', options: ['La fiebre mantenida por encima de 38 grados', 'El aumento del volumen del esputo solo', 'La elevacion marcada de la proteina C reactiva', 'La purulencia con aumento de disnea o volumen'], correct: 3, explanation: 'De los tres sintomas cardinales de Anthonisen, el que mejor identifica la carga bacteriana es el cambio de color del esputo. Se trata la exacerbacion con purulencia acompa&#241;ada de aumento de disnea o de volumen, y tambien la que requiere ventilacion, con independencia del aspecto del esputo.', dificultad: 'intermedio' },
  { q: 'Cual es el objetivo de saturacion al dar oxigeno en la exacerbacion?', options: ['Del 94 al 98%', 'Por encima del 92%', 'Del 88 al 92%', 'Por encima del 96%'], correct: 2, explanation: 'La ventana estrecha del 88 al 92% evita la hipoxemia peligrosa sin favorecer la hipercapnia. La mascarilla de Venturi es preferible porque permite fijar la fraccion inspirada de oxigeno, mientras que las gafas nasales la dejan variar con el patron respiratorio del paciente.', dificultad: 'facil' },
  { q: 'Por que empeora la hipercapnia el oxigeno a alto flujo en la EPOC?', options: ['Por perdida de vasoconstriccion hipoxica y efecto Haldane', 'Por depresion directa del centro respiratorio bulbar', 'Por aumento del consumo de oxigeno del musculo', 'Por broncoconstriccion refleja de la via aerea distal'], correct: 0, explanation: 'El oxigeno abole la vasoconstriccion pulmonar hipoxica y aumenta la perfusion de zonas mal ventiladas, con lo que crece el espacio muerto; ademas la hemoglobina oxigenada suelta dioxido de carbono. La depresion del centro respiratorio contribuye poco y durante a&#241;os se le atribuyo casi todo el fenomeno.', dificultad: 'dificil' },
  { q: 'Cuando esta indicada la ventilacion no invasiva en la exacerbacion?', options: ['Con hipoxemia que no corrige con gafas nasales', 'Con frecuencia respiratoria mayor de 30 por minuto', 'Con somnolencia y descenso del nivel de conciencia', 'Con pH de 7.35 o menor y PaCO2 mayor de 45 mmHg'], correct: 3, explanation: 'La acidosis respiratoria es la indicacion con mejor nivel de evidencia de toda la medicina respiratoria: reduce intubacion, estancia y mortalidad. La hipoxemia aislada se corrige con oxigeno, y el descenso del nivel de conciencia con incapacidad para proteger la via aerea es mas bien un motivo para intubar.', dificultad: 'intermedio' },
  { q: 'Que componentes integran la escala DECAF?', options: ['Edad, FEV1, comorbilidad, acidemia y disnea basal', 'Disnea, eosinofilia, creatinina, anemia y fiebre', 'Disnea, eosinopenia, consolidacion, acidemia y fibrilacion', 'Disnea, edad, consolidacion, hipoalbuminemia y taquicardia'], correct: 2, explanation: 'El acronimo recoge disnea basal extendida, eosinopenia por debajo de 0.05 x10^9/L, consolidacion radiologica, acidemia con pH menor de 7.30 y fibrilacion auricular. Se calcula con los datos del ingreso, antes de que el tratamiento modifique el pH y el recuento.', dificultad: 'intermedio' },
  { q: 'Que mortalidad intrahospitalaria predice un DECAF de 3 o mas?', options: ['Del 24 al 45%', 'Del 1 al 2%', 'Del 5 al 8%', 'Superior al 70%'], correct: 0, explanation: 'Es la franja de alto riesgo, frente a cerca del 1% con 0 a 1 punto y en torno al 5% con 2 puntos. Identifica al paciente en el que hay que anticipar la ventilacion no invasiva y mantener una conversacion explicita sobre el nivel de cuidados.', dificultad: 'intermedio' },
  { q: 'Que diagnostico se pasa por alto con mas frecuencia ante una exacerbacion sin causa clara?', options: ['El neumotorax espontaneo', 'La embolia pulmonar', 'La neumonia por aspiracion', 'El derrame pleural paraneumonico'], correct: 1, explanation: 'Su prevalencia en las exacerbaciones ingresadas sin foco infeccioso es lo bastante alta como para justificar un umbral bajo de sospecha, sobre todo con dolor pleuritico, hipoxemia desproporcionada o ausencia de purulencia. Las otras tres se ven en la radiografia inicial.', dificultad: 'dificil' },
  { q: 'Que cifra de PaO2 en situacion estable indica oxigenoterapia domiciliaria?', options: ['65 mmHg o menos', '70 mmHg o menos', '55 mmHg o menos', '45 mmHg o menos'], correct: 2, explanation: 'Equivale a una saturacion del 88% o menos. Entre 56 y 59 mmHg tambien se indica, pero solo si hay cor pulmonale, hipertension pulmonar, edemas o hematocrito por encima del 55%. La gasometria debe hacerse en situacion estable, nunca durante el ingreso.', dificultad: 'intermedio' },
  { q: 'Cuantas horas diarias de oxigeno domiciliario se necesitan para mejorar la supervivencia?', options: ['8 horas', '15 horas', '4 horas', '24 horas'], correct: 1, explanation: 'Los ensayos NOTT y del Medical Research Council mostraron que el beneficio depende de las horas de uso, y establecieron ese minimo diario. Por debajo de el no se ha demostrado ventaja en supervivencia, aunque pueda mejorar sintomas puntuales.', dificultad: 'intermedio' },
  { q: 'Que demostro el ensayo LOTT sobre la desaturacion moderada en la EPOC?', options: ['Que el oxigeno reduce los ingresos hospitalarios', 'Que el oxigeno mejora la distancia de marcha', 'Que el oxigeno acelera la caida del FEV1', 'Que el oxigeno no aporta beneficio en ese grupo'], correct: 3, explanation: 'En pacientes con desaturacion moderada en reposo o solo con el esfuerzo, el oxigeno no mejoro mortalidad, ingresos ni calidad de vida. El beneficio de la oxigenoterapia domiciliaria se limita a la hipoxemia grave que cumple los criterios gasometricos clasicos.', dificultad: 'dificil' },
  { q: 'Que criterio indica ventilacion no invasiva domiciliaria tras un ingreso por exacerbacion?', options: ['PaCO2 de 52 mmHg o mas a las 2 a 4 semanas', 'PaCO2 mayor de 45 mmHg durante el ingreso', 'Saturacion nocturna media por debajo del 90%', 'FEV1 por debajo del 30% del predicho'], correct: 0, explanation: 'La indicacion se basa en la hipercapnia que PERSISTE tras la recuperacion, no en la del episodio agudo, que casi siempre mejora. El ensayo HOT-HMV mostro que la ventilacion domiciliaria con presiones altas reduce reingresos y mortalidad en ese grupo.', dificultad: 'dificil' },
  { q: 'Que cuatro variables componen el indice BODE?', options: ['Edad, obstruccion, disnea y exacerbaciones', 'Masa corporal, obstruccion, disnea y ejercicio', 'Masa corporal, oxigenacion, disnea y edad', 'Bicarbonato, obstruccion, difusion y ejercicio'], correct: 1, explanation: 'El acronimo recoge indice de masa corporal, obstruccion medida por el FEV1, disnea en la escala mMRC y capacidad de ejercicio en la marcha de 6 minutos. Predice mortalidad mejor que el FEV1 aislado porque incorpora la dimension sistemica y funcional de la enfermedad.', dificultad: 'intermedio' },
  { q: 'Que valor del indice de masa corporal suma un punto en el BODE?', options: ['21 o menos', '25 o mas', '18.5 o menos', '30 o mas'], correct: 0, explanation: 'Es la unica variable del indice que puntua al reves de lo intuitivo: en la EPOC adelgazar empeora el pronostico. La perdida de masa magra es un marcador de gravedad sistemica independiente del FEV1 y justifica valoracion nutricional y entrenamiento de fuerza.', dificultad: 'intermedio' },
  { q: 'A quien hay que solicitar la determinacion de alfa-1-antitripsina?', options: ['Solo a los menores de 45 a&#241;os con enfisema', 'Solo a quienes tienen historia familiar', 'A todo paciente con EPOC, al menos una vez', 'Solo a los que no han fumado en su vida'], correct: 2, explanation: 'La recomendacion de la OMS es cribar una vez en la vida a todo paciente con EPOC, porque el deficit esta muy infradiagnosticado y explica del 1 al 2% de los casos. La sospecha se prioriza con enfisema precoz, predominio basal, poca carga tabaquica o historia familiar.', dificultad: 'intermedio' },
  { q: 'Que patron de enfisema sugiere deficiencia de alfa-1-antitripsina?', options: ['Centrolobulillar de predominio en lobulos superiores', 'Paraseptal con bullas subpleurales apicales', 'Cicatricial alrededor de lesiones fibroticas', 'Panlobulillar de predominio en lobulos inferiores'], correct: 3, explanation: 'Es la distribucion inversa a la del enfisema del fumador, que es centrolobulillar y de predominio superior. Encontrarla en la tomografia, sobre todo en un paciente joven o con poca carga tabaquica, obliga a medir la alfa-1-antitripsina y a genotipar si esta baja.', dificultad: 'intermedio' },
  { q: 'Cual es el papel de los vasodilatadores pulmonares en el cor pulmonale de la EPOC?', options: ['No se indican de rutina y pueden empeorar la hipoxemia', 'Son de eleccion cuando hay dilatacion del ventriculo derecho', 'Se pautan si la presion pulmonar media supera 20 mmHg', 'Sustituyen a la oxigenoterapia cuando esta no se tolera'], correct: 0, explanation: 'Vasodilatan tambien las zonas mal ventiladas y agravan el desequilibrio ventilacion-perfusion. El tratamiento de la hipertension pulmonar del grupo 3 es el de la enfermedad de base y la correccion de la hipoxemia; los vasodilatadores solo se plantean en centros expertos y en fenotipos concretos.', dificultad: 'dificil' },
  { q: 'Que conducta corresponde a un paciente con EPOC que necesita un betabloqueante por cardiopatia?', options: ['Sustituirlo por un antagonista del calcio', 'Reducir su dosis a la mitad de la habitual', 'Retirarlo mientras dure la exacerbacion', 'Mantener el betabloqueante cardioselectivo'], correct: 3, explanation: 'El beneficio cardiovascular supera con mucho al riesgo respiratorio, y los cardioselectivos se toleran bien incluso en la obstruccion grave. Retirarlos por miedo a broncoespasmo es uno de los errores mas repetidos y priva al paciente de un tratamiento que le prolonga la vida.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Varon de 68 a&#241;os, fumador de 45 paquetes-a&#241;o, con disnea al andar deprisa en llano. En el ultimo a&#241;o ha tenido una exacerbacion tratada en casa con antibiotico. Espirometria posbroncodilatador: FEV1/FVC de 0.55 y FEV1 del 58% del predicho. Eosinofilos de 150 por microlitro. mMRC de 1 y CAT de 8.', steps: [
    { q: 'Como se clasifica este paciente?', options: ['GOLD 3, grupo B', 'GOLD 2, grupo A', 'GOLD 2, grupo E', 'GOLD 3, grupo A'], correct: 1 },
    { q: 'Cual es el tratamiento inicial mas apropiado?', options: ['LABA mas LAMA mas corticoide inhalado', 'LABA mas corticoide inhalado', 'Corticoide inhalado en monoterapia', 'Un broncodilatador de larga duracion'], correct: 3 },
    { q: 'Que medida a&#241;adida modifica mas su pronostico?', options: ['El abandono del tabaco', 'El aumento de la dosis del broncodilatador', 'La oxigenoterapia domiciliaria nocturna', 'El tratamiento con azitromicina de mantenimiento'], correct: 0 }
  ], explanation: 'Un FEV1 del 58% situa al paciente en GOLD 2, y con mMRC de 1, CAT de 8 y una sola exacerbacion sin ingreso corresponde al grupo A, donde la monoterapia con un broncodilatador sigue siendo aceptable. Los eosinofilos de 150 no justifican corticoide inhalado, y con un solo episodio ambulatorio tampoco hay criterio de grupo E. De todo lo que se le puede ofrecer, dejar de fumar es lo unico que frena la caida acelerada del FEV1.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Mujer de 74 a&#241;os con EPOC GOLD 3 que acude por disnea creciente de 4 dias, tos y esputo verdoso abundante. Frecuencia respiratoria de 30, saturacion del 84% con aire ambiente, usa musculatura accesoria. Gasometria con oxigeno en gafas: pH de 7.28, PaCO2 de 68 mmHg y PaO2 de 58 mmHg. Radiografia sin consolidacion.', steps: [
    { q: 'Cual es la medida terapeutica prioritaria?', options: ['Intubacion orotraqueal inmediata', 'Aumento del flujo de oxigeno a 8 litros', 'Ventilacion no invasiva', 'Nebulizacion continua de salbutamol'], correct: 2 },
    { q: 'Que tratamiento farmacologico corresponde a&#241;adir?', options: ['Prednisona 40 mg durante 5 dias y antibiotico', 'Prednisona 40 mg durante 14 dias sin antibiotico', 'Antibiotico solo, sin corticoide sistemico', 'Metilprednisolona a 1 mg por kilogramo y antibiotico'], correct: 0 },
    { q: 'Cual es el objetivo de saturacion mientras se estabiliza?', options: ['Del 94 al 98%', 'Por encima del 95%', 'Del 80 al 85%', 'Del 88 al 92%'], correct: 3 }
  ], explanation: 'La acidosis respiratoria con pH de 7.28 y PaCO2 de 68 mmHg es la indicacion clasica de ventilacion no invasiva, que reduce intubacion y mortalidad y se aplica antes de plantear la via aerea artificial. Subir el flujo de oxigeno agravaria la hipercapnia. La purulencia junto al aumento de disnea justifica el antibiotico, y el corticoide se pauta 5 dias a 40 mg, sin pauta descendente. La ventana de saturacion del 88 al 92% se mantiene durante todo el episodio.', dificultad: 'facil' },

  { type: 'cascade', vignette: 'Varon de 70 a&#241;os con EPOC GOLD 4, exfumador, en tratamiento con LABA, LAMA y corticoide inhalado. Acude a revision 8 semanas despues de un ingreso. Esta estable, sin exacerbaciones desde el alta. Gasometria en aire ambiente: PaO2 de 52 mmHg, PaCO2 de 44 mmHg y pH de 7.41. Hematocrito del 49%.', steps: [
    { q: 'Que conducta corresponde con esa gasometria?', options: ['Indicar oxigenoterapia domiciliaria', 'Repetir la gasometria en 6 meses', 'Iniciar ventilacion no invasiva domiciliaria', 'Solicitar cateterismo cardiaco derecho'], correct: 0 },
    { q: 'Cuantas horas diarias hay que prescribirle como minimo?', options: ['8 horas', '12 horas', '15 horas', '10 horas'], correct: 2 },
    { q: 'Que hay que comprobar antes de instalar el equipo en su domicilio?', options: ['La presencia de poliglobulia significativa', 'La ausencia de tabaquismo activo', 'La tolerancia a la marcha de 6 minutos', 'La ausencia de hipertension pulmonar'], correct: 1 }
  ], explanation: 'Una PaO2 de 52 mmHg en situacion estable, medida al menos 4 a 8 semanas despues del ingreso, cumple por si sola el criterio de oxigenoterapia domiciliaria sin necesidad de datos adicionales de cor pulmonale. El beneficio en supervivencia depende de las horas de uso y exige un minimo de 15 al dia. El tabaquismo activo es una contraindicacion de seguridad por el riesgo de quemadura, y ha de comprobarse antes de la prescripcion.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Mujer de 41 a&#241;os con disnea de esfuerzo progresiva de 2 a&#241;os, etiquetada de asma sin respuesta al tratamiento. Fumo 4 paquetes-a&#241;o y lo dejo hace una decada. Su hermano fue trasplantado de pulmon a los 48. Espirometria: FEV1/FVC de 0.51 y FEV1 del 47%. La tomografia muestra enfisema panlobulillar de predominio en ambas bases.', steps: [
    { q: 'Cual es el diagnostico mas probable?', options: ['Asma de larga evolucion con remodelado', 'Bronquiolitis obliterante posinfecciosa', 'Linfangioleiomiomatosis pulmonar', 'Deficiencia de alfa-1-antitripsina'], correct: 3 },
    { q: 'Que prueba confirma el diagnostico?', options: ['La capacidad de difusion de monoxido de carbono', 'El fenotipado o genotipado de SERPINA1', 'La tomografia de alta resolucion inspiratoria', 'La biopsia pulmonar quirurgica'], correct: 1 },
    { q: 'Que tratamiento especifico puede corresponderle?', options: ['Corticoide inhalado a dosis altas mantenido', 'Azitromicina oral tres dias por semana', 'Sustitucion de alfa-1-antitripsina', 'Roflumilast oral en dosis diaria'], correct: 2 }
  ], explanation: 'El enfisema panlobulillar de predominio basal en una mujer joven con escasa carga tabaquica y antecedente familiar de trasplante es la presentacion tipica del deficit. La concentracion serica orienta pero puede ser falsamente normal por ser un reactante de fase aguda, de modo que la confirmacion es el estudio del gen SERPINA1. La sustitucion intravenosa semanal de alfa-1-antitripsina enlentece la perdida de densidad pulmonar en el deficit grave con enfisema establecido.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Varon de 65 a&#241;os con EPOC GOLD 2 que consulta por disnea de 2 dias y dolor toracico al respirar. Tos seca, sin cambio en el esputo. Saturacion del 88%, frecuencia cardiaca de 112 y frecuencia respiratoria de 26. Radiografia de torax sin consolidacion ni neumotorax. Gasometria: pH de 7.46, PaCO2 de 31 mmHg y PaO2 de 55 mmHg.', steps: [
    { q: 'Que hallazgo del caso hace dudar de una exacerbacion simple?', options: ['La frecuencia cardiaca de 112 latidos', 'La alcalosis respiratoria con dolor pleuritico', 'La saturacion del 88% en aire ambiente', 'La radiografia de torax sin alteraciones relevantes'], correct: 1 },
    { q: 'Cual es el siguiente paso diagnostico mas apropiado?', options: ['Angiotomografia de arterias pulmonares', 'Tomografia de alta resolucion pulmonar', 'Espirometria con prueba broncodilatadora', 'Ecocardiograma transtoracico urgente'], correct: 0 },
    { q: 'Que tratamiento NO corresponde con los datos disponibles?', options: ['El oxigeno con objetivo del 88 al 92%', 'El broncodilatador de accion corta', 'La profilaxis antitrombotica del ingreso', 'El antibiotico empirico de amplio espectro'], correct: 3 }
  ], explanation: 'La exacerbacion tipica cursa con hipercapnia o al menos sin hiperventilacion, y con cambio en el esputo. Aqui hay dolor pleuritico, hipoxemia desproporcionada y alcalosis respiratoria por taquipnea, un cuadro que apunta a embolia pulmonar y obliga a la angiotomografia. Sin purulencia ni consolidacion no hay criterio de antibiotico, mientras que el oxigeno controlado, el broncodilatador y la profilaxis siguen siendo correctos.', dificultad: 'dificil' },

  { type: 'cascade', vignette: 'Paciente con EPOC muy grave intubado por exacerbacion, en volumen control con frecuencia de 22, volumen corriente de 500 mL y relacion inspiracion-espiracion de 1 a 2. Aparece hipotension progresiva hasta 70/40 mmHg con presiones de la via aerea en ascenso. La curva de flujo espiratorio no llega a cero antes de la siguiente insuflacion.', steps: [
    { q: 'Cual es la causa mas probable del cuadro?', options: ['Un neumotorax a tension del lado derecho', 'Un choque septico de origen pulmonar', 'Una hiperinsuflacion dinamica con auto-PEEP', 'Un infarto agudo de miocardio perioperatorio'], correct: 2 },
    { q: 'Que ajuste del respirador corrige el problema?', options: ['Aumentar el volumen corriente a 8 mL por kilogramo', 'Aumentar la PEEP externa por encima de la intrinseca', 'Cambiar a presion control manteniendo la frecuencia', 'Bajar la frecuencia respiratoria y alargar la espiracion'], correct: 3 },
    { q: 'Que dato confirma la sospecha a pie de cama?', options: ['El ascenso de la presion venosa central medida', 'La mejoria de la tension al desconectar el respirador', 'La aparicion de crepitantes en la auscultacion', 'El descenso de la saturacion tras la desconexion'], correct: 1 }
  ], explanation: 'El flujo espiratorio que no llega a cero es la firma grafica del atrapamiento aereo: el pulmon no termina de vaciarse y la presion alveolar teleespiratoria positiva reduce el retorno venoso. Alargar el tiempo espiratorio bajando la frecuencia es la correccion directa, y la respuesta tensional inmediata a la desconexion confirma el mecanismo. El neumotorax a tension es el diferencial obligado y por eso se explora el torax a la vez.', dificultad: 'dificil' }
];

export const flashcards = [
  { front: 'Criterio diagnostico de EPOC', back: 'FEV1/FVC POSBRONCODILATADOR menor de 0.70. Sin espirometria no hay diagnostico.' },
  { front: 'Grados espirometricos GOLD', back: '1 leve: FEV1 80% o mas. 2 moderada: 50 a 79%. 3 grave: 30 a 49%. 4 muy grave: menos de 30%.' },
  { front: 'Que decide el grado GOLD 1 a 4', back: 'El pronostico, no el tratamiento. El tratamiento inicial lo decide el grupo A, B o E.' },
  { front: 'Definicion del grupo E', back: '2 o mas exacerbaciones moderadas, o 1 o mas con ingreso, en el ultimo a&#241;o. Ignora los sintomas.' },
  { front: 'Umbral de sintomas para grupo B o E', back: 'mMRC de 2 o mas, o CAT de 10 o mas.' },
  { front: 'Tratamiento inicial por grupo', back: 'A: un broncodilatador. B: LABA + LAMA. E: LABA + LAMA, y triple si eosinofilos 300 o mas.' },
  { front: 'Eosinofilos y corticoide inhalado', back: 'Menos de 100: casi sin beneficio y con riesgo de neumonia. 300 o mas: beneficio claro.' },
  { front: 'Cuando NO poner corticoide inhalado', back: 'Neumonias de repeticion, infeccion micobacteriana previa o eosinofilos por debajo de 100.' },
  { front: 'Escalado en el seguimiento', back: 'No se recalcula el grupo: se escala por el rasgo dominante, disnea o exacerbaciones.' },
  { front: 'Antes de escalar cualquier tratamiento', back: 'Comprobar adherencia y tecnica del inhalador con el dispositivo real.' },
  { front: 'Mecanismo de la disnea en la EPOC', back: 'Atrapamiento aereo con hiperinsuflacion dinamica y PEEP intrinseca, no falta de entrada de aire.' },
  { front: 'Que predice la disnea mejor que el FEV1', back: 'La caida de la capacidad inspiratoria durante el ejercicio.' },
  { front: 'Signo de Hoover', back: 'Retraccion paradojica del borde costal inferior en la inspiracion, por diafragma aplanado.' },
  { front: 'Definicion de Roma de la exacerbacion', back: 'Empeoramiento de disnea, tos o esputo instaurado en MENOS DE 14 DIAS.' },
  { front: 'Corticoide en la exacerbacion', back: 'Prednisona 40 mg al dia durante 5 DIAS, sin pauta descendente (ensayo REDUCE).' },
  { front: 'Cuando dar antibiotico en la exacerbacion', back: 'Purulencia del esputo con aumento de disnea o de volumen, o necesidad de ventilacion.' },
  { front: 'Sintomas cardinales de Anthonisen', back: 'Aumento de disnea, del volumen del esputo y de la purulencia. Tipo I los tres, tipo II dos.' },
  { front: 'Objetivo de saturacion en la exacerbacion', back: 'Del 88 al 92%, preferentemente con mascarilla de Venturi.' },
  { front: 'Por que el oxigeno excesivo sube la PaCO2', back: 'Abole la vasoconstriccion hipoxica (mas espacio muerto) y por efecto Haldane.' },
  { front: 'Indicacion de ventilacion no invasiva aguda', back: 'pH de 7.35 o menor con PaCO2 mayor de 45 mmHg. Reduce intubacion y mortalidad.' },
  { front: 'Componentes del DECAF', back: 'Disnea basal (eMRCD 5a o 5b), Eosinopenia, Consolidacion, Acidemia y Fibrilacion auricular.' },
  { front: 'DECAF de 3 o mas', back: 'Alto riesgo: mortalidad intrahospitalaria del 24 al 45%.' },
  { front: 'Diagnostico que mas se escapa en la exacerbacion', back: 'La embolia pulmonar, sobre todo sin purulencia y con hipoxemia desproporcionada.' },
  { front: 'Criterio gasometrico de oxigenoterapia domiciliaria', back: 'PaO2 de 55 mmHg o menos (o saturacion 88% o menos) en situacion ESTABLE.' },
  { front: 'Criterio intermedio de oxigenoterapia', back: 'PaO2 de 56 a 59 mmHg SOLO con cor pulmonale, edemas o hematocrito mayor del 55%.' },
  { front: 'Horas minimas de oxigeno domiciliario', back: 'Al menos 15 al dia: por debajo no hay beneficio en supervivencia.' },
  { front: 'Que demostro el ensayo LOTT', back: 'Que la desaturacion moderada aislada NO se beneficia de oxigenoterapia.' },
  { front: 'Ventilacion no invasiva domiciliaria', back: 'PaCO2 de 52 mmHg o mas persistente 2 a 4 semanas tras el alta (ensayo HOT-HMV).' },
  { front: 'Componentes del indice BODE', back: 'Indice de masa corporal, Obstruccion (FEV1), Disnea (mMRC) y Ejercicio (marcha de 6 minutos).' },
  { front: 'Cribado de alfa-1-antitripsina', back: 'Una vez en la vida a TODO paciente con EPOC, no solo a los jovenes.' },
  { front: 'Enfisema de la deficiencia de alfa-1-antitripsina', back: 'PANLOBULILLAR de predominio BASAL, al reves que el del fumador.' },
  { front: 'Betabloqueantes en la EPOC', back: 'Los cardioselectivos NO se retiran si hay indicacion cardiaca: el beneficio supera al riesgo.' }
];

export default { quiz, flashcards };
