// topics/alteraciones-plaquetarias-cuantitativas/study.js: Autoevaluación de Alteraciones
// Plaquetarias Cuantitativas.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Nota de método (ver memoria del proyecto): todas las preguntas se escribieron primero con la
// respuesta correcta en options[0]/correct:0 (trivialmente verificable), y luego se redistribuyó
// la posición de `correct` mecánicamente con un script, sin volver a adivinar cuál texto es el
// correcto.

export const quiz = [
  { q: '¿Cuál es la causa más frecuente de trombocitopenia aislada en el adulto sin otra enfermedad de base evidente?', options: ['Trombocitopenia inducida por heparina', 'Anemia aplásica', 'Púrpura Trombocitopénica Inmune (PTI)', 'Síndrome mielodisplásico'], correct: 2, explanation: 'La PTI es la causa más frecuente de trombocitopenia aislada en el adulto sin otra enfermedad de base evidente.', dificultad: 'facil' },
  { q: '¿Cuál es la causa más frecuente de trombocitosis en la práctica clínica?', options: ['Trombocitosis reactiva/secundaria', 'Trombocitemia esencial', 'Policitemia vera', 'Mielofibrosis'], correct: 0, explanation: 'La trombocitosis reactiva/secundaria es, con diferencia, la causa más frecuente de un recuento plaquetario elevado, considerablemente más frecuente que la trombocitemia esencial.', dificultad: 'facil' },
  { q: '¿Cuál es el mecanismo central de destrucción plaquetaria en la PTI?', options: ['Consumo masivo de plaquetas por microtrombos', 'Secuestro esplénico pasivo sin ningún componente inmune', 'Producción medular completamente ausente de megacariocitos', 'Autoanticuerpos se unen a glucoproteínas de la superficie plaquetaria y las plaquetas recubiertas son fagocitadas por macrófagos esplénicos'], correct: 3, explanation: 'En la PTI, autoanticuerpos se unen a glucoproteínas de la superficie plaquetaria (con frecuencia IIb/IIIa), y las plaquetas recubiertas son reconocidas y fagocitadas por macrófagos esplénicos.', dificultad: 'intermedio' },
  { q: '¿Por qué la PTI es un diagnóstico de exclusión?', options: ['Porque nunca produce ningún síntoma clínico', 'No existe una prueba confirmatoria positiva única; requiere descartar otras causas identificables de trombocitopenia', 'Porque siempre se acompaña de anemia y leucopenia', 'Porque solo ocurre en niños'], correct: 1, explanation: 'No existe una prueba confirmatoria positiva única para la PTI; el diagnóstico requiere descartar otras causas identificables de trombocitopenia primero.', dificultad: 'intermedio' },
  { q: '¿Cuál es el tratamiento de primera línea de la PTI con sangrado activo significativo?', options: ['Corticoides, con o sin inmunoglobulina intravenosa para elevación más rápida', 'Esplenectomía inmediata sin ningún tratamiento médico previo', 'Anticoagulación sistémica', 'Transfusión de concentrado eritrocitario'], correct: 0, explanation: 'Los corticoides son el tratamiento de primera línea, con inmunoglobulina intravenosa añadida cuando se necesita una respuesta más rápida.', dificultad: 'facil' },
  { q: '¿Qué mecanismo distingue fundamentalmente a la trombocitopenia inducida por heparina (HIT) de la mayoría de las demás trombocitopenias farmacológicas?', options: ['La HIT nunca produce ningún grado de trombocitopenia real', 'La HIT solo afecta a pacientes pediátricos', 'El anticuerpo activa directamente a las plaquetas además de marcarlas para destrucción, produciendo un estado protrombótico paradójico', 'La HIT se resuelve siempre sin necesidad de suspender la heparina'], correct: 2, explanation: 'A diferencia de la mayoría de las trombocitopenias farmacológicas, el anticuerpo de la HIT activa directamente a las plaquetas (además de marcarlas para destrucción), produciendo un estado protrombótico paradójico.', dificultad: 'dificil' },
  { q: '¿Contra qué complejo se dirige el anticuerpo característico de la HIT?', options: ['Factor de von Willebrand', 'Heparina y factor plaquetario 4 (PF4)', 'Glucoproteína Ib plaquetaria aislada', 'Proteína C activada'], correct: 1, explanation: 'El anticuerpo de la HIT se dirige contra el complejo formado por la heparina y el factor plaquetario 4 (PF4).', dificultad: 'intermedio' },
  { q: '¿Con qué tipo de heparina es la HIT considerablemente más frecuente?', options: ['Heparina de bajo peso molecular exclusivamente', 'Ninguna heparina produce HIT', 'Fondaparinux', 'Heparina no fraccionada'], correct: 3, explanation: 'La HIT es considerablemente más frecuente con heparina no fraccionada que con heparina de bajo peso molecular.', dificultad: 'facil' },
  { q: '¿En qué ventana temporal característica ocurre la caída plaquetaria de la HIT en el paciente sin exposición previa reciente?', options: ['Día 5 a 10 tras iniciar heparina', 'En las primeras 2 horas siempre', 'Después de 6 meses de exposición continua', 'Nunca antes del día 30'], correct: 0, explanation: 'La caída plaquetaria de la HIT ocurre característicamente entre el día 5 y 10 tras iniciar heparina en el paciente sin exposición previa reciente.', dificultad: 'intermedio' },
  { q: '¿Qué herramienta orienta la probabilidad pretest de HIT antes del estudio serológico confirmatorio?', options: ['PLASMIC Score', 'Score de Wells', '4T Score', 'ISTH-BAT'], correct: 2, explanation: 'El 4T Score orienta la probabilidad pretest de HIT combinando 4 categorías clínicas, antes de solicitar el estudio serológico confirmatorio.', dificultad: 'facil' },
  { q: '¿Cuál es la conducta apropiada ante un 4T Score intermedio-alto, incluso antes de la confirmación serológica?', options: ['Continuar la heparina sin ningún cambio hasta el resultado serológico', 'Aumentar la dosis de heparina', 'Esperar 2 semanas antes de tomar cualquier decisión', 'Suspender toda heparina de inmediato e iniciar un anticoagulante no heparínico'], correct: 3, explanation: 'Ante un 4T Score intermedio-alto, se debe suspender toda heparina de inmediato e iniciar un anticoagulante no heparínico, sin esperar la confirmación serológica.', dificultad: 'intermedio' },
  { q: '¿Por qué se debe evitar la warfarina en la fase aguda de la HIT antes de la recuperación plaquetaria sustancial?', options: ['La warfarina no tiene ningún efecto anticoagulante en este contexto', 'Riesgo de necrosis cutánea y gangrena de extremidades por la caída transitoria adicional de proteína C que produce al inicio de su efecto', 'La warfarina cura la HIT de forma inmediata sin ningún riesgo', 'No existe ninguna razón real para evitarla en este contexto'], correct: 1, explanation: 'La warfarina debe evitarse en la fase aguda de la HIT por el riesgo de necrosis cutánea y gangrena de extremidades, asociado a la caída transitoria adicional de proteína C al inicio de su efecto.', dificultad: 'dificil' },
  { q: '¿Qué es la pseudotrombocitopenia?', options: ['Un artefacto de laboratorio por agregación plaquetaria inducida por el anticoagulante EDTA del tubo de recolección', 'Una forma leve y verdadera de trombocitopenia inmune', 'Una complicación exclusiva del embarazo', 'Un sinónimo de trombocitopenia inducida por heparina'], correct: 0, explanation: 'La pseudotrombocitopenia es un artefacto de laboratorio por agregación plaquetaria inducida por el EDTA del tubo estándar, que produce un recuento automatizado falsamente bajo.', dificultad: 'facil' },
  { q: '¿Cómo se confirma o descarta la pseudotrombocitopenia?', options: ['Con una biopsia de médula ósea', 'Con un estudio de imagen abdominal', 'Repitiendo el recuento plaquetario en un tubo con citrato en lugar de EDTA', 'No existe ninguna forma de confirmarla'], correct: 2, explanation: 'Repetir el recuento plaquetario en un tubo con citrato (o heparina) confirma o descarta el artefacto de la pseudotrombocitopenia.', dificultad: 'intermedio' },
  { q: '¿Cuál es la causa más frecuente de trombocitopenia leve durante el embarazo?', options: ['Preeclampsia/síndrome HELLP', 'Trombocitopenia gestacional benigna', 'PTI de novo', 'Púrpura trombocitopénica trombótica'], correct: 1, explanation: 'La trombocitopenia gestacional benigna es la causa más frecuente de trombocitopenia leve durante el embarazo, presente en una proporción considerable de embarazos normales.', dificultad: 'facil' },
  { q: '¿Qué hallazgos distinguen a la preeclampsia/síndrome HELLP de la trombocitopenia gestacional benigna?', options: ['Un recuento plaquetario siempre normal', 'Ausencia completa de cualquier síntoma materno', 'Ocurrencia exclusiva en el primer trimestre', 'Hipertensión, proteinuria, y alteración de pruebas hepáticas'], correct: 3, explanation: 'La preeclampsia/síndrome HELLP se distingue por hipertensión, proteinuria, y alteración de las pruebas hepáticas, ausentes en la trombocitopenia gestacional benigna.', dificultad: 'intermedio' },
  { q: '¿Cuál es el mecanismo predominante por el que la mayoría de los estímulos producen trombocitosis reactiva?', options: ['Aumento de la producción hepática de trombopoyetina mediada por citocinas inflamatorias, particularmente interleucina-6', 'Proliferación clonal autónoma de un progenitor mutado', 'Destrucción acelerada de plaquetas normales', 'Secuestro esplénico disminuido'], correct: 0, explanation: 'La mayoría de los estímulos que producen trombocitosis reactiva actúan a través del aumento de la producción hepática de trombopoyetina, mediada por citocinas inflamatorias como la interleucina-6.', dificultad: 'intermedio' },
  { q: '¿Qué distingue mecanísticamente a la trombocitosis reactiva de la trombocitemia esencial?', options: ['No existe ninguna diferencia mecanística entre ambas', 'La trombocitosis reactiva siempre tiene mayor riesgo trombótico que la trombocitemia esencial', 'En la trombocitosis reactiva la producción permanece bajo control regulatorio normal; en la trombocitemia esencial es autónoma y clonal', 'La trombocitemia esencial siempre se resuelve espontáneamente sin tratamiento'], correct: 2, explanation: 'En la trombocitosis reactiva la producción plaquetaria permanece bajo control regulatorio normal y se resuelve al tratar la causa; en la trombocitemia esencial la proliferación es autónoma y clonal.', dificultad: 'dificil' },
  { q: '¿Cuándo se considera el estudio de mutaciones driver (JAK2, CALR, MPL) en un paciente con trombocitosis?', options: ['De rutina en todo paciente con cualquier grado de trombocitosis, sin excepción', 'Nunca es necesario en la evaluación de trombocitosis', 'Solo si el paciente ya tiene un evento trombótico confirmado', 'Cuando no se identifica ninguna causa reactiva plausible tras un estudio razonable'], correct: 3, explanation: 'El estudio molecular se reserva para los casos donde no se identifica ninguna causa reactiva plausible tras un estudio razonable, para evaluar trombocitemia esencial.', dificultad: 'intermedio' },
  { q: '¿Qué umbral de recuento plaquetario se asocia con mayor riesgo de sangrado espontáneo grave?', options: ['Aproximadamente 10,000-20,000/µL', 'Aproximadamente 150,000/µL', 'Aproximadamente 500,000/µL', 'No existe ningún umbral relacionado con el riesgo de sangrado'], correct: 0, explanation: 'Un recuento plaquetario por debajo de aproximadamente 10,000-20,000/µL se asocia con mayor riesgo de sangrado espontáneo grave, aunque el umbral exacto varía entre individuos.', dificultad: 'intermedio' },
  { q: '¿Qué tipo de sangrado mucoso se considera de mayor riesgo de progresión a sangrado grave en la trombocitopenia?', options: ['Sangrado cutáneo aislado exclusivamente', 'Sangrado "húmedo" (gingivorragia, epistaxis, hematuria, sangrado gastrointestinal)', 'Ausencia completa de cualquier sangrado', 'Dolor articular sin ningún signo de sangrado'], correct: 1, explanation: 'El sangrado mucoso "húmedo" (gingivorragia, epistaxis, hematuria, sangrado gastrointestinal) se considera de mayor riesgo de progresión que el sangrado cutáneo aislado.', dificultad: 'intermedio' },
  { q: '¿Cuál es la complicación más temida, aunque infrecuente, de la trombocitopenia grave no tratada oportunamente?', options: ['Trombosis venosa profunda', 'Insuficiencia renal aguda', 'Hemorragia intracraneal espontánea', 'Neumonía adquirida en la comunidad'], correct: 2, explanation: 'La hemorragia intracraneal espontánea, aunque infrecuente, es la complicación más temida de la trombocitopenia grave no tratada oportunamente.', dificultad: 'facil' },
  { q: '¿Por qué la transfusión de plaquetas puede tener eficacia limitada en la PTI, pese a usarse en el sangrado con compromiso vital?', options: ['Las plaquetas transfundidas siempre corrigen completamente el recuento en la PTI', 'La transfusión de plaquetas está formalmente contraindicada en cualquier paciente con PTI', 'El recuento plaquetario nunca es bajo en la PTI', 'Las plaquetas transfundidas también son blanco del autoanticuerpo circulante'], correct: 3, explanation: 'En la PTI, las plaquetas transfundidas también son blanco del autoanticuerpo circulante, por lo que su eficacia puede ser limitada, aunque se transfunden de todas formas ante una urgencia vital.', dificultad: 'dificil' },
  { q: '¿Por qué se recomienda ecografía Doppler venosa de rutina en la HIT confirmada, incluso sin síntomas trombóticos evidentes?', options: ['Por el riesgo trombótico subclínico reconocido, incluso en ausencia de manifestación clínica inicial', 'Porque la HIT nunca produce ningún riesgo trombótico real', 'Porque es un requisito administrativo sin ninguna justificación clínica', 'Porque descarta por completo el diagnóstico de HIT si es negativa'], correct: 0, explanation: 'Se recomienda por el riesgo trombótico subclínico reconocido en la HIT confirmada, incluso en ausencia de manifestación clínica inicial evidente.', dificultad: 'intermedio' },
  { q: '¿Cuándo se considera la esplenectomía en la PTI?', options: ['Como primera línea de tratamiento en todo paciente con PTI recién diagnosticada', 'En la enfermedad crónica (&gt;12 meses) refractaria a múltiples líneas de tratamiento médico', 'Nunca se considera en la PTI bajo ninguna circunstancia', 'Únicamente en el paciente pediátrico con PTI aguda autolimitada'], correct: 1, explanation: 'La esplenectomía se considera en la PTI crónica (&gt;12 meses) refractaria a múltiples líneas de tratamiento médico previo.', dificultad: 'intermedio' },
  { q: '¿Qué medida se recomienda idealmente 2 semanas antes de una esplenectomía electiva por PTI refractaria?', options: ['Suspender toda medicación previa del paciente', 'Iniciar anticoagulación profiláctica indefinida', 'Vacunación completa contra organismos encapsulados', 'Realizar un trasplante de médula ósea'], correct: 2, explanation: 'La vacunación completa contra organismos encapsulados (Streptococcus pneumoniae, Haemophilus influenzae tipo b, Neisseria meningitidis) se recomienda idealmente 2 semanas antes del procedimiento electivo.', dificultad: 'facil' },
  { q: '¿Qué hallazgo intraoperatorio se busca activamente durante una esplenectomía por PTI, dado que su presencia no resecada es una causa reconocida de recaída?', options: ['Bazo accesorio', 'Adenopatía mesentérica', 'Quiste hepático', 'Divertículo colónico'], correct: 0, explanation: 'El bazo accesorio se busca activamente durante la esplenectomía, dado que si no se identifica y reseca es una causa reconocida de recaída tras una esplenectomía aparentemente exitosa.', dificultad: 'intermedio' },
  { q: '¿Qué fenómeno hemostático paradójico puede desarrollarse en la trombocitosis extrema, particularmente por encima de aproximadamente 1,000,000-1,500,000/µL?', options: ['Deficiencia congénita de factor VIII', 'Hemofilia A adquirida por un mecanismo idéntico', 'Ausencia completa de cualquier riesgo hemorrágico o trombótico', 'Enfermedad de von Willebrand adquirida, por absorción de los multímeros de mayor peso molecular por el exceso de plaquetas'], correct: 3, explanation: 'En la trombocitosis extrema puede desarrollarse enfermedad de von Willebrand adquirida, por absorción y depuración de los multímeros de mayor peso molecular (los más hemostáticamente activos) por el exceso de plaquetas circulantes.', dificultad: 'dificil' },
  { q: '¿Qué citorreductor se usa como primera línea en la trombocitemia esencial de alto riesgo con trombocitosis extrema?', options: ['Insulina', 'Hidroxiurea', 'Levotiroxina', 'Furosemida'], correct: 1, explanation: 'La hidroxiurea es el citorreductor de primera línea en la trombocitemia esencial de alto riesgo con trombocitosis extrema.', dificultad: 'intermedio' },
  { q: '¿Qué procedimiento se considera como medida temporal de urgencia en la trombocitosis extrema con evento trombótico agudo?', options: ['Esplenectomía urgente', 'Trasplante de médula ósea urgente', 'Plaquetaféresis', 'Diálisis'], correct: 2, explanation: 'La plaquetaféresis se considera como medida temporal de reducción rápida del recuento plaquetario en casos seleccionados de urgencia trombótica aguda con trombocitosis extrema.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 28 años presenta petequias y equimosis extensas de aparición súbita en las últimas 48 horas, sin otro síntoma. Biometría hemática: plaquetas 8,000/µL, hemoglobina y leucocitos normales. Frotis sin esquistocitos ni blastos.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable dado el patrón de citopenia aislada y el frotis sin hallazgos alarmantes?', options: ['Púrpura Trombocitopénica Inmune (PTI)', 'Púrpura trombocitopénica trombótica', 'Leucemia aguda', 'Coagulación intravascular diseminada'], correct: 0, explanation: 'La trombocitopenia aislada y grave, sin anemia ni leucopenia asociadas, sin esquistocitos ni blastos en el frotis, es característica de PTI.' },
      { q: '¿Qué se debe descartar antes de confirmar el diagnóstico, dado que la PTI es un diagnóstico de exclusión?', options: ['No es necesario descartar ninguna otra causa', 'Pseudotrombocitopenia, causas secundarias (VIH, hepatitis C, lupus), y microangiopatía trombótica', 'Únicamente se requiere repetir la biometría hemática una vez más', 'Solo se requiere un estudio de imagen abdominal'], correct: 1, explanation: 'Antes de confirmar PTI, se deben descartar pseudotrombocitopenia, causas secundarias (VIH, hepatitis C, lupus), y microangiopatía trombótica.' },
      { q: 'Confirmada la PTI grave sintomática (plaquetas 8,000/µL con petequias/equimosis extensas), ¿cuál es el tratamiento de primera línea?', options: ['Esplenectomía inmediata sin ningún tratamiento médico previo', 'Observación sin ningún tratamiento dado que es asintomática', 'Anticoagulación sistémica', 'Corticoides, con inmunoglobulina intravenosa si se necesita respuesta más rápida'], correct: 3, explanation: 'Ante PTI con trombocitopenia grave sintomática, los corticoides son el tratamiento de primera línea, con inmunoglobulina intravenosa añadida si se necesita una respuesta más rápida.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 62 años en el día 7 de tratamiento con heparina no fraccionada por trombosis venosa profunda presenta caída del recuento plaquetario de 220,000 a 95,000/µL, y ahora también dolor y edema de la pierna contralateral.',
    steps: [
      { q: '¿Qué diagnóstico se debe sospechar dado el patrón temporal y el nuevo síntoma?', options: ['PTI de novo sin relación con la heparina', 'Pseudotrombocitopenia', 'Trombocitopenia inducida por heparina (HIT) con trombosis paradójica', 'Trombocitopenia gestacional'], correct: 2, explanation: 'La caída plaquetaria en el día 5-10 de exposición a heparina, junto con un nuevo evento trombótico, es característica de HIT con trombosis paradójica.' },
      { q: '¿Cuál es la conducta inmediata apropiada, incluso antes de la confirmación serológica?', options: ['Suspender toda heparina de inmediato e iniciar un anticoagulante no heparínico', 'Continuar la heparina en la misma dosis hasta el resultado serológico', 'Aumentar la dosis de heparina para "compensar" la trombosis', 'Esperar 1 semana antes de tomar cualquier decisión'], correct: 0, explanation: 'Ante sospecha razonable de HIT (4T Score intermedio-alto), se debe suspender toda heparina de inmediato e iniciar un anticoagulante no heparínico sin esperar la confirmación serológica.' },
      { q: 'Una vez estabilizado, ¿qué anticoagulante se debe evitar hasta la recuperación plaquetaria sustancial?', options: ['Argatrobán', 'Warfarina', 'Bivalirudina', 'Fondaparinux'], correct: 1, explanation: 'La warfarina debe evitarse hasta la recuperación plaquetaria sustancial, dado el riesgo de necrosis cutánea y gangrena de extremidades si se inicia prematuramente en este contexto.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 45 años presenta un recuento plaquetario automatizado de 45,000/µL en un estudio preoperatorio de rutina, sin ningún síntoma de sangrado ni antecedente relevante.',
    steps: [
      { q: '¿Qué se debe hacer primero ante este hallazgo asintomático inesperado?', options: ['Revisar el frotis de sangre periférica en busca de agregados plaquetarios', 'Iniciar tratamiento con corticoides de inmediato', 'Cancelar la cirugía sin ninguna evaluación adicional', 'Transfundir plaquetas profilácticamente'], correct: 0, explanation: 'Ante una trombocitopenia "sorpresa" asintomática, se debe revisar primero el frotis de sangre periférica en busca de agregados plaquetarios sugestivos de pseudotrombocitopenia.' },
      { q: 'El frotis muestra agregados plaquetarios evidentes. ¿Qué estudio confirma o descarta el artefacto?', options: ['Biopsia de médula ósea', 'Estudio de imagen abdominal', 'Repetir el recuento plaquetario en un tubo con citrato', 'Panel de trombofilia'], correct: 2, explanation: 'Repetir el recuento en un tubo con citrato (en lugar de EDTA) confirma o descarta la pseudotrombocitopenia.' },
      { q: 'El recuento en tubo con citrato es de 240,000/µL, normal. ¿Cuál es la conducta apropiada de aquí en adelante?', options: ['Iniciar tratamiento inmunosupresor de todas formas', 'Realizar esplenectomía preventiva', 'Repetir el estudio con EDTA cada semana indefinidamente', 'Documentar la pseudotrombocitopenia en el expediente para evitar estudios repetidos innecesarios en el futuro'], correct: 3, explanation: 'Una vez confirmada la pseudotrombocitopenia, se debe documentar claramente en el expediente para evitar estudios repetidos innecesarios en evaluaciones futuras.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 55 años con adenocarcinoma pulmonar metastásico conocido presenta un recuento plaquetario de 780,000/µL en una biometría hemática de control, sin ningún síntoma de sangrado ni trombosis.',
    steps: [
      { q: '¿Cuál es la interpretación más probable de este hallazgo en el contexto de la neoplasia activa conocida?', options: ['Trombocitemia esencial de novo', 'Trombocitosis reactiva/secundaria a la neoplasia', 'Pseudotrombocitopenia', 'Trombocitopenia inducida por fármacos'], correct: 1, explanation: 'La trombocitosis en el contexto de una neoplasia activa conocida es característicamente reactiva/secundaria, la causa más frecuente de trombocitosis en la práctica clínica.' },
      { q: '¿Qué mecanismo explica principalmente esta elevación reactiva?', options: ['Aumento de la producción hepática de trombopoyetina mediada por citocinas inflamatorias (interleucina-6)', 'Proliferación clonal autónoma de un progenitor mutado', 'Destrucción acelerada de eritrocitos', 'Secuestro esplénico disminuido'], correct: 0, explanation: 'El aumento de la producción hepática de trombopoyetina, mediado por citocinas inflamatorias como la interleucina-6 (elevada en el contexto neoplásico/inflamatorio), explica la trombocitosis reactiva.' },
      { q: '¿Cuál es el manejo apropiado de la trombocitosis en sí en este paciente asintomático?', options: ['Hidroxiurea de inmediato', 'Plaquetaféresis urgente', 'Ningún tratamiento citorreductor ni antiagregante específico dirigido a la trombocitosis; manejo centrado en la neoplasia de base', 'Esplenectomía profiláctica'], correct: 2, explanation: 'La trombocitosis reactiva en sí no requiere tratamiento citorreductor ni antiagregante específico en la gran mayoría de los casos; el manejo se centra en la causa reactiva (la neoplasia de base).' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 38 años con trombocitemia esencial conocida presenta recuento plaquetario de 1,400,000/µL y epistaxis recurrente inesperada, pese al recuento tan elevado.',
    steps: [
      { q: '¿Qué fenómeno paradójico se debe sospechar dado el sangrado pese al recuento plaquetario extremadamente alto?', options: ['Deficiencia congénita de factor VIII coincidente', 'Es imposible que un paciente con trombocitosis extrema tenga sangrado', 'Hemofilia A adquirida', 'Enfermedad de von Willebrand adquirida por absorción de multímeros de alto peso molecular'], correct: 3, explanation: 'En la trombocitosis extrema (particularmente &gt;1,000,000-1,500,000/µL) puede desarrollarse enfermedad de von Willebrand adquirida, por absorción de los multímeros de mayor peso molecular por el exceso de plaquetas.' },
      { q: '¿Qué estudio confirma esta sospecha?', options: ['Biopsia de médula ósea exclusivamente', 'Antígeno y actividad del factor de von Willebrand, con estudio de multímeros', 'Panel de trombofilia', 'Ensayo de Bethesda'], correct: 1, explanation: 'El antígeno y la actividad del factor de von Willebrand, junto con el estudio de multímeros, confirman la enfermedad de von Willebrand adquirida asociada a la trombocitosis extrema.' },
      { q: '¿Qué medida terapéutica central se debe considerar dado el mecanismo identificado?', options: ['Transfusión de concentrado de factor VIII', 'Aumentar la dosis de ácido acetilsalicílico', 'Citorreducción del recuento plaquetario (hidroxiurea) para reducir la trombocitosis extrema y revertir el fenómeno', 'Ninguna intervención es necesaria'], correct: 2, explanation: 'La citorreducción del recuento plaquetario extremo (con hidroxiurea) es la medida central, dado que reduce la trombocitosis y revierte el fenómeno de absorción de multímeros que produce la enfermedad de von Willebrand adquirida.' }
    ]
  }
];

export const flashcards = [
  { front: 'Causa más frecuente de trombocitopenia aislada en el adulto', back: 'Púrpura Trombocitopénica Inmune (PTI).' },
  { front: 'Causa más frecuente de trombocitosis', back: 'Trombocitosis reactiva/secundaria.' },
  { front: 'Mecanismo de destrucción plaquetaria en PTI', back: 'Autoanticuerpos contra glucoproteínas plaquetarias → fagocitosis esplénica.' },
  { front: 'Por qué la PTI es diagnóstico de exclusión', back: 'No hay prueba confirmatoria positiva única; requiere descartar otras causas primero.' },
  { front: 'Tratamiento de primera línea, PTI con sangrado activo', back: 'Corticoides ± inmunoglobulina intravenosa (respuesta más rápida).' },
  { front: 'Mecanismo distintivo de HIT', back: 'El anticuerpo activa las plaquetas además de destruirlas → trombosis paradójica.' },
  { front: 'Complejo antigénico de la HIT', back: 'Heparina + factor plaquetario 4 (PF4).' },
  { front: 'Heparina con mayor riesgo de HIT', back: 'Heparina no fraccionada (más que heparina de bajo peso molecular).' },
  { front: 'Ventana temporal característica de HIT', back: 'Día 5-10 tras iniciar heparina (sin exposición previa reciente).' },
  { front: 'Herramienta de probabilidad pretest de HIT', back: '4T Score.' },
  { front: 'Conducta ante 4T Score intermedio-alto', back: 'Suspender heparina de inmediato + anticoagulante no heparínico, sin esperar serología.' },
  { front: 'Por qué evitar warfarina en HIT aguda', back: 'Riesgo de necrosis cutánea/gangrena por caída transitoria de proteína C.' },
  { front: 'Pseudotrombocitopenia: mecanismo', back: 'Artefacto por agregación plaquetaria inducida por EDTA del tubo.' },
  { front: 'Confirmar/descartar pseudotrombocitopenia', back: 'Repetir el recuento en tubo con citrato.' },
  { front: 'Causa más frecuente de trombocitopenia leve en el embarazo', back: 'Trombocitopenia gestacional benigna.' },
  { front: 'Distinguir preeclampsia/HELLP de trombocitopenia gestacional', back: 'Hipertensión, proteinuria, alteración hepática (ausentes en la gestacional benigna).' },
  { front: 'Mecanismo de la trombocitosis reactiva', back: 'Aumento de trombopoyetina hepática mediado por interleucina-6.' },
  { front: 'Trombocitosis reactiva vs. trombocitemia esencial', back: 'Reactiva: producción regulada normal. Esencial: proliferación clonal autónoma.' },
  { front: 'Cuándo estudiar JAK2/CALR/MPL en trombocitosis', back: 'Solo si no se identifica causa reactiva plausible tras estudio razonable.' },
  { front: 'Umbral de plaquetas con mayor riesgo de sangrado espontáneo grave', back: 'Aproximadamente 10,000-20,000/µL.' },
  { front: 'Sangrado de mayor riesgo en trombocitopenia', back: '"Húmedo" (gingivorragia, epistaxis, hematuria, GI) vs. cutáneo aislado.' },
  { front: 'Complicación más temida de trombocitopenia grave', back: 'Hemorragia intracraneal espontánea.' },
  { front: 'Por qué la transfusión de plaquetas tiene eficacia limitada en PTI', back: 'Las plaquetas transfundidas también son blanco del autoanticuerpo.' },
  { front: 'Razón trombosis:sangrado en HIT no tratada', back: '~4 eventos trombóticos por cada sangrado significativo (patrón opuesto a otras trombocitopenias).' },
  { front: 'Por qué Doppler venoso de rutina en HIT confirmada', back: 'Riesgo trombótico subclínico incluso sin síntomas evidentes.' },
  { front: 'Cuándo considerar esplenectomía en PTI', back: 'Enfermedad crónica (&gt;12 meses) refractaria a ≥2 líneas de tratamiento médico.' },
  { front: 'Preparación pre-esplenectomía en PTI', back: 'Vacunación completa contra organismos encapsulados, idealmente 2 semanas antes.' },
  { front: 'Hallazgo a buscar en esplenectomía por PTI', back: 'Bazo accesorio (causa reconocida de recaída si no se reseca).' },
  { front: 'Fenómeno hemostático paradójico de trombocitosis extrema', back: 'Enfermedad de von Willebrand adquirida (absorción de multímeros grandes por exceso de plaquetas).' },
  { front: 'Citorreductor de primera línea en trombocitemia esencial de alto riesgo', back: 'Hidroxiurea.' }
];
