// topics/sindrome-hiperviscosidad/study.js: Autoevaluación de Síndrome de Hiperviscosidad.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Nota de método (ver memoria del proyecto): todas las preguntas se escribieron primero con la
// respuesta correcta en options[0]/correct:0 (trivialmente verificable), y luego se redistribuyó
// la posición de `correct` mecánicamente con un script, sin volver a adivinar cuál texto es el
// correcto.

export const quiz = [
  { q: '¿Cuál es la tríada clínica clásica del síndrome de hiperviscosidad sintomático?', options: ['Fiebre, adenopatías, y pérdida de peso', 'Dolor torácico, disnea, y palpitaciones', 'Sangrado mucocutáneo, alteración visual, y síntomas neurológicos', 'Ictericia, coluria, y acolia'], correct: 2, explanation: 'La tríada clínica clásica del síndrome de hiperviscosidad sintomático es sangrado mucocutáneo, alteración visual, y síntomas neurológicos.', dificultad: 'facil' },
  { q: '¿Cuáles son los 2 grandes mecanismos que pueden producir hiperviscosidad?', options: ['Exceso de una proteína plasmática (paraproteína) y exceso de células circulantes', 'Deficiencia de hierro y deficiencia de vitamina B12', 'Hipertensión arterial y diabetes mellitus', 'Insuficiencia renal e insuficiencia hepática'], correct: 0, explanation: 'La hiperviscosidad puede originarse por exceso de una proteína plasmática (paraproteína monoclonal) o por exceso de células circulantes (leucocitos o eritrocitos).', dificultad: 'facil' },
  { q: '¿Cuál es la causa clásica y más frecuentemente asociada al síndrome de hiperviscosidad sintomático?', options: ['Anemia ferropénica', 'Macroglobulinemia de Waldenström', 'Deficiencia de vitamina B12', 'Hipotiroidismo'], correct: 1, explanation: 'La macroglobulinemia de Waldenström es la causa clásica y más frecuentemente asociada al síndrome de hiperviscosidad sintomático, por el efecto desproporcionado de la IgM sobre la viscosidad.', dificultad: 'facil' },
  { q: '¿Por qué la IgM tiene un efecto desproporcionado sobre la viscosidad plasmática en comparación con otras inmunoglobulinas?', options: ['Es la inmunoglobulina de menor tamaño de todas', 'Nunca circula en el plasma, solo en los tejidos', 'Tiene una vida media extremadamente corta', 'Es una molécula pentamérica de gran tamaño con tendencia a formar agregados de alto peso molecular'], correct: 3, explanation: 'La IgM es una molécula pentamérica de gran tamaño (5 veces el tamaño de la IgG monomérica) con tendencia a formar agregados de alto peso molecular, lo que aumenta desproporcionadamente la viscosidad plasmática.', dificultad: 'intermedio' },
  { q: '¿Qué subtipo de mieloma múltiple tiene mayor riesgo relativo de hiperviscosidad sintomática dentro de esa enfermedad?', options: ['IgA', 'IgG en concentración baja', 'IgD', 'Mieloma no secretor'], correct: 0, explanation: 'El mieloma de tipo IgA tiene mayor riesgo relativo de hiperviscosidad sintomática dentro del mieloma múltiple, dada su mayor tendencia a la polimerización en comparación con la IgG.', dificultad: 'intermedio' },
  { q: '¿Por qué la hiperviscosidad sintomática es considerablemente menos frecuente en el mieloma múltiple que en la macroglobulinemia de Waldenström?', options: ['Porque el mieloma múltiple nunca produce ninguna proteína monoclonal', 'Porque el mieloma múltiple es una enfermedad mucho más rara que la macroglobulinemia de Waldenström', 'Porque la IgG (el tipo más frecuente en mieloma) es monomérica y tiene un efecto proporcionalmente menor sobre la viscosidad por gramo de proteína', 'Porque la viscosidad no depende del tipo de inmunoglobulina en absoluto'], correct: 2, explanation: 'La IgG, el tipo más frecuente en el mieloma múltiple, es monomérica y tiene un efecto proporcionalmente menor sobre la viscosidad plasmática por gramo de proteína en comparación con la IgM pentamérica.', dificultad: 'dificil' },
  { q: '¿Qué umbral de leucocitos se asocia a un riesgo considerablemente aumentado de leucostasis, particularmente en leucemia mieloide aguda?', options: ['Mayor de 5,000/µL', 'Mayor de 100,000/µL', 'Mayor de 500/µL', 'Menor de 1,000/µL'], correct: 1, explanation: 'Un recuento leucocitario mayor de 100,000/µL se asocia a un riesgo considerablemente aumentado de leucostasis, particularmente en la leucemia mieloide aguda.', dificultad: 'facil' },
  { q: '¿Por qué el mecanismo de la leucostasis es distinto del de la hiperviscosidad plasmática por paraproteína?', options: ['La leucostasis nunca afecta a la microcirculación', 'Los blastos mieloides son más pequeños que los eritrocitos normales', 'No existe ninguna diferencia mecanística entre ambos procesos', 'Los blastos mieloides son de mayor tamaño y menos deformables, obstruyendo físicamente la microcirculación además de aumentar la viscosidad global'], correct: 3, explanation: 'Los blastos mieloides, de mayor tamaño y menos deformables, expresan moléculas de adhesión que favorecen su interacción con el endotelio, produciendo obstrucción física de la microcirculación además del efecto sobre la viscosidad global.', dificultad: 'dificil' },
  { q: '¿Qué subtipo de leucemia mieloide aguda tiene mayor riesgo relativo de leucostasis por las características de adhesión de sus células?', options: ['Leucemia monocítica aguda', 'Leucemia promielocítica aguda con recuento leucocitario bajo', 'Leucemia mieloide aguda con cariotipo normal exclusivamente', 'Ninguna variante tiene mayor riesgo que otra'], correct: 0, explanation: 'Los subtipos monocíticos de leucemia mieloide aguda tienen mayor riesgo relativo de leucostasis por las características de adhesión particulares de los monoblastos.', dificultad: 'intermedio' },
  { q: '¿Qué medida transfusional se debe evitar en el paciente con hiperleucocitosis extrema no controlada?', options: ['Hidratación intravenosa adecuada', 'Profilaxis de síndrome de lisis tumoral', 'Transfusión de concentrado eritrocitario no urgente', 'Citorreducción con hidroxiurea'], correct: 2, explanation: 'Debe evitarse la transfusión de concentrado eritrocitario no urgente en el paciente con hiperleucocitosis extrema no controlada, dado que puede aumentar aún más la viscosidad sanguínea global y agravar la leucostasis.', dificultad: 'intermedio' },
  { q: '¿Cuál es la medida de citorreducción rápida usada como puente mientras se organiza el tratamiento definitivo de la leucostasis?', options: ['Insulina en infusión', 'Warfarina', 'Furosemida', 'Hidroxiurea'], correct: 3, explanation: 'La hidroxiurea se usa como medida puente de citorreducción rápida mientras se organiza el tratamiento definitivo (quimioterapia de inducción) en la leucostasis.', dificultad: 'intermedio' },
  { q: '¿Qué fenómeno de laboratorio reconocido puede mostrar una saturación de oxígeno artificialmente baja en el paciente con hiperleucocitosis extrema?', options: ['Hiperoxemia verdadera sin ninguna explicación', 'Pseudohipoxemia, por el consumo de oxígeno de los blastos en la muestra', 'Un artefacto exclusivo del electrocardiograma', 'Un fenómeno que nunca ocurre en la práctica clínica'], correct: 1, explanation: 'La pseudohipoxemia es un fenómeno reconocido en el que la saturación de oxígeno medida es artificialmente baja por el consumo de oxígeno de los blastos circulantes en la muestra de sangre.', dificultad: 'dificil' },
  { q: '¿Cuál es la causa más frecuente de hiperviscosidad celular por eritrocitosis?', options: ['Policitemia vera', 'Anemia ferropénica', 'Anemia megaloblástica', 'Talasemia menor'], correct: 0, explanation: 'La policitemia vera es la causa más frecuente de hiperviscosidad celular por eritrocitosis, dado el aumento marcado y sostenido de la masa eritrocitaria circulante.', dificultad: 'facil' },
  { q: '¿Cómo es la relación entre el hematocrito y la viscosidad sanguínea por encima de un umbral aproximado de 55-60%?', options: ['Lineal simple sin ningún cambio de pendiente', 'Inversamente proporcional', 'Exponencial: incrementos relativamente pequeños adicionales producen aumentos desproporcionadamente grandes de la viscosidad', 'No existe ninguna relación entre ambas variables'], correct: 2, explanation: 'Por encima de un hematocrito de aproximadamente 55-60%, la relación con la viscosidad sanguínea se vuelve exponencial, explicando por qué el control estricto del hematocrito es central en la policitemia vera.', dificultad: 'dificil' },
  { q: '¿Qué riesgo predomina característicamente en la hiperviscosidad por eritrocitosis, a diferencia de las otras causas de este tema?', options: ['Riesgo hemorrágico exclusivo, sin ningún riesgo trombótico', 'Riesgo trombótico (arterial y venoso)', 'Riesgo de infección oportunista', 'Riesgo de rechazo de trasplante'], correct: 1, explanation: 'A diferencia de la hiperviscosidad plasmática o la leucostasis (predominantemente asociadas a sangrado), la hiperviscosidad por eritrocitosis se asocia característicamente a un mayor riesgo trombótico.', dificultad: 'intermedio' },
  { q: '¿Cuál es la medida terapéutica central y de acción más rápida para reducir agudamente el hematocrito en la eritrocitosis sintomática?', options: ['Trasplante de médula ósea', 'Radioterapia esplénica', 'Diálisis', 'Flebotomía terapéutica'], correct: 3, explanation: 'La flebotomía terapéutica es la medida central y de acción más rápida para reducir agudamente el hematocrito y la viscosidad asociada en la eritrocitosis sintomática.', dificultad: 'facil' },
  { q: '¿Qué hallazgo característico de fondo de ojo se describe en el síndrome de hiperviscosidad?', options: ['Venas retinianas dilatadas y segmentadas ("en salchicha")', 'Manchas de Roth exclusivamente', 'Desprendimiento total de retina', 'Cataratas bilaterales'], correct: 0, explanation: 'El hallazgo característico de fondo de ojo en el síndrome de hiperviscosidad es la dilatación y segmentación de las venas retinianas ("en salchicha").', dificultad: 'facil' },
  { q: '¿Por qué la circulación retiniana es particularmente vulnerable al enlentecimiento del flujo por hiperviscosidad?', options: ['No recibe ningún flujo sanguíneo bajo condiciones normales', 'Es la circulación de mayor calibre de todo el cuerpo', 'Tiene vasos de muy pequeño calibre y un alto requerimiento metabólico', 'Está completamente protegida de cualquier cambio en la viscosidad sanguínea'], correct: 2, explanation: 'La circulación retiniana tiene vasos de muy pequeño calibre y un alto requerimiento metabólico (segundo solo al cerebro), lo que la hace particularmente vulnerable al enlentecimiento del flujo por hiperviscosidad.', dificultad: 'intermedio' },
  { q: '¿Cuál es el mecanismo central de la disfunción plaquetaria adquirida en la hiperviscosidad plasmática?', options: ['Destrucción autoinmune directa de las plaquetas por anticuerpos específicos', 'Producción medular de plaquetas defectuosas de origen genético', 'Consumo masivo de plaquetas por coagulación intravascular diseminada exclusivamente', 'La paraproteína circulante en exceso recubre la superficie de las plaquetas e interfiere con su función normal'], correct: 3, explanation: 'La paraproteína circulante en exceso recubre la superficie de las plaquetas, interfiriendo con su función normal de adhesión y agregación, un mecanismo cualitativo y no cuantitativo.', dificultad: 'dificil' },
  { q: '¿Por qué la transfusión de plaquetas tiene utilidad limitada en el sangrado por disfunción plaquetaria adquirida asociada a hiperviscosidad?', options: ['Las plaquetas transfundidas siempre corrigen completamente cualquier tipo de sangrado', 'Las plaquetas transfundidas también quedarán disfuncionales mientras persista la paraproteinemia no tratada', 'La transfusión de plaquetas está formalmente contraindicada en todo paciente hematológico', 'El recuento plaquetario siempre es extremadamente bajo en este contexto'], correct: 1, explanation: 'Dado que el mecanismo es disfuncional (cualitativo) y no cuantitativo, las plaquetas transfundidas también quedarán disfuncionales mientras persista la paraproteinemia no tratada, por lo que su utilidad es limitada.', dificultad: 'dificil' },
  { q: '¿Cuál es el tratamiento más eficaz para revertir agudamente la disfunción plaquetaria adquirida por hiperviscosidad plasmática?', options: ['Plasmaféresis urgente', 'Transfusión de plaquetas aislada', 'Ácido acetilsalicílico en dosis altas', 'Vitamina K intravenosa'], correct: 0, explanation: 'La plasmaféresis urgente es el tratamiento más eficaz, dado que remueve directamente la paraproteína causal, revirtiendo la disfunción plaquetaria adquirida.', dificultad: 'intermedio' },
  { q: '¿Por qué se debe extremar la cautela al transfundir concentrado eritrocitario en un paciente con hiperviscosidad activa por anemia concomitante?', options: ['La transfusión siempre reduce la viscosidad sanguínea de forma segura', 'No existe ningún riesgo asociado a la transfusión en este contexto', 'La transfusión de concentrado eritrocitario cura directamente la hiperviscosidad', 'Puede aumentar aún más la viscosidad sanguínea global y precipitar descompensación cardiovascular'], correct: 3, explanation: 'La transfusión de concentrado eritrocitario en un paciente con hiperviscosidad ya establecida aumenta aún más la viscosidad sanguínea global y el volumen circulante, pudiendo precipitar descompensación cardiovascular.', dificultad: 'intermedio' },
  { q: '¿Qué alternativa se considera en lugar de una transfusión simple cuando la hiperviscosidad está activa y el paciente requiere corrección de la anemia?', options: ['Transfusión masiva sin ninguna modificación del protocolo estándar', 'Plasmaféresis o exanguinotransfusión parcial', 'Suspender indefinidamente cualquier corrección de la anemia', 'Diálisis peritoneal'], correct: 1, explanation: 'Se considera plasmaféresis o exanguinotransfusión parcial en lugar de una transfusión simple cuando la hiperviscosidad está activa, para evitar agravar aún más la viscosidad global.', dificultad: 'intermedio' },
  { q: '¿Cuál es el estudio de elección urgente ante deterioro neurológico agudo en un paciente con hiperviscosidad, para distinguir isquemia de hemorragia?', options: ['Electroencefalograma', 'Punción lumbar inmediata sin estudio de imagen previo', 'TC cerebral simple', 'Radiografía simple de cráneo'], correct: 2, explanation: 'La TC cerebral simple urgente es el primer estudio ante cualquier deterioro neurológico agudo, para distinguir un mecanismo isquémico de uno hemorrágico, dado que el manejo difiere sustancialmente.', dificultad: 'facil' },
  { q: '¿Por qué la anticoagulación o la trombolisis requieren especial cautela en el contexto de hiperviscosidad activa?', options: ['Existe un riesgo hemorrágico concomitante por la disfunción plaquetaria adquirida asociada', 'Estos tratamientos siempre son completamente seguros sin ninguna consideración especial', 'La hiperviscosidad elimina por completo cualquier riesgo de sangrado', 'Nunca hay ningún evento isquémico en el contexto de hiperviscosidad'], correct: 0, explanation: 'La anticoagulación o trombolisis requieren cautela dado el riesgo hemorrágico concomitante por la disfunción plaquetaria adquirida asociada a la hiperviscosidad, particularmente la de origen plasmático.', dificultad: 'dificil' },
  { q: '¿Qué componente de la calculadora de criterios de hiperviscosidad sintomática es el signo objetivo más específico?', options: ['La edad del paciente', 'El color de la piel', 'El peso corporal', 'El hallazgo de fondo de ojo'], correct: 3, explanation: 'El hallazgo de fondo de ojo (venas retinianas dilatadas y segmentadas) es el signo objetivo más específico dentro de la calculadora de criterios de hiperviscosidad sintomática.', dificultad: 'intermedio' },
  { q: '¿Qué manifestación clínica específica de la eritrocitosis por policitemia vera, distinta de la tríada clásica de hiperviscosidad plasmática, es característica?', options: ['Sangrado mucocutáneo exclusivo sin ningún otro síntoma', 'Prurito acuagénico (tras el baño) y eritromelalgia', 'Pérdida auditiva bilateral súbita', 'Alopecia difusa'], correct: 1, explanation: 'El prurito acuagénico (tras el baño) y la eritromelalgia (dolor y eritema urente en manos/pies) son manifestaciones características de la policitemia vera, distintas de la tríada clásica de hiperviscosidad plasmática.', dificultad: 'intermedio' },
  { q: '¿Qué tratamiento sistémico se inicia una vez estabilizada la hiperviscosidad sintomática aguda por macroglobulinemia de Waldenström con plasmaféresis?', options: ['Insulina en infusión continua', 'Anticoagulación oral indefinida sin ningún otro tratamiento', 'Esquemas sistémicos basados en rituximab, con frecuencia combinado con otros agentes', 'Radioterapia total del cuerpo'], correct: 2, explanation: 'Tras la plasmaféresis inicial, se inicia o intensifica el tratamiento sistémico dirigido al clon linfoplasmocítico subyacente, con esquemas con frecuencia basados en rituximab.', dificultad: 'intermedio' },
  { q: '¿Cuál es el mecanismo por el que la deshidratación agrava cualquier causa de hiperviscosidad?', options: ['Concentra aún más la sangre, aumentando la viscosidad relativa', 'Diluye la sangre, reduciendo la viscosidad', 'No tiene ningún efecto sobre la viscosidad sanguínea', 'Elimina completamente la paraproteína circulante'], correct: 0, explanation: 'La deshidratación concentra aún más la sangre, aumentando la viscosidad relativa y agravando cualquier mecanismo subyacente de hiperviscosidad (plasmático o celular).', dificultad: 'facil' },
  { q: '¿Cuántos criterios de la calculadora de hiperviscosidad sintomática (o qué hallazgo aislado) indican plasmaféresis urgente según la lógica clínica descrita?', options: ['Únicamente si los 4 criterios están presentes simultáneamente', '2 o más criterios presentes, o el hallazgo de fondo de ojo por sí solo', 'Ningún criterio aislado justifica nunca tratamiento urgente', 'Solo la edad del paciente determina la urgencia del tratamiento'], correct: 1, explanation: '2 o más criterios presentes, o el hallazgo de fondo de ojo por sí solo, indican plasmaféresis urgente según la calculadora de criterios de hiperviscosidad sintomática.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 68 años con macroglobulinemia de Waldenström conocida presenta epistaxis recurrente de 3 días, visión borrosa progresiva, y cefalea leve. El fondo de ojo muestra venas retinianas dilatadas y segmentadas.',
    steps: [
      { q: '¿Qué síndrome debe sospecharse con este cuadro?', options: ['Neuropatía óptica isquémica aislada', 'Migraña con aura', 'Conjuntivitis viral', 'Síndrome de hiperviscosidad sintomático'], correct: 3, explanation: 'La combinación de epistaxis, visión borrosa, cefalea, y el hallazgo de fondo de ojo característico en un paciente con macroglobulinemia de Waldenström es característica del síndrome de hiperviscosidad sintomático.' },
      { q: '¿Cuál es el tratamiento urgente de elección?', options: ['Plasmaféresis urgente', 'Transfusión de plaquetas exclusivamente', 'Observación sin ninguna intervención', 'Anticoagulación sistémica en dosis altas'], correct: 0, explanation: 'La plasmaféresis urgente es el tratamiento de elección para reducir agudamente la concentración de IgM circulante en la hiperviscosidad sintomática.' },
      { q: '¿Qué se debe hacer inmediatamente después de estabilizar el cuadro agudo con plasmaféresis?', options: ['Suspender todo seguimiento dado que la plasmaféresis ya es curativa por sí sola', 'Iniciar o intensificar el tratamiento sistémico dirigido al clon linfoplasmocítico subyacente', 'Indicar únicamente observación ambulatoria sin ningún cambio en el manejo', 'Reducir la dosis de cualquier tratamiento sistémico actual sin otra justificación'], correct: 1, explanation: 'La plasmaféresis es una medida temporal; el tratamiento sistémico dirigido al clon subyacente debe iniciarse o intensificarse para controlar la producción de IgM y prevenir la recurrencia.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 45 años con leucemia mieloide aguda recién diagnosticada presenta leucocitos de 180,000/µL, disnea progresiva, e hipoxemia. La saturación de oxígeno medida es de 82% pese a aporte de oxígeno suplementario.',
    steps: [
      { q: '¿Qué complicación se debe sospechar de inmediato?', options: ['Leucostasis pulmonar', 'Neumonía bacteriana aislada sin ninguna otra causa', 'Insuficiencia cardiaca crónica descompensada', 'Asma bronquial'], correct: 0, explanation: 'La hiperleucocitosis extrema (&gt;100,000/µL) con disnea e hipoxemia en la leucemia mieloide aguda recién diagnosticada es característica de leucostasis pulmonar.' },
      { q: '¿Qué fenómeno podría explicar parcialmente la saturación de oxígeno tan baja pese al aporte suplementario?', options: ['Un error de calibración del oxímetro que nunca ocurre en la práctica clínica', 'Anemia ferropénica aguda concomitante', 'Pseudohipoxemia por el consumo de oxígeno de los blastos en la muestra de sangre', 'Hipertiroidismo no diagnosticado'], correct: 2, explanation: 'La pseudohipoxemia, por el consumo de oxígeno de los blastos circulantes en la muestra, es un fenómeno reconocido que puede explicar parcialmente una saturación medida artificialmente baja en este contexto.' },
      { q: '¿Cuál es la medida terapéutica urgente más apropiada?', options: ['Transfusión de concentrado eritrocitario no urgente para corregir cualquier anemia asociada', 'Citorreducción urgente (hidroxiurea como puente, o quimioterapia de inducción inmediata si es factible)', 'Observación sin ninguna intervención hasta el día siguiente', 'Anticoagulación sistémica en dosis altas'], correct: 1, explanation: 'La citorreducción urgente (hidroxiurea como medida puente, o quimioterapia de inducción inmediata si es factible) es la medida terapéutica central en la leucostasis, además de evitar la transfusión eritrocitaria no urgente.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 58 años con policitemia vera conocida pero sin tratamiento regular presenta cefalea, mareo, prurito tras el baño, y hematocrito de 62%.',
    steps: [
      { q: '¿Qué mecanismo explica estos síntomas?', options: ['Hiperviscosidad celular por eritrocitosis marcada', 'Hiperviscosidad plasmática por paraproteína', 'Leucostasis por hiperleucocitosis extrema', 'Deficiencia de hierro'], correct: 0, explanation: 'El hematocrito marcadamente elevado (62%) en un paciente con policitemia vera no tratada, junto con los síntomas descritos, es característico de hiperviscosidad celular por eritrocitosis.' },
      { q: '¿Cuál es la medida terapéutica de acción más rápida para reducir agudamente el hematocrito?', options: ['Trasplante de médula ósea urgente', 'Plasmaféresis', 'Flebotomía terapéutica', 'Transfusión de concentrado eritrocitario'], correct: 2, explanation: 'La flebotomía terapéutica es la medida de acción más rápida para reducir agudamente el hematocrito y la viscosidad asociada en la eritrocitosis sintomática.' },
      { q: '¿Qué riesgo predomina característicamente en este paciente, a diferencia de la hiperviscosidad plasmática?', options: ['Riesgo hemorrágico exclusivo por disfunción plaquetaria', 'Riesgo de infección oportunista', 'Riesgo de rechazo de trasplante', 'Riesgo trombótico (arterial y venoso)'], correct: 3, explanation: 'A diferencia de la hiperviscosidad plasmática (predominantemente hemorrágica), la eritrocitosis por policitemia vera se asocia característicamente a un mayor riesgo trombótico.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 72 años con mieloma múltiple tipo IgA conocido y anemia sintomática (hemoglobina 7.2 g/dL) presenta también signos de hiperviscosidad activa (visión borrosa, fondo de ojo característico).',
    steps: [
      { q: '¿Qué precaución especial se debe tener antes de corregir la anemia con transfusión estándar?', options: ['Ninguna precaución especial es necesaria en este contexto', 'Extremar la cautela, dado que la transfusión puede aumentar aún más la viscosidad sanguínea global', 'La transfusión siempre debe evitarse por completo en cualquier paciente con mieloma', 'La transfusión debe administrarse en el mayor volumen posible lo más rápido posible'], correct: 1, explanation: 'Dado que la paciente tiene hiperviscosidad activa, se debe extremar la cautela antes de transfundir, dado que puede aumentar aún más la viscosidad sanguínea global y precipitar descompensación.' },
      { q: '¿Qué alternativa se considera en lugar de una transfusión simple en este contexto?', options: ['Plasmaféresis o exanguinotransfusión parcial', 'Transfusión masiva sin ninguna modificación del protocolo', 'Suspender indefinidamente cualquier corrección de la anemia', 'Diálisis peritoneal'], correct: 0, explanation: 'Se considera plasmaféresis o exanguinotransfusión parcial en lugar de una transfusión simple cuando la hiperviscosidad está activa, para evitar agravar aún más la viscosidad global.' },
      { q: 'Si finalmente se decide transfundir con extrema cautela, ¿cómo debe hacerse?', options: ['En el volumen estándar habitual sin ninguna modificación', 'Lo más rápido posible para minimizar el tiempo del procedimiento', 'Sin ninguna vigilancia clínica adicional durante la transfusión', 'En volúmenes pequeños y a ritmo lento, con vigilancia clínica estrecha'], correct: 3, explanation: 'Si se decide transfundir, debe hacerse en volúmenes pequeños y a ritmo lento, con vigilancia clínica estrecha, dado el riesgo de agravar la hiperviscosidad y precipitar sobrecarga de volumen.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 61 años con macroglobulinemia de Waldenström conocida presenta confusión progresiva de 6 horas de evolución y una convulsión focal presenciada por su familia.',
    steps: [
      { q: '¿Cuál es el estudio urgente de primera línea ante este deterioro neurológico agudo?', options: ['TC cerebral simple', 'Electroencefalograma ambulatorio programado', 'Punción lumbar sin estudio de imagen previo', 'Radiografía simple de cráneo'], correct: 0, explanation: 'La TC cerebral simple urgente es el estudio de primera línea ante cualquier deterioro neurológico agudo, para distinguir isquemia de hemorragia antes de cualquier otro procedimiento.' },
      { q: 'La TC no muestra hemorragia ni lesión focal aguda. ¿Qué mecanismo de la hiperviscosidad podría explicar este cuadro?', options: ['Es imposible que la hiperviscosidad produzca síntomas neurológicos sin una lesión estructural visible', 'Encefalopatía por flujo microvascular cerebral alterado, sin lesión estructural evidente en la TC simple', 'Una infección del sistema nervioso central es la única explicación posible', 'Los síntomas neurológicos nunca se asocian a hiperviscosidad'], correct: 1, explanation: 'La encefalopatía por hiperviscosidad puede producir alteración del estado de conciencia y síntomas neurológicos por flujo microvascular cerebral alterado, sin necesariamente mostrar una lesión estructural evidente en la TC simple.' },
      { q: '¿Cuál es la medida terapéutica central para revertir este mecanismo?', options: ['Anticoagulación sistémica en dosis altas sin ninguna otra consideración', 'Observación sin ninguna intervención específica', 'Plasmaféresis urgente dirigida a reducir la concentración de IgM circulante', 'Antibióticos empíricos de amplio espectro como única medida'], correct: 2, explanation: 'La plasmaféresis urgente, dirigida a reducir la concentración de IgM circulante causal, es la medida terapéutica central para revertir el mecanismo de la hiperviscosidad y sus complicaciones neurológicas.' }
    ]
  }
];

export const flashcards = [
  { front: 'Tríada clásica del síndrome de hiperviscosidad', back: 'Sangrado mucocutáneo, alteración visual, síntomas neurológicos.' },
  { front: '2 mecanismos de hiperviscosidad', back: 'Plasmático (exceso de paraproteína) y celular (exceso de leucocitos o eritrocitos).' },
  { front: 'Causa clásica más frecuente de hiperviscosidad sintomática', back: 'Macroglobulinemia de Waldenström (IgM).' },
  { front: 'Por qué la IgM tiene efecto desproporcionado sobre la viscosidad', back: 'Molécula pentamérica de gran tamaño con tendencia a formar agregados de alto peso molecular.' },
  { front: 'Subtipo de mieloma con mayor riesgo de hiperviscosidad', back: 'IgA (tiende a polimerizar), más que IgG (monomérica).' },
  { front: 'Umbral de leucocitos para riesgo de leucostasis', back: 'Mayor de 100,000/µL, particularmente en leucemia mieloide aguda.' },
  { front: 'Mecanismo de la leucostasis', back: 'Blastos mieloides grandes, poco deformables, con moléculas de adhesión; obstrucción física de la microcirculación.' },
  { front: 'Subtipo de LMA con mayor riesgo de leucostasis', back: 'Leucemia monocítica aguda.' },
  { front: 'Transfusión a evitar en hiperleucocitosis extrema', back: 'Concentrado eritrocitario no urgente (agrava la viscosidad global).' },
  { front: 'Citorreducción puente en leucostasis', back: 'Hidroxiurea, mientras se organiza el tratamiento definitivo.' },
  { front: 'Pseudohipoxemia', back: 'Saturación de oxígeno artificialmente baja por consumo de oxígeno de los blastos en la muestra.' },
  { front: 'Causa más frecuente de hiperviscosidad por eritrocitosis', back: 'Policitemia vera.' },
  { front: 'Relación hematocrito-viscosidad por encima de 55-60%', back: 'Exponencial: pequeños incrementos producen aumentos desproporcionados de viscosidad.' },
  { front: 'Riesgo predominante en hiperviscosidad por eritrocitosis', back: 'Trombótico (arterial y venoso), a diferencia del riesgo hemorrágico de las otras causas.' },
  { front: 'Tratamiento de acción más rápida en eritrocitosis sintomática', back: 'Flebotomía terapéutica.' },
  { front: 'Hallazgo característico de fondo de ojo en hiperviscosidad', back: 'Venas retinianas dilatadas y segmentadas ("en salchicha").' },
  { front: 'Por qué la retina es vulnerable a la hiperviscosidad', back: 'Vasos de muy pequeño calibre y alto requerimiento metabólico.' },
  { front: 'Mecanismo de la disfunción plaquetaria adquirida', back: 'La paraproteína recubre las plaquetas e interfiere con su función (cualitativo, no cuantitativo).' },
  { front: 'Por qué la transfusión de plaquetas tiene utilidad limitada aquí', back: 'Las plaquetas transfundidas también quedarán disfuncionales mientras persista la paraproteinemia.' },
  { front: 'Tratamiento más eficaz para la disfunción plaquetaria por hiperviscosidad', back: 'Plasmaféresis urgente (remueve la paraproteína causal).' },
  { front: 'Riesgo de transfundir en hiperviscosidad activa', back: 'Puede aumentar aún más la viscosidad y precipitar descompensación cardiovascular.' },
  { front: 'Alternativa a la transfusión simple en hiperviscosidad activa', back: 'Plasmaféresis o exanguinotransfusión parcial.' },
  { front: 'Estudio urgente ante deterioro neurológico agudo en hiperviscosidad', back: 'TC cerebral simple (distinguir isquemia de hemorragia).' },
  { front: 'Por qué cautela con anticoagulación/trombolisis en hiperviscosidad', back: 'Riesgo hemorrágico concomitante por disfunción plaquetaria adquirida.' },
  { front: 'Signo más específico de la calculadora de hiperviscosidad', back: 'Hallazgo de fondo de ojo.' },
  { front: 'Manifestaciones características de policitemia vera', back: 'Prurito acuagénico (tras el baño) y eritromelalgia.' },
  { front: 'Tratamiento sistémico tras estabilizar hiperviscosidad por Waldenström', back: 'Esquemas basados en rituximab.' },
  { front: 'Por qué la deshidratación agrava la hiperviscosidad', back: 'Concentra aún más la sangre, aumentando la viscosidad relativa.' },
  { front: 'Umbral de la calculadora que indica plasmaféresis urgente', back: '2 o más criterios presentes, o el hallazgo de fondo de ojo por sí solo.' },
  { front: 'Complicación cardiovascular reconocida en el manejo de hiperviscosidad', back: 'Insuficiencia cardiaca por sobrecarga de volumen, particularmente al transfundir sin cautela.' }
];
