// topics/nodulo-cancer-pulmon/study.js: Autoevaluacion de Nodulo Pulmonar y Cancer de Pulmon.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// 48 subpreguntas (30 sueltas + 6 cascadas de 3 pasos) y 32 tarjetas.
// Sin em dash (ver [[feedback-no-em-dash]]). Texto sin acentos.

export const quiz = [
  { q: 'Que tama&#241;o separa a un nodulo pulmonar de una masa?', options: ['20 mm o menos', '10 mm o menos', '30 mm o menos', '40 mm o menos'], correct: 2, explanation: 'Un nodulo mide 30 mm o menos. Por encima de esa cifra se llama masa, y la diferencia no es semantica: la masa se estudia como un cancer hasta que se demuestre lo contrario, sin periodos de observacion ni algoritmos de vigilancia.', dificultad: 'facil' },
  { q: 'Cual es el primer gesto ante un nodulo pulmonar hallado por casualidad?', options: ['Buscar y revisar imagenes previas', 'Pedir marcadores tumorales sericos', 'Solicitar una tomografia de positrones', 'Programar una puncion transtoracica'], correct: 0, explanation: 'Recuperar estudios antiguos resuelve una parte enorme de los casos y se hace antes que cualquier tabla. Hay que mirar tambien las imagenes de otros centros y las tomografias abdominales que incluyan las bases pulmonares.', dificultad: 'facil' },
  { q: 'En cual de estos pacientes NO se aplican las guias de Fleischner?', options: ['Un fumador de 68 a&#241;os con enfisema', 'Una mujer de 52 a&#241;os sin antecedentes', 'Un varon de 40 a&#241;os con nodulo perifisurario', 'Un paciente en tratamiento inmunosupresor'], correct: 3, explanation: 'El inmunodeprimido queda fuera del ambito de la guia, igual que los menores de 35 a&#241;os, los pacientes con cancer conocido y los nodulos de cribado. En el inmunodeprimido hay que descartar activamente infeccion y linfoma, y el umbral de estudio es mucho mas bajo.', dificultad: 'intermedio' },
  { q: 'Durante cuanto tiempo se sigue un nodulo subsolido persistente?', options: ['2 a&#241;os', '5 a&#241;os', '1 a&#241;o', '3 a&#241;os'], correct: 1, explanation: 'El subsolido se sigue 5 a&#241;os, frente a los 2 del solido. Las lesiones de la via adenocarcinomatosa crecen tan despacio que 2 a&#241;os de estabilidad no permiten darlas por benignas.', dificultad: 'intermedio' },
  { q: 'Por que el nodulo subsolido se sigue durante 5 a&#241;os y no 2?', options: ['Porque recidiva tras la reseccion', 'Porque se mide con menos exactitud', 'Porque crece muy despacio', 'Porque suele ser multiple'], correct: 2, explanation: 'Corresponde a lesiones de la via adenocarcinomatosa (hiperplasia adenomatosa atipica, adenocarcinoma in situ y minimamente invasivo) cuya velocidad de crecimiento es muy baja, de modo que un plazo de 2 a&#241;os deja escapar casos.', dificultad: 'intermedio' },
  { q: 'Que hallazgo indica invasion en un nodulo subsolido en seguimiento?', options: ['El crecimiento del componente solido', 'El aumento del diametro total', 'La perdida de los bordes definidos', 'El aumento de la densidad media'], correct: 0, explanation: 'Lo que marca el cambio de comportamiento es el componente solido, no el tama&#241;o global. Un nodulo que se hace mas grande pero sigue siendo vidrio puro preocupa menos que uno estable que desarrolla un nucleo solido.', dificultad: 'dificil' },
  { q: 'Cual de estos patrones de calcificacion NO orienta hacia benignidad?', options: ['La calcificacion central', 'La calcificacion excentrica', 'La calcificacion laminar concentrica', 'La calcificacion en palomita de maiz'], correct: 1, explanation: 'Los cuatro patrones benignos son el central, el laminar concentrico, el difuso y el de palomita de maiz. Las calcificaciones excentricas o punteadas no tranquilizan, porque un tumor puede englobar un granuloma antiguo.', dificultad: 'intermedio' },
  { q: 'Que sugiere la presencia de grasa dentro de un nodulo pulmonar?', options: ['Un granuloma tuberculoso', 'Un carcinoide periferico', 'Un ganglio intrapulmonar', 'Un hamartoma pulmonar'], correct: 3, explanation: 'La grasa medida en unidades Hounsfield es practicamente diagnostica de hamartoma y cierra el caso sin mas estudio. Es uno de los pocos hallazgos radiologicos que valen por si solos.', dificultad: 'intermedio' },
  { q: 'En cual de estas lesiones es mas probable un positrones falsamente negativo?', options: ['Un adenocarcinoma lepidico', 'Un carcinoma escamoso cavitado', 'Un carcinoma microcitico central', 'Una metastasis de cancer de colon'], correct: 0, explanation: 'El adenocarcinoma de crecimiento lepidico capta poco, igual que el tumor carcinoide y que cualquier lesion menor de 8 a 10 mm. Un resultado negativo en esas situaciones no permite volver a la vigilancia sin mas.', dificultad: 'dificil' },
  { q: 'Que causa con mas frecuencia un positrones falsamente positivo en el torax?', options: ['La atelectasia obstructiva', 'El infarto pulmonar reciente', 'La inflamacion granulomatosa', 'El derrame pleural trasudativo'], correct: 2, explanation: 'La tuberculosis, las micosis y la sarcoidosis captan intensamente. En zonas endemicas la especificidad de la prueba cae mucho, y por eso una captacion positiva nunca sustituye a la histologia.', dificultad: 'intermedio' },
  { q: 'Que hacer ante una adenopatia mediastinica captante en un candidato a cirugia?', options: ['Considerarla afectada y no operar', 'Confirmarla con una puncion', 'Repetir el positrones a los 3 meses', 'Ampliar la diseccion durante la cirugia'], correct: 1, explanation: 'La captacion tiene falsos positivos frecuentes, de modo que no basta para negarle a un paciente una cirugia potencialmente curativa. Se confirma con ecobroncoscopia con puncion o, si esta no es concluyente, con mediastinoscopia.', dificultad: 'intermedio' },
  { q: 'Por que hay que puncionar un derrame pleural que acompa&#241;a a un cancer de pulmon?', options: ['Porque alivia la disnea de inmediato', 'Porque permite medir marcadores tumorales', 'Porque descarta un empiema asociado', 'Porque su citologia cambia el estadio'], correct: 3, explanation: 'Un derrame maligno confirmado convierte la enfermedad en irresecable. Puncionarlo diagnostica y estadifica en un solo gesto, y puede evitar una toracotomia inutil.', dificultad: 'intermedio' },
  { q: 'Que poblacion cumple hoy los criterios de cribado con tomografia de baja dosis?', options: ['De 50 a 80 a&#241;os con 20 paquetes-a&#241;o', 'De 55 a 74 a&#241;os con 30 paquetes-a&#241;o', 'De 45 a 75 a&#241;os con 15 paquetes-a&#241;o', 'De 60 a 80 a&#241;os con 40 paquetes-a&#241;o'], correct: 0, explanation: 'La recomendacion de 2021 bajo la edad de inicio de 55 a 50 a&#241;os y la carga de 30 a 20 paquetes-a&#241;o, con lo que casi duplico el numero de personas elegibles. Se exige ademas ser fumador actual o haberlo dejado hace menos de 15 a&#241;os.', dificultad: 'facil' },
  { q: 'Cuando deja de estar indicado el cribado en un exfumador?', options: ['A los 5 a&#241;os sin fumar', 'A los 10 a&#241;os sin fumar', 'A los 15 a&#241;os sin fumar', 'A los 20 a&#241;os sin fumar'], correct: 2, explanation: 'A partir de los 15 a&#241;os de abstinencia el riesgo residual ya no compensa los da&#241;os del cribado. El programa se interrumpe tambien si aparece una condicion que impida un tratamiento curativo.', dificultad: 'intermedio' },
  { q: 'Que condicion obliga a no cribar aunque se cumplan la edad y la carga tabaquica?', options: ['El antecedente de neumonias de repeticion', 'La presencia de nodulos benignos previos', 'El uso cronico de oxigeno domiciliario', 'Una enfermedad que impida tratar'], correct: 3, explanation: 'Detectar un cancer en alguien que no podria recibir tratamiento curativo solo a&#241;ade pruebas, ansiedad y da&#241;o, sin beneficio posible. Es el criterio de exclusion que mas se olvida al indicar el cribado.', dificultad: 'intermedio' },
  { q: 'Con que sistema se informan los nodulos detectados en un programa de cribado?', options: ['Con la escala de Fleischner', 'Con la escala Lung-RADS', 'Con la clasificacion TNM', 'Con los criterios de Light'], correct: 1, explanation: 'Lung-RADS es el sistema propio del cribado y categoriza el riesgo y la conducta. Las guias de Fleischner estan pensadas para el nodulo incidental y no se aplican en este contexto.', dificultad: 'intermedio' },
  { q: 'Que intervencion debe ofrecerse en cada visita de un programa de cribado?', options: ['La vacunacion antineumococica', 'La espirometria de control anual', 'La deshabituacion tabaquica', 'La medicion de alfa-1-antitripsina'], correct: 2, explanation: 'El cribado no sustituye al abandono del tabaco: su beneficio se suma al de la deshabituacion, que sigue siendo la intervencion que mas reduce el riesgo de cancer de pulmon.', dificultad: 'facil' },
  { q: 'Que debe conocerse antes de iniciar tratamiento sistemico en un estadio IV?', options: ['El perfil molecular y el PD-L1', 'El resultado de la gammagrafia osea', 'Los valores de los marcadores tumorales', 'La respuesta a un primer ciclo de platino'], correct: 0, explanation: 'El estudio molecular (EGFR, ALK, ROS1, BRAF, KRAS G12C, MET, RET, NTRK, HER2) y la expresion de PD-L1 son parte del diagnostico, no un complemento. Empezar sin ellos puede costarle al paciente el mejor tratamiento disponible.', dificultad: 'facil' },
  { q: 'Cual es el tratamiento del carcinoma no microcitico en estadio III irresecable?', options: ['Quimioterapia sola y radioterapia si progresa', 'Quimiorradioterapia seguida de durvalumab', 'Inmunoterapia en monoterapia de inicio', 'Cirugia citorreductora y radioterapia'], correct: 1, explanation: 'La quimiorradioterapia concurrente seguida de durvalumab de consolidacion cambio la supervivencia de este grupo, que es el mas heterogeneo y el que mas exige valoracion en comite.', dificultad: 'intermedio' },
  { q: 'Que alternativa curativa existe en el estadio I si el paciente no es operable?', options: ['La quimioterapia con platino a dosis plenas', 'La braquiterapia endobronquial paliativa', 'La quimiorradioterapia concurrente', 'La radioterapia estereotactica corporal'], correct: 3, explanation: 'La radioterapia estereotactica corporal consigue tasas de control local muy altas en el tumor periferico peque&#241;o y es la opcion de eleccion cuando la funcion pulmonar o la comorbilidad impiden la reseccion.', dificultad: 'intermedio' },
  { q: 'Como se divide clasicamente el carcinoma microcitico de pulmon?', options: ['En central y periferico', 'En temprano y avanzado', 'En limitado y extendido', 'En operable e inoperable'], correct: 2, explanation: 'La division en enfermedad limitada (abarcable en un campo de radioterapia tolerable) y extendida sigue usandose en la practica junto con el TNM, porque separa dos estrategias terapeuticas distintas.', dificultad: 'facil' },
  { q: 'Cual es el tratamiento de la enfermedad limitada en el carcinoma microcitico?', options: ['Platino, etoposido y radioterapia concurrente', 'Cirugia seguida de quimioterapia adyuvante', 'Platino y etoposido con inmunoterapia', 'Radioterapia toracica exclusiva a dosis altas'], correct: 0, explanation: 'La quimioterapia con platino y etoposido concurrente con la radioterapia toracica se administra con intencion curativa y es donde estan los largos supervivientes. La inmunoterapia se a&#241;ade en la enfermedad extendida.', dificultad: 'intermedio' },
  { q: 'Que prueba de estadificacion es obligatoria en todo carcinoma microcitico?', options: ['La gammagrafia osea con tecnecio', 'La biopsia de medula osea bilateral', 'La ecobroncoscopia con puncion', 'La resonancia magnetica cerebral'], correct: 3, explanation: 'La frecuencia de metastasis cerebrales, muchas veces asintomaticas, obliga a hacerla en todos los pacientes. Su resultado cambia tanto la estadificacion como el tratamiento.', dificultad: 'intermedio' },
  { q: 'Que tumor pulmonar produce con mas frecuencia secrecion inadecuada de hormona antidiuretica?', options: ['El adenocarcinoma', 'El carcinoma microcitico', 'El carcinoma escamoso', 'El carcinoide tipico'], correct: 1, explanation: 'Su origen neuroendocrino explica la produccion ectopica de vasopresina. Una hiponatremia hipoosmolar con orina concentrada en un fumador obliga a buscar un carcinoma microcitico.', dificultad: 'facil' },
  { q: 'Que estirpe se asocia a la hipercalcemia por peptido relacionado con la parathormona?', options: ['El carcinoma escamoso', 'El adenocarcinoma', 'El carcinoma microcitico', 'El carcinoma de celulas grandes'], correct: 0, explanation: 'El escamoso es el que produce con mas frecuencia este peptido. La hipercalcemia cursa con parathormona suprimida y puede ser la primera manifestacion de la enfermedad.', dificultad: 'intermedio' },
  { q: 'Que diferencia al sindrome de Lambert-Eaton de la miastenia gravis?', options: ['La debilidad predomina en los musculos oculares', 'Los reflejos estan exaltados desde el inicio', 'La fuerza MEJORA con la contraccion repetida', 'La debilidad empeora con el frio ambiental'], correct: 2, explanation: 'Es el dato exploratorio que los separa: en el Lambert-Eaton la fuerza y los reflejos mejoran tras el ejercicio repetido. Se asocia al carcinoma microcitico y puede preceder al tumor en meses o a&#241;os.', dificultad: 'dificil' },
  { q: 'Que triada define al sindrome de Horner del tumor del sulcus superior?', options: ['Ptosis, midriasis y sudoracion facial', 'Ptosis, miosis y anhidrosis', 'Diplopia, miosis y disfonia', 'Exoftalmos, miosis y anhidrosis'], correct: 1, explanation: 'Traduce la afectacion de la cadena simpatica cervical y se acompa&#241;a de dolor de hombro y de brazo y de debilidad de la mano por invasion del plexo braquial. Se confunde con una patologia del hombro durante meses.', dificultad: 'intermedio' },
  { q: 'Con que estirpe se asocia sobre todo la osteoartropatia hipertrofica?', options: ['Con el carcinoma microcitico', 'Con el carcinoma escamoso', 'Con el tumor carcinoide', 'Con el adenocarcinoma'], correct: 3, explanation: 'Las acropaquias con periostitis dolorosa de huesos largos son tipicas del adenocarcinoma, pueden preceder al diagnostico y mejoran al tratar el tumor.', dificultad: 'dificil' },
  { q: 'Por que hay que medir la DLCO aunque el FEV1 sea normal?', options: ['Porque predice complicaciones por si sola', 'Porque permite estimar la carga tabaquica', 'Porque sustituye a la prueba de esfuerzo', 'Porque define la extension de la reseccion'], correct: 0, explanation: 'La DLCO predice las complicaciones posoperatorias de forma independiente del FEV1, y omitirla es uno de los fallos clasicos de la valoracion preoperatoria. Ambos valores se traducen a su equivalente predicho posoperatorio.', dificultad: 'intermedio' },
  { q: 'Que aporto la integracion precoz de los cuidados paliativos en el cancer de pulmon avanzado?', options: ['Redujo el numero de ingresos hospitalarios urgentes', 'Permitio reducir las dosis de quimioterapia', 'Mejoro la calidad de vida y la supervivencia', 'Adelanto la decision de limitar el esfuerzo'], correct: 2, explanation: 'En un ensayo clasico en cancer de pulmon metastasico, los pacientes con cuidados paliativos integrados desde el diagnostico tuvieron mejor calidad de vida y vivieron mas, pese a recibir tratamiento menos agresivo al final de la vida.', dificultad: 'intermedio' },

  { type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 64 a&#241;os, fumador de 40 paquetes-a&#241;o, sin otros antecedentes. Se le hace una tomografia abdominal por un colico renal y en las bases pulmonares aparece un nodulo SOLIDO unico de 7 mm en el lobulo superior derecho, de bordes lisos.',
    steps: [
      { q: 'Que gesto corresponde antes de aplicar cualquier algoritmo?', options: ['Buscar y revisar imagenes previas', 'Pedir marcadores tumorales', 'Solicitar positrones de entrada', 'Programar una puncion guiada'], correct: 0 },
      { q: 'No hay estudios previos. Que seguimiento corresponde a este nodulo?', options: ['Sin seguimiento por su tama&#241;o', 'Positrones o toma de muestra', 'Tomografia a los 6 a 12 meses', 'Reseccion por videotoracoscopia'], correct: 2 },
      { q: 'A los 9 meses el nodulo mide 11 mm. Que corresponde ahora?', options: ['Seguir vigilando cada 6 meses', 'Tomografia por emision de positrones', 'Repetir la tomografia en 2 a&#241;os', 'Alta con informe al paciente'], correct: 1 }
    ],
    explanation: 'Buscar previos va antes que cualquier tabla. Sin previos, un nodulo solido de 6 a 8 mm en un paciente de riesgo alto se vigila con tomografia a los 6 a 12 meses y despues a los 18 a 24. El crecimiento documentado es el dato mas potente a favor de malignidad y saca al nodulo del terreno de la vigilancia: se pasa a positrones y, segun el resultado, a toma de muestra.' },

  { type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 58 a&#241;os que nunca ha fumado. En una angiotomografia hecha por sospecha de embolia pulmonar, descartada, se ve un nodulo en VIDRIO DESLUSTRADO PURO de 9 mm en el lobulo superior izquierdo.',
    steps: [
      { q: 'Que seguimiento corresponde a este nodulo?', options: ['Sin seguimiento rutinario', 'Positrones y biopsia si capta', 'Reseccion en cu&#241;a diagnostica', 'Tomografia a los 6 a 12 meses'], correct: 3 },
      { q: 'Hasta cuando se prolonga el seguimiento si se mantiene estable?', options: ['Hasta los 2 a&#241;os', 'Hasta los 5 a&#241;os', 'Hasta los 3 a&#241;os', 'Hasta los 10 a&#241;os'], correct: 1 },
      { q: 'A los 3 a&#241;os aparece un componente solido de 7 mm. Que corresponde?', options: ['Seguir con controles anuales', 'Repetir en 6 meses y comparar', 'Positrones, biopsia o reseccion', 'Alta por estabilidad del vidrio'], correct: 2 }
    ],
    explanation: 'El vidrio deslustrado puro de 6 mm o mas se controla a los 6 a 12 meses para confirmar que persiste y despues cada 2 a&#241;os hasta los 5, porque estas lesiones crecen muy despacio. Lo que cambia la conducta no es el tama&#241;o global sino el componente SOLIDO: a partir de 6 mm traduce invasion y obliga a positrones, biopsia o reseccion. Un positrones negativo aqui no tranquiliza, porque el crecimiento lepidico capta poco.' },

  { type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 70 a&#241;os con una masa de 4 cm en el lobulo superior derecho. La biopsia muestra adenocarcinoma. En el positrones hay captacion en una adenopatia subcarinal de 12 mm, sin lesiones a distancia. La valoracion funcional lo hace apto para lobectomia.',
    steps: [
      { q: 'Que significa la captacion de esa adenopatia?', options: ['Que el paciente ya no es operable', 'Que hay que confirmarla con puncion', 'Que corresponde iniciar quimioterapia', 'Que basta con ampliar la reseccion'], correct: 1 },
      { q: 'Que prueba se elige para confirmarla?', options: ['Mediastinoscopia de entrada', 'Biopsia transtoracica guiada', 'Puncion pleural diagnostica', 'Ecobroncoscopia con puncion'], correct: 3 },
      { q: 'La puncion es negativa y la mediastinoscopia tambien. Que corresponde?', options: ['Cirugia con diseccion ganglionar', 'Quimiorradioterapia concurrente', 'Tratamiento sistemico paliativo', 'Radioterapia estereotactica sola'], correct: 0 }
    ],
    explanation: 'El positrones tiene falsos positivos frecuentes por infeccion e inflamacion granulomatosa, de modo que una adenopatia captante no basta para negarle a un paciente una cirugia potencialmente curativa. La confirmacion se busca con ecobroncoscopia con puncion, que llega a las estaciones accesibles con menos riesgo que la mediastinoscopia. Con la estadificacion ganglionar negativa, el tratamiento es la lobectomia con diseccion ganglionar mediastinica.' },

  { type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 61 a&#241;os que nunca ha fumado, con adenocarcinoma de pulmon y metastasis oseas y cerebrales. Estado funcional 1. Acude a la primera consulta de oncologia.',
    steps: [
      { q: 'Que debe hacerse antes de iniciar cualquier tratamiento sistemico?', options: ['Iniciar platino y pemetrexed', 'Solicitar marcadores tumorales', 'Estudio molecular completo y PD-L1', 'Empezar inmunoterapia en monoterapia'], correct: 2 },
      { q: 'El estudio detecta una mutacion de EGFR. Que corresponde?', options: ['Inhibidor de tirosina cinasa de EGFR', 'Quimioterapia con platino y pemetrexed', 'Inmunoterapia en monoterapia de inicio', 'Quimioinmunoterapia de primera linea'], correct: 0 },
      { q: 'Que otra medida ha demostrado mejorar la calidad de vida y la supervivencia?', options: ['Radioterapia holocraneal profilactica', 'Irradiacion toracica de consolidacion', 'Anticoagulacion profilactica indefinida', 'Cuidados paliativos precoces'], correct: 3 }
    ],
    explanation: 'En el estadio IV no se inicia tratamiento sistemico sin el perfil molecular y la expresion de PD-L1. El perfil de esta paciente (mujer, nunca fumadora, adenocarcinoma) es en el que mas frecuentes son las alteraciones diana. Con mutacion de EGFR, el inhibidor especifico consigue respuestas prolongadas y es el tratamiento de primera linea. Los cuidados paliativos integrados desde el diagnostico mejoraron la calidad de vida y la supervivencia en un ensayo clasico hecho justamente en este escenario.' },

  { type: 'cascade', dificultad: 'dificil',
    vignette: 'Varon de 68 a&#241;os con EPOC y un carcinoma escamoso en el lobulo inferior derecho, sin afectacion ganglionar confirmada. Se plantea lobectomia inferior derecha, que supone resecar 5 segmentos funcionantes. FEV1 del 68% del predicho y DLCO del 52%.',
    steps: [
      { q: 'Que valores predichos posoperatorios resultan?', options: ['FEV1 del 50% y DLCO del 38%', 'FEV1 del 58% y DLCO del 44%', 'FEV1 del 45% y DLCO del 34%', 'FEV1 del 62% y DLCO del 47%'], correct: 0 },
      { q: 'Que riesgo quirurgico corresponde a esos valores?', options: ['Riesgo bajo: procede la reseccion prevista', 'Riesgo alto: contraindicada la cirugia', 'Riesgo intermedio: prueba de esfuerzo', 'No valorable sin la gammagrafia'], correct: 2 },
      { q: 'El consumo maximo de oxigeno resulta de 9 mL/kg/min. Que corresponde?', options: ['Proceder con la lobectomia programada', 'Valorar radioterapia estereotactica', 'Ampliar a neumonectomia reglada', 'Repetir la prueba en 3 meses'], correct: 1 }
    ],
    explanation: 'Con 5 de los 19 segmentos resecados quedan 14, es decir el 74% de la funcion: el FEV1 predicho posoperatorio es del 50% y la DLCO del 38%. Al quedar entre el 30 y el 60%, el riesgo es intermedio y esta indicada la prueba de esfuerzo cardiopulmonar. Un consumo maximo de oxigeno por debajo de 10 mL/kg/min indica riesgo muy alto de mortalidad perioperatoria: la reseccion mayor se desaconseja y hay que ofrecer una alternativa curativa no quirurgica, como la radioterapia estereotactica corporal.' },

  { type: 'cascade', dificultad: 'facil',
    vignette: 'Varon de 57 a&#241;os, exfumador desde hace 6 a&#241;os, con una carga acumulada de 28 paquetes-a&#241;o. Sin comorbilidad relevante. Pregunta en consulta si deberia hacerse alguna prueba para detectar precozmente un cancer de pulmon.',
    steps: [
      { q: 'Cumple los criterios de cribado con tomografia de baja dosis?', options: ['No: le faltan paquetes-a&#241;o', 'No: es demasiado joven', 'No: dejo de fumar hace tiempo', 'Si: cumple los tres criterios'], correct: 3 },
      { q: 'Con que frecuencia se repite la prueba?', options: ['Cada dos a&#241;os', 'Una vez al a&#241;o', 'Cada seis meses', 'Una sola vez'], correct: 1 },
      { q: 'Que hay que explicarle antes de entrar en el programa?', options: ['Que una tomografia normal descarta el cancer', 'Que el cribado sustituye a dejar de fumar', 'Que la mayoria de hallazgos seran benignos', 'Que rara vez habra que repetir pruebas'], correct: 2 }
    ],
    explanation: 'Cumple los tres criterios: edad entre 50 y 80 a&#241;os, 20 paquetes-a&#241;o o mas, y abandono hace menos de 15. La tomografia de baja dosis se repite de forma anual dentro de un programa con seguimiento estructurado. La conversacion previa es parte del procedimiento: la mayoria de los hallazgos seran nodulos benignos que obligaran a repetir pruebas, existe sobrediagnostico, y el cribado no sustituye a la deshabituacion tabaquica, que debe ofrecerse en cada visita.' }
];

export const flashcards = [
  { front: 'Que es un nodulo pulmonar', back: 'Opacidad de 30 mm o MENOS rodeada de pulmon. Por encima es una masa.' },
  { front: 'Que hacer con una masa mayor de 30 mm', back: 'Estudiarla como un cancer: sin periodos de observacion ni algoritmos de vigilancia.' },
  { front: 'Primer gesto ante un nodulo incidental', back: 'Buscar estudios de imagen PREVIOS: la estabilidad resuelve el caso.' },
  { front: 'Estabilidad que da por benigno un nodulo', back: '2 a&#241;os si es solido; 5 a&#241;os si es subsolido.' },
  { front: 'A quien NO se aplican las guias de Fleischner', back: 'Menores de 35 a&#241;os, inmunodeprimidos, cancer conocido y nodulos de cribado.' },
  { front: 'Nodulo solido unico menor de 6 mm', back: 'Sin seguimiento si el riesgo es bajo; tomografia opcional a los 12 meses si es alto.' },
  { front: 'Nodulo solido unico de 6 a 8 mm', back: 'Tomografia a los 6 a 12 meses y despues a los 18 a 24.' },
  { front: 'Nodulo solido unico mayor de 8 mm', back: 'Tomografia a los 3 meses, positrones o toma de muestra, segun la probabilidad.' },
  { front: 'Vidrio deslustrado puro de 6 mm o mas', back: 'Control a los 6 a 12 meses y despues cada 2 a&#241;os HASTA LOS 5.' },
  { front: 'Parcialmente solido de 6 mm o mas', back: 'Control a los 3 a 6 meses y despues anual hasta los 5 a&#241;os.' },
  { front: 'Que saca a un subsolido de la vigilancia', back: 'Un componente SOLIDO de 6 mm o mas: traduce invasion.' },
  { front: 'Por que el subsolido se sigue 5 a&#241;os', back: 'Las lesiones de la via adenocarcinomatosa crecen muy despacio.' },
  { front: 'Calcificaciones que orientan a benignidad', back: 'Central, laminar concentrica, difusa y en palomita de maiz.' },
  { front: 'Calcificaciones que NO tranquilizan', back: 'Las excentricas y las punteadas: un tumor puede englobar un granuloma.' },
  { front: 'Grasa dentro de un nodulo', back: 'Practicamente diagnostica de HAMARTOMA: cierra el caso.' },
  { front: 'Tres franjas de probabilidad y su conducta', back: 'Menor del 5%: vigilar. Del 5 al 65%: positrones. Mayor del 65%: muestra o reseccion.' },
  { front: 'Falsos negativos del positrones', back: 'Lesiones menores de 8 a 10 mm, adenocarcinoma lepidico y carcinoide.' },
  { front: 'Falsos positivos del positrones', back: 'Infeccion e inflamacion granulomatosa: tuberculosis, sarcoidosis, micosis.' },
  { front: 'Adenopatia mediastinica captante', back: 'Se CONFIRMA con ecobroncoscopia y puncion; no basta para negar la cirugia.' },
  { front: 'Derrame pleural que acompa&#241;a al tumor', back: 'Puncionarlo: si es maligno cambia el estadio y evita una cirugia inutil.' },
  { front: 'Marcadores tumorales ante un nodulo', back: 'NO tienen papel: generan confusion y ansiedad sin aportar nada.' },
  { front: 'Criterios de cribado con baja dosis', back: 'De 50 a 80 a&#241;os, 20 paquetes-a&#241;o o mas, fumador o abandono hace menos de 15 a&#241;os.' },
  { front: 'Cuando se deja de cribar', back: 'A los 15 a&#241;os sin fumar, o si aparece algo que impida un tratamiento curativo.' },
  { front: 'Sistema de informe del cribado', back: 'LUNG-RADS, no las guias de Fleischner.' },
  { front: 'Novedad de la novena edicion del TNM', back: 'Subdivide el N2 en unico y multiple, y el M1c segun afecte a uno o varios organos.' },
  { front: 'Requisito antes de tratar un estadio IV', back: 'Estudio molecular completo y expresion de PD-L1.' },
  { front: 'Estadio III irresecable', back: 'Quimiorradioterapia concurrente seguida de DURVALUMAB de consolidacion.' },
  { front: 'Estadio I no operable', back: 'Radioterapia estereotactica corporal, alternativa curativa no quirurgica.' },
  { front: 'Enfermedad limitada en el microcitico', back: 'Platino y etoposido CONCURRENTE con radioterapia toracica.' },
  { front: 'Prueba obligatoria en todo microcitico', back: 'Resonancia cerebral: las metastasis son frecuentes y a menudo asintomaticas.' },
  { front: 'Paraneoplasicos por estirpe', back: 'Microcitico: hiponatremia y Lambert-Eaton. Escamoso: hipercalcemia. Adenocarcinoma: acropaquias.' },
  { front: 'Funcion predicha posoperatoria', back: 'Valor preoperatorio por (19 menos segmentos resecados) entre 19. Ambos mayores del 60%: opera.' }
];

export default { quiz, flashcards };
