// topics/quemaduras/study.js: Autoevaluacion de quemaduras.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
// Fuentes: Jeschke MG, et al. Burn injury. Nat Rev Dis Primers 2020;6:11; manual ATLS de 10.a
// edicion, capitulo 9. 30 sueltas + 6 cascadas de 3 = 48 subpreguntas, 32 tarjetas.

export const quiz = [
  { q:'&#191;Que quemaduras NO se cuentan al calcular la superficie quemada?', options:['Las de espesor total', 'Las electricas', 'Las de espesor parcial profundo', 'Las superficiales'], correct:3, explanation:'Solo se suman las de espesor parcial o total. Incluir las superficiales (primer grado) sobreestima la superficie y lleva a la sobrerreanimacion.', dificultad:'facil' },
  { q:'Segun la regla de los nueves, &#191;que porcentaje corresponde a un miembro inferior completo del adulto?', options:['El 9%', 'El 27%', 'El 18%', 'El 4.5%'], correct:2, explanation:'Cabeza y cuello 9%, cada miembro superior 9%, tronco anterior 18%, tronco posterior 18%, cada miembro inferior 18% y perine 1%.', dificultad:'facil' },
  { q:'&#191;Que superficie aproximada representa la palma de la mano del paciente con los dedos?', options:['El 1%', 'El 5%', 'El 0.1%', 'El 9%'], correct:0, explanation:'Aproximadamente un 1% de su superficie corporal. Es util para estimar quemaduras irregulares o salpicadas.', dificultad:'facil' },
  { q:'&#191;Por que no se usa la regla de los nueves en el ni&#241;o?', options:['Porque su piel es mas gruesa', 'Porque las quemaduras son menos profundas', 'Porque sus proporciones corporales son otras', 'Porque se calcula por el peso y no la superficie'], correct:2, explanation:'La cabeza del ni&#241;o tiene una proporcion mayor de superficie y las extremidades menor. Se usan los diagramas de Lund y Browder.', dificultad:'facil' },
  { q:'&#191;Como es tipicamente una quemadura de espesor total?', options:['Roja y dolorosa, sin ampollas', 'Con ampollas y muy dolorosa', 'Humeda y palida a la presion', 'Seca e insensible'], correct:3, explanation:'Es seca e insensible al tacto ligero y al pinchazo, y paradojicamente casi no duele porque destruye las terminaciones nerviosas. Salvo que sea muy peque&#241;a, necesita cirugia.', dificultad:'facil' },
  { q:'&#191;Que quemadura de espesor parcial necesita cirugia?', options:['La profunda', 'La superficial', 'Ninguna de ellas', 'Solo la de la cara'], correct:0, explanation:'La de espesor parcial superficial cura sin cirugia; la profunda, menos dolorosa y mas seca, necesita cirugia y deja cicatriz.', dificultad:'intermedio' },
  { q:'&#191;Que es la zona de estasis de una quemadura?', options:['El area central de necrosis por coagulacion', 'El borde periferico con vasodilatacion', 'Un area con perfusion baja recuperable', 'La zona de tejido sano que rodea la herida'], correct:2, explanation:'Tiene perfusion reducida pero potencialmente recuperable. Es la que una mala reanimacion puede convertir en necrosis. En el centro esta la zona de coagulacion y en la periferia la de hiperemia.', dificultad:'intermedio' },
  { q:'&#191;Que mide la pulsioximetria en un paciente con intoxicacion por monoxido de carbono?', options:['Valores falsamente bajos', 'La carboxihemoglobina real', 'Valores normales falsos', 'Nada, deja de dar lectura'], correct:2, explanation:'La mayoria de los pulsioximetros no distinguen la oxihemoglobina de la carboxihemoglobina, de modo que pueden marcar 98% a 100%. Hace falta la gasometria con carboxihemoglobina.', dificultad:'intermedio' },
  { q:'&#191;Cuanto baja la vida media de la carboxihemoglobina con oxigeno al 100%?', options:['De 4 horas a unos 40 minutos', 'De 12 horas a unas 6 horas', 'De 1 hora a unos 5 minutos', 'No cambia con el oxigeno'], correct:0, explanation:'Respirando aire ambiente es de unas 4 horas, y con oxigeno al 100% baja a unos 40 a 45 minutos. Por eso todo expuesto recibe oxigeno al 100% con mascarilla con reservorio.', dificultad:'intermedio' },
  { q:'&#191;Hasta cuando se mantiene el oxigeno al 100% tras un incendio, segun el Primer?', options:['Hasta que la saturacion supere el 95%', 'Hasta carboxihemoglobina menor del 5%', 'Solo durante la primera media hora de llegada', 'Hasta que el paciente refiera mejoria'], correct:1, explanation:'Aunque no este indicada la intubacion, se mantiene el oxigeno al 100% hasta confirmar niveles de carboxihemoglobina menores del 5%. Los niveles pueden ser normales al llegar si ya recibio oxigeno.', dificultad:'intermedio' },
  { q:'&#191;Que sugiere una acidosis persistente sin otra causa en un paciente de un incendio?', options:['Una intoxicacion por cianuro', 'Una hiperpotasemia por necrosis', 'Una cetoacidosis de ayuno', 'Una sobrecarga de cristaloide'], correct:0, explanation:'La toxicidad por cianuro se diagnostica a menudo clinicamente por una acidosis persistente sin otra causa sistemica. El tratamiento empirico con hidroxocobalamina ha aumentado, con evidencia limitada.', dificultad:'intermedio' },
  { q:'&#191;Que exige la American Burn Association para diagnosticar la lesion por inhalacion?', options:['Hollin en la boca y quemadura facial', 'Carboxihemoglobina mayor del 20%', 'Hipoxemia en la gasometria de ingreso', 'Humo infraglotico en la broncoscopia'], correct:3, explanation:'Exposicion a un agente combustible y signos de humo por debajo de las cuerdas vocales identificados por broncoscopia. Las quemaduras faciales y el hollin solo obligan a explorar.', dificultad:'intermedio' },
  { q:'&#191;Descartan la lesion por inhalacion una gasometria y una radiografia normales al ingreso?', options:['Si, si ambas son normales', 'No, pueden empeorar luego', 'Si, en el paciente consciente', 'No, salvo que haya hollin'], correct:1, explanation:'La respuesta inflamatoria pulmonar tarda en desarrollarse, y los valores pueden deteriorarse con el tiempo. Unos valores normales al ingreso no la excluyen.', dificultad:'intermedio' },
  { q:'&#191;Que diametro minimo de tubo endotraqueal recomienda el ATLS en el adulto quemado?', options:['6.0 mm', '10.0 mm', '5.5 mm', '7.5 mm'], correct:3, explanation:'Al menos 7.5 mm de diametro interno, preferiblemente 8 mm, porque un tubo fino dificulta la ventilacion, la salida de secreciones y la broncoscopia. Y no se recorta, por el edema que va a venir.', dificultad:'intermedio' },
  { q:'Con alta probabilidad de inhalacion, &#191;a partir de que superficie quemada indica el ATLS intubar en el adulto?', options:['Mas del 7.5%', 'Mas del 20%', 'Mas del 60%', 'Mas del 80%'], correct:1, explanation:'Un paciente con alta probabilidad de inhalacion y una quemadura de mas del 20% en el adulto, o de mas del 10% en menores de 10 o mayores de 50 a&#241;os, debe ser intubado.', dificultad:'dificil' },
  { q:'&#191;Con que volumen inicia el ATLS la reanimacion del adulto quemado?', options:['4 mL por kg y por %', '1 mL por kg y por %', '2 mL por kg y por %', '0.5 mL por kg y por %'], correct:2, explanation:'Inicia con 2 mL de Ringer lactato por kg y por % de superficie de espesor parcial o total en 24 horas. La American Burn Association acepta de 2 a 4 mL.', dificultad:'facil' },
  { q:'&#191;Como se reparte el volumen calculado en las primeras 24 horas?', options:['Un tercio en cada periodo de 8 horas', 'De forma uniforme a lo largo del dia', 'Todo en las primeras 12 horas', 'La mitad en las primeras 8 horas'], correct:3, explanation:'La mitad en las primeras 8 horas desde la quemadura y la otra mitad en las 16 siguientes. Las 8 horas se cuentan desde la quemadura, no desde la llegada.', dificultad:'facil' },
  { q:'&#191;Que diuresis objetivo se busca en el adulto quemado?', options:['0.25 mL/kg/h', '5 mL/kg/h', '3 mL/kg/h', '0.5 mL/kg/h'], correct:3, explanation:'0.5 mL/kg/h en el adulto, entre 30 y 50 mL/h para minimizar la sobrerreanimacion, y 1 mL/kg/h en el ni&#241;o de menos de 30 kg.', dificultad:'facil' },
  { q:'&#191;Que papel tiene la formula de Parkland despues de la primera hora?', options:['Fija el volumen exacto de las 24 horas', 'Solo da el ritmo inicial y se titula', 'Se repite cada 8 horas con el nuevo peso', 'Se abandona por la presion venosa central'], correct:1, explanation:'La formula solo da el objetivo inicial; despues se titula cada hora por la diuresis. No hay que bajar a la mitad de golpe a las 8 horas ni dar bolos salvo hipotension.', dificultad:'intermedio' },
  { q:'&#191;Cuando estan indicados los bolos de liquido en el quemado?', options:['Cuando la diuresis baja de 0.5 mL/kg/h', 'Cada 8 horas de forma programada', 'Solo si el paciente esta hipotenso', 'Al cambiar de la primera a la segunda mitad'], correct:2, explanation:'Los bolos se evitan salvo hipotension. Una diuresis baja se maneja ajustando la velocidad de infusion.', dificultad:'intermedio' },
  { q:'Segun la regla de los dieces, &#191;cual es el ritmo inicial para un adulto de 80 kg con un 40% de superficie?', options:['200 mL/h', '400 mL/h', '800 mL/h', '1600 mL/h'], correct:1, explanation:'Se redondea la superficie a la decena (40) y se multiplica por 10: 400 mL/h. Por encima de 80 kg se suman 100 mL/h por cada 10 kg. Vale para adultos de 40 a 130 kg.', dificultad:'dificil' },
  { q:'&#191;Cuando sugiere el Primer el rescate con albumina al 5%?', options:['En toda quemadura del 20% o mas', 'Ante una reanimacion masiva', 'Solo si hay inhalacion asociada', 'Desde la primera hora en el anciano'], correct:1, explanation:'En quien se preve una reanimacion masiva (mas de 1500 mL/h durante 2 horas o mas de 250 mL/kg en 24 horas), desde las 8 horas. Reduce el volumen total de cristaloide.', dificultad:'dificil' },
  { q:'&#191;Que complicaciones produce la sobrerreanimacion con cristaloide?', options:['Sindromes compartimentales', 'Hipernatremia grave', 'Insuficiencia suprarrenal', 'Rabdomiolisis aislada'], correct:0, explanation:'Sindromes compartimentales de extremidades, abdomen y orbita, que pueden requerir descompresion urgente. Por eso la formula es un punto de partida, no un objetivo.', dificultad:'intermedio' },
  { q:'&#191;Por que la quemadura electrica es mas grave de lo que aparenta?', options:['Porque infecta con mas frecuencia', 'Por la necrosis profunda oculta', 'Porque produce arritmias graves', 'Porque no responde a los liquidos'], correct:1, explanation:'La diferente disipacion del calor entre tejidos superficiales y profundos permite una piel relativamente sana sobre una necrosis muscular profunda. Un pu&#241;o cerrado con una entrada peque&#241;a debe alertar.', dificultad:'facil' },
  { q:'Ante una orina rojo oscura en una quemadura electrica, &#191;que diuresis se busca en el adulto?', options:['30 mL/h', '50 mL/h', '100 mL/h', '2 mL/kg/h'], correct:2, explanation:'La guia de la American Burn Association aumenta los liquidos a 4 mL/kg por % para una diuresis de 100 mL/h en el adulto hasta que se aclare la orina, sin esperar al laboratorio.', dificultad:'intermedio' },
  { q:'&#191;Como se trata una quemadura quimica?', options:['Neutralizando el agente cuanto antes', 'Con apositos secos sin irrigar', 'Con lavado abundante de agua tibia', 'Con aceite para arrastrar el producto'], correct:2, explanation:'Lavado abundante con agua tibia al menos 20 a 30 minutos. Los neutralizantes estan contraindicados porque generan calor.', dificultad:'facil' },
  { q:'&#191;Cuanto puede durar la respuesta hipermetabolica tras una quemadura grave?', options:['Hasta 36 meses', 'Unas 72 horas', 'Dos semanas', 'Hasta el alta'], correct:0, explanation:'Tras una fase hipometabolica de 72 a 96 horas aparece la fase de flujo, que puede persistir hasta 36 meses, con catabolismo, resistencia a la insulina y riesgo de fallo de organos.', dificultad:'intermedio' },
  { q:'&#191;Cual es el tratamiento de referencia de la herida de espesor total?', options:['Esperar a que la escara se desprenda', 'Antimicrobiano topico indefinido', 'Escision precoz e injerto', 'Oxigeno hiperbarico diario'], correct:2, explanation:'La escision precoz y el injerto atenuan el estado hipermetabolico, retiran el foco de inflamacion e infeccion y permiten movilizar antes. La espera a que la escara se desprendiera llevaba a la sepsis.', dificultad:'facil' },
  { q:'&#191;Que farmacos mitigan el hipermetabolismo segun el Primer?', options:['Corticoides y heparina', 'Antibioticos y estatinas', 'Insulina y furosemida', 'Propranolol y oxandrolona'], correct:3, explanation:'Los agentes anabolicos como la oxandrolona y los reductores del catabolismo como el propranolol forman parte de los cuidados de soporte y la rehabilitacion.', dificultad:'intermedio' },
  { q:'&#191;Cual de estos es criterio de traslado a un centro de quemados?', options:['Superficial del 15% en el brazo', 'Espesor parcial del 5% en el muslo', 'Quemadura solar extensa sin ampollas', 'Tercer grado a cualquier edad'], correct:3, explanation:'Entre los criterios: espesor parcial de mas del 10%, zonas especiales (cara, manos, pies, genitales, perine, grandes articulaciones), tercer grado a cualquier edad, electricas, quimicas e inhalacion, entre otros.', dificultad:'facil' },

  { type:'cascade', vignette:'Varon de 45 a&#241;os, 80 kg, rescatado de un incendio en su casa. Tiene quemaduras de espesor parcial y total en el tronco anterior completo y en ambos miembros superiores completos, y eritema sin ampollas en la cara. Esta consciente, sin ronquera ni estridor.', steps:[
    { q:'&#191;Que superficie quemada se calcula?', options:['El 45%', 'El 40.5%', 'El 36%', 'El 54%'], correct:2 },
    { q:'&#191;Que volumen en 24 horas estima el ATLS?', options:['Unos 2.880 mL', 'Unos 11.520 mL', 'Unos 23.040 mL', 'Unos 5.760 mL'], correct:3 },
    { q:'&#191;Que diuresis se busca?', options:['Unos 10 mL/h', 'Unos 40 mL/h', 'Unos 100 mL/h', 'Unos 200 mL/h'], correct:1 }
  ], explanation:'Tronco anterior (18%) y ambos miembros superiores (9% + 9%) suman un 36%; el eritema facial sin ampollas es superficial y no se cuenta. Con 2 mL x 80 kg x 36% salen 5.760 mL en 24 horas, la mitad en las primeras 8 horas. La diuresis objetivo es 0.5 mL/kg/h, unos 40 mL/h, y la formula solo da el ritmo inicial.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Mujer de 38 a&#241;os encontrada en un garaje cerrado tras un incendio. Tiene cefalea, nauseas y esta algo confusa. Saturacion del 99% por pulsioximetria. Hollin en la boca y quemaduras faciales leves. Voz normal.', steps:[
    { q:'&#191;Que valor tiene la saturacion del 99%?', options:['Descarta la hipoxemia', 'Indica alcalosis', 'Confirma que no inhalo', 'No excluye el CO'], correct:3 },
    { q:'&#191;Cual es la primera medida?', options:['Oxigeno al 100% con reservorio', 'Oxigeno por gafas a 2 L/min', 'Esperar la gasometria antes', 'Observar y repetir la oximetria'], correct:0 },
    { q:'&#191;Que obligan a hacer el hollin y las quemaduras faciales?', options:['Intubar de inmediato a todos', 'Nada mas, si la voz es normal', 'Explorar faringe y cuerdas', 'Una tomografia craneal urgente'], correct:2 }
  ], explanation:'La pulsioximetria no distingue la carboxihemoglobina y puede marcar 98% a 100%; la cefalea, las nauseas y la confusion orientan a una intoxicacion por monoxido de carbono. Oxigeno al 100% con reservorio de inmediato, que reduce la vida media de unas 4 horas a unos 40 minutos. El hollin y las quemaduras faciales no indican por si solos inhalacion, pero obligan a explorar la faringe posterior y las cuerdas.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 30 a&#241;os, electricista, tras un contacto con una linea de alta tension. Tiene una peque&#241;a quemadura de entrada en la palma derecha, que mantiene cerrada en pu&#241;o, y otra de salida en el pie. La piel del antebrazo parece casi intacta. Orina rojo oscura en la sonda.', steps:[
    { q:'&#191;Que hay que sospechar bajo la piel del antebrazo?', options:['Tejido sano sin lesion', 'Solo edema por el pu&#241;o', 'Una necrosis muscular profunda', 'Una lesion limitada a la dermis'], correct:2 },
    { q:'&#191;Que monitorizacion requiere?', options:['Monitor de ritmo prolongado', 'Solo si pierde la conciencia', 'Solo una glucemia horaria', 'Unicamente la temperatura'], correct:0 },
    { q:'&#191;Como se ajustan los liquidos ante la orina oscura?', options:['Se restringen para no sobrecargar', 'Se mantienen a 2 mL/kg/%', 'Se esperan las cifras de mioglobina', 'Se suben a 4 mL/kg/% hasta aclarar'], correct:3 }
  ], explanation:'En la quemadura electrica una piel casi sana puede cubrir una necrosis muscular profunda, y el pu&#241;o cerrado con entrada peque&#241;a debe alertar. Alto voltaje y lesion por la quemadura indican monitorizacion prolongada del ritmo. Ante la orina oscura se asume mioglobinuria sin esperar al laboratorio: 4 mL/kg por % para una diuresis de 100 mL/h hasta que se aclare.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Mujer de 62 a&#241;os con una quemadura de espesor total circunferencial en la pierna izquierda, de 5 horas de evolucion, en reanimacion con liquidos. Refiere dolor profundo creciente y hormigueo en el pie, que esta frio, con relleno capilar lento. No se palpa el pulso pedio.', steps:[
    { q:'&#191;Que se hace primero?', options:['Elevar y aplicar frio local', 'Retirar joyas y usar Doppler', 'Reducir el ritmo de liquidos', 'Pedir una arteriografia urgente'], correct:1 },
    { q:'Si se confirma el compromiso circulatorio, &#191;que procede?', options:['Amputacion primaria', 'Anticoagulacion plena', 'Una escarotomia', 'Vendaje compresivo'], correct:2 },
    { q:'&#191;Que se vigila despues en el resto del cuerpo?', options:['Otros compartimentos', 'La glucemia horaria', 'La temperatura oral', 'El sodio cada hora'], correct:0 }
  ], explanation:'En la quemadura circunferencial la escara actua como un torniquete al formarse el edema. Se retiran joyas y se comprueba la circulacion distal, con el Doppler como metodo mas preciso para el pulso. Si hay compromiso, escarotomia con interconsulta quirurgica. Y la reanimacion con liquidos obliga a vigilar los demas compartimentos: abdomen, otras extremidades y orbitas.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 70 a&#241;os con un 30% de superficie quemada y lesion por inhalacion confirmada por broncoscopia. Lo atienden en un hospital comarcal a 3 horas por carretera del centro de quemados. Esta intubado y estable.', steps:[
    { q:'&#191;Que puntuacion de Baux tiene?', options:['70', '30', '2100', '100'], correct:3 },
    { q:'&#191;Y la de Baux modificada?', options:['117', '100', '130', '87'], correct:0 },
    { q:'&#191;Que transporte se recomienda?', options:['Terrestre convencional', 'Aereo, por la distancia', 'Esperar a que mejore', 'Terrestre sin sedacion'], correct:1 }
  ], explanation:'Baux: edad mas superficie, 70 + 30 = 100. La version modificada suma 17 puntos por la inhalacion: 117. Cumple criterios de traslado (inhalacion, mas del 10% de espesor parcial) y, por encima de 2 horas o 100 km por tierra, se recomienda el transporte aereo.', dificultad:'dificil' },

  { type:'cascade', vignette:'Ni&#241;o de 3 a&#241;os, 15 kg, con una escaldadura por agua caliente de espesor parcial en el tronco anterior y el brazo derecho. Sus padres le han puesto pasta de dientes en las lesiones. Esta irritable pero estable.', steps:[
    { q:'&#191;Con que se estima la superficie en este ni&#241;o?', options:['Con la regla de los nueves', 'Con la puntuacion de Baux', 'Con la regla de los dieces', 'Con Lund y Browder'], correct:3 },
    { q:'&#191;Con que volumen por kg y por % empieza el ATLS en el ni&#241;o?', options:['1 mL', '2 mL', '3 mL', '1.5 mL'], correct:2 },
    { q:'&#191;Que diuresis se busca?', options:['0.5 mL/kg/h', '1 mL/kg/h', '3 mL/kg/h', '0.1 mL/kg/h'], correct:1 }
  ], explanation:'En el ni&#241;o la regla de los nueves es inexacta y se usan los diagramas de Lund y Browder. El ATLS inicia con 3 mL/kg por % en el ni&#241;o, a&#241;adiendo mantenimiento con dextrosa si pesa menos de 30 kg, y busca una diuresis de 1 mL/kg/h. Los remedios caseros como la pasta de dientes no se recomiendan porque pueden da&#241;ar mas el tejido.', dificultad:'intermedio' }
];

export const flashcards = [
  { front:'Que no se cuenta en la superficie', back:'Las quemaduras SUPERFICIALES (primer grado). Solo espesor parcial o total.' },
  { front:'Regla de los nueves', back:'Cabeza 9, cada brazo 9, tronco anterior 18, tronco posterior 18, cada pierna 18, perine 1.' },
  { front:'La palma del paciente', back:'Con los dedos, aproximadamente un 1% de su superficie.' },
  { front:'Ni&#241;o', back:'Regla de los nueves inexacta: diagramas de Lund y Browder.' },
  { front:'Espesor parcial superficial', back:'Ampollas, exudado, muy dolorosa, palidece a la presion. Cura sin cirugia.' },
  { front:'Espesor parcial profundo', back:'Menos dolorosa, mas seca, no palidece. Necesita cirugia y deja cicatriz.' },
  { front:'Espesor total', back:'Seca, insensible al tacto y al pinchazo, casi sin dolor. Cirugia salvo que sea muy peque&#241;a.' },
  { front:'Zonas de la herida', back:'Coagulacion en el centro, estasis (recuperable) y hiperemia en la periferia.' },
  { front:'Pulsioximetria y monoxido', back:'No distingue la carboxihemoglobina: puede marcar 98% a 100%. Gasometria con carboxihemoglobina.' },
  { front:'Vida media de la carboxihemoglobina', back:'Unas 4 horas con aire ambiente; unos 40 a 45 minutos con oxigeno al 100%.' },
  { front:'Oxigeno tras un incendio', back:'Al 100% con reservorio hasta carboxihemoglobina menor del 5%; empirico 4 a 6 horas si no puede medirse.' },
  { front:'Sintomas del monoxido', back:'Menos del 20%: pocos. 20 a 30%: cefalea y nauseas. 30 a 40%: confusion. 40 a 60%: coma. Mas del 60%: muerte.' },
  { front:'Cianuro', back:'Sospechar ante acidosis persistente sin otra causa sistemica.' },
  { front:'Diagnostico de inhalacion (ABA)', back:'Exposicion a combustible y humo por debajo de las cuerdas en la broncoscopia.' },
  { front:'Radiografia y gasometria normales', back:'No descartan la inhalacion: pueden deteriorarse con el tiempo.' },
  { front:'Intubacion en la inhalacion', back:'Con alta probabilidad de inhalacion y mas del 20% de superficie en el adulto, o mas del 10% en menores de 10 o mayores de 50.' },
  { front:'Tubo endotraqueal', back:'Al menos 7.5 mm en el adulto, sin recortar por el edema.' },
  { front:'Parkland segun el ATLS', back:'2 mL de Ringer lactato por kg y por % en el adulto; 3 mL en el ni&#241;o; 4 mL en la electrica con mioglobinuria.' },
  { front:'Reparto del volumen', back:'Mitad en las primeras 8 horas desde la QUEMADURA; la otra mitad en las 16 siguientes.' },
  { front:'Diuresis objetivo', back:'Adulto 0.5 mL/kg/h (30 a 50 mL/h). Ni&#241;o de menos de 30 kg, 1 mL/kg/h.' },
  { front:'La formula es solo el inicio', back:'Se titula cada hora por la diuresis. Sin bajar a la mitad de golpe ni bolos salvo hipotension.' },
  { front:'Regla de los dieces', back:'% redondeado x 10 = mL/h; mas 100 mL/h por cada 10 kg por encima de 80. Adultos de 40 a 130 kg.' },
  { front:'Reanimacion masiva', back:'Mas de 1500 mL/h durante 2 h o mas de 250 mL/kg en 24 h: albumina al 5% o plasma.' },
  { front:'Sobrerreanimacion', back:'Sindromes compartimentales de extremidades, abdomen y orbita.' },
  { front:'Quemadura electrica', back:'Piel casi sana sobre necrosis profunda. Pu&#241;o cerrado con entrada peque&#241;a. Monitor si alto voltaje, perdida de conciencia o arritmia.' },
  { front:'Mioglobinuria', back:'No esperar al laboratorio: 4 mL/kg/% y diuresis de 100 mL/h en el adulto hasta aclarar la orina.' },
  { front:'Quemadura quimica', back:'Agua tibia abundante, 20 a 30 minutos. Sin neutralizantes, que generan calor.' },
  { front:'Escarotomia', back:'Si una circunferencial compromete circulacion o ventilacion. Con cirujano. Rara vez necesaria en las primeras 6 horas.' },
  { front:'Hipermetabolismo', back:'Fase de reflujo de 72 a 96 h y fase de flujo hasta 36 meses. Propranolol y oxandrolona.' },
  { front:'Escision precoz e injerto', back:'Tratamiento de referencia: atenua el hipermetabolismo y retira el foco de infeccion.' },
  { front:'Criterios de traslado', back:'Espesor parcial mayor del 10%, zonas especiales, tercer grado, electrica, quimica, inhalacion, comorbilidad, trauma, ni&#241;os sin medios, necesidad social.' },
  { front:'Baux', back:'Edad + % de superficie. Modificado: mas 17 puntos si hay inhalacion. Predictor mas aceptado.' }
];

export default { quiz, flashcards };
