// topics/supresion-alcoholica/study.js: Autoevaluacion del sindrome de supresion alcoholica.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
// Fuentes: guia de la ASAM de 2020 (J Addict Med 2020;14(3S Suppl 1):1-72) y validacion de la
// PAWSS (Maldonado JR, et al. Alcohol Alcohol 2015;50(5):509-518).
// 30 sueltas + 6 cascadas de 3 = 48 subpreguntas, 32 tarjetas.

export const quiz = [
  { q:'&#191;Cuando suelen empezar los sintomas de abstinencia tras la ultima toma?', options:['Entre 1 y 3 horas despues', 'Entre 6 y 24 horas despues', 'Entre 48 y 72 horas despues', 'Entre 5 y 7 dias despues'], correct:1, explanation:'Los sintomas tipicamente empiezan entre 6 y 24 horas despues de suspender o reducir el consumo: ansiedad, insomnio, nauseas, temblor, sudoracion, taquicardia e hipertension.', dificultad:'facil' },
  { q:'&#191;Cuando aparece habitualmente el delirium por supresion?', options:['Entre 6 y 12 horas', 'Entre 12 y 24 horas', 'Entre 72 y 96 horas', 'Despues de 10 dias'], correct:2, explanation:'Aparece entre las 72 y las 96 horas tras la ultima toma, y puede durar unas horas, aunque lo habitual son 2 a 3 dias.', dificultad:'facil' },
  { q:'&#191;Cuando tienen su pico las convulsiones por abstinencia?', options:['Hacia las 24 horas', 'Hacia las 4 horas', 'Hacia las 96 horas', 'Hacia los 7 dias'], correct:0, explanation:'Pueden empezar desde las 8 horas, tienen su pico hacia las 24 y pueden aparecer hasta las 48 horas. Pueden llegar sin otros sintomas llamativos.', dificultad:'intermedio' },
  { q:'&#191;Para que NO debe usarse la CIWA-Ar segun la guia?', options:['Para guiar las dosis de benzodiacepina', 'Para clasificar la gravedad actual', 'Para seguir la evolucion del paciente', 'Para diagnosticar la abstinencia'], correct:3, explanation:'Las escalas de gravedad como la CIWA-Ar no deben usarse para diagnosticar, porque otras enfermedades elevan su puntuacion. El diagnostico se hace con criterios como los del DSM-5.', dificultad:'intermedio' },
  { q:'&#191;Que significa una alcoholemia positiva en un paciente con sintomas de abstinencia?', options:['Descarta que se trate de una abstinencia', 'Confirma una intoxicacion sin abstinencia', 'No confirma ni descarta la abstinencia', 'Obliga a esperar a que se negativice'], correct:2, explanation:'La guia pide no descartar ni confirmar la abstinencia por una alcoholemia positiva. Ademas, tener sintomas con alcohol en sangre es un factor de riesgo de complicacion.', dificultad:'intermedio' },
  { q:'&#191;Que puntuacion de CIWA-Ar corresponde a una abstinencia moderada?', options:['De 0 a 5 puntos', 'De 25 a 40 puntos', 'De 41 a 67 puntos', 'De 10 a 18 puntos'], correct:3, explanation:'Leve menor de 10, moderada de 10 a 18 y grave de 19 o mas. La complicada se define por convulsiones, delirium o alucinaciones nuevas, no por un numero.', dificultad:'facil' },
  { q:'&#191;Que define la abstinencia complicada?', options:['Una CIWA-Ar por encima de 30 puntos', 'Una frecuencia cardiaca superior a 140', 'Convulsion, delirium o alucinaciones', 'Una alcoholemia mayor de 300 mg/dL'], correct:2, explanation:'La abstinencia complicada incluye las convulsiones, los signos de delirium (incapacidad para comprender instrucciones, confusion) o las alucinaciones de nueva aparicion.', dificultad:'facil' },
  { q:'&#191;Que pide la guia hacer antes que medir los sintomas?', options:['Estimar el riesgo', 'Obtener una alcoholemia exacta', 'Hacer una tomografia craneal', 'Pedir un electroencefalograma'], correct:0, explanation:'Lo primero es determinar si el paciente tiene riesgo de abstinencia grave o complicada, con una escala validada y los factores de riesgo individuales, ademas de los sintomas actuales.', dificultad:'intermedio' },
  { q:'&#191;Cual de estos es un factor de riesgo de abstinencia complicada?', options:['Consumo exclusivo de cerveza', 'Edad menor de 30 a&#241;os', 'Un delirium previo', 'Consumo solo en fin de semana'], correct:2, explanation:'Entre los factores: delirium o convulsiones previos, muchas abstinencias previas, comorbilidad (sobre todo traumatismo craneal), edad mayor de 65, consumo intenso prolongado, convulsion en el episodio actual, hiperactividad autonomica marcada y dependencia de benzodiacepinas.', dificultad:'facil' },
  { q:'&#191;Con cuantos puntos de PAWSS se considera alto el riesgo?', options:['Con 1 punto o mas', 'Con 4 puntos o mas', 'Con 8 puntos o mas', 'Con 10 puntos'], correct:1, explanation:'Con 4 puntos o mas el riesgo de abstinencia complicada es alto. La guia la recomienda para predecir el riesgo en el paciente medicamente enfermo hospitalizado.', dificultad:'intermedio' },
  { q:'&#191;Que caracteriza a la PAWSS frente a la CIWA-Ar?', options:['Mide la gravedad de los sintomas actuales', 'Sirve tambien para el paciente en delirium', 'Se usa antes de que aparezcan sintomas', 'Sustituye a los criterios del DSM-5'], correct:2, explanation:'La PAWSS predice el riesgo de abstinencia complicada y puede usarse en pacientes que todavia no tienen sintomas. La CIWA-Ar mide la gravedad de los sintomas presentes.', dificultad:'intermedio' },
  { q:'&#191;Que farmacos son de primera linea en la abstinencia alcoholica?', options:['Los antipsicoticos', 'Los agonistas alfa-2', 'Los betabloqueantes', 'Las benzodiacepinas'], correct:3, explanation:'Las benzodiacepinas, por su eficacia para reducir los sintomas y la incidencia de convulsiones y de delirium.', dificultad:'facil' },
  { q:'&#191;Cual es el metodo de dosificacion de benzodiacepinas preferido?', options:['Pauta fija descendente para todos', 'Perfusion continua desde el ingreso', 'Dosis unica al ingreso y observar', 'Tratamiento guiado por sintomas'], correct:3, explanation:'El tratamiento guiado por sintomas es el metodo preferido. La pauta fija se reserva para cuando no puede usarse, y aun asi se vigilan los sintomas y se a&#241;aden dosis si hacen falta.', dificultad:'intermedio' },
  { q:'&#191;Que se recomienda en la abstinencia grave (CIWA-Ar de 19 o mas)?', options:['Carga de benzodiacepina', 'Antipsicotico en monoterapia', 'Solo cuidados de soporte', 'Alcohol intravenoso en perfusion'], correct:0, explanation:'La guia recomienda la dosis de carga inicial (front loading) en la abstinencia grave, con diazepam o clordiazepoxido como agentes preferidos.', dificultad:'intermedio' },
  { q:'&#191;Por que se prefieren las benzodiacepinas de accion larga?', options:['Porque son mas eficaces que las cortas', 'Porque no se metabolizan en el higado', 'Por las ventajas de su mayor duracion', 'Porque no producen sedacion excesiva'], correct:2, explanation:'Ningun agente es mas eficaz que otro, pero las de accion larga se prefieren por los beneficios clinicos de su duracion: cubren mejor el periodo de riesgo y reducen los rebotes.', dificultad:'intermedio' },
  { q:'Si hay hepatopatia significativa, &#191;que benzodiacepina conviene?', options:['La de mayor potencia disponible', 'La de menor metabolismo hepatico', 'La de vida media mas prolongada', 'Se evita y se usa fenobarbital'], correct:1, explanation:'Si hay signos de hepatopatia significativa, o no se dispone de los resultados, la guia pide usar una benzodiacepina con menor metabolismo hepatico.', dificultad:'intermedio' },
  { q:'&#191;Que papel tienen los agonistas alfa-2 y los betabloqueantes?', options:['Coadyuvantes para la hiperactividad autonomica', 'Primera linea en la abstinencia moderada', 'Tratamiento de eleccion de las convulsiones', 'Alternativa a las benzodiacepinas en el delirium'], correct:0, explanation:'Pueden usarse como coadyuvantes de las benzodiacepinas para la hiperactividad autonomica no controlada, pero no deben usarse solos ni para prevenir o tratar convulsiones o delirium.', dificultad:'intermedio' },
  { q:'&#191;Que dice la guia sobre el baclofeno en la abstinencia?', options:['Que es de primera linea si hay cirrosis', 'Que sustituye a la benzodiacepina oral', 'Que no hay evidencia para recomendarlo', 'Que previene el delirium por supresion'], correct:2, explanation:'No hay evidencia suficiente para su uso en el tratamiento de la abstinencia. Tampoco se usa alcohol oral o intravenoso, ni magnesio como tratamiento de la abstinencia en si.', dificultad:'intermedio' },
  { q:'&#191;Cuando puede usarse el fenobarbital segun la guia?', options:['Por cualquier medico en atencion primaria', 'Como farmaco de primera linea en todos', 'Solo en la abstinencia leve ambulatoria', 'Por clinicos con experiencia en su uso'], correct:3, explanation:'Solo por clinicos experimentados, por su estrecho margen terapeutico. Es alternativa si las benzodiacepinas estan contraindicadas y coadyuvante en la grave; la via parenteral solo en entornos muy vigilados.', dificultad:'intermedio' },
  { q:'&#191;Que se administra de inmediato tras una convulsion por abstinencia?', options:['Fenitoina intravenosa en carga', 'Benzodiacepina rapida', 'Un betabloqueante intravenoso', 'Clonidina por via oral'], correct:1, explanation:'Benzodiacepina de accion rapida, como lorazepam o diazepam, por via parenteral, mejor intravenosa. El fenobarbital es una opcion menos preferida.', dificultad:'facil' },
  { q:'&#191;Que dice la guia sobre la fenitoina en las convulsiones por abstinencia?', options:['Que es la primera opcion tras la segunda crisis', 'Que debe darse a todos durante una semana', 'Que se prefiere al lorazepam intravenoso', 'Que no se usa salvo epilepsia de base'], correct:3, explanation:'La fenitoina no debe usarse salvo para tratar una epilepsia concomitante. Los agonistas alfa-2 y los betabloqueantes tampoco: son ineficaces, y los betabloqueantes bajan el umbral convulsivo.', dificultad:'intermedio' },
  { q:'&#191;Cuando se atribuye una convulsion a la abstinencia?', options:['Si dejo de beber en las 48 h previas', 'Si la alcoholemia es negativa al llegar', 'Si el paciente refiere consumo habitual', 'Si la crisis dura menos de cinco minutos'], correct:0, explanation:'Solo si hubo una suspension o reduccion clara del consumo en las 24 a 48 horas previas. Ante una primera convulsion o un patron nuevo, electroencefalograma y neuroimagen.', dificultad:'intermedio' },
  { q:'&#191;Que escala NO se recomienda para seguir el delirium por supresion?', options:['La CAM-ICU', 'La MINDS', 'La RASS', 'La CIWA-Ar'], correct:3, explanation:'La CIWA-Ar no se recomienda en el delirium porque depende de lo que cuenta el paciente. Se usan la CAM-ICU, la Delirium Detection Score, la RASS o la MINDS.', dificultad:'intermedio' },
  { q:'&#191;Cual es el objetivo de sedacion en el delirium por supresion?', options:['Una sedacion profunda con apnea', 'Una agitacion leve controlable', 'Una somnolencia ligera', 'Un paciente totalmente despierto'], correct:2, explanation:'Sedar hasta conseguir y mantener una somnolencia ligera, con benzodiacepinas como primera linea, preferiblemente por via intravenosa.', dificultad:'intermedio' },
  { q:'&#191;Que dice la guia sobre la perfusion continua de benzodiacepinas en el delirium?', options:['Que es superior a los bolos intermitentes', 'Que es obligatoria en la unidad de criticos', 'Que no es superior y resulta mas cara', 'Que reduce la necesidad de intubacion'], correct:2, explanation:'Los bolos intravenosos intermitentes de farmacos de accion larga o corta son aceptables y eficaces. La perfusion continua es bastante mas cara y no ha demostrado superioridad terapeutica.', dificultad:'dificil' },
  { q:'Con dosis intravenosas altas y repetidas de lorazepam o diazepam, &#191;que hay que vigilar?', options:['Hipernatremia y alcalosis', 'Hiperpotasemia e hipoglucemia', 'Hiponatremia y acidosis metabolica', 'Hipercalcemia e hipofosfatemia'], correct:2, explanation:'La guia pide vigilar de cerca la hiponatremia y la acidosis metabolica en los pacientes que reciben dosis intravenosas altas y repetidas.', dificultad:'dificil' },
  { q:'&#191;Que pauta de tiamina describe la guia como habitual?', options:['100 mg al dia de 3 a 5 dias', '10 mg en dosis unica', '1 g diario durante un mes', '500 mg cada hora el primer dia'], correct:0, explanation:'Dosis habitual de 100 mg intravenosa o intramuscular al dia durante 3 a 5 dias, preferiblemente por esas vias si hay mala nutricion, malabsorcion o abstinencia complicada.', dificultad:'facil' },
  { q:'&#191;En que orden se administran la glucosa y la tiamina?', options:['Primero la tiamina y luego la glucosa', 'En dias separados', 'La glucosa dos horas antes', 'En cualquier orden o a la vez'], correct:3, explanation:'La guia indica que pueden administrarse en cualquier orden o de forma simultanea.', dificultad:'intermedio' },
  { q:'&#191;Con que cifra de fosforo indica la guia suplementarlo?', options:['Por debajo de 3 mg/dL', 'Por debajo de 4 mg/dL', 'Por debajo de 2.5 mg/dL', 'Por debajo de 1 mg/dL'], correct:3, explanation:'Si el fosforo es menor de 1 mg/dL hay que suplementarlo. En la hipofosfatemia moderada, de 1 a 2 mg/dL, basta con corregirla con una nutricion adecuada.', dificultad:'dificil' },
  { q:'&#191;Que debe aprovecharse durante el manejo de la abstinencia?', options:['Para tratar el trastorno por consumo', 'Para retirar toda medicacion cronica', 'Para hacer una endoscopia de cribado', 'Para pautar benzodiacepinas indefinidas'], correct:0, explanation:'La guia pide usar ese periodo para implicar al paciente en el tratamiento del trastorno por consumo de alcohol, incluido el farmacologico cuando el estado cognitivo lo permita, con una derivacion activa.', dificultad:'facil' },

  { type:'cascade', vignette:'Varon de 54 a&#241;os ingresado hace 2 dias por una neumonia. Bebe a diario desde hace a&#241;os. Esta tembloroso, sudoroso y ansioso, con frecuencia de 112. Esta orientado y colabora. Hace 3 a&#241;os tuvo una convulsion al dejar de beber.', steps:[
    { q:'&#191;Que escala usarias para medir la gravedad actual?', options:['La RASS', 'La CAM-ICU', 'La CIWA-Ar', 'La de Glasgow'], correct:2 },
    { q:'Puntua 16. &#191;Que gravedad tiene?', options:['Leve', 'Complicada', 'Grave', 'Moderada'], correct:3 },
    { q:'&#191;Que pesa en su riesgo de complicacion?', options:['La neumonia sin mas', 'La edad de 54 a&#241;os', 'La convulsion previa', 'La frecuencia de 112'], correct:2 }
  ], explanation:'Orientado y colaborador, la CIWA-Ar es valida: 16 puntos es una abstinencia moderada que requiere tratamiento farmacologico. Pero lo que mas pesa es el antecedente de convulsiones por abstinencia, uno de los factores de riesgo de complicacion de mas peso, que orienta hacia un tratamiento mas agresivo.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Mujer de 47 a&#241;os en urgencias, CIWA-Ar de 24. Temblor intenso y ansiedad extrema, pero orientada y sin alucinaciones. No tiene hepatopatia conocida. Sin convulsiones en este episodio.', steps:[
    { q:'&#191;Que gravedad tiene la abstinencia?', options:['Leve', 'Moderada', 'Grave', 'Complicada'], correct:2 },
    { q:'&#191;Que estrategia de tratamiento recomienda la guia?', options:['Solo cuidados de soporte', 'Carga inicial de benzodiacepina', 'Gabapentina en monoterapia', 'Clonidina y observacion'], correct:1 },
    { q:'&#191;Que farmacos se prefieren para esa carga?', options:['Diazepam o clordiazepoxido', 'Haloperidol o quetiapina', 'Propofol o ketamina', 'Fenitoina o levetiracetam'], correct:0 }
  ], explanation:'Con 19 puntos o mas la abstinencia es grave, y sin convulsiones, delirium ni alucinaciones no es complicada. La guia recomienda la dosis de carga inicial, con diazepam o clordiazepoxido como agentes preferidos, ambos de accion larga.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 38 a&#241;os traido a urgencias tras una convulsion tonicoclonica generalizada. Dejo de beber hace 30 horas. Ya tuvo convulsiones parecidas en abstinencias previas. La exploracion neurologica es normal y no hay signos meningeos.', steps:[
    { q:'&#191;Que tratamiento se da de inmediato?', options:['Fenitoina intravenosa', 'Lorazepam intravenoso', 'Propranolol intravenoso', 'Clonidina oral'], correct:1 },
    { q:'&#191;Es imprescindible la neuroimagen en este caso?', options:['Si, en toda convulsion', 'No, salvo que repita en 1 h', 'Si, con puncion lumbar', 'No, si el patron es conocido'], correct:3 },
    { q:'&#191;Donde y como se vigila despues?', options:['Alta con benzodiacepina oral', 'Ingreso vigilado cada 12 h', 'Observacion de 2 horas y alta', 'Ingreso solo si repite la crisis'], correct:1 }
  ], explanation:'Benzodiacepina de accion rapida por via parenteral de inmediato. Con antecedente claro de convulsiones por abstinencia, crisis generalizada, exploracion sin focalidad y sin sospecha de meningitis, la neuroimagen puede no ser necesaria. Tras la convulsion, ingreso en un entorno vigilado con reevaluacion cada 12 horas durante 6 a 24 horas, atentos al delirium y a los sueros.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 61 a&#241;os en el cuarto dia de ingreso por una fractura de cadera. Desde esta ma&#241;ana esta desorientado, agitado, ve insectos en la pared, sudoroso y con frecuencia de 128. Su familia cuenta que bebia mucho a diario y que nadie lo pregunto al ingreso.', steps:[
    { q:'&#191;Cual es el diagnostico mas probable?', options:['Alucinosis alcoholica', 'Delirium por supresion', 'Abstinencia leve', 'Demencia con cuerpos de Lewy'], correct:1 },
    { q:'&#191;Con que escala se sigue?', options:['La CIWA-Ar', 'La PAWSS', 'La RASS', 'La AUDIT'], correct:2 },
    { q:'&#191;Que farmaco es la primera linea?', options:['Haloperidol solo', 'Clonidina oral', 'Dexmedetomidina sola', 'Benzodiacepina intravenosa'], correct:3 }
  ], explanation:'Confusion, alucinaciones e hiperactividad autonomica al cuarto dia de abstinencia no reconocida: delirium por supresion. Se sigue con CAM-ICU, RASS o MINDS, no con la CIWA-Ar. La primera linea son las benzodiacepinas intravenosas hasta somnolencia ligera; los antipsicoticos solo como coadyuvantes, y los agonistas alfa-2 no se usan para el delirium. El caso muestra por que hay que cribar el consumo en todo ingreso.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Mujer de 42 a&#241;os en urgencias por abstinencia. CIWA-Ar de 7. No esta intoxicada. Nunca ha tenido convulsiones ni delirium. Sin otras enfermedades relevantes. Vive con su pareja, que puede supervisar la medicacion, y puede volver a consulta en dos dias.', steps:[
    { q:'&#191;Que gravedad tiene?', options:['Moderada', 'Grave', 'Complicada', 'Leve'], correct:3 },
    { q:'&#191;Donde puede tratarse?', options:['De forma ambulatoria', 'En la unidad de criticos', 'En planta de medicina', 'En observacion 72 horas'], correct:0 },
    { q:'&#191;Que prescripcion es razonable?', options:['Benzodiacepina indefinida', 'Pauta corta de 1 a 2 dias', 'Antipsicotico nocturno', 'Baclofeno a dosis altas'], correct:1 }
  ], explanation:'Abstinencia leve, sin intoxicacion, sin antecedentes complicados, sin comorbilidad relevante y con apoyo y seguimiento: cumple los criterios de la guia para el manejo ambulatorio. Puede darse una prescripcion corta, de 1 a 2 dias, hasta la visita de seguimiento.', dificultad:'facil' },

  { type:'cascade', vignette:'Varon de 50 a&#241;os en la unidad de criticos, intubado por una pancreatitis grave. Consumo intenso diario. Desarrolla una abstinencia que no se controla pese a dosis altas de benzodiacepinas. Esta desnutrido.', steps:[
    { q:'&#191;Que puede a&#241;adirse en la abstinencia resistente?', options:['Baclofeno por sonda nasogastrica', 'Propofol, ya que esta ventilado', 'Valproico en monoterapia', 'Alcohol intravenoso'], correct:1 },
    { q:'&#191;Por que via se da la tiamina?', options:['Oral por sonda', 'Parenteral', 'No esta indicada', 'Solo si hay ataxia'], correct:1 },
    { q:'Si el delirium dura mas de 72 horas, &#191;que hay que buscar?', options:['Una dosis de carga mayor', 'La suspension de la tiamina', 'Solo un deficit de magnesio', 'Otra causa o farmaco implicado'], correct:3 }
  ], explanation:'En la abstinencia resistente en criticos, el propofol puede usarse en el paciente que ya requiere ventilacion mecanica, y la dexmedetomidina es otra opcion; el fenobarbital, como coadyuvante con vigilancia estrecha. La tiamina se da por via parenteral en criticos y en el desnutrido. Si el delirium dura mas de 72 horas, buscar delirium farmacologico o abstinencia de otro gabaergico.', dificultad:'dificil' }
];

export const flashcards = [
  { front:'Inicio de los sintomas', back:'Entre 6 y 24 horas despues de la ultima toma.' },
  { front:'Convulsiones por abstinencia', back:'Desde las 8 horas, pico hacia las 24, hasta las 48. Pueden llegar sin otros sintomas.' },
  { front:'Alucinaciones', back:'Entre 12 y 24 horas; se resuelven en 24 a 48 horas si no aparece delirium.' },
  { front:'Delirium por supresion', back:'Entre 72 y 96 horas tras la ultima toma; dura habitualmente 2 a 3 dias.' },
  { front:'CIWA-Ar y diagnostico', back:'NO sirve para diagnosticar: otras enfermedades elevan la puntuacion. El diagnostico se hace con criterios como los del DSM-5.' },
  { front:'Categorias de CIWA-Ar', back:'Leve menor de 10, moderada de 10 a 18, grave de 19 o mas.' },
  { front:'Abstinencia complicada', back:'Convulsion, delirium o alucinaciones de nueva aparicion.' },
  { front:'Alcoholemia positiva', back:'No confirma ni descarta la abstinencia. Sintomas con alcohol en sangre son factor de riesgo de complicacion.' },
  { front:'Lo primero segun la guia', back:'Estimar el RIESGO de abstinencia grave o complicada, antes que medir los sintomas.' },
  { front:'Factores de riesgo de complicacion', back:'Delirium o convulsiones previos, muchas abstinencias, traumatismo craneal, mas de 65 a&#241;os, consumo prolongado, convulsion actual, hiperactividad autonomica marcada.' },
  { front:'PAWSS', back:'Predice abstinencia complicada en el paciente ingresado, antes de los sintomas. Riesgo alto con 4 puntos o mas.' },
  { front:'Validacion de la PAWSS', back:'Identifico CIWA-Ar de 15 o mas con sensibilidad del 93.1% y especificidad del 99.5%.' },
  { front:'Cribado al ingreso', back:'Todo paciente que ingresa se criba para el riesgo de abstinencia, con AUDIT o AUDIT-PC.' },
  { front:'Sin historia o riesgo alto', back:'Orientar las decisiones hacia un tratamiento mas agresivo, sean cuales sean los sintomas.' },
  { front:'Primera linea', back:'Benzodiacepinas: reducen sintomas, convulsiones y delirium.' },
  { front:'Dosificacion preferida', back:'Guiada por SINTOMAS. Pauta fija solo si no se puede, y aun asi con dosis extra segun sintomas.' },
  { front:'Abstinencia grave', back:'Dosis de CARGA inicial con diazepam o clordiazepoxido.' },
  { front:'Que benzodiacepina', back:'Ninguna es mas eficaz, pero se prefieren las de accion larga. Con hepatopatia, una de menor metabolismo hepatico.' },
  { front:'Si no se controla', back:'Primero subir la dosis. Despues, reconsiderar el ambito, cambiar de farmaco o a&#241;adir coadyuvante.' },
  { front:'Alfa-2 y betabloqueantes', back:'Solo coadyuvantes para la hiperactividad autonomica. No previenen convulsiones ni delirium.' },
  { front:'Lo que no se usa', back:'Alcohol oral o intravenoso, baclofeno, valproico en monoterapia y magnesio como tratamiento de la abstinencia.' },
  { front:'Fenobarbital', back:'Solo por clinicos experimentados. Alternativa si hay contraindicacion y coadyuvante. Parenteral solo en criticos.' },
  { front:'Tras una convulsion', back:'Benzodiacepina rapida parenteral (lorazepam o diazepam). Ingreso vigilado, reevaluar cada 12 h durante 6 a 24 h.' },
  { front:'Fenitoina', back:'No en las convulsiones por abstinencia salvo epilepsia de base.' },
  { front:'Atribuir una convulsion a la abstinencia', back:'Solo con suspension clara del consumo en las 24 a 48 h previas. Primera crisis o patron nuevo: EEG y neuroimagen.' },
  { front:'Seguir el delirium', back:'CAM-ICU, RASS, Delirium Detection Score o MINDS. NO la CIWA-Ar.' },
  { front:'Objetivo en el delirium', back:'Somnolencia ligera con benzodiacepina intravenosa. Pueden hacer falta dosis muy altas.' },
  { front:'Antipsicoticos en el delirium', back:'Solo coadyuvantes, nunca en monoterapia.' },
  { front:'Abstinencia resistente en criticos', back:'Fenobarbital coadyuvante, propofol si ya esta ventilado, dexmedetomidina.' },
  { front:'Tiamina', back:'100 mg intravenosa o intramuscular al dia de 3 a 5 dias. Glucosa y tiamina en cualquier orden.' },
  { front:'Magnesio y fosforo', back:'Magnesio si esta bajo, hay arritmias o convulsiones previas. Fosforo si es menor de 1 mg/dL.' },
  { front:'Alta ambulatoria desde urgencias', back:'Leve, o moderada sin complicaciones; sin intoxicacion; sin abstinencia complicada previa; sin comorbilidad significativa; con seguimiento posible.' }
];

export default { quiz, flashcards };
