// topics/leucemia-linfocitica-cronica/study.js: Autoevaluación de Leucemia Linfocítica Crónica.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
// IMPORTANTE (ver memoria del proyecto): cada `correct` se construyó colocando el texto correcto
// FÍSICAMENTE en el índice objetivo y se releyó options+correct+explanation juntos por pregunta
// antes de cerrar el archivo. Antes de terminar, se verificó que grep -c "q:" y
// grep -c "correct: [0-9]" sean iguales entre sí y ambos iguales a 45 (30 sueltas + 5 cascadas x 3
// pasos), no solo el conteo de distribución.
//
// Índices `correct` de las 30 preguntas sueltas, en orden: 2,0,3,1,2,1,3,0,2,1,0,3,1,2,0,3,1,2,0,
// 3,1,0,2,3,1,0,2,3,1,0. Recuento: 0×8, 1×8, 2×7, 3×7. Sin racha >2 ni ciclo fijo.
// Índices `correct` de los pasos de las 5 preguntas en cascada (3 pasos c/u), en orden: 0,1,2 /
// 2,0,3 / 1,3,0 / 0,2,1 / 3,1,2. Recuento: 0×4, 1×4, 2×4, 3×3.

export const quiz = [
  { q: '¿Cuál es la leucemia más frecuente en el adulto en países occidentales?', options: ['Leucemia mieloide aguda', 'Leucemia linfoblástica aguda', 'Leucemia linfocítica crónica', 'Leucemia mieloide crónica'], correct: 2, explanation: 'La leucemia linfocítica crónica es la leucemia más frecuente en el adulto en países occidentales.', dificultad: 'facil' },
  { q: '¿Cuál es el mecanismo celular central que produce la acumulación de linfocitos en la LLC?', options: ['Supervivencia clonal prolongada (escape de la apoptosis normal), más que proliferación rápida', 'Proliferación explosiva similar a la leucemia aguda', 'Deficiencia de hierro en los precursores linfoides', 'Destrucción autoinmune de los precursores linfoides'], correct: 0, explanation: 'La LLC se acumula por supervivencia clonal prolongada (escape de la apoptosis), no por proliferación rápida como en la leucemia aguda.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo diferencia a la LLC de la leucemia aguda en cuanto al comportamiento celular?', options: ['Ambas proliferan explosivamente por igual', 'La LLC nunca afecta la médula ósea', 'La LLC siempre requiere tratamiento inmediato al diagnóstico', 'La LLC se acumula lentamente por supervivencia prolongada, no por proliferación rápida como la leucemia aguda'], correct: 3, explanation: 'La LLC se acumula lentamente por supervivencia clonal prolongada, a diferencia de la proliferación rápida de la leucemia aguda.', dificultad: 'intermedio' },
  { q: '¿Cuál es la prueba diagnóstica definitiva de la LLC?', options: ['Biopsia de médula ósea de rutina', 'Citometría de flujo de sangre periférica', 'Tomografía computarizada', 'Electroforesis de proteínas'], correct: 1, explanation: 'La citometría de flujo de sangre periférica es la prueba diagnóstica definitiva de la LLC.', dificultad: 'facil' },
  { q: '¿Cuál es el umbral de linfocitos B clonales que define LLC franca (a diferencia de MBL)?', options: ['≥1,000 células/µL', '≥2,000 células/µL', '≥5,000 células/µL', '≥20,000 células/µL'], correct: 2, explanation: 'El umbral de linfocitos B clonales que define LLC franca es ≥5,000 células/µL.', dificultad: 'intermedio' },
  { q: '¿Qué es la linfocitosis B monoclonal (MBL)?', options: ['Sinónimo de LLC franca', 'Entidad precursora: clon B &lt;5,000/µL sin adenopatías, organomegalia, ni citopenias', 'Una forma de linfoma agresivo', 'Una complicación autoinmune de la LLC'], correct: 1, explanation: 'La MBL es la entidad precursora de la LLC: un clon B &lt;5,000/µL sin adenopatías, organomegalia, ni citopenias.', dificultad: 'intermedio' },
  { q: '¿Qué caracteriza al linfoma linfocítico pequeño (SLL) en relación con la LLC?', options: ['Es una neoplasia biológicamente distinta con otro inmunofenotipo', 'Nunca se trata con los mismos fármacos que la LLC', 'Solo ocurre en niños', 'Es la misma neoplasia biológica, con predominio de presentación ganglionar/tisular sobre la linfocitosis en sangre periférica'], correct: 3, explanation: 'El SLL es la misma neoplasia biológica que la LLC, con predominio de presentación ganglionar/tisular sobre la linfocitosis en sangre periférica.', dificultad: 'intermedio' },
  { q: '¿Qué factor biológico predice un curso considerablemente más indolente en la LLC?', options: ['IGHV mutado', 'del(17p)/TP53 mutado', 'Edad avanzada al diagnóstico', 'Sexo masculino'], correct: 0, explanation: 'El IGHV mutado predice un curso considerablemente más indolente en la LLC.', dificultad: 'intermedio' },
  { q: '¿Qué alteración citogenética/molecular identifica el grupo de peor pronóstico con resistencia relativa a la quimioinmunoterapia convencional?', options: ['Trisomía 12 aislada', 'del(13q) aislada', 'del(17p)/mutación de TP53', 'IGHV mutado'], correct: 2, explanation: 'La del(17p)/mutación de TP53 identifica el grupo de peor pronóstico con resistencia relativa a la quimioinmunoterapia convencional.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo morfológico característico (aunque no exclusivo) se observa en el frotis de sangre periférica en la LLC?', options: ['Bastones de Auer', 'Sombras de Gumprecht (linfocitos frágiles rotos)', 'Células en diana', 'Cuerpos de Howell-Jolly'], correct: 1, explanation: 'Las sombras de Gumprecht (linfocitos frágiles rotos durante la preparación del frotis) son un hallazgo característico de la LLC.', dificultad: 'facil' },
  { q: '¿Cuál es el manejo apropiado de la LLC de bajo riesgo asintomática?', options: ['Vigilancia activa ("vigilar y esperar"), sin tratamiento citorreductor', 'Quimioterapia intensiva inmediata', 'Trasplante alogénico inmediato', 'Radioterapia de todos los ganglios afectados'], correct: 0, explanation: 'La LLC de bajo riesgo asintomática se maneja con vigilancia activa ("vigilar y esperar"), sin tratamiento citorreductor.', dificultad: 'facil' },
  { q: '¿Por qué NO se inicia tratamiento citorreductor en la LLC asintomática de bajo riesgo?', options: ['Porque el tratamiento siempre es tóxico sin excepción', 'Porque no existen fármacos aprobados para la LLC', 'Porque la enfermedad nunca progresa', 'Porque el inicio temprano de tratamiento no ha demostrado beneficio de supervivencia en la enfermedad asintomática'], correct: 3, explanation: 'El inicio temprano de tratamiento no ha demostrado beneficio de supervivencia en la enfermedad asintomática.', dificultad: 'intermedio' },
  { q: '¿Qué sistema de estadificación clínica es más usado en Norteamérica?', options: ['Binet', 'Rai', 'CLL-IPI', 'Ann Arbor'], correct: 1, explanation: 'El sistema de Rai es el más usado en Norteamérica para la estadificación clínica de la LLC.', dificultad: 'intermedio' },
  { q: '¿Qué sistema de estadificación clínica es más usado en Europa?', options: ['Rai', 'CLL-IPI', 'Binet', 'Ann Arbor'], correct: 2, explanation: 'El sistema de Binet es el más usado en Europa para la estadificación clínica de la LLC.', dificultad: 'intermedio' },
  { q: '¿Qué componentes incluye el CLL-IPI?', options: ['Edad, estadio clínico, IGHV, TP53, y beta-2-microglobulina', 'Únicamente la edad del paciente', 'Únicamente el recuento leucocitario', 'Únicamente el tamaño esplénico'], correct: 0, explanation: 'El CLL-IPI incluye edad, estadio clínico, estado mutacional de IGHV, TP53, y beta-2-microglobulina.', dificultad: 'facil' },
  { q: 'Según el CLL-IPI, ¿cuántos puntos aporta la alteración de TP53?', options: ['1 punto', '2 puntos', '3 puntos', '4 puntos'], correct: 3, explanation: 'La alteración de TP53 aporta 4 puntos en el CLL-IPI, el factor de mayor peso.', dificultad: 'intermedio' },
  { q: '¿Cuál es uno de los criterios iwCLL de enfermedad activa que indica inicio de tratamiento?', options: ['Linfocitosis leve estable sin progresión', 'Citopenias progresivas atribuibles a infiltración medular', 'Un solo ganglio palpable pequeño y estable', 'MBL de bajo conteo sin cambios'], correct: 1, explanation: 'Las citopenias progresivas atribuibles a infiltración medular son un criterio iwCLL de enfermedad activa.', dificultad: 'intermedio' },
  { q: '¿Qué clase de fármacos ha desplazado a la quimioinmunoterapia convencional como primera línea preferida en la mayoría de los pacientes con LLC que requieren tratamiento?', options: ['Corticoides en monoterapia', 'Antibióticos profilácticos', 'Terapias dirigidas (inhibidores de BTK, inhibidores de BCL2)', 'Radioterapia total del cuerpo'], correct: 2, explanation: 'Las terapias dirigidas (inhibidores de BTK, inhibidores de BCL2) han desplazado a la quimioinmunoterapia convencional como primera línea preferida.', dificultad: 'intermedio' },
  { q: '¿Cuál es el blanco terapéutico de los inhibidores de BTK en la LLC?', options: ['La señalización crónica a través del receptor de células B (BCR)', 'El receptor de eritropoyetina', 'La vía JAK-STAT', 'El receptor de andrógenos'], correct: 0, explanation: 'Los inhibidores de BTK bloquean la señalización crónica a través del receptor de células B (BCR), que sostiene la supervivencia del clon.', dificultad: 'intermedio' },
  { q: '¿Qué precaución particular requiere el inicio de venetoclax en la enfermedad de alta carga tumoral?', options: ['Ninguna precaución especial es necesaria', 'Solo requiere vigilancia de la presión arterial', 'Solo requiere vigilancia de la función hepática', 'Riesgo de síndrome de lisis tumoral, que requiere escalonamiento gradual de dosis y profilaxis'], correct: 3, explanation: 'El venetoclax en enfermedad de alta carga tumoral tiene riesgo de síndrome de lisis tumoral, requiriendo escalonamiento gradual de dosis y profilaxis.', dificultad: 'dificil' },
  { q: '¿Cuál es la citopenia autoinmune más frecuente en la LLC?', options: ['Neutropenia autoinmune aislada', 'Anemia hemolítica autoinmune', 'Aplasia pura de la serie roja aislada', 'Pancitopenia autoinmune'], correct: 1, explanation: 'La anemia hemolítica autoinmune es la citopenia autoinmune más frecuente en la LLC.', dificultad: 'facil' },
  { q: '¿Qué prueba de laboratorio confirma la anemia hemolítica autoinmune en la LLC?', options: ['Prueba de antiglobulina directa (Coombs directo) positiva, con reticulocitosis y LDH elevada', 'Únicamente la biometría hemática aislada', 'Únicamente la ferritina sérica', 'Únicamente la velocidad de sedimentación'], correct: 0, explanation: 'El Coombs directo positivo, con reticulocitosis y LDH elevada, confirma la anemia hemolítica autoinmune.', dificultad: 'intermedio' },
  { q: '¿La citopenia autoinmune en la LLC indica automáticamente iniciar tratamiento citorreductor de la enfermedad de base?', options: ['Sí, siempre y en todos los casos sin excepción', 'No, nunca requiere ningún tratamiento', 'No necesariamente; el tratamiento de primera línea es la inmunosupresión (corticoides), salvo que coexista enfermedad activa por otros motivos', 'Sí, pero solo con trasplante alogénico inmediato'], correct: 2, explanation: 'La citopenia autoinmune no indica automáticamente tratamiento citorreductor; el tratamiento de primera línea es la inmunosupresión, salvo enfermedad activa concomitante.', dificultad: 'dificil' },
  { q: '¿Qué fármaco de uso en LLC es un desencadenante reconocido de anemia hemolítica autoinmune cuando se usa en monoterapia?', options: ['Rituximab', 'Venetoclax', 'Ibrutinib', 'Fludarabina'], correct: 3, explanation: 'La fludarabina en monoterapia es un desencadenante reconocido de anemia hemolítica autoinmune.', dificultad: 'intermedio' },
  { q: '¿Por qué las infecciones son una causa importante de morbimortalidad en la LLC?', options: ['Por deficiencia de hierro asociada', 'Por hipogammaglobulinemia progresiva y disfunción de la inmunidad celular', 'Por hipertensión arterial no controlada', 'Por deficiencia de vitamina B12 asociada'], correct: 1, explanation: 'La hipogammaglobulinemia progresiva y la disfunción de la inmunidad celular explican el riesgo infeccioso aumentado en la LLC.', dificultad: 'intermedio' },
  { q: '¿Qué tipo de vacunas deben evitarse en el paciente con LLC dado su estado de inmunosupresión?', options: ['Vacunas de virus vivos atenuados', 'Vacunas inactivadas en general', 'La vacuna antigripal inactivada', 'Ninguna vacuna debe evitarse'], correct: 0, explanation: 'Las vacunas de virus vivos atenuados deben evitarse en el paciente con LLC dado su estado de inmunosupresión.', dificultad: 'facil' },
  { q: '¿Qué tratamiento se considera en el paciente con hipogammaglobulinemia grave e infecciones recurrentes graves pese a medidas preventivas estándar?', options: ['Quimioterapia citotóxica adicional', 'Esplenectomía de rutina', 'Inmunoglobulina de reemplazo (intravenosa o subcutánea)', 'Radioterapia esplénica'], correct: 2, explanation: 'La inmunoglobulina de reemplazo se considera en la hipogammaglobulinemia grave con infecciones recurrentes graves.', dificultad: 'intermedio' },
  { q: '¿Cuál es la forma más frecuente de transformación de Richter?', options: ['Leucemia mieloide aguda', 'Mieloma múltiple', 'Linfoma de Hodgkin exclusivamente', 'Linfoma difuso de células B grandes'], correct: 3, explanation: 'El linfoma difuso de células B grandes es la forma más frecuente de transformación de Richter.', dificultad: 'facil' },
  { q: '¿Qué hallazgo clínico sugiere transformación de Richter en lugar de progresión no transformada de la LLC?', options: ['Crecimiento ganglionar simétrico y lento en todos los sitios por igual', 'Crecimiento ganglionar asimétrico, rápido y desproporcionado, con LDH marcadamente elevada', 'Linfocitosis estable sin cambios', 'Ausencia total de síntomas'], correct: 1, explanation: 'El crecimiento ganglionar asimétrico, rápido y desproporcionado, con LDH marcadamente elevada, sugiere transformación de Richter.', dificultad: 'intermedio' },
  { q: '¿Qué estudio se recomienda para identificar el sitio óptimo de biopsia ante sospecha de transformación de Richter?', options: ['PET-TC, para dirigir la biopsia al sitio de mayor actividad metabólica', 'Radiografía simple de tórax', 'Ecografía abdominal aislada', 'Electrocardiograma'], correct: 0, explanation: 'El PET-TC dirige la biopsia al sitio de mayor actividad metabólica ante sospecha de transformación de Richter.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 72 años, hallazgo incidental de linfocitos B clonales de 3,200/µL en una biometría hemática de rutina. Sin adenopatías palpables, sin esplenomegalia, sin citopenias. Antecedente familiar: hermano con LLC.',
    steps: [
      { q: '¿Cuál es la interpretación más apropiada de este hallazgo?', options: ['Linfocitosis B monoclonal (MBL), dado que el clon está por debajo del umbral diagnóstico de LLC franca y no hay adenopatías/citopenias', 'Leucemia linfocítica crónica franca, dado el antecedente familiar', 'Leucemia linfoblástica aguda', 'Linfoma difuso de células B grandes'], correct: 0 },
      { q: '¿Qué manejo es apropiado en este momento?', options: ['Iniciar quimioinmunoterapia de inmediato', 'Ningún tratamiento; seguimiento periódico con biometría hemática', 'Trasplante alogénico inmediato', 'Esplenectomía profiláctica'], correct: 1 },
      { q: 'En el seguimiento a 2 años, el clon B alcanza 8,000/µL, con adenopatías cervicales nuevas. ¿Cómo se reclasifica este caso?', options: ['Sigue siendo MBL sin cambios', 'Se reclasifica como linfoma de Hodgkin', 'Progresó a leucemia linfocítica crónica franca (clon ≥5,000/µL con adenopatías)', 'Se reclasifica como mieloma múltiple'], correct: 2 }
    ],
    explanation: 'Un clon B &lt;5,000/µL sin adenopatías, organomegalia, ni citopenias es MBL, que no requiere tratamiento sino seguimiento periódico. La progresión a un clon ≥5,000/µL con adenopatías reclasifica el caso como LLC franca.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 68 años con LLC conocida presenta fatiga marcada, pérdida de peso de 12% en 4 meses, sudoración nocturna profusa, y adenopatías cervicales de crecimiento progresivo en las últimas 8 semanas. Hemoglobina 9 g/dL (basal previo 13 g/dL).',
    steps: [
      { q: '¿Esta presentación cumple criterios iwCLL de enfermedad activa?', options: ['No, los síntomas son inespecíficos y no cuentan', 'No, se requiere biopsia de médula ósea primero en todos los casos', 'Sí: síntomas constitucionales y anemia progresiva cumplen criterios de enfermedad activa', 'No, solo aplica si hay trombocitopenia'], correct: 2 },
      { q: '¿Qué estudio molecular debe realizarse ANTES de elegir el esquema de tratamiento?', options: ['IGHV y FISH/TP53', 'Únicamente la biometría hemática de control', 'Únicamente la velocidad de sedimentación', 'Únicamente el perfil lipídico'], correct: 0 },
      { q: 'El estudio confirma del(17p)/TP53 mutado. ¿Qué implica esto para la elección terapéutica?', options: ['Que la quimioinmunoterapia clásica con fludarabina es la mejor opción', 'Que no existe ningún tratamiento eficaz disponible', 'Que se debe posponer el tratamiento indefinidamente', 'Que se prefiere una terapia dirigida (inhibidor de BTK o venetoclax), dado que estos fármacos mantienen eficacia independientemente del estado de TP53'], correct: 3 }
    ],
    explanation: 'Los síntomas constitucionales y la anemia progresiva cumplen criterios iwCLL de enfermedad activa. Antes de elegir el esquema debe realizarse IGHV y FISH/TP53. Confirmado TP53 mutado, se prefiere una terapia dirigida, dado que mantiene eficacia independientemente del estado de TP53, a diferencia de la quimioinmunoterapia clásica.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 65 años con LLC estadio Rai 0 (bajo riesgo, en vigilancia) presenta ictericia leve de aparición súbita y fatiga marcada de 5 días. Hemoglobina 7.5 g/dL (basal 13.5 g/dL), reticulocitos elevados, LDH elevada, haptoglobina baja, Coombs directo positivo.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable?', options: ['Progresión de la LLC por infiltración medular', 'Anemia hemolítica autoinmune', 'Deficiencia de hierro aguda', 'Sangrado gastrointestinal oculto'], correct: 1 },
      { q: '¿Este hallazgo indica automáticamente iniciar tratamiento citorreductor de la LLC de base?', options: ['Sí, es indicación automática y absoluta', 'Sí, siempre requiere quimioinmunoterapia intensiva inmediata', 'Sí, es indicación de trasplante alogénico urgente', 'No necesariamente; el tratamiento de primera línea es la inmunosupresión con corticoides'], correct: 3 },
      { q: '¿Cuál es el tratamiento de primera línea más apropiado en este momento?', options: ['Corticoides sistémicos en dosis altas', 'Quimioinmunoterapia con fludarabina en monoterapia', 'Trasplante alogénico inmediato', 'Esplenectomía de entrada'], correct: 0 }
    ],
    explanation: 'La ictericia súbita con reticulocitosis, LDH elevada, haptoglobina baja y Coombs directo positivo confirma anemia hemolítica autoinmune. Esto no indica automáticamente tratamiento citorreductor de la LLC; el tratamiento de primera línea es la inmunosupresión con corticoides sistémicos en dosis altas.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 70 años con LLC de larga evolución en tratamiento con ibrutinib presenta crecimiento rápido y asimétrico de una adenopatía axilar derecha en 3 semanas, fiebre, y LDH marcadamente elevada, desproporcionada a su LLC basal.',
    steps: [
      { q: '¿Cuál es la sospecha diagnóstica más apropiada?', options: ['Transformación de Richter', 'Progresión no transformada de la LLC de base', 'Infección viral aislada sin relación', 'Reacción adversa aislada al ibrutinib'], correct: 0 },
      { q: '¿Qué estudio es más apropiado para identificar el sitio óptimo de biopsia?', options: ['Radiografía de tórax simple', 'Ecografía abdominal aislada', 'PET-TC, para dirigir la biopsia al sitio de mayor actividad metabólica', 'Electrocardiograma'], correct: 2 },
      { q: 'La biopsia confirma linfoma difuso de células B grandes clonalmente relacionado con la LLC. ¿Cuál es el manejo apropiado?', options: ['Continuar el mismo esquema dirigido usado para la LLC no transformada', 'Quimioinmunoterapia intensiva específica para linfoma agresivo (tipo R-CHOP u otro esquema), distinta del tratamiento de la LLC no transformada', 'Observación sin tratamiento', 'Únicamente radioterapia local'], correct: 1 }
    ],
    explanation: 'El crecimiento ganglionar asimétrico y rápido con LDH marcadamente elevada sugiere transformación de Richter. El PET-TC dirige la biopsia al sitio de mayor actividad metabólica. Confirmado el linfoma difuso de células B grandes, se requiere quimioinmunoterapia intensiva específica para linfoma agresivo, distinta del esquema usado para la LLC no transformada.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 60 años con LLC de alta carga tumoral (linfocitosis marcada, adenopatías voluminosas) inicia venetoclax según protocolo de escalonamiento de dosis.',
    steps: [
      { q: '¿Qué complicación debe vigilarse activamente al iniciar y escalonar la dosis de venetoclax en este paciente de alta carga tumoral?', options: ['Hipertensión arterial exclusivamente', 'Fibrilación auricular exclusivamente', 'Hipotiroidismo', 'Síndrome de lisis tumoral'], correct: 3 },
      { q: '¿Qué medida de profilaxis es apropiada ANTES de iniciar el escalonamiento de dosis en este paciente de alto riesgo?', options: ['Ninguna profilaxis es necesaria', 'Hidratación intravenosa agresiva y agente hipouricemiante (alopurinol o rasburicasa según riesgo)', 'Transfusión profiláctica de plaquetas', 'Antibiótico profiláctico de amplio espectro'], correct: 1 },
      { q: '¿Dónde debe vigilarse inicialmente el escalonamiento de dosis en el paciente de alto riesgo de síndrome de lisis tumoral?', options: ['En el domicilio sin ninguna vigilancia especial', 'En consulta ambulatoria breve sin laboratorio de control', 'Con hospitalización para vigilancia electrolítica estrecha según protocolo', 'Sin ningún seguimiento hasta la siguiente dosis programada'], correct: 2 }
    ],
    explanation: 'El venetoclax en enfermedad de alta carga tumoral tiene riesgo de síndrome de lisis tumoral. La profilaxis apropiada incluye hidratación agresiva y un agente hipouricemiante. El escalonamiento de dosis en el paciente de alto riesgo se vigila con hospitalización y electrolitos seriados según protocolo.'
  }
];

export const flashcards = [
  { front: 'Leucemia más frecuente en el adulto (países occidentales)', back: 'Leucemia linfocítica crónica (LLC).' },
  { front: 'Mecanismo celular central de la LLC', back: 'Supervivencia clonal prolongada (escape de apoptosis), no proliferación rápida.' },
  { front: 'Prueba diagnóstica definitiva de la LLC', back: 'Citometría de flujo de sangre periférica.' },
  { front: 'Umbral de linfocitos B clonales para LLC franca', back: '≥5,000 células/µL.' },
  { front: 'Linfocitosis B monoclonal (MBL)', back: 'Clon B &lt;5,000/µL, sin adenopatías/organomegalia/citopenias; entidad precursora.' },
  { front: 'Linfoma linfocítico pequeño (SLL)', back: 'Misma neoplasia que LLC, predominio ganglionar/tisular sobre linfocitosis.' },
  { front: 'Factor que predice curso indolente en LLC', back: 'IGHV mutado.' },
  { front: 'Alteración de peor pronóstico en LLC', back: 'del(17p)/mutación de TP53.' },
  { front: 'Hallazgo morfológico característico de LLC', back: 'Sombras de Gumprecht en el frotis.' },
  { front: 'Manejo de LLC de bajo riesgo asintomática', back: 'Vigilar y esperar, sin tratamiento citorreductor.' },
  { front: 'Por qué no tratar la LLC asintomática temprano', back: 'El tratamiento temprano no demuestra beneficio de supervivencia.' },
  { front: 'Estadificación de Rai vs. Binet', back: 'Rai: más usado en Norteamérica. Binet: más usado en Europa.' },
  { front: 'Componentes del CLL-IPI', back: 'Edad, estadio clínico, IGHV, TP53, beta-2-microglobulina.' },
  { front: 'Puntos de TP53 en CLL-IPI', back: '4 puntos (el factor de mayor peso).' },
  { front: 'Fármacos que desplazaron a la quimioinmunoterapia en LLC', back: 'Terapias dirigidas: inhibidores de BTK, inhibidores de BCL2.' },
  { front: 'Blanco de los inhibidores de BTK', back: 'Señalización crónica del receptor de células B (BCR).' },
  { front: 'Riesgo del venetoclax en alta carga tumoral', back: 'Síndrome de lisis tumoral; requiere escalonamiento gradual + profilaxis.' },
  { front: 'Citopenia autoinmune más frecuente en LLC', back: 'Anemia hemolítica autoinmune.' },
  { front: 'Confirmación de anemia hemolítica autoinmune', back: 'Coombs directo positivo + reticulocitosis + LDH elevada.' },
  { front: 'Tratamiento de primera línea de citopenia autoinmune en LLC', back: 'Corticoides sistémicos (no indica automáticamente tratar la LLC de base).' },
  { front: 'Fármaco desencadenante de AHAI en monoterapia', back: 'Fludarabina.' },
  { front: 'Por qué infecciones frecuentes en LLC', back: 'Hipogammaglobulinemia progresiva + disfunción de inmunidad celular.' },
  { front: 'Vacunas a evitar en LLC', back: 'Vacunas de virus vivos atenuados.' },
  { front: 'Tratamiento de hipogammaglobulinemia grave con infecciones recurrentes', back: 'Inmunoglobulina de reemplazo.' },
  { front: 'Forma más frecuente de transformación de Richter', back: 'Linfoma difuso de células B grandes.' },
  { front: 'Hallazgo sugestivo de transformación de Richter', back: 'Crecimiento ganglionar asimétrico rápido + LDH marcadamente elevada.' },
  { front: 'Estudio para dirigir biopsia en sospecha de Richter', back: 'PET-TC (sitio de mayor actividad metabólica).' }
];
