// topics/anemias-hemoliticas-adquiridas/study.js: Autoevaluación de Anemias Hemolíticas Adquiridas.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Índices `correct` de las 30 preguntas sueltas, en orden: 2,0,3,1,2,0,1,3,0,3,3,1,0,2,1,2,0,2,1,
// 3,0,1,2,3,1,0,3,2,1,3. Recuento: 0×7, 1×8, 2×7, 3×8. Sin racha >2 ni ciclo fijo.
// Índices `correct` de los pasos de las 5 preguntas en cascada (3 pasos c/u), en orden: 1,0,2 /
// 2,3,1 / 3,1,2 / 0,2,3 / 1,0,3. Recuento: 0×3, 1×4, 2×4, 3×4.

export const quiz = [
  { q: '¿Cuál es el mecanismo predominante de destrucción eritrocitaria en la AHAI caliente?', options: ['Fragmentación mecánica en una microvasculatura ocluida por microtrombos', 'Lisis directa por el complejo de ataque de membrana del complemento', 'Fagocitosis extravascular esplénica mediada por receptores Fc tras la unión de IgG', 'Defecto estructural intrínseco de la membrana eritrocitaria'], correct: 2, explanation: 'Los macrófagos esplénicos, ricos en receptores Fc-gamma, fagocitan el eritrocito recubierto de IgG (o porciones de su membrana), produciendo hemólisis predominantemente extravascular esplénica.', dificultad: 'facil' },
  { q: 'En la AHAI caliente, ¿qué hallazgo característico se observa en el frotis de sangre periférica?', options: ['Esferocitos', 'Esquistocitos', 'Dianocitos', 'Drepanocitos'], correct: 0, explanation: 'La pérdida de membrana por la fagocitosis parcial esplénica produce esferocitos, el hallazgo característico de la AHAI caliente.', dificultad: 'facil' },
  { q: '¿Cuál es el patrón típico de la prueba de antiglobulina directa (Coombs directa) en la AHAI fría (enfermedad por crioaglutininas)?', options: ['Positiva para IgG únicamente', 'Positiva para IgG y C3d simultáneamente en igual intensidad', 'Negativa en la mayoría de los casos', 'Positiva solo para C3d, sin IgG detectable'], correct: 3, explanation: 'El IgM se disocia de la membrana eritrocitaria a temperatura ambiente antes de realizar la prueba, dejando solo el C3d fijado como positivo.', dificultad: 'intermedio' },
  { q: '¿Por qué la esplenectomía es poco eficaz en la AHAI fría, a diferencia de la caliente?', options: ['Porque el bazo no puede extirparse quirúrgicamente en estos pacientes', 'Porque la destrucción eritrocitaria es predominantemente hepática (vía Kupffer) y mediada por complemento, no esplénica', 'Porque la AHAI fría no produce ningún grado de hemólisis', 'Porque el bazo produce el autoanticuerpo IgM directamente'], correct: 1, explanation: 'En la AHAI fría, los eritrocitos opsonizados con C3b son fagocitados por receptores hepáticos (Kupffer), no por macrófagos esplénicos, por lo que la esplenectomía aporta poco beneficio.', dificultad: 'intermedio' },
  { q: '¿Cuál es el tratamiento de elección en la enfermedad por crioaglutininas sintomática crónica?', options: ['Esplenectomía de primera línea', 'Corticoide en dosis altas de forma indefinida', 'Rituximab (en monoterapia o con bendamustina)', 'Transfusión periódica sin tratamiento dirigido'], correct: 2, explanation: 'Rituximab, solo o combinado con bendamustina, es el tratamiento de elección en la enfermedad por crioaglutininas sintomática crónica.', dificultad: 'facil' },
  { q: '¿Qué mide el PLASMIC score?', options: ['La probabilidad de deficiencia grave de ADAMTS13 antes de tener el resultado del ensayo', 'La gravedad de la insuficiencia renal en el SHU', 'El riesgo de recaída de la AHAI caliente', 'El tamaño de la clona de hemoglobinuria paroxística nocturna'], correct: 0, explanation: 'El PLASMIC score estima, con 7 variables clínicas y de laboratorio disponibles rápidamente, la probabilidad de que la actividad de ADAMTS13 sea &lt;10%.', dificultad: 'intermedio' },
  { q: 'Un paciente con sospecha de PTT tiene un PLASMIC score de 6. ¿Cuál es la conducta más apropiada?', options: ['Esperar el resultado de ADAMTS13 antes de iniciar cualquier tratamiento', 'Iniciar plasmaféresis y corticoide de inmediato, sin esperar la confirmación de ADAMTS13', 'Transfundir plaquetas de forma profiláctica sin más estudio', 'Descartar PTT y buscar otro diagnóstico'], correct: 1, explanation: 'Un PLASMIC score de 6-7 corresponde a alto riesgo (~62-82% de probabilidad de ADAMTS13 &lt;10%); debe iniciarse plasmaféresis urgente sin esperar la confirmación del ensayo.', dificultad: 'intermedio' },
  { q: '¿Cuál es el hallazgo característico del frotis de sangre periférica en la microangiopatía trombótica (PTT/SHU)?', options: ['Esferocitos', 'Dianocitos', 'Cuerpos de Howell-Jolly', 'Esquistocitos abundantes'], correct: 3, explanation: 'La fragmentación mecánica del eritrocito al atravesar una microvasculatura parcialmente ocluida por microtrombos produce esquistocitos abundantes.', dificultad: 'facil' },
  { q: '¿Por qué la transfusión de plaquetas está contraindicada en la PTT salvo sangrado mayor que ponga en riesgo la vida?', options: ['Porque puede alimentar la formación de más microtrombos y empeorar la isquemia de órgano', 'Porque las plaquetas transfundidas no sobreviven más de una hora en estos pacientes', 'Porque produce reacción alérgica grave en todos los casos', 'Porque no existe compatibilidad plaquetaria en la PTT'], correct: 0, explanation: 'Las plaquetas transfundidas pueden incorporarse a los microtrombos ya formados, empeorando potencialmente la isquemia de órgano en la PTT.', dificultad: 'intermedio' },
  { q: '¿Cuál es el mecanismo de acción del caplacizumab en la PTT?', options: ['Repone la actividad de ADAMTS13 de forma directa', 'Inhibe el complemento terminal (C5)', 'Remueve el autoanticuerpo inhibidor por unión directa', 'Bloquea la interacción entre el factor de von Willebrand y las plaquetas'], correct: 3, explanation: 'El caplacizumab es un nanocuerpo que bloquea la interacción entre los multímeros de factor de von Willebrand y el receptor plaquetario, reduciendo la formación de nuevos microtrombos.', dificultad: 'dificil' },
  { q: '¿Cuál es la causa más frecuente del síndrome hemolítico urémico típico?', options: ['Mutación del factor H del complemento', 'Deficiencia grave de ADAMTS13', 'Autoanticuerpo contra el factor de von Willebrand', 'Toxina Shiga de Escherichia coli enterohemorrágico'], correct: 3, explanation: 'El SHU típico es producido por la toxina Shiga de E. coli enterohemorrágico (con frecuencia serotipo O157:H7) tras un pródromo de diarrea.', dificultad: 'facil' },
  { q: '¿Qué distingue fisiopatológicamente al SHU atípico del SHU típico?', options: ['El atípico siempre tiene ADAMTS13 &lt;10%', 'El atípico es producido por desregulación crónica de la vía alterna del complemento, sin el pródromo diarreico característico', 'El atípico solo ocurre en niños tras diarrea sanguinolenta', 'El atípico no produce nunca insuficiencia renal'], correct: 1, explanation: 'El SHU atípico obedece a una desregulación crónica de la vía alterna del complemento (mutaciones de reguladores o autoanticuerpos), sin el pródromo diarreico del SHU típico.', dificultad: 'intermedio' },
  { q: '¿Por qué deben evitarse los antibióticos y antiperistálticos durante la fase diarreica prodrómica del SHU típico?', options: ['Porque se han asociado a mayor liberación de toxina Shiga y peor desenlace', 'Porque están formalmente contraindicados en cualquier diarrea infecciosa', 'Porque aumentan el riesgo de anafilaxia en estos pacientes', 'Porque interfieren con la absorción de hierro'], correct: 0, explanation: 'Los antibióticos y antiperistálticos durante la fase prodrómica se han asociado a mayor liberación de toxina Shiga y a un peor desenlace del SHU típico.', dificultad: 'intermedio' },
  { q: '¿Cuál es el tratamiento dirigido de elección en el SHU atípico confirmado?', options: ['Plasmaféresis diaria indefinida', 'Quimioterapia de inducción', 'Eculizumab o ravulizumab (inhibidores del complemento)', 'Esplenectomía'], correct: 2, explanation: 'Eculizumab o ravulizumab, inhibidores terminales del complemento, son el tratamiento dirigido de elección en el SHU atípico confirmado.', dificultad: 'facil' },
  { q: '¿Qué medida es obligatoria antes o al inicio de un inhibidor del complemento (eculizumab/ravulizumab)?', options: ['Esplenectomía profiláctica', 'Vacunación contra Neisseria meningitidis', 'Transfusión profiláctica de plaquetas', 'Biopsia renal obligatoria'], correct: 1, explanation: 'El bloqueo del complemento terminal aumenta el riesgo de infección meningocócica invasiva, por lo que la vacunación es obligatoria antes o al inicio del tratamiento.', dificultad: 'intermedio' },
  { q: '¿Cuál es el defecto molecular fundamental en la hemoglobinuria paroxística nocturna?', options: ['Deficiencia hereditaria de la enzima G6PD', 'Mutación germinal de un gen de reparación del ADN', 'Mutación somática de PIGA con pérdida de proteínas ancladas a GPI', 'Deficiencia de la cadena beta de la hemoglobina'], correct: 2, explanation: 'Una mutación somática adquirida de PIGA impide la síntesis del anclaje GPI, con pérdida de todas las proteínas normalmente ancladas por él.', dificultad: 'facil' },
  { q: '¿Qué 2 proteínas ancladas a GPI son las más relevantes para explicar la hemólisis de la HPN?', options: ['CD55 y CD59', 'Espectrina y anquirina', 'CD19 y CD20', 'Factor V y factor VIII'], correct: 0, explanation: 'CD55 (inhibidor de la convertasa C3) y CD59 (inhibidor del complejo de ataque de membrana) son los reguladores del complemento ausentes en la clona de HPN.', dificultad: 'intermedio' },
  { q: '¿Cuál es el estándar diagnóstico actual para confirmar y cuantificar la clona de HPN?', options: ['Prueba de Ham exclusivamente', 'Coombs directa', 'Citometría de flujo de alta sensibilidad con FLAER', 'Biopsia de médula ósea exclusivamente'], correct: 2, explanation: 'La citometría de flujo de alta sensibilidad con FLAER es el estándar diagnóstico actual, superior a la histórica prueba de Ham.', dificultad: 'facil' },
  { q: '¿Cuál es la principal causa de mortalidad en la HPN no tratada?', options: ['Infección oportunista', 'Trombosis, con frecuencia en sitios atípicos', 'Sangrado mucocutáneo', 'Insuficiencia cardiaca de alto gasto'], correct: 1, explanation: 'La trombosis, con predilección por sitios atípicos como las venas hepáticas/porta o los senos venosos cerebrales, es la principal causa de mortalidad en la HPN no tratada.', dificultad: 'intermedio' },
  { q: '¿Cuál es el mecanismo por el que la hemoglobina libre circulante contribuye al dolor abdominal y el espasmo esofágico en la HPN?', options: ['Depósito directo de hemosiderina en el músculo liso', 'Formación de cálculos biliares obstructivos agudos', 'Activación directa de receptores opioides intestinales', 'Consumo de óxido nítrico, que promueve disfunción del músculo liso'], correct: 3, explanation: 'La hemoglobina libre consume óxido nítrico, promoviendo disfunción del músculo liso que se manifiesta como espasmo esofágico y dolor abdominal.', dificultad: 'dificil' },
  { q: '¿Qué proporción aproximada de pacientes con anemia aplásica tiene una clona de HPN detectable?', options: ['~50-70%', '&lt;5%', '~20%', '100%'], correct: 0, explanation: 'Hasta 50-70% de los pacientes con anemia aplásica tienen una clona de HPN detectable al diagnóstico o durante el seguimiento.', dificultad: 'intermedio' },
  { q: '¿Qué mecanismo produce la lesión renal aguda en la hemólisis intravascular masiva?', options: ['Depósito de amiloide renal agudo', 'Toxicidad tubular directa por la hemoglobina libre filtrada y sus radicales de hierro', 'Glomerulonefritis membranosa aguda', 'Nefritis intersticial alérgica'], correct: 1, explanation: 'La hemoglobina libre filtrada se reabsorbe y metaboliza en el túbulo proximal, generando radicales libres de hierro que producen daño oxidativo tubular directo.', dificultad: 'facil' },
  { q: '¿Cuál es la medida más eficaz para reducir la progresión de la lesión renal en la hemólisis intravascular masiva?', options: ['Restricción hídrica estricta', 'Diálisis profiláctica en todos los casos', 'Hidratación intravenosa precoz junto con el tratamiento dirigido de la causa hemolítica de base', 'Alcalinización urinaria como única medida, sin hidratación'], correct: 2, explanation: 'La hidratación intravenosa precoz para mantener el flujo tubular, junto con el tratamiento dirigido de la causa hemolítica de base, es la medida más eficaz.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo de laboratorio ayuda a distinguir la hemoglobinuria de un sangrado urológico real?', options: ['La presencia de cristales de oxalato', 'La elevación aislada de creatinina', 'La presencia de proteinuria masiva', 'La ausencia de hematuria verdadera en el sedimento urinario pese a la orina oscura'], correct: 3, explanation: 'En la hemoglobinuria, el examen general de orina muestra hemoglobina positiva sin hematuria verdadera en el sedimento, a diferencia de un sangrado urológico real.', dificultad: 'intermedio' },
  { q: '¿Qué es la panaglutinación en el contexto de una AHAI que requiere transfusión?', options: ['Una reacción alérgica cutánea a la transfusión', 'Una reacción positiva del autoanticuerpo frente a todos los paneles de eritrocitos de reactivo disponibles', 'La ausencia total de reactividad en la compatibilidad cruzada', 'Un tipo de hemólisis intravascular aguda'], correct: 1, explanation: 'El autoanticuerpo reacciona frente a un antígeno de alta frecuencia presente en la mayoría de los eritrocitos de reactivo, produciendo panaglutinación.', dificultad: 'facil' },
  { q: '¿Qué técnica de laboratorio permite excluir un aloanticuerpo clínicamente significativo enmascarado por un autoanticuerpo eritrocitario?', options: ['Eluido del autoanticuerpo seguido de adsorción con eritrocitos de fenotipo conocido', 'Repetir la prueba de Coombs directa varias veces', 'Electroforesis de hemoglobina', 'Prueba de Ham'], correct: 0, explanation: 'El eluido del autoanticuerpo seguido de adsorción con eritrocitos de fenotipo conocido permite excluir un aloanticuerpo enmascarado.', dificultad: 'intermedio' },
  { q: '¿Por qué la reposición de hierro debe hacerse con precaución en un paciente con HPN?', options: ['Porque está formalmente contraindicada en cualquier grado de deficiencia', 'Porque produce anafilaxia en la mayoría de los pacientes con HPN', 'Porque interfiere con la citometría de flujo de forma permanente', 'Porque puede exacerbar transitoriamente la hemólisis al aumentar el tamaño de la clona funcional'], correct: 3, explanation: 'La reposición de hierro puede aumentar transitoriamente el tamaño de la clona hematopoyética funcional, exacerbando la hemólisis.', dificultad: 'dificil' },
  { q: '¿Cuál es el método de referencia actual para cuantificar de forma no invasiva la carga de hierro cardiaca y hepática en un paciente con sobrecarga transfusional?', options: ['Ferritina sérica aislada', 'Biopsia hepática obligatoria en todos los casos', 'RM con secuencia T2*', 'Tomografía computarizada simple'], correct: 2, explanation: 'La RM con secuencia T2* es el método de referencia actual para cuantificar de forma no invasiva la carga de hierro hepática y cardiaca.', dificultad: 'intermedio' },
  { q: '¿Cuál es el fármaco clásicamente asociado a hemólisis inmune inducida por fármacos?', options: ['Paracetamol', 'Metildopa', 'Loratadina', 'Omeprazol'], correct: 1, explanation: 'La metildopa es el fármaco clásicamente asociado a hemólisis inmune inducida por fármacos.', dificultad: 'facil' },
  { q: '¿Qué caracteriza a la hemoglobinuria paroxística a frigore (anticuerpo de Donath-Landsteiner)?', options: ['Un IgM monoclonal de bajo grado exclusivo del adulto mayor', 'Una deficiencia hereditaria de ADAMTS13', 'Una mutación somática de PIGA', 'Un IgG bifásico que fija el complemento en frío y completa la hemólisis al recalentar el eritrocito'], correct: 3, explanation: 'El anticuerpo de Donath-Landsteiner es un IgG bifásico que se une al eritrocito en frío y completa la hemólisis mediada por complemento al recalentarlo.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 34 años con antecedente de lupus eritematoso sistémico presenta fatiga e ictericia progresivas de 2 semanas. Hb 6.8 g/dL, LDH muy elevada, haptoglobina indetectable, bilirrubina indirecta elevada. La prueba de antiglobulina directa es positiva para IgG y C3d. El banco de sangre reporta panaglutinación en el panel de compatibilidad cruzada.',
    steps: [
      { q: '¿Cuál es el diagnóstico hematológico más probable?', options: ['AHAI fría (enfermedad por crioaglutininas)', 'Anemia hemolítica autoinmune caliente secundaria a lupus eritematoso sistémico', 'Microangiopatía trombótica (PTT)', 'Hemoglobinuria paroxística nocturna'], correct: 1 },
      { q: 'Dado que necesita transfusión por anemia sintomática grave, ¿qué estudio de banco de sangre permite excluir un aloanticuerpo clínicamente significativo enmascarado por el autoanticuerpo?', options: ['Eluido del autoanticuerpo seguido de adsorción con eritrocitos de fenotipo conocido', 'Repetir la prueba de Coombs directa varias veces', 'Prueba de Ham', 'Electroforesis de hemoglobina'], correct: 0 },
      { q: 'Mientras se completa ese estudio, la anemia sintomática grave no permite esperar. ¿Cuál es la conducta más apropiada?', options: ['Negar la transfusión hasta completar el estudio inmunohematológico completo', 'Indicar exanguinotransfusión de urgencia', 'Transfundir la unidad "menos incompatible" disponible sin retrasar la transfusión clínicamente necesaria', 'Esperar 72 horas adicionales sin ninguna intervención'], correct: 2 }
    ],
    explanation: 'La anemia hemolítica Coombs directa positiva para IgG en una paciente con lupus define una AHAI caliente secundaria. La panaglutinación por el autoanticuerpo requiere eluido y adsorción para excluir un aloanticuerpo enmascarado; ante anemia sintomática grave, no debe retrasarse una transfusión clínicamente necesaria esperando el estudio completo, sino transfundir la unidad menos incompatible disponible.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 45 años presenta confusión fluctuante, fiebre y equimosis de 4 días de evolución. Plaquetas 12,000/µL, Hb 7.2 g/dL con esquistocitos abundantes en el frotis, LDH muy elevada, haptoglobina indetectable, Coombs directa negativa, creatinina 1.1 mg/dL, INR 1.1, VCM 88 fL. No tiene cáncer activo ni antecedente de trasplante.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable?', options: ['Coagulación intravascular diseminada', 'Síndrome hemolítico urémico típico', 'Púrpura trombocitopénica trombótica (PTT)', 'Anemia hemolítica autoinmune caliente'], correct: 2 },
      { q: 'Calculando el PLASMIC score con estos datos (plaquetas &lt;30, hemólisis combinada presente, sin cáncer, sin trasplante, VCM &lt;90, INR &lt;1.5, creatinina &lt;2.0), ¿qué categoría de riesgo resulta?', options: ['Bajo riesgo (0-4 puntos)', 'Riesgo intermedio (5 puntos)', 'No puede calcularse con los datos disponibles', 'Alto riesgo (6-7 puntos)'], correct: 3 },
      { q: '¿Cuál es la conducta más apropiada dado este resultado, sin esperar la confirmación de ADAMTS13?', options: ['Transfusión profiláctica de plaquetas de inmediato', 'Iniciar plasmaféresis y corticoide de inmediato', 'Vigilancia expectante hasta el resultado de ADAMTS13', 'Iniciar antibiótico empírico de amplio espectro como tratamiento principal'], correct: 1 }
    ],
    explanation: 'La tríada de anemia hemolítica microangiopática, trombocitopenia grave y síntomas neurológicos fluctuantes, con Coombs negativa, sugiere PTT. Los 7 criterios del PLASMIC están todos presentes (7/7 puntos), lo que ubica al paciente en alto riesgo de deficiencia grave de ADAMTS13; debe iniciarse plasmaféresis y corticoide de inmediato sin esperar el resultado del ensayo.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Niño de 4 años presenta diarrea sanguinolenta seguida, 6 días después, de oliguria, palidez y equimosis. Laboratorio: Hb 7.0 g/dL con esquistocitos, plaquetas 45,000/µL, creatinina elevada para la edad, coprocultivo positivo para E. coli productor de toxina Shiga.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable?', options: ['Síndrome hemolítico urémico atípico', 'Púrpura trombocitopénica trombótica', 'Coagulación intravascular diseminada', 'Síndrome hemolítico urémico típico'], correct: 3 },
      { q: '¿Cuál de las siguientes NO debe usarse durante el manejo de la fase diarreica prodrómica de esta enfermedad?', options: ['Hidratación cuidadosa', 'Antibióticos y antiperistálticos', 'Vigilancia de la función renal', 'Manejo de soporte de la insuficiencia renal aguda, incluida diálisis si es necesaria'], correct: 1 },
      { q: '¿Cuál es la conducta respecto a la plasmaféresis en este paciente?', options: ['Está indicada de rutina, igual que en la PTT', 'Está formalmente contraindicada en cualquier caso', 'No ha demostrado beneficio consistente en esta forma y se reserva a casos seleccionados con compromiso neurológico grave', 'Debe iniciarse solo si el paciente desarrolla fiebre'], correct: 2 }
    ],
    explanation: 'El pródromo de diarrea sanguinolenta con toxina Shiga positiva confirma el SHU típico. Los antibióticos y antiperistálticos deben evitarse en la fase prodrómica por asociarse a mayor liberación de toxina y peor desenlace. La plasmaféresis no ha demostrado beneficio consistente en el SHU típico, a diferencia de la PTT, y se reserva a casos seleccionados con compromiso neurológico grave.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 29 años, sin pródromo diarreico, presenta insuficiencia renal aguda progresiva y anemia hemolítica microangiopática 2 semanas después del parto. ADAMTS13 no gravemente deficiente. El estudio genético del complemento identifica una mutación del factor H.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable?', options: ['Síndrome hemolítico urémico atípico', 'Síndrome hemolítico urémico típico', 'Púrpura trombocitopénica trombótica', 'Preeclampsia/síndrome HELLP no complicado'], correct: 0 },
      { q: '¿Cuál es el tratamiento dirigido de elección?', options: ['Plasmaféresis diaria indefinida sin otro tratamiento', 'Antibiótico de amplio espectro', 'Eculizumab o ravulizumab', 'Quimioterapia de inducción'], correct: 2 },
      { q: 'Antes de iniciar este tratamiento, ¿qué medida es obligatoria?', options: ['Esplenectomía profiláctica', 'Biopsia renal en todos los casos', 'Suspensión de toda anticoagulación previa', 'Vacunación contra Neisseria meningitidis'], correct: 3 }
    ],
    explanation: 'La ausencia de pródromo diarreico, un ADAMTS13 no gravemente deficiente, y una mutación de un regulador del complemento (factor H) confirman SHU atípico, desencadenado por el puerperio. Eculizumab o ravulizumab son el tratamiento dirigido de elección, y la vacunación antimeningocócica es obligatoria antes de iniciarlo por el mayor riesgo de infección meningocócica invasiva.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 27 años con hemólisis intravascular crónica Coombs-negativa presenta dolor abdominal agudo, hepatomegalia dolorosa y ascitis de instalación rápida. La citometría de flujo con FLAER, realizada meses atrás por hemoglobinuria recurrente, había documentado una clona grande de hemoglobinuria paroxística nocturna.',
    steps: [
      { q: '¿Cuál es la complicación más probable que explica el cuadro abdominal agudo?', options: ['Colelitiasis pigmentaria simple', 'Síndrome de Budd-Chiari por trombosis de venas hepáticas', 'Pancreatitis aguda', 'Perforación intestinal'], correct: 1 },
      { q: '¿Cuál es la conducta terapéutica inmediata más apropiada, además del manejo de soporte?', options: ['Anticoagulación sistémica de inmediato, con inicio o intensificación simultánea del inhibidor del complemento', 'Observación sin tratamiento hasta confirmar con biopsia hepática', 'Esplenectomía urgente', 'Transfusión profiláctica de plaquetas'], correct: 0 },
      { q: 'Si la hipertensión portal resultante es refractaria al manejo médico y a la anticoagulación, ¿qué intervención debe considerarse?', options: ['Trasplante renal', 'Esplenectomía', 'Quimioterapia de inducción', 'TIPS (derivación portosistémica intrahepática transyugular)'], correct: 3 }
    ],
    explanation: 'El dolor abdominal agudo con hepatomegalia y ascitis en un paciente con HPN conocida sugiere síndrome de Budd-Chiari, la manifestación trombótica más característica de esta enfermedad. El manejo agudo combina anticoagulación sistémica con el inicio o la intensificación del inhibidor del complemento, que trata el mecanismo protrombótico subyacente. Si la hipertensión portal resultante es refractaria, el TIPS es la intervención a considerar.'
  }
];

export const flashcards = [
  { front: 'Mecanismo de destrucción en la AHAI caliente', back: 'Fagocitosis extravascular esplénica mediada por receptores Fc tras la unión de IgG a 37°C.' },
  { front: 'Frotis en la AHAI caliente', back: 'Esferocitos.' },
  { front: 'Coombs directa en la AHAI fría', back: 'Positiva SOLO para C3d (el IgM se disocia a temperatura ambiente).' },
  { front: 'Por qué la esplenectomía falla en la AHAI fría', back: 'La destrucción es predominantemente hepática (Kupffer), no esplénica.' },
  { front: 'Tratamiento de elección en la enfermedad por crioaglutininas', back: 'Rituximab (± bendamustina); evitar corticoide/esplenectomía (poco eficaces).' },
  { front: 'PLASMIC score: qué estima', back: 'Probabilidad de deficiencia grave de ADAMTS13 (&lt;10%) antes del resultado del ensayo.' },
  { front: 'PLASMIC score: bandas de riesgo', back: '0-4 bajo, 5 intermedio, 6-7 alto riesgo.' },
  { front: 'Frotis en la microangiopatía trombótica', back: 'Esquistocitos abundantes.' },
  { front: 'Por qué no transfundir plaquetas en la PTT (salvo sangrado mayor)', back: 'Puede alimentar la formación de más microtrombos y empeorar la isquemia de órgano.' },
  { front: 'Mecanismo del caplacizumab', back: 'Bloquea la interacción entre el factor de von Willebrand y las plaquetas.' },
  { front: 'Causa del SHU típico', back: 'Toxina Shiga de E. coli enterohemorrágico, tras pródromo de diarrea.' },
  { front: 'Causa del SHU atípico', back: 'Desregulación crónica de la vía alterna del complemento, sin pródromo diarreico.' },
  { front: 'Por qué evitar antibióticos/antiperistálticos en el SHU típico prodrómico', back: 'Se asocian a mayor liberación de toxina Shiga y peor desenlace.' },
  { front: 'Tratamiento dirigido del SHU atípico', back: 'Eculizumab o ravulizumab.' },
  { front: 'Medida obligatoria antes de un inhibidor del complemento', back: 'Vacunación contra Neisseria meningitidis.' },
  { front: 'Defecto molecular de la HPN', back: 'Mutación somática de PIGA, con pérdida de proteínas ancladas a GPI.' },
  { front: 'Proteínas GPI clave perdidas en la HPN', back: 'CD55 (inhibe convertasa C3) y CD59 (inhibe complejo de ataque de membrana).' },
  { front: 'Estándar diagnóstico de la HPN', back: 'Citometría de flujo de alta sensibilidad con FLAER.' },
  { front: 'Principal causa de mortalidad en la HPN no tratada', back: 'Trombosis, con frecuencia en sitios atípicos (venas hepáticas/porta, senos venosos cerebrales).' },
  { front: 'Por qué la HPN causa espasmo esofágico/dolor abdominal', back: 'La hemoglobina libre consume óxido nítrico, produciendo disfunción del músculo liso.' },
  { front: 'Prevalencia de clona de HPN en anemia aplásica', back: '~50-70% al diagnóstico o seguimiento.' },
  { front: 'Mecanismo de la lesión renal en hemólisis masiva', back: 'Toxicidad tubular directa por hemoglobina libre filtrada y sus radicales de hierro.' },
  { front: 'Hemoglobinuria vs. sangrado urológico: distinción de laboratorio', back: 'Ausencia de hematuria verdadera en el sedimento urinario pese a la orina oscura.' },
  { front: 'Panaglutinación: qué es', back: 'Reacción positiva del autoanticuerpo frente a todos los eritrocitos de reactivo del panel.' },
  { front: 'Técnica para excluir aloanticuerpo enmascarado por autoanticuerpo', back: 'Eluido del autoanticuerpo seguido de adsorción con eritrocitos de fenotipo conocido.' },
  { front: 'Método de referencia para carga de hierro cardiaca/hepática', back: 'RM con secuencia T2*.' },
  { front: 'Fármaco clásico de hemólisis inmune inducida por fármacos', back: 'Metildopa.' },
  { front: 'Anticuerpo de Donath-Landsteiner', back: 'IgG bifásico; fija complemento en frío, completa la hemólisis al recalentar (hemoglobinuria paroxística a frigore).' }
];
