// topics/vasopresores-sedantes/study.js — Autoevaluación de Vasopresores y Sedantes.

export const quiz = [
  { q: '¿Cuál es el vasopresor de primera línea en choque séptico?', options: ['Dopamina', 'Norepinefrina', 'Vasopresina', 'Dobutamina'], correct: 1, explanation: 'La noradrenalina es el vasopresor de primera línea recomendado (SSC 2026), por su eficacia y menor arritmogenicidad frente a dopamina.', dificultad: 'facil' },
  { q: '¿Cuál es el mecanismo de acción predominante de la norepinefrina?', options: ['Agonista β2 puro', 'Agonista α1 predominante con actividad β1 moderada', 'Antagonista de receptores muscarínicos', 'Bloqueador de canales de calcio'], correct: 1, explanation: 'La norepinefrina es un agonista α1 potente (vasoconstricción) con actividad β1 moderada (inotropismo/cronotropismo leve).', dificultad: 'facil' },
  { q: '¿Cuál es el fármaco de elección en el paro cardiaco?', options: ['Norepinefrina', 'Dobutamina', 'Adrenalina', 'Vasopresina en monoterapia'], correct: 2, explanation: 'La adrenalina (1 mg IV/IO cada 3-5 min) es el fármaco de elección en todos los ritmos de paro cardiaco.', dificultad: 'facil' },
  { q: '¿Por qué ya no se recomienda la "dosis renal" de dopamina (1-3 mcg/kg/min)?', options: ['Porque causa hipertensión severa', 'Porque no tiene respaldo en la evidencia actual para proteger la función renal', 'Porque está prohibida por ley en la mayoría de países', 'Porque solo funciona en niños'], correct: 1, explanation: 'La llamada "dosis renal" de dopamina no reduce la lesión renal ni la mortalidad según la evidencia actual, y esa indicación está abandonada.', dificultad: 'facil' },
  { q: '¿En qué contexto se usa la dobutamina?', options: ['Como vasopresor de primera línea en cualquier choque', 'Como inotrópico en disfunción cardiaca con hipoperfusión persistente pese a fluidos y PAM adecuada', 'Como sedante en ventilación mecánica', 'Como antídoto de opioides'], correct: 1, explanation: 'La dobutamina es un inotrópico (agonista β1) usado cuando hay disfunción cardiaca con hipoperfusión persistente, generalmente añadida a un vasopresor si coexiste hipotensión.', dificultad: 'facil' },
  { q: '¿Cómo se dosifica la vasopresina en choque séptico?', options: ['Se titula al alza según respuesta, igual que la noradrenalina', 'Dosis fija en U/min, sin ajuste por peso ni titulación al alza', 'Solo en bolo único', 'Se ajusta según el lactato sérico'], correct: 1, explanation: 'A diferencia de las catecolaminas, la vasopresina se administra a dosis FIJA (0.01-0.07 U/min) — no se titula al alza; si el efecto es insuficiente se agrega otro agente en vez de aumentar su dosis.', dificultad: 'facil' },
  { q: '¿Cuál es el sedante de elección, junto con propofol, para lograr sedación ligera con el paciente despertable ("cooperativa")?', options: ['Midazolam', 'Dexmedetomidina', 'Vecuronio', 'Ketamina'], correct: 1, explanation: 'La dexmedetomidina (agonista α2) permite sedación ligera con el paciente despertable, sin depresión respiratoria significativa — junto con propofol es de elección según PADIS 2018.', dificultad: 'facil' },
  { q: '¿Qué antídoto revierte la sedación por benzodiacepinas como el midazolam?', options: ['Naloxona', 'Sugammadex', 'Flumazenilo', 'Fisostigmina'], correct: 2, explanation: 'El flumazenilo es el antagonista competitivo del receptor benzodiacepínico; se usa con precaución por riesgo de convulsiones en uso crónico de benzodiacepinas.', dificultad: 'facil' },
  { q: '¿Qué antídoto revierte la depresión respiratoria por opioides como el fentanilo?', options: ['Flumazenilo', 'Naloxona', 'Atropina', 'Sugammadex'], correct: 1, explanation: 'La naloxona es el antagonista opioide competitivo; su duración de acción es más corta que la del fentanilo, por lo que puede requerirse redosificación.', dificultad: 'facil' },
  { q: '¿Qué herramienta se usa para monitorizar objetivamente la profundidad del bloqueo neuromuscular?', options: ['Escala RASS', 'Tren de cuatro (TOF) con estimulador de nervio periférico', 'Escala de Glasgow', 'CAM-ICU'], correct: 1, explanation: 'El tren de cuatro (TOF) mediante estimulador de nervio periférico permite evitar sobre o subdosificación del bloqueador neuromuscular.', dificultad: 'facil' },
  { q: 'Paciente en choque séptico con noradrenalina en dosis crecientes, equivalente aproximado ≈0.3 mcg/kg/min. Según SSC 2026, ¿cuál es el siguiente paso más apropiado?', options: ['Duplicar la dosis de noradrenalina antes de considerar otro agente', 'Agregar vasopresina en dosis fija', 'Cambiar a dopamina', 'Suspender el vasopresor y reevaluar volumen únicamente'], correct: 1, explanation: 'Ante dosis crecientes de noradrenalina (equivalente ≈0.3 mcg/kg/min), la SSC 2026 recomienda agregar vasopresina como segundo agente, en vez de seguir escalando la catecolamina.', dificultad: 'dificil' },
  { q: '¿Por qué la ketamina se prefiere frecuentemente para la inducción de pacientes hemodinámicamente inestables?', options: ['Porque bloquea completamente el sistema simpático', 'Porque estimula la liberación de catecolaminas endógenas, preservando relativamente la estabilidad hemodinámica', 'Porque no tiene ningún efecto cardiovascular', 'Porque es un vasodilatador puro'], correct: 1, explanation: 'La ketamina estimula la liberación de catecolaminas endógenas (efecto simpaticomimético indirecto), lo que explica su relativa estabilidad hemodinámica comparada con otros inductores como el propofol.', dificultad: 'dificil' },
  { q: 'En un paciente con vía aérea difícil anticipada que requiere secuencia rápida, ¿qué ventaja específica ofrece el rocuronio sobre el vecuronio en este escenario?', options: ['Tiene menor duración de acción que vecuronio', 'Puede revertirse rápida y completamente con sugammadex si la intubación falla', 'No requiere sedación previa', 'Tiene efecto analgésico agregado'], correct: 1, explanation: 'El rocuronio, a diferencia del vecuronio, puede revertirse de forma rápida y completa con sugammadex incluso en bloqueo profundo — una ventaja crítica si surge un escenario de "no se puede intubar, no se puede ventilar".', dificultad: 'dificil' },
  { q: '¿Por qué la adrenalina puede elevar el lactato sérico sin que esto indique necesariamente hipoperfusión tisular?', options: ['Porque siempre indica hipoperfusión grave sin excepción', 'Por un efecto β2 propio del fármaco sobre la producción de lactato, independiente de la perfusión', 'Porque inhibe la eliminación renal de lactato', 'El lactato no cambia con adrenalina bajo ninguna circunstancia'], correct: 1, explanation: 'La adrenalina tiene un efecto β2 directo que aumenta la producción de lactato (glucogenólisis/glucólisis aeróbica acelerada), lo cual complica interpretar el lactato como marcador puro de hipoperfusión en pacientes que la reciben.', dificultad: 'dificil' },
  { q: 'Paciente con infusión prolongada de propofol a dosis altas (>4-5 mg/kg/h por más de 48h) desarrolla acidosis metabólica inexplicada, rabdomiólisis y arritmia. ¿Qué se debe sospechar?', options: ['Reacción alérgica simple', 'Síndrome de infusión de propofol (SIP)', 'Sobredosis de midazolam', 'Efecto esperado, no requiere acción'], correct: 1, explanation: 'El síndrome de infusión de propofol es una complicación infrecuente pero potencialmente letal, asociada a dosis altas y uso prolongado, que se manifiesta con acidosis metabólica, rabdomiólisis, arritmias e insuficiencia cardiaca — requiere suspender el fármaco de inmediato.', dificultad: 'dificil' },
  { q: 'Según las guías PADIS 2018, ¿por qué se prefiere dexmedetomidina o propofol sobre midazolam para la sedación de rutina en ventilación mecánica?', options: ['Porque el midazolam es más caro', 'Porque las benzodiacepinas se asocian a mayor incidencia de delirium y mayor duración de la ventilación mecánica', 'Porque el midazolam no tiene ningún efecto sedante', 'No hay ninguna preferencia establecida entre estos agentes'], correct: 1, explanation: 'PADIS 2018 recomienda estrategias de sedación no benzodiacepínica (propofol o dexmedetomidina) sobre benzodiacepinas para sedación de rutina, dada la asociación de estas últimas con mayor delirium y ventilación mecánica prolongada.', dificultad: 'dificil' },
  { q: '¿Cuál es la estrategia recomendada antes de escalar la sedación en un paciente crítico que se muestra agitado?', options: ['Aumentar directamente la dosis de sedante sin más evaluación', 'Evaluar y tratar el dolor primero ("analgesia primero"), ya que el dolor no controlado puede manifestarse como agitación', 'Iniciar bloqueo neuromuscular de inmediato', 'Suspender toda medicación y esperar'], correct: 1, explanation: 'La estrategia "analgesia primero" (analgesia-first) reconoce que el dolor no tratado es una causa frecuente de agitación aparente; tratarlo puede reducir la necesidad de sedación adicional.', dificultad: 'dificil' },
  { q: '¿Qué se espera con el uso de vecuronio en un paciente con falla renal significativa?', options: ['Ningún cambio en la duración del efecto', 'Prolongación de la duración del bloqueo neuromuscular', 'Reversión espontánea más rápida', 'Requiere aumentar la dosis, no reducirla'], correct: 1, explanation: 'El vecuronio tiene eliminación renal parcial además de biliar; en insuficiencia renal (o hepática) la duración de su efecto se prolonga significativamente.', dificultad: 'dificil' },
  { q: '¿Cuál de los siguientes hallazgos NO sería consistente con el efecto farmacológico esperado de la vasopresina?', options: ['Vasoconstricción sistémica', 'Hiponatremia por retención de agua libre', 'Aumento marcado y directo de la frecuencia cardiaca', 'Isquemia digital'], correct: 2, explanation: 'La vasopresina actúa sobre receptores V1 (vasoconstricción) y V2 (antidiuresis), sin efecto cronotrópico ni inotrópico directo — un aumento marcado y directo de la FC no es un efecto farmacológico esperado de este fármaco.', dificultad: 'dificil' },
  { q: '¿Cuál es la base fisiopatológica por la que la vasopresina puede ser útil cuando hay hiporrespuesta a catecolaminas en choque prolongado?', options: ['Porque potencia directamente los receptores α1 adrenérgicos', 'Porque actúa vía receptores V1, independientes de los receptores adrenérgicos que pueden estar regulados a la baja en choque prolongado', 'Porque inhibe el metabolismo hepático de la noradrenalina', 'No existe ninguna base fisiopatológica para su uso combinado'], correct: 1, explanation: 'En choque prolongado, los receptores adrenérgicos pueden regularse a la baja (down-regulation), reduciendo la respuesta a catecolaminas; la vasopresina actúa por una vía completamente distinta (receptores V1), por lo que mantiene su efecto vasoconstrictor.', dificultad: 'dificil' }
];

export const flashcards = [
  { front: 'Vasopresor de primera línea en choque séptico', back: 'Norepinefrina (noradrenalina) — agonista α1 predominante.' },
  { front: 'Fármaco de elección en paro cardiaco', back: 'Adrenalina 1 mg IV/IO cada 3-5 minutos, en todos los ritmos.' },
  { front: '¿Por qué ya no se usa la "dosis renal" de dopamina?', back: 'No tiene respaldo en la evidencia actual para reducir lesión renal ni mortalidad.' },
  { front: 'Dosis de dobutamina', back: '2-20 mcg/kg/min IV; inotrópico, se agrega a un vasopresor si hay hipotensión concomitante.' },
  { front: '¿Cómo se dosifica la vasopresina?', back: 'Dosis FIJA 0.01-0.07 U/min — no se ajusta por peso ni se titula al alza.' },
  { front: 'Antídoto de benzodiacepinas', back: 'Flumazenilo (antagonista competitivo del receptor benzodiacepínico).' },
  { front: 'Antídoto de opioides', back: 'Naloxona (antagonista opioide competitivo); duración más corta que muchos opioides — vigilar recurrencia.' },
  { front: 'Sedante que no causa depresión respiratoria significativa', back: 'Dexmedetomidina (agonista α2) — permite sedación "cooperativa".' },
  { front: 'Sedante de elección en ventilación mecánica según PADIS 2018', back: 'Propofol o dexmedetomidina, preferidos sobre benzodiacepinas (menos delirium, menor duración de VM).' },
  { front: 'Complicación grave de infusión prolongada de propofol a dosis altas', back: 'Síndrome de infusión de propofol: acidosis metabólica, rabdomiólisis, arritmias, insuficiencia cardiaca.' },
  { front: '¿Cuándo es de elección el midazolam pese a preferirse otros sedantes?', back: 'Estado epiléptico y abstinencia alcohólica/benzodiacepínica.' },
  { front: 'Inductor preferido en inestabilidad hemodinámica o broncoespasmo', back: 'Ketamina — preserva la estabilidad hemodinámica y el impulso respiratorio.' },
  { front: 'Analgésico opioide de elección en el paciente crítico', back: 'Fentanilo — inicio rápido, perfil hemodinámico estable.' },
  { front: 'Estrategia recomendada antes de escalar sedación', back: '"Analgesia primero": tratar el dolor puede reducir la necesidad de sedación adicional.' },
  { front: 'Herramienta para monitorizar el bloqueo neuromuscular', back: 'Tren de cuatro (TOF) con estimulador de nervio periférico.' },
  { front: 'Ventaja del rocuronio sobre vecuronio en vía aérea difícil', back: 'Reversión rápida y completa con sugammadex, incluso en bloqueo profundo.' },
  { front: 'Dosis de rocuronio en secuencia rápida', back: '1.2 mg/kg IV — inicio de acción ultrarrápido (~45-60 s), similar a succinilcolina.' },
  { front: '¿Por qué la adrenalina puede elevar el lactato sin hipoperfusión real?', back: 'Efecto β2 propio del fármaco sobre la producción de lactato — interpretar con cautela.' },
  { front: 'Riesgo del uso prolongado de bloqueadores neuromusculares en UCI', back: 'Miopatía/polineuropatía del paciente crítico, mayor con corticoides concomitantes.' },
  { front: 'Escala usada para titular sedación', back: 'RASS (Richmond Agitation-Sedation Scale).' }
];

export const caseSteps = [
  { vignette: 'Paciente de 62 años con choque séptico de foco urinario. Ya recibió 30 mL/kg de cristaloides y se inicia noradrenalina, que se titula hasta 0.3 mcg/kg/min sin alcanzar la PAM objetivo de 65 mmHg. ¿Cuál es el siguiente paso más apropiado?', options: ['Duplicar la dosis de noradrenalina indefinidamente', 'Agregar vasopresina a dosis fija (0.03 U/min)', 'Cambiar a dopamina', 'Suspender vasopresores y repetir bolo de cristaloides únicamente'], correct: 1, explanation: 'Ante dosis crecientes de noradrenalina sin alcanzar la PAM objetivo, se agrega vasopresina como segundo agente a dosis fija, en vez de seguir escalando la catecolamina indefinidamente.' },
  { vignette: 'El paciente requiere intubación por deterioro del estado de conciencia y trabajo respiratorio. Está hipotenso pese a los vasopresores. ¿Qué inductor es más apropiado para la secuencia rápida?', options: ['Propofol a dosis estándar', 'Ketamina', 'Tiopental', 'Ninguno — evitar la sedación por completo'], correct: 1, explanation: 'En un paciente hemodinámicamente inestable, la ketamina es preferida por su efecto simpaticomimético relativo, que ayuda a preservar la estabilidad hemodinámica durante la inducción, a diferencia del propofol que puede profundizar la hipotensión.' },
  { vignette: 'Tras la intubación, se requiere bloqueo neuromuscular breve para facilitar la laringoscopia y no hay contraindicaciones para succinilcolina. Sin embargo, el servicio decide usar un no despolarizante por disponibilidad. ¿Cuál es la opción más adecuada para lograr un inicio de acción similarmente rápido?', options: ['Vecuronio a dosis estándar', 'Rocuronio 1.2 mg/kg', 'Cisatracurio a dosis baja', 'No usar ningún bloqueador'], correct: 1, explanation: 'El rocuronio a dosis de 1.2 mg/kg logra un inicio de acción ultrarrápido (~45-60 s), aproximándose al de la succinilcolina, con la ventaja adicional de ser reversible con sugammadex.' },
  { vignette: 'Ya en la UCI, el paciente está ventilado mecánicamente. El equipo debe elegir la estrategia de sedoanalgesia inicial. ¿Cuál es el enfoque recomendado según las guías actuales?', options: ['Sedación profunda con midazolam en infusión desde el inicio', 'Analgesia con fentanilo primero, evaluando dolor con escala validada, y sedación ligera con propofol o dexmedetomidina según necesidad', 'Bloqueo neuromuscular continuo de rutina sin sedación', 'No administrar ningún analgésico ni sedante'], correct: 1, explanation: 'La estrategia recomendada es "analgesia primero": tratar el dolor con un opioide como fentanilo y evaluarlo con una escala validada, agregando sedación ligera (propofol o dexmedetomidina) solo si es necesaria — evitando benzodiacepinas de rutina (PADIS 2018).' },
  { vignette: 'Al tercer día, el paciente sigue con propofol en infusión a dosis relativamente altas. El laboratorio muestra acidosis metabólica de nueva aparición y elevación de creatina-cinasa. ¿Qué se debe sospechar y qué acción tomar?', options: ['Es un hallazgo esperado sin relevancia clínica; continuar igual', 'Sospechar síndrome de infusión de propofol; suspender el fármaco y buscar la causa de la acidosis', 'Aumentar la dosis de propofol para profundizar la sedación', 'Iniciar antibióticos empíricos sin más estudio'], correct: 1, explanation: 'La combinación de acidosis metabólica inexplicada y elevación de CK en un paciente con infusión prolongada de propofol a dosis altas obliga a sospechar el síndrome de infusión de propofol, que requiere suspensión inmediata del fármaco.' }
];

export const caseSummary = 'Este caso integró la escalada de vasopresores en choque séptico (noradrenalina → vasopresina), la elección de ketamina para inducción en inestabilidad hemodinámica, rocuronio con reversión disponible en secuencia rápida, la estrategia "analgesia primero" para sedoanalgesia, y el reconocimiento del síndrome de infusión de propofol. Repasa las monografías de cada fármaco en la sección Fármacos si alguna decisión no quedó clara.';

export default { quiz, flashcards, caseSteps, caseSummary };
