// topics/vasopresores-sedantes/study.js — Autoevaluación de Vasopresores y Sedantes.
// Opciones reordenadas para cumplir .claude/skills/reglas-preguntas/SKILL.md — posición de
// `correct` distribuida sin patrón a lo largo de todo el banco.

export const quiz = [
  { q: '¿Cuál es el vasopresor de primera línea en choque séptico?', options: ['La dopamina IV', 'La vasopresina IV', 'La norepinefrina', 'La dobutamina IV'], correct: 2, explanation: 'La noradrenalina es el vasopresor de primera línea recomendado (SSC 2026), por su eficacia y menor arritmogenicidad frente a dopamina.', dificultad: 'facil' },
  { q: '¿Cuál es el mecanismo de acción predominante de la norepinefrina?', options: ['Agonista α1 con algo de β1', 'Agonista β2 puro y selectivo', 'Antagonista muscarínico puro', 'Bloqueador de canales de calcio'], correct: 0, explanation: 'La norepinefrina es un agonista α1 potente (vasoconstricción) con actividad β1 moderada (inotropismo/cronotropismo leve).', dificultad: 'facil' },
  { q: '¿Cuál es el fármaco de elección en el paro cardiaco?', options: ['La norepinefrina', 'La dobutamina', 'La vasopresina', 'La adrenalina'], correct: 3, explanation: 'La adrenalina (1 mg IV/IO cada 3-5 min) es el fármaco de elección en todos los ritmos de paro cardiaco.', dificultad: 'facil' },
  { q: '¿Por qué ya no se recomienda la "dosis renal" de dopamina (1-3 mcg/kg/min)?', options: ['Porque provoca hipertensión severa', 'No hay evidencia de protección renal', 'Porque está prohibida en varios países', 'Porque solo funciona en la edad pediátrica'], correct: 1, explanation: 'La llamada "dosis renal" de dopamina no reduce la lesión renal ni la mortalidad según la evidencia actual, y esa indicación está abandonada.', dificultad: 'facil' },
  { q: '¿En qué contexto se usa la dobutamina?', options: ['Inotrópico en disfunción cardiaca', 'Vasopresor de primera línea del choque', 'Sedante durante la ventilación mecánica', 'Antídoto de la intoxicación por opioides'], correct: 0, explanation: 'La dobutamina es un inotrópico (agonista β1) usado cuando hay disfunción cardiaca con hipoperfusión persistente, generalmente añadida a un vasopresor si coexiste hipotensión.', dificultad: 'facil' },
  { q: '¿Cómo se dosifica la vasopresina en choque séptico?', options: ['Se titula al alza, como la noradrenalina', 'Se administra en un bolo único', 'Se ajusta según el lactato sérico', 'Dosis fija en U/min, sin titular'], correct: 3, explanation: 'A diferencia de las catecolaminas, la vasopresina se administra a dosis FIJA (0.01-0.07 U/min) — no se titula al alza; si el efecto es insuficiente se agrega otro agente en vez de aumentar su dosis.', dificultad: 'facil' },
  { q: '¿Cuál es el sedante de elección, junto con propofol, para lograr sedación ligera con el paciente despertable ("cooperativa")?', options: ['El midazolam en infusión', 'La dexmedetomidina', 'El vecuronio en infusión', 'La ketamina en infusión'], correct: 1, explanation: 'La dexmedetomidina (agonista α2) permite sedación ligera con el paciente despertable, sin depresión respiratoria significativa — junto con propofol es de elección según PADIS 2018.', dificultad: 'facil' },
  { q: '¿Qué antídoto revierte la sedación por benzodiacepinas como el midazolam?', options: ['Naloxona', 'Sugammadex', 'Flumazenilo', 'Fisostigmina'], correct: 2, explanation: 'El flumazenilo es el antagonista competitivo del receptor benzodiacepínico; se usa con precaución por riesgo de convulsiones en uso crónico de benzodiacepinas.', dificultad: 'facil' },
  { q: '¿Qué antídoto revierte la depresión respiratoria por opioides como el fentanilo?', options: ['Flumazenilo', 'Atropina', 'Sugammadex', 'Naloxona'], correct: 3, explanation: 'La naloxona es el antagonista opioide competitivo; su duración de acción es más corta que la del fentanilo, por lo que puede requerirse redosificación.', dificultad: 'facil' },
  { q: '¿Qué herramienta se usa para monitorizar objetivamente la profundidad del bloqueo neuromuscular?', options: ['La escala RASS de agitación y sedación', 'El tren de cuatro (TOF)', 'La escala de coma de Glasgow completa', 'El CAM-ICU para el delirium'], correct: 1, explanation: 'El tren de cuatro (TOF) mediante estimulador de nervio periférico permite evitar sobre o subdosificación del bloqueador neuromuscular.', dificultad: 'facil' },
  { q: '¿Qué escala se usa para titular el nivel de sedación en el paciente crítico?', options: ['La escala CAM-ICU', 'La escala APACHE II', 'La escala RASS', 'La escala Glasgow-Blatchford'], correct: 2, explanation: 'La escala RASS es la herramienta estándar para fijar y reevaluar un objetivo explícito de sedación en cada turno.', dificultad: 'facil' },
  { q: '¿Qué escala validada se usa para evaluar el dolor en el paciente crítico que no puede comunicarse verbalmente?', options: ['La escala CPOT', 'La escala RASS', 'La escala NEWS2', 'El score de Lille'], correct: 0, explanation: 'El CPOT (junto con la EVA en pacientes que pueden reportar dolor) es la herramienta validada para evaluar dolor en pacientes críticos no comunicativos, base de la estrategia "analgesia primero".', dificultad: 'facil' },
  { q: '¿Cuáles son contraindicaciones clásicas de la succinilcolina que llevan a preferir rocuronio en secuencia rápida?', options: ['Un asma leve, bien controlada con inhalador', 'Hiperkalemia, quemado o lesión medular', 'Tener menos de 40 años de edad cumplidos', 'Hipertensión arterial bien controlada'], correct: 1, explanation: 'La succinilcolina puede causar hiperkalemia peligrosa en pacientes con quemaduras >24-72h, lesión medular o enfermedades neuromusculares, además de estar contraindicada en hiperkalemia preexistente; en estos casos se prefiere rocuronio.', dificultad: 'facil' },
  { q: 'Paciente en choque séptico con noradrenalina en dosis crecientes, equivalente aproximado ≈0.3 mcg/kg/min. Según SSC 2026, ¿cuál es el siguiente paso más apropiado?', options: ['Duplicar la dosis de noradrenalina antes de considerar otro agente', 'Cambiar a dopamina', 'Agregar vasopresina en dosis fija', 'Suspender el vasopresor y reevaluar volumen únicamente'], correct: 2, explanation: 'Ante dosis crecientes de noradrenalina (equivalente ≈0.3 mcg/kg/min), la SSC 2026 recomienda agregar vasopresina como segundo agente, en vez de seguir escalando la catecolamina.', dificultad: 'dificil' },
  { q: '¿Por qué la ketamina se prefiere frecuentemente para la inducción de pacientes hemodinámicamente inestables?', options: ['Libera catecolaminas endógenas', 'Bloquea por completo el simpático', 'No tiene efecto cardiovascular medible', 'Actúa como vasodilatador puro'], correct: 0, explanation: 'La ketamina estimula la liberación de catecolaminas endógenas (efecto simpaticomimético indirecto), lo que explica su relativa estabilidad hemodinámica comparada con otros inductores como el propofol.', dificultad: 'dificil' },
  { q: 'En un paciente con vía aérea difícil anticipada que requiere secuencia rápida, ¿qué ventaja específica ofrece el rocuronio sobre el vecuronio en este escenario?', options: ['Tiene menor duración que el vecuronio', 'No requiere sedación previa alguna', 'Tiene un efecto analgésico agregado', 'Se revierte con sugammadex'], correct: 3, explanation: 'El rocuronio, a diferencia del vecuronio, puede revertirse de forma rápida y completa con sugammadex incluso en bloqueo profundo — una ventaja crítica si surge un escenario de "no se puede intubar, no se puede ventilar".', dificultad: 'dificil' },
  { q: '¿Por qué la adrenalina puede elevar el lactato sérico sin que esto indique necesariamente hipoperfusión tisular?', options: ['Indica una hipoperfusión grave real', 'Inhibe la eliminación renal de lactato', 'Por un efecto β2 propio del fármaco', 'El lactato no cambia con adrenalina'], correct: 2, explanation: 'La adrenalina tiene un efecto β2 directo que aumenta la producción de lactato (glucogenólisis/glucólisis aeróbica acelerada), lo cual complica interpretar el lactato como marcador puro de hipoperfusión en pacientes que la reciben.', dificultad: 'dificil' },
  { q: 'Paciente con infusión prolongada de propofol a dosis altas (>4-5 mg/kg/h por más de 48h) desarrolla acidosis metabólica inexplicada, rabdomiólisis y arritmia. ¿Qué se debe sospechar?', options: ['Síndrome de infusión de propofol', 'Una reacción alérgica simple', 'Una sobredosis de midazolam', 'Un efecto esperado, sin acción'], correct: 0, explanation: 'El síndrome de infusión de propofol es una complicación infrecuente pero potencialmente letal, asociada a dosis altas y uso prolongado, que se manifiesta con acidosis metabólica, rabdomiólisis, arritmias e insuficiencia cardiaca — requiere suspender el fármaco de inmediato.', dificultad: 'dificil' },
  { q: 'Según las guías PADIS 2018, ¿por qué se prefiere dexmedetomidina o propofol sobre midazolam para la sedación de rutina en ventilación mecánica?', options: ['El midazolam resulta bastante más caro', 'Las benzodiacepinas dan más delirium', 'El midazolam no tiene efecto sedante', 'No hay una preferencia establecida'], correct: 1, explanation: 'PADIS 2018 recomienda estrategias de sedación no benzodiacepínica (propofol o dexmedetomidina) sobre benzodiacepinas para sedación de rutina, dada la asociación de estas últimas con mayor delirium y ventilación mecánica prolongada.', dificultad: 'dificil' },
  { q: '¿Cuál es la estrategia recomendada antes de escalar la sedación en un paciente crítico que se muestra agitado?', options: ['Subir la dosis de sedante sin evaluar', 'Iniciar bloqueo neuromuscular de inmediato', 'Suspender toda la medicación y esperar', 'Evaluar y tratar el dolor primero'], correct: 3, explanation: 'La estrategia "analgesia primero" (analgesia-first) reconoce que el dolor no tratado es una causa frecuente de agitación aparente; tratarlo puede reducir la necesidad de sedación adicional.', dificultad: 'dificil' },
  { q: '¿Qué se espera con el uso de vecuronio en un paciente con falla renal significativa?', options: ['Se prolonga el bloqueo neuromuscular', 'No cambia en nada la duración del efecto', 'Revierte de forma más rápida de lo normal', 'Hay que aumentar la dosis, no bajarla'], correct: 0, explanation: 'El vecuronio tiene eliminación renal parcial además de biliar; en insuficiencia renal (o hepática) la duración de su efecto se prolonga significativamente.', dificultad: 'dificil' },
  { q: '¿Cuál de los siguientes hallazgos NO sería consistente con el efecto farmacológico esperado de la vasopresina?', options: ['Vasoconstricción sistémica marcada', 'Hiponatremia por retener agua libre', 'Aumento marcado de la frecuencia', 'Isquemia digital periférica'], correct: 2, explanation: 'La vasopresina actúa sobre receptores V1 (vasoconstricción) y V2 (antidiuresis), sin efecto cronotrópico ni inotrópico directo — un aumento marcado y directo de la FC no es un efecto farmacológico esperado de este fármaco.', dificultad: 'dificil' },
  { q: '¿Cuál es la base fisiopatológica por la que la vasopresina puede ser útil cuando hay hiporrespuesta a catecolaminas en choque prolongado?', options: ['Potencia directamente los receptores α1', 'Inhibe el metabolismo de la noradrenalina', 'No existe base fisiopatológica para ello', 'Actúa por receptores V1, no adrenérgicos'], correct: 3, explanation: 'En choque prolongado, los receptores adrenérgicos pueden regularse a la baja (down-regulation), reduciendo la respuesta a catecolaminas; la vasopresina actúa por una vía completamente distinta (receptores V1), por lo que mantiene su efecto vasoconstrictor.', dificultad: 'dificil' },
  { q: '¿Cuál es la dosis de adrenalina intramuscular recomendada en anafilaxia?', options: ['1 mg IV en bolo directo, sin diluir', '0.3-0.5 mg IM cada 5-15 minutos', '1 mcg/kg/min en infusión continua', 'No se recomienda la adrenalina aquí'], correct: 1, explanation: 'En anafilaxia, la adrenalina se administra por vía intramuscular a dosis de 0.3-0.5 mg (concentración 1 mg/mL), repitiendo cada 5-15 min según respuesta — a diferencia de la dosis IV usada en paro cardiaco o en infusión para choque.', dificultad: 'intermedio' },
  { q: 'A dosis intermedias (3-10 mcg/kg/min), ¿qué efecto predomina con la dopamina?', options: ['Efecto dopaminérgico puro, sin más', 'Efecto α1 puro, solo vasoconstrictor', 'Un bloqueo muscarínico central', 'Efecto β1 predominante'], correct: 3, explanation: 'La dopamina tiene efecto dosis-dependiente: a dosis intermedias predomina el efecto β1 (inotropismo/cronotropismo); a dosis altas (>10 mcg/kg/min) predomina el efecto α1 (vasoconstricción).', dificultad: 'intermedio' },
  { q: 'Según la SSC 2026, ¿se debe retrasar el inicio de la noradrenalina en espera de un acceso venoso central?', options: ['No; puede iniciarse por vía periférica', 'Sí, hay que esperar el acceso central', 'Solo puede darse por vía intramuscular', 'Requiere obligatoriamente vía intraósea'], correct: 0, explanation: 'La SSC 2026 respalda iniciar noradrenalina por vía periférica de forma transitoria cuando no hay acceso central inmediato, con vigilancia estrecha del sitio de infusión, para no retrasar el tratamiento.', dificultad: 'intermedio' },
  { q: '¿Cómo se trata la extravasación de noradrenalina en el sitio de infusión periférica?', options: ['Aplicando únicamente calor local', 'No requiere un tratamiento específico', 'Con fentolamina local', 'Con más noradrenalina en el mismo sitio'], correct: 2, explanation: 'La extravasación de noradrenalina (y otros vasopresores) se trata con infiltración local de fentolamina, un antagonista α que revierte la vasoconstricción local y previene la necrosis tisular.', dificultad: 'intermedio' },
  { q: '¿Cuándo se agrega dobutamina al tratamiento de un paciente en choque séptico?', options: ['En lugar de la noradrenalina, de inicio', 'Si persiste hipoperfusión con PAM en meta', 'Sustituye a la noradrenalina en hipotensión', 'Solo en pacientes fuera de terapia intensiva'], correct: 1, explanation: 'La dobutamina es un inotrópico que se AGREGA a un vasopresor ya iniciado, no lo reemplaza; se indica cuando persiste hipoperfusión por disfunción cardiaca pese a volumen adecuado y PAM en objetivo.', dificultad: 'intermedio' },
  { q: '¿Cuál es la complicación más temida de la vasopresina que obliga a vigilancia estrecha de la perfusión periférica?', options: ['Isquemia digital y mesentérica', 'Un broncoespasmo grave y súbito', 'Una hipoglucemia grave sostenida', 'Convulsiones tonicoclónicas'], correct: 0, explanation: 'La vasopresina puede causar isquemia digital y, más grave aún, isquemia mesentérica por vasoconstricción excesiva; se debe vigilar estrechamente la perfusión periférica durante su uso.', dificultad: 'intermedio' },
  { q: '¿Por qué el midazolam puede acumularse de forma marcada en pacientes con insuficiencia renal?', options: ['Se elimina solo por la vía biliar', 'Su metabolito activo se acumula', 'La falla renal acelera su metabolismo', 'El midazolam no tiene metabolitos activos'], correct: 1, explanation: 'El midazolam genera un metabolito activo (alfa-hidroxi-midazolam) que se acumula en insuficiencia renal, prolongando considerablemente el efecto sedante más allá de lo esperado por la vida media del fármaco original.', dificultad: 'intermedio' },
  { q: '¿En qué pacientes debe usarse el propofol con precaución por el contenido de su emulsión lipídica?', options: ['Con alergia a la penicilina', 'Con intolerancia a la lactosa', 'No hay precaución alguna por alergias', 'Alergia al huevo o a la soya'], correct: 3, explanation: 'La emulsión lipídica del propofol contiene lecitina de huevo y aceite de soya, por lo que debe usarse con precaución en pacientes con alergia documentada a estos componentes.', dificultad: 'intermedio' },
  { q: '¿Por qué se evita el bolo de carga de dexmedetomidina en el paciente crítico inestable?', options: ['No aporta un efecto adicional al paciente', 'Acelera el metabolismo hepático del fármaco', 'Aumenta hipotensión y bradicardia', 'Interfiere con la ventilación mecánica'], correct: 2, explanation: 'El bolo de carga de dexmedetomidina se asocia a mayor riesgo de hipotensión y bradicardia, por lo que en el paciente crítico se prefiere iniciar la infusión sin bolo de carga de rutina.', dificultad: 'intermedio' },
  { q: '¿Por qué la ketamina puede ser especialmente útil en un paciente con broncoespasmo activo (asma/EPOC) que requiere sedación?', options: ['Bloquea los receptores beta-adrenérgicos', 'Es broncodilatadora por sí misma', 'Suprime del todo el reflejo tusígeno', 'No tiene efecto sobre la vía aérea'], correct: 1, explanation: 'La ketamina tiene un efecto broncodilatador propio y preserva el impulso respiratorio, lo que la hace especialmente útil en pacientes con broncoespasmo activo que requieren sedación o inducción.', dificultad: 'intermedio' },
  { q: '¿Por qué la duración del efecto del fentanilo se prolonga considerablemente con infusiones continuas prolongadas, a diferencia de una dosis única?', options: ['Se acumula en el tejido graso', 'Cambia su mecanismo con el tiempo', 'Se une de forma irreversible al mu', 'Su duración no cambia con la infusión'], correct: 0, explanation: 'La alta liposolubilidad del fentanilo permite su acumulación en tejido graso con infusiones prolongadas, generando un "efecto contextual prolongado" en el que la duración clínica tras suspenderlo es mucho mayor que con una dosis única.', dificultad: 'intermedio' },
  { q: '¿Qué factor aumenta particularmente el riesgo de miopatía/polineuropatía del paciente crítico en quienes reciben bloqueo neuromuscular prolongado?', options: ['El uso concomitante de antibióticos betalactámicos', 'La sedación con dexmedetomidina', 'El uso concomitante de corticoides', 'El uso de escalas de dolor validadas'], correct: 2, explanation: 'El uso concomitante de corticoides junto con bloqueo neuromuscular prolongado (>24-48h) aumenta particularmente el riesgo de miopatía/polineuropatía del paciente crítico.', dificultad: 'intermedio' },
  { q: '¿Cuál es la diferencia principal en la dosis de rocuronio para intubación de secuencia rápida frente a la intubación estándar no urgente?', options: ['Es exactamente la misma dosis en ambos', 'La estándar requiere una dosis mayor', 'El rocuronio no se usa en secuencia rápida', 'Rápida 1.2 mg/kg; estándar 0.6-1.0'], correct: 3, explanation: 'Para secuencia rápida se usa la dosis alta de 1.2 mg/kg, que logra un inicio de acción ultrarrápido (~45-60 s); para intubación no urgente basta la dosis estándar de 0.6-1.0 mg/kg, con inicio de acción algo más lento.', dificultad: 'intermedio' },
  { q: 'Paciente con anafilaxia grave (angioedema, broncoespasmo, hipotensión) tras picadura de abeja. ¿Cuál es la vía y dosis correcta de adrenalina en este momento?', options: ['1 mg IV en bolo directo, igual que en paro cardiaco', 'Iniciar directamente una infusión IV sin dosis IM previa', '0.3-0.5 mg IM, pudiendo repetirse cada 5-15 min según respuesta', 'Diferir la adrenalina hasta confirmar el alérgeno causal'], correct: 2, explanation: 'En anafilaxia la primera línea es adrenalina IM 0.3-0.5 mg (1 mg/mL), repetible cada 5-15 min; el bolo IV de 1 mg está reservado para el paro cardiaco, no para la anafilaxia inicial.', dificultad: 'dificil' },
  { q: 'Paciente con vía aérea anticipadamente difícil recibe rocuronio 1.2 mg/kg para secuencia rápida y la intubación resulta fallida con imposibilidad de ventilar. ¿Qué opción permite revertir el bloqueo neuromuscular de forma rápida y completa en este escenario crítico?', options: ['Esperar la resolución espontánea del bloqueo, que tardará minutos', 'Sugammadex, que encapsula la molécula de rocuronio incluso en bloqueo profundo', 'Neostigmina en dosis altas, de efecto inmediato en cualquier profundidad de bloqueo', 'No existe forma de revertir el rocuronio'], correct: 1, explanation: 'El sugammadex encapsula específicamente la molécula de rocuronio y puede revertir incluso el bloqueo profundo de forma rápida y completa, siendo la opción de elección en un escenario de "no se puede intubar, no se puede ventilar".', dificultad: 'dificil' },
  { q: 'Paciente con insuficiencia renal crónica recibe midazolam en infusión continua por varios días y presenta sedación excesiva y prolongada, mucho más allá de lo esperado al suspenderlo. ¿Cuál es la explicación más probable?', options: ['No debería prolongarse en falla renal', 'Es un efecto placebo, sin base real', 'Una interacción con la vasopresina', 'Se acumula el metabolito activo'], correct: 3, explanation: 'El metabolito activo del midazolam se acumula en la insuficiencia renal, prolongando su efecto sedante de forma marcada; en estos pacientes se prefieren agentes con eliminación menos dependiente de la función renal (propofol, dexmedetomidina).', dificultad: 'dificil' },
  { q: 'Paciente con traumatismo craneoencefálico e hipertensión intracraneal requiere sedación para un procedimiento con inestabilidad hemodinámica concomitante. Tradicionalmente se evitaba la ketamina en este contexto. ¿Cómo se interpreta esto según la evidencia reciente?', options: ['Precaución, no contraindicación absoluta', 'Está contraindicada en cualquier grado', 'Baja la presión intracraneal sin riesgo', 'Debe sustituirse por succinilcolina'], correct: 0, explanation: 'La evidencia más reciente cuestiona el dogma clásico de que la ketamina eleva peligrosamente la presión intracraneal, por lo que actualmente se recomienda usarla con precaución (no exclusión absoluta), sobre todo cuando su estabilidad hemodinámica relativa es especialmente valiosa.', dificultad: 'dificil' },
  { q: 'Paciente en UCI recibe bloqueo neuromuscular continuo con vecuronio durante 5 días junto con corticoides sistémicos por SDRA grave. Al suspender ambos fármacos, persiste debilidad muscular marcada. ¿Qué se debe sospechar?', options: ['Efecto residual que cede en unos minutos', 'Miopatía del paciente crítico', 'Un síndrome de infusión de propofol', 'Efecto tóxico de la dexmedetomidina'], correct: 1, explanation: 'La combinación de bloqueo neuromuscular prolongado (días) y corticoides sistémicos es un factor de riesgo bien reconocido para miopatía/polineuropatía del paciente crítico, que puede manifestarse como debilidad persistente tras suspender ambos fármacos.', dificultad: 'dificil' }
];

export const flashcards = [
  { front: 'Vasopresor de primera línea en choque séptico', back: 'Norepinefrina (noradrenalina) — agonista α1 predominante.' },
  { front: 'Fármaco de elección en paro cardiaco', back: 'Adrenalina 1 mg IV/IO cada 3-5 minutos, en todos los ritmos.' },
  { front: 'Dosis de adrenalina en anafilaxia', back: '0.3-0.5 mg IM (1 mg/mL), repetible cada 5-15 min — distinta de la dosis IV de paro cardiaco.' },
  { front: '¿Por qué ya no se usa la "dosis renal" de dopamina?', back: 'No tiene respaldo en la evidencia actual para reducir lesión renal ni mortalidad.' },
  { front: 'Efecto de la dopamina según la dosis', back: 'Bajas: dopaminérgico (sin beneficio probado). Intermedias: β1. Altas (>10 mcg/kg/min): α1.' },
  { front: 'Dosis de dobutamina', back: '2-20 mcg/kg/min IV; inotrópico, se agrega a un vasopresor si hay hipotensión concomitante.' },
  { front: '¿Cómo se dosifica la vasopresina?', back: 'Dosis FIJA 0.01-0.07 U/min — no se ajusta por peso ni se titula al alza.' },
  { front: 'Complicación más temida de la vasopresina', back: 'Isquemia digital y mesentérica por vasoconstricción excesiva.' },
  { front: 'Manejo de la extravasación de noradrenalina', back: 'Infiltración local de fentolamina (antagonista α).' },
  { front: '¿Se puede iniciar noradrenalina por vía periférica?', back: 'Sí, de forma transitoria sin retrasar su inicio, con vigilancia estrecha del sitio (SSC 2026).' },
  { front: 'Antídoto de benzodiacepinas', back: 'Flumazenilo (antagonista competitivo del receptor benzodiacepínico); precaución por riesgo de convulsiones en uso crónico.' },
  { front: 'Antídoto de opioides', back: 'Naloxona (antagonista opioide competitivo); duración más corta que muchos opioides — vigilar recurrencia.' },
  { front: '¿Por qué se acumula el midazolam en falla renal?', back: 'Su metabolito activo (alfa-hidroxi-midazolam) depende de excreción renal.' },
  { front: 'Sedante que no causa depresión respiratoria significativa', back: 'Dexmedetomidina (agonista α2) — permite sedación "cooperativa".' },
  { front: '¿Por qué se evita el bolo de carga de dexmedetomidina en UCI?', back: 'Aumenta el riesgo de hipotensión y bradicardia.' },
  { front: 'Sedante de elección en ventilación mecánica según PADIS 2018', back: 'Propofol o dexmedetomidina, preferidos sobre benzodiacepinas (menos delirium, menor duración de VM).' },
  { front: 'Precaución específica del propofol por su emulsión lipídica', back: 'Alergia al huevo o a la soya (contiene lecitina de huevo y aceite de soya).' },
  { front: 'Complicación grave de infusión prolongada de propofol a dosis altas', back: 'Síndrome de infusión de propofol: acidosis metabólica, rabdomiólisis, arritmias, insuficiencia cardiaca.' },
  { front: '¿Cuándo es de elección el midazolam pese a preferirse otros sedantes?', back: 'Estado epiléptico y abstinencia alcohólica/benzodiacepínica.' },
  { front: 'Inductor preferido en inestabilidad hemodinámica o broncoespasmo', back: 'Ketamina — preserva la estabilidad hemodinámica y el impulso respiratorio, con efecto broncodilatador propio.' },
  { front: 'Ketamina e hipertensión intracraneal', back: 'La evidencia reciente cuestiona el dogma clásico de contraindicación absoluta; usar con precaución, no exclusión total.' },
  { front: 'Analgésico opioide de elección en el paciente crítico', back: 'Fentanilo — inicio rápido, perfil hemodinámico estable.' },
  { front: '¿Por qué se prolonga el efecto del fentanilo con infusión continua prolongada?', back: 'Acumulación en tejido graso por alta liposolubilidad ("efecto contextual prolongado").' },
  { front: 'Estrategia recomendada antes de escalar sedación', back: '"Analgesia primero": tratar el dolor puede reducir la necesidad de sedación adicional.' },
  { front: 'Escala usada para evaluar dolor en el paciente no comunicativo', back: 'CPOT (Critical-Care Pain Observation Tool).' },
  { front: 'Herramienta para monitorizar el bloqueo neuromuscular', back: 'Tren de cuatro (TOF) con estimulador de nervio periférico.' },
  { front: 'Contraindicaciones clásicas de succinilcolina que llevan a preferir rocuronio', back: 'Hiperkalemia, quemados >24-72h, lesión medular, enfermedad neuromuscular.' },
  { front: 'Ventaja del rocuronio sobre vecuronio en vía aérea difícil', back: 'Reversión rápida y completa con sugammadex, incluso en bloqueo profundo.' },
  { front: 'Dosis de rocuronio en secuencia rápida vs. intubación estándar', back: '1.2 mg/kg (ultrarrápido, ~45-60 s) en secuencia rápida; 0.6-1.0 mg/kg en intubación no urgente.' },
  { front: '¿Por qué la adrenalina puede elevar el lactato sin hipoperfusión real?', back: 'Efecto β2 propio del fármaco sobre la producción de lactato — interpretar con cautela.' },
  { front: 'Factor que más aumenta el riesgo de miopatía/polineuropatía del paciente crítico', back: 'Uso concomitante de corticoides junto con bloqueo neuromuscular prolongado.' },
  { front: 'Escala usada para titular sedación', back: 'RASS (Richmond Agitation-Sedation Scale).' }
];

export const caseSteps = [
  { vignette: 'Paciente de 62 años con choque séptico de foco urinario. Ya recibió 30 mL/kg de cristaloides y se inicia noradrenalina, que se titula hasta 0.3 mcg/kg/min sin alcanzar la PAM objetivo de 65 mmHg. ¿Cuál es el siguiente paso más apropiado?', options: ['Duplicar la dosis de noradrenalina indefinidamente', 'Cambiar a dopamina', 'Agregar vasopresina a dosis fija (0.03 U/min)', 'Suspender vasopresores y repetir bolo de cristaloides únicamente'], correct: 2, explanation: 'Ante dosis crecientes de noradrenalina sin alcanzar la PAM objetivo, se agrega vasopresina como segundo agente a dosis fija, en vez de seguir escalando la catecolamina indefinidamente.' },
  { vignette: 'El paciente requiere intubación por deterioro del estado de conciencia y trabajo respiratorio. Está hipotenso pese a los vasopresores. ¿Qué inductor es más apropiado para la secuencia rápida?', options: ['Ketamina', 'Propofol a dosis estándar', 'Tiopental', 'Ninguno — evitar la sedación por completo'], correct: 0, explanation: 'En un paciente hemodinámicamente inestable, la ketamina es preferida por su efecto simpaticomimético relativo, que ayuda a preservar la estabilidad hemodinámica durante la inducción, a diferencia del propofol que puede profundizar la hipotensión.' },
  { vignette: 'Tras la intubación, se requiere bloqueo neuromuscular breve para facilitar la laringoscopia y no hay contraindicaciones para succinilcolina. Sin embargo, el servicio decide usar un no despolarizante por disponibilidad. ¿Cuál es la opción más adecuada para lograr un inicio de acción similarmente rápido?', options: ['Vecuronio a dosis estándar', 'Cisatracurio a dosis baja', 'No usar ningún bloqueador', 'Rocuronio 1.2 mg/kg'], correct: 3, explanation: 'El rocuronio a dosis de 1.2 mg/kg logra un inicio de acción ultrarrápido (~45-60 s), aproximándose al de la succinilcolina, con la ventaja adicional de ser reversible con sugammadex.' },
  { vignette: 'Ya en la UCI, el paciente está ventilado mecánicamente. El equipo debe elegir la estrategia de sedoanalgesia inicial. ¿Cuál es el enfoque recomendado según las guías actuales?', options: ['Sedación profunda con midazolam en infusión desde el inicio', 'Analgesia con fentanilo primero, evaluando dolor con escala validada, y sedación ligera después', 'Bloqueo neuromuscular continuo de rutina sin sedación', 'No administrar ningún analgésico ni sedante'], correct: 1, explanation: 'La estrategia recomendada es "analgesia primero": tratar el dolor con un opioide como fentanilo y evaluarlo con una escala validada (CPOT), agregando sedación ligera (propofol o dexmedetomidina) solo si es necesaria — evitando benzodiacepinas de rutina (PADIS 2018).' },
  { vignette: 'Al tercer día, el paciente sigue con propofol en infusión a dosis relativamente altas. El laboratorio muestra acidosis metabólica de nueva aparición y elevación de creatina-cinasa. ¿Qué se debe sospechar y qué acción tomar?', options: ['Sospechar síndrome de infusión de propofol; suspender el fármaco de inmediato', 'Es un hallazgo esperado sin relevancia clínica; continuar igual', 'Aumentar la dosis de propofol para profundizar la sedación', 'Iniciar antibióticos empíricos sin más estudio'], correct: 0, explanation: 'La combinación de acidosis metabólica inexplicada y elevación de CK en un paciente con infusión prolongada de propofol a dosis altas obliga a sospechar el síndrome de infusión de propofol, que requiere suspensión inmediata del fármaco.' },
  { vignette: 'Se suspende el propofol y se cambia a dexmedetomidina. El paciente mejora, ya sin vasopresores y con parámetros respiratorios adecuados. ¿Qué práctica diaria facilita valorar si ya está listo para el destete ventilatorio?', options: ['Mantener la sedación profunda continua sin interrupciones para evitar el estrés del despertar', 'Reiniciar bloqueo neuromuscular de rutina antes de cualquier prueba de despertar', 'Interrupción diaria de la sedación (o reducción a la mínima efectiva) para reevaluar el destete', 'Suspender toda monitorización una vez que el paciente ya no requiere vasopresores'], correct: 2, explanation: 'La interrupción diaria de la sedación (o su titulación a la mínima dosis efectiva según RASS) es una práctica recomendada por PADIS 2018 que permite reevaluar el nivel de conciencia y la disposición para una prueba de ventilación espontánea, acortando el tiempo de ventilación mecánica.' }
];

export const caseSummary = 'Este caso integró la escalada de vasopresores en choque séptico (noradrenalina → vasopresina), la elección de ketamina para inducción en inestabilidad hemodinámica, rocuronio con reversión disponible en secuencia rápida, la estrategia "analgesia primero" para sedoanalgesia, el reconocimiento del síndrome de infusión de propofol y la interrupción diaria de sedación como práctica hacia el destete ventilatorio. Repasa las monografías de cada fármaco en la sección Fármacos si alguna decisión no quedó clara.';

export default { quiz, flashcards, caseSteps, caseSummary };
