// topics/exploracion-osteoarticular/study.js — Autoevaluación de Exploración Osteoarticular y de
// Extremidades. Mismo patrón que historia-clinica/study.js y los demás temas de Semiología: banco
// único, preguntas sueltas + preguntas en cascada sobre una viñeta (retroalimentación consolidada
// al final, sin revelar correcto/incorrecto paso a paso).

export const quiz = [
  { q: 'Ante una monoartritis AGUDA, ¿qué 2 causas se deben descartar primero?', options: ['Osteoartritis y fibromialgia', 'Artritis séptica y artropatía por cristales (gota, pseudogota)', 'Artritis reumatoide y lupus', 'Espondiloartropatía y artritis psoriásica'], correct: 1, explanation: 'La monoartritis aguda es una urgencia diagnóstica: la artritis séptica puede destruir la articulación rápidamente si no se trata, y las cristalopatías (gota, pseudogota) son causas frecuentes que requieren confirmación por artrocentesis.', dificultad: 'facil' },
  { q: '¿Qué diferencia hay entre evaluar el rango de movimiento activo y el pasivo?', options: ['No hay ninguna diferencia clínica', 'El activo lo realiza el paciente; el pasivo lo realiza el examinador, y ayuda a distinguir causas articulares de periarticulares o musculares', 'El pasivo solo se usa en niños', 'El activo evalúa la fuerza, no el rango'], correct: 1, explanation: 'Comparar el rango activo (limitado por dolor, debilidad o rigidez) con el pasivo (limitado solo por la articulación o tejidos periarticulares) ayuda a localizar el origen del problema.', dificultad: 'intermedio' },
  { q: '¿Qué distingue clínicamente a la sinovitis verdadera (articular) de un proceso periarticular (bursitis, tendinitis)?', options: ['La sinovitis nunca causa tumefacción', 'La sinovitis duele con el movimiento activo Y pasivo en todas direcciones; lo periarticular suele doler solo con el activo o con una dirección/maniobra específica', 'El proceso periarticular siempre es más doloroso', 'No hay ninguna diferencia clínica'], correct: 1, explanation: 'El dolor en todas las direcciones y con ambos tipos de movimiento sugiere compromiso articular verdadero; el dolor direccional o solo activo sugiere una estructura periarticular específica.', dificultad: 'intermedio' },
  { q: 'En la bursitis subacromial, ¿qué es el "arco doloroso"?', options: ['Dolor en todo el rango de movimiento del hombro', 'Dolor con la abducción activa entre 60-120°, con el rango pasivo relativamente indoloro', 'Dolor exclusivamente con el movimiento pasivo', 'Un signo de artritis reumatoide del hombro'], correct: 1, explanation: 'El arco doloroso es característico de patología periarticular (bursitis/tendinopatía del manguito rotador): dolor en un rango específico de movimiento activo, con el pasivo relativamente respetado.', dificultad: 'intermedio' },
  { q: '¿Qué diferencia al choque rotuliano del signo de la oleada?', options: ['Son la misma maniobra con distinto nombre', 'El choque rotuliano detecta derrames moderados-grandes; la oleada detecta derrames pequeños', 'La oleada solo se usa en el hombro', 'El choque rotuliano es más sensible para derrames pequeños'], correct: 1, explanation: 'El choque rotuliano requiere que la rótula "flote" sobre suficiente líquido; con poco volumen, el signo de la oleada (que moviliza visualmente el líquido) es más sensible.', dificultad: 'facil' },
  { q: '¿Por qué el signo de la oleada detecta derrames que el choque rotuliano puede pasar por alto?', options: ['Porque usa instrumentos especiales', 'Porque con poco líquido la rótula no llega a flotar lo suficiente para el ballottement clásico, mientras que "ordeñar" el líquido de un lado a otro es visible incluso con volúmenes pequeños', 'Porque el choque rotuliano solo funciona en rodillas grandes', 'No hay ninguna diferencia real de sensibilidad'], correct: 1, explanation: 'El mecanismo del choque rotuliano depende de un volumen suficiente para que la rótula flote; el signo de la oleada no depende de ese umbral, por eso detecta derrames más sutiles.', dificultad: 'dificil' },
  { q: 'Un patrón poliarticular SIMÉTRICO es característico de:', options: ['Gota aguda', 'Artritis reumatoide, lupus eritematoso sistémico', 'Artritis séptica', 'Espondilitis anquilosante exclusivamente'], correct: 1, explanation: 'La artritis reumatoide y el lupus son los ejemplos clásicos de compromiso poliarticular simétrico.', dificultad: 'facil' },
  { q: '¿Qué caracteriza a un patrón de afectación articular "migratorio"?', options: ['Todas las articulaciones se afectan simultáneamente y permanecen inflamadas', 'Una articulación mejora mientras otra se afecta, sin sumarse de forma permanente', 'Solo afecta articulaciones axiales', 'Es exclusivo de la artritis reumatoide'], correct: 1, explanation: 'El patrón migratorio (fiebre reumática, artritis gonocócica diseminada, algunas artritis virales) se caracteriza porque cada articulación se resuelve antes de que la siguiente se inflame.', dificultad: 'intermedio' },
  { q: '¿Cómo se diferencia un patrón "aditivo" de uno "migratorio"?', options: ['Son sinónimos', 'El aditivo suma articulaciones sin resolver las previas (ej. artritis reumatoide); el migratorio resuelve una articulación antes de afectar la siguiente (ej. fiebre reumática)', 'El migratorio siempre es poliarticular simétrico', 'El aditivo solo ocurre en niños'], correct: 1, explanation: 'Esta distinción de patrón temporal es una pista diagnóstica específica, independiente del número de articulaciones afectadas en un momento dado.', dificultad: 'dificil' },
  { q: '¿Qué estructura evalúa la maniobra de Lachman?', options: ['El menisco medial', 'El ligamento cruzado anterior', 'El nervio mediano', 'Los tendones del primer compartimento extensor de la muñeca'], correct: 1, explanation: 'Lachman (tracción tibial anterior con la rodilla en 20-30° de flexión) evalúa la integridad del ligamento cruzado anterior.', dificultad: 'facil' },
  { q: '¿Por qué la maniobra de Lachman es más sensible que el cajón anterior clásico (a 90° de flexión) para detectar una lesión del LCA?', options: ['Porque se hace más rápido', 'Porque a 20-30° de flexión los isquiotibiales interfieren menos con el desplazamiento tibial que a 90°', 'Porque no requiere ninguna fuerza del examinador', 'No hay diferencia real de sensibilidad entre ambas'], correct: 1, explanation: 'A mayor flexión (90°), la tensión de los isquiotibiales puede enmascarar el desplazamiento tibial anterior; a 20-30° esa interferencia es menor, aumentando la sensibilidad de Lachman.', dificultad: 'dificil' },
  { q: 'En la maniobra de McMurray, ¿qué rotación tibial localiza una lesión del menisco medial?', options: ['Rotación interna', 'Rotación externa', 'Ninguna rotación, solo la flexión', 'La rotación no tiene relación con la localización'], correct: 1, explanation: 'La rotación externa durante la maniobra de McMurray estresa y localiza el menisco medial; la rotación interna localiza el lateral.', dificultad: 'intermedio' },
  { q: 'Los signos de Tinel y Phalen, positivos con parestesias en los dedos, sugieren:', options: ['Lesión del ligamento cruzado anterior', 'Síndrome del túnel carpiano (compresión del nervio mediano)', 'Tenosinovitis de De Quervain', 'Lesión meniscal'], correct: 1, explanation: 'Ambas maniobras reproducen parestesias en el territorio del nervio mediano al comprimirlo dentro del túnel del carpo.', dificultad: 'facil' },
  { q: 'La maniobra de Finkelstein (desviación cubital con el pulgar dentro del puño) evalúa:', options: ['El nervio mediano', 'Los tendones abductor largo y extensor corto del pulgar (tenosinovitis de De Quervain)', 'El ligamento cruzado anterior', 'El menisco lateral'], correct: 1, explanation: 'El dolor en la tabaquera anatómica/estiloides radial con esta maniobra es característico de la tenosinovitis de De Quervain.', dificultad: 'facil' },
  { q: '¿Qué diferencia mecánica hay entre el edema CON fóvea y el edema SIN fóvea?', options: ['No hay diferencia mecánica real', 'Con fóvea: líquido intersticial libre que se desplaza fácilmente (presión hidrostática↑ u oncótica↓). Sin fóvea: proteínas de alto peso molecular que fijan el líquido (linfedema, mixedema)', 'El edema sin fóvea siempre es más grave', 'El edema con fóvea es exclusivo de causas cardiacas'], correct: 1, explanation: 'La fóvea depende de si el líquido intersticial es libre de desplazarse (con fóvea) o está fijado por proteínas de alto peso molecular que no drenan sin sistema linfático funcional (sin fóvea).', dificultad: 'intermedio' },
  { q: '¿Qué es el signo de Stemmer y qué detecta específicamente?', options: ['Dolor a la dorsiflexión del pie; TVP', 'Imposibilidad de pellizcar un pliegue de piel en la base del segundo dedo del pie; específico de linfedema', 'Palidez a la elevación de la pierna; isquemia arterial', 'Hiperpigmentación ocre; insuficiencia venosa'], correct: 1, explanation: 'El signo de Stemmer es específico de linfedema y ayuda a distinguirlo de otras causas de edema con o sin fóvea.', dificultad: 'dificil' },
  { q: 'Un edema UNILATERAL de inicio agudo en una pierna sugiere principalmente:', options: ['Insuficiencia cardiaca', 'Una causa local: trombosis venosa profunda, obstrucción venosa/linfática focal, celulitis', 'Hipoalbuminemia sistémica', 'Hipotiroidismo severo'], correct: 1, explanation: 'A diferencia del edema bilateral (que sugiere causa sistémica), el edema unilateral orienta a un proceso local en esa extremidad.', dificultad: 'facil' },
  { q: '¿Qué tan sensible y específico es el signo de Homans para el diagnóstico de trombosis venosa profunda?', options: ['Muy sensible y específico, suficiente por sí solo', 'Baja sensibilidad y especificidad — su ausencia no descarta TVP', '100% sensible pero poco específico', 'No se ha estudiado nunca formalmente'], correct: 1, explanation: 'Al igual que Kernig/Brudzinski en meningitis, el signo de Homans tiene un rendimiento diagnóstico bajo, y su ausencia no descarta trombosis venosa profunda.', dificultad: 'dificil' },
  { q: '¿Por qué el signo de Homans ha caído en desuso en la práctica clínica actual?', options: ['Porque es doloroso para el examinador', 'Por su baja sensibilidad/especificidad y el riesgo teórico de desprender un trombo con la maniobra', 'Porque requiere equipo especializado', 'Porque solo se puede hacer en el hospital'], correct: 1, explanation: 'Además de su pobre rendimiento diagnóstico, existe la preocupación teórica de que la dorsiflexión forzada del pie podría desprender un trombo ya formado.', dificultad: 'intermedio' },
  { q: '¿Para qué sirve la escala de Wells en la sospecha de trombosis venosa profunda?', options: ['Para reemplazar por completo la necesidad de cualquier estudio de imagen', 'Para estratificar la probabilidad pretest y guiar la necesidad de dímero D o ecografía Doppler, en vez de depender de un signo físico aislado', 'Para medir directamente el tamaño del trombo', 'Solo se usa en pacientes hospitalizados'], correct: 1, explanation: 'La escala de Wells integra varios criterios clínicos ponderados para estimar la probabilidad de TVP antes de solicitar estudios complementarios.', dificultad: 'intermedio' },
  { q: '¿Cuál es el mecanismo fisiopatológico central de la insuficiencia venosa crónica?', options: ['Vasoespasmo arterial recurrente', 'Incompetencia de las válvulas venosas que permite el reflujo retrógrado, elevando crónicamente la presión venosa ambulatoria', 'Obstrucción linfática primaria', 'Vasculitis de pequeño vaso'], correct: 1, explanation: 'La incompetencia valvular (primaria o secundaria a TVP previa) permite que la sangre refluya en sentido retrógrado, elevando la presión venosa de forma crónica.', dificultad: 'intermedio' },
  { q: '¿Cuál es la progresión típica de signos en la insuficiencia venosa crónica?', options: ['Úlcera → varices → edema → dermatitis por estasis', 'Varices → edema vespertino → dermatitis por estasis → lipodermatoesclerosis → úlcera venosa', 'Palidez → cianosis → gangrena', 'Parestesias → parálisis → necrosis'], correct: 1, explanation: 'La insuficiencia venosa crónica progresa de forma característica desde las varices iniciales hasta la úlcera venosa en etapas avanzadas.', dificultad: 'facil' },
  { q: '¿Dónde se localiza característicamente una úlcera venosa?', options: ['En la punta de los dedos', 'En la región maleolar medial ("gaiter area")', 'En el talón', 'En las cabezas metatarsianas'], correct: 1, explanation: 'La úlcera venosa típica se ubica en la zona maleolar medial, a diferencia de la úlcera arterial, que predomina en zonas distales/de presión.', dificultad: 'facil' },
  { q: '¿Cuál es el rango normal del índice tobillo-brazo (ITB)?', options: ['0.5-0.7', '1.0-1.4', '1.8-2.2', 'No existe un rango normal establecido'], correct: 1, explanation: 'Un ITB entre 1.0 y 1.4 se considera normal; ≤0.9 sugiere enfermedad arterial periférica.', dificultad: 'facil' },
  { q: 'Un ITB &gt;1.4, ¿qué significa y por qué es un hallazgo problemático?', options: ['Significa perfusión excelente sin ninguna duda', 'Sugiere arterias no compresibles por calcificación (diabetes de larga evolución, enfermedad renal terminal), lo que hace que el índice deje de ser confiable', 'Siempre indica un error de medición sin significado clínico', 'Es sinónimo de enfermedad arterial periférica severa'], correct: 1, explanation: 'Un ITB muy elevado no descarta enfermedad arterial periférica: puede reflejar arterias rígidas y no compresibles que enmascaran una isquemia significativa, requiriendo pruebas alternativas.', dificultad: 'dificil' },
  { q: '¿Cuáles son las 6 P de la isquemia arterial aguda?', options: ['Pulso, Presión, Piel, Perfusión, Pupila, Pálido', 'Pain, Pallor, Pulselessness, Paresthesia, Paralysis, Poiquilotermia', 'Pain, Pressure, Pulse, Pallor, Position, Prognosis', 'No existen 6 P estandarizadas'], correct: 1, explanation: 'Estos 6 hallazgos cardinales (dolor, palidez, ausencia de pulso, parestesias, parálisis, frialdad) definen clínicamente la isquemia arterial aguda.', dificultad: 'facil' },
  { q: '¿Por qué la parestesia se considera un signo TEMPRANO y la parálisis un signo TARDÍO en la isquemia arterial aguda?', options: ['Es al revés: la parálisis es temprana y la parestesia tardía', 'Las fibras nerviosas son muy sensibles a la isquemia y se afectan antes que el músculo; la parálisis refleja daño muscular ya establecido', 'No hay ninguna diferencia temporal real entre ambas', 'Ambas ocurren siempre simultáneamente'], correct: 1, explanation: 'El tejido nervioso tolera peor la isquemia que el músculo, por lo que los síntomas sensitivos preceden a los motores; la parálisis indica que el daño ya progresó al músculo.', dificultad: 'dificil' },
  { q: '¿Qué significa clínicamente que un paciente con isquemia aguda desarrolle PARÁLISIS de la extremidad?', options: ['Que el pronóstico es excelente y puede esperarse tratamiento electivo', 'Que hay daño tisular ya establecido y se requiere revascularización EMERGENTE', 'Que el cuadro es leve y se resolverá espontáneamente', 'Que se debe suspender cualquier intento de revascularización'], correct: 1, explanation: 'La parálisis marca la transición a isquemia con daño muscular avanzado, elevando la urgencia del tratamiento a emergente.', dificultad: 'intermedio' },
  { q: '¿En qué consiste el signo de Buerger y qué sugiere si es positivo?', options: ['Elevar la pierna 45-60° por 1 minuto (palidece) y luego dejarla colgar (rubor tardío intenso); sugiere enfermedad arterial periférica significativa', 'Percutir el trayecto venoso en busca de dolor; sugiere TVP', 'Comprimir la pantorrilla; sugiere edema linfático', 'Flexionar pasivamente el pie; sugiere TVP'], correct: 0, explanation: 'La palidez con la elevación (el lecho arterial insuficiente no puede mantener la perfusión contra gravedad) seguida de rubor tardío intenso al colgar la pierna (hiperemia reactiva) sugiere insuficiencia arterial significativa.', dificultad: 'intermedio' },
  { q: '¿Cómo se comporta el dolor de una úlcera ARTERIAL con la elevación de la pierna, a diferencia de una úlcera venosa?', options: ['Mejora igual que en la úlcera venosa', 'EMPEORA con la elevación (reduce aún más la perfusión) y mejora al dejar la pierna colgando', 'No se modifica con la posición en ningún caso', 'Solo empeora con el ejercicio, nunca con la posición'], correct: 1, explanation: 'La elevación reduce la presión de perfusión arterial ya comprometida, empeorando el dolor isquémico — el patrón opuesto al de la úlcera venosa, que mejora con la elevación.', dificultad: 'dificil' },
  { q: '¿Cómo se describen típicamente los bordes de una úlcera arterial en comparación con una venosa?', options: ['Ambas tienen bordes idénticos', 'Arterial: "en sacabocados", bien delimitados y profundos. Venosa: irregulares y poco profundos', 'Arterial: irregulares y superficiales. Venosa: en sacabocados y profundos', 'Ninguna de las dos tiene bordes definibles'], correct: 1, explanation: 'La úlcera arterial tiene bordes netos ("en sacabocados") y suele ser más profunda; la venosa tiene bordes irregulares y es más superficial.', dificultad: 'facil' },
  { q: '¿Por qué es importante medir el índice tobillo-brazo ANTES de indicar terapia de compresión para una úlcera de extremidad inferior?', options: ['No es necesario, la compresión siempre es segura', 'Porque aplicar compresión (tratamiento estándar de la úlcera venosa) en una extremidad con enfermedad arterial no reconocida puede empeorar significativamente la isquemia', 'Porque el ITB determina el color del vendaje a usar', 'Porque la compresión solo se usa en úlceras arteriales'], correct: 1, explanation: 'Confundir una úlcera arterial con una venosa y aplicar compresión puede comprometer aún más el flujo arterial ya reducido, por eso el ITB debe medirse antes de decidir el tratamiento.', dificultad: 'dificil' },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente masculino de 55 años con antecedente de hipertensión, presenta dolor e inflamación súbita de la primera articulación metatarsofalángica derecha de 12 horas de evolución, con eritema y calor intensos.',
    steps: [
      { q: '¿Cómo se clasifica este patrón de afectación articular por número de articulaciones y tiempo de evolución?', options: ['Poliartritis crónica', 'Monoartritis aguda', 'Oligoartritis migratoria', 'Poliartritis simétrica'], correct: 1 },
      { q: '¿Cuáles son las 2 causas que se deben descartar primero en este contexto?', options: ['Osteoartritis y fibromialgia', 'Artritis séptica y artropatía por cristales (gota)', 'Artritis reumatoide y lupus', 'Espondiloartropatía y psoriasis'], correct: 1 },
      { q: '¿Qué estudio permite diferenciar con mayor certeza entre gota y artritis séptica en este escenario?', options: ['Radiografía simple únicamente', 'Artrocentesis con análisis del líquido sinovial (cristales y cultivo)', 'Resonancia magnética urgente', 'Ninguno, el diagnóstico es siempre clínico'], correct: 1 }
    ],
    explanation: 'La monoartritis aguda, especialmente en la primera metatarsofalángica (localización clásica de la gota, "podagra"), obliga a descartar de forma prioritaria artritis séptica y artropatía por cristales, dado el riesgo de destrucción articular rápida si es séptica. La artrocentesis con análisis del líquido sinovial (cristales bajo luz polarizada y cultivo) es el estudio que permite diferenciarlas con mayor certeza.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente femenina de 68 años, con cáncer de mama activo en tratamiento, presenta edema unilateral de la pantorrilla izquierda de 3 días de evolución, con dolor localizado en el trayecto venoso profundo. El signo de Homans es negativo.',
    steps: [
      { q: '¿El signo de Homans negativo descarta el diagnóstico de trombosis venosa profunda?', options: ['Sí, si es negativo se descarta con seguridad', 'No, el signo de Homans tiene baja sensibilidad y su negatividad no descarta el diagnóstico', 'Solo lo descarta en pacientes con cáncer', 'El signo de Homans no se relaciona con TVP'], correct: 1 },
      { q: 'Dado el cáncer activo, el edema unilateral y el dolor en trayecto venoso, ¿qué herramienta ayuda a estimar la probabilidad pretest de TVP?', options: ['La escala de Glasgow', 'La escala de Wells', 'Los criterios ABCDE', 'El índice tobillo-brazo'], correct: 1 },
      { q: '¿Qué estudios se solicitarían típicamente según el resultado de esa estratificación de riesgo?', options: ['Ninguno, basta con la exploración física', 'Dímero D y/o ecografía Doppler venosa, según la probabilidad pretest', 'Radiografía simple de la pierna', 'Electrocardiograma únicamente'], correct: 1 }
    ],
    explanation: 'El cáncer activo, el edema unilateral y el dolor en el trayecto venoso son criterios de la escala de Wells que elevan la probabilidad pretest de TVP; la negatividad del signo de Homans (poco sensible) no descarta el diagnóstico. Según la probabilidad estimada, se solicita dímero D (si el riesgo es bajo-intermedio) o directamente ecografía Doppler venosa (si el riesgo es alto).'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente masculino de 70 años con fibrilación auricular no anticoagulada, presenta dolor súbito e intenso en la pierna izquierda, que está pálida y fría, sin pulsos distales palpables. Refiere hormigueo en el pie, pero conserva el movimiento activo de los dedos.',
    steps: [
      { q: '¿Qué hallazgos de las "6 P" de isquemia arterial aguda están presentes en este momento?', options: ['Solo dolor', 'Pain, Pallor, Pulselessness, Paresthesia, Poiquilotermia (5 de 6, sin Paralysis aún)', 'Las 6 P completas, incluida parálisis', 'Ninguna de las 6 P'], correct: 1 },
      { q: '¿Qué significa que el paciente aún conserve el movimiento activo de los dedos (sin parálisis)?', options: ['Que no hay isquemia real', 'Que el daño tisular, aunque presente, probablemente aún no alcanzó al músculo — una ventana donde la revascularización puede ser más efectiva', 'Que se puede posponer el tratamiento varios días', 'Que el diagnóstico es incorrecto'], correct: 1 },
      { q: '¿Cuál es la causa más probable de esta isquemia aguda dado el antecedente de fibrilación auricular no anticoagulada?', options: ['Trombosis venosa profunda', 'Embolismo arterial de origen cardiaco', 'Insuficiencia venosa crónica descompensada', 'Vasculitis de pequeño vaso'], correct: 1 },
    ],
    explanation: 'El paciente presenta 5 de las 6 P (dolor, palidez, ausencia de pulsos, parestesias, frialdad), pero AÚN NO parálisis — la ausencia de este signo tardío indica que el daño muscular todavía no está establecido, una ventana crítica donde la revascularización urgente tiene mejor pronóstico. La fibrilación auricular no anticoagulada es una fuente embólica clásica de isquemia arterial aguda de extremidades.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente femenina de 75 años, diabética, con una úlcera dolorosa en el talón derecho, de bordes bien delimitados y profundos, que empeora cuando eleva la pierna en la cama y mejora cuando la deja colgando al borde de la cama.',
    steps: [
      { q: 'Según la localización, el aspecto de los bordes y el comportamiento del dolor con la posición, ¿qué tipo de úlcera es más probable?', options: ['Úlcera venosa', 'Úlcera arterial', 'Úlcera por presión exclusivamente', 'Úlcera neuropática exclusivamente'], correct: 1 },
      { q: '¿Qué estudio de exploración física debe realizarse antes de considerar terapia de compresión?', options: ['Ninguno, la compresión es segura en todos los casos', 'Índice tobillo-brazo, para descartar enfermedad arterial significativa', 'Signo de Homans únicamente', 'Prueba de Romberg'], correct: 1 },
      { q: '¿Por qué sería riesgoso aplicar compresión sin haber descartado enfermedad arterial en esta paciente?', options: ['La compresión no tiene ningún riesgo en úlceras arteriales', 'Podría reducir aún más el flujo arterial ya comprometido, empeorando la isquemia', 'La compresión solo afecta el sistema linfático', 'No existe relación entre compresión e isquemia arterial'], correct: 1 }
    ],
    explanation: 'La localización distal, los bordes "en sacabocados" y el dolor que empeora con la elevación (y mejora al colgar la pierna, favoreciendo el flujo por gravedad) son característicos de una úlcera arterial, no venosa. Antes de aplicar el tratamiento estándar de compresión (reservado para úlceras venosas), debe medirse el índice tobillo-brazo, porque comprimir una extremidad con enfermedad arterial no reconocida puede empeorar significativamente la isquemia.'
  }
];

export const flashcards = [
  { front: 'Monoartritis aguda: qué descartar primero', back: 'Artritis séptica y artropatía por cristales (gota, pseudogota) — urgencia diagnóstica.' },
  { front: 'Articular vs. periarticular', back: 'Articular: duele con movimiento activo Y pasivo, todas direcciones. Periarticular: duele solo activo o en dirección específica ("arco doloroso").' },
  { front: 'Choque rotuliano vs. signo de la oleada', back: 'Choque rotuliano: derrames moderados-grandes. Oleada: derrames pequeños (la rótula no llega a "flotar").' },
  { front: 'Patrón poliarticular simétrico', back: 'Artritis reumatoide, lupus eritematoso sistémico.' },
  { front: 'Patrón migratorio vs. aditivo', back: 'Migratorio: una articulación se resuelve antes de que otra se afecte (fiebre reumática, gonocócica). Aditivo: se suman sin resolver (artritis reumatoide).' },
  { front: 'Maniobra de Lachman', back: 'Rodilla a 20-30°, tracción tibial anterior → ligamento cruzado anterior. Más sensible que el cajón anterior (90°).' },
  { front: 'Maniobra de McMurray', back: 'Flexión + rotación + extensión → menisco. Rotación externa = medial; interna = lateral.' },
  { front: 'Tinel y Phalen', back: 'Parestesias en territorio del nervio mediano → síndrome del túnel carpiano.' },
  { front: 'Finkelstein', back: 'Dolor en tabaquera anatómica → tenosinovitis de De Quervain (tendones del 1er compartimento extensor).' },
  { front: 'Edema con fóvea vs. sin fóvea', back: 'Con fóvea: líquido libre (↑presión hidrostática, ↓oncótica). Sin fóvea: proteínas fijas (linfedema, mixedema).' },
  { front: 'Signo de Stemmer', back: 'Imposibilidad de pellizcar la piel en la base del 2º dedo del pie → específico de linfedema.' },
  { front: 'Edema unilateral vs. bilateral', back: 'Unilateral: causa local (TVP, obstrucción focal). Bilateral: causa sistémica (IC, hepatopatía, hipoalbuminemia).' },
  { front: 'Signo de Homans', back: 'Dolor en pantorrilla con dorsiflexión pasiva. Baja sensibilidad/especificidad para TVP — en desuso (riesgo teórico de desprender trombo).' },
  { front: 'Escala de Wells (TVP)', back: 'Estratifica probabilidad pretest → guía dímero D vs. ecografía Doppler, en vez de un signo aislado.' },
  { front: 'Insuficiencia venosa crónica: mecanismo', back: 'Incompetencia valvular → reflujo retrógrado → presión venosa ambulatoria crónicamente elevada.' },
  { front: 'Progresión de la insuficiencia venosa crónica', back: 'Varices → edema vespertino → dermatitis por estasis → lipodermatoesclerosis → úlcera venosa.' },
  { front: 'Úlcera venosa: localización', back: 'Región maleolar medial ("gaiter area").' },
  { front: 'ITB normal y patológico', back: 'Normal: 1.0-1.4. Enfermedad arterial periférica: ≤0.9. >1.4: arterias no compresibles (calcificación).' },
  { front: 'Las 6 P de isquemia arterial aguda', back: 'Pain, Pallor, Pulselessness, Paresthesia (temprano), Paralysis (tardío), Poiquilotermia.' },
  { front: 'Parestesia vs. parálisis en isquemia aguda', back: 'Parestesia: temprana (nervio sensible). Parálisis: tardía (daño muscular establecido) → revascularización EMERGENTE.' },
  { front: 'Signo de Buerger', back: 'Palidez al elevar la pierna + rubor tardío intenso al colgarla → enfermedad arterial periférica significativa.' },
  { front: 'Úlcera venosa vs. arterial: dolor y posición', back: 'Venosa: mejora con elevación. Arterial: EMPEORA con elevación, mejora al colgar la pierna.' },
  { front: 'Úlcera venosa vs. arterial: bordes', back: 'Venosa: irregulares, poco profundos. Arterial: "en sacabocados", profundos.' },
  { front: 'ITB antes de compresión', back: 'Medir siempre antes de indicar compresión — comprimir una extremidad arterialmente comprometida empeora la isquemia.' }
];

export default { quiz, flashcards };
