// topics/hipotiroidismo/study.js: Autoevaluacion de Hipotiroidismo.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// Metodo (ver memoria del proyecto): las 48 preguntas (30 sueltas + 6 cascadas de 3 pasos) se
// escribieron con la respuesta correcta en options[0]/correct:0 y luego se redistribuyo la
// posicion de `correct` con un script. Sin em dash (ver [[feedback-no-em-dash]]).

export const quiz = [
  { q: 'Que prueba se usa como cribado inicial del hipotiroidismo primario?', options: ['La TSH aislada', 'La T4 libre aislada', 'La T3 libre aislada', 'Los anticuerpos antitiroperoxidasa'], correct: 0, explanation: 'Por la relacion logaritmica entre TSH y T4 libre, la TSH se altera antes y en mayor magnitud que ninguna otra. Se anade T4 libre solo cuando la TSH esta alterada o cuando se sospecha enfermedad hipofisaria.', dificultad: 'facil' },
  { q: 'Por que un descenso pequeno de T4 libre produce una subida grande de TSH?', options: ['Porque la TSH tiene una vida media mucho mas larga que la T4', 'Porque la T4 libre circula unida a proteinas en su mayor parte', 'Porque la relacion entre ambas es logaritmica y la hipofisis es muy sensible', 'Porque las desyodasas amplifican la senal en el tejido periferico'], correct: 2, explanation: 'La celula tirotropa es la mas sensible del organismo a la hormona tiroidea. De esa amplificacion logaritmica salen las dos consecuencias del tema: el cribado con TSH sola y la existencia misma de la enfermedad subclinica.', dificultad: 'intermedio' },
  { q: 'Que define bioquimicamente al hipotiroidismo subclinico?', options: ['TSH alta con T4 libre baja', 'TSH normal con T4 libre baja', 'TSH baja con T4 libre normal', 'TSH alta con T4 libre normal'], correct: 3, explanation: 'La TSH sube para mantener la T4 libre dentro del rango: mientras lo consigue, el paciente esta compensado a costa de un estimulo tiroideo elevado. TSH alta con T4 libre baja seria el hipotiroidismo franco.', dificultad: 'facil' },
  { q: 'Cual es la causa mas frecuente de hipotiroidismo en zonas con yodo suficiente?', options: ['El tratamiento previo con yodo radiactivo', 'La tiroiditis de Hashimoto', 'La tiroiditis subaguda de De Quervain', 'El tratamiento prolongado con litio'], correct: 1, explanation: 'La tiroiditis linfocitaria cronica autoinmune es la causa dominante donde el aporte de yodo es adecuado, con anticuerpos antitiroperoxidasa positivos en el 90 al 95% de los casos.', dificultad: 'facil' },
  { q: 'Cual es la causa mas frecuente de hipotiroidismo a escala mundial?', options: ['La tiroiditis autoinmune de Hashimoto', 'El deficit de yodo', 'La tiroidectomia por bocio o por cancer', 'El exceso de yodo de los contrastes yodados'], correct: 1, explanation: 'Aunque en los paises con sal yodada domina la autoinmunidad, en el conjunto de la poblacion mundial el deficit de yodo sigue siendo la primera causa de hipotiroidismo y de bocio.', dificultad: 'intermedio' },
  { q: 'Que anticuerpo se pide para documentar el origen autoinmune del hipotiroidismo?', options: ['El antirreceptor de TSH', 'El antimitocondrial', 'El anticelula parietal gastrica', 'El antitiroperoxidasa'], correct: 3, explanation: 'Es positivo en el 90 al 95% de las tiroiditis de Hashimoto y, en el subclinico, predice la progresion a hipotiroidismo franco, por lo que inclina la decision hacia tratar. El antirreceptor de TSH pertenece al estudio de la enfermedad de Graves.', dificultad: 'facil' },
  { q: 'Que patron analitico caracteriza al hipotiroidismo central?', options: ['T4 libre baja con TSH baja, normal o solo levemente alta', 'T4 libre baja con TSH claramente elevada', 'T4 libre normal con TSH elevada de forma persistente', 'T4 libre alta con TSH suprimida por debajo del rango'], correct: 0, explanation: 'La hipofisis no puede responder a la caida de T4, de modo que la TSH es inapropiadamente baja PARA una T4 libre baja. Hasta un tercio de los casos tiene una TSH dentro del rango normal pero biologicamente poco activa.', dificultad: 'intermedio' },
  { q: 'Por que parametro se titula la levotiroxina en el hipotiroidismo central?', options: ['Por la TSH en la mitad baja del rango', 'Por la T3 libre en el centro del rango', 'Por la T4 libre en la mitad alta del rango', 'Por la desaparicion completa de los sintomas'], correct: 2, explanation: 'La TSH no sirve porque el problema esta en la propia hipofisis: usarla como objetivo lleva a infratratar de forma sistematica. Se mide la T4 libre antes de la toma diaria.', dificultad: 'intermedio' },
  { q: 'Que hay que descartar antes de dar la primera dosis de levotiroxina en un hipotiroidismo central?', options: ['La fibrilacion auricular paroxistica', 'El deficit de hormona de crecimiento', 'La insuficiencia suprarrenal', 'La hiperprolactinemia asociada'], correct: 2, explanation: 'La hormona tiroidea acelera el aclaramiento del cortisol y puede precipitar una crisis addisoniana. El orden es siempre glucocorticoide primero, levotiroxina despues.', dificultad: 'dificil' },
  { q: 'Cual es la dosis plena de sustitucion de levotiroxina?', options: ['1.6 microgramos por kilo y dia', '0.5 microgramos por kilo y dia', '3.0 microgramos por kilo y dia', '5.0 microgramos por kilo y dia'], correct: 0, explanation: 'Se calcula mejor sobre peso ideal que sobre peso real, sobre todo en la obesidad. En el menor de 60 anos sin cardiopatia se puede empezar directamente con esa dosis plena.', dificultad: 'facil' },
  { q: 'Como debe tomarse la levotiroxina para asegurar su absorcion?', options: ['Con el desayuno, para mejorar su tolerancia gastrica', 'En ayunas, 30 a 60 minutos antes del desayuno', 'Junto con el suplemento de calcio de la manana', 'Repartida en dos tomas con las comidas principales'], correct: 1, explanation: 'Tambien sirve al acostarse, 3 horas despues de cenar. Debe separarse al menos 4 horas del calcio, el hierro, los inhibidores de la bomba de protones, el sevelamer y las resinas.', dificultad: 'facil' },
  { q: 'A las cuantas semanas de un cambio de dosis se recontrola la TSH?', options: ['A las 1 a 2 semanas', 'A las 3 a 4 semanas', 'A los 6 meses', 'A las 6 a 8 semanas'], correct: 3, explanation: 'El eje hipotalamo-hipofisis-tiroides tarda ese tiempo en reequilibrarse. Medir antes lleva a interpretar mal el resultado y a encadenar ajustes de dosis innecesarios.', dificultad: 'facil' },
  { q: 'Cual es la primera hipotesis ante una TSH que no baja pese a dosis altas de levotiroxina?', options: ['Una resistencia genetica a las hormonas tiroideas', 'Un adenoma hipofisario secretor de TSH', 'Una conversion periferica de T4 a T3 insuficiente', 'La adherencia y la forma de tomar el farmaco'], correct: 3, explanation: 'Es con diferencia lo mas frecuente: toma con alimentos, junto a quelantes o de forma irregular. Solo despues se buscan causas organicas de malabsorcion como la celiaquia o la gastritis atrofica.', dificultad: 'intermedio' },
  { q: 'A partir de que cifra de TSH se trata el hipotiroidismo subclinico con independencia de otros factores?', options: ['A partir de 5 mUI/L', 'A partir de 10 mUI/L', 'A partir de 7 mUI/L', 'A partir de 20 mUI/L'], correct: 1, explanation: 'Es el grupo con riesgo demostrado de progresion a hipotiroidismo franco, de insuficiencia cardiaca y de enfermedad coronaria. Por debajo de esa cifra la decision se individualiza.', dificultad: 'intermedio' },
  { q: 'Que mostro el ensayo TRUST sobre el tratamiento del hipotiroidismo subclinico en mayores de 65 anos?', options: ['Redujo de forma clara los eventos cardiovasculares', 'Mejoro la funcion cognitiva de forma sostenida', 'No mejoro los sintomas ni la calidad de vida', 'Disminuyo la mortalidad por cualquier causa'], correct: 2, explanation: 'Es el argumento principal para no tratar de forma automatica al anciano con TSH ligeramente alta, sobre todo si esta asintomatico, porque el sobretratamiento si tiene riesgos reales.', dificultad: 'intermedio' },
  { q: 'Cual es la conducta habitual ante un hipotiroidismo subclinico leve en un paciente de 85 anos?', options: ['Observar con controles periodicos', 'Iniciar levotiroxina a dosis plena de sustitucion', 'Iniciar levotiroxina con objetivo de TSH suprimida', 'Repetir el perfil solo si aparece bocio palpable'], correct: 0, explanation: 'La TSH sube de forma fisiologica con la edad y una TSH ligeramente alta se ha asociado a mayor supervivencia en el muy anciano. El riesgo de fibrilacion auricular y de fractura por sobretratamiento pesa mas que el beneficio esperable.', dificultad: 'intermedio' },
  { q: 'Que ajuste de levotiroxina se hace en cuanto se confirma un embarazo?', options: ['Subir la dosis un 25 a 30%', 'Mantener la misma dosis hasta el segundo trimestre', 'Bajar la dosis un 25% por el efecto de la gonadotropina', 'Suspenderla y revalorar con el perfil del trimestre'], correct: 0, explanation: 'Una forma practica equivalente es anadir dos dosis extra a la semana. El aumento se hace sin esperar a la analitica, porque el desarrollo neurologico fetal del primer trimestre depende por completo de la T4 materna.', dificultad: 'intermedio' },
  { q: 'Con que frecuencia se controla la TSH en la gestante tratada durante la primera mitad del embarazo?', options: ['Una sola vez en cada trimestre', 'Cada 12 semanas hasta el parto', 'Solo si aparecen sintomas atribuibles', 'Cada 4 semanas hasta la semana 16 a 20'], correct: 3, explanation: 'Y al menos una determinacion mas hacia la semana 30. Tras el parto se vuelve a la dosis pregestacional y se recontrola a las 6 semanas.', dificultad: 'intermedio' },
  { q: 'Que ocurrio con el umbral de TSH de 2.5 mUI/L del primer trimestre?', options: ['Se mantiene como umbral universal de tratamiento', 'Quedo obsoleto porque sobrediagnosticaba', 'Se rebajo a 1.5 mUI/L en la guia mas reciente', 'Se aplica solo a las gestantes sin anticuerpos'], correct: 1, explanation: 'La guia de la ATA de 2017 recomienda usar rangos del propio laboratorio y, si no existen, un limite superior en torno a 4.0 mUI/L, que corresponde a reducir en unos 0.5 el limite de la no gestante.', dificultad: 'dificil' },
  { q: 'Que signo de la exploracion es mas especifico de hipotiroidismo?', options: ['La presencia de edema con fovea en ambos tobillos', 'La palidez cutanea con mucosas bien coloreadas', 'El reflejo aquileo con relajacion lenta', 'El temblor fino distal con las manos extendidas'], correct: 2, explanation: 'Es casi patognomonico cuando se observa. Los otros dos signos de valor son la bradicardia con hipertension diastolica y el derrame pericardico con electrocardiograma de bajo voltaje.', dificultad: 'intermedio' },
  { q: 'Que alteracion lipidica produce el hipotiroidismo?', options: ['Descenso aislado del colesterol HDL', 'Elevacion del colesterol LDL', 'Hipertrigliceridemia grave con quilomicronemia', 'Descenso global de todas las fracciones lipidicas'], correct: 1, explanation: 'Reduce el aclaramiento hepatico de las LDL. Ante una hipercolesterolemia de nueva aparicion o de mal control conviene pedir TSH antes de intensificar la estatina, porque puede corregirse al tratar el tiroides.', dificultad: 'intermedio' },
  { q: 'Que alteracion del sodio se asocia al hipotiroidismo?', options: ['Hiponatremia', 'Hipernatremia', 'Sodio dentro del rango de referencia', 'Hipernatremia con hipopotasemia'], correct: 0, explanation: 'Por deterioro del aclaramiento de agua libre. Junto con la elevacion de la creatincinasa y la anemia normocitica, es una de las pistas indirectas que deben hacer pedir una TSH.', dificultad: 'intermedio' },
  { q: 'Cual es la primera hormona que desciende en el sindrome del enfermo eutiroideo?', options: ['La T4 total', 'La TSH', 'La T3', 'La T4 libre'], correct: 2, explanation: 'La desyodasa tipo 3 desvia la T4 hacia T3 reversa, que es inactiva. Despues cae la T4 y, en la recuperacion, la TSH rebota por encima del rango, lo que imita un hipotiroidismo subclinico.', dificultad: 'dificil' },
  { q: 'Por que no se recomienda pedir perfil tiroideo de rutina en el paciente critico?', options: ['Porque las hormonas tiroideas no se alteran durante la enfermedad aguda', 'Porque la muestra se degrada en los pacientes con inestabilidad', 'Porque el tratamiento sustitutivo mejora el pronostico de todos modos', 'Porque el enfermo eutiroideo genera patrones que imitan enfermedad tiroidea'], correct: 3, explanation: 'Es una adaptacion, no una enfermedad tiroidea, y no se trata con levotiroxina. Si aun asi se pide y sale alterado, la conducta correcta es repetirlo a las 6 a 12 semanas del alta.', dificultad: 'intermedio' },
  { q: 'Cuales son las dos complicaciones relevantes del sobretratamiento con levotiroxina?', options: ['La litiasis renal y la insuficiencia renal cronica', 'La esteatosis hepatica y la hipertransaminasemia', 'La fibrilacion auricular y la perdida de masa osea', 'La anemia hemolitica y la trombocitopenia'], correct: 2, explanation: 'La TSH suprimida acorta el periodo refractario auricular y acelera el remodelado oseo con predominio de la resorcion. El riesgo se concentra en el mayor de 60 anos y en la mujer posmenopausica.', dificultad: 'intermedio' },
  { q: 'Que grupo de farmacos reduce la absorcion de la levotiroxina si se toman a la vez?', options: ['Las estatinas, los fibratos y la ezetimiba', 'El calcio, el hierro y los inhibidores de la bomba de protones', 'Los betabloqueantes, los diureticos y los antagonistas del calcio', 'Los antihistaminicos, los corticoides inhalados y los broncodilatadores'], correct: 1, explanation: 'Tambien el sevelamer, el sucralfato y las resinas de intercambio. La levotiroxina necesita medio acido para disolverse y se quela con facilidad, por eso hay que separarla al menos 4 horas.', dificultad: 'intermedio' },
  { q: 'Que farmacos aumentan la necesidad de levotiroxina por acelerar su aclaramiento hepatico?', options: ['El paracetamol, el ibuprofeno y el metamizol', 'La metformina, la insulina y las sulfonilureas', 'La amlodipina, el enalapril y la hidroclorotiazida', 'La fenitoina, la carbamazepina y la rifampicina'], correct: 3, explanation: 'Actuan por induccion enzimatica, no por malabsorcion, asi que separar los horarios no sirve: hay que subir la dosis. Los estrogenos orales tambien la aumentan, pero al elevar la globulina fijadora de tiroxina.', dificultad: 'dificil' },
  { q: 'Por que no se recomienda la combinacion de T4 con T3 de forma rutinaria?', options: ['Porque no ha demostrado superioridad y da picos no fisiologicos de T3', 'Porque la T3 no se absorbe por via oral de forma fiable', 'Porque suprime la conversion periferica de T4 en T3', 'Porque produce hipotiroidismo central por supresion hipofisaria'], correct: 0, explanation: 'La levotiroxina en monoterapia aprovecha la conversion periferica fisiologica. Lo mismo se aplica a los extractos de tiroides desecada, con contenido de T3 variable y no estandarizado.', dificultad: 'intermedio' },
  { q: 'Por que puede aparecer hiperprolactinemia en el hipotiroidismo primario grave?', options: ['Porque la falta de T3 lesiona el tallo hipofisario', 'Porque la TSH tiene accion directa sobre la celula lactotropa', 'Porque el mixedema comprime la silla turca desde fuera', 'Porque la TRH elevada estimula la secrecion de prolactina'], correct: 3, explanation: 'Puede acompanarse de hiperplasia hipofisaria reversible que imita un adenoma en la resonancia. Todo se normaliza con levotiroxina, por lo que conviene comprobar la TSH antes de plantear cirugia hipofisaria.', dificultad: 'dificil' },
  { q: 'Que hay que sospechar ante un perfil con TSH alta y T4 libre tambien alta?', options: ['Una tiroiditis de Hashimoto en fase inicial', 'Un hipotiroidismo central de larga evolucion', 'Interferencia del ensayo o toma reciente de varias dosis', 'Un sindrome del enfermo eutiroideo en fase precoz'], correct: 2, explanation: 'Antes de pensar en un adenoma secretor de TSH o en resistencia a hormonas tiroideas, hay que descartar lo frecuente: biotina a dosis altas, anticuerpos heterofilos, macro-TSH o un paciente que acumulo dosis antes del analisis.', dificultad: 'dificil' },

  { type: 'cascade', vignette: 'Mujer de 42 anos que consulta por cansancio, estrenimiento e intolerancia al frio de varios meses. En la exploracion destaca bradicardia y piel seca. La analitica muestra TSH de 12.6 mUI/L y T4 libre de 0.6 ng/dL.', steps: [
    { q: 'Como se interpreta este perfil?', options: ['Hipotiroidismo primario franco', 'Hipotiroidismo subclinico', 'Hipotiroidismo central', 'Sindrome del enfermo eutiroideo'], correct: 0 },
    { q: 'Cual es el siguiente paso terapeutico?', options: ['Repetir el perfil en 12 semanas antes de decidir nada', 'Iniciar levotiroxina y pedir anticuerpos antitiroperoxidasa', 'Solicitar una gammagrafia tiroidea con yodo radiactivo', 'Pedir resonancia de hipofisis antes de tratar'], correct: 1 },
    { q: 'Cuando se recontrola la TSH tras iniciar el tratamiento?', options: ['A las 6 a 8 semanas', 'A los 7 dias', 'A las 3 semanas', 'Al ano de tratamiento'], correct: 0 }
  ], explanation: 'TSH alta con T4 libre baja es hipotiroidismo primario franco y se trata siempre, sin necesidad de confirmar con una segunda determinacion. Los anticuerpos antitiroperoxidasa documentan el origen autoinmune. La gammagrafia no tiene papel en el hipotiroidismo, y el eje tarda 6 a 8 semanas en reequilibrarse tras cada cambio de dosis.', dificultad: 'facil' },

  { type: 'cascade', vignette: 'Mujer de 34 anos con hipotiroidismo autoinmune conocido, en tratamiento estable con levotiroxina 100 microgramos al dia. Acude porque una prueba de embarazo ha resultado positiva y esta de 8 semanas.', steps: [
    { q: 'Que hay que hacer con la dosis de levotiroxina?', options: ['Mantenerla y revalorar en el segundo trimestre', 'Subirla un 25 a 30% de inmediato', 'Bajarla un 25% por el efecto de la gonadotropina', 'Suspenderla hasta tener el perfil del trimestre'], correct: 1 },
    { q: 'Cual es el objetivo de TSH en esta paciente?', options: ['Un valor por debajo del limite inferior', 'La mitad alta del rango del trimestre', 'La mitad baja del rango del trimestre', 'Cualquier valor dentro del rango general'], correct: 2 },
    { q: 'Con que frecuencia se controla la TSH hasta la semana 20?', options: ['Cada 2 semanas', 'Cada 8 semanas', 'Solo una vez por trimestre', 'Cada 4 semanas'], correct: 3 }
  ], explanation: 'La necesidad de levotiroxina sube desde el inicio de la gestacion por el aumento de la globulina fijadora, la degradacion placentaria y el estimulo de la gonadotropina corionica. El aumento se hace sin esperar a la analitica, y una alternativa practica equivalente es anadir dos dosis extra a la semana.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Varon de 72 anos con cardiopatia isquemica y angina estable. Consulta por astenia intensa y bradipsiquia. TSH de 45 mUI/L y T4 libre de 0.3 ng/dL. Pesa 70 kg.', steps: [
    { q: 'Con que dosis de levotiroxina se inicia el tratamiento?', options: ['Con la dosis plena de 112 microgramos al dia', 'Con 12.5 a 25 microgramos al dia', 'Con 200 microgramos al dia durante una semana', 'Con levotiroxina intravenosa en dosis de carga'], correct: 1 },
    { q: 'Que hay que vigilar durante el ascenso de la dosis?', options: ['La aparicion de hipoglucemias de repeticion', 'El deterioro progresivo de la funcion renal', 'La aparicion de angina o de taquiarritmia', 'La elevacion de las transaminasas hepaticas'], correct: 2 },
    { q: 'Que objetivo de TSH es razonable en este paciente?', options: ['Un valor suprimido por debajo de 0.1', 'La mitad baja del rango normal', 'Un valor entre 10 y 15 mUI/L', 'El rango normal, aceptando su mitad alta'], correct: 3 }
  ], explanation: 'Acelerar de golpe un corazon acostumbrado a la bradicardia puede desencadenar angina, infarto o arritmia, por lo que en el mayor de 60 anos o con cardiopatia isquemica se empieza bajo y se sube cada 4 a 6 semanas. En el paciente mayor se acepta un objetivo de TSH mas alto que en el joven.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Varon de 66 anos ingresado en cuidados intensivos por choque septico de origen abdominal. Un perfil tiroideo pedido en el ingreso muestra T3 libre baja, T4 libre en el limite inferior y TSH de 0.2 mUI/L.', steps: [
    { q: 'Cual es la interpretacion mas probable?', options: ['Sindrome del enfermo eutiroideo', 'Hipotiroidismo central por hipofisitis', 'Tirotoxicosis por amiodarona', 'Hipotiroidismo primario descompensado'], correct: 0 },
    { q: 'Cual es la conducta correcta?', options: ['Iniciar levotiroxina intravenosa a dosis plena', 'Anadir liotironina para corregir la T3 baja', 'No tratar y repetir el perfil tras la recuperacion', 'Solicitar resonancia de hipofisis urgente'], correct: 2 },
    { q: 'Que se espera encontrar en la fase de recuperacion?', options: ['Una T3 que sigue descendiendo varias semanas', 'Una TSH que permanece suprimida durante meses', 'Una T4 libre que se eleva por encima del rango', 'Una TSH que rebota por encima del rango'], correct: 3 }
  ], explanation: 'El sindrome del enfermo eutiroideo es una adaptacion a la enfermedad grave mediada por la desyodasa tipo 3, no una enfermedad tiroidea, y no mejora con hormona sustitutiva. El rebote de TSH de la convalecencia es la causa mas frecuente de falso diagnostico de hipotiroidismo subclinico en el paciente hospitalizado.', dificultad: 'dificil' },

  { type: 'cascade', vignette: 'Mujer de 58 anos con hipotiroidismo de Hashimoto en tratamiento con levotiroxina 150 microgramos al dia (pesa 62 kg). En los ultimos tres controles la TSH se mantiene entre 12 y 18 mUI/L pese a dos subidas de dosis. Refiere tomarla todos los dias.', steps: [
    { q: 'Cual es la primera hipotesis a considerar?', options: ['Un problema de adherencia o de forma de tomarla', 'Una resistencia genetica a las hormonas tiroideas', 'Un adenoma hipofisario secretor de TSH', 'Un defecto de conversion periferica de T4 en T3'], correct: 0 },
    { q: 'Que estudio dirigido es razonable si la toma parece correcta?', options: ['Gammagrafia tiroidea con tecnecio', 'Cribado de celiaquia y de gastritis atrofica', 'Biopsia tiroidea con aguja fina', 'Cateterismo de senos petrosos inferiores'], correct: 1 },
    { q: 'Que prueba distingue la falta de adherencia de la malabsorcion verdadera?', options: ['Una determinacion de T3 reversa en suero', 'Una curva de TSH tras estimulo con TRH', 'Una medicion de yoduria en orina de 24 horas', 'Una prueba de absorcion supervisada de levotiroxina'], correct: 3 }
  ], explanation: 'La dosis ya supera los 1.9 microgramos por kilo, de modo que subirla mas rara vez es la solucion. En la prueba de absorcion se administra una dosis alta unica bajo observacion y se mide la T4 en serie: un ascenso adecuado descarta malabsorcion y senala que el problema era la toma.', dificultad: 'dificil' },

  { type: 'cascade', vignette: 'Mujer de 68 anos en tratamiento con levotiroxina desde hace 15 anos, sin cambios de dosis. Consulta por palpitaciones e insomnio. TSH de 0.05 mUI/L con T4 libre en el limite alto de la normalidad. Ha perdido 6 kg en el ultimo ano.', steps: [
    { q: 'Cual es el diagnostico mas probable?', options: ['Sobretratamiento con levotiroxina', 'Enfermedad de Graves de nueva aparicion', 'Hipotiroidismo central mal controlado', 'Interferencia del ensayo por biotina'], correct: 0 },
    { q: 'Que complicaciones hay que buscar de forma activa?', options: ['Insuficiencia renal y litiasis de repeticion', 'Fibrilacion auricular y perdida de masa osea', 'Esteatosis hepatica y elevacion de enzimas', 'Anemia hemolitica y trombocitopenia'], correct: 1 },
    { q: 'Cual es la conducta terapeutica?', options: ['Suspender la levotiroxina y repetir el perfil', 'Anadir un antitiroideo de sintesis al tratamiento', 'Reducir la dosis en escalones de 12.5 a 25 microgramos', 'Mantener la dosis y repetir el control en un ano'], correct: 2 }
  ], explanation: 'La perdida de peso y el envejecimiento reducen la necesidad de levotiroxina, y una dosis no revisada durante anos acaba siendo excesiva. Conviene ademas replantear si la indicacion original sigue siendo valida y fijar un objetivo de TSH mas alto en el paciente mayor.', dificultad: 'intermedio' }
];

export const flashcards = [
  { front: 'Prueba de cribado del hipotiroidismo primario', back: 'La TSH aislada. Se anade T4 libre solo si esta alterada o si se sospecha enfermedad hipofisaria.' },
  { front: 'Por que la TSH es la prueba mas sensible del eje', back: 'La relacion con la T4 libre es logaritmica: un descenso pequeno de T4 produce una subida grande de TSH.' },
  { front: 'Definicion de hipotiroidismo subclinico', back: 'TSH alta con T4 libre normal, confirmada en una segunda determinacion a las 6 a 12 semanas.' },
  { front: 'Causa mas frecuente donde hay yodo suficiente', back: 'Tiroiditis de Hashimoto, con anticuerpos antitiroperoxidasa positivos en el 90 al 95%.' },
  { front: 'Causa mas frecuente a escala mundial', back: 'El deficit de yodo.' },
  { front: 'Patron del hipotiroidismo central', back: 'T4 libre baja con TSH baja, normal o solo levemente alta: inapropiadamente baja PARA esa T4.' },
  { front: 'Como se titula el hipotiroidismo central', back: 'Por T4 libre en la mitad alta del rango. La TSH NO sirve como objetivo.' },
  { front: 'Que hacer antes de la primera levotiroxina en el central', back: 'Descartar y tratar la insuficiencia suprarrenal: primero el glucocorticoide, despues la hormona.' },
  { front: 'Dosis plena de sustitucion de levotiroxina', back: '1.6 microgramos por kilo y dia, calculada sobre peso ideal.' },
  { front: 'Inicio en el anciano o el cardiopata', back: '12.5 a 25 microgramos al dia, subiendo cada 4 a 6 semanas.' },
  { front: 'Como se toma la levotiroxina', back: 'En ayunas 30 a 60 minutos antes del desayuno, separada 4 horas de calcio, hierro, IBP, sevelamer y resinas.' },
  { front: 'Cuando se recontrola la TSH', back: 'A las 6 a 8 semanas de cada cambio de dosis, nunca antes.' },
  { front: 'Umbral para tratar el hipotiroidismo subclinico', back: 'TSH de 10 mUI/L o mas. Por debajo se individualiza por edad, anticuerpos, sintomas y embarazo.' },
  { front: 'Que mostro el ensayo TRUST', back: 'No mejoro sintomas ni calidad de vida al tratar el subclinico en mayores de 65 anos.' },
  { front: 'Subclinico en el mayor de 80 a 85 anos', back: 'Observar: la TSH sube de forma fisiologica con la edad y el sobretratamiento si tiene riesgo.' },
  { front: 'Ajuste de levotiroxina al confirmar un embarazo', back: 'Subir la dosis un 25 a 30%, o anadir dos dosis extra a la semana.' },
  { front: 'Control de TSH en la gestante tratada', back: 'Cada 4 semanas hasta la semana 16 a 20, y al menos una vez mas hacia la semana 30.' },
  { front: 'Umbral de TSH del primer trimestre', back: 'En torno a 4.0 mUI/L. El umbral clasico de 2.5 quedo obsoleto con la guia de 2017.' },
  { front: 'Signo exploratorio mas especifico', back: 'El reflejo aquileo con relajacion lenta.' },
  { front: 'Alteracion lipidica del hipotiroidismo', back: 'Elevacion del colesterol LDL por menor aclaramiento hepatico.' },
  { front: 'Alteracion del sodio', back: 'Hiponatremia, por deterioro del aclaramiento de agua libre.' },
  { front: 'Primera hormona que cae en el enfermo eutiroideo', back: 'La T3, desviada a T3 reversa por la desyodasa tipo 3.' },
  { front: 'Por que no pedir perfil tiroideo en el critico', back: 'El enfermo eutiroideo imita enfermedad tiroidea, y en la recuperacion la TSH rebota por encima del rango.' },
  { front: 'Las dos complicaciones del sobretratamiento', back: 'Fibrilacion auricular y perdida de masa osea.' },
  { front: 'TSH que no baja pese a dosis altas: primera hipotesis', back: 'Adherencia y forma de tomar el farmaco, no la dosis.' },
  { front: 'Farmacos que reducen la absorcion de levotiroxina', back: 'Calcio, hierro, inhibidores de la bomba de protones, sevelamer, sucralfato y resinas.' },
  { front: 'Farmacos que aumentan la necesidad por induccion enzimatica', back: 'Fenitoina, carbamazepina, fenobarbital y rifampicina.' },
  { front: 'Por que no se usa la combinacion de T4 con T3', back: 'No ha demostrado superioridad y produce picos no fisiologicos de T3.' },
  { front: 'Hiperprolactinemia en el hipotiroidismo primario grave', back: 'La TRH elevada estimula la prolactina; puede haber hiperplasia hipofisaria reversible que imita un adenoma.' },
  { front: 'TSH alta con T4 libre tambien alta', back: 'Descartar antes lo frecuente: toma reciente de varias dosis e interferencia del ensayo (biotina, heterofilos, macro-TSH).' },
  { front: 'Anticuerpo que documenta el origen autoinmune', back: 'El antitiroperoxidasa. Predice ademas la progresion del subclinico a franco.' },
  { front: 'Objetivo de TSH segun la edad', back: 'Mitad baja del rango en el joven; mitad alta o incluso limite superior en el mayor de 70 a 80 anos.' }
];
