// topics/porfirias/study.js: Autoevaluación de Porfirias.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Índices `correct` de las 30 preguntas sueltas, en orden: 3,1,0,2,3,2,1,0,3,1,2,0,3,0,1,2,3,0,2,
// 1,3,0,1,2,3,1,0,2,1,3. Recuento: 0×7, 1×8, 2×7, 3×8. Sin racha >2 ni ciclo fijo.
// Índices `correct` de los pasos de las 5 preguntas en cascada (3 pasos c/u), en orden: 0,1,2 /
// 2,0,3 / 1,3,0 / 0,2,1 / 3,1,2. Recuento: 0×4, 1×4, 2×4, 3×3.

export const quiz = [
  { q: 'Todas las porfirias tienen en común...', options: ['Ser adquiridas, no hereditarias', 'Afectar la piel, no el sistema nervioso', 'Requerir hemina intravenosa', 'Deficiencia de una enzima del hemo'], correct: 3, explanation: 'Cada porfiria corresponde a la deficiencia parcial de una enzima distinta de la vía de síntesis del hemo.', dificultad: 'facil' },
  { q: '¿Qué determina las manifestaciones clínicas específicas de cada porfiria?', options: ['El sexo del paciente afectado', 'Qué precursor se acumula', 'La edad de inicio del cuadro', 'El tipo de herencia genética'], correct: 1, explanation: 'La molécula que se acumula por encima del bloqueo enzimático específico determina si predominan manifestaciones neuroviscerales (ALA/PBG) o cutáneas (porfirinas).', dificultad: 'intermedio' },
  { q: '¿Cuál es la porfiria más frecuente en general?', options: ['Porfiria cutánea tarda', 'Porfiria aguda intermitente', 'Protoporfiria eritropoyética', 'Coproporfiria hereditaria'], correct: 0, explanation: 'La porfiria cutánea tarda es, con diferencia, la porfiria más frecuente en general.', dificultad: 'facil' },
  { q: '¿Cuál es la porfiria hepática aguda más frecuente?', options: ['Porfiria variegata', 'Coproporfiria hereditaria', 'Porfiria aguda intermitente', 'Deficiencia de ALA-deshidratasa'], correct: 2, explanation: 'La porfiria aguda intermitente es la porfiria hepática aguda más frecuente.', dificultad: 'facil' },
  { q: '¿Por qué las crisis de porfiria aguda intermitente ocurren predominantemente en mujeres jóvenes en edad reproductiva?', options: ['Una mutación del cromosoma X', 'Menor actividad basal de la enzima', 'No tiene explicación conocida', 'La influencia hormonal del ciclo'], correct: 3, explanation: 'Las hormonas sexuales inducen la ALA-sintasa hepática, particularmente en la fase lútea, precipitando las crisis en mujeres jóvenes.', dificultad: 'intermedio' },
  { q: '¿Qué caracteriza clínicamente a la porfiria aguda intermitente, distinguiéndola de la coproporfiria hereditaria y la porfiria variegata?', options: ['Cursa con fiebre alta constante', 'Se presenta solo en varones', 'Ausencia de síntomas cutáneos', 'No produce dolor abdominal'], correct: 2, explanation: 'La porfiria aguda intermitente no produce manifestaciones cutáneas, a diferencia de la coproporfiria hereditaria y la porfiria variegata.', dificultad: 'facil' },
  { q: '¿Qué distingue bioquímicamente a la coproporfiria hereditaria y la porfiria variegata de la porfiria aguda intermitente?', options: ['No elevan ALA ni PBG en orina', 'Acumulan porfirinas en heces', 'Se heredan de forma recesiva', 'Se presentan solo en varones'], correct: 1, explanation: 'La coproporfiria hereditaria y la porfiria variegata acumulan adicionalmente porfirinas en heces, produciendo manifestaciones cutáneas ausentes en la porfiria aguda intermitente.', dificultad: 'intermedio' },
  { q: '¿En qué población tiene la porfiria variegata una prevalencia particularmente elevada por un efecto fundador?', options: ['Población afrikáner de Sudáfrica', 'Población escandinava del norte', 'Población japonesa continental', 'Población andina de gran altura'], correct: 0, explanation: 'La porfiria variegata tiene una prevalencia particularmente elevada en la población afrikáner de Sudáfrica por un efecto fundador.', dificultad: 'intermedio' },
  { q: '¿Cuál es la enzima deficiente en la porfiria cutánea tarda?', options: ['PBG-desaminasa eritrocitaria', 'Ferroquelatasa mitocondrial', 'Coproporfirinógeno oxidasa', 'Uroporfirinógeno descarboxilasa'], correct: 3, explanation: 'La porfiria cutánea tarda es producida por la deficiencia de uroporfirinógeno descarboxilasa.', dificultad: 'facil' },
  { q: '¿Cuál es el factor contribuyente más frecuentemente identificado en la porfiria cutánea tarda esporádica?', options: ['Deficiencia de hierro', 'Exceso de hierro hepático', 'Deficiencia de vitamina B12', 'Hipotiroidismo'], correct: 1, explanation: 'El exceso de hierro hepático inhibe directamente la actividad de la enzima, precipitando la manifestación clínica en la forma esporádica.', dificultad: 'intermedio' },
  { q: '¿Cuál es el tratamiento de primera línea de la porfiria cutánea tarda?', options: ['Hemina intravenosa seriada', 'Afamelanotida subcutánea', 'Flebotomía terapéutica', 'Trasplante hepático programado'], correct: 2, explanation: 'La flebotomía terapéutica seriada, dirigida a reducir el hierro hepático, es el tratamiento de primera línea de la porfiria cutánea tarda.', dificultad: 'facil' },
  { q: '¿Qué distingue a la protoporfiria eritropoyética de las demás porfirias de este tema en cuanto a la edad de inicio?', options: ['Se manifiesta desde la infancia', 'No aparece antes de los 60 años', 'Se diagnostica en el embarazo', 'Se manifiesta en la vejez'], correct: 0, explanation: 'La protoporfiria eritropoyética se manifiesta característicamente desde la infancia, a diferencia de las demás porfirias de este tema.', dificultad: 'intermedio' },
  { q: '¿Qué caracteriza clínicamente a la protoporfiria eritropoyética, distinguiéndola de la porfiria cutánea tarda?', options: ['Ictericia como primer síntoma', 'Se manifiesta solo en varones', 'Requiere hemina intravenosa', 'Dolor cutáneo sin ampollas'], correct: 3, explanation: 'La protoporfiria eritropoyética produce dolor cutáneo agudo desproporcionado a los hallazgos visibles, sin las ampollas francas de la porfiria cutánea tarda.', dificultad: 'intermedio' },
  { q: '¿Qué tipo de luz es la principal responsable del daño cutáneo en la protoporfiria eritropoyética?', options: ['Luz visible, no solo ultravioleta', 'Solo la luz ultravioleta de tipo B', 'La radiación infrarroja térmica', 'El daño no depende de la luz solar'], correct: 0, explanation: 'La luz visible (no solo ultravioleta) es la principal responsable del daño cutáneo en la protoporfiria eritropoyética, por lo que requiere fotoprotección específica.', dificultad: 'dificil' },
  { q: '¿Qué fármaco está aprobado específicamente para aumentar la tolerancia a la luz en la protoporfiria eritropoyética?', options: ['Cloroquina en dosis bajas', 'Afamelanotida subcutánea', 'Givosirán intravenoso', 'Hemina intravenosa'], correct: 1, explanation: 'La afamelanotida está aprobada específicamente para aumentar la tolerancia a la luz en la protoporfiria eritropoyética.', dificultad: 'intermedio' },
  { q: '¿Cuál es el síntoma más frecuente y con frecuencia el primero en aparecer en una crisis porfírica aguda?', options: ['Fiebre alta persistente', 'Erupción cutánea generalizada', 'Dolor abdominal intenso', 'Hemoptisis recurrente'], correct: 2, explanation: 'El dolor abdominal intenso y difuso es el síntoma más frecuente y con frecuencia el primero en aparecer en una crisis porfírica aguda.', dificultad: 'facil' },
  { q: '¿Por qué la crisis porfírica aguda puede confundirse con un abdomen quirúrgico agudo, con el riesgo de una laparotomía innecesaria?', options: ['Cursa con perforación intestinal real', 'El paciente presenta fiebre alta', 'La imagen abdominal sale anormal', 'El dolor imita a un abdomen quirúrgico'], correct: 3, explanation: 'El dolor abdominal intenso de la crisis porfírica puede ser clínicamente indistinguible de una causa quirúrgica sin el estudio bioquímico dirigido (ALA/PBG).', dificultad: 'intermedio' },
  { q: '¿Cuál es el tratamiento específico de elección de la crisis porfírica aguda?', options: ['Hemina intravenosa', 'Antibiótico de amplio espectro', 'Corticoides sistémicos en dosis altas', 'Quimioterapia citotóxica'], correct: 0, explanation: 'La hemina intravenosa es el tratamiento específico de elección de la crisis porfírica aguda.', dificultad: 'facil' },
  { q: '¿Qué terapia de ARN de interferencia está aprobada como profilaxis en pacientes con crisis porfíricas agudas recurrentes frecuentes?', options: ['Eculizumab', 'Rituximab', 'Givosirán', 'Imatinib'], correct: 2, explanation: 'Givosirán, una terapia de ARN de interferencia dirigida a reducir la producción hepática de ALAS1, está aprobado como profilaxis en crisis recurrentes frecuentes.', dificultad: 'intermedio' },
  { q: '¿Qué complicación electrolítica frecuente y de mal pronóstico si es grave puede ocurrir durante una crisis porfírica aguda?', options: ['Hipercalcemia', 'Hiponatremia', 'Hiperpotasemia', 'Hipernatremia'], correct: 1, explanation: 'La hiponatremia es una complicación electrolítica frecuente y de mal pronóstico si es grave durante una crisis porfírica aguda.', dificultad: 'intermedio' },
  { q: '¿Qué tipo de neuropatía produce la crisis porfírica aguda no tratada, distinguiéndola del síndrome de Guillain-Barré?', options: ['Desmielinizante, simétrica y distal', 'Sensitiva pura, sin déficit motor', 'Autoinmune con antigangliósidos', 'Motora axonal, proximal, asimétrica'], correct: 3, explanation: 'La neuropatía de la porfiria es motora axonal, de inicio proximal y con frecuencia asimétrica, a diferencia del Guillain-Barré desmielinizante.', dificultad: 'dificil' },
  { q: '¿Qué estudio permite vigilar el compromiso respiratorio inminente antes de que sea clínicamente evidente en la neuropatía de la crisis porfírica?', options: ['Espirometría seriada con CVF', 'Radiografía de tórax diaria', 'Gasometría arterial al ingreso', 'Electrocardiograma seriado'], correct: 0, explanation: 'La espirometría seriada (capacidad vital forzada) permite vigilar el compromiso respiratorio inminente antes de que sea clínicamente evidente.', dificultad: 'intermedio' },
  { q: '¿Cuál es el riesgo a largo plazo aumentado en la porfiria aguda intermitente de larga evolución, que justifica el cribado periódico con ecografía hepática?', options: ['Cáncer de páncreas exocrino', 'Carcinoma hepatocelular', 'Cáncer de colon distal', 'Cáncer gástrico difuso'], correct: 1, explanation: 'El carcinoma hepatocelular está claramente aumentado en la porfiria aguda intermitente de larga evolución, justificando el cribado periódico.', dificultad: 'intermedio' },
  { q: '¿Qué complicación hepática puede desarrollar un subgrupo de pacientes con protoporfiria eritropoyética?', options: ['Hepatitis autoinmune de novo', 'Colangitis esclerosante primaria', 'Daño hepático por protoporfirina', 'Hígado graso no alcohólico'], correct: 2, explanation: 'Un subgrupo de pacientes con protoporfiria eritropoyética desarrolla daño hepático progresivo por depósito de protoporfirina.', dificultad: 'intermedio' },
  { q: '¿Qué opción terapéutica combinada se considera en la protoporfiria eritropoyética con daño hepático avanzado?', options: ['Diálisis hepática sin trasplante', 'Quimioterapia sistémica intensiva', 'Esplenectomía programada', 'Trasplante hepático y de médula'], correct: 3, explanation: 'El trasplante hepático, en ocasiones combinado con trasplante de médula ósea, se considera en la protoporfiria eritropoyética con daño hepático avanzado, para corregir el defecto de origen eritrocitario.', dificultad: 'dificil' },
  { q: '¿Qué distingue morfológicamente a las lesiones cutáneas de la porfiria cutánea tarda de las de la protoporfiria eritropoyética?', options: ['Ambas producen lesiones idénticas', 'Ampollas frente a dolor sin ampollas', 'La protoporfiria da más ampollas', 'Solo la cutánea tarda da síntomas'], correct: 1, explanation: 'La porfiria cutánea tarda produce ampollas francas de cicatrización lenta; la protoporfiria eritropoyética produce dolor agudo sin ampollas francas en la mayoría de los casos.', dificultad: 'facil' },
  { q: 'Según la herramienta ALA/PBG urinario, ¿qué interpretación corresponde a un PBG elevado (con o sin ALA elevado)?', options: ['Sugestivo de crisis porfírica aguda', 'Descarta cualquier porfiria', 'Confirma protoporfiria eritropoyética', 'Indica intoxicación por plomo'], correct: 0, explanation: 'Un PBG elevado (con o sin ALA elevado) es altamente sugestivo de una crisis porfírica aguda.', dificultad: 'facil' },
  { q: 'Según la herramienta ALA/PBG urinario, ¿qué patrón sugiere considerar deficiencia de ALA-deshidratasa o intoxicación por plomo como diagnóstico diferencial?', options: ['PBG elevado con ALA normal', 'ALA y PBG ambos normales', 'ALA elevado con PBG normal', 'ALA y PBG ambos elevados'], correct: 2, explanation: 'ALA elevado con PBG normal es un patrón atípico que sugiere considerar deficiencia de ALA-deshidratasa o intoxicación por plomo.', dificultad: 'intermedio' },
  { q: '¿Por qué es importante medir ALA y PBG durante el episodio sintomático agudo y no en un momento asintomático?', options: ['Los valores no cambian entre crisis', 'Pueden normalizarse entre crisis', 'El laboratorio solo procesa de día', 'Solo se pueden medir en sangre'], correct: 1, explanation: 'Los valores de ALA y PBG pueden normalizarse entre crisis; un resultado normal en un episodio asintomático no descarta una porfiria hepática aguda latente.', dificultad: 'intermedio' },
  { q: '¿Qué medida general de prevención aplica a TODO paciente con una porfiria hepática aguda diagnosticada?', options: ['No se requiere prevención tras la crisis', 'Evitar la actividad física de por vida', 'Suspender la anticoncepción hormonal', 'Revisar fármacos y evitar el ayuno'], correct: 3, explanation: 'La revisión sistemática de fármacos porfirinogénicos y evitar el ayuno prolongado son medidas preventivas generales para todo paciente con porfiria hepática aguda.', dificultad: 'facil' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 26 años presenta dolor abdominal difuso intenso de 2 días, náusea, y agitación. Refiere haber iniciado un anticonceptivo oral hace 1 semana y estar en ayuno relativo por la náusea. Exploración abdominal sin datos de irritación peritoneal franca pero con dolor difuso importante. Se considera laparotomía exploradora.',
    steps: [
      { q: '¿Qué se debe hacer ANTES de proceder a la laparotomía exploradora dado este cuadro?', options: ['Solicitar ALA y PBG urinarios', 'Proceder directo a la laparotomía', 'Iniciar quimioterapia empírica', 'Dar de alta sin más evaluación'], correct: 0 },
      { q: 'El ALA y el PBG urinarios resultan marcadamente elevados. ¿Cuál es el manejo más apropiado?', options: ['Proceder con la laparotomía igual', 'Hemina urgente y suspender el gatillo', 'Antibiótico de amplio espectro empírico', 'Observación sin tratamiento específico'], correct: 1 },
      { q: '¿Qué gatillos identificables contribuyeron probablemente a esta crisis en esta paciente?', options: ['No hubo gatillo identificable', 'La edad de la paciente', 'El anticonceptivo y el ayuno', 'Un traumatismo abdominal previo'], correct: 2 }
    ],
    explanation: 'Ante dolor abdominal intenso sin irritación peritoneal franca en una mujer joven, debe considerarse el diagnóstico diferencial de crisis porfírica aguda antes de una laparotomía innecesaria. Confirmada la crisis, el manejo es hemina intravenosa urgente y suspensión del anticonceptivo oral. Los gatillos identificables (hormonal, ayuno) explican la precipitación de esta crisis.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 52 años con antecedente de hepatitis C crónica y consumo de alcohol presenta ampollas y fragilidad cutánea en el dorso de las manos tras exposición solar leve. Ferritina sérica marcadamente elevada.',
    steps: [
      { q: '¿Cuál es la sospecha diagnóstica más apropiada?', options: ['Porfiria aguda intermitente', 'Protoporfiria eritropoyética', 'Porfiria cutánea tarda esporádica', 'Penfigoide ampolloso del adulto'], correct: 2 },
      { q: '¿Qué estudio confirma el diagnóstico bioquímico?', options: ['Uroporfirina urinaria elevada', 'ALA y PBG urinarios elevados', 'Protoporfirina eritrocitaria alta', 'Biopsia medular con blastos'], correct: 0 },
      { q: '¿Cuál es el tratamiento de primera línea más apropiado en este paciente?', options: ['Hemina intravenosa indefinida', 'Trasplante hepático inmediato', 'Afamelanotida subcutánea', 'Flebotomía terapéutica seriada'], correct: 3 }
    ],
    explanation: 'El perfil (hepatitis C, alcohol, exceso de hierro) con ampollas fotoinducidas sugiere porfiria cutánea tarda esporádica. Se confirma con uroporfirina/porfirinas de 7 carboxilos elevadas y ALA/PBG normales. El tratamiento de primera línea es la flebotomía terapéutica seriada junto con la corrección de los factores contribuyentes.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Niño de 6 años presenta episodios recurrentes de dolor intenso y quemante en manos y cara tras exposición solar breve, con edema y eritema leve pero sin ampollas visibles. El diagnóstico se ha retrasado por años pese a múltiples consultas.',
    steps: [
      { q: '¿Cuál es la sospecha diagnóstica más apropiada dado este patrón?', options: ['Porfiria cutánea tarda', 'Protoporfiria eritropoyética', 'Porfiria aguda intermitente', 'Urticaria solar idiopática'], correct: 1 },
      { q: '¿Qué estudio confirma esta sospecha?', options: ['ALA y PBG urinarios elevados', 'Uroporfirina urinaria elevada', 'Biopsia cutánea sin bioquímica', 'Protoporfirina eritrocitaria alta'], correct: 3 },
      { q: '¿Cuál es la medida más importante para mejorar la calidad de vida de este paciente?', options: ['Fotoprotección frente a luz visible', 'Evitar el exterior de forma permanente', 'Hemina intravenosa profiláctica', 'Quimioterapia sistémica continua'], correct: 0 }
    ],
    explanation: 'El dolor agudo desproporcionado sin ampollas francas desde la infancia sugiere protoporfiria eritropoyética, confirmada por protoporfirina eritrocitaria marcadamente elevada. La fotoprotección estricta (incluida luz visible) y la afamelanotida son las medidas centrales para mejorar la calidad de vida.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 30 años con porfiria aguda intermitente conocida presenta una nueva crisis con dolor abdominal y agitación, tratada de forma ambulatoria sin hemina. A las 48 horas desarrolla debilidad progresiva en ambas piernas, de inicio proximal.',
    steps: [
      { q: '¿Qué representa esta nueva debilidad motora?', options: ['Complicación neurológica de la crisis', 'Un evento cerebrovascular no relacionado', 'Una neuropatía diabética de novo', 'Un efecto adverso benigno esperado'], correct: 0 },
      { q: '¿Qué estudio debe realizarse de inmediato para vigilar el riesgo de compromiso respiratorio inminente?', options: ['Radiografía de tórax simple', 'Electrocardiograma seriado', 'Espirometría seriada con CVF', 'Ecografía abdominal completa'], correct: 2 },
      { q: '¿Cuál es el manejo más urgente en este momento?', options: ['Observación domiciliaria estrecha', 'Hemina urgente y hospitalización', 'Alta con analgésicos orales pautados', 'Iniciar quimioterapia citotóxica'], correct: 1 }
    ],
    explanation: 'La debilidad motora proximal progresiva tras una crisis no tratada con hemina representa una complicación neurológica. La espirometría seriada vigila el compromiso respiratorio inminente. El manejo urgente es hemina intravenosa y hospitalización con vigilancia estrecha.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 55 años con porfiria aguda intermitente diagnosticada hace 25 años, con múltiples crisis a lo largo de su vida, en seguimiento ambulatorio regular.',
    steps: [
      { q: '¿Qué riesgo a largo plazo justifica un cribado periódico específico en esta paciente?', options: ['Cáncer de mama de novo', 'Cáncer de tiroides papilar', 'Cáncer colorrectal esporádico', 'Carcinoma hepatocelular'], correct: 3 },
      { q: '¿Qué estudio de cribado se recomienda de forma periódica en este contexto?', options: ['Colonoscopia periódica', 'Ecografía hepática con AFP', 'Mamografía anual de tamizaje', 'No hay cribado establecido'], correct: 1 },
      { q: 'Además del cribado, ¿qué otra medida es relevante en el seguimiento a largo plazo de esta paciente con crisis recurrentes?', options: ['Suspender el seguimiento a los 20 años', 'Iniciar quimioterapia profiláctica', 'Considerar givosirán como profilaxis', 'Anticoagulación de rutina'], correct: 2 }
    ],
    explanation: 'La porfiria aguda intermitente de larga evolución tiene riesgo aumentado de carcinoma hepatocelular, justificando cribado periódico con ecografía hepática y alfafetoproteína. En crisis recurrentes frecuentes, debe considerarse givosirán como profilaxis.'
  }
];

export const flashcards = [
  { front: 'Base fisiopatológica común de las porfirias', back: 'Deficiencia parcial de una enzima distinta de la vía de síntesis del hemo; se acumula el sustrato previo al bloqueo.' },
  { front: 'Porfiria más frecuente en general', back: 'Porfiria cutánea tarda.' },
  { front: 'Porfiria hepática aguda más frecuente', back: 'Porfiria aguda intermitente (deficiencia de PBG-desaminasa).' },
  { front: 'Por qué las crisis de PAI ocurren en mujeres jóvenes', back: 'Influencia hormonal, induce ALA-sintasa hepática (fase lútea).' },
  { front: 'PAI vs. coproporfiria hereditaria/porfiria variegata', back: 'PAI: sin manifestaciones cutáneas. Las otras 2: acumulan porfirinas adicionales → manifestaciones cutáneas.' },
  { front: 'Porfiria variegata: población de alta prevalencia', back: 'Población afrikáner de Sudáfrica (efecto fundador).' },
  { front: 'Enzima deficiente en porfiria cutánea tarda', back: 'Uroporfirinógeno descarboxilasa.' },
  { front: 'Factor contribuyente más frecuente en PCT esporádica', back: 'Exceso de hierro hepático.' },
  { front: 'Tratamiento de primera línea de PCT', back: 'Flebotomía terapéutica seriada.' },
  { front: 'Protoporfiria eritropoyética: edad de inicio', back: 'Característicamente desde la infancia.' },
  { front: 'PPE vs. PCT: presentación cutánea', back: 'PPE: dolor agudo desproporcionado, sin ampollas francas. PCT: ampollas francas de cicatrización lenta.' },
  { front: 'Luz relevante en la PPE', back: 'Luz visible (no solo ultravioleta) — requiere fotoprotección específica.' },
  { front: 'Fármaco aprobado para PPE', back: 'Afamelanotida (aumenta tolerancia a la luz).' },
  { front: 'Síntoma más frecuente de crisis porfírica aguda', back: 'Dolor abdominal intenso y difuso.' },
  { front: 'Riesgo diagnóstico de la crisis porfírica', back: 'Puede simular abdomen quirúrgico → laparotomía innecesaria si no se estudia con ALA/PBG.' },
  { front: 'Tratamiento de elección de la crisis porfírica aguda', back: 'Hemina intravenosa.' },
  { front: 'Terapia profiláctica en crisis recurrentes frecuentes', back: 'Givosirán (ARN de interferencia, reduce ALAS1 hepático).' },
  { front: 'Complicación electrolítica de la crisis porfírica', back: 'Hiponatremia (frecuente y de mal pronóstico si es grave).' },
  { front: 'Tipo de neuropatía de la porfiria', back: 'Motora axonal, de inicio proximal, con frecuencia asimétrica (vs. Guillain-Barré desmielinizante distal simétrico).' },
  { front: 'Vigilancia del compromiso respiratorio en neuropatía porfírica', back: 'Espirometría seriada (capacidad vital forzada).' },
  { front: 'Riesgo hepático a largo plazo de PAI', back: 'Carcinoma hepatocelular (cribado periódico con ecografía + alfafetoproteína).' },
  { front: 'Complicación hepática de la PPE', back: 'Daño hepático progresivo por depósito de protoporfirina, puede llegar a falla hepática.' },
  { front: 'Trasplante en PPE con daño hepático avanzado', back: 'Trasplante hepático, en ocasiones combinado con trasplante de médula ósea.' },
  { front: 'Herramienta ALA/PBG: PBG elevado', back: 'Sugestivo de crisis porfírica aguda (con o sin ALA elevado).' },
  { front: 'Herramienta ALA/PBG: ALA elevado sin PBG', back: 'Patrón atípico: considerar deficiencia de ALA-deshidratasa o intoxicación por plomo.' },
  { front: 'Por qué medir ALA/PBG durante el episodio sintomático', back: 'Los valores pueden normalizarse entre crisis; normal en asintomático no descarta porfiria latente.' },
  { front: 'Prevención general en porfiria hepática aguda', back: 'Revisión de fármacos porfirinogénicos antes de prescribir, evitar ayuno prolongado.' }
];
