// topics/abdomen-agudo/study.js: Autoevaluacion de abdomen agudo.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
// Fuentes: Rogers SO Jr, Kirton OC. N Engl J Med 2024;391:60-67; guias de Tokio 2018 de
// colecistitis y colangitis; guia de la AGA de 2018 sobre la pancreatitis aguda.
// 30 sueltas + 6 cascadas de 3 = 48 subpreguntas, 32 tarjetas.

export const quiz = [
  { q:'&#191;Que proporcion de las visitas a urgencias supone el dolor abdominal agudo?', options:['Entre el 1% y el 2%', 'Entre el 20% y el 25%', 'Entre el 5% y el 10%', 'Menos del 0.5%'], correct:2, explanation:'Es uno de los motivos de consulta mas frecuentes: entre el 5% y el 10% de todas las visitas a urgencias.', dificultad:'facil' },
  { q:'&#191;Cuales son los cuatro mecanismos que llevan a cirugia en el abdomen agudo?', options:['Obstruccion, hemorragia, isquemia y perforacion', 'Infeccion, neoplasia, traumatismo y torsion', 'Inflamacion, litiasis, fistula y herniacion', 'Distension, espasmo, reflujo y estenosis'], correct:0, explanation:'Segun la revision, los procesos que llevan a intervencion quirurgica son fundamentalmente la obstruccion, la hemorragia, la isquemia y la perforacion de una viscera.', dificultad:'facil' },
  { q:'&#191;Que dice la revision de 2024 sobre la analgesia antes del diagnostico?', options:['Que debe esperar a la valoracion del cirujano', 'Que solo se admiten antiinflamatorios no opioides', 'Que retrasa el diagnostico de la apendicitis', 'Que se respalda en dosis moderadas desde el inicio'], correct:3, explanation:'Los autores respaldan con firmeza la analgesia en dosis moderadas, incluso antes de la imagen y de la consulta quirurgica: no altera de forma apreciable el diagnostico ni el plan de tratamiento.', dificultad:'facil' },
  { q:'Segun la revision sistematica citada, &#191;que efecto tienen los opioides sobre los errores de manejo?', options:['Duplican las cirugias innecesarias', 'Aumentan la mortalidad a 30 dias', 'Retrasan la cirugia necesaria', 'No aumentan los errores de manejo'], correct:3, explanation:'Pueden modificar algunos hallazgos de la exploracion, pero esos cambios no se tradujeron en un aumento significativo de errores de manejo, definidos como cirugia innecesaria o cirugia necesaria no hecha a tiempo.', dificultad:'intermedio' },
  { q:'&#191;Que se observo en los ensayos con morfina, tramadol o meperidina frente a placebo?', options:['Alivio del dolor con mas perforaciones', 'Menos dolor pero peor exactitud diagnostica', 'Alivio del dolor sin perder exactitud', 'Ningun alivio superior al del placebo'], correct:2, explanation:'En ensayos aleatorizados y doble ciego, estos analgesicos aliviaron el dolor sin interferir con la capacidad de los medicos para evaluar y tratar con exactitud.', dificultad:'intermedio' },
  { q:'&#191;Que disparidad documenta la revision en la analgesia del dolor abdominal?', options:['Los ancianos recibian el doble de opioides', 'Los jovenes recibian menos analgesia que los mayores', 'Las mujeres recibian mas analgesia que los hombres', 'Los pacientes negros recibian menos analgesia'], correct:3, explanation:'Los pacientes negros y de otros grupos desatendidos tenian entre un 22% y un 30% menos probabilidades de recibir analgesia en urgencias que los blancos, reflejo de sesgos y de falsas creencias sobre el dolor.', dificultad:'intermedio' },
  { q:'&#191;Cual es hoy la tecnica de imagen principal en el adulto no gestante con dolor abdominal agudo?', options:['Radiografia simple de abdomen', 'Ecografia abdominal completa', 'Tomografia con contraste', 'Resonancia sin contraste'], correct:2, explanation:'La tomografia de abdomen y pelvis con contraste intravenoso se ha convertido en la tecnica principal: localiza la inflamacion, la perforacion o la isquemia con alto valor predictivo positivo.', dificultad:'facil' },
  { q:'&#191;Cuanta exactitud pierde la tomografia si se hace sin contraste intravenoso?', options:['Cerca de un 30%', 'Menos de un 5%', 'Alrededor de un 70%', 'No pierde exactitud'], correct:0, explanation:'Sin contraste es aproximadamente un 30% menos exacta para el diagnostico y para los hallazgos secundarios relevantes. Retirarlo tiene un coste diagnostico que debe entrar en la decision.', dificultad:'intermedio' },
  { q:'&#191;Que papel tiene el contraste oral en la tomografia del dolor abdominal agudo?', options:['Es imprescindible para ver el intestino', 'Sustituye al contraste intravenoso', 'Solo se omite en el paciente anciano', 'No es un componente estandar'], correct:3, explanation:'El contraste administrado por via oral no es un componente estandar de la tomografia con contraste intravenoso en la evaluacion del dolor abdominal agudo.', dificultad:'intermedio' },
  { q:'&#191;Que se asocia a esperar 2 horas o mas el informe definitivo de la tomografia?', options:['Una mayor exactitud del diagnostico final', 'Ningun efecto sobre el resultado', 'Menos laparotomias en blanco', 'Mas complicaciones sistemicas y muertes'], correct:3, explanation:'Una espera de al menos 2 horas al informe definitivo se asocia a mayor riesgo de complicaciones sistemicas y muerte, por el retraso en la consulta quirurgica y en el control del foco.', dificultad:'intermedio' },
  { q:'En un estudio, &#191;cuanto redujo la tomografia con contraste la tasa de ingresos?', options:['Un 5.2%', 'Un 23.8%', 'Un 48.6%', 'Un 61.0%'], correct:1, explanation:'Aumento la certeza diagnostica del medico, redujo la tasa de ingresos un 23.8% y adelanto las intervenciones quirurgicas.', dificultad:'dificil' },
  { q:'&#191;Cuando conserva utilidad la radiografia simple de abdomen?', options:['Como cribado de toda dolencia abdominal', 'Para graduar la gravedad de la pancreatitis', 'Para descartar la apendicitis en el joven', 'Ante peritonitis franca, para ver aire libre'], correct:3, explanation:'Frente a la tomografia es poco sensible y poco especifica, pero ante signos francos de peritonitis puede identificar rapidamente el aire libre y llevar a una intervencion sin demora.', dificultad:'facil' },
  { q:'&#191;Cual es la prueba de imagen inicial en la embarazada con sospecha de apendicitis?', options:['La ecografia', 'La tomografia', 'La radiografia', 'La gammagrafia'], correct:0, explanation:'La ecografia es la prueba inicial de eleccion en la embarazada con sospecha de apendicitis u otro trastorno pelvico o ginecologico, porque hay que evitar la radiacion ionizante siempre que sea posible.', dificultad:'facil' },
  { q:'&#191;Para que cuadros se prefiere hoy la ecografia en la practica habitual?', options:['La isquemia mesenterica y la perforacion', 'La obstruccion de intestino delgado', 'La patologia biliar aguda y la apendicitis', 'La diverticulitis y la colitis isquemica'], correct:2, explanation:'En la practica moderna se prefiere para el diagnostico de la patologia biliar aguda y de la apendicitis. Su gran limitacion es la dependencia del operador.', dificultad:'intermedio' },
  { q:'&#191;Que proporcion de tomografias no estaban indicadas en un estudio, segun radiologos externos?', options:['El 2%', 'El 20%', 'El 45%', 'El 60%'], correct:1, explanation:'El 20% de las exploraciones no estaban indicadas a juicio de radiologos externos. Y no hay pruebas convincentes de que la mayor exactitud de la tomografia mejore por si sola la estancia, las complicaciones o la mortalidad.', dificultad:'intermedio' },
  { q:'&#191;Por que la tomografia tiene un beneficio particular en el paciente mayor?', options:['Porque tolera mejor el contraste yodado', 'Porque el dolor suele ser mas localizado', 'Porque en el no se puede usar la ecografia', 'Porque su exploracion fisica es poco fiable'], correct:3, explanation:'El mayor puede tener una historia poco fiable, sintomas vagos, alteracion del estado mental, comorbilidades, una exploracion dificil y poca reserva. La tomografia puede detectar aire libre, inflamacion o isquemia y adelantar el control del foco.', dificultad:'intermedio' },
  { q:'&#191;Que tratamiento previo puede enmascarar un abdomen agudo grave?', options:['Las estatinas', 'Los corticoides', 'Los diureticos', 'Los anticoagulantes'], correct:1, explanation:'Los glucocorticoides y otros inmunosupresores atenuan la respuesta inflamatoria, de modo que el peritonismo puede ser poco evidente. Figuran en el diagrama de la revision como factor que favorece el diagnostico perdido.', dificultad:'facil' },
  { q:'&#191;Que se ha asociado de forma constante a menos complicaciones y muertes?', options:['La tomografia de rutina en todos', 'El ayuno estricto hasta el diagnostico', 'La consulta quirurgica precoz', 'La analgesia diferida hasta la cirugia'], correct:2, explanation:'La consulta quirurgica precoz se ha asociado de forma constante a menos complicaciones y muertes, y la consulta con cirujanos presentes en el hospital reduce la mortalidad en los cuadros que requieren cirugia urgente.', dificultad:'facil' },
  { q:'Si los sintomas no encajan con el diagnostico sospechado, &#191;que recomienda la revision?', options:['Repetir la misma tomografia', 'Reevaluar el diagnostico', 'Mantener el diagnostico inicial', 'Esperar 24 horas en observacion'], correct:1, explanation:'Si los sintomas no son congruentes con el diagnostico sospechado, el clinico debe reevaluar y considerar diagnosticos y tratamientos alternativos.', dificultad:'facil' },
  { q:'&#191;Que sesgo describe depender en exceso del primer dato obtenido?', options:['El sesgo de confirmacion', 'El sesgo de disponibilidad', 'El sesgo de atribucion', 'El sesgo de anclaje'], correct:3, explanation:'El anclaje es la tendencia a apoyarse demasiado en la primera informacion, que se convierte en punto de referencia de todos los juicios posteriores, sea o no exacta.', dificultad:'facil' },
  { q:'&#191;Que es el momento diagnostico?', options:['El tiempo hasta el primer analgesico', 'El diagnostico heredado sin revisar', 'La hora en que se pide la tomografia', 'El retraso hasta la consulta quirurgica'], correct:1, explanation:'Es la inercia de un diagnostico de presuncion, por ejemplo el de la ambulancia, que llega a urgencias y se busca confirmar sin considerar otras posibilidades. La historia clinica electronica lo favorece.', dificultad:'intermedio' },
  { q:'&#191;Que ejemplo usa la revision para ilustrar el sesgo de basarse en un unico dato?', options:['Leucocitosis atribuida a una apendicitis', 'Dolor en fosa iliaca derecha en una mujer', 'Amilasa elevada en un bebedor', 'Ictericia en un paciente con cirrosis'], correct:2, explanation:'Una amilasa elevada en un paciente con consumo de alcohol lleva a diagnosticar pancreatitis, pero una perforacion de intestino delgado tambien puede elevarla.', dificultad:'intermedio' },
  { q:'Entre las estrategias de Croskerry, &#191;cual es la de seguridad?', options:['El reconocimiento de patrones', 'El uso de heuristicas propias', 'El metodo hipotetico-deductivo', 'Descartar el peor escenario'], correct:3, explanation:'Descartar el peor escenario es la estrategia de seguridad, la que yerra del lado de la prudencia. El reconocimiento de patrones es rapido pero alimenta el anclaje.', dificultad:'intermedio' },
  { q:'Segun Tokio 2018, &#191;que define el diagnostico de sospecha de colecistitis?', options:['Un signo local y uno sistemico', 'Un signo local e imagen tipica', 'Dos signos sistemicos', 'La triada de Charcot'], correct:0, explanation:'Sospecha: un signo local (Murphy; masa, dolor o defensa en hipocondrio derecho) mas uno sistemico (fiebre, proteina C reactiva o leucocitos elevados). Definitivo: ademas, imagen caracteristica.', dificultad:'facil' },
  { q:'&#191;Que sensibilidad tuvo el signo de Murphy en la validacion de los criterios?', options:['Del 20.5%', 'Del 54.0%', 'Del 87.5%', 'Del 95.1%'], correct:0, explanation:'Sensibilidad del 20.5% y especificidad del 87.5%. Es especifico pero poco sensible: su ausencia no descarta la colecistitis.', dificultad:'dificil' },
  { q:'&#191;Que define el grado III de una colecistitis o una colangitis en Tokio?', options:['La presencia de litiasis en el coledoco', 'Una evolucion de mas de una semana', 'Una bilirrubina por encima de 10 mg/dL', 'La disfuncion de algun organo o sistema'], correct:3, explanation:'El grado III se define por disfuncion de cualquier organo: cardiovascular, neurologica, respiratoria (PaO2/FiO2 menor de 300), renal (creatinina mayor de 2), hepatica (INR mayor de 1.5) o hematologica (plaquetas menores de 100.000).', dificultad:'intermedio' },
  { q:'&#191;Por que Tokio excluyo el dolor abdominal de los criterios de colangitis?', options:['Porque es un dato demasiado subjetivo', 'Porque falta en la mayoria de los casos', 'Por confundirla con la colecistitis', 'Porque no se asociaba a la mortalidad'], correct:2, explanation:'Con el dolor incluido, la sensibilidad era del 95.1% pero la especificidad caia al 66.3% por un 38.8% de falsos positivos de colecistitis. Sin el, la sensibilidad fue del 91.8% y la especificidad del 77.7%.', dificultad:'dificil' },
  { q:'En la pancreatitis aguda, &#191;que recomienda la AGA sobre la alimentacion?', options:['Ayuno hasta normalizar la lipasa', 'Nutricion parenteral de entrada', 'Dieta oral precoz segun tolerancia', 'Sonda nasoyeyunal en todos'], correct:2, explanation:'La AGA recomienda la alimentacion oral precoz, en las primeras 24 horas, segun tolerancia, mejor que mantener el ayuno; y la nutricion enteral mejor que la parenteral si no puede comer.', dificultad:'intermedio' },
  { q:'&#191;Que sugiere la AGA sobre los antibioticos profilacticos en la pancreatitis grave prevista o necrotizante?', options:['Darlos durante catorce dias', 'Darlos solo si hay necrosis', 'Darlos si la proteina C reactiva sube', 'No darlos de forma profilactica'], correct:3, explanation:'La AGA sugiere no usar antibioticos profilacticos en la pancreatitis grave prevista ni en la necrotizante.', dificultad:'intermedio' },
  { q:'En la pancreatitis biliar, &#191;cuando recomienda la AGA la colecistectomia?', options:['A los tres meses del alta', 'Durante el mismo ingreso', 'Solo si hay un segundo episodio', 'Tras una colangiografia retrograda'], correct:1, explanation:'Recomienda la colecistectomia durante el ingreso inicial y no despues del alta. Y sugiere no hacer colangiografia retrograda urgente de rutina si no hay colangitis.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 34 a&#241;os con dolor en fosa iliaca derecha de 12 horas y fiebre de 38. Pide algo para el dolor. El residente de urgencias prefiere no darle nada hasta que lo vea el cirujano, que tardara en bajar.', steps:[
    { q:'&#191;Que conducta respalda la revision de 2024?', options:['Esperar al cirujano para no enmascarar', 'Dar solo un antiespasmodico suave', 'Analgesia en dosis moderadas ya', 'Analgesia solo tras la tomografia'], correct:2 },
    { q:'&#191;Que imagen es razonable pedir primero en este joven?', options:['Radiografia simple de abdomen', 'Ecografia abdominal', 'Resonancia magnetica', 'Gammagrafia con leucocitos'], correct:1 },
    { q:'Si la ecografia no es concluyente, &#191;que procede?', options:['Tomografia con contraste', 'Tomografia sin ningun contraste', 'Repetir la ecografia en 24 horas', 'Dar el alta con analgesia'], correct:0 }
  ], explanation:'La analgesia en dosis moderadas se respalda desde el inicio: no altera de forma apreciable el diagnostico ni el plan. En la practica actual la ecografia es preferida para la apendicitis, y si no aclara, la tecnica principal en el adulto no gestante es la tomografia con contraste intravenoso, que sin contraste pierde en torno a un 30% de exactitud.', dificultad:'facil' },

  { type:'cascade', vignette:'Mujer de 82 a&#241;os en tratamiento cronico con prednisona por una polimialgia. La traen por confusion de un dia de evolucion. Refiere molestias abdominales vagas. El abdomen esta blando y apenas doloroso. Temperatura de 37.4 y leucocitos de 9.800.', steps:[
    { q:'&#191;Que valor tiene la exploracion abdominal anodina?', options:['Descarta un proceso quirurgico', 'Es poco fiable en esta paciente', 'Confirma que la causa es extraabdominal', 'Indica una evolucion favorable'], correct:1 },
    { q:'&#191;Que imagen procede?', options:['Tomografia con contraste', 'Radiografia simple en bipedestacion', 'Ecografia y alta si es normal', 'Solo observacion 24 horas'], correct:0 },
    { q:'La tomografia muestra aire libre. &#191;Que corresponde?', options:['Repetir la tomografia en 12 horas', 'Antibiotico y alta precoz', 'Esperar a que mejore la confusion', 'Consulta quirurgica inmediata'], correct:3 }
  ], explanation:'Edad avanzada, alteracion del estado mental y glucocorticoides: los tres factores del diagrama de la revision que hacen poco fiable la exploracion. La tomografia con contraste tiene aqui un beneficio particular, y el aire libre obliga a la consulta quirurgica inmediata y al control del foco.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 51 a&#241;os con consumo diario de alcohol que consulta por dolor abdominal intenso de inicio brusco hace 4 horas. La amilasa esta elevada. El medico que lo recibe anota pancreatitis aguda y pide fluidos. El abdomen esta rigido.', steps:[
    { q:'&#191;Que riesgo cognitivo hay en este razonamiento?', options:['Sesgo de disponibilidad', 'Basarse en un solo dato', 'Exceso de pruebas', 'Efecto de encuadre'], correct:1 },
    { q:'&#191;Que otra causa puede elevar la amilasa con este cuadro?', options:['Un colico renal izquierdo', 'Una perforacion intestinal', 'Una gastritis erosiva aguda', 'Una cetoacidosis alcoholica'], correct:1 },
    { q:'&#191;Que conducta corrige el error?', options:['Repetir la amilasa en 6 horas', 'Pedir lipasa y esperar', 'Tomografia y cirujano pronto', 'Observacion con fluidos'], correct:2 }
  ], explanation:'Es el ejemplo de la revision: una amilasa elevada en un paciente con consumo de alcohol lleva a la pancreatitis, pero una perforacion de intestino delgado tambien la eleva. Un abdomen rigido no encaja con el diagnostico de trabajo, y si los sintomas no son congruentes hay que reevaluar: tomografia y consulta quirurgica pronto.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Mujer de 58 a&#241;os con dolor en hipocondrio derecho desde hace 4 dias, fiebre de 38.3 y leucocitos de 19.500. No presenta signo de Murphy, pero hay defensa en hipocondrio derecho. La ecografia muestra pared vesicular engrosada con liquido perivesicular. Tension normal, conciencia normal, creatinina, INR y plaquetas normales.', steps:[
    { q:'&#191;Que diagnostico corresponde segun Tokio?', options:['Sospecha de colecistitis', 'Colecistitis definitiva', 'No cumple criterios', 'Colangitis definitiva'], correct:1 },
    { q:'&#191;Que grado de gravedad tiene?', options:['Grado I, leve', 'Grado III, grave', 'No se puede graduar', 'Grado II, moderado'], correct:3 },
    { q:'&#191;Que valor tiene que falte el signo de Murphy?', options:['Ninguno, es poco sensible', 'Descarta la colecistitis', 'Obliga a repetir la ecografia', 'Rebaja el grado de gravedad'], correct:0 }
  ], explanation:'Signo local (defensa en hipocondrio derecho), signos sistemicos (fiebre y leucocitosis) e imagen caracteristica: colecistitis definitiva. Sin disfuncion de organo no es grado III, pero tiene criterios de grado II: leucocitos por encima de 18.000 y mas de 72 horas de evolucion. El signo de Murphy tuvo una sensibilidad del 20.5%: que falte no descarta nada.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 79 a&#241;os con litiasis biliar conocida. Presenta escalofrios, temperatura de 39.2, ictericia y bilirrubina de 6.1 mg/dL. La ecografia muestra dilatacion de la via biliar. No tiene dolor abdominal. Tension, conciencia, creatinina, INR y plaquetas normales.', steps:[
    { q:'&#191;Descarta la colangitis la falta de dolor?', options:['Si, la triada exige el dolor', 'No, Tokio no exige el dolor', 'Si, salvo en mayores de 80', 'No, pero obliga a una resonancia'], correct:1 },
    { q:'&#191;Que diagnostico corresponde?', options:['Sospecha de colangitis', 'Colecistitis definitiva', 'No cumple criterios', 'Colangitis definitiva'], correct:3 },
    { q:'&#191;Que grado tiene?', options:['Grado II, moderado', 'Grado I, leve', 'Grado III, grave', 'Sin grado asignable'], correct:0 }
  ], explanation:'Tokio 2018 no incluye el dolor en los criterios: inflamacion sistemica (fiebre y escalofrios), colestasis (ictericia) e imagen (dilatacion biliar) dan una colangitis definitiva. Sin disfuncion de organo no es grado III, y reune mas de dos criterios de grado II: fiebre de 39 o mas, edad de 75 o mas y bilirrubina de 5 o mas. En todos los grados, antibiotico y drenaje biliar si no responde.', dificultad:'dificil' },

  { type:'cascade', vignette:'Mujer de 45 a&#241;os ingresada por una pancreatitis aguda de origen biliar, sin colangitis. Tolera agua a las 12 horas del ingreso. El equipo discute si mantenerla en ayuno, si pautar antibiotico profilactico y si programar la colangiografia retrograda urgente.', steps:[
    { q:'&#191;Que pauta de alimentacion recomienda la AGA?', options:['Ayuno hasta que baje la lipasa', 'Dieta oral precoz si la tolera', 'Nutricion parenteral total', 'Sonda nasoyeyunal desde el ingreso'], correct:1 },
    { q:'&#191;Y sobre la colangiografia retrograda urgente?', options:['Hacerla en las primeras 24 horas', 'Hacerla si la amilasa sigue alta', 'No hacerla de rutina sin colangitis', 'Sustituirla por drenaje percutaneo'], correct:2 },
    { q:'&#191;Cuando se hace la colecistectomia?', options:['En el mismo ingreso', 'A las seis semanas', 'Solo si recurre', 'Tras un a&#241;o sin dolor'], correct:0 }
  ], explanation:'La AGA recomienda la alimentacion oral precoz, en las primeras 24 horas, segun tolerancia, mejor que el ayuno. Sugiere no hacer colangiografia retrograda urgente de rutina en la pancreatitis biliar sin colangitis, ni antibiotico profilactico en la grave prevista o necrotizante. Y recomienda la colecistectomia durante el ingreso inicial.', dificultad:'intermedio' }
];

export const flashcards = [
  { front:'Peso del dolor abdominal en urgencias', back:'Entre el 5% y el 10% de todas las visitas a urgencias.' },
  { front:'Los cuatro mecanismos quirurgicos', back:'Obstruccion, hemorragia, isquemia y perforacion.' },
  { front:'Cope, 1921', back:'Escribio su tratado del diagnostico precoz del abdomen agudo por el retraso que sufrian los pacientes. Historia y exploracion como primer paso.' },
  { front:'Analgesia antes del diagnostico', back:'Se respalda en dosis moderadas, incluso antes de la imagen y del cirujano. No altera de forma apreciable el diagnostico ni el plan.' },
  { front:'Opioides y errores de manejo', back:'Pueden cambiar algun hallazgo, pero no aumentan las cirugias innecesarias ni las necesarias no hechas a tiempo.' },
  { front:'Disparidad en la analgesia', back:'Los pacientes negros y de otros grupos desatendidos recibian entre un 22% y un 30% menos analgesia en urgencias.' },
  { front:'Tecnica de imagen principal', back:'Tomografia de abdomen y pelvis con contraste INTRAVENOSO en el adulto no gestante.' },
  { front:'Tomografia sin contraste', back:'Aproximadamente un 30% menos exacta. Retirar el contraste tiene un coste diagnostico.' },
  { front:'Contraste oral', back:'No es un componente estandar de la tomografia del dolor abdominal agudo.' },
  { front:'Esperar el informe de la tomografia', back:'Esperar 2 horas o mas se asocia a mas complicaciones sistemicas y muertes. Llamar al cirujano en paralelo.' },
  { front:'Radiografia simple de abdomen', back:'Poco sensible y especifica. Util ante peritonitis franca para ver aire libre rapido.' },
  { front:'Ecografia', back:'Preferida para patologia biliar y apendicitis, y primera prueba en la embarazada. Muy dependiente del operador.' },
  { front:'Sobreuso de la tomografia', back:'En un estudio, el 20% no estaban indicadas. Sin pruebas de que la mayor exactitud mejore por si sola el resultado.' },
  { front:'Paciente mayor', back:'Historia poco fiable, sintomas vagos, alteracion mental, exploracion dificil y poca reserva. Umbral bajo para tomografia y cirujano.' },
  { front:'Glucocorticoides e inmunosupresores', back:'Atenuan la respuesta inflamatoria y enmascaran el peritonismo.' },
  { front:'Consulta quirurgica precoz', back:'Asociada de forma constante a menos complicaciones y muertes. Cirujanos presentes en el hospital reducen la mortalidad.' },
  { front:'Sintomas que no encajan', back:'Reevaluar y considerar diagnosticos alternativos.' },
  { front:'Sesgo de anclaje', back:'Apoyarse en exceso en el primer dato, que se convierte en referencia de todo lo demas.' },
  { front:'Sesgo de confirmacion', back:'Buscar solo los datos que apoyan la hipotesis favorita.' },
  { front:'Momento diagnostico', back:'El diagnostico de presuncion llega a urgencias y nadie lo discute. La historia electronica lo favorece.' },
  { front:'El ejemplo de la amilasa', back:'Amilasa alta en un bebedor lleva a pancreatitis, pero una perforacion de intestino delgado tambien la eleva.' },
  { front:'Estrategia de seguridad de Croskerry', back:'Descartar el peor escenario: errar del lado de la prudencia.' },
  { front:'Tokio: colecistitis', back:'Sospecha: signo local + sistemico. Definitivo: ademas imagen caracteristica.' },
  { front:'Tokio: colangitis', back:'Sospecha: inflamacion sistemica + colestasis o imagen. Definitivo: los tres.' },
  { front:'Grado III en Tokio', back:'Disfuncion de organo: hipotension con vasopresor, alteracion de conciencia, PaO2/FiO2 menor de 300, creatinina mayor de 2, INR mayor de 1.5, plaquetas menores de 100.000.' },
  { front:'Grado II de colecistitis', back:'Uno de: leucocitos mayores de 18.000, masa dolorosa, mas de 72 h, inflamacion local marcada.' },
  { front:'Grado II de colangitis', back:'Dos de: leucocitos mayores de 12.000 o menores de 4.000, fiebre de 39 o mas, edad de 75 o mas, bilirrubina de 5 o mas, hipoalbuminemia.' },
  { front:'Signo de Murphy', back:'Sensibilidad del 20.5% y especificidad del 87.5%. Su ausencia no descarta la colecistitis.' },
  { front:'Triada de Charcot', back:'Muy especifica, pero solo presente en el 21% al 26% de las colangitis en series recientes.' },
  { front:'Pancreatitis: alimentacion (AGA)', back:'Oral precoz en las primeras 24 h segun tolerancia. Enteral mejor que parenteral si no puede comer.' },
  { front:'Pancreatitis: antibioticos (AGA)', back:'Sin antibiotico profilactico en la grave prevista ni en la necrotizante.' },
  { front:'Pancreatitis biliar (AGA)', back:'Sin colangiografia retrograda urgente de rutina si no hay colangitis. Colecistectomia en el mismo ingreso.' }
];

export default { quiz, flashcards };
