// topics/anemia-ferropenica/study.js: Autoevaluación de Anemia Ferropénica.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Índices `correct` de las 30 preguntas sueltas, en orden: 1,3,0,2,1,3,0,2,3,1,0,2,3,0,1,2,0,3,1,
// 2,3,0,2,1,0,3,2,1,0,3. Recuento: 0×8, 1×7, 2×7, 3×8. Sin racha >2 ni ciclo fijo.
// Índices `correct` de los pasos de las 5 preguntas en cascada (3 pasos c/u), en orden: 2,0,3 /
// 1,2,0 / 3,1,2 / 0,3,1 / 1,3,2. Recuento: 0×3, 1×4, 2×4, 3×4.

export const quiz = [
  { q: '¿Cuál es el marcador de laboratorio más sensible y específico de depósitos de hierro agotados?', options: ['Hemoglobina', 'Ferritina sérica', 'VCM', 'Hierro sérico'], correct: 1, explanation: 'La ferritina sérica es el marcador más sensible y específico de depósitos de hierro agotados, aunque puede estar falsamente normal/elevada como reactante de fase aguda en presencia de inflamación.', dificultad: 'facil' },
  { q: '¿Cuál es la causa más frecuente de anemia ferropénica en el varón adulto y en la mujer posmenopáusica?', options: ['Dieta insuficiente en hierro', 'Enfermedad celíaca', 'Aumento de la demanda', 'Pérdida crónica de sangre digestiva'], correct: 3, explanation: 'La pérdida crónica de sangre digestiva es la causa más frecuente de anemia ferropénica en el varón adulto y en la mujer posmenopáusica, con riesgo de neoplasia gastrointestinal oculta.', dificultad: 'facil' },
  { q: '¿Por qué la ferritina puede ser engañosa en un paciente con inflamación concurrente?', options: ['Es un reactante de fase aguda que puede estar falsamente normal o elevada pese a depósitos de hierro realmente bajos', 'Porque disminuye artificialmente con la inflamación', 'Porque no se relaciona en absoluto con los depósitos de hierro', 'Porque solo se altera en el embarazo'], correct: 0, explanation: 'La ferritina es un reactante de fase aguda; la inflamación puede elevarla artificialmente incluso cuando los depósitos de hierro están realmente bajos.', dificultad: 'intermedio' },
  { q: '¿Qué estudio es de primera línea en un varón adulto con anemia ferropénica sin causa evidente?', options: ['Biopsia de médula ósea', 'Serología viral', 'Endoscopia digestiva alta y colonoscopia', 'Resonancia magnética abdominal'], correct: 2, explanation: 'La endoscopia digestiva alta y la colonoscopia son el estudio de primera línea para descartar una fuente de pérdida digestiva oculta, incluida neoplasia.', dificultad: 'facil' },
  { q: '¿Qué mide el índice de Mentzer?', options: ['El déficit total de hierro corporal', 'La relación VCM/recuento de eritrocitos para distinguir ferropenia de rasgo talasémico', 'La saturación de transferrina', 'El tiempo de respuesta al hierro oral'], correct: 1, explanation: 'El índice de Mentzer (VCM/recuento de eritrocitos) ayuda a distinguir la ferropenia del rasgo talasémico en la anemia microcítica leve.', dificultad: 'intermedio' },
  { q: 'Según el índice de Mentzer, ¿qué valor sugiere anemia ferropénica en vez de rasgo talasémico?', options: ['&lt;10', '&lt;13 exactamente', 'Cualquier valor por debajo de 5', '≥13'], correct: 3, explanation: 'Un índice de Mentzer ≥13 es sugestivo de anemia ferropénica, mientras que &lt;13 sugiere rasgo talasémico.', dificultad: 'intermedio' },
  { q: '¿Qué calcula la fórmula de Ganzoni?', options: ['El déficit total de hierro corporal, para dosificar hierro intravenoso', 'El índice de producción reticulocitaria', 'El riesgo de recaída de la ferropenia', 'La probabilidad de rasgo talasémico'], correct: 0, explanation: 'La fórmula de Ganzoni estima el déficit total de hierro corporal, usado para calcular la dosis de reposición de hierro intravenoso.', dificultad: 'intermedio' },
  { q: '¿Cuál es la fórmula de Ganzoni?', options: ['Reticulocitos × hematocrito', 'VCM / eritrocitos', 'Peso (kg) × (Hb objetivo − Hb actual) × 2.4 + depósito', 'Hemoglobina × 2.4'], correct: 2, explanation: 'La fórmula de Ganzoni es: peso (kg) × (hemoglobina objetivo − hemoglobina actual, g/dL) × 2.4 + depósito de hierro a reponer (habitualmente 500 mg en el adulto).', dificultad: 'facil' },
  { q: '¿Cuál es la causa más frecuente de anemia ferropénica en la mujer en edad reproductiva?', options: ['Enfermedad celíaca', 'Cirugía bariátrica previa', 'Deficiencia de vitamina B12 concomitante', 'Menorragia'], correct: 3, explanation: 'La menorragia (sangrado menstrual abundante) es la causa más frecuente de anemia ferropénica en la mujer en edad reproductiva.', dificultad: 'facil' },
  { q: '¿Por qué la enfermedad celíaca debe investigarse de rutina en el estudio etiológico de la ferropenia, incluso sin síntomas digestivos evidentes?', options: ['Porque siempre causa diarrea grave', 'Porque puede debutar únicamente con ferropenia, sin síntomas digestivos floridos', 'Porque es la causa más frecuente en cualquier paciente', 'Porque descarta automáticamente una causa digestiva de sangrado'], correct: 1, explanation: 'La enfermedad celíaca puede debutar únicamente con ferropenia, sin síntomas digestivos evidentes, por lo que se investiga de rutina en el estudio etiológico.', dificultad: 'intermedio' },
  { q: '¿Qué sitio anatómico es el principal responsable de la absorción de hierro dietético?', options: ['Duodeno y yeyuno proximal', 'Íleon terminal', 'Colon ascendente', 'Estómago'], correct: 0, explanation: 'El hierro dietético se absorbe predominantemente en el duodeno y el yeyuno proximal.', dificultad: 'facil' },
  { q: '¿Por qué la cirugía bariátrica con bypass gástrico en Y de Roux predispone a ferropenia?', options: ['Porque aumenta el apetito por alimentos ricos en hierro', 'Porque produce sangrado digestivo crónico en la mayoría de los casos', 'Porque la reconstrucción excluye el duodeno, el sitio principal de absorción de hierro', 'Porque reduce la producción de eritropoyetina'], correct: 2, explanation: 'El bypass gástrico en Y de Roux excluye el duodeno, el sitio anatómico principal de absorción del hierro dietético.', dificultad: 'intermedio' },
  { q: '¿Qué caracteriza a la ferropenia refractaria genética verdadera (IRIDA)?', options: ['Mutación somática de PIGA', 'Deficiencia hereditaria de la enzima G6PD', 'Buena respuesta al hierro oral desde el diagnóstico', 'Mutación bialélica de TMPRSS6, con hepcidina inapropiadamente elevada'], correct: 3, explanation: 'La IRIDA es producida por una mutación bialélica de TMPRSS6, que impide la supresión fisiológica de la hepcidina.', dificultad: 'intermedio' },
  { q: '¿Cuál es el mecanismo por el que la mutación de TMPRSS6 produce ferropenia refractaria?', options: ['Impide la supresión fisiológica de la hepcidina, bloqueando la absorción intestinal y la liberación de hierro de los depósitos', 'Produce hemólisis crónica que consume el hierro disponible', 'Bloquea directamente la síntesis de hemoglobina sin afectar el metabolismo del hierro', 'Aumenta la excreción renal de hierro'], correct: 0, explanation: 'La mutación de TMPRSS6 impide la supresión fisiológica de la hepcidina, que normalmente permite mayor absorción intestinal y liberación de hierro de los depósitos en la ferropenia.', dificultad: 'dificil' },
  { q: '¿Cuál es la estrategia de dosificación de hierro oral que mejora tanto la tolerancia como la absorción fraccional total?', options: ['Dosis única muy alta una vez por semana', 'Dosificación en días alternos en vez de diaria', 'Dosis diaria fraccionada en 4 tomas', 'Tomar el hierro siempre junto con calcio'], correct: 1, explanation: 'La dosificación en días alternos mejora tanto la tolerancia gastrointestinal como la absorción fraccional total, al evitar el pico de hepcidina inducido por cada dosis diaria.', dificultad: 'intermedio' },
  { q: '¿Cuál es la primera línea de tratamiento en la malabsorción estructural establecida (por ejemplo, enfermedad celíaca activa o poscirugía bariátrica)?', options: ['Hierro oral en dosis altas', 'Transfusión profiláctica', 'Hierro intravenoso', 'Vigilancia sin tratamiento'], correct: 2, explanation: 'El hierro intravenoso es primera línea (no de rescate) en la malabsorción estructural establecida, dado que el hierro oral tiene eficacia limitada en ese contexto.', dificultad: 'facil' },
  { q: '¿Cuál es el punto de corte de hemoglobina para diagnosticar anemia en el segundo trimestre del embarazo?', options: ['&lt;10.5 g/dL', '&lt;13 g/dL', '&lt;8 g/dL', '&lt;12 g/dL'], correct: 0, explanation: 'El punto de corte de anemia en el segundo trimestre es &lt;10.5 g/dL, por la hemodilución fisiológica máxima en ese periodo.', dificultad: 'intermedio' },
  { q: '¿Cuál es la causa más frecuente de anemia en el embarazo?', options: ['Anemia de la enfermedad crónica', 'Anemia megaloblástica por deficiencia de B12', 'Anemia hemolítica autoinmune', 'Ferropenia'], correct: 3, explanation: 'La ferropenia es la causa más frecuente de anemia en el embarazo.', dificultad: 'facil' },
  { q: '¿Por qué se recomienda la suplementación universal de hierro oral durante el embarazo?', options: ['Solo si la hemoglobina ya está baja al inicio del embarazo', 'Independientemente de la hemoglobina basal, dado el aumento fisiológico y predecible de la demanda', 'Solo en el tercer trimestre', 'Únicamente si hay antecedente de anemia previa'], correct: 1, explanation: 'La suplementación universal se recomienda independientemente de la hemoglobina basal, dado el aumento fisiológico y predecible de la demanda de hierro durante el embarazo.', dificultad: 'intermedio' },
  { q: '¿Cuál es la tríada del síndrome de Plummer-Vinson?', options: ['Ictericia, fiebre, esplenomegalia', 'Disnea, edema, taquicardia', 'Disfagia, membranas esofágicas, anemia ferropénica', 'Pica, alopecia, coiloniquia'], correct: 2, explanation: 'La tríada del síndrome de Plummer-Vinson (o Paterson-Kelly-Brown) es disfagia, membranas esofágicas y anemia ferropénica.', dificultad: 'dificil' },
  { q: '¿Cuál es el tratamiento de primera línea del síndrome de Plummer-Vinson?', options: ['Dilatación endoscópica inmediata sin tratar la ferropenia', 'Cirugía esofágica de entrada', 'Radioterapia local', 'Reposición agresiva de hierro (con frecuencia intravenosa)'], correct: 3, explanation: 'La reposición agresiva de hierro, con frecuencia intravenosa, es la primera línea; la disfagia mejora en una proporción relevante de los casos solo con la corrección de la ferropenia.', dificultad: 'intermedio' },
  { q: '¿Por qué la insuficiencia cardiaca de alto gasto en la anemia ferropénica grave NO refleja una falla primaria de la bomba cardiaca?', options: ['Porque el problema es una demanda circulatoria excesiva y sostenida por la anemia, no una disfunción intrínseca inicial del miocardio', 'Porque siempre coexiste con una valvulopatía estructural', 'Porque el gasto cardiaco está reducido, no aumentado', 'Porque nunca hay taquicardia asociada'], correct: 0, explanation: 'El problema primario es una demanda circulatoria excesiva y sostenida por la anemia (gasto cardiaco elevado), no una falla intrínseca inicial de la bomba cardiaca.', dificultad: 'intermedio' },
  { q: '¿Cuál es la medida terapéutica central en la insuficiencia cardiaca de alto gasto por anemia ferropénica grave?', options: ['Betabloqueador en dosis altas', 'Cardioversión eléctrica', 'Corrección de la anemia de base', 'Anticoagulación indefinida'], correct: 2, explanation: 'La corrección de la anemia de base es la medida terapéutica central y más eficaz en la insuficiencia cardiaca de alto gasto por anemia.', dificultad: 'facil' },
  { q: '¿Qué hallazgo en las heces es esperado y benigno tras iniciar hierro oral?', options: ['Hematoquecia franca', 'Heces oscuras por el hierro no absorbido', 'Esteatorrea', 'Heces con moco abundante'], correct: 1, explanation: 'Las heces oscuras por el hierro no absorbido son un hallazgo esperado y benigno que debe anticiparse al paciente.', dificultad: 'facil' },
  { q: '¿Por qué los síntomas gastrointestinales del hierro oral son más frecuentes con la dosificación diaria que con días alternos?', options: ['Porque la dosis diaria mantiene una exposición luminal de hierro no absorbido más constante', 'Porque el hierro en días alternos se absorbe menos y por eso irrita menos', 'Porque la dosificación diaria siempre usa una sal de hierro distinta', 'No hay diferencia real entre ambos esquemas'], correct: 0, explanation: 'La dosis diaria mantiene una exposición luminal de hierro no absorbido más constante, lo que produce más síntomas gastrointestinales que el esquema en días alternos.', dificultad: 'intermedio' },
  { q: '¿Cuál es el mecanismo predominante de las reacciones de hipersensibilidad al hierro intravenoso con las formulaciones modernas?', options: ['Anafilaxia mediada por IgE clásica en la gran mayoría de los casos', 'Reacción tóxica directa sobre el miocardio', 'Vasoespasmo coronario primario', 'Reacciones de activación del complemento asociadas a la infusión (pseudoalergia), en su mayoría'], correct: 3, explanation: 'La mayoría de las reacciones son de activación del complemento asociadas a la infusión (pseudoalergia), no anafilaxia mediada por IgE clásica.', dificultad: 'dificil' },
  { q: '¿Cuál es el mecanismo de la hipofosfatemia inducida por carboximaltosa férrica?', options: ['Depósito directo de hierro en el hueso', 'Inhibición de la hormona paratiroidea', 'Aumento marcado e inapropiado del FGF23, que incrementa la excreción renal de fosfato', 'Consumo de fosfato por la eritropoyesis acelerada'], correct: 2, explanation: 'La carboximaltosa férrica induce un aumento marcado e inapropiado del FGF23, que incrementa la excreción renal de fosfato.', dificultad: 'dificil' },
  { q: '¿Cuál es el tratamiento de primera línea de la anafilaxia verdadera por hierro intravenoso?', options: ['Corticoide oral ambulatorio', 'Epinefrina intramuscular', 'Antihistamínico oral únicamente', 'Suspender sin ningún tratamiento adicional'], correct: 1, explanation: 'La epinefrina intramuscular es el tratamiento de primera línea de la anafilaxia verdadera, igual que en cualquier otra causa.', dificultad: 'facil' },
  { q: '¿En qué formulaciones de hierro IV es más frecuente la hipofosfatemia significativa?', options: ['Carboximaltosa férrica en dosis altas repetidas', 'Hierro sacarosa en dosis única baja', 'Sulfato ferroso oral', 'Ninguna formulación de hierro IV la produce'], correct: 0, explanation: 'La hipofosfatemia significativa es más frecuente con dosis altas repetidas de carboximaltosa férrica.', dificultad: 'intermedio' },
  { q: '¿Qué manifestación extrahematológica de la ferropenia consiste en el deseo de consumir sustancias no nutritivas como hielo, tierra o almidón?', options: ['Coiloniquia', 'Síndrome de piernas inquietas', 'Glositis atrófica', 'Pica'], correct: 3, explanation: 'La pica (con frecuencia pagofagia, deseo de comer hielo) es una manifestación extrahematológica reconocida de la ferropenia.', dificultad: 'facil' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 68 años sin antecedentes relevantes presenta fatiga progresiva de 2 meses. Hb 9.2 g/dL, VCM 68 fL, ferritina 8 ng/mL, saturación de transferrina 6%. Niega sangrado digestivo evidente.',
    steps: [
      { q: '¿Cuál es el paso diagnóstico más apropiado a seguir?', options: ['Iniciar hierro oral empírico sin más estudio', 'Repetir la biometría hemática en 3 meses', 'Endoscopia digestiva alta y colonoscopia', 'Transfusión profiláctica'], correct: 2 },
      { q: 'La colonoscopia identifica una lesión sospechosa en el colon ascendente. ¿Cuál es la conducta inmediata?', options: ['Biopsia de la lesión durante el mismo procedimiento', 'Tratar solo con hierro oral y reevaluar en un año', 'Ignorar la lesión si el paciente está asintomático', 'Repetir la colonoscopia en 5 años sin biopsia'], correct: 0 },
      { q: 'Mientras se define el manejo oncológico, el paciente tiene anemia sintomática grave. ¿Qué tratamiento de la ferropenia es más apropiado antes de una eventual cirugía próxima?', options: ['Hierro oral, que corrige la hemoglobina en pocos días', 'Ácido fólico en monoterapia', 'Vigilancia sin tratamiento hasta después de la cirugía', 'Hierro intravenoso, con corrección más rápida que la vía oral'], correct: 3 }
    ],
    explanation: 'En un varón adulto con ferropenia sin causa evidente, la endoscopia digestiva alta y la colonoscopia son el estudio de primera línea, dado el riesgo de neoplasia gastrointestinal oculta. Toda lesión sospechosa debe biopsiarse en el mismo procedimiento. Ante la necesidad de corrección más rápida antes de una cirugía próxima, el hierro intravenoso es preferible al oral.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 26 años, vegana estricta desde hace 4 años, presenta fatiga y caída de cabello. Hb 10.1 g/dL, VCM 71 fL, ferritina 5 ng/mL. Refiere distensión abdominal intermitente y deposiciones ocasionalmente grasosas. Niega sangrado menstrual abundante.',
    steps: [
      { q: 'Además de evaluar el aporte dietético, ¿qué estudio de laboratorio debe solicitarse de rutina en este caso?', options: ['Perfil tiroideo únicamente', 'Serología de enfermedad celíaca (anti-transglutaminasa IgA + IgA total)', 'Electroforesis de hemoglobina como primer paso', 'Prueba de Coombs directa'], correct: 1 },
      { q: 'La serología resulta positiva. ¿Cuál es el siguiente paso para confirmar el diagnóstico?', options: ['Iniciar dieta sin gluten sin ninguna confirmación adicional', 'Colonoscopia como siguiente paso', 'Biopsia duodenal por endoscopia digestiva alta, para confirmación histológica', 'TC abdominal contrastada'], correct: 2 },
      { q: 'Confirmada la enfermedad celíaca, ¿cuál es el manejo más apropiado de la ferropenia?', options: ['Hierro intravenoso como primera línea, dada la malabsorción estructural, además de dieta sin gluten estricta', 'Hierro oral en dosis muy altas, que supera cualquier grado de malabsorción', 'Solo dieta sin gluten, sin suplementación de hierro', 'Transfusión profiláctica sin tratamiento etiológico'], correct: 0 }
    ],
    explanation: 'La serología celíaca se investiga de rutina en el estudio etiológico de la ferropenia, incluso sin síntomas digestivos floridos. Un resultado positivo se confirma con biopsia duodenal. En la malabsorción estructural establecida por enfermedad celíaca activa, el hierro intravenoso es primera línea, junto con la dieta sin gluten estricta que trata la causa de base.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 29 años, embarazo de 26 semanas, presenta fatiga marcada. Hb 9.8 g/dL, ferritina 10 ng/mL. Ha tenido intolerancia gastrointestinal grave con hierro oral en 2 intentos previos.',
    steps: [
      { q: '¿Se confirma anemia según el punto de corte ajustado por trimestre?', options: ['No, 9.8 g/dL es normal en cualquier trimestre', 'Solo se puede confirmar después del parto', 'No, el punto de corte del segundo trimestre es 7 g/dL', 'Sí, la hemoglobina está por debajo de 10.5 g/dL, el punto de corte del segundo trimestre'], correct: 3 },
      { q: 'Dada la intolerancia oral grave ya documentada, ¿cuál es la conducta más apropiada?', options: ['Insistir con hierro oral en dosis aún más altas', 'Hierro intravenoso, con perfil de seguridad establecido desde el segundo trimestre', 'Transfusión profiláctica sin evaluar alternativas', 'Suspender toda suplementación hasta después del parto'], correct: 1 },
      { q: '¿Qué riesgo se busca reducir al corregir oportunamente esta anemia antes del parto?', options: ['Preeclampsia, que no tiene relación con la anemia materna', 'Diabetes gestacional', 'Parto pretérmino, bajo peso al nacer, y peor tolerancia materna a la pérdida sanguínea del parto', 'Malformaciones congénitas estructurales'], correct: 2 }
    ],
    explanation: 'La hemoglobina de 9.8 g/dL está por debajo del punto de corte de 10.5 g/dL del segundo trimestre, confirmando anemia. Con intolerancia oral grave ya documentada, el hierro intravenoso es apropiado desde el segundo trimestre. Corregir oportunamente la anemia reduce el riesgo de parto pretérmino, bajo peso al nacer y peor tolerancia materna a la pérdida sanguínea del parto.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 54 años con anemia ferropénica conocida desde hace años, tratada de forma irregular, presenta disfagia progresiva para sólidos de localización cervical alta, junto con glositis y queilitis angular.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable?', options: ['Síndrome de Plummer-Vinson', 'Acalasia primaria', 'Estenosis péptica por reflujo crónico', 'Carcinoma esofágico distal'], correct: 0 },
      { q: '¿Qué estudio confirma el diagnóstico?', options: ['Manometría esofágica de alta resolución', 'pH-metría de 24 horas', 'TC de tórax simple', 'Esofagograma con bario o endoscopia digestiva alta, mostrando la membrana esofágica cervical'], correct: 3 },
      { q: '¿Cuál es el tratamiento de primera línea?', options: ['Dilatación endoscópica inmediata, sin corregir primero la ferropenia', 'Reposición agresiva de hierro (con frecuencia intravenosa), que puede mejorar la disfagia sin necesidad de dilatación', 'Cirugía de resección esofágica', 'Inhibidor de bomba de protones en monoterapia'], correct: 1 }
    ],
    explanation: 'La disfagia cervical alta con ferropenia crónica grave y manifestaciones extrahematológicas (glositis, queilitis angular) sugiere síndrome de Plummer-Vinson, confirmado por esofagograma con bario o endoscopia. La reposición agresiva de hierro, con frecuencia intravenosa, es la primera línea y puede mejorar la disfagia sin necesidad de dilatación mecánica.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Niño de 8 años con anemia microcítica grave documentada desde los 2 años de edad, con múltiples ciclos de hierro oral bien administrado sin respuesta hematológica significativa. Antecedente de un tío materno con un cuadro similar en la infancia.',
    steps: [
      { q: '¿Cuál es la sospecha diagnóstica más probable dado este patrón?', options: ['Talasemia mayor sin tratamiento transfusional', 'Anemia ferropénica refractaria al hierro (IRIDA) por mutación de TMPRSS6', 'Deficiencia de vitamina B12 congénita', 'Anemia de la enfermedad crónica'], correct: 1 },
      { q: '¿Qué hallazgo de laboratorio apoyaría esta sospecha?', options: ['Ferritina muy elevada, fuera de proporción con cualquier depósito de hierro', 'Reticulocitosis marcada', 'Haptoglobina indetectable', 'Hepcidina sérica inapropiadamente elevada para el grado de ferropenia'], correct: 3 },
      { q: '¿Qué respuesta se espera con el hierro intravenoso en este contexto?', options: ['Normalización completa e inmediata en todos los casos', 'Ninguna respuesta en absoluto, ni siquiera parcial', 'Una respuesta parcial, con mejoría de la hemoglobina sin normalización completa en muchos casos', 'Empeoramiento paradójico de la anemia'], correct: 2 }
    ],
    explanation: 'La refractariedad de por vida al hierro oral desde la infancia, con antecedente familiar similar, sugiere IRIDA por mutación de TMPRSS6, apoyada por una hepcidina sérica inapropiadamente elevada. El hierro intravenoso en la IRIDA logra típicamente una respuesta parcial, sin normalización completa, porque el bloqueo de hepcidina también limita la utilización del hierro parenteral.'
  }
];

export const flashcards = [
  { front: 'Marcador más sensible de depósitos de hierro agotados', back: 'Ferritina sérica (aunque es reactante de fase aguda, puede estar falsamente normal/elevada con inflamación).' },
  { front: 'Causa más frecuente de anemia ferropénica en varón adulto/mujer posmenopáusica', back: 'Pérdida crónica de sangre digestiva; obliga a endoscopia alta + colonoscopia.' },
  { front: 'Causa más frecuente en la mujer en edad reproductiva', back: 'Menorragia.' },
  { front: 'Las 3 etapas de la ferropenia', back: 'Depósitos agotados (ferritina baja) → eritropoyesis deficiente (+ saturación de transferrina baja) → anemia franca (+ VCM/Hb bajos).' },
  { front: 'Índice de Mentzer: interpretación', back: '&lt;13 sugiere rasgo talasémico; ≥13 sugiere ferropenia.' },
  { front: 'Fórmula de Ganzoni', back: 'Peso (kg) × (Hb objetivo − Hb actual) × 2.4 + depósito (500 mg en el adulto). Déficit total de hierro para IV.' },
  { front: 'Sitio principal de absorción del hierro dietético', back: 'Duodeno y yeyuno proximal.' },
  { front: 'Por qué el bypass gástrico en Y de Roux causa ferropenia', back: 'Excluye el duodeno, el sitio principal de absorción de hierro.' },
  { front: 'Serología a pedir de rutina en el estudio etiológico de ferropenia', back: 'Anti-transglutaminasa IgA + IgA total (enfermedad celíaca), incluso sin síntomas digestivos.' },
  { front: 'IRIDA: defecto genético', back: 'Mutación bialélica de TMPRSS6, con hepcidina inapropiadamente elevada que bloquea la absorción de hierro.' },
  { front: 'Estrategia de dosificación que mejora tolerancia y absorción del hierro oral', back: 'Días alternos en vez de dosis diaria.' },
  { front: 'Primera línea en malabsorción estructural establecida (celiaquía activa, poscirugía bariátrica)', back: 'Hierro intravenoso, no oral.' },
  { front: 'Punto de corte de anemia en el embarazo por trimestre', back: '&lt;11 g/dL (1º y 3º trimestre), &lt;10.5 g/dL (2º trimestre).' },
  { front: 'Suplementación de hierro en el embarazo', back: 'Universal, independientemente de la hemoglobina basal.' },
  { front: 'Tríada del síndrome de Plummer-Vinson', back: 'Disfagia + membranas esofágicas + anemia ferropénica.' },
  { front: 'Tratamiento de primera línea del síndrome de Plummer-Vinson', back: 'Reposición agresiva de hierro (con frecuencia IV); puede mejorar la disfagia sin dilatación.' },
  { front: 'Por qué la insuficiencia cardiaca de alto gasto en ferropenia no es una falla primaria de bomba', back: 'Es demanda circulatoria excesiva y sostenida por la anemia, no disfunción intrínseca inicial del miocardio.' },
  { front: 'Manejo central de la insuficiencia cardiaca de alto gasto por anemia', back: 'Corregir la anemia de base (hierro IV, transfusión cuidadosa si es grave).' },
  { front: 'Heces oscuras con hierro oral', back: 'Hallazgo esperado y benigno; distinguir de melena verdadera si hay dolor/alarma.' },
  { front: 'Mecanismo de la mayoría de las reacciones a hierro IV', back: 'Activación del complemento asociada a la infusión (pseudoalergia), no anafilaxia IgE clásica.' },
  { front: 'Mecanismo de la hipofosfatemia por carboximaltosa férrica', back: 'Aumento inapropiado de FGF23, que incrementa la excreción renal de fosfato.' },
  { front: 'Tratamiento de primera línea de anafilaxia verdadera por hierro IV', back: 'Epinefrina intramuscular.' },
  { front: 'Formulación de hierro IV con mayor riesgo de hipofosfatemia', back: 'Carboximaltosa férrica en dosis altas repetidas.' },
  { front: 'Pica en la ferropenia', back: 'Deseo de consumir sustancias no nutritivas (hielo -pagofagia-, tierra, almidón).' },
  { front: 'Manifestaciones extrahematológicas clásicas de la ferropenia', back: 'Pica, síndrome de piernas inquietas, caída de cabello, coiloniquia, glositis atrófica.' },
  { front: 'RDW en ferropenia vs. talasemia', back: 'Elevado en ferropenia (anisocitosis); normal en el rasgo talasémico.' },
  { front: 'Respuesta esperada a hierro IV en la IRIDA', back: 'Parcial, sin normalización completa (el bloqueo de hepcidina también limita el hierro parenteral).' }
];
