// topics/sindromes-mielodisplasicos/study.js: Autoevaluación de Síndromes Mielodisplásicos.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Índices `correct` de las 30 preguntas sueltas, en orden: 2,0,3,1,2,3,0,1,3,2,0,1,2,0,3,1,0,2,1,
// 3,0,3,1,2,3,0,2,1,0,3. Recuento: 0×8, 1×7, 2×7, 3×8. Sin racha >2 ni ciclo fijo.
// Índices `correct` de los pasos de las 5 preguntas en cascada (3 pasos c/u), en orden: 1,3,0 /
// 2,0,3 / 1,2,0 / 3,1,2 / 0,3,1. Recuento: 0×4, 1×4, 2×3, 3×4.

export const quiz = [
  { q: '¿Cuál es la mediana de edad aproximada al diagnóstico de los síndromes mielodisplásicos?', options: ['40 años', '55 años', '~70 años', '90 años'], correct: 2, explanation: 'La mediana de edad al diagnóstico es de ~70 años, y la incidencia aumenta de forma exponencial con la edad, hasta &gt;20 casos por 100,000 habitantes al año en mayores de 70.', dificultad: 'facil' },
  { q: '¿Cuál es la causa más frecuente de muerte en el SMD de alto riesgo no trasplantado?', options: ['Transformación a leucemia mieloide aguda', 'Sangrado gastrointestinal masivo', 'Insuficiencia renal aguda', 'Tromboembolismo pulmonar'], correct: 0, explanation: 'La transformación a leucemia mieloide aguda es la causa de muerte más frecuente en el SMD de alto riesgo no trasplantado.', dificultad: 'facil' },
  { q: '¿Cuál es el estudio que confirma el diagnóstico definitivo de un síndrome mielodisplásico?', options: ['Biometría hemática con diferencial únicamente', 'Frotis de sangre periférica únicamente', 'Panel viral (VIH, parvovirus B19)', 'Aspirado/biopsia de médula ósea con evaluación morfológica, citogenética y molecular'], correct: 3, explanation: 'El diagnóstico definitivo requiere aspirado/biopsia de médula ósea con evaluación morfológica (displasia, porcentaje de blastos), citogenética y molecular; los demás estudios excluyen causas alternativas de citopenia.', dificultad: 'facil' },
  { q: '¿Qué anomalía morfológica del neutrófilo es característica de la displasia en el SMD?', options: ['Bastones de Auer múltiples', 'Hipogranularidad y núcleo hipolobulado (anomalía pseudo-Pelger-Huët)', 'Cuerpos de Döhle prominentes', 'Vacuolización tóxica marcada'], correct: 1, explanation: 'La hipogranularidad citoplasmática y el núcleo hipolobulado (anomalía pseudo-Pelger-Huët) son hallazgos característicos de displasia granulocítica en el SMD.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo de laboratorio, si está presente, permite descartar razonablemente un SMD como causa de macrocitosis y citopenia?', options: ['Ferritina elevada', 'VCM elevado', 'Deficiencia documentada de vitamina B12 o folato, corregida con suplementación', 'Trombocitosis reactiva'], correct: 2, explanation: 'La deficiencia de vitamina B12/folato es una causa reversible de macrocitosis y citopenia que debe excluirse siempre; si se documenta y la citopenia se corrige con suplementación, no es un SMD.', dificultad: 'intermedio' },
  { q: '¿Qué tinción especial en la médula ósea identifica los sideroblastos en anillo?', options: ['Rojo Congo', 'Wright-Giemsa únicamente', 'Reticulina/tricrómico', 'Prusia azul (tinción de hierro)'], correct: 3, explanation: 'La tinción de Prusia azul (hierro) identifica los sideroblastos en anillo, precursores eritroides con gránulos de hierro dispuestos en anillo alrededor del núcleo.', dificultad: 'facil' },
  { q: '¿Qué mutación somática permite establecer el diagnóstico de SMD con sideroblastos en anillo con un porcentaje menor de sideroblastos (≥5% en vez de ≥15%)?', options: ['SF3B1', 'TP53', 'FLT3', 'NPM1'], correct: 0, explanation: 'La mutación de SF3B1, que altera el splicing del ARN y la síntesis de proteínas mitocondriales del metabolismo del hierro, permite el diagnóstico con un umbral menor de sideroblastos en anillo (≥5%) cuando está presente.', dificultad: 'intermedio' },
  { q: '¿Qué gen se localiza en la región comúnmente delecionada del SMD con del(5q), y cuya haploinsuficiencia explica el fenotipo de "ribosomopatía" adquirida de este subtipo?', options: ['TET2', 'RPS14', 'ASXL1', 'DNMT3A'], correct: 1, explanation: 'La haploinsuficiencia de RPS14, un gen ribosomal localizado en la región comúnmente delecionada del 5q, explica el fenotipo de "ribosomopatía" adquirida característico de este subtipo.', dificultad: 'dificil' },
  { q: '¿Cuál es el tratamiento farmacológico de elección en el SMD con del(5q) aislada sintomático?', options: ['Ácido tranexámico', 'Globulina antitimocítica', 'Deferasirox', 'Lenalidomida'], correct: 3, explanation: 'La lenalidomida es el tratamiento de elección en el SMD con del(5q) aislada sintomático, con respuesta eritroide independiente de transfusión en la mayoría de los casos.', dificultad: 'facil' },
  { q: '¿Cuál es el tratamiento de elección en el SMD con mutación de SF3B1/sideroblastos en anillo, dependiente de transfusiones?', options: ['Lenalidomida', 'Globulina antitimocítica', 'Luspatercept', 'Venetoclax'], correct: 2, explanation: 'El luspatercept, un agente madurativo eritroide, es de primera o segunda línea en el SMD SF3B1-mutado/con sideroblastos en anillo dependiente de transfusiones.', dificultad: 'intermedio' },
  { q: '¿Cuáles son las 5 variables que componen el IPSS-R?', options: ['Cariotipo, blastos en médula ósea, hemoglobina, plaquetas y neutrófilos absolutos', 'Edad, cariotipo, ferritina, LDH y albúmina', 'Blastos en sangre periférica, VCM, plaquetas, TP53 y ECOG', 'Cariotipo, blastos, hemoglobina, dímero D y creatinina'], correct: 0, explanation: 'El IPSS-R combina 5 variables: categoría citogenética, porcentaje de blastos en médula ósea, hemoglobina, plaquetas y recuento absoluto de neutrófilos.', dificultad: 'facil' },
  { q: 'Un paciente tiene un IPSS-R de 5 puntos. ¿En qué categoría de riesgo se clasifica?', options: ['Bajo', 'Alto', 'Muy bajo', 'Intermedio'], correct: 1, explanation: 'Un puntaje &gt;4.5-6 se clasifica como riesgo alto en el IPSS-R.', dificultad: 'intermedio' },
  { q: '¿Qué aporta el IPSS-M frente al IPSS-R?', options: ['Elimina la necesidad del cariotipo', 'Sustituye la hemoglobina por la ferritina', 'Incorpora el perfil mutacional somático completo, con TP53 como el modificador de mayor peso', 'Se aplica solo en el SMD hipoplásico'], correct: 2, explanation: 'El IPSS-M incorpora el perfil mutacional somático (NGS) a las variables clínicas del IPSS-R, con TP53 (particularmente bialélico) como el modificador individual de mayor peso, y reclasifica hasta 46% de los pacientes.', dificultad: 'intermedio' },
  { q: '¿Qué caracteriza morfológicamente al SMD con exceso de blastos tipo 2 (el de mayor porcentaje)?', options: ['10-19% de blastos en médula ósea, o presencia de bastones de Auer independientemente del porcentaje', '&lt;5% de blastos en médula ósea', 'Celularidad medular &lt;25%', 'Sideroblastos en anillo ≥15%'], correct: 0, explanation: 'El SMD con exceso de blastos de mayor grado se define por 10-19% de blastos en médula ósea, o por la presencia de bastones de Auer independientemente del porcentaje exacto.', dificultad: 'intermedio' },
  { q: '¿Qué umbral de blastos en médula ósea o sangre periférica define la transformación de un SMD a leucemia mieloide aguda?', options: ['≥5% en médula ósea', '≥10% en médula ósea', '≥15% en médula ósea', '≥20% en médula ósea o sangre periférica (o alteración citogenética/molecular definitoria independientemente del porcentaje)'], correct: 3, explanation: 'El umbral clásico de ≥20% de blastos en médula ósea o sangre periférica define la transformación a LMA, salvo alteraciones citogenéticas/moleculares definitorias de LMA que la definen independientemente del porcentaje.', dificultad: 'facil' },
  { q: '¿Cuál es la principal diferencia fisiopatológica entre el SMD hipoplásico y la anemia aplásica idiopática?', options: ['En la anemia aplásica siempre hay displasia marcada', 'En el SMD hipoplásico hay clonalidad demostrable (citogenética/molecular), ausente en la anemia aplásica idiopática típica', 'La anemia aplásica siempre tiene cariotipo complejo', 'El SMD hipoplásico nunca responde a inmunosupresión'], correct: 1, explanation: 'La clonalidad demostrable (cariotipo o mutación somática) distingue al SMD hipoplásico de la anemia aplásica idiopática, donde ambos suelen ser normales; una fracción de los SMD hipoplásicos, además, sí responde a inmunosupresión.', dificultad: 'intermedio' },
  { q: '¿Qué esquema de tratamiento es una opción específica del SMD hipoplásico, con base en su componente inmunomediado, distinto del resto de los subtipos de esta sección?', options: ['Globulina antitimocítica más ciclosporina', 'Lenalidomida en monoterapia', 'Deferasirox', 'Ácido tranexámico'], correct: 0, explanation: 'La globulina antitimocítica más ciclosporina es una opción de tratamiento específica del SMD hipoplásico, con base en el componente inmunomediado que comparte con la anemia aplásica.', dificultad: 'facil' },
  { q: '¿Qué patrón de latencia y alteración citogenética/molecular es característico del SMD relacionado a tratamiento por agentes alquilantes o radioterapia?', options: ['Latencia de 1-3 años, reordenamiento de MLL/KMT2A', 'Latencia de 1-3 años, sin fase displásica previa', 'Latencia de 5-7 años, con fase displásica previa y cariotipo complejo/pérdida de los cromosomas 5 y/o 7', 'Latencia de 6 meses, mutación de NPM1'], correct: 2, explanation: 'El SMD relacionado a agentes alquilantes o radioterapia tiene una latencia larga (5-7 años), con una fase displásica previa y asociación a cariotipo complejo o pérdida de material de los cromosomas 5 y/o 7.', dificultad: 'intermedio' },
  { q: '¿Qué patrón es característico del SMD relacionado a tratamiento por inhibidores de topoisomerasa II?', options: ['Latencia de 5-7 años, con fase displásica previa', 'Latencia corta (1-3 años), presentación frecuente como leucemia franca sin fase displásica previa, asociado a reordenamientos de MLL/KMT2A', 'Ausencia total de riesgo de leucemia', 'Asociación exclusiva con mutación de SF3B1'], correct: 1, explanation: 'Los inhibidores de topoisomerasa II se asocian a una latencia corta (1-3 años), presentación frecuente como leucemia franca sin fase displásica previa, y reordenamientos del gen MLL/KMT2A (11q23) o de RUNX1.', dificultad: 'intermedio' },
  { q: 'Antes de atribuir citopenias nuevas a un SMD relacionado a tratamiento en un paciente con antecedente de otra neoplasia, ¿qué debe descartarse siempre primero?', options: ['Deficiencia de cobre', 'Deficiencia de vitamina B12', 'Infección por VIH', 'Recaída o persistencia de la neoplasia original'], correct: 3, explanation: 'La recaída o persistencia de la neoplasia original debe descartarse siempre antes de atribuir las citopenias nuevas a un SMD relacionado a tratamiento.', dificultad: 'facil' },
  { q: '¿Cuál es la única opción de tratamiento potencialmente curativa en el SMD de alto riesgo?', options: ['Trasplante alogénico de células madre hematopoyéticas', 'Agente hipometilante en monoterapia indefinida', 'Lenalidomida', 'Ácido tranexámico'], correct: 0, explanation: 'El trasplante alogénico de células madre hematopoyéticas es la única opción de tratamiento potencialmente curativa en el SMD de alto riesgo.', dificultad: 'facil' },
  { q: '¿Cuál es el esquema de tratamiento estándar de primera línea en el SMD de alto riesgo no candidato o en espera de trasplante?', options: ['Globulina antitimocítica', 'Deferasirox', 'Romiplostim', 'Agente hipometilante (azacitidina o decitabina)'], correct: 3, explanation: 'El agente hipometilante (azacitidina o decitabina) es el tratamiento estándar de primera línea en el SMD de alto riesgo no candidato a trasplante inmediato, o como puente mientras se organiza este.', dificultad: 'facil' },
  { q: '¿Por qué las infecciones en el SMD pueden ocurrir pese a un recuento absoluto de neutrófilos no tan bajo?', options: ['Porque siempre coexiste deficiencia de inmunoglobulinas', 'Por disfunción granulocítica cualitativa (quimiotaxis, fagocitosis y capacidad microbicida reducidas) intrínseca al clon displásico', 'Porque los neutrófilos del SMD tienen vida media más larga', 'Porque el bazo está siempre aumentado de tamaño'], correct: 1, explanation: 'La disfunción granulocítica cualitativa intrínseca al clon displásico (quimiotaxis, fagocitosis y capacidad microbicida reducidas) explica que las infecciones ocurran incluso con un recuento absoluto de neutrófilos no tan bajo.', dificultad: 'intermedio' },
  { q: '¿Cuál es la conducta inicial ante fiebre en un paciente con SMD y neutropenia profunda (&lt;500/µL)?', options: ['Esperar el resultado de hemocultivos antes de iniciar antibiótico', 'Iniciar antiviral empírico como primera medida', 'Iniciar antibiótico empírico de amplio espectro con cobertura antipseudomónica dentro de la primera hora', 'Iniciar quelación de hierro de forma inmediata'], correct: 2, explanation: 'Ante fiebre y neutropenia profunda, el antibiótico empírico de amplio espectro con cobertura antipseudomónica debe iniciarse dentro de la primera hora, sin esperar el resultado de los cultivos.', dificultad: 'facil' },
  { q: '¿Por qué el riesgo de sangrado en el SMD no se correlaciona linealmente con el recuento plaquetario aislado?', options: ['Porque el SMD nunca produce trombocitopenia verdadera', 'Porque el sangrado en el SMD depende únicamente de factores de coagulación', 'Porque las plaquetas del SMD son siempre normales en número y función', 'Porque además de la trombocitopenia cuantitativa existe una disfunción plaquetaria cualitativa concomitante'], correct: 3, explanation: 'Además de la trombocitopenia cuantitativa (megacariopoyesis ineficaz), existe una disfunción plaquetaria cualitativa concomitante, por lo que el riesgo hemorrágico no se correlaciona linealmente con el recuento plaquetario aislado.', dificultad: 'intermedio' },
  { q: '¿Qué agente se debe usar con vigilancia estrecha del porcentaje de blastos por la preocupación teórica de estimular la proliferación del clon mielodisplásico?', options: ['Agonistas del receptor de trombopoyetina (romiplostim, eltrombopag)', 'Ácido tranexámico', 'Deferasirox', 'Agentes estimulantes de la eritropoyesis'], correct: 0, explanation: 'Los agonistas del receptor de trombopoyetina (romiplostim, eltrombopag) se usan en trombocitopenia sintomática de bajo riesgo con vigilancia estrecha del porcentaje de blastos, por la preocupación teórica de estimular la proliferación del clon mielodisplásico.', dificultad: 'dificil' },
  { q: '¿A partir de aproximadamente cuántas unidades de concentrado eritrocitario transfundidas se vuelve clínicamente relevante el riesgo de sobrecarga de hierro?', options: ['2-5 unidades', '10-15 unidades', '20-30 unidades', '100 unidades'], correct: 2, explanation: 'El riesgo clínicamente relevante de sobrecarga de hierro aparece aproximadamente a partir de 20-30 unidades transfundidas acumuladas, variable según la reserva basal de cada paciente.', dificultad: 'intermedio' },
  { q: '¿Cuál es el estudio de imagen que cuantifica de forma no invasiva la concentración de hierro en el hígado y el corazón, superior a la ferritina sérica aislada?', options: ['Tomografía computarizada simple', 'Resonancia magnética con secuencia T2*', 'Ecografía Doppler hepática', 'Gammagrafía ósea'], correct: 1, explanation: 'La resonancia magnética con secuencia T2* hepática y cardiaca cuantifica de forma no invasiva la concentración de hierro en cada órgano, superior a la ferritina sérica aislada (que puede elevarse falsamente por inflamación concomitante).', dificultad: 'intermedio' },
  { q: '¿Cuál es el agente de quelación de hierro de elección en el SMD, por su conveniencia posológica oral?', options: ['Deferasirox', 'Deferoxamina subcutánea', 'Ácido tranexámico', 'Romiplostim'], correct: 0, explanation: 'El deferasirox oral es el agente de quelación de hierro de elección por su conveniencia posológica; la deferoxamina subcutánea/IV es la alternativa en caso de intolerancia o insuficiencia renal.', dificultad: 'facil' },
  { q: '¿Qué combinación de hallazgos define los criterios diagnósticos mínimos del International Working Group (IWG) para SMD en un caso límite?', options: ['Solo el porcentaje de blastos, sin necesidad de displasia', 'Únicamente citopenia aislada, sin más estudio', 'Solo la presencia de una alteración citogenética, sin displasia ni citopenia', 'Citopenia persistente (&gt;4 meses) más displasia ≥10% en una línea, o blastos aumentados, o alteración citogenética típica, tras excluir otras causas'], correct: 3, explanation: 'Los criterios IWG exigen citopenia persistente (&gt;4 meses) más displasia ≥10% en una línea, o blastos aumentados, o una alteración citogenética típica, tras excluir otras causas, especialmente relevante en casos límite (citopenia/displasia de significado incierto).', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 68 años, sin antecedentes relevantes, es referida por anemia macrocítica progresiva (Hb 8.2 g/dL, VCM 108 fL) detectada en una biometría hemática de rutina, con leucocitos y plaquetas normales. Vitamina B12, folato y TSH son normales. El aspirado de médula ósea muestra displasia eritroide sin exceso de blastos (2%), y el cariotipo revela una deleción aislada del brazo largo del cromosoma 5.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable?', options: ['Anemia megaloblástica por deficiencia oculta de B12', 'Síndrome mielodisplásico con del(5q) aislada', 'Anemia aplásica idiopática', 'Talasemia intermedia no diagnosticada previamente'], correct: 1 },
      { q: 'Calculado el IPSS-R, la paciente se clasifica en riesgo bajo. ¿Cuál es el tratamiento farmacológico de elección dado el hallazgo citogenético?', options: ['Globulina antitimocítica', 'Azacitidina', 'Deferasirox', 'Lenalidomida'], correct: 3 },
      { q: 'Durante el tratamiento, la paciente desarrolla neutropenia y trombocitopenia leves-moderadas. ¿Cuál es la conducta más apropiada?', options: ['Es un efecto esperado del fármaco; continuar con vigilancia hematológica estrecha, sin suspender de entrada', 'Suspender el fármaco de inmediato y no reintentarlo nunca', 'Iniciar quimioterapia de inducción tipo LMA de inmediato', 'Indicar trasplante alogénico urgente'], correct: 0 }
    ],
    explanation: 'La anemia macrocítica con displasia eritroide y del(5q) aislada, sin otra causa, define el SMD con del(5q); la lenalidomida es el tratamiento de elección, con respuesta eritroide independiente de transfusión en la mayoría de los casos. La citopenia inicial (neutropenia/trombocitopenia) es un efecto esperado del fármaco y no obliga a suspenderlo de entrada, solo a vigilancia hematológica estrecha.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 58 años presenta fatiga progresiva y equimosis fáciles. La biometría hemática muestra pancitopenia. El aspirado de médula ósea muestra 12% de blastos, y el cariotipo revela monosomía 7. El estudio molecular no muestra mutaciones definitorias de leucemia mieloide aguda.',
    steps: [
      { q: '¿Cuál es el diagnóstico y la categoría de riesgo más probable?', options: ['SMD con blastos bajos, riesgo muy bajo', 'SMD hipoplásico, riesgo bajo', 'SMD con exceso de blastos, riesgo alto (IPSS-R)', 'Leucemia mieloide aguda franca'], correct: 2 },
      { q: 'El paciente es joven, sin comorbilidades significativas, y tiene un hermano HLA-idéntico. ¿Cuál es la conducta más apropiada?', options: ['Evaluación temprana para trasplante alogénico de células madre hematopoyéticas, con hipometilante como puente si hay exceso de blastos significativo', 'Solo soporte transfusional indefinido, sin más tratamiento', 'Lenalidomida en monoterapia', 'Vigilancia expectante sin tratamiento hasta progresión a LMA franca'], correct: 0 },
      { q: 'Mientras se organiza el trasplante, se inicia un agente hipometilante. ¿Cuál es una opción de primera línea?', options: ['Deferasirox', 'Romiplostim', 'Ácido tranexámico', 'Azacitidina'], correct: 3 }
    ],
    explanation: 'El exceso de blastos con monosomía 7 define un SMD de alto riesgo por IPSS-R. En el paciente joven, elegible y con donante disponible, el trasplante alogénico temprano es la conducta apropiada por ser la única opción potencialmente curativa; mientras se organiza, un agente hipometilante como azacitidina se usa como puente para controlar la enfermedad.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 32 años presenta pancitopenia progresiva. La biopsia de médula ósea muestra celularidad del 15%. El cariotipo revela trisomía 8, y el panel molecular identifica una mutación somática de ASXL1.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable, y qué hallazgo lo distingue de una anemia aplásica idiopática?', options: ['Anemia aplásica idiopática; el cariotipo siempre es anormal en esta entidad', 'SMD hipoplásico; la clonalidad demostrada (cariotipo y mutación somática) distingue de la anemia aplásica idiopática, donde ambos suelen ser normales', 'Hemoglobinuria paroxística nocturna clásica, sin relación con SMD', 'Mielofibrosis primaria, dado que la médula está hipocelular'], correct: 1 },
      { q: '¿Qué estudio adicional es razonable solicitar antes de decidir el tratamiento?', options: ['Estudio de fragilidad cromosómica con diepoxibutano únicamente si hay sospecha de Fanconi', 'Ninguno adicional, el diagnóstico ya está completo', 'Citometría de flujo para clonas de hemoglobinuria paroxística nocturna', 'Biopsia hepática'], correct: 2 },
      { q: 'La paciente es joven, HLA-DR15 positiva, con una pequeña clona de HPN. ¿Cuál es una opción de tratamiento específica de este subtipo, distinta del resto de los SMD?', options: ['Globulina antitimocítica más ciclosporina', 'Lenalidomida', 'Luspatercept', 'Deferasirox'], correct: 0 }
    ],
    explanation: 'La combinación de hipocelularidad marcada con clonalidad demostrable (cariotipo anormal, mutación somática) define el SMD hipoplásico, distinto de la anemia aplásica idiopática donde ambos suelen ser normales. El perfil de esta paciente (joven, HLA-DR15+, clona de HPN presente) predice buena respuesta a la inmunosupresión con globulina antitimocítica más ciclosporina, una opción específica de este subtipo.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 55 años, tratada hace 3 años con quimioterapia que incluyó un inhibidor de topoisomerasa II por cáncer de mama, presenta pancitopenia de instalación relativamente rápida. El aspirado de médula ósea muestra 8% de blastos, y el estudio citogenético identifica un reordenamiento del gen MLL/KMT2A.',
    steps: [
      { q: '¿Qué debe descartarse primero antes de atribuir el cuadro a un SMD relacionado a tratamiento?', options: ['Deficiencia de vitamina B12', 'Infección por VIH', 'Hipotiroidismo', 'Recaída o persistencia del cáncer de mama original'], correct: 3 },
      { q: 'Descartada la recaída, ¿qué patrón de latencia y alteración citogenética es consistente con el antecedente de un inhibidor de topoisomerasa II?', options: ['Latencia de 5-7 años con fase displásica previa', 'Latencia corta (1-3 años), sin fase displásica previa, con reordenamiento de MLL/KMT2A, como en este caso', 'Ausencia total de asociación con quimioterapia previa', 'Latencia de 15-20 años'], correct: 1 },
      { q: '¿Cuál es la conducta más apropiada respecto al trasplante alogénico en esta paciente, si es elegible?', options: ['Está contraindicado por el antecedente de otra neoplasia, incluso si está controlada', 'Se pospone indefinidamente hasta que aparezcan blastos ≥20%', 'Se considera tempranamente, ya que el t-MDS se comporta como alto riesgo independientemente del porcentaje de blastos al diagnóstico', 'Nunca se realiza en SMD relacionado a tratamiento'], correct: 2 }
    ],
    explanation: 'Antes de atribuir citopenias nuevas a un t-MDS, siempre debe descartarse la recaída de la neoplasia original. El patrón de latencia corta con reordenamiento de MLL/KMT2A es característico de los inhibidores de topoisomerasa II. El SMD relacionado a tratamiento se comporta como una categoría de alto riesgo independientemente del porcentaje de blastos, por lo que el trasplante alogénico se considera tempranamente en todo paciente elegible, sin que el antecedente oncológico controlado lo contraindique por sí solo.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 71 años con SMD de bajo riesgo, en tratamiento con agentes estimulantes de la eritropoyesis, acude a urgencias con fiebre de 38.6°C. La biometría hemática muestra un recuento absoluto de neutrófilos de 380/µL.',
    steps: [
      { q: '¿Cuál es la conducta inmediata más apropiada?', options: ['Hemocultivos + inicio de antibiótico empírico de amplio espectro con cobertura antipseudomónica dentro de la primera hora', 'Esperar el resultado de hemocultivos antes de iniciar cualquier antibiótico', 'Iniciar quelación de hierro de inmediato', 'Alta con antipirético oral y control ambulatorio en 72 horas'], correct: 0 },
      { q: 'A las 96 horas, la fiebre persiste pese al antibiótico de amplio espectro, sin foco identificado. ¿Cuál es la conducta más apropiada?', options: ['Suspender todo antibiótico por falta de respuesta', 'Iniciar quelación de hierro', 'Transfundir plaquetas de forma profiláctica, sin indicación de sangrado', 'Agregar cobertura antifúngica empírica'], correct: 3 },
      { q: 'El paciente también refiere que ha recibido más de 25 unidades de concentrado eritrocitario en los últimos 2 años. ¿Qué se debe vigilar de forma independiente a este episodio agudo?', options: ['Fragilidad cromosómica con diepoxibutano', 'Ferritina sérica seriada, con RM T2* si hay duda, para descartar sobrecarga de hierro', 'Cadenas ligeras libres en suero', 'Alfa-galactosidasa A'], correct: 1 }
    ],
    explanation: 'La fiebre con neutropenia profunda (&lt;500/µL) obliga a hemocultivos e inicio inmediato de antibiótico empírico de amplio espectro, sin esperar cultivos. Si la fiebre persiste más de 96 horas sin foco pese al antibiótico, se agrega cobertura antifúngica empírica. De forma independiente al episodio agudo, la politransfusión sostenida (&gt;20-30 unidades) obliga a vigilar la ferritina sérica para descartar sobrecarga de hierro, confirmando con RM T2* si hay duda.'
  }
];

export const flashcards = [
  { front: 'Mediana de edad al diagnóstico de SMD', back: '~70 años; incidencia aumenta exponencialmente con la edad.' },
  { front: 'Estudio que confirma el diagnóstico de SMD', back: 'Aspirado/biopsia de médula ósea: morfología (displasia, % blastos), citogenética y molecular.' },
  { front: 'Anomalía neutrofílica displásica clásica', back: 'Hipogranularidad y núcleo hipolobulado (anomalía pseudo-Pelger-Huët).' },
  { front: 'Tinción para sideroblastos en anillo', back: 'Prusia azul (hierro); ≥15% (o ≥5% con SF3B1 mutado) define el subtipo.' },
  { front: 'Gen mutado que reduce el umbral de sideroblastos en anillo a 5%', back: 'SF3B1.' },
  { front: 'Gen haploinsuficiente en el SMD con del(5q)', back: 'RPS14: explica el fenotipo de "ribosomopatía" adquirida y la anemia macrocítica.' },
  { front: 'Tratamiento de elección en SMD con del(5q)', back: 'Lenalidomida.' },
  { front: 'Tratamiento de elección en SMD SF3B1-mutado/sideroblastos en anillo', back: 'Luspatercept (agente madurativo eritroide).' },
  { front: 'Las 5 variables del IPSS-R', back: 'Cariotipo, % blastos en médula ósea, hemoglobina, plaquetas, neutrófilos absolutos.' },
  { front: 'IPSS-R: categorías de riesgo', back: '≤1.5 muy bajo; &gt;1.5-3 bajo; &gt;3-4.5 intermedio; &gt;4.5-6 alto; &gt;6 muy alto.' },
  { front: 'IPSS-M: qué agrega al IPSS-R', back: 'Perfil mutacional somático completo (NGS); TP53 es el modificador de mayor peso; reclasifica hasta 46% de los pacientes.' },
  { front: 'Umbral de blastos que define transformación a LMA', back: '≥20% en médula ósea o sangre periférica (o alteración citogenética/molecular definitoria, independiente del %).' },
  { front: 'SMD hipoplásico vs. anemia aplásica idiopática', back: 'La clonalidad (cariotipo/mutación somática) distingue al SMD hipoplásico; en la aplásica típica ambos son normales.' },
  { front: 'Tratamiento específico del SMD hipoplásico', back: 'Globulina antitimocítica + ciclosporina (inmunosupresión), mejor respuesta si joven, HLA-DR15+, clona de HPN.' },
  { front: 't-MDS por alquilantes/radioterapia: patrón', back: 'Latencia larga (5-7 años), fase displásica previa, cariotipo complejo o pérdida de 5/7.' },
  { front: 't-MDS por inhibidores de topoisomerasa II: patrón', back: 'Latencia corta (1-3 años), leucemia franca sin fase displásica previa, reordenamiento de MLL/KMT2A.' },
  { front: 'Antes de diagnosticar t-MDS, descartar siempre', back: 'Recaída o persistencia de la neoplasia original.' },
  { front: 'Única opción curativa en SMD de alto riesgo', back: 'Trasplante alogénico de células madre hematopoyéticas.' },
  { front: 'Tratamiento estándar de primera línea en SMD de alto riesgo (no trasplante inmediato)', back: 'Agente hipometilante: azacitidina o decitabina.' },
  { front: 'Por qué hay infecciones pese a ANC no tan bajo', back: 'Disfunción granulocítica cualitativa intrínseca del clon displásico (quimiotaxis, fagocitosis, poder microbicida reducidos).' },
  { front: 'Fiebre + ANC &lt;500/µL: conducta inmediata', back: 'Hemocultivos + antibiótico empírico de amplio espectro antipseudomónico dentro de la primera hora.' },
  { front: 'Fiebre persistente &gt;96h sin foco pese a antibiótico', back: 'Agregar cobertura antifúngica empírica.' },
  { front: 'Por qué el sangrado no se correlaciona linealmente con el recuento plaquetario', back: 'Disfunción plaquetaria cualitativa concomitante a la trombocitopenia cuantitativa.' },
  { front: 'Agonistas de trombopoyetina en SMD: precaución', back: 'Vigilar % de blastos por preocupación teórica de estimular el clon mielodisplásico.' },
  { front: 'Umbral de unidades transfundidas con riesgo relevante de sobrecarga de hierro', back: '~20-30 unidades acumuladas.' },
  { front: 'Estudio no invasivo para cuantificar hierro en hígado/corazón', back: 'Resonancia magnética con secuencia T2*.' },
  { front: 'Quelante de hierro de elección en SMD', back: 'Deferasirox oral (alternativa: deferoxamina subcutánea/IV).' }
];

export const caseSteps = [];
export const caseSummary = undefined;

export default { quiz, flashcards, caseSteps, caseSummary };
