// topics/exploracion-neurologica/study.js — Autoevaluación de Exploración Neurológica.
// Mismo patrón que historia-clinica/study.js y los demás temas de Semiología: banco único,
// preguntas sueltas + preguntas en cascada sobre una viñeta (retroalimentación consolidada al
// final, sin revelar correcto/incorrecto paso a paso).

export const quiz = [
  { q: '¿Cuál es el orden general de la exploración neurológica?', options: ['Marcha, reflejos, pares craneales, fuerza', 'Estado mental, pares craneales, sistema motor, sistema sensitivo, coordinación, marcha', 'Reflejos primero siempre, luego el resto', 'Signos meníngeos primero siempre, luego el resto'], correct: 1, explanation: 'El orden estándar va del estado mental a los pares craneales, el sistema motor, el sensitivo, la coordinación y la marcha, dejando los signos meníngeos y reflejos patológicos para cuando hay sospecha clínica dirigida.', dificultad: 'facil' },
  { q: '¿Por qué, ante una alteración aguda del estado de conciencia, se valora el nivel de conciencia ANTES que el resto de la exploración neurológica?', options: ['Por protocolo administrativo únicamente', 'Porque es el dato basal contra el que se compararán todas las reevaluaciones posteriores, y puede cambiar rápido', 'Porque los pares craneales no se pueden explorar en un paciente alerta', 'No hay ninguna razón clínica real'], correct: 1, explanation: 'Documentar el nivel de conciencia antes de cualquier sedación o intervención establece la línea basal indispensable para detectar deterioro o mejoría en las siguientes horas.', dificultad: 'intermedio' },
  { q: 'En la desorientación progresiva, ¿qué esfera se suele perder primero?', options: ['Persona', 'Tiempo', 'Espacio', 'Las tres se pierden siempre simultáneamente'], correct: 1, explanation: 'Clásicamente se pierde primero la orientación en tiempo, luego en espacio, y por último en persona (la más resistente a perderse).', dificultad: 'facil' },
  { q: '¿Qué patrón caracteriza a la afasia de Broca?', options: ['Fluente, con comprensión alterada', 'No fluente/esforzada, con comprensión relativamente conservada y repetición alterada', 'Fluente, con repetición y comprensión normales', 'Pérdida total del lenguaje sin ningún componente conservado'], correct: 1, explanation: 'La afasia de Broca (lesión frontal inferior) es no fluente y esforzada, con comprensión relativamente preservada pero repetición alterada.', dificultad: 'intermedio' },
  { q: '¿Qué patrón caracteriza a la afasia de Wernicke?', options: ['No fluente, con comprensión conservada', 'Fluente pero con parafasias y contenido vacío, comprensión y repetición alteradas', 'Solo afecta la escritura, no el habla', 'Afecta exclusivamente la denominación de objetos'], correct: 1, explanation: 'La afasia de Wernicke (lesión temporal posterior) es fluente pero con parafasias, contenido vacío de significado, y tanto la comprensión como la repetición están alteradas.', dificultad: 'intermedio' },
  { q: '¿Qué distingue específicamente a la afasia de conducción de las afasias de Broca y Wernicke?', options: ['Es la única con fluencia normal y comprensión normal', 'La repetición está DESPROPORCIONADAMENTE alterada respecto a la fluencia y la comprensión, por lesión del fascículo arcuato', 'Nunca afecta la repetición', 'Solo ocurre en niños'], correct: 1, explanation: 'En la afasia de conducción, por lesión del fascículo arcuato (que conecta las áreas de Broca y Wernicke), la repetición se altera de forma desproporcionada respecto a una fluencia y comprensión relativamente conservadas.', dificultad: 'dificil' },
  { q: '¿Cuál es la diferencia fundamental entre afasia y disartria?', options: ['Son sinónimos', 'La afasia es un trastorno del lenguaje en sí; la disartria es un trastorno de la articulación motora del habla, con lenguaje y comprensión intactos', 'La disartria siempre es más grave que la afasia', 'La afasia solo afecta el habla, nunca la escritura'], correct: 1, explanation: 'La afasia compromete la formulación/comprensión del lenguaje; la disartria es puramente un problema de articulación motora, con el contenido y la comprensión del lenguaje intactos.', dificultad: 'facil' },
  { q: '¿Cuáles son los 3 componentes de la Escala de Coma de Glasgow?', options: ['Frecuencia cardiaca, respiratoria y presión arterial', 'Apertura ocular, respuesta verbal, respuesta motora', 'Reflejos, tono y fuerza', 'Orientación, atención y memoria'], correct: 1, explanation: 'La ECG suma apertura ocular (máx. 4), respuesta verbal (máx. 5) y respuesta motora (máx. 6), para un rango total de 3 a 15.', dificultad: 'facil' },
  { q: '¿Qué puntaje de la Escala de Coma de Glasgow se asocia clásicamente a la indicación de manejo avanzado de la vía aérea?', options: ['15', '12', '≤8', '3 únicamente'], correct: 2, explanation: 'Un Glasgow ≤8 se asocia clásicamente con pérdida de la capacidad de proteger la vía aérea y es indicación de intubación ("8 = intuba").', dificultad: 'facil' },
  { q: '¿Por qué la Escala de Coma de Glasgow se reporta desglosada (ej. "O2V2M4") y no solo como suma total?', options: ['Por tradición, sin motivo clínico real', 'Porque el mismo puntaje total puede corresponder a combinaciones clínicamente distintas de los 3 componentes', 'Porque la suma total nunca es correcta', 'Porque cada componente se evalúa en un paciente distinto'], correct: 1, explanation: 'Dos pacientes con la misma suma total pueden tener perfiles muy distintos (ej. un componente motor muy bajo compensado por uno verbal alto), por eso reportar los 3 componentes por separado aporta más información clínica.', dificultad: 'intermedio' },
  { q: '¿Qué caracteriza a la pupila de Argyll-Robertson?', options: ['Reacciona a la luz pero no a la acomodación', 'Reacciona a la acomodación pero NO a la luz; clásica de neurosífilis', 'Está fija y dilatada sin ninguna reacción', 'Es normal, sin ninguna alteración'], correct: 1, explanation: 'La pupila de Argyll-Robertson se acomoda pero no reacciona a la luz (descrita clásicamente como "prostitute pupil" en inglés), por una lesión pretectal que respeta la vía de la acomodación; es un signo clásico de neurosífilis.', dificultad: 'dificil' },
  { q: 'En una parálisis del III par craneal con pupila midriática y ARREACTIVA (pupila "afectada"), ¿qué causa se debe descartar con urgencia?', options: ['Causa microvascular/diabética, sin urgencia', 'Causa compresiva, como un aneurisma de la arteria comunicante posterior', 'Migraña oftalmopléjica exclusivamente', 'Nunca es urgente evaluar la pupila en una parálisis del III par'], correct: 1, explanation: 'Las fibras pupilomotoras parasimpáticas viajan en la periferia del III par y se afectan primero por compresión externa (aneurisma) — una pupila afectada es una urgencia neuroquirúrgica hasta demostrar lo contrario.', dificultad: 'dificil' },
  { q: '¿Por qué una parálisis del III par de causa microvascular (ej. diabética) suele RESPETAR la reactividad pupilar?', options: ['Porque la isquemia del vasa nervorum daña preferentemente el centro del nervio, mientras las fibras pupilomotoras periféricas quedan relativamente preservadas', 'Porque la diabetes nunca afecta los pares craneales', 'Porque las fibras pupilomotoras no existen en el III par', 'Es una coincidencia sin base anatómica'], correct: 0, explanation: 'La isquemia microvascular afecta preferentemente el centro del nervio, mientras las fibras pupilomotoras parasimpáticas, ubicadas en la periferia, tienden a preservarse — de ahí el patrón "pupila respetada" en causas isquémicas.', dificultad: 'dificil' },
  { q: '¿Cuál es la tríada del síndrome de Horner?', options: ['Midriasis, ptosis, anhidrosis', 'Ptosis, miosis, anhidrosis facial ipsilateral', 'Diplopía, ptosis, midriasis', 'Nistagmo, ptosis, miosis'], correct: 1, explanation: 'El síndrome de Horner, por lesión de la vía oculosimpática de 3 neuronas, se caracteriza por ptosis, miosis y anhidrosis facial ipsilaterales.', dificultad: 'intermedio' },
  { q: '¿Qué diferencia pupilar distingue al síndrome de Horner de una parálisis del III par, ambos con ptosis?', options: ['No hay ninguna diferencia pupilar', 'Horner cursa con MIOSIS; la parálisis del III par cursa con MIDRIASIS', 'Horner siempre tiene midriasis y el III par siempre miosis', 'Ambos cursan siempre con pupilas normales'], correct: 1, explanation: 'La dirección del cambio pupilar distingue ambos síndromes con ptosis: miosis en el Horner (pérdida del tono simpático dilatador) vs. midriasis en la parálisis del III par (pérdida del tono parasimpático constrictor).', dificultad: 'dificil' },
  { q: '¿Por qué una lesión CENTRAL (corticonuclear) del nervio facial respeta la musculatura de la frente, a diferencia de una lesión PERIFÉRICA?', options: ['Porque la frente no tiene inervación motora', 'Porque la porción del núcleo facial que controla la frente recibe inervación cortical bilateral, mientras la porción inferior solo recibe inervación contralateral', 'Porque la lesión central nunca afecta ningún músculo facial', 'Es un mito sin base anatómica'], correct: 1, explanation: 'La inervación cortical bilateral de la porción superior del núcleo facial explica por qué una lesión por encima del núcleo (central) respeta la frente, mientras una lesión del núcleo o del nervio (periférica) compromete toda la hemicara.', dificultad: 'dificil' },
  { q: 'Un paciente no puede arrugar la frente ni cerrar el ojo del lado afectado, además de la caída de la comisura bucal. ¿Qué tipo de parálisis facial es?', options: ['Central', 'Periférica', 'Ninguna de las dos, es un hallazgo normal', 'Bulbar exclusivamente'], correct: 1, explanation: 'El compromiso de TODA la hemicara, incluida la frente, es característico de una lesión periférica del nervio facial (ej. parálisis de Bell), a diferencia de la lesión central que respeta la frente.', dificultad: 'facil' },
  { q: 'Una parálisis facial periférica BILATERAL debe hacer sospechar, entre otras causas:', options: ['Un evento cerebrovascular único', 'Síndrome de Guillain-Barré, sarcoidosis o enfermedad de Lyme', 'Siempre es un hallazgo normal en el anciano', 'Migraña común'], correct: 1, explanation: 'La afectación bilateral simultánea del nervio facial es infrecuente en un evento cerebrovascular único y obliga a pensar en causas sistémicas como Guillain-Barré, sarcoidosis o enfermedad de Lyme.', dificultad: 'intermedio' },
  { q: 'En la prueba de Weber, si el sonido lateraliza AL oído afectado, esto sugiere:', options: ['Hipoacusia neurosensorial de ese oído', 'Hipoacusia conductiva de ese oído', 'Audición normal', 'Lesión del nervio facial'], correct: 1, explanation: 'En la hipoacusia conductiva, el hueso transmite mejor sin la competencia del ruido ambiental que ya no llega por la vía aérea bloqueada, por lo que el sonido lateraliza AL oído afectado.', dificultad: 'intermedio' },
  { q: 'En la prueba de Weber, si el sonido lateraliza al oído SANO, esto sugiere:', options: ['Hipoacusia conductiva del oído sano', 'Hipoacusia neurosensorial del oído contrario (afectado)', 'Que ambos oídos están sanos', 'Que la prueba fue mal realizada'], correct: 1, explanation: 'En la hipoacusia neurosensorial, la cóclea o el nervio del lado afectado perciben peor el sonido en general, por lo que este lateraliza hacia el oído sano.', dificultad: 'intermedio' },
  { q: 'En una lesión periférica del XII par (hipogloso), al protruir la lengua, ¿hacia qué lado se desvía?', options: ['Hacia el lado sano', 'Hacia el lado de la lesión', 'No se desvía en ninguna lesión del XII par', 'Se desvía hacia arriba'], correct: 1, explanation: 'El geniogloso sano del lado contralateral empuja la lengua hacia el lado débil, por lo que la lengua se desvía HACIA el lado de la lesión periférica.', dificultad: 'facil' },
  { q: 'Según la escala MRC, ¿qué significa un grado 3 de fuerza muscular?', options: ['Sin contracción visible', 'Movimiento activo que vence la gravedad, pero no resistencia adicional', 'Fuerza normal', 'Movimiento activo contra resistencia leve'], correct: 1, explanation: 'El grado 3 de la escala MRC corresponde a un movimiento activo capaz de vencer la gravedad, pero incapaz de vencer cualquier resistencia adicional del examinador.', dificultad: 'facil' },
  { q: '¿Qué distingue al patrón de debilidad "piramidal" de un patrón "periférico"?', options: ['El piramidal predomina en extensores de miembros superiores y flexores de miembros inferiores; el periférico sigue una distribución radicular o troncular', 'No existe ninguna diferencia de distribución', 'El periférico siempre es bilateral y simétrico', 'El piramidal solo afecta las piernas'], correct: 0, explanation: 'El patrón piramidal tiene una distribución característica (predominio en extensores de brazo y flexores de pierna); el patrón periférico sigue el territorio de una raíz (miotoma) o un nervio periférico específico.', dificultad: 'intermedio' },
  { q: '¿Cuál es la diferencia clave entre espasticidad y rigidez?', options: ['No hay diferencia, son sinónimos', 'La espasticidad depende de la velocidad del movimiento pasivo (signo de la navaja); la rigidez es independiente de la velocidad', 'La rigidez solo se ve en niños', 'La espasticidad siempre se acompaña de hipotonía'], correct: 1, explanation: 'La espasticidad (lesión piramidal) aumenta con la velocidad del movimiento y cede bruscamente (signo de la navaja); la rigidez (extrapiramidal) es constante independientemente de la velocidad.', dificultad: 'intermedio' },
  { q: '¿Qué es el "signo de la navaja"?', options: ['Resistencia constante durante todo el movimiento pasivo', 'Resistencia inicial que cede bruscamente durante el movimiento pasivo, típica de espasticidad', 'Un reflejo patológico del pie', 'Un tipo de marcha atáxica'], correct: 1, explanation: 'El signo de la navaja es característico de la espasticidad: resistencia inicial marcada que cede de forma súbita conforme continúa el movimiento pasivo.', dificultad: 'facil' },
  { q: 'Una hipotonía aguda con arreflexia en las 4 extremidades, inmediatamente después de una lesión medular traumática, ¿a qué corresponde?', options: ['Espasticidad esperada de inmediato', 'Shock medular — fase aguda con ausencia transitoria de los reflejos, antes de que aparezca la espasticidad esperada', 'Es siempre un signo de mejoría', 'Nunca ocurre en lesión medular aguda'], correct: 1, explanation: 'En la fase aguda de una lesión medular (shock medular), los reflejos por debajo del nivel de la lesión están transitoriamente abolidos, antes de que se desarrolle la hiperreflexia/espasticidad esperada de una lesión de neurona motora superior.', dificultad: 'dificil' },
  { q: '¿Qué significa un reflejo osteotendinoso graduado como 4+?', options: ['Ausente', 'Normal', 'Hiperactivo, con clono', 'Hipoactivo, sin clono'], correct: 2, explanation: 'La graduación 4+ corresponde a un reflejo hiperactivo acompañado de clono (contracciones rítmicas repetidas al estirar bruscamente el tendón).', dificultad: 'facil' },
  { q: '¿Qué significa la presencia de clono SOSTENIDO al explorar los reflejos?', options: ['Es siempre un hallazgo normal en personas ansiosas', 'Es siempre patológico y confirma una lesión de neurona motora superior', 'Indica una lesión de neurona motora inferior', 'No tiene ningún significado clínico'], correct: 1, explanation: 'A diferencia de unas pocas sacudidas que se agotan rápido (pueden verse en personas sanas y ansiosas), el clono sostenido (que no se agota) es siempre patológico y confirma la pérdida de la inhibición corticoespinal descendente.', dificultad: 'intermedio' },
  { q: '¿Para qué sirve la maniobra de Jendrassik al explorar reflejos osteotendinosos?', options: ['Para medir la fuerza muscular', 'Para reforzar un reflejo que parece abolido, pidiendo al paciente traccionar sus manos entrelazadas mientras se percute', 'Para descartar signos meníngeos', 'Para evaluar la sensibilidad vibratoria'], correct: 1, explanation: 'Cuando un reflejo parece abolido, la maniobra de refuerzo de Jendrassik (traccionar las manos entrelazadas) puede desenmascararlo si en realidad estaba solo suprimido por falta de relajación.', dificultad: 'intermedio' },
  { q: '¿Qué patrón de pérdida sensitiva se espera en un síndrome de Brown-Séquard (hemisección medular)?', options: ['Pérdida global de toda sensibilidad en ambos lados por igual', 'Pérdida de sensibilidad vibratoria/posicional IPSILATERAL y de dolor/temperatura CONTRALATERAL a la lesión', 'Pérdida exclusivamente motora, sin ningún componente sensitivo', 'Pérdida de dolor/temperatura ipsilateral únicamente'], correct: 1, explanation: 'Los cordones posteriores (vibración/posición) aún no habían decusado al ser lesionados, por lo que la pérdida es ipsilateral; la vía espinotalámica (dolor/temperatura) ya había decusado antes de la lesión, por lo que la pérdida es contralateral.', dificultad: 'dificil' },
  { q: '¿Qué patrón de pérdida sensitiva es característico de la siringomielia?', options: ['Pérdida de vibración y posición, bilateral y suspendida', 'Pérdida SUSPENDIDA y bilateral de dolor y temperatura, con preservación de la vibración/posición', 'Pérdida de toda sensibilidad por debajo del nivel de la lesión', 'No produce ningún déficit sensitivo'], correct: 1, explanation: 'La cavidad siringomiélica se forma en la comisura anterior, justo donde decusan las fibras espinotalámicas, produciendo una pérdida suspendida y bilateral de dolor/temperatura con preservación de los cordones posteriores.', dificultad: 'dificil' },
  { q: 'Una pérdida sensitiva distal, simétrica, en "guante y calceta", en las 4 extremidades, sugiere:', options: ['Lesión medular focal', 'Polineuropatía periférica', 'Síndrome de Brown-Séquard', 'Siringomielia'], correct: 1, explanation: 'El patrón distal y simétrico en guante y calceta es característico de una polineuropatía periférica (ej. diabética), no de una lesión medular focal.', dificultad: 'facil' },
  { q: '¿Qué evalúa realmente la maniobra de Romberg?', options: ['La función cerebelosa en su totalidad', 'Específicamente la propiocepción/columna posterior, no todo el cerebelo', 'La fuerza muscular de los miembros inferiores', 'La audición'], correct: 1, explanation: 'Romberg es una prueba dirigida a la propiocepción (columna posterior): evalúa si el paciente puede mantener el equilibrio cuando se le retira la compensación visual.', dificultad: 'intermedio' },
  { q: '¿Por qué el Romberg suele ser NEGATIVO en la ataxia cerebelosa, a pesar de que el paciente esté claramente inestable?', options: ['Porque el cerebelo no participa en el equilibrio', 'Porque la inestabilidad cerebelosa ya está presente incluso con los ojos abiertos; el problema no es la propiocepción', 'Porque la ataxia cerebelosa nunca afecta la marcha', 'El Romberg siempre es positivo en la ataxia cerebelosa'], correct: 1, explanation: 'En la ataxia cerebelosa el defecto es de coordinación, no de propiocepción, por lo que cerrar los ojos no empeora significativamente la inestabilidad ya presente — a diferencia de la ataxia sensitiva.', dificultad: 'dificil' },
  { q: '¿Qué causa típica produce la marcha en "steppage"?', options: ['Lesión piramidal unilateral', 'Debilidad de los dorsiflexores del pie por lesión del nervio peroneo o polineuropatía', 'Enfermedad de Parkinson', 'Debilidad de glúteos medios'], correct: 1, explanation: 'La marcha en steppage (elevación exagerada de la rodilla para no arrastrar el pie caído) refleja debilidad de los dorsiflexores, típica de una lesión del nervio peroneo o de polineuropatía.', dificultad: 'facil' },
  { q: '¿Cómo se distingue la marcha atáxica cerebelosa de la marcha atáxica sensitiva (tabética)?', options: ['Son indistinguibles clínicamente', 'La sensitiva empeora marcadamente al cerrar los ojos (Romberg positivo) y el paciente mira al piso; la cerebelosa es de base amplia e irregular independientemente de la visión', 'La cerebelosa solo ocurre de noche', 'La sensitiva nunca se asocia a arreflexia'], correct: 1, explanation: 'La marcha atáxica sensitiva depende de la compensación visual (empeora al cerrar los ojos, el paciente mira el suelo), mientras que la cerebelosa es igual de inestable con los ojos abiertos o cerrados.', dificultad: 'intermedio' },
  { q: '¿Por qué la ausencia de los signos de Kernig y Brudzinski NO descarta una meningitis?', options: ['Porque estos signos nunca se han estudiado formalmente', 'Porque tienen una sensibilidad muy baja (5-10% en series validadas) en adultos con meningitis confirmada', 'Porque solo aplican en niños', 'Porque siempre son positivos si hay meningitis, así que su ausencia es imposible'], correct: 1, explanation: 'Estudios de validación muestran una sensibilidad muy baja de Kernig y Brudzinski para meningitis; la decisión de puncionar debe basarse en el cuadro clínico global, no en la negatividad aislada de estos signos.', dificultad: 'dificil' },
  { q: '¿Cómo se distingue la rigidez de nuca mecánica (artrosis cervical) de la meníngea?', options: ['No hay ninguna diferencia clínica', 'La mecánica limita TODOS los movimientos del cuello; la meníngea limita predominantemente la flexión, con relativa preservación de la rotación', 'La meníngea nunca limita la flexión', 'La mecánica siempre se acompaña de fiebre'], correct: 1, explanation: 'La rigidez mecánica limita el cuello en todas direcciones (flexión, extensión, rotación); la meníngea afecta predominantemente la flexión, respetando en mayor medida la rotación lateral.', dificultad: 'intermedio' },
  { q: '¿Cómo se define un signo de Babinski positivo?', options: ['Flexión plantar de todos los dedos al estimular la planta', 'Extensión (dorsiflexión) del hallux con apertura en abanico de los demás dedos', 'Ausencia total de respuesta al estímulo plantar', 'Dolor intenso al tocar la planta del pie'], correct: 1, explanation: 'El Babinski positivo es la extensión del hallux con apertura en abanico de los demás dedos al estimular el borde lateral de la planta, de talón a la base de los dedos.', dificultad: 'facil' },
  { q: '¿Por qué el Babinski es un hallazgo NORMAL en lactantes hasta los 2 años?', options: ['Porque los lactantes no tienen reflejos', 'Por la inmadurez de la mielinización de la vía corticoespinal, que aún no suprime el reflejo de retirada primitivo', 'Porque los huesos del pie del lactante son más flexibles', 'No es normal en ningún lactante'], correct: 1, explanation: 'La vía corticoespinal aún no está completamente mielinizada en el lactante, por lo que no logra suprimir el reflejo de retirada primitivo — de ahí que el Babinski extensor sea normal hasta los 2 años.', dificultad: 'intermedio' },
  { q: '¿Qué es el signo de Hoffmann y qué representa?', options: ['Un equivalente del Babinski en el miembro superior: flexión-aducción refleja del pulgar al percutir la falange distal del dedo medio', 'Una maniobra para explorar el nervio facial', 'Un signo meníngeo equivalente a Kernig', 'Una prueba de coordinación cerebelosa'], correct: 0, explanation: 'El signo de Hoffmann es el equivalente funcional del Babinski para el miembro superior, y su positividad también indica liberación piramidal (lesión de neurona motora superior).', dificultad: 'facil' },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente masculino de 58 años con cefalea súbita e intensa, ptosis palpebral derecha y diplopía. A la exploración, la pupila derecha está midriática y no reacciona a la luz.',
    steps: [
      { q: '¿Qué par craneal está más probablemente afectado?', options: ['II (óptico)', 'III (oculomotor)', 'VII (facial)', 'VI (abducens)'], correct: 1 },
      { q: 'Dado que la pupila está afectada (midriática, arreactiva), ¿qué causa se debe descartar con máxima urgencia?', options: ['Causa microvascular/diabética, sin urgencia inmediata', 'Aneurisma de la arteria comunicante posterior comprimiendo el nervio', 'Migraña oftalmopléjica benigna', 'Ninguna causa requiere estudio urgente'], correct: 1 },
      { q: '¿Qué estudio de imagen urgente está indicado?', options: ['Radiografía simple de cráneo', 'Angiografía/angio-TC o angio-RM cerebral para descartar aneurisma', 'Ecografía Doppler carotídea únicamente', 'Ninguno, se puede dar seguimiento ambulatorio'], correct: 1 }
    ],
    explanation: 'La combinación de cefalea súbita intensa, ptosis, diplopía y pupila midriática arreactiva (pupila "afectada") en una parálisis del III par es compatible con compresión aneurismática (clásicamente de la arteria comunicante posterior), una urgencia neuroquirúrgica que requiere angiografía urgente — a diferencia de una parálisis del III par con pupila respetada, más típica de causa microvascular.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente femenina de 70 años, hipertensa, con inicio súbito de debilidad en hemicuerpo derecho (cara, brazo y pierna) y dificultad para hablar. Al explorar la cara, puede arrugar la frente y cerrar ambos ojos con fuerza simétrica, pero la comisura bucal derecha está caída.',
    steps: [
      { q: '¿Qué tipo de parálisis facial presenta la paciente?', options: ['Periférica', 'Central (respeta la frente)', 'No hay parálisis facial', 'Bilateral'], correct: 1 },
      { q: 'Al evaluar el lenguaje, la paciente habla con esfuerzo, de forma no fluente, pero comprende relativamente bien las órdenes. ¿Qué afasia es más probable?', options: ['Afasia de Wernicke', 'Afasia de Broca', 'Afasia de conducción', 'No hay afasia, es disartria'], correct: 1 },
      { q: '¿Qué patrón de reflejos y tono esperarías encontrar en el hemicuerpo derecho, dado el cuadro agudo?', options: ['Hiperreflexia y espasticidad desde el primer minuto', 'Inicialmente pueden estar disminuidos (fase aguda) y evolucionar luego hacia hiperreflexia/espasticidad, un patrón de neurona motora superior', 'Hiporreflexia permanente, patrón de neurona motora inferior', 'No hay cambios esperables en reflejos ni tono'], correct: 1 }
    ],
    explanation: 'El cuadro integra hallazgos concordantes con un evento cerebrovascular que afecta la vía corticoespinal y el área frontal del lenguaje del hemisferio izquierdo: parálisis facial central (respeta la frente, por inervación bilateral de esa porción del núcleo), afasia de Broca (no fluente, comprensión relativamente conservada) y un patrón de neurona motora superior que, en la fase aguda, puede no mostrar aún la hiperreflexia/espasticidad clásicas.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente masculino de 30 años, tras una herida penetrante en el dorso a nivel torácico. Presenta debilidad y pérdida de la sensibilidad vibratoria en la pierna IZQUIERDA (lado de la herida), y pérdida de la sensibilidad al dolor y la temperatura en la pierna DERECHA.',
    steps: [
      { q: '¿Qué síndrome medular es más compatible con este patrón?', options: ['Síndrome medular central', 'Síndrome de Brown-Séquard (hemisección medular)', 'Siringomielia', 'Síndrome de cola de caballo'], correct: 1 },
      { q: '¿Por qué la pérdida de vibración/propiocepción es IPSILATERAL a la lesión?', options: ['Porque los cordones posteriores decusan inmediatamente en la médula', 'Porque los cordones posteriores ascienden ipsilaterales sin decusar hasta el bulbo, por lo que la lesión medular los afecta del mismo lado', 'Es un error, en realidad debería ser contralateral', 'La vibración no tiene relación con los cordones posteriores'], correct: 1 },
      { q: '¿Por qué la pérdida de dolor/temperatura es CONTRALATERAL a la lesión?', options: ['La vía espinotalámica decusa de inmediato, 1-2 segmentos por encima de su entrada, por lo que ya había cruzado al lado contrario antes de ser lesionada', 'El dolor nunca se transmite por la médula espinal', 'Es un error, en realidad debería ser ipsilateral', 'La vía espinotalámica no decusa nunca'], correct: 0 }
    ],
    explanation: 'El síndrome de Brown-Séquard (hemisección medular) produce un patrón disociado característico: pérdida motora y de sensibilidad vibratoria/posicional IPSILATERAL (los cordones posteriores aún no habían decusado) junto con pérdida de dolor/temperatura CONTRALATERAL (la vía espinotalámica ya había decusado antes del nivel de la lesión).'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente femenina de 24 años con fiebre, cefalea intensa y fotofobia de 12 horas de evolución. Al examen, rigidez de nuca marcada; Kernig y Brudzinski negativos.',
    steps: [
      { q: '¿La negatividad de Kernig y Brudzinski descarta el diagnóstico de meningitis?', options: ['Sí, si ambos son negativos se descarta meningitis', 'No, ambos signos tienen sensibilidad muy baja y su ausencia no descarta el diagnóstico', 'Solo descarta meningitis viral, no bacteriana', 'Solo son útiles en pacientes pediátricos'], correct: 1 },
      { q: '¿En qué debe basarse principalmente la decisión de realizar una punción lumbar en este caso?', options: ['Exclusivamente en la positividad de Kernig o Brudzinski', 'En el cuadro clínico global (fiebre, cefalea, fotofobia, rigidez de nuca), no en estos signos aislados', 'Solo si aparece un exantema petequial', 'Nunca debe realizarse si los signos meníngeos clásicos son negativos'], correct: 1 },
      { q: 'La rigidez de nuca de esta paciente limita predominantemente la flexión del cuello, con rotación lateral relativamente conservada. ¿Qué apoya esto?', options: ['Una causa mecánica/articular cervical', 'Un origen meníngeo, a diferencia de la rigidez mecánica que limita todos los movimientos por igual', 'Que no existe rigidez real', 'Que se trata de una contractura muscular voluntaria'], correct: 1 }
    ],
    explanation: 'Kernig y Brudzinski tienen sensibilidad muy baja para meningitis, así que su negatividad no descarta el diagnóstico; la decisión de puncionar se basa en el cuadro clínico completo. El patrón de rigidez de nuca que predomina en la flexión (con rotación relativamente conservada) es más compatible con un origen meníngeo que mecánico.'
  }
];

export const flashcards = [
  { front: 'Orden de la exploración neurológica', back: 'Estado mental → pares craneales → sistema motor (fuerza, tono, reflejos) → sensitivo → coordinación → marcha → signos meníngeos/reflejos patológicos (si hay sospecha).' },
  { front: 'Afasia de Broca', back: 'No fluente/esforzada, comprensión relativamente conservada, repetición alterada. Lesión frontal inferior.' },
  { front: 'Afasia de Wernicke', back: 'Fluente con parafasias, comprensión alterada, repetición alterada. Lesión temporal posterior.' },
  { front: 'Afasia de conducción', back: 'Repetición desproporcionadamente alterada vs. fluencia/comprensión conservadas. Lesión del fascículo arcuato.' },
  { front: 'Escala de Coma de Glasgow', back: 'Apertura ocular (4) + Verbal (5) + Motora (6) = 3-15. ≤8 → indicación de vía aérea avanzada. Reportar siempre desglosada.' },
  { front: 'Pupila de Argyll-Robertson', back: 'Reacciona a la acomodación pero NO a la luz → neurosífilis.' },
  { front: 'III par con pupila afectada vs. respetada', back: 'Afectada (midriática/arreactiva): causa COMPRESIVA (aneurisma) — urgente. Respetada: causa microvascular/isquémica (fibras pupilomotoras periféricas preservadas).' },
  { front: 'Síndrome de Horner', back: 'Ptosis + miosis + anhidrosis facial ipsilateral (vía oculosimpática de 3 neuronas) — se distingue del III par por la MIOSIS (no midriasis).' },
  { front: 'Parálisis facial central vs. periférica', back: 'Central: respeta la frente (inervación bilateral de esa porción del núcleo). Periférica: toda la hemicara, incluida la frente.' },
  { front: 'Weber: conductiva vs. neurosensorial', back: 'Conductiva: lateraliza AL oído afectado. Neurosensorial: lateraliza al oído SANO.' },
  { front: 'Hipogloso (XII) periférico', back: 'La lengua se desvía HACIA el lado de la lesión al protruir (geniogloso sano empuja desde el lado contrario).' },
  { front: 'Patrón de debilidad piramidal', back: 'Predomina en extensores de miembros superiores y flexores de miembros inferiores — distinto de la distribución radicular/troncular periférica.' },
  { front: 'Espasticidad vs. rigidez', back: 'Espasticidad: dependiente de velocidad, "signo de la navaja" (piramidal). Rigidez: independiente de velocidad, "rueda dentada"/"tubo de plomo" (extrapiramidal).' },
  { front: 'Shock medular', back: 'Hipotonía y arreflexia AGUDAS tras lesión medular, antes de que aparezca la espasticidad/hiperreflexia esperada.' },
  { front: 'Clono sostenido', back: 'Siempre patológico → lesión de neurona motora superior (pérdida de inhibición corticoespinal descendente).' },
  { front: 'Maniobra de Jendrassik', back: 'Refuerza un reflejo aparentemente abolido: traccionar las manos entrelazadas mientras se percute.' },
  { front: 'Vías sensitivas: espinotalámica vs. cordones posteriores', back: 'Espinotalámica (dolor/temperatura): decusa de inmediato en la médula. Cordones posteriores (vibración/posición): decusan hasta el bulbo.' },
  { front: 'Síndrome de Brown-Séquard', back: 'Hemisección medular: motor y vibración/posición IPSILATERAL; dolor/temperatura CONTRALATERAL.' },
  { front: 'Siringomielia', back: 'Pérdida SUSPENDIDA y bilateral de dolor/temperatura (comisura anterior); vibración/posición preservadas.' },
  { front: 'Romberg: qué evalúa realmente', back: 'Propiocepción/columna posterior — NO la función cerebelosa global.' },
  { front: 'Romberg: cerebeloso vs. sensitivo', back: 'Cerebeloso: negativo (inestable con ojos abiertos también). Sensitivo: positivo (empeora marcadamente al cerrar los ojos).' },
  { front: 'Marcha en steppage', back: 'Pie caído, eleva la rodilla exageradamente → debilidad de dorsiflexores (nervio peroneo, polineuropatía).' },
  { front: 'Marcha atáxica sensitiva vs. cerebelosa', back: 'Sensitiva: golpea el talón, mira al piso, empeora al cerrar los ojos. Cerebelosa: base amplia e irregular, igual con ojos abiertos o cerrados.' },
  { front: 'Sensibilidad Kernig/Brudzinski', back: 'Muy baja (5-10%) — su ausencia NO descarta meningitis; la decisión de puncionar se basa en el cuadro clínico global.' },
  { front: 'Rigidez de nuca mecánica vs. meníngea', back: 'Mecánica: limita todos los movimientos del cuello. Meníngea: predomina en la flexión, rotación relativamente conservada.' },
  { front: 'Signo de Babinski positivo', back: 'Extensión del hallux + abanico de los otros dedos. Normal solo hasta los 2 años (inmadurez de la vía corticoespinal).' },
  { front: 'Signo de Hoffmann', back: 'Equivalente del Babinski en el miembro superior: flexión-aducción del pulgar al percutir la falange distal del dedo medio.' },
  { front: 'UMN vs. LMN: patrón resumen', back: 'UMN: tono↑, reflejos↑, Babinski+, atrofia mínima, sin fasciculaciones. LMN: tono↓, reflejos↓, Babinski−, atrofia marcada, con fasciculaciones.' }
];

export default { quiz, flashcards };
