// topics/sepsis/study.js — Autoevaluación de Sepsis.
// Opciones reordenadas para cumplir .claude/skills/reglas-preguntas/SKILL.md — posición de `correct` distribuida sin patrón.

export const quiz = [
  { q:'¿Cuál es la definición de sepsis según Sepsis-3?', options:['Dos o más criterios de SIRS con infección', 'Bacteriemia documentada con fiebre alta', 'Disfunción orgánica por desregulación', 'Hipotensión que responde a los fluidos'], correct:2, explanation:'Sepsis-3 (2016) define sepsis como disfunción orgánica potencialmente mortal por una respuesta desregulada del huésped a la infección; el SIRS ya no forma parte de la definición.', dificultad:'facil' },
  { q:'El choque séptico se define por:', options:['Vasopresores para PAM ≥65 y lactato >2', 'Lactato >2 mmol/L de forma aislada', 'Hipotensión arterial que responde a fluidos', 'Un qSOFA mayor o igual a 2 puntos'], correct:0, explanation:'El choque séptico requiere vasopresores para mantener PAM ≥65 mmHg Y lactato >2 mmol/L a pesar de una reanimación con volumen adecuada; su mortalidad supera el 40%.', dificultad:'facil' },
  { q:'¿Qué componente NO forma parte del qSOFA?', options:['Frecuencia respiratoria ≥22/min', 'Presión arterial sistólica ≤100 mmHg', 'Alteración del estado mental', 'Lactato >2 mmol/L'], correct:3, explanation:'El qSOFA incluye frecuencia respiratoria ≥22, PAS ≤100 y alteración mental. El lactato no forma parte del qSOFA.', dificultad:'facil' },
  { q:'Dentro de la primera hora del bundle de sepsis, ¿qué se debe hacer respecto a los hemocultivos y antibióticos?', options:['Antibióticos tras confirmar el patógeno', 'Hemocultivos antes, sin retrasar', 'No tomar hemocultivos antes del antibiótico', 'Esperar 6 horas para el antibiótico'], correct:1, explanation:'Se obtienen hemocultivos antes de los antibióticos, pero sin retrasar el inicio de estos (idealmente <45 min) en sepsis/choque séptico.', dificultad:'facil' },
  { q:'Vasopresor de primera línea en el choque séptico:', options:['La dopamina IV', 'La adrenalina IV', 'La fenilefrina IV', 'La noradrenalina'], correct:3, explanation:'La noradrenalina es el vasopresor de primera línea; se añade vasopresina para reducir la dosis de noradrenalina o si no se alcanza la PAM meta.', dificultad:'facil' },
  { q:'Un aumento agudo de ≥2 puntos en la escala SOFA en un paciente con infección indica:', options:['Un cuadro de SIRS', 'Una sepsis establecida', 'Un choque séptico franco', 'Una bacteriemia aislada'], correct:1, explanation:'Un incremento agudo ≥2 puntos en SOFA respecto al basal, en el contexto de infección, es el criterio operacional de sepsis según Sepsis-3.', dificultad:'facil' },
  { q:'¿Cuáles son los 6 sistemas evaluados por la escala SOFA?', options:['Respiratorio, coagulación, hígado, cardiovascular, SNC y renal', 'Cardiovascular, digestivo, renal, hepático, endocrino y muscular', 'Respiratorio, cardiovascular, renal, hepático, hematológico y cutáneo', 'SNC, respiratorio, renal, endocrino, digestivo y cardiovascular'], correct:0, explanation:'El SOFA puntúa 0-4 en cada uno de 6 sistemas (respiratorio, coagulación, hígado, cardiovascular, SNC y renal), para un total de 0-24.', dificultad:'facil' },
  { q:'¿Cuál es la meta estándar de presión arterial media (PAM) en el choque séptico?', options:['≥50 mmHg', '≥80 mmHg', '≥65 mmHg', '≥100 mmHg'], correct:2, explanation:'La meta estándar es PAM ≥65 mmHg; la SSC 2026 permite una meta algo menor (60-65 mmHg) en pacientes ≥65 años.', dificultad:'facil' },
  { q:'¿Cuál es el volumen inicial recomendado de cristaloides en la reanimación de la sepsis con hipoperfusión?', options:['30 mL/kg en las primeras 3 horas', '10 mL/kg en las primeras 3 horas', '100 mL/kg en las primeras 3 horas', 'Sin volumen fijo, solo diuréticos'], correct:0, explanation:'Se recomiendan cristaloides ≥30 mL/kg IV en las primeras 3 horas en hipoperfusión inducida por sepsis, reevaluando la respuesta con parámetros dinámicos.', dificultad:'facil' },
  { q:'Según la definición de Berlín, ¿qué caracteriza al SDRA?', options:['Edema cardiogénico con PaO₂/FiO₂ normal', 'Derrame pleural aislado, sin hipoxemia', 'Inicio ≤1 semana, bilateral, PaO₂/FiO₂ ≤300', 'Neumonía unilateral con PaO₂/FiO₂ >300'], correct:2, explanation:'La definición de Berlín exige inicio ≤1 semana, infiltrados bilaterales no explicados por falla cardiaca/sobrecarga de volumen, y PaO₂/FiO₂ ≤300 con PEEP ≥5.', dificultad:'facil' },
  { q:'¿Qué escala se usa para cuantificar la coagulación intravascular diseminada (CID) manifiesta?', options:['El score de Lille', 'El score ISTH', 'El score de Ranson', 'El score APACHE II'], correct:1, explanation:'El score ISTH combina plaquetas, dímero D/PDF, TP prolongado y fibrinógeno; ≥5 puntos sugiere CID manifiesta.', dificultad:'facil' },
  { q:'¿Cómo se diagnostica la encefalopatía asociada a sepsis?', options:['Con un patrón específico en la resonancia', 'Únicamente con un electroencefalograma', 'Requiere punción lumbar para confirmar', 'Es un diagnóstico de exclusión'], correct:3, explanation:'Es un diagnóstico de exclusión: alteración mental en el contexto de sepsis, tras descartar meningitis/encefalitis, ACV y causas metabólicas o farmacológicas.', dificultad:'facil' },
  { q:'¿Qué papel tiene el qSOFA en el diagnóstico de sepsis?', options:['Una herramienta de alerta de riesgo', 'El criterio diagnóstico oficial de sepsis', 'Sustituye al SOFA en pacientes de UCI', 'Solo sirve para decidir el alta hospitalaria'], correct:0, explanation:'El qSOFA es una herramienta de tamizaje rápido fuera de UCI; identifica mayor riesgo pero el diagnóstico formal de sepsis requiere el criterio SOFA (Δ≥2) en el contexto de infección.', dificultad:'facil' },
  { q:'¿Qué caracteriza al SOFA-2 (2025) frente al SOFA clásico (1996)?', options:['Elimina dos de los seis sistemas evaluados', 'Solo se aplica a pacientes ambulatorios', 'No requiere validación en estudios amplios', 'Actualiza umbrales de los mismos 6'], correct:3, explanation:'El SOFA-2 conserva los mismos 6 sistemas pero actualiza umbrales y variables (p. ej. tipos de soporte ventilatorio y vasopresor actuales); fue validado en más de 3 millones de pacientes de 9 países (Ranzani et al. 2025).', dificultad:'intermedio' },
  { q:'En un paciente con choque séptico y disfunción cardiaca concomitante con bradiarritmia, ¿qué vasopresor de primera línea es preferible según la SSC 2026?', options:['La noradrenalina', 'La fenilefrina', 'La adrenalina', 'La dopamina'], correct:2, explanation:'Si hay disfunción cardiaca concomitante, noradrenalina o adrenalina son opciones de primera línea; se prefiere adrenalina si hay bradiarritmia y noradrenalina si hay taquiarritmia.', dificultad:'intermedio' },
  { q:'¿En qué momento se recomienda agregar vasopresina al esquema de un paciente en choque séptico?', options:['Si persiste hipotensión con dosis altas', 'Desde el inicio, con la noradrenalina', 'Solo si el paciente ya recibe hidrocortisona', 'No tiene un rol claro en el choque séptico'], correct:0, explanation:'La vasopresina (dosis fija 0.03 U/min) se añade cuando persiste hipotensión pese a dosis crecientes de noradrenalina (equivalente ≈0.3 mcg/kg/min), como estrategia ahorradora de catecolaminas.', dificultad:'intermedio' },
  { q:'¿Cuándo está indicada la hidrocortisona en el choque séptico?', options:['En todo paciente, desde el diagnóstico', 'Solo si hay insuficiencia suprarrenal', 'En choque refractario, 200 mg IV/día', 'No se recomienda en la sepsis grave'], correct:2, explanation:'La hidrocortisona (200 mg IV/día en dosis fraccionadas) se reserva para el choque séptico refractario a líquidos y vasopresores, sin necesidad de confirmar insuficiencia suprarrenal.', dificultad:'intermedio' },
  { q:'Según la SSC 2026, ¿cuál es el tiempo objetivo de antibiótico en un paciente con sepsis probable o definida, sin choque?', options:['Menos de 3 horas', 'Menos de 1 hora', 'Menos de 6 horas', 'Sin límite definido'], correct:1, explanation:'Tanto en choque séptico como en sepsis probable o definida sin choque, el objetivo es iniciar antimicrobianos en <1 hora.', dificultad:'intermedio' },
  { q:'¿Qué conducta recomienda la SSC 2026 ante sepsis "posible" (sin choque, sin confirmación clara de infección)?', options:['Antibiótico de amplio espectro de inmediato', 'Diferir el estudio hasta nuevos síntomas', 'TC de cuerpo entero antes de cualquier decisión', 'Evaluación rápida y tratar si persiste'], correct:3, explanation:'En sepsis posible sin choque, se recomienda una evaluación rápida de causas infecciosas vs. no infecciosas, iniciando antibiótico si persiste la sospecha, con un objetivo de tiempo <3 horas.', dificultad:'intermedio' },
  { q:'¿Cuál es el manejo ventilatorio protector recomendado en el SDRA?', options:['Volumen tidal 6 mL/kg de peso ideal, con presión meseta <30 cmH₂O', 'Volumen tidal 10-12 mL/kg de peso ideal, sin límite de presión meseta', 'Ventilación con presión positiva continua únicamente, sin volumen controlado', 'Volumen tidal alto con PEEP mínima'], correct:0, explanation:'La ventilación protectora usa Vt 6 mL/kg de peso ideal, manteniendo presión meseta <30 cmH₂O, para minimizar el daño pulmonar inducido por el ventilador.', dificultad:'intermedio' },
  { q:'¿En qué situación se recomienda la posición prona en el SDRA asociado a sepsis?', options:['En todo SDRA, sin importar la gravedad', 'Solo en ambulatorios con hipoxemia leve', 'No se recomienda en el SDRA por sepsis', 'Con PaO₂/FiO₂ <150 pese a protección'], correct:3, explanation:'La posición prona está indicada en SDRA moderado-grave con PaO₂/FiO₂ <150 pese a una ventilación protectora ya optimizada, ya que mejora la oxigenación y la supervivencia.', dificultad:'intermedio' },
  { q:'¿Cuáles son los criterios KDIGO para lesión renal aguda (LRA) que se aplican en el contexto de sepsis?', options:['Creatinina ↑0.3 en 48h o diuresis baja', 'Solo diuresis menor de 100 mL en 24 h', 'Creatinina mayor de 5 mg/dL al ingreso', 'Solo la necesidad de diálisis urgente'], correct:0, explanation:'Los criterios KDIGO de LRA incluyen cualquiera de: creatinina ↑≥0.3 mg/dL en 48h, ↑≥1.5× el basal en 7 días, o diuresis <0.5 mL/kg/h durante 6 horas.', dificultad:'intermedio' },
  { q:'¿Cuál es el papel de los diuréticos en la lesión renal aguda asociada a sepsis?', options:['Se recomiendan de rutina para prevenir la progresión de la LRA', 'No se recomienda su uso para prevenir o tratar la LRA asociada a sepsis', 'Son el tratamiento de elección junto con la terapia de reemplazo renal', 'Deben iniciarse antes que la optimización de la PAM'], correct:1, explanation:'No se recomienda el uso de diuréticos para prevenir ni tratar la LRA en sepsis; el manejo se centra en optimizar la perfusión renal (PAM adecuada) y evitar nefrotóxicos.', dificultad:'intermedio' },
  { q:'¿Cuáles son indicaciones para iniciar terapia de reemplazo renal (TRR) en la LRA asociada a sepsis?', options:['Cualquier LRA en estadio KDIGO 1', 'Solo la creatinina absoluta >2 mg/dL', 'Hiperkalemia, acidosis o uremia', 'Solo si ya está en choque séptico'], correct:2, explanation:'La TRR se indica ante hiperkalemia refractaria al tratamiento médico, acidosis grave, sobrecarga de volumen resistente a diuréticos, o uremia sintomática — no por un valor aislado de creatinina.', dificultad:'intermedio' },
  { q:'¿Cuándo está indicada la transfusión de plaquetas, plasma o crioprecipitado en un paciente con CID?', options:['De forma profiláctica en cualquier CID', 'Solo con sangrado o procedimiento', 'Únicamente si el fibrinógeno es normal', 'No se indican en la CID asociada a sepsis'], correct:1, explanation:'En la CID, los hemoderivados se transfunden solo ante sangrado activo o antes de un procedimiento invasivo; la base del tratamiento es controlar la causa (la sepsis).', dificultad:'intermedio' },
  { q:'¿Qué papel tiene el tiempo de llenado capilar en la reanimación del choque séptico según la SSC 2026?', options:['Sustituye por completo al lactato', 'No se le reconoce un rol claro', 'Parámetro adicional, evidencia baja', 'Solo se usa en pediatría, no en adultos'], correct:2, explanation:'La SSC 2026 reconoce el tiempo de llenado capilar como parámetro adicional (junto al lactato) para guiar la reanimación, aunque con evidencia de certeza baja.', dificultad:'intermedio' },
  { q:'¿En qué situación se recomienda considerar el antibiótico prehospitalario en un paciente con sospecha de choque séptico?', options:['Si el traslado supera los 60 minutos', 'Es preferible esperar al hospital', 'Solo si el propio paciente lo solicita', 'Únicamente en pacientes pediátricos'], correct:0, explanation:'Se sugiere considerar el antibiótico prehospitalario si el traslado al hospital se prevé mayor a 60 minutos, para no retrasar el inicio del tratamiento en choque séptico.', dificultad:'intermedio' },
  { q:'Paciente en choque séptico con PAM 50 mmHg pese a 30 mL/kg de cristaloides, con signos de hipoperfusión activa. ¿Cuál es la conducta más apropiada respecto a fluidos y vasopresor?', options:['Más bolos de cristaloides antes del vasopresor', 'Esperar 6 horas más antes de reevaluar', 'Iniciar hidrocortisona, sin vasopresor', 'Fluidos y vasopresor a la vez'], correct:3, explanation:'En el choque séptico marcadamente inestable, la SSC 2026 permite iniciar líquidos y vasopresor de forma simultánea, en lugar de esperar a completar el bolo completo antes de iniciar el vasopresor.', dificultad:'dificil' },
  { q:'Un paciente con SOFA-2 recibe soporte con cánula de alto flujo por hipoxemia, con PaO₂/FiO₂ de 160. ¿Qué puntaje respiratorio máximo podría alcanzar según el SOFA-2 si NO cuenta con soporte ventilatorio avanzado adicional?', options:['2 puntos, por el tope sin soporte', '4 puntos, como con ventilación invasiva', '0 puntos, porque la cánula no cuenta', 'No puede calcularse sin gasometría'], correct:0, explanation:'Según el SOFA-2, sin soporte ventilatorio avanzado (ventilación mecánica invasiva, CPAP, BiPAP, VNI o ECMO) el puntaje respiratorio máximo es 2, incluso con hipoxemia marcada, salvo que dicho soporte no esté disponible o esté limitado por un techo terapéutico.', dificultad:'dificil' },
  { q:'Paciente con choque séptico recibe noradrenalina hasta 0.35 mcg/kg/min más vasopresina, y persiste con PAM 58 mmHg. ¿Cuál es el siguiente paso farmacológico según la SSC 2026?', options:['Aumentar la vasopresina por encima de la dosis fija recomendada', 'Suspender todo vasopresor y reiniciar solo con líquidos', 'Cambiar a dopamina en monoterapia', 'Añadir adrenalina si la PAM sigue siendo inadecuada'], correct:3, explanation:'Si la PAM permanece inadecuada pese a noradrenalina en dosis crecientes más vasopresina, el siguiente paso es añadir adrenalina; la vasopresina se mantiene en su dosis fija (0.03 U/min), sin escalarla.', dificultad:'dificil' },
  { q:'Paciente cirrótico con sepsis de origen urinario, creatinina basal 0.9 mg/dL, que sube a 1.3 mg/dL en 24h con diuresis conservada, sodio urinario <10 mEq/L y sedimento blando. ¿Qué diagnóstico diferencial es más relevante distinguir de la LRA asociada a sepsis en este contexto, y con qué hallazgo?', options:['Nefropatía obstructiva, según la edad', 'Glomerulonefritis, sin biopsia no se sabe', 'Necrosis tubular: sodio alto y cilindros', 'No hay un diferencial relevante aquí'], correct:2, explanation:'En un paciente con hepatopatía de base, debe distinguirse la LRA prerrenal/asociada a sepsis (sodio urinario bajo, sedimento blando) de la necrosis tubular aguda, que típicamente cursa con sodio urinario más elevado y cilindros granulosos por daño tubular estructural.', dificultad:'dificil' },
  { q:'Un paciente con choque séptico por neumonía recibe antibiótico empírico de amplio espectro. A las 72 horas, los cultivos identifican un neumococo sensible y el paciente mejora clínicamente. ¿Cuál es la conducta recomendada sobre la antibioticoterapia?', options:['Mantener el amplio espectro por seguridad', 'Desescalar según el antibiograma', 'Suspender todo el antibiótico de inmediato', 'Agregar un segundo antibiótico de refuerzo'], correct:1, explanation:'Identificado un patógeno sensible y con mejoría clínica, se debe desescalar a terapia dirigida; la duración del tratamiento se apoya en la evolución clínica y, si está disponible, en la procalcitonina, evitando la exposición innecesaria a antibióticos de amplio espectro.', dificultad:'dificil' },
  { q:'Paciente con choque séptico de foco abdominal (absceso no drenado) que persiste con inestabilidad hemodinámica pese a antibiótico adecuado y vasopresor. ¿Cuál es la intervención más urgente pendiente?', options:['Control del foco: drenar el absceso', 'Aumentar la dosis del antibiótico', 'Esperar la mejoría antes de drenar', 'Cambiar por otro antibiótico similar'], correct:0, explanation:'Cuando existe un foco no controlado (absceso, colección), el control del foco —idealmente dentro de las primeras 6 horas— es indispensable; ningún ajuste antibiótico o de vasopresor sustituye el drenaje o desbridamiento de la fuente infecciosa.', dificultad:'dificil' },
  { q:'Un paciente con SDRA grave asociado a sepsis (PaO₂/FiO₂ 65) no mejora pese a ventilación protectora, posición prona y bloqueo neuromuscular. ¿Qué opción de rescate debe considerarse en un centro especializado?', options:['Aumentar el volumen tidal por encima de 6 mL/kg para mejorar la ventilación', 'Suspender la sedación por completo para despertar al paciente', 'Traqueostomía inmediata como única medida de rescate', 'ECMO venovenoso'], correct:3, explanation:'En SDRA grave refractario a ventilación protectora, prona y bloqueo neuromuscular, el ECMO venovenoso es la opción de rescate en centros especializados con experiencia en su manejo.', dificultad:'dificil' }
];

export const flashcards = [
  { front:'Definición de sepsis (Sepsis-3)', back:'Disfunción orgánica potencialmente mortal por una respuesta desregulada del huésped a la infección (incremento agudo ≥2 en SOFA).' },
  { front:'Definición de choque séptico', back:'Vasopresores para PAM ≥65 mmHg + lactato >2 mmol/L pese a reanimación adecuada. Mortalidad >40%.' },
  { front:'Componentes del qSOFA', back:'FR ≥22/min, alteración mental (Glasgow <15), PAS ≤100 mmHg. ≥2 = alerta.' },
  { front:'Meta de PAM en choque séptico', back:'≥65 mmHg (60-65 mmHg en ≥65 años, SSC 2026).' },
  { front:'Volumen inicial en la reanimación de sepsis', back:'Cristaloides 30 mL/kg IV, guiados por parámetros dinámicos; reevaluar para evitar sobrecarga.' },
  { front:'Vasopresor de primera línea', back:'Noradrenalina (añadir vasopresina; hidrocortisona si el choque es refractario).' },
  { front:'Los 6 sistemas de la escala SOFA', back:'Respiratorio, coagulación, hígado, cardiovascular, SNC y renal (0-4 cada uno; total 0-24).' },
  { front:'Meta de aclaramiento de lactato', back:'≥10% (o normalización); guía la respuesta a la reanimación.' },
  { front:'SOFA-2 vs. SOFA clásico', back:'Mismos 6 sistemas, umbrales y variables actualizados (soporte ventilatorio/vasopresor contemporáneo). No intercambiables. OR 1.38 de mortalidad por punto.' },
  { front:'¿Cuándo agregar vasopresina en choque séptico?', back:'Si persiste hipotensión con noradrenalina en dosis crecientes (equivalente ≈0.3 mcg/kg/min). Dosis fija 0.03 U/min.' },
  { front:'Hidrocortisona en choque séptico', back:'200 mg IV/día (dosis fraccionadas), reservada para choque refractario a líquidos y vasopresores.' },
  { front:'Tiempo objetivo de antibiótico en choque séptico o sepsis definida', back:'<1 hora (SSC 2026).' },
  { front:'Tiempo objetivo en sepsis "posible", sin choque', back:'<3 horas: evaluación rápida infecciosa vs. no infecciosa.' },
  { front:'Criterios de Berlín para SDRA', back:'Inicio ≤1 semana, infiltrados bilaterales no cardiogénicos, PaO₂/FiO₂ ≤300 con PEEP ≥5.' },
  { front:'Ventilación protectora en SDRA', back:'Vt 6 mL/kg de peso ideal, presión meseta <30 cmH₂O.' },
  { front:'Indicación de posición prona en SDRA', back:'PaO₂/FiO₂ <150 pese a ventilación protectora optimizada.' },
  { front:'Rescate en SDRA grave refractario', back:'ECMO venovenoso, en centro especializado.' },
  { front:'Criterios KDIGO de LRA', back:'Creatinina ↑≥0.3 mg/dL en 48h, o ↑≥1.5× basal en 7 días, o diuresis <0.5 mL/kg/h por 6h.' },
  { front:'¿Diuréticos para prevenir/tratar la LRA en sepsis?', back:'No se recomiendan; optimizar PAM y volemia, evitar nefrotóxicos.' },
  { front:'Indicaciones de terapia de reemplazo renal en LRA asociada a sepsis', back:'Hiperkalemia refractaria, acidosis grave, sobrecarga de volumen o uremia sintomática (no un valor aislado de creatinina).' },
  { front:'Score ISTH para CID', back:'Plaquetas, dímero D/PDF, TP y fibrinógeno; ≥5 puntos = CID manifiesta.' },
  { front:'¿Cuándo transfundir en CID?', back:'Solo si hay sangrado activo o antes de un procedimiento invasivo; la clave es controlar la sepsis.' },
  { front:'Encefalopatía asociada a sepsis', back:'Diagnóstico de exclusión; evitar benzodiacepinas, vigilar con CAM-ICU.' },
  { front:'Control del foco infeccioso', back:'Drenaje/desbridamiento idealmente dentro de las primeras 6 horas del diagnóstico.' }
];

export const caseSteps = [
  { vignette: 'Varón de 68 años con tos, fiebre 39 °C y confusión. FR 26/min, PA 92/58 mmHg, FC 118 lpm, SpO₂ 90%. ¿Cuál es tu primera evaluación de riesgo junto a la cama?', options: ['Esperar los cultivos antes de actuar', 'Calcular qSOFA (FR ≥22, alteración mental, PAS ≤100)', 'Solicitar TC de tórax antes de cualquier medida', 'Dar de alta con antibiótico oral'], correct: 1, explanation: 'El qSOFA es positivo (3/3: FR ≥22, confusión, PAS ≤100), lo que identifica alto riesgo y obliga a evaluar disfunción orgánica e iniciar el manejo de sepsis.' },
  { vignette: 'El lactato inicial es 4.5 mmol/L y hay hipotensión. Según el bundle de 1 hora, ¿qué haces en esta hora?', options: ['Solo observación', 'Iniciar corticoides como primera medida', 'Transfundir concentrados eritrocitarios', 'Hemocultivos, antibiótico de amplio espectro y cristaloides'], correct: 3, explanation: 'El bundle de 1 hora: medir lactato, hemocultivos antes de antibióticos, antibiótico de amplio espectro, cristaloides 30 mL/kg si hipotensión o lactato ≥4, y vasopresores si persiste la hipotensión.' },
  { vignette: 'Tras 30 mL/kg de cristaloides persiste PAM de 58 mmHg. ¿Cuál es el siguiente paso?', options: ['Iniciar noradrenalina para meta de PAM ≥65 mmHg', 'Más bolos de fluidos sin límite', 'Iniciar dopamina de primera línea', 'Suspender antibióticos'], correct: 0, explanation: 'Si la hipotensión persiste pese a la reanimación con volumen, se inicia noradrenalina (primera línea) para alcanzar una PAM ≥65 mmHg.' },
  { vignette: 'Con noradrenalina se alcanza PAM 68 mmHg. El lactato de control a las 3 h es 2.4 mmol/L. ¿Cómo interpretas la respuesta?', options: ['Empeoramiento: aumentar drásticamente los fluidos', 'Sin utilidad: el lactato no sirve para seguimiento', 'Aclaramiento de lactato ~47%: respuesta adecuada a la reanimación', 'Suspender vasopresores de inmediato'], correct: 2, explanation: 'El aclaramiento ((4.5−2.4)/4.5 ≈ 47%) es ≥10%, lo que indica buena respuesta a la reanimación; se continúa reevaluando la perfusión.' },
  { vignette: 'A las 24 h, con cultivos que muestran neumococo sensible, ¿qué haces con los antibióticos?', options: ['Mantener el esquema de amplio espectro indefinidamente', 'Desescalar a terapia dirigida según el antibiograma y valorar la duración', 'Suspender todos los antibióticos', 'Añadir un antifúngico empírico'], correct: 1, explanation: 'Con un patógeno identificado y sensible, se desescala a terapia dirigida y se evalúa la duración (apoyándose en la evolución clínica y, si se usa, la procalcitonina).' },
  { vignette: 'El paciente se recupera y va a ser dado de alta tras 8 días de hospitalización, 3 de ellos en UCI con ventilación mecánica. ¿Qué debes considerar antes del alta, además de completar el antibiótico?', options: ['Ninguna medida adicional; el episodio de sepsis ya se resolvió', 'Indicar reposo absoluto sin ningún seguimiento programado', 'Suspender toda medicación crónica que tomaba antes del ingreso', 'Evaluar secuelas del síndrome post-cuidados intensivos (debilidad, deterioro cognitivo, síntomas psicológicos) y planear seguimiento/rehabilitación'], correct: 3, explanation: 'La supervivencia a la sepsis grave con estancia en UCI se asocia a síndrome post-cuidados intensivos (debilidad neuromuscular, deterioro cognitivo, ansiedad/depresión/estrés postraumático); debe planearse la vigilancia y rehabilitación correspondiente al alta.' }
];

export const caseSummary = 'Este caso integró el reconocimiento con qSOFA, el bundle de sepsis de 1 hora, la noradrenalina como vasopresor de primera línea, el aclaramiento de lactato como guía de reanimación, la desescalada antibiótica y la vigilancia de secuelas post-UCI. Repasa la sección de Complicaciones y los protocolos "Bundle de sepsis (1 hora)".';

export default { quiz, flashcards, caseSteps, caseSummary };
