// topics/deterioro-cognitivo-demencias/study.js: Autoevaluacion de Deterioro Cognitivo y Demencias.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// 48 subpreguntas (30 sueltas + 6 cascadas de 3 pasos) y 32 tarjetas.
// Sin em dash (ver [[feedback-no-em-dash]]). Texto sin acentos.

export const quiz = [
  { q: 'Que separa el deterioro cognitivo leve de la demencia?', options: ['La perdida de autonomia instrumental', 'La puntuacion del Mini-Mental', 'La presencia de atrofia hipocampal', 'El numero de dominios afectados'], correct: 0, explanation: 'La linea no la marca ningun test ni ninguna imagen: si el paciente ya necesita ayuda para manejar su dinero, su medicacion o sus desplazamientos, es demencia. Si conserva esa autonomia aunque le cueste mas, es deterioro cognitivo leve.', dificultad: 'facil' },
  { q: 'Por que es imprescindible hablar con un informante?', options: ['Porque acorta el tiempo de consulta', 'Porque sustituye al cribado cognitivo', 'Porque el paciente puede minimizar o exagerar', 'Porque permite descartar la depresion'], correct: 2, explanation: 'El paciente con anosognosia resta importancia al problema y el que tiene depresion lo exagera. Hay que preguntar al informante por hechos concretos: quien paga los recibos, si se toma la medicacion solo, si se ha perdido alguna vez.', dificultad: 'facil' },
  { q: 'Que dato apunta a delirium y no a demencia?', options: ['La perdida de memoria episodica', 'La atrofia en la neuroimagen', 'El deterioro de meses de evolucion', 'La alteracion de la ATENCION'], correct: 3, explanation: 'El delirium se define por el inicio agudo, el curso fluctuante y la alteracion de la atencion. Ademas, el diagnostico de demencia no puede establecerse durante un delirium: hay que reevaluar la cognicion cuando el episodio agudo se haya resuelto.', dificultad: 'intermedio' },
  { q: 'Que prueba forma parte del estudio minimo de TODO deterioro cognitivo?', options: ['La puncion lumbar con biomarcadores', 'La vitamina B12', 'El electroencefalograma', 'El estudio genetico de APOE'], correct: 1, explanation: 'A todos se les pide hemograma, bioquimica con calcio, funcion renal y hepatica, hormona tiroestimulante, vitamina B12 y neuroimagen estructural. Las otras tres pruebas se reservan a situaciones concretas.', dificultad: 'facil' },
  { q: 'Que significa un hemograma normal en la sospecha de deficit de vitamina B12?', options: ['Descarta el deficit funcional', 'Obliga a pedir folato en su lugar', 'NO descarta el deficit', 'Indica que el deficit es reciente'], correct: 2, explanation: 'El deficit de B12 puede producir deterioro cognitivo sin anemia y sin macrocitosis. Si el valor queda en zona baja-normal, el acido metilmalonico elevado confirma el deficit funcional.', dificultad: 'intermedio' },
  { q: 'Que lesiones tratables busca la neuroimagen en el deterioro cognitivo?', options: ['Subdural, hidrocefalia y tumor', 'Placas de amiloide corticales', 'Ovillos neurofibrilares', 'Cuerpos de Lewy corticales'], correct: 0, explanation: 'Ese es el motivo principal por el que se pide a todos: el hematoma subdural cronico, la hidrocefalia normotensiva y el tumor tienen tratamiento. De paso informa del patron de atrofia y de la carga vascular.', dificultad: 'facil' },
  { q: 'Cual es el sintoma inicial tipico de la enfermedad de Alzheimer?', options: ['La desinhibicion conductual', 'La amnesia episodica', 'La alteracion de la marcha', 'Las alucinaciones visuales'], correct: 1, explanation: 'La patologia empieza en la corteza entorrinal y el hipocampo, lo que explica que lo primero que falle sea la memoria de hechos recientes. La marcha se afecta tarde, y las tres opciones restantes apuntan a otras demencias.', dificultad: 'facil' },
  { q: 'Que significa que la memoria MEJORE al dar pistas?', options: ['Que el perfil es tipico de Alzheimer', 'Que hay atrofia hipocampal marcada', 'Que se trata de una demencia avanzada', 'Que el fallo esta en la recuperacion'], correct: 3, explanation: 'Si la pista ayuda, el dato estaba almacenado y el problema es de acceso: apunta a un perfil ejecutivo o subcortical, tipico de la demencia vascular. En el Alzheimer la pista no ayuda porque el dato nunca llego a almacenarse.', dificultad: 'dificil' },
  { q: 'Que perfil caracteriza a la demencia vascular?', options: ['Amnesico de inicio insidioso', 'Conductual con memoria conservada', 'Ejecutivo con marcha alterada pronto', 'Visuoespacial con alucinaciones'], correct: 2, explanation: 'La enfermedad de peque&#241;o vaso desconecta los circuitos frontosubcorticales, lo que produce enlentecimiento, dificultad para planificar, apatia y alteracion precoz de la marcha y del control de esfinteres.', dificultad: 'intermedio' },
  { q: 'Que sugiere una escala isquemica de Hachinski de 9 puntos?', options: ['Un origen degenerativo primario', 'Un origen vascular', 'Una demencia con cuerpos de Lewy', 'Una hidrocefalia normotensiva'], correct: 1, explanation: '7 o mas apoya el origen vascular y 4 o menos el degenerativo. Los valores intermedios no discriminan y son compatibles con forma mixta, que en el paciente mayor es probablemente lo mas frecuente.', dificultad: 'intermedio' },
  { q: 'Cuales son los rasgos centrales de la demencia con cuerpos de Lewy?', options: ['Fluctuacion, alucinaciones, REM y parkinsonismo', 'Amnesia, afasia, apraxia y agnosia', 'Alteracion de la marcha, incontinencia y deterioro', 'Desinhibicion, apatia y hiperoralidad'], correct: 0, explanation: 'Fluctuacion de la cognicion y la alerta, alucinaciones visuales bien formadas y recurrentes, trastorno de conducta del sue&#241;o REM y parkinsonismo espontaneo. La tercera opcion describe la hidrocefalia normotensiva y la cuarta la degeneracion frontotemporal.', dificultad: 'intermedio' },
  { q: 'Que significa que el paciente hable o se mueva mientras sue&#241;a?', options: ['Que tiene apnea obstructiva del sue&#241;o', 'Que padece un sindrome de piernas inquietas', 'Que sufre terrores nocturnos del adulto', 'Que puede ser una sinucleinopatia'], correct: 3, explanation: 'El trastorno de conducta del sue&#241;o REM es un rasgo central de la demencia con cuerpos de Lewy y puede preceder en a&#241;os al resto de los sintomas. Hay que preguntarlo de forma explicita a la pareja de cama, porque el paciente no lo sabe.', dificultad: 'dificil' },
  { q: 'Que farmacos hay que evitar en la demencia con cuerpos de Lewy?', options: ['Los anticolinesterasicos', 'Los antipsicoticos tipicos', 'La melatonina nocturna', 'Los inhibidores de la recaptacion de serotonina'], correct: 1, explanation: 'La sensibilidad puede producir rigidez grave, deterioro del nivel de conciencia y un cuadro parecido al sindrome neuroleptico maligno. Si un antipsicotico es imprescindible, quetiapina o clozapina a dosis minimas y con vigilancia estrecha.', dificultad: 'intermedio' },
  { q: 'Que distingue la demencia con cuerpos de Lewy de la demencia de la enfermedad de Parkinson?', options: ['El tipo de alucinaciones que presenta', 'La respuesta a la levodopa', 'El orden temporal de los sintomas', 'La presencia de trastorno del sue&#241;o REM'], correct: 2, explanation: 'Es la regla del a&#241;o: si la demencia precede al parkinsonismo o aparece en el a&#241;o siguiente, es demencia con cuerpos de Lewy; si el parkinsonismo lleva mas de un a&#241;o, es demencia de la enfermedad de Parkinson. Comparten sustrato, pronostico y precauciones.', dificultad: 'dificil' },
  { q: 'Que caracteriza al inicio de la degeneracion frontotemporal?', options: ['La amnesia episodica progresiva', 'La alteracion visuoespacial precoz', 'El parkinsonismo asimetrico', 'El cambio de conducta y de personalidad'], correct: 3, explanation: 'Desinhibicion, apatia, perdida de empatia, conductas repetitivas e hiperoralidad, con memoria y capacidad visuoespacial relativamente conservadas. Se etiqueta como enfermedad psiquiatrica durante a&#241;os, sobre todo porque el paciente es mas joven.', dificultad: 'intermedio' },
  { q: 'Que papel tienen los anticolinesterasicos en la degeneracion frontotemporal?', options: ['NO estan indicados y pueden empeorar', 'Son el tratamiento de primera linea', 'Mejoran el lenguaje en las afasias', 'Retrasan la progresion a la fase grave'], correct: 0, explanation: 'No hay deficit colinergico que justifique su uso y pueden agravar la conducta. Lo que si puede ayudar sobre la desinhibicion y las conductas repetitivas son los inhibidores de la recaptacion de serotonina.', dificultad: 'dificil' },
  { q: 'Con que enfermedad se asocia la degeneracion frontotemporal por C9orf72?', options: ['Con la enfermedad de Huntington juvenil', 'Con la esclerosis multiple', 'Con la esclerosis lateral amiotrofica', 'Con la ataxia de Friedreich'], correct: 2, explanation: 'Un mismo paciente o una misma familia puede presentar ambas. Por eso, ante una degeneracion frontotemporal hay que explorar de forma dirigida los signos de motoneurona, cuya presencia cambia el pronostico y el manejo.', dificultad: 'dificil' },
  { q: 'Que implica una demencia que progresa en semanas o pocos meses?', options: ['Que es necesariamente una enfermedad prionica', 'Que es una urgencia diagnostica', 'Que corresponde iniciar cuidados paliativos', 'Que hay que repetir el cribado en 6 meses'], correct: 1, explanation: 'Una parte importante de las demencias rapidamente progresivas tiene causa TRATABLE: autoinmune, infecciosa, neoplasica o toxico-metabolica. El estudio se hace en paralelo y sin demora, no de forma secuencial.', dificultad: 'intermedio' },
  { q: 'Que hay que descartar antes en una demencia rapidamente progresiva?', options: ['La enfermedad de Creutzfeldt-Jakob', 'La degeneracion frontotemporal', 'La enfermedad de Alzheimer atipica', 'Las causas tratables'], correct: 3, explanation: 'Encefalitis autoinmune y paraneoplasica, infecciones, neoplasia, vasculitis, estado epileptico no convulsivo y causas toxico-metabolicas. La enfermedad prionica es un diagnostico al que se llega por exclusion de lo tratable, no de entrada.', dificultad: 'intermedio' },
  { q: 'Que secuencia de resonancia hay que pedir de forma explicita ante sospecha de priones?', options: ['La difusion', 'La perfusion', 'La angiografia', 'La espectroscopia'], correct: 0, explanation: 'La hiperintensidad cortical en cinta y en ganglios basales aparece en difusion y es el hallazgo mas sensible. Un protocolo estandar puede no incluirla, y entonces el dato se pierde.', dificultad: 'dificil' },
  { q: 'Cual es hoy la prueba de referencia en liquido cefalorraquideo para los priones?', options: ['La proteina 14-3-3', 'La RT-QuIC', 'La enolasa neuroespecifica', 'La proteina tau total'], correct: 1, explanation: 'Es muy especifica. La 14-3-3 y la enolasa son inespecificas y se elevan en cualquier da&#241;o neuronal rapido, incluido un ictus reciente, de modo que su positividad aislada no permite concluir nada.', dificultad: 'dificil' },
  { q: 'Que precaucion especifica exige la enfermedad por priones?', options: ['Aislamiento respiratorio del paciente', 'Aislamiento de contacto estricto', 'Vacunacion de los convivientes', 'Protocolo especial del instrumental'], correct: 3, explanation: 'El prion resiste los metodos habituales de esterilizacion, de modo que ante un procedimiento neuroquirurgico invasivo hay que avisar al servicio. En cambio, el contacto habitual con el paciente no requiere precauciones especiales.', dificultad: 'intermedio' },
  { q: 'Que hay que hacer antes de dar un antipsicotico por agitacion en la demencia?', options: ['Buscar dolor, infeccion o retencion urinaria', 'Aumentar la dosis del anticolinesterasico', 'Solicitar una neuroimagen urgente', 'Iniciar una benzodiacepina de vida corta'], correct: 0, explanation: 'La agitacion en la demencia casi siempre tiene una causa buscable: dolor, infeccion, estre&#241;imiento, retencion urinaria, un farmaco nuevo o un entorno hostil. Los antipsicoticos aumentan la mortalidad en esta poblacion y van despues de todo lo demas.', dificultad: 'intermedio' },
  { q: 'Que intervencion mejora la cognicion sin a&#241;adir ningun farmaco nuevo?', options: ['Prescribir memantina precozmente', 'Repetir el cribado cognitivo', 'Retirar la carga anticolinergica', 'Solicitar biomarcadores en liquido'], correct: 2, explanation: 'Antihistaminicos, antimuscarinicos urinarios, antidepresivos triciclicos y algunos antiemeticos suman carga anticolinergica, y las benzodiacepinas la agravan. Revisar la lista completa y retirar lo prescindible es lo que mas rinde con menos esfuerzo.', dificultad: 'facil' },
  { q: 'Que factor de riesgo modificable de demencia se pasa por alto con mas frecuencia?', options: ['El consumo excesivo de alcohol', 'El sedentarismo mantenido', 'La contaminacion atmosferica', 'La hipoacusia no corregida'], correct: 3, explanation: 'La Comision del Lancet la situa entre los factores modificables de mayor impacto poblacional, y es de los mas faciles de tratar. Ademas distorsiona los tests de cribado, lo que genera falsos positivos.', dificultad: 'intermedio' },
  { q: 'Que patron de respuesta orienta a depresion mas que a demencia?', options: ['Respuestas aproximadas o confabuladas', 'Respuestas repetidas de "no se"', 'Rendimiento bajo pero constante', 'Negacion completa del problema'], correct: 1, explanation: 'El paciente deprimido se queja mucho, se esfuerza poco y responde que no sabe; el paciente con demencia se queja poco, se esfuerza y da respuestas aproximadas. Ambas coexisten con frecuencia, de modo que encontrar una no descarta la otra.', dificultad: 'dificil' },
  { q: 'Que ajuste se aplica al MoCA por escolaridad?', options: ['Se restan 2 puntos si supera los 12 a&#241;os', 'Se descarta la prueba si no sabe leer', 'Se suma 1 punto si tiene 12 a&#241;os o menos', 'Se repite la prueba a los 3 meses'], correct: 2, explanation: 'El umbral habitual es de 26 o mas para considerarlo normal. El ajuste corrige en parte el efecto del nivel educativo, pero no elimina la influencia del idioma ni de los deficits sensoriales durante la prueba.', dificultad: 'intermedio' },
  { q: 'Que significa un cribado normal en alguien con nivel educativo alto y quejas cognitivas?', options: ['NO descarta un deterioro incipiente', 'Descarta cualquier deterioro cognitivo', 'Indica que las quejas son simuladas', 'Obliga a repetirlo cada mes'], correct: 0, explanation: 'El Mini-Mental tiene efecto techo y a estos pacientes se les escapan los perfiles frontales y ejecutivos. Si las quejas persisten, corresponde valoracion neuropsicologica formal, ademas de descartar depresion, farmacos y apnea del sue&#241;o.', dificultad: 'intermedio' },
  { q: 'Cuando estan indicados los biomarcadores de amiloide y tau?', options: ['En toda demencia al diagnostico', 'En la demencia avanzada institucionalizada', 'En el seguimiento anual del Alzheimer', 'Ante duda diagnostica o inicio precoz'], correct: 3, explanation: 'Tambien ante presentaciones atipicas, y de forma obligada antes de plantear un anticuerpo antiamiloide. En un caso tipico de demencia avanzada no cambian el manejo y no estan indicados.', dificultad: 'intermedio' },
  { q: 'Cual es el factor de riesgo vascular con mas impacto sobre la demencia?', options: ['La dislipemia en el anciano', 'La hipertension en la edad media', 'La obesidad en la vejez', 'La hiperuricemia mantenida'], correct: 1, explanation: 'El control de la presion arterial en la edad media de la vida es la intervencion vascular con mas respaldo para reducir el riesgo de demencia posterior, tanto vascular como mixta. Es territorio directo del internista.', dificultad: 'intermedio' },

  { type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 71 a&#241;os que acude con su hija. Se queja de olvidos desde hace un a&#241;o. Sigue llevando sus cuentas, se toma la medicacion sin ayuda y conduce sin incidentes, aunque su hija dice que le cuesta mas que antes. Tiene 8 a&#241;os de escolaridad y obtiene 23 puntos en el MoCA. Toma difenhidramina para dormir desde hace 2 a&#241;os.',
    steps: [
      { q: 'Como se interpreta ese MoCA?', options: ['24 ajustado: dentro de lo normal', '24 ajustado: por debajo del umbral', '23 sin ajuste: normal para su edad', '22 ajustado: deterioro moderado'], correct: 1 },
      { q: 'Que grado de deterioro corresponde?', options: ['Demencia en fase leve', 'Un delirium superpuesto', 'Cognicion dentro de lo normal', 'Deterioro cognitivo leve'], correct: 3 },
      { q: 'Que es lo primero y mas rentable que hay que hacer?', options: ['Iniciar donepezilo', 'Pedir biomarcadores en liquido', 'Retirar la difenhidramina', 'Solicitar positrones cerebrales'], correct: 2 }
    ],
    explanation: 'Con 12 a&#241;os o menos de escolaridad se suma 1 punto al MoCA: 23 mas 1 son 24, por debajo del umbral de 26, de modo que el cribado esta alterado. Pero un cribado alterado no es un diagnostico: como conserva la autonomia en todas las actividades instrumentales, el grado es DETERIORO COGNITIVO LEVE y no demencia. Y antes de pensar en ningun tratamiento hay que retirar la difenhidramina, un antihistaminico con carga anticolinergica alta que puede estar contribuyendo por si solo. Revisar la medicacion es la intervencion que mas rinde con menos esfuerzo.' },

  { type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 76 a&#241;os con deterioro cognitivo de 2 a&#241;os. Su mujer cuenta que hay dias en que esta "ido" y otros en que conversa con normalidad, que ve ni&#241;os en el pasillo que no existen y que desde hace 6 a&#241;os grita y da patadas mientras duerme. Camina algo encorvado y lento. En urgencias le han administrado haloperidol por agitacion y ha quedado rigido y muy somnoliento.',
    steps: [
      { q: 'Que diagnostico explica todo el cuadro?', options: ['Demencia con cuerpos de Lewy', 'Enfermedad de Alzheimer', 'Demencia vascular', 'Degeneracion frontotemporal'], correct: 0 },
      { q: 'Que error se ha cometido en urgencias?', options: ['Retrasar el anticolinesterasico', 'No pedir una neuroimagen urgente', 'Dar un antipsicotico tipico', 'No tratar antes el parkinsonismo'], correct: 2 },
      { q: 'Que sintoma precedio a&#241;os al resto y es un marcador prodromico?', options: ['Las alucinaciones visuales recurrentes', 'El trastorno del sue&#241;o REM', 'La fluctuacion del nivel de alerta', 'El parkinsonismo espontaneo'], correct: 1 }
    ],
    explanation: 'Los cuatro rasgos centrales estan: fluctuacion de la alerta, alucinaciones visuales bien formadas, trastorno de conducta del sue&#241;o REM y parkinsonismo. El haloperidol es el error: la sensibilidad a los antipsicoticos puede producir rigidez grave, deterioro del nivel de conciencia y un cuadro parecido al sindrome neuroleptico maligno, y por eso conviene marcarla de forma visible en la historia. El trastorno de conducta del sue&#241;o REM, que empezo 6 a&#241;os antes, es hoy el marcador prodromico mas util de las sinucleinopatias y hay que preguntarlo siempre a la pareja de cama.' },

  { type: 'cascade', dificultad: 'dificil',
    vignette: 'Varon de 58 a&#241;os traido por su mujer. Desde hace 3 a&#241;os hace comentarios groseros en publico, se rie ante desgracias ajenas, come dulces sin parar y ha ganado 12 kg. Ha sido diagnosticado sucesivamente de depresion y de trastorno bipolar. Recuerda bien las citas, no se pierde y obtiene 25 puntos en el MoCA.',
    steps: [
      { q: 'Que hay que sospechar?', options: ['Un trastorno bipolar de inicio tardio', 'Una enfermedad de Alzheimer atipica', 'Una demencia vascular frontal', 'Una degeneracion frontotemporal'], correct: 3 },
      { q: 'Que dato apoya mas ese diagnostico?', options: ['La perdida de empatia sin amnesia', 'El MoCA de 25 sobre 30', 'La ganancia de peso reciente', 'La edad de 58 a&#241;os al diagnostico'], correct: 0 },
      { q: 'Que tratamiento NO debe pautarse?', options: ['Un inhibidor de la recaptacion de serotonina', 'Un anticolinesterasico', 'Medidas conductuales y ambientales', 'Apoyo estructurado al cuidador'], correct: 1 }
    ],
    explanation: 'Cambio de conducta y de personalidad antes que de memoria, en un paciente de menos de 65 a&#241;os y con etiquetas psiquiatricas previas: es el retrato de la variante conductual de la degeneracion frontotemporal, cuyo retraso diagnostico se mide en a&#241;os. Lo que mas apoya el diagnostico es la combinacion de perdida de empatia, desinhibicion e hiperoralidad CON memoria conservada, porque es justo lo contrario del Alzheimer. Los anticolinesterasicos no estan indicados y pueden empeorar la conducta; los inhibidores de la recaptacion de serotonina si pueden ayudar sobre la desinhibicion y las conductas repetitivas.' },

  { type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 64 a&#241;os. Hace 10 semanas trabajaba con normalidad. Ahora esta desorientada, presenta sacudidas breves que se desencadenan con el sobresalto y camina de forma ataxica. En las ultimas 3 semanas ha pasado de manejarse sola a no reconocer su propia casa.',
    steps: [
      { q: 'Que cambia el enfoque respecto a una demencia habitual?', options: ['La edad de la paciente', 'La presencia de mioclonias', 'La VELOCIDAD de progresion', 'El sexo femenino'], correct: 2 },
      { q: 'Como hay que plantear el estudio?', options: ['Secuencial, empezando por lo mas barato', 'En paralelo y con urgencia', 'Diferirlo hasta confirmar el patron', 'Limitarlo a la neuroimagen estructural'], correct: 1 },
      { q: 'Que prueba de imagen hay que pedir de forma explicita?', options: ['Angiotomografia craneal', 'Espectroscopia por resonancia', 'Positrones con fluorodesoxiglucosa', 'Resonancia con DIFUSION'], correct: 3 }
    ],
    explanation: 'Una demencia degenerativa habitual no cambia de forma perceptible en semanas. La velocidad convierte esto en una urgencia diagnostica, porque una parte importante de las causas de demencia rapidamente progresiva es TRATABLE: encefalitis autoinmune y paraneoplasica, infecciones, neoplasia, vasculitis, estado epileptico no convulsivo y causas toxico-metabolicas. Por eso el estudio se hace en paralelo. Las mioclonias y la ataxia orientan hacia enfermedad prionica, y en ese caso hay que pedir la secuencia de DIFUSION de forma explicita, porque la hiperintensidad cortical en cinta es el hallazgo mas sensible y un protocolo estandar puede no incluirla.' },

  { type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 79 a&#241;os, hipertenso y diabetico, con dos infartos lacunares previos. Su familia describe un deterioro que ha ido "a saltos" en los ultimos 3 a&#241;os. Esta apatico, le cuesta planificar y organizar tareas, camina a pasos cortos y se ha caido dos veces. En la exploracion, la memoria mejora de forma clara cuando se le dan pistas.',
    steps: [
      { q: 'Que perfil de deterioro es?', options: ['Deterioro cognitivo vascular', 'Enfermedad de Alzheimer', 'Demencia con cuerpos de Lewy', 'Degeneracion frontotemporal'], correct: 0 },
      { q: 'Que dato de la exploracion lo apoya mas?', options: ['La edad de 79 a&#241;os', 'La apatia mantenida de meses', 'Las caidas de repeticion recientes', 'Que la memoria mejora con pistas'], correct: 3 },
      { q: 'Que es lo mas util que se puede hacer por el?', options: ['Iniciar memantina de forma precoz', 'Repetir la neuroimagen cada a&#241;o', 'Controlar los factores de riesgo vascular', 'Solicitar biomarcadores de amiloide en liquido'], correct: 2 }
    ],
    explanation: 'Curso escalonado, predominio ejecutivo con apatia, alteracion precoz de la marcha y caidas, sobre factores de riesgo vascular e infartos previos: es deterioro cognitivo vascular. El dato que mas lo apoya en la exploracion es que la memoria MEJORE con pistas, porque significa que el material estaba almacenado y el fallo es de recuperacion, al contrario que en el Alzheimer. Y lo mas util que se puede hacer es controlar de forma estricta la presion arterial, la diabetes, los lipidos y el tabaco: es la demencia con mayor margen de prevencion, y ese control es a la vez tratamiento y prevencion de la progresion.' },

  { type: 'cascade', dificultad: 'facil',
    vignette: 'Mujer de 84 a&#241;os con enfermedad de Alzheimer moderada, ingresada por una infeccion urinaria. La segunda noche esta agitada, intenta salir de la cama y grita. El equipo de guardia pide "algo para calmarla".',
    steps: [
      { q: 'Que es lo primero que hay que hacer?', options: ['Pautar haloperidol intramuscular', 'Buscar dolor, retencion o farmacos', 'Colocar sujecion mecanica', 'Administrar una benzodiacepina'], correct: 1 },
      { q: 'Que medidas van antes que el farmaco?', options: ['Sedacion nocturna programada', 'Restriccion de visitas', 'Luz, orientacion, gafas y audifonos', 'Sonda vesical para evitar levantarse'], correct: 2 },
      { q: 'Si finalmente hace falta un antipsicotico, que corresponde?', options: ['Dosis minima y el menor tiempo posible', 'Pauta fija durante todo el ingreso', 'Asociarlo a una benzodiacepina', 'Mantenerlo al alta de forma indefinida'], correct: 0 }
    ],
    explanation: 'La agitacion en un paciente con demencia ingresado es casi siempre un delirium superpuesto, y tiene una causa buscable: dolor, retencion urinaria, estre&#241;imiento, la propia infeccion, un farmaco nuevo o el entorno. Las medidas no farmacologicas van primero: orientacion, luz natural, gafas y audifonos puestos, movilizacion, sue&#241;o protegido y retirada de sondas y sujeciones, que empeoran el cuadro en lugar de resolverlo. Si al final hace falta un antipsicotico, se usa a la dosis minima y el menor tiempo posible, sabiendo que aumentan la mortalidad en esta poblacion, y se retira antes del alta.' }
];

export const flashcards = [
  { front: 'La linea entre deterioro cognitivo leve y demencia', back: 'La AUTONOMIA en las actividades instrumentales, no la puntuacion de ningun test.' },
  { front: 'Por que hace falta un informante', back: 'El paciente con anosognosia minimiza y el que tiene depresion exagera.' },
  { front: 'Que apunta a delirium y no a demencia', back: 'Inicio agudo, curso fluctuante y alteracion de la ATENCION.' },
  { front: 'Estudio minimo a TODOS', back: 'Hemograma, bioquimica con calcio, TSH, VITAMINA B12 y neuroimagen estructural.' },
  { front: 'Deficit de B12 con hemograma normal', back: 'NO se descarta: puede dar deterioro sin anemia ni macrocitosis. Pedir metilmalonico.' },
  { front: 'Que lesiones tratables busca la neuroimagen', back: 'Hematoma subdural cronico, hidrocefalia normotensiva y tumor.' },
  { front: 'Sintoma inicial del Alzheimer', back: 'AMNESIA EPISODICA: olvida hechos recientes y la pista no le ayuda.' },
  { front: 'Que significa que la pista ayude', back: 'El fallo esta en la RECUPERACION: perfil ejecutivo o subcortical, no Alzheimer.' },
  { front: 'Perfil de la demencia vascular', back: 'Escalonado, EJECUTIVO, con marcha alterada y esfinteres afectados pronto.' },
  { front: 'Umbrales de la escala de Hachinski', back: '7 o mas vascular; 4 o menos degenerativo; 5 a 6 no discrimina (mixta).' },
  { front: 'Los cuatro rasgos centrales de los cuerpos de Lewy', back: 'Fluctuacion, alucinaciones visuales, trastorno del sue&#241;o REM y parkinsonismo.' },
  { front: 'Marcador prodromico de sinucleinopatia', back: 'El trastorno de conducta del sue&#241;o REM: puede preceder a&#241;os. Preguntarlo siempre.' },
  { front: 'El error que da&#241;a en la demencia con cuerpos de Lewy', back: 'Dar un ANTIPSICOTICO tipico: rigidez grave y deterioro del nivel de conciencia.' },
  { front: 'La regla del a&#241;o', back: 'Demencia antes o dentro del a&#241;o: cuerpos de Lewy. Parkinsonismo mas de un a&#241;o antes: demencia del Parkinson.' },
  { front: 'Anticolinesterasicos en cuerpos de Lewy', back: 'Funcionan MEJOR que en el Alzheimer, sobre todo sobre alucinaciones y fluctuacion.' },
  { front: 'Inicio de la degeneracion frontotemporal', back: 'CONDUCTA y personalidad antes que memoria, y en pacientes mas jovenes.' },
  { front: 'Rasgos de la variante conductual', back: 'Desinhibicion, apatia, PERDIDA DE EMPATIA, conductas repetitivas e hiperoralidad.' },
  { front: 'Anticolinesterasicos en la frontotemporal', back: 'NO indicados: pueden empeorar la conducta. Valorar inhibidores de la recaptacion de serotonina.' },
  { front: 'Gen que une frontotemporal y ELA', back: 'C9orf72. Explorar signos de motoneurona en toda degeneracion frontotemporal.' },
  { front: 'Demencia rapidamente progresiva', back: 'Progresion en semanas o pocos meses: URGENCIA diagnostica, estudio en paralelo.' },
  { front: 'Que se descarta primero en la rapidamente progresiva', back: 'Lo TRATABLE: autoinmune, infeccioso, neoplasico, vascular y toxico-metabolico.' },
  { front: 'Resonancia en la enfermedad prionica', back: 'DIFUSION: hiperintensidad cortical en cinta y en ganglios basales. Pedirla explicita.' },
  { front: 'Prueba de referencia en liquido para priones', back: 'RT-QuIC. La 14-3-3 es inespecifica y sube en cualquier da&#241;o neuronal rapido.' },
  { front: 'Precaucion en la enfermedad prionica', back: 'Protocolo especial del INSTRUMENTAL quirurgico. El contacto habitual no requiere aislamiento.' },
  { front: 'Antes de un antipsicotico por agitacion', back: 'Buscar dolor, infeccion, estre&#241;imiento, retencion urinaria o un farmaco nuevo.' },
  { front: 'Lo que mas rinde sin a&#241;adir farmacos', back: 'RETIRAR la carga anticolinergica y las benzodiacepinas.' },
  { front: 'El factor modificable que mas se olvida', back: 'La HIPOACUSIA no corregida. Ademas distorsiona los tests de cribado.' },
  { front: 'Depresion frente a demencia', back: 'Deprimido: se queja mucho y responde "no se". Demencia: se queja poco y confabula.' },
  { front: 'Ajuste del MoCA', back: 'Se suma 1 punto si tiene 12 a&#241;os o menos de escolaridad. Normal: 26 o mas.' },
  { front: 'Cribado normal con nivel educativo alto', back: 'NO descarta: el Mini-Mental tiene efecto techo. Valoracion neuropsicologica formal.' },
  { front: 'Cuando pedir biomarcadores de amiloide y tau', back: 'Duda diagnostica, inicio precoz, presentacion atipica o antes de un antiamiloide.' },
  { front: 'El factor vascular con mas impacto', back: 'La HIPERTENSION en la edad media de la vida.' }
];

export default { quiz, flashcards };
