// topics/historia-clinica/study.js — Autoevaluación de Historia Clínica y Anamnesis Dirigida.
// Banco único: mezcla preguntas sueltas y preguntas en cascada (varios pasos sobre una misma
// viñeta, con retroalimentación consolidada al final) — sin separar "quiz" de "caso clínico".

export const quiz = [
  { q: '¿Cuál es el orden correcto de la historia clínica según su estructura estándar?', options: ['Exploración física, motivo de consulta, padecimiento actual, antecedentes', 'Ficha de identificación, motivo de consulta, padecimiento actual, antecedentes, interrogatorio por aparatos, exploración física', 'Antecedentes, exploración física, motivo de consulta, plan', 'Plan diagnóstico, motivo de consulta, exploración física, antecedentes'], correct: 1, explanation: 'La secuencia estándar va de lo general (identificación) a lo específico (padecimiento actual y antecedentes), y termina con los hallazgos objetivos (exploración física) y el plan.', dificultad: 'facil' },
  { q: 'Según la técnica de redacción del padecimiento actual (PA), ¿qué son los "negativos pertinentes"?', options: ['Errores de redacción que deben corregirse', 'Síntomas que el paciente NO presenta y que ayudan a descartar diagnósticos', 'Antecedentes heredofamiliares negados por el paciente', 'Resultados de laboratorio anormales'], correct: 1, explanation: 'Los negativos pertinentes son síntomas ausentes que el médico incluye deliberadamente porque su ausencia ayuda a acotar el diagnóstico diferencial (ej. "niega fiebre, niega disnea").', dificultad: 'facil' },
  { q: '¿Cuál de las siguientes es la forma correcta de iniciar la redacción de un padecimiento actual?', options: ['Con el diagnóstico presuntivo del médico', 'Indicando edad, sexo y tiempo total de evolución del cuadro', 'Con la lista de medicamentos que toma el paciente', 'Con el resultado de la exploración física'], correct: 1, explanation: 'El PA se abre situando al lector: edad, sexo y tiempo de evolución ("Paciente masculino de 45 años con cuadro de 3 días de evolución…"), y luego se narra en orden cronológico.', dificultad: 'facil' },
  { q: '¿Qué objetivo tiene específicamente el interrogatorio por aparatos y sistemas, a diferencia del padecimiento actual?', options: ['Repetir la misma información del padecimiento actual', 'Detectar síntomas asociados que el paciente no mencionó espontáneamente', 'Reemplazar la exploración física', 'Registrar únicamente antecedentes quirúrgicos'], correct: 1, explanation: 'El interrogatorio por aparatos y sistemas es una revisión sistemática dirigida a encontrar síntomas que el paciente no relacionó espontáneamente con su motivo de consulta.', dificultad: 'facil' },
  { q: 'Un paciente refiere ser trabajador agrícola desde hace 20 años. ¿En qué sección de la historia clínica se documenta este dato y qué relevancia diagnóstica tiene?', options: ['Antecedentes personales patológicos; no tiene relevancia diagnóstica', 'Antecedentes personales no patológicos; orienta a exposición a organofosforados y zoonosis', 'Interrogatorio por aparatos y sistemas; orienta a enfermedad psiquiátrica', 'Motivo de consulta; no requiere documentarse'], correct: 1, explanation: 'La ocupación se documenta en los antecedentes personales no patológicos y, en el caso de trabajo agrícola, orienta a exposición a organofosforados y a zoonosis.', dificultad: 'intermedio' },
  { q: '¿Cuál de los siguientes NO forma parte de los antecedentes personales patológicos?', options: ['Cirugías previas con fecha y motivo', 'Alergias medicamentosas y el tipo de reacción', 'Ocupación actual y exposiciones laborales', 'Antecedentes transfusionales'], correct: 2, explanation: 'La ocupación y las exposiciones laborales pertenecen a los antecedentes personales NO patológicos, no a los patológicos.', dificultad: 'facil' },
  { q: 'Según el acrónimo SOCRATES, ¿qué componente evalúa específicamente si un dolor es constante o intermitente y cuánto dura?', options: ['Site (localización)', 'Character (calidad)', 'Time course (cronología)', 'Severity (intensidad)'], correct: 2, explanation: '"Time course" es el componente de SOCRATES que evalúa la cronología: si el síntoma es constante o intermitente, y su duración total.', dificultad: 'facil' },
  { q: '¿A partir de qué temperatura se define la fiebre, y cómo se llama el rango justo por debajo de ese umbral?', options: ['>37.0 °C; ese rango se llama "hipertermia"', '>38.0 °C; el rango de 37.3-38.0 °C se llama "febrícula"', '>39.0 °C; no existe un rango intermedio', '>36.5 °C; ese rango se llama "normotermia"'], correct: 1, explanation: 'La fiebre se define como temperatura central >38.0 °C. El rango de 37.3-38.0 °C se considera febrícula (subfebril); por encima de 41.0 °C se habla de hiperpirexia.', dificultad: 'facil' },
  { q: '¿A partir de qué duración se considera que una tos es crónica?', options: ['Más de 3 días', 'Más de 1 semana', 'Más de 8 semanas', 'Más de 6 meses'], correct: 2, explanation: 'La tos se clasifica en aguda (<3 semanas), subaguda (3-8 semanas) y crónica (>8 semanas).', dificultad: 'facil' },
  { q: 'La combinación de astenia, pérdida de peso involuntaria y sudoración nocturna profusa se conoce como:', options: ['Tríada de Charcot', 'Síntomas B', 'Signo de Homans', 'Criterios de Light'], correct: 1, explanation: 'Los "síntomas B" (astenia/pérdida de peso/sudoración nocturna) son una tríada de alarma que obliga a descartar neoplasia, tuberculosis e infección por VIH.', dificultad: 'intermedio' },
  { q: 'Un paciente con tos seca crónica que toma enalapril para su hipertensión. ¿Qué causa debe considerarse antes de solicitar estudios extensos?', options: ['Neoplasia pulmonar', 'Efecto adverso del IECA', 'Tuberculosis', 'Insuficiencia cardiaca'], correct: 1, explanation: 'La tos seca crónica es un efecto adverso frecuente y bien reconocido de los IECA como el enalapril; conviene descartarlo antes de estudios más invasivos.', dificultad: 'intermedio' },
  { q: 'Según la escala mMRC de disnea, ¿qué grado corresponde a un paciente que debe detenerse a respirar después de caminar unos 100 metros en llano?', options: ['Grado 1', 'Grado 2', 'Grado 3', 'Grado 4'], correct: 2, explanation: 'El grado 3 de la escala mMRC corresponde a detenerse a respirar tras caminar ~100 metros o pocos minutos en llano; el grado 4 es cuando la disnea impide salir de casa.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente masculino de 52 años acude por dolor torácico de 40 minutos de evolución.',
    steps: [
      { q: '¿Cuál es el primer paso para caracterizar este síntoma guía?', options: ['Solicitar troponinas de inmediato sin interrogar más', 'Aplicar SOCRATES: localización, inicio, calidad, irradiación, síntomas acompañantes, cronología, factores agravantes/atenuantes e intensidad', 'Preguntar directamente si es un infarto', 'Pasar a la exploración física sin más preguntas'], correct: 1 },
      { q: 'El paciente refiere: dolor opresivo, retroesternal, irradiado a brazo izquierdo, con diaforesis, que inició en reposo. ¿Qué sección de la historia clínica se vuelve prioritaria interrogar ahora?', options: ['Antecedentes personales no patológicos', 'Antecedentes personales patológicos', 'Esquema de vacunación', 'Antecedentes ginecoobstétricos'], correct: 1 },
      { q: '¿Cuál sería un "negativo pertinente" útil para incluir en el padecimiento actual de este caso?', options: ['"Niega dolor torácico"', '"Niega disnea, niega palpitaciones, niega dolor con la respiración" — ayuda a orientar entre causa cardiovascular y pleuropulmonar', 'No es necesario incluir negativos en este caso', '"Niega antecedentes familiares" sin especificar cuáles'], correct: 1 }
    ],
    explanation: 'Este caso integra los tres pasos de la anamnesis dirigida: caracterizar el síntoma con SOCRATES, dirigir el interrogatorio de antecedentes según la sospecha diagnóstica generada (aquí, antecedentes personales patológicos y heredofamiliares de riesgo cardiovascular: HTA, diabetes, dislipidemia, tabaquismo, cardiopatía familiar), y documentar negativos pertinentes que acoten el diferencial (cardiovascular isquémico vs. pleuropulmonar).'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente de 58 años con antecedente de litiasis vesicular conocida, refiere dolor en hipocondrio derecho de 6 horas de evolución.',
    steps: [
      { q: 'El paciente describe el dolor como difuso, mal localizado, y refiere que también lo siente en la punta de la escápula derecha. Según su mecanismo, ¿qué tipo de dolor es este?', options: ['Dolor somático', 'Dolor visceral', 'Dolor neuropático', 'Dolor psicógeno'], correct: 1 },
      { q: '¿Qué característica del dolor visceral explica que también se sienta en la escápula, lejos del órgano afectado?', options: ['Es un error de percepción del paciente y no tiene explicación fisiológica', 'Puede referirse a un dermatoma distante que comparte la misma inervación aferente que la víscera', 'El dolor visceral siempre se irradia hacia arriba por gravedad', 'La vesícula biliar tiene terminaciones nerviosas directas en la escápula'], correct: 1 },
      { q: 'Al explorar al paciente, el dolor NO se reproduce con la palpación directa de la pared abdominal ni cambia con el movimiento. ¿Qué componente de SOCRATES ayudó a llegar a esta distinción entre dolor visceral y somático?', options: ['Severity (intensidad) únicamente', 'Character (calidad) y su relación con factores agravantes como el movimiento o la palpación', 'Onset (inicio) únicamente', 'No es posible distinguirlos con la anamnesis'], correct: 1 }
    ],
    explanation: 'El dolor visceral es difuso, mal localizado y puede referirse a un dermatoma distante por compartir vías aferentes con la víscera de origen (vesícula biliar → escápula derecha, isquemia miocárdica → brazo izquierdo/mandíbula) — a diferencia del dolor somático, que es agudo, bien localizado y se reproduce con la palpación o el movimiento. SOCRATES (en particular Character y los factores agravantes) es la herramienta que permite hacer esta distinción en la cabecera del paciente.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente femenina de 61 años consulta por fatiga de 2 meses de evolución.',
    steps: [
      { q: '¿Qué información debe buscarse activamente además de caracterizar la fatiga con SOCRATES?', options: ['Solo su ocupación actual', 'Síntomas B: pérdida de peso involuntaria y sudoración nocturna, además de si la fatiga mejora con el reposo', 'Antecedentes ginecoobstétricos únicamente', 'No hace falta profundizar, la fatiga es inespecífica'], correct: 1 },
      { q: 'La paciente confirma pérdida de 6 kg en 3 meses (>5% de su peso) y sudoración nocturna. ¿Qué antecedente personal patológico es más relevante interrogar a continuación?', options: ['Antecedente de cirugía estética previa', 'Antecedentes oncológicos personales/familiares, antecedente de tuberculosis o factores de riesgo para VIH', 'Tipo de calzado que usa habitualmente', 'Color de cabello natural'], correct: 1 },
      { q: '¿Qué componente de la historia clínica documenta mejor la ocupación y exposiciones ambientales que podrían orientar la causa de estos síntomas?', options: ['Antecedentes personales no patológicos', 'Motivo de consulta', 'Ficha de identificación (solo nombre y edad)', 'Exploración física'], correct: 0 }
    ],
    explanation: 'La presencia de síntomas B (astenia + pérdida de peso involuntaria + sudoración nocturna) obliga a ampliar el interrogatorio hacia antecedentes oncológicos, infecciosos crónicos (TB, VIH) y exposiciones ocupacionales/ambientales documentadas en los antecedentes personales no patológicos — el mismo razonamiento que conecta anamnesis dirigida con diagnóstico diferencial.'
  }
];

export const flashcards = [
  { front: 'Estructura de la historia clínica (orden)', back: 'Ficha de identificación → Motivo de consulta → Padecimiento actual → Antecedentes heredofamiliares → Antecedentes personales patológicos → Antecedentes personales no patológicos → Interrogatorio por aparatos y sistemas → Exploración física → Resumen/lista de problemas → Plan.' },
  { front: 'SOCRATES (semiología del síntoma)', back: 'Site (localización), Onset (inicio), Character (calidad), Radiation (irradiación), Associations (síntomas acompañantes), Time course (cronología), Exacerbating/relieving factors (agravantes/atenuantes), Severity (intensidad).' },
  { front: '¿Qué son los "negativos pertinentes" en el PA?', back: 'Síntomas ausentes que se documentan deliberadamente porque su ausencia ayuda a descartar diagnósticos (ej. "niega fiebre, niega disnea").' },
  { front: 'Antecedentes personales patológicos vs. no patológicos', back: 'Patológicos: enfermedades, cirugías, alergias, transfusiones, vacunas. No patológicos: ocupación, vivienda, alimentación, tabaco/alcohol, sueño, red de apoyo.' },
  { front: 'Dolor visceral vs. dolor somático', back: 'Visceral: difuso, mal localizado, puede referirse a un dermatoma distante. Somático: agudo, bien localizado, se agrava con el movimiento/palpación.' },
  { front: 'Fiebre vs. hipertermia', back: 'Fiebre: reajuste del centro termorregulador por pirógenos. Hipertermia: falla en la disipación de calor, sin reajuste del centro termorregulador.' },
  { front: 'Rangos de temperatura', back: 'Normal 36.5-37.2 °C · Febrícula 37.3-38.0 °C · Fiebre >38.0 °C · Hiperpirexia >41.0 °C.' },
  { front: 'Escala de disnea mMRC (grados 0-4)', back: '0: solo con ejercicio intenso. 1: al andar rápido/subir pendiente leve. 2: más lento que otros o se detiene al caminar en llano. 3: se detiene tras ~100 m. 4: le impide salir de casa.' },
  { front: 'Clasificación de la tos por duración', back: 'Aguda: <3 semanas. Subaguda: 3-8 semanas. Crónica: >8 semanas.' },
  { front: '"Síntomas B"', back: 'Astenia + pérdida de peso involuntaria (>5% en 6-12 meses) + sudoración nocturna profusa — obligan a descartar neoplasia, TB y VIH.' }
];

export default { quiz, flashcards };
