// topics/exploracion-cardiovascular/study.js — Autoevaluación de Exploración Cardiovascular.
// Mismo patrón que historia-clinica/study.js: banco único, preguntas sueltas + preguntas en
// cascada sobre una viñeta (retroalimentación consolidada al final, sin revelar correcto/
// incorrecto paso a paso). Redacción de opciones sujeta a .claude/skills/reglas-preguntas/SKILL.md
// (misma categoría lógica, longitud/detalle comparables, sin pistas gramaticales/semánticas,
// posición de `correct` distribuida sin patrón a lo largo de todo el array).

export const quiz = [
  { q: '¿Cuál es la secuencia correcta de la exploración cardiovascular?', options: ['Auscultación, inspección y palpación del precordio, pulsos periféricos, presión venosa yugular', 'Inspección y palpación del precordio, pulsos periféricos, presión venosa yugular, auscultación', 'Presión venosa yugular, auscultación, inspección y palpación del precordio, pulsos periféricos', 'Auscultación, presión venosa yugular, pulsos periféricos, inspección y palpación del precordio'], correct: 1, explanation: 'El orden estándar va de la inspección/palpación del precordio a los pulsos periféricos, la presión venosa yugular, y se deja la auscultación al final, en varias posiciones.', dificultad: 'facil' },
  { q: '¿Por qué la auscultación cardiaca debe repetirse en decúbito lateral izquierdo (posición de Pachón)?', options: ['Porque mejora la comodidad postural general del paciente durante el examen', 'Porque reduce de forma transitoria la frecuencia cardiaca durante la maniobra', 'Porque elimina por completo los ruidos respiratorios sobreañadidos durante la auscultación', 'Porque acerca el ápex a la pared torácica, acentuando los sonidos graves'], correct: 3, explanation: 'El decúbito lateral izquierdo acerca el ventrículo izquierdo a la pared torácica, lo que acentúa los sonidos graves de baja intensidad como R3, R4 y el retumbo diastólico de la estenosis mitral.', dificultad: 'facil' },
  { q: '¿Qué diferencia acústica hay entre el diafragma y la campana del estetoscopio?', options: ['Diafragma: agudos; campana: graves', 'No existe una diferencia real', 'Campana: agudos; diafragma: graves', 'Los dos filtran igual las frecuencias'], correct: 0, explanation: 'El diafragma (membrana rígida) filtra las frecuencias bajas y deja pasar mejor las agudas (R1, R2, soplo de insuficiencia aórtica); la campana, aplicada con presión leve, transmite mejor las frecuencias graves (R3, R4, retumbo de estenosis mitral).', dificultad: 'intermedio' },
  { q: '¿Dónde se ausculta mejor, típicamente, un soplo de insuficiencia aórtica, y por qué no exactamente sobre la válvula aórtica?', options: ['En el ápex, porque anatómicamente ahí se proyecta la válvula aórtica misma', 'En el epigastrio, porque el chorro turbulento se dirige directamente hacia esa región', 'En el foco de Erb, por la dirección del chorro turbulento, no por proximidad anatómica', 'No existe un foco preferente, se ausculta igual de bien en cualquier punto'], correct: 2, explanation: 'El foco de Erb, punto de convergencia entre el foco aórtico y el pulmonar, suele ser donde mejor se ausculta la insuficiencia aórtica, porque el sonido viaja con la dirección del flujo regurgitante, no por simple cercanía a la válvula.', dificultad: 'intermedio' },
  { q: 'Un choque de la punta desplazado más allá de la línea medioclavicular y difuso (&gt;3 cm) sugiere principalmente:', options: ['Hipertrofia concéntrica por sobrecarga de presión ventricular', 'Dilatación del ventrículo izquierdo por sobrecarga de volumen', 'Derrame pericárdico con compresión extrínseca de las cavidades', 'Estenosis aórtica leve, sin repercusión hemodinámica significativa'], correct: 1, explanation: 'El desplazamiento lateral e inferior junto con un choque difuso son característicos de dilatación ventricular izquierda por sobrecarga de volumen (insuficiencia mitral o aórtica crónicas, miocardiopatía dilatada).', dificultad: 'intermedio' },
  { q: 'Un choque de la punta sostenido, de alta amplitud, "en cúpula", pero SIN desplazarse de su localización normal, sugiere:', options: ['Dilatación por sobrecarga de volumen', 'Derrame pericárdico con taponamiento', 'Comunicación interauricular amplia', 'Hipertrofia por sobrecarga de presión'], correct: 3, explanation: 'El ventrículo se hipertrofia hacia la luz sin dilatarse en la sobrecarga de presión, por lo que el choque se vuelve sostenido y de alta amplitud pero no se desplaza — a diferencia de la sobrecarga de volumen, que sí lo desplaza.', dificultad: 'dificil' },
  { q: '¿Qué significa siempre la presencia de un frémito (thrill) precordial?', options: ['Un soplo funcional especialmente intenso', 'Un hallazgo normal en decúbito lateral', 'Cardiopatía estructural significativa', 'Ansiedad importante durante el examen'], correct: 2, explanation: 'El frémito es la vibración palpable de un soplo muy intenso (grado ≥4/6) y siempre indica organicidad; nunca se palpa con un soplo funcional.', dificultad: 'facil' },
  { q: '¿Qué es un "déficit de pulso" y en qué arritmia es característico?', options: ['Frecuencia auscultada mayor que la palpada; ocurre en fibrilación auricular', 'Ausencia total de pulso radial; ocurre en el paro cardiaco', 'Asimetría entre el pulso radial derecho e izquierdo; en la disección aórtica', 'Un pulso más lento en la pierna que en el brazo; en la coartación aórtica'], correct: 0, explanation: 'En la fibrilación auricular (o extrasistolia frecuente) algunos latidos son demasiado prematuros para generar un volumen de eyección suficiente y no se perciben en el pulso periférico, aunque sí se ausculten — de ahí el déficit.', dificultad: 'intermedio' },
  { q: 'Un pulso arterial de amplitud baja con ascenso lento y pico tardío en meseta corresponde a:', options: ['Pulsus celer et magnus', 'Pulsus alternans clásico', 'Pulsus bisferiens típico', 'Pulsus parvus et tardus'], correct: 3, explanation: 'La obstrucción fija al tracto de salida en la estenosis aórtica severa enlentece y aplana la eyección ventricular, generando un pulso de ascenso lento y amplitud baja.', dificultad: 'intermedio' },
  { q: 'El pulso "en martillo de agua" o de Corrigan (celer et magnus) es característico de:', options: ['La estenosis mitral', 'La insuficiencia aórtica', 'El taponamiento cardiaco', 'El bloqueo AV completo'], correct: 1, explanation: 'La fuga diastólica hacia el ventrículo en la insuficiencia aórtica severa genera un ascenso muy rápido a un pico alto seguido de colapso también rápido, por la amplia presión de pulso.', dificultad: 'facil' },
  { q: '¿Qué mecanismo explica el pulsus alternans?', options: ['Disociación auriculoventricular', 'Fibrilación auricular rápida', 'Falla sistólica severa del VI', 'Estenosis aórtica ligera'], correct: 2, explanation: 'El pulsus alternans (ritmo regular, amplitud que alterna fuerte-débil) refleja disfunción sistólica severa del ventrículo izquierdo, que no se recupera por completo entre contracciones consecutivas.', dificultad: 'dificil' },
  { q: '¿Qué mecanismo explica el pulso paradójico en el taponamiento cardiaco?', options: ['Interdependencia ventricular por el aumento inspiratorio del retorno venoso derecho', 'Aumento significativo del gasto cardiaco durante la inspiración profunda', 'Disminución marcada de la frecuencia cardiaca durante la inspiración', 'Vasodilatación pulmonar generalizada inducida por la inspiración profunda'], correct: 0, explanation: 'Con el pericardio no distensible, el mayor retorno venoso derecho en inspiración desplaza el tabique interventricular hacia la izquierda, reduciendo el llenado y el volumen latido del ventrículo izquierdo — de ahí la caída inspiratoria exagerada de la presión sistólica.', dificultad: 'dificil' },
  { q: 'El pulsus bisferiens (dos picos sistólicos palpables) se asocia clásicamente a:', options: ['Estenosis tricuspídea con onda a alta', 'Insuficiencia aórtica y miocardiopatía', 'Fibrilación auricular de respuesta irregular', 'Comunicación interauricular con R2 fijo'], correct: 1, explanation: 'En ambas condiciones una eyección inicial rápida se ve seguida de una caída mesosistólica (por obstrucción dinámica en la MCH, o por la gran presión de pulso en la insuficiencia aórtica) y un segundo pico.', dificultad: 'dificil' },
  { q: 'En el pulso venoso yugular, ¿qué onda corresponde a la contracción auricular derecha y coincide con la onda P del ECG?', options: ['Onda c', 'Onda v', 'Descenso y', 'Onda a'], correct: 3, explanation: 'La onda a es generada por la contracción auricular derecha y precede a R1, coincidiendo con la P del electrocardiograma.', dificultad: 'facil' },
  { q: '¿Cómo se diferencia clínicamente el pulso venoso yugular del pulso carotídeo, ambos visibles en el cuello?', options: ['El venoso no es palpable y se colapsa', 'El venoso es palpable; el carotídeo no', 'Los dos se colapsan con presión leve', 'El carotídeo varía con la respiración'], correct: 0, explanation: 'Estas diferencias (ondulación múltiple, no palpable, colapsable, variable con posición/inspiración) son la forma práctica de distinguir el pulso venoso del carotídeo a la cabecera.', dificultad: 'intermedio' },
  { q: 'Una onda a "cañón" en el pulso venoso yugular sugiere:', options: ['Fibrilación auricular con actividad auricular desorganizada', 'Insuficiencia tricuspídea severa con onda v prominente', 'Disociación auriculoventricular, como en el bloqueo AV completo', 'Estenosis mitral con refuerzo presistólico característico'], correct: 2, explanation: 'Los cañones ocurren cuando la aurícula se contrae contra una válvula tricúspide cerrada, por disociación entre la actividad auricular y ventricular (bloqueo AV completo, taquicardia ventricular con conducción retrógrada bloqueada).', dificultad: 'dificil' },
  { q: '¿Por qué desaparece la onda a en la fibrilación auricular?', options: ['No hay contracción auricular organizada', 'Porque la frecuencia cardiaca es muy alta', 'Porque la tricúspide queda abierta', 'Porque el ventrículo derecho se dilata'], correct: 0, explanation: 'La onda a depende de una contracción auricular coordinada; en la fibrilación auricular la actividad auricular es caótica y no genera una onda a identificable.', dificultad: 'intermedio' },
  { q: 'Una onda v gigante que borra el descenso x en el pulso venoso yugular es característica de:', options: ['La estenosis mitral cerrada', 'El bloqueo AV de tercer grado', 'La pericarditis constrictiva', 'La insuficiencia tricuspídea'], correct: 3, explanation: 'En la insuficiencia tricuspídea severa el flujo regurgitante sistólico entra directamente a la aurícula derecha, generando una onda v muy prominente que puede fusionarse con la c y borrar el descenso x (onda "cv").', dificultad: 'intermedio' },
  { q: '¿Qué significa el signo de Kussmaul (elevación paradójica de la PVY con la inspiración)?', options: ['Insuficiencia mitral aguda con edema', 'Corazón derecho rígido', 'Un hallazgo normal en personas sanas', 'Estenosis aórtica severa con gradiente'], correct: 1, explanation: 'Normalmente la PVY cae con la inspiración; cuando el corazón derecho es rígido y no puede acomodar el mayor retorno venoso, la PVY sube o no cae — el signo de Kussmaul (pericarditis constrictiva, falla derecha severa, miocardiopatía restrictiva).', dificultad: 'dificil' },
  { q: '¿Qué se considera un reflujo hepatoyugular positivo?', options: ['Un ascenso transitorio de 1-2 latidos', 'Una caída de la PVY al comprimir el hígado', 'Elevación sostenida ≥3-4 cm de la PVY', 'Un cambio de la frecuencia al comprimir'], correct: 2, explanation: 'Un ascenso transitorio puede verse incluso en personas sanas; lo patológico es que la elevación se mantenga sostenida durante toda la compresión, lo que indica que el corazón derecho no puede acomodar el aumento de precarga.', dificultad: 'intermedio' },
  { q: '¿Qué explica el ensanchamiento fisiológico del desdoblamiento de R2 durante la inspiración?', options: ['La frecuencia cardiaca disminuye de forma significativa durante la inspiración', 'El ventrículo izquierdo se contrae con mayor fuerza durante la inspiración', 'La presión arterial sistémica aumenta de forma notable con la inspiración', 'El retorno venoso derecho retrasa P2, y la precarga izquierda adelanta A2'], correct: 3, explanation: 'La inspiración prolonga la eyección del ventrículo derecho (retrasa P2) y acorta levemente la del izquierdo (adelanta A2), ensanchando la separación entre ambos componentes de R2.', dificultad: 'dificil' },
  { q: 'Un desdoblamiento de R2 que NO varía con la respiración (fijo) es característico de:', options: ['Comunicación interauricular', 'Bloqueo de rama derecha', 'Estenosis aórtica severa', 'Insuficiencia mitral severa'], correct: 0, explanation: 'En la comunicación interauricular, el cortocircuito izquierda-derecha iguala las presiones/volúmenes de ambas aurículas durante todo el ciclo respiratorio, por lo que el desdoblamiento deja de variar con la inspiración/espiración.', dificultad: 'intermedio' },
  { q: 'El desdoblamiento paradójico (invertido) de R2, donde P2 precede a A2, se asocia a:', options: ['Comunicación interauricular con desdoblamiento fijo de R2', 'Estenosis pulmonar con soplo eyectivo asociado', 'Bloqueo de rama izquierda o estenosis aórtica severa', 'Insuficiencia tricuspídea con onda v gigante'], correct: 2, explanation: 'El retraso de la eyección ventricular izquierda (bloqueo de rama izquierda o estenosis aórtica severa) retrasa A2 más allá de P2, invirtiendo el orden normal; por eso este desdoblamiento se estrecha con la inspiración, justo lo opuesto al fisiológico.', dificultad: 'dificil' },
  { q: 'Un R4 (galope auricular) desaparece si el paciente entra en fibrilación auricular. ¿Por qué?', options: ['R4 necesita contracción auricular', 'Porque la frecuencia se vuelve muy alta', 'El ventrículo se dilata con el tiempo', 'Porque desaparece la sístole eficaz'], correct: 0, explanation: 'R4 se genera por la contracción auricular impulsando sangre hacia un ventrículo rígido; sin contracción auricular organizada (fibrilación auricular), no hay onda que lo genere.', dificultad: 'intermedio' },
  { q: '¿Qué diferencia hay entre un R3 fisiológico y uno patológico?', options: ['El fisiológico suena más grave', 'Suenan igual: los separa el contexto', 'Suenan distinto con campana o diafragma', 'El patológico solo aparece en decúbito'], correct: 1, explanation: 'R3 fisiológico y patológico se generan por el mismo mecanismo (desaceleración del llenado rápido diastólico) y suenan igual; lo que cambia es el contexto — en un adulto &gt;40 años, un R3 es prácticamente diagnóstico de disfunción ventricular o sobrecarga de volumen.', dificultad: 'dificil' },
  { q: 'Un clic mesosistólico seguido de un soplo sistólico tardío es característico de:', options: ['La estenosis aórtica', 'La estenosis mitral', 'Comunicación interventricular', 'El prolapso mitral'], correct: 3, explanation: 'El clic mesosistólico del prolapso mitral ocurre por la tensión súbita de una valva redundante y sus cuerdas al prolapsar hacia la aurícula; suele seguirse de un soplo de insuficiencia mitral tardío en la sístole.', dificultad: 'intermedio' },
  { q: '¿Qué significa que el intervalo entre R2 y el chasquido de apertura sea corto en la estenosis mitral?', options: ['Que la estenosis es más severa, por mayor presión auricular izquierda', 'Que la estenosis es leve, con escaso gradiente transvalvular', 'Que hay insuficiencia mitral asociada, no relacionada con la severidad', 'No tiene relevancia clínica alguna en la valoración de severidad'], correct: 0, explanation: 'A mayor severidad de la estenosis mitral, mayor la presión auricular izquierda, y por tanto la válvula se abre más rápido tras el cierre aórtico — acortando el intervalo R2-chasquido.', dificultad: 'dificil' },
  { q: 'Según la clasificación semiológica de los soplos, un soplo holosistólico "en meseta" (misma intensidad durante toda la sístole) es típico de:', options: ['Estenosis aórtica', 'Insuficiencia aórtica', 'Insuficiencia mitral', 'Persistencia del conducto arterioso'], correct: 2, explanation: 'Los soplos regurgitantes a través de un orificio relativamente fijo durante toda la sístole (como la insuficiencia mitral) generan un soplo holosistólico en meseta, a diferencia del soplo eyectivo "en diamante" de la estenosis aórtica.', dificultad: 'intermedio' },
  { q: '¿Qué características hacen que un soplo se considere "inocente" o funcional en vez de orgánico?', options: ['Diastólico, grado 4/6, con frémito', 'Sistólico, suave, sin frémito', 'Continuo e irradiado a todo el precordio', 'Holosistólico, irradiado a la axila'], correct: 1, explanation: 'Los soplos inocentes son siempre sistólicos, suaves, sin frémito ni síntomas asociados, y no se acompañan de un R2 anormal — cualquiera de esas características ausente obliga a sospechar organicidad.', dificultad: 'facil' },
  { q: '¿Qué maniobra aumenta el soplo de la miocardiopatía hipertrófica obstructiva pero disminuye el de la estenosis aórtica?', options: ['La maniobra de handgrip', 'La inspiración profunda', 'El decúbito lateral izquierdo', 'La maniobra de Valsalva'], correct: 3, explanation: 'La Valsalva reduce la precarga: esto empeora la obstrucción dinámica del tracto de salida en la MCH obstructiva (aumenta el soplo) pero disminuye la mayoría de los demás soplos, incluida la estenosis aórtica — es la maniobra clásica para distinguir ambas entidades.', dificultad: 'dificil' },
  { q: 'El signo de Carvallo (un soplo que aumenta de intensidad con la inspiración) localiza el soplo a:', options: ['El lado izquierdo del corazón', 'La aorta torácica descendente', 'El lado derecho del corazón', 'Las venas pulmonares centrales'], correct: 2, explanation: 'La inspiración aumenta el retorno venoso al corazón derecho, aumentando la intensidad de los soplos generados ahí — el signo de Carvallo es clásico para distinguir insuficiencia tricuspídea de insuficiencia mitral.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente masculino de 74 años con disnea de esfuerzo progresiva y un episodio de síncope. A la exploración: soplo sistólico creciente-decreciente en el foco aórtico, irradiado a carótidas.',
    steps: [
      { q: '¿Qué característica del pulso arterial esperarías encontrar si la estenosis es severa?', options: ['Pulsus celer et magnus', 'Pulsus alternans clásico', 'Un pulso normal, sin cambios', 'Pulsus parvus et tardus'], correct: 3 },
      { q: '¿Qué esperarías encontrar en la palpación del choque de la punta?', options: ['Desplazado lateralmente y de carácter difuso', 'Sostenido, de alta amplitud, sin desplazar', 'Impalpable, sin choque de punta detectable', 'Doble impulso sistólico palpable en la punta'], correct: 1 },
      { q: '¿Qué hallazgo en R2 apoyaría que la estenosis es severa?', options: ['R2 disminuido o desdoblamiento paradójico', 'Desdoblamiento fijo, sin variar con la respiración', 'Desdoblamiento amplio, con variación normal', 'R2 conservado, sin cambio alguno'], correct: 0 }
    ],
    explanation: 'La estenosis aórtica severa integra varios hallazgos concordantes: soplo eyectivo irradiado a carótidas, pulso parvus et tardus (obstrucción fija que enlentece y aplana la eyección), choque de la punta sostenido sin desplazarse (hipertrofia concéntrica por sobrecarga de presión, a diferencia de la sobrecarga de volumen que sí desplaza el choque), y A2 disminuido/abolido o desdoblamiento paradójico de R2 por retraso de la eyección ventricular izquierda.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente femenina de 38 años con antecedente de fiebre reumática en la infancia. Refiere disnea progresiva. Presión arterial 150/50 mmHg (presión de pulso amplia).',
    steps: [
      { q: '¿Qué tipo de pulso arterial esperarías palpar?', options: ['Pulso parvus et tardus', 'Pulso alternante clásico', 'Celer et magnus (Corrigan)', 'Pulso paradójico marcado'], correct: 2 },
      { q: '¿Dónde se ausculta mejor el soplo esperado, y en qué posición del paciente?', options: ['Foco de Erb, sentado e inclinado', 'Ápex, en decúbito lateral izquierdo', 'Foco pulmonar, en decúbito supino', 'Cualquier foco, sin posición especial'], correct: 0 },
      { q: '¿Qué características tiene este soplo según tiempo y morfología?', options: ['Sistólico, creciente-decreciente', 'Continuo, en maquinaria constante', 'Diastólico, retumbante y de tono grave', 'Diastólico temprano y decreciente'], correct: 3 }
    ],
    explanation: 'El cuadro es compatible con insuficiencia aórtica severa: la presión de pulso amplia (150/50) refleja la fuga diastólica hacia el ventrículo, generando un pulso celer et magnus; el soplo diastólico temprano, decreciente y agudo se ausculta mejor en el foco de Erb/borde esternal izquierdo con el paciente sentado, inclinado hacia adelante, en espiración sostenida — la posición que acentúa los soplos diastólicos de base.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente de 55 años con antecedente de radioterapia torácica, presenta distensión abdominal, edema de miembros inferiores y presión venosa yugular elevada que NO cae con la inspiración.',
    steps: [
      { q: '¿Cómo se llama el hallazgo de que la PVY no caiga (o suba) con la inspiración?', options: ['Signo de Carvallo', 'Signo de Kussmaul', 'Pulsus paradoxus', 'Reflujo hepatoyugular'], correct: 1 },
      { q: 'Si además el descenso y del pulso venoso yugular es rápido y profundo (signo de Friedreich), ¿qué diagnóstico es más probable frente a un taponamiento cardiaco?', options: ['Taponamiento cardiaco, con igual patrón', 'Insuficiencia aórtica aguda, pulso amplio', 'Pericarditis constrictiva', 'Estenosis mitral, con retumbo diastólico'], correct: 2 },
      { q: '¿Por qué el descenso y difiere entre taponamiento y constricción, si en ambos la PVY está elevada?', options: ['No existe diferencia fisiopatológica real', 'Taponamiento: todo el ciclo; constricción: freno', 'El taponamiento tiene descenso y más profundo', 'El descenso y solo se altera con arritmias'], correct: 1 }
    ],
    explanation: 'El signo de Kussmaul (PVY que no cae o sube con la inspiración) y un descenso y anormal orientan hacia enfermedad pericárdica o restrictiva. La clave para diferenciar taponamiento de constricción a la cabecera es el descenso y: abolido/lento en el taponamiento (el llenado está limitado durante todo el ciclo por la presión pericárdica constante) vs. rápido y profundo (signo de Friedreich) en la constricción (la aurícula se vacía con rapidez pero el llenado ventricular se detiene abruptamente por la rigidez del pericardio).'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente masculino de 22 años, deportista, con soplo sistólico en el borde esternal izquierdo bajo detectado en un examen de rutina, sin síntomas.',
    steps: [
      { q: '¿Qué maniobra ayudaría a distinguir si este soplo corresponde a miocardiopatía hipertrófica obstructiva o a un soplo inocente/estenosis aórtica leve?', options: ['Comparar Valsalva y cuclillas', 'Auscultar solo en decúbito supino', 'Medir la presión arterial una sola vez', 'No hay maniobra que las distinga'], correct: 0 },
      { q: 'Si el soplo AUMENTA con Valsalva (fase de esfuerzo) y con la bipedestación súbita, y DISMINUYE en cuclillas, ¿qué diagnóstico es más probable?', options: ['Un soplo inocente funcional', 'Una estenosis aórtica fija', 'Una insuficiencia mitral', 'Miocardiopatía hipertrófica'], correct: 3 },
      { q: '¿Por qué estas maniobras tienen ese efecto específicamente en la MCH obstructiva?', options: ['Porque cambian la frecuencia cardiaca', 'Porque afectan la poscarga, no la precarga', 'Modifican la precarga del ventrículo', 'El efecto es azaroso, sin un mecanismo'], correct: 2 }
    ],
    explanation: 'A diferencia de la estenosis aórtica fija (que se comporta de forma más constante con estas maniobras) y de los soplos inocentes (que no cambian de forma característica), la obstrucción dinámica del tracto de salida en la MCH obstructiva empeora cuando cae la precarga (Valsalva, bipedestación súbita) y mejora cuando aumenta (cuclillas) — el patrón inverso al de la mayoría de los soplos orgánicos.'
  }
];

export const flashcards = [
  { front: 'Secuencia de la exploración cardiovascular', back: 'Inspección/palpación del precordio → pulsos arteriales periféricos → presión venosa yugular → auscultación (decúbito supino, decúbito lateral izquierdo, sentado inclinado hacia adelante).' },
  { front: 'Focos de auscultación cardiaca', back: 'Aórtico (2º EIC derecho) · Pulmonar (2º EIC izquierdo) · Erb (3er EIC izquierdo) · Tricuspídeo (4º-5º EIC izquierdo) · Mitral/ápex (5º EIC línea medioclavicular izquierda).' },
  { front: 'Diafragma vs. campana del estetoscopio', back: 'Diafragma: sonidos agudos (R1, R2, insuficiencia aórtica). Campana (presión leve): sonidos graves (R3, R4, retumbo de estenosis mitral).' },
  { front: 'Choque de la punta normal', back: '5º EIC, línea medioclavicular, ≤2-3 cm de diámetro, breve, baja amplitud.' },
  { front: 'Choque de la punta: sobrecarga de volumen vs. de presión', back: 'Volumen: desplazado y difuso (dilatación). Presión: sostenido, "en cúpula", NO desplazado (hipertrofia concéntrica).' },
  { front: 'Frémito (thrill)', back: 'Vibración palpable de un soplo intenso (≥4/6) — siempre indica cardiopatía orgánica, nunca un soplo inocente.' },
  { front: 'Pulsus parvus et tardus', back: 'Amplitud baja, ascenso lento y tardío → estenosis aórtica severa.' },
  { front: 'Pulsus celer et magnus (Corrigan)', back: 'Ascenso y colapso muy rápidos, pico alto → insuficiencia aórtica severa u otro estado de presión de pulso amplia.' },
  { front: 'Pulsus alternans', back: 'Amplitud que alterna fuerte-débil con ritmo regular → falla sistólica del ventrículo izquierdo severa.' },
  { front: 'Pulsus paradoxus', back: 'Caída inspiratoria de la PA sistólica &gt;10 mmHg → taponamiento cardiaco, pericarditis constrictiva, asma/EPOC severos (mecanismo: interdependencia ventricular).' },
  { front: 'Pulsus bisferiens', back: 'Dos picos sistólicos palpables → insuficiencia aórtica severa o miocardiopatía hipertrófica obstructiva.' },
  { front: 'Ondas del pulso venoso yugular', back: 'a: contracción auricular (~P del ECG). c: abombamiento tricuspídeo. x: relajación auricular/sístole ventricular. v: llenado auricular pasivo. y: vaciamiento rápido al abrir la tricúspide.' },
  { front: 'Onda a "cañón"', back: 'Aurícula contrayéndose contra tricúspide cerrada → disociación auriculoventricular (bloqueo AV completo).' },
  { front: 'Onda v gigante ("cv")', back: 'Insuficiencia tricuspídea severa — flujo regurgitante directo a la aurícula derecha.' },
  { front: 'Signo de Kussmaul', back: 'PVY que sube (o no cae) con la inspiración → pericarditis constrictiva, falla derecha severa, miocardiopatía restrictiva.' },
  { front: 'Reflujo hepatoyugular positivo', back: 'Elevación sostenida ≥3-4 cm de la PVY durante toda la compresión hepática (~10 s) — no un ascenso transitorio de 1-2 latidos.' },
  { front: 'Desdoblamiento fijo de R2', back: 'No varía con la respiración → comunicación interauricular.' },
  { front: 'Desdoblamiento paradójico de R2', back: 'P2 antes que A2, se estrecha con la inspiración → bloqueo de rama izquierda o estenosis aórtica severa.' },
  { front: 'R3 vs. R4', back: 'R3: llenado rápido diastólico — sobrecarga de volumen/falla ventricular (o fisiológico en jóvenes). R4: contracción auricular contra ventrículo rígido — desaparece en fibrilación auricular.' },
  { front: 'Chasquido de apertura', back: 'Estenosis mitral — intervalo R2-chasquido más corto cuanto más severa (mayor presión auricular izquierda).' },
  { front: 'Soplo inocente/funcional', back: 'Sistólico, suave (≤2/6), sin frémito, sin síntomas, R2 normal.' },
  { front: 'Signo de Carvallo', back: 'Soplo que aumenta con la inspiración → localiza el soplo al lado derecho del corazón (ej. insuficiencia tricuspídea).' },
  { front: 'Valsalva y cuclillas: MCH obstructiva vs. estenosis aórtica', back: 'Ambas maniobras mueven los dos soplos en direcciones OPUESTAS: Valsalva/bipedestación aumentan la MCH obstructiva; cuclillas/handgrip la disminuyen (lo contrario en la estenosis aórtica fija).' }
];

export default { quiz, flashcards };
