// topics/anafilaxia/study.js: Autoevaluacion de anafilaxia.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
// Fuente: practice parameter de anafilaxia de 2020 (Shaker MS, et al. J Allergy Clin Immunol
// 2020;145(4):1082-1123). 30 sueltas + 6 cascadas de 3 = 48 subpreguntas, 32 tarjetas.

export const quiz = [
  { q:'&#191;Como se diagnostica la anafilaxia en la practica?', options:['Por una triptasa serica elevada en la primera hora', 'Por la elevacion de la IgE especifica frente al alergeno', 'Con criterios clinicos, sin esperar a ninguna prueba', 'Por una prueba cutanea positiva realizada en urgencias'], correct:2, explanation:'Es un diagnostico clinico. Las pruebas confirmatorias tienen poca sensibilidad, y los criterios del National Institute of Allergy and Infectious Diseases y la Food Allergy and Anaphylaxis Network permiten decidir a pie de cama.', dificultad:'facil' },
  { q:'&#191;Cuantos de los tres criterios clinicos hay que cumplir para considerar probable la anafilaxia?', options:['Uno cualquiera de los tres', 'Dos de los tres como minimo', 'Los tres de forma simultanea', 'El primero y uno de los otros'], correct:0, explanation:'La anafilaxia es probable cuando se cumple uno de los tres criterios. Cada uno permite reconocer una forma distinta de presentacion.', dificultad:'facil' },
  { q:'&#191;Que sensibilidad tienen esos criterios en urgencias?', options:['Alrededor del 60%', 'En torno al 75%', 'Cerca del 40%', 'Cerca del 95%'], correct:3, explanation:'Sensibilidad del 95% y especificidad del 71%, con un cociente de probabilidad negativo de 0.07. Son sensibles, pero la guia recuerda que no sustituyen el juicio clinico.', dificultad:'intermedio' },
  { q:'&#191;Es necesario cumplir los criterios para administrar adrenalina?', options:['Si, porque sin ellos el riesgo supera al beneficio', 'No, puede darse si se sospecha anafilaxia inminente', 'Si, salvo cuando el paciente es un ni&#241;o peque&#241;o', 'No, pero solo si la triptasa ya esta elevada'], correct:1, explanation:'La guia lo dice de forma expresa: cumplir los criterios no es requisito para la adrenalina. Por ejemplo, un paciente en inmunoterapia con urticaria generalizada inmediata tras la inyeccion puede recibirla si se sospecha anafilaxia inminente.', dificultad:'intermedio' },
  { q:'&#191;Que permite reconocer el criterio 2, a diferencia del 1?', options:['La anafilaxia que cursa con hipotension aislada', 'La reaccion que aparece mas de 72 h despues', 'La anafilaxia sin afectacion de piel y mucosas', 'La reaccion bifasica tras una mejoria completa'], correct:2, explanation:'El criterio 2 exige dos o mas dominios tras un alergeno probable, entre los que estan el respiratorio, la hipotension y el gastrointestinal: permite diagnosticar la anafilaxia sin piel, y tambien formas leves como un exantema con vomitos.', dificultad:'intermedio' },
  { q:'&#191;Que basta para cumplir el criterio 3?', options:['Urticaria generalizada tras un alergeno probable', 'Dos dominios afectados tras un alergeno probable', 'Sibilancias y vomitos tras un alergeno desconocido', 'Hipotension tras un alergeno ya conocido'], correct:3, explanation:'La hipotension tras la exposicion a un alergeno CONOCIDO para ese paciente basta por si sola. Es el criterio que recoge el choque aislado sin piel ni sintomas respiratorios.', dificultad:'facil' },
  { q:'Un paciente llega a urgencias asintomatico tras una reaccion que, por lo que cuenta, cumplia criterios. &#191;Que diagnostico corresponde?', options:['Anafilaxia, aunque ya este resuelta', 'Reaccion alergica leve sin anafilaxia', 'Pendiente de tener una triptasa elevada', 'Urticaria aguda de causa no aclarada'], correct:0, explanation:'La guia indica que debe recibir el diagnostico de anafilaxia aunque los sintomas se hayan resuelto y la adrenalina ya no este indicada. Ese diagnostico condiciona el alta, el autoinyector y la derivacion.', dificultad:'intermedio' },
  { q:'&#191;Que valor tiene una triptasa serica normal durante la reaccion?', options:['Descarta la anafilaxia si se extrajo a tiempo', 'Confirma que la reaccion fue solo cutanea', 'No la descarta por su bajo valor negativo', 'Indica que el mecanismo no fue mediado por IgE'], correct:2, explanation:'El valor predictivo positivo de la triptasa es alto (93%), pero el negativo es bajo (17%). Se eleva con menos constancia en la anafilaxia por alimentos. Un valor normal no descarta nada.', dificultad:'intermedio' },
  { q:'&#191;Cual es la dosis de adrenalina intramuscular en la anafilaxia?', options:['0.1 mg/kg con un maximo de 1 mg', '0.01 mg/kg, maximo de 0.5 mg', '0.05 mg/kg con un maximo de 2 mg', '1 mg fijo en el adulto'], correct:1, explanation:'0.01 mg/kg de la solucion de 1 mg/mL, con un maximo de 0.5 mg en el adulto y 0.3 mg en el ni&#241;o. Se puede repetir cada 5 a 15 minutos segun la respuesta.', dificultad:'facil' },
  { q:'&#191;Donde se administra la adrenalina intramuscular?', options:['En el deltoides del brazo dominante', 'En la region glutea superoexterna', 'En el tejido subcutaneo del abdomen', 'En la cara anterolateral del muslo'], correct:3, explanation:'Las guias recomiendan la cara anterolateral del muslo. En voluntarios sanos alcanza concentraciones maximas mas altas que el deltoides y su efecto maximo en unos 10 minutos.', dificultad:'facil' },
  { q:'&#191;Cada cuanto puede repetirse la adrenalina intramuscular?', options:['Cada 5 a 15 minutos', 'Cada 30 a 60 minutos', 'Cada 1 a 2 minutos', 'Solo una vez por episodio'], correct:0, explanation:'Segun la respuesta a la inyeccion inicial, la dosis puede repetirse cada 5 a 15 minutos. La necesidad de mas de una dosis es en si misma un factor de riesgo de reaccion bifasica.', dificultad:'facil' },
  { q:'&#191;Por que la adrenalina estabiliza la reaccion ademas de tratar los sintomas?', options:['Porque bloquea los receptores H1 y H2 de histamina', 'Porque activa receptores beta-2 de mastocitos y basofilos', 'Porque inhibe la sintesis hepatica de complemento', 'Porque neutraliza la IgE especifica circulante'], correct:1, explanation:'Por los receptores beta-2 de mastocitos y basofilos frena la liberacion de mas histamina y mediadores. Por eso no solo trata los sintomas sino que puede evitar la escalada.', dificultad:'dificil' },
  { q:'&#191;Que dice la guia sobre la adrenalina intravenosa en bolo como primer tratamiento?', options:['Es de eleccion en el hospital si hay via', 'Se prefiere en el paciente con choque', 'No es primera linea por el riesgo cardiaco', 'Es equivalente a la via intramuscular'], correct:2, explanation:'No se recomienda como primera linea ni siquiera en un medio sanitario, por el riesgo de arritmias e infarto. Si la intramuscular y el suero no bastan, se pasa a perfusion titulada y monitorizada.', dificultad:'intermedio' },
  { q:'&#191;Cuando se recurre a la adrenalina en perfusion intravenosa?', options:['Si no responde a intramuscular y suero', 'En toda anafilaxia con afectacion respiratoria baja', 'Cuando la triptasa supera el doble del valor basal', 'Al conseguir una via venosa'], correct:0, explanation:'Para el paciente con respuesta inadecuada a la adrenalina intramuscular y al suero intravenoso, por microgoteo, preferiblemente con bomba y en un entorno monitorizado.', dificultad:'intermedio' },
  { q:'Con 1 mg de adrenalina en 1000 mL de salino, &#191;a que ritmo empieza la perfusion segun la guia?', options:['A 20 mL/h', 'A 600 mL/h', 'A 1200 mL/h', 'A 120 mL/h'], correct:3, explanation:'La preparacion da 1 mcg/mL. Se empieza a 2 mcg/min, que son 2 mL/min o 120 mL/h, y se sube hasta 10 mcg/min (600 mL/h), titulando por tension, frecuencia y oxigenacion.', dificultad:'dificil' },
  { q:'&#191;Hay alguna contraindicacion absoluta para la adrenalina en la anafilaxia?', options:['Si, la cardiopatia isquemica conocida', 'No, aunque en algunos hay que sopesarla', 'Si, la hipertension pulmonar grave', 'Si, la edad superior a 80 a&#241;os'], correct:1, explanation:'No existe contraindicacion absoluta. En ancianos con comorbilidad, cardiopatias congenitas complejas, hipertension pulmonar o miocardiopatia previa por adrenalina hay que sopesar sus efectos, pero no se retira.', dificultad:'intermedio' },
  { q:'&#191;Que papel tienen los antihistaminicos en la anafilaxia?', options:['Primera linea en la anafilaxia sin hipotension', 'Alternativa a la adrenalina en el cardiopata', 'Tratamiento de eleccion de la reaccion bifasica', 'Segunda linea, despues de la adrenalina'], correct:3, explanation:'Son segunda linea. Tratan el prurito, el rubor y la urticaria, pero no la hipotension ni el broncoespasmo, y no estabilizan los mastocitos. No deben darse antes ni en lugar de la adrenalina.', dificultad:'facil' },
  { q:'&#191;Cuanto tarda un antihistaminico oral en alcanzar su pico plasmatico?', options:['Entre 1 y 2 horas', 'De 5 a 10 minutos', 'De 15 a 20 minutos', 'De 4 a 6 horas'], correct:0, explanation:'Empieza a actuar en unos 30 minutos, alcanza su pico a los 60 a 120 y puede necesitar otros 60 a 90 para difundir a los tejidos. Demasiado lento para una reaccion que puede matar en minutos.', dificultad:'intermedio' },
  { q:'&#191;Cuanto pueden tardar los corticoides en producir mejoria clinica?', options:['De 10 a 20 minutos por cualquier via', 'Menos de una hora por via intravenosa', 'De 4 a 6 horas, sea cual sea la via', 'Entre 24 y 48 horas tras la dosis'], correct:2, explanation:'Actuan sobre la expresion genica y pueden tardar de 4 a 6 horas en producir mejoria, con independencia de la via. Por eso su papel en la fase aguda es limitado.', dificultad:'intermedio' },
  { q:'&#191;Que sugiere la guia sobre antihistaminicos y corticoides para prevenir la reaccion bifasica?', options:['Darlos a todos durante tres dias tras el alta', 'Darlos solo si la reaccion fue grave', 'No usarlos con ese fin, por falta de beneficio', 'Darlos solo si hubo afectacion cutanea'], correct:2, explanation:'Recomendacion condicional en contra, con certeza muy baja. No se demostro beneficio claro de los H1, los H2 ni los corticoides. Pueden usarse como tratamiento secundario, no como prevencion.', dificultad:'intermedio' },
  { q:'&#191;Que se observo con los corticoides en ni&#241;os respecto a la bifasica?', options:['Una reduccion clara de su frecuencia', 'Un aumento de su frecuencia', 'Sin efecto', 'Una reduccion solo con dosis altas'], correct:1, explanation:'Se identifico una interaccion con la edad: en ni&#241;os, los corticoides se asociaron a mas bifasicas (odds ratio 1.55), aunque no se pudo excluir el efecto de confusion de la gravedad.', dificultad:'dificil' },
  { q:'&#191;Como se define la anafilaxia bifasica?', options:['Recurrencia tras una mejoria completa', 'Reaccion que no responde del todo al tratamiento', 'Anafilaxia con afectacion de dos organos', 'Reaccion que requiere dos dosis de adrenalina'], correct:0, explanation:'Es la recurrencia tras la mejoria completa, entre 1 y 72 horas despues (se ha propuesto hasta 78). Debe distinguirse de la reaccion que no responde del todo y persiste o reaparece enseguida.', dificultad:'facil' },
  { q:'Con los criterios diagnosticos actuales, &#191;con que frecuencia aparece la bifasica?', options:['Alrededor del 20%', 'Cerca del 35%', 'Menos del 0.1%', 'En torno al 4% a 5%'], correct:3, explanation:'Los estudios antiguos, con pacientes graves y sin criterios uniformes, daban hasta un 20%. Los contemporaneos la situan en torno al 4% a 5%, con un rango del 0.18% al 14.7%.', dificultad:'intermedio' },
  { q:'&#191;Cual es el factor de riesgo de reaccion bifasica con mayor odds ratio?', options:['Una presion de pulso amplia', 'Los signos cutaneos iniciales', 'Varias dosis de adrenalina', 'Un desencadenante desconocido'], correct:2, explanation:'Necesitar mas de una dosis de adrenalina tiene un odds ratio de 4.82. Le siguen los signos cutaneos (2.54), el farmaco en el ni&#241;o (2.35), la gravedad y la presion de pulso amplia (2.11) y el desencadenante desconocido (1.63).', dificultad:'intermedio' },
  { q:'&#191;Por que los signos cutaneos ayudan poco a decidir la observacion, pese a su odds ratio?', options:['Porque son muy frecuentes en toda anafilaxia', 'Porque su odds ratio no fue significativo', 'Porque solo aparecen en la reaccion grave', 'Porque suelen ser tardios y pasan inadvertidos'], correct:0, explanation:'La guia lo se&#241;ala: incorporar los signos cutaneos a la decision tiene poca utilidad porque aparecen en la mayoria de las anafilaxias. Discriminan poco.', dificultad:'dificil' },
  { q:'Sin factores de riesgo graves y tras la resolucion completa, &#191;cuanto puede observarse antes del alta?', options:['Al menos 24 horas ingresado', 'Doce horas en planta', 'Una hora sin sintomas', 'Treinta minutos tras la dosis'], correct:2, explanation:'Para el paciente sin rasgos de riesgo grave, el alta tras 1 hora asintomatico puede ser razonable. El valor predictivo negativo de 1 hora de observacion es del 95%.', dificultad:'intermedio' },
  { q:'&#191;Que tiene que ocurrir siempre antes de dar el alta, sea cual sea la gravedad?', options:['Que la triptasa haya vuelto a su valor basal', 'Que hayan pasado 6 horas desde la adrenalina', 'Que se haya completado un ciclo de corticoide', 'Que los sintomas se hayan resuelto por completo'], correct:3, explanation:'Todo paciente queda en observacion, en un entorno capaz de tratar la anafilaxia, hasta la resolucion completa de los signos y sintomas. A partir de ahi se decide cuanto mas observar.', dificultad:'facil' },
  { q:'&#191;En que caso sugiere la guia premedicar con antihistaminicos o corticoides?', options:['Antes de un contraste de baja osmolaridad', 'En protocolos concretos de quimioterapia', 'Antes de cada dosis de infliximab', 'Tras cualquier anafilaxia por alimentos'], correct:1, explanation:'Sugiere premedicar en protocolos concretos de quimioterapia (odds ratio 0.49) y en la inmunoterapia rapida con aeroalergenos. No con infliximab sin reaccion previa ni de rutina ante contrastes de baja osmolaridad.', dificultad:'intermedio' },
  { q:'En un paciente con reaccion inmediata previa al contraste que necesita un contraste no ionico de baja osmolaridad, &#191;que sugiere la guia?', options:['Premedicar con corticoide y antihistaminico', 'Contraindicar cualquier contraste yodado futuro', 'Hacer antes una prueba cutanea con el contraste', 'No premedicar de forma rutinaria'], correct:3, explanation:'Sugiere no premedicar de rutina: no se encontro beneficio (riesgo relativo 1.07). Puede considerarse si el riesgo percibido es muy alto o hay comorbilidad de riesgo, aunque la evidencia es escasa.', dificultad:'dificil' },
  { q:'&#191;Que debe recibir todo paciente al alta tras una anafilaxia?', options:['Corticoide oral de mantenimiento durante un mes', 'Educacion, autoinyector y derivacion al alergologo', 'Antihistaminico diario de forma indefinida', 'Una cita de control con una nueva triptasa'], correct:1, explanation:'Educacion sobre la anafilaxia, el desencadenante, los sintomas, la bifasica y el uso del autoinyector, y derivacion al alergologo. En algunos casos, como un farmaco facil de evitar, el autoinyector puede diferirse con decision compartida.', dificultad:'facil' },

  { type:'cascade', vignette:'Mujer de 34 a&#241;os que, a los 10 minutos de comer en un restaurante, presenta urticaria generalizada, edema de labios y sibilancias. Tension de 104/68 y saturacion del 93%. Pesa 62 kg. Nunca habia tenido una reaccion parecida.', steps:[
    { q:'&#191;Se cumplen criterios de anafilaxia?', options:['No, porque la tension es normal', 'Si, el criterio 1', 'No, porque no hay alergeno conocido', 'Solo con vomitos'], correct:1 },
    { q:'&#191;Cual es el tratamiento inmediato?', options:['Dexclorfeniramina intravenosa', 'Metilprednisolona intravenosa', 'Salbutamol nebulizado', 'Adrenalina intramuscular'], correct:3 },
    { q:'&#191;Que dosis corresponde?', options:['Unos 0.6 mg, que se topan a 0.5 mg', 'Unos 0.3 mg por ser la primera dosis', 'Un miligramo fijo por ser adulta', 'Unos 0.06 mg por kilo de peso'], correct:0 }
  ], explanation:'Inicio agudo con afectacion cutanea y compromiso respiratorio: criterio 1, que no exige hipotension ni alergeno conocido. El tratamiento es la adrenalina intramuscular en la cara anterolateral del muslo, a 0.01 mg/kg: 0.62 mg, que se limita al maximo de 0.5 mg del adulto. Antihistaminicos y corticoides, solo despues.', dificultad:'facil' },

  { type:'cascade', vignette:'Varon de 58 a&#241;os en tratamiento con un betabloqueante. Tras una picadura de avispa presenta mareo intenso y sincope. Tension de 70/40. No tiene lesiones cutaneas ni sintomas respiratorios. Hace dos a&#241;os tuvo una reaccion sistemica a otra picadura.', steps:[
    { q:'&#191;Que criterio cumple?', options:['No cumple criterios', 'El criterio 1', 'El criterio 3', 'Solo el criterio 2'], correct:2 },
    { q:'Tras dos dosis de adrenalina intramuscular y suero, sigue con 75/45. &#191;Que procede?', options:['Adrenalina intravenosa en bolo de 1 mg', 'Adrenalina en perfusion titulada y monitorizada', 'Esperar el efecto del corticoide intravenoso', 'Antihistaminico H2 intravenoso'], correct:1 },
    { q:'&#191;Que implica haber necesitado varias dosis de adrenalina?', options:['Observacion prolongada por riesgo de bifasica', 'Alta tras una hora si queda asintomatico', 'Que el diagnostico de anafilaxia era dudoso', 'Que hay que repetir la triptasa a las 24 h'], correct:0 }
  ], explanation:'Hipotension tras un alergeno conocido para ese paciente: criterio 3, que no exige piel ni sintomas respiratorios. La respuesta inadecuada a la adrenalina intramuscular y al suero lleva a la perfusion titulada en un entorno monitorizado, no al bolo intravenoso. Necesitar mas de una dosis es el factor de riesgo de bifasica de mas peso, de modo que la observacion debe prolongarse.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 41 a&#241;os que acude por urticaria generalizada pruriginosa 30 minutos despues de tomar un antiinflamatorio. Tension de 128/80, saturacion del 99%, sin disnea, sin sintomas digestivos ni otros hallazgos. Ya le han puesto un antihistaminico en la ambulancia.', steps:[
    { q:'&#191;Se cumplen criterios de anafilaxia?', options:['Si, el criterio 1 por la urticaria', 'Si, el criterio 2', 'Si, el criterio 3 por la exposicion', 'No, es urticaria aislada'], correct:3 },
    { q:'&#191;Que conducta es adecuada?', options:['Adrenalina en perfusion intravenosa', 'Intubacion profilactica de la via aerea', 'Vigilar la aparicion de otros dominios', 'Alta inmediata sin mas observacion'], correct:2 },
    { q:'Si a los 20 minutos aparecen sibilancias y vomitos, &#191;que corresponde?', options:['Otra dosis del antihistaminico', 'Un corticoide intravenoso', 'Esperar el pico del antihistaminico', 'Adrenalina intramuscular ya'], correct:3 }
  ], explanation:'La urticaria aislada tras un alergeno no cumple criterios y puede responder a antihistaminicos, pero hay que vigilar: la anafilaxia evoluciona en minutos. Al sumarse el compromiso respiratorio y digestivo tras un alergeno probable, se cumple el criterio 2 y procede la adrenalina intramuscular. Los antihistaminicos no tratan el broncoespasmo.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Mujer de 27 a&#241;os tratada con una dosis de adrenalina por una anafilaxia leve por cacahuete con urticaria y disnea. A la hora esta asintomatica. Conoce su alergia, vive cerca del hospital y no tiene comorbilidades.', steps:[
    { q:'&#191;Cuanto tiempo de observacion es razonable?', options:['Una hora asintomatica', 'Seis horas como minimo', 'Ingreso de 24 horas', 'Hasta normalizar la triptasa'], correct:0 },
    { q:'&#191;Que conviene a&#241;adir para prevenir la bifasica?', options:['Corticoide oral durante tres dias', 'Antihistaminico cada ocho horas', 'Corticoide y antihistaminico juntos', 'Ninguno de ellos la previene'], correct:3 },
    { q:'&#191;Que se le da al alta?', options:['Un antihistaminico diario indefinido', 'Una pauta de corticoide descendente', 'Autoinyector, educacion y alergologo', 'Una cita para repetir la triptasa'], correct:2 }
  ], explanation:'Sin factores de riesgo graves y con resolucion completa, el alta tras 1 hora asintomatica puede ser razonable. Antihistaminicos y corticoides no son intervenciones fiables para prevenir la bifasica. Al alta, todos: educacion sobre la anafilaxia y la bifasica, autoinyector y derivacion al alergologo.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 75 a&#241;os con cardiopatia isquemica que vive solo en una zona rural sin ambulancia cercana. Ha sufrido una anafilaxia grave por un antibiotico, tratada con dos dosis de adrenalina intramuscular. Lleva una hora asintomatico.', steps:[
    { q:'&#191;Cuantos factores de riesgo de bifasica de peso tiene?', options:['Solo uno, la edad', 'Tres, contando la edad', 'Dos: gravedad y dosis', 'Uno, el antibiotico'], correct:2 },
    { q:'&#191;Que observacion procede?', options:['Prolongada: 6 h o ingreso', 'Una hora mas y alta a domicilio', 'Alta con corticoide oral tres dias', 'Alta si la triptasa es normal'], correct:0 },
    { q:'&#191;Su cardiopatia contraindica la adrenalina si recurre?', options:['Si, se sustituye por antihistaminico', 'No, aunque hay que sopesar sus efectos', 'Si, se usa solo glucagon intravenoso', 'Si, salvo con monitorizacion invasiva'], correct:1 }
  ], explanation:'Anafilaxia grave y mas de una dosis de adrenalina: los dos factores que llevan a la guia a sugerir observacion prolongada. Ademas tiene factores de riesgo de anafilaxia mortal (comorbilidad cardiovascular y falta de acceso a emergencias), que justifican hasta 6 horas o mas, incluido el ingreso. No existe contraindicacion absoluta para la adrenalina en la anafilaxia.', dificultad:'dificil' },

  { type:'cascade', vignette:'Mujer de 52 a&#241;os con un cancer de ovario que va a recibir un protocolo de quimioterapia con un taxano. Tiene antecedente de una reaccion inmediata leve a un contraste yodado hace a&#241;os, y la semana que viene necesita una tomografia con contraste no ionico de baja osmolaridad.', steps:[
    { q:'&#191;Que sugiere la guia para la quimioterapia?', options:['Contraindicarla por el riesgo de reaccion', 'Desensibilizar sin premedicacion alguna', 'Premedicar si el protocolo lo indica', 'Administrarla solo en la unidad de criticos'], correct:2 },
    { q:'&#191;Y para la tomografia con contraste de baja osmolaridad?', options:['No premedicar de rutina', 'Premedicar con corticoide y antihistaminico', 'Una resonancia', 'Hacer antes una prueba cutanea'], correct:0 },
    { q:'Si se premedica, &#191;que no debe faltar?', options:['Triptasa basal', 'Ayuno de doce horas previo', 'Un antihistaminico H2 asociado', 'Adrenalina disponible'], correct:3 }
  ], explanation:'La guia sugiere premedicar con antihistaminicos o corticoides cuando lo indica un protocolo concreto de quimioterapia, y sugiere no hacerlo de rutina ante un contraste no ionico de baja osmolaridad o isoosmolar en quien tuvo una reaccion previa. La premedicacion puede fallar, de modo que la adrenalina tiene que estar disponible siempre.', dificultad:'dificil' }
];

export const flashcards = [
  { front:'Definicion de anafilaxia', back:'Reaccion alergica SISTEMICA aguda y potencialmente mortal, con manifestaciones muy variadas. El diagnostico es CLINICO.' },
  { front:'Criterio 1', back:'Inicio agudo con piel o mucosas MAS compromiso respiratorio o hipotension con sintomas de disfuncion de organo.' },
  { front:'Criterio 2', back:'Dos o mas de: piel-mucosas, respiratorio, hipotension, gastrointestinal; tras un alergeno PROBABLE. Permite la anafilaxia sin piel.' },
  { front:'Criterio 3', back:'Hipotension tras un alergeno CONOCIDO para ese paciente. Basta por si sola.' },
  { front:'Cuantos criterios hacen falta', back:'UNO de los tres. Sensibilidad 95%, especificidad 71%, cociente de probabilidad negativo 0.07.' },
  { front:'Criterios y adrenalina', back:'Cumplirlos NO es requisito para la adrenalina. Si se sospecha anafilaxia inminente, se administra.' },
  { front:'Paciente asintomatico que cumplio criterios', back:'Recibe el diagnostico de anafilaxia aunque la adrenalina ya no este indicada.' },
  { front:'Triptasa serica', back:'Valor predictivo positivo 93%, negativo 17%. Normal NO descarta, sobre todo en la anafilaxia por alimentos.' },
  { front:'Dosis de adrenalina intramuscular', back:'0.01 mg/kg de la solucion 1 mg/mL. Maximo 0.5 mg en el adulto y 0.3 mg en el ni&#241;o.' },
  { front:'Donde se pone la adrenalina', back:'Cara anterolateral del MUSLO. Mejor que el deltoides y que la via subcutanea. Efecto maximo en unos 10 min.' },
  { front:'Repeticion de la adrenalina', back:'Cada 5 a 15 minutos segun la respuesta.' },
  { front:'Por que la adrenalina previene la escalada', back:'Por los receptores beta-2 de mastocitos y basofilos frena la liberacion de mas mediadores.' },
  { front:'Adrenalina intravenosa en bolo', back:'NO es primera linea, ni siquiera en el hospital, por el riesgo de arritmias e infarto.' },
  { front:'Anafilaxia refractaria', back:'Respuesta inadecuada a adrenalina intramuscular y suero: perfusion de adrenalina, preferiblemente con bomba y monitorizacion.' },
  { front:'Perfusion sin bomba segun la guia', back:'1 mg en 1000 mL de salino (1 mcg/mL). Empezar a 2 mcg/min (120 mL/h) y subir hasta 10 mcg/min (600 mL/h).' },
  { front:'Contraindicaciones de la adrenalina en la anafilaxia', back:'No hay ninguna absoluta. En ancianos con comorbilidad o cardiopatias complejas se sopesan sus efectos.' },
  { front:'Antihistaminicos', back:'Segunda linea. Tratan piel y comodidad, no la hipotension ni el broncoespasmo. Nunca antes ni en lugar de la adrenalina.' },
  { front:'Rapidez de los antihistaminicos orales', back:'Inicio en unos 30 min, pico a los 60 a 120 min, y otros 60 a 90 para difundir a los tejidos.' },
  { front:'Corticoides en la anafilaxia', back:'Sin beneficio demostrado en la fase aguda. Pueden tardar de 4 a 6 horas en producir mejoria, sea cual sea la via.' },
  { front:'Prevenir la bifasica con antihistaminicos o corticoides', back:'La guia sugiere NO usarlos con ese fin. H1 0.71, H2 1.21, corticoides 0.87: sin beneficio claro.' },
  { front:'Corticoides en ni&#241;os y bifasica', back:'Se asociaron a MAS bifasicas (odds ratio 1.55), sin poder excluir el efecto de la gravedad.' },
  { front:'Anafilaxia bifasica', back:'Recurrencia tras la mejoria COMPLETA, entre 1 y 72 horas despues. No confundir con la reaccion persistente.' },
  { front:'Frecuencia de la bifasica', back:'Con criterios actuales, en torno al 4% a 5% (rango 0.18% a 14.7%). Los estudios antiguos daban hasta un 20%.' },
  { front:'Factor de riesgo de bifasica de mas peso', back:'Mas de una dosis de adrenalina: odds ratio 4.82.' },
  { front:'Otros factores de riesgo de bifasica', back:'Gravedad (2.11), presion de pulso amplia (2.11), desencadenante desconocido (1.63), signos cutaneos (2.54) y farmaco en el ni&#241;o (2.35).' },
  { front:'Observacion sin factores de riesgo graves', back:'El alta tras 1 hora asintomatico puede ser razonable. Valor predictivo negativo del 95%.' },
  { front:'Observacion con riesgo alto', back:'Hasta 6 horas o mas, incluido el ingreso, si el riesgo de bifasica es del 17% o mas o hay factores de riesgo de muerte.' },
  { front:'Factores de riesgo de anafilaxia grave o mortal', back:'Enfermedad cardiovascular, asma, edad avanzada, mastocitosis, betabloqueantes e inhibidores de la enzima convertidora.' },
  { front:'Premedicacion: donde si', back:'Protocolos concretos de quimioterapia e inmunoterapia rapida con aeroalergenos.' },
  { front:'Premedicacion: donde no de rutina', back:'Infliximab sin reaccion previa, y contraste no ionico de baja osmolaridad tras una reaccion inmediata previa.' },
  { front:'Al alta, a todos', back:'Educacion (desencadenante, sintomas, bifasica, adrenalina), autoinyector y derivacion al alergologo.' },
  { front:'Desencadenantes por edad', back:'Adultos: farmacos y himenopteros. Ni&#241;os y adolescentes: alimentos y himenopteros.' }
];

export default { quiz, flashcards };
