// topics/bronquiectasias/study.js: Autoevaluacion de Bronquiectasias.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// 48 subpreguntas (30 sueltas + 6 cascadas de 3 pasos) y 32 tarjetas.
// Sin em dash (ver [[feedback-no-em-dash]]). Texto sin acentos.

export const quiz = [
  { q: 'Cual es la prueba diagnostica de las bronquiectasias?', options: ['La radiografia de torax', 'La tomografia de alta resolucion', 'La espirometria con broncodilatador', 'La broncoscopia con lavado'], correct: 1, explanation: 'Busca el cociente broncoarterial mayor de 1, la falta de afilamiento del bronquio hacia la periferia y los bronquios visibles a menos de 1 cm de la pleura. La espirometria informa de la funcion pero no diagnostica la dilatacion.', dificultad: 'facil' },
  { q: 'Que describe el signo del anillo de sello?', options: ['Un bronquio ocupado por moco', 'Una arteria pulmonar dilatada', 'Un quiste con nivel hidroaereo', 'Un bronquio mayor que su arteria'], correct: 3, explanation: 'En el corte transversal, el bronquio dilatado junto a su arteria acompa&#241;ante recuerda a un anillo con su piedra. Es el criterio radiologico central del diagnostico.', dificultad: 'intermedio' },
  { q: 'Que valor tiene una radiografia de torax normal ante la sospecha?', options: ['No descarta bronquiectasias', 'Las descarta con seguridad', 'Obliga a repetirla en 6 meses', 'Indica enfermedad leve'], correct: 0, explanation: 'La radiografia es poco sensible y puede ser normal con bronquiectasias extensas. Aceptarla como prueba de exclusion es una de las causas principales del retraso diagnostico, que en estos pacientes se mide en a&#241;os.', dificultad: 'facil' },
  { q: 'Que describe el circulo vicioso de las bronquiectasias?', options: ['Broncoespasmo, tos y disnea repetidos', 'Hipoxemia, vasoconstriccion y fibrosis', 'Infeccion, inflamacion y mal aclaramiento', 'Reflujo, aspiracion y neumonia de repeticion'], correct: 2, explanation: 'El moco retenido permite la colonizacion; las bacterias atraen neutrofilos; los neutrofilos destruyen la pared bronquial; el bronquio dilatado se limpia todavia peor. Entenderlo explica el tratamiento entero, que actua en los tres puntos a la vez.', dificultad: 'intermedio' },
  { q: 'Que prueba forma parte del estudio etiologico de TODOS los pacientes?', options: ['El cloro en sudor', 'El oxido nitrico nasal', 'La alfa-1-antitripsina', 'Las inmunoglobulinas sericas'], correct: 3, explanation: 'A todos se les pide hemograma, inmunoglobulinas sericas, estudio de Aspergillus y cultivo de esputo con micobacterias. Las otras tres pruebas son parte del estudio DIRIGIDO, que se pide segun las pistas clinicas.', dificultad: 'intermedio' },
  { q: 'Por que se piden inmunoglobulinas a todos los pacientes?', options: ['Porque predicen las exacerbaciones', 'Porque detectan una causa tratable', 'Porque orientan sobre la extension', 'Porque miden la actividad inflamatoria'], correct: 1, explanation: 'Detectan la inmunodeficiencia comun variable, que se trata con inmunoglobulinas sustitutivas y que se diagnostica con a&#241;os de retraso. Es una de las omisiones mas costosas del estudio etiologico.', dificultad: 'intermedio' },
  { q: 'Que hay que pedir de forma explicita en el cultivo de esputo?', options: ['La determinacion de la carga bacteriana', 'El antibiograma frente a quinolonas', 'El cultivo de micobacterias', 'La tincion de Gram cuantitativa'], correct: 2, explanation: 'El cultivo de micobacterias no se realiza si no se solicita, y su omision lleva a dar macrolidos en monoterapia sobre una micobacteria no diagnosticada, lo que crea resistencia y arruina el tratamiento futuro.', dificultad: 'intermedio' },
  { q: 'Que sugiere la afectacion de lobulo medio y lingula en una mujer mayor?', options: ['Micobacterias no tuberculosas', 'Fibrosis quistica del adulto', 'Aspergilosis broncopulmonar', 'Discinesia ciliar primaria'], correct: 0, explanation: 'Es el patron del sindrome de Lady Windermere: mujer mayor, delgada y no fumadora con afectacion de lobulo medio y lingula. Obliga a pedir de forma explicita cultivos de esputo para micobacterias.', dificultad: 'dificil' },
  { q: 'Que corresponde ante bronquiectasias localizadas en una sola zona?', options: ['Iniciar antibiotico inhalado', 'Hacer broncoscopia', 'Pedir cloro en sudor', 'Repetir la tomografia al a&#241;o'], correct: 1, explanation: 'La afectacion de una sola zona sugiere obstruccion bronquial: cuerpo extra&#241;o, tumor endobronquial o estenosis. Es una de las pocas indicaciones claras de broncoscopia en este tema y no debe posponerse.', dificultad: 'intermedio' },
  { q: 'Cual es la base del tratamiento cronico en todos los pacientes?', options: ['El antibiotico inhalado', 'El corticoide inhalado', 'El macrolido a largo plazo', 'La fisioterapia respiratoria'], correct: 3, explanation: 'Es la medida mas costoeficaz del tema y a la vez la peor prescrita: una proporcion alta de pacientes nunca ha sido instruida por un fisioterapeuta. Actua sobre el eslabon del circulo vicioso que mas se puede modificar.', dificultad: 'facil' },
  { q: 'Cuando esta indicado un macrolido a largo plazo?', options: ['Ante cualquier colonizacion cronica', 'Ante un FEV1 por debajo del 50%', 'Ante 3 o mas exacerbaciones al a&#241;o', 'Ante bronquiectasias quisticas difusas'], correct: 2, explanation: 'Los ensayos controlados mostraron una reduccion de aproximadamente la mitad de las exacerbaciones. El beneficio se atribuye mas al efecto inmunomodulador del macrolido que a su actividad antibiotica directa.', dificultad: 'intermedio' },
  { q: 'Que hay que descartar antes de iniciar un macrolido a largo plazo?', options: ['Micobacterias no tuberculosas', 'Colonizacion por Pseudomonas', 'Aspergilosis broncopulmonar', 'Deficit de alfa-1-antitripsina'], correct: 0, explanation: 'Se pide cultivo de esputo para micobacterias antes de empezar. Es un paso que se salta con frecuencia y cuya omision tiene una consecuencia concreta e irreversible sobre el tratamiento futuro del paciente.', dificultad: 'intermedio' },
  { q: 'Por que hay que descartar micobacterias antes del macrolido?', options: ['Porque el macrolido las enmascara', 'Porque aumenta la toxicidad hepatica', 'Porque prolonga mas el intervalo QT', 'Porque en monoterapia crea resistencia'], correct: 3, explanation: 'El macrolido es el pilar del tratamiento de la micobacteriosis, que exige al menos tres farmacos. Darlo solo sobre una micobacteria no diagnosticada selecciona resistencia y deja al paciente sin el unico tratamiento eficaz.', dificultad: 'dificil' },
  { q: 'Cuando estan indicados los corticoides inhalados en las bronquiectasias?', options: ['En la colonizacion por Pseudomonas', 'Solo si coexiste asma o EPOC', 'En las formas quisticas extensas', 'Tras cada exacerbacion grave'], correct: 1, explanation: 'No se usan de rutina, a diferencia de la EPOC. Aumentan el riesgo de neumonia y de infeccion por micobacterias no tuberculosas, de modo que su uso sin indicacion clara hace mas da&#241;o que beneficio.', dificultad: 'intermedio' },
  { q: 'Que ocurrio con la DNasa recombinante en las bronquiectasias no debidas a fibrosis quistica?', options: ['Empeoro los resultados', 'Redujo las exacerbaciones', 'Mejoro la calidad de vida', 'Mostro un efecto neutro'], correct: 0, explanation: 'En un ensayo controlado empeoro la funcion pulmonar y aumento las exacerbaciones, de modo que esta contraindicada. Es un ejemplo clasico de que lo que funciona en la fibrosis quistica no se puede extrapolar.', dificultad: 'dificil' },
  { q: 'Cuando se usa un antibiotico inhalado a largo plazo?', options: ['En toda bronquiectasia moderada', 'Tras la primera exacerbacion que requiere ingreso', 'Con Pseudomonas cronica y exacerbaciones', 'En la colonizacion por Haemophilus'], correct: 2, explanation: 'Alcanza concentraciones muy altas en la via aerea con escasa absorcion sistemica, lo que permite suprimir la carga bacteriana sin la toxicidad de la via sistemica. La primera dosis se supervisa por el riesgo de broncoespasmo.', dificultad: 'intermedio' },
  { q: 'Que define una exacerbacion de bronquiectasias?', options: ['Fiebre con esputo purulento de 24 horas', '3 de 6 sintomas durante 48 horas o mas', 'Un aumento de la proteina C reactiva', 'Un nuevo infiltrado en la radiografia'], correct: 1, explanation: 'Los seis sintomas son tos, volumen o consistencia del esputo, purulencia, disnea o tolerancia al ejercicio, fatiga y hemoptisis. La ausencia de fiebre NO descarta la exacerbacion y es de hecho frecuente.', dificultad: 'intermedio' },
  { q: 'Que hay que hacer antes de iniciar el antibiotico en una exacerbacion?', options: ['Una radiografia de torax', 'Una gasometria arterial', 'Una espirometria de control', 'Un cultivo de esputo'], correct: 3, explanation: 'Es el gesto que mas se salta y el que mas cuesta despues: una vez iniciado el antibiotico el cultivo pierde valor y el paciente se queda sin mapa microbiologico para la siguiente exacerbacion.', dificultad: 'facil' },
  { q: 'Cuanto dura el antibiotico en una exacerbacion de bronquiectasias?', options: ['14 dias', '5 dias', '7 dias', '21 dias'], correct: 0, explanation: 'Es una duracion mucho mas larga que en la bronquitis aguda o en la exacerbacion de EPOC. La biopelicula y la carga bacteriana alta de una via aerea da&#241;ada no se resuelven con pautas cortas, que dejan al paciente recayendo.', dificultad: 'intermedio' },
  { q: 'A que se dirige el antibiotico empirico de una exacerbacion?', options: ['Al germen mas frecuente en general', 'A la flora habitual de la comunidad', 'Al ultimo aislamiento del paciente', 'Al patogeno de la ultima temporada'], correct: 2, explanation: 'La exacerbacion no suele ser la llegada de un germen nuevo sino el crecimiento del que ya estaba, de modo que el historico de cultivos del propio paciente es la mejor guia mientras llega el resultado actual.', dificultad: 'intermedio' },
  { q: 'Que se hace con la fisioterapia respiratoria durante una exacerbacion?', options: ['Se suspende hasta la mejoria', 'Se reduce a una sesion diaria', 'Se sustituye por nebulizaciones', 'Se intensifica y se hace mas veces'], correct: 3, explanation: 'Es justo cuando mas secreciones hay que movilizar. Suspenderla durante la exacerbacion, que es un error frecuente, favorece la retencion de moco y prolonga el episodio.', dificultad: 'facil' },
  { q: 'Que corresponde ante un PRIMER aislamiento de Pseudomonas?', options: ['Intentar la erradicacion', 'Iniciar antibiotico inhalado', 'Repetir el cultivo en un a&#241;o', 'Aumentar la dosis de macrolido'], correct: 0, explanation: 'Es una oportunidad terapeutica que no se repite: antes de que la biopelicula este establecida, la erradicacion todavia es posible, habitualmente con una fluoroquinolona oral sola o combinada con un antibiotico inhalado.', dificultad: 'intermedio' },
  { q: 'Que define la colonizacion cronica por Pseudomonas?', options: ['Un cultivo positivo con esputo verdoso', '2 cultivos separados 3 meses en un a&#241;o', '3 cultivos positivos consecutivos', 'Un cultivo positivo con fenotipo mucoide'], correct: 1, explanation: 'La separacion temporal es lo que distingue una colonizacion establecida de aislamientos agrupados durante una exacerbacion. Establecida la cronicidad, el objetivo pasa de erradicar a suprimir la carga bacteriana.', dificultad: 'dificil' },
  { q: 'Que supone la colonizacion cronica por Pseudomonas?', options: ['Contraindica el trasplante pulmonar', 'Obliga a suspender la fisioterapia', 'Peor pronostico y mas exacerbaciones', 'Mejor respuesta a los macrolidos'], correct: 2, explanation: 'Se asocia a mas exacerbaciones, peor funcion pulmonar, mas ingresos y mayor mortalidad, y aporta 3 puntos en el indice de gravedad. No contraindica el trasplante, aunque condiciona la profilaxis perioperatoria.', dificultad: 'intermedio' },
  { q: 'Que define el sindrome de Kartagener?', options: ['Situs inversus, sinusitis y bronquiectasias', 'Poliposis, asma e intolerancia a la aspirina', 'Sinusitis, artritis y nefritis', 'Bronquiectasias, esterilidad e hipogammaglobulinemia'], correct: 0, explanation: 'Corresponde a una discinesia ciliar primaria. Los cilios determinan la lateralidad durante el desarrollo embrionario, y por eso alrededor de la mitad de estos pacientes tiene situs inversus.', dificultad: 'intermedio' },
  { q: 'Que hallazgo debe hacer pensar en fibrosis quistica en un adulto?', options: ['Bronquiectasias en lobulos inferiores', 'Colonizacion por Haemophilus influenzae', 'Acropaquias marcadas y bajo peso', 'Infertilidad masculina y malabsorcion'], correct: 3, explanation: 'La ausencia bilateral congenita de conductos deferentes se asocia a mutaciones del gen CFTR. Junto con las bronquiectasias de predominio en lobulos SUPERIORES y la pancreatitis de repeticion, obliga a pedir cloro en sudor y estudio genetico.', dificultad: 'intermedio' },
  { q: 'Cual es el cribado inicial de la discinesia ciliar primaria?', options: ['La biopsia bronquial con microscopia', 'El estudio genetico de rutina', 'El oxido nitrico nasal', 'El aclaramiento mucociliar con isotopos'], correct: 2, explanation: 'Un valor muy bajo hace muy probable el diagnostico, que despues se confirma con microscopia electronica, videomicroscopia de alta velocidad o estudio genetico en un centro de referencia.', dificultad: 'dificil' },
  { q: 'Que criterio microbiologico exige el diagnostico de micobacteriosis pulmonar?', options: ['Un cultivo positivo de esputo', '2 cultivos positivos de esputo', 'Una baciloscopia positiva', 'Una prueba molecular positiva'], correct: 1, explanation: 'Hacen falta 2 cultivos de esputo positivos en muestras distintas, o 1 de lavado broncoalveolar o de biopsia, ademas de criterios clinicos y radiologicos. La exigencia sirve para separar la colonizacion de la enfermedad.', dificultad: 'dificil' },
  { q: 'Que patron clinico hace sospechar micobacterias no tuberculosas?', options: ['Exacerbaciones que ceden con quinolonas', 'Hemoptisis leve de repeticion', 'Fiebre alta de inicio brusco', 'Deterioro progresivo que no responde'], correct: 3, explanation: 'El paciente no tiene exacerbaciones tipicas sino un empeoramiento mantenido pese a ciclos repetidos de antibiotico, con perdida de peso y fatiga. Ese patron es la principal pista clinica.', dificultad: 'intermedio' },
  { q: 'Como se trata una micobacteriosis pulmonar que precisa tratamiento?', options: ['Con al menos tres farmacos', 'Con un macrolido en monoterapia', 'Con quinolona durante 6 meses', 'Con rifampicina y etambutol'], correct: 0, explanation: 'Un macrolido como pilar junto a rifampicina y etambutol, durante 12 meses tras la negativizacion de los cultivos, a&#241;adiendo amikacina en las formas graves. La regla que gobierna el tema es no dar nunca un macrolido solo.', dificultad: 'intermedio' },

  { type: 'cascade', dificultad: 'dificil',
    vignette: 'Varon de 68 a&#241;os con bronquiectasias difusas. Indice de masa corporal de 21 y FEV1 del 55% del predicho. Disnea de grado 3 en la escala del Medical Research Council. Ingreso por exacerbacion hace 8 meses y 4 exacerbaciones en el ultimo a&#241;o. En los cultivos crece Pseudomonas aeruginosa de forma repetida. La tomografia muestra 4 lobulos afectados con areas quisticas.',
    steps: [
      { q: 'Cuantos puntos suma en el indice de gravedad?', options: ['8 puntos', '11 puntos', '14 puntos', '17 puntos'], correct: 2 },
      { q: 'Que categoria de gravedad corresponde?', options: ['Gravedad grave', 'Gravedad leve', 'Gravedad moderada', 'No se puede valorar'], correct: 0 },
      { q: 'Que dos elementos aportan mas puntos en este caso?', options: ['La edad y el FEV1', 'La extension y el peso', 'La disnea y las exacerbaciones', 'El ingreso y la Pseudomonas'], correct: 3 }
    ],
    explanation: 'Suma 14 puntos: edad de 68 a&#241;os (2), FEV1 del 55% (1), ingreso en los ultimos 2 a&#241;os (5), 3 o mas exacerbaciones (2), Pseudomonas (3) y 3 o mas lobulos con areas quisticas (1). El indice de masa corporal de 21 y la disnea de grado 3 no puntuan. Con 9 o mas puntos la gravedad es GRAVE, con riesgo alto de mortalidad, ingresos y exacerbaciones. Los dos elementos de mayor peso son el ingreso previo y la colonizacion por Pseudomonas, lo que refleja que la historia reciente y la microbiologia del paciente pesan mas que cualquier cifra funcional aislada.' },

  { type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 44 a&#241;os con bronquiectasias difusas y tos productiva desde la infancia. Refiere otitis media de repeticion durante la ni&#241;ez, rinosinusitis persistente desde entonces y esterilidad de causa no filiada. En la radiografia de torax llama la atencion una dextrocardia.',
    steps: [
      { q: 'Que hay que sospechar?', options: ['Una fibrosis quistica leve', 'Una discinesia ciliar primaria', 'Una inmunodeficiencia comun variable', 'Una aspergilosis broncopulmonar'], correct: 1 },
      { q: 'Que prueba de cribado corresponde?', options: ['El cloro en sudor en dos ocasiones', 'Las precipitinas frente a Aspergillus', 'La determinacion de alfa-1-antitripsina', 'El oxido nitrico nasal'], correct: 3 },
      { q: 'Como se llama la triada que presenta?', options: ['Sindrome de Kartagener', 'Sindrome de Young', 'Sindrome de Mounier-Kuhn', 'Sindrome de Swyer-James'], correct: 0 }
    ],
    explanation: 'La combinacion de otitis media cronica infantil, rinosinusitis persistente, bronquiectasias e infertilidad apunta a discinesia ciliar primaria, y la dextrocardia lo confirma como sospecha: los cilios determinan la lateralidad durante el desarrollo embrionario, de modo que alrededor de la mitad de estos pacientes tiene situs inversus. Situs inversus, sinusitis y bronquiectasias forman el sindrome de Kartagener. El cribado inicial es el oxido nitrico nasal, muy bajo en esta enfermedad, y la confirmacion se hace en un centro de referencia con microscopia electronica, videomicroscopia o estudio genetico.' },

  { type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 57 a&#241;os con bronquiectasias postinfecciosas. Desde hace 4 dias tiene mas tos, expectora mas cantidad y el esputo se ha vuelto claramente purulento, y se ahoga al subir un piso que antes subia sin parar. Esta afebril. En el ultimo cultivo, hace 5 meses, crecio Pseudomonas aeruginosa.',
    steps: [
      { q: 'Cumple la definicion de exacerbacion?', options: ['Si: 4 sintomas durante mas de 48 horas', 'No: no tiene fiebre', 'No: no lleva 48 horas de evolucion todavia', 'No: solo hay 3 sintomas'], correct: 0 },
      { q: 'Que es lo PRIMERO que hay que hacer?', options: ['Iniciar amoxicilina-clavulanico', 'Pedir una tomografia urgente', 'Recoger un cultivo de esputo', 'Pautar corticoide oral 5 dias'], correct: 2 },
      { q: 'Que antibiotico y durante cuanto tiempo?', options: ['Amoxicilina-clavulanico 7 dias', 'Cubriendo Pseudomonas 14 dias', 'Azitromicina 3 dias', 'Levofloxacino 5 dias'], correct: 1 }
    ],
    explanation: 'Tiene cuatro de los seis sintomas (tos, volumen del esputo, purulencia y disnea) durante 4 dias, de modo que cumple la definicion. La fiebre no forma parte de los criterios y su ausencia no descarta nada. Lo primero es RECOGER EL CULTIVO antes de dar el antibiotico: es el paso que mas se omite y el que deja al paciente sin mapa microbiologico para la proxima vez. El antibiotico empirico se dirige al ultimo aislamiento del propio paciente, que aqui es Pseudomonas, y la duracion habitual es de 14 dias, no de 5 ni 7. Y la fisioterapia respiratoria se intensifica, no se suspende.' },

  { type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 62 a&#241;os con bronquiectasias idiopaticas y unas 2 exacerbaciones al a&#241;o. En un cultivo de esputo de rutina, hecho en fase estable, crece por primera vez Pseudomonas aeruginosa. En todos los cultivos anteriores habian crecido otros microorganismos.',
    steps: [
      { q: 'Que corresponde ante este hallazgo?', options: ['Iniciar antibiotico inhalado cronico', 'No hacer nada: no hay exacerbacion', 'Iniciar un macrolido a largo plazo', 'Intentar la erradicacion'], correct: 3 },
      { q: 'Por que el primer aislamiento se maneja distinto?', options: ['Porque la cepa suele ser sensible', 'Porque la biopelicula no esta formada', 'Porque no hay sintomas todavia', 'Porque el cultivo puede ser un error'], correct: 1 },
      { q: 'Que hay que hacer despues del intento?', options: ['Repetir la tomografia de torax', 'Iniciar corticoide inhalado', 'Repetir cultivos de control', 'Medir la funcion pulmonar mensual'], correct: 2 }
    ],
    explanation: 'El primer aislamiento de Pseudomonas es una oportunidad terapeutica que no se repite: antes de que la biopelicula este establecida, la erradicacion todavia es posible, habitualmente con una fluoroquinolona oral con actividad frente a Pseudomonas durante varias semanas, sola o combinada con un antibiotico inhalado. Una vez formada la biopelicula, la matriz protege a la bacteria de los antibioticos y del sistema inmunitario y eliminarla resulta practicamente imposible. Despues del intento hay que repetir cultivos de control para saber si ha funcionado, porque de eso depende todo el manejo posterior. Y en paralelo, reforzar el aclaramiento de secreciones.' },

  { type: 'cascade', dificultad: 'dificil',
    vignette: 'Varon de 71 a&#241;os con bronquiectasias difusas y 4 exacerbaciones en el ultimo a&#241;o pese a hacer fisioterapia respiratoria correcta a diario y estar vacunado. Se plantea a&#241;adir azitromicina a largo plazo para reducir las exacerbaciones.',
    steps: [
      { q: 'Que hay que hacer ANTES de iniciarla?', options: ['Una espirometria con broncodilatador', 'Una tomografia de alta resolucion', 'Cultivos para micobacterias', 'Una gasometria arterial basal'], correct: 2 },
      { q: 'Que otras dos comprobaciones corresponden?', options: ['Funcion renal y potasio', 'Vision y sensibilidad distal', 'Peso y presion arterial', 'Intervalo QT y audicion'], correct: 3 },
      { q: 'Crece Mycobacterium avium en dos esputos. Que corresponde?', options: ['NO dar azitromicina sola', 'Iniciar la azitromicina igualmente', 'Bajar la dosis de azitromicina', 'Alternar azitromicina y descanso'], correct: 0 }
    ],
    explanation: 'El macrolido a largo plazo esta indicado con 3 o mas exacerbaciones al a&#241;o, pero antes hay que DESCARTAR micobacterias no tuberculosas con cultivos de esputo, y comprobar el intervalo QT y la audicion por el riesgo de prolongacion del QT y de ototoxicidad. Si crece una micobacteria, la azitromicina en monoterapia esta contraindicada: el macrolido es el pilar del tratamiento de la micobacteriosis, que exige al menos tres farmacos, y darlo solo selecciona resistencia y deja al paciente sin el unico tratamiento eficaz. Habria que valorar entonces si esa micobacteria cumple criterios de enfermedad y precisa tratamiento completo.' },

  { type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 59 a&#241;os con bronquiectasias idiopaticas que refiere esputo muy espeso y dificil de expectorar pese a hacer fisioterapia respiratoria a diario. No tiene asma ni EPOC. Se plantea a&#241;adir algo que facilite el aclaramiento de secreciones.',
    steps: [
      { q: 'Que tratamiento esta CONTRAINDICADO en esta paciente?', options: ['El suero salino hipertonico', 'La DNasa recombinante', 'El manitol inhalado', 'La fisioterapia con dispositivo'], correct: 1 },
      { q: 'Por que?', options: ['Porque empeoro los resultados', 'Porque produce broncoespasmo grave', 'Porque no llega a la via aerea distal', 'Porque interacciona con los antibioticos inhalados'], correct: 0 },
      { q: 'Que si se le puede ofrecer?', options: ['Corticoide inhalado a dosis media', 'Antibiotico inhalado profilactico', 'Suero salino hipertonico supervisado', 'Mucolitico oral a dosis altas'], correct: 2 }
    ],
    explanation: 'La DNasa recombinante funciona en la fibrosis quistica pero esta CONTRAINDICADA en las bronquiectasias de otras causas: en un ensayo controlado empeoro la funcion pulmonar y aumento las exacerbaciones. Es el ejemplo clasico de que lo que sirve en la fibrosis quistica no se puede extrapolar. Lo que si puede ayudar como coadyuvante del aclaramiento es el suero salino hipertonico o el manitol inhalado, siempre con broncodilatador previo y con la PRIMERA DOSIS SUPERVISADA por el riesgo de broncoespasmo. Y el corticoide inhalado no esta indicado aqui, porque la paciente no tiene asma ni EPOC.' }
];

export const flashcards = [
  { front: 'Que son las bronquiectasias', back: 'Dilatacion bronquial IRREVERSIBLE. No una enfermedad, sino un resultado final comun.' },
  { front: 'Prueba diagnostica', back: 'TOMOGRAFIA DE ALTA RESOLUCION. La radiografia normal no descarta nada.' },
  { front: 'Criterio radiologico central', back: 'Cociente broncoarterial mayor de 1: el signo del anillo de sello.' },
  { front: 'El circulo vicioso', back: 'Infeccion, inflamacion, da&#241;o de la pared y peor aclaramiento, que realimenta la infeccion.' },
  { front: 'Estudio etiologico de TODOS', back: 'Hemograma, INMUNOGLOBULINAS, estudio de Aspergillus y cultivo con MICOBACTERIAS.' },
  { front: 'Por que las inmunoglobulinas', back: 'Detectan la inmunodeficiencia comun variable, una causa TRATABLE con sustitucion.' },
  { front: 'Distribucion en lobulos superiores', back: 'Fibrosis quistica, aspergilosis broncopulmonar alergica o tuberculosis previa.' },
  { front: 'Distribucion en lobulo medio y lingula', back: 'Micobacterias no tuberculosas: el sindrome de Lady Windermere.' },
  { front: 'Bronquiectasias en una sola zona', back: 'BRONCOSCOPIA: descartar cuerpo extra&#241;o, tumor o estenosis.' },
  { front: 'La base del tratamiento cronico', back: 'FISIOTERAPIA RESPIRATORIA diaria: lo que mas rinde y lo que menos se prescribe.' },
  { front: 'Cuando se a&#241;ade macrolido a largo plazo', back: 'Con 3 o mas exacerbaciones al a&#241;o. Reduce las exacerbaciones a la mitad.' },
  { front: 'Antes de un macrolido a largo plazo', back: 'DESCARTAR micobacterias no tuberculosas, y comprobar QT y audicion.' },
  { front: 'Por que descartar micobacterias antes', back: 'Un macrolido en monoterapia crea resistencia y arruina el unico tratamiento eficaz.' },
  { front: 'Corticoides inhalados en bronquiectasias', back: 'NO de rutina: solo si coexiste asma o EPOC. Aumentan neumonias y micobacterias.' },
  { front: 'DNasa recombinante', back: 'CONTRAINDICADA fuera de la fibrosis quistica: empeoro funcion y exacerbaciones.' },
  { front: 'Coadyuvantes del aclaramiento que si valen', back: 'Suero salino hipertonico y manitol, con broncodilatador y primera dosis supervisada.' },
  { front: 'Cuando antibiotico inhalado a largo plazo', back: 'Pseudomonas cronica con exacerbaciones frecuentes.' },
  { front: 'Definicion de exacerbacion', back: '3 o mas de 6 sintomas durante 48 horas o mas, con cambio de tratamiento.' },
  { front: 'Los 6 sintomas de la exacerbacion', back: 'Tos, volumen o consistencia del esputo, purulencia, disnea, fatiga y hemoptisis.' },
  { front: 'Lo primero en una exacerbacion', back: 'CULTIVO DE ESPUTO antes del antibiotico. Es el paso que mas se salta.' },
  { front: 'Duracion del antibiotico', back: '14 DIAS, no 5 ni 7: la biopelicula no se resuelve con pautas cortas.' },
  { front: 'A que se dirige el antibiotico empirico', back: 'Al ULTIMO AISLAMIENTO del propio paciente.' },
  { front: 'Fisioterapia durante la exacerbacion', back: 'Se INTENSIFICA, no se suspende: es cuando mas secreciones hay que mover.' },
  { front: 'Primer aislamiento de Pseudomonas', back: 'Intentar ERRADICAR: la ventana no se repite una vez formada la biopelicula.' },
  { front: 'Colonizacion cronica por Pseudomonas', back: '2 o mas cultivos separados 3 meses o mas en 12 meses.' },
  { front: 'Que supone Pseudomonas cronica', back: 'Peor pronostico, mas exacerbaciones y 3 puntos en el indice de gravedad.' },
  { front: 'Indice de gravedad: los dos pesos mayores', back: 'Ingreso en 2 a&#241;os (5 puntos) y Pseudomonas (3 puntos).' },
  { front: 'Categorias del indice de gravedad', back: '0 a 4 leve; 5 a 8 moderada; 9 o mas grave.' },
  { front: 'Sindrome de Kartagener', back: 'Situs inversus, sinusitis y bronquiectasias: es una discinesia ciliar primaria.' },
  { front: 'Cribado de discinesia ciliar primaria', back: 'OXIDO NITRICO NASAL, muy bajo. Confirmar en centro de referencia.' },
  { front: 'Pistas de fibrosis quistica en el adulto', back: 'Lobulos superiores, infertilidad masculina, malabsorcion y pancreatitis.' },
  { front: 'Criterios de micobacteriosis pulmonar', back: 'Clinica + radiologia + 2 cultivos de esputo (o 1 de lavado o biopsia).' }
];

export default { quiz, flashcards };
