// topics/cefaleas/study.js: Autoevaluación de Cefaleas.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices al final de este comentario
// antes de dar el archivo por terminado).
//
// Índices `correct` de las 34 preguntas sueltas, en orden: 2,0,1,3,1,2,0,3,1,0,2,3,1,0,2,3,1,2,0,
// 3,0,2,1,3,0,1,2,0,3,1,2,0,1,3. Recuento: 0×9, 1×9, 2×8, 3×8. Sin racha larga ni ciclo fijo
// (verificado: value[i] no coincide con value[i+4] de forma sostenida a lo largo de la lista).
// Índices `correct` de los pasos de las 6 preguntas en cascada (3 pasos c/u), en orden: 1,3,0 /
// 2,0,3 / 0,1,2 / 3,2,1 / 1,0,3 / 2,3,0. Recuento: 0×5, 1×4, 2×4, 3×5.

export const quiz = [
  { q: '¿Qué proporción aproximada de las consultas por cefalea corresponde a cefaleas primarias?', options: ['~50%', '~70%', 'Más del 90%', '~25%'], correct: 2, explanation: 'Las cefaleas primarias, en las que la cefalea es en sí misma la enfermedad, representan más del 90% de las consultas por este motivo; las secundarias, aunque menos frecuentes, incluyen las causas de mayor morbimortalidad potencial.', dificultad: 'facil' },
  { q: '¿Qué representa la mnemotecnia SNNOOP10?', options: ['Una lista de señales de alarma que orientan hacia una cefalea secundaria', 'Los criterios diagnósticos oficiales de la migraña', 'Una escala de gravedad exclusiva de la cefalea en racimos', 'Un esquema de tratamiento escalonado para la cefalea tensional'], correct: 0, explanation: 'SNNOOP10 agrupa las señales de alarma (1 S, 2 N, 2 O, 10 P) cuya presencia obliga a descartar una causa secundaria antes de clasificar el fenotipo primario.', dificultad: 'facil' },
  { q: '¿Cuál es la duración de los episodios de migraña sin tratar, según los criterios ICHD-3?', options: ['30 minutos a 7 días', '4 a 72 horas', '15 a 180 minutos', 'Menos de 1 minuto'], correct: 1, explanation: 'Los criterios ICHD-3 exigen una duración de 4 a 72 horas sin tratamiento para cada episodio de migraña.', dificultad: 'facil' },
  { q: '¿Qué característica NO es típica de la migraña?', options: ['Dolor unilateral y pulsátil', 'Náusea o vómito asociados', 'Fotofobia y fonofobia simultáneas', 'Dolor bilateral que mejora con la actividad física'], correct: 3, explanation: 'El dolor bilateral que mejora con la actividad física es más propio de la cefalea tensional; la migraña típicamente empeora con la actividad física de rutina.', dificultad: 'facil' },
  { q: '¿Qué es en realidad el aura de la migraña?', options: ['Un pródromo de horas de duración sin correlato eléctrico', 'Un síntoma neurológico focal totalmente reversible atribuido a depresión cortical propagada', 'Un signo exclusivo de la cefalea en racimos', 'Un fenómeno psiquiátrico sin base fisiopatológica conocida'], correct: 1, explanation: 'El aura es un síntoma neurológico focal totalmente reversible, típicamente visual, que se desarrolla de forma gradual y se atribuye a la depresión cortical propagada.', dificultad: 'intermedio' },
  { q: '¿Cuál es el tratamiento agudo de primera línea para una crisis de migraña de intensidad leve-moderada?', options: ['Opioides de acción corta', 'Corticoide oral', 'Un AINE o un triptán', 'Anticuerpo monoclonal anti-CGRP'], correct: 2, explanation: 'Un AINE o un triptán, administrado tan pronto como sea posible tras el inicio del dolor, es el tratamiento agudo de primera línea en intensidad leve-moderada.', dificultad: 'facil' },
  { q: '¿Cuándo se considera iniciar un tratamiento preventivo en la migraña?', options: ['Cuando hay 4 o más días de migraña al mes, o discapacidad significativa pese al tratamiento agudo', 'Únicamente si el paciente lo solicita, sin otro criterio', 'Solo después de 10 años de evolución de la enfermedad', 'Nunca, ya que el tratamiento agudo siempre es suficiente'], correct: 0, explanation: 'Se considera el tratamiento preventivo cuando hay 4 o más días de migraña al mes, discapacidad significativa pese al tratamiento agudo, o riesgo de abuso de medicación.', dificultad: 'intermedio' },
  { q: '¿Qué neuropéptido está centralmente involucrado en la fisiopatología de la migraña y es el blanco de varios tratamientos actuales?', options: ['Sustancia P', 'Neuropéptido Y', 'El péptido relacionado con el gen de la calcitonina (CGRP)', 'Óxido nítrico exclusivamente'], correct: 2, explanation: 'El CGRP, liberado por la activación del sistema trigeminovascular, es central en la fisiopatología de la migraña y el blanco de los gepantes y los anticuerpos monoclonales anti-CGRP.', dificultad: 'intermedio' },
  { q: '¿Cómo se define la migraña crónica?', options: ['Cefalea diaria sin ningún periodo libre de dolor', 'Cefalea 15 o más días al mes por más de 3 meses, con características migrañosas en al menos 8 días', 'Cualquier migraña que dure más de 72 horas en un solo episodio', 'Migraña que no responde a un solo triptán'], correct: 1, explanation: 'La migraña crónica se define por 15 o más días de cefalea al mes durante más de 3 meses, con características migrañosas en al menos 8 de esos días.', dificultad: 'facil' },
  { q: '¿Cuál es el umbral de uso de triptanes u opioides que define la cefalea por abuso de medicación?', options: ['10 o más días al mes', '30 o más días al mes', '2 o más días a la semana de forma ocasional', 'Cualquier uso, sin importar la frecuencia'], correct: 0, explanation: 'El umbral es 10 o más días al mes para triptanes, ergóticos u opioides, y 15 o más días al mes para analgésicos simples como AINE o paracetamol.', dificultad: 'intermedio' },
  { q: '¿Cuál es la conducta terapéutica correcta ante una cefalea por abuso de medicación?', options: ['Aumentar la dosis del analgésico de abuso hasta lograr control', 'Mantener el analgésico y agregar solo un preventivo', 'Esperar a que el paciente decida suspender el fármaco por sí solo', 'Suspender el fármaco de abuso e iniciar un tratamiento preventivo de forma simultánea'], correct: 3, explanation: 'La suspensión del fármaco de abuso, con un tratamiento preventivo iniciado de forma simultánea, es la conducta correcta para romper el ciclo de abuso.', dificultad: 'intermedio' },
  { q: '¿Qué características distinguen a la cefalea tensional de la migraña?', options: ['Dolor unilateral y pulsátil, con náusea prominente', 'Duración de 15 a 180 minutos con síntomas autonómicos', 'Dolor bilateral, opresivo, sin náusea significativa y a lo sumo un síntoma de foto/fonofobia', 'Inicio súbito en trueno con déficit neurológico focal'], correct: 2, explanation: 'La cefalea tensional es bilateral, opresiva, de intensidad leve-moderada, sin náusea significativa y con a lo sumo uno de foto o fonofobia, nunca ambos.', dificultad: 'facil' },
  { q: 'Si un paciente con cefalea presenta náusea y tanto fotofobia como fonofobia simultáneamente, ¿qué diagnóstico es más probable frente a la cefalea tensional?', options: ['Migraña', 'Cefalea en racimos', 'Neuralgia del trigémino', 'Cefalea pospunción lumbar'], correct: 0, explanation: 'La presencia simultánea de náusea con fotofobia y fonofobia orienta hacia migraña, ya que la cefalea tensional permite a lo sumo uno de foto/fonofobia sin náusea significativa.', dificultad: 'intermedio' },
  { q: '¿Cuál es el tratamiento preventivo de primera línea en la cefalea tensional crónica?', options: ['Topiramato', 'Amitriptilina', 'Verapamilo a dosis altas', 'Toxina botulínica tipo A'], correct: 1, explanation: 'La amitriptilina es el tratamiento preventivo de primera línea en la cefalea tensional crónica, con la evidencia más consistente entre las opciones disponibles.', dificultad: 'facil' },
  { q: '¿Qué características definen a la cefalea en racimos?', options: ['Dolor bilateral leve que mejora con el reposo', 'Episodios de más de 4 horas sin síntomas autonómicos', 'Dolor occipital progresivo a lo largo del día', 'Dolor unilateral severo con síntoma autonómico ipsilateral e inquietud motora'], correct: 3, explanation: 'La cefalea en racimos se caracteriza por dolor unilateral severo, de 15 a 180 minutos, con al menos un síntoma autonómico ipsilateral o inquietud/agitación durante la crisis.', dificultad: 'facil' },
  { q: '¿Cuál es el tratamiento agudo de primera línea de la cefalea en racimos?', options: ['Un AINE oral', 'Paracetamol IV', 'Oxígeno de alto flujo o sumatriptán subcutáneo', 'Amitriptilina oral'], correct: 2, explanation: 'El oxígeno de alto flujo o el sumatriptán subcutáneo, por su inicio de acción rápido, son el tratamiento agudo de primera línea dada la corta duración del episodio.', dificultad: 'facil' },
  { q: '¿Cuál es el tratamiento preventivo de primera línea de la cefalea en racimos, y qué vigilancia requiere?', options: ['Verapamilo a dosis altas, con monitorización electrocardiográfica por riesgo de bloqueo AV', 'Ácido valproico, sin vigilancia adicional necesaria', 'Litio, sin necesidad de niveles séricos', 'Carbamazepina, vigilando la función hepática exclusivamente'], correct: 0, explanation: 'El verapamilo a dosis altas es la primera línea preventiva, y requiere monitorización electrocardiográfica por el riesgo de bloqueo auriculoventricular.', dificultad: 'intermedio' },
  { q: '¿Qué diferencia la conducta del paciente durante una crisis de cefalea en racimos frente a una crisis de migraña?', options: ['En ambas el paciente permanece completamente inmóvil', 'En la cefalea en racimos hay inquietud y agitación motora, mientras que en la migraña el paciente busca quietud y oscuridad', 'En la migraña el paciente se agita, mientras que en la cefalea en racimos permanece inmóvil', 'No existe ninguna diferencia conductual reconocida entre ambas'], correct: 1, explanation: 'La inquietud y agitación motora durante la crisis es característica de la cefalea en racimos, en contraste con la búsqueda de quietud y oscuridad típica de la migraña.', dificultad: 'intermedio' },
  { q: '¿Qué rasgo distingue a la hemicránea paroxística dentro del espectro de las cefalalgias autonómico-trigeminales?', options: ['Episodios de más de 4 horas de duración', 'Ausencia total de síntomas autonómicos', 'Predominio exclusivo en hombres jóvenes', 'Respuesta absoluta y característica a la indometacina'], correct: 3, explanation: 'La respuesta absoluta a la indometacina es el rasgo distintivo de la hemicránea paroxística, usada incluso como prueba terapéutica diagnóstica.', dificultad: 'dificil' },
  { q: '¿En qué circunstancia debe sospecharse con prioridad una cefalea secundaria en vez de una primaria?', options: ['Cuando el paciente ya tiene un diagnóstico previo de migraña', 'Cuando el dolor es unilateral y pulsátil', 'Cuando está presente cualquier señal de alarma de la mnemotecnia SNNOOP10', 'Cuando el paciente es menor de 30 años'], correct: 2, explanation: 'La presencia de cualquier señal de alarma de SNNOOP10 obliga a descartar una causa secundaria antes de clasificar el fenotipo primario.', dificultad: 'facil' },
  { q: '¿Cómo se define operacionalmente la cefalea en trueno?', options: ['Cefalea que alcanza su intensidad máxima en menos de 1 minuto', 'Cefalea que dura más de 72 horas sin tratamiento', 'Cefalea que se presenta exclusivamente durante el sueño', 'Cefalea que mejora completamente con analgésicos simples'], correct: 0, explanation: 'La cefalea en trueno se define por alcanzar la intensidad máxima en menos de 1 minuto desde su inicio, independientemente de la causa final.', dificultad: 'facil' },
  { q: '¿Cuál es el primer estudio que debe realizarse ante una cefalea en trueno?', options: ['Resonancia magnética programada de forma ambulatoria', 'Tomografía computarizada simple de cráneo, de forma urgente', 'Electroencefalograma', 'Punción lumbar de entrada, sin imagen previa'], correct: 1, explanation: 'La TC simple de cráneo urgente es el primer estudio, para descartar hemorragia antes de continuar el algoritmo diagnóstico.', dificultad: 'facil' },
  { q: 'Si la TC simple es negativa pero la sospecha de hemorragia subaracnoidea persiste, ¿cuál es el siguiente paso?', options: ['Dar de alta con analgesia y control ambulatorio', 'Repetir la TC simple en 7 días', 'Angiografía por sustracción digital de entrada, sin otro estudio previo', 'Punción lumbar (xantocromía) o resonancia magnética con secuencias sensibles a sangre'], correct: 3, explanation: 'Con TC negativa y sospecha persistente, el siguiente paso es la punción lumbar buscando xantocromía o una RM con secuencias sensibles a sangre.', dificultad: 'intermedio' },
  { q: '¿A partir de qué edad debe sospecharse arteritis de células gigantes ante una cefalea de nuevo inicio?', options: ['Mayor a 50 años', 'Mayor a 18 años', 'Mayor a 30 años', 'No tiene relación con la edad'], correct: 0, explanation: 'La arteritis de células gigantes es prácticamente exclusiva de mayores de 50 años, con un pico entre los 70 y 80 años.', dificultad: 'facil' },
  { q: '¿Qué hallazgo clínico tiene mayor especificidad para el diagnóstico de arteritis de células gigantes?', options: ['Cefalea bilateral leve', 'Fiebre de bajo grado aislada', 'Claudicación mandibular', 'Rigidez de nuca'], correct: 2, explanation: 'La claudicación mandibular, dolor al masticar que cede con el reposo, tiene alta especificidad para el diagnóstico de arteritis de células gigantes.', dificultad: 'intermedio' },
  { q: 'Un paciente con sospecha de arteritis de células gigantes presenta amaurosis fugaz. ¿Cuál es la conducta más apropiada?', options: ['Esperar la biopsia de arteria temporal antes de iniciar cualquier tratamiento', 'Iniciar tratamiento de inmediato (metilprednisolona IV en pulsos), sin esperar la confirmación histológica', 'Iniciar únicamente AINE mientras se organiza el estudio', 'Diferir el tratamiento hasta confirmar la VSG elevada'], correct: 1, explanation: 'Ante síntomas visuales, el tratamiento con metilprednisolona IV en pulsos debe iniciarse de inmediato, sin esperar la biopsia, por el riesgo de pérdida visual irreversible.', dificultad: 'intermedio' },
  { q: '¿Cómo debe realizarse la reducción del corticoide en la arteritis de células gigantes ya controlada?', options: ['Suspensión abrupta en cuanto ceden los síntomas', 'Reducción en un plazo de 2 semanas', 'Reducción en un plazo de 1 mes', 'Reducción muy gradual a lo largo de 1-2 años, guiada por la clínica y los reactantes de fase aguda'], correct: 3, explanation: 'La reducción del corticoide debe ser muy gradual, a lo largo de 1-2 años, guiada por la clínica y los reactantes de fase aguda, para minimizar el riesgo de recaída.', dificultad: 'intermedio' },
  { q: '¿Cuál es el patrón característico de la cefalea posterior a punción lumbar?', options: ['Ortostática: empeora en bipedestación y mejora al recostarse', 'Empeora al recostarse y mejora de pie', 'Sin relación alguna con la postura', 'Exclusivamente nocturna'], correct: 0, explanation: 'El patrón ortostático (empeora de pie, mejora al recostarse) es la característica clínica definitoria de la cefalea pospunción lumbar.', dificultad: 'facil' },
  { q: '¿Cuál es el tratamiento definitivo más eficaz para la cefalea pospunción lumbar refractaria al manejo conservador?', options: ['Reposo estricto en cama prolongado', 'Analgésicos opioides en dosis altas', 'Parche hemático epidural autólogo', 'Punción lumbar repetida para "aliviar la presión"'], correct: 2, explanation: 'El parche hemático epidural autólogo es el tratamiento definitivo más eficaz, con una tasa de éxito superior al 70-90% cuando está indicado.', dificultad: 'facil' },
  { q: '¿Qué hallazgo debe hacer sospechar trombosis de senos venosos cerebrales en vez de una cefalea pospunción lumbar típica?', options: ['Mejoría completa al recostarse', 'Ausencia de mejoría en decúbito, a diferencia del patrón ortostático típico', 'Aparición dentro de las primeras 24 horas del procedimiento', 'Localización frontal-occipital del dolor'], correct: 1, explanation: 'La trombosis de senos venosos, que puede ser precipitada por la propia punción lumbar, característicamente NO mejora en decúbito, a diferencia del patrón ortostático típico de la cefalea pospunción.', dificultad: 'dificil' },
  { q: '¿Qué características definen a la neuralgia del trigémino?', options: ['Dolor continuo, sordo, sin zona gatillo identificable', 'Dolor bilateral simétrico de inicio gradual', 'Dolor facial que dura horas y se acompaña de síntomas autonómicos prominentes', 'Dolor unilateral, breve, en descarga eléctrica, desencadenado por una zona gatillo'], correct: 3, explanation: 'La neuralgia del trigémino se caracteriza por episodios de dolor unilateral, breve, similar a una descarga eléctrica, desencadenados por estímulos táctiles en una zona gatillo.', dificultad: 'facil' },
  { q: '¿Cuál es el tratamiento farmacológico de primera línea de la neuralgia del trigémino?', options: ['Carbamazepina u oxcarbazepina', 'Ácido acetilsalicílico', 'Sumatriptán', 'Prednisona en dosis altas'], correct: 0, explanation: 'La carbamazepina o la oxcarbazepina son el tratamiento farmacológico de primera línea, con alta tasa de respuesta inicial.', dificultad: 'facil' },
  { q: '¿En qué contexto clínico de neuralgia del trigémino debe sospecharse esclerosis múltiple como causa secundaria?', options: ['Paciente mayor de 70 años con dolor unilateral típico', 'Paciente con buena respuesta a carbamazepina en dosis bajas', 'Paciente joven, especialmente con presentación bilateral', 'Paciente con antecedente de hipertensión arterial únicamente'], correct: 2, explanation: 'La neuralgia del trigémino en un paciente joven, especialmente si es bilateral, debe hacer sospechar esclerosis múltiple como causa secundaria.', dificultad: 'intermedio' },
  { q: '¿Cuál es el tratamiento con mayor probabilidad de remisión prolongada en la neuralgia del trigémino farmacorresistente con compresión neurovascular confirmada?', options: ['Aumentar la dosis de carbamazepina de forma indefinida', 'Agregar un segundo fármaco sin reevaluar la causa', 'Radioterapia externa convencional', 'Descompresión microvascular'], correct: 3, explanation: 'La descompresión microvascular ofrece las tasas más altas de remisión prolongada en los candidatos con compresión neurovascular confirmada.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 32 años con antecedente de migraña desde la adolescencia presenta un episodio de cefalea unilateral pulsátil con náusea y fotofobia, similar a sus crisis habituales, de 8 horas de evolución, sin fiebre, sin déficit neurológico, sin cambio en el patrón habitual.',
    steps: [
      { q: '¿Cuál es la conducta más apropiada respecto al estudio de imagen?', options: ['Solicitar RM cerebral de rutina por tratarse de cefalea recurrente', 'No está indicada de rutina, dado que el patrón es típico, estable y sin señales de alarma', 'Solicitar TC simple de cráneo de forma urgente', 'Solicitar angio-TC de cabeza y cuello de rutina'], correct: 1 },
      { q: '¿Cuál es el tratamiento agudo más apropiado dada la intensidad moderada del episodio?', options: ['Opioide de acción corta', 'Corticoide oral', 'Anticuerpo monoclonal anti-CGRP', 'Un AINE o un triptán'], correct: 3 },
      { q: 'La paciente refiere que en el último año ha tenido 6 días de migraña al mes, con impacto significativo en su trabajo. ¿Cuál es la conducta más apropiada?', options: ['Discutir el inicio de un tratamiento preventivo', 'Indicar que no existe ninguna opción más allá del tratamiento agudo', 'Aumentar la dosis del triptán de forma preventiva diaria', 'Derivar de inmediato a cirugía de descompresión'], correct: 0 }
    ],
    explanation: 'Con un patrón migrañoso típico, estable y sin señales de alarma, la imagen no está indicada de rutina. El tratamiento agudo de un episodio moderado es un AINE o un triptán. La frecuencia de 6 días al mes con impacto laboral significativo cumple criterios para discutir el inicio de un tratamiento preventivo, en vez de escalar el uso del triptán agudo, lo que aumentaría el riesgo de cefalea por abuso de medicación.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Hombre de 45 años presenta cefalea occipital súbita que alcanzó su máxima intensidad en 30 segundos, mientras realizaba ejercicio físico intenso. No hay rigidez de nuca ni déficit focal. La TC simple de cráneo es normal.',
    steps: [
      { q: 'Dado que la TC es normal, ¿cuál es la conducta más apropiada?', options: ['Dar de alta de inmediato sin más estudio, dado que la TC descarta cualquier causa grave', 'Indicar que se trata definitivamente de una cefalea primaria en trueno', 'Ampliar el estudio con punción lumbar y/o angio-TC/angio-RM de cabeza y cuello, dado que una TC normal no descarta todas las causas graves', 'Repetir la TC en 6 meses como único seguimiento'], correct: 2 },
      { q: '¿Qué causa vascular debe considerarse especialmente dado que el episodio ocurrió durante el ejercicio físico intenso?', options: ['Síndrome de vasoconstricción cerebral reversible', 'Migraña sin aura típica', 'Cefalea tensional crónica', 'Neuralgia del trigémino'], correct: 0 },
      { q: 'Si se confirma un síndrome de vasoconstricción cerebral reversible, ¿qué debe evitarse en el manejo?', options: ['El reposo relativo', 'La hidratación adecuada', 'El control de la presión arterial', 'Los fármacos vasoconstrictores, incluidos los triptanes'], correct: 3 }
    ],
    explanation: 'Una TC normal no descarta todas las causas graves de cefalea en trueno; el estudio debe ampliarse con punción lumbar y/o estudio vascular. El desencadenante por esfuerzo físico intenso es característico del síndrome de vasoconstricción cerebral reversible. En su manejo, deben evitarse los fármacos vasoconstrictores, incluidos los triptanes, que pueden agravar el vasoespasmo segmentario.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 72 años presenta cefalea temporal de 2 semanas de evolución, con dolor al peinarse y dolor al masticar que cede con el reposo. No refiere síntomas visuales.',
    steps: [
      { q: '¿Cuál es el estudio de laboratorio más urgente a solicitar?', options: ['VSG y PCR', 'Perfil lipídico', 'Hemoglobina glucosilada', 'Anticuerpos antinucleares'], correct: 0 },
      { q: '¿Cuál es la conducta terapéutica más apropiada en este momento, dado que no hay síntomas visuales?', options: ['Esperar el resultado de la biopsia de arteria temporal antes de iniciar cualquier tratamiento', 'Iniciar prednisona oral en dosis altas sin esperar la biopsia', 'Iniciar únicamente AINE hasta confirmar el diagnóstico', 'No se requiere tratamiento hasta confirmar la afectación de grandes vasos'], correct: 1 },
      { q: '¿Cuál es la conducta apropiada respecto a la biopsia de arteria temporal?', options: ['Omitirla por completo si la VSG está elevada', 'Realizarla únicamente si el corticoide no controla los síntomas', 'Realizarla idealmente dentro de las primeras 1-2 semanas de iniciado el corticoide, sin que esto retrase el tratamiento', 'Realizarla solo si aparecen síntomas visuales posteriormente'], correct: 2 }
    ],
    explanation: 'La cefalea temporal de nuevo inicio con claudicación mandibular en una mujer mayor de 70 años es altamente sugestiva de arteritis de células gigantes; la VSG y la PCR son el estudio urgente inicial. Sin síntomas visuales, se inicia prednisona oral en dosis altas sin esperar la biopsia, que se realiza idealmente dentro de las primeras 1-2 semanas del corticoide, sin retrasar el tratamiento por confirmarla primero.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 38 años con migraña desde los 20 años, reporta cefalea 20 días al mes en el último trimestre, con características migrañosas en la mayoría de esos días. Refiere tomar un triptán prácticamente a diario para poder trabajar.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable dado este patrón?', options: ['Migraña episódica sin cambios', 'Cefalea tensional crónica aislada', 'Cefalea en racimos crónica', 'Migraña crónica con cefalea por abuso de medicación asociada'], correct: 3 },
      { q: '¿Cuál es el primer paso terapéutico más importante?', options: ['Aumentar la dosis del triptán para lograr mejor control', 'Agregar un segundo triptán de otra familia', 'Suspender el triptán de uso diario, con un tratamiento preventivo simultáneo', 'Indicar reposo absoluto indefinido'], correct: 2 },
      { q: '¿Qué debe explicársele a la paciente que puede ocurrir tras suspender el fármaco de abuso?', options: ['Una mejoría inmediata sin ningún periodo de transición', 'Un empeoramiento transitorio de la cefalea (cefalea de rebote) antes de la mejoría', 'Que el dolor desaparecerá permanentemente en 24 horas', 'Que no debe esperarse ningún cambio en el patrón de cefalea'], correct: 1 }
    ],
    explanation: 'Cefalea 20 días al mes con características migrañosas en la mayoría de ellos, más uso diario de triptán, cumple criterios de migraña crónica con cefalea por abuso de medicación asociada. El manejo requiere suspender el fármaco de abuso con un preventivo simultáneo, anticipando y explicando el empeoramiento transitorio esperado (cefalea de rebote) antes de la mejoría.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Hombre de 35 años, fumador, presenta episodios de dolor periorbitario derecho muy intenso, de 45 minutos de duración, varias veces al día durante las últimas 2 semanas, acompañados de lagrimeo y congestión nasal del mismo lado. Refiere no poder quedarse quieto durante los episodios.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable?', options: ['Migraña con aura', 'Cefalea en racimos', 'Cefalea tensional crónica', 'Neuralgia del trigémino'], correct: 1 },
      { q: '¿Qué estudio de imagen debe solicitarse en este primer episodio?', options: ['RM cerebral con protocolo hipofisario/silla turca', 'Radiografía simple de senos paranasales', 'Ecografía Doppler carotídea', 'Ninguno, el diagnóstico es exclusivamente clínico'], correct: 0 },
      { q: '¿Cuál es el tratamiento agudo más apropiado para sus episodios?', options: ['AINE oral de acción prolongada', 'Paracetamol IV', 'Amitriptilina de rescate', 'Oxígeno de alto flujo o sumatriptán subcutáneo'], correct: 3 }
    ],
    explanation: 'Dolor unilateral periorbitario severo, breve, con síntoma autonómico ipsilateral e inquietud motora, en un hombre fumador, es el cuadro característico de la cefalea en racimos. Todo primer episodio requiere RM con protocolo hipofisario para descartar causas secundarias. El tratamiento agudo de elección es oxígeno de alto flujo o sumatriptán subcutáneo, por su inicio de acción rápido.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 29 años presenta episodios de dolor facial derecho, breve, en descarga eléctrica, desencadenados al cepillarse los dientes. Los episodios comenzaron a presentarse también del lado izquierdo en el último mes.',
    steps: [
      { q: 'Dado el contexto (paciente joven, presentación bilateral), ¿qué causa secundaria debe descartarse con prioridad?', options: ['Arteritis de células gigantes', 'Cefalea en racimos crónica', 'Esclerosis múltiple', 'Migraña con aura prolongada'], correct: 2 },
      { q: '¿Cuál es el estudio de imagen más apropiado?', options: ['TC simple de cráneo, como único estudio necesario', 'Radiografía panorámica dental', 'Ecografía Doppler transcraneal', 'RM cerebral con protocolo de fosa posterior'], correct: 3 },
      { q: 'Mientras se completa el estudio, ¿cuál es el tratamiento farmacológico inicial más apropiado?', options: ['Carbamazepina u oxcarbazepina', 'Sumatriptán subcutáneo', 'Metilprednisolona IV en pulsos de inmediato', 'Sin tratamiento hasta tener el resultado de la RM'], correct: 0 }
    ],
    explanation: 'La neuralgia del trigémino bilateral en una paciente joven es atípica para la forma clásica y debe hacer sospechar esclerosis múltiple. La RM con protocolo de fosa posterior es el estudio de elección, tanto para buscar la compresión neurovascular como para excluir la causa secundaria. Mientras se completa el estudio, la carbamazepina u oxcarbazepina siguen siendo el tratamiento farmacológico inicial apropiado.'
  }
];

export const flashcards = [
  { front: '¿Qué proporción de las cefaleas son primarias vs. secundarias?', back: 'Más del 90% son primarias; las secundarias son menos frecuentes pero incluyen las causas de mayor morbimortalidad.' },
  { front: 'SNNOOP10', back: 'Mnemotecnia de señales de alarma (1 S, 2 N, 2 O, 10 P) que orientan hacia una cefalea secundaria.' },
  { front: 'Duración de la migraña sin tratar', back: '4 a 72 horas, según los criterios ICHD-3.' },
  { front: 'Diferencia clave entre migraña y cefalea tensional', back: 'La migraña permite náusea Y ambos foto/fonofobia; la tensional, a lo sumo uno de foto/fonofobia, sin náusea significativa.' },
  { front: 'Qué es el aura en realidad', back: 'Un síntoma neurológico focal totalmente reversible, atribuido a la depresión cortical propagada.' },
  { front: 'Tratamiento agudo de primera línea de la migraña', back: 'Un AINE o un triptán, tan pronto como sea posible tras el inicio del dolor.' },
  { front: 'Cuándo iniciar preventivo en migraña', back: '4 o más días de migraña al mes, o discapacidad significativa pese al tratamiento agudo.' },
  { front: 'CGRP en la migraña', back: 'Neuropéptido central en la fisiopatología; blanco de gepantes y anticuerpos monoclonales.' },
  { front: 'Definición de migraña crónica', back: '15 o más días de cefalea al mes por más de 3 meses, con características migrañosas en al menos 8 días.' },
  { front: 'Umbral de abuso de triptanes/opioides vs. AINE/paracetamol', back: '10 o más días/mes (triptanes, ergóticos, opioides) o 15 o más días/mes (analgésicos simples).' },
  { front: 'Manejo de la cefalea por abuso de medicación', back: 'Suspender el fármaco de abuso e iniciar un preventivo de forma simultánea, anticipando la cefalea de rebote transitoria.' },
  { front: 'Preventivo de primera línea en cefalea tensional crónica', back: 'Amitriptilina.' },
  { front: 'Cefalea en racimos: características', back: 'Dolor unilateral severo, 15-180 min, con síntoma autonómico ipsilateral o inquietud/agitación.' },
  { front: 'Tratamiento agudo de la cefalea en racimos', back: 'Oxígeno de alto flujo o sumatriptán subcutáneo.' },
  { front: 'Preventivo de la cefalea en racimos', back: 'Verapamilo a dosis altas, con monitorización electrocardiográfica por riesgo de bloqueo AV.' },
  { front: 'Conducta durante la crisis: racimos vs. migraña', back: 'Inquietud/agitación en la cefalea en racimos; búsqueda de quietud y oscuridad en la migraña.' },
  { front: 'Hemicránea paroxística: rasgo distintivo', back: 'Respuesta absoluta y característica a la indometacina.' },
  { front: 'Cefalea en trueno: definición', back: 'Intensidad máxima alcanzada en menos de 1 minuto desde el inicio.' },
  { front: 'Primer estudio ante cefalea en trueno', back: 'TC simple de cráneo, de forma urgente.' },
  { front: 'TC negativa + sospecha de HSA persistente', back: 'Punción lumbar (xantocromía) o RM con secuencias sensibles a sangre.' },
  { front: 'Arteritis de células gigantes: edad típica', back: 'Prácticamente exclusiva de mayores de 50 años; pico entre 70-80 años.' },
  { front: 'Hallazgo más específico de arteritis de células gigantes', back: 'Claudicación mandibular.' },
  { front: 'Arteritis de células gigantes con síntomas visuales: conducta', back: 'Tratamiento inmediato (metilprednisolona IV en pulsos), sin esperar la biopsia.' },
  { front: 'Reducción del corticoide en arteritis de células gigantes', back: 'Muy gradual, a lo largo de 1-2 años, guiada por la clínica y los reactantes de fase aguda.' },
  { front: 'Cefalea pospunción lumbar: patrón', back: 'Ortostático: empeora de pie, mejora al recostarse.' },
  { front: 'Tratamiento definitivo de la cefalea pospunción refractaria', back: 'Parche hemático epidural autólogo.' },
  { front: 'Diferenciador de trombosis venosa vs. cefalea pospunción típica', back: 'La trombosis venosa NO mejora en decúbito, a diferencia del patrón ortostático típico.' },
  { front: 'Neuralgia del trigémino: características', back: 'Dolor unilateral, breve, en descarga eléctrica, desencadenado por una zona gatillo.' },
  { front: 'Tratamiento de primera línea de la neuralgia del trigémino', back: 'Carbamazepina u oxcarbazepina.' },
  { front: 'Sospecha de esclerosis múltiple en neuralgia del trigémino', back: 'Paciente joven, especialmente con presentación bilateral.' },
  { front: 'Mejor tratamiento en neuralgia del trigémino farmacorresistente con compresión confirmada', back: 'Descompresión microvascular.' }
];

export const caseSteps = [];
export const caseSummary = undefined;

export default { quiz, flashcards, caseSteps, caseSummary };
