// topics/guillain-barre-miastenia/study.js: Autoevaluacion de Guillain-Barre y Miastenia Gravis.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// 48 subpreguntas (30 sueltas + 6 cascadas de 3 pasos) y 32 tarjetas.
// Sin em dash (ver [[feedback-no-em-dash]]). Texto sin acentos.

export const quiz = [
  { q: 'Como estan los reflejos en la miastenia gravis?', options: ['Abolidos desde el inicio', 'Exaltados de forma difusa', 'Normales', 'Abolidos solo en las piernas'], correct: 2, explanation: 'La lesion esta en la union neuromuscular y no en el nervio, de modo que el arco reflejo funciona. Reflejos normales y ausencia de alteracion sensitiva son lo que separa la miastenia del sindrome de Guillain-Barre.', dificultad: 'intermedio' },
  { q: 'En cuanto tiempo alcanza su maximo el sindrome de Guillain-Barre?', options: ['En menos de 4 semanas', 'En menos de 24 horas', 'Entre 2 y 6 meses', 'En mas de 8 semanas'], correct: 0, explanation: 'Habitualmente el nadir se alcanza en unas 2 semanas. Si la progresion se prolonga mas alla de 8 semanas, el cuadro deja de comportarse como una forma aguda y pasa a manejarse como una polineuropatia inflamatoria cronica.', dificultad: 'facil' },
  { q: 'Que significa un liquido cefalorraquideo normal en la primera semana?', options: ['Que descarta el diagnostico', 'Que hay que buscar otra causa', 'Que la forma es axonal', 'Que NO descarta el diagnostico'], correct: 3, explanation: 'La disociacion albuminocitologica tarda dias en aparecer y falta en una proporcion importante de los pacientes al principio. El diagnostico es clinico, y un liquido normal no autoriza a suspender la vigilancia ni a dar el alta.', dificultad: 'intermedio' },
  { q: 'Que obliga a replantear el diagnostico de Guillain-Barre?', options: ['Proteinas de 120 mg/dL', 'Mas de 50 celulas en el liquido', 'Arreflexia generalizada', 'Antecedente de diarrea'], correct: 1, explanation: 'Una pleocitosis marcada no encaja con el sindrome tipico y obliga a pensar en VIH, enfermedad de Lyme, linfoma o sarcoidosis. Las proteinas elevadas y la arreflexia, en cambio, son lo esperable.', dificultad: 'dificil' },
  { q: 'Que papel tienen los corticoides en el sindrome de Guillain-Barre?', options: ['NO son eficaces', 'Son el tratamiento de eleccion', 'Se asocian a inmunoglobulinas', 'Se usan solo en la forma axonal'], correct: 0, explanation: 'Es uno de los contrastes que mas se preguntan: los corticoides si son eficaces en la polineuropatia inflamatoria CRONICA, pero no han demostrado beneficio en la forma aguda y no forman parte de su tratamiento.', dificultad: 'intermedio' },
  { q: 'Que relacion tienen las inmunoglobulinas y la plasmaferesis en el Guillain-Barre?', options: ['La plasmaferesis es superior', 'Se administran de forma conjunta', 'Son equivalentes y no se combinan', 'Las inmunoglobulinas son superiores'], correct: 2, explanation: 'Tienen eficacia comparable y se elige por disponibilidad, acceso vascular y comorbilidad. Combinarlas no aporta beneficio adicional y a&#241;ade riesgos, de modo que se usa una u otra.', dificultad: 'intermedio' },
  { q: 'Cuales son las dos causas de muerte del sindrome de Guillain-Barre?', options: ['Sepsis y tromboembolia', 'Fallo respiratorio y disautonomia', 'Ictus y arritmia auricular', 'Hemorragia digestiva y delirium'], correct: 1, explanation: 'La disautonomia se pasa por alto con facilidad y produce arritmias, bradicardia extrema con maniobras vagales, labilidad tensional, ileo y retencion. Por eso la monitorizacion cardiaca acompa&#241;a siempre a la vigilancia respiratoria.', dificultad: 'intermedio' },
  { q: 'Que sintoma del Guillain-Barre precede a menudo a la debilidad y despista?', options: ['La diplopia binocular', 'La retencion urinaria', 'La disfagia progresiva', 'El dolor de espalda'], correct: 3, explanation: 'Se debe a la afectacion radicular y es muy frecuente. Hace que el paciente consulte por lumbalgia y se vaya a casa con analgesia, lo que retrasa el diagnostico hasta que la debilidad es evidente.', dificultad: 'dificil' },
  { q: 'Que define a la miastenia gravis?', options: ['La debilidad simetrica ascendente', 'La debilidad que mejora con el uso', 'La debilidad que empeora con el uso', 'La debilidad con arreflexia precoz'], correct: 2, explanation: 'Es la fatigabilidad: empeora con el uso repetido y a lo largo del dia, y mejora con el reposo. La debilidad que MEJORA con la contraccion sostenida es la del sindrome de Lambert-Eaton, que es justo lo contrario.', dificultad: 'facil' },
  { q: 'Con que sintomas debuta la mayoria de las miastenias?', options: ['Ptosis y diplopia', 'Disnea de esfuerzo', 'Debilidad de las piernas', 'Disfagia para solidos'], correct: 0, explanation: 'La musculatura extraocular es especialmente vulnerable por su alta frecuencia de disparo y su menor margen de seguridad sinaptico. Una proporcion importante de las formas oculares generaliza en los dos primeros a&#241;os.', dificultad: 'facil' },
  { q: 'Que prueba de imagen hay que pedir a TODO paciente con miastenia?', options: ['Resonancia craneal con contraste', 'Ecografia de troncos supraaorticos', 'Radiografia de columna cervical', 'Tomografia de torax'], correct: 3, explanation: 'Busca un TIMOMA, presente en una minoria pero con implicaciones quirurgicas inmediatas. Es una de las peticiones que mas se olvidan en la practica y su omision puede dejar sin tratar un tumor.', dificultad: 'intermedio' },
  { q: 'Cuando esta siempre indicada la timectomia?', options: ['En la forma puramente ocular', 'Si hay timoma', 'Si los anticuerpos son anti-MuSK', 'Si el paciente supera los 70 a&#241;os'], correct: 1, explanation: 'La indicacion la marca el propio tumor, con independencia del control de la miastenia. Ademas, un ensayo aleatorizado demostro beneficio en la miastenia generalizada con anticuerpos frente al receptor de acetilcolina y de inicio precoz aunque no haya timoma.', dificultad: 'intermedio' },
  { q: 'Que grupo de antibioticos puede desencadenar una crisis miastenica?', options: ['Las cefalosporinas de tercera', 'Los glucopeptidos', 'Las fluoroquinolonas', 'Las penicilinas antipseudomonicas'], correct: 2, explanation: 'Junto con macrolidos y aminoglucosidos. Son las que mas se prescriben sin pensar en esto, y una proporcion relevante de las crisis es iatrogenica y por tanto evitable comprobando la lista antes de prescribir.', dificultad: 'intermedio' },
  { q: 'Como se inicia el corticoide en la miastenia gravis?', options: ['A dosis alta desde el primer dia', 'Solo por via intravenosa', 'En pulsos mensuales', 'A dosis baja y subiendo despacio'], correct: 3, explanation: 'Iniciarlo a dosis alta puede producir un empeoramiento transitorio grave en las primeras semanas, capaz de precipitar una crisis. Por eso se empieza bajo y se sube de forma progresiva, o se hace con el paciente vigilado.', dificultad: 'dificil' },
  { q: 'Que caracteriza al subtipo con anticuerpos frente a MuSK?', options: ['Predominio bulbar y facial', 'Excelente respuesta a piridostigmina', 'Indicacion clara de timectomia', 'Curso limitado a la forma ocular'], correct: 0, explanation: 'A&#241;ade atrofia lingual, peor respuesta a los anticolinesterasicos y buena respuesta al rituximab, que en este grupo se considera de eleccion en la enfermedad refractaria. La timectomia no esta indicada en este subtipo.', dificultad: 'dificil' },
  { q: 'Para que sirve el titulo de anticuerpos en el seguimiento de la miastenia?', options: ['Para ajustar la dosis de corticoide', 'Para nada: no se correlaciona', 'Para decidir la timectomia', 'Para predecir la crisis'], correct: 1, explanation: 'El titulo no se correlaciona con la gravedad ni con la respuesta. El seguimiento se hace con escalas funcionales como la MG-ADL y con la exploracion, no repitiendo la determinacion de anticuerpos.', dificultad: 'intermedio' },
  { q: 'Por que no se espera a la gasometria para intubar?', options: ['Porque tarda demasiado en el laboratorio', 'Porque la muestra suele ser venosa', 'Porque el pH se mantiene normal', 'Porque la hipercapnia es tardia'], correct: 3, explanation: 'El paciente compensa aumentando la frecuencia respiratoria hasta que se agota, y para entonces la claudicacion es inminente. La decision se toma con la capacidad vital y con los signos clinicos, no con los gases.', dificultad: 'intermedio' },
  { q: 'Que umbral de capacidad vital indica riesgo de claudicacion respiratoria?', options: ['Menos de 40 mL/kg', 'Menos de 30 mL/kg', 'Menos de 20 mL/kg', 'Menos de 10 mL/kg'], correct: 2, explanation: 'Es el primer numero de la regla de 20, 30 y 40, junto con una presion inspiratoria maxima por debajo de 30 cmH2O en valor absoluto y una espiratoria por debajo de 40. La tendencia importa mas que el valor aislado.', dificultad: 'intermedio' },
  { q: 'Que adelanta la decision de intubar aunque los numeros no la cumplan?', options: ['La debilidad bulbar', 'La ptosis bilateral', 'La debilidad proximal', 'La arreflexia aquilea'], correct: 0, explanation: 'Si el paciente no maneja sus propias secreciones, el riesgo no es la fatiga respiratoria sino la ASPIRACION, y ese riesgo no lo mide la capacidad vital. La ventilacion no invasiva no protege la via aerea en este escenario.', dificultad: 'dificil' },
  { q: 'Que maniobra de cabecera estima la reserva respiratoria sin aparatos?', options: ['Medir el perimetro toracico', 'Contar de corrido hasta 20', 'Palpar el pulso paradojico', 'Auscultar en decubito lateral'], correct: 1, explanation: 'Si el paciente no puede completar la cuenta en una sola espiracion, la capacidad vital esta comprometida. Junto con el habla entrecortada y el uso de musculatura accesoria, anuncia la claudicacion antes que ninguna prueba.', dificultad: 'intermedio' },
  { q: 'Cual es el desencadenante mas frecuente de una crisis miastenica?', options: ['El calor ambiental', 'El ejercicio intenso', 'La infeccion intercurrente', 'El ayuno prolongado'], correct: 2, explanation: 'Sobre todo respiratoria. Le siguen la cirugia, el embarazo y el parto, un farmaco de la lista de contraindicados y la retirada rapida de la inmunosupresion. Identificar el desencadenante cambia el tratamiento y previene la siguiente crisis.', dificultad: 'intermedio' },
  { q: 'Que se hace con la piridostigmina durante la ventilacion mecanica?', options: ['Se dobla la dosis habitual', 'Se pasa a via intravenosa', 'Se mantiene sin cambios', 'Se suele suspender'], correct: 3, explanation: 'Con el paciente ventilado ya no aporta beneficio y aumenta las secreciones bronquiales, que es justo lo que complica el manejo. Se reintroduce de forma progresiva durante el destete.', dificultad: 'dificil' },
  { q: 'Que dato pupilar apunta a una crisis colinergica?', options: ['La midriasis arreactiva', 'La miosis', 'La anisocoria', 'La pupila de Adie'], correct: 1, explanation: 'Acompa&#241;a al resto de los sintomas muscarinicos: diarrea, colicos, sudoracion, lagrimeo, sialorrea y broncorrea, con bradicardia y fasciculaciones. La midriasis arreactiva, en cambio, es el sello del botulismo.', dificultad: 'intermedio' },
  { q: 'Que se hace ante la duda entre crisis miastenica y colinergica?', options: ['Suspender la piridostigmina y observar', 'Doblar la dosis y reevaluar', 'Dar atropina de forma empirica', 'Esperar 24 horas sin cambios'], correct: 0, explanation: 'Es la conducta segura en ambos escenarios, y ademas es lo que se hace durante la ventilacion mecanica. Si el paciente mejora era colinergica y si empeora era miastenica, pero el soporte respiratorio es la prioridad en los dos casos.', dificultad: 'intermedio' },
  { q: 'Que ocurre con la fuerza en el sindrome de Lambert-Eaton?', options: ['Empeora tras la contraccion', 'Se mantiene invariable', 'Fluctua a lo largo del dia', 'MEJORA tras la contraccion'], correct: 3, explanation: 'Es el fenomeno de facilitacion: la contraccion sostenida acumula calcio en la terminal presinaptica y aumenta la liberacion de acetilcolina. Es lo opuesto a la miastenia y se ve tambien en el estudio neurofisiologico como incremento.', dificultad: 'intermedio' },
  { q: 'Que tumor se asocia al sindrome de Lambert-Eaton?', options: ['El adenocarcinoma de colon', 'El timoma anterior', 'El carcinoma microcitico', 'El linfoma de Hodgkin'], correct: 2, explanation: 'Se asocia en mas de la mitad de los casos, sobre todo en fumadores mayores. El timoma, en cambio, es el tumor asociado a la miastenia gravis, y confundirlos es un error frecuente.', dificultad: 'intermedio' },
  { q: 'Por que se repite el cribado tumoral en el sindrome de Lambert-Eaton?', options: ['Porque el tumor puede aparecer despues', 'Porque los anticuerpos se negativizan', 'Porque la clinica cambia con los a&#241;os', 'Porque el tratamiento lo enmascara'], correct: 0, explanation: 'El cuadro neurologico puede preceder en meses o incluso a&#241;os al diagnostico del carcinoma microcitico. Un cribado inicial negativo no cierra el caso, y se repite de forma periodica durante al menos dos a&#241;os.', dificultad: 'dificil' },
  { q: 'Que hallazgo pupilar delata al botulismo?', options: ['La miosis puntiforme', 'La midriasis arreactiva', 'La anisocoria fluctuante', 'El reflejo consensuado abolido'], correct: 1, explanation: 'La toxina bloquea tambien las sinapsis colinergicas autonomas. Las pupilas NUNCA se afectan en la miastenia, de modo que una midriasis arreactiva en un paciente con paralisis descendente es el dato que lo separa.', dificultad: 'intermedio' },
  { q: 'En que direccion progresa la paralisis del botulismo?', options: ['Ascendente desde los pies', 'De proximal a distal', 'De un lado al otro', 'Descendente desde la cara'], correct: 3, explanation: 'Empieza por los pares craneales (diplopia, ptosis, disartria, disfagia) y desciende de forma simetrica. Se acompa&#241;a de boca seca y estre&#241;imiento, sin fiebre y sin alteracion sensitiva.', dificultad: 'intermedio' },
  { q: 'Que determina la eficacia de la antitoxina botulinica?', options: ['La dosis administrada', 'La via de administracion', 'La precocidad', 'El peso del paciente'], correct: 2, explanation: 'Solo neutraliza la toxina que todavia circula, no la que ya se ha unido a la terminal nerviosa. Por eso se administra ante la sospecha clinica y sin esperar la confirmacion de laboratorio, que es lenta.', dificultad: 'dificil' },

  { type: 'cascade', dificultad: 'dificil',
    vignette: 'Varon de 48 a&#241;os que hace 3 dias comenzo con debilidad en las piernas, dos semanas despues de un cuadro de diarrea. Hoy no puede subir escaleras y presenta diplejia facial. Los reflejos estan abolidos en las cuatro extremidades. La suma de fuerza del Medical Research Council es de 38 sobre 60.',
    steps: [
      { q: 'Que puntuacion EGRIS tiene al ingreso?', options: ['3 puntos', '5 puntos', '7 puntos', '2 puntos'], correct: 1 },
      { q: 'Que categoria de riesgo corresponde?', options: ['Riesgo bajo', 'Riesgo intermedio', 'Riesgo ALTO', 'No valorable'], correct: 2 },
      { q: 'Que implica esa categoria?', options: ['Ingreso donde se pueda intubar ya', 'Alta con revision en 48 horas', 'Ingreso en planta convencional sin mas', 'Observacion en urgencias 12 horas'], correct: 0 }
    ],
    explanation: 'Suma 5 puntos: instauracion en 3 dias (2 puntos), debilidad facial presente (1 punto) y suma de fuerza de 38, que cae en la franja de 31 a 40 (2 puntos). Con 5 o mas, el riesgo de necesitar ventilacion mecanica es ALTO, lo que justifica ingresar al paciente en un area con capacidad de intubacion inmediata. La escala predice al ingreso pero NO sustituye a la vigilancia seriada: hay que medir capacidad vital y presiones maximas cada 4 a 6 horas y monitorizar el electrocardiograma por la disautonomia.' },

  { type: 'cascade', dificultad: 'dificil',
    vignette: 'El mismo paciente, 24 horas despues. Pesa 75 kg. La capacidad vital medida a pie de cama es de 1200 mL y la presion inspiratoria maxima de 26 cmH2O en valor absoluto. Habla de forma entrecortada y no consigue contar hasta 20 en una sola espiracion.',
    steps: [
      { q: 'Cual es su capacidad vital por kilogramo?', options: ['24 mL/kg', '20 mL/kg', '12 mL/kg', '16 mL/kg'], correct: 3 },
      { q: 'Que corresponde hacer?', options: ['Intubacion e ingreso en criticos', 'Repetir la medicion en 12 horas', 'Iniciar oxigeno en gafas nasales', 'Pedir gasometria y decidir con ella'], correct: 0 },
      { q: 'Que farmaco NO se debe usar para intubarlo?', options: ['El propofol', 'El rocuronio', 'La succinilcolina', 'El etomidato'], correct: 2 }
    ],
    explanation: '1200 mL entre 75 kg son 16 mL/kg, por debajo del umbral de 20. Ademas la presion inspiratoria maxima de 26 esta por debajo de 30, con lo que se cumplen dos criterios de la regla de 20, 30 y 40, y a eso se suman los signos clinicos de claudicacion. Corresponde intubacion electiva, que siempre es preferible a la urgente en un paciente que se agota, sin esperar a la gasometria porque la hipercapnia es un signo tardio. Y la succinilcolina esta contraindicada en la denervacion aguda por el riesgo de hiperpotasemia grave con parada cardiaca.' },

  { type: 'cascade', dificultad: 'facil',
    vignette: 'Mujer de 31 a&#241;os que desde hace 4 meses ve doble al final de la tarde y nota que se le cae el parpado derecho segun avanza el dia. Por la ma&#241;ana esta perfectamente. Los reflejos son normales, no hay alteracion sensitiva y las pupilas son normales y reactivas.',
    steps: [
      { q: 'Que hay que sospechar?', options: ['Una miastenia gravis', 'Un sindrome de Miller Fisher', 'Una oftalmopatia tiroidea', 'Un botulismo incipiente'], correct: 0 },
      { q: 'Que prueba sencilla se puede hacer en la consulta?', options: ['El test de Tensilon', 'La prueba del hielo', 'La maniobra de Valsalva', 'El reflejo oculocefalico'], correct: 1 },
      { q: 'Que prueba de imagen no puede faltar?', options: ['Una resonancia de orbitas', 'Una angiotomografia cerebral', 'Una ecografia tiroidea', 'Una tomografia de torax'], correct: 3 }
    ],
    explanation: 'Sintomas oculares fluctuantes que empeoran a lo largo del dia, con reflejos normales, sin alteracion sensitiva y con pupilas normales: es el retrato de una miastenia gravis de inicio ocular. La prueba del hielo sobre el parpado durante unos dos minutos es barata, segura y con buen rendimiento para la ptosis, y puede hacerse en la propia consulta. El diagnostico se confirma con anticuerpos frente al receptor de acetilcolina y, si son negativos, con anti-MuSK y neurofisiologia. Y la tomografia de torax es obligada en todos para buscar timoma.' },

  { type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente con miastenia generalizada que acude a revision. Sobre la ultima semana refiere: habla nasal constante (2), fatiga al masticar comida solida (1), atragantamientos frecuentes con cambio de dieta (2), disnea con el esfuerzo (1), necesita descansos para peinarse (1), se apoya levemente en los brazos para levantarse (1), vision doble diaria pero no constante (2) y caida del parpado diaria pero no constante (2).',
    steps: [
      { q: 'Que puntuacion suma en la escala MG-ADL?', options: ['8 puntos', '10 puntos', '12 puntos', '15 puntos'], correct: 2 },
      { q: 'Que impacto refleja esa puntuacion?', options: ['Sin sintomas', 'Impacto leve', 'Impacto moderado', 'Impacto grave'], correct: 3 },
      { q: 'Que NO sirve para seguir la respuesta al tratamiento?', options: ['La escala MG-ADL', 'El titulo de anticuerpos', 'La capacidad vital', 'La exploracion de la fuerza'], correct: 1 }
    ],
    explanation: 'La suma es 12 sobre 24, que corresponde a un impacto grave y a una enfermedad mal controlada. Ademas, los tres items bulbares (habla, masticacion y deglucion) suman 5, lo que define un perfil de mayor riesgo de crisis y de aspiracion y obliga a valorar formalmente la deglucion. Corresponde revisar adherencia y dosis, descartar un desencadenante y valorar escalada terapeutica. Y el titulo de anticuerpos no sirve para nada en el seguimiento, porque no se correlaciona con la gravedad ni con la respuesta: para eso estan las escalas funcionales y la exploracion.' },

  { type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 64 a&#241;os con miastenia gravis en tratamiento con piridostigmina y prednisona. Hace 4 dias le pautaron levofloxacino por una infeccion urinaria. Acude hoy con disnea, voz nasal y dificultad para tragar su propia saliva. Las pupilas son normales y no tiene diarrea, sudoracion ni sialorrea.',
    steps: [
      { q: 'Que tipo de crisis es?', options: ['Crisis colinergica', 'Crisis miastenica', 'Crisis mixta', 'Crisis de ansiedad'], correct: 1 },
      { q: 'Que farmaco de los que toma ha podido desencadenarla?', options: ['El levofloxacino', 'La prednisona', 'La piridostigmina', 'El paracetamol'], correct: 0 },
      { q: 'Que es lo mas urgente?', options: ['Iniciar inmunoglobulinas', 'Retirar el antibiotico', 'Hacer una tomografia de torax', 'Valorar la funcion respiratoria'], correct: 3 }
    ],
    explanation: 'Sin sintomas muscarinicos, sin miosis y sin fasciculaciones, el perfil es de crisis MIASTENICA. El levofloxacino es una fluoroquinolona, del grupo de antibioticos que con mas frecuencia desencadena una crisis, y su prescripcion sin comprobar la lista es una de las causas evitables mas habituales. Pero lo primero no es ni retirar el antibiotico ni empezar la inmunoterapia: es valorar la funcion respiratoria, porque la dificultad para tragar la propia saliva indica debilidad bulbar y ese dato adelanta la indicacion de intubar aunque los numeros no la cumplan todavia. Despues: retirar el farmaco, tratar la infeccion con otro antibiotico e iniciar inmunoglobulinas o plasmaferesis.' },

  { type: 'cascade', dificultad: 'dificil',
    vignette: 'Varon de 58 a&#241;os, fumador de 40 paquetes-a&#241;o. Desde hace 5 meses le cuesta cada vez mas levantarse de la silla y subir escaleras. Refiere ademas la boca muy seca. En la exploracion, los reflejos rotulianos estan abolidos, pero reaparecen tras pedirle que contraiga el cuadriceps durante 15 segundos.',
    steps: [
      { q: 'Que fenomeno describe la reaparicion de los reflejos?', options: ['El decremento', 'La fatigabilidad', 'La facilitacion', 'La miotonia'], correct: 2 },
      { q: 'Que diagnostico explica el cuadro?', options: ['Miastenia gravis', 'Sindrome de Lambert-Eaton', 'Sindrome de Guillain-Barre', 'Polimiositis'], correct: 1 },
      { q: 'Que hay que buscar de forma activa y repetida?', options: ['Un carcinoma microcitico', 'Un timoma anterior', 'Una gammapatia monoclonal', 'Una enfermedad tiroidea'], correct: 0 }
    ],
    explanation: 'La reaparicion de los reflejos tras la contraccion sostenida es la FACILITACION: el ejercicio acumula calcio en la terminal presinaptica y aumenta la liberacion de acetilcolina. Es lo opuesto a la miastenia, donde el uso empeora la debilidad. Junto con la debilidad proximal de piernas y la boca seca, que es un sintoma autonomo precoz y muy caracteristico, el cuadro es un sindrome de Lambert-Eaton. En un fumador de esta edad hay que buscar un carcinoma microcitico de pulmon, que se asocia en mas de la mitad de los casos, y REPETIR el cribado de forma periodica durante al menos dos a&#241;os, porque el tumor puede aparecer despues del cuadro neurologico.' }
];

export const flashcards = [
  { front: 'Los tres datos que separan la debilidad aguda', back: 'Reflejos, pupilas y direccion de la debilidad.' },
  { front: 'Reflejos en miastenia frente a Guillain-Barre', back: 'Normales en la miastenia, abolidos en el Guillain-Barre.' },
  { front: 'Progresion del Guillain-Barre', back: 'Maximo en menos de 4 semanas, habitualmente en 2.' },
  { front: 'Liquido cefalorraquideo en el Guillain-Barre', back: 'Disociacion albuminocitologica, pero puede ser NORMAL la primera semana.' },
  { front: 'Mas de 50 celulas en el liquido', back: 'No encaja: pensar en VIH, Lyme, linfoma o sarcoidosis.' },
  { front: 'Corticoides en el Guillain-Barre', back: 'NO son eficaces. Si lo son en la forma inflamatoria CRONICA.' },
  { front: 'Inmunoglobulinas o plasmaferesis', back: 'Eficacia equivalente. Se usa una U otra: NUNCA se combinan.' },
  { front: 'Las dos causas de muerte del Guillain-Barre', back: 'Insuficiencia respiratoria y DISAUTONOMIA.' },
  { front: 'El sintoma que despista en el Guillain-Barre', back: 'El dolor de espalda radicular, que a menudo precede a la debilidad.' },
  { front: 'Escala EGRIS', back: 'Dias hasta el ingreso, debilidad facial o bulbar y suma MRC. 5 o mas: riesgo ALTO.' },
  { front: 'Regla de 20, 30 y 40', back: 'Capacidad vital menor de 20 mL/kg, PIM menor de 30 o PEM menor de 40 cmH2O.' },
  { front: 'Por que no esperar a la gasometria', back: 'La hipercapnia es TARDIA: aparece cuando el paciente ya esta agotado.' },
  { front: 'Lo que adelanta la intubacion', back: 'La DEBILIDAD BULBAR: el riesgo es la aspiracion, no la fatiga.' },
  { front: 'Signo de cabecera sin aparatos', back: 'No poder contar de corrido hasta 20 en una sola espiracion.' },
  { front: 'Farmaco contraindicado para intubar', back: 'La SUCCINILCOLINA: riesgo de hiperpotasemia grave en la denervacion aguda.' },
  { front: 'Que define a la miastenia', back: 'La FATIGABILIDAD: empeora con el uso y con el dia, mejora con el reposo.' },
  { front: 'Sintomas de debut de la miastenia', back: 'Ptosis y diplopia en la mayoria. Una parte generaliza en 2 a&#241;os.' },
  { front: 'Prueba del hielo', back: 'Hielo sobre el parpado 2 minutos: mejora la ptosis. Barata y con buen rendimiento.' },
  { front: 'La imagen obligada en la miastenia', back: 'TOMOGRAFIA DE TORAX a todos, para buscar TIMOMA.' },
  { front: 'Cuando timectomia', back: 'Siempre si hay timoma. Y en la generalizada anti-receptor de inicio precoz sin timoma.' },
  { front: 'Subtipo anti-MuSK', back: 'Bulbar y facial, atrofia lingual, mala respuesta a piridostigmina, buena a rituximab.' },
  { front: 'Titulo de anticuerpos en el seguimiento', back: 'NO sirve: no se correlaciona con la gravedad. Usar escalas funcionales.' },
  { front: 'Como se inicia el corticoide en la miastenia', back: 'A dosis BAJA y subiendo despacio: a dosis alta puede empeorar de forma transitoria.' },
  { front: 'Antibioticos que desencadenan crisis', back: 'FLUOROQUINOLONAS, macrolidos y aminoglucosidos. Comprobar antes de prescribir.' },
  { front: 'Otros farmacos contraindicados', back: 'Betabloqueantes, MAGNESIO intravenoso, bloqueantes neuromusculares, penicilamina, cloroquina.' },
  { front: 'Desencadenante mas frecuente de crisis miastenica', back: 'La INFECCION intercurrente. Le siguen cirugia, farmacos y retirada rapida de inmunosupresion.' },
  { front: 'Piridostigmina durante la ventilacion', back: 'Se SUSPENDE: ya no aporta y aumenta las secreciones.' },
  { front: 'Crisis colinergica', back: 'Sintomas muscarinicos, MIOSIS, bradicardia y fasciculaciones. Hoy es rara.' },
  { front: 'Ante la duda entre las dos crisis', back: 'Asegurar la respiracion y SUSPENDER la piridostigmina.' },
  { front: 'Facilitacion', back: 'La fuerza MEJORA tras la contraccion sostenida: sindrome de Lambert-Eaton.' },
  { front: 'Tumores asociados', back: 'Miastenia: TIMOMA. Lambert-Eaton: carcinoma MICROCITICO, y se criba de forma repetida.' },
  { front: 'Lo que delata al botulismo', back: 'PUPILAS MIDRIATICAS con paralisis DESCENDENTE. Antitoxina precoz.' }
];

export default { quiz, flashcards };
