// topics/broncoaspiracion/study.js: Autoevaluacion de broncoaspiracion.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
// Fuentes: Marik PE. N Engl J Med 2001;344:665-671; guia ATS/IDSA de 2019 de neumonia
// comunitaria; Hadid W, et al. J Thorac Dis 2024;16:3431-3440.
// 30 sueltas + 6 cascadas de 3 = 48 subpreguntas, 32 tarjetas.

export const quiz = [
  { q:'&#191;Que es la neumonitis por aspiracion?', options:['Una infeccion por flora orofaringea', 'Una lesion quimica por contenido gastrico', 'Una neumonia por anaerobios de la cavidad oral', 'Una reaccion alergica al alimento'], correct:1, explanation:'Es una lesion pulmonar aguda quimica tras inhalar contenido gastrico regurgitado, que es esteril en condiciones normales. La neumonia por aspiracion, en cambio, es una infeccion por secreciones orofaringeas colonizadas.', dificultad:'facil' },
  { q:'&#191;En que paciente es tipica la neumonitis por aspiracion?', options:['Anciano institucionalizado con disfagia', 'Fumador con bronquitis cronica', 'Paciente con reflujo leve y tos cronica', 'Paciente con conciencia muy disminuida'], correct:3, explanation:'Aparece en pacientes con una alteracion marcada de la conciencia: sobredosis, convulsiones, ictus extenso o anestesia. El riesgo aumenta cuanto menor es la escala de Glasgow.', dificultad:'facil' },
  { q:'&#191;En que paciente es tipica la neumonia por aspiracion?', options:['Joven tras una sobredosis', 'Paciente durante la anestesia', 'Anciano con disfagia', 'Embarazada en el parto'], correct:2, explanation:'En el anciano, a menudo institucionalizado, con disfagia o dismotilidad gastrica, en el que aparece una neumonia con infiltrado en un segmento declive sin que nadie haya visto aspirar.', dificultad:'facil' },
  { q:'&#191;Que umbrales de pH y volumen se aceptan para producir neumonitis?', options:['pH menor de 2.5 y mas de 0.3 mL/kg', 'pH menor de 5 y mas de 1 mL/kg', 'pH menor de 7 y mas de 0.1 mL/kg', 'pH menor de 1 y mas de 5 mL/kg'], correct:0, explanation:'La mayoria de los autores acepta un pH menor de 2.5 y un volumen mayor de 0.3 mL/kg (20 a 25 mL en el adulto). Pero el material particulado puede da&#241;ar aunque el pH sea mayor de 2.5.', dificultad:'dificil' },
  { q:'&#191;Como es la lesion pulmonar tras la aspiracion de acido?', options:['Unica y tardia, a los 3 dias', 'Inmediata y sin inflamacion', 'Progresiva durante una semana', 'Bifasica, a las 1-2 y 4-6 h'], correct:3, explanation:'Es bifasica: un primer pico a las 1 a 2 horas por el efecto caustico del acido, y un segundo a las 4 a 6 horas por la infiltracion de neutrofilos y la inflamacion aguda.', dificultad:'dificil' },
  { q:'&#191;Por que la neumonitis no es una infeccion al principio?', options:['Porque el acido mata a las bacterias', 'Porque el moco atrapa a las bacterias', 'Porque los pulmones son esteriles', 'Porque la saliva neutraliza el acido'], correct:0, explanation:'El acido gastrico impide el crecimiento bacteriano, de modo que el contenido gastrico es esteril en condiciones normales. La infeccion puede aparecer mas tarde.', dificultad:'intermedio' },
  { q:'&#191;Que hace que el contenido gastrico deje de ser esteril?', options:['El ayuno prolongado de varios dias', 'Antisecretores y nutricion enteral', 'La posicion semiincorporada en cama', 'La dieta rica en fibra vegetal'], correct:1, explanation:'Al subir el pH con antiacidos, antagonistas H2 o inhibidores de la bomba de protones, o con la nutricion enteral, la gastroparesia o la obstruccion intestinal, el estomago se coloniza por gramnegativos.', dificultad:'intermedio' },
  { q:'&#191;Que se recomienda sobre el antibiotico profilactico tras una aspiracion presenciada?', options:['Darlo durante 5 dias', 'Darlo si hay fiebre', 'No darlo', 'Darlo con corticoide'], correct:2, explanation:'No se recomienda, aunque sea practica habitual. Tampoco se aconseja empezarlo poco despues porque aparezcan fiebre, leucocitosis o infiltrado: selecciona germenes resistentes en una lesion quimica.', dificultad:'facil' },
  { q:'&#191;Cuando debe considerarse el antibiotico en la neumonitis?', options:['Si hay fiebre en las primeras horas', 'Si la radiografia esta alterada', 'Si la aspiracion fue presenciada', 'Si no se resuelve en 48 horas'], correct:3, explanation:'Debe considerarse si la neumonitis no se resuelve en 48 horas, y es apropiado de entrada si hay obstruccion intestinal u otra condicion que colonice el contenido gastrico.', dificultad:'intermedio' },
  { q:'&#191;En que neumonitis esta indicado el antibiotico empirico de entrada?', options:['En el joven tras una sobredosis', 'En la aspiracion durante la anestesia', 'En la que tiene obstruccion intestinal', 'En la que se presenta con broncoespasmo'], correct:2, explanation:'Cuando hay obstruccion de intestino delgado u otra condicion asociada a colonizacion gastrica, porque el material aspirado ya no es esteril.', dificultad:'intermedio' },
  { q:'&#191;Que se concluye sobre los corticoides en la neumonitis por aspiracion?', options:['Que mejoran la supervivencia', 'Que acortan la ventilacion', 'Que no pueden recomendarse', 'Que previenen la neumonia'], correct:2, explanation:'No pueden recomendarse: un ensayo mejoro antes la radiografia pero alargo la estancia en criticos sin cambiar el resultado, otro estudio asocio mas neumonias por gramnegativos, y los modelos animales no mostraron beneficio.', dificultad:'intermedio' },
  { q:'&#191;Que proporcion de las aspiraciones durante la anestesia fue asintomatica en la serie citada?', options:['El 10%', 'El 25%', 'El 63%', 'El 95%'], correct:2, explanation:'De 67 pacientes que aspiraron durante la anestesia, 42 (63%) no tuvieron sintomas. De los 25 sintomaticos, 13 necesitaron ventilacion mas de 6 horas y 4 murieron.', dificultad:'dificil' },
  { q:'&#191;Que es la aspiracion silente?', options:['La que solo se ve como desaturacion', 'La que ocurre durante el sue&#241;o', 'La que no produce ningun da&#241;o', 'La que solo afecta a la laringe'], correct:0, explanation:'Se manifiesta solo como desaturacion arterial con imagen compatible, sin otros sintomas. Es frecuente en el ictus y en el anciano.', dificultad:'intermedio' },
  { q:'&#191;Que proporcion de las neumonias comunitarias son por aspiracion?', options:['Entre el 5% y el 15%', 'Menos del 1%', 'Entre el 40% y el 50%', 'Mas del 70%'], correct:0, explanation:'Varios estudios indican que entre el 5% y el 15% de las neumonias comunitarias son neumonias por aspiracion.', dificultad:'intermedio' },
  { q:'Si la aspiracion ocurrio en decubito, &#191;que segmentos suelen afectarse?', options:['Los segmentos basales de ambos lobulos inferiores', 'La lingula y el lobulo medio', 'Posteriores superiores y apicales inferiores', 'Los anteriores de los lobulos superiores'], correct:2, explanation:'En decubito, los segmentos posteriores de los lobulos superiores y los apicales de los inferiores. Sentado o semiincorporado, los segmentos basales de los lobulos inferiores.', dificultad:'intermedio' },
  { q:'&#191;Hace falta haber visto la aspiracion para diagnosticar una neumonia por aspiracion?', options:['Si, debe haber sido presenciada', 'No, basta con una tos con la comida', 'Si, salvo que haya contenido en la boca', 'No, se infiere del riesgo y la imagen'], correct:3, explanation:'Es uno de los cuatro errores que se&#241;ala Marik. La neumonia por aspiracion casi nunca se presencia: se infiere en un paciente de riesgo con un infiltrado en un segmento declive caracteristico.', dificultad:'facil' },
  { q:'&#191;Que proporcion de adultos sanos aspira peque&#241;as cantidades de secrecion durante el sue&#241;o?', options:['Alrededor de la mitad', 'Menos del 5%', 'Practicamente todos', 'Alrededor de un 15%'], correct:0, explanation:'Aproximadamente la mitad. La baja carga bacteriana, la tos, el aclaramiento ciliar y la inmunidad lo resuelven sin consecuencias en la mayoria.', dificultad:'intermedio' },
  { q:'&#191;Que germenes predominaron en la neumonia por aspiracion comunitaria con tecnicas modernas?', options:['Anaerobios estrictos de la boca', 'Virus respiratorios comunes', 'Hongos y micobacterias atipicas', 'Neumococo, S. aureus y enterobacterias'], correct:3, explanation:'Con cepillo protegido y cultivo cuantitativo predominaron Streptococcus pneumoniae, Staphylococcus aureus, Haemophilus influenzae y enterobacterias en la comunitaria, y gramnegativos con Pseudomonas en la hospitalaria. No se aislaron anaerobios.', dificultad:'intermedio' },
  { q:'&#191;Por que los estudios antiguos encontraban sobre todo anaerobios?', options:['Porque usaban mejores tecnicas de cultivo', 'Por muestras tardias y contaminadas', 'Porque entonces no habia gramnegativos', 'Porque los pacientes eran mas jovenes'], correct:1, explanation:'Las muestras transtraqueales se tomaban tarde, a menudo con abscesos o empiema ya formados, en pacientes alcoholicos con esputo putrido, y podian contaminarse con flora orofaringea.', dificultad:'dificil' },
  { q:'&#191;Que dice la guia ATS/IDSA de 2019 sobre la cobertura anaerobia en la sospecha de neumonia por aspiracion?', options:['A&#241;adirla de entrada a todos', 'A&#241;adirla si hay fiebre', 'A&#241;adirla en mayores de 65', 'No a&#241;adirla de rutina'], correct:3, explanation:'Recomienda no a&#241;adir de rutina cobertura anaerobia salvo que se sospeche absceso o empiema. Marik ya la reservaba a la enfermedad periodontal grave, el esputo putrido y la neumonia necrotizante o el absceso.', dificultad:'intermedio' },
  { q:'&#191;Que limitacion tienen la penicilina y la clindamicina en la neumonia por aspiracion?', options:['Son demasiado nefrotoxicas', 'No cubren a los gramnegativos', 'No alcanzan el pulmon', 'Interaccionan con la nutricion'], correct:1, explanation:'Consideradas clasicamente el estandar, son insuficientes para la mayoria de los pacientes, porque lo que suele hacer falta es actividad frente a gramnegativos.', dificultad:'intermedio' },
  { q:'&#191;Que dato orienta a cubrir anaerobios?', options:['Una edad mayor de 80 a&#241;os', 'Una fiebre mayor de 39 grados', 'Un esputo putrido', 'Una tos con la ingesta'], correct:2, explanation:'La enfermedad periodontal grave, el esputo putrido, el alcoholismo y la neumonia necrotizante o el absceso en la imagen. En esos casos si se cubren anaerobios.', dificultad:'facil' },
  { q:'&#191;Que valor tienen los reflejos tusigeno y nauseoso para valorar el riesgo de aspiracion?', options:['Son el metodo de referencia', 'Solo fallan en el anciano', 'Son fiables en el ictus', 'No son fiables'], correct:3, explanation:'No son fiables. Hace falta una valoracion completa de la deglucion, completada con videofluoroscopia o endoscopia, que puede hacer un logopeda a pie de cama.', dificultad:'facil' },
  { q:'&#191;Previene la gastrostomia la neumonia por aspiracion mejor que la sonda nasogastrica?', options:['Si, la reduce a la mitad', 'No, fue similar', 'Si, en el ictus agudo', 'No, la aumenta claramente'], correct:1, explanation:'En dos estudios la gastrostomia aporto mejor la nutricion, pero la incidencia de neumonia fue similar, y tambien con sondas pospiloricas. Ninguna protege de las secreciones orofaringeas colonizadas.', dificultad:'intermedio' },
  { q:'Tras la extubacion, &#191;cuanto propone Marik mantener al paciente sin alimentacion oral?', options:['Al menos 6 horas', 'Al menos 72 horas', 'Solo 30 minutos', 'Hasta el dia siguiente'], correct:0, explanation:'Al menos 6 horas, por si hay que reintubar, y despues dieta de pure y luego blanda durante al menos 48 horas.', dificultad:'intermedio' },
  { q:'&#191;Tras cuantas horas de intubacion ya puede alterarse el reflejo deglutorio?', options:['Tras 7 dias', 'Tras 2 semanas', 'Tras 72 horas', 'Tras 24 horas'], correct:3, explanation:'La alteracion se detecta incluso tras 24 horas de intubacion, y suele resolverse en 48 horas.', dificultad:'dificil' },
  { q:'&#191;Que proporcion de pacientes en decubito supino tiene reflujo gastroesofagico?', options:['Menos del 2%', 'Hasta un 30%', 'Mas del 80%', 'Solo con sonda'], correct:1, explanation:'Hasta un 30%, incluso sin sonda nasogastrica ni nutricion enteral. Por eso se evita el decubito supino estricto en el critico.', dificultad:'intermedio' },
  { q:'&#191;Que sonda puede tener ventajas en el critico con gastroparesia?', options:['La nasogastrica gruesa', 'La pospilorica', 'La orogastrica', 'La de doble luz'], correct:1, explanation:'La alimentacion pospilorica puede tener ventajas en el paciente con gastroparesia, en el que el residuo alto distiende el estomago y favorece la regurgitacion.', dificultad:'intermedio' },
  { q:'&#191;Que proporcion de abscesos pulmonares no responde al antibiotico?', options:['Menos del 5%', 'Mas del 90%', 'Alrededor del 70%', 'Hasta un 37%'], correct:3, explanation:'El antibiotico sistemico tiene un exito del 63% al 67%, de modo que hasta un 37% no responde y puede necesitar drenaje o cirugia.', dificultad:'intermedio' },
  { q:'&#191;Que tama&#241;o de absceso responde peor al antibiotico?', options:['Menos de 2 cm', 'Mas de 6 cm', 'Entre 2 y 3 cm', 'El tama&#241;o no influye'], correct:1, explanation:'Los abscesos de mas de 6 cm responden peor y a menudo requieren drenaje. Tambien hay que buscar una obstruccion endobronquial por tumor o cuerpo extra&#241;o.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 24 a&#241;os traido por una sobredosis de benzodiacepinas y alcohol, con Glasgow de 7. Vomita en urgencias y se observa contenido gastrico en la orofaringe. A las 3 horas presenta taquipnea, sibilancias y saturacion del 88%, con infiltrado en el lobulo inferior derecho y fiebre de 38.',
    steps:[
    { q:'&#191;Cual es el diagnostico mas probable?', options:['Neumonia por aspiracion', 'Neumonia comunitaria', 'Edema cardiogenico', 'Neumonitis quimica'], correct:3 },
    { q:'&#191;Que hacer con el antibiotico ahora?', options:['Iniciarlo por la fiebre', 'Iniciarlo con anaerobios', 'No darlo de entrada', 'Darlo con corticoide'], correct:2 },
    { q:'&#191;Que medida de la via aerea procede?', options:['Intubar si no la protege', 'Solo oxigeno con gafas', 'Maniobra de Heimlich', 'Sonda y esperar'], correct:0 }
  ], explanation:'Conciencia muy disminuida, aspiracion de contenido gastrico y clinica en horas: neumonitis quimica. La fiebre y el infiltrado precoces pueden ser solo inflamatorios, y no se recomienda el antibiotico de entrada. Se aspira la via aerea y se intuba si el paciente no puede protegerla.', dificultad:'facil' },

  { type:'cascade', vignette:'Mujer de 84 a&#241;os en una residencia, con disfagia tras un ictus hace un a&#241;o. Desde hace 3 dias tiene fiebre, tos y taquipnea. La radiografia muestra una consolidacion en el segmento basal del lobulo inferior derecho. Nadie la vio atragantarse. Buena dentadura y sin esputo putrido.', steps:[
    { q:'&#191;Cual es el diagnostico?', options:['Neumonitis quimica', 'Neumonia por aspiracion', 'Tromboembolia pulmonar aguda', 'Absceso pulmonar'], correct:1 },
    { q:'&#191;Que espectro antibiotico necesita?', options:['Solo anaerobios', 'No precisa, es quimica', 'Solo grampositivos', 'Con gramnegativos'], correct:3 },
    { q:'&#191;Hace falta cubrir anaerobios?', options:['Si, por la edad', 'Si, por la disfagia', 'No, sin datos de ello', 'Si, por la residencia'], correct:2 }
  ], explanation:'Disfagia, residencia, evolucion de dias y consolidacion declive: neumonia por aspiracion, que se infiere aunque nadie la haya visto. Necesita antibiotico con cobertura de gramnegativos, incluida Pseudomonas por proceder de una residencia. Sin absceso, empiema, periodontitis grave ni esputo putrido, no se cubren anaerobios de rutina.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 66 a&#241;os ingresado por una obstruccion de intestino delgado, con sonda nasogastrica y tratamiento con un inhibidor de la bomba de protones. Vomita y aspira. A las pocas horas tiene fiebre, hipoxemia e infiltrado bilateral.', steps:[
    { q:'&#191;Es esteril el material aspirado?', options:['Si, por el acido', 'No, esta colonizado', 'Si, por la sonda', 'Depende del volumen aspirado'], correct:1 },
    { q:'&#191;Se indica antibiotico de entrada?', options:['No, hay que esperar 48 h', 'Solo si sale cultivo', 'No, es una lesion quimica', 'Si, por la colonizacion'], correct:3 },
    { q:'&#191;Que espectro es el adecuado?', options:['Amplio con gramnegativos', 'Penicilina sola a dosis altas', 'Solo clindamicina', 'Solo antifungico'], correct:0 }
  ], explanation:'La obstruccion intestinal y el inhibidor de la bomba de protones colonizan el estomago por gramnegativos, de modo que el aspirado ya no es esteril. En este caso si es apropiado el antibiotico empirico de entrada, con un espectro amplio que cubra gramnegativos.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Mujer de 70 a&#241;os extubada esta ma&#241;ana tras 4 dias de ventilacion por una neumonia. La intubacion inicial fue dificil y traumatica. La enfermera pregunta si puede darle el desayuno, 2 horas despues de la extubacion.', steps:[
    { q:'&#191;Puede comer ya?', options:['Si, dieta normal', 'Solo liquidos claros', 'No, esperar 6 horas', 'Si, si tose bien'], correct:2 },
    { q:'&#191;Que dieta se introduce despues?', options:['Normal desde el inicio', 'Pure y luego blanda', 'Solo liquidos 72 horas', 'Nutricion parenteral'], correct:1 },
    { q:'&#191;Que a&#241;ade la intubacion traumatica?', options:['Nada, se sigue igual', 'Valoracion de la deglucion', 'Antibiotico preventivo inmediato', 'Una nueva intubacion'], correct:1 }
  ], explanation:'Marik propone suspender la alimentacion oral al menos 6 horas tras la extubacion, por si hay que reintubar, y despues pure y dieta blanda durante al menos 48 horas. La intubacion traumatica justifica una valoracion formal de la deglucion antes de avanzar.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 58 a&#241;os con alcoholismo y muy mala dentadura que consulta por fiebre de 2 semanas, perdida de peso y esputo putrido. La tomografia muestra una cavidad de 7 cm con nivel hidroaereo en el lobulo superior derecho.', steps:[
    { q:'&#191;Que diagnostico corresponde?', options:['Neumonitis quimica', 'Neumotorax', 'Bulla infectada', 'Absceso pulmonar'], correct:3 },
    { q:'&#191;Hace falta cubrir anaerobios?', options:['No, no se cubren', 'Si, en este caso si', 'No, solo gramnegativos', 'Solo si es mayor de 10 cm'], correct:1 },
    { q:'&#191;Que implica el tama&#241;o de 7 cm?', options:['Respuesta peor al antibiotico', 'Indicacion de corticoide sistemico', 'Curacion espontanea', 'Que no es un absceso'], correct:0 }
  ], explanation:'Cavidad con nivel hidroaereo, esputo putrido, mala dentadura y alcoholismo: absceso pulmonar, el escenario en el que si se cubren anaerobios. Los abscesos de mas de 6 cm responden peor al antibiotico y a menudo requieren drenaje, endoscopico si hay un bronquio de acceso o percutaneo.', dificultad:'intermedio' },

  { type:'cascade', vignette:'Varon de 76 a&#241;os con un ictus agudo hace 3 dias. Come solo y no tose con las comidas. El residente da por hecho que no tiene riesgo de aspiracion porque el reflejo nauseoso esta presente.', steps:[
    { q:'&#191;Es valido ese razonamiento?', options:['Si, el reflejo protege', 'Solo en los jovenes', 'Si, si no tose al comer', 'No, no es fiable'], correct:3 },
    { q:'&#191;Que es frecuente en estos pacientes?', options:['La aspiracion silente', 'El reflujo acido aislado', 'La neumonitis quimica', 'La obstruccion intestinal'], correct:0 },
    { q:'&#191;Que prueba completa la valoracion?', options:['Una radiografia de torax', 'Una videofluoroscopia', 'Una tomografia craneal', 'Una gasometria basal'], correct:1 }
  ], explanation:'Los reflejos tusigeno y nauseoso no son fiables para identificar el riesgo. En el ictus la disfagia afecta al 40% a 70%, muchos aspiran de forma silente, y la neumonia es 7 veces mas probable si se confirma la aspiracion. Hace falta una valoracion formal de la deglucion con videofluoroscopia o endoscopia.', dificultad:'intermedio' }
];

export const flashcards = [
  { front:'Neumonitis por aspiracion', back:'Lesion QUIMICA por contenido gastrico esteril, en el paciente con la conciencia muy disminuida. Horas.' },
  { front:'Neumonia por aspiracion', back:'INFECCION por secrecion orofaringea colonizada, en el anciano con disfagia. Dias. Casi nunca presenciada.' },
  { front:'Sindrome de Mendelson', back:'La forma historica de neumonitis, descrita en 1946 en la anestesia obstetrica.' },
  { front:'Umbrales de la neumonitis', back:'pH menor de 2.5 y volumen mayor de 0.3 mL/kg (20 a 25 mL). El material particulado da&#241;a aunque el pH sea mayor.' },
  { front:'Lesion bifasica', back:'Pico a las 1 a 2 h por el acido y a las 4 a 6 h por neutrofilos e inflamacion.' },
  { front:'Contenido gastrico esteril', back:'El acido impide el crecimiento bacteriano. Deja de serlo con antisecretores, nutricion enteral, gastroparesia u obstruccion intestinal.' },
  { front:'Antibiotico en la neumonitis', back:'No profilactico, ni por fiebre o infiltrado precoces. Si de entrada con obstruccion intestinal o colonizacion; considerar si no se resuelve en 48 h.' },
  { front:'Corticoides en la neumonitis', back:'No recomendados: mas estancia en criticos y mas neumonias por gramnegativos.' },
  { front:'Neumonitis en la anestesia', back:'1 de cada 3.000 anestesias; 10% a 30% de las muertes por anestesia. El 63% de las aspiraciones fue asintomatico.' },
  { front:'Neumonitis en la sobredosis', back:'Alrededor del 10% de los ingresados por sobredosis.' },
  { front:'Aspiracion silente', back:'Solo desaturacion con imagen compatible. Frecuente en el ictus y el anciano.' },
  { front:'Neumonia por aspiracion en cifras', back:'Del 5% al 15% de las neumonias comunitarias. 18% de las de residencia frente a 5% de las comunitarias en un estudio.' },
  { front:'Aspiracion en el sue&#241;o', back:'Alrededor de la mitad de los adultos sanos aspira peque&#241;as cantidades sin consecuencias.' },
  { front:'Segmentos en decubito', back:'Posteriores de los lobulos superiores y apicales de los inferiores.' },
  { front:'Segmentos sentado', back:'Basales de los lobulos inferiores.' },
  { front:'Los cuatro errores de Marik', back:'No distinguir neumonitis de neumonia, creer infecciosa toda aspiracion, no conocer los germenes reales y exigir que la aspiracion se haya visto.' },
  { front:'Germenes comunitarios', back:'Neumococo, S. aureus, H. influenzae y enterobacterias.' },
  { front:'Germenes hospitalarios', back:'Gramnegativos, incluida Pseudomonas aeruginosa.' },
  { front:'Anaerobios con tecnicas modernas', back:'No se aislaron en los estudios con cepillo protegido y cultivo cuantitativo.' },
  { front:'Cobertura anaerobia (ATS/IDSA 2019)', back:'No de rutina en la sospecha de neumonia por aspiracion; si se sospecha absceso o empiema.' },
  { front:'Cuando si cubrir anaerobios', back:'Absceso, empiema, neumonia necrotizante, periodontitis grave, esputo putrido o alcoholismo.' },
  { front:'Penicilina y clindamicina', back:'Clasicamente el estandar, pero insuficientes para la mayoria: hace falta cubrir gramnegativos.' },
  { front:'Reflejos tusigeno y nauseoso', back:'No fiables para valorar el riesgo. Valoracion formal con videofluoroscopia o endoscopia.' },
  { front:'Disfagia en el ictus', back:'Del 40% al 70%. Neumonia 7 veces mas probable si se confirma la aspiracion.' },
  { front:'Gastrostomia frente a sonda', back:'Mejor nutricion, pero la misma incidencia de neumonia. Ninguna protege de las secreciones.' },
  { front:'Estrategias compensadoras', back:'Dieta blanda, bocados peque&#241;os, barbilla abajo, cabeza girada, degluciones repetidas.' },
  { front:'Reflujo en el critico', back:'Hasta un 30% en decubito supino, incluso sin sonda. Evitar el supino estricto.' },
  { front:'Gastroparesia en el critico', back:'Quemados, sepsis, trauma, cirugia y choque. La sonda pospilorica puede ayudar.' },
  { front:'Tras la extubacion', back:'Nada por boca 6 horas; despues pure y blanda 48 horas. Valoracion formal si la intubacion fue traumatica.' },
  { front:'Reflejo deglutorio tras intubar', back:'Alterado incluso tras 24 h de intubacion; suele normalizarse en 48 h.' },
  { front:'Absceso: respuesta al antibiotico', back:'Exito del 63% al 67%; hasta un 37% no responde. Peor si mide mas de 6 cm.' },
  { front:'Drenaje del absceso', back:'Endoscopico si hay bronquio de acceso, con menos complicaciones; percutaneo si no. Reseccion como ultimo recurso.' }
];

export default { quiz, flashcards };
