// topics/hemoglobinopatias/study.js: Autoevaluación de Hemoglobinopatías.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Índices `correct` de las 30 preguntas sueltas, en orden: 1,3,2,0,1,0,3,2,1,3,0,2,1,0,3,1,2,3,0,
// 2,1,0,3,2,1,3,0,2,0,3. Recuento: 0×8, 1×7, 2×7, 3×8. Sin racha >2 ni ciclo fijo.
// Índices `correct` de los pasos de las 5 preguntas en cascada (3 pasos c/u), en orden: 0,1,2 /
// 2,0,3 / 1,3,0 / 0,2,1 / 3,1,2. Recuento: 0×4, 1×4, 2×4, 3×3.
// IMPORTANTE: cada `correct` fue verificado contra el texto de la explanation antes de cerrar el
// archivo (ver memoria del proyecto sobre errores de índice al reordenar opciones por objetivo).

export const quiz = [
  { q: '¿Cuál es la diferencia mecanística fundamental entre las talasemias y la enfermedad de células falciformes?', options: ['No hay ninguna diferencia real, ambas son la misma enfermedad', 'Las talasemias son un defecto cuantitativo (déficit de producción de una cadena de globina normal); la enfermedad de células falciformes es un defecto cualitativo (producción normal de una cadena de globina estructuralmente anómala)', 'Las talasemias solo afectan a niños', 'La enfermedad de células falciformes nunca es hereditaria'], correct: 1, explanation: 'Las talasemias son un defecto cuantitativo; la enfermedad de células falciformes es un defecto cualitativo de una cadena de globina estructuralmente anómala.', dificultad: 'facil' },
  { q: '¿Cuántas copias del gen de globina alfa tiene una persona normalmente?', options: ['2 (1 en cada cromosoma 16)', '1 solamente', '3 en total', '4 (2 en cada cromosoma 16)'], correct: 3, explanation: 'Una persona tiene normalmente 4 copias del gen de globina alfa, 2 en cada cromosoma 16.', dificultad: 'facil' },
  { q: '¿Qué produce la pérdida de 3 de los 4 genes de globina alfa?', options: ['Ningún efecto clínico', 'Hidropesía fetal incompatible con la vida sin tratamiento', 'Enfermedad de HbH, con anemia hemolítica moderada', 'Rasgo talasémico asintomático'], correct: 2, explanation: 'La pérdida de 3 de los 4 genes de globina alfa produce la enfermedad de HbH, con anemia hemolítica moderada.', dificultad: 'intermedio' },
  { q: '¿Qué produce la pérdida de los 4 genes de globina alfa?', options: ['Hidropesía fetal por hemoglobina de Bart, generalmente incompatible con la vida extrauterina sin tratamiento intrauterino', 'Ningún efecto clínico significativo', 'Rasgo talasémico leve', 'Enfermedad de HbH moderada'], correct: 0, explanation: 'La pérdida de los 4 genes de globina alfa produce hidropesía fetal por hemoglobina de Bart, generalmente incompatible con la vida extrauterina sin tratamiento intrauterino especializado.', dificultad: 'intermedio' },
  { q: '¿Cuántas copias del gen de globina beta tiene una persona normalmente?', options: ['4 en total', '2 (1 en cada cromosoma 11)', '1 solamente', '3 en total'], correct: 1, explanation: 'Una persona tiene 2 copias del gen de globina beta, 1 en cada cromosoma 11 (a diferencia de las 4 copias del gen de globina alfa).', dificultad: 'facil' },
  { q: '¿Qué hallazgo de electroforesis es clave para el diagnóstico del rasgo de talasemia beta?', options: ['HbA2 elevada', 'HbS predominante', 'Hemoglobina de Bart', 'Hemoglobina H'], correct: 0, explanation: 'La HbA2 elevada es el hallazgo clave del rasgo de talasemia beta en la electroforesis de hemoglobina.', dificultad: 'intermedio' },
  { q: '¿Cuál es el pilar fundamental del tratamiento a largo plazo del paciente con talasemia mayor politransfundido?', options: ['Ácido fólico exclusivamente', 'Esplenectomía de rutina', 'Antibiótico profiláctico de por vida', 'Quelación de hierro sistemática, dado que la sobrecarga de hierro es la principal causa de morbimortalidad tardía'], correct: 3, explanation: 'La quelación de hierro sistemática es el pilar fundamental del tratamiento a largo plazo, dado que la sobrecarga de hierro transfusional es la principal causa de morbimortalidad tardía.', dificultad: 'facil' },
  { q: '¿Cuál es la única opción curativa disponible para la talasemia mayor?', options: ['Hidroxiurea en dosis altas', 'Quelación de hierro intensiva sin transfusión', 'Trasplante alogénico de células madre hematopoyéticas', 'Esplenectomía'], correct: 2, explanation: 'El trasplante alogénico de células madre hematopoyéticas es la única opción curativa disponible para la talasemia mayor.', dificultad: 'intermedio' },
  { q: '¿Cuál es la mutación específica responsable de la hemoglobina S?', options: ['Deleción completa del gen de globina beta', 'Una sustitución puntual (ácido glutámico por valina) en la cadena beta de globina', 'Una translocación cromosómica', 'Una deleción parcial del gen de globina alfa'], correct: 1, explanation: 'La hemoglobina S es producida por una sustitución puntual (ácido glutámico por valina) en la posición 6 de la cadena beta de globina.', dificultad: 'intermedio' },
  { q: '¿Qué condición favorece la polimerización de la hemoglobina S y la falciformación del eritrocito?', options: ['La sobreoxigenación', 'La hipertermia únicamente', 'La alcalosis metabólica', 'La desoxigenación'], correct: 3, explanation: 'La desoxigenación favorece la polimerización de la hemoglobina S, distorsionando el eritrocito hacia la forma de hoz.', dificultad: 'facil' },
  { q: '¿Cuál es el motivo de consulta más frecuente en la enfermedad de células falciformes?', options: ['Crisis vaso-oclusiva dolorosa', 'Fiebre aislada sin otro síntoma', 'Ictericia aislada', 'Cefalea crónica'], correct: 0, explanation: 'La crisis vaso-oclusiva dolorosa es el motivo de consulta más frecuente en la enfermedad de células falciformes.', dificultad: 'facil' },
  { q: '¿Qué fármaco es el tratamiento modificador de la enfermedad de primera línea en la enfermedad de células falciformes?', options: ['Deferoxamina', 'Ácido fólico en dosis altas', 'Hidroxiurea, que aumenta la producción de hemoglobina fetal', 'Penicilina de por vida'], correct: 2, explanation: 'La hidroxiurea, que aumenta la producción de hemoglobina fetal (inhibiendo la polimerización de HbS), es el tratamiento modificador de la enfermedad de primera línea.', dificultad: 'facil' },
  { q: '¿Por qué se administra profilaxis antibiótica con penicilina desde la infancia temprana en la enfermedad de células falciformes?', options: ['Para prevenir la anemia', 'Por la asplenia funcional progresiva y el riesgo de sepsis por organismos encapsulados', 'Para prevenir el dolor de las crisis vaso-oclusivas', 'Para reducir la hemólisis crónica'], correct: 1, explanation: 'La profilaxis antibiótica previene la sepsis fulminante por organismos encapsulados, dado el riesgo elevado por la asplenia funcional progresiva.', dificultad: 'intermedio' },
  { q: '¿Cuál es la manifestación temprana característica de la crisis vaso-oclusiva en el lactante/niño pequeño?', options: ['Síndrome mano-pie (dactilitis)', 'Cefalea intensa aislada', 'Diarrea crónica', 'Pérdida de peso aislada'], correct: 0, explanation: 'El síndrome mano-pie (dactilitis) es una manifestación temprana característica de la crisis vaso-oclusiva en el lactante/niño pequeño.', dificultad: 'intermedio' },
  { q: '¿Cuál es un problema histórico reconocido en el manejo del dolor de la crisis vaso-oclusiva que debe evitarse activamente?', options: ['El uso excesivo de líquidos intravenosos', 'El uso excesivo de oxígeno suplementario', 'La hospitalización innecesaria', 'La administración tardía o insuficiente de analgésicos'], correct: 3, explanation: 'La administración tardía o insuficiente de analgésicos es un problema histórico reconocido que debe evitarse activamente en el manejo de la crisis vaso-oclusiva.', dificultad: 'dificil' },
  { q: '¿Cuáles son las causas fisiopatológicas del síndrome torácico agudo?', options: ['Únicamente infección bacteriana', 'Múltiples y con frecuencia superpuestas: infección, embolia grasa por infarto medular, infarto pulmonar in situ, e hipoventilación por dolor concomitante', 'Únicamente embolia grasa', 'Únicamente hipoventilación por dolor'], correct: 1, explanation: 'El síndrome torácico agudo tiene múltiples causas fisiopatológicas con frecuencia superpuestas.', dificultad: 'dificil' },
  { q: '¿Cuál es el estudio diagnóstico central del síndrome torácico agudo?', options: ['Electrocardiograma', 'Ecografía abdominal', 'Radiografía de tórax, buscando un nuevo infiltrado pulmonar', 'Punción lumbar'], correct: 2, explanation: 'La radiografía de tórax, buscando un nuevo infiltrado pulmonar junto con fiebre y/o síntomas respiratorios, es el estudio diagnóstico central del síndrome torácico agudo.', dificultad: 'facil' },
  { q: '¿Qué medida durante una crisis vaso-oclusiva con dolor torácico/abdominal ayuda a prevenir la progresión a síndrome torácico agudo?', options: ['Restricción hídrica agresiva', 'Sedación profunda', 'Reposo absoluto sin movilización', 'Espirometría incentivada activa, para prevenir la atelectasia que perpetúa el círculo vicioso'], correct: 3, explanation: 'La espirometría incentivada activa previene la atelectasia que perpetúa el círculo vicioso de hipoventilación y falciformación pulmonar.', dificultad: 'intermedio' },
  { q: '¿Cuál es el umbral de velocidad en el Doppler transcraneal considerado "anormal" y que indica transfusiones crónicas profilácticas?', options: ['≥200 cm/s (confirmado en 2 estudios)', '≥120 cm/s', '≥50 cm/s', '≥350 cm/s'], correct: 0, explanation: 'Una velocidad ≥200 cm/s confirmada en 2 estudios se considera anormal e indica el inicio de transfusiones crónicas profilácticas.', dificultad: 'intermedio' },
  { q: '¿Qué segmento vascular estenosa progresivamente en la vasculopatía de la enfermedad de células falciformes, detectable por Doppler transcraneal?', options: ['Las venas periféricas de las extremidades', 'La aorta abdominal', 'Las grandes arterias intracraneales (particularmente la arteria carótida interna distal y la arteria cerebral media proximal)', 'Las arterias coronarias exclusivamente'], correct: 2, explanation: 'Las grandes arterias intracraneales, particularmente la carótida interna distal y la cerebral media proximal, estenosan progresivamente y son detectables por Doppler transcraneal.', dificultad: 'intermedio' },
  { q: '¿Por qué el adulto con enfermedad de células falciformes tiene proporcionalmente mayor riesgo de hemorragia intracraneal que el niño?', options: ['Por el uso crónico de anticoagulantes', 'Por la fragilidad de los vasos colaterales desarrollados en respuesta a la estenosis crónica (patrón similar a moyamoya)', 'Por la hipertensión arterial exclusivamente', 'No hay diferencia real entre adultos y niños'], correct: 1, explanation: 'La fragilidad de los vasos colaterales desarrollados en respuesta a la estenosis crónica (patrón similar a moyamoya) contribuye al mayor riesgo hemorrágico en el adulto.', dificultad: 'dificil' },
  { q: '¿Qué son los "infartos silentes" en la enfermedad de células falciformes?', options: ['Hallazgos incidentales en resonancia magnética sin correlato clínico focal evidente, pero asociados a deterioro cognitivo medible', 'Infartos que nunca se detectan por ningún método', 'Sinónimo de evento cerebrovascular clínico manifiesto', 'Un hallazgo exclusivo del adulto mayor'], correct: 0, explanation: 'Los infartos silentes son hallazgos incidentales en resonancia magnética sin déficit focal evidente, pero asociados a deterioro cognitivo medible.', dificultad: 'intermedio' },
  { q: '¿Qué es el secuestro esplénico agudo?', options: ['Aumento crónico y lento del tamaño esplénico sin repercusión hemodinámica', 'Sinónimo de asplenia funcional completa', 'Un hallazgo exclusivo del adulto con enfermedad de células falciformes', 'Caída aguda y brusca de la hemoglobina con esplenomegalia dolorosa, potencialmente fatal en el niño pequeño'], correct: 3, explanation: 'El secuestro esplénico agudo es una caída aguda y brusca de la hemoglobina con esplenomegalia dolorosa, una urgencia pediátrica potencialmente fatal antes de que se complete la autoesplenectomía.', dificultad: 'intermedio' },
  { q: '¿Por qué la fiebre en un niño con enfermedad de células falciformes debe considerarse potencialmente grave hasta demostrar lo contrario?', options: ['Porque siempre indica una crisis vaso-oclusiva', 'Porque nunca requiere evaluación médica', 'Por el riesgo de sepsis fulminante por organismos encapsulados dada la asplenia funcional', 'Porque siempre indica síndrome torácico agudo'], correct: 2, explanation: 'La fiebre debe considerarse potencialmente grave por el riesgo de sepsis fulminante por organismos encapsulados dada la asplenia funcional.', dificultad: 'facil' },
  { q: '¿Cuál es la complicación crónica particularmente elevada en la HbSC (a diferencia de la HbSS)?', options: ['Talasemia mayor concomitante', 'Necrosis avascular y retinopatía proliferativa', 'Hidropesía fetal', 'Deficiencia de hierro'], correct: 1, explanation: 'La HbSC tiene un riesgo particularmente elevado de necrosis avascular (especialmente de cadera) y de retinopatía proliferativa.', dificultad: 'intermedio' },
  { q: '¿En qué circunstancia extrema puede el portador de rasgo falciforme (HbAS), generalmente asintomático, tener falciformación clínicamente relevante?', options: ['Nunca ocurre bajo ninguna circunstancia', 'Solo durante el sueño', 'Solo con la ingesta de alimentos ricos en hierro', 'Ejercicio físico extenuante, deshidratación extrema, o gran altitud'], correct: 3, explanation: 'El portador de rasgo falciforme puede tener falciformación clínicamente relevante en condiciones de hipoxia extrema: ejercicio extenuante, deshidratación extrema, o gran altitud.', dificultad: 'dificil' },
  { q: '¿Qué es el priapismo prolongado en la enfermedad de células falciformes y por qué es una urgencia?', options: ['Erección dolorosa sostenida por oclusión del drenaje venoso peneano; requiere manejo urgente para prevenir daño tisular permanente', 'Un hallazgo benigno que se resuelve espontáneamente sin tratamiento', 'Sinónimo de disfunción eréctil crónica', 'Exclusivo del paciente con talasemia mayor'], correct: 0, explanation: 'El priapismo prolongado es una erección dolorosa sostenida por oclusión del drenaje venoso peneano, una urgencia urológica que requiere manejo inmediato para prevenir daño tisular permanente.', dificultad: 'intermedio' },
  { q: '¿Cuál es el mecanismo de la colelitiasis frecuente en las hemoglobinopatías con hemólisis crónica?', options: ['Deficiencia de hierro asociada', 'Uso crónico de quelantes de hierro', 'Exceso crónico de bilirrubina de la hemólisis, formando cálculos de pigmento biliar', 'Deficiencia de vitamina B12'], correct: 2, explanation: 'El exceso crónico de bilirrubina de la hemólisis forma cálculos de pigmento biliar, produciendo colelitiasis frecuente en las hemoglobinopatías hemolíticas crónicas.', dificultad: 'intermedio' },
  { q: '¿Qué prueba de laboratorio es diagnóstica definitiva para establecer el tipo específico de hemoglobinopatía?', options: ['Electroforesis de hemoglobina (o HPLC)', 'Biometría hemática aislada', 'Velocidad de sedimentación globular', 'Perfil de hierro aislado'], correct: 0, explanation: 'La electroforesis de hemoglobina (o HPLC) es la prueba diagnóstica definitiva que cuantifica las fracciones de hemoglobina y establece el diagnóstico específico.', dificultad: 'facil' },
  { q: '¿Qué medida preventiva reproductiva es relevante en parejas donde ambos son portadores de hemoglobinopatías compatibles?', options: ['Ninguna medida es necesaria', 'Suspender toda planificación familiar de forma permanente', 'Iniciar quimioterapia profiláctica antes del embarazo', 'Consejo genético para estimar el riesgo en la descendencia'], correct: 3, explanation: 'El consejo genético es la medida preventiva relevante en parejas donde ambos son portadores de hemoglobinopatías compatibles, para estimar el riesgo en la descendencia.', dificultad: 'facil' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Niño de 3 años con enfermedad de células falciformes (HbSS) conocida presenta palidez marcada de instauración rápida, distensión abdominal dolorosa, y esplenomegalia palpable nueva de 6 cm bajo el reborde costal. Hemoglobina de 4.5 g/dL (basal habitual 8 g/dL).',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable dado este cuadro?', options: ['Secuestro esplénico agudo', 'Síndrome torácico agudo', 'Crisis aplásica por parvovirus', 'Priapismo'], correct: 0 },
      { q: '¿Cuál es el manejo inmediato más apropiado?', options: ['Observación domiciliaria sin intervención', 'Reanimación con líquidos y transfusión urgente, con hospitalización', 'Iniciar hidroxiurea de inmediato', 'Alta con analgésicos orales únicamente'], correct: 1 },
      { q: '¿Qué medida preventiva es relevante tras la resolución de este episodio, dado el riesgo de recurrencia?', options: ['Ninguna medida adicional es necesaria', 'Suspender todo seguimiento médico', 'Educación familiar sobre palpación esplénica domiciliaria para detección temprana de recurrencias', 'Iniciar quimioterapia profiláctica'], correct: 2 }
    ],
    explanation: 'La esplenomegalia dolorosa aguda con caída brusca de hemoglobina en un niño pequeño con enfermedad de células falciformes es característica de secuestro esplénico agudo, una urgencia pediátrica. El manejo inmediato es reanimación con líquidos y transfusión urgente. Tras la resolución, la educación familiar sobre palpación esplénica domiciliaria ayuda a detectar recurrencias tempranamente.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 24 años con enfermedad de células falciformes es hospitalizada por crisis vaso-oclusiva dolorosa lumbar. A las 36 horas desarrolla fiebre, dolor torácico, y taquipnea. La radiografía de tórax muestra un nuevo infiltrado en el lóbulo inferior derecho.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable?', options: ['Neumotórax espontáneo', 'Embolia pulmonar aislada sin relación', 'Síndrome torácico agudo', 'Ansiedad aguda'], correct: 2 },
      { q: '¿Cuál es el manejo inicial más apropiado?', options: ['Oxígeno suplementario + antibiótico empírico de amplio espectro + hidratación cuidadosa evitando sobrecarga', 'Alta inmediata sin más evaluación', 'Restricción absoluta de líquidos sin oxígeno', 'Observación sin ninguna intervención activa'], correct: 0 },
      { q: '¿Qué medida adicional debe implementarse activamente dado el dolor lumbar concomitante que limita la ventilación?', options: ['Sedación profunda para reducir el dolor', 'Restricción total de analgésicos', 'Reposo absoluto sin ninguna movilización', 'Espirometría incentivada activa, para prevenir la atelectasia que perpetúa el cuadro'], correct: 3 }
    ],
    explanation: 'La fiebre, dolor torácico y nuevo infiltrado tras una crisis vaso-oclusiva son característicos de síndrome torácico agudo. El manejo inicial incluye oxígeno, antibiótico empírico e hidratación cuidadosa. La espirometría incentivada activa es clave dado el dolor lumbar concomitante que limita la ventilación, para prevenir el círculo vicioso de atelectasia y más falciformación pulmonar.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Niño de 4 años con enfermedad de células falciformes (HbSS) acude a su Doppler transcraneal de cribado anual. La velocidad media temporal máxima en la arteria cerebral media es de 210 cm/s.',
    steps: [
      { q: '¿Cómo se clasifica este resultado según la herramienta de Doppler transcraneal?', options: ['Normal', 'Anormal', 'Condicional', 'No interpretable'], correct: 1 },
      { q: '¿Qué paso sigue inmediatamente tras este resultado inicial?', options: ['Ignorar el resultado hasta el próximo control anual', 'Iniciar quimioterapia de inmediato', 'Indicar trasplante de médula ósea de inmediato sin más estudio', 'Confirmar el resultado con un segundo estudio antes de tomar la decisión terapéutica definitiva'], correct: 3 },
      { q: 'El segundo estudio confirma la velocidad anormal. ¿Cuál es la conducta terapéutica indicada?', options: ['Iniciar transfusiones crónicas profilácticas para reducir el riesgo de un primer evento cerebrovascular', 'No hacer ningún cambio en el manejo actual', 'Suspender la hidroxiurea si la estaba recibiendo', 'Indicar reposo absoluto sin más intervención'], correct: 0 }
    ],
    explanation: 'Una velocidad ≥200 cm/s se clasifica como anormal. Antes de la decisión terapéutica definitiva, debe confirmarse con un segundo estudio. Confirmada la velocidad anormal, la conducta indicada es iniciar transfusiones crónicas profilácticas para reducir el riesgo de un primer evento cerebrovascular clínico.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Recién nacido con tamizaje neonatal positivo para hemoglobinopatía. La electroforesis de hemoglobina confirma HbSS. Los padres preguntan sobre el manejo inicial recomendado.',
    steps: [
      { q: '¿Qué medida preventiva debe iniciarse desde la infancia temprana en este paciente?', options: ['Profilaxis antibiótica con penicilina y vacunación completa (incluida neumocócica)', 'Ninguna medida especial, dado que el niño está asintomático al nacer', 'Quimioterapia profiláctica inmediata', 'Trasplante de médula ósea inmediato sin más evaluación'], correct: 0 },
      { q: '¿A partir de qué edad debe iniciarse el cribado sistemático con Doppler transcraneal?', options: ['Al nacer, de inmediato', 'Solo tras el primer evento neurológico', 'Desde los 2 años de edad, de forma anual', 'A partir de los 18 años'], correct: 2 },
      { q: '¿Qué terapia modificadora de la enfermedad debe considerarse como primera línea conforme el niño crece?', options: ['Deferoxamina', 'Hidroxiurea, dado que aumenta la producción de hemoglobina fetal', 'Antibiótico de amplio espectro continuo', 'Quimioterapia citotóxica convencional'], correct: 1 }
    ],
    explanation: 'Confirmado el diagnóstico de HbSS por tamizaje neonatal, debe iniciarse profilaxis antibiótica con penicilina y vacunación completa desde la infancia temprana. El Doppler transcraneal de cribado anual se inicia desde los 2 años de edad. La hidroxiurea es la terapia modificadora de la enfermedad de primera línea conforme el niño crece.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Pareja joven acude a consulta preconcepcional. Ambos son de ascendencia mediterránea. El estudio revela que ambos son portadores del rasgo de talasemia beta (heterocigotos), asintomáticos, con microcitosis leve incidental conocida desde hace años.',
    steps: [
      { q: '¿Qué riesgo tiene la descendencia de esta pareja dado que ambos son portadores del rasgo de talasemia beta?', options: ['Ningún riesgo adicional, dado que ambos son asintomáticos', 'Riesgo exclusivo de enfermedad de células falciformes', 'Riesgo de hidropesía fetal por hemoglobina de Bart', 'Riesgo de que un hijo herede ambos genes afectados y desarrolle talasemia mayor o intermedia'], correct: 3 },
      { q: '¿Qué medida es apropiada ofrecer a esta pareja antes o durante el embarazo?', options: ['Ninguna medida adicional, dado que ambos son solo portadores', 'Consejo genético reproductivo, con la opción de diagnóstico prenatal si lo desean', 'Iniciar quimioterapia profiláctica preconcepcional', 'Indicar esterilización permanente'], correct: 1 },
      { q: 'Si el feto resulta afectado con talasemia mayor, ¿cuál sería el manejo esperado tras el nacimiento?', options: ['Ningún manejo especial es necesario al nacer', 'Observación sin ninguna intervención hasta la adultez', 'Programa de transfusión regular con quelación de hierro sistemática desde el diagnóstico, con evaluación de trasplante alogénico si hay donante disponible', 'Esplenectomía inmediata al nacer sin más manejo'], correct: 2 }
    ],
    explanation: 'Ambos progenitores portadores del rasgo de talasemia beta tienen riesgo de que su descendencia herede ambos genes afectados y desarrolle talasemia mayor o intermedia. El consejo genético reproductivo, con opción de diagnóstico prenatal, es apropiado. Si el feto resulta afectado con talasemia mayor, el manejo tras el nacimiento incluye un programa de transfusión regular con quelación de hierro sistemática, evaluando trasplante alogénico si hay donante disponible.'
  }
];

export const flashcards = [
  { front: 'Talasemias vs. enfermedad de células falciformes', back: 'Talasemias: defecto cuantitativo (déficit de producción). ECF: defecto cualitativo (cadena anómala en cantidad normal).' },
  { front: 'Genes de globina alfa', back: '4 copias (2 en cada cromosoma 16).' },
  { front: 'Pérdida de 3 genes de globina alfa', back: 'Enfermedad de HbH, anemia hemolítica moderada.' },
  { front: 'Pérdida de 4 genes de globina alfa', back: 'Hidropesía fetal por HbBart, generalmente incompatible con la vida sin tratamiento intrauterino.' },
  { front: 'Genes de globina beta', back: '2 copias (1 en cada cromosoma 11).' },
  { front: 'Hallazgo clave en electroforesis del rasgo de talasemia beta', back: 'HbA2 elevada.' },
  { front: 'Pilar del tratamiento a largo plazo en talasemia mayor', back: 'Quelación de hierro sistemática (previene la principal causa de morbimortalidad tardía).' },
  { front: 'Única opción curativa de la talasemia mayor', back: 'Trasplante alogénico de células madre hematopoyéticas.' },
  { front: 'Mutación de la hemoglobina S', back: 'Sustitución puntual (ácido glutámico por valina) en la cadena beta.' },
  { front: 'Condición que favorece la polimerización de HbS', back: 'La desoxigenación.' },
  { front: 'Motivo de consulta más frecuente en ECF', back: 'Crisis vaso-oclusiva dolorosa.' },
  { front: 'Tratamiento modificador de primera línea en ECF', back: 'Hidroxiurea (aumenta hemoglobina fetal).' },
  { front: 'Por qué profilaxis con penicilina desde la infancia en ECF', back: 'Asplenia funcional progresiva → riesgo de sepsis por organismos encapsulados.' },
  { front: 'Manifestación temprana de crisis vaso-oclusiva en el niño pequeño', back: 'Síndrome mano-pie (dactilitis).' },
  { front: 'Problema histórico en el manejo del dolor de crisis VOC', back: 'Analgesia tardía o insuficiente; debe evitarse activamente.' },
  { front: 'Causas del síndrome torácico agudo', back: 'Múltiples y superpuestas: infección, embolia grasa, infarto pulmonar in situ, hipoventilación por dolor.' },
  { front: 'Estudio diagnóstico central del síndrome torácico agudo', back: 'Radiografía de tórax (nuevo infiltrado).' },
  { front: 'Medida para prevenir progresión a síndrome torácico agudo', back: 'Espirometría incentivada activa durante crisis con dolor torácico/abdominal.' },
  { front: 'Umbral TCD "anormal"', back: '≥200 cm/s (confirmado en 2 estudios) → transfusiones crónicas profilácticas.' },
  { front: 'Segmento vascular estenosado en la vasculopatía de ECF', back: 'Carótida interna distal y cerebral media proximal.' },
  { front: 'Por qué mayor riesgo hemorrágico en el adulto con ECF', back: 'Fragilidad de vasos colaterales (patrón tipo moyamoya).' },
  { front: 'Infartos silentes', back: 'Hallazgo incidental en RM sin déficit focal, pero con deterioro cognitivo asociado.' },
  { front: 'Secuestro esplénico agudo', back: 'Caída aguda de Hb con esplenomegalia dolorosa; urgencia pediátrica antes de la autoesplenectomía.' },
  { front: 'HbSC: complicaciones características', back: 'Necrosis avascular (cadera) y retinopatía proliferativa, riesgo particularmente elevado.' },
  { front: 'Priapismo prolongado', back: 'Urgencia urológica (&gt;4h); riesgo de daño tisular permanente sin manejo inmediato.' },
  { front: 'Mecanismo de la colelitiasis en hemoglobinopatías hemolíticas', back: 'Exceso crónico de bilirrubina → cálculos de pigmento biliar.' },
  { front: 'Prueba diagnóstica definitiva de hemoglobinopatías', back: 'Electroforesis de hemoglobina (o HPLC).' }
];
