// topics/sindrome-aortico-agudo/study.js: Autoevaluación de Síndrome Aórtico Agudo.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Nota de método (ver memoria del proyecto): todas las preguntas se escribieron primero con la
// respuesta correcta en options[0]/correct:0 (trivialmente verificable), y luego se redistribuyó
// la posición de `correct` mecánicamente con un script, sin volver a adivinar cuál texto es el
// correcto. Cada pregunta se releyó completa (options+correct+explanation) tras la
// redistribución para confirmar que options[correct] es realmente la respuesta correcta.

export const quiz = [
  { q: '¿Cuáles son las 3 entidades agudas que conforman el síndrome aórtico agudo?', options: ['Infarto agudo, tromboembolia y neumotórax', 'Aneurisma torácico, abdominal y poplíteo', 'Disección, hematoma intramural y úlcera', 'Pericarditis, miocarditis y endocarditis'], correct: 2, explanation: 'El síndrome aórtico agudo agrupa la disección aórtica, el hematoma intramural aórtico, y la úlcera aórtica penetrante.', dificultad: 'facil' },
  { q: '¿Qué determina fundamentalmente si el manejo de cualquiera de las 3 entidades agudas es quirúrgico urgente o médico?', options: ['El tipo específico de entidad aguda', 'La edad del paciente al diagnóstico', 'El sexo biológico del paciente', 'La clasificación Stanford A/B'], correct: 3, explanation: 'La clasificación Stanford A/B, según si se compromete la aorta ascendente o solo la descendente, determina el manejo quirúrgico urgente vs. médico, independientemente del tipo específico de lesión.', dificultad: 'facil' },
  { q: '¿Cuál es el factor de riesgo más frecuente para las 4 entidades de este tema?', options: ['Hipertensión arterial no controlada', 'Deficiencia crónica de vitamina D', 'Hipotiroidismo primario no tratado', 'Anemia ferropénica crónica'], correct: 0, explanation: 'La hipertensión arterial no controlada es el factor de riesgo más frecuente para las 4 entidades de este tema.', dificultad: 'facil' },
  { q: '¿Cómo se describe característicamente el dolor de la disección aórtica, a diferencia del síndrome coronario agudo?', options: ['Progresivo, opresivo, en aumento gradual', 'Desgarrante y súbito, máximo al inicio', 'Ausente en la gran mayoría de los casos', 'Localizado solo en el brazo izquierdo'], correct: 1, explanation: 'El dolor de la disección aórtica es desgarrante, de inicio súbito, con máxima intensidad desde el comienzo, a diferencia del síndrome coronario agudo que típicamente es progresivo.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo de exploración física sugiere fuertemente disección aórtica?', options: ['Presión arterial idéntica en los brazos', 'Una exploración física del todo normal', 'Déficit de pulso o asimetría >20 mmHg', 'Reflejos osteotendinosos exaltados'], correct: 2, explanation: 'El déficit de pulso o una diferencia de presión arterial mayor de 20 mmHg entre extremidades sugiere fuertemente disección aórtica.', dificultad: 'intermedio' },
  { q: '¿Cuál es el manejo de la disección aórtica Stanford A?', options: ['Manejo médico exclusivo, sin cirugía', 'Cirugía urgente, sin demora', 'Observación domiciliaria, sin tratar', 'Anticoagulación como único tratamiento'], correct: 1, explanation: 'La disección Stanford A requiere cirugía urgente sin demora, dado que la mortalidad aumenta considerablemente con cada hora de retraso.', dificultad: 'facil' },
  { q: '¿Cuál es el manejo de la disección aórtica Stanford B no complicada?', options: ['Cirugía urgente, igual que en Stanford A', 'No hace falta tratamiento en absoluto', 'Trasplante aórtico inmediato urgente', 'Médico: control de frecuencia y presión'], correct: 3, explanation: 'La disección Stanford B no complicada se maneja médicamente con control estricto de frecuencia cardiaca y presión arterial.', dificultad: 'facil' },
  { q: '¿Por qué se administra un betabloqueador ANTES que un vasodilatador en el control farmacológico de la disección aórtica?', options: ['Evita la taquicardia refleja y el cizallamiento', 'Los vasodilatadores están del todo contraindicados', 'El betabloqueador no baja la frecuencia cardiaca', 'El orden de administración es irrelevante'], correct: 0, explanation: 'Un vasodilatador administrado antes que el betabloqueador produciría taquicardia refleja que aumentaría el estrés de cizallamiento (dP/dt) sobre la pared aórtica, por lo que el betabloqueador se administra primero.', dificultad: 'dificil' },
  { q: '¿Qué distingue mecánicamente al hematoma intramural aórtico de la disección aórtica clásica?', options: ['El hematoma muestra una doble luz visible', 'No hay desgarro: rotura de vasa vasorum', 'El hematoma no progresa a disección franca', 'Ambas entidades son mecánicamente idénticas'], correct: 1, explanation: 'El hematoma intramural se origina por rotura de los vasa vasorum sin un desgarro de la íntima identificable, a diferencia de la disección clásica.', dificultad: 'intermedio' },
  { q: '¿Cuál es el hallazgo característico del hematoma intramural aórtico en la angio-TC?', options: ['Engrosamiento en semiluna, sin doble luz', 'Doble luz con colgajo de íntima realzado', 'Un nicho ulceroso sobre placa ateromatosa', 'Ausencia de cualquier hallazgo anormal'], correct: 0, explanation: 'El hematoma intramural muestra un engrosamiento hiperdenso en semiluna de la pared, sin realce con contraste y sin colgajo de íntima ni doble luz.', dificultad: 'intermedio' },
  { q: '¿Cómo se clasifica y maneja el hematoma intramural aórtico en comparación con la disección clásica?', options: ['Solo con manejo médico, sin cirugía', 'Cirugía urgente para cualquier tipo', 'No hay esquema de clasificación aplicable', 'Igual que Stanford: A cirugía, B médico'], correct: 3, explanation: 'El hematoma intramural se clasifica y maneja con el mismo esquema Stanford A/B que la disección clásica.', dificultad: 'intermedio' },
  { q: '¿Sobre qué sustrato se origina característicamente la úlcera aórtica penetrante?', options: ['Una enfermedad genética del tejido conectivo', 'Una infección bacteriana directa de la pared', 'Una placa ateroesclerótica ulcerada', 'Una malformación congénita de nacimiento'], correct: 2, explanation: 'La úlcera aórtica penetrante se origina sobre una placa ateroesclerótica ulcerada que penetra la lámina elástica interna hacia la media.', dificultad: 'facil' },
  { q: '¿En qué población ocurre característicamente la úlcera aórtica penetrante?', options: ['El paciente joven con síndrome de Marfan', 'El anciano con ateroesclerosis difusa', 'La mujer embarazada en el tercer trimestre', 'El paciente sin factores de riesgo'], correct: 1, explanation: 'La úlcera aórtica penetrante ocurre característicamente en el paciente de edad avanzada con ateroesclerosis aórtica difusa.', dificultad: 'facil' },
  { q: '¿Cuál es la modalidad de reparación preferida para la úlcera aórtica penetrante sintomática, dado el perfil típico del paciente?', options: ['Reparación endovascular', 'Cirugía abierta, no endovascular', 'No hay tratamiento disponible', 'Trasplante aórtico completo'], correct: 0, explanation: 'La reparación endovascular se prefiere sobre la cirugía abierta en la úlcera aórtica penetrante sintomática, dado que el paciente típico tiene múltiples comorbilidades ateroscleróticas.', dificultad: 'intermedio' },
  { q: '¿En qué población se recomienda el tamizaje con ecografía abdominal para aneurisma aórtico abdominal?', options: ['Mujeres de cualquier edad, sin riesgo', 'Solo pacientes menores de 40 años de edad', 'Varones de 65-75 años que fumaron', 'No hay recomendación de tamizaje alguna'], correct: 2, explanation: 'El tamizaje con ecografía abdominal está recomendado en varones de 65-75 años que hayan fumado alguna vez.', dificultad: 'facil' },
  { q: '¿Cuál es el umbral de diámetro habitual para la reparación electiva de un aneurisma aórtico abdominal en varones?', options: ['Un diámetro ≥2.0 cm', 'Un diámetro ≥10.0 cm', 'Un diámetro ≥3.0 cm', 'Un diámetro ≥5.5 cm'], correct: 3, explanation: 'El umbral habitual para la reparación electiva del aneurisma abdominal en varones es ≥5.5 cm (≥5.0 cm en mujeres).', dificultad: 'intermedio' },
  { q: '¿Qué indica un crecimiento del aneurisma &gt;0.5 cm en 6 meses, independientemente del diámetro absoluto?', options: ['No tiene relevancia si el diámetro es bajo', 'Indica que el aneurisma se está resolviendo', 'Indicación de reparación por el riesgo', 'Es un hallazgo esperado, sin más acción'], correct: 2, explanation: 'Un crecimiento &gt;0.5 cm en 6 meses es indicación de reparación independientemente del diámetro absoluto, dado el riesgo de rotura asociado.', dificultad: 'intermedio' },
  { q: '¿Qué distingue a la rotura aórtica "contenida" de la rotura hacia una cavidad libre?', options: ['Da una ventana breve para intervenir', 'Ambas tienen el mismo pronóstico inmediato', 'La contenida no requiere intervención', 'La libre tiene mejor pronóstico que la otra'], correct: 0, explanation: 'La rotura contenida transitoriamente ofrece una ventana breve para intervenir antes del colapso franco, a diferencia de la rotura hacia una cavidad libre, donde la exanguinación es habitualmente rápida.', dificultad: 'intermedio' },
  { q: '¿Qué estrategia de presión arterial se recomienda mientras se organiza la reparación urgente de una rotura aórtica?', options: ['Hipertensión inducida de forma agresiva', 'No hace falta controlar la presión arterial', 'Anticoagulación terapéutica inmediata', 'Hipotensión permisiva'], correct: 3, explanation: 'Se recomienda hipotensión permisiva, evitando tanto la hipertensión (que agrava el sangrado) como la hipoperfusión excesiva de órganos, mientras se organiza la reparación definitiva.', dificultad: 'dificil' },
  { q: '¿Cuál es el mecanismo del taponamiento cardiaco en la disección aórtica?', options: ['Una infección pericárdica no relacionada', 'La tipo A rompe hacia el pericardio', 'Compresión externa por un tumor mediastínico', 'Un mecanismo igual al de la pericarditis viral'], correct: 1, explanation: 'El taponamiento en la disección resulta de la extensión retrógrada de la disección tipo A hacia la raíz aórtica, con rotura hacia el espacio pericárdico.', dificultad: 'intermedio' },
  { q: '¿Qué componentes conforman la tríada de Beck del taponamiento cardiaco?', options: ['Fiebre, rigidez de nuca y fotofobia intensa', 'Hipertensión, bradicardia y respiración irregular', 'Hipotensión, yugulares y ruidos velados', 'Cefalea, vómito y papiledema bilateral'], correct: 2, explanation: 'La tríada de Beck consiste en hipotensión, ingurgitación yugular, y ruidos cardiacos velados/apagados.', dificultad: 'facil' },
  { q: '¿Por qué se evita la pericardiocentesis como tratamiento aislado de rutina en el taponamiento por disección tipo A?', options: ['La pericardiocentesis resulta inefectiva', 'No hay riesgo asociado al procedimiento', 'La pericardiocentesis cura la disección', 'El alivio brusco agrava el sangrado'], correct: 3, explanation: 'El alivio brusco de la presión pericárdica por pericardiocentesis puede precipitar un aumento súbito de la presión arterial y agravar el sangrado activo hacia el pericardio, por lo que se prefiere proceder directamente a cirugía.', dificultad: 'dificil' },
  { q: '¿Cuál es la diferencia entre la malperfusión dinámica y la malperfusión estática de una rama aórtica?', options: ['Dinámica: comprime la luz; estática: ocluye', 'Ambos mecanismos son idénticos entre sí', 'La estática se resuelve sola, sin intervenir', 'La dinámica no fluctúa con el tiempo'], correct: 0, explanation: 'La malperfusión dinámica es por compresión de la falsa luz expandida sobre la verdadera (puede fluctuar); la estática es por oclusión directa y fija del ostium de la rama por el plano de disección.', dificultad: 'dificil' },
  { q: '¿Cuál de los territorios de malperfusión es el más devastador y menos reversible una vez establecido?', options: ['El territorio cutáneo', 'Medular (paraplejia)', 'El mesentérico, reversible', 'Todos tienen igual gravedad'], correct: 1, explanation: 'La malperfusión medular (paraplejia) es la más devastadora y menos reversible de los territorios de malperfusión una vez establecida.', dificultad: 'intermedio' },
  { q: '¿Cuál es la prioridad de manejo ante malperfusión de una rama aórtica por disección?', options: ['Intervenir primero sobre la rama afectada', 'No tratar si el paciente está estable', 'Anticoagulación exclusiva, sin mecánica', 'Corregir el flujo aórtico central'], correct: 3, explanation: 'La prioridad es corregir el flujo aórtico central, dado que con frecuencia restaura el flujo a la rama comprometida sin necesidad de una intervención separada sobre esa rama.', dificultad: 'intermedio' },
  { q: '¿Por qué el ventrículo izquierdo no tolera bien el volumen regurgitante en la insuficiencia aórtica AGUDA, a diferencia de la crónica?', options: ['No está dilatado ni remodelado aún', 'Está dilatado, igual que en la crónica', 'La forma aguda no produce síntomas', 'El mecanismo es idéntico en las dos formas'], correct: 0, explanation: 'En la forma aguda, el ventrículo izquierdo no está dilatado ni remodelado (a diferencia de la crónica, con adaptación compensadora), por lo que no tolera el volumen regurgitante súbito y desarrolla edema pulmonar rápidamente.', dificultad: 'dificil' },
  { q: '¿Cuáles son los 3 mecanismos por los que la disección tipo A puede producir insuficiencia aórtica aguda?', options: ['Solo por infección de las cúspides valvulares', 'Solo por calcificación degenerativa previa', 'Dilatación del anillo, comisura o colgajo', 'La disección no llega a afectar la válvula'], correct: 2, explanation: 'La disección tipo A puede producir insuficiencia aórtica aguda por dilatación del anillo, desprendimiento de una comisura, o un colgajo de íntima que prolapsa a través del orificio valvular.', dificultad: 'dificil' },
  { q: '¿Cuál es el manejo definitivo de la insuficiencia aórtica aguda por disección tipo A?', options: ['Manejo médico con diuréticos, sin cirugía', 'Cirugía urgente con reparación valvular', 'Observación ambulatoria, sin tratamiento', 'Trasplante cardiaco de urgencia inmediato'], correct: 1, explanation: 'El manejo definitivo es la cirugía urgente de la disección con reparación o reemplazo valvular en el mismo procedimiento, según el mecanismo y la reparabilidad de la válvula.', dificultad: 'intermedio' },
  { q: '¿Qué 3 categorías conforman el score ADD-RS?', options: ['Edad, sexo y peso corporal del paciente', 'Presión arterial, frecuencia y temperatura', 'Condiciones, dolor y exploración de riesgo', 'Hemoglobina, plaquetas y leucocitos totales'], correct: 2, explanation: 'El ADD-RS combina condiciones de alto riesgo, características del dolor de alto riesgo, y hallazgos de exploración de alto riesgo, 1 punto por categoría.', dificultad: 'facil' },
  { q: '¿Qué se recomienda ante un ADD-RS de 2 o más puntos?', options: ['Observación domiciliaria, sin estudio', 'Esperar el dímero D antes de la imagen', 'Descartar el diagnóstico, sin imagen alguna', 'Imagen urgente, sin esperar dímero D'], correct: 3, explanation: 'Un ADD-RS ≥2 indica riesgo alto, por lo que se recomienda imagen urgente sin demora, sin esperar el resultado del dímero D.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 58 años con hipertensión mal controlada presenta dolor torácico desgarrante de inicio súbito que migró hacia la espalda. Presión arterial 160/95 en brazo derecho, 120/70 en brazo izquierdo.',
    steps: [
      { q: 'Con este cuadro y la diferencia de presión arterial entre brazos, ¿qué diagnóstico se debe sospechar de inmediato?', options: ['Síndrome aórtico agudo', 'Reflujo gastroesofágico', 'Costocondritis costal', 'Neumonía de la comunidad'], correct: 0, explanation: 'El dolor desgarrante de inicio súbito que migra, junto con la diferencia de presión arterial entre brazos, sugiere fuertemente un síndrome aórtico agudo.' },
      { q: '¿Qué estudio debe solicitarse de inmediato, sin retrasarse por otros estudios de menor rendimiento?', options: ['Radiografía de tórax, y nada más', 'Angio-TC de aorta completa urgente', 'Prueba de esfuerzo la próxima semana', 'Endoscopia digestiva alta urgente'], correct: 1, explanation: 'La angio-TC de aorta completa es el estudio de elección y debe solicitarse de inmediato ante la sospecha clínica alta.' },
      { q: 'La angio-TC confirma disección que compromete la aorta ascendente. ¿Cuál es la clasificación y el manejo correspondiente?', options: ['Stanford B, manejo médico exclusivo', 'No requiere clasificación ni tratamiento específico', 'Stanford A, cirugía urgente sin demora', 'Observación ambulatoria con control en 1 semana'], correct: 2, explanation: 'El compromiso de la aorta ascendente corresponde a Stanford A, que requiere cirugía urgente sin demora dado que la mortalidad aumenta por hora.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 71 años con disección Stanford A confirmada desarrolla hipotensión súbita, ingurgitación yugular marcada, y ruidos cardiacos apagados durante la espera para cirugía.',
    steps: [
      { q: '¿Qué complicación se debe sospechar dado este cuadro?', options: ['Neumotórax a tensión no relacionado', 'Taponamiento por extensión retrógrada', 'Embolia pulmonar masiva concomitante', 'Reacción alérgica al medio de contraste'], correct: 1, explanation: 'La combinación de hipotensión, ingurgitación yugular, y ruidos velados (tríada de Beck) en una disección tipo A sugiere taponamiento por extensión retrógrada hacia el pericardio.' },
      { q: '¿Cuál es el manejo apropiado de esta complicación?', options: ['Líquidos como puente y cirugía urgente', 'Pericardiocentesis aislada, definitiva', 'Observación, sin intervención alguna', 'Anticoagulación terapéutica inmediata'], correct: 0, explanation: 'La reanimación con líquidos es solo un puente temporal; el tratamiento definitivo es la cirugía urgente de la disección subyacente, evitando la pericardiocentesis aislada de rutina.' },
      { q: '¿Por qué se evita la pericardiocentesis como tratamiento aislado en este contexto específico?', options: ['La pericardiocentesis es del todo segura', 'No hay riesgo alguno en este escenario', 'Resuelve por sí sola la disección', 'El alivio brusco reactiva el sangrado'], correct: 3, explanation: 'El alivio brusco de la presión pericárdica puede precipitar un aumento súbito de la presión arterial y agravar el sangrado activo hacia el pericardio en el contexto de disección tipo A.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 64 años con disección aórtica tipo B en tratamiento médico desarrolla dolor abdominal intenso desproporcionado al examen físico, 6 horas después del diagnóstico inicial.',
    steps: [
      { q: '¿Qué complicación se debe sospechar dado este nuevo síntoma?', options: ['Progresión esperada, sin complicación', 'Una reacción adversa al betabloqueador', 'Malperfusión mesentérica de la disección', 'Una gastritis aguda no relacionada'], correct: 2, explanation: 'El dolor abdominal desproporcionado al examen en un paciente con disección aórtica sugiere malperfusión mesentérica por compromiso de una rama visceral.' },
      { q: '¿Qué estudio de laboratorio apoya la sospecha de isquemia mesentérica en evolución?', options: ['Lactato sérico elevado', 'Hemoglobina A1c', 'Perfil lipídico en ayuno', 'Hormona estimulante de tiroides'], correct: 0, explanation: 'El lactato sérico elevado apoya la sospecha de isquemia mesentérica progresando hacia infarto intestinal.' },
      { q: '¿Cuál es la prioridad de manejo ante esta malperfusión mesentérica?', options: ['Operar el intestino sin tocar la aorta', 'Observación, sin intervención alguna', 'Anticoagulación como único tratamiento', 'Corregir el flujo aórtico central'], correct: 3, explanation: 'La prioridad es corregir el flujo aórtico central (quirúrgico o endovascular), que con frecuencia restaura el flujo a la rama mesentérica comprometida.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 70 años, exfumador, en tamizaje rutinario por ecografía abdominal se identifica un aneurisma aórtico abdominal infrarrenal de 4.2 cm, asintomático.',
    steps: [
      { q: 'Con este diámetro y sin síntomas, ¿cuál es el manejo apropiado?', options: ['Reparación quirúrgica electiva inmediata', 'Vigilancia por imagen y control de riesgo', 'Se puede suspender el seguimiento por imagen', 'Anticoagulación terapéutica de por vida'], correct: 1, explanation: 'Con un diámetro de 4.2 cm, por debajo del umbral quirúrgico de 5.5 cm, el manejo apropiado es la vigilancia por imagen periódica junto con control de factores de riesgo.' },
      { q: 'En el control a los 6 meses, el aneurisma mide 4.9 cm. ¿Qué implica este crecimiento?', options: ['Un crecimiento sin relevancia clínica', 'Indica la resolución espontánea del saco', 'Obliga a suspender toda vigilancia futura', 'Más de 0.5 cm en 6 meses: reparar'], correct: 3, explanation: 'Un crecimiento mayor de 0.5 cm en 6 meses es indicación de reparación independientemente de que el diámetro absoluto (4.9 cm) aún no alcance el umbral estándar de 5.5 cm.' },
      { q: '¿Qué modalidad de reparación se considera, dado el perfil típico de comorbilidad ateroesclerótica de este paciente?', options: ['No hay tratamiento intervencionista posible', 'Un trasplante aórtico completo de donante', 'Endovascular o abierta según anatomía', 'Observación de por vida, sin reparación'], correct: 2, explanation: 'La reparación electiva (endovascular o abierta según la anatomía) está indicada dado el crecimiento rápido documentado, independientemente del diámetro absoluto.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 55 años con disección aórtica tipo A confirmada desarrolla disnea aguda progresiva. Auscultación revela un soplo diastólico nuevo en el foco aórtico.',
    steps: [
      { q: '¿Qué complicación se debe sospechar dado este nuevo hallazgo?', options: ['Insuficiencia aórtica aguda valvular', 'Neumonía de la comunidad no relacionada', 'Una embolia pulmonar aguda alternativa', 'Un asma bronquial de inicio tardío'], correct: 0, explanation: 'La disnea aguda con un soplo diastólico nuevo en una disección tipo A sugiere insuficiencia aórtica aguda por compromiso de la válvula.' },
      { q: '¿Por qué esta paciente desarrolla edema pulmonar rápidamente, a diferencia de un paciente con insuficiencia aórtica crónica de larga evolución?', options: ['Está dilatado, igual que en la crónica', 'No está dilatado: no tolera el volumen', 'La forma aguda no afecta la función pulmonar', 'No hay diferencia entre las dos formas'], correct: 1, explanation: 'En la forma aguda, el ventrículo izquierdo no está dilatado ni remodelado (a diferencia de la adaptación compensadora de la forma crónica), por lo que no tolera el volumen regurgitante súbito.' },
      { q: '¿Cuál es el tratamiento definitivo de esta complicación?', options: ['Diuréticos como tratamiento único, sin cirugía', 'Observación ambulatoria, sin más tratamiento', 'Cirugía urgente con reemplazo valvular', 'Solo vasodilatadores, sin cirugía alguna'], correct: 2, explanation: 'El tratamiento definitivo es la cirugía urgente de la disección con reparación o reemplazo valvular en el mismo procedimiento, sin retrasarse por el manejo médico del edema pulmonar.' }
    ]
  }
];

export const flashcards = [
  { front: 'Las 3 entidades del síndrome aórtico agudo', back: 'Disección, hematoma intramural, úlcera penetrante.' },
  { front: 'Qué determina manejo quirúrgico vs. médico', back: 'Clasificación Stanford A (ascendente) vs. B (solo descendente).' },
  { front: 'Factor de riesgo más frecuente para las 4 entidades', back: 'Hipertensión arterial no controlada.' },
  { front: 'Dolor característico de la disección', back: 'Desgarrante, súbito, máxima intensidad desde el inicio.' },
  { front: 'Hallazgo de exploración sugestivo de disección', back: 'Déficit de pulso / diferencia de PA &gt;20 mmHg entre brazos.' },
  { front: 'Manejo de Stanford A', back: 'Cirugía urgente sin demora.' },
  { front: 'Manejo de Stanford B no complicado', back: 'Médico: control estricto de FC y PA.' },
  { front: 'Por qué betabloqueador antes que vasodilatador', back: 'Evita taquicardia refleja que aumentaría el estrés de cizallamiento.' },
  { front: 'Mecanismo del hematoma intramural', back: 'Rotura de vasa vasorum, SIN desgarro de íntima.' },
  { front: 'Hematoma intramural en angio-TC', back: 'Semiluna hiperdensa sin realce, sin doble luz.' },
  { front: 'Sustrato de la úlcera aórtica penetrante', back: 'Placa ateroesclerótica ulcerada que penetra la lámina elástica interna.' },
  { front: 'Población típica de la úlcera penetrante', back: 'Paciente de edad avanzada con ateroesclerosis difusa.' },
  { front: 'Reparación preferida en úlcera penetrante sintomática', back: 'Endovascular (perfil de comorbilidad ateroesclerótica).' },
  { front: 'Tamizaje de AAA', back: 'Ecografía abdominal, varones 65-75 años que fumaron alguna vez.' },
  { front: 'Umbral quirúrgico AAA', back: '≥5.5 cm varones / ≥5.0 cm mujeres.' },
  { front: 'Crecimiento que indica reparación pese al diámetro', back: '&gt;0.5 cm en 6 meses.' },
  { front: 'Rotura contenida vs. cavidad libre', back: 'Contenida: ventana breve para intervenir. Cavidad libre: exanguinación rápida.' },
  { front: 'Estrategia de PA en rotura aórtica', back: 'Hipotensión permisiva mientras se organiza reparación.' },
  { front: 'Mecanismo del taponamiento en disección', back: 'Extensión retrógrada tipo A hacia raíz, rotura a pericardio.' },
  { front: 'Tríada de Beck', back: 'Hipotensión + ingurgitación yugular + ruidos velados.' },
  { front: 'Por qué evitar pericardiocentesis aislada', back: 'Alivio brusco de presión puede agravar el sangrado activo.' },
  { front: 'Malperfusión dinámica vs. estática', back: 'Dinámica: compresión de falsa luz (fluctúa). Estática: oclusión fija del ostium.' },
  { front: 'Territorio de malperfusión más devastador', back: 'Medular (paraplejia).' },
  { front: 'Prioridad ante malperfusión de rama', back: 'Corregir flujo aórtico central primero.' },
  { front: 'Por qué el VI no tolera la IAo aguda', back: 'No está dilatado/remodelado, a diferencia de la crónica.' },
  { front: '3 mecanismos de IAo aguda en disección tipo A', back: 'Dilatación del anillo, desprendimiento de comisura, colgajo transvalvular.' },
  { front: 'Manejo definitivo de IAo aguda por disección', back: 'Cirugía urgente con reparación/reemplazo valvular en el mismo procedimiento.' },
  { front: '3 categorías del ADD-RS', back: 'Condiciones de alto riesgo, dolor de alto riesgo, exploración de alto riesgo.' },
  { front: 'ADD-RS ≥2', back: 'Riesgo alto: imagen urgente sin esperar dímero D.' },
  { front: 'ADD-RS 0 y dímero D', back: 'Bajo riesgo: dímero D bajo tiene alto valor predictivo negativo.' }
];
