// topics/osteoporosis/study.js: Autoevaluacion de Osteoporosis.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// Metodo (ver memoria del proyecto): las 48 preguntas (30 sueltas + 6 cascadas de 3 pasos) se
// escribieron con la respuesta correcta en options[0]/correct:0 y luego se redistribuyo la
// posicion de `correct` con un script. Sin em dash (ver [[feedback-no-em-dash]]).

export const quiz = [
  { q: 'Que define a la osteoporosis como enfermedad?', options: ['Masa osea baja y deterioro de la microarquitectura', 'Un descenso aislado del calcio serico por debajo del rango normal', 'La presencia de dolor oseo difuso con fosfatasa alcalina elevada', 'La perdida de cartilago articular con formacion de osteofitos'], correct: 0, explanation: 'La osteoporosis combina cantidad (masa osea baja) y calidad (deterioro de la microarquitectura), y su unica manifestacion clinica es la fractura. La calcemia es normal, y la perdida de cartilago con osteofitos es artrosis.', dificultad: 'facil' },
  { q: 'Que puntuacion T define la osteoporosis por densitometria?', options: ['De -1.0 o menor', 'De -2.0 o menor', 'De -2.5 o menor', 'De -3.5 o menor'], correct: 2, explanation: 'Los criterios de la OMS: T de -1.0 o mayor es normal; entre -1.0 y -2.5 es masa osea baja u osteopenia; y de -2.5 o menor es osteoporosis. Se toma el peor valor de columna lumbar, cuello femoral o cadera total.', dificultad: 'facil' },
  { q: 'Que rango de puntuacion T corresponde a la masa osea baja (osteopenia)?', options: ['Entre 0 y -1.0', 'Entre -2.5 y -3.5', 'Entre -1.5 y -2.0', 'Entre -1.0 y -2.5'], correct: 3, explanation: 'Es la zona intermedia, y es precisamente donde el FRAX decide si se trata: con un riesgo a 10 anos de 3% o mas para cadera, o de 20% o mas para fractura mayor, se inicia tratamiento farmacologico.', dificultad: 'intermedio' },
  { q: 'En que pacientes se usa la puntuacion Z en lugar de la T?', options: ['En todos los pacientes mayores de 70 anos con comorbilidad', 'En premenopausicas, varones menores de 50 anos y ninos', 'Solo cuando la densitometria de columna no es valorable', 'En los pacientes que ya han sufrido una fractura previa'], correct: 1, explanation: 'La puntuacion Z compara con la poblacion de la misma edad y sexo, no con el adulto joven. En esos grupos no se etiqueta de osteoporosis basandose solo en la densitometria, y un valor de -2.0 o menor obliga a buscar causa secundaria.', dificultad: 'intermedio' },
  { q: 'Que hallazgo diagnostica osteoporosis aunque la densitometria sea normal?', options: ['Una puntuacion Z de -1.5 en columna lumbar', 'Una fosfatasa alcalina elevada con calcio normal', 'Una perdida de talla de 1 cm en un ano', 'Una fractura por fragilidad de cadera o de vertebra'], correct: 3, explanation: 'Es el segundo camino diagnostico, que a menudo se olvida: una fractura de cadera o de vertebra por traumatismo de baja energia establece el diagnostico con independencia de la densidad mineral osea, incluso con puntuacion T normal.', dificultad: 'intermedio' },
  { q: 'Que sitios se miden en la densitometria y cual se usa para clasificar?', options: ['Solo la columna lumbar, por ser el hueso trabecular mas representativo', 'Columna, cuello femoral y cadera; se usa el peor', 'Calcaneo y radio distal, por su facil accesibilidad tecnica', 'Columna y cadera, y se usa el promedio aritmetico de ambas'], correct: 1, explanation: 'Se miden los tres y se clasifica por el peor valor. El radio al 33% se reserva para cuando los otros no son valorables, por ejemplo en el hiperparatiroidismo, la obesidad extrema o la presencia de protesis.', dificultad: 'intermedio' },
  { q: 'Por que la densitometria de columna puede ser enganosa en el anciano?', options: ['La artrosis y las calcificaciones aorticas sobreestiman la densidad', 'La perdida de masa muscular infraestima la densidad de forma sistematica', 'El aumento de la grasa medular falsea el resultado a la baja', 'La osteomalacia asociada eleva de forma artificial la puntuacion Z'], correct: 0, explanation: 'Los cambios degenerativos, las calcificaciones de la aorta y las fracturas vertebrales previas aumentan la densidad medida y pueden hacer parecer normal un hueso que no lo es. Por eso el cuello femoral suele ser mas fiable en el anciano.', dificultad: 'dificil' },
  { q: 'A partir de que edad se recomienda el cribado densitometrico sistematico?', options: ['A los 50 anos en ambos sexos, con o sin factores', 'A los 60 anos en la mujer y a los 65 en el varon', 'A los 65 anos en la mujer y a los 70 en el varon', 'A los 75 anos en ambos sexos, salvo fractura previa'], correct: 2, explanation: 'Mujeres desde los 65 y varones desde los 70; antes en mujeres posmenopausicas y varones de 50 a 69 anos con factores de riesgo, y en toda persona de 50 anos o mas que sufra una fractura por fragilidad.', dificultad: 'facil' },
  { q: 'Cuales son los umbrales de FRAX para iniciar tratamiento en la masa osea baja?', options: ['1% o mas para cadera, o 10% o mas para fractura mayor', '3% o mas para cadera, o 20% o mas para fractura mayor', '10% o mas para cadera, o 30% o mas para fractura mayor', '5% o mas para cadera, o 15% o mas para fractura mayor'], correct: 1, explanation: 'Son los umbrales habituales para decidir en la zona intermedia. Con puntuacion T de -2.5 o menor, o con una fractura de cadera o de vertebra, se trata sin necesidad de calcular el FRAX.', dificultad: 'intermedio' },
  { q: 'Como explica la perdida de estrogenos la aceleracion de la perdida osea en la menopausia?', options: ['Aumenta la esclerostina y se bloquea de forma directa al osteoblasto', 'Disminuye la absorcion intestinal de calcio de forma irreversible', 'Se eleva la parathormona de forma continua por hipocalcemia', 'Cae la osteoprotegerina y RANKL queda libre para activar al osteoclasto'], correct: 3, explanation: 'El estrogeno mantiene alta la produccion osteoblastica de osteoprotegerina, el senuelo que secuestra RANKL. Al perderse, RANKL queda libre, activa el receptor RANK del precursor osteoclastico y la resorcion se dispara.', dificultad: 'dificil' },
  { q: 'Que papel tiene la esclerostina en el hueso?', options: ['Es el principal activador del osteoclasto producido por el osteoblasto', 'Es la proteina que fija el calcio a la matriz osea mineralizada', 'Es el freno fisiologico de la formacion osea, secretado por el osteocito', 'Es el receptor de la parathormona en la superficie del osteoblasto'], correct: 2, explanation: 'El osteocito, atrapado en la matriz, secreta esclerostina para frenar la via Wnt y con ella la actividad del osteoblasto. El romosozumab es un anticuerpo contra la esclerostina: quita ese freno y estimula la formacion.', dificultad: 'dificil' },
  { q: 'Cual es el mecanismo de accion del denosumab?', options: ['Anticuerpo contra RANKL que impide activar al osteoclasto', 'Se fija a la hidroxiapatita y envenena al osteoclasto que la resorbe', 'Bloquea la esclerostina y estimula la formacion osea del osteoblasto', 'Imita el pulso de parathormona y activa la formacion osea'], correct: 0, explanation: 'El denosumab actua como una osteoprotegerina artificial: secuestra RANKL e impide que active al osteoclasto. La segunda opcion describe a los bisfosfonatos, la tercera al romosozumab y la cuarta a la teriparatida.', dificultad: 'intermedio' },
  { q: 'Que precaucion cardiovascular tiene el romosozumab?', options: ['Esta contraindicado en la hipertension arterial controlada', 'Obliga a suspender la antiagregacion durante su administracion', 'No se usa si ha habido infarto o ictus en el ano previo', 'Requiere ecocardiograma de control cada tres meses'], correct: 2, explanation: 'En el estudio ARCH se observo un exceso de eventos cardiovasculares mayores frente al alendronato, lo que llevo a un aviso de seguridad: no se administra a pacientes con infarto de miocardio o ictus en los 12 meses previos.', dificultad: 'intermedio' },
  { q: 'Por que la teriparatida estimula la formacion osea si la parathormona resorbe hueso?', options: ['Porque se administra de forma intermitente, no de forma continua', 'Porque se une a un receptor distinto del de la parathormona endogena', 'Porque bloquea al mismo tiempo la accion de la esclerostina', 'Porque aumenta la absorcion intestinal de calcio y de fosforo'], correct: 0, explanation: 'La parathormona elevada de forma continua (hiperparatiroidismo) produce resorcion, pero administrada como pulso diario predomina el efecto anabolico sobre el osteoblasto. Es el mismo receptor: lo que cambia es el patron temporal.', dificultad: 'dificil' },
  { q: 'Con que filtrado glomerular estan contraindicados los bisfosfonatos?', options: ['Por debajo de 60 mL/min/1.73 m2', 'Por debajo de 30 a 35 mL/min/1.73 m2', 'Por debajo de 15 mL/min/1.73 m2', 'No tienen contraindicacion por funcion renal'], correct: 1, explanation: 'Los bisfosfonatos se eliminan por via renal y estan contraindicados por debajo de 30 a 35 mL/min/1.73 m2. El denosumab es la alternativa en la enfermedad renal, porque no requiere ajuste, aunque conlleva mayor riesgo de hipocalcemia.', dificultad: 'intermedio' },
  { q: 'Cual es la secuencia optima cuando se van a usar un anabolico y un antirresortivo?', options: ['El antirresortivo primero y el anabolico despues', 'Los dos a la vez desde el inicio del tratamiento', 'El orden no influye en el resultado obtenido', 'El anabolico primero y el antirresortivo despues'], correct: 3, explanation: 'Empezar por el anabolico y consolidar despues con el antirresortivo produce mas ganancia de densidad que el orden inverso: un antirresortivo previo embota la respuesta al anabolico posterior, como mostro el estudio DATA-Switch.', dificultad: 'dificil' },
  { q: 'Que hay que hacer siempre al terminar un tratamiento anabolico?', options: ['Suspender todo tratamiento y repetir la densitometria en dos anos', 'Repetir un segundo ciclo del mismo anabolico de inmediato', 'Iniciar unas vacaciones terapeuticas de dos a tres anos', 'Continuar con un antirresortivo para consolidar lo ganado'], correct: 3, explanation: 'La ganancia obtenida con teriparatida, abaloparatida o romosozumab se pierde en meses si no se consolida con un antirresortivo. Dejar al paciente sin tratamiento tras un anabolico anula el beneficio conseguido.', dificultad: 'intermedio' },
  { q: 'A que farmacos se aplica el concepto de vacaciones terapeuticas?', options: ['Solo a los bisfosfonatos', 'A todos los antirresortivos, incluido el denosumab', 'Solo al denosumab, por su efecto reversible', 'A los anabolicos tras completar dos anos'], correct: 0, explanation: 'Los bisfosfonatos se depositan en el hueso y su efecto persiste tras suspenderlos, lo que permite pausar 2 a 3 anos tras 5 anos de tratamiento oral o 3 de intravenoso si el riesgo ya no es alto. Con el denosumab el concepto no existe.', dificultad: 'intermedio' },
  { q: 'Que ocurre si se suspende el denosumab sin pasar a otro antirresortivo?', options: ['El efecto persiste varios anos porque el farmaco queda depositado en el hueso', 'La densidad se mantiene estable y solo hay que repetir la densitometria', 'Se produce un rebote de la resorcion con riesgo de fracturas vertebrales multiples', 'Se produce una hipercalcemia por liberacion brusca de calcio oseo'], correct: 2, explanation: 'El denosumab no se deposita en el hueso y su bloqueo de RANKL es reversible: al eliminarse, la maquinaria osteoclastica acumulada se activa de golpe y la resorcion rebota por encima del nivel basal, con fracturas vertebrales multiples en los meses siguientes.', dificultad: 'intermedio' },
  { q: 'Como se hace la transicion cuando hay que suspender el denosumab?', options: ['Espaciando de forma progresiva las dosis cada 9 y luego cada 12 meses', 'Pautando un bisfosfonato en el momento en que tocaba la dosis omitida', 'Suspendiendo sin mas y repitiendo la densitometria a los 2 anos', 'Sustituyendolo por calcio y vitamina D a dosis altas'], correct: 1, explanation: 'Se administra un bisfosfonato (acido zoledronico o alendronato) 6 meses despues de la ultima dosis de denosumab, es decir, cuando tocaria la siguiente, y se controlan los marcadores de remodelado a los 3 a 6 meses por si hace falta repetir.', dificultad: 'dificil' },
  { q: 'Cual es el aporte recomendado de calcio y de vitamina D en la osteoporosis?', options: ['Calcio de 1000 a 1200 mg y vitamina D de 800 a 1000 UI al dia', 'Calcio de 2000 a 2500 mg diarios y vitamina D de 4000 UI', 'Calcio de 500 mg diarios y vitamina D de 400 UI al dia', 'Calcio de 1500 mg diarios y vitamina D de 200 UI al dia'], correct: 0, explanation: 'De preferencia cubriendo el calcio con la dieta: los suplementos por encima de lo necesario no aportan beneficio y se han asociado a litiasis renal. Si se suplementa, en tomas de 500 a 600 mg como maximo, porque por encima la absorcion cae.', dificultad: 'facil' },
  { q: 'Por que hay que corregir el deficit de vitamina D antes de un antirresortivo potente?', options: ['Para que el farmaco se absorba de forma adecuada en el intestino', 'Para prevenir la aparicion de osteonecrosis de los maxilares', 'Para reducir el riesgo de reaccion de fase aguda tras la infusion', 'Para evitar una hipocalcemia grave al frenar bruscamente la resorcion'], correct: 3, explanation: 'El acido zoledronico y sobre todo el denosumab frenan de golpe la salida de calcio del hueso; si el paciente tiene deficit de vitamina D y por tanto poca absorcion intestinal, la calcemia puede caer de forma peligrosa.', dificultad: 'intermedio' },
  { q: 'Cual es la causa mas frecuente de osteoporosis secundaria?', options: ['El hipertiroidismo subclinico', 'El tratamiento con glucocorticoides', 'La enfermedad celiaca no diagnosticada', 'El hiperparatiroidismo primario'], correct: 1, explanation: 'Los glucocorticoides son con diferencia la primera causa de osteoporosis secundaria y la causa mas frecuente de osteoporosis en pacientes jovenes, hasta el punto de tener una guia de manejo propia.', dificultad: 'facil' },
  { q: 'Cuando se inicia el tratamiento preventivo en el paciente que va a recibir glucocorticoides?', options: ['Solo cuando la densitometria muestre una puntuacion T de -2.5 o menor', 'Unicamente si aparece una fractura durante el tratamiento', 'Si va a recibirlos 3 meses o mas y tiene riesgo moderado o alto', 'Solo con dosis equivalentes a 20 mg de prednisona o superiores'], correct: 2, explanation: 'El riesgo de fractura por glucocorticoides aparece pronto (en los primeros 3 a 6 meses), con dosis bajas y de forma desproporcionada a la perdida de densidad medible: esperar a que la densitometria se altere es llegar tarde.', dificultad: 'intermedio' },
  { q: 'Que farmaco se prefiere en la osteoporosis por glucocorticoides de riesgo alto?', options: ['El raloxifeno, por su efecto selectivo sobre el tejido oseo', 'La calcitonina, por su efecto analgesico anadido al oseo', 'La teriparatida, superior al bisfosfonato en ese escenario', 'El calcio y la vitamina D en monoterapia a dosis altas'], correct: 2, explanation: 'Los bisfosfonatos son de primera linea por eficacia y coste, pero en la osteoporosis inducida por glucocorticoides con riesgo alto la teriparatida ha demostrado ser superior, lo que encaja con que los esteroides danan sobre todo la formacion osea.', dificultad: 'dificil' },
  { q: 'Que estudio es obligado ante una osteoporosis en el varon?', options: ['La densitometria de radio distal, por ser mas fiable en el varon', 'La testosterona total matutina, por el hipogonadismo', 'La biopsia osea con doble marcaje de tetraciclinas', 'La gammagrafia osea de cuerpo entero de forma rutinaria'], correct: 1, explanation: 'Hasta la mitad o mas de las osteoporosis del varon son secundarias, y el hipogonadismo (incluida la terapia de deprivacion androgenica en el cancer de prostata) es la causa mas frecuente. La testosterona matutina es obligada en el estudio.', dificultad: 'intermedio' },
  { q: 'Que proporcion de las fracturas vertebrales por fragilidad son asintomaticas?', options: ['Menos del 10% de ellas', 'Practicamente todas producen dolor', 'Alrededor del 20% de ellas', 'Alrededor de dos tercios'], correct: 3, explanation: 'La mayoria se descubre de forma casual en una radiografia pedida por otro motivo, o se sospecha por la perdida de talla y la cifosis. Por eso se pide imagen vertebral ante perdida de talla, cifosis o uso de glucocorticoides.', dificultad: 'intermedio' },
  { q: 'Cual es la mortalidad al ano tras una fractura de cadera por fragilidad?', options: ['Del 20 al 30%', 'Menos del 5%', 'Del 50 al 60%', 'Alrededor del 10%'], correct: 0, explanation: 'Es la fractura mas grave de la osteoporosis: entre el 20 y el 30% de los pacientes fallece en el ano siguiente, y de los supervivientes una proporcion importante no recupera la independencia funcional previa.', dificultad: 'intermedio' },
  { q: 'Que aporta el acido zoledronico administrado tras una fractura de cadera?', options: ['Acelera la consolidacion del foco de fractura operado', 'Reduce las nuevas fracturas y tambien la mortalidad', 'Sustituye la necesidad de rehabilitacion posquirurgica', 'Permite retirar el calcio y la vitamina D del tratamiento'], correct: 1, explanation: 'Es de los pocos tratamientos de la osteoporosis con reduccion demostrada de la mortalidad. Se administra a partir de las 2 semanas de la cirugia, una vez corregido el deficit de vitamina D.', dificultad: 'dificil' },
  { q: 'Que se debe hacer ante dolor en el muslo en un paciente con antirresortivo prolongado?', options: ['Tranquilizar al paciente y repetir la densitometria en un ano', 'Aumentar la dosis del antirresortivo por sospecha de fallo terapeutico', 'Radiografiar los dos femures, no solo el sintomatico', 'Solicitar una gammagrafia osea antes que cualquier radiografia'], correct: 2, explanation: 'El dolor prodromico en muslo o ingle precede semanas o meses a la fractura femoral atipica, que es subtrocanterica o diafisaria y transversa, y bilateral en cerca de un tercio de los casos. Si las radiografias son normales y persiste la sospecha, se hace resonancia.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 68 anos, menopausia a los 51, sin fracturas previas. Acude por cribado. Densitometria: columna lumbar T de -2.1, cuello femoral T de -2.7, cadera total T de -2.5. No toma farmacos y no tiene antecedentes de interes.',
    steps: [
      { q: 'Cual es el diagnostico densitometrico?', options: ['Osteoporosis, por la puntuacion T del cuello femoral', 'Masa osea baja, por el promedio de los tres valores', 'Densidad normal, porque la columna esta por encima de -2.5', 'No es valorable sin conocer la puntuacion Z'], correct: 0, explanation: 'Se clasifica por el PEOR de los tres sitios: el cuello femoral con T de -2.7 esta por debajo de -2.5, de modo que hay osteoporosis. No se promedian los valores.' },
      { q: 'Que hay que hacer antes de iniciar el tratamiento?', options: ['Solicitar una biopsia osea para confirmar el diagnostico', 'Repetir la densitometria a los 6 meses para confirmar', 'Calcular el FRAX, que es imprescindible en este caso', 'Descartar causas secundarias y corregir el deficit de vitamina D'], correct: 3, explanation: 'El panel minimo incluye calcio, fosforo, fosfatasa alcalina, funcion renal, 25-hidroxivitamina D, hormona paratiroidea, TSH, proteinograma y calcio en orina. Con T de -2.5 o menor se trata sin necesidad de calcular el FRAX.' },
      { q: 'Cual es el tratamiento farmacologico de eleccion?', options: ['Un bisfosfonato, por perfil de riesgo alto', 'Romosozumab, por tratarse de una osteoporosis densitometrica', 'Solo calcio y vitamina D, por la ausencia de fracturas previas', 'Teriparatida durante dos anos como primera opcion de entrada'], correct: 0, explanation: 'No hay fractura reciente, ni fracturas multiples, ni una puntuacion T muy baja: es un perfil de riesgo alto, no muy alto. El bisfosfonato es la primera linea por eficacia y coste; el anabolico se reserva para el riesgo muy alto.' }
    ],
    explanation: 'Una densitometria se clasifica por el peor de los tres sitios: un cuello femoral de -2.7 es osteoporosis. Se descartan causas secundarias y se corrige la vitamina D antes de iniciar un bisfosfonato, que es la primera linea en el riesgo alto.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 74 anos que acude por dolor dorsal agudo tras un esfuerzo minimo. La radiografia muestra una fractura vertebral de D12 de aspecto reciente y otra antigua en L1. La densitometria realizada despues muestra una puntuacion T de -2.0 en cuello femoral.',
    steps: [
      { q: 'Tiene osteoporosis con una puntuacion T de -2.0?', options: ['No: hace falta una puntuacion T de -2.5 o menor para el diagnostico', 'Si: la fractura vertebral por fragilidad ya la diagnostica', 'No se puede afirmar sin calcular antes el FRAX de la paciente', 'Solo si se demuestra que la fractura fue por traumatismo minimo repetido'], correct: 1, explanation: 'Es el segundo camino diagnostico: una fractura por fragilidad de cadera o de vertebra establece el diagnostico de osteoporosis aunque la densidad mineral osea no llegue al umbral, e incluso con puntuacion T normal.' },
      { q: 'En que categoria de riesgo se encuentra?', options: ['Riesgo alto, porque la puntuacion T no llega a -2.5 todavia', 'Riesgo moderado, al no haber fractura de cadera asociada', 'Riesgo muy alto, por fractura reciente y multiple', 'Riesgo bajo, porque el dolor responde bien a la analgesia'], correct: 2, explanation: 'La fractura vertebral reciente (sobre todo en los 12 a 24 meses previos) y la presencia de fracturas multiples definen riesgo muy alto, con independencia de la puntuacion T.' },
      { q: 'Que tratamiento farmacologico corresponde?', options: ['Un bisfosfonato oral en monoterapia durante cinco anos seguidos', 'Calcio y vitamina D solos hasta que se repita la densitometria', 'Raloxifeno, por tratarse de fracturas vertebrales', 'Empezar por un anabolico y consolidar con un antirresortivo'], correct: 3, explanation: 'En el riesgo muy alto se prefiere empezar por teriparatida, abaloparatida o romosozumab, porque el anabolico rinde mas si va primero, y despues consolidar con un antirresortivo para no perder lo ganado.' }
    ],
    explanation: 'Una fractura vertebral por fragilidad diagnostica osteoporosis aunque la T sea de -2.0, y al ser reciente y multiple define riesgo muy alto: se empieza por un anabolico y se consolida despues con un antirresortivo.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 66 anos lleva 4 anos con denosumab semestral, con buena respuesta densitometrica. Acude a consulta y comenta que, como su vecina descansa del tratamiento de los huesos cada cierto tiempo, ella tambien quiere tomarse unas vacaciones terapeuticas de dos anos.',
    steps: [
      { q: 'Que hay que explicarle?', options: ['Que puede descansar dos anos si repite la densitometria al final', 'Que puede espaciar las dosis a cada 12 meses en lugar de suspender', 'Que el descanso es adecuado tras cuatro anos de buena respuesta', 'Que las vacaciones son solo para los bisfosfonatos'], correct: 3, explanation: 'Los bisfosfonatos se depositan en el hueso y su efecto persiste tras suspenderlos, de ahi el concepto de vacaciones. El denosumab no se deposita y su bloqueo es reversible: al retirarlo la resorcion rebota por encima del nivel basal.' },
      { q: 'Que puede ocurrir si suspende el denosumab sin mas?', options: ['Una hipercalcemia grave por liberacion brusca del calcio oseo', 'Una perdida lenta y progresiva similar a la de la menopausia', 'Fracturas vertebrales multiples en los meses siguientes por el rebote', 'Nada relevante, porque el efecto persiste durante anos'], correct: 2, explanation: 'La maquinaria osteoclastica acumulada durante el bloqueo se activa de golpe: la densidad ganada se pierde en 12 a 24 meses y pueden aparecer fracturas vertebrales multiples, sobre todo en quien ya tenia fracturas previas.' },
      { q: 'Si finalmente hay que suspenderlo, como se hace la transicion?', options: ['Retirandolo y aumentando el calcio y la vitamina D del plan', 'Con un bisfosfonato cuando tocaba la dosis omitida', 'Sustituyendolo por teriparatida durante dos anos completos', 'Espaciando las dosis de forma progresiva hasta retirarlo'], correct: 1, explanation: 'Se administra acido zoledronico o alendronato 6 meses despues de la ultima dosis, es decir, cuando tocaria la siguiente, y se controlan los marcadores de remodelado a los 3 a 6 meses por si hay que repetir el zoledronico.' }
    ],
    explanation: 'Las vacaciones terapeuticas son solo para bisfosfonatos: suspender el denosumab sin transicion provoca un rebote de la resorcion con fracturas vertebrales multiples, y si hay que retirarlo se pauta un bisfosfonato en el momento de la dosis omitida.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 62 anos con arteritis de celulas gigantes recien diagnosticada. Se le va a iniciar prednisona a 40 mg diarios con pauta descendente lenta, previsiblemente durante al menos un ano. No tiene fracturas previas y no se le ha hecho nunca una densitometria.',
    steps: [
      { q: 'Que corresponde hacer respecto del hueso?', options: ['Densitometria basal y calcio con vitamina D desde el inicio', 'Esperar a los 12 meses y valorar entonces con una densitometria', 'No hacer nada porque la pauta es descendente y limitada', 'Iniciar directamente un anabolico sin ningun estudio previo'], correct: 0, explanation: 'El riesgo de fractura por glucocorticoides aparece en los primeros 3 a 6 meses y con dosis bajas. Se pide densitometria basal y se inician calcio y vitamina D en todos los pacientes desde el comienzo del tratamiento.' },
      { q: 'Cuando esta indicado anadir tratamiento farmacologico especifico?', options: ['Solo si la densitometria muestra una puntuacion T de -2.5 o menor', 'Si va a recibirlos 3 meses o mas con riesgo moderado o alto', 'Unicamente si aparece una fractura durante el seguimiento', 'Solo cuando la dosis supere el equivalente de 30 mg de prednisona'], correct: 1, explanation: 'Se trata de forma precoz y con umbrales mas bajos que en la osteoporosis primaria: la perdida de calidad osea por glucocorticoides es desproporcionada a la perdida de densidad medible, de modo que esperar a la densitometria alterada es llegar tarde.' },
      { q: 'Que farmaco se prefiere si el riesgo resulta alto?', options: ['Teriparatida, superior al bisfosfonato aqui', 'Raloxifeno, por su perfil de seguridad en el varon adulto', 'Calcitonina intranasal por su efecto analgesico anadido', 'Solo aumentar la dosis de calcio y de vitamina D pautadas'], correct: 0, explanation: 'Los bisfosfonatos son de primera linea por eficacia y coste, pero en la osteoporosis inducida por glucocorticoides de riesgo alto la teriparatida ha demostrado ser superior, lo que encaja con que los esteroides danan sobre todo la formacion osea.' }
    ],
    explanation: 'Ante glucocorticoides previstos 3 meses o mas: densitometria basal, calcio y vitamina D en todos desde el inicio, y tratamiento especifico si el riesgo es moderado o alto, con teriparatida preferida en el riesgo alto.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 58 anos remitido por una densitometria con puntuacion T de -2.6 en cuello femoral, solicitada tras una fractura de muneca por una caida desde su altura. Fuma 20 cigarrillos al dia y refiere disminucion de la libido desde hace anos.',
    steps: [
      { q: 'Que estudio es obligado en este paciente?', options: ['La densitometria de radio distal para confirmar el diagnostico', 'Una biopsia osea con doble marcaje de tetraciclinas', 'Un estudio genetico de osteogenesis imperfecta del adulto', 'La testosterona total matutina y el panel de causas'], correct: 3, explanation: 'Hasta la mitad o mas de las osteoporosis del varon son secundarias, y el hipogonadismo es la causa mas frecuente. Los sintomas que refiere lo hacen aun mas probable, y se mide la testosterona total matutina, repetida si esta baja.' },
      { q: 'Que otras causas conviene descartar en el varon?', options: ['Solo el deficit de vitamina D, que explica la mayoria de los casos', 'Unicamente el hiperparatiroidismo primario', 'Alcohol, hipertiroidismo, malabsorcion, hipercalciuria y mieloma', 'No hace falta ampliar si la testosterona resulta baja'], correct: 2, explanation: 'El panel del varon incluye calcio, fosforo, fosfatasa alcalina, funcion renal, 25-hidroxivitamina D, hormona paratiroidea, TSH, proteinograma con inmunofijacion, calcio en orina de 24 horas y testosterona, con umbral bajo para celiaquia y hemocromatosis.' },
      { q: 'Si se confirma hipogonadismo, basta con reponer testosterona?', options: ['Si: la testosterona normaliza la densidad osea por si sola', 'Si, con calcio y vitamina D asociados al tratamiento hormonal', 'No: el riesgo alto exige ademas farmaco especifico', 'No: la testosterona esta contraindicada si hay osteoporosis'], correct: 2, explanation: 'La testosterona se indica por el hipogonadismo en si y mejora la densidad, pero no es un tratamiento de la osteoporosis: con una puntuacion T de -2.6 y una fractura por fragilidad hay que anadir un farmaco especifico con eficacia antifractura demostrada.' }
    ],
    explanation: 'En el varon con osteoporosis hay que buscar causa secundaria de forma sistematica, con testosterona matutina obligada; y aunque se confirme un hipogonadismo, la reposicion hormonal no sustituye al tratamiento especifico si el riesgo de fractura es alto.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 71 anos en tratamiento con alendronato desde hace 8 anos. Consulta por dolor sordo en la cara anterior del muslo derecho de 3 meses de evolucion, que empeora al caminar y que no ha mejorado con analgesia. No ha sufrido ninguna caida ni traumatismo.',
    steps: [
      { q: 'Que hay que sospechar?', options: ['Una artrosis de cadera de evolucion inusualmente rapida', 'Una metastasis osea de tumor primario desconocido', 'Una osteonecrosis de la cabeza femoral incipiente', 'Una fractura femoral atipica en fase de estres'], correct: 3, explanation: 'El dolor prodromico en muslo o ingle, sordo y mecanico, durante semanas o meses, en una paciente con antirresortivo prolongado, es el aviso caracteristico de la fractura femoral atipica antes de que se complete.' },
      { q: 'Que prueba de imagen corresponde solicitar?', options: ['Radiografia de los dos femures, no solo del sintomatico', 'Radiografia solo del femur sintomatico, para no irradiar de mas', 'Gammagrafia osea de cuerpo entero como primera prueba', 'Tomografia abdominal en busca de un tumor primario oculto'], correct: 0, explanation: 'Se radiografian ambos femures buscando engrosamiento cortical localizado y trazo transverso subtrocanterico o diafisario. Si las radiografias son normales y la sospecha persiste, se completa con resonancia o gammagrafia para detectar la fractura de estres.' },
      { q: 'Que conducta corresponde si se confirma?', options: ['Aumentar la dosis del bisfosfonato para acelerar la consolidacion', 'Suspender el antirresortivo y descargar el miembro', 'Mantener el tratamiento y limitarse a la analgesia pautada', 'Iniciar denosumab como alternativa inmediata al bisfosfonato'], correct: 1, explanation: 'Se suspende el antirresortivo, se descarga el miembro y se valora el enclavado intramedular profilactico si hay fractura incompleta con dolor. La teriparatida se ha usado para favorecer la consolidacion, que es lenta.' }
    ],
    explanation: 'El dolor prodromico en muslo en una paciente con antirresortivo prolongado obliga a descartar una fractura femoral atipica radiografiando los DOS femures; si se confirma, se suspende el antirresortivo, se descarga el miembro y se valora el enclavado profilactico.'
  }
];

export const flashcards = [
  { front: 'Definicion de osteoporosis', back: 'Masa osea baja y deterioro de la microarquitectura, con aumento de la fragilidad y del riesgo de fractura. La calcemia es normal.' },
  { front: 'Criterios densitometricos de la OMS', back: 'T de -1.0 o mayor normal; entre -1.0 y -2.5 masa osea baja; de -2.5 o menor osteoporosis.' },
  { front: 'Cuando se usa la puntuacion Z', back: 'Mujeres premenopausicas, varones menores de 50 y ninos. Z de -2.0 o menor: buscar causa secundaria.' },
  { front: 'El segundo camino diagnostico', back: 'Una fractura por fragilidad de cadera o vertebra diagnostica osteoporosis aunque la densitometria sea normal.' },
  { front: 'Sitios de densitometria y cual se usa', back: 'Columna lumbar, cuello femoral y cadera total; se clasifica por el PEOR de los tres.' },
  { front: 'Trampa de la densitometria de columna en el anciano', back: 'La artrosis, las calcificaciones aorticas y las fracturas previas SOBREESTIMAN la densidad.' },
  { front: 'Edad de cribado densitometrico', back: 'Mujeres desde los 65 anos, varones desde los 70; antes con factores de riesgo o tras una fractura por fragilidad.' },
  { front: 'Umbrales de FRAX para tratar', back: '3% o mas para cadera, o 20% o mas para fractura mayor osteoporotica.' },
  { front: 'Por que la menopausia acelera la perdida osea', back: 'Cae la osteoprotegerina y RANKL queda libre para activar al osteoclasto.' },
  { front: 'Papel de la esclerostina', back: 'Freno fisiologico de la formacion osea, secretado por el osteocito; el romosozumab la bloquea.' },
  { front: 'Mecanismo del denosumab', back: 'Anticuerpo contra RANKL: actua como una osteoprotegerina artificial.' },
  { front: 'Mecanismo de los bisfosfonatos', back: 'Se fijan a la hidroxiapatita y envenenan al osteoclasto que la resorbe.' },
  { front: 'Precaucion cardiovascular del romosozumab', back: 'No usar si ha habido infarto o ictus en el ano previo (estudio ARCH).' },
  { front: 'Por que la teriparatida forma hueso', back: 'Porque la parathormona administrada de forma INTERMITENTE es anabolica; de forma continua es resortiva.' },
  { front: 'Contraindicacion renal de los bisfosfonatos', back: 'Filtrado glomerular por debajo de 30 a 35 mL/min/1.73 m2; el denosumab no requiere ajuste.' },
  { front: 'Secuencia optima anabolico-antirresortivo', back: 'El ANABOLICO PRIMERO y el antirresortivo despues: el orden inverso embota la respuesta al anabolico.' },
  { front: 'Que hacer al terminar un anabolico', back: 'Consolidar siempre con un antirresortivo: lo ganado se pierde en meses si no.' },
  { front: 'A quien se aplican las vacaciones terapeuticas', back: 'SOLO a los bisfosfonatos (5 anos oral, 3 anos intravenoso). Nunca al denosumab.' },
  { front: 'Rebote tras suspender el denosumab', back: 'La resorcion rebota por encima del basal, con fracturas vertebrales multiples en 12 a 24 meses.' },
  { front: 'Transicion al suspender denosumab', back: 'Bisfosfonato (zoledronico o alendronato) 6 meses despues de la ultima dosis, cuando tocaria la siguiente.' },
  { front: 'Aporte de calcio y vitamina D', back: 'Calcio 1000 a 1200 mg/dia (mejor con la dieta) y vitamina D 800 a 1000 UI/dia.' },
  { front: 'Por que corregir la vitamina D antes del antirresortivo potente', back: 'Para evitar hipocalcemia grave al frenar bruscamente la salida de calcio del hueso.' },
  { front: 'Causa mas frecuente de osteoporosis secundaria', back: 'El tratamiento con glucocorticoides.' },
  { front: 'Cuando tratar la osteoporosis por glucocorticoides', back: 'Si se van a recibir 3 meses o mas y el riesgo es moderado o alto; no esperar a que la densitometria se altere.' },
  { front: 'Farmaco preferido en osteoporosis por glucocorticoides de riesgo alto', back: 'Teriparatida, superior al bisfosfonato en ese escenario.' },
  { front: 'Estudio obligado en la osteoporosis del varon', back: 'Testosterona total matutina: el hipogonadismo es la causa secundaria mas frecuente.' },
  { front: 'Fracturas vertebrales asintomaticas', back: 'Alrededor de dos tercios; se descubren en una radiografia pedida por otro motivo.' },
  { front: 'Mortalidad al ano tras fractura de cadera', back: 'Del 20 al 30%.' },
  { front: 'Acido zoledronico tras fractura de cadera', back: 'Reduce nuevas fracturas y tambien la MORTALIDAD; se da a partir de las 2 semanas de la cirugia.' },
  { front: 'Dolor en muslo con antirresortivo prolongado', back: 'Sospechar fractura femoral atipica: radiografiar LOS DOS femures (bilateral en un tercio).' },
  { front: 'Osteonecrosis mandibular: frecuencia real', back: 'Muy rara a dosis de osteoporosis; valoracion odontologica antes de iniciar el antirresortivo.' },
  { front: 'Riesgo muy alto: que lo define', back: 'Fractura de cadera o vertebra reciente, fracturas multiples, T muy bajo, o fractura durante el tratamiento.' }
];
