// topics/cetoacidosis-estado-hiperosmolar/study.js: Autoevaluacion de las crisis hiperglucemicas.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// Metodo (ver memoria del proyecto): las 48 preguntas (30 sueltas + 6 cascadas de 3 pasos) se
// escribieron con la respuesta correcta en options[0]/correct:0 y luego se redistribuyo la
// posicion de `correct` con un script a una secuencia objetivo equilibrada (12 por posicion).
// Cada pregunta se releyo completa tras la redistribucion. Sin em dash (ver [[feedback-no-em-dash]]).

export const quiz = [
  { q: 'Que explica que un paciente haga un estado hiperosmolar en vez de una cetoacidosis?', options: ['Tiene una reserva hepatica de glucogeno mucho mayor de lo habitual', 'Conserva insulina residual suficiente para frenar la lipolisis', 'Su glucagon esta suprimido por el grado de hiperglucemia', 'Elimina los cuerpos cetonicos mas rapido por via renal'], correct: 1, explanation: 'Frenar la lipolisis exige mucha menos insulina que controlar la glucemia. En el EHH queda insulina residual bastante para apagar la cetogenesis pero no para contener la glucosa; en la CAD el deficit es absoluto o casi y las dos vias quedan abiertas.', dificultad: 'intermedio' },
  { q: 'Cuales son los tres criterios diagnosticos de la cetoacidosis diabetica segun el consenso ADA/EASD de 2024?', options: ['Glucosa de 600 mg/dL o mayor, cetosis y osmolalidad alta', 'Glucosa de 250 mg/dL o mayor, cetonuria y sodio bajo', 'Hiperglucemia, alteracion del sensorio y anion gap normal', 'Glucosa de 200 mg/dL o mayor, cetosis y acidosis metabolica'], correct: 3, explanation: 'El consenso de 2024 exige glucosa de 200 mg/dL o mayor (o diabetes conocida), cetosis (beta-hidroxibutirato de 3.0 mmol/L o mayor, o cetonuria de 2+ o mas) y acidosis metabolica (pH menor de 7.30 o bicarbonato menor de 18). El umbral clasico de 250 se bajo para no perder las formas euglucemicas.', dificultad: 'intermedio' },
  { q: 'Que marcador de cetosis prefiere el consenso ADA/EASD de 2024 y con que umbral?', options: ['Beta-hidroxibutirato de 3.0 mmol/L o mayor', 'Cetonuria por nitroprusiato de 1+ o mas', 'Acetona espirada detectable', 'Acetoacetato serico de 1.0 mmol/L o mayor'], correct: 0, explanation: 'El beta-hidroxibutirato en sangre de 3.0 mmol/L o mayor es el criterio preferido porque es el cuerpo cetonico predominante al inicio y permite seguir la respuesta al tratamiento; la cetonuria de 2+ o mas sirve como alternativa cuando no se dispone de el.', dificultad: 'intermedio' },
  { q: 'Por que la cetonuria por nitroprusiato puede aumentar mientras el paciente mejora?', options: ['Porque la insulina aumenta la produccion renal de cuerpos cetonicos', 'Porque la rehidratacion concentra las cetonas en la orina emitida', 'Porque no detecta beta-hidroxibutirato, que al tratar pasa a acetoacetato', 'Porque el bicarbonato administrado genera acetoacetato adicional'], correct: 2, explanation: 'La tira de nitroprusiato detecta acetoacetato y acetona pero no beta-hidroxibutirato, que predomina al inicio. Al mejorar, el beta-hidroxibutirato se reoxida a acetoacetato y la tira se positiviza mas. Por eso se sigue el beta-hidroxibutirato en sangre o el anion gap.', dificultad: 'dificil' },
  { q: 'Cuales son los criterios diagnosticos del estado hiperosmolar hiperglucemico?', options: ['Glucosa de 300 mg/dL o mayor, cetonemia franca y pH menor de 7.30', 'Glucosa de 400 mg/dL o mayor, sodio bajo y anion gap muy elevado', 'Hiperglucemia con bicarbonato menor de 15 y osmolalidad normal', 'Glucosa 600 o mayor, osmolalidad alta y sensorio alterado, sin acidosis'], correct: 3, explanation: 'El EHH exige glucosa de 600 mg/dL o mayor, osmolalidad efectiva elevada (mayor de 300 mOsm/kg en el consenso de 2024, mayor de 320 en el criterio clasico), ausencia de cetoacidosis (pH mayor de 7.30 y bicarbonato mayor de 18) y alteracion del estado mental.', dificultad: 'intermedio' },
  { q: 'Como se calcula la osmolalidad plasmatica efectiva y por que se excluye la urea?', options: ['Dos veces el sodio mas la glucosa entre 18; la urea cruza libremente', 'Dos veces el sodio mas la urea entre 2.8; la glucosa no genera gradiente', 'La suma de sodio, potasio y cloro; los demas solutos son irrelevantes', 'Dos veces el sodio corregido mas el lactato; la glucosa ya esta incluida'], correct: 0, explanation: 'La osmolalidad efectiva o tonicidad es 2 por el sodio mas la glucosa entre 18. La urea se excluye porque cruza libremente las membranas celulares y no genera un gradiente osmotico eficaz, aunque si aumenta la osmolalidad total.', dificultad: 'intermedio' },
  { q: 'Con que parametros se gradua la gravedad de la cetoacidosis diabetica en el consenso de 2024?', options: ['Con la glucemia y la osmolalidad', 'Con el anion gap y el sodio corregido', 'Con el pH y el bicarbonato venosos', 'Con el beta-hidroxibutirato y el potasio'], correct: 2, explanation: 'La gravedad se gradua solo por el pH y el bicarbonato: leve (pH 7.20 a 7.29, bicarbonato 15 a 17), moderada (pH 7.10 a 7.19, bicarbonato 10 a 14) y grave (pH menor de 7.10, bicarbonato menor de 10). La declaracion clasica de 2009 incluia ademas el estado mental.', dificultad: 'intermedio' },
  { q: 'Cual es el factor precipitante mas frecuente de las crisis hiperglucemicas?', options: ['El infarto agudo de miocardio', 'La infeccion', 'El tratamiento con glucocorticoides', 'La pancreatitis aguda'], correct: 1, explanation: 'La infeccion (neumonia, infeccion urinaria, sepsis) explica del 30 al 50% de los casos. Le siguen la omision o el ajuste insuficiente de la insulina, que es la primera causa en el paciente joven con DM1, y los eventos isquemicos.', dificultad: 'facil' },
  { q: 'Que parametro hay que comprobar obligatoriamente antes de administrar la primera dosis de insulina?', options: ['El potasio serico', 'El sodio corregido', 'El fosfato serico', 'El lactato arterial'], correct: 0, explanation: 'La insulina desplaza el potasio al interior de la celula. Con un potasio menor de 3.3 mmol/L, administrarla puede provocar una arritmia mortal y paralisis de la musculatura respiratoria, asi que se repone primero.', dificultad: 'facil' },
  { q: 'Que se hace si el potasio inicial es de 3.0 mmol/L en una cetoacidosis diabetica?', options: ['Iniciar la insulina a la mitad de dosis y reponer potasio a la vez', 'Iniciar la insulina y anadir potasio solo si baja de 3.0', 'Reponer potasio y no iniciar la insulina hasta superar 3.3 mmol/L', 'Administrar bicarbonato para desplazar el potasio al plasma'], correct: 2, explanation: 'Con potasio menor de 3.3 mmol/L se repone a 10 a 20 mmol/h (hasta 20 a 30 en situacion critica y con monitorizacion) y no se inicia la insulina hasta superar ese umbral. Mientras tanto si se reponen liquidos y se busca el precipitante.', dificultad: 'intermedio' },
  { q: 'Cuanto potasio se anade a cada litro de fluido cuando el potasio inicial esta entre 3.3 y 5.2 mmol/L?', options: ['De 60 a 80 mmol por litro', 'De 20 a 30 mmol por litro', 'De 5 a 10 mmol por litro', 'No se anade potasio en ese rango'], correct: 1, explanation: 'Con potasio de 3.3 a 5.2 mmol/L se anaden 20 a 30 mmol por litro de fluido con el objetivo de mantenerlo entre 4 y 5. Por encima de 5.2 no se repone todavia y se repite el control a las 2 h.', dificultad: 'intermedio' },
  { q: 'Por que el potasio serico inicial suele ser normal o alto pese a un deficit corporal importante?', options: ['La diuresis osmotica retiene potasio en el tubulo distal renal', 'La deshidratacion aumenta su reabsorcion en el intestino delgado', 'El glucagon estimula su liberacion desde el tejido oseo', 'La acidosis y la falta de insulina lo desplazan fuera de la celula'], correct: 3, explanation: 'El deficit corporal total es de 3 a 5 mmol/kg por la diuresis osmotica, los vomitos y el hiperaldosteronismo, pero la acidosis y la ausencia de insulina sacan el potasio de la celula y enmascaran ese deficit. Al iniciar la insulina la cifra se desploma.', dificultad: 'intermedio' },
  { q: 'Cual es la pauta de insulina intravenosa recomendada en la cetoacidosis diabetica?', options: ['Bolo de 0.5 U/kg y despues una infusion de 0.3 U/kg/h', 'Infusion fija de 10 U/h con independencia del peso y de la glucemia', 'Bolo de 0.1 U/kg y despues 0.1 U/kg/h, o bien 0.14 U/kg/h sin bolo', 'Bolos intermitentes de 0.4 U/kg cada 4 horas sin infusion'], correct: 2, explanation: 'Las dos pautas son equivalentes: bolo de 0.1 U/kg seguido de una infusion de 0.1 U/kg/h, o directamente una infusion de 0.14 U/kg/h sin bolo. Dosis mayores no aceleran la resolucion y aumentan el riesgo de hipopotasemia e hipoglucemia.', dificultad: 'intermedio' },
  { q: 'Cual es la velocidad de descenso de la glucosa que se busca con la infusion de insulina?', options: ['De 150 a 200 mg/dL por hora', 'De 50 a 75 mg/dL por hora', 'De 10 a 20 mg/dL por hora', 'Lo mas rapido que tolere el paciente'], correct: 1, explanation: 'El objetivo es un descenso de 50 a 75 mg/dL/h. Si en la primera hora no baja al menos un 10%, se administra un bolo de 0.14 U/kg y se continua. Un descenso mas rapido aumenta el riesgo de edema cerebral.', dificultad: 'intermedio' },
  { q: 'Que se hace cuando la glucosa baja a 200 a 250 mg/dL durante el tratamiento de la cetoacidosis?', options: ['Suspender la insulina y continuar solo con suero salino', 'Mantener la misma infusion y no modificar los fluidos', 'Pasar directamente a insulina subcutanea de accion rapida', 'Anadir dextrosa y reducir la infusion, sin suspender la insulina'], correct: 3, explanation: 'Se anade dextrosa al 5 o al 10% y se baja la infusion a 0.02 a 0.05 U/kg/h, manteniendo la glucosa en 150 a 200 mg/dL. La insulina se mantiene porque es lo que cierra el anion gap; suspenderla al normalizar la glucosa reabre la cetosis.', dificultad: 'intermedio' },
  { q: 'Que cristaloide prefiere el consenso ADA/EASD de 2024 para la reposicion inicial y por que?', options: ['Una solucion balanceada, porque el salino produce hipercloremia', 'Suero salino 0.9%, porque expande mas el espacio intravascular', 'Suero glucosalino, porque aporta sustrato energetico desde el inicio', 'Albumina al 5%, porque mantiene mejor la presion oncotica del plasma'], correct: 0, explanation: 'Las soluciones balanceadas (Ringer lactato, Plasma-Lyte) se prefieren al salino 0.9%, cuyo exceso de cloro genera una acidosis metabolica hipercloremica que retrasa la resolucion de la cetoacidosis. Los ensayos SMART y SCOPE-DKA apoyan esa preferencia.', dificultad: 'dificil' },
  { q: 'Que parametro guia la eleccion del tipo de suero tras la primera hora de reposicion?', options: ['La glucemia capilar en ese momento', 'El bicarbonato de la gasometria venosa', 'El anion gap corregido por la albumina', 'El sodio corregido por la hiperglucemia'], correct: 3, explanation: 'Con el sodio corregido normal o alto se pasa a salino al 0.45%; con el sodio corregido bajo se mantiene salino al 0.9%. El sodio medido esta falsamente bajo por la hiperglucemia y no sirve para decidir.', dificultad: 'intermedio' },
  { q: 'Cuando esta indicado el bicarbonato en la cetoacidosis diabetica?', options: ['Cuando el bicarbonato sea menor de 10 mmol/L', 'En toda cetoacidosis grave para acelerar la resolucion', 'Solo con pH menor de 6.9 a 7.0, y no de rutina', 'Cuando el anion gap supera los 20 mmol/L'], correct: 2, explanation: 'No se usa de rutina. Solo se considera con pH menor de 6.9 a 7.0 (100 mmol en 400 mL con 20 mmol de cloruro potasico en 2 h). Sus riesgos son hipopotasemia, acidosis paradojica del sistema nervioso central, edema cerebral y retraso en la resolucion de la cetosis.', dificultad: 'intermedio' },
  { q: 'Cuando se repone fosfato en la cetoacidosis diabetica?', options: ['Solo si es menor de 1.0 mg/dL o hay disfuncion cardiaca o respiratoria', 'En todos los pacientes desde la primera hora del tratamiento', 'Cuando el fosfato baje por debajo de 2.5 mg/dL en dos controles', 'Solo si el potasio esta por encima de 5.2 mmol/L de forma mantenida'], correct: 0, explanation: 'La reposicion sistematica de fosfato no ha mostrado beneficio y puede causar hipocalcemia. Se reserva a fosfato menor de 1.0 mg/dL o a la presencia de disfuncion cardiaca, anemia hemolitica o depresion respiratoria, en forma de fosfato potasico.', dificultad: 'dificil' },
  { q: 'Cuales son los criterios de resolucion de la cetoacidosis diabetica?', options: ['Glucosa menor de 150 mg/dL y cetonuria negativa en dos muestras seguidas', 'Glucosa menor de 200 y dos de: bicarbonato 15, pH mayor de 7.30, anion gap 12', 'Bicarbonato mayor de 22 mmol/L y potasio dentro del rango de normalidad', 'Desaparicion de la respiracion de Kussmaul y del dolor abdominal referido'], correct: 1, explanation: 'Se exige glucosa menor de 200 mg/dL mas al menos dos de los tres criterios bioquimicos. El consenso de 2024 prefiere guiarse por el cierre del anion gap o por un beta-hidroxibutirato menor de 0.6 mmol/L, no por la glucosa aislada.', dificultad: 'intermedio' },
  { q: 'Que significa un bicarbonato que sigue bajo cuando el anion gap ya se ha normalizado?', options: ['Una cetoacidosis persistente que obliga a subir la infusion de insulina', 'Una acidosis hipercloremica por el salino, que no requiere tratamiento', 'Una acidosis lactica sobreanadida por hipoperfusion mantenida', 'Un error de laboratorio que obliga a repetir la gasometria venosa'], correct: 1, explanation: 'El exceso de cloro del salino 0.9% desplaza bicarbonato y genera una acidosis con anion gap normal que se resuelve sola en 24 a 48 h. Por eso la resolucion se sigue con el anion gap y no con el bicarbonato aislado.', dificultad: 'dificil' },
  { q: 'Como se hace la transicion de la insulina intravenosa a la subcutanea?', options: ['Administrando la basal subcutanea 1 a 2 horas antes de parar la infusion', 'Suspendiendo la infusion y poniendo la basal en ese mismo momento', 'Suspendiendo la infusion y esperando a la primera glucemia alta', 'Iniciando solo bolos de rapida con las comidas durante 24 horas'], correct: 0, explanation: 'La insulina regular intravenosa tiene una vida media de unos 7 minutos: si se corta sin solapar, la cetosis reaparece en pocas horas. La basal subcutanea se administra 1 a 2 h antes de retirar la infusion, y solo con la crisis resuelta y el paciente capaz de comer.', dificultad: 'intermedio' },
  { q: 'Cual es la velocidad maxima a la que debe descender la osmolalidad efectiva en el estado hiperosmolar?', options: ['10 mOsm/kg por hora', '1 mOsm/kg por hora', '20 mOsm/kg por hora', '3 mOsm/kg por hora'], correct: 3, explanation: 'La osmolalidad no debe bajar mas de 3 mOsm/kg/h ni el sodio corregirse mas de 10 mmol/L en 24 h. Una correccion mas rapida provoca edema cerebral por entrada de agua en la celula, que se habia adaptado con osmoles idiogenicos.', dificultad: 'intermedio' },
  { q: 'Que particularidad tiene la insulina en el tratamiento del estado hiperosmolar?', options: ['Se administra a doble dosis por la resistencia extrema a la insulina', 'Se sustituye por analogo rapido subcutaneo en cualquier escenario', 'Se inicia despues de la reposicion inicial de volumen y a dosis menor', 'No se utiliza porque la rehidratacion por si sola es suficiente'], correct: 2, explanation: 'La insulina desplaza agua al interior de la celula, asi que darla antes de reponer volumen agrava la hipovolemia. Se inicia tras la carga inicial, a 0.05 a 0.1 U/kg/h, con objetivo de glucosa de 250 a 300 mg/dL hasta normalizar la osmolalidad y el sensorio.', dificultad: 'dificil' },
  { q: 'En que momento aparece tipicamente el edema cerebral durante el tratamiento de una crisis hiperglucemica?', options: ['Entre 4 y 12 horas despues de iniciar la reposicion', 'En los primeros 30 minutos, antes de cualquier tratamiento', 'A partir del quinto dia de ingreso', 'Solo tras la transicion a insulina subcutanea'], correct: 0, explanation: 'Aparece tipicamente entre 4 y 12 h del inicio del tratamiento, cuando la osmolalidad plasmatica ya ha bajado. Cualquier deterioro neurologico tras varias horas de mejoria analitica obliga a sospecharlo.', dificultad: 'intermedio' },
  { q: 'Cual es la conducta ante la sospecha de edema cerebral durante el tratamiento?', options: ['Solicitar una tomografia craneal urgente antes de cualquier tratamiento', 'Aumentar la velocidad de infusion de fluidos isotonicos de inmediato', 'Administrar un bolo de bicarbonato para corregir con rapidez el pH', 'Tratar de inmediato con manitol o salino hipertonico, y la imagen despues'], correct: 3, explanation: 'Es un diagnostico clinico y urgente: manitol al 20% a 0.5 a 1 g/kg en 20 minutos, o salino hipertonico al 3% a 5 a 10 mL/kg en 30 minutos, con elevacion de la cabecera y reduccion del aporte de fluidos. La tomografia se hace despues y puede ser normal en fases precoces.', dificultad: 'intermedio' },
  { q: 'Como se trata la cetoacidosis euglucemica por inhibidores de SGLT2?', options: ['Solo con reposicion de volumen, sin insulina, porque la glucosa es normal', 'Igual que la cetoacidosis, pero con dextrosa desde el inicio', 'Con bicarbonato intravenoso por la ausencia de hiperglucemia franca', 'Retirando el farmaco y esperando la resolucion espontanea del cuadro'], correct: 1, explanation: 'La insulina sigue siendo necesaria para cerrar el anion gap, pero como la glucemia ya es baja hay que administrar suero glucosado desde el principio y ajustar la dextrosa, no la insulina, para mantener la glucosa en 150 a 200 mg/dL. Ademas se suspende el inhibidor de SGLT2.', dificultad: 'dificil' },
  { q: 'Con cuanta antelacion se suspende un inhibidor de SGLT2 antes de una cirugia mayor?', options: ['La manana de la intervencion', '24 horas antes', 'De 3 a 4 dias antes', 'No hace falta suspenderlo'], correct: 2, explanation: 'Se suspende 3 a 4 dias antes de una cirugia mayor y ante cualquier enfermedad aguda con ayuno, y no se reinicia hasta que el paciente come con normalidad y esta estable. El ayuno y el estres quirurgico sobre el farmaco precipitan la cetoacidosis euglucemica.', dificultad: 'intermedio' },
  { q: 'Con que se correlaciona la intensidad del dolor abdominal en la cetoacidosis diabetica?', options: ['Con el grado de deshidratacion del paciente', 'Con el nivel absoluto de hiperglucemia', 'Con la gravedad de la acidosis metabolica', 'Con la concentracion de potasio serico'], correct: 2, explanation: 'El dolor abdominal aparece en el 40 al 75% de las cetoacidosis y su intensidad se correlaciona con la gravedad de la acidosis, no con la deshidratacion ni con la glucemia. Cede al corregir el pH; si persiste despues, hay que buscar una causa estructural.', dificultad: 'dificil' },
  { q: 'Que infeccion fungica tiene una asociacion clasica con la cetoacidosis diabetica y como se trata?', options: ['La candidiasis esofagica, con fluconazol oral en pauta corta', 'La mucormicosis rinocerebral, con anfotericina B y desbridamiento', 'La aspergilosis pulmonar invasiva, con voriconazol en monoterapia oral', 'La criptococosis meningea, con anfotericina B mas flucitosina'], correct: 1, explanation: 'La acidosis libera hierro de la transferrina y, con la hiperglucemia, favorece el crecimiento de los Mucorales. Exige anfotericina B liposomal inmediata ante la sospecha y desbridamiento quirurgico urgente y repetido, porque la trombosis vascular impide que el antifungico alcance el tejido invadido.', dificultad: 'dificil' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 22 anos sin antecedentes acude por vomitos, dolor abdominal y respiracion profunda desde hace 12 horas. Glucosa 480 mg/dL, pH venoso 7.08, bicarbonato 8 mmol/L, sodio 130, cloro 96, potasio 4.8 mmol/L y beta-hidroxibutirato 5.6 mmol/L. Pesa 60 kg.',
    steps: [
      { q: 'Cual es el diagnostico y su gravedad?', options: ['Cetoacidosis diabetica grave', 'Cetoacidosis diabetica moderada', 'Estado hiperosmolar hiperglucemico', 'Acidosis lactica por hipoperfusion'], correct: 0, explanation: 'Cumple los tres criterios (glucosa mayor de 200, beta-hidroxibutirato mayor de 3.0 y pH menor de 7.30 con bicarbonato menor de 18) y el pH menor de 7.10 con bicarbonato menor de 10 la clasifica como grave, lo que indica ingreso en cuidados intensivos o intermedios.' },
      { q: 'Cual es el primer paso del tratamiento?', options: ['Administrar bicarbonato por el pH menor de 7.10', 'Iniciar la insulina de inmediato sin esperar analitica', 'Pasar analogo rapido subcutaneo cada 2 horas en planta', 'Reponer volumen y comprobar el potasio antes de la insulina'], correct: 3, explanation: 'Se inicia la reposicion con 15 a 20 mL/kg de cristaloide en la primera hora y se comprueba el potasio antes de la insulina. Con 4.8 mmol/L se puede iniciar la insulina anadiendo 20 a 30 mmol de potasio por litro de fluido.' },
      { q: 'Que pauta de insulina intravenosa corresponde a esta paciente?', options: ['Bolo de 30 U y despues una infusion de 18 U/h', 'Bolo de 6 U y despues 6 U/h, o bien 8.4 U/h sin bolo', 'Infusion fija de 2 U/h con independencia del peso', 'Un bolo de 12 U cada 4 horas sin infusion continua asociada'], correct: 1, explanation: 'Con 60 kg: bolo de 0.1 U/kg (6 U) seguido de 0.1 U/kg/h (6 U/h), o bien 0.14 U/kg/h (8.4 U/h) sin bolo; las dos pautas son equivalentes. El objetivo es bajar la glucosa 50 a 75 mg/dL/h.' }
    ],
    explanation: 'Una mujer joven con vomitos, Kussmaul, glucosa 480, pH 7.08 y beta-hidroxibutirato 5.6 tiene una cetoacidosis diabetica grave: se repone volumen, se comprueba el potasio antes de la insulina y se pauta insulina regular intravenosa a 0.1 U/kg/h con bolo, o 0.14 U/kg/h sin bolo.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varon de 35 anos con DM1 llega por una cetoacidosis tras varios dias de vomitos y omision de la insulina. Glucosa 410 mg/dL, pH 7.15, bicarbonato 11 mmol/L y potasio 3.0 mmol/L. La enfermera pregunta si prepara ya la infusion de insulina.',
    steps: [
      { q: 'Que se responde?', options: ['Si: se inicia la insulina y se repone el potasio en paralelo desde ahora', 'Si, pero a la mitad de la dosis habitual por el potasio bajo inicial', 'No: reponer potasio primero y no iniciar la insulina hasta superar 3.3', 'No: primero hay que corregir la acidosis con bicarbonato intravenoso'], correct: 2, explanation: 'Con potasio menor de 3.3 mmol/L la insulina esta contraindicada hasta reponerlo: lo desplazaria al interior de la celula y podria provocar una arritmia mortal o paralisis respiratoria. Se repone a 10 a 20 mmol/h y se inicia la insulina al superar 3.3.' },
      { q: 'Que otra medida se pone en marcha mientras tanto?', options: ['Bicarbonato intravenoso mientras sube el potasio', 'Analogo rapido subcutaneo hasta que el potasio se corrija', 'Perfusion de glucosa al 10% para proteger el sistema nervioso', 'Reposicion de volumen con cristaloide y busqueda del precipitante'], correct: 3, explanation: 'La reposicion de volumen se inicia desde la primera hora con independencia del potasio, y en paralelo se busca el precipitante (aqui, la omision de insulina y los vomitos). El bicarbonato no esta indicado con un pH de 7.15.' },
      { q: 'Por que el potasio bajo inicial es especialmente preocupante en este paciente?', options: ['Porque indica un deficit corporal muy grande enmascarado por la acidosis', 'Porque significa que la cetoacidosis ya se esta resolviendo sola', 'Porque impide por completo la reposicion inicial de volumen', 'Porque obliga a administrar bicarbonato para desplazarlo al plasma'], correct: 0, explanation: 'La acidosis y la falta de insulina desplazan potasio fuera de la celula, de modo que un potasio ya bajo al ingreso implica un deficit corporal total muy superior a los 3 a 5 mmol/kg habituales; caera aun mas al iniciar la insulina.' }
    ],
    explanation: 'Un potasio de 3.0 mmol/L en una cetoacidosis obliga a reponerlo antes de iniciar la insulina; mientras tanto se repone volumen y se busca el precipitante. Un potasio ya bajo al ingreso indica un deficit corporal enmascarado especialmente grave.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 81 anos con DM2 e institucionalizado llega confuso tras una semana de deterioro. Glucosa 940 mg/dL, sodio medido 148 mmol/L, pH 7.36, bicarbonato 21 mmol/L y beta-hidroxibutirato 0.8 mmol/L. Pesa 65 kg.',
    steps: [
      { q: 'Cual es el diagnostico y cual es la osmolalidad efectiva aproximada?', options: ['Cetoacidosis diabetica, con osmolalidad efectiva de unos 348 mOsm/kg', 'Estado hiperosmolar, con osmolalidad efectiva de unos 296 mOsm/kg', 'Forma mixta de cetoacidosis y estado hiperosmolar', 'Estado hiperosmolar, con osmolalidad efectiva de unos 348 mOsm/kg'], correct: 3, explanation: 'Osmolalidad efectiva = 2 x 148 + 940/18 = 296 + 52 = 348 mOsm/kg. Con glucosa mayor de 600, pH mayor de 7.30, bicarbonato mayor de 18, beta-hidroxibutirato menor de 3.0 y sensorio alterado, es un estado hiperosmolar puro.' },
      { q: 'Cual es el pilar del tratamiento y a que velocidad debe corregirse?', options: ['Reposicion de volumen, bajando la osmolalidad no mas de 3 mOsm/kg/h', 'Insulina en infusion alta, para normalizar la glucosa en unas 6 horas', 'Bicarbonato intravenoso, para prevenir la acidosis secundaria', 'Suero hipertonico, para evitar el descenso del sodio'], correct: 0, explanation: 'El pilar es la reposicion de volumen, con un deficit de 100 a 200 mL/kg. La osmolalidad no debe bajar mas de 3 mOsm/kg/h ni el sodio corregirse mas de 10 mmol/L en 24 h, para no provocar edema cerebral ni mielinolisis.' },
      { q: 'Cuando y como se inicia la insulina en este paciente?', options: ['Antes que los fluidos, con bolo de 0.1 U/kg', 'Solo cuando la glucosa baje por debajo de 300 mg/dL en dos controles', 'Tras la carga inicial de volumen, a 0.05 a 0.1 U/kg/h', 'No se usa insulina en el estado hiperosmolar'], correct: 2, explanation: 'La insulina desplaza agua al interior de la celula y agrava la hipovolemia si se da antes de reponer volumen. Se inicia despues de la carga inicial, a dosis menor que en la cetoacidosis, con objetivo de glucosa de 250 a 300 mg/dL hasta normalizar la osmolalidad y el sensorio.' }
    ],
    explanation: 'Un anciano institucionalizado con glucosa 940, sodio 148, sin acidosis ni cetosis y con sensorio alterado tiene un estado hiperosmolar con osmolalidad efectiva de 348 mOsm/kg: el pilar es el volumen, con correccion lenta (no mas de 3 mOsm/kg/h) e insulina a dosis baja despues de la carga inicial.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 52 anos con DM2 en tratamiento con metformina y dapagliflozina ingresa para una colecistectomia programada. Tras 14 horas de ayuno refiere nauseas y malestar. Glucosa capilar 172 mg/dL, pH 7.19, bicarbonato 12 mmol/L, anion gap 24 y beta-hidroxibutirato 4.8 mmol/L.',
    steps: [
      { q: 'Cual es el diagnostico?', options: ['Acidosis lactica secundaria a la metformina', 'Cetoacidosis euglucemica por el inhibidor de SGLT2', 'Cetosis de ayuno sin trascendencia clinica real', 'Acidosis metabolica hipercloremica del preoperatorio inmediato'], correct: 1, explanation: 'Hay acidosis con anion gap elevado y cetonemia franca (beta-hidroxibutirato 4.8) con una glucemia solo levemente alta, en una paciente que toma un inhibidor de SGLT2 y esta en ayuno prequirurgico: es una cetoacidosis euglucemica. La glucemia tranquilizadora es la trampa.' },
      { q: 'Que diferencia el tratamiento respecto de una cetoacidosis convencional?', options: ['Se administra dextrosa desde el inicio junto con la insulina intravenosa', 'Se trata unicamente con volumen, sin insulina, porque la glucosa es normal', 'Se administra bicarbonato porque el anion gap es muy alto', 'Se sustituye la insulina por un analogo rapido subcutaneo'], correct: 0, explanation: 'La insulina sigue siendo necesaria para cerrar el anion gap, pero la glucemia ya es baja: se pone suero glucosado desde el principio y se ajusta la dextrosa, no la insulina, para mantener la glucosa entre 150 y 200 mg/dL. Ademas se suspende el inhibidor de SGLT2.' },
      { q: 'Como se podria haber evitado el episodio?', options: ['Administrando insulina basal la noche previa a la intervencion', 'Suspendiendo la dapagliflozina 3 a 4 dias antes de la cirugia', 'Acortando el ayuno preoperatorio a 6 horas', 'Sustituyendo la metformina por una sulfonilurea'], correct: 1, explanation: 'Se recomienda suspender los inhibidores de SGLT2 3 a 4 dias antes de una cirugia mayor y ante enfermedad aguda con ayuno, y no reiniciarlos hasta que el paciente coma con normalidad y este estable.' }
    ],
    explanation: 'Una acidosis con anion gap alto y cetonemia franca con glucemia de 172 mg/dL en una paciente con dapagliflozina en ayuno prequirurgico es una cetoacidosis euglucemica: se trata como una cetoacidosis pero con dextrosa desde el inicio, y se previene suspendiendo el farmaco 3 a 4 dias antes.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 28 anos ingresado por cetoacidosis diabetica lleva 14 horas de tratamiento. Ahora: glucosa 168 mg/dL, pH venoso 7.33, bicarbonato 16 mmol/L, sodio 140, cloro 112 mmol/L y anion gap 12. Esta alerta, sin nauseas, y quiere comer.',
    steps: [
      { q: 'Se cumplen los criterios de resolucion de la cetoacidosis?', options: ['No: el bicarbonato de 16 impide considerarla resuelta todavia', 'No: hace falta que el bicarbonato supere los 22 mmol/L', 'Si: glucosa menor de 200 y los tres criterios bioquimicos', 'No se puede saber sin repetir el beta-hidroxibutirato en sangre'], correct: 2, explanation: 'Glucosa menor de 200 mg/dL mas al menos dos de los tres criterios: bicarbonato de 15 o mayor (16), pH venoso mayor de 7.30 (7.33) y anion gap de 12 o menor (12). Se cumplen los tres, asi que la cetoacidosis esta resuelta.' },
      { q: 'Como se interpreta que el bicarbonato siga en 16 con el cloro en 112?', options: ['Es una cetoacidosis persistente que obliga a subir la insulina', 'Es una acidosis lactica por hipoperfusion tisular mantenida', 'Es un error de laboratorio que obliga a repetir la muestra', 'Es una acidosis hipercloremica del salino, sin tratamiento'], correct: 3, explanation: 'El anion gap ya esta normal y el cloro elevado: el exceso de cloro del salino ha desplazado bicarbonato. Es una acidosis con anion gap normal que se corrige sola en 24 a 48 h; por eso la resolucion se sigue con el anion gap y no con el bicarbonato.' },
      { q: 'Como se hace la transicion a insulina subcutanea?', options: ['Parar la infusion y poner la basal en ese mismo momento', 'Parar la infusion y esperar a la primera glucemia por encima de 200 mg/dL', 'Administrar la basal subcutanea 1 a 2 h antes de parar la infusion', 'Mantener solo bolos de rapida con las comidas durante 24 h'], correct: 2, explanation: 'La insulina regular intravenosa tiene una vida media de unos 7 minutos: hay que solapar la basal subcutanea 1 a 2 h antes de retirar la infusion, o la cetosis reaparece. Se hace solo con la crisis resuelta y el paciente capaz de comer, como es el caso.' }
    ],
    explanation: 'Con glucosa 168, pH 7.33, bicarbonato 16 y anion gap 12 la cetoacidosis esta resuelta; el bicarbonato aun bajo con cloro alto es una acidosis hipercloremica del salino que no requiere tratamiento, y la transicion se hace solapando la basal subcutanea 1 a 2 h antes de parar la infusion.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Chico de 17 anos ingresado por cetoacidosis diabetica de debut. A las 7 horas de tratamiento, con la analitica en clara mejoria, refiere cefalea intensa y se muestra progresivamente somnoliento. La frecuencia cardiaca ha bajado de 120 a 58 lpm y la presion arterial ha subido.',
    steps: [
      { q: 'Cual es la sospecha diagnostica?', options: ['Hipoglucemia por exceso de insulina', 'Trombosis de senos venosos cerebrales', 'Acidosis paradojica del sistema nervioso central', 'Edema cerebral'], correct: 3, explanation: 'Deterioro neurologico entre 4 y 12 h del inicio del tratamiento, con cefalea, somnolencia y bradicardia con hipertension (triada de Cushing), en un adolescente con cetoacidosis de debut: es un edema cerebral hasta que se demuestre lo contrario.' },
      { q: 'Cual es la conducta inmediata?', options: ['Tomografia craneal urgente antes de iniciar cualquier tratamiento', 'Manitol o salino hipertonico al 3% sin esperar a la imagen', 'Bolo de suero salino isotonico para mejorar la perfusion cerebral', 'Suspender la insulina y esperar la evolucion neurologica'], correct: 1, explanation: 'Es un diagnostico clinico y urgente: manitol al 20% a 0.5 a 1 g/kg en 20 minutos, o salino hipertonico al 3% a 5 a 10 mL/kg en 30 minutos, elevando la cabecera y reduciendo el aporte de fluidos. La tomografia se hace despues y puede ser normal en fases precoces.' },
      { q: 'Que factor del tratamiento se asocia a este cuadro?', options: ['Un descenso demasiado rapido de la osmolalidad', 'Un aporte insuficiente de potasio en las primeras horas', 'Una infusion de insulina por debajo de 0.1 U/kg/h', 'La ausencia de profilaxis antitrombotica'], correct: 0, explanation: 'La celula cerebral se adapta a la hiperosmolalidad con osmoles idiogenicos; si la osmolalidad plasmatica baja mas rapido de lo que esos osmoles se eliminan, entra agua en la celula. Contribuyen tambien el volumen elevado de fluidos en las primeras 4 h, el uso de bicarbonato y un sodio corregido que no asciende.' }
    ],
    explanation: 'Cefalea, somnolencia y bradicardia con hipertension a las 7 horas de tratar una cetoacidosis de debut en un adolescente es un edema cerebral: se trata de inmediato con manitol o salino hipertonico sin esperar a la tomografia, y se previene corrigiendo la osmolalidad despacio.'
  }
];

export const flashcards = [
  { front: 'Diferencia fisiopatologica entre CAD y EHH', back: 'En el EHH queda insulina residual suficiente para frenar la lipolisis (hace falta muy poca); en la CAD el deficit es absoluto o casi.' },
  { front: 'Criterios de CAD (ADA/EASD 2024)', back: 'Glucosa 200 mg/dL o mayor (o diabetes conocida) + beta-hidroxibutirato 3.0 mmol/L o mayor + pH menor de 7.30 o bicarbonato menor de 18.' },
  { front: 'Criterios de EHH', back: 'Glucosa 600 o mayor + osmolalidad efectiva mayor de 300 (clasico: 320) + pH mayor de 7.30 y bicarbonato mayor de 18 + sensorio alterado.' },
  { front: 'Osmolalidad efectiva', back: '2 x sodio + glucosa/18. Excluye la urea, que cruza libremente las membranas.' },
  { front: 'Gravedad de la CAD', back: 'Leve pH 7.20-7.29 y HCO3 15-17; moderada pH 7.10-7.19 y HCO3 10-14; grave pH menor de 7.10 y HCO3 menor de 10.' },
  { front: 'Precipitante mas frecuente de la crisis hiperglucemica', back: 'La infeccion (30 al 50%); en el joven con DM1, la omision de insulina.' },
  { front: 'Lo que hay que mirar antes de la primera dosis de insulina', back: 'El potasio.' },
  { front: 'Potasio menor de 3.3 mmol/L', back: 'NO iniciar la insulina. Reponer 10 a 20 mmol/h hasta superar 3.3.' },
  { front: 'Potasio de 3.3 a 5.2 mmol/L', back: 'Anadir 20 a 30 mmol por litro de fluido; objetivo de 4 a 5 mmol/L.' },
  { front: 'Deficit corporal total de potasio en la CAD', back: 'De 3 a 5 mmol/kg, aunque el potasio serico inicial parezca normal o alto.' },
  { front: 'Pauta de insulina intravenosa en la CAD', back: 'Bolo 0.1 U/kg + 0.1 U/kg/h, o bien 0.14 U/kg/h sin bolo (equivalentes).' },
  { front: 'Velocidad objetivo de descenso de la glucosa', back: '50 a 75 mg/dL por hora.' },
  { front: 'Que hacer con glucosa de 200 a 250 mg/dL en la CAD', back: 'Anadir dextrosa y bajar la infusion a 0.02-0.05 U/kg/h; NO suspender la insulina hasta cerrar el anion gap.' },
  { front: 'Fluido de eleccion segun el consenso de 2024', back: 'Cristaloide balanceado (Ringer lactato, Plasma-Lyte) mejor que salino 0.9%, que produce acidosis hipercloremica.' },
  { front: 'Que guia la eleccion del suero tras la primera hora', back: 'El sodio corregido: normal o alto, salino 0.45%; bajo, salino 0.9%.' },
  { front: 'Volumen de la primera hora', back: '15 a 20 mL/kg (1 a 1.5 L) de cristaloide; luego 250 a 500 mL/h.' },
  { front: 'Indicacion del bicarbonato', back: 'Solo con pH menor de 6.9 a 7.0; nunca de rutina.' },
  { front: 'Indicacion de reponer fosfato', back: 'Solo si es menor de 1.0 mg/dL o hay disfuncion cardiaca, hemolisis o depresion respiratoria.' },
  { front: 'Criterios de resolucion de la CAD', back: 'Glucosa menor de 200 + 2 de: bicarbonato 15 o mayor, pH mayor de 7.30, anion gap 12 o menor. O beta-hidroxibutirato menor de 0.6.' },
  { front: 'Bicarbonato bajo con anion gap ya normal', back: 'Acidosis hipercloremica del salino: se resuelve sola, no es CAD persistente.' },
  { front: 'Regla de la transicion a insulina subcutanea', back: 'Dar la basal 1 a 2 h ANTES de parar la infusion (vida media de la insulina regular intravenosa: 7 minutos).' },
  { front: 'Correccion maxima de la osmolalidad en el EHH', back: '3 mOsm/kg/h; y el sodio, no mas de 10 mmol/L en 24 h.' },
  { front: 'Deficit de agua en el EHH', back: 'De 100 a 200 mL/kg (unos 9 L), frente a unos 100 mL/kg (6 L) en la CAD.' },
  { front: 'Insulina en el EHH', back: 'Despues de la carga inicial de volumen, a 0.05 a 0.1 U/kg/h; objetivo de glucosa 250 a 300 mg/dL.' },
  { front: 'Momento tipico del edema cerebral', back: 'Entre 4 y 12 horas del inicio del tratamiento.' },
  { front: 'Tratamiento del edema cerebral', back: 'Manitol 0.5-1 g/kg en 20 min o salino al 3% 5-10 mL/kg en 30 min, ANTES de la tomografia.' },
  { front: 'Cetoacidosis euglucemica: causa principal hoy', back: 'Inhibidores de SGLT2 (tambien embarazo, ayuno prolongado y hepatopatia).' },
  { front: 'Tratamiento de la cetoacidosis euglucemica', back: 'Igual que la CAD pero con dextrosa desde el inicio; ajustar la dextrosa, no la insulina. Suspender el iSGLT2.' },
  { front: 'Suspension del iSGLT2 antes de cirugia mayor', back: 'De 3 a 4 dias antes; no reiniciar hasta que coma con normalidad y este estable.' },
  { front: 'Dolor abdominal en la CAD', back: 'Su intensidad se correlaciona con la gravedad de la acidosis; cede al corregir el pH.' },
  { front: 'Trampa de la cetonuria por nitroprusiato', back: 'No detecta beta-hidroxibutirato y se positiviza mas al mejorar, cuando este se convierte en acetoacetato.' },
  { front: 'Infeccion fungica clasica de la CAD', back: 'Mucormicosis rinocerebral: anfotericina B liposomal inmediata + desbridamiento quirurgico urgente.' },
  { front: 'Mortalidad de la CAD y del EHH', back: 'CAD menor del 1% en centros con experiencia; EHH del 5 al 20%.' },
  { front: 'Correccion del anion gap por albumina', back: 'Anion gap + 2.5 x (4.0 menos albumina en g/dL); sin corregir se infraestima la acidosis.' }
];
