// topics/traumatismo-craneoencefalico/study.js: Autoevaluación de Traumatismo Craneoencefálico.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Nota de método (ver memoria del proyecto): todas las preguntas se escribieron primero con la
// respuesta correcta en options[0]/correct:0 (trivialmente verificable), y luego se redistribuyó
// la posición de `correct` mecánicamente con un script, sin volver a adivinar cuál texto es el
// correcto. Cada pregunta se releyó completa (options+correct+explanation) tras la
// redistribución para confirmar que options[correct] es realmente la respuesta correcta.

export const quiz = [
  { q: '¿Cómo se clasifica la gravedad del TCE según la Escala de Coma de Glasgow?', options: ['Leve 15, moderado 10-14, severo ≤9', 'Leve ≤8, moderado 9-12, severo 13-15', 'No existe ninguna clasificación estandarizada por GCS', 'Leve 13-15, moderado 9-12, severo ≤8'], correct: 3, explanation: 'El TCE se clasifica según GCS en leve (13-15), moderado (9-12), y severo (≤8), una clasificación que determina la vía de manejo inicial.', dificultad: 'facil' },
  { q: '¿Cuál es la diferencia entre lesión primaria y lesión secundaria en el TCE?', options: ['Ambas ocurren simultáneamente en el momento del impacto sin ninguna diferencia temporal', 'La primaria es siempre prevenible y la secundaria siempre irreversible', 'La primaria ocurre en el momento del impacto y es irreversible; la secundaria se desarrolla después y es potencialmente prevenible', 'Solo existe lesión primaria en el TCE; el concepto de lesión secundaria no aplica'], correct: 2, explanation: 'La lesión primaria ocurre en el momento del impacto y es irreversible; la lesión secundaria se desarrolla en las horas y días siguientes por hipoxia, hipotensión o hipertensión intracraneal, y es potencialmente prevenible.', dificultad: 'facil' },
  { q: '¿Cuáles son los 2 picos característicos de incidencia del TCE?', options: ['Adultos jóvenes (colisiones vehiculares, violencia) y adultos mayores (caídas)', 'Exclusivamente lactantes y adultos mayores, sin ningún caso en adultos jóvenes', 'Exclusivamente mujeres en edad reproductiva', 'El TCE tiene una distribución uniforme sin picos de edad identificables'], correct: 0, explanation: 'El TCE tiene 2 picos característicos de incidencia: adultos jóvenes (colisiones vehiculares, violencia) y adultos mayores (caídas, con frecuencia sobre un cerebro atrófico y en contexto de anticoagulación).', dificultad: 'facil' },
  { q: '¿Cuál es el patrón de lesión más frecuente del TCE?', options: ['Hematoma epidural', 'TCE leve/conmoción cerebral', 'Hematoma subdural crónico', 'Lesión axonal difusa'], correct: 1, explanation: 'El TCE leve/conmoción cerebral es el patrón de lesión más frecuente del TCE en todos los grupos de edad.', dificultad: 'facil' },
  { q: '¿Es necesaria la pérdida franca de la conciencia para diagnosticar una conmoción cerebral?', options: ['Sí, es un requisito absoluto sin el cual no puede diagnosticarse conmoción', 'Solo es necesaria en pacientes mayores de 65 años', 'No, la pérdida de conciencia no es un requisito para el diagnóstico', 'Solo es necesaria si el mecanismo fue deportivo'], correct: 2, explanation: 'La pérdida de conciencia no es un requisito para el diagnóstico de conmoción cerebral; puede o no estar presente.', dificultad: 'intermedio' },
  { q: '¿Por qué se evitan los antiinflamatorios no esteroideos en las primeras 24-48 horas tras un TCE leve?', options: ['Porque están formalmente contraindicados de por vida tras cualquier TCE', 'Por el riesgo teórico de sangrado', 'Porque aceleran la progresión a hematoma subdural crónico', 'No existe ninguna razón real para evitarlos'], correct: 1, explanation: 'Se evitan los antiinflamatorios no esteroideos en las primeras 24-48 horas por el riesgo teórico de sangrado.', dificultad: 'intermedio' },
  { q: '¿Cuál es el origen vascular más frecuente del hematoma epidural?', options: ['Venoso, por rotura de las venas puente', 'Capilar, por daño microvascular difuso', 'Linfático, por obstrucción del drenaje linfático craneal', 'Arterial, con mayor frecuencia por laceración de la arteria meníngea media'], correct: 3, explanation: 'El hematoma epidural es de origen arterial con mayor frecuencia por laceración de la arteria meníngea media, asociada a fractura temporal.', dificultad: 'facil' },
  { q: '¿Qué es el "intervalo lúcido" característico del hematoma epidural?', options: ['El periodo breve de recuperación aparente de la conciencia entre el impacto y el deterioro secundario', 'El tiempo que tarda en formarse la fractura craneal', 'El periodo durante el cual el paciente está completamente asintomático de forma permanente', 'El tiempo de espera antes de solicitar la TC craneal'], correct: 0, explanation: 'El intervalo lúcido es el periodo breve de recuperación aparente de la conciencia entre el impacto y el deterioro neurológico secundario conforme el hematoma se expande.', dificultad: 'intermedio' },
  { q: '¿Cómo se describe la forma característica del hematoma epidural en la TC, y por qué no cruza las suturas?', options: ['En semiluna, porque sigue la curvatura natural del cráneo', 'Redonda y bien circunscrita, sin relación con las suturas craneales', 'Biconvexa (lenticular), porque la duramadre está firmemente adherida al hueso en las líneas de sutura', 'Irregular y difusa, sin ningún patrón geométrico definido'], correct: 2, explanation: 'El hematoma epidural tiene forma biconvexa (lenticular) porque la duramadre está firmemente adherida al hueso en las líneas de sutura, limitando la expansión del hematoma en esos puntos.', dificultad: 'intermedio' },
  { q: '¿Cuál es el manejo de elección de un hematoma epidural sintomático o de tamaño significativo?', options: ['Manejo expectante ambulatorio sin ningún seguimiento', 'Anticoagulación terapéutica inmediata', 'Observación domiciliaria sin ninguna evaluación neuroquirúrgica', 'Evacuación quirúrgica urgente (craneotomía)'], correct: 3, explanation: 'La evacuación quirúrgica urgente (craneotomía) es el manejo de elección de un hematoma epidural sintomático o de tamaño significativo.', dificultad: 'facil' },
  { q: '¿Cuál es el origen vascular del hematoma subdural?', options: ['Venoso, por rotura de las venas puente que cruzan el espacio subdural', 'Arterial, por laceración de la arteria meníngea media', 'Capilar, por daño microvascular cortical difuso', 'Linfático, por obstrucción del drenaje venoso dural'], correct: 0, explanation: 'El hematoma subdural es de origen venoso, por rotura de las venas puente que cruzan el espacio subdural entre la corteza y los senos venosos durales.', dificultad: 'facil' },
  { q: '¿Por qué el hematoma subdural cruza las suturas craneales pero no la línea media, a diferencia del epidural?', options: ['El hematoma subdural nunca cruza ninguna estructura anatómica', 'La sangre venosa se extiende libremente por el espacio subdural (no limitada por suturas) pero está limitada en la línea media por la hoz del cerebro', 'Ambos hematomas tienen exactamente el mismo comportamiento respecto a suturas y línea media', 'La duramadre impide por completo cualquier extensión del hematoma subdural'], correct: 1, explanation: 'La sangre subdural se extiende libremente por ese espacio (no limitada por las suturas, a diferencia del epidural) pero está limitada en la línea media por la hoz del cerebro.', dificultad: 'dificil' },
  { q: '¿Qué población es característica del hematoma subdural crónico?', options: ['Exclusivamente niños menores de 2 años', 'Exclusivamente deportistas de alto rendimiento sin ninguna comorbilidad', 'Exclusivamente pacientes sin ningún factor de riesgo identificable', 'El adulto mayor (atrofia cerebral) y el paciente anticoagulado, con frecuencia sin trauma claro recordado'], correct: 3, explanation: 'El hematoma subdural crónico es característico del adulto mayor (por atrofia cerebral que expande el espacio subdural) y del paciente anticoagulado, con frecuencia sin antecedente traumático claro.', dificultad: 'intermedio' },
  { q: '¿Qué manejo quirúrgico suele ser suficiente para el hematoma subdural crónico sintomático, a diferencia del agudo?', options: ['Craneotomía extensa siempre, igual que en la forma aguda', 'Ningún manejo quirúrgico es posible en la forma crónica', 'Drenaje por trépano (burr hole), dado que la sangre ya está licuada', 'Amputación del hueso craneal afectado'], correct: 2, explanation: 'El drenaje por trépano (burr hole) con frecuencia es suficiente en el hematoma subdural crónico, dado que la sangre ya está licuada y es más fácil de drenar que un coágulo agudo.', dificultad: 'intermedio' },
  { q: '¿Qué mecanismo produce la hemorragia subaracnoidea traumática y la lesión axonal difusa?', options: ['Compresión estática y sostenida sin ningún componente de movimiento', 'Fuerzas de aceleración-desaceleración rotacional', 'Exposición prolongada a hipoxia sin trauma mecánico directo', 'Infección bacteriana ascendente del espacio subaracnoideo'], correct: 1, explanation: 'Las fuerzas de aceleración-desaceleración rotacional producen tanto la rotura de vasos corticales (hemorragia subaracnoidea traumática) como el cizallamiento axonal (lesión axonal difusa).', dificultad: 'intermedio' },
  { q: '¿Por qué la lesión axonal difusa puede ser clínicamente mucho más grave de lo que sugiere la TC inicial?', options: ['Es un daño microscópico que con frecuencia es sutil o no visible en la TC inicial pese a su gravedad clínica real', 'La TC siempre sobreestima la gravedad de la lesión axonal difusa', 'La lesión axonal difusa nunca produce ningún síntoma clínico', 'La TC detecta la lesión axonal difusa con perfecta sensibilidad en todos los casos'], correct: 0, explanation: 'La lesión axonal difusa es un daño microscópico que con frecuencia es sutil en la TC inicial, pese a ser desproporcionadamente grave clínicamente, siendo una causa frecuente de estado vegetativo persistente.', dificultad: 'dificil' },
  { q: '¿Qué doctrina explica por qué un proceso expansivo intracraneal eleva la presión intracraneal una vez agotada la capacidad compensatoria?', options: ['La ley de Starling aplicada al sistema nervioso central', 'El principio de Bernoulli sobre el flujo de líquidos', 'La doctrina de Monro-Kellie (el cráneo es un compartimento rígido de volumen fijo)', 'La ley de Boyle sobre gases a presión constante'], correct: 2, explanation: 'La doctrina de Monro-Kellie explica que el cráneo es un compartimento rígido de volumen fijo; cuando se agota la capacidad compensatoria, la presión intracraneal se eleva progresivamente.', dificultad: 'intermedio' },
  { q: '¿Qué componentes conforman la tríada de Cushing, signo tardío de hipertensión intracraneal grave?', options: ['Hipertensión, bradicardia, y respiración irregular', 'Hipotensión, taquicardia, y taquipnea', 'Fiebre, rigidez de nuca, y fotofobia', 'Hipoglucemia, diaforesis, y temblor'], correct: 0, explanation: 'La tríada de Cushing consiste en hipertensión, bradicardia, y respiración irregular, un signo tardío y ominoso de hipertensión intracraneal grave.', dificultad: 'intermedio' },
  { q: '¿Qué signo clínico clásico indica herniación uncal inminente?', options: ['Miosis bilateral simétrica sin ningún otro hallazgo', 'Midriasis unilateral arreactiva por compresión del III par craneal', 'Nistagmo horizontal aislado', 'Hipoacusia unilateral súbita'], correct: 1, explanation: 'La midriasis unilateral arreactiva, por compresión del III par craneal por el uncus del lóbulo temporal, es el signo clásico de herniación uncal inminente.', dificultad: 'facil' },
  { q: '¿Por qué se evita la hiperventilación profiláctica o prolongada en el manejo de la hipertensión intracraneal?', options: ['Porque siempre aumenta la presión intracraneal en lugar de reducirla', 'Porque no tiene ningún efecto sobre la vasculatura cerebral', 'Porque está asociada a un mayor riesgo de neumotórax', 'Por el riesgo de isquemia cerebral por vasoconstricción excesiva'], correct: 3, explanation: 'La hiperventilación profiláctica o prolongada se evita por el riesgo de isquemia cerebral por vasoconstricción excesiva; solo se usa como medida temporal de rescate ante herniación inminente.', dificultad: 'dificil' },
  { q: '¿Cómo se clasifican las crisis convulsivas postraumáticas según el momento de aparición?', options: ['Inmediatas (&lt;24h), tempranas (día 1-7), y tardías (&gt;7 días)', 'Solo se clasifican en tempranas y tardías, sin categoría inmediata', 'Todas las crisis postraumáticas se consideran del mismo tipo, sin clasificación temporal', 'Se clasifican exclusivamente según la edad del paciente'], correct: 0, explanation: 'Las crisis convulsivas postraumáticas se clasifican en inmediatas (dentro de las 24 horas), tempranas (día 1 a 7), y tardías (después de 7 días).', dificultad: 'facil' },
  { q: '¿Cuánto tiempo se recomienda típicamente la profilaxis anticonvulsivante en el TCE severo con factores de riesgo?', options: ['6 meses', '24 horas exclusivamente', 'De por vida, sin límite de tiempo', '7 días'], correct: 3, explanation: 'La profilaxis anticonvulsivante de corta duración, típicamente 7 días, reduce el riesgo de crisis tempranas sin haber demostrado prevenir la epilepsia postraumática tardía.', dificultad: 'intermedio' },
  { q: '¿Qué signo clínico de aparición tardía (días después del trauma) sugiere fractura de la fosa media (peñasco)?', options: ['Signo de Chvostek', 'Signo de Battle (equimosis retroauricular)', 'Signo de Kernig', 'Signo de Murphy'], correct: 1, explanation: 'El signo de Battle (equimosis retroauricular), de aparición tardía días después del trauma, sugiere fractura de la fosa media (peñasco).', dificultad: 'facil' },
  { q: '¿Qué prueba de laboratorio confirma que un líquido de fuga nasal/ótica es verdaderamente LCR?', options: ['Proteína C reactiva', 'Dímero D', 'Beta-2 transferrina', 'Procalcitonina'], correct: 2, explanation: 'La beta-2 transferrina es un marcador específico de LCR, ausente en moco nasal u otras secreciones, útil para confirmar una fuga de LCR verdadera.', dificultad: 'intermedio' },
  { q: '¿Se recomienda la profilaxis antibiótica de rutina en la fuga de LCR postraumática sin infección activa?', options: ['Sí, está indicada en absolutamente todos los casos sin excepción', 'No, no está recomendada de forma generalizada', 'Solo se recomienda en pacientes pediátricos', 'Solo se recomienda si la fuga es de origen ótico, nunca si es nasal'], correct: 1, explanation: 'La profilaxis antibiótica de rutina en la fuga de LCR NO está recomendada de forma generalizada, dado que no ha demostrado prevenir la meningitis y puede seleccionar organismos resistentes.', dificultad: 'dificil' },
  { q: '¿Cuál es el manejo apropiado ante una fuga de LCR que persiste más allá de 1-2 semanas pese al manejo conservador?', options: ['Continuar el manejo conservador indefinidamente sin ninguna otra intervención', 'Anticoagulación terapéutica', 'Reparación quirúrgica del defecto dural', 'Observación sin ningún seguimiento adicional'], correct: 2, explanation: 'La reparación quirúrgica del defecto dural está indicada si la fuga de LCR persiste más allá de 1-2 semanas pese al manejo conservador.', dificultad: 'intermedio' },
  { q: '¿Qué es el síndrome poscontusional?', options: ['Un hematoma que se forma exclusivamente semanas después de un TCE leve', 'Una complicación exclusiva del TCE severo, nunca del leve', 'Una infección del sistema nervioso central postraumática', 'Constelación de síntomas físicos, cognitivos y emocionales que persisten más allá del periodo esperado de recuperación tras un TCE leve'], correct: 3, explanation: 'El síndrome poscontusional es una constelación de síntomas físicos, cognitivos, y emocionales que persisten más allá del periodo esperado de recuperación (típicamente más de 2-4 semanas) tras un TCE leve.', dificultad: 'intermedio' },
  { q: '¿Qué antecedente aumenta el riesgo de desarrollar síndrome poscontusional?', options: ['Conmoción cerebral previa, migraña preexistente, o ansiedad/depresión de base', 'Ausencia total de cualquier síntoma en la fase aguda', 'Edad menor de 10 años exclusivamente', 'Uso previo de anticoagulantes'], correct: 0, explanation: 'El antecedente de conmoción previa, migraña preexistente, o trastornos de ansiedad/depresión de base aumenta el riesgo de síndrome poscontusional.', dificultad: 'intermedio' },
  { q: '¿A qué población aplica la Canadian CT Head Rule?', options: ['Cualquier paciente con TCE de cualquier gravedad, sin ninguna restricción', 'TCE con GCS 13-15, con pérdida de conciencia, amnesia definida, o desorientación presenciada, dentro de las 24 horas del trauma', 'Exclusivamente pacientes pediátricos menores de 16 años', 'Exclusivamente pacientes con TCE severo (GCS ≤8)'], correct: 1, explanation: 'La Canadian CT Head Rule aplica a TCE con GCS 13-15, con pérdida de conciencia, amnesia definida, o desorientación presenciada, dentro de las 24 horas del trauma.', dificultad: 'intermedio' },
  { q: '¿Cuál es la diferencia entre los criterios de alto riesgo y de mediano riesgo en la Canadian CT Head Rule?', options: ['No existe ninguna diferencia real entre ambas categorías de criterios', 'Los de mediano riesgo son más graves que los de alto riesgo', 'Los criterios de alto riesgo solo aplican a pacientes pediátricos', 'Los de alto riesgo predicen necesidad de intervención neuroquirúrgica; los de mediano riesgo predicen detección de lesión en TC'], correct: 3, explanation: 'Los criterios de alto riesgo identifican la necesidad de intervención neuroquirúrgica; los de mediano riesgo identifican la detección de lesión en la TC.', dificultad: 'dificil' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 22 años sufre un golpe en la cabeza jugando fútbol americano. Breve confusión, sin pérdida de la conciencia. GCS 15 a la evaluación, sin vómito, sin signos de fractura de base de cráneo, sin amnesia significativa, mecanismo no peligroso.',
    steps: [
      { q: '¿Qué diagnóstico es más probable dado este cuadro?', options: ['TCE leve/conmoción cerebral', 'Hematoma epidural', 'Hematoma subdural agudo', 'Lesión axonal difusa'], correct: 0, explanation: 'La confusión breve sin pérdida de conciencia franca, con GCS 15, es característica de una conmoción cerebral (TCE leve), el patrón más frecuente.' },
      { q: 'Aplicando la Canadian CT Head Rule con los datos dados (sin criterios de alto ni mediano riesgo), ¿qué se recomienda?', options: ['TC craneal urgente de todas formas', 'Resonancia magnética inmediata en lugar de TC', 'No se recomienda TC craneal por esta regla', 'Angiografía cerebral urgente'], correct: 2, explanation: 'Sin ningún criterio de alto ni mediano riesgo presente, la Canadian CT Head Rule no recomienda TC craneal en este paciente.' },
      { q: '¿Cuál es el manejo apropiado en este momento?', options: ['Observación clínica con instrucciones claras de signos de alarma, retorno gradual a la actividad', 'Ingreso hospitalario obligatorio con TC diaria', 'Craneotomía profiláctica', 'Anticoagulación profiláctica'], correct: 0, explanation: 'El manejo apropiado es la observación clínica con instrucciones claras de signos de alarma y retorno gradual a la actividad según la tolerancia sintomática.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 19 años sufre un golpe directo en la región temporal durante una caída en bicicleta. Pierde la conciencia brevemente, se recupera y camina normalmente ("se ve bien"), pero 2 horas después presenta cefalea intensa progresiva, vómito, y deterioro del estado de alerta con midriasis derecha.',
    steps: [
      { q: '¿Qué patrón de lesión describe mejor esta secuencia clínica?', options: ['Hematoma subdural crónico', 'Hematoma epidural con intervalo lúcido', 'TCE leve sin lesión estructural', 'Fractura de base de cráneo aislada sin hematoma'], correct: 1, explanation: 'La secuencia de pérdida breve de la conciencia, recuperación aparente (intervalo lúcido), y deterioro neurológico rápido horas después es característica del hematoma epidural.' },
      { q: '¿Qué hallazgo en la TC craneal confirmaría este diagnóstico?', options: ['Colección en semiluna que cruza las suturas craneales', 'Hiperdensidad difusa en surcos y cisternas sin masa focal', 'TC completamente normal sin ningún hallazgo', 'Colección biconvexa hiperdensa que no cruza las suturas craneales'], correct: 3, explanation: 'Una colección biconvexa (lenticular) hiperdensa que no cruza las suturas craneales, con frecuencia asociada a fractura temporal, confirma el hematoma epidural.' },
      { q: 'Con midriasis derecha y deterioro del GCS, ¿cuál es la conducta inmediata?', options: ['Observación ambulatoria con reevaluación en 24 horas', 'Alta con analgésicos y seguimiento en 1 semana', 'Evaluación neuroquirúrgica urgente para evacuación quirúrgica sin demora', 'Iniciar anticoagulación profiláctica'], correct: 2, explanation: 'La midriasis unilateral con deterioro del GCS indica herniación uncal inminente por el hematoma epidural en expansión, requiriendo evacuación quirúrgica urgente sin demora.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 78 años, en tratamiento con warfarina por fibrilación auricular, es traída por su familia por deterioro cognitivo progresivo, cefalea, y marcha inestable en las últimas 3 semanas. No recuerda ningún trauma craneal reciente.',
    steps: [
      { q: '¿Qué diagnóstico se debe sospechar fuertemente dado este cuadro insidioso en una paciente anticoagulada de edad avanzada?', options: ['Hematoma epidural agudo', 'Hematoma subdural crónico', 'Meningitis bacteriana aguda', 'Estado epiléptico no convulsivo'], correct: 1, explanation: 'El deterioro cognitivo insidioso, la cefalea, y la marcha inestable en una paciente anciana anticoagulada, sin trauma recordado, es característico del hematoma subdural crónico.' },
      { q: '¿Por qué la ausencia de un trauma recordado no descarta este diagnóstico?', options: ['El hematoma subdural crónico nunca requiere ningún antecedente traumático de ningún tipo', 'Es imposible que ocurra sin un trauma mayor claramente identificable', 'El hematoma subdural crónico con frecuencia ocurre tras un trauma trivial no recordado, particularmente en el anciano anticoagulado', 'La anticoagulación previene por completo cualquier hematoma subdural'], correct: 2, explanation: 'El hematoma subdural crónico con frecuencia se asocia a un trauma trivial no recordado por el paciente, particularmente en el contexto de atrofia cerebral y anticoagulación.' },
      { q: 'Confirmado el diagnóstico por TC (colección en semiluna, hipodensa, con efecto de masa) y siendo sintomática, ¿cuál es el manejo apropiado además de revertir la anticoagulación?', options: ['Observación exclusivamente, sin ninguna intervención quirúrgica posible', 'Craneotomía extensa siempre obligatoria', 'Radioterapia craneal', 'Drenaje por trépano (burr hole), con frecuencia suficiente en la forma crónica'], correct: 3, explanation: 'El drenaje por trépano (burr hole) con frecuencia es suficiente para el hematoma subdural crónico sintomático, dado que la sangre ya está licuada, junto con la reversión de la anticoagulación.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente con TCE severo (GCS 6) tras colisión vehicular de alta velocidad. TC inicial muestra edema cerebral difuso sin hematoma focal significativo. Se coloca catéter de presión intracraneal, que registra valores progresivamente elevados.',
    steps: [
      { q: 'Con hipertensión intracraneal progresiva, ¿qué doctrina explica por qué el cráneo no puede compensar indefinidamente el aumento de volumen?', options: ['La doctrina de Monro-Kellie (compartimento rígido de volumen fijo)', 'La ley de Starling', 'El principio de Bernoulli', 'La ley de Boyle'], correct: 0, explanation: 'La doctrina de Monro-Kellie explica que el cráneo es un compartimento rígido de volumen fijo; una vez agotada la capacidad compensatoria, la presión intracraneal se eleva progresivamente.' },
      { q: 'El paciente desarrolla midriasis derecha progresiva. ¿Qué tipo de herniación está ocurriendo y qué estructura se comprime?', options: ['Herniación amigdalina, con compresión del bulbo raquídeo', 'Herniación uncal, con compresión del III par craneal', 'Herniación central, sin compresión de ningún par craneal', 'No hay ninguna herniación; la midriasis es un hallazgo incidental sin relación'], correct: 1, explanation: 'La midriasis unilateral progresiva refleja herniación uncal, con el uncus del lóbulo temporal comprimiendo el III par craneal ipsilateral.' },
      { q: 'Pese a las medidas de primera línea (cabecera elevada, sedoanalgesia, normotermia), la presión intracraneal sigue elevada. ¿Cuál es el siguiente paso apropiado?', options: ['Hiperventilación profiláctica sostenida como medida de primera línea', 'Suspender toda intervención y solo observar', 'Iniciar anticoagulación terapéutica', 'Soluciones hiperosmolares (manitol o solución salina hipertónica) y considerar craniectomía descompresiva si es refractaria'], correct: 3, explanation: 'Ante hipertensión intracraneal refractaria a las medidas de primera línea, se escala a soluciones hiperosmolares y, si persiste refractaria, se considera craniectomía descompresiva.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 30 años tras trauma frontal directo presenta equimosis periorbitaria bilateral ("ojos de mapache") y rinorrea clara persistente desde el trauma, hace 5 días.',
    steps: [
      { q: '¿Qué localización de fractura de base de cráneo se sospecha dado el patrón de equimosis periorbitaria bilateral?', options: ['Fosa anterior (lámina cribosa)', 'Fosa media (peñasco)', 'Fosa posterior exclusivamente', 'No hay ninguna fractura de base de cráneo asociada a este signo'], correct: 0, explanation: 'La equimosis periorbitaria bilateral ("ojos de mapache") sugiere fractura de la fosa anterior, comprometiendo la lámina cribosa.' },
      { q: '¿Qué prueba confirmaría que la rinorrea es verdaderamente líquido cefalorraquídeo?', options: ['Proteína C reactiva sérica', 'Cultivo bacteriano de rutina de la secreción nasal', 'Beta-2 transferrina en el líquido', 'Radiografía simple de senos paranasales'], correct: 2, explanation: 'La beta-2 transferrina es un marcador específico de LCR, ausente en secreciones nasales habituales, y confirma que la rinorrea es verdaderamente LCR.' },
      { q: 'Con la fuga persistiendo 5 días, ¿cuál es el manejo apropiado en este momento?', options: ['Continuar manejo conservador (cabecera elevada, evitar Valsalva); NO iniciar profilaxis antibiótica de rutina', 'Iniciar profilaxis antibiótica de amplio espectro de inmediato de forma rutinaria', 'Reparación quirúrgica inmediata sin esperar más tiempo de manejo conservador', 'No requiere ningún seguimiento adicional dado que 5 días ya es tiempo suficiente para descartar cualquier problema'], correct: 0, explanation: 'A los 5 días aún se mantiene el manejo conservador (la ventana esperada de cierre espontáneo es la primera semana); la profilaxis antibiótica de rutina no está recomendada. La reparación quirúrgica se reserva para la fuga que persiste más allá de 1-2 semanas.' }
    ]
  }
];

export const flashcards = [
  { front: 'Clasificación de gravedad del TCE por GCS', back: 'Leve 13-15, moderado 9-12, severo ≤8.' },
  { front: 'Lesión primaria vs. secundaria', back: 'Primaria: en el impacto, irreversible. Secundaria: horas/días después, prevenible.' },
  { front: 'Patrón de TCE más frecuente', back: 'TCE leve/conmoción cerebral.' },
  { front: 'Hematoma epidural: origen y forma en TC', back: 'Arterial (meníngea media); biconvexo, no cruza suturas.' },
  { front: 'Hematoma epidural: signo clásico', back: 'Intervalo lúcido (presente solo en una minoría de casos).' },
  { front: 'Hematoma subdural: origen y forma en TC', back: 'Venoso (venas puente); semiluna, cruza suturas, no cruza línea media.' },
  { front: 'Hematoma subdural crónico: población típica', back: 'Adulto mayor (atrofia cerebral) y paciente anticoagulado.' },
  { front: 'Manejo del subdural crónico sintomático', back: 'Drenaje por trépano (burr hole), con frecuencia suficiente.' },
  { front: 'Mecanismo de HSA traumática y lesión axonal difusa', back: 'Aceleración-desaceleración rotacional.' },
  { front: 'Lesión axonal difusa: relevancia pronóstica', back: 'Causa frecuente de estado vegetativo persistente; puede ser sutil en TC inicial.' },
  { front: 'Doctrina de Monro-Kellie', back: 'Cráneo = compartimento rígido de volumen fijo.' },
  { front: 'Tríada de Cushing', back: 'Hipertensión + bradicardia + respiración irregular (signo tardío).' },
  { front: 'Signo de herniación uncal', back: 'Midriasis unilateral arreactiva (compresión del III par).' },
  { front: 'Por qué evitar hiperventilación profiláctica', back: 'Riesgo de isquemia por vasoconstricción excesiva.' },
  { front: 'Clasificación temporal de crisis postraumáticas', back: 'Inmediatas &lt;24h, tempranas día 1-7, tardías &gt;7 días.' },
  { front: 'Duración típica de profilaxis anticonvulsivante', back: '7 días en TCE severo de alto riesgo.' },
  { front: 'Signo de Battle', back: 'Equimosis retroauricular, tardío, sugiere fractura de fosa media (peñasco).' },
  { front: '"Ojos de mapache"', back: 'Equimosis periorbitaria bilateral, sugiere fractura de fosa anterior.' },
  { front: 'Prueba que confirma fuga de LCR', back: 'Beta-2 transferrina.' },
  { front: 'Profilaxis antibiótica en fuga de LCR', back: 'NO recomendada de rutina.' },
  { front: 'Manejo de fuga de LCR persistente &gt;1-2 semanas', back: 'Reparación quirúrgica del defecto dural.' },
  { front: 'Síndrome poscontusional: definición', back: 'Síntomas persistentes &gt;2-4 semanas tras TCE leve, sin lesión estructural.' },
  { front: 'Factores de riesgo del síndrome poscontusional', back: 'Conmoción previa, migraña preexistente, ansiedad/depresión de base.' },
  { front: 'A quién aplica la Canadian CT Head Rule', back: 'GCS 13-15 + pérdida de conciencia/amnesia/desorientación, &lt;24h del trauma.' },
  { front: 'Canadian CT Head Rule: criterios de alto riesgo', back: 'GCS &lt;15 a 2h, fractura abierta/hundimiento, signos de fx de base, ≥2 vómitos, edad ≥65.' },
  { front: 'Canadian CT Head Rule: criterios de mediano riesgo', back: 'Amnesia ≥30 min antes del impacto, mecanismo peligroso.' },
  { front: 'Alto riesgo vs. mediano riesgo (Canadian CT Head Rule)', back: 'Alto: predice cirugía neuroquirúrgica. Medio: predice lesión en TC.' },
  { front: 'GCS: dónde ver la escala completa', back: 'Tema de Exploración Neurológica (sin calculadora duplicada aquí).' },
  { front: 'Analgesia en TCE leve: qué evitar', back: 'AINEs en las primeras 24-48h (riesgo teórico de sangrado).' },
  { front: 'Craniectomía descompresiva: cuándo', back: 'Hipertensión intracraneal refractaria al manejo médico máximo.' }
];
