// topics/hipertension-arterial/study.js: Autoevaluacion de Hipertension Arterial.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// Metodo (ver memoria del proyecto): las 48 preguntas (30 sueltas + 6 cascadas de 3 pasos) se
// escribieron primero con la respuesta correcta en options[0]/correct:0 (trivialmente
// verificable), y luego se redistribuyo la posicion de `correct` de forma mecanica con un script
// a una secuencia objetivo equilibrada (12 por posicion). Cada pregunta se releyo completa
// (options + correct + explanation) tras la redistribucion. Sin em dash (ver [[feedback-no-em-dash]]).

export const quiz = [
  { q: 'Segun la guia ESC 2024, cual es el umbral de PA de consultorio que define hipertension?', options: ['130/80 mmHg o mayor', '140/90 mmHg o mayor', '120/70 mmHg o mayor', '160/100 mmHg o mayor'], correct: 1, explanation: 'La ESC 2024 mantiene el diagnostico de hipertension en 140/90 mmHg o mayor de consultorio, con una categoria intermedia de PA elevada entre 120-139 / 70-89. La ACC/AHA 2025 usa un umbral mas bajo (130/80 mmHg o mayor para el estadio 2, y 130-139 / 80-89 para el estadio 1).', dificultad: 'facil' },
  { q: 'En la clasificacion ACC/AHA 2025, como se clasifica una PA de consultorio de 134/86 mmHg?', options: ['PA normal', 'PA elevada', 'Estadio 2', 'Estadio 1'], correct: 3, explanation: 'La ACC/AHA 2025 define el estadio 1 como 130-139 mmHg de sistolica o 80-89 de diastolica; 134/86 cae en ese rango. La PA elevada es 120-129 / menor de 80 y el estadio 2 es 140/90 o mayor.', dificultad: 'intermedio' },
  { q: 'Cual es la prueba de referencia para confirmar el diagnostico de hipertension y detectar la HTA de bata blanca?', options: ['La monitorizacion ambulatoria de PA de 24 horas', 'La toma unica de PA en la consulta', 'La automedicion domiciliaria de un solo dia', 'El registro de la PA durante una prueba de esfuerzo'], correct: 0, explanation: 'La MAPA de 24 horas es la prueba de referencia: confirma el diagnostico, identifica la HTA de bata blanca y la enmascarada y valora el patron nocturno. La AMPA es una alternativa valida (7 dias, lecturas por duplicado manana y noche).', dificultad: 'facil' },
  { q: 'Cual es el umbral de hipertension con automedicion domiciliaria o con la media diurna de la MAPA?', options: ['130/80 mmHg o mayor', '140/90 mmHg o mayor', '135/85 mmHg o mayor', '125/75 mmHg o mayor'], correct: 2, explanation: 'El umbral fuera de consultorio para la AMPA y la media diurna de la MAPA es 135/85 mmHg o mayor. La media de 24 horas de la MAPA usa 130/80 y la media nocturna 120/70.', dificultad: 'intermedio' },
  { q: 'Un paciente tiene la PA de consultorio elevada pero la MAPA y la AMPA son normales. Que fenotipo es?', options: ['HTA enmascarada', 'HTA sostenida', 'HTA resistente', 'HTA de bata blanca'], correct: 3, explanation: 'La HTA de bata blanca es una PA de consultorio alta con medicion fuera de consultorio normal; conlleva un riesgo intermedio. La HTA enmascarada es lo contrario (consultorio normal, fuera alta) y tiene un riesgo parecido al de la HTA sostenida.', dificultad: 'intermedio' },
  { q: 'Cual es el fenotipo de un paciente con PA de consultorio normal y MAPA o AMPA elevadas?', options: ['HTA de bata blanca', 'HTA enmascarada', 'Normotension verdadera', 'Pseudohipertension'], correct: 1, explanation: 'La HTA enmascarada es una PA de consultorio normal con medicion fuera de consultorio elevada; su riesgo cardiovascular es similar al de la HTA sostenida, por lo que es importante buscarla en pacientes de alto riesgo o con dano de organo.', dificultad: 'intermedio' },
  { q: 'Que intervencion dietetica ha demostrado reducir el ictus y la mortalidad en un ensayo aleatorizado?', options: ['El aumento del consumo de sodio', 'La restriccion estricta de proteinas', 'El sustituto de sal enriquecido con potasio', 'Los suplementos de calcio y vitamina D'], correct: 2, explanation: 'El estudio SSaSS mostro que sustituir la sal comun por un sustituto con potasio reduce el ictus, los eventos cardiovasculares mayores y la mortalidad en personas con hipertension o antecedente de ictus; se evita en la enfermedad renal avanzada por el riesgo de hiperpotasemia.', dificultad: 'dificil' },
  { q: 'Cual es el objetivo de PA sistolica en la mayoria de los adultos hipertensos, si se tolera?', options: ['120 a 129 mmHg', '130 a 139 mmHg', '140 a 149 mmHg', '110 a 119 mmHg'], correct: 0, explanation: 'La ESC 2024 y la ACC/AHA recomiendan un objetivo de PA sistolica de 120-129 mmHg en la mayoria de los adultos que lo toleren (objetivo global menor de 130/80), individualizado y menos estricto en el anciano fragil.', dificultad: 'intermedio' },
  { q: 'Cual es la estrategia farmacologica inicial recomendada para la mayoria de los hipertensos?', options: ['Monoterapia escalonada empezando por un betabloqueador a dosis alta', 'Monoterapia con un diuretico del asa', 'Tres farmacos distintos a dosis plena desde el inicio', 'Combinacion de dos farmacos a dosis baja en un solo comprimido'], correct: 3, explanation: 'Se inicia con una combinacion doble a dosis baja en un solo comprimido (IECA o ARA-II mas calcioantagonista o diuretico tipo tiazida), que controla mejor la PA y mejora la adherencia frente a la monoterapia escalonada.', dificultad: 'intermedio' },
  { q: 'Que diuretico tipo tiazida se prefiere por su mayor evidencia de reduccion de eventos?', options: ['Hidroclorotiazida a dosis baja', 'Furosemida oral', 'Clortalidona o indapamida', 'Espironolactona en monoterapia'], correct: 2, explanation: 'Se prefieren la clortalidona y la indapamida (tiazidicas de accion prolongada) sobre la hidroclorotiazida por su mayor potencia y evidencia de reduccion de eventos cardiovasculares.', dificultad: 'intermedio' },
  { q: 'Que combinacion de antihipertensivos se debe evitar?', options: ['IECA con calcioantagonista', 'IECA con ARA-II', 'ARA-II con diuretico tipo tiazida', 'Calcioantagonista con diuretico tipo tiazida'], correct: 1, explanation: 'La combinacion de un IECA con un ARA-II no aporta beneficio y aumenta la hiperpotasemia, la lesion renal aguda y la hipotension. Las demas combinaciones de familias distintas son sinergicas y estan recomendadas.', dificultad: 'facil' },
  { q: 'En que situacion estan indicados los betabloqueadores en el tratamiento de la hipertension?', options: ['Solo si coexiste una indicacion especifica concomitante', 'Como primer farmaco en todo hipertenso joven', 'Para bajar la PA de forma rapida en la urgencia hipertensiva', 'Como cuarto farmaco de eleccion en la HTA resistente'], correct: 0, explanation: 'Los betabloqueadores se reservan para indicaciones especificas concomitantes: cardiopatia isquemica, insuficiencia cardiaca con fraccion reducida, control de frecuencia en fibrilacion auricular o embarazo (labetalol). No son de primera linea en la hipertension no complicada.', dificultad: 'intermedio' },
  { q: 'Cual es el cuarto farmaco de eleccion en la HTA resistente?', options: ['Un betabloqueador', 'Un diuretico del asa', 'Espironolactona', 'Un agente de accion central'], correct: 2, explanation: 'El estudio PATHWAY-2 demostro que la espironolactona 25-50 mg es el cuarto farmaco mas eficaz en la HTA resistente, superior al bisoprolol y a la doxazosina, por el papel del exceso relativo de aldosterona y de la retencion de sodio.', dificultad: 'intermedio' },
  { q: 'Que condiciones deben cumplirse antes de anadir espironolactona en la HTA resistente?', options: ['Potasio mayor de 5.0 mmol/L y filtrado glomerular menor de 30', 'Presencia de proteinuria en rango nefrotico', 'Edad menor de 40 anos y ausencia de diabetes', 'Filtrado glomerular mayor de 45 y potasio menor de 4.5 mmol/L'], correct: 3, explanation: 'Se anade espironolactona si el filtrado glomerular es mayor de 45 mL/min y el potasio es menor de 4.5 mmol/L, por el riesgo de hiperpotasemia; despues hay que vigilar el potasio y la funcion renal.', dificultad: 'dificil' },
  { q: 'Cual es la definicion de HTA resistente?', options: ['PA por encima del objetivo tras al menos 6 meses de cambios de estilo de vida intensivos', 'PA sobre el objetivo pese a 3 farmacos a dosis optimas, uno un diuretico', 'Cualquier hipertension que precise mas de un farmaco', 'HTA que solo se controla en el consultorio y no en el domicilio'], correct: 1, explanation: 'La HTA resistente es la PA que permanece por encima del objetivo pese a 3 farmacos a dosis optimas o maximas toleradas, uno de ellos un diuretico, con adherencia confirmada y tras descartar la HTA de bata blanca y las causas secundarias. La controlada con 4 o mas farmacos tambien se considera resistente.', dificultad: 'intermedio' },
  { q: 'Cual es la causa mas frecuente de pseudorresistencia al tratamiento antihipertensivo?', options: ['La mala adherencia al tratamiento', 'Un feocromocitoma oculto', 'La coartacion de aorta', 'La estenosis bilateral de las arterias renales'], correct: 0, explanation: 'La causa mas frecuente de pseudorresistencia es la baja adherencia; le siguen la tecnica de medicion incorrecta, un manguito inadecuado, la HTA de bata blanca y las dosis o combinaciones suboptimas. Hay que descartarlas antes de etiquetar a un paciente como resistente verdadero.', dificultad: 'intermedio' },
  { q: 'Que causa de HTA secundaria se debe cribar de forma prioritaria en todo paciente con HTA resistente?', options: ['La displasia fibromuscular renal', 'El sindrome de Cushing', 'El hiperaldosteronismo primario', 'La coartacion de aorta'], correct: 2, explanation: 'El hiperaldosteronismo primario aparece en cerca del 20% de las HTA resistentes y a menudo pasa desapercibido; se criba con el cociente aldosterona/renina. Es tratable con antagonistas del receptor mineralocorticoide o con suprarrenalectomia si lateraliza.', dificultad: 'intermedio' },
  { q: 'Cual es la prueba de cribado del hiperaldosteronismo primario?', options: ['El cortisol libre en orina de 24 horas', 'El cociente aldosterona/renina', 'Las metanefrinas plasmaticas libres', 'La renina plasmatica aislada'], correct: 1, explanation: 'El cribado del hiperaldosteronismo primario es el cociente aldosterona/renina, medido en condiciones adecuadas (potasio corregido, sodio libre, muestra matutina, suspension previa de los antagonistas del receptor mineralocorticoide). Un cociente elevado con aldosterona alta obliga a una prueba de confirmacion.', dificultad: 'intermedio' },
  { q: 'Que hallazgo de laboratorio es una pista clasica de hiperaldosteronismo primario?', options: ['Hiperpotasemia persistente con acidosis metabolica de brecha normal', 'Hipernatremia grave con poliuria', 'Hipoglucemia de ayuno recurrente', 'Hipopotasemia espontanea o desproporcionada al diuretico'], correct: 3, explanation: 'La hipopotasemia espontanea, o desproporcionada a una dosis baja de diuretico, junto con una alcalosis metabolica leve, es una pista clasica de hiperaldosteronismo primario, aunque muchos pacientes tienen el potasio normal.', dificultad: 'intermedio' },
  { q: 'Que distingue a la emergencia hipertensiva de la urgencia hipertensiva?', options: ['La presencia de dano agudo de organo en curso', 'Una cifra de PA sistolica mayor de 200 mmHg', 'La presencia de cefalea intensa', 'El antecedente de mala adherencia al tratamiento'], correct: 0, explanation: 'La emergencia hipertensiva se define por dano agudo de organo en curso (encefalopatia, ictus, edema agudo de pulmon, sindrome coronario, diseccion, lesion renal aguda, retinopatia grado III-IV, eclampsia); la urgencia es una PA muy elevada sin ese dano. La cifra absoluta de PA no es lo que las separa.', dificultad: 'facil' },
  { q: 'Cual es el manejo apropiado de una urgencia hipertensiva?', options: ['Nitroprusiato intravenoso para normalizar la PA en una hora', 'Farmacos orales con reduccion gradual de la PA en horas o dias', 'Nifedipino sublingual de accion corta repetido', 'Ingreso en cuidados intensivos con linea arterial'], correct: 1, explanation: 'La urgencia hipertensiva se maneja de forma ambulatoria o en observacion breve: reposo, reanudacion o intensificacion del tratamiento oral y reduccion gradual de la PA en horas o dias. El descenso brusco (nifedipino sublingual, nitroprusiato) puede provocar isquemia cerebral, coronaria o renal.', dificultad: 'intermedio' },
  { q: 'Cual es el objetivo general de reduccion de la PA en la primera hora de una emergencia hipertensiva?', options: ['Normalizar la PA por debajo de 120/80 mmHg', 'Reducir la PA sistolica a menos de 100 mmHg', 'Mantener la PA sin cambios hasta tener la TC', 'Reducir la PA media un 20 a 25%'], correct: 3, explanation: 'El objetivo general es reducir la PA media un 20 a 25% en la primera hora, luego a 160/100-110 mmHg en 2 a 6 horas y a cifras normales en 24 a 48 horas, para no comprometer la perfusion de organos con autorregulacion desplazada.', dificultad: 'intermedio' },
  { q: 'En una emergencia hipertensiva por diseccion aortica, cual es el objetivo de PA y frecuencia cardiaca?', options: ['Mantener la PA sistolica en torno a 160 mmHg sin objetivo de frecuencia cardiaca', 'Reduccion del 15% de la PA en 24 horas', 'PA sistolica menor de 120 mmHg y frecuencia cardiaca menor de 60 lpm', 'PA media reducida un 25% en la primera hora'], correct: 2, explanation: 'La diseccion aortica exige un control rapido y agresivo: PA sistolica menor de 120 mmHg y frecuencia cardiaca menor de 60 lpm en unos 20 minutos, con un betabloqueador intravenoso primero (esmolol o labetalol) y luego un vasodilatador, para reducir la fuerza de cizallamiento sobre la pared.', dificultad: 'dificil' },
  { q: 'En un ictus isquemico agudo sin criterio de trombolisis, cual es la conducta con la PA?', options: ['Manejo permisivo: tratar solo si supera 220/120 mmHg', 'Reducir la PA a menos de 140/90 mmHg de inmediato', 'Reducir la PA media un 25% en la primera hora', 'Elevar la PA con vasopresores para mejorar la perfusion'], correct: 0, explanation: 'En el ictus isquemico agudo se permite una PA elevada (respuesta protectora de la penumbra) y solo se trata si supera 220/120 mmHg, o 185/110 mmHg si el paciente va a recibir trombolisis, con un descenso suave de alrededor del 15%.', dificultad: 'dificil' },
  { q: 'Cual es el farmaco intravenoso de eleccion en la mayoria de las emergencias hipertensivas, incluida la encefalopatia?', options: ['Nifedipino de liberacion rapida', 'Enalaprilato en bolo unico', 'Furosemida a dosis altas', 'Nicardipino o clevidipino'], correct: 3, explanation: 'El nicardipino y el clevidipino son calcioantagonistas intravenosos titulables, de accion rapida y facil manejo, y son de eleccion en la mayoria de los escenarios, incluida la encefalopatia hipertensiva y el ictus. El labetalol es una alternativa util.', dificultad: 'intermedio' },
  { q: 'En una eclampsia, que farmaco se administra para prevenir y tratar las convulsiones, ademas del antihipertensivo?', options: ['Sulfato de magnesio intravenoso', 'Fenitoina intravenosa', 'Diazepam en perfusion continua', 'Levetiracetam oral'], correct: 0, explanation: 'El sulfato de magnesio intravenoso es el farmaco de eleccion para prevenir y tratar las convulsiones de la eclampsia; el control de la PA se hace con labetalol, hidralazina o nifedipino (objetivo menor de 160/110) y el tratamiento definitivo es la finalizacion del embarazo.', dificultad: 'intermedio' },
  { q: 'Que hallazgo en el electrocardiograma indica hipertrofia ventricular izquierda por HTA?', options: ['Intervalo PR mayor de 200 ms', 'Indice de Sokolow-Lyon mayor de 35 mm', 'Onda Q patologica en cara inferior', 'Elevacion difusa del segmento ST'], correct: 1, explanation: 'Un indice de Sokolow-Lyon mayor de 35 mm o un producto de Cornell mayor de 2440 mm x ms en el electrocardiograma indican hipertrofia ventricular izquierda, un marcador de dano de organo; el ecocardiograma es mas sensible para cuantificarla.', dificultad: 'intermedio' },
  { q: 'Cual es la segunda causa mas frecuente de enfermedad renal cronica terminal, despues de la diabetes?', options: ['La glomerulonefritis membranosa', 'La enfermedad renal poliquistica', 'La nefroangioesclerosis hipertensiva', 'La nefropatia por analgesicos'], correct: 2, explanation: 'La nefroangioesclerosis hipertensiva es la segunda causa de enfermedad renal cronica terminal tras la nefropatia diabetica; es un diagnostico de exclusion en un hipertenso de larga evolucion con descenso lento del filtrado glomerular, proteinuria leve y rinones pequenos y simetricos.', dificultad: 'intermedio' },
  { q: 'Que grado de retinopatia hipertensiva de Keith-Wagener-Barker define una emergencia hipertensiva?', options: ['Grado III o IV (hemorragias, exudados o edema de papila)', 'El grado I, con estrechamiento arteriolar leve y difuso del fondo', 'Grado II (cruces arteriovenosos)', 'Cualquier grado en un paciente sintomatico'], correct: 0, explanation: 'Los grados III (hemorragias, exudados y manchas algodonosas) y IV (ademas edema de papila) de la retinopatia hipertensiva indican dano grave de organo y, en el contexto agudo, constituyen una emergencia hipertensiva, antes llamada hipertension maligna.', dificultad: 'intermedio' },
  { q: 'En que grupo de pacientes NO debe usarse SCORE2 para estimar el riesgo cardiovascular?', options: ['En los adultos de 40 a 69 anos sin enfermedad conocida', 'En los fumadores activos', 'En los pacientes con diabetes mellitus', 'En las personas con la PA no controlada'], correct: 2, explanation: 'SCORE2 no debe usarse en pacientes con diabetes (existe SCORE2-Diabetes), enfermedad cardiovascular establecida, enfermedad renal cronica moderada-grave o hipercolesterolemia familiar, porque ya se clasifican como de riesgo alto o muy alto. Se aplica en adultos de 40 a 69 anos aparentemente sanos (SCORE2-OP a partir de los 70).', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 52 anos, sin antecedentes ni sintomas, acude a un chequeo de empresa. En dos tomas de consultorio separadas la PA es 148/94 y 150/92 mmHg. El indice de masa corporal es de 29.',
    steps: [
      { q: 'Cual es el siguiente paso antes de establecer el diagnostico de hipertension?', options: ['Iniciar de inmediato una combinacion de dos farmacos', 'Repetir la toma de consultorio dentro de un ano', 'Solicitar una coronariografia electiva', 'Confirmar con MAPA de 24 horas o AMPA'], correct: 3, explanation: 'Salvo PA muy elevada o dano de organo, el diagnostico de hipertension se confirma con una medicion fuera de consultorio (MAPA o AMPA), que ademas descarta la HTA de bata blanca.' },
      { q: 'La MAPA muestra una media de 24 horas de 138/86 y una media diurna de 142/90 mmHg. Cual es el fenotipo?', options: ['HTA de bata blanca', 'HTA sostenida', 'Normotension', 'HTA enmascarada'], correct: 1, explanation: 'La PA esta elevada tanto en el consultorio como fuera de el (media de 24 horas mayor de 130/80 y media diurna mayor de 135/85), lo que corresponde a una HTA sostenida y confirma el diagnostico.' },
      { q: 'Ademas de los cambios de estilo de vida, cual es el tratamiento farmacologico inicial?', options: ['Monoterapia con atenolol a dosis alta', 'Un diuretico del asa en monoterapia', 'Combinacion doble a dosis baja en un solo comprimido', 'Espironolactona como primer farmaco'], correct: 2, explanation: 'El tratamiento inicial es una combinacion doble a dosis baja en un comprimido (IECA o ARA-II mas calcioantagonista o diuretico tipo tiazida), con objetivo de PA sistolica de 120-129 mmHg si se tolera.' }
    ],
    explanation: 'Una PA de consultorio de 148/94 mmHg se confirma con MAPA o AMPA; si la medicion fuera de consultorio tambien esta elevada se trata de una HTA sostenida y se inicia una combinacion doble a dosis baja en un comprimido junto con los cambios de estilo de vida.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 60 anos con hipertension de 8 anos de evolucion. La PA es 158/96 mmHg pese a losartan 100 mg, amlodipino 10 mg e hidroclorotiazida 25 mg, todos a dosis plenas. El recuento de comprimidos confirma la adherencia y la MAPA descarta bata blanca. Potasio 3.9 mmol/L, filtrado glomerular 68 mL/min.',
    steps: [
      { q: 'Como se clasifica esta situacion?', options: ['HTA resistente', 'HTA de bata blanca', 'Urgencia hipertensiva', 'HTA secundaria confirmada'], correct: 0, explanation: 'La PA esta por encima del objetivo con 3 farmacos a dosis plenas, uno de ellos un diuretico, con adherencia confirmada y bata blanca descartada: es una HTA resistente.' },
      { q: 'Que causa secundaria se debe cribar de forma prioritaria?', options: ['Un feocromocitoma, con determinacion de catecolaminas en sangre capilar', 'Sindrome de Cushing, con cortisol salival nocturno', 'Coartacion de aorta, con radiografia de torax', 'Hiperaldosteronismo primario, con el cociente aldosterona/renina'], correct: 3, explanation: 'El hiperaldosteronismo primario es frecuente en la HTA resistente (cerca del 20%) y se criba con el cociente aldosterona/renina en condiciones adecuadas.' },
      { q: 'Cual es el cuarto farmaco de eleccion para anadir al tratamiento?', options: ['Doxazosina a dosis alta', 'Espironolactona 25 a 50 mg', 'Un betabloqueador cardioselectivo', 'Un agente de accion central'], correct: 1, explanation: 'La espironolactona 25-50 mg es el cuarto farmaco de eleccion en la HTA resistente (PATHWAY-2), y esta paciente cumple los requisitos (filtrado glomerular mayor de 45 y potasio menor de 4.5); despues hay que vigilar el potasio y la funcion renal.' }
    ],
    explanation: 'Una PA no controlada con 3 farmacos a dosis plenas incluido un diuretico, con adherencia confirmada y bata blanca descartada, es una HTA resistente; se criba el hiperaldosteronismo primario con el cociente aldosterona/renina y se anade espironolactona como cuarto farmaco si el filtrado glomerular es mayor de 45 y el potasio menor de 4.5.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varon de 45 anos acude a urgencias con PA de 210/125 mmHg, cefalea intensa, vision borrosa y confusion leve. El fondo de ojo muestra hemorragias, exudados y edema de papila. La creatinina es de 1.9 mg/dL (previa 1.0).',
    steps: [
      { q: 'Que cuadro clinico presenta este paciente?', options: ['Urgencia hipertensiva', 'Migrana con aura', 'Crisis de ansiedad con PA elevada', 'Emergencia hipertensiva'], correct: 3, explanation: 'Hay dano agudo de organo en curso (encefalopatia hipertensiva, retinopatia grado IV y lesion renal aguda) con PA gravemente elevada: es una emergencia hipertensiva.' },
      { q: 'Cual es el objetivo de reduccion de la PA en la primera hora?', options: ['Normalizar la PA por debajo de 120/80 mmHg', 'Reducir la PA media un 20 a 25%', 'Bajar la PA sistolica a 100 mmHg', 'No modificar la PA hasta completar la TC'], correct: 1, explanation: 'En la encefalopatia hipertensiva se reduce la PA media un 20 a 25% en la primera hora y luego de forma progresiva, evitando descensos bruscos que agraven la isquemia cerebral.' },
      { q: 'Cual es el farmaco de eleccion para el control de la PA?', options: ['Nicardipino o labetalol intravenoso', 'Nifedipino sublingual de accion corta', 'Captopril sublingual repetido', 'Hidralazina intramuscular'], correct: 0, explanation: 'Se usan farmacos intravenosos titulables como el nicardipino o el labetalol, con monitorizacion invasiva de la PA en cuidados intensivos, para lograr un descenso controlado.' }
    ],
    explanation: 'La PA gravemente elevada con encefalopatia, retinopatia grado IV y lesion renal aguda es una emergencia hipertensiva; se ingresa en cuidados intensivos y se reduce la PA media un 20 a 25% en la primera hora con nicardipino o labetalol intravenosos, evitando el descenso brusco.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 68 anos acude a urgencias remitido por PA de 192/108 mmHg detectada en una farmacia. No tiene cefalea, focalidad ni disnea. El electrocardiograma es normal, el fondo de ojo no muestra hemorragias ni edema y la creatinina es normal. Refiere que dejo la medicacion hace 2 semanas.',
    steps: [
      { q: 'Cual es el diagnostico?', options: ['Emergencia hipertensiva', 'HTA de bata blanca', 'Urgencia hipertensiva', 'Crisis simpaticomimetica'], correct: 2, explanation: 'La PA esta muy elevada pero no hay dano agudo de organo (exploracion, fondo de ojo, electrocardiograma y creatinina normales): es una urgencia hipertensiva.' },
      { q: 'Cual es la conducta apropiada?', options: ['Iniciar nitroprusiato intravenoso en cuidados intensivos', 'Reanudar el tratamiento oral y bajar la PA de forma gradual', 'Administrar nifedipino sublingual y repetir cada 15 minutos', 'Dar de alta sin tratamiento y citar en 3 meses'], correct: 1, explanation: 'La urgencia hipertensiva se maneja reanudando o intensificando el tratamiento oral, con reduccion gradual de la PA en horas o dias y una revision ambulatoria en pocos dias; una observacion breve confirma la tendencia descendente.' },
      { q: 'Que medida esta contraindicada en este paciente?', options: ['La reanudacion de su IECA habitual', 'La adicion de amlodipino oral', 'El nifedipino sublingual de accion corta', 'El reposo en un ambiente tranquilo'], correct: 2, explanation: 'El nifedipino sublingual de accion corta provoca descensos bruscos e impredecibles de la PA y se ha asociado a isquemia cerebral y coronaria; esta contraindicado en la crisis hipertensiva.' }
    ],
    explanation: 'Una PA muy elevada sin dano agudo de organo tras abandonar la medicacion es una urgencia hipertensiva: se reanuda el tratamiento oral con reduccion gradual de la PA y seguimiento ambulatorio, evitando el nifedipino sublingual y cualquier descenso brusco.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Gestante de 34 semanas acude con PA de 172/114 mmHg, cefalea, dolor epigastrico y proteinuria intensa. En la exploracion tiene hiperreflexia. Poco despues presenta una crisis tonico-clonica generalizada.',
    steps: [
      { q: 'Que diagnostico explica esta convulsion?', options: ['Epilepsia de novo no relacionada', 'Encefalopatia hipertensiva no gestacional', 'Ictus hemorragico del embarazo', 'Eclampsia'], correct: 3, explanation: 'Una crisis convulsiva en una gestante con hipertension, proteinuria y sintomas de preeclampsia grave (cefalea, epigastralgia, hiperreflexia) es una eclampsia.' },
      { q: 'Que farmaco se administra para tratar y prevenir nuevas convulsiones?', options: ['Sulfato de magnesio intravenoso', 'Fenitoina intravenosa', 'Acido valproico intravenoso', 'Propofol en perfusion'], correct: 0, explanation: 'El sulfato de magnesio intravenoso es el farmaco de eleccion para la eclampsia, superior a la fenitoina y a las benzodiacepinas para prevenir la recurrencia de las convulsiones.' },
      { q: 'Cual es el objetivo de PA y el tratamiento definitivo?', options: ['Bajar la PA a menos de 120/80 con nitroprusiato y mantener una conducta expectante', 'PA menor de 160/110 con labetalol o hidralazina, y finalizar el embarazo', 'PA sin cambios y reposo absoluto hasta el termino', 'PA menor de 140/90 con IECA intravenoso'], correct: 1, explanation: 'En la eclampsia se controla la PA a menos de 160/110 mmHg con labetalol, hidralazina o nifedipino (los IECA y ARA-II estan contraindicados en el embarazo) y el tratamiento definitivo es la finalizacion del embarazo.' }
    ],
    explanation: 'Una convulsion en una gestante con preeclampsia grave es una eclampsia: se administra sulfato de magnesio para las convulsiones, se baja la PA a menos de 160/110 con labetalol o hidralazina (nunca IECA ni ARA-II) y se finaliza el embarazo.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varon de 58 anos con hipertension de larga evolucion mal controlada refiere disnea de esfuerzo progresiva. El electrocardiograma muestra un indice de Sokolow-Lyon de 40 mm. El ecocardiograma muestra hipertrofia concentrica, fraccion de eyeccion del 58%, disfuncion diastolica y auricula izquierda dilatada. El BNP esta elevado.',
    steps: [
      { q: 'Que explica la disnea de este paciente?', options: ['Una miocardiopatia dilatada idiopatica ya en fase avanzada', 'Tromboembolia pulmonar cronica', 'Enfermedad pulmonar obstructiva cronica', 'Insuficiencia cardiaca con fraccion de eyeccion preservada por HTA'], correct: 3, explanation: 'La hipertrofia concentrica, la disfuncion diastolica, la auricula izquierda dilatada y el BNP elevado con fraccion de eyeccion preservada en un hipertenso de larga evolucion configuran una cardiopatia hipertensiva con insuficiencia cardiaca con fraccion de eyeccion preservada.' },
      { q: 'Que grupos de farmacos favorecen mas la regresion de la hipertrofia ventricular izquierda?', options: ['Los diureticos del asa y la hidralazina', 'Los alfabloqueadores y el minoxidil', 'Los IECA o ARA-II y los calcioantagonistas', 'Los nitratos y la digoxina'], correct: 2, explanation: 'El control de la PA induce regresion de la hipertrofia, y ese efecto es mayor con los IECA o ARA-II y con los calcioantagonistas que con otros grupos.' },
      { q: 'Que farmaco con beneficio demostrado en la insuficiencia cardiaca con fraccion de eyeccion preservada se debe anadir?', options: ['Un inhibidor de SGLT2', 'Digoxina a dosis baja', 'Un antiarritmico de clase I', 'Un calcioantagonista no dihidropiridinico'], correct: 0, explanation: 'Los inhibidores de SGLT2 reducen las hospitalizaciones por insuficiencia cardiaca en la fraccion de eyeccion preservada y en la reducida, y se anaden al tratamiento de control de la PA y de la congestion.' }
    ],
    explanation: 'La disnea de un hipertenso de larga evolucion con hipertrofia concentrica, disfuncion diastolica y BNP elevado corresponde a una cardiopatia hipertensiva con insuficiencia cardiaca con fraccion de eyeccion preservada; se controla la PA con IECA o ARA-II y calcioantagonistas (mayor regresion de la hipertrofia) y se anade un inhibidor de SGLT2.'
  }
];

export const flashcards = [
  { front: 'Umbral de HTA de consultorio (ESC 2024)', back: '140/90 mmHg o mayor.' },
  { front: 'Umbral de HTA de consultorio (ACC/AHA 2025)', back: 'Estadio 1: 130-139 / 80-89. Estadio 2: 140/90 o mayor.' },
  { front: 'Prueba de referencia para confirmar el diagnostico', back: 'MAPA de 24 horas (AMPA como alternativa).' },
  { front: 'Umbral de HTA en AMPA o media diurna de MAPA', back: '135/85 mmHg o mayor.' },
  { front: 'Umbral de HTA en la media de 24 horas de la MAPA', back: '130/80 mmHg o mayor (nocturna 120/70).' },
  { front: 'HTA de bata blanca', back: 'Consultorio alta, medicion fuera de consultorio normal. Riesgo intermedio.' },
  { front: 'HTA enmascarada', back: 'Consultorio normal, fuera de consultorio alta. Riesgo similar a la sostenida.' },
  { front: 'Intervencion dietetica con reduccion de ictus y mortalidad (SSaSS)', back: 'Sustituto de sal enriquecido con potasio (evitar en enfermedad renal avanzada).' },
  { front: 'Objetivo de PA sistolica en la mayoria, si se tolera', back: '120 a 129 mmHg (objetivo global menor de 130/80).' },
  { front: 'Tratamiento farmacologico inicial', back: 'Combinacion doble a dosis baja en un solo comprimido (IECA o ARA-II + calcioantagonista o diuretico tipo tiazida).' },
  { front: 'Diuretico tipo tiazida preferido', back: 'Clortalidona o indapamida sobre la hidroclorotiazida.' },
  { front: 'Combinacion de antihipertensivos a evitar', back: 'IECA con ARA-II.' },
  { front: 'Betabloqueadores en HTA', back: 'Solo con indicacion especifica (cardiopatia isquemica, insuficiencia cardiaca, fibrilacion auricular, embarazo).' },
  { front: 'Cuarto farmaco de eleccion en HTA resistente', back: 'Espironolactona 25 a 50 mg (PATHWAY-2).' },
  { front: 'Requisitos para anadir espironolactona', back: 'Filtrado glomerular mayor de 45 y potasio menor de 4.5 mmol/L.' },
  { front: 'Definicion de HTA resistente', back: 'PA sobre el objetivo con 3 farmacos a dosis optimas, uno un diuretico, con adherencia confirmada y bata blanca y causa secundaria descartadas.' },
  { front: 'Causa mas frecuente de pseudorresistencia', back: 'Mala adherencia al tratamiento.' },
  { front: 'Causa secundaria a cribar de forma prioritaria en HTA resistente', back: 'Hiperaldosteronismo primario (cociente aldosterona/renina).' },
  { front: 'Pista de laboratorio del hiperaldosteronismo primario', back: 'Hipopotasemia espontanea o desproporcionada al diuretico.' },
  { front: 'Emergencia frente a urgencia hipertensiva', back: 'La emergencia tiene dano agudo de organo en curso; la urgencia no.' },
  { front: 'Manejo de la urgencia hipertensiva', back: 'Farmacos orales, reduccion gradual en horas o dias, ambulatorio. Evitar nifedipino sublingual.' },
  { front: 'Objetivo de PA en la primera hora de la emergencia hipertensiva', back: 'Reducir la PA media un 20 a 25%.' },
  { front: 'Objetivo en la diseccion aortica', back: 'PA sistolica menor de 120 mmHg y frecuencia cardiaca menor de 60 lpm en 20 minutos.' },
  { front: 'PA en el ictus isquemico agudo', back: 'Permisivo: tratar solo si supera 220/120 (o 185/110 si se va a trombolizar).' },
  { front: 'Farmaco IV de eleccion en la mayoria de emergencias', back: 'Nicardipino o clevidipino (labetalol como alternativa).' },
  { front: 'Farmaco para las convulsiones de la eclampsia', back: 'Sulfato de magnesio intravenoso.' },
  { front: 'HVI en el electrocardiograma', back: 'Sokolow-Lyon mayor de 35 mm o producto de Cornell mayor de 2440 mm x ms.' },
  { front: 'Segunda causa de enfermedad renal cronica terminal', back: 'Nefroangioesclerosis hipertensiva (tras la diabetes).' },
  { front: 'Retinopatia hipertensiva que define emergencia', back: 'Grado III (hemorragias y exudados) o IV (edema de papila).' },
  { front: 'Poblacion en la que no se usa SCORE2', back: 'Diabetes (usar SCORE2-Diabetes), enfermedad cardiovascular establecida, ERC moderada-grave, hipercolesterolemia familiar.' },
  { front: 'Cada 10 mmHg menos de PA sistolica', back: 'Reduce alrededor de un 20% los eventos mayores, un 27% el ictus y un 28% la insuficiencia cardiaca.' }
];
