// topics/estado-epileptico/study.js: Autoevaluación de Estado Epiléptico y Epilepsia.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices al final de este comentario
// antes de dar el archivo por terminado).
//
// Índices `correct` de las 34 preguntas sueltas, en orden: 3,1,0,2,3,0,1,2,0,3,2,1,0,3,1,2,0,1,3,
// 2,0,3,1,0,2,3,1,0,2,1,3,0,2,1. Recuento: 0×9, 1×9, 2×8, 3×8. Sin racha larga ni ciclo fijo.
// Índices `correct` de los pasos de las 6 preguntas en cascada (3 pasos c/u), en orden: 2,0,3 /
// 1,3,0 / 0,2,1 / 3,1,2 / 2,3,0 / 0,1,3. Recuento: 0×5, 1×4, 2×4, 3×5.

export const quiz = [
  { q: '¿Cuál es la duración mínima de una crisis convulsiva para definirla operacionalmente como estado epiléptico (T1)?', options: ['1 minuto', '2 minutos', '10 minutos', '5 minutos'], correct: 3, explanation: 'La definición operacional (ILAE 2015) fija en 5 minutos el punto T1, a partir del cual es poco probable que la crisis ceda espontáneamente y debe iniciarse tratamiento sin demora.', dificultad: 'facil' },
  { q: '¿Qué marca el punto T2 (30 minutos) en la definición operacional del estado epiléptico?', options: ['El momento a partir del cual aumenta el riesgo de lesión neuronal permanente', 'El momento en que se descarta definitivamente una causa estructural', 'El momento en que debe suspenderse todo tratamiento', 'El momento en que se confirma el diagnóstico de epilepsia'], correct: 1, explanation: 'T2 marca el punto a partir del cual aumenta el riesgo de lesión neuronal a largo plazo si el estado epiléptico continúa sin controlarse.', dificultad: 'facil' },
  { q: '¿Cuál es el tratamiento de primera línea del estado epiléptico convulsivo?', options: ['Ácido valproico IV', 'Fenitoína IV', 'Una benzodiacepina (lorazepam IV o midazolam IM)', 'Levetiracetam IV'], correct: 0, explanation: 'Las benzodiacepinas (lorazepam IV o midazolam IM si no hay acceso IV) son el tratamiento de primera línea del estado epiléptico convulsivo.', dificultad: 'facil' },
  { q: '¿Cuál es la dosis correcta de lorazepam IV en el estado epiléptico convulsivo?', options: ['1 mg/kg', '0.01 mg/kg', '0.1 mg/kg (máximo 4 mg por dosis)', '10 mg/kg'], correct: 2, explanation: 'La dosis es 0.1 mg/kg IV, con un máximo de 4 mg por dosis, y puede repetirse una vez si persiste la crisis.', dificultad: 'facil' },
  { q: 'Según el ensayo RAMPART, ¿cómo se compara el midazolam intramuscular con el lorazepam intravenoso en el estado epiléptico prehospitalario?', options: ['El midazolam IM es claramente inferior', 'El midazolam IM no es inferior, e incluso resulta más rápido por el tiempo que toma canalizar una vena', 'El lorazepam IV es la única opción aceptada en el ámbito prehospitalario', 'El midazolam IM solo se recomienda en niños'], correct: 3, explanation: 'RAMPART demostró que el midazolam intramuscular no es inferior al lorazepam IV, con la ventaja práctica de no depender de un acceso venoso ya establecido.', dificultad: 'facil' },
  { q: '¿Qué demostró el ensayo ESETT respecto a los fármacos de segunda línea del estado epiléptico?', options: ['La fenitoína es claramente superior a las otras opciones', 'Ninguno de los tres fármacos evaluados es eficaz', 'Fosfenitoína, ácido valproico y levetiracetam tienen eficacia similar entre sí', 'El ácido valproico debe evitarse siempre en el estado epiléptico'], correct: 0, explanation: 'ESETT mostró eficacia similar entre fosfenitoína, ácido valproico y levetiracetam IV como segunda línea, por lo que la elección se individualiza según la comorbilidad del paciente.', dificultad: 'facil' },
  { q: '¿Qué estudio NO debe retrasar el inicio del tratamiento farmacológico en el estado epiléptico convulsivo?', options: ['La medición de glucosa capilar', 'La TC simple de cráneo', 'La toma de un acceso IV', 'La monitorización de signos vitales'], correct: 1, explanation: 'La TC simple de cráneo se realiza si no hay causa clara identificada, pero nunca debe retrasar el inicio de la benzodiacepina de primera línea.', dificultad: 'facil' },
  { q: '¿Cómo se confirma el diagnóstico de estado epiléptico no convulsivo?', options: ['Con la clínica exclusivamente, sin estudios adicionales', 'Únicamente con una punción lumbar', 'Con electroencefalograma', 'Con una TC simple de cráneo'], correct: 2, explanation: 'El estado epiléptico no convulsivo, al carecer de actividad motora evidente, solo puede confirmarse mediante electroencefalograma.', dificultad: 'facil' },
  { q: '¿Qué evalúan los criterios de Salzburg?', options: ['La gravedad clínica al ingreso del estado epiléptico', 'El riesgo de recurrencia tras una primera crisis', 'El diagnóstico electroencefalográfico del estado epiléptico no convulsivo', 'La probabilidad de epilepsia farmacorresistente'], correct: 2, explanation: 'Los criterios de Salzburg estandarizan el diagnóstico por EEG del estado epiléptico no convulsivo, reduciendo la variabilidad interobservador.', dificultad: 'facil' },
  { q: '¿Qué predice principalmente la escala STESS?', options: ['El tipo específico de crisis epiléptica', 'El pronóstico al ingreso del estado epiléptico', 'El riesgo de recurrencia tras una primera crisis', 'La necesidad de cirugía de epilepsia'], correct: 3, explanation: 'STESS combina nivel de consciencia, tipo de crisis, edad y antecedente de crisis previas para predecir el pronóstico al ingreso del estado epiléptico.', dificultad: 'facil' },
  { q: '¿Qué puntaje de STESS se asocia a mal pronóstico (muerte o no retorno al estado neurológico basal)?', options: ['0 puntos', '1 punto', '2 puntos', '3 puntos o más'], correct: 2, explanation: 'Un STESS de 3 o más predice mal pronóstico; un puntaje de 2 o menos predice buen pronóstico.', dificultad: 'intermedio' },
  { q: '¿Cómo se define el estado epiléptico refractario?', options: ['El que responde completamente a la primera línea', 'El que persiste pese a una benzodiacepina adecuada más un FAE de segunda línea', 'El que dura menos de 5 minutos', 'El que solo ocurre en pacientes sin epilepsia previa'], correct: 1, explanation: 'El estado epiléptico refractario es aquel que persiste pese a haber recibido una benzodiacepina adecuada más un fármaco antiepiléptico de segunda línea.', dificultad: 'intermedio' },
  { q: '¿Cómo se define el estado epiléptico superrefractario?', options: ['El que continúa o recurre 24 horas o más después de iniciada la anestesia general', 'El que cede tras la primera dosis de benzodiacepina', 'El que se resuelve espontáneamente sin tratamiento', 'El que ocurre exclusivamente en niños'], correct: 0, explanation: 'El estado superrefractario es aquel que continúa o recurre 24 horas o más después del inicio de la anestesia general, incluidos los casos que recurren al reducir la anestesia.', dificultad: 'intermedio' },
  { q: 'En un estado epiléptico superrefractario de un adulto joven previamente sano, sin causa estructural ni metabólica identificada, ¿qué etiología debe sospecharse con prioridad?', options: ['Encefalitis autoinmune', 'Efecto adverso acumulativo de las benzodiacepinas', 'Epilepsia generalizada genética de inicio muy tardío', 'Deficiencia aislada de vitamina B12'], correct: 3, explanation: 'La encefalitis autoinmune (anti-NMDA-R, anti-LGI1, entre otras) es una causa relevante de estado superrefractario en jóvenes previamente sanos sin otra causa identificada.', dificultad: 'intermedio' },
  { q: '¿Se recomienda iniciar un fármaco antiepiléptico de rutina tras una primera crisis no provocada de bajo riesgo?', options: ['Sí, siempre, sin excepción', 'No, ya que el tratamiento inmediato no mejora el pronóstico a largo plazo en el bajo riesgo', 'Solo si el paciente lo solicita explícitamente', 'Sí, pero únicamente en mujeres'], correct: 1, explanation: 'En el bajo riesgo, el FAE reduce la recurrencia a corto plazo pero no mejora la remisión a largo plazo, por lo que no se recomienda de rutina; se individualiza si hay factores de alto riesgo.', dificultad: 'intermedio' },
  { q: '¿Cuáles son factores de alto riesgo de recurrencia tras una primera crisis no provocada?', options: ['Anomalía epileptiforme en el EEG, lesión estructural en la imagen, examen neurológico anormal o crisis nocturna', 'Edad menor a 30 años exclusivamente', 'Ausencia total de antecedentes familiares', 'Un único episodio con recuperación completa e inmediata'], correct: 0, explanation: 'La anomalía epileptiforme en el EEG, la lesión estructural en la neuroimagen, el examen neurológico anormal y la crisis de inicio nocturno son los factores de riesgo de recurrencia descritos por la guía AAN/AES 2015.', dificultad: 'facil' },
  { q: '¿Cuáles son los tres criterios operacionales de la ILAE (2014) para el diagnóstico de epilepsia?', options: ['Dos crisis provocadas por fiebre en cualquier momento de la vida', 'Dos o más crisis no provocadas separadas &gt;24h, o una crisis con riesgo de recurrencia ≥60% a 10 años, o un síndrome epiléptico reconocido', 'Una sola crisis de cualquier tipo, sin más requisitos', 'Un EEG anormal, independientemente de la clínica'], correct: 3, explanation: 'Los tres criterios operacionales son: 2 o más crisis no provocadas separadas por más de 24 horas, o 1 crisis con riesgo de recurrencia similar (≥60% a 10 años), o el diagnóstico de un síndrome epiléptico específico.', dificultad: 'intermedio' },
  { q: '¿Cuál es la primera bifurcación en la clasificación ILAE 2017 de los tipos de crisis?', options: ['Motora frente a no motora', 'Provocada frente a no provocada', 'Inicio focal frente a generalizado frente a desconocido', 'Con aura frente a sin aura'], correct: 2, explanation: 'La clasificación ILAE 2017 divide primero por el inicio: focal, generalizado, o de inicio desconocido, la bifurcación de mayor relevancia terapéutica inmediata.', dificultad: 'facil' },
  { q: '¿Cómo se denominaba anteriormente la crisis focal con alteración de la consciencia?', options: ['Crisis de ausencia atípica', 'Crisis parcial simple', 'Crisis tónico-clónica generalizada', 'Crisis parcial compleja'], correct: 1, explanation: 'La antigua nomenclatura "parcial compleja" corresponde a la crisis focal con alteración de la consciencia en la terminología actual de la ILAE.', dificultad: 'facil' },
  { q: '¿Qué es en realidad el "aura" que refieren algunos pacientes antes de una crisis?', options: ['Un pródromo de horas de duración, sin relación eléctrica con la crisis', 'El inicio mismo de una crisis focal con consciencia preservada', 'Un fenómeno exclusivo de las crisis generalizadas', 'Un signo de que la crisis no es epiléptica'], correct: 3, explanation: 'El aura corresponde en realidad al inicio mismo de una crisis focal con consciencia preservada, no a un fenómeno separado que la precede.', dificultad: 'intermedio' },
  { q: '¿Cuáles son las características típicas de una crisis de ausencia?', options: ['Duración prolongada con confusión postictal marcada', 'Movimientos asincrónicos de las cuatro extremidades', 'Pérdida súbita del tono postural con caída', 'Interrupción breve y súbita de la actividad, sin aura ni confusión postictal'], correct: 3, explanation: 'Las ausencias son interrupciones breves y súbitas de la actividad, sin aura previa ni confusión postictal, típicas de la infancia.', dificultad: 'facil' },
  { q: '¿Cuál es el fármaco antiepiléptico de mayor eficacia demostrada en las epilepsias generalizadas genéticas, y cuál es su principal limitación?', options: ['Ácido valproico, limitado por su teratogenicidad en mujeres en edad reproductiva', 'Carbamazepina, sin ninguna limitación relevante', 'Fenitoína, limitada solo por su costo', 'Gabapentina, sin eficacia demostrada en ningún tipo de crisis'], correct: 0, explanation: 'El ácido valproico es el más eficaz en las epilepsias generalizadas genéticas, pero se evita en mujeres en edad reproductiva por su teratogenicidad, prefiriendo lamotrigina o levetiracetam.', dificultad: 'intermedio' },
  { q: '¿Qué grupo de fármacos antiepilépticos puede empeorar las ausencias y las mioclonías si se usa de forma inapropiada?', options: ['Los bloqueadores de canales de sodio (p. ej. carbamazepina)', 'Las benzodiacepinas', 'El levetiracetam', 'La lamotrigina en dosis bajas'], correct: 3, explanation: 'La carbamazepina y otros bloqueadores de canales de sodio pueden empeorar las ausencias y las mioclonías, por lo que deben evitarse si estos tipos de crisis predominan.', dificultad: 'intermedio' },
  { q: '¿Cuál es el estándar de oro para diagnosticar una crisis psicógena no epiléptica?', options: ['El nivel sérico de prolactina de forma aislada', 'La resonancia magnética cerebral', 'El video-electroencefalograma que capture un evento típico del paciente', 'El electroencefalograma interictal ambulatorio'], correct: 1, explanation: 'El video-EEG, que permite correlacionar el evento clínico típico del paciente con la ausencia de actividad eléctrica anormal, es el estándar de oro diagnóstico.', dificultad: 'facil' },
  { q: '¿Qué utilidad y qué limitación tiene la prolactina sérica en el diagnóstico diferencial de las crisis?', options: ['No tiene ninguna utilidad reconocida en este contexto', 'Un valor elevado 10-20 minutos tras el evento apoya una crisis epiléptica generalizada verdadera, pero con sensibilidad limitada', 'Un valor normal descarta siempre una crisis epiléptica', 'Solo es útil en crisis focales sin alteración de consciencia'], correct: 0, explanation: 'La prolactina elevada poco después del evento apoya una crisis epiléptica generalizada verdadera, pero su sensibilidad es limitada y un valor normal no descarta el diagnóstico.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo es más característico de una crisis psicógena no epiléptica frente a una crisis epiléptica verdadera?', options: ['Cianosis franca durante el evento', 'Ojos cerrados con resistencia a la apertura pasiva', 'Confusión postictal prolongada', 'Correlato electroencefalográfico presente durante el evento'], correct: 2, explanation: 'Los ojos cerrados con resistencia a la apertura pasiva son más característicos de la crisis psicógena; ningún signo aislado es absoluto, por lo que el video-EEG sigue siendo el estándar diagnóstico.', dificultad: 'intermedio' },
  { q: '¿Cómo se define la epilepsia farmacorresistente?', options: ['Fallo de un único fármaco antiepiléptico, sin importar la dosis utilizada', 'Fallo de 2 fármacos antiepilépticos apropiados, adecuadamente dosificados y tolerados', 'Presencia de más de una crisis en el mismo mes', 'Necesidad de más de una consulta neurológica anual'], correct: 3, explanation: 'La definición de consenso ILAE exige el fallo de 2 FAE apropiados, adecuadamente seleccionados, dosificados y tolerados, en monoterapia o combinación.', dificultad: 'facil' },
  { q: 'Antes de escalar el tratamiento en un paciente con aparente epilepsia farmacorresistente, ¿qué debe descartarse primero?', options: ['La pseudorresistencia (adherencia deficiente, FAE inapropiado, o diagnóstico erróneo)', 'La necesidad de cirugía inmediata sin más evaluación', 'La presencia de cualquier comorbilidad psiquiátrica', 'La edad del paciente como criterio único'], correct: 0, explanation: 'Debe confirmarse primero que el diagnóstico y la clasificación del tipo de crisis son correctos, y que la adherencia y la dosificación fueron adecuadas, antes de etiquetar al paciente como verdaderamente farmacorresistente.', dificultad: 'intermedio' },
  { q: '¿Qué tratamiento tiene la mayor probabilidad de lograr libertad de crisis en la epilepsia farmacorresistente con un foco bien localizado?', options: ['Añadir un tercer o cuarto fármaco antiepiléptico de forma indefinida', 'La cirugía resectiva del foco epiléptico', 'La estimulación del nervio vago como primera opción', 'La dieta cetogénica como primera opción en adultos'], correct: 3, explanation: 'La cirugía resectiva en candidatos bien seleccionados logra libertad de crisis en 60-70% a largo plazo, muy superior a la probabilidad de éxito de seguir ensayando fármacos adicionales.', dificultad: 'intermedio' },
  { q: '¿Qué es el SUDEP y con qué se relaciona directamente?', options: ['Muerte súbita inesperada en epilepsia, cuyo riesgo aumenta con las crisis tónico-clónicas generalizadas no controladas', 'Un síndrome epiléptico específico de la infancia', 'Una complicación exclusiva de la cirugía de epilepsia', 'Un efecto adverso característico del ácido valproico'], correct: 1, explanation: 'SUDEP (muerte súbita inesperada en epilepsia) tiene un riesgo proporcional a la frecuencia de crisis, en especial las tónico-clónicas generalizadas no controladas.', dificultad: 'dificil' },
  { q: '¿Cuál es el hallazgo estructural más frecuentemente asociado a epilepsia focal farmacorresistente?', options: ['La esclerosis mesial temporal', 'El infarto lacunar talámico', 'La hidrocefalia comunicante', 'La atrofia cerebelosa difusa'], correct: 0, explanation: 'La esclerosis mesial temporal es la causa estructural más común de epilepsia focal farmacorresistente, típicamente de origen temporal.', dificultad: 'facil' },
  { q: '¿En qué pacientes con crisis o estado epiléptico debe administrarse tiamina IV antes de la glucosa?', options: ['En todos los pacientes, sin excepción', 'En pacientes con sospecha de desnutrición o alcoholismo, para prevenir la encefalopatía de Wernicke', 'Únicamente en pacientes pediátricos', 'Nunca antes de la glucosa, siempre después'], correct: 2, explanation: 'En pacientes con sospecha de desnutrición o consumo crónico de alcohol, se administra tiamina IV antes de la glucosa para prevenir precipitar una encefalopatía de Wernicke.', dificultad: 'intermedio' },
  { q: 'Antes de escalar el manejo de un estado superrefractario, ¿qué inmunoterapia empírica puede considerarse ante sospecha razonable de encefalitis autoinmune?', options: ['Esteroides, inmunoglobulina IV o plasmaféresis, incluso antes de tener el resultado de los anticuerpos', 'Solo antibióticos de amplio espectro', 'Ningún tratamiento inmunomodulador está justificado sin confirmación serológica previa', 'Quimioterapia citotóxica de forma empírica'], correct: 0, explanation: 'Ante sospecha razonable de encefalitis autoinmune en un estado superrefractario, se considera inmunoterapia empírica incluso antes de tener los resultados de anticuerpos, dado el tiempo que toman estas pruebas.', dificultad: 'dificil' },
  { q: '¿Cuál es la causa más frecuente y más prevenible de estado epiléptico en un paciente con epilepsia ya conocida?', options: ['Una infección respiratoria intercurrente', 'El abandono o la subdosificación del fármaco antiepiléptico habitual', 'La exposición a luces intermitentes', 'El consumo excesivo de cafeína'], correct: 2, explanation: 'El abandono o la subdosificación del FAE habitual es la causa más frecuente y prevenible de estado epiléptico en un paciente con epilepsia ya conocida, de ahí la importancia de la educación sobre adherencia.', dificultad: 'facil' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Hombre de 35 años, epiléptico conocido con mala adherencia al tratamiento, presenta una crisis tónico-clónica generalizada que lleva 6 minutos sin ceder. No se cuenta con acceso IV inmediato.',
    steps: [
      { q: '¿Cuál es la conducta inicial más apropiada?', options: ['Esperar a canalizar una vía IV antes de administrar cualquier fármaco', 'Trasladar de inmediato sin administrar tratamiento prehospitalario', 'Administrar midazolam intramuscular de inmediato, sin esperar el acceso IV', 'Observar 5 minutos adicionales antes de decidir el tratamiento'], correct: 2 },
      { q: 'A los 20 minutos la crisis persiste pese a la benzodiacepina. ¿Cuál es la conducta más apropiada?', options: ['Iniciar un fármaco de segunda línea IV: fosfenitoína, ácido valproico o levetiracetam', 'Repetir la misma dosis de benzodiacepina una tercera vez', 'Esperar 15 minutos adicionales antes de escalar el tratamiento', 'Iniciar anestesia general de inmediato, sin ensayar la segunda línea'], correct: 0 },
      { q: 'La crisis persiste a los 45 minutos pese a la segunda línea. ¿Cuál es el siguiente paso?', options: ['Repetir la segunda línea con otro fármaco antes de escalar', 'Dar de alta con ajuste de FAE oral', 'Continuar solo con observación clínica sin más intervenciones', 'Iniciar anestesia general (midazolam, propofol o pentobarbital) con intubación y EEG continuo'], correct: 3 }
    ],
    explanation: 'Sin acceso IV, el midazolam intramuscular es la opción de primera línea más práctica y no inferior al lorazepam IV (RAMPART). Si la crisis persiste a los 20 minutos, se escala a un fármaco de segunda línea IV (fosfenitoína, ácido valproico o levetiracetam, de eficacia similar según ESETT). Si persiste a los 40-45 minutos pese a la segunda línea, se define como refractario y se inicia anestesia general con intubación y EEG continuo, sin retrasar el escalamiento por observación adicional.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 60 años en UCI por sepsis, tras resolverse un episodio de crisis tónico-clónica tratado con lorazepam, permanece con alteración persistente del estado de alerta 2 horas después, sin nueva actividad motora evidente.',
    steps: [
      { q: '¿Cuál es la sospecha diagnóstica más importante a descartar?', options: ['Efecto sedante residual de la benzodiacepina, sin necesidad de más estudio', 'Estado epiléptico no convulsivo', 'Delirium hipoactivo por la sepsis, sin relación con las crisis', 'Recurrencia de una crisis tónico-clónica no reconocida'], correct: 1 },
      { q: '¿Qué estudio debe solicitarse para confirmar o descartar esta sospecha?', options: ['Resonancia magnética urgente', 'Punción lumbar de entrada', 'Nivel sérico del FAE únicamente', 'Electroencefalograma urgente (criterios de Salzburg)'], correct: 3 },
      { q: 'El EEG confirma actividad epileptiforme continua. ¿Cuál es la conducta más apropiada respecto al escalamiento del tratamiento?', options: ['Benzodiacepina IV, con un umbral más alto para escalar a anestesia general, individualizando según el contexto clínico', 'Anestesia general inmediata en todos los casos, igual que en el estado convulsivo', 'No requiere tratamiento adicional si no hay actividad motora', 'Suspender toda sedación de inmediato sin más intervención'], correct: 0 }
    ],
    explanation: 'Una alteración del estado de alerta persistente sin causa clara tras un estado convulsivo tratado obliga a descartar la transición a un estado epiléptico no convulsivo, que solo se confirma con EEG (criterios de Salzburg). Confirmado el diagnóstico, el manejo escalonado es similar al convulsivo, pero con un umbral más alto para escalar a anestesia general, individualizando según si hay o no coma asociado.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 24 años previamente sana desarrolla un estado epiléptico que no responde a benzodiacepina, segunda línea, ni a 48 horas de anestesia general con propofol; no se identifica causa estructural ni metabólica en el estudio inicial.',
    steps: [
      { q: 'Dado el contexto (joven, previamente sana, sin causa estructural ni metabólica identificada), ¿qué etiología debe sospecharse de forma prioritaria?', options: ['Encefalitis autoinmune', 'Efecto adverso acumulativo de los propios anestésicos', 'Epilepsia genética generalizada de inicio tardío', 'Simulación o crisis psicógena sobreañadida'], correct: 0 },
      { q: '¿Qué estudios adicionales son más apropiados en este punto?', options: ['Repetir únicamente la TC simple de cráneo', 'RM con contraste y punción lumbar con panel de encefalitis autoinmune', 'Suspender todo estudio adicional y continuar solo con anestesia', 'Electromiografía de las cuatro extremidades'], correct: 1 },
      { q: 'Mientras se esperan los resultados de los anticuerpos, ¿cuál es la conducta más apropiada?', options: ['Esperar el resultado de los anticuerpos antes de iniciar cualquier tratamiento inmunomodulador', 'Iniciar inmunoterapia empírica (esteroides, inmunoglobulina IV o plasmaféresis) sin esperar el resultado de los anticuerpos', 'Suspender la anestesia de inmediato para reevaluar sin sedación', 'Iniciar quimioterapia empírica de amplio espectro'], correct: 2 }
    ],
    explanation: 'En una paciente joven previamente sana con estado superrefractario sin causa estructural ni metabólica identificada, la encefalitis autoinmune es una causa relevante que debe buscarse activamente con RM con contraste y punción lumbar con panel autoinmune. Dado el tiempo que toman los resultados de anticuerpos, se justifica iniciar inmunoterapia empírica ante sospecha razonable, sin esperar la confirmación serológica.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Hombre de 45 años sin antecedentes presenta una primera crisis tónico-clónica generalizada durante el sueño. El examen neurológico es normal, el panel metabólico es normal, y el EEG muestra descargas epileptiformes focales temporales.',
    steps: [
      { q: '¿Cuál es el estudio de imagen más apropiado en este momento?', options: ['No se requiere ningún estudio de imagen', 'TC simple de cráneo, como único estudio necesario', 'Resonancia magnética cerebral con protocolo de epilepsia', 'Ecografía Doppler transcraneal'], correct: 1 },
      { q: 'Dado que la crisis fue nocturna y el EEG muestra una anomalía epileptiforme, ¿cómo se clasifica el riesgo de recurrencia a 2 años?', options: ['Muy bajo, prácticamente nulo', 'Idéntico al de una crisis sin ningún factor de riesgo', 'Alto, por la combinación de factores de riesgo presentes', 'No puede estimarse sin una segunda crisis'], correct: 3 },
      { q: '¿Cuál es la conducta más apropiada respecto al inicio de un fármaco antiepiléptico?', options: ['Nunca se inicia un FAE tras una primera crisis, independientemente del riesgo', 'Iniciar un FAE de forma obligatoria sin discutirlo con el paciente', 'Iniciar doble terapia antiepiléptica de entrada', 'Discutir de forma individualizada el inicio de un FAE, dado el riesgo alto de recurrencia'], correct: 2 }
    ],
    explanation: 'La RM cerebral con protocolo de epilepsia es el estudio de imagen ambulatorio de elección tras una primera crisis. La combinación de crisis nocturna y anomalía epileptiforme en el EEG coloca a este paciente en un grupo de alto riesgo de recurrencia (hasta 65-70% a 2 años), lo que justifica discutir de forma individualizada el inicio de un FAE, a diferencia del manejo expectante que se recomienda en el bajo riesgo.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 28 años con episodios recurrentes descritos como "convulsiones" de hasta 10 minutos de duración, con movimientos asincrónicos de las extremidades, ojos cerrados con resistencia a la apertura pasiva, sin cianosis, y sin confusión posterior significativa. Ha sido tratada con 3 fármacos antiepilépticos sin respuesta.',
    steps: [
      { q: '¿Qué diagnóstico debe considerarse fuertemente dado este patrón clínico?', options: ['Epilepsia farmacorresistente que requiere un cuarto FAE', 'Estado epiléptico no convulsivo recurrente', 'Crisis psicógena no epiléptica', 'Epilepsia generalizada genética de inicio en la edad adulta'], correct: 2 },
      { q: '¿Cuál es el estudio de referencia para confirmar este diagnóstico?', options: ['Nivel sérico de prolactina de forma aislada', 'Resonancia magnética cerebral', 'Electroencefalograma interictal ambulatorio', 'Video-electroencefalograma que capture un evento típico del paciente'], correct: 3 },
      { q: 'Confirmado el diagnóstico, sin evidencia de epilepsia concomitante, ¿cuál es la conducta más apropiada respecto a los fármacos antiepilépticos ya indicados?', options: ['Suspender los FAE de forma gradual y derivar a terapia cognitivo-conductual especializada', 'Añadir un cuarto FAE de mecanismo distinto', 'Duplicar la dosis de los FAE actuales', 'Mantener los 3 FAE de forma indefinida por seguridad'], correct: 0 }
    ],
    explanation: 'La duración prolongada, los movimientos asincrónicos, los ojos cerrados con resistencia a la apertura pasiva, la ausencia de cianosis y la ausencia de confusión postictal son hallazgos que orientan hacia una crisis psicógena no epiléptica, la explicación más probable de la "farmacorresistencia" en este caso. El video-EEG confirma el diagnóstico al no mostrar correlato eléctrico durante el evento típico. Sin evidencia de epilepsia verdadera, los FAE no están indicados y deben retirarse de forma gradual, derivando a terapia cognitivo-conductual especializada.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 19 años con crisis de sacudidas breves y bilaterales de los brazos al despertar, y un episodio de crisis tónico-clónica generalizada la semana pasada tras una noche de privación de sueño. El EEG muestra descargas generalizadas de polipunta-onda.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable?', options: ['Epilepsia mioclónica juvenil (una epilepsia generalizada genética)', 'Epilepsia focal temporal con generalización secundaria', 'Crisis psicógena no epiléptica', 'Síndrome de West'], correct: 0 },
      { q: '¿Cuál es el fármaco de mayor eficacia demostrada para este síndrome, y cuál es la principal limitación a considerar en esta paciente?', options: ['Carbamazepina, considerada de primera elección sin limitaciones relevantes', 'Ácido valproico, limitado por su teratogenicidad en una mujer en edad reproductiva', 'Fenitoína, limitada únicamente por su costo elevado', 'Ningún fármaco tiene eficacia demostrada en este síndrome'], correct: 1 },
      { q: 'Dado el contexto de esta paciente, ¿qué alternativas son preferibles al fármaco de mayor eficacia teórica?', options: ['Suspender cualquier tratamiento farmacológico y solo evitar la privación de sueño', 'Carbamazepina u oxcarbazepina como alternativas de primera elección', 'Fenobarbital como alternativa preferida en mujeres jóvenes', 'Lamotrigina o levetiracetam como alternativas más apropiadas en edad reproductiva'], correct: 3 }
    ],
    explanation: 'Las mioclonías al despertar más una crisis tónico-clónica generalizada precipitada por privación de sueño, con descargas de polipunta-onda en el EEG, son el cuadro clásico de la epilepsia mioclónica juvenil. El ácido valproico es el fármaco de mayor eficacia demostrada, pero su teratogenicidad limita su uso en mujeres en edad reproductiva, por lo que lamotrigina o levetiracetam son alternativas preferidas en este contexto; la carbamazepina, en cambio, puede empeorar las mioclonías y debe evitarse.'
  }
];

export const flashcards = [
  { front: 'Definición operacional T1 de estado epiléptico convulsivo', back: 'Crisis de 5 minutos o más de duración, o crisis repetidas sin recuperación completa de la consciencia entre ellas.' },
  { front: 'T2, qué marca', back: 'A los 30 minutos aumenta el riesgo de lesión neuronal permanente si el estado epiléptico continúa.' },
  { front: 'Primera línea de tratamiento del estado epiléptico', back: 'Benzodiacepina: lorazepam IV 0.1 mg/kg (máx. 4 mg), o midazolam IM si no hay acceso IV.' },
  { front: 'RAMPART: hallazgo principal', back: 'El midazolam IM no es inferior al lorazepam IV, e incluso más rápido por el tiempo de acceso venoso.' },
  { front: 'Segunda línea del estado epiléptico (20 minutos)', back: 'Fosfenitoína, ácido valproico o levetiracetam IV; ESETT mostró eficacia similar entre los tres.' },
  { front: 'Manejo del estado epiléptico refractario (40 minutos)', back: 'Anestesia general: midazolam, propofol o pentobarbital en infusión continua, con intubación y EEG continuo.' },
  { front: 'Definición de estado epiléptico superrefractario', back: 'El que continúa o recurre 24 horas o más después de iniciada la anestesia general.' },
  { front: 'Causa a sospechar en un estado superrefractario en joven previamente sano', back: 'Encefalitis autoinmune (anti-NMDA-R, anti-LGI1, entre otras).' },
  { front: 'Estado epiléptico no convulsivo: cómo se diagnostica', back: 'Solo con electroencefalograma (criterios de Salzburg); la clínica es alteración del estado de consciencia sin actividad motora evidente.' },
  { front: 'STESS: componentes', back: 'Nivel de consciencia, peor tipo de crisis, edad, antecedente de crisis previas; 0-6 puntos, ≥3 mal pronóstico.' },
  { front: 'Definición operacional de epilepsia (ILAE 2014)', back: '≥2 crisis no provocadas separadas >24h, o 1 crisis con riesgo de recurrencia ≥60% a 10 años, o un síndrome epiléptico reconocido.' },
  { front: 'Clasificación ILAE 2017: primera bifurcación de las crisis', back: 'Inicio focal, generalizado, o desconocido.' },
  { front: 'Crisis focal con alteración de consciencia: término antiguo', back: '"Crisis parcial compleja".' },
  { front: 'Qué es el aura en realidad', back: 'El inicio mismo de una crisis focal con consciencia preservada, no un fenómeno separado que la precede.' },
  { front: 'Ausencias: características clave', back: 'Interrupción breve y súbita de la actividad, sin aura ni confusión postictal, típica de la infancia.' },
  { front: 'Fármaco de elección en epilepsias generalizadas genéticas', back: 'Ácido valproico; se evita en mujeres en edad reproductiva por teratogenicidad, prefiriendo lamotrigina o levetiracetam.' },
  { front: 'Fármacos a evitar si predominan ausencias o mioclonías', back: 'Carbamazepina y otros bloqueadores de canales de sodio, que pueden empeorarlas.' },
  { front: 'Video-EEG: para qué sirve', back: 'Es el estándar de oro para diferenciar una crisis epiléptica de una crisis psicógena no epiléptica.' },
  { front: 'Prolactina sérica: utilidad y limitación', back: 'Elevada 10-20 min tras el evento apoya una crisis epiléptica generalizada verdadera, pero con sensibilidad limitada.' },
  { front: 'Diferenciador clínico útil entre crisis epiléptica y psicógena', back: 'Ojos cerrados con resistencia a la apertura pasiva orienta a crisis psicógena; ningún signo aislado es absoluto.' },
  { front: 'Definición de epilepsia farmacorresistente', back: 'Fallo de 2 FAE apropiados, adecuadamente dosificados y tolerados, en monoterapia o combinación.' },
  { front: 'Antes de escalar en aparente farmacorresistencia, qué descartar', back: 'Pseudorresistencia: adherencia deficiente, FAE inapropiado para el tipo de crisis, o diagnóstico erróneo.' },
  { front: 'Mejor tratamiento en farmacorresistencia con foco bien localizado', back: 'Cirugía resectiva: 60-70% de libertad de crisis a largo plazo.' },
  { front: 'SUDEP', back: 'Muerte súbita inesperada en epilepsia; riesgo proporcional a la frecuencia de crisis tónico-clónicas generalizadas no controladas.' },
  { front: 'Hallazgo estructural típico en epilepsia focal farmacorresistente', back: 'Esclerosis mesial temporal.' },
  { front: 'Por qué dar tiamina antes de glucosa en ciertos pacientes', back: 'En sospecha de desnutrición o alcoholismo, para prevenir precipitar la encefalopatía de Wernicke.' },
  { front: 'Causa más frecuente y prevenible de estado epiléptico en epiléptico conocido', back: 'Abandono o subdosificación del fármaco antiepiléptico habitual.' },
  { front: 'Riesgo de recurrencia a 2 años tras una primera crisis de bajo riesgo', back: 'Aproximadamente 25-30%, frente a 60% o más si hay varios factores de alto riesgo presentes.' },
  { front: 'Primera crisis no provocada de bajo riesgo: ¿se inicia FAE de rutina?', back: 'No; el tratamiento inmediato reduce la recurrencia a corto plazo pero no mejora la remisión a largo plazo.' },
  { front: 'Inmunoterapia empírica en estado superrefractario con sospecha autoinmune', back: 'Esteroides, inmunoglobulina IV o plasmaféresis, incluso antes del resultado de los anticuerpos.' }
];

export const caseSteps = [];
export const caseSummary = undefined;

export default { quiz, flashcards, caseSteps, caseSummary };
