// topics/anemia-aplasica/study.js: Autoevaluación de Anemia Aplásica.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Índices `correct` de las 30 preguntas sueltas, en orden: 2,0,3,1,2,3,0,2,1,3,0,1,2,3,0,1,3,2,0,
// 1,3,0,2,1,3,2,0,3,1,2. Recuento: 0×7, 1×7, 2×8, 3×8. Sin racha >2 ni ciclo fijo.
// Índices `correct` de los pasos de las 5 preguntas en cascada (3 pasos c/u), en orden: 1,3,0 /
// 2,0,3 / 1,2,0 / 3,1,2 / 0,3,1. Recuento: 0×4, 1×4, 2×3, 3×4.

export const quiz = [
  { q: '¿Cuál es la principal diferencia fisiopatológica entre la anemia aplásica y el síndrome mielodisplásico?', options: ['En la anemia aplásica la médula es hipercelular con apoptosis excesiva', 'Ambas comparten exactamente el mismo mecanismo', 'En la anemia aplásica hay destrucción inmunomediada de la célula madre con médula vacía (hipocelular), sin displasia ni clonalidad', 'La anemia aplásica siempre tiene blastos circulantes'], correct: 2, explanation: 'En la anemia aplásica, la destrucción inmunomediada de la célula madre hematopoyética produce una médula vacía (hipocelular), sin displasia ni clonalidad, a diferencia de la hematopoyesis ineficaz clonal del síndrome mielodisplásico.', dificultad: 'facil' },
  { q: '¿Cuál es el mecanismo predominante de la anemia aplásica adquirida idiopática?', options: ['Destrucción inmunomediada de la célula madre hematopoyética por linfocitos T citotóxicos', 'Mutación somática que confiere ventaja proliferativa al clon', 'Depósito de amiloide en el estroma medular', 'Fibrosis reactiva del estroma medular'], correct: 0, explanation: 'La destrucción inmunomediada de la célula madre hematopoyética por linfocitos T citotóxicos oligoclonales es el mecanismo predominante de la forma adquirida idiopática.', dificultad: 'facil' },
  { q: '¿Qué hallazgo clínico, si está presente, debe hacer reconsiderar el diagnóstico de anemia aplásica?', options: ['Fatiga por anemia', 'Equimosis', 'Infecciones recurrentes', 'Adenopatías, hepatoesplenomegalia o dolor óseo significativos'], correct: 3, explanation: 'La ausencia de adenopatías, hepatoesplenomegalia y dolor óseo significativos es característica de la anemia aplásica; su presencia obliga a reconsiderar el diagnóstico hacia una neoplasia hematológica infiltrativa.', dificultad: 'facil' },
  { q: '¿Cuáles son los 3 componentes citopénicos de los criterios de gravedad de Camitta?', options: ['Hemoglobina, leucocitos totales, linfocitos', 'Neutrófilos absolutos, plaquetas, reticulocitos', 'Blastos, LDH, ácido úrico', 'VCM, ferritina, eritropoyetina'], correct: 1, explanation: 'Los criterios de Camitta combinan neutrófilos absolutos, plaquetas y reticulocitos, junto con la celularidad medular.', dificultad: 'facil' },
  { q: 'Según los criterios de Camitta, ¿qué define la anemia aplásica muy grave a diferencia de la grave?', options: ['Celularidad medular &gt;50%', 'Ausencia de trombocitopenia', 'Los mismos criterios de gravedad, con neutrófilos absolutos &lt;200/µL', 'Presencia de blastos circulantes'], correct: 2, explanation: 'La anemia aplásica muy grave cumple los mismos criterios que la grave, pero con un recuento absoluto de neutrófilos &lt;200/µL.', dificultad: 'intermedio' },
  { q: '¿Qué proporción aproximada de pacientes con anemia aplásica tiene una clona de hemoglobinuria paroxística nocturna detectable al diagnóstico o durante el seguimiento?', options: ['&lt;5%', '~10%', '~25%', '~50-70%'], correct: 3, explanation: 'Hasta 50-70% de los pacientes con anemia aplásica tienen una clona de hemoglobinuria paroxística nocturna detectable al diagnóstico o durante el seguimiento.', dificultad: 'intermedio' },
  { q: '¿Qué implica la presencia de una clona de HPN en un paciente con anemia aplásica?', options: ['Mayor probabilidad de respuesta a la inmunosupresión', 'Contraindicación absoluta para cualquier tratamiento', 'Diagnóstico automático de leucemia mieloide aguda', 'Necesidad de esplenectomía inmediata'], correct: 0, explanation: 'La presencia de una clona de HPN se asocia a mayor probabilidad de respuesta a la inmunosupresión, además de obligar a vigilancia de hemólisis/trombosis si crece.', dificultad: 'intermedio' },
  { q: '¿Qué estudio es obligatorio en todo paciente menor de 40 años con anemia aplásica antes de iniciar cualquier tratamiento definitivo?', options: ['Biopsia hepática', 'Endoscopia digestiva alta', 'Estudio de fragilidad cromosómica con diepoxibutano o mitomicina C', 'Electromiografía'], correct: 2, explanation: 'El estudio de fragilidad cromosómica es obligatorio en todo paciente joven para excluir anemia de Fanconi antes de cualquier tratamiento definitivo.', dificultad: 'facil' },
  { q: '¿Por qué es fundamental descartar anemia de Fanconi antes de iniciar tratamiento en un paciente joven con anemia aplásica?', options: ['Porque la anemia de Fanconi siempre cursa con blastos circulantes', 'Porque el acondicionamiento pretrasplante estándar es tóxico de forma desproporcionada en Fanconi, y la inmunosupresión no corrige el defecto intrínseco', 'Porque la anemia de Fanconi no requiere ningún tratamiento', 'Porque la anemia de Fanconi se cura espontáneamente sin intervención'], correct: 1, explanation: 'El acondicionamiento pretrasplante estándar (dosis convencionales de alquilantes/radiación) es tóxico de forma desproporcionada en Fanconi por la hipersensibilidad intrínseca al daño del ADN, y la inmunosupresión no corrige el defecto intrínseco de la célula madre.', dificultad: 'intermedio' },
  { q: '¿Cuál es el fármaco clásicamente asociado a anemia aplásica idiosincrásica?', options: ['Paracetamol', 'Amoxicilina', 'Metformina', 'Cloranfenicol'], correct: 3, explanation: 'El cloranfenicol es el fármaco clásicamente asociado a anemia aplásica idiosincrásica, no dosis-dependiente.', dificultad: 'facil' },
  { q: '¿Qué caracteriza al síndrome de hepatitis-aplasia?', options: ['Hepatitis aguda seronegativa (sin virus hepatotropo identificado) seguida de aplasia medular semanas después, predominante en varones jóvenes', 'Hepatitis por virus de la hepatitis B seguida de cirrosis', 'Hepatitis autoinmune con buena respuesta a corticoide', 'Hepatitis alcohólica con recuperación medular espontánea'], correct: 0, explanation: 'El síndrome de hepatitis-aplasia es hepatitis aguda seronegativa seguida de aplasia medular semanas después, predominante en varones jóvenes.', dificultad: 'intermedio' },
  { q: '¿Cuál es el esquema de inmunosupresión estándar de primera línea en la anemia aplásica adquirida grave, con las mejores tasas de respuesta hematológica completa?', options: ['Corticoide en monoterapia', 'Globulina antitimocítica de caballo + ciclosporina + eltrombopag', 'Quimioterapia de inducción tipo LMA', 'Rituximab en monoterapia'], correct: 1, explanation: 'La globulina antitimocítica de caballo más ciclosporina más eltrombopag es el esquema estándar de primera línea, con mejores tasas de respuesta hematológica completa que la inmunosupresión sola.', dificultad: 'facil' },
  { q: '¿Qué producto de globulina antitimocítica ha demostrado superioridad sobre el otro en estudios comparativos para la anemia aplásica?', options: ['El de conejo sobre el de caballo', 'Ambos son exactamente equivalentes en todos los desenlaces', 'El de caballo sobre el de conejo', 'Ninguno de los dos productos existe en la práctica clínica actual'], correct: 2, explanation: 'La globulina antitimocítica de caballo ha demostrado superioridad sobre la de conejo en estudios comparativos directos para la anemia aplásica.', dificultad: 'intermedio' },
  { q: '¿Cuál es el tratamiento de primera línea en el paciente joven con anemia aplásica grave/muy grave que tiene un hermano HLA-idéntico?', options: ['Solo eltrombopag en monoterapia', 'Andrógenos', 'Solo soporte transfusional indefinido', 'Trasplante alogénico de células madre hematopoyéticas'], correct: 3, explanation: 'El trasplante alogénico de un hermano HLA-idéntico es el tratamiento de primera línea en el paciente joven con enfermedad grave/muy grave.', dificultad: 'facil' },
  { q: '¿Por qué se prefiere el soporte transfusional restrictivo y con hemoderivados irradiados/leucorreducidos en la anemia aplásica grave, evitando transfusiones de familiares?', options: ['Para minimizar la aloinmunización y preservar la elegibilidad para un futuro trasplante alogénico', 'Porque los hemoderivados irradiados son más baratos', 'Porque la irradiación cura la anemia aplásica', 'Porque las transfusiones de familiares están prohibidas por ley en cualquier contexto'], correct: 0, explanation: 'El soporte transfusional restrictivo con hemoderivados irradiados/leucorreducidos, evitando familiares, minimiza la aloinmunización y preserva la elegibilidad para un futuro trasplante alogénico.', dificultad: 'intermedio' },
  { q: '¿Cuál es la conducta terapéutica en la anemia aplásica no grave sin dependencia transfusional ni citopenias sintomáticas?', options: ['Trasplante alogénico inmediato', 'Vigilancia expectante, sin tratamiento específico de rutina', 'Globulina antitimocítica de entrada en todos los casos', 'Quimioterapia de inducción'], correct: 1, explanation: 'La vigilancia expectante, sin tratamiento específico de rutina, es la conducta apropiada en la anemia aplásica no grave sin dependencia transfusional ni citopenias sintomáticas.', dificultad: 'facil' },
  { q: '¿Cuál es el tratamiento de primera línea (no curativo) en la anemia de Fanconi sin donante de trasplante disponible?', options: ['Globulina antitimocítica más ciclosporina', 'Quimioterapia de inducción intensiva', 'Rituximab', 'Andrógenos (danazol u oximetolona)'], correct: 3, explanation: 'Los andrógenos son el tratamiento de primera línea no curativo en la anemia de Fanconi sin donante disponible.', dificultad: 'intermedio' },
  { q: '¿Por qué la inmunosupresión estándar (globulina antitimocítica/ciclosporina) NO está indicada en la anemia aplásica congénita?', options: ['Porque produce curación inmediata sin necesidad de otro tratamiento', 'Porque está contraindicada solo por razones de costo', 'Porque el defecto es intrínseco a la célula madre y no inmunomediado, por lo que la inmunosupresión no corrige la causa', 'Porque siempre produce remisión completa en menos de una semana'], correct: 2, explanation: 'El defecto en las formas congénitas es intrínseco a la célula madre (reparación del ADN, mantenimiento telomérico, biogénesis ribosomal según el síndrome), no inmunomediado, por lo que la inmunosupresión no corrige la causa.', dificultad: 'intermedio' },
  { q: '¿Cuál es la tríada clásica de la disqueratosis congénita?', options: ['Leucoplasia oral, distrofia ungueal, pigmentación reticular cutánea', 'Talla baja, anomalías del pulgar, manchas café con leche', 'Insuficiencia pancreática exocrina, neutropenia, talla baja', 'Anemia macrocítica aislada, anomalías del pulgar, aplasia pura de células rojas'], correct: 0, explanation: 'La tríada clásica de la disqueratosis congénita es leucoplasia oral, distrofia ungueal y pigmentación reticular cutánea.', dificultad: 'facil' },
  { q: '¿Qué caracteriza al síndrome de Shwachman-Diamond?', options: ['Fragilidad cromosómica marcada con diepoxibutano', 'Neutropenia predominante con insuficiencia pancreática exocrina', 'Acortamiento telomérico acelerado', 'Aplasia pura de células rojas aislada desde la infancia'], correct: 1, explanation: 'El síndrome de Shwachman-Diamond se caracteriza por neutropenia predominante con insuficiencia pancreática exocrina.', dificultad: 'intermedio' },
  { q: '¿Cuál es el estudio de médula ósea más informativo para establecer el diagnóstico de anemia aplásica?', options: ['Aspirado de médula ósea únicamente, sin biopsia', 'Punción lumbar', 'Biopsia hepática', 'Biopsia de médula ósea (más informativa que el aspirado)'], correct: 3, explanation: 'La biopsia de médula ósea es más informativa que el aspirado para cuantificar la celularidad real y establecer el diagnóstico.', dificultad: 'facil' },
  { q: '¿Qué hallazgo distingue a la anemia aplásica de un síndrome mielodisplásico hipoplásico?', options: ['Ausencia de clonalidad (cariotipo/NGS normales) en la anemia aplásica, presente en el SMD hipoplásico', 'Ambas tienen exactamente el mismo cariotipo siempre', 'La anemia aplásica siempre tiene fibrosis reticulínica', 'El SMD hipoplásico nunca tiene citopenias'], correct: 0, explanation: 'La ausencia de clonalidad demostrable (cariotipo y NGS normales) distingue a la anemia aplásica del SMD hipoplásico, donde sí hay clonalidad.', dificultad: 'intermedio' },
  { q: '¿Cuál es el umbral profiláctico habitual de transfusión plaquetaria en un paciente con anemia aplásica sin fiebre ni sangrado activo?', options: ['&lt;100,000/µL', '&lt;50,000/µL', '&lt;10,000/µL', '&lt;80,000/µL'], correct: 2, explanation: 'El umbral profiláctico habitual en ausencia de fiebre o sangrado es &lt;10,000/µL; el umbral es más alto si hay fiebre o un procedimiento planeado.', dificultad: 'intermedio' },
  { q: '¿Cuándo debe agregarse cobertura antifúngica empírica en un paciente con anemia aplásica y neutropenia febril?', options: ['Nunca, no está indicada en esta enfermedad', 'Si la fiebre persiste más de 4-7 días pese a antibiótico de amplio espectro', 'Solo si hay cultivos positivos para hongos confirmados', 'Desde el primer día de fiebre, sin esperar evolución'], correct: 1, explanation: 'La cobertura antifúngica empírica se agrega si la fiebre persiste más de 4-7 días pese al antibiótico de amplio espectro, dado el riesgo particularmente alto de infección fúngica invasiva.', dificultad: 'intermedio' },
  { q: '¿Cuál es el riesgo acumulado aproximado a 10 años de evolución a síndrome mielodisplásico/leucemia mieloide aguda tras anemia aplásica adquirida?', options: ['&lt;1%', '~50%', '~90%', '~10-15%'], correct: 3, explanation: 'El riesgo acumulado a 10 años de evolución a SMD/LMA tras anemia aplásica adquirida es de aproximadamente 10-15%.', dificultad: 'intermedio' },
  { q: '¿Qué alteración citogenética se asocia a mayor riesgo de evolución clonal en la anemia aplásica?', options: ['Deleción aislada del(20q)', 'Trisomía 8 aislada', 'Monosomía 7', 'Deleción aislada del(5q)'], correct: 2, explanation: 'La monosomía 7 se asocia al mayor riesgo de evolución clonal a síndrome mielodisplásico/leucemia mieloide aguda en la anemia aplásica.', dificultad: 'dificil' },
  { q: '¿Cuál es la conducta ante una anemia aplásica con expansión de una clona de hemoglobinuria paroxística nocturna que produce hemólisis clínicamente significativa?', options: ['Esplenectomía inmediata', 'Quimioterapia de inducción intensiva', 'Inhibidor del complemento (eculizumab o ravulizumab)', 'Radioterapia dirigida al bazo'], correct: 2, explanation: 'El inhibidor del complemento (eculizumab o ravulizumab) es el tratamiento dirigido de elección ante hemólisis clínicamente significativa por expansión de una clona de HPN.', dificultad: 'intermedio' },
  { q: '¿Cuál es la presentación temporal característica de la enfermedad del suero tras la administración de globulina antitimocítica?', options: ['En las primeras 24 horas', '1-2 semanas después de iniciada', 'A los 6 meses', 'Nunca ocurre con este fármaco'], correct: 1, explanation: 'La enfermedad del suero por globulina antitimocítica se presenta característicamente 1-2 semanas después de iniciada.', dificultad: 'facil' },
  { q: '¿Cómo se confirma el rechazo/falla de injerto tras un trasplante alogénico por anemia aplásica?', options: ['Biopsia de piel exclusivamente', 'Quimerismo hematopoyético seriado mostrando pérdida progresiva de las células del donante', 'Elevación aislada de la LDH', 'Un único hemocultivo positivo'], correct: 1, explanation: 'El quimerismo hematopoyético seriado, mostrando pérdida progresiva de las células del donante, confirma el rechazo/falla de injerto.', dificultad: 'intermedio' },
  { q: '¿Cuáles son los 3 factores que componen la puntuación de riesgo EBMT para trasplante en anemia aplásica?', options: ['Edad, hemoglobina, ferritina', 'Sexo, VCM, plaquetas', 'Edad del receptor, tipo de donante, intervalo diagnóstico-trasplante', 'Cariotipo, blastos, LDH'], correct: 2, explanation: 'La puntuación de riesgo EBMT combina la edad del receptor, el tipo de donante, y el intervalo entre el diagnóstico y el trasplante.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 22 años presenta fatiga marcada, fiebre y equimosis de 3 semanas de evolución. La biometría hemática muestra ANC 150/µL, plaquetas 8,000/µL, reticulocitos absolutos 12,000/µL. La biopsia de médula ósea muestra celularidad del 5%, sin fibrosis, infiltración blástica ni displasia. El panel viral es negativo.',
    steps: [
      { q: '¿Cómo se clasifica la gravedad según los criterios de Camitta?', options: ['No grave', 'Muy grave (ANC &lt;200/µL)', 'Grave, pero no muy grave', 'No se puede clasificar sin más estudios'], correct: 1 },
      { q: 'Antes de decidir el tratamiento, ¿qué estudio es obligatorio dado que el paciente tiene menos de 40 años?', options: ['Biopsia hepática', 'Colonoscopia', 'Electromiografía', 'Estudio de fragilidad cromosómica con diepoxibutano o mitomicina C'], correct: 3 },
      { q: 'El estudio de fragilidad cromosómica es negativo y el paciente tiene un hermano HLA-idéntico. ¿Cuál es la conducta más apropiada?', options: ['Trasplante alogénico de células madre hematopoyéticas del hermano HLA-idéntico, como primera línea', 'Andrógenos en monoterapia', 'Vigilancia expectante sin tratamiento', 'Quimioterapia de inducción tipo LMA'], correct: 0 }
    ],
    explanation: 'Con ANC &lt;200/µL y 2 de 3 citopenias en rango grave sobre médula hipocelular, el cuadro cumple criterios de anemia aplásica muy grave. Antes de cualquier tratamiento definitivo en un paciente joven, debe descartarse anemia de Fanconi con fragilidad cromosómica. Descartada esta y con hermano HLA-idéntico disponible, el trasplante alogénico es el tratamiento de primera línea en el paciente joven.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 55 años con anemia aplásica grave confirmada (Camitta) no tiene hermanos HLA-idénticos disponibles.',
    steps: [
      { q: '¿Cuál es la conducta terapéutica de primera línea en este contexto?', options: ['Trasplante de donante no emparentado de inmediato, sin ensayar otra opción', 'Vigilancia expectante', 'Globulina antitimocítica (de caballo) más ciclosporina más eltrombopag', 'Radioterapia corporal total'], correct: 2 },
      { q: 'Dos semanas después de iniciada la globulina antitimocítica, la paciente presenta fiebre, artralgias y exantema, sin foco infeccioso identificado tras estudio dirigido. ¿Cuál es el diagnóstico más probable?', options: ['Enfermedad del suero', 'Sepsis neutropénica', 'Enfermedad de injerto contra huésped', 'Reacción transfusional hemolítica'], correct: 0 },
      { q: '¿Cuál es el tratamiento de esta complicación?', options: ['Suspender toda la inmunosupresión de forma permanente', 'Antibiótico empírico de amplio espectro', 'Transfusión de plaquetas', 'Corticoide sistémico'], correct: 3 }
    ],
    explanation: 'Sin donante HLA-idéntico disponible, la inmunosupresión con globulina antitimocítica, ciclosporina y eltrombopag es la primera línea. La fiebre con artralgias y exantema sin foco infeccioso 1-2 semanas después de la globulina antitimocítica es característica de la enfermedad del suero, una reacción de hipersensibilidad tipo III que se trata con corticoide sistémico.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 19 años presenta ictericia y elevación de transaminasas sin virus hepatotropo identificado en el panel serológico. Se resuelve espontáneamente en 3 semanas. Seis semanas después, desarrolla pancitopenia progresiva.',
    steps: [
      { q: '¿Cuál es el diagnóstico más probable que explica la pancitopenia?', options: ['Hepatitis autoinmune con compromiso medular directo', 'Síndrome de hepatitis-aplasia (anemia aplásica secundaria a la hepatitis seronegativa previa)', 'Anemia megaloblástica por deficiencia de B12', 'Leucemia mieloide crónica'], correct: 1 },
      { q: '¿Qué característica de este síndrome debe tenerse en cuenta al informar el pronóstico?', options: ['Tiene mejor pronóstico que la forma idiopática promedio', 'No requiere ningún tratamiento específico', 'Tiene un curso característicamente más grave y menor respuesta a inmunosupresión que la forma idiopática promedio', 'Se resuelve siempre de forma espontánea en días'], correct: 2 },
      { q: '¿Cuál es la conducta general de tratamiento en este paciente si cumple criterios de gravedad?', options: ['El mismo algoritmo que la forma idiopática (trasplante o inmunosupresión según edad/donante), sin un tratamiento específico dirigido al virus', 'Antivirales de amplio espectro como tratamiento definitivo', 'Solo vigilancia expectante, independientemente de la gravedad', 'Corticoide en monoterapia como tratamiento definitivo'], correct: 0 }
    ],
    explanation: 'La hepatitis aguda seronegativa seguida de pancitopenia semanas después define el síndrome de hepatitis-aplasia, una forma de anemia aplásica secundaria con curso característicamente más grave y menor respuesta a inmunosupresión que el promedio. El tratamiento sigue el mismo algoritmo general que la forma idiopática según gravedad y disponibilidad de donante, sin un tratamiento antiviral específico dirigido.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 24 años con anemia aplásica de reciente diagnóstico tiene talla baja y manchas café con leche en la exploración, sin otras anomalías evidentes.',
    steps: [
      { q: '¿Qué estudio debe solicitarse antes de cualquier tratamiento, dado el fenotipo y la edad?', options: ['Biopsia renal', 'Panel de autoanticuerpos', 'TC de tórax', 'Estudio de fragilidad cromosómica con diepoxibutano o mitomicina C'], correct: 3 },
      { q: 'El estudio es positivo, confirmando anemia de Fanconi. La paciente tiene una hermana con estudio hematológico normal. ¿Qué debe hacerse antes de considerar a la hermana como donante de trasplante?', options: ['Nada adicional, un hemograma normal ya la descarta como portadora', 'Tamizar a la hermana con el mismo estudio de fragilidad cromosómica, porque podría portar el defecto sin manifestación hematológica evidente aún', 'Proceder directamente al trasplante sin más estudio', 'Descartarla automáticamente como donante por ser familiar'], correct: 1 },
      { q: 'Mientras se evalúa la disponibilidad de un donante, ¿cuál es una opción de tratamiento de primera línea no curativa razonable?', options: ['Globulina antitimocítica más ciclosporina', 'Quimioterapia de inducción intensiva', 'Andrógenos (danazol u oximetolona)', 'Radioterapia corporal total'], correct: 2 }
    ],
    explanation: 'El fenotipo (talla baja, manchas café con leche) en una paciente joven con anemia aplásica obliga a descartar anemia de Fanconi con fragilidad cromosómica antes de cualquier tratamiento. Confirmada la Fanconi, los hermanos potenciales donantes deben tamizarse con el mismo estudio, porque podrían portar el defecto genético sin manifestación hematológica evidente. Mientras se define el donante, los andrógenos son una opción de primera línea no curativa; la inmunosupresión estándar no está indicada porque el defecto es intrínseco, no inmunomediado.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 40 años con anemia aplásica tratada con inmunosupresión hace 4 años, en remisión hematológica completa, presenta orina oscura matutina recurrente y dolor abdominal. La biometría hemática muestra Hgb 9.5 g/dL con reticulocitosis relativa.',
    steps: [
      { q: '¿Cuál es la sospecha diagnóstica más probable?', options: ['Expansión clínicamente significativa de una clona de hemoglobinuria paroxística nocturna', 'Recaída de la anemia aplásica en su forma original', 'Transformación a leucemia mieloide aguda', 'Efecto tóxico tardío de la ciclosporina'], correct: 0 },
      { q: '¿Qué estudios confirman la sospecha?', options: ['Biopsia hepática únicamente', 'Panel viral completo', 'Cariotipo de médula ósea únicamente', 'Citometría de flujo de alta sensibilidad para HPN, más LDH/haptoglobina/bilirrubina para documentar hemólisis'], correct: 3 },
      { q: 'Se confirma una clona de HPN grande con hemólisis significativa. ¿Cuál es el tratamiento dirigido de elección?', options: ['Esplenectomía', 'Inhibidor del complemento (eculizumab o ravulizumab)', 'Quimioterapia de inducción', 'Aumentar la dosis de ciclosporina'], correct: 1 }
    ],
    explanation: 'La orina oscura matutina y el dolor abdominal en un paciente con anemia aplásica previa sugieren expansión clínicamente significativa de una clona de HPN. La citometría de flujo de alta sensibilidad confirma la clona, y los marcadores de hemólisis (LDH, haptoglobina, bilirrubina) documentan su actividad. El inhibidor del complemento (eculizumab o ravulizumab) es el tratamiento dirigido de elección para la hemólisis clínicamente significativa asociada a HPN.'
  }
];

export const flashcards = [
  { front: 'Mecanismo predominante de la anemia aplásica adquirida idiopática', back: 'Destrucción inmunomediada de la célula madre hematopoyética por linfocitos T citotóxicos.' },
  { front: 'Hallazgos que deben hacer reconsiderar el diagnóstico de anemia aplásica', back: 'Adenopatías, hepatoesplenomegalia o dolor óseo significativos.' },
  { front: 'Criterios de gravedad de Camitta: componentes', back: 'Celularidad medular &lt;25% + ≥2 de 3: ANC &lt;500, plaquetas &lt;20,000, reticulocitos &lt;20,000/µL.' },
  { front: 'Anemia aplásica muy grave vs. grave', back: 'Mismos criterios, con ANC &lt;200/µL en la muy grave.' },
  { front: 'Prevalencia de clona de HPN en anemia aplásica', back: '~50-70% al diagnóstico o seguimiento; predice mejor respuesta a inmunosupresión.' },
  { front: 'Estudio obligatorio en &lt;40 años antes de tratar', back: 'Fragilidad cromosómica (diepoxibutano/mitomicina C) para excluir anemia de Fanconi.' },
  { front: 'Fármaco clásico asociado a anemia aplásica', back: 'Cloranfenicol (reacción idiosincrásica).' },
  { front: 'Síndrome de hepatitis-aplasia', back: 'Hepatitis seronegativa seguida de aplasia medular semanas después, varones jóvenes, curso más grave.' },
  { front: 'Esquema estándar de primera línea (sin donante)', back: 'Globulina antitimocítica de caballo + ciclosporina + eltrombopag.' },
  { front: 'ATG de caballo vs. conejo', back: 'El de caballo es superior en estudios comparativos directos.' },
  { front: 'Primera línea con hermano HLA-idéntico, paciente joven', back: 'Trasplante alogénico de células madre hematopoyéticas.' },
  { front: 'Soporte transfusional en anemia aplásica: reglas', back: 'Restrictivo, hemoderivados irradiados/leucorreducidos, evitar donantes familiares.' },
  { front: 'Anemia aplásica no grave: conducta', back: 'Vigilancia expectante si no hay dependencia transfusional ni síntomas.' },
  { front: 'Primera línea no curativa en Fanconi sin donante', back: 'Andrógenos (danazol u oximetolona).' },
  { front: 'Por qué NO usar inmunosupresión en formas congénitas', back: 'El defecto es intrínseco a la célula madre, no inmunomediado.' },
  { front: 'Tríada de disqueratosis congénita', back: 'Leucoplasia oral + distrofia ungueal + pigmentación reticular cutánea.' },
  { front: 'Shwachman-Diamond: características', back: 'Neutropenia predominante + insuficiencia pancreática exocrina + talla baja.' },
  { front: 'AA vs. SMD hipoplásico: distinción clave', back: 'Ausencia de clonalidad (cariotipo/NGS normales) en AA; presente en SMD hipoplásico.' },
  { front: 'Umbral profiláctico de transfusión plaquetaria (sin fiebre/sangrado)', back: '&lt;10,000/µL.' },
  { front: 'Cobertura antifúngica empírica: cuándo', back: 'Fiebre &gt;4-7 días pese a antibiótico de amplio espectro.' },
  { front: 'Riesgo de evolución a SMD/LMA a 10 años', back: '~10-15%, mayor con monosomía 7.' },
  { front: 'HPN con hemólisis significativa: tratamiento', back: 'Inhibidor del complemento (eculizumab o ravulizumab).' },
  { front: 'Enfermedad del suero por ATG: presentación', back: 'Fiebre, artralgias, exantema, 1-2 semanas después; se trata con corticoide.' },
  { front: 'Confirmación de rechazo de injerto postrasplante', back: 'Quimerismo hematopoyético seriado con pérdida progresiva de células del donante.' },
  { front: 'Puntuación de riesgo EBMT: componentes', back: 'Edad del receptor, tipo de donante, intervalo diagnóstico-trasplante.' },
  { front: 'Tamizaje de hermanos donantes en síndromes congénitos', back: 'Siempre tamizar primero: podrían portar el defecto sin manifestación hematológica evidente.' }
];

export const caseSteps = [];
export const caseSummary = undefined;

export default { quiz, flashcards, caseSteps, caseSummary };
