// topics/anemia-enfermedad-cronica/study.js: Autoevaluación de Anemia de la Enfermedad Crónica.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Índices `correct` de las 30 preguntas sueltas, en orden: 3,1,0,2,3,0,2,1,0,3,1,2,0,3,2,1,0,2,3,
// 1,2,0,1,3,0,2,3,1,0,2. Recuento: 0×8, 1×7, 2×8, 3×7. Sin racha >2 ni ciclo fijo.
// Índices `correct` de los pasos de las 5 preguntas en cascada (3 pasos c/u), en orden: 0,2,1 /
// 3,1,0 / 2,0,3 / 1,3,2 / 0,2,1. Recuento: 0×4, 1×4, 2×4, 3×3.

export const quiz = [
  { q: '¿Cuál es la segunda causa más frecuente de anemia en el mundo, después de la ferropénica?', options: ['Anemia megaloblástica por B12', 'Anemia hemolítica autoinmune', 'Talasemia menor heterocigota', 'Anemia de la enfermedad crónica'], correct: 3, explanation: 'La anemia de la enfermedad crónica es la segunda causa más frecuente de anemia en el mundo, y la más frecuente en el paciente hospitalizado.', dificultad: 'facil' },
  { q: '¿Qué le pasa a los depósitos de hierro corporal en la AEC pura, a diferencia de la ferropenia verdadera?', options: ['Vacíos, igual que en la ferropenia', 'Conservados pero secuestrados', 'Destruidos por autoinmunidad', 'Aumentados hasta la hemocromatosis'], correct: 1, explanation: 'En la AEC, los depósitos de hierro están conservados o aumentados, pero funcionalmente inaccesibles para la eritropoyesis por el bloqueo mediado por hepcidina.', dificultad: 'facil' },
  { q: '¿Cuál es la hormona reguladora central del metabolismo del hierro cuya elevación media el mecanismo de la AEC?', options: ['Hepcidina', 'Eritropoyetina', 'Transferrina', 'Ferroportina'], correct: 0, explanation: 'La hepcidina, producida por el hígado, es la hormona reguladora central del metabolismo del hierro; su elevación en la inflamación media el mecanismo de la AEC.', dificultad: 'intermedio' },
  { q: '¿Qué hace la hepcidina elevada sobre la ferroportina?', options: ['La activa y aumenta la exportación', 'No modifica su expresión celular', 'La degrada y bloquea la exportación', 'Duplica su expresión génica basal'], correct: 2, explanation: 'La hepcidina degrada la ferroportina, el único exportador conocido de hierro celular, bloqueando la liberación del hierro almacenado.', dificultad: 'facil' },
  { q: '¿Cuál es la citocina inflamatoria principal que estimula la producción hepática de hepcidina?', options: ['Eritropoyetina renal', 'Factor derivado de plaquetas', 'Interleucina-10 (IL-10)', 'Interleucina-6 (IL-6)'], correct: 3, explanation: 'La interleucina-6 es la citocina principal que estimula la producción hepática de hepcidina en la respuesta inflamatoria.', dificultad: 'intermedio' },
  { q: '¿Cuál es el patrón típico de índices eritrocitarios en la AEC?', options: ['Normocítica y normocrómica', 'Macrocítica marcada y persistente', 'Microcítica grave e hipocrómica', 'Normocítica con reticulocitosis'], correct: 0, explanation: 'La AEC produce típicamente una anemia normocítica-normocrómica, con microcitosis discreta solo en casos de larga evolución.', dificultad: 'facil' },
  { q: '¿Qué patrón de TIBC distingue a la AEC de la ferropenia verdadera?', options: ['TIBC elevada en ambas entidades por igual', 'TIBC carece de valor diferencial', 'TIBC baja-normal, elevada en ferropenia', 'TIBC indetectable en la AEC pura'], correct: 2, explanation: 'La TIBC está baja-normal en la AEC, a diferencia de la ferropenia verdadera, donde está elevada.', dificultad: 'intermedio' },
  { q: '¿Qué mide el índice sTfR/log ferritina?', options: ['El déficit total de hierro corporal', 'AEC pura frente a ferropenia verdadera', 'El riesgo trombótico de los agentes AEE', 'La actividad inflamatoria de base'], correct: 1, explanation: 'El índice sTfR/log ferritina distingue la AEC pura de la ferropenia verdadera, particularmente útil cuando la ferritina es ambigua.', dificultad: 'facil' },
  { q: 'Según el índice sTfR/log ferritina, ¿qué valor sugiere AEC pura sin ferropenia?', options: ['Un índice menor de 1', 'Un índice mayor de 2', 'Un índice de 1.5 exacto', 'Un índice de valor negativo'], correct: 0, explanation: 'Un índice &lt;1 es sugestivo de AEC pura, sin ferropenia verdadera concomitante.', dificultad: 'intermedio' },
  { q: '¿Qué valor del índice sTfR/log ferritina sugiere ferropenia verdadera, con o sin AEC concomitante?', options: ['&lt;0.5', 'Entre 0 y 1', 'Exactamente 1', '&gt;2'], correct: 3, explanation: 'Un índice &gt;2 sugiere ferropenia verdadera, con o sin AEC concomitante.', dificultad: 'intermedio' },
  { q: '¿Por qué la ferritina pierde fiabilidad como marcador de depósitos de hierro en la AEC?', options: ['Disminuye de forma artificial con la inflamación', 'Es un reactante de fase aguda y se eleva', 'Solo se altera durante la gestación', 'No guarda relación con el hierro corporal'], correct: 1, explanation: 'La ferritina es un reactante de fase aguda; se eleva con la inflamación independientemente del estado real de los depósitos de hierro.', dificultad: 'facil' },
  { q: '¿Cuál es el mecanismo por el que la enfermedad renal crónica agrava la anemia más allá del componente inflamatorio compartido con la AEC clásica?', options: ['Produce hemólisis crónica intravascular', 'Aumenta la absorción intestinal de hierro', 'El riñón no produce suficiente eritropoyetina', 'Bloquea la síntesis de la hemoglobina'], correct: 2, explanation: 'El riñón enfermo no logra aumentar la producción de eritropoyetina de forma proporcional al grado de anemia, un déficit relativo verdadero.', dificultad: 'intermedio' },
  { q: '¿Qué debe corregirse antes o junto con el inicio de un agente estimulante de la eritropoyesis en la enfermedad renal crónica?', options: ['La ferropenia concomitante asociada', 'La presión arterial hasta valores bajos', 'No hace falta corregir nada antes', 'La función tiroidea de forma aislada'], correct: 0, explanation: 'La ferropenia concomitante debe corregirse antes o junto con el agente estimulante de la eritropoyesis, dado que mejora sustancialmente su eficacia.', dificultad: 'facil' },
  { q: '¿Cuál es el objetivo de hemoglobina recomendado al usar agentes estimulantes de la eritropoyesis, y por qué?', options: ['Normalización completa de la hemoglobina', 'El valor más alto que se pueda lograr', 'No hay un objetivo definido de Hb', 'Moderado, 10-11.5 g/dL, sin normalizar'], correct: 3, explanation: 'Se recomienda un objetivo moderado (10-11.5 g/dL), evitando la normalización completa dado el mayor riesgo trombótico asociado a objetivos más altos.', dificultad: 'intermedio' },
  { q: '¿Qué corrige de forma más completa y sostenida la anemia de la enfermedad renal crónica?', options: ['La diálisis peritoneal por sí sola', 'Los diuréticos de asa en dosis altas', 'El trasplante renal exitoso', 'La restricción proteica estricta'], correct: 2, explanation: 'El trasplante renal exitoso ofrece la corrección más completa y sostenida al restaurar la producción endógena de eritropoyetina.', dificultad: 'dificil' },
  { q: '¿Por qué la anemia combinada (AEC + ferropenia verdadera) es el escenario diagnóstico más desafiante de este tema?', options: ['Porque cursa sin síntomas clínicos', 'Porque los marcadores se superponen', 'Porque solo ocurre en la infancia', 'Porque carece de tratamiento eficaz'], correct: 1, explanation: 'Los marcadores de laboratorio de la AEC y la ferropenia verdadera se superponen y pueden enmascararse mutuamente, dificultando el diagnóstico.', dificultad: 'intermedio' },
  { q: '¿Cuál es la enfermedad que produce clásicamente el mecanismo combinado de AEC más pérdida sanguínea digestiva directa?', options: ['Enfermedad inflamatoria intestinal activa', 'Hipotiroidismo', 'Osteoartritis', 'Diabetes mellitus tipo 2 sin complicaciones'], correct: 0, explanation: 'La enfermedad inflamatoria intestinal activa produce tanto el componente de AEC como pérdida sanguínea digestiva directa por la inflamación de la mucosa.', dificultad: 'facil' },
  { q: '¿Está indicado el hierro en la anemia combinada con ferropenia verdadera, a diferencia de la AEC pura?', options: ['No, el hierro no aporta en la AEC', 'Solo en dosis mínimas de mantenimiento', 'Sí, a diferencia de la AEC pura', 'Solo si el paciente lo solicita'], correct: 2, explanation: 'A diferencia de la AEC pura, en la forma combinada con ferropenia verdadera sí está indicada la reposición de hierro.', dificultad: 'intermedio' },
  { q: '¿Cuál es la vía preferida de reposición de hierro en la enfermedad inflamatoria intestinal activa con ferropenia concomitante?', options: ['Hierro oral en dosis muy altas', 'Dieta rica en hierro, sin suplemento', 'Transfusión profiláctica programada', 'Hierro intravenoso, mejor tolerado'], correct: 3, explanation: 'El hierro intravenoso es la vía preferida en la enfermedad inflamatoria intestinal activa, dado que el oral puede exacerbar los síntomas y su absorción está reducida por la inflamación.', dificultad: 'facil' },
  { q: '¿Qué agrava específicamente la anemia del paciente crítico más allá del mecanismo inflamatorio agudo?', options: ['El uso profiláctico de antibióticos', 'La flebotomía diagnóstica repetida', 'La sedación profunda prolongada', 'La ventilación en posición prona'], correct: 1, explanation: 'La flebotomía diagnóstica repetida es un componente iatrogénico reconocido que agrava la anemia del paciente crítico, y es en gran medida prevenible.', dificultad: 'intermedio' },
  { q: '¿Cuál es la medida preventiva más simple y de mayor impacto acumulado en la anemia del paciente crítico?', options: ['Transfusión profiláctica diaria', 'Suspender toda toma de laboratorio', 'Minimizar la flebotomía diagnóstica', 'Eritropoyetina rutinaria en la UCI'], correct: 2, explanation: 'Minimizar la flebotomía diagnóstica a lo estrictamente necesario es la medida preventiva más simple y de mayor impacto acumulado.', dificultad: 'facil' },
  { q: '¿Cuál es el umbral de transfusión recomendado en el paciente crítico hemodinámicamente estable sin cardiopatía isquémica activa?', options: ['Hemoglobina menor de 7 g/dL', 'Hemoglobina menor de 10 g/dL', 'Cualquier valor por debajo del normal', 'Según la preferencia del paciente'], correct: 0, explanation: 'El umbral restrictivo recomendado es hemoglobina &lt;7 g/dL en el paciente crítico estable sin cardiopatía isquémica activa.', dificultad: 'intermedio' },
  { q: '¿Se recomienda el uso rutinario de agentes estimulantes de la eritropoyesis en el paciente crítico general?', options: ['Sí, en todo paciente de UCI con anemia', 'No, sin beneficio y con riesgo trombótico', 'Solo en pacientes menores de 40 años', 'Solo si la anemia es grave y sintomática'], correct: 1, explanation: 'El uso rutinario de agentes estimulantes de la eritropoyesis en el paciente crítico general no ha demostrado beneficio consistente y se asocia a mayor riesgo trombótico.', dificultad: 'facil' },
  { q: '¿Cuál es el riesgo de administrar hierro a un paciente con AEC pura sin ferropenia verdadera?', options: ['Corrige la anemia de forma inmediata', 'Reduce el riesgo de infección activa', 'Mejora la respuesta a los agentes AEE', 'No mejora y puede favorecer infecciones'], correct: 3, explanation: 'El hierro no corrige el bloqueo por hepcidina y no mejora la anemia; además, el hierro libre no utilizado puede favorecer teóricamente microorganismos que lo requieren para proliferar.', dificultad: 'intermedio' },
  { q: '¿Cuál es la conducta correcta cuando el índice sTfR/log ferritina resulta &lt;1 en un paciente con anemia y enfermedad crónica?', options: ['No indicar hierro, es AEC pura', 'Indicar hierro intravenoso en dosis altas', 'Indicar transfusión profiláctica', 'Repetir el estudio cada semana'], correct: 0, explanation: 'Un índice &lt;1 confirma AEC pura sin ferropenia, por lo que no debe indicarse hierro.', dificultad: 'facil' },
  { q: '¿Cuál es el mecanismo por el que los agentes estimulantes de la eritropoyesis aumentan el riesgo trombótico?', options: ['Producen vasodilatación excesiva', 'Reducen la producción de plaquetas', 'Aumentan la viscosidad sanguínea', 'Bloquean la cascada de coagulación'], correct: 2, explanation: 'Estos agentes aumentan la viscosidad sanguínea y activan directamente receptores de eritropoyetina presentes en plaquetas y células endoteliales.', dificultad: 'intermedio' },
  { q: '¿En qué contexto se ha observado la señal de posible progresión tumoral asociada a agentes estimulantes de la eritropoyesis?', options: ['En cualquier uso, sin relación con la meta', 'Solo en la enfermedad renal sin cáncer', 'Solo en el paciente pediátrico oncológico', 'Con metas de Hb cercanas a lo normal'], correct: 3, explanation: 'La señal de progresión tumoral se ha observado predominantemente en ensayos con objetivo de hemoglobina cercano a la normalización completa en el contexto oncológico.', dificultad: 'dificil' },
  { q: '¿Por qué la interpretación de la ferritina es especialmente cautelosa al evaluar sobrecarga de hierro transfusional en un paciente con AEC?', options: ['La ferritina es normal en la sobrecarga', 'Ya está elevada por la inflamación', 'La ferritina no se puede medir así', 'La sobrecarga no ocurre en la AEC'], correct: 1, explanation: 'La ferritina ya está elevada de base por la inflamación en la AEC, lo que obliga a interpretar su tendencia con cautela adicional al evaluar sobrecarga de hierro.', dificultad: 'intermedio' },
  { q: '¿Cuál es el método de referencia para cuantificar de forma no invasiva la carga de hierro cuando la interpretación de la ferritina es dudosa?', options: ['RM hepática y cardiaca con T2*', 'Ferritina sérica aislada repetida', 'Biopsia hepática percutánea', 'Tomografía computarizada simple'], correct: 0, explanation: 'La RM con secuencia T2* es el método de referencia para cuantificar de forma no invasiva la carga de hierro hepática y cardiaca.', dificultad: 'facil' },
  { q: '¿Cuál es el riesgo de atribuir automáticamente toda anemia a una enfermedad crónica conocida sin estudio dirigido?', options: ['No hay riesgo, la atribución es correcta', 'Aumentar la eritropoyetina compensadora', 'Retrasar una causa concomitante tratable', 'Reducir la actividad inflamatoria basal'], correct: 2, explanation: 'Atribuir automáticamente la anemia sin estudio dirigido puede retrasar el diagnóstico de una causa concomitante tratable, incluida una neoplasia gastrointestinal oculta.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 58 años con artritis reumatoide activa de larga evolución presenta fatiga. Hb 10.2 g/dL, VCM 84 fL, ferritina 180 ng/mL, TIBC baja.',
    steps: [
      { q: '¿Qué sugiere este perfil de hierro?', options: ['AEC clásica, con ferritina normal o alta', 'Ferropenia verdadera aislada sin AEC', 'Deficiencia de B12 concomitante grave', 'Hemólisis aguda intravascular activa'], correct: 0 },
      { q: 'Para confirmar la ausencia de ferropenia verdadera concomitante, ¿qué estudio es más útil?', options: ['Electroforesis de hemoglobina', 'Coombs directa', 'Índice sTfR/log ferritina', 'Aspirado de médula ósea de rutina'], correct: 2 },
      { q: 'El índice resulta &lt;1. ¿Cuál es la conducta terapéutica más apropiada respecto al hierro?', options: ['Iniciar hierro intravenoso en dosis altas', 'No indicar hierro, controlar la artritis', 'Iniciar hierro oral de forma indefinida', 'Transfusión profiláctica mensual'], correct: 1 }
    ],
    explanation: 'La ferritina normal/alta con TIBC baja es compatible con AEC clásica, no con ferropenia verdadera. El índice sTfR/log ferritina confirma la ausencia de ferropenia; con un resultado &lt;1, no debe indicarse hierro, y el manejo debe enfocarse en controlar la actividad de la artritis reumatoide de base.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 67 años con enfermedad renal crónica estadio 4 (TFG 25 mL/min/1.73m²) presenta fatiga progresiva. Hb 9.0 g/dL, ferritina 40 ng/mL, saturación de transferrina 15%.',
    steps: [
      { q: '¿Cuál es el paso más apropiado antes de iniciar cualquier agente estimulante de la eritropoyesis?', options: ['Iniciar diálisis de urgencia sin más evaluación', 'Iniciar el agente estimulante de la eritropoyesis de inmediato sin evaluar el hierro', 'Solicitar biopsia renal', 'Corregir la ferropenia concomitante, frecuente en este contexto'], correct: 3 },
      { q: 'Una vez corregida la ferropenia, ¿cuál es el objetivo de hemoglobina apropiado al iniciar el agente estimulante de la eritropoyesis?', options: ['Normalización completa, 14-15 g/dL', 'Moderado, 10-11.5 g/dL', 'El más bajo posible, cerca de 6 g/dL', 'Sin un objetivo de Hb definido'], correct: 1 },
      { q: '¿Qué intervención ofrece la corrección más completa y sostenida de esta anemia si el paciente progresa a enfermedad renal terminal?', options: ['Trasplante renal exitoso', 'Diálisis peritoneal continua', 'Restricción proteica estricta', 'Vitamina D en dosis altas'], correct: 0 }
    ],
    explanation: 'La ferropenia concomitante (frecuente en la enfermedad renal crónica) debe corregirse antes de iniciar un agente estimulante de la eritropoyesis. El objetivo de hemoglobina debe ser moderado, evitando la normalización completa. El trasplante renal exitoso, si el paciente progresa a enfermedad renal terminal, ofrece la corrección más completa y sostenida al restaurar la producción endógena de eritropoyetina.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 32 años con enfermedad de Crohn activa presenta fatiga marcada, Hb 8.2 g/dL (más baja de lo esperado por la actividad de su enfermedad), ferritina 45 ng/mL, índice sTfR/log ferritina 1.6.',
    steps: [
      { q: '¿Qué sugiere este índice sTfR/log ferritina?', options: ['AEC pura sin componente carencial', 'Ferropenia pura sin inflamación', 'Zona indeterminada, anemia combinada', 'Resultado sin valor interpretativo'], correct: 2 },
      { q: '¿Qué se debe investigar activamente en este contexto?', options: ['Una pérdida sanguínea digestiva', 'Solo la actividad de la enfermedad', 'Una causa psiquiátrica de la fatiga', 'No hace falta investigar más'], correct: 0 },
      { q: '¿Cuál es la vía de reposición de hierro más apropiada en este contexto?', options: ['Hierro oral en dosis altas', 'No dar hierro, la ferritina no es baja', 'Transfusión sin estudio adicional', 'Hierro intravenoso, mejor tolerado'], correct: 3 }
    ],
    explanation: 'Un índice sTfR/log ferritina de 1.6 cae en la zona indeterminada, sugestiva de anemia combinada. En la enfermedad inflamatoria intestinal activa debe investigarse activamente una fuente de pérdida sanguínea digestiva concomitante. La reposición de hierro es apropiada aquí (a diferencia de la AEC pura), y la vía intravenosa es preferida dado que el oral puede exacerbar los síntomas y su absorción está reducida.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 45 años en UCI por sepsis de origen abdominal, día 10 de estancia, presenta caída progresiva de hemoglobina de 12 a 8.5 g/dL sin sangrado activo evidente. Se han realizado múltiples estudios de laboratorio diarios.',
    steps: [
      { q: '¿Cuál es el paso diagnóstico inicial más apropiado?', options: ['Asumir anemia de la enfermedad crítica', 'Descartar sangrado y hemólisis', 'Transfundir de inmediato sin estudio', 'Suspender la monitorización de rutina'], correct: 1 },
      { q: 'Descartadas otras causas, ¿qué componente iatrogénico reconocido puede estar contribuyendo de forma relevante?', options: ['La posición del paciente en la cama', 'El tipo de sedante utilizado', 'La temperatura ambiente de la UCI', 'La flebotomía diagnóstica repetida'], correct: 3 },
      { q: 'El paciente está hemodinámicamente estable, sin cardiopatía isquémica activa, con Hb 7.2 g/dL. ¿Cuál es la conducta más apropiada según el umbral transfusional restrictivo?', options: ['Transfundir de inmediato, Hb menor de 10', 'Iniciar un agente estimulante de rutina', 'No transfundir, el umbral es 7 g/dL', 'Iniciar hierro intravenoso sin perfil'], correct: 2 }
    ],
    explanation: 'Antes de atribuir la caída de hemoglobina a la anemia de la enfermedad crítica, debe descartarse sangrado no reconocido y hemólisis. La flebotomía diagnóstica repetida es un componente iatrogénico reconocido que contribuye a esta anemia. Con Hb 7.2 g/dL y estabilidad hemodinámica sin cardiopatía isquémica, el umbral restrictivo (Hb &lt;7 g/dL) indica que aún no está indicada la transfusión.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 78 años con diabetes mellitus tipo 2 e hipertensión, sin otra enfermedad inflamatoria activa conocida, presenta anemia de Hb 9.5 g/dL detectada en un control de rutina, atribuida inicialmente por su médico a "la edad". La hemoglobina ha descendido progresivamente en los últimos 3 controles.',
    steps: [
      { q: '¿Es apropiado atribuir esta anemia solo a la edad sin más estudio?', options: ['No, la anemia requiere estudio dirigido', 'Sí, la edad basta como única explicación', 'Sí, si no tiene síntomas asociados', 'Solo si el paciente lo pide expresamente'], correct: 0 },
      { q: 'Dado el descenso progresivo de hemoglobina en controles sucesivos, ¿qué se debe investigar de forma prioritaria en un varón de esta edad?', options: ['Repetir la biometría hemática en un año', 'Un estudio genético de hemoglobinopatías', 'Una pérdida digestiva oculta', 'Solo vigilancia clínica periódica'], correct: 2 },
      { q: '¿Qué estudio de laboratorio ayuda a orientar si hay o no un componente inflamatorio verdadero (AEC) además de la posible causa concomitante?', options: ['La velocidad de sedimentación aislada', 'Perfil de hierro con índice sTfR', 'Prueba de Coombs directa e indirecta', 'Electroforesis de proteínas séricas'], correct: 1 }
    ],
    explanation: 'La anemia nunca debe atribuirse automáticamente a la edad sin un estudio dirigido. El descenso progresivo de hemoglobina en un varón de edad avanzada obliga a investigar una fuente de pérdida sanguínea digestiva oculta mediante endoscopia y colonoscopia. El perfil de hierro completo con el índice sTfR/log ferritina ayuda a orientar si además hay un componente inflamatorio verdadero.'
  }
];

export const flashcards = [
  { front: 'Anemia de la enfermedad crónica: posición epidemiológica', back: 'Segunda causa más frecuente de anemia en el mundo; la más frecuente en el paciente hospitalizado.' },
  { front: 'Estado de los depósitos de hierro en la AEC', back: 'Conservados o aumentados, pero secuestrados y funcionalmente inaccesibles ("ferropenia funcional").' },
  { front: 'Hormona central del mecanismo de la AEC', back: 'Hepcidina, elevada por IL-6, degrada la ferroportina.' },
  { front: 'Efecto de la hepcidina sobre la ferroportina', back: 'La degrada, bloqueando la exportación de hierro de macrófagos y enterocitos.' },
  { front: 'Patrón hematológico típico de la AEC', back: 'Normocítica-normocrómica (discretamente microcítica si es prolongada).' },
  { front: 'TIBC: AEC vs. ferropenia verdadera', back: 'Baja-normal en AEC; elevada en ferropenia verdadera.' },
  { front: 'Índice sTfR/log ferritina: interpretación', back: '&lt;1 → AEC pura. &gt;2 → ferropenia verdadera. 1-2 → indeterminado/combinada.' },
  { front: 'Por qué la ferritina pierde fiabilidad en la AEC', back: 'Es reactante de fase aguda, se eleva con la inflamación sin reflejar depósitos reales.' },
  { front: 'Mecanismo adicional en la anemia de la enfermedad renal crónica', back: 'Déficit relativo verdadero de eritropoyetina, más el componente inflamatorio compartido.' },
  { front: 'Antes de iniciar un agente estimulante de la eritropoyesis en ERC', back: 'Corregir la ferropenia concomitante.' },
  { front: 'Objetivo de hemoglobina con agentes estimulantes de la eritropoyesis', back: 'Moderado (10-11.5 g/dL); evitar normalización completa (mayor riesgo trombótico).' },
  { front: 'Corrección más completa de la anemia de ERC', back: 'Trasplante renal exitoso (restaura producción endógena de EPO).' },
  { front: 'Por qué la anemia combinada es el diferencial más difícil', back: 'Los marcadores de AEC y ferropenia se superponen y se enmascaran mutuamente.' },
  { front: 'Enfermedad con mecanismo combinado clásico (AEC + sangrado)', back: 'Enfermedad inflamatoria intestinal activa.' },
  { front: 'Hierro en anemia combinada vs. AEC pura', back: 'SÍ indicado en combinada; contraindicado en AEC pura.' },
  { front: 'Vía preferida de hierro en enfermedad inflamatoria intestinal activa', back: 'Intravenosa (oral exacerba síntomas, absorción reducida por inflamación mucosa).' },
  { front: 'Componente iatrogénico de la anemia del paciente crítico', back: 'Flebotomía diagnóstica repetida, en gran medida prevenible.' },
  { front: 'Medida preventiva central en la anemia del paciente crítico', back: 'Minimizar volumen y frecuencia de la flebotomía diagnóstica.' },
  { front: 'Umbral transfusional restrictivo en el paciente crítico estable', back: 'Hemoglobina &lt;7 g/dL.' },
  { front: 'Agentes estimulantes de la eritropoyesis en el paciente crítico general', back: 'NO recomendados de rutina; sin beneficio en mortalidad, mayor riesgo trombótico.' },
  { front: 'Riesgo de dar hierro en AEC pura sin ferropenia', back: 'No corrige la anemia (mecanismo intacto); riesgo teórico de favorecer microorganismos que requieren hierro.' },
  { front: 'Mecanismo del mayor riesgo trombótico con agentes estimulantes de la eritropoyesis', back: 'Aumento de viscosidad sanguínea + activación de receptores de EPO en plaquetas/endotelio.' },
  { front: 'Contexto de la señal de progresión tumoral con estos agentes', back: 'Objetivo de hemoglobina cercano a normalización completa en pacientes oncológicos.' },
  { front: 'Por qué interpretar la ferritina con cautela en sobrecarga de hierro transfusional en AEC', back: 'Ya está elevada de base por la inflamación, independiente de la sobrecarga real.' },
  { front: 'Método de referencia para carga de hierro cuando la ferritina es dudosa', back: 'RM hepática y cardiaca con secuencia T2*.' },
  { front: 'Riesgo de atribuir toda anemia a "enfermedad crónica" sin estudio', back: 'Retrasa el diagnóstico de una causa tratable, incluida neoplasia gastrointestinal oculta.' },
  { front: 'Estudio sistemático ante cualquier anemia con enfermedad crónica conocida', back: 'Perfil de hierro con índice sTfR/log ferritina + B12/folato, sin atribución automática.' }
];
