// topics/patologia-pleural/study.js: Autoevaluacion de Patologia Pleural.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// 48 subpreguntas (30 sueltas + 6 cascadas de 3 pasos) y 32 tarjetas.
// Distribucion de `correct` en el banco completo: 12 en cada posicion.
// Sin em dash (ver [[feedback-no-em-dash]]). Texto sin acentos.

export const quiz = [
  { q: 'Cuantos criterios de Light hacen falta para clasificar un derrame como exudado?', options: ['Uno cualquiera de los tres', 'Los tres a la vez', 'Al menos dos de los tres', 'Los dos cocientes, sin el tercero'], correct: 0, explanation: 'Basta con uno: cociente de proteinas mayor de 0.5, cociente de lactato deshidrogenasa mayor de 0.6, o lactato deshidrogenasa del liquido por encima de dos tercios del limite alto serico. Esa exigencia baja hace la regla muy sensible y poco especifica, que es justo lo buscado.', dificultad: 'facil' },
  { q: 'Que muestra hay que extraer siempre junto con el liquido pleural?', options: ['Una muestra de orina de la misma ma&#241;ana', 'Un hemocultivo de dos localizaciones', 'Una muestra de suero simultanea', 'Una muestra de esputo inducido'], correct: 2, explanation: 'Dos de los tres criterios de Light son cocientes entre el liquido y el suero, de modo que sin la muestra serica la regla no se puede aplicar y hay que repetir la puncion. Es uno de los olvidos mas frecuentes y de los mas evitables.', dificultad: 'facil' },
  { q: 'En que paciente clasifican mal los criterios de Light un trasudado como exudado?', options: ['En el que tiene una neumonia bilateral asociada', 'En la insuficiencia cardiaca con diureticos', 'En el cirrotico con ascitis a tension refractaria', 'En el que tiene un derrame bilateral muy extenso'], correct: 1, explanation: 'Los diureticos concentran las proteinas del liquido pleural y lo empujan por encima de los umbrales. Ocurre en alrededor de una cuarta parte de los trasudados, y es la situacion en la que hay que calcular el gradiente de albumina.', dificultad: 'intermedio' },
  { q: 'Que gradiente de albumina reclasifica un derrame como trasudado?', options: ['Mayor de 0.5 g/dL', 'Mayor de 2.5 g/dL', 'Mayor de 3.1 g/dL', 'Mayor de 1.2 g/dL'], correct: 3, explanation: 'Se calcula restando la albumina del liquido a la del suero. El gradiente de PROTEINAS tiene un umbral distinto, mayor de 3.1 g/dL. Ambos se usan solo como rescate cuando la clinica apunta a trasudado y Light dice exudado.', dificultad: 'intermedio' },
  { q: 'Que recomienda la guia de enfermedad pleural sobre la toracocentesis?', options: ['Que se haga siempre guiada por imagen', 'Que se haga en el punto de maxima matidez', 'Que se reserve a derrames de mas de 2 cm', 'Que se acompa&#241;e de radiografia sistematica'], correct: 0, explanation: 'La recomendacion es fuerte: la puncion a ciegas multiplica el neumotorax iatrogenico y la puncion en seco. En la misma linea, las biopsias pleurales ciegas no deben realizarse, y se sustituyen por biopsia guiada por imagen o por toracoscopia.', dificultad: 'facil' },
  { q: 'Que hallazgo en el liquido de una neumonia obliga a colocar un tubo de drenaje?', options: ['Una proteina total mayor de 3 g/dL', 'Un predominio de linfocitos en la formula', 'Un pH de 7.2 o menor', 'Una adenosina desaminasa elevada'], correct: 2, explanation: 'Indica derrame complicado: las bacterias y los neutrofilos consumen glucosa y generan acido en el espacio pleural. Junto con la glucosa por debajo de 60 mg/dL, la lactato deshidrogenasa por encima de 1000 U/L y la microbiologia positiva, define el derrame que el antibiotico solo no resuelve.', dificultad: 'facil' },
  { q: 'Como debe recogerse la muestra para medir el pH del liquido pleural?', options: ['En tubo seco, sin anticoagulante alguno', 'En tubo con heparina de litio y refrigerada', 'En frasco de hemocultivo aerobio', 'En jeringa de gasometria, sin aire ni anestesico'], correct: 3, explanation: 'Las burbujas de aire elevan falsamente el pH y el anestesico local que se cuela en la muestra lo baja, de modo que ambos errores llevan a decisiones equivocadas sobre el drenaje. Se procesa pronto, y en el pus franco no se mide.', dificultad: 'dificil' },
  { q: 'Que conducta corresponde ante la salida de pus franco en la toracocentesis?', options: ['Enviar el pH antes de tomar una decision', 'Drenar sin necesidad de mas analisis', 'Repetir la puncion en 24 horas', 'Iniciar antibiotico y reevaluar en 48 horas'], correct: 1, explanation: 'El pus define el empiema por si solo. Medir el pH en pus franco estropea el gasometro y no cambia nada, porque la conducta ya esta decidida. El antibiotico se pauta, pero sin drenaje no resuelve la infeccion pleural.', dificultad: 'facil' },
  { q: 'Que tratamiento intrapleural se usa cuando el drenaje cesa con coleccion residual?', options: ['Estreptoquinasa en dosis unica diaria', 'Activador del plasminogeno en monoterapia', 'Activador del plasminogeno mas DNasa', 'DNasa sola durante cinco dias seguidos'], correct: 2, explanation: 'Se administran 10 mg de activador tisular del plasminogeno y 5 mg de DNasa, dos veces al dia durante 3 dias. El fibrinolitico rompe los tabiques y la DNasa reduce la viscosidad del pus: por separado no funcionan, y la estreptoquinasa no debe usarse.', dificultad: 'intermedio' },
  { q: 'Que calibre de tubo se prefiere para drenar una infeccion pleural?', options: ['Fino, de 10 a 14 French', 'Grueso, de 28 a 32 French', 'Grueso, de 20 a 24 French', 'Fino, pero solo si no hay tabiques'], correct: 0, explanation: 'Los estudios comparativos no encontraron ventaja en el calibre grueso y si mucho mas dolor. La permeabilidad del tubo fino se mantiene con lavados periodicos, y su atasco es la causa mas frecuente de un falso fracaso del drenaje.', dificultad: 'intermedio' },
  { q: 'Cuando corresponde derivar a cirugia una infeccion pleural?', options: ['Al confirmar la presencia de tabiques', 'Al identificar un anaerobio en el cultivo', 'Al superar los 14 dias de antibiotico', 'Ante fracaso del drenaje a los 5 a 7 dias'], correct: 3, explanation: 'Tambien ante sepsis persistente o pulmon atrapado por corteza fibrosa. La cirugia toracoscopica con desbridamiento y decorticacion es la opcion habitual, y retrasarla mas alla de ese plazo empeora el resultado funcional.', dificultad: 'intermedio' },
  { q: 'Que componentes integran la escala RAPID de la infeccion pleural?', options: ['Edad, proteina C reactiva, pH, albumina y fiebre', 'Urea, edad, purulencia, origen y albumina', 'Urea, edad, pH, glucosa y lactato deshidrogenasa', 'Edad, comorbilidad, purulencia, pH y albumina'], correct: 1, explanation: 'El acronimo recoge funcion renal, edad, purulencia, origen de la infeccion (comunitario u hospitalario) y factores dieteticos representados por la albumina. Estratifica el riesgo de mala evolucion, sin decidir por si sola el drenaje ni la cirugia.', dificultad: 'intermedio' },
  { q: 'Que signo tomografico distingue un empiema de un absceso pulmonar?', options: ['El signo de la pleura escindida', 'El signo del halo peritumoral', 'El broncograma aereo interno', 'El signo del creciente aereo'], correct: 0, explanation: 'El empiema es lenticular y comprime el pulmon, con realce de ambas hojas pleurales separadas por el liquido; el absceso es redondeado, de pared gruesa e irregular y forma angulos agudos con la pleura. Confundirlos importa: un absceso no se drena con tubo pleural.', dificultad: 'dificil' },
  { q: 'Cual es el rendimiento aproximado de la citologia en el derrame pleural maligno?', options: ['Cerca del 20%', 'Cerca del 40%', 'Cerca del 60%', 'Cerca del 95%'], correct: 2, explanation: 'Mejora al repetir la puncion y al enviar volumenes mayores. Cuando sigue siendo negativa y la sospecha persiste, se pasa a biopsia guiada por imagen o a toracoscopia medica, que tiene un rendimiento muy alto y permite tratar en el mismo acto.', dificultad: 'intermedio' },
  { q: 'Que situacion hace preferible el cateter pleural permanente a la pleurodesis?', options: ['La citologia positiva para adenocarcinoma', 'El derrame de mas de dos litros evacuados', 'La expectativa de vida superior a un a&#241;o', 'El pulmon atrapado que no reexpande'], correct: 3, explanation: 'La pleurodesis necesita que las dos hojas pleurales contacten, y con el pulmon atrapado eso no ocurre. En el paciente que si reexpande, la guia recomienda OFRECER A ELEGIR entre pleurodesis con talco y cateter permanente, comentando riesgos y beneficios.', dificultad: 'intermedio' },
  { q: 'Que dato de la exploracion separa un derrame de una consolidacion?', options: ['La abolicion del murmullo vesicular', 'La disminucion de las vibraciones vocales', 'La presencia de matidez a la percusion', 'La aparicion de dolor pleuritico referido'], correct: 1, explanation: 'El liquido aisla y las vibraciones DISMINUYEN, mientras que el pulmon consolidado transmite mejor el sonido y AUMENTAN. La matidez y la abolicion del murmullo aparecen en los dos y no distinguen nada por si solas.', dificultad: 'intermedio' },
  { q: 'Cual es el cambio principal de la guia de 2023 en el manejo del neumotorax?', options: ['Se amplia el uso de la pleurodesis quimica inicial', 'Se recomienda tomografia en todos los casos', 'Se decide por sintomas y riesgo, no por tama&#241;o', 'Se sustituye el drenaje por aspiracion con aguja'], correct: 2, explanation: 'Durante decadas se drenaba todo neumotorax de mas de 2 cm. El ensayo que comparo el manejo conservador con el intervencionista mostro resultados no inferiores y muchas menos complicaciones, y hoy el conservador es una opcion en el primario poco sintomatico con independencia del tama&#241;o.', dificultad: 'intermedio' },
  { q: 'Cual de estas es una caracteristica de alto riesgo en el neumotorax?', options: ['El hemoneumotorax', 'El dolor pleuritico intenso', 'El antecedente de neumotorax previo', 'La talla alta con complexion delgada'], correct: 0, explanation: 'Junto con la inestabilidad hemodinamica, la hipoxia significativa, la bilateralidad, la enfermedad pulmonar de base y la edad mayor de 50 a&#241;os con tabaquismo importante. Cualquiera de ellas lleva directamente al drenaje.', dificultad: 'intermedio' },
  { q: 'Que conducta corresponde a un neumotorax espontaneo primario grande y asintomatico?', options: ['Drenaje con tubo fino e ingreso', 'Aspiracion con aguja y alta posterior', 'Pleurodesis quimica en el primer episodio', 'Manejo conservador con observacion'], correct: 3, explanation: 'Sin caracteristicas de alto riesgo y con sintomas minimos, el tama&#241;o ya no obliga a intervenir. Se pautan observacion, analgesia, control clinico y radiologico e instrucciones escritas sobre cuando volver a consultar.', dificultad: 'dificil' },
  { q: 'Como se diagnostica un neumotorax a tension?', options: ['Con tomografia toracica urgente', 'Clinicamente, sin esperar a la imagen', 'Con radiografia en espiracion forzada', 'Con medicion de la presion intrapleural'], correct: 1, explanation: 'Hipotension, ingurgitacion yugular, desviacion traqueal, timpanismo y abolicion del murmullo bastan para actuar. El tiempo que se pierde esperando una imagen puede costar la vida, y la descompresion revierte el cuadro en segundos.', dificultad: 'facil' },
  { q: 'Donde se recomienda hoy la descompresion con aguja del neumotorax a tension en el adulto?', options: ['En el 4.o o 5.o espacio intercostal, linea axilar media', 'En el 2.o espacio intercostal, linea medioclavicular', 'En el 7.o espacio intercostal, linea axilar posterior', 'En el 5.o espacio intercostal, linea paraesternal'], correct: 0, explanation: 'La pared toracica es mas delgada en esa localizacion que en el segundo espacio de la linea medioclavicular, donde una proporcion notable de las punciones no alcanza el espacio pleural. Tras descomprimir se coloca siempre un tubo de drenaje.', dificultad: 'intermedio' },
  { q: 'Por que se hipotensa un paciente con neumotorax a tension?', options: ['Por vasodilatacion refleja de origen vagal', 'Por hipoxemia grave con acidosis lactica', 'Por acodamiento de las venas cavas', 'Por depresion directa de la contractilidad'], correct: 2, explanation: 'La presion pleural positiva desplaza el mediastino y acoda las cavas, con lo que se hunde el retorno venoso: el fallo es hemodinamico antes que respiratorio. Por eso el paciente no responde a volumen y por eso la descompresion lo resuelve de inmediato.', dificultad: 'dificil' },
  { q: 'Cuando se indica cirugia de prevencion de recurrencias en el neumotorax espontaneo?', options: ['Tras el primer episodio en todo paciente joven', 'Ante un segundo episodio del mismo lado', 'Cuando el neumotorax supera los 3 cm', 'Si la fuga aerea dura mas de 24 horas'], correct: 1, explanation: 'Tambien ante un primer episodio del lado contrario, ante fuga aerea persistente y, tras el primer episodio, si la recurrencia seria especialmente grave: profesiones de riesgo como buceadores, pilotos o militares, o neumotorax a tension inicial.', dificultad: 'intermedio' },
  { q: 'Que consejo corresponde al alta de un paciente con neumotorax espontaneo?', options: ['Reposo absoluto domiciliario durante cuatro semanas', 'Evitar el ejercicio fisico de por vida', 'Volar solo con oxigeno suplementario', 'Buceo contraindicado salvo cirugia definitiva'], correct: 3, explanation: 'El buceo queda contraindicado de por vida salvo cirugia definitiva bilateral, porque la expansion del gas durante el ascenso puede producir un neumotorax a tension. Volar se permite tras la resolucion completa comprobada, y no hace falta reposo absoluto.', dificultad: 'intermedio' },
  { q: 'Que proporcion de las hemoptisis amenazantes procede de la circulacion bronquial?', options: ['Alrededor del 30%', 'Alrededor del 50%', 'Alrededor del 90%', 'Alrededor del 10%'], correct: 2, explanation: 'La circulacion bronquial es sistemica y de alta presion, y en la enfermedad cronica prolifera y desarrolla anastomosis. Esa es la base anatomica de que el tratamiento de eleccion sea la embolizacion arterial bronquial y no la cirugia.', dificultad: 'intermedio' },
  { q: 'Cual es la primera maniobra ante una hemoptisis amenazante?', options: ['Colocar al paciente sobre el lado que sangra', 'Sentar al paciente para facilitar la expectoracion', 'Colocar al paciente en decubito supino estricto', 'Colocar al paciente sobre el lado que no sangra'], correct: 0, explanation: 'La gravedad protege entonces el pulmon sano de la inundacion, que es lo que mata: el arbol bronquial se llena con unos 150 mL y el paciente se ahoga mucho antes de desangrarse. Es una maniobra inmediata, gratis y a menudo decisiva.', dificultad: 'facil' },
  { q: 'Cual es la prueba de imagen de eleccion en la hemoptisis amenazante del paciente estable?', options: ['La radiografia de torax en dos proyecciones', 'La tomografia angiografica de torax', 'La broncoscopia flexible diagnostica', 'La gammagrafia de ventilacion y perfusion'], correct: 1, explanation: 'Localiza el sangrado, identifica la causa y mapea las arterias bronquiales antes de la embolizacion, con mas informacion que la broncoscopia inicial. La broncoscopia mantiene su papel terapeutico y en el paciente inestable con sangrado activo.', dificultad: 'intermedio' },
  { q: 'Cual es el tratamiento de eleccion de la hemoptisis amenazante?', options: ['La reseccion quirurgica del lobulo afectado', 'La broncoscopia rigida con laser', 'El taponamiento endobronquial con balon', 'La embolizacion arterial bronquial'], correct: 3, explanation: 'Consigue el control inmediato en la gran mayoria de los casos, con recidiva en una minoria que suele responder a una segunda sesion. La cirugia queda como ultimo recurso y el balon como puente hasta la embolizacion.', dificultad: 'facil' },
  { q: 'Que dato diferencia la hemoptisis de la hematemesis?', options: ['La sangre es roja, espumosa y sale con tos', 'La sangre es oscura y de aspecto pastoso', 'La sangre se acompa&#241;a de dolor epigastrico', 'La sangre tiene un pH claramente acido'], correct: 0, explanation: 'La hematemesis produce sangre oscura, con restos alimentarios, acida y precedida de nauseas. Confundirlas cambia por completo la conducta y es uno de los errores clasicos de la urgencia; tambien hay que descartar el sangrado de la via aerea superior.', dificultad: 'facil' },
  { q: 'Que debito por el tubo indica toracotomia en un hemotorax traumatico?', options: ['Un debito inicial de 300 mL', 'Un debito de 100 mL por hora durante 6 horas', 'Un debito inicial de 1000 a 1500 mL', 'Un debito total de 500 mL en 24 horas'], correct: 2, explanation: 'Tambien un debito mantenido por encima de 200 mL por hora durante 2 a 4 horas. El hemotorax retenido que no se evacua predispone al empiema y a la fibrosis que atrapa el pulmon, y se resuelve mejor con cirugia toracoscopica precoz que con fibrinoliticos.', dificultad: 'dificil' },

  { type: 'cascade', vignette: 'Varon de 78 a&#241;os con insuficiencia cardiaca conocida, en tratamiento con furosemida a dosis altas. Ingresa por disnea y presenta un derrame pleural derecho de tama&#241;o moderado. Se punciona: proteinas del liquido 3.4 g/dL con proteinas sericas 5.9, lactato deshidrogenasa del liquido 190 U/L con serica 260 y limite alto de la normalidad de 250. Albumina serica 3.5 g/dL y del liquido 2.0 g/dL.', steps: [
    { q: 'Como clasifican los criterios de Light este derrame?', options: ['Trasudado, por no cumplir ningun criterio', 'No valorable sin conocer la glucosa', 'Trasudado, por el aspecto del liquido', 'Exudado, por el cociente de proteinas'], correct: 3 },
    { q: 'Que calculo corresponde hacer a continuacion?', options: ['El gradiente de albumina entre suero y liquido', 'El cociente entre glucosa pleural y serica', 'La adenosina desaminasa del liquido', 'El recuento diferencial de celulas'], correct: 0 },
    { q: 'Cual es la conclusion y la conducta?', options: ['Exudado de causa no aclarada: toracoscopia', 'Exudado paraneumonico: colocar drenaje', 'Trasudado: optimizar el tratamiento cardiaco', 'Quilotorax: dieta y estudio del conducto toracico'], correct: 2 }
  ], explanation: 'El cociente de proteinas es 3.4 entre 5.9, es decir 0.58, por encima de 0.5, de modo que Light lo clasifica como exudado aunque los dos criterios de lactato deshidrogenasa sean negativos. En un paciente con insuficiencia cardiaca y diureticos a dosis altas hay que sospechar el falso exudado: el gradiente de albumina es 3.5 menos 2.0, es decir 1.5 g/dL, por encima de 1.2, lo que reclasifica el derrame como trasudado. La conducta es tratar el corazon y no seguir estudiando la pleura.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Mujer de 62 a&#241;os ingresada por neumonia del lobulo inferior izquierdo. Al cuarto dia de ceftriaxona persiste febril y con dolor pleuritico. La ecografia muestra un derrame de 35 mm con tabiques. Se punciona y sale liquido turbio, no purulento: pH de 7.11, glucosa de 38 mg/dL y lactato deshidrogenasa de 1850 U/L. Urea de 9.5 mmol/L, albumina de 24 g/L, infeccion comunitaria.', steps: [
    { q: 'Que estadio corresponde a este derrame?', options: ['Simple o exudativo no complicado', 'Complicado o fibrinopurulento', 'Empiema organizado en fase tardia', 'Derrame paramaligno concomitante'], correct: 1 },
    { q: 'Cual es la conducta inmediata?', options: ['Ampliar el antibiotico y repetir en 48 horas', 'A&#241;adir corticoide sistemico durante 5 dias', 'Colocar tubo de drenaje guiado por ecografia', 'Solicitar toracoscopia diagnostica programada'], correct: 2 },
    { q: 'Cual es su puntuacion RAPID?', options: ['3 puntos', '4 puntos', '6 puntos', '5 puntos'], correct: 3 }
  ], explanation: 'Con pH de 7.11, glucosa por debajo de 60 y lactato deshidrogenasa por encima de 1000, el derrame es complicado y necesita drenaje: el antibiotico solo no lo resuelve, y los tabiques refuerzan la indicacion. En la escala RAPID suma dos puntos por una urea mayor de 8 mmol/L, uno por la edad entre 50 y 70, uno por el liquido no purulento, ninguno por ser comunitaria y uno por la albumina menor de 27 g/L, es decir 5 puntos, que ya corresponden a riesgo alto.', dificultad: 'dificil' },

  { type: 'cascade', vignette: 'Varon de 24 a&#241;os, alto y delgado, fumador, sin antecedentes. Acude por dolor toracico derecho de inicio brusco hace 6 horas. Esta comodo, habla con frases completas, saturacion del 97% en aire ambiente, presion arterial de 124/74. La radiografia muestra un neumotorax derecho con una distancia de 4 cm entre la pleura visceral y la pared.', steps: [
    { q: 'Que hay que valorar antes de decidir el manejo?', options: ['Las caracteristicas de alto riesgo y los sintomas', 'El tama&#241;o exacto medido en dos proyecciones', 'La presencia de bullas en la tomografia', 'La funcion pulmonar mediante espirometria'], correct: 0 },
    { q: 'Cual es la conducta mas apropiada en este paciente?', options: ['Drenaje con tubo fino e ingreso hospitalario', 'Pleurodesis quimica con talco por el tama&#241;o', 'Aspiracion con aguja seguida de observacion', 'Manejo conservador con observacion y analgesia'], correct: 3 },
    { q: 'Que consejo es imprescindible al alta?', options: ['Reposo domiciliario estricto durante un mes', 'Abandono del tabaco y no bucear', 'Antibiotico profilactico durante siete dias', 'Espirometria de control a las 48 horas'], correct: 1 }
  ], explanation: 'No hay ninguna caracteristica de alto riesgo y el paciente esta practicamente asintomatico, de modo que desde 2023 el tama&#241;o deja de obligar a intervenir y el manejo conservador es una opcion valida. El abandono del tabaco reduce de forma marcada la recurrencia, que es alta en el primer a&#241;o, y el buceo queda contraindicado de por vida salvo cirugia definitiva bilateral. Volar se permite tras la resolucion completa comprobada.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Varon de 68 a&#241;os con EPOC grave, ingresado y en ventilacion mecanica por una exacerbacion. De forma brusca presenta hipotension de 70/40 mmHg, ascenso de la presion pico de la via aerea y saturacion del 84%. En la exploracion, ingurgitacion yugular y ausencia de murmullo en el hemitorax izquierdo con timpanismo.', steps: [
    { q: 'Cual es el diagnostico mas probable?', options: ['Taponamiento cardiaco pericardico', 'Intubacion selectiva del bronquio derecho', 'Neumotorax a tension izquierdo', 'Tromboembolia pulmonar masiva'], correct: 2 },
    { q: 'Cual es la primera actuacion?', options: ['Solicitar radiografia de torax portatil urgente', 'Descompresion inmediata con aguja', 'Desconectar del respirador y dejar espirar', 'Iniciar noradrenalina y reponer volumen'], correct: 1 },
    { q: 'Que hay que hacer inmediatamente despues?', options: ['Colocar un tubo de drenaje pleural', 'Repetir la gasometria arterial de control', 'Aumentar la PEEP para reexpandir el pulmon', 'Realizar una tomografia toracica urgente'], correct: 0 }
  ], explanation: 'La triada de hipotension con ingurgitacion yugular, timpanismo y abolicion del murmullo en un paciente ventilado es un neumotorax a tension hasta que se demuestre lo contrario, y en el ventilado el equivalente del cuadro clasico es el ascenso brusco de la presion de la via aerea. Es un diagnostico clinico: no se espera a la radiografia. Tras la descompresion con aguja se coloca siempre un tubo de drenaje, porque la aguja es una medida temporal.', dificultad: 'facil' },

  { type: 'cascade', vignette: 'Mujer de 71 a&#241;os con adenocarcinoma de pulmon en tratamiento. Acude por disnea progresiva. La radiografia muestra un derrame pleural izquierdo masivo. Se evacuan 1400 mL de liquido serohematico con alivio inmediato de la disnea, pero la radiografia posterior muestra que el pulmon no ha reexpandido y persiste una camara aerea. La citologia es positiva.', steps: [
    { q: 'Que situacion describe la falta de reexpansion?', options: ['Un neumotorax iatrogenico por la puncion', 'Una fistula broncopleural establecida', 'Una atelectasia por tapon de moco', 'Un pulmon atrapado por afectacion pleural'], correct: 3 },
    { q: 'Que tratamiento pleural corresponde en su caso?', options: ['Pleurodesis con talco por el tubo de drenaje', 'Toracoscopia con pleurodesis mecanica', 'Cateter pleural permanente', 'Toracocentesis repetidas a demanda'], correct: 2 },
    { q: 'Que hay que organizar antes del alta?', options: ['Ingreso programado para retirada del cateter', 'Educacion del paciente y de la familia en el manejo', 'Radiografia semanal durante los tres primeros meses', 'Profilaxis antibiotica mientras dure el cateter'], correct: 1 }
  ], explanation: 'La pleurodesis necesita que las dos hojas pleurales contacten, y con el pulmon atrapado eso no ocurre, de modo que fracasaria. El cateter pleural permanente controla la disnea con independencia de la reexpansion y reduce los dias de hospital, que es un objetivo de primer orden en una enfermedad avanzada. Antes del alta hay que educar al paciente y a la familia en el drenaje y derivar a enfermeria comunitaria.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Varon de 55 a&#241;os con bronquiectasias por tuberculosis previa. Acude por expectoracion de sangre roja abundante, unos 400 mL en las ultimas 4 horas, con tos. Saturacion del 90% con gafas nasales, frecuencia respiratoria de 28, presion arterial de 118/70. Refiere sensacion de calor en el hemitorax derecho antes de cada episodio. Toma acenocumarol por una fibrilacion auricular.', steps: [
    { q: 'Cual es la primera medida postural?', options: ['Decubito lateral derecho', 'Sedestacion a 90 grados', 'Decubito lateral izquierdo', 'Trendelenburg con la cabeza baja'], correct: 0 },
    { q: 'Que actuacion farmacologica es prioritaria?', options: ['Iniciar antibiotico de amplio espectro', 'Revertir la anticoagulacion y dar tranexamico', 'Administrar un antitusigeno opioide potente', 'Nebulizar adrenalina en dosis repetidas'], correct: 1 },
    { q: 'Cual es el siguiente paso diagnostico y terapeutico?', options: ['Broncoscopia flexible diagnostica inicial', 'Reseccion quirurgica del lobulo sangrante', 'Gammagrafia de ventilacion y perfusion', 'Tomografia angiografica y embolizacion'], correct: 3 }
  ], explanation: 'La sensacion de calor localizada indica el lado del sangrado, y el paciente debe colocarse sobre ese lado para que la gravedad proteja el pulmon sano: se muere ahogado, no desangrado. La correccion de la coagulacion es de las pocas medidas aplicables de inmediato, junto con el acido tranexamico por via sistemica o nebulizada. La tomografia angiografica localiza y mapea las arterias bronquiales, y la embolizacion es el tratamiento de eleccion, con la cirugia como ultimo recurso.', dificultad: 'intermedio' }
];

export const flashcards = [
  { front: 'Criterios de Light', back: 'Exudado si se cumple UNO: proteinas L/S mayor de 0.5, LDH L/S mayor de 0.6, o LDH del liquido mayor de dos tercios del limite alto serico.' },
  { front: 'Lo que hay que extraer siempre con el liquido', back: 'Una muestra de SUERO simultanea: sin ella no se pueden aplicar los cocientes.' },
  { front: 'Sensibilidad y especificidad de Light', back: 'Sensibilidad cercana al 98% y especificidad en torno al 80%: clasifica mal una cuarta parte de los trasudados.' },
  { front: 'La trampa del diuretico', back: 'Los diureticos concentran las proteinas y convierten un trasudado en falso exudado.' },
  { front: 'Gradientes de rescate', back: 'Albumina (suero menos liquido) mayor de 1.2 g/dL, o proteinas mayor de 3.1 g/dL: es trasudado.' },
  { front: 'Regla innegociable de los procedimientos pleurales', back: 'Toda toracocentesis, guiada por ECOGRAFIA. Las biopsias pleurales ciegas no deben hacerse.' },
  { front: 'Causa mas frecuente de derrame pleural', back: 'La insuficiencia cardiaca, con diferencia.' },
  { front: 'Vibraciones vocales: derrame frente a consolidacion', back: 'DISMINUIDAS en el derrame y en el neumotorax, AUMENTADAS en la consolidacion.' },
  { front: 'Cuando puncionar el derrame de una neumonia', back: 'Todo derrame de mas de 10 mm si la neumonia no mejora en 48 a 72 horas.' },
  { front: 'Criterios de drenaje del derrame paraneumonico', back: 'pH de 7.2 o menor, glucosa menor de 60 mg/dL, LDH mayor de 1000 U/L, germen visible o pus.' },
  { front: 'Como se recoge el pH pleural', back: 'En jeringa de gasometria, sin aire (lo sube) y sin anestesico local (lo baja). Nunca en pus.' },
  { front: 'Conducta ante pus franco', back: 'Es empiema: se drena sin necesidad de ningun analisis mas.' },
  { front: 'Calibre del tubo en la infeccion pleural', back: 'Fino, de 10 a 14 French: igual de eficaz que uno grueso y mucho menos doloroso.' },
  { front: 'Tratamiento intrapleural si el drenaje cesa', back: 'Activador del plasminogeno 10 mg MAS DNasa 5 mg, dos veces al dia, 3 dias. Nunca por separado.' },
  { front: 'Fibrinolitico que NO debe usarse', back: 'La estreptoquinasa.' },
  { front: 'Cuando derivar a cirugia la infeccion pleural', back: 'Fracaso a los 5 a 7 dias, sepsis persistente o pulmon atrapado.' },
  { front: 'Componentes de la escala RAPID', back: 'Urea (Renal), edad (Age), purulencia, origen de la infeccion y albumina (Dietary).' },
  { front: 'Empiema frente a absceso pulmonar en la tomografia', back: 'El empiema es lenticular con signo de la pleura escindida; el absceso, redondo y de pared gruesa.' },
  { front: 'Rendimiento de la citologia en el derrame maligno', back: 'Cerca del 60%, y mejora al repetir la puncion y enviar mas volumen.' },
  { front: 'Pulmon atrapado y pleurodesis', back: 'La pleurodesis fracasa si el pulmon no reexpande: la opcion es el cateter permanente.' },
  { front: 'Eleccion en el derrame maligno con pulmon expansible', back: 'Se OFRECE A ELEGIR entre pleurodesis con talco y cateter pleural permanente.' },
  { front: 'Cambio de 2023 en el neumotorax', back: 'Se decide por SINTOMAS y caracteristicas de alto riesgo, no por el tama&#241;o.' },
  { front: 'Caracteristicas de alto riesgo del neumotorax', back: 'Inestabilidad, hipoxia, bilateralidad, hemoneumotorax, enfermedad pulmonar de base y mayor de 50 con tabaquismo.' },
  { front: 'Neumotorax primario poco sintomatico', back: 'Manejo conservador, con independencia del tama&#241;o.' },
  { front: 'Diagnostico del neumotorax a tension', back: 'CLINICO: no se espera a la radiografia.' },
  { front: 'Lugar de la descompresion con aguja en el adulto', back: '4.o o 5.o espacio intercostal en la linea axilar media; despues, tubo de drenaje.' },
  { front: 'Por que se hipotensa el neumotorax a tension', back: 'La presion pleural positiva acoda las venas cavas y hunde el retorno venoso.' },
  { front: 'Cirugia de prevencion de recurrencias', back: 'Segundo episodio ipsilateral, primero contralateral, fuga persistente o profesion de riesgo.' },
  { front: 'Consejo de por vida tras un neumotorax', back: 'El buceo queda contraindicado salvo cirugia definitiva bilateral; volar, tras la resolucion.' },
  { front: 'Origen de la hemoptisis amenazante', back: 'El 90% procede de la circulacion BRONQUIAL, sistemica y de alta presion.' },
  { front: 'Primera maniobra en la hemoptisis amenazante', back: 'Decubito lateral SOBRE EL LADO QUE SANGRA, para proteger el pulmon sano.' },
  { front: 'Prueba de imagen y tratamiento de la hemoptisis', back: 'Tomografia angiografica para localizar y mapear, y embolizacion arterial bronquial.' }
];

export default { quiz, flashcards };
