// topics/alteraciones-serie-blanca/study.js: Autoevaluación de Alteraciones de la Serie Blanca.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Índices `correct` de las 30 preguntas sueltas, en orden: 2,0,1,3,2,3,0,1,2,0,3,1,0,2,1,3,0,1,3,
// 2,1,0,2,3,1,3,0,2,3,1. Recuento: 0×7, 1×8, 2×7, 3×8. Sin racha >2 ni ciclo fijo.
// Índices `correct` de los pasos de las 5 preguntas en cascada (3 pasos c/u), en orden: 0,1,2 /
// 2,0,3 / 1,3,0 / 0,2,1 / 3,1,2. Recuento: 0×4, 1×4, 2×4, 3×3.

export const quiz = [
  { q: '¿Cuál es la causa más frecuente de leucocitosis en la práctica clínica general?', options: ['Neoplasia hematológica primaria', 'Reacción alérgica aislada', 'Infección bacteriana aguda', 'Deficiencia de hierro'], correct: 2, explanation: 'La infección bacteriana aguda es, con diferencia, la causa más frecuente de leucocitosis en la práctica clínica.', dificultad: 'facil' },
  { q: '¿Qué es la "desviación a la izquierda" en el hemograma?', options: ['Aumento de bandas y formas inmaduras', 'Aumento de linfocitos atípicos circulantes', 'Reducción del conteo absoluto de neutrófilos', 'Aumento aislado de eosinófilos maduros'], correct: 0, explanation: 'La desviación a la izquierda es el aumento de bandas y formas inmaduras de neutrófilos, reflejando la liberación medular acelerada ante un estímulo inflamatorio o infeccioso.', dificultad: 'facil' },
  { q: '¿Cuál es el mecanismo de la neutrofilia por estrés fisiológico agudo (cirugía, trauma, convulsión) o por corticoides?', options: ['Aumento real de la producción medular', 'Desmarginación desde el endotelio', 'Destrucción acelerada de neutrófilos', 'Redistribución de neutrófilos al bazo'], correct: 1, explanation: 'El estrés fisiológico y los corticoides producen neutrofilia por desmarginación de neutrófilos ya presentes y retraso de su apoptosis, sin verdadero aumento de la producción medular.', dificultad: 'intermedio' },
  { q: '¿Qué es una "reacción leucemoide"?', options: ['Leucemia mieloide crónica en fase inicial', 'Neutropenia grave con fiebre asociada', 'Linfocitosis clonal de bajo grado circulante', 'Leucocitosis reactiva que simula una LMC'], correct: 3, explanation: 'La reacción leucemoide es un fenómeno reactivo con leucocitosis extrema y desviación a la izquierda marcada, sin la mutación clonal de la leucemia mieloide crónica.', dificultad: 'dificil' },
  { q: '¿Cuál es la causa más frecuente de neutropenia en el paciente oncológico?', options: ['Infección viral aguda intercurrente', 'Neutropenia congénita grave', 'Quimioterapia citotóxica', 'Hiperesplenismo asociado'], correct: 2, explanation: 'La quimioterapia citotóxica mielosupresora es, con diferencia, la causa más frecuente de neutropenia en el paciente oncológico.', dificultad: 'facil' },
  { q: '¿Cuáles son los 3 mecanismos generales de la neutropenia?', options: ['Solo producción medular insuficiente', 'Solo destrucción periférica acelerada', 'Solo redistribución transitoria al endotelio', 'Producción, destrucción o redistribución'], correct: 3, explanation: 'La neutropenia se produce por 3 mecanismos generales: producción medular insuficiente, destrucción/consumo periférico acelerado, o redistribución transitoria.', dificultad: 'intermedio' },
  { q: '¿Cuál es el umbral de RAN que define neutropenia?', options: ['&lt;1500 células/µL', '&lt;3000 células/µL', '&lt;5000 células/µL', '&lt;10,000 células/µL'], correct: 0, explanation: 'El umbral de RAN que define neutropenia es &lt;1500 células/µL.', dificultad: 'facil' },
  { q: 'Según la calculadora RAN, ¿qué rango corresponde a neutropenia moderada?', options: ['1000-1499 células/µL', '500-999 células/µL', '100-499 células/µL', '&lt;100 células/µL'], correct: 1, explanation: 'La neutropenia moderada corresponde a un RAN de 500-999 células/µL.', dificultad: 'intermedio' },
  { q: '¿Cuál es la causa más frecuente de eosinofilia en la práctica clínica general?', options: ['Síndrome hipereosinofílico neoplásico', 'Leucemia eosinofílica crónica clonal', 'Alergia y reacción farmacológica', 'Vasculitis sistémica primaria'], correct: 2, explanation: 'La alergia/atopia y la reacción farmacológica son las causas más frecuentes de eosinofilia en la práctica clínica general.', dificultad: 'facil' },
  { q: '¿Qué citocina está principalmente implicada en la activación de la respuesta inmune tipo 2 que produce eosinofilia?', options: ['Interleucina-5', 'Interleucina-1', 'Interleucina-12', 'Interferón gamma'], correct: 0, explanation: 'La interleucina-5 estimula la producción y supervivencia de eosinófilos en la médula ósea, siendo central en la respuesta inmune tipo 2.', dificultad: 'intermedio' },
  { q: '¿Qué línea celular se eleva característicamente durante la fase de recuperación tras un episodio de neutropenia?', options: ['Eosinófilos', 'Basófilos', 'Linfocitos atípicos', 'Monocitos'], correct: 3, explanation: 'Los monocitos, junto con formas inmaduras de neutrófilos, suelen ser de las primeras líneas en recuperarse tras un episodio de neutropenia.', dificultad: 'intermedio' },
  { q: '¿Qué virus es la causa clásica de linfocitosis reactiva con linfocitos atípicos (mononucleosis infecciosa)?', options: ['Virus de la hepatitis B', 'Virus de Epstein-Barr', 'Virus de la varicela zóster', 'Virus del papiloma humano'], correct: 1, explanation: 'El virus de Epstein-Barr es la causa clásica de mononucleosis infecciosa, con linfocitos atípicos característicos en el frotis.', dificultad: 'facil' },
  { q: '¿Qué mutación/translocación caracteriza a la leucemia mieloide crónica, distinguiéndola de la reacción leucemoide?', options: ['t(9;22), BCR-ABL1', 'Mutación JAK2 V617F', 'Mutación de FLT3-ITD', 'Deleción del 5q'], correct: 0, explanation: 'La leucemia mieloide crónica se caracteriza por la translocación t(9;22) (cromosoma Filadelfia) que genera el gen de fusión BCR-ABL1.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo en el frotis de sangre periférica orienta más hacia leucemia mieloide crónica que hacia una reacción leucemoide?', options: ['Granulación tóxica de los neutrófilos', 'Cuerpos de Döhle en los neutrófilos', 'Todo el espectro madurativo con basofilia', 'Linfocitos atípicos circulantes abundantes'], correct: 2, explanation: 'La leucemia mieloide crónica muestra el espectro completo de maduración mieloide con basofilia, a diferencia de la reacción leucemoide que predomina en bandas y segmentados.', dificultad: 'facil' },
  { q: '¿Por qué la fiebre puede ser el ÚNICO signo de infección en el paciente con neutropenia grave?', options: ['Porque la fiebre precede a la neutropenia', 'Los signos locales dependen del neutrófilo', 'Porque la neutropenia eleva la temperatura', 'Porque el neutropénico no percibe dolor'], correct: 1, explanation: 'Los signos inflamatorios localizados habituales (eritema, induración, pus) dependen de los neutrófilos, ausentes o muy reducidos en la neutropenia grave.', dificultad: 'dificil' },
  { q: '¿Cuál es el criterio de temperatura para definir neutropenia febril?', options: ['≥37.5°C en cualquier momento', '≥39°C sostenido por 24 horas', '≥38.5°C medido 2 veces en 12 h', '≥38.3°C o ≥38.0°C por 1 hora'], correct: 3, explanation: 'El criterio de temperatura para neutropenia febril es ≥38.3°C único o ≥38.0°C sostenido durante al menos 1 hora.', dificultad: 'intermedio' },
  { q: '¿Cuál es el manejo inicial más urgente ante una neutropenia febril confirmada?', options: ['Antibiótico empírico antipseudomónico ya', 'Esperar los hemocultivos antes de tratar', 'Iniciar quimioterapia adicional de inmediato', 'Transfusión de neutrófilos de entrada'], correct: 0, explanation: 'La antibioticoterapia empírica de amplio espectro con cobertura antipseudomónica debe iniciarse idealmente dentro de la primera hora, sin esperar los cultivos.', dificultad: 'facil' },
  { q: '¿Por qué se deben obtener hemocultivos ANTES de iniciar el antibiótico empírico en la neutropenia febril, sin retrasar el inicio del tratamiento por ello?', options: ['Los hemocultivos no aportan valor aquí', 'Permiten ajustar después el tratamiento', 'El antibiótico debe esperar al resultado', 'Los hemocultivos sustituyen al antibiótico'], correct: 1, explanation: 'Los hemocultivos se obtienen antes del antibiótico para no comprometer su rendimiento diagnóstico, pero sin retrasar el inicio del tratamiento empírico.', dificultad: 'intermedio' },
  { q: '¿Cuál es el umbral de eosinófilos que define eosinofilia grave?', options: ['&gt;500 células/µL', '&gt;1000 células/µL', '&gt;1500 células/µL', '&gt;5000 células/µL'], correct: 3, explanation: 'La eosinofilia grave se define como un conteo absoluto de eosinófilos &gt;5000 células/µL.', dificultad: 'facil' },
  { q: '¿Cuál es el órgano más temido y particularmente vulnerable en el síndrome hipereosinofílico?', options: ['El riñón, por glomerulopatía', 'El hígado, por colestasis', 'El corazón, por fibrosis', 'El páncreas, por pancreatitis'], correct: 2, explanation: 'El corazón es particularmente vulnerable en el síndrome hipereosinofílico, con fibrosis endomiocárdica, trombos murales e insuficiencia cardiaca restrictiva.', dificultad: 'intermedio' },
  { q: '¿Qué estudio de imagen debe solicitarse en TODO paciente con sospecha de síndrome hipereosinofílico, incluso si está asintomático desde el punto de vista cardiaco?', options: ['Resonancia magnética cerebral', 'Ecocardiograma', 'Tomografía de abdomen', 'Gammagrafía ósea'], correct: 1, explanation: 'El ecocardiograma debe solicitarse en todo paciente con sospecha de síndrome hipereosinofílico, dado que la afectación cardiaca puede ser inicialmente asintomática.', dificultad: 'facil' },
  { q: '¿Qué distingue a la variante clonal/neoplásica del síndrome hipereosinofílico de la variante reactiva/linfocítica?', options: ['Un reordenamiento de PDGFRA', 'La clonal tiene mejor pronóstico', 'La clonal no afecta al corazón', 'No hay diferencia real entre ambas'], correct: 0, explanation: 'La variante clonal se distingue por un reordenamiento genético (más frecuentemente de PDGFRA) que produce una proliferación eosinofílica autónoma.', dificultad: 'intermedio' },
  { q: '¿Cuál es el tratamiento de elección si se confirma un síndrome hipereosinofílico con reordenamiento de PDGFRA?', options: ['Quimioterapia citotóxica convencional', 'Corticoides en monoterapia indefinida', 'Un inhibidor de tirosina cinasa', 'Radioterapia esplénica dirigida'], correct: 2, explanation: 'Un inhibidor de tirosina cinasa (imatinib) es altamente eficaz y de elección si se confirma el reordenamiento de PDGFRA.', dificultad: 'facil' },
  { q: '¿Cuál es el primer paso diferenciador ante una alteración de la serie blanca sin causa reactiva clara?', options: ['Aspirado de médula ósea de entrada', 'Estudio molecular amplio sin dirección', 'Citometría de flujo de entrada', 'Frotis de sangre periférica revisado'], correct: 3, explanation: 'El frotis de sangre periférica examinado por un observador experimentado es la herramienta central para el primer paso diferenciador.', dificultad: 'intermedio' },
  { q: '¿Cuándo está indicado el aspirado/biopsia de médula ósea en el estudio de una alteración de la serie blanca?', options: ['De rutina en cualquier alteración leve', 'De tercera línea, si persiste la duda', 'Solo cuando el paciente lo solicita', 'No aporta información en este contexto'], correct: 1, explanation: 'El aspirado/biopsia de médula ósea es un estudio de tercera línea, reservado cuando el diagnóstico permanece incierto tras el frotis y los estudios de segunda línea.', dificultad: 'facil' },
  { q: '¿Qué hallazgo de imagen orienta siempre hacia la sospecha de un proceso neoplásico subyacente ante una alteración de la serie blanca?', options: ['Un nódulo pulmonar aislado sin relación', 'Una radiografía de tórax normal', 'Un hígado de tamaño normal', 'Esplenomegalia'], correct: 3, explanation: 'La esplenomegalia siempre debe elevar la sospecha de un proceso neoplásico subyacente ante una alteración de la serie blanca.', dificultad: 'facil' },
  { q: '¿Qué revisión debe hacerse sistemáticamente ANTES de avanzar a estudios invasivos ante neutropenia o eosinofilia inexplicadas?', options: ['Revisión estructurada de fármacos', 'Biopsia de médula ósea inmediata', 'Estudio genético amplio sin dirección', 'No hace falta revisión adicional'], correct: 0, explanation: 'La revisión estructurada de fármacos activos debe hacerse sistemáticamente antes de avanzar a estudios invasivos.', dificultad: 'intermedio' },
  { q: '¿Qué recuento celular sugiere pancitopenia asociada en lugar de neutropenia aislada, orientando hacia un proceso medular más amplio?', options: ['Solo neutrófilos bajos con hemoglobina y plaquetas normales', 'Neutrófilos normales con hemoglobina baja aislada', 'Neutrófilos, hemoglobina y plaquetas simultáneamente bajos', 'Solo plaquetas bajas con neutrófilos normales'], correct: 2, explanation: 'La reducción simultánea de neutrófilos, hemoglobina y plaquetas sugiere pancitopenia y un proceso medular más amplio.', dificultad: 'facil' },
  { q: '¿Qué caracteriza a la linfocitosis clonal de un síndrome linfoproliferativo crónico, distinguiéndola de la linfocitosis reactiva?', options: ['Se asocia a fiebre alta persistente', 'Se resuelve espontáneamente en días', 'Predomina en el paciente pediátrico', 'Persistente y sin contexto infeccioso'], correct: 3, explanation: 'La linfocitosis clonal es persistente, con frecuencia en el adulto mayor, sin el contexto infeccioso agudo típico de la linfocitosis reactiva.', dificultad: 'intermedio' },
  { q: '¿Qué fármaco de uso común puede producir neutropenia idiosincrásica no dosis-dependiente?', options: ['Paracetamol', 'Clozapina', 'Vitamina C', 'Loratadina'], correct: 1, explanation: 'La clozapina es un fármaco reconocido por producir neutropenia idiosincrásica, con frecuencia inmunomediada y no dosis-dependiente.', dificultad: 'facil' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 45 años con neumonía adquirida en la comunidad presenta leucocitos 18,000/µL con 85% neutrófilos y 8% bandas. Sin esplenomegalia. Fiebre y tos productiva de 3 días de evolución.',
    steps: [
      { q: '¿Cuál es la interpretación más apropiada de este hemograma?', options: ['Neutrofilia reactiva con bandas', 'Leucemia mieloide crónica', 'Síndrome hipereosinofílico', 'Neutropenia con desviación izquierda'], correct: 0 },
      { q: '¿Qué estudio adicional NO es necesario de rutina en este caso, dado que la causa reactiva es evidente?', options: ['Cultivo dirigido según el foco infeccioso sospechado', 'Estudio molecular de BCR-ABL1', 'Marcadores inflamatorios (VSG, PCR)', 'Radiografía de tórax si aporta al diagnóstico del foco'], correct: 1 },
      { q: 'Tras 5 días de antibiótico dirigido, la fiebre se resuelve pero la leucocitosis persiste sin mejoría. ¿Qué se debe reconsiderar?', options: ['Que la neumonía no era el diagnóstico', 'Aumentar la dosis del mismo antibiótico', 'Reacción leucemoide o neoplasia de fondo', 'Que la leucocitosis persistente es normal'], correct: 2 }
    ],
    explanation: 'La leucocitosis neutrofílica con desviación a la izquierda es reactiva y congruente con el foco infeccioso; no requiere estudio molecular de rutina cuando la causa es evidente. Si la leucocitosis persiste pese a la resolución clínica de la infección, debe reconsiderarse el diagnóstico diferencial (reacción leucemoide extrema o un proceso neoplásico no identificado inicialmente).'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 58 años en quimioterapia por cáncer de mama presenta fiebre de 38.6°C. Biometría hemática: leucocitos 800/µL, 40% neutrófilos, 5% bandas.',
    steps: [
      { q: 'Calcula el RAN e interpreta.', options: ['RAN 800, neutropenia leve', 'RAN 640, neutropenia moderada', 'RAN 360, neutropenia grave', 'RAN 1200, sin neutropenia'], correct: 2 },
      { q: '¿Cuál es el manejo inicial más apropiado?', options: ['Hemocultivos y antibiótico en la 1a hora', 'Esperar el resultado de los hemocultivos', 'Iniciar quimioterapia adicional de inmediato', 'Manejo ambulatorio sin evaluación hospitalaria'], correct: 0 },
      { q: 'No se identifica un foco infeccioso claro al examen físico ni en los estudios iniciales. ¿Cómo se interpreta esto?', options: ['No hay infección: suspender el antibiótico', 'Descarta la necesidad de hospitalizar', 'Indica repetir la quimioterapia de inmediato', 'Esperado: respuesta inflamatoria atenuada'], correct: 3 }
    ],
    explanation: 'RAN = 800 x (40+5)/100 = 360 células/µL (neutropenia grave), que con la fiebre documentada cumple criterios de neutropenia febril, una urgencia médica. El manejo inicial es hemocultivos seguidos de antibiótico empírico de amplio espectro sin retrasar el tratamiento. La ausencia de un foco claro es esperada, dado que la respuesta inflamatoria localizada depende de los neutrófilos.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Varón de 35 años presenta eosinófilos 2200 células/µL en 2 biometrías separadas por 6 semanas, sin antecedente de alergia, sin fármacos nuevos, coproparasitoscópico negativo. Refiere disnea de esfuerzo progresiva de 2 meses.',
    steps: [
      { q: '¿Cuál es la sospecha diagnóstica más apropiada dado este patrón?', options: ['Eosinofilia alérgica simple, sin más estudio', 'Síndrome hipereosinofílico', 'Neutropenia febril posquimioterapia', 'Linfocitosis reactiva por mononucleosis'], correct: 1 },
      { q: '¿Qué estudio es prioritario dado el síntoma respiratorio y la sospecha diagnóstica?', options: ['Repetir el estudio coproparasitoscópico', 'Biopsia de piel aunque no haya lesión', 'Radiografía simple de columna dorsal', 'Ecocardiograma transtorácico'], correct: 3 },
      { q: 'El ecocardiograma muestra fibrosis endomiocárdica incipiente. ¿Cuál es el manejo más apropiado?', options: ['Corticoides ya, sin esperar el molecular', 'Esperar el estudio molecular completo', 'Manejo ambulatorio sin seguimiento cardiológico', 'Observación sin tratamiento, es leve'], correct: 0 }
    ],
    explanation: 'La eosinofilia grave persistente sin causa reactiva identificable, con un síntoma respiratorio nuevo, sugiere síndrome hipereosinofílico. El ecocardiograma es prioritario porque la afectación cardiaca puede ser asintomática. Confirmado el daño de órgano, el tratamiento urgente (corticoides) no debe esperar el estudio etiológico completo.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente crítico en la unidad de cuidados intensivos con sepsis grave por peritonitis presenta leucocitos 62,000/µL con predominio de bandas y segmentados, sin blastos identificados en el frotis, sin esplenomegalia.',
    steps: [
      { q: '¿Cuál es la interpretación más apropiada de esta leucocitosis extrema?', options: ['Reacción leucemoide por la sepsis', 'Leucemia mieloide crónica confirmada', 'Síndrome hipereosinofílico grave', 'Leucemia aguda por el recuento alto'], correct: 0 },
      { q: '¿Qué estudio confirmaría o descartaría definitivamente el diagnóstico diferencial con leucemia mieloide crónica?', options: ['Repetir el frotis de sangre periférica', 'Ecografía abdominal con Doppler', 'BCR-ABL1 por PCR o FISH', 'Radiografía de tórax en dos proyecciones'], correct: 2 },
      { q: 'El estudio molecular resulta negativo para BCR-ABL1 y la sepsis se resuelve con el tratamiento antibiótico. ¿Qué se espera de la leucocitosis?', options: ['Que persista pese a resolverse la sepsis', 'Que se resuelva junto con la sepsis', 'Que requiera quimioterapia para ceder', 'Que indique un inhibidor de tirosina cinasa'], correct: 1 }
    ],
    explanation: 'La leucocitosis extrema sin blastos ni esplenomegalia en el contexto de sepsis grave sugiere reacción leucemoide. El estudio molecular BCR-ABL1 confirma o descarta definitivamente leucemia mieloide crónica. Negativo el estudio, se espera que la leucocitosis se resuelva con la sepsis, confirmando el diagnóstico reactivo.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Mujer de 72 años, hallazgo incidental de linfocitosis persistente (12,000/µL, 80% linfocitos) en varias biometrías a lo largo de 6 meses, sin fiebre, sin adenopatías dolorosas ni síntomas de infección aguda actual.',
    steps: [
      { q: '¿Qué patrón hace sospechar un proceso linfoproliferativo clonal en lugar de una linfocitosis reactiva?', options: ['La presencia de fiebre alta y aguda', 'Un episodio único autolimitado en un joven', 'Un contexto claro de infección viral aguda', 'Persistencia de 6 meses en el adulto mayor'], correct: 3 },
      { q: '¿Qué estudio ayuda a distinguir una linfocitosis reactiva policlonal de una clonal?', options: ['Serología viral aislada del paciente', 'Citometría de flujo periférica', 'Radiografía de tórax de rutina', 'Coproparasitoscópico seriado'], correct: 1 },
      { q: 'La citometría de flujo confirma una población clonal de linfocitos B. ¿Cuál es el paso apropiado siguiente?', options: ['Manejar como mononucleosis con reposo', 'Iniciar antituberculoso empírico', 'Referir a hematología para evaluación', 'Repetir solo la biometría en 1 año'], correct: 2 }
    ],
    explanation: 'La persistencia de la linfocitosis por 6 meses en una paciente de edad avanzada, sin contexto infeccioso agudo, sugiere un proceso clonal. La citometría de flujo distingue una población reactiva policlonal de una clonal. Confirmada la clonalidad, corresponde referir a hematología para evaluar un síndrome linfoproliferativo crónico.'
  }
];

export const flashcards = [
  { front: 'Causa más frecuente de leucocitosis', back: 'Infección bacteriana aguda.' },
  { front: '"Desviación a la izquierda"', back: 'Aumento de bandas y formas inmaduras de neutrófilos en sangre periférica, por liberación medular acelerada.' },
  { front: 'Mecanismo de neutrofilia por estrés/corticoides', back: 'Desmarginación de neutrófilos y retraso de apoptosis, sin aumento real de producción.' },
  { front: 'Reacción leucemoide', back: 'Leucocitosis reactiva extrema (&gt;50,000/µL) con desviación a la izquierda, simula LMC pero es BCR-ABL1 negativa.' },
  { front: 'Causa más frecuente de neutropenia en oncología', back: 'Quimioterapia citotóxica.' },
  { front: '3 mecanismos de neutropenia', back: 'Producción medular insuficiente, destrucción/consumo periférico acelerado, redistribución transitoria.' },
  { front: 'Fórmula del RAN', back: 'RAN = leucocitos totales x (%neutrófilos + %bandas) / 100.' },
  { front: 'Umbrales de severidad de neutropenia (RAN)', back: 'Normal ≥1500. Leve 1000-1499. Moderada 500-999. Grave 100-499. Agranulocitosis &lt;100 células/µL.' },
  { front: 'Causa más frecuente de eosinofilia', back: 'Alergia/atopia y reacción farmacológica.' },
  { front: 'Citocina central en la eosinofilia', back: 'Interleucina-5.' },
  { front: 'Línea celular elevada en recuperación de neutropenia', back: 'Monocitos.' },
  { front: 'Virus causante de mononucleosis infecciosa', back: 'Virus de Epstein-Barr (linfocitos atípicos en el frotis).' },
  { front: 'Mutación de la leucemia mieloide crónica', back: 't(9;22), gen de fusión BCR-ABL1.' },
  { front: 'Frotis: LMC vs. reacción leucemoide', back: 'LMC: espectro completo de maduración mieloide + basofilia. Leucemoide: predominan bandas/segmentados.' },
  { front: 'Por qué la fiebre puede ser el único signo en neutropenia grave', back: 'Los signos inflamatorios localizados dependen de los neutrófilos, ausentes/reducidos.' },
  { front: 'Criterio de temperatura para neutropenia febril', back: '≥38.3°C único o ≥38.0°C sostenido ≥1 hora, con RAN &lt;500 (o &lt;1000 con descenso esperado).' },
  { front: 'Manejo inicial de neutropenia febril', back: 'Hemocultivos + antibiótico empírico antipseudomónico dentro de la primera hora, sin esperar cultivos.' },
  { front: 'Umbral de eosinofilia grave', back: '&gt;5000 células/µL.' },
  { front: 'Órgano más vulnerable en síndrome hipereosinofílico', back: 'Corazón (fibrosis endomiocárdica, trombos murales, insuficiencia restrictiva).' },
  { front: 'Estudio obligatorio en sospecha de síndrome hipereosinofílico', back: 'Ecocardiograma (afectación cardiaca puede ser asintomática).' },
  { front: 'Variante clonal del síndrome hipereosinofílico', back: 'Reordenamiento genético (más frecuente PDGFRA), tirosina cinasa constitutivamente activa.' },
  { front: 'Tratamiento de elección si PDGFRA positivo', back: 'Inhibidor de tirosina cinasa (imatinib).' },
  { front: 'Primer paso ante alteración de serie blanca sin causa clara', back: 'Frotis de sangre periférica por observador experimentado.' },
  { front: 'Cuándo indicar aspirado/biopsia de médula ósea', back: 'Estudio de tercera línea, si el diagnóstico permanece incierto tras frotis y estudios de segunda línea.' },
  { front: 'Hallazgo de imagen que eleva sospecha neoplásica', back: 'Esplenomegalia.' },
  { front: 'Revisión sistemática antes de estudios invasivos', back: 'Revisión estructurada de fármacos activos.' },
  { front: 'Linfocitosis clonal vs. reactiva', back: 'Clonal: persistente, adulto mayor, sin contexto infeccioso agudo.' }
];
