// topics/exploracion-cabeza-cuello/study.js — Autoevaluación de Exploración de Cabeza, Cuello y
// Ganglios. Mismo patrón que historia-clinica/study.js y los demás temas de Semiología: banco
// único, preguntas sueltas + preguntas en cascada sobre una viñeta (retroalimentación consolidada
// al final, sin revelar correcto/incorrecto paso a paso). Redacción de opciones sujeta a
// .claude/skills/reglas-preguntas/SKILL.md (misma categoría lógica, longitud/detalle comparables,
// sin pistas gramaticales/semánticas, posición de `correct` distribuida sin patrón a lo largo de
// todo el array).

export const quiz = [
  { q: '¿Dónde se ubica el istmo tiroideo en relación con los landmarks cervicales?', options: ['Por encima del cartílago tiroides', 'En el triángulo cervical posterior', 'A nivel del hueso hioides', 'Justo debajo del cartílago cricoides'], correct: 3, explanation: 'El istmo tiroideo se localiza inmediatamente debajo del cartílago cricoides, un landmark clave para orientar la palpación tiroidea.', dificultad: 'facil' },
  { q: '¿Cómo se delimita el triángulo cervical anterior?', options: ['Trapecio, clavícula y esternocleidomastoideo', 'Línea media, borde mandibular y el ECM', 'Solo el hueso hioides, sin más límites', 'Las dos clavículas, de forma simétrica'], correct: 1, explanation: 'El triángulo cervical anterior está delimitado por la línea media del cuello, el borde inferior de la mandíbula y el borde anterior del músculo esternocleidomastoideo.', dificultad: 'intermedio' },
  { q: '¿Por qué la glándula tiroides se eleva con la deglución?', options: ['Porque está fijada a la tráquea por la fascia pretraqueal', 'Por contracción de un supuesto músculo tiroideo', 'Por un reflejo nervioso independiente de la anatomía', 'La tiroides en realidad no se eleva con la deglución'], correct: 0, explanation: 'La fijación de la glándula a la tráquea mediante la fascia pretraqueal hace que se desplace hacia arriba junto con la laringe durante la deglución.', dificultad: 'intermedio' },
  { q: 'Una masa cervical que NO se eleva con la deglución sugiere que su origen es:', options: ['Tiroideo, con total certeza diagnóstica', 'De naturaleza maligna en todo caso', 'No tiroideo, o no fijado a la tráquea', 'Un quiste tirogloso, sin más opción'], correct: 2, explanation: 'La ausencia de movimiento con la deglución orienta a que la masa no depende de la fijación traqueal característica de la tiroides.', dificultad: 'facil' },
  { q: '¿Cuáles son las 2 técnicas clásicas de palpación tiroidea según la posición del examinador?', options: ['Técnicas de Homans y de Pratt', 'Lahey (anterior) y Crile (posterior)', 'Técnicas de Kernig y de Brudzinski', 'Técnicas de Lachman y de McMurray'], correct: 1, explanation: 'La técnica anterior (Lahey) se realiza de frente al paciente; la técnica posterior (Crile), de pie por detrás.', dificultad: 'facil' },
  { q: '¿Qué mecanismo explica un soplo/frémito tiroideo continuo?', options: ['Compresión traqueal por un bocio grande', 'Fibrosis extensa y progresiva de la glándula', 'Es un hallazgo normal del bocio simple', 'Hipervascularización por hiperfunción'], correct: 3, explanation: 'El aumento marcado del flujo sanguíneo tiroideo en el hipertiroidismo difuso (Graves) genera turbulencia audible/palpable, algo que no se espera en un bocio nodular no hiperfuncionante.', dificultad: 'dificil' },
  { q: 'Según la clasificación de la OMS, un bocio Grado I se define como:', options: ['Ni palpable ni visible al examen', 'Visible incluso desde cierta distancia', 'Palpable, pero no visible', 'Visible con el cuello en posición normal'], correct: 2, explanation: 'El Grado I es palpable a la exploración pero no se aprecia visualmente con el cuello en posición neutra.', dificultad: 'facil' },
  { q: '¿Qué mecanismo explica el signo de Pemberton positivo (congestión facial y distensión yugular al elevar los brazos)?', options: ['Un bocio retroesternal que comprime', 'Aumento transitorio del gasto cardiaco', 'Una deshidratación aguda reciente', 'Hipotensión ortostática postural'], correct: 0, explanation: 'La elevación de los brazos desplaza la clavícula hacia arriba, agravando la compresión del espacio torácico superior ya limitado por el bocio retroesternal, y obstruyendo el retorno venoso yugular.', dificultad: 'dificil' },
  { q: '¿Qué conducta amerita un signo de Pemberton positivo antes de cualquier cirugía tiroidea?', options: ['No amerita nada: se opera sin más', 'Indicar solo levotiroxina por vía oral', 'Repetir la maniobra solo para confirmar', 'Evaluar la extensión retroesternal por TC'], correct: 3, explanation: 'Conocer la extensión retroesternal antes de la cirugía es clave para anticipar y manejar el riesgo de obstrucción de la vía aérea durante la manipulación quirúrgica.', dificultad: 'intermedio' },
  { q: 'Una adenopatía preauricular sugiere un proceso originado en:', options: ['La conjuntiva o los párpados', 'El labio inferior y el mentón', 'La cavidad oral y la lengua', 'El tórax, el mediastino o el esófago'], correct: 0, explanation: 'La cadena preauricular drena la conjuntiva, los párpados y la piel de la región temporal.', dificultad: 'facil' },
  { q: 'Una adenopatía occipital sugiere un proceso originado en:', options: ['La faringe y la amígdala', 'La glándula tiroides y el istmo', 'El cuero cabelludo posterior', 'El abdomen y la pelvis'], correct: 2, explanation: 'La cadena occipital drena el cuero cabelludo posterior.', dificultad: 'facil' },
  { q: '¿Por qué es importante examinar TODAS las cadenas ganglionares y no solo la región sintomática?', options: ['Por protocolo, sin relevancia clínica', 'Una adenopatía silente puede ser la clave', 'Todas las cadenas se afectan a la vez', 'No hace falta si el paciente no tiene síntomas'], correct: 1, explanation: 'Un hallazgo asintomático en una cadena alejada del síntoma principal, como la supraclavicular, puede cambiar por completo el enfoque diagnóstico.', dificultad: 'intermedio' },
  { q: '¿Qué características tiene típicamente una adenopatía reactiva/inflamatoria?', options: ['Blanda, móvil, dolorosa y lisa', 'Dura, fija e indolora al tacto', 'Gomosa, confluente y fija', 'Pétrea, irregular y adherida'], correct: 0, explanation: 'La hiperplasia folicular benigna en respuesta a un estímulo antigénico local produce un ganglio blando, móvil y doloroso.', dificultad: 'facil' },
  { q: '¿Qué características hacen sospechar que una adenopatía es de origen neoplásico?', options: ['Blanda, móvil y claramente dolorosa', 'Únicamente un tamaño mayor de 1 cm', 'Dura, fija, indolora e irregular', 'Aparición tras una infección respiratoria'], correct: 2, explanation: 'La consistencia firme, la fijación a planos profundos, la ausencia de dolor y la confluencia ("matted") son las características que más orientan a malignidad.', dificultad: 'intermedio' },
  { q: '¿Por qué una adenopatía neoplásica es típicamente INDOLORA, a diferencia de una reactiva?', options: ['Las células tumorales no tienen nervios', 'El crecimiento lento no distiende la cápsula', 'Su interior suele estar necrosado ya', 'No hay diferencia real de dolor entre ambas'], correct: 1, explanation: 'El dolor ganglionar depende de la distensión aguda de la cápsula; el crecimiento neoplásico, al ser progresivo y lento, no suele generar ese estímulo doloroso agudo.', dificultad: 'dificil' },
  { q: '¿Qué significa que varios ganglios estén "confluentes" o "matted"?', options: ['Que están separados e individualizables', 'Que tienen una consistencia muy blanda', 'Que corresponden a una infección aguda', 'Que están fusionados entre sí'], correct: 3, explanation: 'La fusión de varios ganglios adyacentes en una masa única ("matted") es un patrón que orienta hacia metástasis o linfoma.', dificultad: 'intermedio' },
  { q: '¿Dónde se localiza el ganglio de Virchow?', options: ['Submandibular derecho, en el ángulo', 'Occipital, bilateral y simétrico', 'Supraclavicular izquierdo', 'Preauricular izquierdo, junto al trago'], correct: 2, explanation: 'El ganglio de Virchow se ubica en la región supraclavicular izquierda, en el ángulo formado por el esternocleidomastoideo y la clavícula.', dificultad: 'facil' },
  { q: '¿Qué mecanismo anatómico explica que una neoplasia gástrica se manifieste como una adenopatía supraclavicular izquierda?', options: ['El conducto torácico drena ahí', 'Metástasis hematógena directa a la piel', 'Es pura coincidencia, sin mecanismo', 'El estómago tiene inervación al cuello'], correct: 0, explanation: 'El conducto torácico es la vía final común de drenaje linfático de gran parte del abdomen, y su desembocadura en el ángulo yugulo-subclavio izquierdo explica el signo de Troisier.', dificultad: 'dificil' },
  { q: '¿Qué diferencia hay, en términos de origen probable, entre una adenopatía supraclavicular izquierda y una derecha?', options: ['No hay diferencia real entre los lados', 'La adenopatía derecha resulta benigna', 'La izquierda no se asocia con cáncer', 'Izquierda: abdomen; derecha: tórax'], correct: 3, explanation: 'El drenaje linfático distinto de cada lado (conducto torácico a la izquierda vs. conducto linfático derecho, más corto, a la derecha) explica el origen probable diferente según el lado afectado.', dificultad: 'dificil' },
  { q: '¿Dónde se localiza típicamente un quiste tirogloso?', options: ['Lateral, en el borde anterior del esternocleidomastoideo', 'En la línea media, a la altura del hueso hioides', 'En la región supraclavicular', 'En la región preauricular'], correct: 1, explanation: 'El quiste tirogloso, remanente del conducto tirogloso embrionario, se ubica en la línea media, cerca del hueso hioides.', dificultad: 'facil' },
  { q: '¿Qué maniobra dinámica ayuda a identificar un quiste tirogloso, y por qué?', options: ['La protrusión lingual, por el conducto', 'La deglución, por fijación a la tráquea', 'La flexión pasiva y lateral del cuello', 'No existe maniobra que lo distinga'], correct: 0, explanation: 'El conducto tirogloso conecta embriológicamente la base de la lengua con la posición final de la tiroides, por lo que el quiste se eleva al protruir la lengua.', dificultad: 'intermedio' },
  { q: '¿Dónde se localiza típicamente un quiste branquial (del segundo arco)?', options: ['En la línea media exacta del cuello del paciente', 'Lateral, en el borde anterior del ECM, tercio superior', 'En la región occipital, cerca del cuero cabelludo posterior', 'Únicamente dentro del triángulo cervical posterior'], correct: 1, explanation: 'El quiste branquial se localiza lateralmente, siguiendo el borde anterior del esternocleidomastoideo, en su tercio superior.', dificultad: 'facil' },
  { q: '¿Cuál es el origen embriológico del quiste branquial y cómo se comporta con la deglución/protrusión lingual?', options: ['Del conducto tirogloso; sube al deglutir', 'Es un ganglio reactivo, no malformación', 'Del primer arco; se mueve al masticar', 'Del segundo arco; no se mueve'], correct: 3, explanation: 'A diferencia del quiste tirogloso y de la tiroides, el quiste branquial no tiene relación embriológica con la tráquea ni con la lengua, por lo que permanece fijo con ambas maniobras.', dificultad: 'intermedio' },
  { q: '¿Cómo se realiza correctamente la auscultación carotídea en busca de un soplo?', options: ['Con la campana, respirando profundamente', 'Solo de pie, en apnea espiratoria forzada', 'Con el diafragma, en apnea breve', 'No se ausculta la carótida de rutina'], correct: 2, explanation: 'Contener la respiración elimina los ruidos respiratorios que podrían confundirse con un soplo carotídeo verdadero.', dificultad: 'facil' },
  { q: '¿Por qué debe compararse un soplo carotídeo con la auscultación cardiaca simultánea?', options: ['Por costumbre clínica, sin relevancia', 'Puede ser propio o transmitido', 'Corazón y carótida no comparten sonido', 'Solo así se mide la presión arterial'], correct: 1, explanation: 'Un soplo cardiaco intenso (ej. estenosis aórtica) puede transmitirse por el flujo sanguíneo hacia el cuello, simulando un soplo carotídeo local si no se compara con el precordio.', dificultad: 'intermedio' },
  { q: '¿Por qué la AUSENCIA de un soplo carotídeo no descarta una estenosis carotídea significativa?', options: ['El soplo aparece en cualquier estenosis', 'Los soplos no se relacionan con el grado', 'Si es casi oclusiva, cesa la turbulencia', 'La ausencia de soplo descarta la estenosis'], correct: 2, explanation: 'Al igual que ocurre con Kernig/Brudzinski en meningitis o Homans en TVP, este es otro ejemplo de un signo físico cuya negatividad no permite excluir la enfermedad, especialmente en estenosis muy avanzadas.', dificultad: 'dificil' },
  { q: '¿Qué diferencia clínica distingue el pulso venoso yugular del pulso carotídeo, ambos visibles en el cuello?', options: ['Venoso: ondulado, no palpable, postural', 'Los dos son idénticos a la inspección', 'El carotídeo es el que varía con la posición', 'El venoso resulta de mayor intensidad'], correct: 0, explanation: 'Estas diferencias prácticas (ondulación múltiple, no palpable, colapsable, variable con posición e inspiración) permiten distinguir el pulso venoso del arterial a la cabecera.', dificultad: 'intermedio' },
  { q: 'Si durante la exploración cervical general se detecta una presión venosa yugular elevada, ¿cuál es el paso siguiente recomendado?', options: ['Ignorar el hallazgo si no hay síntomas', 'Solicitar de inmediato punción lumbar', 'Repetir la exploración en decúbito supino', 'Medir el PVY y analizar sus ondas'], correct: 3, explanation: 'Un hallazgo positivo en el examen general de PVY debe seguirse de la técnica detallada (altura, morfología de las ondas) para caracterizar completamente el hallazgo.', dificultad: 'facil' },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente femenina de 32 años con pérdida de peso, taquicardia y temblor fino de 2 meses de evolución. A la inspección, el cuello muestra un aumento de tamaño simétrico visible en posición normal.',
    steps: [
      { q: 'Según la clasificación de la OMS, ¿qué grado de bocio corresponde a este hallazgo (visible con el cuello en posición normal)?', options: ['Bocio grado 0', 'Bocio grado I', 'Bocio grado II', 'Bocio grado III'], correct: 2 },
      { q: 'A la palpación se percibe un frémito continuo sobre la glándula. ¿Qué mecanismo explica este hallazgo?', options: ['Hipervascularización por hiperfunción', 'Fibrosis glandular extensa y progresiva', 'Compresión traqueal por el crecimiento', 'Es un hallazgo normal del bocio simple'], correct: 0 },
      { q: 'Dado el cuadro clínico completo (bocio difuso, frémito, hipertiroidismo clínico), ¿qué diagnóstico es más probable?', options: ['Tiroiditis subaguda de De Quervain', 'Bocio multinodular no tóxico', 'Carcinoma papilar de tiroides', 'Enfermedad de Graves'], correct: 3 }
    ],
    explanation: 'La combinación de bocio difuso (grado II), frémito/soplo tiroideo (por la hipervascularización de la hiperfunción difusa) y manifestaciones clínicas de hipertiroidismo (pérdida de peso, taquicardia, temblor) es característica de la enfermedad de Graves, a diferencia de un bocio nodular no hiperfuncionante, que no genera frémito.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente masculino de 62 años con pérdida de peso no intencionada y saciedad temprana de 3 meses. Al examinar el cuello, se palpa un ganglio duro, fijo, indoloro, en la región supraclavicular izquierda.',
    steps: [
      { q: '¿Cómo se llama este hallazgo ganglionar específico?', options: ['Adenopatía reactiva cervical', 'Ganglio de Virchow', 'El signo de Pemberton', 'Ganglio de Delphian'], correct: 1 },
      { q: '¿Qué vía anatómica explica que una neoplasia abdominal se manifieste en esta localización?', options: ['Diseminación hematógena directa a la piel', 'Invasión directa por simple contigüidad', 'No existe relación anatómica real alguna', 'El conducto torácico drena ahí'], correct: 3 },
      { q: 'Dado el contexto clínico (pérdida de peso, saciedad temprana) y este hallazgo, ¿qué estudio estaría indicado a continuación?', options: ['Nada: es un hallazgo normal del anciano', 'Buscar una neoplasia abdominal oculta', 'Únicamente observación durante 6 meses', 'Radiografía de tórax, sin ver el abdomen'], correct: 1 }
    ],
    explanation: 'Las características del ganglio (duro, fijo, indoloro) en localización supraclavicular izquierda, junto con síntomas digestivos altos (saciedad temprana, pérdida de peso), son muy sugestivas de un ganglio de Virchow por diseminación de una neoplasia gástrica a través del conducto torácico, y ameritan un estudio digestivo dirigido.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Niño de 6 años con una masa cervical de consistencia quística, en la línea media del cuello, a la altura del hueso hioides, presente desde el nacimiento.',
    steps: [
      { q: 'Al pedirle al niño que protruya la lengua, la masa se eleva claramente. ¿Qué sugiere este hallazgo?', options: ['Es un quiste tirogloso', 'Es un quiste branquial', 'Es un ganglio linfático reactivo', 'Es la propia glándula tiroides'], correct: 0 },
      { q: '¿Qué maniobra NO se espera que mueva significativamente esta masa, a diferencia de la glándula tiroides?', options: ['La protrusión de la lengua', 'No hay maniobra que la mueva', 'La deglución', 'La flexión pasiva del cuello'], correct: 2 },
      { q: 'Si la misma masa hubiera estado localizada lateralmente, en el borde anterior del esternocleidomastoideo, y no se moviera ni con la deglución ni con la protrusión lingual, ¿qué diagnóstico sería más probable?', options: ['Un quiste tirogloso', 'Un quiste branquial', 'Un bocio nodular', 'Un ganglio de Virchow'], correct: 1 }
    ],
    explanation: 'La localización en la línea media a nivel del hioides junto con la elevación al protruir la lengua (por su origen embriológico en el conducto tirogloso) es característica del quiste tirogloso, que se distingue de la tiroides (se eleva con la deglución) y del quiste branquial (lateral, sin movimiento con ninguna maniobra).'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente masculino de 70 años, hipertenso y diabético, con antecedente de un episodio transitorio de debilidad en el brazo derecho la semana pasada, ya resuelto. A la auscultación cervical se escucha un soplo en el trayecto de la carótida izquierda.',
    steps: [
      { q: '¿Qué maniobra ayuda a distinguir si este soplo se origina en la carótida o es transmitido desde el corazón?', options: ['Repetir la auscultación en decúbito', 'Medir la presión en los dos brazos', 'Comparar el cuello con el precordio', 'No hay forma clínica de distinguirlo'], correct: 2 },
      { q: 'El soplo es más intenso en el cuello que en el precordio. ¿Qué sugiere esto sobre su origen?', options: ['Origen cardiaco transmitido al cuello', 'No tiene relevancia diagnóstica real', 'Una insuficiencia venosa yugular', 'Origen local: estenosis carotídea'], correct: 3 },
      { q: 'Dado el episodio neurológico transitorio previo (ya resuelto) y este hallazgo, ¿qué estudio sería el más apropiado para evaluar el grado de estenosis?', options: ['Ecografía Doppler carotídea', 'Nada: el soplo ya lo confirma', 'Un electrocardiograma aislado', 'Radiografía de tórax, sin más'], correct: 0 }
    ],
    explanation: 'Un soplo carotídeo focal, más intenso en el cuello que en el precordio, sugiere estenosis local; combinado con un episodio neurológico transitorio reciente (compatible con un ataque isquémico transitorio), amerita evaluación con ecografía Doppler carotídea para cuantificar el grado de estenosis y guiar el manejo.'
  }
];

export const flashcards = [
  { front: 'Istmo tiroideo: ubicación', back: 'Justo debajo del cartílago cricoides.' },
  { front: 'Triángulo cervical anterior', back: 'Línea media + borde inferior de la mandíbula + borde anterior del esternocleidomastoideo.' },
  { front: 'Por qué la tiroides se eleva con la deglución', back: 'Está fijada a la tráquea por la fascia pretraqueal.' },
  { front: 'Técnicas de palpación tiroidea', back: 'Lahey: anterior. Crile: posterior.' },
  { front: 'Soplo/frémito tiroideo', back: 'Hipervascularización por hiperfunción difusa → enfermedad de Graves.' },
  { front: 'Clasificación OMS del bocio', back: '0: no palpable/visible. I: palpable, no visible. II: visible en posición normal.' },
  { front: 'Signo de Pemberton', back: 'Elevar los brazos → congestión facial/distensión yugular → bocio con extensión retroesternal comprimiendo el estrecho torácico superior.' },
  { front: 'Drenaje de la cadena preauricular', back: 'Conjuntiva, párpados, piel temporal.' },
  { front: 'Drenaje de la cadena occipital', back: 'Cuero cabelludo posterior.' },
  { front: 'Adenopatía reactiva/inflamatoria', back: 'Blanda/elástica, móvil, dolorosa, superficie lisa, aislada.' },
  { front: 'Adenopatía neoplásica', back: 'Dura/pétrea o gomosa, fija, indolora, superficie irregular, con frecuencia confluente ("matted").' },
  { front: 'Por qué la adenopatía neoplásica es indolora', back: 'El crecimiento lento no genera la distensión capsular aguda que sí produce el dolor en la inflamación.' },
  { front: 'Ganglio de Virchow', back: 'Supraclavicular izquierdo — conducto torácico drena el abdomen hacia la unión yugulo-subclavia izquierda.' },
  { front: 'Signo de Troisier', back: 'Ganglio de Virchow palpable → buscar neoplasia abdominal oculta, clásicamente gástrica.' },
  { front: 'Supraclavicular izquierda vs. derecha', back: 'Izquierda (Virchow): neoplasia abdominal. Derecha: más frecuente neoplasia torácica o linfoma.' },
  { front: 'Quiste tirogloso: ubicación y maniobra', back: 'Línea media, a nivel del hioides. Se eleva con la PROTRUSIÓN DE LA LENGUA.' },
  { front: 'Quiste branquial: ubicación y maniobra', back: 'Lateral, borde anterior del ECM (tercio superior). NO se mueve con deglución ni protrusión lingual.' },
  { front: 'Auscultación carotídea: técnica', back: 'Diafragma sobre el trayecto carotídeo, paciente en apnea breve (evita ruidos respiratorios).' },
  { front: 'Soplo carotídeo: origen local vs. transmitido', back: 'Comparar con auscultación cardiaca simultánea — más intenso en cuello = local; igual/mayor en precordio = transmitido.' },
  { front: 'Ausencia de soplo carotídeo', back: 'NO descarta estenosis significativa — una estenosis casi oclusiva puede dejar de generar turbulencia audible.' },
  { front: 'Pulso venoso vs. carotídeo (recordatorio)', back: 'Venoso: ondulación múltiple, no palpable, colapsable, varía con posición/inspiración. Carotídeo: onda única, palpable.' },
  { front: 'PVY elevada en el examen cervical general', back: 'Señal para profundizar con la técnica completa de ondas (a, c, x, v, y) — ver Exploración Cardiovascular.' }
];

export default { quiz, flashcards };
