// topics/exploracion-cabeza-cuello/study.js — Autoevaluación de Exploración de Cabeza, Cuello y
// Ganglios. Mismo patrón que historia-clinica/study.js y los demás temas de Semiología: banco
// único, preguntas sueltas + preguntas en cascada sobre una viñeta (retroalimentación consolidada
// al final, sin revelar correcto/incorrecto paso a paso). Redacción de opciones sujeta a
// .claude/skills/reglas-preguntas/SKILL.md (misma categoría lógica, longitud/detalle comparables,
// sin pistas gramaticales/semánticas, posición de `correct` distribuida sin patrón a lo largo de
// todo el array).

export const quiz = [
  { q: '¿Dónde se ubica el istmo tiroideo en relación con los landmarks cervicales?', options: ['Por encima del cartílago tiroides', 'En el triángulo cervical posterior', 'A nivel del hueso hioides', 'Justo debajo del cartílago cricoides'], correct: 3, explanation: 'El istmo tiroideo se localiza inmediatamente debajo del cartílago cricoides, un landmark clave para orientar la palpación tiroidea.', dificultad: 'facil' },
  { q: '¿Cómo se delimita el triángulo cervical anterior?', options: ['Por el trapecio, la clavícula y el esternocleidomastoideo', 'Por la línea media, el borde mandibular y el ECM', 'Solo por el hueso hioides, sin otros límites', 'Por ambas clavículas, de forma completamente simétrica y bilateral'], correct: 1, explanation: 'El triángulo cervical anterior está delimitado por la línea media del cuello, el borde inferior de la mandíbula y el borde anterior del músculo esternocleidomastoideo.', dificultad: 'intermedio' },
  { q: '¿Por qué la glándula tiroides se eleva con la deglución?', options: ['Porque está fijada a la tráquea por la fascia pretraqueal', 'Por contracción de un supuesto músculo tiroideo', 'Por un reflejo nervioso independiente de la anatomía', 'La tiroides en realidad no se eleva con la deglución'], correct: 0, explanation: 'La fijación de la glándula a la tráquea mediante la fascia pretraqueal hace que se desplace hacia arriba junto con la laringe durante la deglución.', dificultad: 'intermedio' },
  { q: 'Una masa cervical que NO se eleva con la deglución sugiere que su origen es:', options: ['Tiroideo, con total certeza diagnóstica', 'Siempre de naturaleza maligna', 'No tiroideo (o no fijado firmemente a la tráquea)', 'Siempre correspondiente a un quiste tirogloso'], correct: 2, explanation: 'La ausencia de movimiento con la deglución orienta a que la masa no depende de la fijación traqueal característica de la tiroides.', dificultad: 'facil' },
  { q: '¿Cuáles son las 2 técnicas clásicas de palpación tiroidea según la posición del examinador?', options: ['Técnica de Homans y de Pratt', 'Técnica de Lahey (anterior) y de Crile (posterior)', 'Técnica de Kernig y de Brudzinski', 'Técnica de Lachman y de McMurray'], correct: 1, explanation: 'La técnica anterior (Lahey) se realiza de frente al paciente; la técnica posterior (Crile), de pie por detrás.', dificultad: 'facil' },
  { q: '¿Qué mecanismo explica un soplo/frémito tiroideo continuo?', options: ['Compresión traqueal por un bocio de gran tamaño', 'Fibrosis extensa y progresiva de la glándula tiroides', 'Un hallazgo completamente normal en cualquier tipo de bocio', 'Hipervascularización glandular por hiperfunción difusa (enfermedad de Graves)'], correct: 3, explanation: 'El aumento marcado del flujo sanguíneo tiroideo en el hipertiroidismo difuso (Graves) genera turbulencia audible/palpable, algo que no se espera en un bocio nodular no hiperfuncionante.', dificultad: 'dificil' },
  { q: 'Según la clasificación de la OMS, un bocio Grado I se define como:', options: ['No palpable ni visible en ningún caso', 'Visible incluso desde cierta distancia', 'Palpable, pero no visible con el cuello en posición normal', 'Visible con el cuello en posición normal'], correct: 2, explanation: 'El Grado I es palpable a la exploración pero no se aprecia visualmente con el cuello en posición neutra.', dificultad: 'facil' },
  { q: '¿Qué mecanismo explica el signo de Pemberton positivo (congestión facial y distensión yugular al elevar los brazos)?', options: ['Un bocio retroesternal cuya compresión aumenta al elevar los brazos, obstruyendo el retorno venoso', 'Aumento transitorio del gasto cardiaco inducido por el ejercicio', 'Deshidratación aguda, de instalación reciente y significativa', 'Hipotensión ortostática, al cambiar bruscamente de posición'], correct: 0, explanation: 'La elevación de los brazos desplaza la clavícula hacia arriba, agravando la compresión del espacio torácico superior ya limitado por el bocio retroesternal, y obstruyendo el retorno venoso yugular.', dificultad: 'dificil' },
  { q: '¿Qué conducta amerita un signo de Pemberton positivo antes de cualquier cirugía tiroidea?', options: ['Ninguna, se puede proceder a operar sin más estudios', 'Indicar únicamente tratamiento con levotiroxina oral', 'Repetir la maniobra varias veces solo para confirmar', 'Evaluar la extensión retroesternal (TC de cuello/tórax) por riesgo de obstrucción'], correct: 3, explanation: 'Conocer la extensión retroesternal antes de la cirugía es clave para anticipar y manejar el riesgo de obstrucción de la vía aérea durante la manipulación quirúrgica.', dificultad: 'intermedio' },
  { q: 'Una adenopatía preauricular sugiere un proceso originado en:', options: ['La conjuntiva, los párpados o la piel temporal', 'El labio inferior', 'La cavidad oral', 'El tórax, mediastino o esófago'], correct: 0, explanation: 'La cadena preauricular drena la conjuntiva, los párpados y la piel de la región temporal.', dificultad: 'facil' },
  { q: 'Una adenopatía occipital sugiere un proceso originado en:', options: ['La faringe', 'La glándula tiroides', 'El cuero cabelludo posterior', 'El abdomen'], correct: 2, explanation: 'La cadena occipital drena el cuero cabelludo posterior.', dificultad: 'facil' },
  { q: '¿Por qué es importante examinar TODAS las cadenas ganglionares y no solo la región sintomática?', options: ['Por protocolo establecido, sin ninguna relevancia clínica real', 'Porque una adenopatía "silente" en una cadena distante puede ser el hallazgo más relevante', 'Porque todas las cadenas siempre resultan afectadas de forma simultánea', 'No es necesario si el paciente se encuentra asintomático'], correct: 1, explanation: 'Un hallazgo asintomático en una cadena alejada del síntoma principal, como la supraclavicular, puede cambiar por completo el enfoque diagnóstico.', dificultad: 'intermedio' },
  { q: '¿Qué características tiene típicamente una adenopatía reactiva/inflamatoria?', options: ['Blanda o elástica, móvil, dolorosa, superficie lisa', 'Dura, fija, indolora', 'Gomosa y confluente', 'Pétrea e irregular'], correct: 0, explanation: 'La hiperplasia folicular benigna en respuesta a un estímulo antigénico local produce un ganglio blando, móvil y doloroso.', dificultad: 'facil' },
  { q: '¿Qué características hacen sospechar que una adenopatía es de origen neoplásico?', options: ['Blanda, móvil y claramente dolorosa a la palpación', 'Únicamente un tamaño mayor a 1 centímetro de diámetro', 'Dura/pétrea o gomosa, fija a planos profundos, indolora, superficie irregular y confluente', 'Aparición reciente tras una infección respiratoria alta'], correct: 2, explanation: 'La consistencia firme, la fijación a planos profundos, la ausencia de dolor y la confluencia ("matted") son las características que más orientan a malignidad.', dificultad: 'intermedio' },
  { q: '¿Por qué una adenopatía neoplásica es típicamente INDOLORA, a diferencia de una reactiva?', options: ['Porque las células tumorales carecen de terminaciones nerviosas propias', 'Porque el crecimiento neoplásico lento no genera la distensión capsular aguda de la inflamación', 'Porque siempre se encuentra necrótica en su interior', 'No hay ninguna diferencia real de dolor entre ambos tipos'], correct: 1, explanation: 'El dolor ganglionar depende de la distensión aguda de la cápsula; el crecimiento neoplásico, al ser progresivo y lento, no suele generar ese estímulo doloroso agudo.', dificultad: 'dificil' },
  { q: '¿Qué significa que varios ganglios estén "confluentes" o "matted"?', options: ['Que están completamente separados y son fácilmente individualizables', 'Que tienen una consistencia particularmente blanda al tacto', 'Que siempre corresponden a una causa infecciosa aguda', 'Que varios ganglios están fusionados entre sí, típico de metástasis o linfoma'], correct: 3, explanation: 'La fusión de varios ganglios adyacentes en una masa única ("matted") es un patrón que orienta hacia metástasis o linfoma.', dificultad: 'intermedio' },
  { q: '¿Dónde se localiza el ganglio de Virchow?', options: ['Submandibular derecho, cerca del ángulo mandibular', 'Occipital, de forma bilateral y simétrica', 'Supraclavicular izquierdo, en el ángulo entre ECM y clavícula', 'Preauricular izquierdo, junto al trago auricular'], correct: 2, explanation: 'El ganglio de Virchow se ubica en la región supraclavicular izquierda, en el ángulo formado por el esternocleidomastoideo y la clavícula.', dificultad: 'facil' },
  { q: '¿Qué mecanismo anatómico explica que una neoplasia gástrica se manifieste como una adenopatía supraclavicular izquierda?', options: ['El conducto torácico, que drena la linfa abdominal, desemboca en la unión yugulo-subclavia izquierda', 'Metástasis hematógena directa hacia la piel del cuello', 'Es pura coincidencia anatómica, sin ningún mecanismo real', 'El estómago posee inervación nerviosa directa hacia el cuello'], correct: 0, explanation: 'El conducto torácico es la vía final común de drenaje linfático de gran parte del abdomen, y su desembocadura en el ángulo yugulo-subclavio izquierdo explica el signo de Troisier.', dificultad: 'dificil' },
  { q: '¿Qué diferencia hay, en términos de origen probable, entre una adenopatía supraclavicular izquierda y una derecha?', options: ['No hay ninguna diferencia real entre ambos lados', 'La adenopatía derecha siempre resulta ser benigna', 'La adenopatía izquierda nunca se asocia con cáncer', 'La izquierda (Virchow) sugiere neoplasia abdominal; la derecha, neoplasia torácica o linfoma'], correct: 3, explanation: 'El drenaje linfático distinto de cada lado (conducto torácico a la izquierda vs. conducto linfático derecho, más corto, a la derecha) explica el origen probable diferente según el lado afectado.', dificultad: 'dificil' },
  { q: '¿Dónde se localiza típicamente un quiste tirogloso?', options: ['Lateral, en el borde anterior del esternocleidomastoideo', 'En la línea media, a la altura del hueso hioides', 'En la región supraclavicular', 'En la región preauricular'], correct: 1, explanation: 'El quiste tirogloso, remanente del conducto tirogloso embrionario, se ubica en la línea media, cerca del hueso hioides.', dificultad: 'facil' },
  { q: '¿Qué maniobra dinámica ayuda a identificar un quiste tirogloso, y por qué?', options: ['La protrusión de la lengua, porque sigue el trayecto embrionario del conducto tirogloso', 'La deglución, porque está fijado a la tráquea igual que la tiroides', 'La flexión pasiva y lateral del cuello del paciente', 'Ninguna maniobra logra distinguirlo de otras masas'], correct: 0, explanation: 'El conducto tirogloso conecta embriológicamente la base de la lengua con la posición final de la tiroides, por lo que el quiste se eleva al protruir la lengua.', dificultad: 'intermedio' },
  { q: '¿Dónde se localiza típicamente un quiste branquial (del segundo arco)?', options: ['En la línea media exacta del cuello del paciente', 'Lateral, en el borde anterior del ECM, tercio superior', 'En la región occipital, cerca del cuero cabelludo posterior', 'Únicamente dentro del triángulo cervical posterior'], correct: 1, explanation: 'El quiste branquial se localiza lateralmente, siguiendo el borde anterior del esternocleidomastoideo, en su tercio superior.', dificultad: 'facil' },
  { q: '¿Cuál es el origen embriológico del quiste branquial y cómo se comporta con la deglución/protrusión lingual?', options: ['Remanente del conducto tirogloso; se eleva con la deglución', 'Es un ganglio linfático reactivo, no una malformación', 'Remanente del primer arco branquial; se mueve al masticar', 'Remanente del segundo arco branquial; no se mueve con ninguna maniobra'], correct: 3, explanation: 'A diferencia del quiste tirogloso y de la tiroides, el quiste branquial no tiene relación embriológica con la tráquea ni con la lengua, por lo que permanece fijo con ambas maniobras.', dificultad: 'intermedio' },
  { q: '¿Cómo se realiza correctamente la auscultación carotídea en busca de un soplo?', options: ['Con la campana, mientras el paciente respira de forma profunda', 'Solo con el paciente de pie, en apnea espiratoria forzada', 'Con el diafragma sobre el trayecto carotídeo, pidiendo contener brevemente la respiración', 'No se ausculta la carótida como parte de la rutina'], correct: 2, explanation: 'Contener la respiración elimina los ruidos respiratorios que podrían confundirse con un soplo carotídeo verdadero.', dificultad: 'facil' },
  { q: '¿Por qué debe compararse un soplo carotídeo con la auscultación cardiaca simultánea?', options: ['Por simple costumbre clínica, sin ninguna relevancia diagnóstica', 'Porque el soplo puede originarse en la carótida o ser transmitido desde un soplo cardiaco', 'Porque el corazón y la carótida nunca comparten el mismo sonido auscultatorio', 'Porque solo de esa forma se puede medir la presión arterial'], correct: 1, explanation: 'Un soplo cardiaco intenso (ej. estenosis aórtica) puede transmitirse por el flujo sanguíneo hacia el cuello, simulando un soplo carotídeo local si no se compara con el precordio.', dificultad: 'intermedio' },
  { q: '¿Por qué la AUSENCIA de un soplo carotídeo no descarta una estenosis carotídea significativa?', options: ['Porque el soplo siempre está presente ante cualquier grado de estenosis', 'Porque los soplos carotídeos no guardan relación con el grado de estenosis', 'Porque una estenosis muy severa, casi oclusiva, reduce tanto el flujo que deja de generar turbulencia', 'La ausencia de soplo siempre descarta la estenosis con seguridad'], correct: 2, explanation: 'Al igual que ocurre con Kernig/Brudzinski en meningitis o Homans en TVP, este es otro ejemplo de un signo físico cuya negatividad no permite excluir la enfermedad, especialmente en estenosis muy avanzadas.', dificultad: 'dificil' },
  { q: '¿Qué diferencia clínica distingue el pulso venoso yugular del pulso carotídeo, ambos visibles en el cuello?', options: ['El venoso tiene ondulación múltiple, no palpable, varía con posición; el carotídeo es de onda única', 'Ambos son completamente idénticos a la simple inspección', 'El pulso carotídeo varía con la posición, y el venoso no', 'El pulso venoso siempre es de mayor intensidad que el carotídeo'], correct: 0, explanation: 'Estas diferencias prácticas (ondulación múltiple, no palpable, colapsable, variable con posición e inspiración) permiten distinguir el pulso venoso del arterial a la cabecera.', dificultad: 'intermedio' },
  { q: 'Si durante la exploración cervical general se detecta una presión venosa yugular elevada, ¿cuál es el paso siguiente recomendado?', options: ['Ignorar por completo el hallazgo si el paciente está asintomático', 'Solicitar de inmediato una punción lumbar diagnóstica', 'Repetir la exploración en decúbito supino, sin elevar el tronco', 'Profundizar con la técnica completa de medición y análisis de ondas del PVY'], correct: 3, explanation: 'Un hallazgo positivo en el examen general de PVY debe seguirse de la técnica detallada (altura, morfología de las ondas) para caracterizar completamente el hallazgo.', dificultad: 'facil' },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente femenina de 32 años con pérdida de peso, taquicardia y temblor fino de 2 meses de evolución. A la inspección, el cuello muestra un aumento de tamaño simétrico visible en posición normal.',
    steps: [
      { q: 'Según la clasificación de la OMS, ¿qué grado de bocio corresponde a este hallazgo (visible con el cuello en posición normal)?', options: ['Grado 0', 'Grado I', 'Grado II', 'No se clasifica así'], correct: 2 },
      { q: 'A la palpación se percibe un frémito continuo sobre la glándula. ¿Qué mecanismo explica este hallazgo?', options: ['Hipervascularización por hiperfunción tiroidea difusa', 'Fibrosis glandular extensa y progresiva', 'Compresión traqueal por el crecimiento glandular', 'Un hallazgo normal en cualquier tipo de bocio'], correct: 0 },
      { q: 'Dado el cuadro clínico completo (bocio difuso, frémito, hipertiroidismo clínico), ¿qué diagnóstico es más probable?', options: ['Tiroiditis subaguda de De Quervain', 'Bocio multinodular no tóxico', 'Carcinoma papilar de tiroides', 'Enfermedad de Graves'], correct: 3 }
    ],
    explanation: 'La combinación de bocio difuso (grado II), frémito/soplo tiroideo (por la hipervascularización de la hiperfunción difusa) y manifestaciones clínicas de hipertiroidismo (pérdida de peso, taquicardia, temblor) es característica de la enfermedad de Graves, a diferencia de un bocio nodular no hiperfuncionante, que no genera frémito.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente masculino de 62 años con pérdida de peso no intencionada y saciedad temprana de 3 meses. Al examinar el cuello, se palpa un ganglio duro, fijo, indoloro, en la región supraclavicular izquierda.',
    steps: [
      { q: '¿Cómo se llama este hallazgo ganglionar específico?', options: ['Adenopatía reactiva cervical', 'Ganglio de Virchow (signo de Troisier)', 'Signo de Pemberton', 'Ganglio de Delphian'], correct: 1 },
      { q: '¿Qué vía anatómica explica que una neoplasia abdominal se manifieste en esta localización?', options: ['Diseminación hematógena directa hacia la piel del cuello', 'Invasión directa por simple contigüidad anatómica local', 'No existe ninguna relación anatómica real entre ambos', 'El conducto torácico drena la linfa abdominal hacia la unión yugulo-subclavia izquierda'], correct: 3 },
      { q: 'Dado el contexto clínico (pérdida de peso, saciedad temprana) y este hallazgo, ¿qué estudio estaría indicado a continuación?', options: ['Ninguno, es un hallazgo normal esperado en el anciano', 'Estudio dirigido a buscar una neoplasia abdominal oculta, clásicamente gástrica', 'Únicamente observación clínica durante 6 meses', 'Radiografía de tórax exclusivamente, sin evaluar el abdomen'], correct: 1 }
    ],
    explanation: 'Las características del ganglio (duro, fijo, indoloro) en localización supraclavicular izquierda, junto con síntomas digestivos altos (saciedad temprana, pérdida de peso), son muy sugestivas de un ganglio de Virchow por diseminación de una neoplasia gástrica a través del conducto torácico, y ameritan un estudio digestivo dirigido.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Niño de 6 años con una masa cervical de consistencia quística, en la línea media del cuello, a la altura del hueso hioides, presente desde el nacimiento.',
    steps: [
      { q: 'Al pedirle al niño que protruya la lengua, la masa se eleva claramente. ¿Qué sugiere este hallazgo?', options: ['Que la masa es un quiste tirogloso, remanente del conducto embrionario', 'Que la masa es en realidad un quiste branquial', 'Que la masa es un ganglio linfático reactivo', 'Que la masa es la propia glándula tiroides'], correct: 0 },
      { q: '¿Qué maniobra NO se espera que mueva significativamente esta masa, a diferencia de la glándula tiroides?', options: ['La protrusión de la lengua', 'Ninguna maniobra logra moverla', 'La deglución', 'La flexión pasiva del cuello'], correct: 2 },
      { q: 'Si la misma masa hubiera estado localizada lateralmente, en el borde anterior del esternocleidomastoideo, y no se moviera ni con la deglución ni con la protrusión lingual, ¿qué diagnóstico sería más probable?', options: ['Quiste tirogloso', 'Quiste branquial (remanente del segundo arco)', 'Bocio nodular', 'Ganglio de Virchow'], correct: 1 }
    ],
    explanation: 'La localización en la línea media a nivel del hioides junto con la elevación al protruir la lengua (por su origen embriológico en el conducto tirogloso) es característica del quiste tirogloso, que se distingue de la tiroides (se eleva con la deglución) y del quiste branquial (lateral, sin movimiento con ninguna maniobra).'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente masculino de 70 años, hipertenso y diabético, con antecedente de un episodio transitorio de debilidad en el brazo derecho la semana pasada, ya resuelto. A la auscultación cervical se escucha un soplo en el trayecto de la carótida izquierda.',
    steps: [
      { q: '¿Qué maniobra ayuda a distinguir si este soplo se origina en la carótida o es transmitido desde el corazón?', options: ['Repetir la auscultación solo en decúbito supino', 'Medir la presión arterial en ambos brazos del paciente', 'Comparar la intensidad del soplo en el cuello con la auscultación cardiaca', 'No existe ninguna forma clínica de distinguirlo'], correct: 2 },
      { q: 'El soplo es más intenso en el cuello que en el precordio. ¿Qué sugiere esto sobre su origen?', options: ['Origen cardiaco transmitido, como una estenosis aórtica', 'No tiene ninguna relevancia diagnóstica real', 'Indica insuficiencia venosa yugular asociada', 'Origen local: estenosis de la arteria carótida'], correct: 3 },
      { q: 'Dado el episodio neurológico transitorio previo (ya resuelto) y este hallazgo, ¿qué estudio sería el más apropiado para evaluar el grado de estenosis?', options: ['Ecografía Doppler carotídea', 'Ninguno, el soplo confirma el diagnóstico por sí solo', 'Electrocardiograma, de manera exclusiva', 'Radiografía de tórax, sin más estudios'], correct: 0 }
    ],
    explanation: 'Un soplo carotídeo focal, más intenso en el cuello que en el precordio, sugiere estenosis local; combinado con un episodio neurológico transitorio reciente (compatible con un ataque isquémico transitorio), amerita evaluación con ecografía Doppler carotídea para cuantificar el grado de estenosis y guiar el manejo.'
  }
];

export const flashcards = [
  { front: 'Istmo tiroideo: ubicación', back: 'Justo debajo del cartílago cricoides.' },
  { front: 'Triángulo cervical anterior', back: 'Línea media + borde inferior de la mandíbula + borde anterior del esternocleidomastoideo.' },
  { front: 'Por qué la tiroides se eleva con la deglución', back: 'Está fijada a la tráquea por la fascia pretraqueal.' },
  { front: 'Técnicas de palpación tiroidea', back: 'Lahey: anterior. Crile: posterior.' },
  { front: 'Soplo/frémito tiroideo', back: 'Hipervascularización por hiperfunción difusa → enfermedad de Graves.' },
  { front: 'Clasificación OMS del bocio', back: '0: no palpable/visible. I: palpable, no visible. II: visible en posición normal.' },
  { front: 'Signo de Pemberton', back: 'Elevar los brazos → congestión facial/distensión yugular → bocio con extensión retroesternal comprimiendo el estrecho torácico superior.' },
  { front: 'Drenaje de la cadena preauricular', back: 'Conjuntiva, párpados, piel temporal.' },
  { front: 'Drenaje de la cadena occipital', back: 'Cuero cabelludo posterior.' },
  { front: 'Adenopatía reactiva/inflamatoria', back: 'Blanda/elástica, móvil, dolorosa, superficie lisa, aislada.' },
  { front: 'Adenopatía neoplásica', back: 'Dura/pétrea o gomosa, fija, indolora, superficie irregular, con frecuencia confluente ("matted").' },
  { front: 'Por qué la adenopatía neoplásica es indolora', back: 'El crecimiento lento no genera la distensión capsular aguda que sí produce el dolor en la inflamación.' },
  { front: 'Ganglio de Virchow', back: 'Supraclavicular izquierdo — conducto torácico drena el abdomen hacia la unión yugulo-subclavia izquierda.' },
  { front: 'Signo de Troisier', back: 'Ganglio de Virchow palpable → buscar neoplasia abdominal oculta, clásicamente gástrica.' },
  { front: 'Supraclavicular izquierda vs. derecha', back: 'Izquierda (Virchow): neoplasia abdominal. Derecha: más frecuente neoplasia torácica o linfoma.' },
  { front: 'Quiste tirogloso: ubicación y maniobra', back: 'Línea media, a nivel del hioides. Se eleva con la PROTRUSIÓN DE LA LENGUA.' },
  { front: 'Quiste branquial: ubicación y maniobra', back: 'Lateral, borde anterior del ECM (tercio superior). NO se mueve con deglución ni protrusión lingual.' },
  { front: 'Auscultación carotídea: técnica', back: 'Diafragma sobre el trayecto carotídeo, paciente en apnea breve (evita ruidos respiratorios).' },
  { front: 'Soplo carotídeo: origen local vs. transmitido', back: 'Comparar con auscultación cardiaca simultánea — más intenso en cuello = local; igual/mayor en precordio = transmitido.' },
  { front: 'Ausencia de soplo carotídeo', back: 'NO descarta estenosis significativa — una estenosis casi oclusiva puede dejar de generar turbulencia audible.' },
  { front: 'Pulso venoso vs. carotídeo (recordatorio)', back: 'Venoso: ondulación múltiple, no palpable, colapsable, varía con posición/inspiración. Carotídeo: onda única, palpable.' },
  { front: 'PVY elevada en el examen cervical general', back: 'Señal para profundizar con la técnica completa de ondas (a, c, x, v, y) — ver Exploración Cardiovascular.' }
];

export default { quiz, flashcards };
