// topics/signos-clasicos/study.js — Autoevaluación de Signos y Maniobras Clásicas. Mismo patrón
// que historia-clinica/study.js y los demás temas de Semiología: banco único, preguntas sueltas +
// preguntas en cascada sobre una viñeta (retroalimentación consolidada al final, sin revelar
// correcto/incorrecto paso a paso). Redacción de opciones sujeta a .claude/skills/reglas-preguntas/
// SKILL.md (misma categoría lógica, longitud/detalle comparables, sin pistas gramaticales/
// semánticas, posición de `correct` distribuida sin patrón a lo largo de todo el array).

export const quiz = [
  { q: '¿En qué consiste el signo de Musset?', options: ['Un soplo femoral doble, sisto-diastólico', 'Pulsación visible en el lecho ungueal', 'Cabeceo rítmico con cada latido', 'Un ruido en pistoletazo sobre la femoral'], correct: 2, explanation: 'El signo de Musset es el cabeceo sincrónico con el pulso, observado sin ningún contacto físico con el paciente.', dificultad: 'facil' },
  { q: '¿Qué mecanismo fisiopatológico único explica la tétrada de Musset, Duroziez, Traube y Quincke?', options: ['Presión de pulso amplia por fuga diastólica, transmitida a la periferia', 'Vasoespasmo coronario recurrente, de origen puramente funcional', 'Hipertensión pulmonar severa, de evolución crónica y progresiva', 'Fibrilación auricular con respuesta ventricular rápida y variable'], correct: 0, explanation: 'Los 4 signos comparten el mismo origen: la regurgitación aórtica severa amplía la presión de pulso (sistólica alta, diastólica muy baja), y esa onda amplia se transmite de forma exagerada hacia la periferia.', dificultad: 'intermedio' },
  { q: '¿Cómo se realiza el signo de Duroziez y qué lo hace positivo?', options: ['Auscultar la femoral sin comprimirla nada', 'Palpar el pulso radial de forma bilateral', 'Medir la presión en decúbito y de pie', 'Comprimir la femoral proximal y distal'], correct: 3, explanation: 'Normalmente solo se ausculta un soplo sistólico al comprimir proximalmente; el hallazgo anormal es que también aparezca un soplo diastólico al comprimir distalmente.', dificultad: 'intermedio' },
  { q: '¿Qué es el signo de Traube ("pistol shot")?', options: ['Un soplo que exige comprimir la femoral', 'Un ruido seco, sin comprimir la femoral', 'Una pulsación visible en el lecho ungueal', 'Un cabeceo rítmico con cada pulso arterial'], correct: 1, explanation: 'A diferencia del signo de Duroziez, el de Traube no requiere compresión: el ruido "en pistoletazo" se ausculta directamente sobre la arteria femoral.', dificultad: 'facil' },
  { q: '¿Dónde se busca el signo de Quincke y qué representa?', options: ['En el lecho ungueal; pulsación capilar con alternancia de palidez y rubor', 'En la arteria femoral; representa un soplo sistodiastólico intenso', 'En el precordio; representa un frémito palpable y localizado', 'En el cuello; representa ingurgitación yugular visible y pulsátil'], correct: 0, explanation: 'El signo de Quincke se observa como una pulsación capilar visible al presionar suavemente la punta de la uña, reflejando la amplia presión de pulso transmitida hasta la microcirculación.', dificultad: 'facil' },
  { q: '¿Por qué la tétrada periférica de la insuficiencia aórtica severa tiene hoy un valor más histórico que de primera línea?', options: ['No fueron signos clínicos verdaderos', 'Solo aparecen en la insuficiencia leve', 'Requieren equipo muy especializado y caro', 'Baja sensibilidad frente al ecocardiograma'], correct: 3, explanation: 'El ecocardiograma ofrece una evaluación mucho más precisa de la severidad de la insuficiencia aórtica que estos signos periféricos, relegándolos a un valor más de reconocimiento clásico.', dificultad: 'intermedio' },
  { q: '¿Qué es el signo de Levine y qué sugiere?', options: ['Señalar el dolor con un dedo; muscular', 'Puño sobre el esternón; isquémico', 'Un soplo carotídeo; una estenosis', 'Cabeceo con el pulso; insuficiencia aórtica'], correct: 1, explanation: 'El gesto del puño cerrado sobre el esternón, al describir espontáneamente el dolor, es un dato semiológico clásico de dolor isquémico miocárdico.', dificultad: 'facil' },
  { q: '¿Por qué el dolor isquémico cardiaco se describe típicamente "en puño" y no señalado con un dedo?', options: ['Por costumbre cultural, sin base real', 'El corazón no tiene inervación sensitiva', 'El dolor visceral converge en T1-T4', 'El dolor isquémico suele ser leve'], correct: 2, explanation: 'La convergencia de la inervación visceral cardiaca sobre un territorio dermatomal amplio explica por qué el paciente no puede señalar un punto preciso, a diferencia del dolor somático de pared torácica.', dificultad: 'dificil' },
  { q: 'Según la "ley de Courvoisier", una vesícula palpable, aumentada de tamaño y NO dolorosa, en un paciente con ictericia, sugiere:', options: ['Colelitiasis con colecistitis aguda asociada', 'Un hallazgo normal, sin significado real', 'Una hepatitis viral aguda reciente', 'Obstrucción biliar neoplásica'], correct: 3, explanation: 'Una vesícula crónicamente inflamada por cálculos suele estar fibrótica y no distensible; una vesícula distendida e indolora sugiere obstrucción extrínseca gradual, más compatible con neoplasia.', dificultad: 'intermedio' },
  { q: '¿Por qué una vesícula litiásica crónicamente inflamada rara vez se palpa distendida, a diferencia de la obstrucción neoplásica?', options: ['Los cálculos disuelven la pared vesicular', 'La fibrosis crónica la hace rígida', 'La litiasis no llega a causar obstrucción', 'No hay diferencia real de distensibilidad'], correct: 1, explanation: 'La fibrosis de la pared vesicular por inflamación crónica limita su capacidad de distenderse, mientras que una vesícula previamente sana sometida a obstrucción extrínseca gradual sí puede distenderse y hacerse palpable.', dificultad: 'dificil' },
  { q: '¿Qué mecanismo explica el signo de Kehr (dolor referido al hombro izquierdo en la ruptura esplénica)?', options: ['Compresión directa y sostenida del plexo braquial homolateral', 'Una fractura costal asociada al mismo traumatismo abdominal', 'Irritación del nervio frénico por sangre en contacto con el diafragma', 'Espasmo agudo y doloroso del músculo trapecio ipsilateral'], correct: 2, explanation: 'El nervio frénico comparte origen cervical con el dermatoma del hombro, por lo que la irritación diafragmática se percibe como dolor referido en esa localización.', dificultad: 'dificil' },
  { q: 'En un paciente con traumatismo abdominal cerrado y dolor referido al hombro izquierdo, ¿qué diagnóstico se debe descartar de inmediato?', options: ['Ruptura esplénica con hemoperitoneo', 'Fractura de clavícula, de origen traumático', 'Neumotórax derecho, a tensión', 'Colecistitis aguda, litiásica'], correct: 0, explanation: 'El signo de Kehr en el contexto de trauma abdominal es un signo de alarma clásico para ruptura esplénica.', dificultad: 'facil' },
  { q: '¿Cómo se explora el signo de Chvostek?', options: ['Inflando un manguito de presión por encima de la sistólica', 'Percutiendo suavemente el nervio facial por delante del trago', 'Flexionando pasivamente el cuello del paciente hacia adelante', 'Comprimiendo firmemente la arteria femoral de forma bilateral'], correct: 1, explanation: 'La percusión del nervio facial en ese punto provoca contracción de los músculos faciales ipsilaterales si hay hiperexcitabilidad neuromuscular por hipocalcemia.', dificultad: 'facil' },
  { q: '¿Por qué la hipocalcemia genera hiperexcitabilidad neuromuscular (base del signo de Chvostek)?', options: ['El calcio no afecta la excitabilidad', 'La hipocalcemia libera más acetilcolina', 'El calcio estabiliza el umbral', 'La hipocalcemia bloquea los canales de sodio'], correct: 2, explanation: 'El calcio extracelular normalmente estabiliza la membrana neuronal; su déficit reduce el umbral necesario para la despolarización, generando hiperexcitabilidad.', dificultad: 'intermedio' },
  { q: '¿Cómo se realiza el signo de Trousseau de la tetania?', options: ['Inflar el manguito sobre la sistólica 3 min', 'Percutir el nervio facial ante el trago', 'Flexionar pasivamente el cuello del paciente', 'Comprimir la femoral de forma bilateral'], correct: 0, explanation: 'La isquemia inducida por el manguito exacerba la hiperexcitabilidad neuromuscular de la hipocalcemia, provocando el característico espasmo en "mano de partero".', dificultad: 'facil' },
  { q: '¿Cuál de los dos signos —Chvostek o Trousseau de la tetania— es más sensible y específico para hipocalcemia?', options: ['El signo de Chvostek', 'Los dos rinden igual', 'Ni uno ni otro sirve', 'El signo de Trousseau'], correct: 3, explanation: 'El signo de Trousseau de la tetania es más sensible y específico que el Chvostek, que puede ser positivo incluso en personas normocalcémicas.', dificultad: 'intermedio' },
  { q: '¿Qué hallazgo caracteriza al signo de Trousseau de tromboflebitis migratoria?', options: ['Espasmo carpal por isquemia del brazo', 'Contracción facial al percutir el nervio', 'Tromboflebitis superficial recurrente', 'Un soplo femoral doble y variable'], correct: 2, explanation: 'A diferencia del Trousseau de la tetania, este signo se refiere a episodios de tromboflebitis superficial migratoria, no a un espasmo muscular.', dificultad: 'facil' },
  { q: '¿A qué neoplasia se asocia clásicamente el signo de Trousseau de tromboflebitis migratoria?', options: ['Adenocarcinoma de páncreas', 'Cáncer de mama, en estadio avanzado', 'Linfoma de Hodgkin, de tipo clásico', 'Cáncer de próstata, metastásico'], correct: 0, explanation: 'La tromboflebitis migratoria paraneoplásica se asoció clásicamente al adenocarcinoma de páncreas, aunque puede verse en otras neoplasias.', dificultad: 'facil' },
  { q: '¿Por qué es clínicamente peligroso confundir el "signo de Trousseau" de la tetania con el de tromboflebitis migratoria?', options: ['No es peligroso: son intercambiables', 'Significan cosas distintas pese al nombre', 'Los dos requieren el mismo tratamiento', 'Los dos son signos benignos, sin más'], correct: 1, explanation: 'Confundir ambos "Trousseau" podría llevar a pasar por alto una neoplasia oculta (si se asume erróneamente que se trata de hipocalcemia) o viceversa — la nomenclatura idéntica es una trampa real de examen y de práctica clínica.', dificultad: 'dificil' },
  { q: '¿Qué dato histórico curioso rodea al signo de Trousseau de tromboflebitis migratoria?', options: ['No llegó a confirmarse en la práctica', 'Fue descrito por error y luego retirado', 'Solo se ha descrito en pacientes mujeres', 'Trousseau lo reconoció en sí mismo'], correct: 3, explanation: 'Este es un dato histórico real y frecuentemente citado: Trousseau describió el signo, y años después, al desarrollar tromboflebitis migratoria por su propio cáncer pancreático, reconoció el signo que él mismo había descrito.', dificultad: 'intermedio' },
  { q: '¿Qué provoca el signo de Lhermitte y qué sensación genera?', options: ['Flexionar el cuello; descarga eléctrica', 'Percutir el tendón rotuliano; dolor local', 'Comprimir la carótida; un mareo súbito', 'Extender la cadera; un dolor lumbar'], correct: 0, explanation: 'La flexión cervical estira mecánicamente los cordones posteriores de la médula, generando la sensación eléctrica característica cuando hay desmielinización.', dificultad: 'facil' },
  { q: '¿Qué mecanismo explica la sensación eléctrica del signo de Lhermitte?', options: ['Compresión de una raíz nerviosa lumbar', 'Espasmo agudo del esternocleidomastoideo', 'Axones desmielinizados, descarga ectópica', 'Isquemia de la arteria vertebral izquierda'], correct: 2, explanation: 'La desmielinización deja los axones más sensibles al estiramiento mecánico, generando descargas ectópicas percibidas como una sensación eléctrica.', dificultad: 'dificil' },
  { q: '¿Dónde aparece la equimosis en el signo de Battle?', options: ['Periorbitaria, de forma bilateral', 'En el cuello, de forma lateral', 'En el tórax anterior, difusa', 'Retroauricular, sobre la mastoides'], correct: 3, explanation: 'El signo de Battle es la equimosis retroauricular, sobre la mastoides, indicativa de fractura de la base del cráneo.', dificultad: 'facil' },
  { q: '¿Por qué el signo de Battle y los ojos de mapache NO son útiles para descartar una fractura de base de cráneo en la evaluación INICIAL de un trauma?', options: ['No llegan a ocurrir en fracturas reales', 'Son signos tardíos, de 1-3 días', 'Requieren tomografía para confirmarse', 'Solo ocurren en pacientes pediátricos'], correct: 1, explanation: 'Al ser hallazgos tardíos, su ausencia en las primeras horas tras el trauma no descarta la fractura — la decisión de estudiar debe basarse en el mecanismo y otros hallazgos, no en la ausencia de estos signos.', dificultad: 'intermedio' },
  { q: '¿Qué se observa en el signo de Hoover, y en qué enfermedad es característico?', options: ['Expansión torácica simétrica y normal', 'Asimetría de la expansión; neumotórax', 'Retracción intercostal; crisis asmática', 'Reborde costal hacia adentro; EPOC'], correct: 3, explanation: 'El diafragma aplanado por la hiperinsuflación crónica, al contraerse, tracciona el reborde costal hacia adentro en vez de expandir el tórax hacia afuera.', dificultad: 'intermedio' },
  { q: '¿Cómo se manifiesta el signo de Gowers y en qué enfermedad es clásico?', options: ['Debilidad distal de manos; túnel carpiano', 'Trepa sobre su cuerpo; Duchenne', 'Temblor de reposo; enfermedad de Parkinson', 'Marcha atáxica amplia; ataxia cerebelosa'], correct: 1, explanation: 'La debilidad severa de la cintura pélvica obliga al paciente a usar sus brazos como apoyo mecánico adicional para incorporarse, un hallazgo clásico de la distrofia muscular de Duchenne.', dificultad: 'facil' },
  { q: '¿Qué patrón de herencia hace que el signo de Gowers se observe típicamente en niños varones?', options: ['Ligada al X (distrofia muscular de Duchenne)', 'Autosómica dominante, de penetrancia variable', 'Autosómica recesiva, con portadores asintomáticos', 'Mitocondrial, de herencia materna'], correct: 0, explanation: 'La distrofia muscular de Duchenne, la causa clásica del signo de Gowers, tiene herencia ligada al cromosoma X, por lo que afecta predominantemente a varones.', dificultad: 'intermedio' },
  { q: '¿Qué es el signo de Auspitz y en qué enfermedad se observa?', options: ['Urticación al friccionar una lesión; mastocitosis', 'Fragilidad epidérmica con la fricción; pénfigo', 'Sangrado puntiforme al desprender una escama; psoriasis', 'Aparición de lesiones en sitios de trauma; liquen plano'], correct: 2, explanation: 'El desprendimiento de la escama psoriásica expone capilares dérmicos superficiales muy cercanos a la superficie, que sangran con facilidad.', dificultad: 'facil' },
  { q: '¿Qué es el signo de Darier y qué lo provoca?', options: ['Sangrado al desprender escama; psoriasis', 'Roncha al friccionar; mastocitosis', 'Contracción facial al percutir; calcio', 'Cabeceo con el pulso; insuficiencia aórtica'], correct: 1, explanation: 'La fricción mecánica degranula los mastocitos acumulados en la lesión, liberando histamina y generando la roncha localizada característica.', dificultad: 'facil' },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente masculino de 45 años con antecedente de fiebre reumática en la infancia, presenta disnea progresiva. A la exploración, se observa un cabeceo rítmico sincrónico con cada latido cardiaco.',
    steps: [
      { q: '¿Cómo se llama este hallazgo y qué sugiere?', options: ['Signo de Kehr; ruptura esplénica', 'Signo de Musset; aórtica severa', 'Signo de Chvostek; hipocalcemia', 'Signo de Gowers; una miopatía'], correct: 1 },
      { q: 'Al comprimir la arteria femoral con el estetoscopio, se ausculta un soplo tanto en la compresión proximal como en la distal. ¿Cómo se llama este hallazgo?', options: ['Signo de Traube', 'Signo de Quincke', 'Signo de Levine', 'Signo de Duroziez'], correct: 3 },
      { q: '¿Qué mecanismo fisiopatológico único explica tanto el cabeceo como el hallazgo femoral?', options: ['Presión de pulso amplia por la fuga', 'Vasoespasmo coronario difuso recurrente', 'Fibrilación auricular de respuesta rápida', 'Hipertensión pulmonar severa y antigua'], correct: 0 }
    ],
    explanation: 'El cabeceo sincrónico (signo de Musset) y el soplo sistodiastólico a la compresión femoral (signo de Duroziez) son 2 de los 4 signos periféricos clásicos de la insuficiencia aórtica severa, y ambos comparten el mismo mecanismo: la presión de pulso muy amplia generada por la fuga diastólica masiva a través de la válvula aórtica insuficiente.'
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Paciente masculino de 68 años con ictericia progresiva indolora y pérdida de peso de 2 meses. A la palpación abdominal se identifica una vesícula biliar aumentada de tamaño, de consistencia lisa, sin dolor a la palpación.',
    steps: [
      { q: '¿Cómo se llama este hallazgo (vesícula palpable, no dolorosa, con ictericia)?', options: ['El signo de Murphy', 'El signo de Kehr', 'Signo de Courvoisier', 'El signo de Chvostek'], correct: 2 },
      { q: 'Según la "ley de Courvoisier", ¿qué causa es MENOS probable en este escenario?', options: ['Colelitiasis con obstrucción biliar', 'Carcinoma de la cabeza del páncreas', 'Colangiocarcinoma distal, de origen biliar', 'Ampuloma, de la papila de Vater'], correct: 0 },
      { q: 'Durante los siguientes meses, el paciente desarrolla episodios recurrentes de tromboflebitis superficial en sitios variables de las piernas. ¿Cómo se llama este segundo hallazgo y qué NO se debe confundir con él?', options: ['Signo de Homans; no el signo de Pratt', 'Trousseau migratorio, no el de tetania', 'Signo de Buerger; no el de Duroziez', 'Signo de Stemmer; no el signo de Kehr'], correct: 1 }
    ],
    explanation: 'La combinación de una vesícula palpable e indolora con ictericia (signo de Courvoisier, que hace poco probable la litiasis y sugiere obstrucción neoplásica extrínseca) junto con tromboflebitis superficial migratoria (signo de Trousseau paraneoplásico) es un cuadro clásicamente integrador de neoplasia pancreática — y una oportunidad perfecta para remarcar que este NO es el mismo "signo de Trousseau" que el de la tetania hipocalcémica.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Paciente femenina de 35 años, 48 horas después de una tiroidectomía total, refiere hormigueo perioral y en los dedos.',
    steps: [
      { q: 'Al percutir suavemente el nervio facial por delante del trago, se observa contracción de los músculos faciales ipsilaterales. ¿Cómo se llama este signo?', options: ['Signo de Trousseau', 'Signo de Lhermitte', 'Signo de Battle', 'Signo de Chvostek'], correct: 3 },
      { q: '¿Qué maniobra, más sensible y específica que la anterior, confirmaría mejor la sospecha diagnóstica?', options: ['Signo de Gowers, en la extremidad inferior', 'Signo de Kehr, en el hombro izquierdo', 'Signo de Trousseau de la tetania', 'Signo de Hoover, en la pared torácica'], correct: 2 },
      { q: '¿Cuál es la causa más probable de este cuadro, dado el antecedente quirúrgico reciente?', options: ['Tromboflebitis migratoria paraneoplásica', 'Insuficiencia aórtica aguda, valvular', 'Fractura de base de cráneo postraumática', 'Hipocalcemia por lesión paratiroidea'], correct: 3 }
    ],
    explanation: 'El hormigueo perioral y en los dedos tras una tiroidectomía, junto con un Chvostek positivo, sugiere hipocalcemia por hipoparatiroidismo posquirúrgico (lesión o remoción inadvertida de las glándulas paratiroides, adyacentes a la tiroides); el signo de Trousseau de la tetania, más sensible y específico, confirmaría mejor la hiperexcitabilidad neuromuscular por hipocalcemia — sin relación alguna con el otro "signo de Trousseau" paraneoplásico.'
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Niño de 4 años, varón, es traído por sus padres porque "se cae mucho" y tiene dificultad para subir escaleras. Al pedirle que se levante del suelo, el niño se apoya primero en sus rodillas y luego sube las manos progresivamente por sus muslos hasta ponerse de pie.',
    steps: [
      { q: '¿Cómo se llama esta maniobra característica?', options: ['Signo de Gowers', 'Signo de Romberg', 'Signo de Babinski', 'Signo de Kernig'], correct: 0 },
      { q: '¿Qué grupo muscular está predominantemente afectado?', options: ['Musculatura distal de ambas manos y dedos', 'Musculatura ocular extrínseca, de ambos ojos', 'Musculatura de la cintura pélvica y los muslos', 'Musculatura facial, de la hemicara afectada'], correct: 2 },
      { q: 'Dado el sexo del paciente y la edad de presentación, ¿qué enfermedad neuromuscular es la causa clásica de este signo?', options: ['Esclerosis lateral amiotrófica', 'Distrofia muscular de Duchenne', 'Miastenia gravis generalizada', 'Síndrome de Guillain-Barré'], correct: 1 }
    ],
    explanation: 'El signo de Gowers, en un niño varón con debilidad progresiva de la cintura pélvica, es altamente sugestivo de distrofia muscular de Duchenne (herencia ligada al X), y amerita evaluación dirigida con creatina cinasa sérica y estudio genético.'
  }
];

export const flashcards = [
  { front: 'Signo de Musset', back: 'Cabeceo sincrónico con el pulso, sin tocar al paciente → insuficiencia aórtica severa.' },
  { front: 'Signo de Duroziez', back: 'Compresión femoral proximal Y distal → soplo sistólico Y diastólico → insuficiencia aórtica severa.' },
  { front: 'Signo de Traube', back: 'Ruido "en pistoletazo" sobre la femoral sin comprimir → insuficiencia aórtica severa.' },
  { front: 'Signo de Quincke', back: 'Pulsación capilar visible en el lecho ungueal → insuficiencia aórtica severa.' },
  { front: 'Mecanismo común de la tétrada de AR', back: 'Presión de pulso amplia por fuga diastólica masiva, transmitida exageradamente a la periferia.' },
  { front: 'Signo de Levine', back: 'Puño cerrado sobre el esternón al describir el dolor → dolor isquémico visceral (convergencia dermatomal T1-T4).' },
  { front: 'Ley de Courvoisier', back: 'Vesícula palpable + indolora + ictericia → obstrucción neoplásica (pancreática), NO litiasis (vesícula litiásica está fibrosada, no distensible).' },
  { front: 'Signo de Kehr', back: 'Dolor referido en hombro izquierdo → irritación diafragmática (nervio frénico C3-C5) → ruptura esplénica.' },
  { front: 'Signo de Chvostek', back: 'Percusión del facial pre-trago → contracción facial → hipocalcemia (poco sensible/específico).' },
  { front: 'Signo de Trousseau (tetania)', back: 'Manguito >sistólica x3 min → espasmo carpal ("mano de partero") → hipocalcemia. Más sensible/específico que Chvostek.' },
  { front: 'Signo de Trousseau (tromboflebitis migratoria)', back: '¡DISTINTO al anterior! Tromboflebitis superficial recurrente y migratoria → neoplasia oculta, clásicamente pancreática.' },
  { front: 'Dato histórico: Trousseau y su propio signo', back: 'Armand Trousseau desarrolló cáncer de páncreas y reconoció en sí mismo el signo de tromboflebitis migratoria que él había descrito.' },
  { front: 'Signo de Lhermitte', back: 'Flexión del cuello → descarga eléctrica que baja por la columna → desmielinización de cordones posteriores cervicales (EM, mielopatía compresiva).' },
  { front: 'Signo de Battle', back: 'Equimosis retroauricular (mastoides) → fractura de base de cráneo. Signo TARDÍO (1-3 días).' },
  { front: 'Ojos de mapache', back: 'Equimosis periorbitaria bilateral → fractura de base de cráneo. Signo TARDÍO (1-3 días).' },
  { front: 'Signo de Hoover', back: 'Reborde costal se mueve hacia ADENTRO en inspiración → diafragma aplanado por hiperinsuflación → EPOC avanzado.' },
  { front: 'Signo de Gowers', back: '"Trepar" sobre el propio cuerpo para levantarse del suelo → debilidad de cintura pélvica → distrofia muscular de Duchenne.' },
  { front: 'Signo de Auspitz', back: 'Sangrado puntiforme al desprender escama → papilas dérmicas elongadas y vascularizadas → psoriasis.' },
  { front: 'Signo de Darier', back: 'Roncha al friccionar la lesión → degranulación mecánica de mastocitos → mastocitosis cutánea.' },
  { front: 'Índice: signos ya construidos en otros temas', back: 'Murphy/McBurney/Rovsing/Blumberg/Cullen/Grey Turner (Abdominal) · Kernig/Brudzinski/Babinski/Romberg/Horner (Neurológica) · Homans/Buerger/Stemmer (Osteoarticular) · Pemberton/Troisier (Cabeza y Cuello) · Nikolsky/Koebner (Piel y Faneras) · Kussmaul/Carvallo (Cardiovascular).' }
];

export default { quiz, flashcards };
