// topics/hiperesplenismo/study.js: Autoevaluación de Hiperesplenismo.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoría lógica y longitud comparable
// entre opciones, distractores plausibles, sin pistas gramaticales/semánticas, posición de
// `correct` distribuida sin patrón (verificar el listado de índices antes de dar el archivo por
// terminado).
//
// Nota de método (ver memoria del proyecto): todas las preguntas se escribieron primero con la
// respuesta correcta en options[0]/correct:0 (trivialmente verificable), y luego se redistribuyó
// la posición de `correct` mecánicamente con un script, sin volver a adivinar cuál texto es el
// correcto.

export const quiz = [
  { q: '¿Cuáles son los 4 elementos de la tétrada clásica de Dameshek que definen el hiperesplenismo?', options: ['Fiebre, adenopatías, hepatomegalia y astenia', 'Hipertensión, taquicardia, edema y disnea', 'Ictericia, coluria, acolia y prurito intenso', 'Esplenomegalia, citopenia, médula normal y corrección'], correct: 3, explanation: 'La tétrada de Dameshek define el hiperesplenismo por esplenomegalia, citopenia periférica de 1 o más líneas, médula ósea normal o hiperplásica compensadora, y corrección de la citopenia tras esplenectomía.', dificultad: 'facil' },
  { q: '¿Por qué se dice que el hiperesplenismo es un síndrome y no una enfermedad en sí mismo?', options: ['Porque no tiene una causa identificable', 'Es vía final común de varias enfermedades', 'Porque solo ocurre en la edad pediátrica', 'Porque se resuelve solo, sin intervención'], correct: 1, explanation: 'El hiperesplenismo es la vía final común de causas muy distintas (hipertensión portal, infiltración neoplásica, infección crónica, enfermedades de depósito) que comparten el mecanismo de secuestro y destrucción esplénica acelerada.', dificultad: 'facil' },
  { q: '¿Cuál es la causa más frecuente de hiperesplenismo en la práctica clínica general?', options: ['Cirrosis con hipertensión portal', 'Malaria crónica en zona endémica', 'Enfermedad de Gaucher tipo 1', 'Síndrome de Felty en artritis'], correct: 0, explanation: 'La hipertensión portal secundaria a cirrosis hepática es la causa más frecuente de hiperesplenismo en la práctica clínica general, dada la alta prevalencia de la enfermedad hepática crónica.', dificultad: 'facil' },
  { q: '¿Qué mecanismo produce la citopenia en el hiperesplenismo por hipertensión portal?', options: ['Infiltración por células neoplásicas clonales', 'Autoanticuerpos contra las células sanguíneas', 'Congestión pasiva que retiene y destruye', 'Deficiencia enzimática hereditaria de base'], correct: 2, explanation: 'La congestión vascular pasiva crónica secundaria a la hipertensión portal produce hiperplasia de la pulpa roja y retención/destrucción acelerada de células sanguíneas normales.', dificultad: 'intermedio' },
  { q: '¿Cuál es la citopenia predominante característica del hiperesplenismo por hipertensión portal?', options: ['Neutropenia aislada', 'Trombocitopenia', 'Eosinofilia', 'Policitemia'], correct: 1, explanation: 'La trombocitopenia predominante, con frecuencia leve-moderada, es la citopenia característica del hiperesplenismo por hipertensión portal, dado el mayor volumen de reserva esplénica normal de plaquetas.', dificultad: 'intermedio' },
  { q: '¿Qué neoplasia mieloproliferativa produce con frecuencia la esplenomegalia más masiva entre las causas de hiperesplenismo?', options: ['Trombocitemia esencial leve', 'Leucemia mieloide aguda', 'Anemia aplásica', 'Mielofibrosis'], correct: 3, explanation: 'La mielofibrosis produce con frecuencia la esplenomegalia más masiva de todas las causas de hiperesplenismo, por hematopoyesis extramedular compensadora que ocurre en el bazo.', dificultad: 'intermedio' },
  { q: '¿Por qué la hematopoyesis extramedular esplénica ocurre en la mielofibrosis?', options: ['La médula fibrótica pierde su función', 'El bazo produce más células que la médula', 'Es un proceso ajeno a la enfermedad medular', 'El bazo carece de capacidad hematopoyética'], correct: 0, explanation: 'En la mielofibrosis, la médula ósea fibrótica pierde su capacidad hematopoyética normal, y el bazo (junto con otros sitios) asume una función hematopoyética compensadora extramedular.', dificultad: 'dificil' },
  { q: '¿Qué causas infecciosas se asocian clásicamente al hiperesplenismo?', options: ['El resfriado común y la faringitis viral', 'La influenza estacional y el rinovirus', 'Malaria, endocarditis y leishmaniasis', 'Solo infecciones urinarias no complicadas'], correct: 2, explanation: 'La malaria crónica, la endocarditis subaguda, la tuberculosis diseminada, y la leishmaniasis visceral (kala-azar) son causas infecciosas clásicamente asociadas al hiperesplenismo.', dificultad: 'facil' },
  { q: '¿Qué enfermedad hereditaria de depósito es la causa más frecuente de hiperesplenismo dentro de ese subgrupo?', options: ['Fenilcetonuria clásica', 'Enfermedad de Wilson', 'Hemocromatosis hereditaria', 'Enfermedad de Gaucher'], correct: 3, explanation: 'La enfermedad de Gaucher, por deficiencia de glucocerebrosidasa y acumulación de glucocerebrósido en macrófagos esplénicos, es la enfermedad de depósito lisosomal más común entre las causas de hiperesplenismo.', dificultad: 'intermedio' },
  { q: '¿Qué combinación clínica define al síndrome de Felty?', options: ['Diabetes, hipertensión arterial y dislipidemia', 'Artritis reumatoide, esplenomegalia, neutropenia', 'Fiebre, exantema y artralgias en un joven', 'Ictericia, ascitis y encefalopatía hepática'], correct: 1, explanation: 'El síndrome de Felty se define por la combinación de artritis reumatoide de larga evolución (con frecuencia seropositiva), esplenomegalia, y neutropenia.', dificultad: 'intermedio' },
  { q: '¿Por qué la médula ósea normal o hiperplásica es un criterio central en la definición de hiperesplenismo?', options: ['La distingue de una falla medular primaria', 'La médula está ausente en el hiperesplenismo', 'Carece de toda relevancia diagnóstica real', 'Solo se evalúa en pacientes pediátricos'], correct: 0, explanation: 'Confirmar que la médula es normal o hiperplásica compensadora (no hipoplásica ni infiltrada) distingue el mecanismo del hiperesplenismo de una citopenia por falla medular primaria, orientando el estudio hacia la causa de la esplenomegalia.', dificultad: 'dificil' },
  { q: '¿Cuál es el estudio de imagen de primera línea para confirmar y cuantificar la esplenomegalia?', options: ['Resonancia magnética de cráneo', 'Radiografía simple de tórax', 'Ecografía abdominal', 'Densitometría ósea corporal'], correct: 2, explanation: 'La ecografía abdominal es el estudio de primera línea para confirmar y cuantificar la esplenomegalia, y evaluar el sistema portoesplénico.', dificultad: 'facil' },
  { q: '¿Cuál es el mecanismo central por el que un bazo aumentado de tamaño se vuelve más vulnerable a la rotura?', options: ['Su irrigación arterial se vuelve terminal', 'El bazo agrandado no tiene mayor riesgo', 'Porque el bazo se calcifica por completo', 'Sale de la caja torácica y adelgaza'], correct: 3, explanation: 'El bazo agrandado se extiende más allá de la protección ósea de la caja torácica inferior izquierda y su cápsula se vuelve más delgada y friable en relación con el grado de agrandamiento.', dificultad: 'intermedio' },
  { q: '¿En qué contexto clínico se describe característicamente la rotura esplénica espontánea (atraumática)?', options: ['Faringitis estreptocócica no complicada', 'Mononucleosis infecciosa aguda', 'Resfriado común sin fiebre asociada', 'Otitis media aguda no complicada'], correct: 1, explanation: 'La rotura esplénica espontánea se describe característicamente en la mononucleosis infecciosa aguda, particularmente en las primeras 2-3 semanas cuando el bazo está más frágil.', dificultad: 'intermedio' },
  { q: '¿Qué signo clínico clásico refleja la irritación diafragmática referida por hemorragia intraabdominal en la rotura esplénica?', options: ['Signo de Kehr', 'Signo de Murphy', 'Signo de McBurney', 'Signo de Rovsing'], correct: 0, explanation: 'El signo de Kehr (dolor irradiado al hombro izquierdo por irritación diafragmática referida) es el signo clásico asociado a hemorragia intraabdominal, incluyendo la rotura esplénica.', dificultad: 'intermedio' },
  { q: '¿Cuál es el estudio de elección para confirmar rotura esplénica en el paciente hemodinámicamente estable?', options: ['Radiografía simple de abdomen', 'Electrocardiograma', 'TC de abdomen con contraste', 'Densitometría ósea'], correct: 2, explanation: 'La TC de abdomen con contraste es el estudio de elección en el paciente hemodinámicamente estable, que además permite graduar la lesión esplénica para orientar el manejo.', dificultad: 'facil' },
  { q: '¿Por qué se prefiere cada vez más el manejo conservador sobre la esplenectomía en la lesión esplénica de bajo grado y paciente estable?', options: ['Porque resulta más rápido que la cirugía', 'Porque la cirugía fracasa en estas lesiones', 'Porque la esplenectomía carece de riesgos', 'Preserva la función y evita la OPSI'], correct: 3, explanation: 'El manejo conservador preserva la función esplénica y evita el riesgo de sepsis post-esplenectomía (OPSI) a largo plazo, por lo que se prefiere cuando es factible.', dificultad: 'intermedio' },
  { q: '¿Cuál es el mecanismo central de la sepsis fulminante post-esplenectomía (OPSI)?', options: ['Se pierde la depuración de encapsulados', 'Aumenta la producción de anticuerpos', 'Disminuye el riesgo de cualquier infección', 'Es un mecanismo enteramente no infeccioso'], correct: 0, explanation: 'La OPSI ocurre porque el bazo cumple una función inmunológica central en la depuración de organismos encapsulados; sin él, estos escapan del control inmunológico y pueden proliferar sin control.', dificultad: 'intermedio' },
  { q: '¿Cuáles son los organismos encapsulados más frecuentemente implicados en la OPSI?', options: ['Escherichia coli y enterobacterias', 'Neumococo, Haemophilus y meningococo', 'Candida albicans y otras levaduras', 'Virus de la hepatitis B y hepatitis C'], correct: 1, explanation: 'Streptococcus pneumoniae es el organismo más frecuentemente implicado en la OPSI, seguido de Haemophilus influenzae tipo b y Neisseria meningitidis, todos organismos encapsulados.', dificultad: 'facil' },
  { q: '¿Cuál es la conducta apropiada ante cualquier sospecha de infección en un paciente esplenectomizado?', options: ['Esperar los hemocultivos antes de tratar', 'Observar hasta que aparezcan signos de choque', 'Antibiótico empírico de inmediato', 'Indicar solo antipiréticos, sin antibiótico'], correct: 2, explanation: 'Dado el riesgo de progresión fulminante en horas, se debe iniciar antibióticos empíricos de amplio espectro de inmediato ante cualquier sospecha de infección en el paciente esplenectomizado.', dificultad: 'intermedio' },
  { q: '¿Cuándo se recomienda administrar la vacunación contra organismos encapsulados en relación con una esplenectomía electiva?', options: ['No hace falta vacunar tras la esplenectomía', 'Solo cuando el paciente lo solicita', 'Diez años después del procedimiento', 'Dos semanas antes del procedimiento'], correct: 3, explanation: 'La vacunación completa contra organismos encapsulados se recomienda idealmente 2 semanas antes de una esplenectomía electiva, para asegurar una respuesta inmunológica adecuada antes de perder la función esplénica.', dificultad: 'facil' },
  { q: '¿Qué fenómeno hematológico posoperatorio favorece la trombosis venosa portal/esplénica tras la esplenectomía?', options: ['Trombocitosis reactiva marcada', 'Trombocitopenia grave persistente', 'Anemia hemolítica aguda grave', 'Neutropenia grave prolongada'], correct: 0, explanation: 'La trombocitosis reactiva marcada que ocurre en las semanas posteriores a la esplenectomía (al perderse el sitio fisiológico de secuestro plaquetario) favorece la formación de trombo en el muñón venoso esplénico.', dificultad: 'intermedio' },
  { q: '¿En qué grupo de pacientes es mayor el riesgo de trombosis venosa portal/esplénica tras esplenectomía?', options: ['Esplenectomía traumática en un joven sano', 'Esplenectomía por causa hematológica', 'Esplenectomía parcial de bajo volumen', 'El riesgo es igual en todos los grupos'], correct: 1, explanation: 'El riesgo es mayor en la esplenectomía por indicación hematológica, particularmente en neoplasias mieloproliferativas, donde el estado protrombótico basal ya está aumentado.', dificultad: 'intermedio' },
  { q: '¿Cuál es el estudio de vigilancia inicial recomendado ante sospecha de trombosis venosa portal/esplénica posoperatoria?', options: ['Radiografía simple de abdomen', 'Electrocardiograma', 'Ecografía Doppler abdominal', 'Espirometría'], correct: 2, explanation: 'La ecografía Doppler abdominal es el estudio de vigilancia inicial recomendado, con TC/RM con contraste para confirmar y caracterizar la extensión si es sugestiva.', dificultad: 'facil' },
  { q: '¿Cuál es el mecanismo típico del infarto esplénico?', options: ['Oclusión de una rama arterial esplénica', 'Rotura completa de la cápsula esplénica', 'Infección bacteriana directa del parénquima', 'Depósito de amiloide en el parénquima'], correct: 0, explanation: 'El infarto esplénico ocurre por oclusión de una rama de la arteria esplénica, con mayor frecuencia por un émbolo (cardioembólico u otro origen) o por trombosis local.', dificultad: 'intermedio' },
  { q: '¿Qué característica del dolor distingue clínicamente al infarto esplénico de la rotura esplénica?', options: ['El infarto esplénico cursa sin dolor', 'La rotura no produce dolor abdominal', 'No hay diferencia clínica entre ambos', 'El infarto no produce choque hipovolémico'], correct: 3, explanation: 'A diferencia de la rotura esplénica, el infarto esplénico no complicado no produce signos de choque hipovolémico progresivo, aunque ambos pueden producir dolor agudo en el hipocondrio izquierdo.', dificultad: 'dificil' },
  { q: '¿Qué hallazgo tomográfico es característico del infarto esplénico?', options: ['Masa hiperdensa que capta contraste', 'Defecto hipodenso en cuña periférica', 'Calcificaciones difusas del parénquima', 'Ausencia del bazo en el estudio'], correct: 1, explanation: 'El infarto esplénico se caracteriza en la TC con contraste por un defecto de perfusión hipodenso en forma de cuña, de base periférica, correspondiente al territorio vascular ocluido.', dificultad: 'intermedio' },
  { q: '¿Qué enfermedad hemoglobinopática produce un "autoinfarto" esplénico progresivo característico?', options: ['Talasemia menor heterocigota', 'Deficiencia de G6PD ligada al X', 'Anemia de células falciformes', 'Esferocitosis hereditaria leve'], correct: 2, explanation: 'La anemia de células falciformes produce un autoinfarto esplénico progresivo característico por oclusión microvascular repetida, que con el tiempo puede llevar a asplenia funcional.', dificultad: 'intermedio' },
  { q: '¿Cuál es el manejo apropiado del infarto esplénico simple no complicado?', options: ['Soporte con analgesia; suele resolverse', 'Esplenectomía urgente en todos los casos', 'Transfusión masiva de hemoderivados', 'Trasplante de médula ósea urgente'], correct: 0, explanation: 'El infarto esplénico simple no complicado se maneja con soporte y analgesia, dado que con frecuencia se resuelve espontáneamente con cicatrización del área afectada.', dificultad: 'intermedio' },
  { q: '¿Qué grado de esplenomegalia se considera "masiva" en la mayoría de los criterios clínicos?', options: ['Mayor de 5-8 cm', 'Mayor de 20-22 cm', 'Mayor de 15-18 cm', 'Menor de 13 cm'], correct: 1, explanation: 'La esplenomegalia masiva se define generalmente como una longitud craneocaudal mayor de 20-22 cm, un grado asociado a mayor riesgo de complicaciones y mayor dificultad técnica quirúrgica.', dificultad: 'intermedio' },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 58 años con cirrosis hepática conocida por hepatitis C acude a control de rutina. La biometría hemática muestra plaquetas de 78,000/µL (previamente normales hace 2 años). No refiere sangrado ni síntomas nuevos.',
    steps: [
      { q: '¿Cuál es la interpretación más probable de este hallazgo?', options: ['Hiperesplenismo por hipertensión portal', 'Púrpura trombocitopénica inmune primaria', 'Anemia aplásica adquirida idiopática', 'Leucemia aguda con infiltración medular'], correct: 0, explanation: 'En un paciente con cirrosis conocida, la trombocitopenia progresiva de nueva aparición es característica del hiperesplenismo por hipertensión portal.' },
      { q: '¿Qué estudio de imagen es apropiado para apoyar esta sospecha?', options: ['Radiografía simple de tórax', 'Densitometría ósea corporal', 'Ecografía abdominal con Doppler', 'Electrocardiograma de reposo'], correct: 2, explanation: 'La ecografía abdominal con Doppler confirma la esplenomegalia y evalúa el sistema portoesplénico, apoyando el diagnóstico de hiperesplenismo por hipertensión portal.' },
      { q: 'La ecografía confirma esplenomegalia leve y signos de hipertensión portal. Las plaquetas permanecen estables sin sangrado. ¿Cuál es el manejo apropiado?', options: ['Esplenectomía inmediata programada', 'Transfusión profiláctica de plaquetas', 'Trasplante de médula ósea urgente', 'Tratar la hepatopatía de base'], correct: 3, explanation: 'La trombocitopenia leve-moderada aislada por hiperesplenismo con frecuencia no requiere tratamiento específico dirigido al bazo; el manejo se centra en la hepatopatía de base.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 34 años presenta dolor agudo en el hipocondrio izquierdo irradiado al hombro izquierdo, 10 días después del inicio de un cuadro compatible con mononucleosis infecciosa. Taquicardia de 118 lpm, presión arterial 92/58 mmHg.',
    steps: [
      { q: '¿Qué complicación se debe sospechar de inmediato?', options: ['Infarto esplénico simple', 'Rotura esplénica espontánea', 'Absceso hepático piógeno', 'Colecistitis aguda litiásica'], correct: 1, explanation: 'El dolor agudo con irradiación al hombro izquierdo (signo de Kehr) junto con taquicardia e hipotensión en el contexto de mononucleosis infecciosa reciente es característico de rotura esplénica espontánea.' },
      { q: 'Dado que la paciente muestra signos de inestabilidad hemodinámica, ¿cuál es el estudio inicial más apropiado?', options: ['Ecografía FAST junto a la cama', 'TC de abdomen con contraste intravenoso', 'Radiografía simple de abdomen de pie', 'Esperar 24 horas antes de reevaluar'], correct: 0, explanation: 'En el paciente hemodinámicamente inestable, la ecografía FAST al lado de la cama es el estudio inicial apropiado, dado que no requiere traslado y es rápida.' },
      { q: 'Se confirma hemoperitoneo significativo y la paciente no responde a la reanimación inicial con líquidos. ¿Cuál es la conducta apropiada?', options: ['Manejo conservador ambulatorio', 'Alta con seguimiento en 1 semana', 'Esplenectomía de urgencia', 'Observación sin intervenir de momento'], correct: 2, explanation: 'En la paciente hemodinámicamente inestable con hemoperitoneo significativo que no responde a la reanimación inicial, la esplenectomía urgente es la conducta apropiada.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 45 años, 3 años después de una esplenectomía por trauma, acude a urgencias con fiebre de 39.2°C y escalofríos de inicio hace 4 horas. Se ve progresivamente más letárgico durante la evaluación.',
    steps: [
      { q: '¿Qué diagnóstico se debe sospechar y tratar como urgencia máxima en este paciente?', options: ['Migraña con aura visual prolongada', 'Gastroenteritis viral leve autolimitada', 'Cefalea tensional episódica frecuente', 'Sepsis fulminante post-esplenectomía'], correct: 3, explanation: 'La fiebre de inicio agudo con deterioro rápido en un paciente esplenectomizado debe hacer sospechar OPSI, una urgencia médica máxima dado su potencial de progresión fulminante.' },
      { q: '¿Cuál es la conducta apropiada respecto al inicio de antibióticos?', options: ['Antibiótico empírico de inmediato', 'Esperar los hemocultivos 24-48 horas', 'Esperar a identificar el organismo', 'Solo antipiréticos, sin antibiótico'], correct: 0, explanation: 'Dado el riesgo de progresión fulminante en horas, los antibióticos empíricos de amplio espectro deben iniciarse de inmediato, sin esperar la confirmación microbiológica.' },
      { q: '¿Qué medida preventiva, si se hubiera aplicado correctamente tras la esplenectomía, habría reducido el riesgo de este cuadro?', options: ['Evitar la actividad física de por vida', 'Vacunación contra encapsulados', 'Suspender la medicación previa del paciente', 'Una segunda esplenectomía preventiva'], correct: 1, explanation: 'La vacunación completa contra Streptococcus pneumoniae, Haemophilus influenzae tipo b, y Neisseria meningitidis tras la esplenectomía es la medida preventiva central para reducir el riesgo de OPSI.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'dificil',
    vignette: 'Mujer de 52 años, 2 semanas después de una esplenectomía por mielofibrosis con bazo masivo, presenta dolor abdominal persistente y distensión progresiva. Biometría hemática muestra plaquetas de 950,000/µL.',
    steps: [
      { q: '¿Qué complicación se debe sospechar dado el contexto posoperatorio y el hallazgo hematológico?', options: ['Rotura esplénica recurrente (imposible, el bazo ya fue extirpado)', 'Anemia ferropénica aguda', 'Trombosis venosa portal/esplénica posesplenectomía', 'Hipotiroidismo posoperatorio'], correct: 2, explanation: 'La trombocitosis reactiva marcada (950,000/µL) junto con dolor abdominal persistente en el posoperatorio de esplenectomía por indicación hematológica de alto riesgo sugiere trombosis venosa portal/esplénica.' },
      { q: '¿Cuál es el estudio de elección para confirmar esta sospecha?', options: ['Electrocardiograma de reposo', 'Ecografía Doppler abdominal', 'Radiografía simple de tórax', 'Espirometría con broncodilatador'], correct: 1, explanation: 'La ecografía Doppler abdominal es el estudio de vigilancia inicial, complementada con TC/RM con contraste para confirmar y caracterizar la extensión del trombo si es sugestiva.' },
      { q: 'Se confirma trombosis extensa del muñón esplénico con extensión a la vena porta. ¿Cuál es el manejo apropiado?', options: ['Observación sin tratamiento activo', 'Repetir el procedimiento quirúrgico', 'Transfundir plaquetas para diluir', 'Anticoagulación terapéutica'], correct: 3, explanation: 'Una vez confirmado el trombo, la anticoagulación terapéutica es el manejo apropiado, con duración determinada según la extensión y los factores de riesgo asociados.' }
    ]
  },
  {
    type: 'cascade', dificultad: 'intermedio',
    vignette: 'Varón de 67 años con fibrilación auricular no anticoagulada presenta dolor pleurítico agudo en el hipocondrio izquierdo que empeora con la inspiración profunda, sin signos de inestabilidad hemodinámica.',
    steps: [
      { q: '¿Qué diagnóstico se debe sospechar dado el contexto y el carácter del dolor?', options: ['Infarto esplénico', 'Rotura esplénica traumática', 'Absceso esplénico', 'Quiste esplénico simple no complicado'], correct: 0, explanation: 'El dolor pleurítico en hipocondrio izquierdo sin inestabilidad hemodinámica en un paciente con fibrilación auricular (fuente embólica) sugiere infarto esplénico por embolia.' },
      { q: '¿Qué hallazgo se espera en la TC de abdomen con contraste si se confirma esta sospecha?', options: ['Una masa homogénea que capta contraste uniformemente en todo el parénquima', 'Ausencia completa del bazo', 'Múltiples quistes de pared fina distribuidos difusamente', 'Un defecto de perfusión hipodenso en forma de cuña, de base periférica'], correct: 3, explanation: 'El infarto esplénico se caracteriza en la TC con contraste por un defecto de perfusión hipodenso en forma de cuña, correspondiente al territorio vascular ocluido por el émbolo.' },
      { q: '¿Cuál es el manejo apropiado una vez confirmado el infarto esplénico no complicado en este paciente?', options: ['Esplenectomía urgente e inmediata', 'Soporte y anticoagular la fibrilación', 'Observación sin anticoagulación alguna', 'Trasplante esplénico de donante'], correct: 1, explanation: 'El infarto esplénico no complicado se maneja con soporte y analgesia; además, se debe anticoagular dirigido a la fibrilación auricular subyacente para prevenir nuevos eventos embólicos.' }
    ]
  }
];

export const flashcards = [
  { front: 'Tétrada de Dameshek (hiperesplenismo)', back: 'Esplenomegalia, citopenia periférica, médula normal/hiperplásica compensadora, corrección tras esplenectomía.' },
  { front: 'Causa más frecuente de hiperesplenismo', back: 'Hipertensión portal secundaria a cirrosis hepática.' },
  { front: 'Citopenia predominante en hiperesplenismo por hipertensión portal', back: 'Trombocitopenia (con frecuencia leve-moderada).' },
  { front: 'Causa de esplenomegalia más masiva entre las causas de hiperesplenismo', back: 'Mielofibrosis, por hematopoyesis extramedular esplénica compensadora.' },
  { front: 'Causas infecciosas clásicas de hiperesplenismo', back: 'Malaria crónica, endocarditis subaguda, tuberculosis diseminada, leishmaniasis visceral (kala-azar).' },
  { front: 'Enfermedad de depósito más frecuente asociada a hiperesplenismo', back: 'Enfermedad de Gaucher (deficiencia de glucocerebrosidasa).' },
  { front: 'Síndrome de Felty', back: 'Artritis reumatoide de larga evolución + esplenomegalia + neutropenia.' },
  { front: 'Por qué la médula compensadora es criterio central de hiperesplenismo', back: 'Distingue de una citopenia por falla medular primaria (hipoplásica/infiltrada).' },
  { front: 'Signo de Kehr', back: 'Dolor irradiado al hombro izquierdo por irritación diafragmática referida; sugiere hemoperitoneo/rotura esplénica.' },
  { front: 'Rotura esplénica espontánea: contexto clásico', back: 'Mononucleosis infecciosa aguda, particularmente primeras 2-3 semanas.' },
  { front: 'Estudio de elección para rotura esplénica en paciente estable', back: 'TC de abdomen con contraste.' },
  { front: 'Por qué se prefiere manejo conservador en lesión esplénica de bajo grado', back: 'Preserva función esplénica y evita riesgo de OPSI a largo plazo.' },
  { front: 'OPSI: mecanismo', back: 'Pérdida de la función inmunológica esplénica de depuración de organismos encapsulados.' },
  { front: 'OPSI: organismos más frecuentes', back: 'Streptococcus pneumoniae principalmente; también Haemophilus influenzae tipo b y Neisseria meningitidis.' },
  { front: 'OPSI: conducta ante fiebre en paciente esplenectomizado', back: 'Antibióticos empíricos de amplio espectro inmediatos, sin esperar cultivos.' },
  { front: 'Vacunación pre-esplenectomía electiva', back: 'Idealmente 2 semanas antes del procedimiento.' },
  { front: 'Trombosis venosa portal/esplénica posesplenectomía: factor favorecedor', back: 'Trombocitosis reactiva marcada posoperatoria.' },
  { front: 'Mayor riesgo de trombosis posesplenectomía', back: 'Esplenectomía por indicación hematológica, particularmente neoplasia mieloproliferativa.' },
  { front: 'Estudio de vigilancia inicial para trombosis posesplenectomía', back: 'Ecografía Doppler abdominal.' },
  { front: 'Mecanismo del infarto esplénico', back: 'Oclusión de una rama de la arteria esplénica, con frecuencia embólica o trombótica local.' },
  { front: 'Infarto esplénico vs. rotura esplénica: diferencia clínica clave', back: 'El infarto no produce signos de choque hipovolémico progresivo, a diferencia de la rotura.' },
  { front: 'Hallazgo tomográfico del infarto esplénico', back: 'Defecto de perfusión hipodenso en forma de cuña, de base periférica.' },
  { front: 'Autoinfarto esplénico progresivo', back: 'Característico de la anemia de células falciformes, por oclusión microvascular repetida.' },
  { front: 'Manejo del infarto esplénico simple no complicado', back: 'Soporte y analgesia; con frecuencia se resuelve espontáneamente.' },
  { front: 'Esplenomegalia "masiva"', back: 'Longitud craneocaudal mayor de 20-22 cm.' },
  { front: 'Estudio de primera línea para confirmar esplenomegalia', back: 'Ecografía abdominal (con Doppler para evaluar el sistema portoesplénico).' },
  { front: 'Por qué el bazo agrandado es más vulnerable a la rotura', back: 'Se extiende más allá de la protección de la caja torácica y su cápsula se vuelve más delgada y friable.' },
  { front: 'Terapia de reemplazo enzimático en enfermedad de Gaucher', back: 'Imiglucerasa u otras; pilar del tratamiento moderno, reduce la necesidad de esplenectomía.' },
  { front: 'Marcador de actividad de enfermedad de Gaucher', back: 'Quitotriosidasa.' },
  { front: 'Manejo del síndrome de Felty', back: 'Tratamiento óptimo de la artritis reumatoide de base, que con frecuencia mejora la neutropenia asociada.' }
];
