// topics/enfermedad-intersticial/study.js: Autoevaluacion de Enfermedad Pulmonar Intersticial.
// Sigue .claude/skills/reglas-preguntas/SKILL.md: misma categoria logica y longitud comparable
// entre las 4 opciones, distractores plausibles, sin pistas gramaticales ni semanticas, y la
// posicion de `correct` distribuida sin patron a lo largo de todo el banco.
//
// 48 subpreguntas (30 sueltas + 6 cascadas de 3 pasos) y 32 tarjetas.
// Sin em dash (ver [[feedback-no-em-dash]]). Texto sin acentos.

export const quiz = [
  { q: 'Que prueba confirma un patron restrictivo?', options: ['La espirometria con FVC baja', 'La capacidad pulmonar total', 'La DLCO corregida por hemoglobina', 'La marcha de 6 minutos con oximetria'], correct: 1, explanation: 'Una FVC baja con cociente FEV1/FVC normal solo SUGIERE restriccion: puede deberse a esfuerzo insuficiente o a atrapamiento aereo. Confirmarla exige medir los volumenes por pletismografia, y ese es uno de los errores mas repetidos del tema.', dificultad: 'facil' },
  { q: 'Que parametro separa la restriccion parenquimatosa de la extrapulmonar?', options: ['El cociente FEV1/FVC posbroncodilatador', 'El volumen residual medido por dilucion', 'La presion inspiratoria maxima', 'La DLCO'], correct: 3, explanation: 'La DLCO esta baja cuando el problema es del parenquima y conservada cuando lo que falla es la bomba o la caja toracica. La KCO afina la separacion: en la restriccion extrapulmonar el pulmon transfiere mas por unidad de volumen porque esta sano pero poco distendido.', dificultad: 'intermedio' },
  { q: 'Que hallazgo funcional es casi caracteristico de la restriccion extrapulmonar?', options: ['Una DLCO por debajo del 40% del predicho', 'Un cociente FEV1/FVC por debajo de 0.70', 'Una KCO normal o alta con volumenes bajos', 'Un volumen residual desproporcionadamente bajo'], correct: 2, explanation: 'El pulmon esta sano pero poco distendido, de modo que transfiere mas monoxido de carbono por cada litro de volumen alveolar. Es lo que ocurre en la obesidad, la cifoescoliosis, la paralisis diafragmatica y la enfermedad neuromuscular.', dificultad: 'dificil' },
  { q: 'Que hay que hacer antes de interpretar una DLCO baja?', options: ['Corregirla por la hemoglobina', 'Repetirla tras un broncodilatador', 'Compararla con el volumen residual', 'Confirmarla con gasometria arterial'], correct: 0, explanation: 'La anemia baja la DLCO sin que exista ninguna enfermedad pulmonar, y no corregirla ha generado muchos estudios innecesarios. Tambien la elevan la poliglobulia y la hemorragia alveolar, y la baja el tabaquismo activo por la carboxihemoglobina.', dificultad: 'intermedio' },
  { q: 'Que indica una caida de la FVC mayor del 20% al pasar de sentado a decubito?', options: ['Una obstruccion de la via aerea superior', 'Una disfuncion diafragmatica significativa', 'Un derrame pleural no detectado', 'Una insuficiencia cardiaca izquierda'], correct: 1, explanation: 'Al tumbarse, el contenido abdominal empuja un diafragma que ya no genera presion suficiente. Es una prueba de cabecera, barata y que casi nadie pide, y anticipa la hipoventilacion nocturna antes de que la gasometria diurna se altere.', dificultad: 'intermedio' },
  { q: 'Que valor tiene oir crepitantes en velcro con una radiografia de torax normal?', options: ['Descarta la enfermedad intersticial', 'Indica insuficiencia cardiaca incipiente', 'Sugiere un artefacto de la auscultacion', 'Obliga a solicitar una tomografia'], correct: 3, explanation: 'Los crepitantes secos teleinspiratorios pueden preceder en a&#241;os a las alteraciones radiologicas, y la radiografia simple es poco sensible para la EPID. Oirlos en un paciente con disnea de esfuerzo es motivo para estudiar, no para tranquilizar.', dificultad: 'facil' },
  { q: 'Cual es el hallazgo mas precoz de la enfermedad intersticial en las pruebas funcionales?', options: ['La desaturacion al esfuerzo', 'La caida de la FVC por debajo del 70%', 'La hipoxemia en reposo', 'La hipercapnia diurna'], correct: 0, explanation: 'La saturacion en reposo puede ser normal con enfermedad ya establecida. Solo se detecta midiendo durante la marcha de 6 minutos, y esa es la razon de pedirla en la valoracion inicial y en el seguimiento.', dificultad: 'intermedio' },
  { q: 'Que consecuencia tiene un patron de neumonia intersticial usual DEFINITIVO en la tomografia?', options: ['Obliga a criobiopsia transbronquial', 'Confirma por si solo el diagnostico etiologico', 'Evita la necesidad de biopsia', 'Excluye la neumonitis por hipersensibilidad'], correct: 2, explanation: 'Con ese patron y un contexto clinico compatible, tras excluir exposiciones, autoinmunidad y farmacos, el diagnostico es fibrosis pulmonar idiopatica sin muestra histologica. Es una de las pocas veces en que una imagen ahorra una cirugia con mortalidad propia.', dificultad: 'intermedio' },
  { q: 'Que hallazgo define el patron de neumonia intersticial usual definitivo?', options: ['Vidrio deslustrado difuso de predominio superior', 'Nodulos centrolobulillares mal definidos', 'Mosaico con atrapamiento aereo en espiracion', 'Panal de abeja subpleural y basal'], correct: 3, explanation: 'Quistes agrupados, de pared gruesa y tama&#241;o similar, dispuestos en varias capas subpleurales y con predominio basal. Los otros tres hallazgos son precisamente los que sacan el caso de este patron y lo llevan a la categoria de diagnostico alternativo.', dificultad: 'intermedio' },
  { q: 'Que sugiere el mosaico con atrapamiento aereo en espiracion en una EPID?', options: ['Fibrosis pulmonar idiopatica avanzada', 'Neumonitis por hipersensibilidad', 'Asbestosis con placas pleurales', 'Neumonia intersticial no especifica'], correct: 1, explanation: 'Traduce la afectacion bronquiolar caracteristica de esta enfermedad, cuyos granulomas son bronquiolocentricos. Por eso la tomografia debe hacerse tambien en ESPIRACION: sin ese corte, el hallazgo se pierde y el caso puede etiquetarse mal de fibrosis idiopatica.', dificultad: 'intermedio' },
  { q: 'Cual es el patron de referencia del diagnostico de las enfermedades intersticiales?', options: ['La biopsia pulmonar quirurgica', 'La tomografia de alta resolucion', 'El comite multidisciplinar', 'El lavado broncoalveolar'], correct: 2, explanation: 'La discusion conjunta entre neumologo, radiologo y patologo con toda la informacion clinica supera a cualquier prueba aislada, incluida la biopsia. Cambia el diagnostico en una proporcion importante de los casos remitidos y mejora la concordancia entre centros.', dificultad: 'intermedio' },
  { q: 'Que significa que la fibrosis pulmonar idiopatica sea un diagnostico de exclusion?', options: ['Que hay que descartar exposiciones, autoinmunidad y farmacos', 'Que solo se acepta con biopsia quirurgica negativa', 'Que exige un lavado broncoalveolar sin linfocitosis', 'Que requiere descartar antes la insuficiencia cardiaca'], correct: 0, explanation: 'Las tres exclusiones tienen tratamiento propio: retirar el antigeno, inmunosuprimir la conectivopatia o suspender el farmaco. Confundir una neumonitis por hipersensibilidad con una fibrosis idiopatica priva al paciente de la unica medida que puede detener su enfermedad.', dificultad: 'facil' },
  { q: 'Que demostro el ensayo que probo prednisona, azatioprina y N-acetilcisteina en la fibrosis idiopatica?', options: ['Una mejoria modesta de la capacidad vital', 'Un aumento de la mortalidad y de los ingresos', 'Un beneficio limitado a los pacientes jovenes', 'Una reduccion de las exacerbaciones agudas'], correct: 1, explanation: 'El ensayo se detuvo antes de tiempo por da&#241;o en el grupo tratado. Es uno de los resultados que mas ha cambiado la practica y explica por que la inmunosupresion esta contraindicada aqui, mientras es el tratamiento de eleccion en la neumonitis por hipersensibilidad y en la EPID autoinmunitaria.', dificultad: 'intermedio' },
  { q: 'Que efecto tienen los antifibroticos en la fibrosis pulmonar idiopatica?', options: ['Revierten la fibrosis ya establecida', 'Normalizan la capacidad de difusion', 'Sustituyen a la indicacion de trasplante', 'Enlentecen la caida de la capacidad vital'], correct: 3, explanation: 'Ni la pirfenidona ni el nintedanib revierten nada: frenan la velocidad de deterioro. Por eso la derivacion a trasplante se hace igualmente, y en el momento del diagnostico, no cuando el paciente ya se ha deteriorado.', dificultad: 'facil' },
  { q: 'A quien se aplican los criterios de fibrosis pulmonar progresiva?', options: ['A las EPID fibrosantes que no son fibrosis idiopatica', 'A cualquier paciente con fibrosis, incluida la idiopatica', 'Solo a la neumonitis por hipersensibilidad fibrotica', 'Solo a la EPID asociada a esclerosis sistemica'], correct: 0, explanation: 'La fibrosis idiopatica se considera progresiva por definicion y lleva antifibrotico desde el diagnostico. El concepto sirve para identificar, entre el resto de EPID fibrosantes, a las que se comportan como ella y por tanto responden al antifibrotico.', dificultad: 'intermedio' },
  { q: 'Cuantos criterios hacen falta para definir una fibrosis pulmonar progresiva?', options: ['Uno cualquiera de los tres', 'Los tres a la vez', 'Dos de los tres', 'Dos, siempre incluyendo el radiologico'], correct: 2, explanation: 'Empeoramiento de los sintomas, progresion fisiologica y progresion radiologica, en el ultimo a&#241;o y sin otra explicacion. Ninguno de los tres es obligatorio: cualquier combinacion de dos cumple la definicion.', dificultad: 'intermedio' },
  { q: 'Que caida de la FVC define la progresion fisiologica en la fibrosis progresiva?', options: ['Una caida relativa del 15%', 'Una caida absoluta del 15% del predicho', 'Una caida relativa del 20%', 'Una caida absoluta del 5% del predicho'], correct: 3, explanation: 'Se mide en puntos ABSOLUTOS del porcentaje del predicho: de un 74% a un 67% son 7 puntos y cumplen el criterio. El umbral equivalente para la DLCO es una caida absoluta del 10% del predicho.', dificultad: 'dificil' },
  { q: 'Que farmaco ha demostrado eficacia en la fibrosis pulmonar progresiva no idiopatica?', options: ['La prednisona a dosis altas', 'El nintedanib', 'La N-acetilcisteina', 'La azatioprina'], correct: 1, explanation: 'Redujo la caida de la FVC en este fenotipo con independencia de la enfermedad de base, y tambien en la EPID de la esclerosis sistemica. A diferencia de la fibrosis idiopatica, aqui el inmunosupresor si tiene papel cuando la enfermedad de base lo justifica.', dificultad: 'intermedio' },
  { q: 'Que componentes integran el indice GAP?', options: ['Sexo, edad, FVC y DLCO', 'Edad, tabaquismo, FVC y marcha', 'Sexo, edad, panal y DLCO', 'Edad, DLCO, hipertension pulmonar y FVC'], correct: 0, explanation: 'Las siglas corresponden a genero, edad y fisiologia, esta ultima medida por la FVC y la DLCO en porcentaje del predicho. La puntuacion va de 0 a 8 y define tres estadios con mortalidad claramente creciente.', dificultad: 'intermedio' },
  { q: 'Cuando debe remitirse a trasplante un paciente con fibrosis pulmonar idiopatica?', options: ['Cuando la FVC baja del 50% del predicho', 'Cuando aparece hipoxemia en reposo', 'En el momento del diagnostico', 'Cuando fracasa el tratamiento antifibrotico'], correct: 2, explanation: 'El curso es impredecible y una exacerbacion aguda puede excluir al paciente en cuestion de dias. La derivacion tardia es una de las causas evitables de que un candidato no llegue nunca a entrar en lista.', dificultad: 'intermedio' },
  { q: 'Cual es la principal causa de muerte en la fibrosis pulmonar idiopatica?', options: ['El cancer de pulmon asociado', 'La exacerbacion aguda', 'La hipertension pulmonar', 'La cardiopatia isquemica'], correct: 1, explanation: 'Deterioro respiratorio en menos de un mes con vidrio deslustrado nuevo sobre la fibrosis previa, sin insuficiencia cardiaca ni sobrecarga que lo expliquen. Su mortalidad hospitalaria se acerca al 50% y la ventilacion invasiva rara vez cambia el desenlace.', dificultad: 'intermedio' },
  { q: 'Como se clasifica hoy la neumonitis por hipersensibilidad?', options: ['En aguda, subaguda y cronica', 'En ocupacional y domestica', 'En granulomatosa y no granulomatosa', 'En fibrotica y no fibrotica'], correct: 3, explanation: 'La division temporal clasica se abandono porque lo que predice el pronostico es la presencia de fibrosis y no el tiempo de evolucion. Un paciente puede tener una forma fibrotica tras pocos meses de exposicion intensa, y una no fibrotica tras a&#241;os.', dificultad: 'intermedio' },
  { q: 'Cual es la unica medida capaz de detener una neumonitis por hipersensibilidad?', options: ['El corticoide sistemico prolongado', 'El nintedanib desde el diagnostico', 'La retirada del antigeno', 'El micofenolato como ahorrador'], correct: 2, explanation: 'El corticoide mejora los sintomas y la inflamacion, y el antifibrotico enlentece la fibrosis, pero solo eliminar la exposicion puede revertir la forma no fibrotica. Cuando el antigeno no se identifica, el pronostico empeora precisamente por eso.', dificultad: 'facil' },
  { q: 'Que significa una precipitina positiva frente a antigenos de aves?', options: ['Que existe exposicion, no necesariamente enfermedad', 'Que confirma la neumonitis por hipersensibilidad', 'Que la enfermedad esta en fase fibrotica', 'Que el corticoide sera especialmente eficaz'], correct: 0, explanation: 'Muchos expuestos tienen precipitinas sin desarrollar nunca la enfermedad, y un resultado negativo no la descarta si el antigeno responsable no esta en el panel. Es un apoyo dentro de la valoracion global, nunca un criterio aislado.', dificultad: 'intermedio' },
  { q: 'Que hallazgo del lavado broncoalveolar apoya la neumonitis por hipersensibilidad?', options: ['Una neutrofilia superior al 50%', 'Un predominio de eosinofilos', 'La presencia de hemosiderofagos', 'Una linfocitosis marcada'], correct: 3, explanation: 'Con frecuencia supera el 30% de linfocitos, muy por encima de lo habitual en la fibrosis idiopatica. Es una de las pocas indicaciones claras del lavado en el estudio de una EPID, junto con la sospecha de infeccion, hemorragia alveolar o neoplasia.', dificultad: 'intermedio' },
  { q: 'Que complicacion hay que cribar de forma repetida en la silicosis?', options: ['La hipertension pulmonar', 'La tuberculosis', 'La insuficiencia cardiaca derecha', 'El neumotorax espontaneo'], correct: 1, explanation: 'La silice altera la funcion del macrofago alveolar y multiplica el riesgo de enfermedad tuberculosa, activa y latente. El cribado se repite en el seguimiento y no se limita al momento del diagnostico.', dificultad: 'intermedio' },
  { q: 'Que hallazgo radiologico es el marcador de exposicion al asbesto?', options: ['Las placas pleurales', 'Las adenopatias en cascara de huevo', 'Los nodulos centrolobulillares', 'La fibrosis masiva progresiva'], correct: 0, explanation: 'Indican exposicion, no enfermedad parenquimatosa: pueden aparecer sin asbestosis y con funcion pulmonar normal. La calcificacion en cascara de huevo y la fibrosis masiva progresiva corresponden a la silicosis.', dificultad: 'intermedio' },
  { q: 'Que prueba separa la beriliosis de la sarcoidosis?', options: ['La biopsia transbronquial con granulomas', 'La enzima convertidora de angiotensina', 'La prueba de proliferacion linfocitaria al berilio', 'El patron de las adenopatias en la tomografia'], correct: 2, explanation: 'Las dos enfermedades son practicamente indistinguibles en clinica, imagen e histologia, porque el berilio actua como antigeno y produce granulomas identicos. Sin preguntar por la exposicion y sin esta prueba, la beriliosis se diagnostica como sarcoidosis.', dificultad: 'dificil' },
  { q: 'Que relacion puede tener la EPID con una enfermedad autoinmunitaria sistemica?', options: ['Aparece siempre despues del diagnostico reumatologico', 'Puede ser su primera manifestacion', 'Solo aparece en la esclerosis sistemica', 'Excluye el diagnostico si la serologia es negativa'], correct: 1, explanation: 'A veces precede en a&#241;os a la afectacion articular o cutanea, y por eso el panel de autoinmunidad, incluido el de miositis, se pide en toda EPID aunque no haya sintomas reumatologicos. La capilaroscopia y la exploracion de las manos son igual de rentables.', dificultad: 'intermedio' },
  { q: 'Que conducta corresponde ante un deterioro respiratorio en un paciente con EPID inmunosuprimido?', options: ['Aumentar la dosis de inmunosupresor', 'A&#241;adir nintedanib de forma urgente', 'Iniciar corticoide a dosis altas sin mas', 'Descartar infeccion antes de escalar'], correct: 3, explanation: 'La infeccion oportunista es el diferencial mas urgente y el mas peligroso de confundir con una progresion de la EPID. Subir la inmunosupresion sobre una infeccion no reconocida es el error con peores consecuencias de esta ficha.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Varon de 71 a&#241;os, exfumador, con disnea de esfuerzo de 2 a&#241;os y tos seca. Crepitantes secos en velcro en ambas bases y acropaquias. Saturacion del 96% en reposo. Espirometria: FVC del 66% del predicho con cociente FEV1/FVC de 0.84. Capacidad pulmonar total del 64% y DLCO corregida del 42%. La tomografia muestra reticulacion subpleural y basal con panal de abeja.', steps: [
    { q: 'Como se clasifica el patron funcional?', options: ['Obstructivo con atrapamiento aereo', 'Mixto con predominio obstructivo', 'Restrictivo de origen parenquimatoso', 'Restrictivo de origen extrapulmonar'], correct: 2 },
    { q: 'Que corresponde hacer con la tomografia descrita?', options: ['Solicitar biopsia pulmonar quirurgica reglada', 'Clasificarla como patron de NIU definitivo', 'Repetirla en espiracion y prono antes de decidir', 'Considerarla indeterminada y biopsiar despues'], correct: 1 },
    { q: 'Que hay que completar antes de etiquetarlo de fibrosis idiopatica?', options: ['Un lavado broncoalveolar con recuento celular', 'Una gammagrafia de ventilacion y perfusion', 'Una prueba de provocacion bronquial', 'Exposiciones, autoinmunidad y farmacos'], correct: 3 }
  ], explanation: 'Capacidad pulmonar total del 64% confirma la restriccion, y la DLCO del 42% indica que el problema es del parenquima. La reticulacion subpleural y basal con panal define el patron de neumonia intersticial usual definitivo, con el que no hace falta biopsia. Pero idiopatica significa que se ha buscado y no se ha encontrado: hay que interrogar por aves, humedades y toda la historia laboral, pedir panel de autoinmunidad y revisar todos los farmacos antes de poner esa etiqueta.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Mujer de 54 a&#241;os no fumadora, con disnea y tos de 8 meses. Tiene dos periquitos desde hace 5 a&#241;os. Refiere que en las tres semanas que paso en casa de su hija se encontro claramente mejor. La tomografia muestra vidrio deslustrado, nodulos centrolobulillares mal definidos y, en los cortes espiratorios, mosaico con atrapamiento aereo en varios lobulos, sin panal.', steps: [
    { q: 'Cual es el diagnostico mas probable?', options: ['Neumonitis por hipersensibilidad', 'Fibrosis pulmonar idiopatica', 'Sarcoidosis pulmonar en estadio II', 'Neumonia intersticial no especifica'], correct: 0 },
    { q: 'Que prueba complementaria apoya mejor ese diagnostico?', options: ['La enzima convertidora de angiotensina', 'La DLCO corregida por hemoglobina', 'El lavado broncoalveolar con linfocitosis', 'La biopsia pulmonar quirurgica'], correct: 2 },
    { q: 'Cual es la medida terapeutica decisiva?', options: ['Iniciar nintedanib desde el diagnostico', 'Retirar las aves del domicilio', 'Pautar micofenolato de mantenimiento', 'Corticoide inhalado a dosis altas'], correct: 1 }
  ], explanation: 'La mejoria al alejarse del domicilio, el antecedente de aves y el mosaico con atrapamiento aereo en espiracion componen el cuadro. Sin los cortes espiratorios ese hallazgo se pierde y el caso puede etiquetarse mal. El lavado con linfocitosis marcada apoya el diagnostico, pero lo que puede detener y hasta revertir la enfermedad en su forma no fibrotica es eliminar el antigeno; el corticoide alivia mientras tanto.', dificultad: 'facil' },

  { type: 'cascade', vignette: 'Varon de 63 a&#241;os con artritis reumatoide seropositiva y EPID fibrosante conocida desde hace 3 a&#241;os, en tratamiento con metotrexato. Hace un a&#241;o la FVC era del 72% y la DLCO del 55%. Hoy la FVC es del 64% y la DLCO del 43%, refiere mas disnea y la tomografia muestra mas reticulacion y bronquiectasias de traccion. Esta afebril, sin expectoracion y el peptido natriuretico es normal.', steps: [
    { q: 'Que hay que descartar antes de aceptar la progresion?', options: ['Una hipertension pulmonar asociada a la fibrosis', 'Una miopatia esteroidea concomitante', 'Un deficit de alfa-1-antitripsina', 'Infeccion, insuficiencia cardiaca y toxicidad'], correct: 3 },
    { q: 'Cuantos criterios de fibrosis pulmonar progresiva cumple?', options: ['Ninguno de los tres', 'Un criterio', 'Dos criterios', 'Los tres criterios'], correct: 3 },
    { q: 'Que tratamiento corresponde a&#241;adir?', options: ['Nintedanib', 'Prednisona a dosis altas', 'N-acetilcisteina oral', 'Azatioprina'], correct: 0 }
  ], explanation: 'Antes de aceptar la progresion hay que excluir lo que la imita, y aqui la toxicidad por metotrexato es especialmente relevante. Cumple los tres criterios: sintomas peores, progresion fisiologica (la FVC cae 8 puntos absolutos, por encima del umbral de 5, y la DLCO 12, por encima de 10) y progresion radiologica. El nintedanib redujo la caida de la FVC en este fenotipo con independencia de la enfermedad de base, y aqui se combina con el tratamiento inmunosupresor que la artritis reumatoide justifica.', dificultad: 'dificil' },

  { type: 'cascade', vignette: 'Varon de 34 a&#241;os que trabaja desde hace 6 a&#241;os cortando y puliendo encimeras de aglomerado de cuarzo, en seco y sin proteccion respiratoria. Consulta por disnea de esfuerzo de un a&#241;o. La tomografia muestra nodulos de predominio en lobulos superiores, adenopatias hiliares con calcificacion periferica y dos masas conglomeradas en los vertices.', steps: [
    { q: 'Cual es el diagnostico mas probable?', options: ['Sarcoidosis pulmonar avanzada', 'Silicosis con fibrosis masiva progresiva', 'Tuberculosis pulmonar cavitada', 'Histiocitosis de celulas de Langerhans'], correct: 1 },
    { q: 'Que complicacion hay que descartar de forma sistematica?', options: ['La tuberculosis', 'El mesotelioma pleural', 'La aspergilosis broncopulmonar alergica', 'La proteinosis alveolar autoinmunitaria'], correct: 0 },
    { q: 'Que actuacion corresponde ademas del tratamiento del paciente?', options: ['Iniciar corticoide sistemico prolongado', 'Solicitar prueba de proliferacion al berilio', 'Programar lavado pulmonar total', 'Notificarlo y estudiar a los companeros'], correct: 3 }
  ], explanation: 'La exposicion a silice cristalina en el corte en seco de aglomerados de cuarzo produce formas aceleradas en trabajadores jovenes, con nodulos de predominio superior, adenopatias en cascara de huevo y masas de fibrosis masiva progresiva. La silice altera la funcion del macrofago y multiplica el riesgo de tuberculosis, que hay que cribar de forma repetida. Y un caso indice obliga a notificar la enfermedad profesional y a estudiar a los companeros expuestos al mismo foco.', dificultad: 'intermedio' },

  { type: 'cascade', vignette: 'Mujer de 47 a&#241;os con disnea de 4 meses. En la exploracion tiene fenomeno de Raynaud, engrosamiento cutaneo de los dedos y fisuras hiperqueratosicas en los bordes radiales de las manos. La tomografia muestra vidrio deslustrado con reticulacion fina de predominio basal y preservacion subpleural, sin panal. La capilaroscopia es patologica.', steps: [
    { q: 'Que orientacion diagnostica dan los hallazgos cutaneos?', options: ['Una neumonitis por hipersensibilidad domestica', 'Una sarcoidosis con eritema nodoso', 'Una EPID asociada a enfermedad autoinmunitaria', 'Una toxicidad pulmonar por farmacos'], correct: 2 },
    { q: 'Que estudio serologico no puede faltar?', options: ['El panel de miositis con antisintetasas', 'Las precipitinas frente a antigenos aviarios', 'La enzima convertidora de angiotensina', 'La determinacion de alfa-1-antitripsina'], correct: 0 },
    { q: 'Que patron tomografico describe el caso?', options: ['Neumonia intersticial usual definitiva', 'Neumonia organizada criptogenetica', 'Neumonia intersticial usual probable', 'Neumonia intersticial no especifica'], correct: 3 }
  ], explanation: 'Las manos de mecanico junto al Raynaud, la esclerodactilia y la capilaroscopia patologica apuntan a un sindrome antisintetasa o a una esclerosis sistemica, en las que la EPID puede ser la primera manifestacion. El panel de miositis debe pedirse en toda EPID aunque no haya debilidad muscular. El vidrio deslustrado con reticulacion fina, predominio basal y preservacion subpleural es el patron tipico de la neumonia intersticial no especifica, el mas frecuente en estas enfermedades.', dificultad: 'dificil' },

  { type: 'cascade', vignette: 'Varon de 58 a&#241;os con esclerosis lateral amiotrofica de 2 a&#241;os de evolucion. Refiere cefalea al despertar, somnolencia diurna y sue&#241;o poco reparador. FVC sentado del 58% del predicho y en decubito del 41%. DLCO del 88% con KCO del 112%. Gasometria diurna: pH de 7.40, PaCO2 de 44 mmHg y bicarbonato de 29 mmol/L.', steps: [
    { q: 'Como se interpretan la DLCO y la KCO?', options: ['Confirman restriccion extrapulmonar', 'Indican enfermedad intersticial precoz', 'Sugieren enfisema asociado al tabaco', 'Son incompatibles con la restriccion'], correct: 0 },
    { q: 'Que dato de la gasometria diurna es relevante pese a la PaCO2 normal?', options: ['El pH en el limite alto de la normalidad', 'El bicarbonato elevado', 'La ausencia de hipoxemia', 'El exceso de bases negativo'], correct: 1 },
    { q: 'Cual es la intervencion que mas cambia su pronostico?', options: ['La oxigenoterapia domiciliaria continua', 'La rehabilitacion respiratoria intensiva', 'El corticoide sistemico a dosis bajas', 'La ventilacion no invasiva domiciliaria'], correct: 3 }
  ], explanation: 'Volumenes bajos con DLCO normal y KCO alta definen la restriccion extrapulmonar: el pulmon esta sano pero poco distendido. La caida de la FVC del 58% al 41% en decubito, muy por encima del 20%, confirma la debilidad diafragmatica. El bicarbonato de 29 con PaCO2 diurna normal delata la hipoventilacion nocturna ya establecida, porque el ri&#241;on lleva tiempo compensando. La ventilacion no invasiva domiciliaria prolonga la supervivencia y mejora la calidad de vida en esta enfermedad; el oxigeno solo, sin soporte ventilatorio, puede empeorar la hipercapnia.', dificultad: 'dificil' }
];

export const flashcards = [
  { front: 'Que confirma un patron restrictivo', back: 'La capacidad pulmonar total, no la espirometria: una FVC baja solo lo sugiere.' },
  { front: 'Que separa la restriccion intrinseca de la extrinseca', back: 'La DLCO: baja en la parenquimatosa, normal en la de la bomba.' },
  { front: 'KCO normal o alta con volumenes bajos', back: 'Restriccion EXTRAPULMONAR: pulmon sano pero poco distendido.' },
  { front: 'Antes de interpretar una DLCO baja', back: 'Corregirla por la hemoglobina: la anemia la baja sin enfermedad pulmonar.' },
  { front: 'Caida de la FVC mayor del 20% en decubito', back: 'Disfuncion diafragmatica significativa; anticipa la hipoventilacion nocturna.' },
  { front: 'Crepitantes en velcro con radiografia normal', back: 'Pueden preceder a&#241;os a la imagen: pedir tomografia, no tranquilizar.' },
  { front: 'Hallazgo funcional mas precoz de la EPID', back: 'La desaturacion al esfuerzo, con saturacion normal en reposo.' },
  { front: 'Patron de NIU definitivo en la tomografia', back: 'Evita la biopsia si el contexto encaja y las exclusiones estan hechas.' },
  { front: 'Que define la NIU definitiva', back: 'Predominio subpleural y basal, heterogenea, con PANAL DE ABEJA.' },
  { front: 'Mosaico con atrapamiento aereo en espiracion', back: 'Muy sugestivo de neumonitis por hipersensibilidad. Exige cortes en espiracion.' },
  { front: 'Patron de referencia del diagnostico de EPID', back: 'El COMITE MULTIDISCIPLINAR, por encima de cualquier prueba aislada.' },
  { front: 'Las tres exclusiones antes de decir idiopatica', back: 'Exposiciones, enfermedad autoinmunitaria y farmacos. Las tres tienen tratamiento.' },
  { front: 'Que demostro el ensayo PANTHER-IPF', back: 'Que prednisona con azatioprina y N-acetilcisteina AUMENTA la mortalidad en la FPI.' },
  { front: 'Que hacen los antifibroticos', back: 'Enlentecen la caida de la FVC. No revierten la fibrosis ni sustituyen al trasplante.' },
  { front: 'A quien se aplican los criterios de fibrosis progresiva', back: 'A EPID fibrosantes que NO son fibrosis idiopatica, que ya es progresiva por definicion.' },
  { front: 'Criterios de fibrosis pulmonar progresiva', back: '2 de 3 en un a&#241;o: sintomas, progresion fisiologica y progresion radiologica.' },
  { front: 'Umbrales de progresion fisiologica', back: 'Caida ABSOLUTA de la FVC del 5% o mas, o de la DLCO del 10% o mas, del predicho.' },
  { front: 'Farmaco de la fibrosis pulmonar progresiva', back: 'Nintedanib, con independencia de la enfermedad de base.' },
  { front: 'Componentes del indice GAP', back: 'Genero, edad y fisiologia (FVC y DLCO). De 0 a 8 puntos, tres estadios.' },
  { front: 'Cuando remitir a trasplante en la FPI', back: 'EN EL MOMENTO DEL DIAGNOSTICO, no cuando el paciente ya se ha deteriorado.' },
  { front: 'Principal causa de muerte en la FPI', back: 'La exacerbacion aguda, con mortalidad hospitalaria cercana al 50%.' },
  { front: 'Clasificacion actual de la neumonitis por hipersensibilidad', back: 'Fibrotica y NO fibrotica; se abandono la de aguda, subaguda y cronica.' },
  { front: 'Unica medida que detiene la neumonitis por hipersensibilidad', back: 'Retirar el antigeno. Si no se identifica, el pronostico empeora.' },
  { front: 'Que significa una precipitina positiva', back: 'Exposicion, NO enfermedad. Y una negativa no descarta si falta el antigeno en el panel.' },
  { front: 'Lavado broncoalveolar en la neumonitis por hipersensibilidad', back: 'Linfocitosis marcada, con frecuencia por encima del 30%.' },
  { front: 'Complicacion a cribar de forma repetida en la silicosis', back: 'La TUBERCULOSIS: la silice altera la funcion del macrofago alveolar.' },
  { front: 'Marcador radiologico de exposicion al asbesto', back: 'Las placas pleurales, que indican exposicion y no enfermedad parenquimatosa.' },
  { front: 'Como se separa la beriliosis de la sarcoidosis', back: 'Con la prueba de proliferacion linfocitaria al berilio, y preguntando por la exposicion.' },
  { front: 'La EPID y las conectivopatias', back: 'Puede ser la PRIMERA manifestacion, a&#241;os antes que la piel o las articulaciones.' },
  { front: 'Deterioro en un paciente con EPID inmunosuprimido', back: 'Descartar INFECCION oportunista antes de subir la inmunosupresion.' },
  { front: 'Farmacos que producen EPID', back: 'Amiodarona, metotrexato, nitrofurantoina, bleomicina e inhibidores del punto de control.' },
  { front: 'Ventilacion no invasiva domiciliaria en la ELA', back: 'Prolonga la supervivencia y mejora la calidad de vida; el oxigeno solo empeora la hipercapnia.' }
];

export default { quiz, flashcards };
